apache/pulsar

- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/batching/AbstractBatchedMetadataStore.java
Avoid raw use of parameterized class 'MessagePassingQueue'
Add MetadataOp as parameterized class.
> [metadata] Avoid raw use of parameterized class 'MessagePassingQueue'

- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/LongHierarchicalLedgerRangeIterator.java
- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerIdGenerator.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/compaction/TestCompaction.java
Fix log numbber incorrect on pulsar metadata
Simple changes, no need doc
> Fix log numbber incorrect on pulsar metadata

- site2/website/static/swagger/2.9.0/swagger.json
- site2/website/static/swagger/2.9.0/swaggerfunctions.json
- site2/website/static/swagger/2.9.0/swaggerpackages.json
- site2/website/static/swagger/2.9.0/swaggersink.json
- site2/website/static/swagger/2.9.0/swaggersource.json
Update Swagger files for 2.9.0 according to the [Release process](https://github.com/apache/pulsar/wiki/Release-process)
> Swagger files for Pulsar 2.9.0

- site2/website/static/swagger/2.9.1/swagger.json
- site2/website/static/swagger/2.9.1/swaggerfunctions.json
- site2/website/static/swagger/2.9.1/swaggerpackages.json
- site2/website/static/swagger/2.9.1/swaggersink.json
- site2/website/static/swagger/2.9.1/swaggersource.json
Update Swagger files for 2.9.1 according to the [Release process](https://github.com/apache/pulsar/wiki/Release-process)
> Swagger files for Pulsar 2.9.1

- site2/docs/tiered-storage-filesystem.md
- site2/website-next/docs/tiered-storage-filesystem.md
- site2/website-next/versioned_docs/version-2.7.1/tiered-storage-filesystem.md
- site2/website-next/versioned_docs/version-2.7.2/tiered-storage-filesystem.md
- site2/website-next/versioned_docs/version-2.7.3/tiered-storage-filesystem.md
- site2/website-next/versioned_docs/version-2.8.0/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.0/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.1/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.2/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.3/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.0/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.1/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.2/tiered-storage-filesystem.md
The [required configurations in filesystem offloader driver](https://pulsar.apache.org/docs/en/tiered-storage-filesystem/#configure-filesystem-offloader-driver) has mistake on `offloadersDirectory`, it should be `fileSystemProfilePath`.
Fix docs mistake.
*(or)*
*(or)*
*(example:)*
- …
> fix(docs): wrong configuration set in filesystem offloader

- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
- align fix made in #13434 with recent refactoring #13388
> Optimize TopicsImpl fix made in #13434

- pulsar-client-cpp/wireshark/README.md
Add docs about how to install the Pulsar Wireshark dissector.
> [Doc] Add docs on how to install the Pulsar Wireshark dissector

- site2/docs/getting-started-clients.md
- site2/website/release-notes.md
Fix https://github.com/apache/pulsar/issues/13414
> [Doc] fix invalid wiki URL

- pulsar-client-cpp/wireshark/README.md
From this [PR](https://github.com/apache/pulsar/pull/13401)
> Fix License check failure

- conf/functions_worker.yml
Fix typo in functions-work.yaml
trival changes, no need doc
> Fix typo in functions-work.yaml

- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java
Add the CmdTransactions to PulsarAdminTool.
Add the CmdTransactions to PulsarAdminTool.
*(or)*
*(or)*
*(example:)*
- The …
> [Transaction] Add transaction admin

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Backlog quota support cross multiple clusters
> Backlog quota support cross multiple clusters

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Message TTL support cross multiple clusters
> Message TTL support cross multiple clusters

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Message dispatch rate policies support cross multiple clusters.
> Message dispatch rate policies support cross multiple clusters.

- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java
Fix: pulsar-admin cli docs of transactions is missing
*(or)*
*(or)*
*(example:)*
*If `yes` was chosen, please …
> [website] fix: pulsar-admin cli docs of transactions

- site2/docs/tiered-storage-filesystem.md
- site2/website-next/docs/tiered-storage-filesystem.md
- site2/website-next/versioned_docs/version-2.7.1/tiered-storage-filesystem.md
- site2/website-next/versioned_docs/version-2.7.2/tiered-storage-filesystem.md
- site2/website-next/versioned_docs/version-2.7.3/tiered-storage-filesystem.md
- site2/website-next/versioned_docs/version-2.8.0/tiered-storage-filesystem.md
- site2/website-next/versioned_docs/version-2.8.1/tiered-storage-filesystem.md
- site2/website-next/versioned_docs/version-2.8.2/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.0/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.1/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.2/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.3/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.0/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.1/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.2/tiered-storage-filesystem.md
In the [tiered-storage-filesystem](https://pulsar.apache.org/docs/en/2.8.1/tiered-storage-filesystem/) tutorial uses `pulsarctl`. But it is confusing for users that pulsar docs has no context about `pulsarctl`, so i think it will be better to use `pulsar-admin` to keep consistent. 
Replace `pulsarctl` with `pulsar-admin` in [tiered-storage-filesystem](https://pulsar.apache.org/docs/en/2.8.1/tiered-storage-filesystem/) 
*(or)*
*(or)*
*(example:)* …
> fix(docs): replace pulsarctl in offload docs

- site2/website/static/swagger/2.7.4/swagger.json
- site2/website/static/swagger/2.7.4/swaggerfunctions.json
- site2/website/static/swagger/2.7.4/swaggersink.json
- site2/website/static/swagger/2.7.4/swaggersource.json
As releasing 2.7.4, so add relative swagger file.
> Add 2.7.4 swagger file

- site2/website/release-notes.md
As releasing 2.7.4, so add release note.
> Add release note for 2.7.4

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Max producer support cross multiple clusters
> Max producer support cross multiple clusters

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
> remove duplicated code

- site2/docs/getting-started-standalone.md
Update the `getting-started-standalone.md` file.
1. Update the module `What your package contains`: Per the latest Pulsar version, the `instances` folder is also the default directory in Pulsar.
2. Update the command `pulsar-daemon start standalone` to `bin/pulsar-daemon start standalone` according to the whole context(eg. `bin/pulsar` is used in this chapter), which can be more easily executed by users. If not, users will be promoted that `pulsar-daemon: command not found`.
> [docs] Update `Getting Started Standalone`

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Max consumers support cross multiple clusters
> Max consumers support cross multiple clusters

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/StatsBuckets.java
- managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/TestStatsBuckets.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/stats/StatsBuckets.java
Fixes #13466
*(or)*
*(or)*
*(example:)*
*If …
> fix: bug when allAll bucket

- .github/PULL_REQUEST_TEMPLATE.md
I think that we don't need committer priviledge to label this pr, only need to check box.
template change.
> [PR template] Optimize to avoid ambiguity

- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java
Fixes #13452 
*(or)*
*(or)*
*(example:)*
- *Extended integration …
> [website] fix: pulsar website cli docs build error

- site2/website/blog/2021-12-14-Apache-Pulsar-2-7-4.md
Do not merge this PR since 2.7.4 is not announced officially and https://github.com/apache/pulsar/pull/13391 is not merged (that is the TBD link in this release blog).
> [Blog] add 2.7.4 release blog

- site2/tools/docker-build-site.sh
Fix: pulsar cli build failure due to `/pulsar/distribution/server/target/classpath.txt: No such file or directory`
*(or)*
*(or)*
*(example:)*
- *Added …
> [website] fix: pulsar cli build failure due to /pulsar/distribution/server/target/classpath.txt: No such file or directory

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Publish rate support cross multiple clusters
> Publish rate support cross multiple clusters

- site2/tools/docker-build-site.sh
fix: website build fail due to can't find classes
*(or)*
*(or)*
*(example:)* …
> [website] fix: website build fail due to can't find classes

- site2/docs/security-tls-keystore.md
- site2/website/versioned_docs/version-2.7.4/security-tls-keystore.md
- site2/website/versioned_docs/version-2.8.2/client-libraries-websocket.md
- site2/website/versioned_docs/version-2.8.2/security-tls-keystore.md
- site2/website/versioned_docs/version-2.9.0/client-libraries-websocket.md
- site2/website/versioned_docs/version-2.9.1/administration-geo.md
- site2/website/versioned_docs/version-2.9.1/client-libraries-websocket.md
Since the doc sets of 2.7.4, 2.8.2, 2.9.1 have been generated, this PR apply the same doc changes of https://github.com/apache/pulsar/pull/12810, https://github.com/apache/pulsar/pull/12633/, https://github.com/apache/pulsar/pull/11681
> [Doc] add docs for client, security, geo

- site2/website/pages/en/download.js
Fixes #13565 
*(or)*
*(or)*
*(example:)*
- *Extended integration test …
> fix: website build fail due to download page parse error

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Subsribe rate support cross multiple clusters
> Subscribe rate support cross multiple clusters

- site2/tools/docker-build-site.sh
- site2/tools/pulsar-doc-gen.sh
- site2/website/brodocs/pulsar-manifest.json
…emoved
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
- *Extended …
> [website] fix: website build fail due to pulsar sub cli cmd dicovery has been removed

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Compaction threshold policies support cross multiple clusters.
> Compaction threshold policies support cross multiple clusters

- site2/tools/docker-build-site.sh
…ocker container
fix: website build fail due to java home setting wrong in docker container
*(or)*
*(or)*
*(example:)* …
> [website] fix: website build fail due to java home setting wrong in docker container

- site2/docs/reference-metrics.md
Fix https://github.com/apache/pulsar/issues/13486
Wil apply the same doc changes to 2.7.x, 2.8.x, 2.9.x.
> [Doc] add explanations for performance metrics

- site2/website/static/swagger/2.8.2/swagger.json
- site2/website/static/swagger/2.8.2/swaggerfunctions.json
- site2/website/static/swagger/2.8.2/swaggerpackages.json
- site2/website/static/swagger/2.8.2/swaggersink.json
- site2/website/static/swagger/2.8.2/swaggersource.json
Update swagger file for 2.8.2 release
> Update 2.8.2 swagger file

- pulsar-sql/pom.xml
- pulsar-sql/presto-distribution/LICENSE
Presto libraries contain multiple mixed versions of SLF4J libraries. 
- add dependency management entries to address the dependency issue
> [Presto] Fix issue of mixed SLF4J library versions in presto libs

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
MaxMessageSize support cross multiple clusters
> MaxMessageSize support cross multiple clusters

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
Fixes #<xyz>
Condition 'policies != null' is always 'true' ,so no need to judge.
delete 'policies != null'.
*(or)*
*(or)*
*(example:)*
- …
> Condition 'policies != null' is always 'true' ,no need to judge.

- site2/docs/security-tls-authentication.md
- site2/website-next/docs/security-tls-authentication.md
- site2/website-next/versioned_docs/version-2.9.0/security-tls-authentication.md
- site2/website-next/versioned_docs/version-2.9.1/security-tls-authentication.md
- site2/website/versioned_docs/version-2.9.0/security-tls-authentication.md
- site2/website/versioned_docs/version-2.9.1/security-tls-authentication.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
> [Doc] Fix security-tls-authentication documentation

- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordCursor.java
Should check the field eventTime but not publishTime.
> Fix time field use error

- pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java
Fix raw use of generic types in OwnershipCache
Fix the raw use of generic types in `org.apache.pulsar.broker.namespace.OwnershipCache#locallyAcquiredLocks`
- The schema: ( no)
> [Broker] Fix raw use of generic types in OwnershipCache

- pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiHealthCheckTest.java
> Healthcheck v2 failed

- site2/docs/client-libraries-go.md
- site2/website/versioned_docs/version-2.6.0/client-libraries-go.md
- site2/website/versioned_docs/version-2.6.1/client-libraries-go.md
- site2/website/versioned_docs/version-2.6.2/client-libraries-go.md
- site2/website/versioned_docs/version-2.6.3/client-libraries-go.md
- site2/website/versioned_docs/version-2.6.4/client-libraries-go.md
- site2/website/versioned_docs/version-2.7.0/client-libraries-go.md
- site2/website/versioned_docs/version-2.7.1/client-libraries-go.md
- site2/website/versioned_docs/version-2.7.2/client-libraries-go.md
- site2/website/versioned_docs/version-2.7.3/client-libraries-go.md
- site2/website/versioned_docs/version-2.7.4/client-libraries-go.md
- site2/website/versioned_docs/version-2.8.0/client-libraries-go.md
- site2/website/versioned_docs/version-2.8.1/client-libraries-go.md
- site2/website/versioned_docs/version-2.8.2/client-libraries-go.md
- site2/website/versioned_docs/version-2.9.0/client-libraries-go.md
- site2/website/versioned_docs/version-2.9.1/client-libraries-go.md
Signed-off-by: xiaolongran <rxl@apache.org>
Fix code example of producer for delay message, when we use delay message, we need to disable batch in Producer side.
Fix code example of delay message for version-2.6.0 to new master version.
> Fix code example of producer for delay message

- pulsar-client-api/pom.xml
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/AuthenticationFactory.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/BatcherBuilder.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/EncryptionKeyInfo.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/KeySharedPolicy.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Message.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/MessageId.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Range.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Reader.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ReaderBuilder.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/SizeUnit.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/KeyValueSchema.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaReader.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/transaction/TransactionCoordinatorClientException.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/internal/DefaultImplementation.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/internal/PulsarClientImplementationBinding.java
- pulsar-client-api/src/main/java/org/apache/pulsar/common/schema/SchemaInfo.java
- pulsar-client-api/src/main/java/org/apache/pulsar/common/schema/SchemaType.java
- tests/docker-images/java-test-image/pom.xml
currently, the `pulsar-client-api` module is not protected by the `checkstyle-plugin`.
- Enable CheckStyle Plugin
- Fix checkstyle violations
java checkstyle changes, no need doc.
> Enable CheckStyle Plugin in Pulsar client api

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
Fixes #12635 
remove redundant code
remove redundant  code.
> remove redundant code

- site2/README.md
- site2/docs/admin-api-tenants.md
Fixes #13657
Improve the docs around tenant admin api.
Just some minor website fixes.
No
> [Issue 13657][website] fixes to admin-api-tenants page

- NOTICE
- distribution/server/src/assemble/NOTICE.bin.txt
> Update notice year.

- site2/website-next/docusaurus.config.js
- site2/website-next/src/components/CLI.js
- site2/website-next/src/pages/pulsar-admin-cli.js
- site2/website-next/src/pages/pulsar-cli.js
- site2/website-next/src/pages/pulsar-client-cli.js
- site2/website-next/src/pages/pulsar-perf-cli.js
- site2/website-next/src/theme/Navbar/index.js
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
> [website][upgrade] feat: cli pages migration

- site2/docs/develop-plugin.md
- site2/website/contributing.md
- site2/website/sidebars.json
Add docs for https://github.com/apache/pulsar/pull/12869 and https://github.com/apache/pulsar/pull/12970
Thanks for your tech inputs and guidance @315157973 
> [Doc] add explanations for entry filter

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Fixes #13671
Master Issue: #13671
see #13671
- Fix wrong expression.
> fixed Producer semaphore permit release issue

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
* Upgrade to BookKeeper 4.14.4: https://github.com/apache/bookkeeper/pulls?q=is%3Apr+is%3Aclosed+label%3Arelease%2F4.14.4 
* Upgrade Grpc to 1.42.1 to match the same version used in BK
> Upgrade BK to 4.14.4 and Grpc to 1.42.1

- pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdProduce.java
- site2/website-next/docs/reference-cli-tools.md
We would like to use disable replication in pulsar-client-tools.
Add `--disable-replication` parameter to `produce` (sub command) in pulsar-client-tools
> [pulsar-client-tools] Support Disable Replication in Pulsar Client Tools

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
maxSubscriptionsPerTopic support cross multiple clusters
> maxSubscriptionsPerTopic support cross multiple clusters

- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/TableViewBuilder.java
The TableView PR https://github.com/apache/pulsar/pull/12838 was developed before the checkstyle was enabled. So now it's failing the CI check after it's merged.
```
Error:  src/main/java/org/apache/pulsar/client/api/TableViewBuilder.java:[25,1] (imports) ImportOrder: Extra separation in import group before 'java.util.Map'
Error:  src/main/java/org/apache/pulsar/client/api/TableViewBuilder.java:[25,1] (imports) ImportOrder: Import java.util.Map appears after other imports that it should precede
Error:  src/main/java/org/apache/pulsar/client/api/TableViewBuilder.java:[81] (javadoc) JavadocStyle: First sentence should end with a period.
Error:  src/main/java/org/apache/pulsar/client/api/TableViewBuilder.java:[89] (javadoc) JavadocStyle: First sentence should end with a period.
Error: …
```
> fix checkstyle for TableViewBuilder

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Offload policies support cross multiple clusters
> Offload policies support cross multiple clusters

- site2/website-next/data/resources.js
- site2/website-next/data/team.js
- site2/website-next/data/users.js
- site2/website-next/docusaurus.config.js
- site2/website-next/src/components/CommonTable.js
- site2/website-next/src/css/custom.css
- site2/website-next/src/pages/powered-by.js
- site2/website-next/src/pages/resources.js
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
> [website][upgrade]feat: resources page and powered-by page

- pulsar-client-1x-base/pom.xml
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ClientConfiguration.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/Consumer.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ConsumerConfiguration.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/MessageBuilder.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/MessageListener.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/Producer.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ProducerConfiguration.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/PulsarClient.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/Reader.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ReaderConfiguration.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ReaderListener.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/package-info.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/impl/MessageBuilderImpl.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/impl/package-info.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/impl/v1/ConsumerV1Impl.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/impl/v1/ProducerV1Impl.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/impl/v1/PulsarClientV1Impl.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/impl/v1/ReaderV1Impl.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/impl/v1/package-info.java
- pulsar-client-messagecrypto-bc/pom.xml
- pulsar-client-messagecrypto-bc/src/main/java/org/apache/pulsar/client/impl/crypto/MessageCryptoBc.java
- pulsar-client-messagecrypto-bc/src/main/java/org/apache/pulsar/client/impl/crypto/package-info.java
Motivation
enable checkStyle_plugin  in  pulsar-client-1x-base module.
enable checkStyle_plugin  in pulsar-client-messagecrypto-bc module.
Documentation
> Enable CheckStyle Plugin in pulsar-client-1x-base module

- site2/docs/functions-worker.md
> [Docs] add documentation for additionalJavaRuntimeArguments (PR #13282)

- site2/website-next/data/connectors.js
- site2/website/data/connectors.js
[pulsar download](https://pulsar.apache.org/en/download/) is missing two connectors: [debezium-mssql](https://github.com/apache/pulsar/tree/master/pulsar-io/debezium/mssql) and [debezium-oracle](https://github.com/apache/pulsar/tree/master/pulsar-io/debezium/oracle).
Added the missing connectors on download page.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after broker …
> fix(website): missing connectors on download page

- site2/docs/functions-worker.md
- site2/website-next/docs/concepts-messaging.md
- site2/website-next/versioned_docs/version-2.9.0/concepts-messaging.md
- site2/website-next/versioned_docs/version-2.9.1/concepts-messaging.md
- site2/website/versioned_docs/version-2.9.0/concepts-messaging.md
- site2/website/versioned_docs/version-2.9.1/concepts-messaging.md
Fix https://github.com/apache/pulsar/issues/13667
> [Doc] fix dead links in messaging chapter

- wireshark/README.md
- wireshark/pulsar.lua
Fixes #13517
add a Lua plugin
maybe need a code review
*(or)*
*(or)*
*(example:)* …
> feat: add lua wireshark for pulsar

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SystemTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/SystemTopicClient.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/InactiveTopicDeleteTest.java
See #13611
- Resolve cheery-pick conflict.
- The schema: (no )
> [Branch 2.8] Fixed internal topic effect by InactiveTopicPolicy.

- pulsar-testclient/pom.xml
- pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java
- pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/SimpleTestProducerSocket.java
- pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/package-info.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/BrokerMonitor.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/CmdGenerateDocumentation.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/DefaultMessageFormatter.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationClient.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationController.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/ManagedLedgerWriter.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerfClientUtils.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/package-info.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/utils/FixedColumnLengthTableMaker.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/utils/package-info.java
- pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceTransactionTest.java
Motivation
enable checkStyle plugin in pulsar-testclient module.
Documentation
> Enable  checkStyle plugin in pulsar-testclient module

- pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/RGUsageMTAggrWaitForAllMsgsTest.java
Master Issue: #13755
Unregistering namespace rg-3/rg-0 will affect the subsequent course of action
> [Flaky-test] RGUsageMTAggrWaitForAllMsgsTest. testMTProduceConsumeRGUsageNonPersistentTopicNamesDifferentTenant 

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/DeprecatedCommanderTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
DeduplicationSnapshotIntervalSeconds support cross multiple clusters
> DeduplicationSnapshotIntervalSeconds support cross multiple clusters

- pulsar-sql/pom.xml
- pulsar-sql/presto-distribution/src/main/java/org/openjdk/jol/info/ClassLayout.java
- pulsar-sql/presto-distribution/src/main/java/org/openjdk/jol/info/package-info.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarColumnHandle.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarColumnMetadata.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorModule.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarDispatchingRowDecoderFactory.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarInternalColumn.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarMetadata.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordCursor.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordSet.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRowDecoder.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarSqlSchemaInfoProvider.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/avro/PulsarAvroColumnDecoder.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/avro/PulsarAvroRowDecoder.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/avro/PulsarAvroRowDecoderFactory.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/json/PulsarJsonFieldDecoder.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/json/PulsarJsonRowDecoder.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/json/PulsarJsonRowDecoderFactory.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/primitive/PulsarPrimitiveRowDecoder.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/primitive/PulsarPrimitiveRowDecoderFactory.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/protobufnative/PulsarProtobufNativeColumnDecoder.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/protobufnative/PulsarProtobufNativeRowDecoder.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/protobufnative/PulsarProtobufNativeRowDecoderFactory.java
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/util/CacheSizeAllocator.java
Motivation
enable checkStyle plugin in pulsar-sql module.
Documentation
> Enable check style plugin in pulsar sql module

- conf/broker.conf
The possible values hint for `managedLedgerOffloadDriver` on `broker.conf` is quite out of date, so i want to update it.
I added values of `azureblob`, `aliyun-oss`, `filesystem` and deprecate the `S3` seems it is not supported. 
*(or)*
*(or)*
*(example:)*
- Dependencies (does it add …
> fix(conf): update OffloadDriver values hint in broker conf

- site2/tools/pulsar-admin-doc-gen.sh
- site2/website/brodocs/pulsar-admin-manifest.json
Fixes https://github.com/apache/pulsar/issues/13857
[website] fix: pulsar admin bookie cli missing
*(or)*
*(or)*
*(example:)* …
> [website]fix: pulsar admin bookie cli missing

- site2/docs/reference-metrics.md
> Fix managed cursor acknowledgment state metric names

- site2/website/data/team.js
Add three new committers to the team page.
> [website] Add new committers to team page

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
Master Issue: #13854
See #13854
> [Issue 13854][broker] Fix call sync method in async rest api for internalGetPartitionedStatsInternal

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/HierarchyTopicPolicies.java
Master Issue: #13756
See #13756
Add  retentionPolicies in HierarchyTopicPolicies
This change is already covered by existing tests
- org.apache.pulsar.broker.service.PersistentTopicConcurrentTest#testConcurrentTopicGCAndSubscriptionDelete
> [broker] Optimize retentionPolicies with HierarchyTopicPolicies

- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsServlet.java
Exception information is not recorded in the log
Optimize the exception log not to print
simple change
> Optimize the exception log is not printed

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
Avoid call sync method in async rest API for PersistentTopicsBase#internalResetCursorOnPosition.
> [Broker] Fix call sync method in async rest api for internalResetCursorOnPosition

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
Master Issue: #13854
See #13854
> [Issue 13854][broker] Fix call sync method in async rest api for internalDeleteSubscription #13884

- site2/docs/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.6.4/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.7.0/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.7.1/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.7.2/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.7.3/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.7.4/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.8.0/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.8.1/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.8.2/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.9.0/tiered-storage-azure.md
- site2/website/versioned_docs/version-2.9.1/tiered-storage-azure.md
Like the https://github.com/apache/pulsar/pull/13801, fix the markdown format issues in Azure offload docs.
Fixed markown format issues on docs.
*(or)*
*(or)*
*(example:)*
- The default …
> fix(docs): markdown format issue in azure offload docs

- site2/docs/reference-metrics.md
Add doc for pulsar_publish_rate_limit_times
see https://github.com/apache/pulsar/pull/13538
- [ x ] `doc`
> Add doc for pulsar_publish_rate_limit_times

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
Avoid call sync method in async rest API for PersistentTopicsBase#preValidation.
> [Broker] Fix call sync method in async rest api for preValidation.

- site2/docs/getting-started-clients.md
- site2/docs/reference-metrics.md
Add docs for https://github.com/apache/pulsar/issues/13971
> [Doc] update bookie metrics and function matrix link

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/HierarchyTopicPolicies.java
Master Issue: #13756
See #13756
Add  maxUnackedMessagesOnSubscription in HierarchyTopicPolicies
This change is already covered by existing tests
- org.apache.pulsar.broker.admin.TopicPoliciesTest#testMaxUnackedMessagesOnSubscriptionPriority
> [broker] optimize maxUnackedMessagesOnSubscription with HierarchyTopicPolicies

- deployment/terraform-ansible/aws/versions.tf
Fix missed license header introduced by #7887
> Fix missed license header introduced by #7887

- pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
> [broker]make validateTopicPolicyOperation method async in PulsarWebResource

- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/transaction/TransactionCoordinatorClientException.java
Remove unnecessary exceptions.
*(or)*
*(or)*
*(example:)*
- The admin cli options: (yes / …
> [Transaction] Delete TransactionTimeoutException

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java
Fixes #14080
Master Issue: #14080
see #14080
- Add null check to avoid NPE.
> [Issue 14080] Clean up Cleanup NPEs in ``ServerCnxTest ``

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TableViewTest.java
Currently, the TableView doesn't have a units test to cover its behavior, we should add some units test to cover it.
Add units test for TableView.
> [Test] Add units test for TableView

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
Make  ``BrokerBase#healthCheck`` to pure async.
- change sync method to async.
> Make  ``BrokerBase#healthCheck`` to pure async

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java
`failPendingRequest()` is changed to be executed in internalPinnedExecutor in #13135
But `pendingRequests.clear()` is called right after `failPendingRequest()`, so `pendingRequests` is always empty when the codes in failPendingRequest is executed.
1. Remove `failPendingRequest()` out of internalPinnedExecutor. It's already executed in internalPinnedExecutor.
2. Changes `pendingRequests.keys()` to `pendingRequests.forEach`, as `ConcurrentLongHashMap#keys` makes a  copy of keys.
This change is already covered by existing tests, such as org.apache.pulsar.client.impl.TransactionClientConnectTest#testPulsarClientCloseThenCloseTcClient
- The …
> [Client][Transaction] Fix OpBase.callback is not called in TransactionMetaStoreHandler#failPendingRequest

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
remove unused code in PersistentTopicsBase.
> [Broker]remove unused code in PersistentTopicsBase

- pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntime.java
Fixes #14157
Remove sensitive information from log
> [Issue 14157] Remove sensitive information from log

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
> [Issue 14013][broker]make offloadStatus method async

- pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
> [broker]make validateNamespacePolicyOperation method async in PulsarWebResource

- pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
Fixes #14105
See #14105
The root cause is that when we call `TopicLookupBase#internalLookupTopicAsync` --> `NamespaceService#checkTopicExists` --> `BrokerService#getTopicIfExists` during lookup request handing, non-persistent partitioned topic is auto created at
https://github.com/apache/pulsar/blob/00e7cc6e3429d38d6e24af3dc5a840ff9a73601f/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L949-L956
But the ns bundle may not bind to this broker yet, so this PR resolve this issue by avoid creating any topics in `NamespaceService#checkTopicExists`.
This change is already covered by existing tests, such as AdminApi2Test.testGetListInBundle
- The public …
> [Issue 14105] Avoid creating any topics in `NamespaceService#checkTopicExists` during topic lookup.

- site2/docs/client-libraries-dotnet.md
Hello, Apache Pulsar community!
As this is my first pull request in this repo, please let me know if I did everything correctly or if there is anything I can improve in this PR to get it accepted.  
Helping others using Apache Pulsar by improving the docs.
In the client-libraries-dotnet.md file under "Acknowledge messages"
There was an error in Acknowledge messages individually subsection.
Changed the code to use Acknowledge(message) method.
As it is shown in the official dotnet client docs https://github.com/apache/pulsar-dotpulsar/wiki/Consumer
Yes new docs should be generated
> Documentation: Fix in docs for dotnet client

- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/ManagedLedgerWriter.java
- site2/docs/reference-cli-tools.md
Master Issue: #13760 
Add doc for #14145
> [Doc] Allow configuring `metadataStoreUrl` in `pulsar-perf managed-ledger`

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Redundant debug log
delete redundant debug log
> [Broker] Reduce redundant debug log

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
There is a log information error in PulsarAuthorizationProvider
change the log information
- Make sure that the change passes the CI checks.
- The schema: (no )
> fix a log error in PulsarAuthorizationProvider

- pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
cover log.debug with log.isDebugEnabled() in PulsarWebResource
cover log.debug with log.isDebugEnabled() in PulsarWebResource
This change is a trivial rework without any test coverage.
> [Minor] cover log.debug with log.isDebugEnabled()

- pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java
- site2/docs/reference-cli-tools.md
- site2/website-next/docs/reference-cli-tools.md
- *Add short name 'cf' for long parameter name 'conf-file'.*
- PerformanceClient.java
- PerformanceConsumer.java
- PerformanceProducer.java
- PerformanceReader.java
- PerformanceTransaction.java
- 2 'reference-cli-tools.md' pages.
Check the box below or label this PR directly …
> [testclient] Add short name for conf-file parameter.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java
When a user calls the admin rest API resulting in an exception, we need to add an error log,
it is very helpful for the user to understand what happened.
- Add some logs for the ``BrokerBase`` method.
> [Management] Optimize ``BrokerBase`` log.

- site2/docs/client-libraries-java.md
1. Add a new section "Registering listeners"
2. Change code example for "Configure TableView"
> [Doc] TableView java client: Add a new section and change code example

- pom.xml
- tests/bc_2_0_0/pom.xml
- tests/bc_2_0_1/pom.xml
- tests/bc_2_6_0/pom.xml
- tests/integration/pom.xml
- tests/pulsar-client-admin-shade-test/pom.xml
- tests/pulsar-client-all-shade-test/pom.xml
- tests/pulsar-client-shade-test/pom.xml
Fixes #14294
works around https://youtrack.jetbrains.com/issue/IDEA-278750
> Fix IntelliJ error with @{testJacocoAgentArgument} parameter

- pulsar-common/src/main/java/org/apache/pulsar/common/util/RelativeTimeUtil.java
- Replace the deprecated method in RelativeTimeUtil
- fix a typo
> [CLEANUP] Replace the deprecated method in RelativeTimeUtil

- .asf.yaml
Whitespace commit to trigger content deployment as recommended by Infra
> Update .asf.yaml to try to trigger deployment

- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBookies.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBrokers.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPackages.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSchemas.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Add short name for full name in admin cli.
> [pulsar-admin] Add short name for full name in admin cli

- site2/website/siteConfig.js
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
> [website]feat: add new website preview link into website navigation

- site2/docs/sql-deployment-configurations.md
- site2/website/versioned_docs/version-2.7.0/sql-deployment-configurations.md
- site2/website/versioned_docs/version-2.7.1/sql-deployment-configurations.md
- site2/website/versioned_docs/version-2.7.2/sql-deployment-configurations.md
- site2/website/versioned_docs/version-2.7.3/sql-deployment-configurations.md
- site2/website/versioned_docs/version-2.7.4/sql-deployment-configurations.md
- site2/website/versioned_docs/version-2.8.0/sql-deployment-configurations.md
- site2/website/versioned_docs/version-2.8.1/sql-deployment-configurations.md
- site2/website/versioned_docs/version-2.8.2/sql-deployment-configurations.md
- site2/website/versioned_docs/version-2.9.0/sql-deployment-configurations.md
- site2/website/versioned_docs/version-2.9.1/sql-deployment-configurations.md
1. Fix https://github.com/apache/pulsar/pull/8635
2. Preview looks good:
3. Will apply the same changes to versions ≥ 2.7.0 once this PR gets approved.
> [Doc][SQL] add explanations for how to get last message in topics

- site2/docs/io-mongo-sink.md
- site2/website/versioned_docs/version-2.5.0/io-mongo-sink.md
- site2/website/versioned_docs/version-2.6.0/io-mongo-sink.md
- site2/website/versioned_docs/version-2.6.1/io-mongo-sink.md
- site2/website/versioned_docs/version-2.6.2/io-mongo-sink.md
- site2/website/versioned_docs/version-2.6.3/io-mongo-sink.md
- site2/website/versioned_docs/version-2.6.4/io-mongo-sink.md
- site2/website/versioned_docs/version-2.7.0/io-mongo-sink.md
- site2/website/versioned_docs/version-2.7.1/io-mongo-sink.md
- site2/website/versioned_docs/version-2.7.2/io-mongo-sink.md
- site2/website/versioned_docs/version-2.7.3/io-mongo-sink.md
- site2/website/versioned_docs/version-2.7.4/io-mongo-sink.md
- site2/website/versioned_docs/version-2.8.0/io-mongo-sink.md
- site2/website/versioned_docs/version-2.8.1/io-mongo-sink.md
- site2/website/versioned_docs/version-2.8.2/io-mongo-sink.md
- site2/website/versioned_docs/version-2.9.0/io-mongo-sink.md
- site2/website/versioned_docs/version-2.9.1/io-mongo-sink.md
Like the https://github.com/apache/pulsar/pull/14418, fix the yaml formal issue in mongo-sink docs.
Fix the yaml formal issue in mongo-sink docs.
*(or)*
*(or)*
*(example:)*
- The …
> fix(docs): fix yaml formal in mongo-sink

- site2/website/versioned_docs/version-2.4.1/io-debug.md
- site2/website/versioned_docs/version-2.4.2/io-debug.md
- site2/website/versioned_docs/version-2.5.1/io-debug.md
- site2/website/versioned_docs/version-2.5.2/io-debug.md
- site2/website/versioned_docs/version-2.6.0/io-debug.md
- site2/website/versioned_docs/version-2.6.1/io-debug.md
- site2/website/versioned_docs/version-2.6.2/io-debug.md
- site2/website/versioned_docs/version-2.6.3/io-debug.md
- site2/website/versioned_docs/version-2.6.4/io-debug.md
- site2/website/versioned_docs/version-2.7.0/io-debug.md
- site2/website/versioned_docs/version-2.7.1/io-debug.md
- site2/website/versioned_docs/version-2.7.2/io-debug.md
- site2/website/versioned_docs/version-2.7.3/io-debug.md
- site2/website/versioned_docs/version-2.7.4/io-debug.md
- site2/website/versioned_docs/version-2.8.0/io-debug.md
- site2/website/versioned_docs/version-2.8.1/io-debug.md
- site2/website/versioned_docs/version-2.8.2/io-debug.md
- site2/website/versioned_docs/version-2.9.0/io-debug.md
- site2/website/versioned_docs/version-2.9.1/io-debug.md
The `mongo-sink-config.yaml` in [How to debug Pulsar connectors](https://pulsar.apache.org/docs/en/io-debug/#debug-in-cluster-mode) uses a wrong yaml format, you will get an error `java.lang.IllegalArgumentException: Required property not set.` if you use that sample config.
Fix the format issue in `mongo-sink-config.yaml`.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after …
> fix(docs): wrong yaml format in docs

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
Remove an unnecessary stream use
Remove unnecessary stream usage at  org.apache.pulsar.client.impl.MultiTopicsConsumerImpl#getLastMessageIdAsync
> [pulsar-client] Remove an unnecessary stream use

- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/CLITest.java
Adjust PulsarAdminException to ParameterException in cli, which is more friendly when displaying error messages.
*pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java.* …
> [pulsar-client-tools] Adjust PulsarAdminException to ParameterException in cli.

- site2/docs/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.0/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.1/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.2/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.3/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.4/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.0/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.1/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.2/tiered-storage-filesystem.md
Fix the markdown format issue on filesystem offloader docs: 
Fix the markdown format issue on filesystem offloader docs. 
*(or)*
*(or)*
*(example:)* …
> fix(docs): format issue in filesystem offloader docs

- site2/docs/client-libraries-python.md
- `except:` -> `except Exception:`
- Update supported python versions
Fixes #<xyz>
Couldn't Ctrl+C one of the python client code examples (I think because of bare except)
Replace some bare exceptions so that the try: except block doesn't catch `Ctrl+C` interrupts. 
Just changes to docs
nope
> [docs] Fix bare excepts in python client example code

- site2/website/versioned_docs/version-2.5.0/io-influxdb-sink.md
- site2/website/versioned_docs/version-2.9.0/io-influxdb-sink.md
- site2/website/versioned_docs/version-2.9.1/io-influxdb-sink.md
Like the https://github.com/apache/pulsar/pull/14418, fix the yaml formal issue in influxdb-sink docs.
*(or)*
*(or)*
*(example:)*
- The default …
> fix(docs): yaml format issue in influxdb sink

- pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java
**Motivation**
Fix some typos.
> Fix some typos

- structured-event-log/pom.xml
- structured-event-log/src/main/java/org/apache/pulsar/structuredeventlog/EventResourcesImpl.java
- structured-event-log/src/main/java/org/apache/pulsar/structuredeventlog/StructuredEventLog.java
- structured-event-log/src/main/java/org/apache/pulsar/structuredeventlog/package-info.java
- structured-event-log/src/main/java/org/apache/pulsar/structuredeventlog/slf4j/Slf4jEvent.java
- structured-event-log/src/main/java/org/apache/pulsar/structuredeventlog/slf4j/package-info.java
Motivation
enable checkStyle_plugin  in  structured-event-log module.
Documentation
> Enable CheckStyle Plugin in structured-event-log module

- pom.xml
- pulsar-package-management/bookkeeper-storage/pom.xml
- pulsar-package-management/filesystem-storage/pom.xml
*Remove junit4 dependency item.*
- pom.xml
- pulsar-package-management/bookkeeper-storage/pom.xml
- pulsar-package-management/filesystem-storage/pom.xml
(If you need help on updating docs, …
> [junit4] Remove junit4 dependency item.

- site2/docs/administration-pulsar-manager.md
Fixed #13583
Currently, when deployed according to the documentation, the structure is confusing and not easy to install quickly.
I have modified the structure of the documentation to follow the Docker deployment style to make it easier for users to understand and deploy quickly.
The above picture is the revised outline of the article.
- Dependencies (does it add or upgrade a dependency): (yes /**no**)
- Anything that affects deployment: (yes / no/ **don't know**)
> [Doc] Optimize pulsar-manager documentation

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
Fix log in `updateSubscriptionPermissionAsync` method.
> [Authorization] Fix log in updateSubscriptionPermissionAsync

- site2/website/blog/2022-02-24-apache-pulsar-community-welcomes-500th-contributor
Fixes ISSUE-14462
Master Issue: [ISSUE-14462](https://github.com/streamnative/pulsar/issues/3824)
Recently, the Pulsar community reached 500 contributors. This blog, co-authored by Matteo Merli with Karin Landers and Alice Bi, provides an overview of the growth of the Pulsar community, product updates, and celebrates this community milestone.
Adding this blog to https://pulsar.apache.org/blog/
- …
> [Issue 14462] 500th contributor blog

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
Fixes #<xyz>
Correct status message prompt.
When the topic of getPartitionedMetadata does not exist, it should prompt the non-existence of the topic, not the non-existence of the tenant.
*(or)*
*(or)*
*(example:)*
- …
> Correct status message prompt.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
Now we merged https://github.com/apache/pulsar/pull/14288, but https://github.com/apache/pulsar/pull/14246 has removed the log. So we add back to help find if there are other bugs.
> Add log to track negtive unacked msg.

- site2/website/data/resources.js
- site2/website/pages/en/resources.js
Many books on Apache Pulsar have been published, so I would love to add the book resource to the website to help community members to learn Apache Pulsar.
Add books resources to the webpage.
> [website] Add books to Resources page

- site2/docs/admin-api-clusters.md
- site2/docs/concepts-architecture-overview.md
- site2/docs/deploy-bare-metal-multi-cluster.md
- site2/docs/deploy-bare-metal.md
- site2/docs/reference-cli-tools.md
- site2/docs/reference-configuration.md
To align with follow-up code changes for #13760 (ZK free), fix the remaining zookeeper wordings in the document.
> [Doc] Follow-up modifications for ZK free

- pulsar-broker/src/test/java/org/apache/pulsar/client/api/MemoryLimitTest.java
Fixes #14220
Fixes #14220
make sure OpSendMessages will not be sent to broker while sending messages, await util all message send, and await util all message send complete
bugfix for testcase
> Fixed flaky test MemoryLimitTest#testRejectMessages (#14220)

- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Message.java
fix a java client javadoc typo
> [typo] [minor] fix java client javadoc typo

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java
Optimize ClientBuilderImpl        
1. unify argument check logic using Preconditions instead of partly using Preconditions partly use if ...
2. simplify if else logic on checking serviceUrlProvider
Fixes #<xyz>
I  find `ClientBuilderImpl` class can be improved by unify code style when checking argument validity and simplifying  if else logic for  param serviceUrlProvider verifying.   At present,  in `ClientBuilderImpl` some params verifying use Preconditions ， while some do not, it is not unified，and some if else logic can be omitted eg: when checking serviceUrlProvider.  
therefore, I submit …
>  Optimize ClientBuilderImpl

- pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionStats.java
- pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java
- site2/docs/reference-metrics.md
> Fix description about subscription backlog

- site2/docs/cookbooks-retention-expiry.md
Remove the duplicate image  introduced in https://github.com/apache/pulsar/pull/14546.
> [Doc] Remove duplicate image

- pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
Make field final in [JavaInstanceRunnable](https://github.com/apache/pulsar/blob/master/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java) Class
> [optimize] Make field final in java instance runnable

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentDispatcherFailoverConsumerTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
> [cleanup] [broker] Cleanup the unused subscriptionInitialPosition of onsumer.java

- pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java
- pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java
- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/AbstractMetadataDriver.java
Fixes #14690
Try to build a metadata store from configuration.
> Fix failed initialized METADATA_STORE_SCHEME

- pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroup.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupConfigListener.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/PendingAckHandleImpl.java
- pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
- pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/process/ProcessRuntimeTest.java
- pulsar-io/file/src/test/java/org/apache/pulsar/io/file/FileListingThreadTests.java
- pulsar-io/file/src/test/java/org/apache/pulsar/io/file/ProcessedFileThreadTests.java
- pulsar-io/hdfs2/src/test/java/org/apache/pulsar/io/hdfs2/sink/AbstractHdfsSinkTest.java
- pulsar-io/twitter/src/test/java/org/apache/pulsar/io/twitter/TwitterFireHoseConfigTests.java
- pulsar-testclient/src/test/java/org/apache/pulsar/testclient/Oauth2PerformanceTransactionTest.java
- pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceProducerTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/CLITest.java
*Remove redundant toString() method callings*
Remove redundant toString() method callings
(If this PR contains doc …
> Remove redundant toString() method callings in logs

- pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
Cleanup the create admin client and create ns code in standalone.
Improve create admin client and create ns by the method provided by PulsarService.
> [cleanup][broker]: Improve create admin and ns in standalone starter

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
Apply the change of #14759 to `topicPublisherThrottlingTickTimeMillis`.
The config of `topicPublisherThrottlingTickTimeMillis` is marked as dynamic,  does not support like increase the value from 1 to 1000.
1. similar as #14759
- BrokerServiceTest#testDynamicTopicPublisherThrottlingTickTimeMillis
> [enh][broker] Support dynamic update between non-zero values of topicPublisherThrottlingTickTimeMillis

- site2/website/release-notes.md
Here are the release notes for 2.8.3. This is a work in progress. Please let me know if you have any recommendations.
* Add notes to the `website`
> 2.8.3 Release Notes

- site2/website/contributing.md
> [feature][workflow] Add Pulsar PR Naming Convention

- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java
fix flaky test link https://github.com/apache/pulsar/issues/14844
> [fix][test]: fix flaky test testTransactionBufferRecoverThrowPulsarClientException

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
Fixes #14877
Fixes #14877
cherry pick from #13950
> [fix][broker][branch-2.8] Fix no value present

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
Fixes #14877
Fixes #14877
cherry pick from #13950
> [fix][broker][branch-2.7] Fix no value present

- pulsar-common/src/main/java/org/apache/pulsar/common/stats/JvmMetrics.java
Since to [Netty 4.1.35.Final](https://github.com/netty/netty/pull/8945), we have an API to get used direct memory, so we don't need to use reflecting to get the used direct memory.
Use netty API instead of reflecting to get used direct memory
> [improve][broker] Use netty API instead of reflecting to get used direct memory

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
Fixes #14877
Fixes #14877
cherry pick from #13950
> [fix][broker][branch-2.9] Fix no value present

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/BinaryProtoLookupService.java
- pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarClassLoader.java
> [fix][client] fix debug level

- site2/website/versioned_docs/version-2.1.0-incubating/cookbooks-deduplication.md
- site2/website/versioned_docs/version-2.1.0-incubating/deploy-kubernetes.md
Signed-off-by: Li Li <urfree@apache.org>
fix: some docs format wrong in 2.1.0-incubating
*(or)*
*(or)*
*(example:)* …
> fix: some docs format wrong in 2.1.0-incubating

- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicPoliciesImpl.java
- pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/sink/PulsarSinkTest.java
- pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactoryTest.java
- pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java
- pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/process/ProcessRuntimeTest.java
- pulsar-io/batch-data-generator/src/main/java/org/apache/pulsar/io/batchdatagenerator/BatchDataGeneratorSource.java
- pulsar-io/data-generator/src/main/java/org/apache/pulsar/io/datagenerator/DataGeneratorSource.java
- pulsar-io/dynamodb/src/main/java/org/apache/pulsar/io/dynamodb/StreamsRecord.java
- pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/AbstractKafkaConnectSource.java
- pulsar-io/rabbitmq/src/test/java/org/apache/pulsar/io/rabbitmq/sink/RabbitMQSinkTest.java
- pulsar-io/redis/src/test/java/org/apache/pulsar/io/redis/sink/RedisSinkTest.java
- tests/docker-images/java-test-functions/src/main/java/org/apache/pulsar/tests/integration/io/TestPropertySource.java
Remove unnecessary override methods
Remove unnecessary override methods
> [hotfix] Remove unnecessary override methods

- pulsar-broker/src/main/java/org/apache/pulsar/broker/BrokerData.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/WRRPlacementStrategy.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelector.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicPoliciesService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/streamingdispatch/StreamingEntryReader.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/TransactionBuffer.java
Fixes #14783 
Fixing the javadoc warnings on the executing maven build for pulsar-broker. 
Changes done in the Java doc which is added as part of code.
```diff
+&lt;
- <
+&gt;
- >
+@link:
-@link
+and
-&&
```
*(or)*
*(or)*
*(example:)*
- Dependencies (does it add or upgrade a dependency): (~~yes~~ / **no**)
- The public API: (~~yes~~ / …
> [Issue 14783][pulsar-broker] Fix javadoc warnings on pulsar-broker

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
> [cleanup] [broker] Remove ledger instance from map by requested id when initialization fails

- site2/website/static/swagger/2.9.2/swagger.json
- site2/website/static/swagger/2.9.2/swaggerfunctions.json
- site2/website/static/swagger/2.9.2/swaggerpackages.json
- site2/website/static/swagger/2.9.2/swaggersink.json
- site2/website/static/swagger/2.9.2/swaggersource.json
The Pulsar 2.9.2 was released, need to update swagger files.
Update swagger files for Pulsar `2.9.2`.
> [release][Doc] Update swagger files for `2.9.2`

- site2/tools/build-site.sh
Signed-off-by: Li Li <urfree@apache.org>
fix: Invalid code tab markdown caused by Translation docs
*(or)*
*(or)*
*(example:)* …
> [fix][website] Invalid code tab markdown caused by Translation docs

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarStats.java
Code cleanup, remove unused field variable:pulsarService in PulsarStats.
Delete field variable:pulsarService.
> [cleanup][broker]remove unused field variable in PulsarStats

- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarSinksTest.java
Improve test coverage of the Kinesis Sink
Added an integration test for `FULL_MESSAGE_IN_JSON_EXPAND_VALUE` with AVRO KeyValue messages input
* Run `org.apache.pulsar.tests.integration.io.sinks. PulsarSinksTest`
- The public API: (yes / no)no
- The schema: (yes / no / don't know)no
- The default values of configurations: (yes / no)no
- The wire protocol: (yes / no)no
- The rest endpoints: (yes / no)no
- The admin cli options: (yes / no)no
- Anything that affects deployment: (yes / no / don't know)no
(If you need …
> Add integration test for Kinesis sink with schema and JSON output

- site2/tools/build-site.sh
Signed-off-by: Li Li <urfree@apache.org>
[fix][website] building fail due to invalid tab error
*(or)*
*(or)*
*(example:)* …
> [fix][website] building fail due to invalid tab error

- site2/docs/reference-metrics.md
add doc for https://github.com/apache/pulsar/pull/14723
add doc in reference-metrics.md
> [doc] schema metrics doc

- site2/tools/build-site.sh
- site2/website/scripts/fix-tab.js
> [fix][website] script for auto fix invalid tab docs

- site2/tools/build-site.sh
- site2/website/scripts/fix-tab.js
> [fix][website] fix script for invalid tab check

- site2/docs/txn-use.md
Add systemTopicEnable=true config to enable transaction
*(or)*
*(or)*
*(example:)*
- The …
> [Improve][doc][txn] add systemTopicEnabled=true for enable transaction

- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java
> [fix] [minor] Fix typo in ConsumerBuilder

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
Fixes #15166 
Add the reader into `readers` concurrent after creation
*(or)*
*(or)*
*(example:)*
- …
> TableView should cache created readers

- site2/docs/txn-use.md
Add brokerDeduplicationEnabled=true config to enable transaction deduplication
*(or)*
*(or)*
*(example:)*
- The rest …
> [Improve][doc][txn] add brokerDeduplicationEnabled=true to enable transaction deduplication

- site2/docs/security-oauth2.md
add configuration to configure brokers to authenticate clients
*(or)*
*(or)*
*(example:)*
- …
> [Improve][doc] add broker config for Oauth2

- site2/docs/client-libraries-cpp.md
This small changes make the examples compile properly in Debian after installing the libraries from the .deb packages.
I was following the code example for the C++ library and I found this small issues when I try to compile it for a Debian.
The modification are just to make the code compile without any change.
- [ X ] `doc`
> [improve][c++ client doc] Example code was not compiling properly

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
Fixes #15196.
If broker having conf `topicFencingTimeoutSeconds`>0, a topic is trigged closed and closed normally, `closeFencedTopicForcefully` should not be called.
Cancel fenced topic monitoring task if topic close normally, which cancel running `closeFencedTopicForcefully`.
- Add `org.apache.pulsar.broker.service.PersistentTopicTest#testTopicCloseFencingTimeout`
- Anything that affects deployment: …
> [fix][broker] Cancel `fencedTopicMonitoringTask` when topic closed normally.

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/KeyValueSchemaImpl.java
- pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/KeyValueSchemaTest.java
Fixes #15118
Added `schemaMap` and to cache results of `atSchemaVersion` in `KeyValueSchemaImpl `
* Run `KeyValueSchemaTest:: testKeyValueSchemaCache `
no
(Docs have …
> Issue 15118: Add a cache of versioned KeyValueSchemaImpl

- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiHealthCheckTest.java
AdminApiHealthCheckTest is now flaky after adding the unit test for detecting deadlocks in the health check (#15155).
The `ManagementFactory.getThreadMXBean().findDeadlockedThreads()` seems to do some caching internally so the test should wait until the deadlocked status clears off before continuing to the next test.
Use Awaitility to wait until the  `ManagementFactory.getThreadMXBean().findDeadlockedThreads()` doesn't report a deadlock.
> Fix flaky test AdminApiHealthCheckTest. Wait for deadlocked status to clear before continuing

- site2/website/scripts/replace.js
> [fix][website]: Pulsar IO Connectors release url error of some versions(for example: 2.10.0)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Cherry-pick #13885 to branch-2.9
> [branch-2.9][Broker] Fix call sync method in onPoliciesUpdate method

- site2/docs/io-elasticsearch.md
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
> Update Elasticsearch name

- pulsar-client-admin-api/src/main/java/org/apache/pulsar/policies/data/loadbalancer/ResourceUsage.java
- pulsar-common/src/test/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerDataTest.java
Fixes #15313 
fix ResourceUsage percentUsage is always 0 when construct by json serialize
> [fix][broker] Fix broker LoadBalance uneffective

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/CreateSubscriptionTest.java
Fixes #15343
We are missing support for SubscriptionProperties for non-durable subscriptions.
- Handle subscription properties in the non-durable subscription path
- Add more tests
- Add more test coverage about subscription properties and Shared subscriptions
> [enh][broker] Support properties on NonDurable subscriptions (PIP-105)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/v1/TopicLookup.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/v2/TopicLookup.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/lookup/http/HttpTopicLookupv2Test.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/lookup/http/v2/TopicLookupTest.java
Make TopicLookupBase#internalLookupTopicAsync pure async
> Make TopicLookupBase#internalLookupTopicAsync pure async

- pulsar-client-cpp/python/pulsar/__init__.py
- pulsar-client-cpp/python/pulsar_test.py
- pulsar-client-cpp/python/src/config.cc
Master Issue: #15325
support listener_name in python client
> [python] support listener_name in python client

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractBaseDispatcherTest.java
fixes-#15297
Fix totalEntries calculation problem in AbstractBaseDispatcher#filterEntriesForConsumere
> [fix] [broker] Fix totalEntries calculation problem in AbstractBaseDispatcher#filterEntriesForConsumere

- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
There's a remaining proxy connection leak which was introduced by the changes #14078 made to fix another connection leak .
Use a better state model to prevent leaks.
> [Proxy] Fix proxy connection leak when inbound connection closes while connecting is in progress

- pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
Master Issue: #10117 #15088 
Fix flaky test at SimpleProducerConsumerTest#testRedeliveryFailOverConsumer
> [flaky test] Fix flaky test at SimpleProducerConsumerTest#testRedeliveryFailOverConsumer

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
Log tuning in SystemTopicBasedTopicPoliciesService#refreshTopicPoliciesCache
> [cleanup][broker] Log tuning in SystemTopicBasedTopicPoliciesService#refreshTopicPoliciesCache

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
Clean unused methods in `BrokerService`
Remove `futureWithDeadline` and `foreachCnx` in `BrokerService`
> [cleanup][broker] Clean unused methods in BrokerService

- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/BrokerDiscoveryProvider.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/BrokerProxyValidator.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ParserProxyHandler.java
There is some unused code in the pulsar-proxy module that can be removed.
- remove unused methods and code
- make one refactoring to fix a warning about generics type
> [Proxy] Remove unused methods and code

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
- managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadPrefixTest.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java
Porting of https://github.com/apache/pulsar/pull/15008 to branch-2.8
> [branch-2.8][fix][broker] Avoid heartbeat topic to offload.

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerStatsRecorderImpl.java
> [improve][java-client] Add pending messages information while print the producer stats

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/NonPersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicsTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApi2Test.java
Make PersistentTopicsBase#internalGetPartitionedMetadata async.
> [Broker] Make PersistentTopicsBase#internalGetPartitionedMetadata async

- bin/bookkeeper
- bin/function-localrunner
- bin/pulsar
Same  with #14711,  fix  wrong IS_JAVA_8 check
Use $JAVA instead of java
> [fix][env]Fix potential incompatible java opts caused by IS_JAVA_8

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
- pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/TopicPolicies.java
- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicPoliciesImpl.java
- pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionPolicies.java
- pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TopicPolicies.java
See PIP-152 #15094
See #15094
- org.apache.pulsar.broker.admin.TopicPoliciesTest#testSubscriptionLevelDispatchRate
- The rest endpoints: (**yes**)
- The admin cli options: (**yes**)
Doc added in admin client api.
> [PIP-152] Support subscription level dispatch rate limiter setting.

- site2/docs/io-kafka-source.md
- site2/website/versioned_docs/version-2.10.0/io-kafka-source.md
- site2/website/versioned_docs/version-2.9.2/io-kafka-source.md
The Kafka source connector configs are updated. Therefore, update docs accordingly.
- Update Kafka source connector docs.
- Related releases:
- latest
- 2.10.0
- 2.9.2
- [ x ] `doc` 
> [Improve][Doc]Update Kafka source connector docs

- site2/docs/getting-started-docker.md
- site2/website/versioned_docs/version-2.10.0/getting-started-docker.md
- site2/website/versioned_docs/version-2.3.1/getting-started-docker.md
- site2/website/versioned_docs/version-2.3.2/getting-started-docker.md
- site2/website/versioned_docs/version-2.5.0/getting-started-docker.md
- site2/website/versioned_docs/version-2.5.1/standalone-docker.md
- site2/website/versioned_docs/version-2.6.0/getting-started-docker.md
- site2/website/versioned_docs/version-2.6.1/getting-started-docker.md
- site2/website/versioned_docs/version-2.6.2/getting-started-docker.md
- site2/website/versioned_docs/version-2.6.3/getting-started-docker.md
- site2/website/versioned_docs/version-2.6.4/getting-started-docker.md
- site2/website/versioned_docs/version-2.7.0/getting-started-docker.md
- site2/website/versioned_docs/version-2.7.1/getting-started-docker.md
- site2/website/versioned_docs/version-2.7.2/getting-started-docker.md
- site2/website/versioned_docs/version-2.7.3/getting-started-docker.md
- site2/website/versioned_docs/version-2.7.4/getting-started-docker.md
- site2/website/versioned_docs/version-2.8.0/getting-started-docker.md
- site2/website/versioned_docs/version-2.8.1/getting-started-docker.md
- site2/website/versioned_docs/version-2.8.2/getting-started-docker.md
- site2/website/versioned_docs/version-2.8.3/getting-started-docker.md
- site2/website/versioned_docs/version-2.9.0/getting-started-docker.md
- site2/website/versioned_docs/version-2.9.1/getting-started-docker.md
- site2/website/versioned_docs/version-2.9.2/getting-started-docker.md
> [fix][doc] Fix incorrect layout issues

- site2/website/data/team.js
> [improve][doc] Update committers page

- site2/website/blog/2022-05-11-apache-pulsar-community-welcomes-500th-contributor.md
- site2/website/blog/2022-05-11-whats-new-in-pulsar-210.md
Add blog: whats new in pulsar 2.10
> [feature][website] add blog - whats new in pulsar 2.10

- site2/docs/concepts-messaging.md
- site2/website/versioned_docs/version-2.10.0/getting-started-standalone.md
* Managed Ledger is explained after it is mentioned in Messaging and Concepts documentation hence the needed hyperlink
* Running Pulsar standalone on M1 introduces challenges due to new architecture not yet supported. The docs now explain how to overcome that
> [improve][doc] Clarify documentation regarding M1 JDK and Managed Ledger

- site2/docs/io-rabbitmq-sink.md
1.From the description and examples, we can see prefetchGlobal is wrong and that is routingKey
2.Yaml format is incorrect.
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
- *Added integration tests …
> [improve][doc] fix error param and config in io-rabbitmq-sink.md

- site2/docs/develop-plugin.md
- site2/website/versioned_docs/version-2.10.0/develop-plugin.md
https://pulsar.apache.org/docs/next/develop-plugin 
Describe a NAR file.
Create an **entry_filter.yaml** file in the resources/META-INF/services directory to describe a NAR file. 
the `entry_filter.yaml` should `entry_filter.yml` 
```java
static final String ENTRY_FILTER_DEFINITION_FILE = "entry_filter.yml";
```
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java#L39
addition, i write a plugin for the broker side msg filter by this doc, thanks @315157973 
https://github.com/yangl/pulsar-msg-filter-plugin
fix the error description `entry_filter.yaml` to `entry_filter.yml` .
*(or)*
This …
> [doc] modify the `entry_filter.yaml` Nar filename to `entry_filter.yml`.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/EntryFilterProviderTest.java
- site2/docs/develop-plugin.md
> [improve][broker] Add .yaml suffix support for broker filter config file

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
Make `getTenants` /  `getTenantAdmin` / `createTenant` / `updateTenant` / `deleteTenant` methods in TenantsBase to pure async.
> [improve][broker] Make some methods in TenantsBase async.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSubscriptionTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicsTest.java
To fix https://issues.apache.org/jira/browse/PULSAR-20
> [improve][admin] add topic name and sub name for NotFound error message

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ResourceQuotasBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/ResourceQuotas.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/ResourceQuotas.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/LedgerOffloaderMetricsTest.java
Make `getDefaultResourceQuota` /  `getNamespaceBundleResourceQuota` / `setNamespaceBundleResourceQuota` / `removeNamespaceBundleResourceQuota` methods in ResourceQuotasBase to pure async.
> Make some methods in ResourceQuotasBase async.

- site2/docs/concepts-overview.md
- site2/website/versioned_docs/version-2.1.1-incubating/concepts-overview.md
- site2/website/versioned_docs/version-2.10.0/concepts-overview.md
- site2/website/versioned_docs/version-2.2.0/concepts-overview.md
- site2/website/versioned_docs/version-2.3.2/concepts-overview.md
- site2/website/versioned_docs/version-2.4.0/concepts-overview.md
- site2/website/versioned_docs/version-2.4.1/concepts-overview.md
- site2/website/versioned_docs/version-2.4.2/concepts-overview.md
- site2/website/versioned_docs/version-2.5.0/concepts-overview.md
- site2/website/versioned_docs/version-2.5.1/concepts-overview.md
- site2/website/versioned_docs/version-2.5.2/concepts-overview.md
- site2/website/versioned_docs/version-2.6.0/concepts-overview.md
- site2/website/versioned_docs/version-2.6.1/concepts-overview.md
- site2/website/versioned_docs/version-2.6.2/concepts-overview.md
- site2/website/versioned_docs/version-2.6.3/concepts-overview.md
- site2/website/versioned_docs/version-2.6.4/concepts-overview.md
- site2/website/versioned_docs/version-2.7.0/concepts-overview.md
- site2/website/versioned_docs/version-2.7.1/concepts-overview.md
- site2/website/versioned_docs/version-2.7.2/concepts-overview.md
- site2/website/versioned_docs/version-2.7.3/concepts-overview.md
- site2/website/versioned_docs/version-2.7.4/concepts-overview.md
- site2/website/versioned_docs/version-2.8.0/concepts-overview.md
- site2/website/versioned_docs/version-2.8.1/concepts-overview.md
- site2/website/versioned_docs/version-2.8.2/concepts-overview.md
- site2/website/versioned_docs/version-2.8.3/concepts-overview.md
- site2/website/versioned_docs/version-2.9.0/concepts-overview.md
- site2/website/versioned_docs/version-2.9.1/concepts-overview.md
- site2/website/versioned_docs/version-2.9.2/concepts-overview.md
The original sentence contains a comma splice. In writing, we usually do not connect two independent clauses with a comma.
> [Improve][Doc] Fix comma splice

- site2/docs/concepts-architecture-overview.md
* Added link to load balancing explanation 
* Fixed IntellIK warnings on markdown of that file
> [fix][doc] Add link for load balancing

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Subscription.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsController.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSubscriptionTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
- pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBase.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ResetCursorData.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/CLITest.java
This is the port of #15488 to branch-2.10
cherry picked from commit e2fa1898f7e9a38b1743b2abf21c87eafe126ee2
I am porting to 2.10 because PIP-105 is missing this feature in order to be used.
There is a little API addition, but it is 100% backward compatible.
> [enh] Issue 15455: Pulsar Admin: create subscripion with Properties (PIP-105) (#15503)

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
Cherry-pick #13090
- Delete `GET_REPLICATED_SUBSCRIPTION_STATUS` in `allowTopicOperationAsync`. because the current version is not supported.
> [branch-2.9][Authorization] Optimize the logic of allowing namespace operation.

- site2/docs/concepts-architecture-overview.md
- site2/website/start.sh
> [fix][website]fix: assets path

- pulsar-sql/presto-distribution/pom.xml
I got an error when cherry-pick PR to branch-2.9, It looks like forget to delete `<guice.version>`  when cherry-pick PR #14300.
> [branch-2.9][fix][broker] Fix `<guice.version>` license issue.

- bin/pulsar-daemon
> [branch-2.9][fix][deploy]: fix the pid occupied check when use pulsar-daemon start or stop process.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebExecutorStats.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/web/WebServiceTest.java
- pulsar-sql/presto-distribution/pom.xml
> [branch-2.9][enh][monitor]: add metrics for pulsar web service thread pool

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImpl.java
> [branch-2.9][improve][client] Avoid timer task run before previous subscribe complete.

- site2/docs/schema-understand.md
- site2/website/versioned_docs/version-2.10.0/schema-understand.md
- site2/website/versioned_docs/version-2.4.1/schema-understand.md
- site2/website/versioned_docs/version-2.4.2/schema-understand.md
- site2/website/versioned_docs/version-2.5.0/schema-understand.md
- site2/website/versioned_docs/version-2.5.1/schema-understand.md
- site2/website/versioned_docs/version-2.5.2/schema-understand.md
- site2/website/versioned_docs/version-2.6.0/schema-understand.md
- site2/website/versioned_docs/version-2.6.1/schema-understand.md
- site2/website/versioned_docs/version-2.6.2/schema-understand.md
- site2/website/versioned_docs/version-2.6.3/schema-understand.md
- site2/website/versioned_docs/version-2.6.4/schema-understand.md
- site2/website/versioned_docs/version-2.7.0/schema-understand.md
- site2/website/versioned_docs/version-2.7.1/schema-understand.md
- site2/website/versioned_docs/version-2.7.2/schema-understand.md
- site2/website/versioned_docs/version-2.7.3/schema-understand.md
- site2/website/versioned_docs/version-2.7.4/schema-understand.md
- site2/website/versioned_docs/version-2.8.0/schema-understand.md
- site2/website/versioned_docs/version-2.8.1/schema-understand.md
- site2/website/versioned_docs/version-2.8.2/schema-understand.md
- site2/website/versioned_docs/version-2.8.3/schema-understand.md
- site2/website/versioned_docs/version-2.9.0/schema-understand.md
- site2/website/versioned_docs/version-2.9.1/schema-understand.md
- site2/website/versioned_docs/version-2.9.2/schema-understand.md
* The document states that <code>**You** application reads the messages</code>.  Updated to state <code>**Your** application reads the messages</code>
> [fix][schema-understand][docs] Updated example section

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #15732
Rename doc label.
- `no-need-doc` -> `doc-not-needed`
- `doc-added` -> `doc-complete`
> Rename doc label in PR template

- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionProduceTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTestBase.java
Fix flaky test `testDeleteNamespaceBeforeCommit`.
> [branch-2.9][broker][test] Fix flaky test `testDeleteNamespaceBeforeCommit`

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/MemoryLimitController.java
- under load, it's possible that the trigger immediately releases memory and causes the current
usage to go under the limit while the trigger is executing. If a memory reservation call that exceed the limit occurs while the trigger is still executing, it would cause the trigger to be run even though the previous one is still executing. This scenario should be prevented.
- the trigger was introduced in #15216
- prevent the trigger being run concurrently
> [Broker] Prevent the trigger running concurrently in the memory limit controller

- site2/docs/reference-cli-tools.md
Fixed a 404 link in Pulsar CLI Tools documenation
> [fix][doc] fixed bad link in Pulsar CLI Tools

- pulsar-client-cpp/python/setup.py
- pulsar-functions/instance/src/scripts/run_python_instance_tests.sh
- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/CoordinationServiceImpl.java
- site2/docs/admin-api-brokers.md
- site2/docs/admin-api-clusters.md
- site2/docs/admin-api-functions.md
- site2/docs/admin-api-namespaces.md
- site2/docs/admin-api-overview.md
- site2/docs/admin-api-packages.md
- site2/docs/admin-api-permissions.md
- site2/docs/admin-api-tenants.md
- site2/docs/admin-api-topics.md
- site2/docs/administration-geo.md
- site2/docs/administration-isolation.md
- site2/docs/client-libraries-java.md
- site2/docs/concepts-messaging.md
- site2/docs/concepts-proxy-sni-routing.md
- site2/docs/cookbooks-retention-expiry.md
- site2/docs/functions-develop.md
- site2/docs/io-overview.md
- site2/docs/io-use.md
- site2/docs/schema-manage.md
- site2/docs/security-encryption.md
- site2/docs/security-extending.md
- site2/docs/security-jwt.md
- site2/docs/security-overview.md
Fixes #15774
CoordinationServiceImpl.close can hang. See #15774.
- add a fixed timeout of 10 seconds
- also close the scheduled executor
> [Broker] Add timeout to closing CoordinationServiceImpl

- pom.xml
- pulsar-io/batch-data-generator/pom.xml
- pulsar-io/batch-discovery-triggerers/pom.xml
- pulsar-io/canal/pom.xml
Bump spring version from 5.3.19 to 5.3.20 to solve CVE-2016-1000027
> Bump spring version to 5.3.20 to solve CVE-2022-22970

- site2/website/api.sh
Build the .md files for Pulsar admin CLI documentation. In this example, you only need to run this command because the modified content is part of Pulsar admin CLI documentation.
```
site2/website/api.sh admin
```
Build the .md files for Pulsar client CLI documentation.
```
site2/website/api.sh client
```
Build the .md files for Pulsar perf CLI documentation.
```
site2/website/api.sh perf
```
Build the .md files for Pulsar pulsar CLI documentation.
```
site2/website/api.sh pulsar
```
Build the .md file for all CLI documentation 
```
site2/website/api.sh
```
> [feature][website] api generate script

- site2/website/api.sh
- site2/website/start.sh
> [feature][website]update preview scripts

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaTest.java
Make `getSchema` /  `deleteSchema` / `postSchema` / `getVersionBySchema` / `testCompatibility` methods in SchemasResourceBase to pure async.
> [improve][broker] Make some methods in SchemasResourceBase async.

- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
Add cli cmd for subscription level dispatch-rate-limiter
Add "--subscription" for `set/get/delete-subscription-dispatch-rate`.
- See PulsarAdminToolTest.java
- The admin cli options: (**yes**)
- [] `doc-required` 
> [feature][client] Add cli cmd for subscription level dispatch-rate-limiter

- site2/docs/io-use.md
- site2/website/versioned_docs/version-2.10.0/io-use.md
- site2/website/versioned_docs/version-2.5.1/io-use.md
- site2/website/versioned_docs/version-2.5.2/io-use.md
- site2/website/versioned_docs/version-2.6.0/io-use.md
- site2/website/versioned_docs/version-2.6.1/io-use.md
- site2/website/versioned_docs/version-2.6.2/io-use.md
- site2/website/versioned_docs/version-2.6.3/io-use.md
- site2/website/versioned_docs/version-2.6.4/io-use.md
- site2/website/versioned_docs/version-2.7.0/io-use.md
- site2/website/versioned_docs/version-2.7.1/io-use.md
- site2/website/versioned_docs/version-2.7.2/io-use.md
- site2/website/versioned_docs/version-2.7.3/io-use.md
- site2/website/versioned_docs/version-2.7.4/io-use.md
- site2/website/versioned_docs/version-2.8.0/io-use.md
- site2/website/versioned_docs/version-2.8.1/io-use.md
- site2/website/versioned_docs/version-2.8.2/io-use.md
- site2/website/versioned_docs/version-2.8.3/io-use.md
- site2/website/versioned_docs/version-2.9.0/io-use.md
- site2/website/versioned_docs/version-2.9.1/io-use.md
- site2/website/versioned_docs/version-2.9.2/io-use.md
* Removed extra 'f' from end of line
* Removed extra 'f' from end of line
> [fix][io-use][docs] Removed extra 'f'

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
Fixes #15920
Follow up on #14538. The original intention of the solution introduced in #14538 was to ignore exceptions when closing producers and consumer fail or timeout. The solution contained a bug so that the timeout exception get propagated to the caller.
- don't return timeout exception to caller
> [Client] Continue shutdown of client when closing producers and consumers timeout

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/LedgerOffloaderStatsImpl.java
There was already had
``` java
LoadingCache<String, TopicName> cache = CacheBuilder.newBuilder().maximumSize(100000)
.expireAfterAccess(30, TimeUnit.MINUTES).build(new CacheLoader<String, TopicName>() {
@Override
public TopicName load(String name) throws Exception {
return new TopicName(name);
}
});
```
in `TopicName`, so that we don't need `topic -> namespace cache` in `LedgerOffloaderStatsImpl` any more.
> [fix][broker] remove topic -> namespace cache of LedgerOffloaderStatsImpl

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
When I use the Admin API to create a tenant, if the tenants are limited and I already have the max # of tenants, I get an error "412 Reached the max tenants [n] restriction." This is good, but if I'm trying to create a tenant that already exists, I get the same error. But, creating a tenant that already exists should be a no-op and would not actually push me over my limit.
"409 Already exists" is a softer error than "412 Reached the max restriction." It might be a little cleaner if Pulsar checked if the tenant exists first, and returned that error, before throwing the 412 exception. Otherwise the responsibility to fetch the tenants and check if it already exists must be done by the user.
*Explain here the context, and why you're making that change. What is the problem you're trying to …
> [fix] [admin] fix reach max tenants error if the tenant already exists

- site2/docs/sql-deployment-configurations.md
Add docs for the new feature implemented in #15571 
1. Add configs to enable and configure Pulsar auth for Pulsar SQL.
2. Add headings for existing content with minor corrections.
> [feature][doc] Add Pulsar Auth support for Pulsar SQL

- site2/docs/develop-binary-protocol.md
- site2/docs/developing-binary-protocol.md
* Fixed documentation of basic command structure to match the code
> [fix][doc] Fixed binary protocol naming and descriptions

- pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
PulsarWebResource#checkLocalOrGetPeerReplicationCluster is called by several methods, like `lookup`, `getPartitionedTopicMetadata`, `validateGlobalNamespaceOwnership`.  
These methods are all asynchronous and are called frequently in the system. However, I found that getOwnerFromPeerClusterList inside this method is indeed called synchronously, so I think this method needs to be changed to asynchronous.
> [improve][broker] Make PulsarWebResource#getOwnerFromPeerClusterList async.

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/StructSchema.java
> [cleanup][schema] Remove useless code of class StructSchema

- site2/docs/security-policy-and-supported-versions.md
- site2/website/versioned_docs/version-2.10.0/security-policy-and-supported-versions.md
Add version 2.10.x to the "Supported Versions Page".
> [doc] Add 2.10.x to supported versions table

- site2/docs/client-libraries-go.md
- site2/website/versioned_docs/version-2.1.1-incubating/client-libraries-go.md
- site2/website/versioned_docs/version-2.10.0/client-libraries-go.md
- site2/website/versioned_docs/version-2.3.2/client-libraries-go.md
- site2/website/versioned_docs/version-2.4.1/client-libraries-go.md
- site2/website/versioned_docs/version-2.4.2/client-libraries-go.md
- site2/website/versioned_docs/version-2.8.0/client-libraries-go.md
- site2/website/versioned_docs/version-2.8.1/client-libraries-go.md
- site2/website/versioned_docs/version-2.8.2/client-libraries-go.md
- site2/website/versioned_docs/version-2.8.3/client-libraries-go.md
- site2/website/versioned_docs/version-2.9.0/client-libraries-go.md
- site2/website/versioned_docs/version-2.9.1/client-libraries-go.md
- site2/website/versioned_docs/version-2.9.2/client-libraries-go.md
Fixes #<xyz>
[client-libraries-go](https://pulsar.apache.org/docs/2.9.0/client-libraries-go/#create-a-client) has a client sample code missing the golang format which looks like 
Add missing go format on client sample code
*(or)*
*(or)*
*(example:)*
- …
> fix(docs): add missing go format on client sample code

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
> [fix][admin] Fix typo in validation message

- .github/workflows/ci-documentbot.yml
This is a follow up change to https://github.com/apache/pulsar/pull/16027
Wrong action repository path.
Update action repository path
*(or)*
*(or)*
*(example:)*
- The default values of configurations: (yes / …
> [fix][workflow] Update action repository path

- README.md
Original text `[README](site2/README.md).` is invalid. Replace it with some continuously updated resources.
> [feat][workflow] add links of doc contribution guides to readme

- site2/docs/getting-started-helm.md
- site2/website/versioned_docs/version-2.10.0/getting-started-helm.md
- site2/website/versioned_docs/version-2.5.1/getting-started-helm.md
- site2/website/versioned_docs/version-2.5.2/getting-started-helm.md
- site2/website/versioned_docs/version-2.6.0/getting-started-helm.md
- site2/website/versioned_docs/version-2.6.1/getting-started-helm.md
- site2/website/versioned_docs/version-2.6.2/getting-started-helm.md
- site2/website/versioned_docs/version-2.6.3/getting-started-helm.md
- site2/website/versioned_docs/version-2.6.4/getting-started-helm.md
- site2/website/versioned_docs/version-2.7.0/getting-started-helm.md
- site2/website/versioned_docs/version-2.7.1/getting-started-helm.md
- site2/website/versioned_docs/version-2.7.2/getting-started-helm.md
- site2/website/versioned_docs/version-2.7.3/getting-started-helm.md
- site2/website/versioned_docs/version-2.7.4/getting-started-helm.md
- site2/website/versioned_docs/version-2.8.0/getting-started-helm.md
- site2/website/versioned_docs/version-2.8.1/getting-started-helm.md
- site2/website/versioned_docs/version-2.8.2/getting-started-helm.md
- site2/website/versioned_docs/version-2.8.3/getting-started-helm.md
- site2/website/versioned_docs/version-2.9.0/getting-started-helm.md
- site2/website/versioned_docs/version-2.9.1/getting-started-helm.md
- site2/website/versioned_docs/version-2.9.2/getting-started-helm.md
Add more explanation about how to use the script to create relevant secrets for Pulsar if using the Helm chart to install it.
> [Improve][Doc] Add explanation about the Helm release script

- pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/functions/FunctionConfig.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
Add option `function-type` to admin CLI for Functions.
This option can be used as an alternative to the `--jar` option to create a built-in Function.
This is the equivalent of the `--sink-type`/`--source-type` options of connectors for Functions
This change is already covered by existing tests, such as `testCreateFunctionWithBuiltinNar `
yes
yes. Adds a `--function-type` option to admin create function command
- Anything that affects deployment: (yes / no / …
> [improve][admin] Add option function-type to admin CLI for Functions

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
Fix compile issue caused by cherry-pick 422588782146bc60721f532f8a4f7c2e1a91f1f2.
- Add missing import.
> [branch-2.9] Fix compile issue by cherry-pick

- site2/docs/getting-started-docker.md
- site2/website/versioned_docs/version-2.10.0/getting-started-docker.md
1. Add docs for how to change Pulsar configs in Docker. --- fix this issue #15972 
2. Minor fixes in the Get Started topic.
> [improve][doc] Add docs for how to change Pulsar configs in Docker 

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java
fix [PR.15674](https://github.com/apache/pulsar/pull/15674), there was a incorrect API usage in it, need to fix.
fix issue
> [fix][broker][monitoring] fix message ack rate

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/BaseResources.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokerStatsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/BrokerInterceptor.java
- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BaseResource.java
> [typo] Fix some typos

- pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java
- pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Function.java
- pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/StateStore.java
- pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/WindowContext.java
> [cleanup][functions] Fix some javadoc issues

- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/go/PulsarFunctionsGoProcessTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/go/PulsarFunctionsGoThreadTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarFunctionsJavaProcessTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarFunctionsJavaTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarFunctionsJavaThreadTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarWorkerRebalanceDrainProcessTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarWorkerRebalanceDrainThreadTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/python/PulsarFunctionsPythonProcessTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/python/PulsarFunctionsPythonThreadTest.java
> [cleanup][functions] Realign Functions integration test classes

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
> [improve][broker][PIP-149]make internalPeekNthMessage method async

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LinuxBrokerHostUsageImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadReportNetworkLimitTest.java
Apply fix  #15304 to branch-2.10
> [fix][branch-2.10] Fix wrong unit of NIC speed on linux

- site2/docs/helm-upgrade.md
- site2/website/versioned_docs/version-2.10.0/helm-upgrade.md
- site2/website/versioned_docs/version-2.5.1/helm-upgrade.md
- site2/website/versioned_docs/version-2.5.2/helm-upgrade.md
- site2/website/versioned_docs/version-2.6.0/helm-upgrade.md
- site2/website/versioned_docs/version-2.6.1/helm-upgrade.md
- site2/website/versioned_docs/version-2.6.2/helm-upgrade.md
- site2/website/versioned_docs/version-2.6.3/helm-upgrade.md
- site2/website/versioned_docs/version-2.6.4/helm-upgrade.md
- site2/website/versioned_docs/version-2.7.0/helm-upgrade.md
- site2/website/versioned_docs/version-2.7.1/helm-upgrade.md
- site2/website/versioned_docs/version-2.7.2/helm-upgrade.md
- site2/website/versioned_docs/version-2.7.3/helm-upgrade.md
- site2/website/versioned_docs/version-2.7.4/helm-upgrade.md
- site2/website/versioned_docs/version-2.8.0/helm-upgrade.md
- site2/website/versioned_docs/version-2.8.1/helm-upgrade.md
- site2/website/versioned_docs/version-2.8.2/helm-upgrade.md
- site2/website/versioned_docs/version-2.8.3/helm-upgrade.md
- site2/website/versioned_docs/version-2.9.0/helm-upgrade.md
- site2/website/versioned_docs/version-2.9.1/helm-upgrade.md
- site2/website/versioned_docs/version-2.9.2/helm-upgrade.md
The original note is truncated. The sentence "pass this file through..." should be included in the note.
This is a preview of my pr change:
> [fix][doc] Fix truncated notes

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
> [improve][broker][PIP-149]make getBacklog method async

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
> [improve][broker][PIP-149]make examineMessage method async

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
> [improve][broker][PIP-149]make deleteTopic method async

- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
Fixes #13617
Master Issue: #13617
See issue #13617
- Add explanations for topic retention policy.
> [Doc][Cli] Add explanations for topic retention policy.

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-broker/pom.xml
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentQueueE2ETest.java
- pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/sink/HbaseAbstractSink.java
- pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/sink/HbaseGenericRecordSink.java
- pulsar-io/hdfs2/pom.xml
- pulsar-io/hdfs2/src/main/java/org/apache/pulsar/io/hdfs2/sink/HdfsSyncThread.java
- pulsar-io/hdfs3/pom.xml
- pulsar-io/hdfs3/src/main/java/org/apache/pulsar/io/hdfs3/sink/HdfsSyncThread.java
- pulsar-io/influxdb/pom.xml
- pulsar-io/influxdb/src/main/java/org/apache/pulsar/io/influxdb/BatchSink.java
- pulsar-io/nsq/pom.xml
- pulsar-io/nsq/src/main/java/org/apache/pulsar/io/nsq/NSQSourceConfig.java
- pulsar-io/redis/pom.xml
- pulsar-io/redis/src/main/java/org/apache/pulsar/io/redis/sink/RedisSink.java
- pulsar-io/solr/pom.xml
- pulsar-io/twitter/pom.xml
- pulsar-io/twitter/src/main/java/org/apache/pulsar/io/twitter/TwitterFireHose.java
- pulsar-io/twitter/src/main/java/org/apache/pulsar/io/twitter/TwitterFireHoseConfig.java
Fixes #16208
commons-collections 3 is too old.
**- Dependencies (does it add or upgrade a dependency): (yes )**
> [improve][broker][pulsar-io] upgrade commons collections to 4.4

- .asf.yaml
> [feat][workflow] Enable required status check of docbot label job

- README.md
Fixes #15958
Please see https://github.com/apache/pulsar/issues/15538#issuecomment-1126064195 for more info.
Add badges for README. Also formatted README.
> [feature][doc] Add badges for README

- README.md
Add links for badges created in #16233
Please see https://github.com/apache/pulsar/pull/16233#issuecomment-1169341660 for more info.
Add links for badges in README.
> [feature][doc] Add links for badges in README

- .github/workflows/ci-documentbot.yaml
> [improve][workflow] Sync the new docbot to branch-2.10

- buildtools/pom.xml
- pulsar-client-tools/pom.xml
- pulsar-functions/localrun-shaded/pom.xml
We no longer use JUnit, so remove this.
- Remove Junit dependency
> [cleanup][dependency] Remove JUnit

- site2/README.md
> [feat][doc] add Pulsar contribution guide links to readme in site2 repo

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/UnAckedMessageTracker.java
If an exception is thrown in the `redeliverUnacknowledgedMessages()` method, the next ack-timeout tasks will not get scheduled and messages will just stay in "unacked" state after that.
> Ensure ack-timeout task gets re-scheduled when there are exception in the final stage

- pulsar-zookeeper-utils/src/test/java/org/apache/pulsar/zookeeper/ZkIsolatedBookieEnsemblePlacementPolicyTest.java
Fix cherry-pick issue.
`IsolatedBookieEnsemblePlacementPolicy not found ` commit: c3fd77de35ac3eda3cf0a5093a31f24f035cdfd7
> [branch-2.9] Fix cherry-pick issues.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
- pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
> [Branch 2.9] Fix compaction subscription acknowledge Marker msg issue.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxAuthorizationTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
> [Branch-2.9] Fix passing incorrect authentication data

- pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckReplyCallBack.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
> [Branch-2.9][transaction] Cmd-Subscribe and Cmd-Producer will not succeed even after 100 retries.

- site2/docs/schema-understand.md
- site2/website/versioned_docs/version-2.10.0/schema-understand.md
- site2/website/versioned_docs/version-2.4.1/schema-understand.md
- site2/website/versioned_docs/version-2.4.2/schema-understand.md
- site2/website/versioned_docs/version-2.5.0/schema-understand.md
- site2/website/versioned_docs/version-2.5.1/schema-understand.md
- site2/website/versioned_docs/version-2.5.2/schema-understand.md
- site2/website/versioned_docs/version-2.6.0/schema-understand.md
- site2/website/versioned_docs/version-2.6.1/schema-understand.md
- site2/website/versioned_docs/version-2.6.2/schema-understand.md
- site2/website/versioned_docs/version-2.6.3/schema-understand.md
- site2/website/versioned_docs/version-2.6.4/schema-understand.md
- site2/website/versioned_docs/version-2.7.0/schema-understand.md
- site2/website/versioned_docs/version-2.7.1/schema-understand.md
- site2/website/versioned_docs/version-2.7.2/schema-understand.md
- site2/website/versioned_docs/version-2.7.3/schema-understand.md
- site2/website/versioned_docs/version-2.7.4/schema-understand.md
- site2/website/versioned_docs/version-2.8.0/schema-understand.md
- site2/website/versioned_docs/version-2.8.1/schema-understand.md
- site2/website/versioned_docs/version-2.8.2/schema-understand.md
- site2/website/versioned_docs/version-2.8.3/schema-understand.md
- site2/website/versioned_docs/version-2.9.0/schema-understand.md
- site2/website/versioned_docs/version-2.9.1/schema-understand.md
- site2/website/versioned_docs/version-2.9.2/schema-understand.md
* The producer side section states <code>...  Pulsar **extract** schema definition from the POJO class and **construct** the...</code>.
* Updated to <code>...Pulsar **extracts** schema definition from the POJO class and **constructs** the ...</code>
- The public API: no  …
> [fix][schema-understand][docs] Minor correction in producer side step 1

- site2/website/static/swagger/2.10.1/swagger.json
- site2/website/static/swagger/2.10.1/swaggerfunctions.json
- site2/website/static/swagger/2.10.1/swaggerpackages.json
- site2/website/static/swagger/2.10.1/swaggersink.json
- site2/website/static/swagger/2.10.1/swaggersource.json
> Generate swagger files for 2.10.1 release

- .gitignore
- README.md
- I think the Intellij should be changed to IntelliJ IDEA. For details, please refer to the official website https://www.jetbrains.com/idea/ and https://en.wikipedia.org/wiki/IntelliJ_IDEA.
- Modify Intellij to IntelliJ IDEA.
*(or)*
*(or)*
*(example:)*
- The public API: …
> [Fix][docs] Fix the Intellij key nouns.

- site2/docs/reference-metrics.md
doc for https://github.com/apache/pulsar/pull/15674
> [doc][broker][monitoring] add message_ack_rate metric doc

- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
Fixes #16382 
Try to fix the flaky test related to PersistentTopicTest.setup.
> [fix][flaky-test] Try to fix flaky test related to PersistentTopicTest.setup

- pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java
- pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicyTest.java
Fixes #16272
Fix the local police IsolationGroups permanent cover the `defaultIsolationGroups`, which will cause even we rollback the local police to empty,  the `defaultIsolationGroups` always use the latest local police IsolationGroups setting and  is not use the setting in broker.conf as default.
The `defaultIsolationGroups` be covered point.
https://github.com/apache/pulsar/blob/0eed84203b23e325ac15d7dc50e1ed6dbdf4fa2a/pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java#L141
1.  fix the `defaultIsolationGroups` be covered point 
2. merge the `newEnsemble` and `replaceBookie` method duplication code to `getBlacklistedBookies()` ,to avoid change only cover one method in the future. 
3. add some unit test.
`
> [fix][broker] fix the local police IsolationGroups permanent cover the defaultIsolationGroups

- site2/docs/reference-configuration.md
- site2/website/versioned_docs/version-2.10.1/reference-configuration.md
Fix table formatting and copy docs to 2.10.1.
> Fix Documentation for Client Pass Through Configuration

- site2/docs/concepts-messaging.md
This change is documented here: https://github.com/apache/pulsar/issues/16203
I also made a minor spelling correction on that page.
> [doc-complete] #16203 Added doc to fix issue with missing client instructions for batch index acknowledgment

- tests/pulsar-client-admin-shade-test/src/test/java/org/apache/pulsar/tests/integration/SimpleProducerConsumerTest.java
- tests/pulsar-client-all-shade-test/src/test/java/org/apache/pulsar/tests/integration/SimpleProducerConsumerTest.java
- tests/pulsar-client-shade-test/src/test/java/org/apache/pulsar/tests/integration/SimpleProducerConsumerTest.java
Reduce build noise by fixing compiler warnings.
Fixed various compiler warnings in the pulsar-client-*shade-test modules.
> [cleanup][client-tests] Fixed various compiler warnings

- tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/AdminMultiHostTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/CLITest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/SchemaUpdateStrategyTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ChaosContainer.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/PulsarContainer.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarStateTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/PulsarGenericObjectSinkTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/PulsarIOTestBase.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/PulsarIOTestRunner.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearchSinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KafkaSinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/SinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/AvroKafkaSourceTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/SourceTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMongoDbSourceTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMySqlSourceTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/PulsarIODebeziumSourceRunner.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestBaseOffload.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/StockProtoMessage.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/TestBasicPresto.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/TestPrestoQueryTieredStorage.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/TestPulsarSQLBase.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/semantics/SemanticsTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarClusterSpec.java
Reduce build noise by fixing compiler warnings.
Fixed various compiler warnings in the integration test modules.
> [cleanup][integration] Fixed various compiler warnings

- site2/docs/admin-api-brokers.md
pulsar documentation page [here](https://pulsar.apache.org/docs/next/admin-api-brokers#list-active-brokers) has a style mistake:
Change markdown content like other tab item.
> [fix][doc] API tab style mistake

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
> [improve][broker][PIP-149]make getMaxConsumersPerSubscription method async in Namespaces

- site2/website/blog/2022-07-12-Apache-Pulsar-2-10-1.md
Add 2.10.1 release blog.
Preview looks good.
> [feature][blog] Add 2.10.1 release blog

- site2/docs/administration-metadata-store.md
- site2/docs/reference-configuration.md
- site2/website/sidebars.json
Fix issue #15838 
1. Add a new topic for configuring metadata store
2. Minor fixes.
> [feature][doc] Add docs for how to configure metadata store

- site2/website/versioned_docs/version-2.10.0/performance-pulsar-perf.md
- site2/website/versioned_docs/version-2.10.1/performance-pulsar-perf.md
> [fix][doc] Fix the documentation of performance-pulsar-perf for 2.10.x

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Fixes https://github.com/apache/pulsar/issues/14882
The subscription `__compaction` may fail with error `Subscription is fenced`. if that happens the compaction round will fail for that topic but it will recover on the next one. When this error happens, the stacktrace is printed in the broker logs even if it's not a real error and it will recover automatically.
* Only print exception message to WARN level if subscription is __compaction and the error is `SubscriptionFencedException`
> [fix][compaction] Hide stacktrace if compaction subscription is fenced

- site2/docs/getting-started-standalone.md
In the getting started guide:
`brew install sdkman` doesn't find any matching formulae. It seems that sdkman is not available through homebrew anymore.
Installing through SDKMan website was quick & straightforward for me. This is why I suggest removing homebrew as an installation method.
Stop suggesting homebrew as an installation method.
This change only impacts documentation.
- Anything that affects deployment: (yes / **no** / …
> [improve][doc] Getting started guide: remove homebrew as possible installation method of sdkman

- site2/docs/schema-manage.md
Fixes #16548
Provide a correct JSON schema example
Changed one line to correct three problems reported.
This change is a trivial  documentation cleanup without any test coverage.
> [Doc] Schema-manage upload update example 1

- pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandaloneStarter.java
- pulsar-broker/src/main/java/org/apache/pulsar/PulsarVersionStarter.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/StandaloneTest.java
- pulsar-metadata/src/test/java/org/apache/pulsar/metadata/TestZKServer.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketServiceStarter.java
To keep the code style consistency. Referencing the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s4.8.3.2-array-declarations)
> The square brackets form a part of the type, not the variable
Change `Type name[]` to `Type[] name`. e.g, Change `String arg[]` to `String[] arg`
> [refactor] Replace C-style array declaration with Java-style

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/api/MessageDispatchThrottlingTest.java
*  Cleanup unused code in `DispatchRateLimiter`
* Removing `DispatchRateLimiter#getPoliciesDispatchRate` and the UT about it
> [cleanup][broker]Cleanup Unused code in DispatchRateLimter

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
Master Issue: https://github.com/apache/pulsar/issues/14365
* See https://github.com/apache/pulsar/issues/14365
* Make `internalTruncateTopic` pure async
> [improve][broker][PIP-149]Make TruncateTopic pure async

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
Make the below method async:
`setAutoSubscriptionCreation` / `getAutoSubscriptionCreation` / `removeAutoSubscriptionCreation`
> [improve][broker] Make AutoSubscriptionCreation async

- site2/docs/schema-manage.md
Fixes [16585](https://github.com/apache/pulsar/issues/16585)
To provide a valid schema example
Changes two schema attributes to fix the example
> [Doc] schema-manage example 1 fix

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
Correct log in `NamespacesBase`#`internalClearProperties` method.
> Correct log in NamespacesBase#internalClearProperties

- pom.xml
- pulsar-io/canal/pom.xml
- src/owasp-dependency-check-false-positives.xml
- src/owasp-dependency-check-suppressions.xml
Fix some OWASP dependency problems, the details as below:
- #16148 
- #15829
- #15864
- #14910
- Fix some OWASP dependency problems
*(or)*
*(or)*
*(example:)*
> [Branch 2.10] Fix some OWASP dependency problems.

- pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Fixes #16608
Add key if exists to deadLetter message
org.apache.pulsar.client.api.DeadLetterTopicTest#testDeadLetterTopicWithMessageKey
> [improve][client] Add message key if exists to deadLetter messages

- site2/docs/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.10.0/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.10.1/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.0/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.1/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.2/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.3/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.7.4/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.0/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.1/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.2/tiered-storage-filesystem.md
- site2/website/versioned_docs/version-2.8.3/tiered-storage-filesystem.md
* The output states <code>The ledger 696 is **rollovered**.</code>
* Updated to <code>The ledger 696 is **rolled over**.</code>
This PR is documentation update.
> [fix][tiered-storage-filesystem][docs] Updated output

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
* Cleanup sync method `getTopicReference`
* Cleanup sync method `getTopicReference`
> [cleanup][broker]Cleanup sync method getTopicReference

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerCloseTest.java
Fixes #15277
Master Issue: #15277
> [fix][flaky-tests]Fix flaky test ProducerCloseTest.brokerCloseTopicTest.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java
There is a sequence of events that can lead to a deadlock in the key-shared dispatcher.
```
"BookKeeperClientWorker-OrderedExecutor-6-0":
at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.readOperationCompleted(ManagedCursorImpl.java:2843)
- waiting to lock <0x0000000684151218> (a java.util.ArrayDeque)
at org.apache.bookkeeper.mledger.impl.OpReadEntry.checkReadCompletion(OpReadEntry.java:153)
at org.apache.bookkeeper.mledger.impl.OpReadEntry.readEntriesComplete(OpReadEntry.java:87)
at org.apache.bookkeeper.mledger.impl.EntryCacheImpl.asyncReadEntry0(EntryCacheImpl.java:285)
at org.apache.bookkeeper.mledger.impl.EntryCacheImpl.asyncReadEntry(EntryCacheImpl.java:243)
at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncReadEntry(ManagedLedgerImpl.java:1935)
at …
```
> Fixed deadlock in key-shared dispatcher

- site2/website/static/swagger/2.9.3/swagger.json
- site2/website/static/swagger/2.9.3/swaggerfunctions.json
- site2/website/static/swagger/2.9.3/swaggerpackages.json
- site2/website/static/swagger/2.9.3/swaggersink.json
- site2/website/static/swagger/2.9.3/swaggersource.json
Update swagger file for release 2.9.3
> Update swagger file for release 2.9.3

- site2/website/blog/2022-07-15-pulsar-summit-san-francisco.md
Add the Pulsar Summit San Francisco 2022 blog
Some preview images:
> [Blog] [Pulsar Summit] Add pulsar summit san francisco 2022 blog

- pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
Add comments to the deprecated method in the `Topics` interface.
- Add comments to the deprecated method in the `Topics` interface.
> [improve][client] Add deprecated note to Topics interface.

- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java
Fixes #16515 
The receiver queue size is too small. This causes the entry filter to trigger message redelivery more frequently. However, there will be a default interval of 1 second when delivering messages.  This tends to make the whole test take too long, leading to the timeout exception.
* Increase the receiver queue size
* Fix some problems in the test
> [fix][test] Fix testEntryFilterRescheduleMessageDependingOnConsumerSharedSubscription

- site2/docs/reference-configuration.md
- site2/website/versioned_docs/version-2.10.0/reference-configuration.md
- site2/website/versioned_docs/version-2.10.1/reference-configuration.md
Update metadataStoreConfigPath description, link to https://pulsar.apache.org/docs/next/administration-metadata-store/.
> [improve][doc] Update metadataStoreConfigPath description

- site2/docs/functions-cli.md
> [improve][doc] Add doc for function type to functions-cli.md

- pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/ConsumerStatsImpl.java
- site2/docs/reference-metrics.md
> [improve][doc] Add missing doc for metric pulsar_consumer_msg_ack_rate

- pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/CounterBrokerInterceptor.java
#16516 
I haven't reproduced it locally and the logic of the test is clear. Maybe a member variables visibility issue. 
- Add the `volatile` modifier to the variable.
> [fix][flaky-test] BrokerInterceptorTest.testProducerCreation

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
> [improve][broker][PIP-149]make offload police methods async in Namespaces

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
Fix problem caused by cherry-pick #16676 to branch-2.9.
> [branch-2.9] Fix compatible issue.

- pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java
Fixes #16483, #16538
Fix flaky test by try add `alwaysRun`.
> [fix][flaky-test] Fix PulsarFunctionTlsTest.tearDown

- site2/docs/admin-api-overview.md
- site2/docs/administration-pulsar-shell.md
- site2/docs/reference-cli-tools.md
- site2/website/sidebars.json
Master Issue: #16250
Document new Pulsar shell tool
* Added new page on the Administration sidebar "Pulsar shell" with the guide to how to install it and configure
* Added the reference along with other client tools
> [feature][doc] Documentation for Pulsar shell

- pom.xml
> [fix][doc]Update pulsar link

- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/MessageDuplicationTest.java
https://github.com/apache/pulsar/commit/a8694d751578227b33273f2fb2e84f16108ac91b introduced a compile failure.
bug fix.
> [Branch 2.7] Fix compile failure.

- pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
… exception
Fixes #16653
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after broker …
> [fix][client] Fix ReconsumeLater will hang up if retryLetterProducer exception

- site2/website/blog/2022-07-26-pulsar-sessions-in-apachecon-aisa-2022.md
ApacheCon Asia 2022 is just around the corner. There are some sessions related to Apache Pulsar in ApacheCon Asia. Add this blog for awareness among community members.
Some preview images for reference:
> [Blog][ApacheCon Aisa] Add ApacheCon Asia 2022 blog

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
- managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
cherry-pick #14545 to branch 2.7
When the user config the offloader, as the ledger close, it will trigger the ledger to offload. If there are many ledgers that need to offload, but the topic has been unloaded, the offloader will continue to offload. Because the offloader uses the shared executor pool in ManagedLedgerFactoryImpl and when the managed ledger closes, it doesn't cancel the tasks.
```
15:29:59.180 [pulsar-web-41-3] INFO  org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [null] Unloading topic persistent://public/default/UpdateNodeCharts
15:29:59.201 [pulsar-web-41-3] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/UpdateNodeCharts] Closing managed ledger
15:29:59.216 [main-EventThread] INFO …
```
> [branch 2.7] Cancel offload tasks when managed ledger closed

- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Need to use the logger to print logs in the unit test.
* Use logger instead of `System.out`.
> [refactor][test] Use logger to print log

- pulsar-package-management/core/pom.xml
Remove unused gson dependency in pulsar-package-core
remove dependency, no need test
> Remove unused gson dependency in pulsar-package-core

- pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/RetentionPolicies.java
* Fix typo in `RetentionPolicies` comment
* Fix typo in `RetentionPolicies` comment
> [fix][broker]Fix RetentionPolicies comment typo

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationDataHttps.java
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderToken.java
- pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderTokenTest.java
> [improve][authentication][branch-2.8] Support for get token from HTTP params

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyConnectionTest.java
- pulsar-sql/presto-distribution/LICENSE
After cherry-picked some PRs directly to branch 2.7, the CI is broken.
Revert some PRs:
- 10b4e99a815d1c36660c315171f71d1f866a4f74 "[fix][proxy] Fix client service url (#16834)" Causing compile error in unit test.
- 99c93d2f5fe2f72e185d46813383c7f7c984022d "[Build] Use grpc-bom to align grpc library versions (#15234)" Causing compile error as grpc version not updated in this branch.
- 5ad16b623fdf3a2157577694ff4bc7fd06450a9b "upgrade aircompressor to 0.20 (#11790)" causing License check CI failure.
- 32fe228854464504d18de240f719b583cf262042 "[Branch-2.7] Fixed deadlock on metadata cache missing while doing checkReplication (#12484)" causing org.apache.pulsar.broker.service.BrokerBookieIsolationTest#testBookieIsilationWithSecondaryGroup failure.
- Revert changes of …
> [Branch 2.7] Revert some PRs to fix CI for branch 2.7

- pulsar-broker/pom.xml
Patch #16470, Add lookup REST API swagger config.
- Add lookup REST API swagger config.
> [improve][rest] Add lookup REST API swagger config.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-common/src/main/java/org/apache/pulsar/common/policies/impl/NamespaceIsolationPolicies.java
> [typos]fix some typos

- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/EtcdMetadataStore.java
- pulsar-metadata/src/test/java/org/apache/pulsar/metadata/impl/EtcdMetadataStoreTest.java
Fixes #<xyz>
Now, pulsar can not working for etcd cluster, just use this url can be reproduce:`http://etcd1:2379,http://etcd2:2379,http://etcd3:2379`, This PR can fix this problem and add test for etcd cluster.
*(or)*
*(or)*
*(example:)* …
> [fix][broker] Fix etcd cluster error and add test for etcd cluster

- pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
This PR comes from #16014.
- Fix tlsTrustCertsFilePath
- Fix service url
> [branch-2.7][fix][broker] Fix create client with TLS config

- conf/broker.conf
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
Current retention configuration is not clear for user especially the explanation of default value . So add more explanation for retention configuration
> [improve][doc]add more explanation for retention configuration

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
#16065 fixes the race condition issue, but introduces a new issue. This issue is triggered when the Proxy and Broker work together, when we use the proxy to request the broker to do lookup/subscribe/produce operation, the broker always uses the original authentication data for authorization, not proxy authentication data, which causes this issue.
- Fix passing authentication data, differentiate between original auth data and connected auth data by avoid to use the  `getAuthenticationData()`, this method name is easy to cause confusion and can not correctly get the authentication data
(cherry picked from commit 936bbbcc6a4e8cf61547aeedf92e84fb3a089502)
(Your PR needs to update …
> [fix][broker][branch-2.8] Fix passing incorrect authentication data (#16201)

- buildtools/pom.xml
- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-functions/secrets/src/test/java/org/apache/pulsar/functions/secretsprovider/EnvironmentBasedSecretsProviderTest.java
- pulsar-io/flume/src/test/java/org/apache/pulsar/io/flume/node/TestEnvVarResolverProperties.java
Co-authored-by: liudezhi <liudezhi2098@163.com>
(cherry picked from commit 09ec578dd0b710d2591b06c2ede0e2591bce84e7)
> [branch-2.8][fix][broker] Upgrade log4j2 version to 2.18.0 (#16884)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/BookiesApiTest.java
cherry pick #14336 to branch 2.7
If the rack name set in the following case:
-  Enabled rack aware placement policy, and user set rack name which contains "/" in addition to the head and tail of the string. Such as "/r/a" or "r/a/b"
- Enabled region aware placement policy, and user set the rack name which contains multiple "/" in addition to the head and tail of the string. Such as "/region/region/a" or "region/a/rack/b"
The broker will throw the following exception on `onBookieRackChange`
```
10:29:08.112 [BookKeeperClientScheduler-OrderedScheduler-0-0] ERROR org.apache.bookkeeper.client.TopologyAwareEnsemblePlacementPolicy - Unexpected exception while handling joining bookie test.bk3:3183
org.apache.bookkeeper.net.NetworkTopologyImpl$InvalidTopologyException: Invalid network topology. …
```
> [Branch 2.7] Validate rack name

- pulsar-functions/instance/src/main/python/python_instance_main.py
Fixes #16696 
Make python instance main process zip file correctly when using relative path
Fix relative path error in `python_instance_main.py`
bug fix
> [fix][function] Fix python instance not process zip file correctly

- site2/docs/admin-api-topics.md
- site2/website/versioned_docs/version-2.9.0/admin-api-topics.md
doc for https://github.com/apache/pulsar/pull/14531
> [doc][monitoring][admin] Add doc for filteredMsgCount

- conf/broker.conf
- conf/proxy.conf
- conf/standalone.conf
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderBasic.java
- pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderBasicTest.java
- pulsar-broker-common/src/test/resources/authentication/basic/.htpasswd
- pulsar-common/src/main/java/org/apache/pulsar/client/api/url/URL.java
Original PR #16526 and #16935.
> [improve][authentication][branch-2.7] Improve get the basic authentication config

- site2/docs/security-tls-transport.md
- site2/website/versioned_docs/version-2.10.1/security-tls-transport.md
Fixes #16877,  fixes #16844
There is a 404 link in the doc of `security > Transport Encryption`.
```
wget https://raw.githubusercontent.com/apache/pulsar/master/site2/website/static/examples/openssl.cnf
```
* Fix the link
> [fix][doc] Fix 404 in security-tls-transport.md

- pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterTest.java
Fixes #16723
Master Issue: #16723
The problem is that it occasionally runs in 5s or so, which is normally quite fast
- Use ` @Test(timeOut = 1000 * 10)` to limit the time, delete time limits in method args.
- Increase the maximum time limit
- Reduce write count
> [fix][flaky-test]ManagedCursorMetricsTest timeout

- conf/broker.conf
- conf/proxy.conf
- conf/standalone.conf
- deployment/terraform-ansible/templates/broker.conf
- deployment/terraform-ansible/templates/proxy.conf
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
- pulsar-client-cpp/test-conf/standalone-ssl.conf
- pulsar-client-cpp/test-conf/standalone.conf
- pulsar-client-cpp/tests/authentication.conf
- pulsar-client-cpp/tests/standalone.conf
- pulsar-proxy/src/test/resources/proxy.conf
- site2/docs/reference-configuration-broker.md
- site2/docs/reference-configuration-standalone.md
The default value of `advertisedAddress` has been changed to `InetAddress.getLocalHost().getCanonicalHostName()` in https://github.com/apache/pulsar/pull/6235, but the documents are not updated.
Update the documents.
(Your PR needs to update docs and you will …
> [doc] Fix the documents for the config `advertisedAddress`

- buildtools/pom.xml
- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-functions/secrets/src/test/java/org/apache/pulsar/functions/secretsprovider/EnvironmentBasedSecretsProviderTest.java
- pulsar-io/flume/src/test/java/org/apache/pulsar/io/flume/node/TestEnvVarResolverProperties.java
Cherry pick #16884 to branch 2.7
Upgrade log4j2 version to 2.18.0
> [Branch 2.9][fix][broker] Upgrade log4j2 version to 2.18.0 (#16884)

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationDataHttps.java
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderToken.java
- pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderTokenTest.java
> [improve][authentication][branch-2.9] Support for get token from HTTP params

- .github/changes-filter.yaml
- .github/workflows/ci-go-functions-style.yaml
- .github/workflows/ci-go-functions-test.yaml
- .github/workflows/pulsar-ci.yaml
Currently, Java tests consume major CI resources. And it is not necessary to run all the tests for changes that are only on the  C++ or python parts of the code. This PR skips unnecessary tests when there are only cpp/python changes. This can greatly increase the efficiency of CI when testing the C++/Python part of the code.
* Skip java unit tests, integration tests(the part only for java codes), go function tests when there are only cpp/python changes.
* The system test is not skipped because there are some python function codes in that test.
I have created a test PR in a separate repo to verify this change: https://github.com/RobertIndie/pulsar-ci-test/pull/1
It can skip many unnecessary Java tests and reduce the flaky of CI testing.
Need …
> [improve][ci] Skip unnecessary tests when there are only cpp/python related changes

- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/PackagesApiNotEnabledTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/PackagesApiTest.java
- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PackagesImpl.java
Improve the package download process to handle the download
body more efficiently.
*(or)*
*(or)*
*(example:)*
- …
> Improve the package download process

- pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
> [clean][broker] remove unused code

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
https://github.com/apache/pulsar/pull/14185 had a minor bug in that the first message sent to the producer would always deliver because `lastBatchSendNanoTime` was not initialized correctly. In https://github.com/apache/pulsar/pull/15406, we improved the initialization, but I am concerned that it didn't completely solve the problem because the counter is initialized before grabbing the connection, which will often take longer than the `batchingMaxPublishDelayMicros`, which defaults to 1 millisecond. This PR aims to solve the underlying problem by only initializing the timer once the producer is connected to the topic. Note that this change aligns with the original behavior, which started the scheduled task once the producer connected to the topic.
If possible, I hope to get this merged …
> [imp][java client] lastBatchSendNanoTime initialization

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
Cherry-pick original PR #16968
- Cherry-pick original PR #16968
> [branch-2.10][fix][broker]Prevent StackOverFlowException in SHARED subscription

- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java
- site2/docs/io-cli.md
> [fix][doc] Fix issues in documentation of topic-pattern parameter

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationDataHttps.java
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderToken.java
- pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderTokenTest.java
> [improve][authentication][branch-2.10] Support for get token from HTTP params

- pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/LedgerOffloaderMetricsTest.java
Fixes #16858
Master Issue: #16858
After Pulsar is started, still being spy-mock on `pulsarService`, which is prone to destabilizing mock objects. And these mocks are unnecessary
https://github.com/apache/pulsar/blob/c1c3c86f83e6bece06c29bbdd6e5b1b1cb841ef5/pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/LedgerOffloaderMetricsTest.java#L132-L133
remove unnecessary mocks
> [fix][flaky-test]LedgerOffloaderMetricsTest

- wiki/release/create-gpg-keys.md
- wiki/release/release-candidate-validation.md
- wiki/release/release-process.md
After moving to the pulsar codebase
- Everyone can contribute to the validation doc
- The release process doc update can get reviewers to review
The mailing list discussion: https://lists.apache.org/thread/mv1to079cznkxdldrpoq5518l2ozl5kr
> Move Pulsar release related docs to codebase

- tests/docker-images/java-test-functions/src/main/java/org/apache/pulsar/tests/integration/functions/RemoveAvroFieldRecordFunction.java
Now all CI failed with below error.
https://github.com/apache/pulsar/runs/7911509789?check_suite_focus=true
> [fix][test] Fix CI build error

- tests/docker-images/java-test-functions/src/main/java/org/apache/pulsar/tests/integration/functions/RemoveAvroFieldRecordFunction.java
Cherry-pick #17177 to branch-2.11
> [Branch-2.11][test] Cherry-pick 17177

- site2/docs/functions-concepts.md
- site2/docs/functions-develop-api.md
> [improve][doc] Add doc on Record as Function output type

- site2/docs/io-debug.md
- site2/docs/io-develop.md
This is a hotfix to correct the grammar as well as the page layout of the Pulsar IO  > Debug and Pulsar IO > Develop pages.
- Fixed grammar on the Debug page
- Fixed grammar on the Develop page
- Fixed errors regarding source/sink on the Develop page
- Fixed page layout (Handling schema as a subsection to source and sink, Infobox regarding licensing)
- …
> [fix][doc] Hotfix Pulsar IO docs

- pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java
Add test for checking the customized properties is copied to DLQ
> [improve][test] Add test for checking the customized properties is copied to DLQ

- buildtools/pom.xml
Trivial changes. cc @codelipenghui @lhotari
> [cleanup][build] Use netty.version consistently

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
See https://github.com/apache/pulsar/pull/16222 for the motivation.
* Fix an incorrect description for the `authoritative` swagger annotation.
> Fix swagger annotation for analyzeBacklog endpoint

- site2/docs/kubernetes-helm.md
* Step 4.4 indicates <code>...After successfully **created** an environment..</code>
* Updated Step 4.4 to <code>...After successfully **creating** an environment...</code>
This change is a trivial rework / code cleanup without any test coverage.  This PR is doc update only.
- The wire protocol: yes
- Anything that affects deployment: no 
(Your PR contains …
> [fix][kubernetes-helm] Update to Step 4.4

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
issue:  link https://github.com/apache/pulsar/pull/17287, don't fix the batch message to DLQ
can make batch messages to DLQ when reaching the redelivery count
```
redeliveryCount > deadLetterPolicy.getMaxRedeliverCount()
```
send this message to DLQ directly
add the test
- Does this pull request introduce a new feature? (yes)
- If a feature is not applicable for documentation, …
> [fix][client] Fix reach redeliverCount client can't send batch messags

- .github/workflows/ci-documentbot.yml
Master Issue: #15797 https://github.com/apache/pulsar-test-infra/issues/67
Simplify invocation of docbot action
Upgrade to latest docbot action
> [improve][workflow] Upgrade to latest docbot action

- site2/docs/client-libraries-cpp.md
- site2/docs/client-libraries-dotnet.md
- site2/docs/client-libraries-go.md
- site2/docs/client-libraries-java.md
- site2/docs/client-libraries-node.md
- site2/docs/client-libraries-python.md
This closes #17303.
cc @shibd @RobertIndie @Anonymitaet @momo-jun
> [improve][doc] sync Connection URLs section

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadManager.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
There are multiple ways of loading classes with reflection in Pulsar load balance module. And we should have some common code.
- Unify the reflection method in pulsar load balance module.
> [refactor][broker]refactor reflection method in loadbalance module

- site2/docs/administration-metadata-store.md
As part of #16309, updated the docs to accept Http URLs as part of metadataStoreUrl 
Update etcd metadataStoreUrl in administration-metadata-store.md file
> [fix][doc] Update etcd metadataStoreUrl to accept Http URLs

- README.md
Add Pulsar Site repo link to README file.
Just one README file update.
> Add Pulsar Site Repo link to README

- site2/docs/about.md
Doc updates and navigational support to improve user experience.
Improve user experience by adding "paths" and providing context.
Context updates for each content block. Describes where the user should start.
This is a doc change and does not require CI checks or test coverage.
> [Doc] Added explanations for documentation landing page

- wiki/release/release-process.md
Some links are broken after we moved the wiki to codebase.
1. update catalog, sync with the content.
2. Fix broken url.
3. Copy the connectors before start standalone in step 3.
Update wiki.
> [fix][doc] Fix some errors in release-process wiki.

- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java
Fix typo
This PR changes client's javadoc
> [client][javadoc] fix a typo of ConsumerBuilder javadoc

- pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/storage/ManagedLedgerStorage.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/TransactionBufferProvider.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/TransactionPendingAckStoreProvider.java
There are multiple ways of loading classes with reflection in Pulsar storage and transaction module. And we should have some common code.
- Unify the reflection method in pulsar storage and transaction module.
> [refactor][broker]refactor reflection method in storage and transaction module

- pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/RecordFunction.java
- tests/docker-images/java-test-functions/src/main/java/org/apache/pulsar/tests/integration/io/TestLoggingSink.java
> [cleanup][functions] Cleanup test functions

- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PackagesImpl.java
Fix compile failure introduced when cherry-pick #16365
bug fix.
> [fix][branch-2.10] Fix compile error

- .github/workflows/ci-python-build-3.9-client.yaml
- site2/docs/client-libraries-python.md
> Revert "[improve][ci] Add workflow for python local install (#17232)"

- pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java
> Factorize code in LocalRunner

- README.md
Update pulsar version in README.
> [doc] Update pulsar version in README

- buildtools/pom.xml
- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
> [fix][sec] bump snakeyaml to 1.31 fix CVE-2022-25857

- buildtools/pom.xml
- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
Cherry-pick #17457 to branch-2.11.
cc @Technoboy-
> [fix][sec][BP-2.11] bump snakeyaml to 1.31 fix CVE-2022-25857 (#17457)

- pulsar-sql/presto-distribution/LICENSE
We update the jna version in this [PR](https://github.com/apache/pulsar/pull/17262).
We should update the version in presto license file as well.
*(or)*
*(or)*
*(example:)*
- The schema: (yes / no / …
> [fix][license] Update the jna version in the presto license file

- pulsar-sql/presto-distribution/LICENSE
We update the log4j version in [PR](https://github.com/apache/pulsar/pull/16884),
but we haven't update the license file for the version.
update the log4j version in license file to the correct version
*(or)*
*(or)*
*(example:)*
- The schema: …
> [fix][license] Update the log4j version in the presto license file

- site2/website/static/swagger/2.7.5/swagger.json
- site2/website/static/swagger/2.7.5/swaggerfunctions.json
- site2/website/static/swagger/2.7.5/swaggersink.json
- site2/website/static/swagger/2.7.5/swaggersource.json
Update swagger file for v2.7.5
auto gen by `mvn -am -pl pulsar-broker install -DskipTests -Pswagger` in branch-2.7
> [doc] Update swagger file for v2.7.5

- site2/docs/develop-schema.md
- site2/docs/io-quickstart.md
- site2/docs/io-use.md
- site2/docs/reference-configuration.md
- site2/docs/sql-getting-started.md
- site2/docs/tiered-storage-aliyun.md
- site2/docs/tiered-storage-aws.md
- site2/docs/tiered-storage-azure.md
- site2/docs/tiered-storage-filesystem.md
- site2/docs/tiered-storage-gcs.md
- site2/docs/tiered-storage-overview.md
- site2/docs/tiered-storage-s3.md
> [fix][docs] getting-started-standalone backlinks

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleFactory.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java
> [improve][admin] Make `getBundleRange` async

- pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClient.java
- pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
- pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/elastic/ElasticSearchJavaRestClient.java
- pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/opensearch/OpenSearchHighLevelRestClient.java
- pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkTests.java
- testmocks/pom.xml
> [improve][test] Remove WhiteBox for ElasticSearchSinkTests 

- pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java
Fixes: #17112
Add more context
Add more context
> [fix][flaky-test]PulsarFunctionTlsTest.testFunctionsCreation

- site2/docs/io-quickstart.md
Fixes #17555
At first, I'd like to fix the broken links in `Pulsar I/O` chapter. But I found that not only this chapter has this problem, so I open #17599 for further discussion.
In this PR, I replace the docker introduction with a reference link and improve some code snippets.
> [improve][doc] improve pulsar I/O document

- site2/website/static/swagger/2.8.4/swagger.json
- site2/website/static/swagger/2.8.4/swaggerfunctions.json
- site2/website/static/swagger/2.8.4/swaggerpackages.json
- site2/website/static/swagger/2.8.4/swaggersink.json
- site2/website/static/swagger/2.8.4/swaggersource.json
Update swagger file for 2.8.4
auto gen by `mvn -am -pl pulsar-broker install -DskipTests -Pswagger` in branch-2.7
> [doc] Update swagger file for 2.8.4

- .github/workflows/ci-documentbot.yml
This closes https://github.com/apache/pulsar-test-infra/issues/73.
cc @michaeljmarshall @nodece 
> [improve][ci] docbot comment only for open PRs

- site2/docs/security-oauth2.md
- site2/website/versioned_docs/version-2.10.0-deprecated/security-oauth2.md
- site2/website/versioned_docs/version-2.10.1-deprecated/security-oauth2.md
- site2/website/versioned_docs/version-2.10.x/security-oauth2.md
there are two repeated words in a sentence. Therefore remove the redundant word
- [ x ] `doc` 
> [improve][doc]--remove redundant word

- site2/docs/about.md
PR in forked repository: https://github.com/Anonymitaet/pulsar/pull/1
> [improve][doc] add a tip for doc contribution

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
Cleanup unused sync method in NamespacesBase
Removing `validatePolicies` and `internalSetTopicDispatchRate`
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/2
> [cleanup][admin]cleanup unused sync method in NamespacesBase

- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyRefreshAuthTest.java
> [branch-2.10] Fix JDK compatibility issues.

- .github/PULL_REQUEST_TEMPLATE.md
cc @lhotari @nodece 
PR in forked repository: trivial to skip.
> [cleanup] properly comment out chunk

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/doc.yml
- .github/ISSUE_TEMPLATE/pip.yml
- .github/changes-filter.yaml
This is a follow-up to #16902. See https://github.com/apache/pulsar/pull/16902#discussion_r977204882.
N/A
> improve issue templates wordings

- site2/docs/administration-zk-bk.md
Fixes #xyz
The example in the documentation will send the namespace into an endless loop waiting for ack. The number ack's should be relative to the number of bookies.
Reverse the param values to make ack's less that # of bookies.
*(or)*
*(or)*
*(example:)*
> [docs][bugfix] Fix set-persistence parameters

- site2/docs/administration-zk-bk.md
Our admin examples must not show users incorrect information.
Changed Bookkeeper persistence example.
*(or)*
*(or)*
*(example:)*
> [Doc][bugfix] Example broke Ensemble>=WriteQuorum>=AckQuorum Rule

- pulsar-common/src/main/java/org/apache/pulsar/common/util/RateLimiter.java
Add thread name for RateLimiter
PR in forked repository: https://github.com/Technoboy-/pulsar/pull/11
> [improve][common] Add thread name for RateLimiter.

- README.md
* add link to https://github.com/apache/pulsar-client-cpp to README.md
* add link to https://github.com/apache/pulsar-client-python to README.md
cc @Anonymitaet @momo-jun
> [improve][doc] Add link to C++ and Python client to README.md

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
Fix the thread blocked.
```
2022-10-14T06:11:23,621+0000 [pulsar-io-4-1] ERROR org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider - Failed to get tenant staging
org.apache.pulsar.metadata.api.MetadataStoreException: Failed to get data from /admin/policies/staging
at org.apache.pulsar.broker.resources.BaseResources.get(BaseResources.java:87) ~[io.streamnative-pulsar-broker-common-2.10.0.4.jar:2.10.0.4]
at org.apache.pulsar.broker.resources.TenantResources.getTenant(TenantResources.java:61) ~[io.streamnative-pulsar-broker-common-2.10.0.4.jar:2.10.0.4]
at org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider.lambda$validateTenantAdminAccess$25(PulsarAuthorizationProvider.java:697) ~[io.streamnative-pulsar-broker-common-2.10.0.4.jar:2.10.0.4]
at …
```
> [fix][broker] Make full async call in PulsarAuthorizationProvider

- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
Fix `testGetTxnID`: transaction Id is not begin at 0;
`testSubscriptionRecreateTopic` : topic is already exsit.
and `testPendingAckMarkDeletePosition`: failed to get TP manager stats due to `testEndTPRecoveringWhenManagerLedgerDisReadable` set a mock 'TransactionPendingAckStoreProvider'  into pulsar.
fix them.
*(or)*
*(or)*
*(example:)* …
> [fix][test] Fix TransactionTest failure due to  clean up after class

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
Fixes #xyz
remove internalUnloadNamespace
internalDeleteTopicDispatchRate
internalRemoveBacklogQuota
see https://github.com/leizhiyuan/pulsar/pull/3
*(or)*
*(or)*
*(example:)*
> [cleanup][broker] Cleanup unused method in namespace base

- site2/docs/concepts-messaging.md
Fixes #18060
Fix errors in `concepts-messaging.md`.
PR in forked repository: https://github.com/labuladong/pulsar/pull/2
> [fix][doc] Fix errors in subscription document

- pulsar-client-cpp/docker/alpine/Dockerfile
- pulsar-client-cpp/docker/alpine/Dockerfile-alpine-3.8
- pulsar-client-cpp/docker/manylinux1/Dockerfile
- pulsar-client-cpp/docker/manylinux2014/Dockerfile
- pulsar-client-cpp/docker/manylinux_musl/Dockerfile
- pulsar-client-cpp/python/build-mac-wheels.sh
Cherry-pick: https://github.com/apache/pulsar/pull/18127
- Change the URL to point to the archive so that we won't get in the same situation on next release.
> [branch-2.11][cpp] Fix zlib dowload path.

- pulsar-client-cpp/docker/alpine/Dockerfile
- pulsar-client-cpp/docker/alpine/Dockerfile-alpine-3.8
- pulsar-client-cpp/docker/manylinux1/Dockerfile
- pulsar-client-cpp/docker/manylinux2014/Dockerfile
Cherry-pick: https://github.com/apache/pulsar/pull/18127
- Change the URL to point to the archive so that we won't get in the same situation on next release.
> [branch-2.8][cpp] Fix zlib dowload path.

- README.md
> [improve][doc] Use semver latest stable version

- site2/docs/administration-geo.md
> [fix][doc] admonitions syntax

- .github/workflows/pulsar-ci.yaml
- src/check-binary-license.sh
This closes #16783.
This closes #15253.
PR in forked repository: https://github.com/tisonkun/pulsar/pull/8
> [fix][ci] Check full build artifacts licenses

- site2/website/static/swagger/2.10.2/swagger.json
- site2/website/static/swagger/2.10.2/swaggerfunctions.json
- site2/website/static/swagger/2.10.2/swaggerpackages.json
- site2/website/static/swagger/2.10.2/swaggersink.json
- site2/website/static/swagger/2.10.2/swaggersource.json
> [improve][doc] Update swagger for 2.10.2

- README.md
> [fix][doc] Reflect archived and halted repositories

- pulsar-client-cpp/docker/alpine/Dockerfile
- pulsar-client-cpp/docker/alpine/Dockerfile-alpine-3.8
- pulsar-client-cpp/docker/manylinux1/Dockerfile
- pulsar-client-cpp/docker/manylinux2014/Dockerfile
- pulsar-client-cpp/docker/manylinux_musl/Dockerfile
- pulsar-client-cpp/python/build-mac-wheels.sh
Cherry-pick: https://github.com/apache/pulsar/pull/18127
- Change the URL to point to the archive so that we won't get in the same situation on next release.
> [branch-2.10][cpp] Fix zlib dowload path.

- tests/integration/src/test/java/org/apache/pulsar/tests/integration/tls/ClientTlsTest.java
> [fix][test] Fix ClientTlsTest license

- site2/docs/client-libraries-cpp.md
- site2/website/versioned_docs/version-2.10.x/client-libraries-cpp.md
- site2/website/versioned_docs/version-2.7.5/client-libraries-cpp.md
- site2/website/versioned_docs/version-2.8.x/client-libraries-cpp.md
- site2/website/versioned_docs/version-2.9.x/client-libraries-cpp.md
Master issue: #17917
See https://github.com/apache/pulsar/issues/17917#issuecomment-1290146425.
cc @momo-jun @Anonymitaet
> [improve][doc] cherry-pick cpp client docs installation section

- pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/OwnershipCacheTest.java
Fixes #18196
Master Issue: #18196
change get to remove
*(or)*
*(or)*
*(example:)*
> [improve][broker] Remove locallyAcquiredLock when removeOwnership

- deployment/terraform-ansible/deploy-pulsar.yaml
- distribution/io/src/assemble/io.xml
- pom.xml
- pulsar-io/docs/pom.xml
- pulsar-io/http/pom.xml
- pulsar-io/http/src/main/java/org/apache/pulsar/io/http/HttpSink.java
- pulsar-io/http/src/main/java/org/apache/pulsar/io/http/HttpSinkConfig.java
- pulsar-io/http/src/main/java/org/apache/pulsar/io/http/JsonConverter.java
- pulsar-io/http/src/main/java/org/apache/pulsar/io/http/package-info.java
- pulsar-io/http/src/main/resources/META-INF/services/pulsar-io.yaml
- pulsar-io/http/src/test/java/org/apache/pulsar/io/http/HttpSinkTest.java
- pulsar-io/pom.xml
The HTTP Sink pushes records to any HTTP server with the record value in the body of POST method. 
It means you can have event push notification to a simple webhook. This enables the number of applications and platforms to integrate with Pulsar in an existing architecture without Pulsar’s library dependencies and constraints of OS and language that current Pulsar clients can only support.
The Sink takes inspiration from [Pulsar Beam](https://github.com/kafkaesque-io/pulsar-beam) and the [Confluent HTTP Sink connector](https://docs.confluent.io/kafka-connectors/http/current/overview.html).
The body of the HTTP request is the JSON representation of the record value.
Some headers are added to the HTTP request:
* `PulsarTopic`: the topic of the record
* `PulsarKey`: the key of the record
* …
> [feat][io] Provide a HTTP Sink

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
In https://github.com/apache/pulsar/pull/17398, we've introduced `managedLedgerOffloadThresholdInSenconds` to pulsar.
But there is a bug, see https://github.com/apache/pulsar/pull/17398#discussion_r1005568241
PR in forked repository: https://github.com/tjiuming/pulsar/pull/9
> [fix][offload] Fix the problem that ManagedLedger does not release locks in some cases when offload

- pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
Cleanup `NamespaceService`
Remove some unused code to cleanup  `NamespaceService`
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/13
> [cleanup][broker] Cleanup NamespaceService

- conf/standalone.conf
- pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
Fixes #18206
Calculate `dbStorage_readAheadCacheMaxSizeMb` and `dbStorage_writeCacheMaxSizeMb` correctly in standalone mode to avoid OOM.
PR in forked repository: https://github.com/labuladong/pulsar/pull/4
> [fix][broker] calculate default cache size correctly in standalone mode

- pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterTest.java
see: 
- https://github.com/apache/pulsar/actions/runs/3303558527/jobs/5456181204
`TxnLogBufferedWriter` is used to write multiple data to the ledger in batches and maintains a task queue internally. When the `TxnLogBufferedWriter.close` is called, tasks that have not yet been executed in the queue will fail early, causing the failed task get `callback` before the previous tasks. This makes it flaky to validate the execution results sequentially.
- Only verify that the order of the correct callback is verified
- Make sure all requests have received callbacks.
- https://github.com/poorbarcode/pulsar/pull/35
> [fix][test]fix flaky test TxnLogBufferedWriterTest.testMainProcess

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java
remove unused method: isSlowestReader
PR in forked repository: https://github.com/lordcheng10/pulsar/pull/39
> [cleanup][broker] Cleanup unused method: isSlowestReader

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
Some implementation classes are missing annotations.
Add `@Override` annotation.
> [cleanup][misc] Add override annotation

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
The variable `expireChunkMessageTaskScheduled` could be accessed by multi-thread concurrently. Need to make it thread-safe.
* Use AtomicBoolean and CAS operation to access the `expireChunkMessageTaskScheduled`
PR in forked repository: https://github.com/RobertIndie/pulsar/pull/7
> [fix][client] Use atomic and CAS to access expireChunkMessageTaskScheduled

- site2/docs/cookbooks-encryption.md
- site2/docs/schema-manage.md
- site2/docs/standalone.md
- site2/website/versioned_docs/version-2.10.x/standalone.md
This is the counterpart of https://github.com/apache/pulsar-site/pull/281.
This refers to https://github.com/apache/pulsar/issues/18410.
PR in forked repository: N/A
> [fix][doc] Redirections

- pulsar-io/hdfs2/src/test/java/org/apache/pulsar/io/hdfs2/sink/seq/HdfsSequentialSinkTests.java
- pulsar-io/hdfs2/src/test/java/org/apache/pulsar/io/hdfs2/sink/seq/HdfsTextSinkTests.java
- pulsar-io/hdfs2/src/test/java/org/apache/pulsar/io/hdfs2/sink/text/HdfsStringSinkTests.java
- pulsar-io/hdfs3/src/test/java/org/apache/pulsar/io/hdfs3/sink/AbstractHdfsSinkTest.java
- pulsar-io/hdfs3/src/test/java/org/apache/pulsar/io/hdfs3/sink/seq/HdfsSequentialSinkTests.java
- pulsar-io/hdfs3/src/test/java/org/apache/pulsar/io/hdfs3/sink/seq/HdfsTextSinkTests.java
- pulsar-io/hdfs3/src/test/java/org/apache/pulsar/io/hdfs3/sink/text/HdfsStringSinkTests.java
Also, do some code format. The changes are trivial so I think it's OK.
PR in forked repository: https://github.com/tisonkun/pulsar/pull/15
> [improve][test] Enable IO/HDFS tests that pass locally

- .github/workflows/ci-go-functions.yaml
- .github/workflows/pulsar-ci-flaky.yaml
- .github/workflows/pulsar-ci.yaml
PR in forked repository: https://github.com/tisonkun/pulsar/pull/14
> [improve][ci] skip CI cronjob in forks 

- site2/docs/functions-package-java.md
Documents are not highlighted correctly.
Before:
Current:
Change to `XML`.
> [improve][doc] change code style

- README.md
The repo halted doesn't mean we don't provide related functionality :)
N/A
cc @Anonymitaet @dave2wave @merlimat
> [improve][doc] Clarify halted repos are bundled

- pulsar-io/cassandra/src/main/java/org/apache/pulsar/io/cassandra/CassandraAbstractSink.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/CassandraSinkTester.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarIOSinkRunner.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarSinksTest.java
This is based on https://github.com/apache/pulsar/pull/4036.
PR in forked repository: https://github.com/tisonkun/pulsar/pull/16
> [fix][test] Enable Cassandra sink tests

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
Backport #17779 to branch-2.9.
> [fix][sec] [branch-2.9] Bump snakeyaml to 1.32 for CVE-2022-38752

- site2/docs/reference-cli-tools.md
This is a follow-up to https://github.com/apache/pulsar/pull/18101.
> [fix][doc] Tips markup

- CONTRIBUTING.md
- README.md
- site2/README.md
This reflects https://github.com/apache/pulsar-site/pull/295.
> [improve][doc] Update links to the contribute guide

- pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarSinkE2ETest.java
This refers to #16578.
`setNegativeAckRedeliveryDelayMs` to 1 ms so that messages are sent to DLQ quickly.
PR in forked repository: https://github.com/tisonkun/pulsar/pull/18
> [fix][test] Try fix PulsarSinkE2ETest.testPulsarSinkDLQ

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Currently, if there are duplicated messages whose chunk id is both 0, then it may result in allocating an unused buffer and may lead to the buffer memory leak.
* Only allocate the bytebuffer when there is no duplicated chunk message with chunk id 0.
PR in forked repository: https://github.com/RobertIndie/pulsar/pull/9
> [fix][client] Avoid allocating unused buffer when receiving chunk message

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageChunkingTest.java
The test `testMaxPendingChunkMessages` is disabled, this PR enables it.
* Fix some issues in the testMaxPendingChunkMessages
* Enable testMaxPendingChunkMessages
PR in forked repository: https://github.com/RobertIndie/pulsar/pull/10
> [fix][test] Enable testMaxPendingChunkMessages

- buildtools/pom.xml
- pom.xml
- pulsar-broker/pom.xml
- pulsar-io/netty/pom.xml
- structured-event-log/pom.xml
- Dependency is duplicated in file(s): Pulsar、Pulsar-io/netty、structured-event-log.  And there are already duplicate dependencies in the root file pom.xml, open source considers using maven dependency delivery to solve the problem of duplicate dependencies
`<dependency>`
`<groupId>org.testng</groupId>`
`<artifactId>testng</artifactId>`
`<scope>test</scope>`
` </dependency>`
- XML: collapse empty tags
*(or)*
*(or)*
*(example:)*
- *Extended integration …
> [refactor][build] Collapse empty tags and duplicated dependences in pom.xml

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageChunkingTest.java
Master Issue: #18570
Currently, the flaky test `testMaxPendingChunkMessages` has blocked many PRs. Although I have fixed some problems of this test, there are still other flaky issues. This PR disables this flaky test first. Then I will open a new PR to fix this flaky test.
* Disable the test `testMaxPendingChunkMessages`
> [fix][test] Disable testMaxPendingChunkMessages to unblock the flaky test first

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
Fixes https://github.com/apache/pulsar/issues/18591
Fix the bug: the body param of the Restful API about `set a backlog quota for a topic` is missing
https://pulsar.apache.org/admin-rest-api/?version=master#operation/setBacklogQuota
Add the body param declaration for the Restful API about `set a backlog quota for a topic`
*(or)*
*(or)*
*(example:)* …
> [fix][doc] fix rest api param description of setting backlog quota on topic

- pulsar-functions/instance/src/main/python/python_instance.py
Fixes #18424
Python function instance doesn't support `SubscriptionPosition`
Support `SubscriptionPosition`
https://github.com/jiangpengcheng/pulsar/pull/3
> [improve][fn] Support SubscriptionPosition in python instance

- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
Fixes #18588
NamespacesTest.testSetOffloadThreshold is flaky.
- Use awaitility to poll for changes (which are asynchronously applied in Pulsar, there is no strong consistency)
- Drop the validation for default values since that was ignored any ways.
> [fix][test] Fix flaky NamespacesTest.testSetOffloadThreshold

- site2/docs/io-elasticsearch-sink.md
> [fix][doc] Fix elasticsearch sink layout

- .asf.yaml
reason : https://lists.apache.org/thread/jcrq9q0k6kh9rvb71dwb9s3mvo5c5dk5
> [fix][ci] Enable branch-2.9 force push

- site2/docs/reference-pulsar-admin.md
Fixes #xyz
Modify documentation related to this [PR]( https://github.com/apache/pulsar/pull/16130) and this [issue](https://github.com/apache/pulsar/issues/16082)
PR in forked repository: https://github.com/AlvaroStream/pulsar
> [improve][doc] Updated set retention time documentation

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherMultipleConsumers.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
We should avoid use same `Random` instance in multi-thread program, here is reason from [Random javadoc][1]:
> Instances of java.util.Random are threadsafe. However, the concurrent use of the same java.util.Random instance across threads may encounter contention and consequent poor performance. Consider instead using [ThreadLocalRandom](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/ThreadLocalRandom.html) in multithreaded designs.
And there is an answer explain contention in Random.next: https://stackoverflow.com/a/22313588/3378901
[1]: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Random.html
Using ThreadLocalRandom instead. …
> [improve][broker] Avoid share same random in multi-threads due to performance issue

- site2/website/versioned_docs/version-2.10.x/security-tls-transport.md
- site2/website/versioned_docs/version-2.2.0/security-tls-transport.md
- site2/website/versioned_docs/version-2.2.1/security-tls-transport.md
- site2/website/versioned_docs/version-2.3.0/security-tls-transport.md
- site2/website/versioned_docs/version-2.3.1/security-tls-transport.md
- site2/website/versioned_docs/version-2.3.2/security-tls-transport.md
- site2/website/versioned_docs/version-2.4.0/security-tls-transport.md
- site2/website/versioned_docs/version-2.4.1/security-tls-transport.md
- site2/website/versioned_docs/version-2.4.2/security-tls-transport.md
- site2/website/versioned_docs/version-2.5.0/security-tls-transport.md
- site2/website/versioned_docs/version-2.5.1/security-tls-transport.md
- site2/website/versioned_docs/version-2.5.2/security-tls-transport.md
- site2/website/versioned_docs/version-2.6.0/security-tls-transport.md
- site2/website/versioned_docs/version-2.6.1/security-tls-transport.md
- site2/website/versioned_docs/version-2.6.2/security-tls-transport.md
- site2/website/versioned_docs/version-2.6.3/security-tls-transport.md
- site2/website/versioned_docs/version-2.6.4/security-tls-transport.md
- site2/website/versioned_docs/version-2.7.0/security-tls-transport.md
- site2/website/versioned_docs/version-2.7.1/security-tls-transport.md
- site2/website/versioned_docs/version-2.7.2/security-tls-transport.md
- site2/website/versioned_docs/version-2.7.3/security-tls-transport.md
- site2/website/versioned_docs/version-2.7.4/security-tls-transport.md
- site2/website/versioned_docs/version-2.7.5/security-tls-transport.md
- site2/website/versioned_docs/version-2.8.x/security-tls-transport.md
- site2/website/versioned_docs/version-2.9.x/security-tls-transport.md
Fixes #18656
There are many url like `wget https://raw.githubusercontent.com/apache/pulsar-site/main/site2/website/static/examples/openssl.cnf` link to the openssl.cnf. But this file was deleted at https://github.com/apache/pulsar-site/pull/215.
* Fix the URL to link to https://pulsar.apache.org/examples/openssl.cnf
> [fix][doc] Fix all 404 link for example openssl.cnf

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionProduceTest.java
Cherry-pick https://github.com/apache/pulsar/pull/18307
> [cherry-pick][branch2.10]Fix namespace can not be deleted by force.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannel.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
Fixes #xyz
This PR Added ServiceUnitStateChannelImpl and its unit test.
For the pip-192 project, this ServiceUnitStateChannelImpl
- has a tableview and a producer on the system topic, persistent://pulsar/system/service-unit-state-channel
- has a leader coordination service to elect the owner broker of the channel.
- define message handlers according to the service unit state changes.
- define ownership cleanup logic in case a broker is unregistered (dead).
- *Added unit tests for the new classes.
We will have separate PRs to …
> [improve][broker] PIP-192 Added ServiceUnitStateChannelImpl

- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTopicApiTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/ShadowReplicatorTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/AutoScaledReceiverQueueSizeTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/DynamicReceiverQueueSizeTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/topicpolicies/SchemaCompatibilityStrategyTest.java
Some tests use `BeforeClass` twice. I think this is a mistake.
PR in forked repository: https://github.com/labuladong/pulsar/pull/14
> [fix][test] correct `AfterClass` usage

- pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ResendRequestTest.java
1. add missing code for cherry-pick #17592
2. fix flaky test testFailoverSingleAckedPartitionedTopic. redeliver in another thread will cause receive repeat messages.
3. run test for branch-2.9
> [cherry-pick][branch-2.9] fix cherry-pick #17592 missing code and flaky test testFailoverSingleAckedPartitionedTopic

- pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactorTool.java
- pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionWorkerStarter.java
This is somewhat of a blocker to https://github.com/apache/pulsar/issues/18721.
> [fix][cli] pulsar cli should exit normally on help and generate doc

- conf/broker.conf
- conf/proxy.conf
- conf/standalone.conf
- conf/websocket.conf
We provide incorrect examples of the ciphers and protocols.
Using `key=value1,value2` format instead of the incorrect `[value1, value2]` format.
> [improve][misc] Improve examples of ciphers and protocols

- pulsar-functions/instance/src/main/python/contextimpl.py
Fixes #18627
Python instance doesn't expose pulsar client while java does, so it's better to expose it in python instance too
expose pulsar client in python functions
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/5
> [improve][fn] Expose pulsar client in python instance

- site2/docs/io-connectors.md
- site2/docs/io-http-sink.md
PR in forked repository: https://github.com/cbornet/pulsar/pull/10
> [feat][doc] Add doc for the HTTP Sink

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/schema/compatibility/SchemaCompatibilityCheckTest.java
- pulsar-common/src/main/java/org/apache/pulsar/common/protocol/schema/SchemaStorage.java
> [branch-2.10][fix][broker] Fix duplicated schemas creation

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java
- pulsar-common/src/main/java/org/apache/pulsar/common/protocol/schema/SchemaStorage.java
(cherry picked from commit 390b1413624e6154faf50d4a083d7d6efc4d0265)
Cherry-pick: #18701
> [branch-2.9][fix][broker] Fix duplicated schemas creation (#18701)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
> [cleanup][broker] Remove the unused method internalGetList from PersistentTopicsBase

- pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SourceConfigUtils.java
- pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/SourceApiV3ResourceTest.java
- site2/docs/io-cdc-debezium.md
- site2/docs/io-debezium-source.md
This closes #15667.
PR in forked repository: https://github.com/tisonkun/pulsar/pull/20
> [improve][fn] topic name is not required for source config

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
cherry-pick #18823
If users set topic policy for system topic, then delete this system topic, the topic policy should be deleted.
Only change_events topic do not need to clear topic policies.
PR in forked repository: https://github.com/liangyepianzhou/pulsar/pull/16
> [cherry-pick][branch-2.9] Fix delete system topic clean topic policy (#18823)

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorContainer.java
A minor improvement for ManagedCursorContainer if there is only one cursor ledger
Avoid the `heap` swap if the `heap` size equals 1
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/20
> [improve][broker] Improve ManagedCursorContainer if there is only one cursor in ledger

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java
- pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java
- pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/AuthPolicies.java
- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
- pulsar-common/src/main/java/org/apache/pulsar/client/admin/internal/data/AuthPoliciesImpl.java
Reverts apache/pulsar#15576
After an offline discussion with @michaeljmarshall I learned that there can be a better solution than this PR implements. Also, the original PIP associated to this PR didn't have a formal resolution.
Pending to revert first.
> Revert "[PIP-167][Authorization] Make it Configurable to Require Subscription Permission"

- pulsar-functions/instance/src/main/python/contextimpl.py
> [fix][fn] Typo in method name

- site2/website/versioned_docs/version-2.10.x/functions-runtime.md
I only fixed a small typo error
Fixes #xyz
*(or)*
*(or)*
*(example:)*
> [fix][doc] typo in functions-runtime

- site2/docs/deploy-docker.md
Fix https://github.com/apache/pulsar/issues/18952
There is some indentation problem in docker-compose.yaml.
Fix the docker-compose.yaml.
*(or)*
*(or)*
*(example:)*
> [fix][doc]Fix indentation problem in docker-compose.yaml

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/BrokerSelectionStrategy.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeight.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/package-info.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeightTest.java
This PR Added `LeastResourceUsageWithWeight` to the load balancer extensions and its unit test.
For the pip-192 project, this LeastResourceUsageWithWeight
- is a copy of the existing broker-bundle assignment strategy, `org.apache.pulsar.broker.loadbalance.impl.LeastResourceUsageWithWeight`.
- uses the load data from the load balancer extensions.
- *Added unit tests for the new classes.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/17
> [improve][broker] PIP-192 Added LeastResourceUsageWithWeight broker assignment strategy to the load balancer extensions

- src/owasp-dependency-check-suppressions.xml
> [improve][sec] Suppress false positive OWASP reports

- pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/DebeziumSource.java
- pulsar-io/debezium/mongodb/src/main/java/org/apache/pulsar/io/debezium/mongodb/DebeziumMongoDbSource.java
2.10 backport of https://github.com/apache/pulsar/pull/19004
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/alpreu/pulsar/pull/5
> [branch-2.10][cherry-pick] Debezium sources: Support loading config from secrets

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryController.java
Fixes https://github.com/liangyepianzhou/pulsar/actions/runs/3889405613/jobs/6637633408
Upgrade the version of the bookkeeper to resolve the compile issue.
*(or)*
*(or)*
*(example:)*
> [branch-2.10][fix] Fix the compile issue of Branch-2.10

- buildtools/src/main/java/org/apache/pulsar/tests/FailFastNotifier.java
This is a follow up change for #19220 which contained a change to call cleanup methods when a test fails.
This change causes problems for later tests which are skipped since the @After* methods get called when the @Before* methods have been skipped. The cleanup methods should only be called in the current test class where the first exception happened
- revisit solution so that cleanup methods are only called in the current test class where the first exception happened (when exceptions happen when fail fast mode is enabled)
> [improve][ci] Revisit the TestNG FailFastNotifier changes to fix NPEs when a test fails

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/CompactionReaderImplTest.java
Fixes https://github.com/apache/pulsar/issues/19214
Fixes https://github.com/apache/pulsar/issues/19214
Created a consumer before publishing messages.
I couldn't replicate the issue in my local env. However, we need to create a consumer first to run this test consistently. (This pre-step in other tests is searched by `// subscribe before ` comment.)
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/21
> [fix][test] Fix flaky test CompactionReaderImplTest

- pulsar-io/elastic-search/pom.xml
- pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java
- pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
- pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfigTests.java
2.11 backport of https://github.com/apache/pulsar/pull/18986
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/alpreu/pulsar/pull/7
> [branch-2.11][cherry-pick] Elasticsearch sink: Support loading config from secrets

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/CompactionReaderImplTest.java
Fixes https://github.com/apache/pulsar/issues/19214
Fixes https://github.com/apache/pulsar/issues/19214
Wait until the consumer future completes before calling the issue function, `reader.getLastMessageIdAsync()`
I couldn't replicate the issue in my local env. However, we better wait til the consumer init completes before calling the consumer apis. 
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/21
>  Fix flaky test CompactionReaderImplTest(wait until the consumerFuture completes)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PartitionKeywordCompatibilityTest.java
(cherry picked from commit fc4bca6823282c4f5375e5d48552c1f0e114b5ee)
> [fix][broker] Support deleting partitioned topics with the keyword `-partition-` (#19230)

- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyIdleTimeoutTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPingTest.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/AbstractWebSocketHandler.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketProxyConfiguration.java
Cherry-pick https://github.com/apache/pulsar/pull/19203 to branch-2.9.
> [improve][websocket][branch-2.9] Add ping support

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyIdleTimeoutTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPingTest.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/AbstractWebSocketHandler.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketProxyConfiguration.java
- pulsar-websocket/src/test/java/org/apache/pulsar/websocket/AbstractWebSocketHandlerTest.java
Cherry-pick https://github.com/apache/pulsar/pull/19203 to branch-2.10.
> [improve][websocket][branch-2.10] Add ping support

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyIdleTimeoutTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPingTest.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/AbstractWebSocketHandler.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketProxyConfiguration.java
- pulsar-websocket/src/test/java/org/apache/pulsar/websocket/AbstractWebSocketHandlerTest.java
Cherry-pick #19203 to branch-2.11.
> [improve][websocket][branch-2.11] Add ping support

- pulsar-functions/java-examples/src/main/resources/example-window-function-config.yaml
Fixes #19299 
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [fix] fix window function example yaml

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/AbstractWebSocketHandler.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java
- pulsar-websocket/src/test/java/org/apache/pulsar/websocket/AbstractWebSocketHandlerTest.java
> [fix][websocket][branch-2.9] Fix webSocketPingDurationSeconds config

- bin/pulsar
- pom.xml
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/BrokerStatTest.java
> [fix][cli][branch-2.10] Fix mbeans to json

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
Partition-topic condition change from `!topicName.isPartitioned() && partitionMetadata.partitions > 0` to ` partitionMetadata.partitions > 0`
Partition-topic condition change from `!topicName.isPartitioned() && partitionMetadata.partitions > 0` to ` partitionMetadata.partitions > 0`
*(or)*
*(or)*
*(example:)* …
> [improve][admin] Improve partitioned-topic condition evaluation

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionBuilderImpl.java
If the transaction build fails, the `Success to new txn` still is printed. This is an incorrect log and will make users confused.
* Print success log only if the transaction build successfully.
> [fix][txn] Fix the incorrect log of Transaction Builder

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStore.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreFactory.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/TableViewLoadDataStoreImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeightTest.java
This PR should not impact the existing broker load balance behavior.
For the PIP-192 project, this PR
* Implemented load data store.
* Added units test.
PR in forked repository: https://github.com/Demogorgon314/pulsar/pull/6
> [improve][broker] PIP-192: Implement load data store

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
Calling synchronous methods in an async call chain could cause deadlocks and poor performance.
Fix an issue in PerrsistentTopicsBase's internalSetReplicationClusters method
- use async calls
> [fix][broker] Remove synchronous method call in async call chain in PersistentTopicsBase

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
Calling synchronous methods in an async call chain could cause deadlocks and poor performance.
Fix an issue in NamespacesBase#internalDeleteNamespaceBundleAsync.
- replace `validateNamespaceBundleOwnership` with `validateNamespaceBundleOwnershipAsync`
> [fix][broker] Replace sync method in NamespacesBase#internalDeleteNamespaceBundleAsync

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
- when a failure happens, the entry (Netty bytebuf) isn't properly released in ServerCnx#handleLastMessageIdFromCompactedLedger
Do the release in a finally block.
> [fix][broker] Release Netty buffer in finally block in ServerCnx#handleLastMessageIdFromCompactedLedger

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
- `isNamespaceReplicated` method call is synchronous and it's used as part of an async call chain in `AdminResource#internalCreatePartitionedTopic`.
- calling synchronous methods in an async call chain could cause deadlocks and poor performance. 
- replace with asynchronous calls and make it explicit that creating topics to replicated clusters happens in the background
- add proper logging for creation of topics in the replicated clusters
> [fix][broker] Replace sync call in async call chain of AdminResource#internalCreatePartitionedTopic

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicEventsDispatcher.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicEventsListener.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/TopicEventsListenerTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerTestBase.java
Topic events for KOP
PIP-241: https://github.com/apache/pulsar/issues/19224
Added TopicEventsListener interface, topic events dispatching for the BrokerService
This change added unit tests
Added applicable JavaDoc
PR in forked repository: https://github.com/dlg99/pulsar/pull/7
> [improve] PIP-241: add TopicEventListener / topic events for the BrokerService

- buildtools/src/main/resources/pulsar/checkstyle.xml
- pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java
- pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicyTest.java
- pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/BrokerFilter.java
Following the [Code of Conduct](https://www.apache.org/foundation/policies/conduct), terms such as `blacklist`/`whitelist` should be avoided.
The underlying assumption of the whitelist/blacklist metaphor is that white = good and black = bad.
It is easy to find other terms that are more descriptive and more inclusive.
Replace `blacklisted` by `excluded`, `whitelisted` by `allowed`
PR in forked repository: https://github.com/cbornet/pulsar/pull/12
> [cleanup][broker] Remove references to blacklist/whitelist

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/RoundRobinBrokerSelector.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerStrategyTest.java
Added a simple RoundRobin logic to select brokers for bundle ownership. This simple selector can help distribute the bundle load when there are many concurrent lookup requests(especially useful for performance tests where most lookups happen at the beginning of tests).
Added RoundRobinBrokerSelector and its unit test.
- *Added an unit test to cover RoundRobinBrokerSelector*
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/22
> [improve][broker] Added RoundRobinBrokerSelector

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
Cherry-pick https://github.com/apache/pulsar/pull/17123
*(or)*
*(or)*
*(example:)*
> [fix][broker] Pass subscriptionName to auth service (#17123)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/BrokerInterceptorWithClassLoader.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/BrokerInterceptors.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/ExceptionsBrokerInterceptor.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/ExceptionsBrokerInterceptorTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
Fixes #19146 
see #19146 
catch exception for brokerInterceptor
> [fix][broker] catch exception for brokerInterceptor

- conf/functions_log4j2.xml
Fixes #18861
*(or)*
*(or)*
*(example:)*
> [fix][fn] log4j root level

- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyClientCnx.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java
Cherry pick https://github.com/apache/pulsar/pull/19540 to branch 2.11
> [branch-2.11][fix][proxy] Fix using wrong client version in pulsar proxy

- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyClientCnx.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
- pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java
Cherry pick https://github.com/apache/pulsar/pull/19540 to branch 2.11
> [branch-2.10][fix][proxy] Fix using wrong client version in pulsar proxy

- pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionLocalRunTest.java
- pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/functions/FunctionConfig.java
- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
- pulsar-functions/instance/src/main/python/python_instance.py
- pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/pojo/AvroTestObject.java
- pulsar-functions/python-examples/avro_schema_test_function.py
- pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTestBase.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarFunctionsJavaTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/python/PulsarFunctionsPythonTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/utils/CommandGenerator.java
Fixes #10114
Python instance doesn't support schema yet
Add schema support for python instance
- `org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest`
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/2
> [improve][fn] Support schema in python instance

- pulsar-functions/instance/src/main/python/python_instance.py
Fixes #18626
Python instance doesn't support e2e encryption yet
Add e2e encryption support
- *org.apache.pulsar.tests.integration.functions.python.PulsarFunctionsPythonTest*
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/4
> [improve][fn] Support e2e cryption in python instance 

- distribution/server/src/assemble/LICENSE.bin.txt
- pulsar-sql/presto-distribution/LICENSE
Fix check License which is caused by cherry-picked https://github.com/apache/pulsar/pull/19417
*(or)*
*(or)*
*(example:)*
> [branch-2.10][build]Fix check License

- managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsReaderImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderImpl.java
The branch-2.9 build failed, refer to: https://github.com/apache/pulsar/actions/runs/4280465072/jobs/7452270803
Fix the build
> [Branch-2.9] [Build] Fix branch-2.9 build failed

- pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/BucketDelayedDeliveryTrackerFactory.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/ImmutableBucket.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/BucketDelayedDeliveryTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java
PIP: #16763
The `getRemainSnapshotSegment` should load data from nextSegmentEntryId to lastSegmentEntryId otherwise, the tracker will record replicated index.
* Fix merge issues
* Improve test
* Start bucketSnapshotStorage
* Fix delayedDeliveryMaxTimeStepPerBucketSnapshotSegmentSeconds unit
* Fix deadlock when clear bucket snapshot
*(or)*
*(or)*
*(example:)*
> [fix][broker] Fix BucketDelayedDeliveryTracker merge issues

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-sql/presto-distribution/LICENSE
Error 1:
```
Error:  Failures: 
Error:  org.apache.pulsar.broker.service.BrokerServiceTest.testGetTopic(org.apache.pulsar.broker.service.BrokerServiceTest)
[INFO]   Run 1: PASS
Error:    Run 2: BrokerServiceTest.testGetTopic:1492 expected [0] but found [1]
[INFO] 
```
Error 2:
```
leveldb-0.10.jar unaccounted for in lib/presto/LICENSE
leveldb-api-0.10.jar unaccounted for in lib/presto/LICENSE
leveldb-0.[12](https://github.com/apache/pulsar/actions/runs/4239032335/jobs/7399965467#step:11:13).jar mentioned in lib/presto/LICENSE, but not bundled
leveldb-api-0.12.jar mentioned in lib/presto/LICENSE, but not bundled
```
- Fix test
- Fix presto license
> [fix][ci][branch-2.11] Fix broken CI

- pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/PrometheusMetricsProvider.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/tools/LoadReportCommand.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/util/ExecutorProvider.java
- pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/InstanceCache.java
- pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/ClusterServiceCoordinator.java
> [cherry-pick][branch-2.9] Add UncaughtExceptionHandler for every thread pool (#18211)

- conf/broker.conf
- conf/proxy.conf
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/PulsarResources.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyAuthenticationTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyAuthorizationTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyConfigurationTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyIdleTimeoutTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPingTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTlsTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeWithoutZKTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/v1/V1_ProxyAuthenticationTest.java
- pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java
- pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Worker.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java
- pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java
Fixes #xyz
PIP: #xyz 
cherry-pick from #19156
*(or)*
*(or)*
*(example:)*
> [fix][branch-2.9] Support zookeeper read-only config

- pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java
- pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStore.java
Cherry-pick: https://github.com/apache/pulsar/pull/19201
PR in forked repository: https://github.com/thetumbled/pulsar/pull/16
> [cherry-pick][branch-2.9]  fix txn coordinator recover handle committing and aborting txn race condition. #19201

- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java
fix the `create-subscription` command `--subscription`  description.
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/yangl/pulsar/pull/20
> [fix][admin] fix create-subscription command --subscription description

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
> [cherry-pick][branch-2.9] Fix race condition while updating partition number (#19199)

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
Fixes #xyz
PIP: #xyz 
BookKeeper 4.14.7 has been released and it contains a lot of notable bug fixes. We need to upgrade the BookKeeper dependency from 4.14.5 to 4.14.7.
BookKeeper release notes can be found:
https://github.com/apache/bookkeeper/releases
Upgrade BookKeeper dependency from 4.14.5 to 4.14.7
> [improve][branch-2.9]upgrade the bookkeeper version to 4.14.7

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorAdminTlsTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorAdminTlsWithKeyStoreTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java
> [fix][broker][branch-2.11] Fix geo-replication admin

- src/get-project-version.py
- src/stage-release.sh
1. Upgrade python to python3
2. Remove the cpp-related command
> [fix][cli][branch-2.9] Fix release tool

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerStrategy.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerStrategyTest.java
Same problem as [PR19560](https://github.com/apache/pulsar/pull/19560)
When a broker is no longer active, delete its load information
https://github.com/315157973/pulsar/pull/7
> [fix][broker] Fixed history load not releasing

- buildtools/pom.xml
- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-metadata/src/test/java/org/apache/pulsar/metadata/coordination/impl/LeaderElectionImplTest.java
- pulsar-sql/presto-distribution/LICENSE
> [cherry-pick][branch-2.9] Upgrade Netty to 4.1.87.Final (#19417)

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicListWatcher.java
Fix topic list watcher fail log
Correct topic list watcher fail log
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/32
> [fix][client] Fix topic list watcher fail log

- pulsar-client/src/main/java/org/apache/pulsar/client/util/ExecutorProvider.java
The original fix is https://github.com/apache/pulsar/pull/18268.
But after the fix is cherry-picked, the fix is overridden when resolving
conflicts for cherry-pick https://github.com/apache/pulsar/pull/18211.
Return the local thread variables in the `newThread`.
*(or)*
*(or)*
*(example:)*
> [fix][client][branch-2.10]Return local thread for the `newThread`

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannel.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/AntiAffinityGroupPolicyFilter.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/policies/AntiAffinityGroupPolicyHelper.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/AntiAffinityNamespaceGroupExtensionTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/AntiAffinityNamespaceGroupTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/AntiAffinityNamespaceGroupExtensionTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java
We need to support AntiAffinityGroupPolicy in Load Manager Extension as well.
This PR 
- added AntiAffinityGroupPolicyFilter used in the broker assignment logic.
- added AntiAffinityGroupPolicyHelper that is passed to TransferShedder and AntiAffinityGroupPolicyFilter
- modified LoadManagerShared.filterAntiAffinityGroupOwnedBrokers and LoadManagerShared.getAntiAffinityNamespaceOwnedBrokers to accept the bundle ownership data from the Load Manager Extension.
- moved ModularLoadManagerImpl.refreshBrokerToFailureDomainMap(..) to LoadManager.refreshBrokerToFailureDomainMap(..) to reuse it in ExtensibleLoadManagerImpl.
- modified AntiAffinityNamespaceGroupTest to …
> [improve][broker] PIP-192 Supports AntiAffinityGroupPolicy

- wiki/proposals/PIP.md
> [fix][doc] Amend PIP voting process description

- README.md
Wanted to contribute to the community .And helping makes me feel better.
Modified the link in crypto section of the readme file.
*(or)*
*(or)*
*(example:)*
> [improve][doc] enhancement of link

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java
PR that may be relevant: https://github.com/apache/pulsar/pull/10367
There is no need to double-check whether the type of the existing schema is different from that of the new schema.
https://github.com/apache/pulsar/blob/e973388eb77f226e0546f88c87821f8c7ee26281/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java#L468-L480
https://github.com/apache/pulsar/blob/e973388eb77f226e0546f88c87821f8c7ee26281/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java#L349-L363
Remove type checks for existing schemas and new schemas outside `org.apache.pulsar.broker.service.schema.SchemaRegistryServiceImpl#checkCompatible(SchemaAndMetadata, SchemaData, SchemaCompatibilityStrategy)`. And check at the beginning in …
> [cleanup][broker] Remove duplicate code in the SchemaRegistryServiceImpl that checks for existing schema and new schema types

- distribution/server/src/assemble/LICENSE.bin.txt
- distribution/shell/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
Fixes #xyz
PIP: #xyz 
Upgrade bookkeeper to 4.15.4.
Change bookkeeper version to 4.15.4
*(or)*
*(or)*
*(example:)*
> [improve] Upgrade bookkeeper to 4.15.4

- .github/changes-filter.yaml
- .idea/icon.svg
> [improve][misc] Add idea icon

- pulsar-common/src/main/java/org/apache/pulsar/common/util/FutureUtil.java
- pulsar-common/src/test/java/org/apache/pulsar/common/util/FutureUtilTest.java
- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/LockManagerImpl.java
- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/ResourceLockImpl.java
(cherry picked from commit https://github.com/apache/pulsar/commit/2637bda91d46f443762b22ac9963935725af2c8a)
> [fix][meta] Follow up #19817, Fix race condition between ResourceLock update and invalidation

- pulsar-functions/instance/src/main/python/contextimpl.py
- pulsar-functions/instance/src/main/python/python_instance.py
- pulsar-functions/instance/src/main/python/python_instance_main.py
- pulsar-functions/instance/src/test/python/test_python_instance.py
Fixes #18903 
Make pulsar python functions support to set `processingGuarantees` to `EFFECTIVELY_ONCE`
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/tpiperatgod/pulsar/pull/9
> [improve][fn] Support processingGuarantees "EFFECTIVELY_ONCE" in python function 

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
Cherry-pick the https://github.com/apache/pulsar/pull/17033 to make the namespace with many partition topics can be deleted successfully.
*(or)*
*(or)*
*(example:)*
> [improve][admin][branch-2.10] Unset namespace policy to improve deleting namespace (#17033)

- pom.xml
While looking at some reflection related code, stumbled upon the library version and released that there is a new version that has fixes for various CVEs
Upgraded `org.reflections-reflections` library from `0.9.11` to `0.10.2`.
This change is a trivial rework.
PR in forked repository: [https://github.com/abhilashmandaliya/pulsar](https://github.com/abhilashmandaliya/pulsar/tree/patch-1)
> [improve][io][broker] Updated org.reflections-reflections library version

- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ProducerBuilder.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerBuilderImpl.java
- pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerBuilderImplTest.java
This closes https://github.com/apache/pulsar/issues/19139.
It's a lightweight feature alignment. Since it somehow touches public API, I don't know if it requires a PIP. It may not be, just trivial.
Support configure MessageCrypto in ProducerBuilder.
We already test this field but never pass or expose the config:
https://github.com/apache/pulsar/blob/32ad90606062c1eda660037e6277253b35d4a1e6/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L207-L219
Trivial.
Maybe I should update some doc, but I'm not sure where is related doc.
> [feat][client] Support configure MessageCrypto in ProducerBuilder

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java
- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/intercept/ManagedLedgerInterceptor.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/MangedLedgerInterceptorImplTest.java
- pulsar-common/src/main/java/org/apache/pulsar/common/intercept/AppendIndexMetadataInterceptor.java
Cherry-pick #19727 to branch-2.9
> [branch-2.9][fix][broker] Fix index generator is not rollback after entries are failed added

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java
- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/intercept/ManagedLedgerInterceptor.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/MangedLedgerInterceptorImplTest.java
- pulsar-common/src/main/java/org/apache/pulsar/common/intercept/AppendIndexMetadataInterceptor.java
Cherry-pick  #19727 to branch-2.8
> [branch-2.8][fix][broker] Fix index generator is not rollback after entries are failed added. 

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java
- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/intercept/ManagedLedgerInterceptor.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/MangedLedgerInterceptorImplTest.java
- pulsar-common/src/main/java/org/apache/pulsar/common/intercept/AppendIndexMetadataInterceptor.java
Cherry-pick #19727 to branch-2.10
> [branch-2.10][fix][broker] Fix index generator is not rollback after entries are failed added

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
There are some cases where an error is returned when trying to expire messages using the pulsar-admin command. For example, when there are no messages in the backlog.
```sh
$ ./bin/pulsar-admin topics expire-messages -s sub1 -t 1m persistent://public/default/massakam
2023-03-09T16:07:01,485+0900 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/public/default/massakam/subscription/sub1/expireMessages/60] Failed to perform http post request: javax.ws.rs.ClientErrorException: HTTP 409 {"reason":"Expire message by timestamp not issued on topic persistent://public/default/massakam for subscription sub1 due to ongoing message expiration not finished or subscription almost catch  up. If it's performed on a partitioned …
```
> [refactor][broker] Suppress error logging when message expiration fails

- distribution/server/src/assemble/LICENSE.bin.txt
- distribution/shell/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/LongAdderCounter.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/SameThreadOrderedSafeExecutor.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
- pulsar-sql/presto-distribution/LICENSE
- pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorMetricsTracker.java
- testmocks/src/main/java/org/apache/bookkeeper/client/TestStatsProvider.java
Fixes #xyz
PIP: #xyz 
Upgrade the BookKeeper dependency to 4.16.0
*(or)*
*(or)*
*(example:)*
> [improve] [broker] Upgrade the BookKeeper dependency to 4.16.0

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
Fixes #xyz
PIP: #xyz 
BookKeeper has upgraded the RocksDB dependency to 7.9.2, related discussion:
https://lists.apache.org/thread/8j90y4vrvgz1nvt5pb0xdjjy3o8z57z7
https://github.com/apache/bookkeeper/issues/3734
However, Pulsar also has the RocksDB dependency and it will override the BookKeeper's RocksDB dependency version. It will lead to the release package still using the old RocksDB version (6.29.4.1)
Upgrade the Pulsar's RocksDB dependency to 7.9.2 to keep sync with the BookKeeper's RocksDB dependency.
*(or)*
*(or)*
This change added tests and can be verified …
> Upgrade the RocksDB version to 7.9.2 to keep sync with BookKeeper's RocksDB dependency

- .github/workflows/ci-owasp-dependency-check.yaml
We just created branch-3.0
PR in forked repository: https://github.com/cbornet/pulsar/pull/13
> [improve][ci]Add branch-3.0 to owasp checks

- wiki/proposals/PIP.md
Add a link to see existing PIP issues so you can select a number
> [fix][doc] Add link to PIP proposal

- distribution/server/src/assemble/LICENSE.bin.txt
- distribution/shell/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
Fixes #xyz
PIP: #xyz 
Upgrade the BookKeeper dependency to 4.16.1
*(or)*
*(or)*
*(example:)*
> [improve] [broker] Upgrade the BookKeeper dependency to 4.16.1

- pom.xml
See CVE-2023-20863 and https://github.com/apache/pulsar/actions/runs/4719451944/jobs/8392825486?pr=20114.
> [fix][sec] spring.version=5.3.27 to fix CVE-2023-20863

- conf/broker.conf
- conf/standalone.conf
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java
Support disabling delayed bucket merging.
- Support disabling delayed bucket merging.
> [improve][broker] Support disabling delayed bucket merging.

- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
- pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java
Fixes #19970
Fix the return value of getPartitionedStats doesn't contain subscription type
handle `type` field in `SubscriptionStatsImpl#add` and `SubscriptionStatsImpl#reset`
PR in forked repository: https://github.com/1Jack2/pulsar/pull/3
> [fix][broker] Fix Return value of getPartitionedStats doesn't contain subscription type

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupConfigListener.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarStats.java
Use bulk operation instead of iteration
Use putAll,addAll method instead of forEach
> [improve][broker] Use bulk operation instead of iteration

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
…cksDB version
Fixes #xyz
PIP: #xyz 
Upgrade rocksDB version to 6.29.4.1 to keep in sync with BookKeeper's RocksDB version
*(or)*
*(or)*
*(example:)*
> [fix] [broker] [branch-2.9] Upgrade rocksDB version to 6.29.4.1 to keep in sync with BookKeeper's RocksDB version

- .github/workflows/ci-go-functions.yaml
- .github/workflows/pulsar-ci-flaky.yaml
- .github/workflows/pulsar-ci.yaml
We need to enable CI tests for all PRs on the branch-3.0
> [improve][ci][branch-3.0] Enable CI tests for PRs

- buildtools/pom.xml
- distribution/server/src/assemble/LICENSE.bin.txt
- distribution/shell/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-broker-auth-oidc/pom.xml
- pulsar-functions/runtime/pom.xml
- pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/auth/KubernetesSecretsTokenAuthProvider.java
- pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java
- pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java
- pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/auth/KubernetesSecretsTokenAuthProviderTest.java
- pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactoryTest.java
- pulsar-functions/secrets/pom.xml
- pulsar-io/flume/pom.xml
- pulsar-io/kafka-connect-adaptor/pom.xml
- pulsar-sql/presto-distribution/LICENSE
- src/owasp-dependency-check-suppressions.xml
Upgrade dependency to fix CVE.
> [improve][build] Upgrade dependency to fix CVE.

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
- pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerImplTest.java
This is a follow-up for https://github.com/apache/pulsar/pull/20242.
Please review in commits. If it's accepted, please merge by `rebase and merge` so that we can pick the second commit without style changes.
Revert unrelated style changes and use `IllegalStateException` over `CancellationException`.
AS DESCRIBED MOVE.
`testSeekAsyncInternal`
> [fix][client] thread-safe seek

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LinuxBrokerHostUsageImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/api/v1/V1_ProducerConsumerTest.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/Reader.java
> [fix][doc] Correcting spelling mistakes

- pom.xml
Recently, the latest version of Hadoop and HBase were released, 3.3.5 and 2.4.16 respectively. This PR upgrades them to ensure that the current Pulsar IOs work with them.
Updated the version number of those dependencies in pom.xml.
This change is already covered by existing tests, such as the tests under pulsar-io/hdfs3/src/test/java and pulsar-io/hbase/src/test/java.
- Hadoop and HBase were upgraded to 3.3.5 and 2.4.16 respectively.
PR in forked repository: https://github.com/sekikn/incubator-pulsar/pull/12 (failed on BROKER_GROUP_1 but seems to be unrelated to this fix)
> [improve][io] Upgrade Hadoop and HBase versions

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
My repository. https://github.com/horizonzy/pulsar/pull/14
Fixes #xyz
PIP: #xyz 
Update the zookeeper version to 3.6.4 for https://issues.apache.org/jira/browse/ZOOKEEPER-3988
*(or)*
*(or)*
*(example:)*
> [Branch-2.9] [fix] update the zookeeper version to 3.6.4

- pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawReaderTest.java
Currently, we lost the BrokerEntryMetadata when rebatchMessage, it is used to copy data from the original topic to the compacted topic, so I think we should copy it.
Copy BrokerEntryMetadata when rebatchMessage, if it exists.
*(or)*
*(or)*
*(example:)*
> [improve][broker] Copy BrokerEntryMetadata when rebatchMessage

- pom.xml
Building the pulsar-all docker image is very slow. Most of the time is spent in nar file creation.
Update nar maven plugin to 1.5.0
Contains fixes such as
- https://issues.apache.org/jira/browse/NIFI-10599
- https://issues.apache.org/jira/browse/NIFI-11217
> [fix][ci] Update nar maven plugin version to fix excessive downloads

- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/SegmentAbortedTxnProcessorTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTestBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionBufferCloseTest.java
1. When create PROCESSOR_TOPIC, the snapshot segment is not enable.
2. The testSnapshotProcessorUpgrade should use different namespace.
*(or)*
*(or)*
*(example:)*
> [fix][test] Fix SegmentAbortedTxnProcessorTest

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PackagesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java
After #20456, AuthorizationProvider has supported revoking the permission, so make sure all the revoking calls point to AuthorizationProvider.
> [improve][admin] Using AuthorizationService to revoke the permissions.

- pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java
- pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java
This PR is a combination of https://github.com/apache/pulsar/pull/20482 and https://github.com/apache/pulsar/pull/20513 because cherry picking those PRs produced too many conflicts.
* Made the same addition as the source PRs, though the code has changed a bit, so I had to make a few extra changes.
> [fix][fn] Configure pulsar admin for TLS

- pip/TEMPLATE.md
Fix typo in pip template.
`Compatability` -> `Compatibility`
PR in forked repository:  N/A
> [fix][misc] Fix typo in  pip template 

- pom.xml
Removed unused reload4j define
PR in forked repository: https://github.com/Shoothzj/pulsar/pull/4
> [cleanup][build] Removed unused reload4j define

- pip/pip-274.md
> [pip][design] PIP-276: Add metric `pulsar_topic_load_times`

- .github/changes-filter.yaml
Skip test for modification of pip directory, including markdown and image.
> [improve][ci] Skip test for pip directory

- tests/docker-images/latest-version-image/Dockerfile
We don't need to download and configure Golang manually. We don't depend on any build artifacts but function-go's source.
Let's simplify the Dockerfile.
Use golang base image to build function-go examples.
Should be a seamless refactor.
> [improve][build] Build function-go in golang image

- pip/TEMPLATE.md
Clarify images should be avoided in PIPs
> [improve][doc] Update PIP TEMPLATE.md: Clarify images

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
[PIP:276](https://github.com/apache/pulsar/pull/20627)
reformat property,for a http header name cannot contain the following prohibited characters: =,;: \t\r\n\v\f
for example:
{"city=shanghai":"tag"}
when we run `bin/pulsar-admin topics get-message-by-id `, it will throw exception, the exception is:
`Reason: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: a header name cannot contain the following prohibited characters: =,;: \t\r\n\v\f: =`
when generate response with entry, reformat property in http header …
> [fix][broker] Reformat property in generateResponseWithEntry

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PulsarCompactorSubscription.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactionServiceFactory.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/PulsarCompactionServiceFactory.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/PulsarTopicCompactionService.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/TopicCompactionService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/compaction/TopicCompactionServiceTest.java
PIP: #20624 
* Add interface `TopicCompactionService` and `CompactionServiceFactory`
* Implement `PulsarCompactionServiceFactory` and `PulsarTopicCompactionService`
* Add `compactionServiceFactoryClassName` config in the ServiceConfiguration
* Rename `CompactorSubscription` to `PulsarCompactorSubscription`.
* Add test for `PulsarTopicCompactionService`
*(or)*
*(or)*
*(example:)*
*If the …
> [feat][broker][PIP-278] Support pluggable topic compaction service - part1

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
1.   The topics have been deleted twice.
https://github.com/apache/pulsar/blob/90369a0da639d43c841974d08ab77faeb7ba5cdd/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L342-L355
2. Similar to https://github.com/apache/pulsar/pull/20683
We need to do Deduplication.
*(or)*
*(or)*
*(example:)*
PR in …
> [fix][branch-2.10] Fix duplicated deleting topics

- distribution/server/src/assemble/LICENSE.bin.txt
- distribution/shell/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
Fixes #xyz
PIP: #xyz 
Upgrade bookkeeepr to 4.16.2
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/zymap/pulsar/pull/48
> [improve][broker] Upgrade bookkeeper to 4.16.2

- conf/bookkeeper.conf
- conf/broker.conf
- conf/proxy.conf
- conf/standalone.conf
- conf/zookeeper.conf
Fixes #xyz
PIP: #xyz 
Corrected all spelling mistakes I found in the config directory.
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/daziz/pulsar.git
> [fix][doc] Correcting spelling mistakes in config

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
The `ServerCnx#closeProducer` method must be called from the `ServerCnx`'s netty executor because it modifies a `HashMap`.
* Add an `assert` call to verify the correct thread calls the `closeProducer` method
* Fix the cluster migration code that calls the `closeProducer` method
The `ClusterMigrationTest` covers this change. It fails without the complete change.
> [fix][broker] call ServerCnx#closeProducer from correct thread

- .github/labeler.yml
- .github/workflows/labeler.yml
This closes https://github.com/apache/pulsar/issues/20712.
Following the actions document - https://github.com/actions/labeler
> [feat][ci] Label PIP request

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
becase -> because
*(example:)*
> [fix][broker] typo in ServerCnx.java

- pulsar-broker-auth-athenz/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderAthenzTest.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsController.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilter.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/TransactionBuffer.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SnapshotSegmentAbortedTxnProcessorImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApi2Test.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ResendRequestTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/api/v1/V1_ProducerConsumerTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PulsarTestClient.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/UnAcknowledgedMessagesTimeoutTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/stats/client/PulsarBrokerStatsClientTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/zookeeper/ZookeeperServerTest.java
Fixes #xyz
PIP: #xyz 
Corrected all spelling mistakes I found in the pulsar-broker module.
*(or)*
*(or)*
*(example:)*
> [fix][doc]Correcting spelling mistakes in the pulsar-broker module

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageKeyBasedContainer.java
Fix compatibility issue and test branch 2.10.
*(or)*
*(or)*
*(example:)*
> [fix][build]Fix compatibility issue cause by #20819

- pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Record.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/AvroSchemaCache.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/ByteBufferSchemaWrapper.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/BytesWithKafkaSchema.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSink.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaBytesSink.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaBytesSource.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaSinkConfig.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaSourceConfig.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaStringSource.java
- pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/ByteBufferSchemaWrapperTest.java
- pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/KafkaBytesSourceTest.java
- pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/sink/KafkaAbstractSinkTest.java
- pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java
PR in forked repository: https://github.com/cbornet/pulsar/pull/17
> [cleanup][io] Cleanup Kafka connector

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/HierarchyTopicAutoCreationTest.java
> [branch-2.10][fix][broker] Inconsistent behaviour for topic auto_creation

- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SubscribeRateLimiter.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/lookup/http/HttpTopicLookupv2Test.java
> [branch-2.10][fix][broker] Fix inconsensus namespace policies by getPoliciesIfCached

- pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSchemas.java
This closes https://github.com/apache/pulsar/issues/10578.
Screenshot -
> [improve][cli] Better error message for pulsar-admin schema upload

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/BookiesApiTest.java
Fixes #20871
Fix http error message of Bookie rack placement config API when bookie-rack is not configured.
Fix http error message of Bookie rack placement config API when bookie-rack is not configured.
PR in forked repository: https://github.com/1Jack2/pulsar/pull/4
> [fix][broker] Fix http error message of Bookie rack placement config API when bookie-rack is not configured.

- pom.xml
Lombok 1.8.28 brings in the support for compiling with JDK 20.
> [fix] Lombok 1.8.28

- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ClientSideEncryptionWssConsumer.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ClientSideEncryptionWssProducer.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/CryptoKeyReaderForTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeClientSideEncryptionTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/WssClientSideEncryptUtils.java
- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/DummyCryptoKeyReaderImpl.java
- pulsar-client-messagecrypto-bc/src/main/java/org/apache/pulsar/client/impl/crypto/MessageCryptoBc.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ProducerHandler.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/data/ConsumerMessage.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/data/ProducerMessage.java
- pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WSSDummyMessageCryptoImpl.java
- pulsar-websocket/src/test/java/org/apache/pulsar/websocket/ProducerHandlerTest.java
See https://github.com/apache/pulsar/pull/20923
> [feat][ws] PIP-290 Make WSS support E2E encryption

- README.md
We had a contributor expose a vulnerability in public in a GitHub issue.
Added to the main readme a level 2 heading and stronger language.
Read Me change cannot impact CI
> [improve][doc] Add stronger Security Policy Language to README

- pip/pip-264.md
Add PIP-264 (copied from https://github.com/apache/pulsar/issues/20197)
> [improve][pip] PIP-264: Enhanced OTel-based metric system

- pip/pip-296.md
Adding the `getLastMessageIds` Interface to Reader. 
Implement getLastMessageIds API for Reader 
*(or)*
*(or)*
*(example:)*
> [improve][pip] Implement getLastMessageIds API for Reader

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
> [fix][broker] Fix unsubscribe non-durable subscription error

- pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java
- pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicyTest.java
This is a cherry-pick commit for #21096.
> [branch-2.10] [fix] [broker] Fix isolated group not work problem.

- pip/pip-297.md
This PIP is to improve the current function exception handler. It will be applied to both Pulsar Function and Pulsar IO Connector.
For more details, please refer to `pip-297.md`
> [improve][pip] PIP-297: Support terminating Function & Connector with the fatal exception

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageChunkingTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Fixes https://github.com/apache/pulsar/actions/runs/5934883964/job/16092673164?pr=21043
Fix the flaky test.
The root cause is `doAcknowledge` is an async method.
The chunk 1 may not be acked when call `redeliverUnacknowledgedMessages`.
```
doAcknowledge(msgId, AckType.Individual, Collections.emptyMap(), null);
```
*(or)*
*(or)*
*(example:)* …
> [fix][test]Flaky test testMaxPendingChunkMessages

- distribution/server/src/assemble/LICENSE.bin.txt
- distribution/shell/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
Fixes #xyz
PIP: #xyz 
Upgrade bookie to 4.16.3.
*(or)*
*(or)*
*(example:)*
> [improve][broker] Upgrade bookkeeper to 4.16.3

- conf/entry_location_rocksdb.conf
Fixes #xyz
PIP: #xyz 
Sync fix from BookKeeper: https://github.com/apache/bookkeeper/pull/3860
*(or)*
*(or)*
*(example:)*
> [fix] [bookie] Fix RocksDB configuration

- distribution/server/src/assemble/LICENSE.bin.txt
> [fix][ci] Fix missing binary license

- .github/workflows/pulsar-ci.yaml
> [fix][ci] Enable CI for branch-3.1

- .asf.yaml
- .github/workflows/ci-owasp-dependency-check.yaml
Add branch protection to the new branch-3.1.
> [improve][ci] Protect branch-3.1

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedderTest.java
Backport https://github.com/apache/pulsar/pull/21025
> [fix][broker][branch-3.1] Backport fix UniformLoadShedder selecet wrong overloadbroker and underloadbroker

- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerUnderreplicationManager.java
- pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/LedgerUnderreplicationManagerTest.java
> [fix][bk] Improve to the ReplicaitonWorker performance by deleting invalid underreplication nodes

- pom.xml
> [fix][ci] Fix license check issue

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedderTest.java
Backport https://github.com/apache/pulsar/pull/21025
> [fix][broker] Backport fix UniformLoadShedder selecet wrong overloadbroker and underloadbroker 

- pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java
- pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
Cherry-pick #21081 into branch-3.0
> [fix][broker][branch-3.0] Fix write duplicate entries into the compacted ledger after RawReader reconnects (#21081)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedderTest.java
> [fix][broker] Backport  fix UniformLoadShedder selecet wrong overloadbroker and underloadbroker

- pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClient.java
- pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
- pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchAuthTests.java
- pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientSslTests.java
- pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java
- pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkTests.java
- pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/opensearch/OpenSearchClientSslTests.java
We have introduced the `SinkContext.fatal` method in https://github.com/apache/pulsar/pull/21143
This PR use this fatal method to handle the elastic sink connector exception correctly.
- Use `SinkContext.fatal` to throw connector exception
- Add state to the ElasticSearchClient
*(or)*
*(or)*
*(example:)*
> [improve][io] Use `SinkContext.fatal` in elastic search connector

- pom.xml
- pulsar-metadata/pom.xml
- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/AbstractHierarchicalLedgerManager.java
- pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
> [fix][auto-recovery] [branch-2.11] Fix metadata store deadlock due to BookkeeperInternalCallbacks.Processor 

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloader.java
- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/NullLedgerOffloader.java
- tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java
- tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloader.java
`getOffloadPolicies` should be better to return `OffloadPolicies` instead of `OffloadPoliciesImpl`.
Change `getOffloadPolicies` return value type.
This is a breaking change while the interface is marked as `Evolving`. I'd prefer to treat it as a mistake or tech debt to pay back. Implementations of `LedgerOffloader` should not be affected because Java's inheritance allows refinement. But if the application code receive the result of `getOffloadPolicies` as `OffloadPoliciesImpl`, they may now need a coercion.
> [improve][offload] Avoid implementation details leak on getOffloadPolicies return value

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
As discussed, https://lists.apache.org/list?dev@pulsar.apache.org:lte=1M:ConcurrentHashMap,
use ConcurrentHashMap in ServiceUnitStateChannel and avoid recursive update error to avoid any issues from the custom implementation of the hashmap.
- use ConcurrentHashMap in ServiceUnitStateChannel
- avoid recursive update error by removing map.remove inside computeIfAbsent.
> [improve][broker] use ConcurrentHashMap in ServiceUnitStateChannel and avoid recursive update error

- pulsar-metadata/pom.xml
- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerUnderreplicationManager.java
- pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
- pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/LedgerUnderreplicationManagerTest.java
> [fix] [auto-recovery] [branch-2.11] Fix PulsarLedgerUnderreplicationManager notify problem.

- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerAuditorManager.java
- pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
- pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AutoRecoveryMainTest.java
> [fix] [auto-recovery] [branch-2.11] Fix pulsar ledger auditor dead lock problem.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Subscription.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Fix some spelling mistakes in Subscription interface
Modify the interface name from `isSubsciptionMigrated` to `isSubscriptionMigrated`
> [fix][broker] Fix typos in Subscription interface

- pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
Fix AuditorLedgerCheckerTest flaky test.
> [fix][test] [branch-3.0] Fix AuditorLedgerCheckerTest flaky test.

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionBuilderImpl.java
Fix typos in doc for TransactionBuilderImpl class
`coorindator` => `coordinator`
> [fix][doc] Fix typos in TransactionBuilderImpl class

- pip/pip_307.md
Support subscribing multi topics for WebSocket
> [improve][pip] PIP-307: Support subscribing multi topics for WebSocket

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-sql/presto-distribution/LICENSE
Fix in-correct license definetion
> [fix] [build] [branch-3.0] Fix in-correct license definetion

- pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java
> [fix] [broker] [branch-2.11] Fix isolated group not work problem

- pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
Delete methods marked Lombok @Getter, they are using the same method signature, so it shouldn't have compatibility issues.
- Delete methods marked Lombok @Getter
> [cleanup][broker] Delete methods marked Lombok @Getter

- pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/BucketDelayedDeliveryTrackerFactory.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleLoadManagerImplTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/AntiAffinityNamespaceGroupExtensionTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MaxMessageSizeTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiRolesTokenAuthorizationProviderTest.java
There are thread leaks in tests.
Fix multiple thread leaks in Broker Group 1 unit tests.
> [fix][test] Fix multiple thread leaks in Broker Group 1 unit tests

- deployment/kubernetes/README.md
Fixes #21195 
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [fix][readme]update deploy-kubernetes url

- pulsar-broker/src/test/java/org/apache/pulsar/client/api/OrphanPersistentTopicTest.java
- `CompactionServiceFactory` was added by the feature PR https://github.com/apache/pulsar/pull/20645; it is not exists in `branch-3.0`.
- The test `testNoOrphanTopicIfInitFailed` was added by https://github.com/apache/pulsar/pull/21540
Since injecting an error for the test `testNoOrphanTopicIfInitFailed` without the class `CompactionServiceFactory` is too difficult, I want to remove this test.
Remove test `testNoOrphanTopicIfInitFailed`
> [fix] [build] [branch-3.0] Remove test testNoOrphanTopicIfInitFailed

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicUtils.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicUtilsTest.java
Cherry-pick #21465 into branch-3.1, and add a compatible method to avoid breaking branch-3.1
> [fix][broker][branch-3.1] Fix issue with consumer read uncommitted messages from compacted topic (#21465)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceUnloadingTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java
- pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolTest.java
Cherry-pick #21445 to branch-3.0
> [fix][broker] Fix namespace bundle stuck in unloading status (#21445)

- pip/pip-312.md
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [improve][pip] PIP-312: Use StateStoreProvider to manage state in Pulsar Functions endpoints

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherSingleActiveConsumer.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopic.java
- pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
Cherry-pick #21465 into branch-3.0
> [fix][broker][branch-3.0] Fix issue with consumer read uncommitted messages from compacted topic (#21465)

- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaSinkConfig.java
- pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaSourceConfig.java
sslTruststorePassword value contains the sensitive passwords. We need to mark it as a sensitive configuration field.
- Make `sslTruststorePassword` sensitive for the Kafka connector config
> [improve] Make `sslTruststorePassword` sensitive for the Kafka connector config

- pip/README.md
Some people didn't understand the "closing the vote" on step 8
Added an example that roughly describes what really goes on.
> [improve][docs] Added example to PIP process

- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
Fixes #21703
The root cause is that we increase the count  no matter the send error occurs.
Test should  send 50 msgs, but sent 49 msgs:
```
2023-12-07T06:50:49,933 - INFO  - [docker-java-stream-1337430181:DockerUtils$2@252] - DOCKER.exec(PerfToolTest-ianwu-zookeeper:bin/pulsar-perf produce -u pulsar://pulsar-proxy-pulsar-proxy:6650 -m 50 persistent://public/ns-hdannumd/testConsume-xwgdqllc-1701931838074): STDOUT: 2023-12-07T06:50:49,933+0000 [Thread-0] INFO  org.apache.pulsar.testclient.PerformanceProducer - Aggregated throughput stats --- 49 records sent --- 4.895 msg/s --- 0.038 Mbit/s
2023-12-07T06:50:43,602 - INFO  - [docker-java-stream-1337430181:DockerUtils$2@252] - DOCKER.exec(PerfToolTest-ianwu-zookeeper:bin/pulsar-perf produce -u pulsar://pulsar-proxy-pulsar-proxy:6650 -m 50 …
```
> [fix][test] Fix PerformanceProducer send count error

- pulsar-io/alluxio/pom.xml
- pulsar-io/alluxio/src/main/java/org/apache/pulsar/io/alluxio/sink/AlluxioSink.java
- pulsar-io/alluxio/src/test/java/org/apache/pulsar/io/alluxio/sink/AlluxioSinkTest.java
> [fix][build] Upgrade alluxio version to 2.9.3 to fix CVE-2023-38889

- pom.xml
> [improve][ci] Upgrade Aerospike java client to 4.5.0 to avoid CVE-2023-36480

- NOTICE
- distribution/server/src/assemble/NOTICE.bin.txt
- distribution/shell/src/assemble/NOTICE.bin.txt
It's a new year now.
Update copyright date from 2022 to 2024.
> [improve][build] Update copyright date

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [fix][broker] Fix typo

- pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/stats/ComponentStatsManager.java
Fixes #xyz
PIP: #xyz 
Some exceptions may have an empty messages, which makes it hard to know the exact error reason for pulsar functions
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/19
> [improve][fn] Show the class name of exceptions for pulsar functions

- pip/pip-326.md
Please see Background + Motivation section of proposed PIP document for details.
> [improve][pip] PIP-326: Create a BOM to ease dependency management

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java
Fix typos in doc for UniformLoadShedder class
1、fix typos: `msgThroughtput` => `msgThroughput`
2、fix errors in comments
> [fix][broker] Fix typos in UniformLoadShedder class

- pulsar-sql/presto-distribution/LICENSE
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [fix] [bk] [Branch-3.0] Fix the BookKeeper license

- .github/workflows/codeql.yaml
Enable GitHub CodeQL static code scanner to detect potentially vulnerable code in PRs and master branch.
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/merlimat/pulsar/pull/10
> [improve] Added CodeQL static scanner

- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
Fix the build issue from cherry-pick
> [fix] [ci] [branch-3.0] Fix the build issue from cherry-pick

- pip/pip-339.md
PIP-339: Introducing the --log-topic Option for Pulsar Sinks and Sources
Make Pulsar Sinks and Sources able to send logs to a Pulsar topic.
*(or)*
*(or)*
*(example:)*
> [improve][pip] PIP-339: Introducing the --log-topic Option for Pulsar Sinks and Sources

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreFactory.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/TableViewLoadDataStoreImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchMessageContainerImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java
PR: https://github.com/apache/pulsar/pull/22064
(cherry picked from commit 5a614e96406335715e7c8239cab812864702d3e7)
> [fix][broker][branch-3.0] Set ServiceUnitStateChannel topic compaction threshold explicitly, improve getOwnerAsync, and fix other bugs (#22064)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreFactory.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/TableViewLoadDataStoreImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchMessageContainerImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java
PR: https://github.com/apache/pulsar/pull/22064
cherry picked from commit 5a614e96406335715e7c8239cab812864702d3e7
> [fix][broker][branch-3.2] Set ServiceUnitStateChannel topic compaction threshold explicitly, improve getOwnerAsync, and fix other bugs (#22064)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java
Fixes https://github.com/apache/pulsar/issues/22119
PIP: #xyz 
Fix TopicTransactionBuffer potential thread safety issue.
Make all the read/write operations of `TopicTransactionBuffer#ongoingTxns` in `sync` scope.
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/dao-jun/pulsar/pull/7
> [fix][txn]Fix TopicTransactionBuffer potential thread safety issue

- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java
> [fix][build][branch-3.1] Fix compile issue in test

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplBaseTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplWithTransactionCoordinatorTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/messaging/MessagingSmokeTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarClusterTestBase.java
- tests/integration/src/test/resources/pulsar-messaging.xml
Cherry-picking https://github.com/apache/pulsar/pull/22139 into `branch-3.2`.
> [fix][broker][branch-3.2] Fix broker not starting when both transactions and the Extensible Load Manager are enabled

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
- pulsar-broker/src/test/java/org/apache/pulsar/compaction/GetLastMessageIdCompactedTest.java
cherry pick from: https://github.com/apache/pulsar/pull/21969
https://github.com/apache/pulsar/pull/21969#issuecomment-1967408666
> [fix] [branch-3.0] Fix reader stuck when read from compacted topic with read compact mode disable

- pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PulsarWorkerService.java
- pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
- pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
cherry-pick PR #22140
cherry picked from commit c7cedc6828e08765e6a14335bb5a00cf23f0cfa3
> [improve][fn][branch-3.0] Add missing "exception" argument to some `log.error` (#22140)

- pip/pip-324-Alpine Docker images.md
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [improve][pip] PIP-324: Alpine Docker images

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java
- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryMBeanImpl.java
- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerMBeanImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/DimensionStats.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/LongAdderCounter.java
- pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionRetentionTest.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ClientConfiguration.java
- pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ConsumerConfiguration.java
- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImpl.java
- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TransactionsImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/AutoClusterFailover.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ControlledClusterFailover.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderBuilderImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TypedMessageBuilderImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionBuilderImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/util/ObjectCache.java
- testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockBookKeeper.java
- testmocks/src/main/java/org/apache/bookkeeper/client/TestStatsProvider.java
Fix https://github.com/apache/pulsar/issues/22242
Revert "[fix][sec] Add a check for the input time value (apache#22023)"
*(or)*
*(or)*
*(example:)*
> [fix][sec]  Revert "[fix][sec] Add a check for the input time value (apache#22023)" 

- .github/workflows/pulsar-ci.yaml
Enable CI for branch-3.2
PR in forked repository: https://github.com/yaalsn/pulsar/pull/1
> [fix][ci] Enable CI for branch-3.2

- buildtools/pom.xml
- buildtools/src/main/resources/pulsar/checkstyle.xml
- pom.xml
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
- pulsar-common/src/main/java/org/apache/pulsar/common/tls/InetAddressUtils.java
- pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/LongPairSet.java
Fixes #22286
Upgrade checkstyle to 10.14.2 for support [IntelliJ checkstyle plugin@5.88](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea).
- Upgrade checkstyle from 8.37 to 10.14.2
> [improve][misc] Upgrade checkstyle to 10.14.2

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/api/TopicNameForInfiniteHttpCallGetSubscriptionsTest.java
Cherry-pick https://github.com/apache/pulsar/pull/21997
> [fix][broker][branch-2.11] Fast fix infinite HTTP call createSubscriptions caused by wrong topicName

- distribution/server/src/assemble/LICENSE.bin.txt
- distribution/shell/src/assemble/LICENSE.bin.txt
- pom.xml
Fixes #21421 
BookKeeper 4.16.5 has been released with some important fixes such as https://github.com/apache/bookkeeper/pull/4196.
Upgrade BookKeeper dependencies to 4.16.5
> [improve][misc] Upgrade to Bookkeeper 4.16.5

- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAuthZTest.java
Currently, the permission test of topic API only verifies the AuthAction but does not verify whether the topic operation meets expectations. This is a guarantee for other authorizationProvider implementations.
Add checker topic operation for topic API
*(or)*
*(or)*
*(example:)*
> [improve][test] Add topic operation checker for topic API

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
Fixes https://github.com/apache/pulsar/issues/22505
Add topic name to emitted error messages.
*(or)*
*(or)*
*(example:)*
> [improve][broker] Add topic name to emitted error messages.

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
Fix typos in `org.apache.pulsar.broker.service.Consumer` class
fix typos: `negtiveUnackedMsgsTimestamp` => `negativeUnackedMsgsTimestamp`
> [fix][broker] Fix typos in Consumer class

- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespaceAuthZTest.java
Complete the missing policy authentication test for namespace API.
*(or)*
*(or)*
*(example:)*
> [improve][test] Add policy authentication test for namespace API

- pom.xml
Fixes https://github.com/apache/pulsar/issues/22632
Avoid CVE-2024-21634
Upgrade aws-sdk version to 1.12.638
which avoids ion-java which caused the vulnerability.
> [fix][sec] Upgrade aws-sdk.version to avoid CVE-2024-21634

- pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/elastic/ElasticSearchJavaRestClient.java
- pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkTests.java
(cherry picked from commit efcedf6b0d4217db7e47efef3420eb61da282c50)
> [fix][io] Fix es index creation (#22654)

- docker/pulsar-all/pom.xml
- docker/pulsar/pom.xml
- pom.xml
Use `docker.skip.push` to decide whether to skip publishing.
See https://dmp.fabric8.io/#build-configuration
- Update `docker/pulsar/pom.xml` and `docker/pulsar-all/pom.xml`
> [improve][build] Improve docker-push

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
There are many warn logs ("Empty selected broker for ownership") when closing the last broker. However, this log should not be warn because it's expected.
- Remove the warning log when `selectBroker` returns an empty optional string because the following log "Overriding ownership" will reflect this case by showing the state is changed from Owned to Free.
- Use a functional programming style to replace `getOverrideInactiveBrokerStateData`, which uses Optional as a parameter. See discussion here: https://stackoverflow.com/questions/31922866/why-should-java-8s-optional-not-be-used-in-arguments
> [cleanup][broker] Remove warn logs when changing the state from Owned to Free (Extensible LB)

- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicationTxnTest.java
- Add a test to guarantee the TNX system topics will not be replicated
- Add a test to guarantee the messages that are in an ongoing TXN will not be replicated.
> [improve] [test] Add a test to guarantee the TNX topics will not be replicated

- docker/pulsar/Dockerfile
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [fix][build] Fix CVE-2024-2511 by upgrading to OpenSSL in docker image

- docker/pulsar/Dockerfile
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [fix][build] Fixed creation of `packages-storage` directory in docker image

- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/OxiaMetadataStore.java
For testing purposes, it's often useful to pass directly a mocked instance of client and wrap it with `MetadataStore` API.
*(or)*
*(or)*
*(example:)*
> [improve] Allow to construct Oxia metadata-store directly from a client instance

- docker/pulsar/Dockerfile
Upgrade `busybox` package in Alpine at build time to get latest version with fix.
*(or)*
*(or)*
*(example:)*
> [fix] Upgrade Alpine packages at build time to fix CVE-2023-4236

- managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImplTest.java
Fixes #22345
Actually, the ledger will roll over here because it will fill up the current ledger:
https://github.com/apache/pulsar/blob/6372b9c8f5448757cdb56dc70aaf0ebb52a1063e/managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImplTest.java#L77
Therefore, the source ML will update the managed ledger info. And the shadowML will get the updated MLInfo and update the LCE. So the assertion here is incorrect because the LCE will be updated:
https://github.com/apache/pulsar/blob/6372b9c8f5448757cdb56dc70aaf0ebb52a1063e/managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImplTest.java#L79-L81
The process of updating MLInfo from sourceML to shadowML is asynchronous. This causes the test to be unreliable.
Regarding the change for …
> [fix][test] Fix flaky test testShadowWrites

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [improve] Upgrade to Oxia client 0.3.0

- pip/pip-356.md
- [DIscussion](https://lists.apache.org/thread/8tp0rl05mjmqrxbp8m8nxx77d9x42chz)
- [Vote](https://lists.apache.org/thread/36jwdtdqspl4cq3m1cgz7xjk3gdpj45j)
> [improve] [pip] PIP-356: Support Geo-Replication starts at earliest position

- pulsar-broker/src/main/java/org/apache/pulsar/utils/auth/tokens/TokensCliUtils.java
The CLI tool that can be used to generate and sign tokens, should force the validation of token in the validate subcommand.
*(or)*
*(or)*
*(example:)*
> [fix] JWT CLI util should force the token validation

- pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/api/OrphanPersistentTopicTest.java
(cherry picked from commit a91a172b4ee6d8b974a3fa905e435975557fcc57)
cherry picked from #22860
*(or)*
*(or)*
*(example:)*
> [fix][broker][branch-3.0] The topic might reference a closed ledger (#22860)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImplTest.java
Those bundles that are filtered when try to unload them should not be included in the indicator.
Increment the metric only when the bundle are unloaded.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/58
> [fix] [broker] fix unload bundle count metric.

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
upgrade RoaringBitmap to 1.0.6
*(or)*
*(or)*
*(example:)*
> [improve][misc] Bump RoaringBitmap version to 1.0.6

- distribution/server/src/assemble/LICENSE.bin.txt
- distribution/shell/src/assemble/LICENSE.bin.txt
- pom.xml
Bookkeeper 4.16.6 has been released with important fixes.
- Upgrade Bookkeeper to 4.16.6 
- This PR is for branch-3.2
> [improve][misc][branch-3.2] Upgrade to Bookkeeper 4.16.6

- distribution/server/src/assemble/LICENSE.bin.txt
- distribution/shell/src/assemble/LICENSE.bin.txt
- pom.xml
Bookkeeper 4.17.1 has been released with fixes.
Upgrade Bookkeeper to 4.17.1
> [improve][misc] Upgrade Bookkeeper to 4.17.1

- pom.xml
There's a [mandatory upgrade notice](https://github.com/jeremylong/DependencyCheck?tab=readme-ov-file#mandatory-upgrade-notice) about upgrading to 10.0.2 version.
Upgrade dependency-check-maven-plugin to 10.0.2
> [improve][build] Upgrade dependency-check-maven-plugin to 10.0.2

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java
We encounter problem in MessageDeduplication and find it need to add log info.
add log
> [improve][broker] log exception in MessageDeduplication#takeSnapshot

- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java
increase the delay time, receive wait 5 seconds is smaller than the delay time 5 seconds
change 5 to 7
*(or)*
*(or)*
*(example:)*
> [fix][test]Fix flaky test increase the delay time

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
Upgrading to latest oxia client version: https://github.com/streamnative/oxia-java/releases/tag/v0.3.1
*(or)*
*(or)*
*(example:)*
> [fix] Upgrade to Oxia 0.3.1

- pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/DelayedDeliveryTracker.java
Fix compile failing introduced by https://github.com/apache/pulsar/pull/22735
*(or)*
*(or)*
*(example:)*
> [fix] Fix compile failing

- pip/pip-366.md
Discuss thread: https://lists.apache.org/thread/98ggo1zg1k7dbyx8wr9bc8onm10p16c6
Support to specify different config for Configuration and Local Metadata Store
> [improve][pip] PIP-366: Support to specify different config for Configuration and Local Metadata Store

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
(cherry picked from commit 55e468ee412fff9706f6badcd07b5c8f11ed8375)
> [fix][broker][branch-3.2] Do not try to clean owned bundles from inactive source brokers (ExtensibleLoadManagerImpl only) (#23064)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
(cherry picked from commit 55e468ee412fff9706f6badcd07b5c8f11ed8375)
> [fix][broker][branch-3.3] Do not try to clean owned bundles from inactive source brokers (ExtensibleLoadManagerImpl only) (#23064)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
(cherry picked from commit 55e468ee412fff9706f6badcd07b5c8f11ed8375)
> [fix][broker][branch-3.0] Do not try to clean owned bundles from inactive source brokers (ExtensibleLoadManagerImpl only) (#23064)

- pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicListWatcher.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java
Fixes : https://github.com/apache/pulsar/issues/23250
[PIP-91](https://github.com/apache/pulsar/pull/11627/) had added a change to accumulate list of Exceptions and attempt for not any good reasons. On connection failure, client lib always logs the exception and error  so, there is always a way to find out any previous exception for the connection issues. and there is no any good reason or standard to keep large number of  exception-list in memory and additionally generate huge huge logs which creates unnecessary string objects and consumes high CPU that eventually makes broker unavailable due to high CPU and high gc pauses.
Client lib keeps the previous exception list during connection failure which is unnecessary because of two reasons: 
1) in almost all cases, all previous Exceptions …
> [fix][client] Fix broker/Client CPU reaching 100% during retriable connection failure

- pip/pip-374.md
> [improve][pip] PIP-374: Visibility of messages in receiverQueue for the consumers

- pip/pip-360.md
Adding support for showing metadata of schema in readable format.
Adding admin API and cli to read schema metadata.
*(or)*
*(or)*
*(example:)*
> [improve][pip] PIP-360 Add admin API to display Schema metadata

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
Remove unnecessary return in ManagedLedgerImpl
> [fix][ml] Remove unnecessary return in ManagedLedgerImpl

- pulsar-broker/src/test/java/org/apache/pulsar/broker/web/WebServiceTest.java
- tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/provider/AbstractJCloudBlobStoreFactoryTest.java
> [fix][broker] Fix typos in pulsar-broker and tiered-storage.

- pom.xml
- contains fixes CVE-2024-38819 and CVE-2024-38820
- Upgrade Spring version to 6.1.14
> [improve][io] Upgrade Spring version to 6.1.14 in IO Connectors

- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryIntegrationTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TableViewTest.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
(cherry picked from commit 7d7dc80f0ee9e5926c8ac53a155de98bc6ffa3fa)
> [fix][broker] Fix the broker registering might be blocked for long time (#23371)

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistry.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
- pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Brokers.java
- pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BrokersImpl.java
(cherry picked from commit eee9283666cc9d84d0ddb998c279600898121d2b)
> [fix][broker] timeout when broker registry hangs and monitor broker registry (ExtensibleLoadManagerImpl only) (#23382)

- src/set-project-version.sh
Fixes spurious backup files found in source distribution tarballs `-source-release.zip` like https://repo.maven.apache.org/maven2/org/apache/pulsar/pulsar/4.0.0/pulsar-4.0.0-source-release.zip
PIP: #xyz 
Avoid unwanted files in official source distribution files
*(or)*
*(or)*
*(example:)*
> [cleanup][build] skip generating pom.xml.versionsBackup

- pip/pip-373.md
- [DIscussion](https://lists.apache.org/thread/7mblhyvsrw5zybo0gs5512xg8f9sm67v)
- [Vote](https://lists.apache.org/thread/s6z5gcjyw081cxf9pwz361r8dt2k8gvl)
> [improve] [pip] PIP-373: Add a topic's system prop that indicates whether users have published TXN messages in before.

- pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImplTest.java
Remove useless test code, refer to [this](https://github.com/apache/pulsar/pull/23817#discussion_r1905845395).
> [fix][test] Remove useless test code

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
Upgrade the oxia java client to 0.5.0
- upgrade the oxia java client to 0.5.0
> [feat][misc] upgrade oxia java client to 0.5.0

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Avoid logging errors for retriable errors when creating producer
- For RetriableError to print info log.
> [improve][client] Avoid logging errors for retriable errors when creating producer

- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
- pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
- pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
When setting the retention policy at the namespace level, an error message will be displayed if illegal parameters is set, but no relevant verification is added when setting the topic level policy.
We should keep the same validation rule at topic level with namespace level.
Add retention validation when setting retention policy on topic level.
*(or)*
*(or)*
*(example:)* …
> [fix][broker] Fix missing validation when setting retention policy on topic level

- conf/broker.conf
- pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
Typo correction: from backlogQuotaDefaultLimitByte to backlogQuotaDefaultLimitBytes
Typo correction: from backlogQuotaDefaultLimitByte to backlogQuotaDefaultLimitBytes
PR in forked repository: https://github.com/StevenLuMT/pulsar/pull/11
> [fix][broker] Typo correction: from backlogQuotaDefaultLimitByte to backlogQuotaDefaultLimitBytes

- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/IncrementPartitionsTest.java
The previous assertion only verified subscriptions for partition 15. This change expands the scope to cover all partitions, ensuring comprehensive validation of subscription behavior.
Fix assertion to iterate through all partitions and verify subscriptions, ensuring comprehensive coverage instead of checking only partition 15.
PR in forked repository: https://github.com/kontotto/pulsar/pull/5
> [fix][test] Update partitioned topic subscription assertions in IncrementPartitionsTest

- pom.xml
The CI Job `OWASP Dependency Check` has failed consistently since [last month][failed-job-url], below are the error details:
```
Error:  Error updating the NVD Data
org.owasp.dependencycheck.data.update.exception.UpdateException: Error updating the NVD Data
Caused by: io.github.jeremylong.openvulnerability.client.nvd.NvdApiException: Failed to parse NVD data
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.github.jeremylong.openvulnerability.client.nvd.CvssV4Data$ModifiedCiaType`, problem: SAFETY
Caused by: java.lang.IllegalArgumentException: SAFETY
```
According to `dependency-check` [Mandatory Upgrade Notice][upgrade-notice]:
```
Due to compatibility issues with the NVD API - all users must upgrade to 12.1.0 or later.
```
This …
> [fix][ci] Bump dependency-check to 12.1.0 to fix OWASP Dependency Check job

- pip/pip-412.md
> [improve][pip] PIP-412: Support setting messagePayloadProcessor in Pulsar Functions and Sinks

- pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImplTest.java
Fixes https://github.com/apache/pulsar/issues/24169
fix flaky-test in ManagedLedgerInterceptorImplTest.testManagedLedgerPayloadInputProcessorFailure
PR in forked repository: https://github.com/3pacccccc/pulsar/pull/3
> [fix][test]flaky-test:ManagedLedgerInterceptorImplTest.testManagedLedgerPayloadInputProcessorFailure

- pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AuthZTest.java
Follow up on #24165. There's a remaining issue since mocks get modified in multi-threaded context in tests using `AuthZTest` as base class which modifies mocks in `@BeforeMethod`. That's not necessary with the solution and it could happen as soon as the broker is started so that the problem doesn't occur.
```
Error:  org.apache.pulsar.broker.admin.TransactionAndSchemaAuthZTest.after  Time elapsed: 0.012 s  <<< FAILURE!
org.mockito.exceptions.misusing.UnfinishedStubbingException: 
Unfinished stubbing detected here:
-> at org.apache.pulsar.broker.admin.AuthZTest.before(AuthZTest.java:88)
E.g. thenReturn() may be missing.
Examples of correct stubbing:
when(mock.isOk()).thenReturn(true);
when(mock.isOk()).thenThrow(exception);
doThrow(exception).when(mock).someVoidMethod();
Hints:
1. missing …
```
> [fix][test] Fix remaining UnfinishedStubbingException issue with AuthZTests

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HealthChecker.java
Fixes #24215
Follow up on #24210 which extracted the health checker logic to a separate class, HealthChecker.
There's a dead lock in broker shutdown and this PR addresses the issue.
- add a separate single threaded executor for executing health check operations and asynchronous callbacks
- this fixes the dead lock issue
- this avoids running health check operations on metadata or Pulsar internal threads
- add other minor cleanup and improvements
- set the send timeout
- disable batching for the producer
> [fix][broker] Fix HealthChecker deadlock in shutdown

- pom.xml
Upgrade Jacoco to 0.8.13 which support JDK 24 byte code.
> [improve][build] Upgrade to jacoco 0.8.13

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
remove unused static fields in BrokerService
*(or)*
*(or)*
*(example:)*
> [cleanup] Remove unused static fields in BrokerService

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/AutoClusterFailover.java
- pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java
- pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java
- pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
- pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationController.java
Fixes #24389 
fix resource leak using `try-catch` stmt methoned in #24389 , and close other leaks in this project I've found later
use `try-with` stmt to close the resoure in:
- AutoClusterFailover.java
- RuntimeUtils.java
- FunctionActioner.java
- ComponentImpl.java
- LoadSimulationController.java
> [fix][client] Fix some potential resource leak

- pip/pip-416.md
> [improve][pip] PIP-416: Add a new topic method to implement trigger offload by size threshold

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-broker/pom.xml
- pulsar-metadata/pom.xml
- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/OxiaMetadataStore.java
- pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BaseMetadataStoreTest.java
- pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
Upgrade to latest stable version of Oxia
*(or)*
*(or)*
*(example:)*
> [improve] Update to Oxia 0.6.0 and use new group-id

- managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
---
When do some expirmental changes with the managed ledger, we need to access the lock fields in the sub-class. Change the field scope to allow this happen.
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [refactor][broker] Expose the managedLedger field for the sub class

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
The error log https://github.com/apache/pulsar/blob/e7eb7b37a779f9b74b8abf43cf622957663495d1/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java#L757-L758 mostly comes from the client.
The client could already receive this error, as seen at https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-common/src/main/java/org/apache/pulsar/common/api/raw/MessageParser.java#L151-L152
We do not need to print this error log in the broker. Doing so would fill up the broker error logs and make them hard to manage.
- Change to warn log level for ack validation error
> [improve][broker] change to warn log level for ack validation error

- pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java
The current message deduplication logic in `MessageDeduplication.java` contains unnecessary null checks and variable declarations
- Removed redundant `MessageMetadata md = null` declaration
- Eliminated unnecessary null check before metadata parsing
- Inlined the metadata parsing logic for chunked messages
- Reduced variable scope where possible
The changes affect only the `isDuplicateNormal` method in `MessageDeduplication.java`.
PR in forked repository: https://github.com/3pacccccc/pulsar/pull/10
> [improve][broker] Optimize message deduplication by removing redundant null checks and variable declarations

- pip/pip-421-client-java-17.md
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
> [improve][client][pip] Require Java 17 as the minimum for Pulsar Java client SDK

- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java
- pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java
In the `org.apache.pulsar.metadata.impl.ZKMetadataStore` class, during initialization and upon receiving the `SessionReestablished` event from ZooKeeper, a watcher is registered using the following code:
```java
zkc.addWatch("/", this::handleWatchEvent, AddWatchMode.PERSISTENT_RECURSIVE,
(rc, path, ctx) -> {
// ...
}, null);
```
The use of `this::handleWatchEvent` here causes the watcher passed to the `addWatch` method not to be the same object each time, which may lead to duplicate registrations.
Use the same watcher object when calling the `addWatch` method
- Added test in `org.apache.pulsar.metadata.ZKSessionTest#testNoDuplicateWatcherRegistrationAfterSessionReestablished` …
> [fix][broker] Fix duplicate watcher registration after SessionReestablished

- pip/pip-436.md
> [improve][pip]PIP-436: Add decryptFailListener to Consumer

- pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/state/PulsarMetadataStateStoreProviderImpl.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarBKStateStoreTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarMetadataStateStoreTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarMetadataStoreStateTest.java
- tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarStateTest.java
- tests/integration/src/test/resources/pulsar-function.xml
Fixes #24720
The `PulsarMetadataStateStoreProviderImpl.init` method fetches the `METADATA_URL` field from the config argument, but it doesn't exist in normal case, fallback to `stateStorageServiceUrl` just like other `StateStoreProviderImpl`
When the provided argument doesn't contains a `METADATA_URL` field, fallback to fetching with key `stateStorageServiceUrl` 
- org.apache.pulsar.tests.integration.functions.PulsarMetadataStoreStateTest 
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/47
> [feat][fn] Fallback to using `STATE_STORAGE_SERVICE_URL` in `PulsarMetadataStateStoreProviderImpl.init`

- pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImpl.java
- pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicListWatcher.java
Fixes https://github.com/apache/pulsar/issues/24707
Rollback TopicListWatcher retry behavior in PR https://github.com/apache/pulsar/pull/24698
Rollback TopicListWatcher retry behavior to avoid "breaking change".
PR in forked repository: https://github.com/oneby-wang/pulsar/pull/3
> [fix][client] rollback TopicListWatcher retry behavior

- pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java
Hi, I'm currently studying Pulsar.  
While exploring the source code to better understand how Pulsar works, 
I noticed a few typos and decided to create my first PR.  
There were several typos in the `PulsarClusterMetadataSetup`, including:
- Error message string
- Variable name typo
- Minor typo in comment
- Error message string (`occured` → `occurred`)
- Variable name typo(`metadataStoreUrlNoIdentifer` → `metadataStoreUrlNoIdentifier`)
- Minor typo in comment(add space)
- [O] Make sure that the change passes the CI checks.
*(or)*
*(or)* …
> [fix][broker] Fix typos in PulsarClusterMetadataSetup

- pip/pip-443.md
> [improve][pip] PIP-443: Stop using Netty Recycler in new code

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
```
├──────────────────────────────────────────────────────────────┼────────────────┼──────────┼──────────┼───────────────────┼───────────────┼──────────────────────────────────────────────────────────────┤
│ io.grpc:grpc-netty-shaded                                    │ CVE-2025-55163 │ HIGH     │ fixed    │ 1.72.0            │ 1.75.0        │ netty: netty-codec-http2: Netty MadeYouReset HTTP/2 DDoS     │
│ (io.grpc-grpc-netty-shaded-1.72.0.jar)                       │                │          │          │                   │               │ Vulnerability                                                │
│                                                              │                │          │          │                   │               │ https://avd.aquasec.com/nvd/cve-2025-55163 …
```
> [fix] Update gRPC to 1.75.0

- distribution/server/src/assemble/LICENSE.bin.txt
- pom.xml
- pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/OxiaMetadataStore.java
Upgrading to latest stable version of Oxia client
*(or)*
*(or)*
*(example:)*
> [improve][ml] Upgrade Oxia client to 0.7.0
