apache/pulsar

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
Related to #15335
Sometimes the CommandSubscribe object has already been released and it triggers this error:
> 17:36:40.676 [bookkeeper-ml-scheduler-OrderedScheduler-3-0] WARN  org.apache.pulsar.broker.service.ServerCnx - [/192.168.1.111:50688][persistent://public/default/test-cb4105f6-f850-4bdf-9e79-66d4ac42658c][13b9ee68-4ee4-4845-b955-77420b8b6a29] Failed to create consumer: consumerId=0, refCnt: 0
> java.util.concurrent.CompletionException: io.netty.util.IllegalReferenceCountException: refCnt: 0
> 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
> 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
> 	at java.util.concurrent.CompletableFuture.tryFire(CompletableFuture.java:1081) ~[?:?]
> 	at …
=> PIP-105: Fix error on recycled SubscriptionPropertiesList

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Master Issue: #12795
Dev email: [discuss](https://lists.apache.org/thread/7ofh935lrjr4lovvpnpp6w0m3b6tjojx) and [reply](https://lists.apache.org/thread/wbny8x0b31jdkgoc9cjlc29gt9fdsm6v)
Deleting topic also deletes its schema.
=> Ensure the deletion consistency of topic and schema

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryController.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryControllerTest.java
Sometimes the messages sent to consumers are delayed over 100ms and we find that the CPU is wasted on :
```
"BookKeeperClientWorker-OrderedExecutor-4-0" #64 prio=5 os_prio=0 cpu=2447920216.81ms elapsed=3636758.63s tid=0x00007f48bdc07290 nid=0xae runnable  [0x00007f47ee2e2000]
at org.apache.bookkeeper.util.collections.ConcurrentLongLongPairHashMap.forEach(ConcurrentLongLongPairHashMap.java:197)
at org.apache.pulsar.broker.service.persistent.MessageRedeliveryController.containsStickyKeyHashes(MessageRedeliveryController.java:97)
at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumers.getRestrictedMaxEntriesForConsumer(PersistentStickyKeyDispatcherMultipleConsumers.java:335)
at …
```
=> [improve][broker] Use shrink map for message redelivery.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/MessageDuplicationTest.java
#15204 
In the current implementation, When the first time execute `purgeInactiveProducers`, Although the produces does not expire, it removed directly from the collection(464 line). The will result in these producers never being remove.
https://github.com/apache/pulsar/blob/9861dfb1208c4b6b8a1f17ef026e9af71c3e784c/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java#L454-L472
1. It is removed from the collection only when the producer is inactive.
2. Take a snapshot after each removal of an inactive producer. When `managedLedger.getLastConfirmedEntry` equals `managedCursor.getMarkDeletedPosition()`, The`deduplication-snapshot-monitor` thread does not trigger a snapshot. The persistence these producers only the next time a message is produced, …
=> Fix MessageDeduplication#inactiveProducers may not be persistence correctly

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryController.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSet.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentSortedLongPairSet.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/LongPairSet.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentSortedLongPairSetTest.java
Sometimes the messages sent to consumers are delayed over 100ms and we find that the CPU is wasted on :
```
"BookKeeperClientWorker-OrderedExecutor-4-0" #64 prio=5 os_prio=0 cpu=12748552.31ms elapsed=42037.79s tid=0x00007f7b4dc05720 nid=0xaf runnable  [0x00007f7a376f4000]
at org.apache.pulsar.common.util.collections.ConcurrentLongPairSet.forEach(ConcurrentLongPairSet.java:157)
at org.apache.pulsar.common.util.collections.ConcurrentSortedLongPairSet.items(ConcurrentSortedLongPairSet.java:136)
at org.apache.pulsar.common.util.collections.ConcurrentSortedLongPairSet.items(ConcurrentSortedLongPairSet.java:128)
at org.apache.pulsar.common.util.collections.ConcurrentSortedLongPairSet.items(ConcurrentSortedLongPairSet.java:113)
at …
```
=> [improve][broker] Support shrink for ConcurrentSortedLongPairSet 

conf/presto/jvm.config, pulsar-sql/java-version-trim-agent/pom.xml, pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java, pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/package-info.java, pulsar-sql/pom.xml, pulsar-sql/presto-distribution/pom.xml, pulsar-sql/presto-distribution/src/assembly/assembly.xml, pulsar-sql/presto-pulsar/pom.xml, src/check-binary-license, tests/docker-images/latest-version-image/conf/presto/jvm.config, tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/TestPrestoQueryTieredStorage.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java
Fix #14951
The presto 332 couldn't parse Java version like this `11.0.14.1`, so add a Java version trim agent to walk around the problem.
This is a temporary patch, after the presto upgrade to 332+, we could remove this.
(cherry picked from commit a1aa18f1a856d074bb23d68f5c330d3558bdf6cb)
Add a Java version trim agent to format the system property `java.version` for the Pulsar SQL plugin.
- The default values of configurations: (yes)
Check the box below or label this …
=> [cherry-pick][pulsar-sql] Java version trim agent presto332 branch2.8

site2/docs/client-libraries-node.md, site2/docs/tiered-storage-filesystem.md
Fix https://github.com/apache/pulsar/issues/14526
The current Filesystem Offload documentation has no documentation on how to directly read the data after offload, so consider adding documentation for this section
*(or)*
*(or)*
*(example:)*
- …
=> [doc][tiered storage] read data from filesystem

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java
Add test for negative ack API to ensure that when negative msg, the msg has been removed from `UnAckedMessageTracker`.
Before this test, there may exist that `negative ack doesn't remove the message id from UnAckedMessageTracker when message id is instance of BatchMessageIdImpl`with related issue #6869.
I think #6869 has been fixed by #9440 and after discussion,  we decide to add this test to ensure that negative ack would remove BatchMessageIdImpl.
- Add test to verify the internal state.
- Add test to cover `enableBatchIndexAcknowledgment=true`.
=> [improve][test] Add test for negative ack.

pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentSortedLongPairSet.java
In `ConcurrentSortedLongPairSet`, there are someplace don't need to use atomic type, we can use basic type to replace it. 
Change atomic type to basic type.
=> [improve][broker] Change unnecessary atomic to basic type

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
Fix: #13952
#14000 didn't fix issue #13952 .  The root cause is that the backlog obtained by the admin is not precise. 
In the `BacklogQuotaManagerTest`, the message backlog in stats obtained from the admin may not be precise. This causes them to become flaky tests. We need to get the precise backlog in the test.
Here is a more deep investigation for #13952 :
```
2022-02-28T16:46:19,368+0800 [pulsar-web-63-14] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [prop/ns-quota/persistent/topic3] Consumer c2 cursor ml-entries: 14 -- deleted-counter: 9 other counters: mdPos 4:-1 rdPos 4:0
2022-02-28T16:46:19,369+0800 [pulsar-web-63-14] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [prop/ns-quota/persistent/topic3] getNumberOfEntries. (4:-1..4:3] allEntries: 4 …
```
=> [Test] Use precise backlog when getting stats in the test.

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfigTests.java, site2/docs/io-elasticsearch-sink.md
In the ElasticSearch sink connector the `bulkFlushIntervalInMs` is currently disabled by default.
This option is used to control the maximum time that the messages are retained in memory before being flushed to the ES server (along with `bulkActions` and `bulkSizeInMb`) when bulk mode is enabled.
`bulkActions` and `bulkSizeInMb` are based on the traffic and if `bulkFlushIntervalInMs` is disabled, the messages can be blocked in the sink forever. This is a problem because then the function subscriptions are stuck (messages are not acked since correctly sent to elastic).
`bulkFlushIntervalInMs` is a time-based setting and it will avoid this kind of scenario by design. However this could increase the overhead with low-traffic. With high traffic there should not be visible changes.
Enable …
=> [fix][elasticsearch-sink] enable bulk flushing scheduling by default

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java
- there is usually not an advantage to have many connections per host
- discussion in pulsar-client-go PR https://github.com/apache/pulsar-client-go/pull/765#issuecomment-1112679878
Change the default number of connections from 100 to 1 in pulsar-perf components.
=> [pulsar-perf] Change the default for max-connections from 100 to 1

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConnectionController.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
There was a typo in the enum name `Sate` added in #10754 . The PR fixes the typo by renaming `Sate` to `State`.
In addition, there's a slight refactoring to handle closing the channel after the writeAndFlush has completed. In practice this most likely doesn't make a difference.
`ctx.channel().writeAndFlush` has been changed to `ctx.writeAndFlush`, since that's the usual way to write messages in the handler. 
- rename `Sate` to `State`
- `ctx.channel().writeAndFlush` -> `ctx.writeAndFlush`
- use `.addListener(ChannelFutureListener.CLOSE)` to close the channel after the `.writeAndFlush` promise completes.
=> [Broker] Fix typo in enum name and handle closing of the channel properly since writeAndFlush is asynchronous

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
No need to get namespace policies when update topic policies, Because we have used `HierarchyTopicPolicies`
Remove  `getNamespacePolicies`
=> [cleanup][broker]Cleanup getNamespacePolicies when update TopicPolicies

src/check-binary-license.sh
We don't need to check the `java-version-trim-agent.jar` when checking presto license files.
Exclude `java-version-trim-agent.jar` from presto license check.
=> [fix][license] Exclude `java-version-trim-agent.jar` from presto license check

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminResourceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Make PersistentTopicsBase#internalUpdatePartitionedTopic async.
=> [Broker] Make PersistentTopicsBase#internalUpdatePartitionedTopic async

pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ControlledClusterFailover.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpClient.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/auth/oauth2/protocol/TokenClient.java
The AsyncHttpConnector will use the configuration inside System properties http.proxyHost and http.proxyPort
It is recommended to use pulsar like this for example:
PULSAR_EXTRA_OPTS="-Dhttps.proxyHost=<proxy> -Dhttps.proxyPort=<proxy_port> -Dhttp.proxyHost=<proxy> -Dhttp.proxyPort=<proxy_port>" bin/pulsar-admin tenants list
Before this change the execution need to add the org.asynchttpclient.useProxyProperties that it is a little bit complex to find.
PULSAR_EXTRA_OPTS="-Dhttps.proxyHost=<proxy> -Dhttps.proxyPort=<proxy_port> -Dhttp.proxyHost=<proxy> -Dhttp.proxyPort=<proxy_port> -Dorg.asynchttpclient.useProxyProperties=true" bin/pulsar-admin tenants list
When trying to use a web proxy with the pulsar-admin, the configuration was not taking into account unless the variable: …
=>  [Improve][admin|client] AsyncHttpConnector doesn't use the system properties configured

tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java
Master Issue: #15207 
- As per the [Java build 17 upgrade work](https://github.com/apache/pulsar/pull/15264), KinesisSink's default aggregation is exposed in the KinesisSinkTester. We need to cover this record aggregation behavior in the test.
- Updated the KinesisSinkTester to deaggregate response records, if aggregated.
- [] Make sure that the change passes the CI checks.
This change is already covered by existing tests, such as *PulsarSinksTest#testKinesis*.
- The …
=> [PIP-156][fix][ci] fixed KinesisSinkTest record format error by deaggregation

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarChannelInitializer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java
Fixes #10150 
Make PersistentTopicE2ETest#testBrokerConnectionStats tests stable.
Need to update docs? r)
=> [Flaky Tests] Make PersistentTopicE2ETest#testBrokerConnectionStats tests stable.

conf/functions_worker.yml, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionTlsTest.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Worker.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/WorkerServer.java, site2/docs/functions-worker.md
Master Issue: https://github.com/apache/pulsar/issues/11548
Some use security sensitive users prefer to disable plaintext ports to ensure that there is no accidentally non-encrypted traffic. We added the ability to disable the non-TLS server on the broker https://github.com/apache/pulsar/pull/11681, and this PR adds the same feature for the function worker.
I have two questions about the implementation:
1. Is it a breaking change to update the worker id logic? It looks like the existing logic has two different methods of construction. The first is modified in this PR and the second is below. They differ only slightly. https://github.com/apache/pulsar/blob/74eae1a729c33c9fead9d54594bdee5fac8ab153/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L1681-L1685
2. In the …
=> [feature][Function Worker] Support disabling non-TLS service port

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
`BatchMessageTest` is very flaky, some tests failed at checking the
backlog of a topic. This flakiness, maybe the bug, was introduced from
https://github.com/apache/pulsar/pull/14185. `batchFlushTask` calculates
the time duration between now and `lastBatchSendNanoTime`. However,
for the first time `batchFlushTask` is called, `lastBatchSendNanoTime`
is not initialized, so the time diff duration satified so that
`batchMessageAndSend` will always be called for the first time.
For example, if all messages can be split into two batches for a given
batch size limit, there is a chance that when first few messages are in
the batch, `batchFlushTask` is called at the same time and these
messages could be sent first.
Here are some extra logs added by myself:
```
2022-05-01T12:35:23,545+0800 [main] …
```
=> [Java Client] Fix flaky BatchMessageTest by initializing lastBatchSendNanoTime

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/RocksdbMetadataStore.java
The contructor of RocksdbMetadataStore  should throw expception when rocksdb file directory create failed，instead of just printing the exception message。
throw MetadataStoreException instead of exception printStackTrace
=> [fix][Broker] fix bug in contructor of RocksdbMetadataStore

pom.xml, pulsar-io/canal/pom.xml
Bump dependency check version to avoid potential FP
Bump spring version to solve [CVE-2022-22968](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-22968)
- Bump dependency check version from 6.1.6 to 7.1.0
- Bump spring version from 5.3.18 to 5.3.19
=> Bump dependency check and spring version to avoid potential FP

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Check subscribeRateLimiter.isPresent to avoid unnecessary operation.
=> [cleanup][broker] Pre check subscribeRateLimiter.isPresent to avoid unnecessary operation.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
Remove unused authenticateOriginalAuthData in ServerCnx.
=> [cleanup][broker] Remove authenticateOriginalAuthData in ServerCnx

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java
Fixes #15397
The changes in #12890 introduced a regression that when delayed messages with interleaved delays occur on a shared subscriptions, many of the messages are not delivered and stay in the backlog. 
The reason is that we're peeking into `getMessagesToReplayNow()` and we cannot discard the returned set, because these message ids are not tracked anymore in the delayed messages controller.
=> Fixed key-shared delivery of messages with interleaved delays

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConnectionPoolTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ServiceChannelInitializer.java
- `DnsNameResolver` doesn't coordinate concurrency and this leads to DNS server DoS
under high load to the Pulsar Proxy. This happens when a large number of connections are initiated at once.
Dns lookups will timeout since the DNS server will get overloaded and won't be able to respond in time.
Example error message `query via UDP timed out after 5000 milliseconds`:
```
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'pulsar-testenv-pulsar-broker-2.pulsar-testenv-pulsar-broker.pulsar-testenv.svc.cluster.local' and search domain query for configured domains failed as well: [pulsar-testenv.svc.cluster.local, svc.cluster.local, cluster.local]
at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047) …
```
=> [Proxy/Client] Fix DNS server denial-of-service issue when DNS entry expires

pulsar-client-cpp/python/build-mac-wheels.sh
Fix #15402
In the `build-mac-wheels.sh` script we were not building the wheel for Python 3.7. We need to treat 3.7 in a slightly different way because it has no support for Mac M1 binaries (`universal2` which support was added in Python 3.8). Therefore for Python 3.7 we're going to build an `x86_64` only wheel file, cross compiling is the build is happening on an M1 Mac.
=> [Python] Adjusted script to build wheel for Python 3.7 on Mac

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java
- Calling `new InetSocketAddress(brokerURI.getHost(), brokerURI.getPort())` does a blocking DNS lookup. This should be avoided since Pulsar's ConnectionPool uses Netty's non-blocking DNS lookup. Unresolved addresses are expected as input to ConnectionPool.
replace `new InetSocketAddress` with `InetSocketAddress.createUnresolved` by using existing helper method to create the `InetSocketAddress` instance
=> [Proxy] Remove unnecessary blocking DNS lookup in LookupProxyHandler

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
```
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.api.SimpleProducerConsumerTest.testRedeliveryFailOverConsumer() didn't finish within the time-out 300000
```
Now the tests maybe timeout. Make produce at once to reduce time of spend. It didn't change the intention of the test.
=> [improve] [test] Improve timeout problem at SimpleProducerConsumerTest#testRedeliveryFailOverConsumer

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Fixes #15018 
tweak the timeout msg at OpSendMsg.
=> [fix][client-producer] tweak the timeout msg before opMsg flush.

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClient.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/BulkProcessor.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/elastic/ElasticBulkProcessor.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/opensearch/OpenSearchHighLevelRestClient.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkTests.java
After https://github.com/apache/pulsar/pull/14805, there's a memory leak while using the OpenSearch client.
Every request is kept in a collection, mapping the request with an unique id. The collection is never clear and the objects never collected by the GC.
* Refactor the internal mapping needed for access the pulsar record removing the collection and passing the object directly into the callback (using a wrapper object)
Note: this only affects current pulsar master.
=> [fix][pulsar-io] Fix memory leak in ElasticSearch sink

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/ClusterResources.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
See PIP #14365  and change tracker #15043.
- Make `ClusterBase` `getClusters / getCluster / createCluster / updateCluster` methods to pure async.
We have `AdminTest` covering this change.
=> [improve][broker] Make some methods of `ClusterBase` pure async.

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceTest.java
Add verification for configured default backlog quota and data retention, to keep consistent with 
the namespace level policy and topic level policy.
Add verification for the backlog quota and retention of size and time duration while starting Pulsar.
Added a new test to verify the different situations.
- The rest endpoints: ( no)
- Anything that affects deployment: (yes)
(Your PR contains doc …
=> [improve][broker] Add verification for configured default backlog quota and retention

site2/website/versioned_docs/version-2.10.0/io-elasticsearch-sink.md
ElasticSearch Sink configuration doc contains a parameter which is not included in Pulsar 2.10.0
The parameter is `compatibilityMode`.
https://pulsar.apache.org/docs/en/io-elasticsearch-sink/#configuration
https://github.com/apache/pulsar/pull/14805
Removed the parameter from 2.10 doc
=> [doc][elasticsearch-sink] Remove 'compatibilityMode' from the Pulsar 2.10 docs

.github/workflows/ci-cpp.yaml, .github/workflows/ci-owasp-dep-check.yaml, .github/workflows/ci-owasp-dependency-check.yaml, .github/workflows/pulsar-ci.yaml
Uploading surefire reports and container logs has been broken in the new Pulsar CI workflow.
Example failure: https://github.com/apache/pulsar/runs/6301697885?check_suite_focus=true
```
Error: Create Artifact Container failed: The artifact name Unit-BROKER_GROUP_2-surefire-reports is not valid. Request URL https://pipelines.actions.githubusercontent.com/EXIZfX8ixSbQEfqDA00dMJrEtloTMSwjlUs9NqJqrTcJfd7NaR/_apis/pipelines/workflows/2269710766/artifacts?api-version=6.0-preview
```
This seems to be caused by the solution in Pulsar CI which attempts to delete logs from a previous test run.
- remove solution to delete possible previous logs
- upgrade upload-artifact to v3
- set retention to 7 days to save storage space
=> [CI] Fix issue in uploading surefire reports and container logs

pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/PackagesStorage.java, pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/impl/PackagesManagementImpl.java, pulsar-package-management/core/src/test/java/org/apache/pulsar/packages/management/core/impl/PackagesManagementImplTest.java, pulsar-package-management/filesystem-storage/src/main/java/org/apache/pulsar/packages/management/storage/filesystem/FileSystemPackagesStorage.java
---
Fixes #15362
*Motivation*
The PR https://github.com/apache/pulsar/pull/13218 supports saving
package data into filesystem. But it introduces a regression for the
old versions.
For example, we have a package function://public/default/package@v0.1,
it will save the meta to the path function/public/default/package/v0.1/meta,
and save the data to the path function/public/default/package/v0.1.
By default, we are using distributed log as the package storage, and
it supports saving data in a directory.
But some storage like filesystem doesn't have the similar ability, it
needs another path for saving data.
This API provides the ability to support saving the data in another place.
If you specify the data path as `/data`, the package will be saved into …
=> [fix][package-management] Fix the new path `/data` introduced regression

pulsar-client-cpp/docker/manylinux1/Dockerfile, pulsar-client-cpp/docker/manylinux2014/Dockerfile, pulsar-client-cpp/docker/manylinux_musl/Dockerfile, pulsar-client-cpp/python/pulsar/schema/definition.py, pulsar-client-cpp/python/setup.py
Since we have set the min python version to 3.7, we can get rid of some dependencies that were only related to Python2
=> [Python] Removed dependencies only need by Python2

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/BundleSplitterTask.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/InactiveTopicDeleteTest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarSinkE2ETest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/json/PulsarJsonRowDecoderFactory.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/AbstractWebSocketHandler.java, site2/docs/client-libraries-cpp.md, site2/website/release-notes.md, site2/website/versioned_docs/version-2.10.0/client-libraries-cpp.md, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/JdbcPostgresSinkTester.java
I found log lines like
```
INFO  org.apache.pulsar.broker.loadbalance.BundleSplitStrategy - The count of topics on the bundle benchmark/ns-85SYDFY/0x4c000000_0x50000000 is less than 2ï¼Œskip split!
```
this is coming from 
```
log.info("The count of topics on the bundle {} is less than 2，skip split!", bundle);
```
where "，" is a single unicode character.
replaced "，" with regular comma and space, skipped text/files where it was next to hieroglyphs/other unicode characters.
NO …
=> Replaced unicode 'comma and space' as single glyph with regular comma and space characters

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
the `hppc` 0.7.3 is released in 2017, keep update.
CHANGELOG: https://github.com/carrotsearch/hppc/blob/master/CHANGES.txt
=> Bump hppc version from 0.7.3 to 0.9.1

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStore.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionLogImpl.java
The queue size + NUMBER_OF_PER_READ_ENTRY should <= the capacity of queue instead of the queue size <= the capacity of queue. If the processing speed is less than the read speed, the part that exceeds the queue capacity will be ignored.
It hard to add test for this change.
This class of replay/recover/FillEntryQueueCallback is not public, so it can not be import by test.
And then their flied can not be changed by reflection.
With `Thread.sleep` allowed, we  can only test the recover of  TC by call a `Thread.sleep` in `transactionLogReplayCallback` and can not test TP/TB.
*(or)*
*(or)* …
=> [Fix][Txn]Fix transaction component recover fillQueue

conf/proxy.conf, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java, site2/docs/reference-configuration.md
=> [Improve][doc] Add config of IO and acceptor threads in proxy

conf/broker.conf, conf/standalone.conf, site2/docs/reference-configuration.md
Add doc for #15011.
Add  `transactionBufferClientOperationTimeoutInMills` at `reference-configuration.md`
=> [improve][doc] Support configurable transactionBufferClientOperationTimeoutInMills

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
It is difficult to get CR due to so many modifications in PIP 81 #10729.
So I split this PR into multiple sub-PRs to facilitate CR
I split the logic in createNewMetadataLedger into multiple methods to facilitate subsequent reuse
1. Put the logic of creating Ledger into `doCreateNewMetadataLedger` separately
2. `switchToNewLedger` does not need to wrap another layer of callback, so remove redundant wrapping
3. When persisting data fails, we need to delete the created Ledger, this part of the logic is put into `deleteLedger`
This modification does not change any previous behavior, so no unit tests are required, but the previous unit tests must be ensured to pass
(Docs have been …
=> [PIP 81] Part-1  Split createNewMetadataLedger into multiple methods for reuse

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/LocalMemoryMetadataStore.java
https://github.com/apache/pulsar/issues/15091
The essential reason for https://github.com/apache/pulsar/pull/13911 is that two threads execute the refresh method concurrently. In PR https://github.com/apache/pulsar/pull/13911 change, it doesn't completely solve the problem, just avoid concurrent access by threads.
In #14283, The problem was radically resolved by changing below.
```
objCache.asMap().computeIfPresent(path, (oldKey, oldValue) -> readValueFromStore(path));
```
In #13911, although multi-threaded access is avoided, it will cause the test `future.get()` to not get the expected result. 
This will cause the `updateValueWhenKeyDisappears` test to fail. So, revert this commit. 
- Revert "Fix: LockManagerTest.updateValue is flaky (#13911)"
=> Revert "Fix: LockManagerTest.updateValue is flaky (#13911)"

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/AutoScaledReceiverQueueSizeTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConsumerMemoryLimitTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MemoryLimitController.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ZeroQueueConsumerImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/MemoryLimitControllerTest.java
This is the final part of PIP-74.
https://github.com/apache/pulsar/wiki/PIP-74%3A-Pulsar-client-memory-limits
1. This feature does not take effect by default for now. Consumer memory usage take account only if `autoScaledReceiverQueueSizeEnabled` is enabled. We can change this to default when this feature is verified by more production usage.
2. Block consumer receiver queue size expansion if memory usage > 75%
3. Trigger consumer receiver queue size shrinking if memory usage > 95%
- ConsumerMemoryLimitTest
- MemoryLimitControllerTest
- …
=> [PIP-74] Support consumer client memory limit

site2/docs/tiered-storage-filesystem.md
The current tutorials for data offload use the docusaurus tab style to contain content for both HDFS and NFS. However, it is misleading people because the headings shown in the hot links are disordered. It is also hard to notice the tab itself among such a long tutorial.
1. Remove the tab style and use one more layer of heading to separate the two sections.
2. Fix links and typos.
=> [fix][doc] Remove tab style for data offload tutorials

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java
#10586 introduces NPE check to avoid problems caused by recycling race conditions, but another conditional judgment in `isDuplicate` logic is not strongly dependent on the `messageIdOfLastAck`, we can still use `pendingIndividualAcks.contains(messageId)` to judge again.
- Use `pendingIndividualAcks.contains(messageId)` to judgement when `messageIdOfLastAck` is null.
=> [improve][client] improve logic when ACK grouping tracker checks duplicated message id

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SubscribeRateLimiter.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscribeRateTest.java
Close `subscribeRateLimiter ` if it changes from non-empty to empty,  when namespace level or  topic level or broker level policies updated
All modifications are located at `org.apache.pulsar.broker.service.persistent.PersistentTopic`
=> [broker]Fix subscribeRateLimiter not close

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStore.java
When the end transaction log is appended to the transaction log, the transaction ended. The transaction should be removed from the `txnMetaMap`. If transactionLog fails to delete the location, we only need to log it.
Not complete exceptionally, but only give a warn log.
*(or)*
*(or)*
*(example:)*
- Dependencies (does it add or upgrade a …
=> [Fix][txn] Make transaction stats consistent at end txn

site2/docs/concepts-messaging.md
Fixes  #15380.
Add information to link with partition key and show its data type.
=> [improve][doc] Clarify the definition of message key

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/ListTopicsOptions.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdTopics.java
When users use CLI or REST to get topic list, there is going to show all the topics including system topics. This may confuse users, because of not created by themselves.
In this patch, I decided to add an option `--include-system-topic` when getting the topic list.   The default value if `false`, only show user-created topics.
- Add `--include-system-topic` for `list` and `list-partitioned-topics` for CLI.
- Use `ListTopicsOptions` instead of Map as the query condition.
- Deprecate `getList(String namespace, TopicDomain topicDomain, Map<QueryParam, Object> params)`
=> [improve][CLI] Support filtering system topic when get list.

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerStatsRecorderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerStatsRecorderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/conf/ClientConfigurationDataTest.java
Currently, we are print password field to consumer/producer stats log
- add missed `@JsonIgnore` on field and getMethod
- delete unused `withoutAttribute` call
=> [security] Remove sensitive msg from consumer/producer stats log

site2/docs/reference-metrics.md
Fixes  https://github.com/apache/pulsar/issues/15439
Fix doc issue about `pulsar_storage_backlog_size` metric.
According to [org.apache.bookkeeper.mledger.](https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java) #getEstimatedBacklogSize(), backlogSize should be backlog messages size in bytes.
=> [doc][monitoring] Fix doc issue about `pulsar_storage_backlog_size`  metric

site2/docs/developing-binary-protocol.md
Now, the website do not have related doc of `CommandAckResponse` in https://github.com/apache/pulsar/pull/8996.
Add the doc for `CommandAckResponse`.
*(or)*
*(or)*
*(example:)* …
=> [feature][Doc] Add doc for `CommandAckResponse`

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/FilterContext.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractBaseDispatcherTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/EntryFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java
In some cases a Consumer will reject the processing of a message, and so negative acknowledge it.
With this change you can emulate this behaviour and save resources by not sending the Entry to the Consumer, but anticipating the "negative acknowledge".
- Allow the EntryFilter to access the Consumer who is going to receive the message (add Consumer to FilterContext)
- Add a new FilterResult RESCHEDULE that means that the Filter wills to schedule the message to "another consumer" or to post pone the processing of the message
I am adding a test about two consumers on the same Shared subscription that compete on the messages, some messages are for consumer-1 and the other messages are for consumer-2
=> [enh] [broker] EntryFilter (PIP-105) - support per-Consumer filtering

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationTest.java
Fixes #14191
Master Issue: #14191
As #14191 described, users may get confused about the current permission.
First, we only define the below actions in the grant-permission interface:
```
produce,consume,sources,sinks,functions,packages
```
Though we grant all the actions to some roles like below (`myuser` is not admin, only a normal user):
```
$ pulsar-admin namespaces grant-permission public/default --role myuser --actions produce,consume,sources,sinks,functions,packages
```
But when we list topics under a namespace:
```
$ pulsar-admin --admin-url https://dev.pulsar.xyz.com:8081 --auth-plugin "org.apache.pulsar.client.impl.auth.AuthenticationToken" --auth-params "token:<token>" topics list public/default
```
We will get the below error message :
```
HTTP 403 : Unauthorized to …
```
=> [fix][security] Fix grant all permissions but can't list topic.

pulsar-client-cpp/lib/ClientImpl.cc
The pulsar-client-node library uses the c api to interact with the pulsar client. The model for the c api is to pass in a `void *ctx` to async functions with a callback. Typically, these callbacks free the context and rely heavily on the fact that the callback is called once. I was able to reproducibly trigger the close callback to call twice, resulting in a double free error in pulsar-client-node.
My running theory is that the cause for this is a race condition in the decrementing of `numberOfOpenHandlers` shared pointer. It is possible for two threads to decrement the number in parallel, and to both end up with `*numberOfOpenHandlers == 0`. This fix assumes this can happen and synchronizes on the state, so even if this does happen, only one thread will be able to set the state to …
=> [fix][c++ client] avoid race condition causing double callback on close

build/run_integration_group.sh, buildtools/pom.xml, pom.xml
After PIP-156 PR #15264 changes, Java JDK 17 is required for building Pulsar.
The previous solution to support building with Java 8 and Java 11 had added jdk11 profile. This can be removed now.
- remove obsolete jdk11, errorprone-jdk8 and errorprone-jdk11 profiles
- add Maven Enforcer plugin to stop the build when JDK is not Java 17+
=> [Build] Remove obsolete jdk11 and errorprone-jdk11 maven profiles

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/ClusterResources.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
- Make `ClusterBase` `setPeerClusterNames / getPeerCluster / deleteCluster` methods to pure async.
`AdminApi2Test#testPeerCluster` and `AdminTest#clusters` already cover this change.
=> [improve][broker] Make some methods of `ClusterBase` pure async. 

pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ReaderHandler.java, pulsar-websocket/src/test/java/org/apache/pulsar/websocket/ReaderHandlerTest.java
This fixes an issue similar to the one solved in https://github.com/apache/pulsar/pull/14316. When the `reader` is a `MultiTopicReader`, the `getConsumer()` method currently throws a `ClassCastException`.
* Update `MultiTopicReader#getConsumer` so that it safely casts the `reader`.
* Update the `ReaderHandler` constructor to use the `getConsumer` method.
I expanded existing tests to cover the scenario that would have previously failed.
No, this is not a breaking change.
=> [WebSocket] Fix MultiTopicReader#getConsumer ClassCastException

.asf.yaml
Master Issue: #12637
We are ready to switch over website publishing to the pulsar-site repository.
Remove the .asf.yaml file which stops publishing of the website from the `asf-site` branch.
(Please …
=> [feature][website] Remove .asf.yaml as website content is moving to repos/pulsar-site

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PrecisPublishLimiter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PublishRateLimiter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PublishRateLimiterDisable.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PublishRateLimiterImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
#10384 has defined PublishRateLimiter to extend AutoCloseable, but its `close ` method will throw exception, cause to cache it when updating the limiter. 
I think we can override `close` method to avoid catching the exception everywhere.
=> [cleanup][broker] Override close method to avoid caching exception.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java
Enable `SO_REUSEADDR` on listen sockets for broker,proxy, this allows sockets to be bound even if there are sockets from a previous application still in `TIME_WAIT` state, so we can restart the application at once.
Enable SO_REUSEADDR on listen sockets for broker,proxy.
This change is already covered by existing tests
(Your PR needs …
=> [improve][broker] Enable SO_REUSEADDR on listen sockets for broker,proxy

site2/docs/admin-api-packages.md
Fixes #14472
Missing a note of enabled package management on admin-api-packages page
Add a note of enabled package management on admin-api-packages page
=> [improve][doc] Add a note of enabled package management on admin-api-packages page

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/NonPersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTopicApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Avoid using the synchronization method in `internalGetStats()`.
- Use the asynchronous method instead of the synchronization method
- Remove `getStat` method from `NonPersistentTopics` controller, because of the `NonPersistentTopics` inherits `PersistentTopics`
=> [improve][broker] Make internalGetStats to async

site2/docs/administration-upgrade.md
Update hyperlink for Apache BookKeeper Upgrade guide
Fixes #15542 
Master Issue: #15542 
The hyperlink to the Apache BookKeeper Upgrade guide is out of date
Update hyperlink for Apache BookKeeper Upgrade guide
http://bookkeeper.apache.org/docs/next/admin/upgrade/
- [√ ] `no-need-doc`
=> [improve][Doc] Update hyperlink for Apache BookKeeper Upgrade guide #15542

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
Close `topicPublishRateLimiter` when it is disabled  to prevent resource leakages
Close `topicPublishRateLimiter` when it change from enable to disable
=> [fix][broker]Close publishLimiter when disable it

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
The test `SimpleProducerConsumerTest.java#testConcurrentConsumerReceiveWhileReconnect` is not stable, because restart broker operation cost time is not stable, and the consumer receive operation may be timeout before finishing restart broker operation.
```
Error:  testConcurrentConsumerReceiveWhileReconnect(org.apache.pulsar.client.api.SimpleProducerConsumerTest)  Time elapsed: 12.698 s  <<< FAILURE!
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.apache.pulsar.client.api.SimpleProducerConsumerTest that uses org.apache.pulsar.client.impl.ConsumerImpl expected [10] but found [0] within 10 seconds.
at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
at org.awaitility.core.AssertionCondition.await(AssertionCondition …
```
=> [fix][test] Adjust flaky test concurrent consume reconnect

pulsar-io/influxdb/src/main/java/org/apache/pulsar/io/influxdb/v2/InfluxDBSink.java
"measurement" is the actual mandatory field and the "device" error message is confusing in my opinion. Thus I propose to replace it so it is self-explainatory.
Replaced the word "device" (which is not a mandatory field) with "measurement" which is the correct one (check line 67)
This change is a trivial rework
- The default values of configurations:  no
- The rest endpoints:  no
- The admin cli options:  no
- Anything that affects deployment:  no
(I am not really pro in Pulsar nor java, but my understanding is that this will only affect people trying to configure topics …
=> [improve][component/connector]Replaced "Device" with "measurement"

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConsumerAckResponseTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerBuilderImplTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerBuilderImplTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ContextImplTest.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionMetaDataTopicTailerTest.java
I found out some test classes which don't set `alwaysRun=true` in the @BeforeTests and @BeforeMethod annotation.
This can cause the test setup to not run, depending on the way the maven command is specified. (for example if you don't specify the `groups` option)
* Add `alwaysRun=true`
=> [fix][tests] Add alwaysRun=true in some @Before* TestNG annotations

pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/LedgerUnderreplicationManagerTest.java
In our CI environment we've seen many times that the test `LedgerUnderreplicationManagerTest` fails in this way:
```
java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
at org.apache.pulsar.metadata.bookkeeper.LedgerUnderreplicationManagerTest.test2reportSame(LedgerUnderreplicationManagerTest.java:428)
```
All of the tests then fail. The reason behind the timeout is that the method `LedgerUnderreplicationManagerTest#getLedgerToReplicate` uses the common thread pool and it causes deadlock in some way. Using a dedicated thread pool solves the issue.
Note that I haven't ever seen this failure in the OSS pulsar CI so I believe is …
=> [improve][test] Reduce LedgerUnderreplicationManagerTest flakyness

site2/website/blog/2022-05-11-apache-pulsar-community-welcomes-500th-contributor.md
The blog post added in #14464 was missing the `.md` extension and therefore it never made it to the website. Fixed naming and changed the date since the original one was back in February.
=> [blog] renamed blog post file to have `.md` extension

site2/website/contributing.md
As commented [here](https://github.com/apache/pulsar/pull/15264#issuecomment-1113076698), moving this instruction, `how to run Pulsar CI from fork`, to the contribution page in order to make it more accessible for new contributors.
Added instructions about how to run Pulsar CI from forked github repositories in the contribution page. 
- Anything that affects …
=> [improve][doc] added instructions about how to run ci from fork

conf/presto/jvm.config, pulsar-sql/java-version-trim-agent/pom.xml, pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java, pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/package-info.java, pulsar-sql/pom.xml, pulsar-sql/presto-distribution/pom.xml, pulsar-sql/presto-distribution/src/assembly/assembly.xml, pulsar-sql/presto-pulsar/pom.xml, src/check-binary-license.sh, tests/docker-images/latest-version-image/conf/presto/jvm.config, tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/TestPrestoQueryTieredStorage.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java
Fix #14951
The presto 332 couldn't parse Java version like this `11.0.14.1`, so add a Java version trim agent to walk around the problem.
This is a temporary patch, after the presto upgrade to 332+, we could remove this.
(cherry picked from commit a1aa18f1a856d074bb23d68f5c330d3558bdf6cb)
Add a Java version trim agent to format the system property `java.version` for the Pulsar SQL plugin.
- The default values of configurations: (yes)
Check the box below or label this …
=> [cherry-pick][pulsar-sql] Java version trim agent presto332 branch2.10

pulsar-client-cpp/docker-build-centos7.sh, pulsar-client-cpp/docker/alpine/Dockerfile, pulsar-client-cpp/docker/alpine/Dockerfile-alpine-3.8, pulsar-client-cpp/docker/centos-7/Dockerfile, pulsar-client-cpp/docker/manylinux1/Dockerfile, pulsar-client-cpp/docker/manylinux2014/Dockerfile, pulsar-client-cpp/pkg/deb/Dockerfile, pulsar-client-cpp/pkg/rpm/Dockerfile
protobuf 3.3.0 is vulnerable.
https://snyk.io/vuln/pip:protobuf
upgrade the version of protobuf in pulsar-client-cpp to 3.20.0.
- Anything that affects deployment: (don't know)
=> [pulsar-client-cpp] Upgrade protobuf

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
If transaction is not in the state of open, we should not allow it to ack message with in transaction. And the message should be redeliver again.
*(or)*
*(or)*
*(example:)* …
=> [Fix][Txn] Fix transaction redeliver message if ack failed

pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicsTest.java
Master Issue: #15546
When lookup the topic ownership using REST produce, the redirect URI is incorrect, because :
```
uri.getPath(false); //Get the path of the current request relative to the base URI as a string.
```
So the redirect URI does not contain the base path:
```
URI redirectURI = new URI(String.format("%s%s", redirectAddresses.get(0), uri.getPath(false))) 
```
=> [fix][broker] Fix REST produce msg redirect issue.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
We need to make sure to trigger the removal from the map in a different thread, otherwise we can deadlock ourselves by trying to re-acquire the same StampedLock from the same thread when removing. This can happen if all the operation in the topic creation path are completing immediately and ultimately with a failure in the dedup or geo-replication check.
```
"pulsar-web-42-1" #109 prio=5 os_prio=0 cpu=3026.59ms elapsed=225914.89s tid=0x00007f7be6bf0000 nid=0x2d78 waiting on condition  [0x00007f7b268b4000]
at jdk.internal.misc.Unsafe.park(java.base@11.0.14.1/Native Method)
- parking to wait for  <0x0000000687b6a410> (a org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section)
at …
```
=> [fix][broker] Fix deadlock in broker after race condition in topic creation failure

.asf.yaml
PIP-156 PR #15264 added new build jobs which should be required checks.
Since required checks are changed, it was first necessary to remove the existing required checks that are were removed in #15264 . This was done in #15496 .  
This PR finally adds the new build jobs as required checks.
Add `CI - Integration - Shade on Java 8`, `CI - Integration - Shade on Java 11` and `CI - Integration - Shade on Java 17` to required checks in `.asf.yaml`.
- This PR shouldn't be merged before the in-progress PRs are processed, since they might have completed the build using the previous version of the GitHub Actions workflow. Merging this PR will require that the new build version has been used for all PRs.
=> [CI] Add "CI - Integration - Shade on Java *" builds as required

tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMsSqlSourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumPostgreSqlSourceTester.java
=> [cleanup][tests] Use TestNG instead of JUnit

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/PendingAckHandleImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckPersistentTest.java
Now, PendingAckHandle use the ending transaction ID to append abort mark, but it is wrong. We should append abort mark for the first transaction in the  individualAckOfTransaction after judgment.
Append abort mark for the first transaction in the  individualAckOfTransaction after judgment.
*(or)*
*(or)*
*(example:)*
- Dependencies (does …
=> [Fix][Txn] Fix transaction PendingAck lowWaterMark

site2/docs/security-encryption.md, site2/website/versioned_docs/version-2.10.0/security-encryption.md, site2/website/versioned_docs/version-2.7.2/security-encryption.md, site2/website/versioned_docs/version-2.7.3/security-encryption.md, site2/website/versioned_docs/version-2.7.4/security-encryption.md, site2/website/versioned_docs/version-2.8.0/security-encryption.md, site2/website/versioned_docs/version-2.8.1/security-encryption.md, site2/website/versioned_docs/version-2.8.3/security-encryption.md, site2/website/versioned_docs/version-2.9.0/security-encryption.md, site2/website/versioned_docs/version-2.9.1/security-encryption.md, site2/website/versioned_docs/version-2.9.2/security-encryption.md
Fixes #15522 
1. Clarify the scope of key pairs for different clients.
2. Minor fixes.
3. Apply both item1 and item2 to more historical versions of docs since 2.7.2.
=> [fix][doc] Add the scope of key pairs for different clients

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ContextImplTest.java, pulsar-io/common/src/test/java/org/apache/pulsar/io/common/IOConfigUtilsTest.java, pulsar-io/core/src/main/java/org/apache/pulsar/io/core/SinkContext.java, pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/sink/KafkaAbstractSinkTest.java
The configuration of SinkConfig is rich, and the user can flexibly specify it when registry the sink. But some sinks do not support these configurations, for example we want to disable autoAck.
So, add SinkConfig to SinkContext, enables the sink to validate the configuration when executing the `sink.open` method.
- Add getSinkConfig method to SinkContext
=> [improve][connector] Add getSinkConfig method to SinkContext

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorInfoMetadataTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java, managed-ledger/src/test/java/org/apache/bookkeeper/test/ZooKeeperUtil.java
=> [cleanup][managed-ledger] Use TestNG instead of JUnit

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Remove repeated `subscribeRateLimiter`  update for topic-level and ns-level, because we have updated it using `org.apache.pulsar.broker.service.persistent.PersistentTopic#updateSubscribeRateLimiter`
Remove repeated subscribeRateLimiter update
=> [improve][broker]Remove repeated subscribeRateLimiter update

site2/docs/deploy-bare-metal.md
Fixes # 15071
Previous command doesn't need the cluster name for the execution of the command
- [ X] `no-need-doc` 
- [ X] `doc` 
=> [Improve][Doc] Unnecessary warning removal

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
BookKeeper 4.14.5 has been released. It contains a crucial fix identified in Pulsar (https://github.com/apache/pulsar/issues/14436)
Release notes: https://bookkeeper.apache.org/release-notes/#4145
* Upgrade BK dependency
=> [improve] Upgrade BookKeeper to 4.14.5 (2.8, 2.9, 2.10 branches)

site2/docs/io-elasticsearch-sink.md
=> [improve][doc] Include Elasticsearch sink compatibility 

CONTRIBUTING.md
The current link to the contributor's guide is broken and results in a 404. Replace it with the new link.
* Update the `CONTRIBUTING.md` link.
=> [docs] Fix broken contributing guide link

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SinkConfigUtilsTest.java
Currently there's no way to remove the timeout from a running sink. You get a error like `Sink timeout must be a positive number`. 
- Allow to set timeout=0 when creating/updating a sink
=> [improve][functions] Sinks: allow to reset --timeout-ms to zero

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TenantResources.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
Make `NamespacesBase` `getTenantNamespaces / createNamespace / getTopics / getPolicies / getPermissions` methods to pure async.
=> [improve][broker] Make some methods in NamespacesBase async.

pulsar-client-cpp/python/pulsar/__init__.py
This is just a small docstring fix. This example was fixed in other locations a long time ago in PR #1951 but it appears they were missed in the same example that lives in these docstrings. They show up in the pdoc generated docs: https://pulsar.apache.org/api/python/2.10.0/pulsar.html
=> [fix][doc] Adjust python example in cpp client directory to fix string interpolation

pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/LedgerManagerIteratorTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/LedgerUnderreplicationManagerTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarLayoutManagerTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerAuditorManagerTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarMetadataDriverBaseStaticTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClientTest.java
=> [cleanup][metadata] Use TestNG instead of JUnit

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiClusterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiDynamicConfigurationsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiHealthCheckTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleBrokerStartTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractBaseDispatcherTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/LedgerOffloaderMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/TimeWindowTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionClientConnectTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorMXBeanImplTest.java
=> [cleanup][broker] Use TestNG instead of JUnit

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, site2/docs/reference-pulsar-admin.md
In the `pulsar-admin` command, enable users to specify values for some time-related options not only in seconds, but also in minutes, hours, days, and so on.
e.g.
```sh
$ ./bin/pulsar-admin topics expire-messages -s sub -t 3h persistent://foo/bar/baz
```
Use the existing utility method [RelativeTimeUtil#parseRelativeTimeInSeconds](https://github.com/apache/pulsar/blob/c8d24108b0fb80ad0f8b3a6a8337429efc667a2b/pulsar-common/src/main/java/org/apache/pulsar/common/util/RelativeTimeUtil.java#L31-L67) to parse the given options and convert them to seconds.
=> [improve][admin] Enable users to specify some time options in units other than seconds

pulsar-client/src/test/java/org/apache/pulsar/client/impl/AutoClusterFailoverTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerImplTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/auth/oauth2/protocol/TokenClientTest.java
=> [cleanup][client] Use TestNG instead of JUnit

pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMapTest.java
=> [cleanup][common] Use TestNG instead of JUnit

docker/pulsar/scripts/apply-config-from-env-with-prefix.py
Copying change from `apply-config-from-env.py` to ensure new line included before appending 
- The schema: ( no)
- The wire protocol: ( no)
- The rest endpoints: ( no)
- The admin cli options: ( no)
- Anything that affects deployment: ( no )
=> [fix][broker] ensure new line added before appending new keys from env

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/NonPersistentTopicStatsImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java, pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/NonPersistentPartitionedTopicStatsTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/PersistentTopicStatsTest.java
Fixes #15471
Please see https://github.com/apache/pulsar/issues/15471 .
* if producerName is null, then fall back to `supportsPartialProducer=false`
- currently, producerName is required when`supportsPartialProducer=true`, because stats are aggregated by producerName
* allow null producerName on getPublishers
* Add tests for null producerName
This PR is one of the fixing issues.
=> [fix][broker] Fix to avoid TopicStatsImpl NPE even if producerName is null

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
Revert https://github.com/apache/pulsar/pull/15524
In the previous implementation, if the user confirmed the message with the transaction that the supermarket has timed out, an exception will be reported to the user and the message will be redeliver. But after our discussion, we think that it may be a better choice to hand over whether to resend the message to the users.
Recover the previous implementation.
*(or)*
*(or)*
*(example:)*
- *Extended …
=> Revert #15524: do not redeliver message when txn is not opened

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java, pulsar-common/src/main/java/org/apache/pulsar/common/stats/JvmMetrics.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/DirectMemoryUtils.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntimeFactory.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntimeFactoryTest.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerStatsManager.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerfClientUtils.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/stats/JvmMetrics.java
- `PlatformDependent.maxDirectMemory()` can be inaccurate if `io.netty.maxDirectMemory` are setted
- Bookkeeper's `DirectMemoryUtils` is not worked within some jdk releases.
In netty 4.1.75, they introduced a new method `PlatformDependent.estimateMaxDirectMemory` to help users get maxDirectMemory. Since netty's this method works well on many jdk releases, use this to replace below two.
PS: `DirectMemoryUtils` has been removed from bookkeeper in https://github.com/apache/bookkeeper/pull/2989
- use `PlatformDependent.estimateMaxDirectMemory` instead
=> use netty PlatformDependent.estimateMaxDirectMemory

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
https://github.com/apache/pulsar/blob/58c82a71beb7506e422def391af532945be2b7a7/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L377-L399
The object lock may change when execute at line-382, and cause the lock to become useless.
So use `dispatchRateLimiterLock` to synchronize.
=> [fix][broker] Use dispatchRateLimiterLock to update dispatchRateLimiter.

site2/docs/reference-metrics.md
- Add `topic_load_times`
- Move the managed ledger cache and connection metrics under the broker metrics section
=> [doc] Add topic load latency metrics documentation

pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/bookkeeper/test/BookKeeperClusterTestCase.java
=> [cleanup][package-management] Use TestNG instead of JUnit

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/schema/KafkaConnectData.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/PulsarSchemaToKafkaSchemaTest.java
Kafka Connect Adaptor Sink may fail with 
```
ERROR org.apache.pulsar.io.kafka.connect.KafkaConnectSink - Error sending the record SinkRecord(sourceRecord=PulsarRecord(topicName=Optional[persistent://pexpipelinetest/connectors/cbart-pex-text.public.links], partition=0, message=Optional[org.apache.pulsar.client.impl.MessageImpl@528e9a52], schema=AUTO_CONSUME({schemaVersion=,schemaType=BYTES}{schemaVersion=\x00\x00\x00\x00\x00\x00\x00\x06,schemaType=KEY_VALUE}{schemaVersion=org.apache.pulsar.common.protocol.schema.LatestVersion@1ec80826,schemaType=KEY_VALUE}), failFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$303/0x0000000100728040@4bcce14b, ackFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$302/0x0000000100709c40@24de2714), value=(key = …
```
=> [fix][connector] KCA Sink: org.apache.kafka.connect.errors.DataException: Invalid Java object for schema with type ..

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcher.java
`NonPersistentDispatcher`'s superclass `Dispatcher` already declares exactly the same methods, so definitions of those methods are completely unnecessary.
https://github.com/apache/pulsar/blob/b6351f73481fc78d8ba13f7355194c9c51dc59c4/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcher.java#L34-L50
Delete these methods
=> [cleanup][broker] Delete duplicate method definitions

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
Make NamespacesBase `getDeduplication / modifyDeduplication / removeDeduplication` methods to pure async.
=> [improve][broker] Make some operation deduplication methods in Namespaces async.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Tidy up the code updating rate limiter to make it more clear.
* Pick `updateSubscribeRateLimiter()` out of `initializeRateLimiterIfNeeded` to make the code more clear. 
* Also rename `initializeRateLimiterIfNeeded` to  `initializeDispatchRateLimiterIfNeeded`
=> [cleanup][broker]Tidy dispatchRateLimiter init

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
Make NamespacesBase `getNamespaceMessageTTL / setNamespaceMessageTTL / removeNamespaceMessageTTL ` methods to pure async.
=> [improve][broker] Make some operation messageTTL methods in Namespaces async.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
It's because of this issue https://github.com/apache/pulsar/issues/13787.
Then diving into the codes, I find that if the client tries to subscribe multiple times over a short period of time, it is possible to have more than one consumer at the same dispatcher. just like below:
```
for ( long requestId = 1; i < 5; i++ ){
ByteBuf request1 = Commands.newSubscribe(topic, subscription, consumerId, requestId , getSubType(),
priorityLevel, consumerName, isDurable, startMessageIdData, metadata, readCompacted,
conf.isReplicateSubscriptionState(),
InitialPosition.valueOf(subscriptionInitialPosition.getValue()),
startMessageRollbackDuration, si, createTopicIfDoesNotExist, conf.getKeySharedPolicy(),
// Use the current epoch to subscribe.
conf.getSubscriptionProperties(), CONSUMER_EPOCH.get(this)); …
```
=> [fix][broker] Fix potential to add duplicated consumer

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
- release notes https://netty.io/news/2022/05/06/2-1-77-Final.html
- some highlights:
- improves Alpine / musl compatibility
- could help issues such as #14534 #11415 #11224 #10798
- improves shading compatibility
- fixes a bug related to the native epoll transport and epoll_pwait2
Upgrade Netty to 4.1.77.Final and netty-tcnative to 2.0.52.Final
=> Upgrade Netty to 4.1.77.Final and netty-tcnative to 2.0.52.Final

pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java, pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandaloneStarter.java
Fixes #15625
There's an issue  reported about problems in broker shutdown. This PR will help print log fully when we shut down broker;
After this PR fixed, the broker shutdown log printed as follow:
We have set `log4j.shutdownHookEnabled=false`, so we need add finally `LogManager.shutdown()` invoke in `PulsarBrokerStarter` and `PulsarStandaloneStarter` Runtime ShutdownHook.
=> [Broker] Fix logging in shutdown when broker shutdown

src/owasp-dependency-check-false-positives.xml
`google-http-client-gson-1.41.0.jar` is getting confused with gson version < 2.8.9
>the package com.google.code.gson:gson before 2.8.9 are vulnerable to Deserialization of Untrusted Data via the writeReplace() method in internal classes, which may lead to DoS attacks.
CI failure: https://github.com/apache/pulsar/runs/6483813433?check_suite_focus=true#step:8:13
* Suppress that rule for that package
=> [fix][owasp] Fix false positive google-http-client-gson-1.41.0.jar

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/ResourceUnit.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerWrapper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleResourceUnit.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/AdvertisedListenersTest.java
#14839 fixes the HTTP lookup with multiple advertised listeners, and the added test
is trying to verify the advertised listeners with 2 brokers, but the config of the
the additional broker will not update, so the test gets passed.
The root cause is we are using the (advertised address + WebService port) to register
the broker under the loadbalance path, but while creating the lookup result, we will
use the WebService URL to get the data, so we will get `MetadataStoreException$NotFoundException`.
```
2022-05-17T14:18:55,658+0800 [pulsar-load-manager-38-1] INFO  org.apache.pulsar.metadata.coordination.impl.ResourceLockImpl - Acquired resource lock on /loadbalance/brokers/BROKER-0:15004
2022-05-17T14:19:01,126+0800 [pulsar-4-1] WARN  org.apache.pulsar.broker.lookup.TopicLookupBase - Failed …
```
=> [fix][broker] fix MetadataStoreException$NotFoundException while doing topic lookup

.github/workflows/ci-owasp-dependency-check.yaml
Owasp check doesn't work with branch-2.9 and branch-2.8 because now it uses JDK 17. They have to run with JDK 11.
Also branch-2.10 is missing
- Added explicit exception in the job to use JDK 11 for branch 2.8, 2.9 and 2.10, leave master and future release branches to use JDK 17
- Add 2.10 to the matrix
=> [ci] Owasp check: add branch-2.10 and fix JDK version for each branch

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Subscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsController.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSubscriptionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBase.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ResetCursorData.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/CLITest.java
Fixes #15455
We are missing tools to manage Subscription properties introduces in PIP-105.
Add initial support to "create subscription" in PulsarAdmin API (Java and CLI) to pass subscription properties.
The properties are passed as a query string parameter in order to keep compatibility with the old API and do not require a new API.
This patch adds tests
The documentation of pulsar-admin and PulsarAdmin is automatically generated, no need to do anything more
=> [enh] Issue 15455: Pulsar Admin: create subscripion with Properties (PIP-105)

bin/pulsar, bin/pulsar-daemon, conf/bkenv.sh, conf/pulsar_env.sh
1、same as #14725, `BOOKIE_PID_DIR` in `bkenv.sh` took no effect.
2、If We set `BOOKIE_LOG_DIR` and `PULSAR_LOG_DIR` rather than default value `PULSAR_HOME/logs`. Error below would be thrown.
```
[0.002s][error][logging] Error opening log file 'logs/pulsar_bookie_gc_36230.log': No such file or directory
[0.002s][error][logging] Initialization of output 'file=logs/pulsar_bookie_gc_%p.log' using options 'filecount=10,filesize=20M' failed.
Invalid -Xlog option '-Xlog:gc*:logs/pulsar_bookie_gc_%p.log:time,uptime,level,tags:filecount=10,filesize=20M', see error log for details.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
3. When set `BOOKIE_LOG_DIR` in `bkenv.sh`, it would be overwrite by `PULSAR_LOG_DIR` set in `pulsar_env.sh`, …
=> [fix][env]Fix wrongly set jvm gc log dir

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerBuilderImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerBuilderImplTest.java
when `messageRoutingMode` is set `CustomPartition` and `messageRouter` is  not set,  the exception message is :
```
When 'messageRouter' is set, 'messageRoutingMode' should be set as CustomPartition
```
which will confuse the users
Correct the exceptions message
-  `org.apache.pulsar.client.impl.ProducerBuilderImplTest#testProducerBuilderImplWhenMessageRoutingIsCustomPartitionAndMessageRouterNotSet`
=> [improve][client] improve exception messages in setMessageRoutingMode

site2/docs/tiered-storage-overview.md, site2/website/versioned_docs/version-2.10.0/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.10.0/tiered-storage-overview.md, site2/website/versioned_docs/version-2.7.0/tiered-storage-overview.md, site2/website/versioned_docs/version-2.7.2/tiered-storage-overview.md, site2/website/versioned_docs/version-2.7.3/tiered-storage-overview.md, site2/website/versioned_docs/version-2.7.4/tiered-storage-overview.md, site2/website/versioned_docs/version-2.8.0/tiered-storage-overview.md, site2/website/versioned_docs/version-2.8.1/tiered-storage-overview.md, site2/website/versioned_docs/version-2.8.2/tiered-storage-overview.md, site2/website/versioned_docs/version-2.8.3/tiered-storage-overview.md, site2/website/versioned_docs/version-2.9.0/tiered-storage-overview.md, site2/website/versioned_docs/version-2.9.1/tiered-storage-overview.md, site2/website/versioned_docs/version-2.9.2/tiered-storage-overview.md
Before:
After:
🔹🔹🔹🔹🔹
Fix https://github.com/apache/pulsar-site/issues/89
Rule: https://docs.google.com/document/d/12De2btkDHQVaqUlHjTqERmroMLKGhHdiC7rEttFTyqc/edit#bookmark=id.jxpgnl5lpf0i
Before:
After:
=> [fix][doc] Fix incorrect rendering issues

pom.xml
JClouds 2.4.0 is marked as vulnerable because it contains gson 2.8.5 which has a CVE reported (CVE-2022-25647)
We already override the gson dependency but given that:
- owasp check fails https://github.com/apache/pulsar/runs/6483813433?check_suite_focus=true
- upgrading from 2.4.0 to 2.5.0 is light https://jclouds.apache.org/releasenotes/2.5.0/
it is better to upgrade to 2.5.0
* Upgrade JClouds to 2.5.0
=> [improve][offloaders] Upgrade JClouds to 2.5.0

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
When the user wants to set the `AutoTopicCreationOverride` policy with `non-partitioned` type, the correct request body is as below. 
```json
{
"allowAutoTopicCreation": true,
"topicType": "non-partitioned"
}
```
On the broker side, the request body entity field `defaultNumPartitions` is `null`. the NPE will occur when the user sets config `maxNumPartitionsPerPartitionedTopic` greater than 0.
https://github.com/apache/pulsar/blob/3c60063716d3cdd561bf1e956a551a2297869fd9/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L839-L842
- Check `maxNumPartitionsPerPartitionedTopic` just `topicType` is `partitioned`
Add a test `testAutoTopicCreationOverrideWithMaxNumPartitionsLimit` to verify this change.
=> [fix][broker] Fix NPE when set `AutoTopicCreationOverride`

.github/workflows/ci-owasp-dependency-check.yaml
Owasp regular checks is now failing with this error
```
Invalid workflow file
The workflow is not valid. .github/workflows/ci-owasp-dependency-check.yaml (Line: 69, Col: 13): Unexpected symbol: '"branch-2'. Located at position 16 within expression: matrix.name != "branch-2.8" && matrix.name != "branch-2.9" && matrix.name != "branch-2.10" .github/workflows/ci-owasp-dependency-check.yaml (Line: 76, Col: 13): Unexpected symbol: '"branch-2'. Located at position 16 within expression: matrix.name == "branch-2.8" || matrix.name == "branch-2.9" || matrix.name == "branch-2.10"
```
That is because single quote must be used with strings.
* Use single quote for strings
=> [fix][ci] Fix Owasp dependency check: Unexpected symbol: branch-2

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/PulsarResources.java
In old version, the `configurationMetadataStore` and `localMetadataStore` are exposed.
This behavior broke by [#12078](https://github.com/apache/pulsar/pull/12078/files#diff-2784063a9101df0581a149ff4129b18623c01ca4638a91e3fdd58c380e75dd2cL31).
Affected version: 2.9.x, 2.10.x
- expose the `configurationMetadataStore` and `localMetadataStore` in `PulsarResources`
=> [fix][broker-common] expose configurationMetadataStore and localMetadataStore

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchExtractTests.java, site2/docs/io-elasticsearch-sink.md, site2/website/versioned_docs/version-2.10.0/io-elasticsearch-sink.md
In case of the inbound message is structured (Avro or JSON) the fields order may change overtime and there's no fields order guarantee from the Pulsar function framework.
The generated _id field of the document is supposed to be the same regardless the input message key fields order.    
* New option `canonicalKeyFields` (boolean, default false) to sort the key fields. Both for JSON and Avro we have to parse and rewrite the entire payload. It may increase the CPU overhead even if the sort is only performed on the keys that MUST be lower to 512 bytes in order to suit in the ElasticSearch _id field.
=> [feature][connector] ElasticSearch Sink: option to output canonical key fields (JSON and Avro)

.gitignore, .mvn/wrapper/maven-wrapper.properties, README.md, mvnw, mvnw.cmd, pom.xml
* The maven wrapper helps getting started quickly without having to install Maven
* It helps to control that a working version of Maven is used
* Added the wrapper
* Modified READMEs to use the wrapper
Scripts and CI still use the unwrapped `mvn` command and Maven is still indicated as a requirement but this could be changed in a later PR.
Install the project with `./mvnw install -DskipTests`
This change is a trivial rework
- The public API: (yes / no) no
- The schema: (yes / no / don't know) no
- The default values of configurations: (yes / no) no
- The wire protocol: (yes / no) no
- The rest endpoints: (yes / no) no
- The admin cli options: (yes / no) no
- Anything …
=> [feature][tool] Add the Maven wrapper

pom.xml
Hadoop versions < 3.3.3 are vulnerable to [CVE-2022-26612](https://nvd.nist.gov/vuln/detail/CVE-2022-26612) which has a CVSS score of 9.8
3.3.3 has been released yesterday and it contains the fix
See https://issues.apache.org/jira/browse/HADOOP-18198 for more details
* Upgrade from 3.3.1 to 3.3.3
=> [fix][security] Tiered storage: Upgrade Hadoop to 3.3.3 to get rid of CVE-2022-26612

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
Currently only `--user-config '{"some-key": "some-value"}}'` is allowed which is limiting
With this change any JSON compatible object is allowed. Eg: `--user-config '{"some-key": ["value1", "value2"]}}'`
Changed TypeToken to `TypeToken<Map<String, Object>>() {}`
Run test `CmdFunctionsTest::testCreateFunction`
No
(Your PR needs to …
=> [improve][admin] Parse function userConfig to Map<String, Object>

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-common/pom.xml, pulsar-sql/presto-distribution/LICENSE
Make `CompressorCodecBackwardCompatTest` paas on Apple M1
- Bump snappy from 1.1.7 to 1.1.8.4
- Bump zstd version from 1.3.7-3 to 1.1.8.4
=> Bump snappy zstd version to fix CompressorCodecBackwardCompatTest on Apple M1

site2/docs/develop-binary-protocol.md, site2/docs/developing-binary-protocol.md
Fixes #15690 
1. Add a note for performing topic lookup before creating/connecting a producer/consumer.
2. Add deprecation notice to an outdated doc page.
=> [fix][doc] Binary protocol spec: perform topic lookup before creating/connecting a producer/consumer

site2/docs/schema-evolution-compatibility.md
Fix wrong text in Full and Full Transitive schema compatibility 
=> [fix][doc] Fixed wrong text in Full Transitive and Full Schema Compatibility docs

pulsar-client-cpp/lib/Future.h, pulsar-client-cpp/python/CMakeLists.txt, pulsar-client-cpp/python/src/client.cc, pulsar-client-cpp/python/src/consumer.cc, pulsar-client-cpp/python/src/exceptions.cc, pulsar-client-cpp/python/src/producer.cc, pulsar-client-cpp/python/src/pulsar.cc, pulsar-client-cpp/python/src/reader.cc, pulsar-client-cpp/python/src/utils.cc, pulsar-client-cpp/python/src/utils.h
Fix #6477
Currently the Python wrapper is calling blocking methods in the C++ API. That means that the Python interpreter thread is stuck in the blocking call (even if other Python threads are allowed to run), but it will prevent the interpreter to process any OS signals.
Instead, we should use C++ async methods and check periodically for Python signals, so that we can unblock the interpreter when needed.
Added wrapper functions to handle the logic of checking for the future completion and for the Python signal handling.
=> [Python] Use async C++ calls to check for Python signals

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/RangeCacheTest.java
When `ReferenceCounted` object overrides the method `deallocate` to make the `getLength` value equal null will cause NPE because the `RangeCache#put` method is not thread-safe. (The process of describing this abstraction is not very clear, please refer to the code modification :)
Pulsar implementation may throw an exception to make `OpAddEntry` fail abnormal and fence the topic. relative code as below:
https://github.com/apache/pulsar/blob/defeec0e84a63ea865f3a2790bc61b66a02254c5/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java#L211-L217
**Exception screenshot:**
```java
java.lang.NullPointerException: Cannot invoke "String.length()" because "value.s" is null
at org.apache.bookkeeper.mledger.util.RangeCacheTest.lambda$testInParallel$6(RangeCacheTest.java:279) …
```
=> [fix][ML]Fix NPE when put value to `RangeCache`.

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
First time I tried to use this method, I got an unhelpful error. It turns out all I had to do was call `enableRetry(true)` on the consumer. A better error message would have saved me a lot of time :)
=> [improve][java-client] Better error message for `reconsumeLater`

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/Metadata.java, pulsar-common/src/test/java/org/apache/pulsar/common/naming/MetadataTests.java
There is a hard coded limit of 1k for the Consumer Metadata, it may happen that a Consumer fails to subscribe due to this limit.
Consumer metadata are often used to provide information about the Consumer.
It may happen that such pieces of information are collected from the local environment of the Consumer and they could be slightly bigger than 1kb. 
We should make this limit configurable, to unblock such usercases.
Add `maxConsumerMetadataSize` configuration parameter, defaults to 1k as in previous Pulsar versions
This change is already covered by existing tests and I have added some new tests
=> [enh] Broker: make max size of Consumer metadata configurable

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/HierarchyTopicPolicies.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TopicPolicies.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
Since `schemaValidationEnforced` is supported on namespace and broker level, so this patch is going to support it on topic level.
=> [feature][broker] Support `schemaValidationEnforced` on topic level.

pulsar-client-cpp/include/pulsar/Result.h, pulsar-client-cpp/include/pulsar/c/result.h, pulsar-client-cpp/lib/BlockingQueue.h, pulsar-client-cpp/lib/ClientImpl.cc, pulsar-client-cpp/lib/ConsumerImpl.cc, pulsar-client-cpp/lib/ExecutorService.cc, pulsar-client-cpp/lib/MemoryLimitController.cc, pulsar-client-cpp/lib/MemoryLimitController.h, pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc, pulsar-client-cpp/lib/PartitionedConsumerImpl.cc, pulsar-client-cpp/lib/ProducerImpl.cc, pulsar-client-cpp/lib/Result.cc, pulsar-client-cpp/lib/Semaphore.cc, pulsar-client-cpp/lib/Semaphore.h, pulsar-client-cpp/lib/UnboundedBlockingQueue.h, pulsar-client-cpp/python/src/enums.cc, pulsar-client-cpp/python/src/exceptions.cc, pulsar-client-cpp/tests/BlockingQueueTest.cc, pulsar-client-cpp/tests/SemaphoreTest.cc, pulsar-client-cpp/tests/UnboundedBlockingQueueTest.cc
All the blocking operations on the C++ client are currently not unblocked when the producer/consumer/client are closed. 
Introduced new error `ResultInterrupted` which is triggered when client is closed while we're waiting on some conditions.
=> [C++] Unblock all threads when Pulsar client is closed

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MemoryLimitController.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
Fixes #15691
There's a performance regression in 2.10 in geo-replication since the client memory limit is enabled by default in  "PIP-120: Enable client memory limit by default", #13306 .
- disable memory limit by default for broker client and replication clients
- restore the default `maxPendingMessages` & `maxPendingMessagesAcrossPartitions` limits for producers to the defaults used before PIP-120 changes when the memory limit is disabled.
- The broker client's producer is used in a few location and it would be more consistent also for other applications when the defaults are adjusted if the memory limit is disabled.
=> [Broker] Disable memory limit controller for broker client and replication clients

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java
=> [branch-2.9] [Authorization] Role with namespace produce authz can also get topics.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java
https://github.com/apache/pulsar/pull/14809 is not cherry-picked to branch-2.7 and branch-2.8, but we support system topic since 2.6, so this issue is also existed in branch-2.8. So we need to cherry-pick it.
=> [branch-2.8][broker] Fix can not enable system topic if `AutoUpdateSchemaEnabled=false`.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
We find that sometimes the broker shutdown blocked at BrokerService#unloadNamespaceBundlesGracefully:
```
2022-05-20T03:37:05.4960249Z "main" #1 prio=5 os_prio=0 cpu=32274.29ms elapsed=2566.54s tid=0x00007fd108024380 nid=0x1af8f waiting on condition  [0x00007fd10fcd0000]
2022-05-20T03:37:05.4960659Z    java.lang.Thread.State: WAITING (parking)
2022-05-20T03:37:05.4961114Z 	at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
2022-05-20T03:37:05.4961875Z 	- parking to wait for  <0x00000000cdf00010> (a java.util.concurrent.CompletableFuture$Signaller)
2022-05-20T03:37:05.4962343Z 	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.3/LockSupport.java:211)
2022-05-20T03:37:05.4963171Z 	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.3/Completable …
```
=> [fix][broker] Add timeout for unload namespace bundle.

site2/docs/io-cli.md, site2/docs/io-overview.md, site2/docs/io-quickstart.md, site2/docs/io-use.md, site2/website/sidebars.json, site2/website/versioned_docs/version-2.10.0/io-cli.md, site2/website/versioned_docs/version-2.10.0/io-overview.md, site2/website/versioned_docs/version-2.10.0/io-quickstart.md, site2/website/versioned_docs/version-2.10.0/io-use.md, site2/website/versioned_sidebars/version-2.10.0-sidebars.json
Both version 2.10 and the next version docs have broken links and fail to redirect to the io-cli page.
However, this io-cli page (https://pulsar.apache.org/docs/next/io-cli/) is no longer maintained.
This fix is to make https://pulsar.apache.org/tools/pulsar-admin/ the single source of truth for Pulsar admin docs and for i/o connector admin docs as well.
1. Add a deprecation notice in the `io-cli.md` file and hide it from left navigation.
2. Update occurrences that have referenced `io-cli.md` in other files.
3. Minor typo fixes.
=> [fix][doc] Deprecate io-cli page and update occurrences referenced elsewhere

tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/provider/JCloudBlobStoreProvider.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/provider/TieredStorageConfiguration.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/provider/JCloudBlobStoreProviderTests.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/provider/TieredStorageConfigurationTests.java
There have some cloud storages are compatible with S3
APIs, such as aliyun-oss. Some other storages also use
the S3 APIs and want to offload the data into them, but
we only support the AWS or the Aliyun.
The PR https://github.com/apache/pulsar/pull/8985 provides
the Aliyun offload provider, but it has a force limitation of
the `S3Constants.PROPERTY_S3_VIRTUAL_HOST_BUCKETS`. That
is not a limitation on other storage services which compatible
with S3 APIs.
This PR provides  a more general offload provider `S3` which uses
pure JClouds S3 metadata and allows people to override the
default JClouds properties through system properties.
- Add the pure S3 offload provider …
=> [feat] [tiered-storage] Add pure S3 provider for the offloader

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
Currently creating a built-in function with argument `--jar builtin://my-built-in-function` is rejected with error `The specified jar file does not exist`.
This change allows to do it.
Check if the jar starts with `builtin://`
Run test `CmdFunctionsTest::testCreateFunctionWithBuiltinNar `
No
Need to …
=> [improve][admin] Allow creating builtin functions in pulsar-admin CLI

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/JsonConverterTests.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearchSinkTester.java
Avro native objects for Arrays and Maps are not supported by the sink.
If you try to use a Java POJO with a java.util.List/java.util.Set field with Avro Schema, you get:
```
022-04-26T11:56:51.477776276Z Caused by: java.lang.ClassCastException: class org.apache.avro.generic.GenericData$Array cannot be cast to class [Ljava.lang.Object; (org.apache.avro.generic.GenericData$Array is in unnamed module of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
2022-04-26T11:56:51.477782027Z 	at org.apache.pulsar.io.elasticsearch.JsonConverter.toJson(JsonConverter.java:90) ~[?:?
```
For java.util.Map
```
ERROR org.apache.pulsar.io.elasticsearch.ElasticSearchSink - write error:
2022-04-26T12:03:34.776219894Z java.lang.IllegalArgumentException: Error while converting a …
```
=> [fix][elasticsearch-sink] Handle Avro collections native types (GenericData.Array and Utf8 map keys)

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java
When trying to reproduce the problem of #15609 using the master's code, it was found that the master also had this bug. The root cause is:
When there is only one ledger in the ManagedLedger, after the current ledger is closed, it has the timestamp and exceeds the time set by the backlog-qutoa, resulting in the failure to create the producer.
The added test could reproduce this. 
So when there is only one ledger, we should not exclude it.
If revert this patch, the added test will fail.
=> [fix][broker] Fix creating producer failure when set backlog quota.

site2/docs/concepts-messaging.md
Clarified the documentation on Exclusive and Failover subscription types
=> [fix][doc] Clarify Exclusive and Failover subscription types

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerWrapper.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java
PR #15633 uses the API `Map.of()` introduced in JDK 9, but branch-2.9 needs to be compiled in JDK 8.
- Use `Collections.unmodifiableMap(map)` to instead of `Map.of()`
=> [branch-2.9][fix][broker] Fix jdk API compatibility issues.

site2/docs/concepts-messaging.md
Add two links to Message Deduplication documentation pointing to the PIP which explains the design and how it works, and to a blog post that is also related.
=> [fix][doc] Message Deduplication: Add more links for how it works under the hood

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/LockManagerImpl.java, testmocks/src/main/java/org/apache/zookeeper/MockZooKeeper.java
Master issue #15643, #15753
Blocked at BrokerService#unloadNamespaceBundlesGracefully:
```
2022-05-20T03:37:05.4960249Z "main" #1 prio=5 os_prio=0 cpu=32274.29ms elapsed=2566.54s tid=0x00007fd108024380 nid=0x1af8f waiting on condition  [0x00007fd10fcd0000]
2022-05-20T03:37:05.4960659Z    java.lang.Thread.State: WAITING (parking)
2022-05-20T03:37:05.4961114Z 	at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
2022-05-20T03:37:05.4961875Z 	- parking to wait for  <0x00000000cdf00010> (a java.util.concurrent.CompletableFuture$Signaller)
2022-05-20T03:37:05.4962343Z 	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.3/LockSupport.java:211)
2022-05-20T03:37:05.4963171Z 	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.3/CompletableFuture.java:186 …
```
=> [fix][broker] Fix the broker close hanged issue.

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest2.java
Cherry-pick https://github.com/apache/pulsar/pull/13164
=> [branch-2.9] fix:remove the loadbalance/bundle-data node

docker/pulsar/Dockerfile
Fixes #15230
The Quickstart/[Getting Started in Docker](https://pulsar.apache.org/docs/next/getting-started-docker) example does not work with Pulsar 2.10.0:
```shell
docker run -it -p 6650:6650  -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:2.10.0 bin/pulsar standalone
```
When you run the command, you get a permissions error:
```
ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.
java.nio.file.AccessDeniedException: /pulsar/data/standalone
```
This is because the Docker image is running as a non-root user but does not have permissions to write to the volume being mounted at `/pulsar/data`
I think this issue is an important concern because it frustrates prospective/new Pulsar …
=> [Fix][Docker] Add write permissions to /pulsar subdirectories to enable running as non-root user

pulsar-client-cpp/python/build-mac-wheels.sh
To get broader compatibility for Python wheel files on Mac, we can target MacOS 10.15 instead of 11.0.
=> [Python] Use MacOS 10.15 as the target OS version for Python wheel files

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, site2/docs/reference-pulsar-admin.md
There were some options that weren't fixed in [the previous PR](https://github.com/apache/pulsar/pull/15563), so I fixed them as well as the other options.
=> [improve][admin] Enable users to specify TTL options in units other than seconds

site2/docs/concepts-messaging.md
* Clarify the notion that non-persistent topics do not buffer in-memory messages at all.
=> [fix][doc] Clarifying non-persistent topics a bit more

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LinuxBrokerHostUsageImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadReportNetworkLimitTest.java
Apply  fix #15304 to branch-2.9
=> [fix][branch-2.9] Fix wrong unit of NIC speed on linux 

site2/docs/security-basic-auth.md, site2/docs/security-overview.md, site2/website/sidebars.json, site2/website/versioned_docs/version-2.10.0/security-basic-auth.md, site2/website/versioned_docs/version-2.10.0/security-overview.md, site2/website/versioned_docs/version-2.8.0/security-basic-auth.md, site2/website/versioned_docs/version-2.8.0/security-overview.md, site2/website/versioned_docs/version-2.8.1/security-basic-auth.md, site2/website/versioned_docs/version-2.8.1/security-overview.md, site2/website/versioned_docs/version-2.8.2/security-basic-auth.md, site2/website/versioned_docs/version-2.8.2/security-overview.md, site2/website/versioned_docs/version-2.8.3/security-basic-auth.md, site2/website/versioned_docs/version-2.8.3/security-overview.md, site2/website/versioned_docs/version-2.9.0/security-basic-auth.md, site2/website/versioned_docs/version-2.9.0/security-overview.md, site2/website/versioned_docs/version-2.9.1/security-basic-auth.md, site2/website/versioned_docs/version-2.9.1/security-overview.md, site2/website/versioned_docs/version-2.9.2/security-basic-auth.md, site2/website/versioned_docs/version-2.9.2/security-overview.md, site2/website/versioned_sidebars/version-2.10.0-sidebars.json, site2/website/versioned_sidebars/version-2.8.0-sidebars.json, site2/website/versioned_sidebars/version-2.8.1-sidebars.json, site2/website/versioned_sidebars/version-2.8.2-sidebars.json, site2/website/versioned_sidebars/version-2.8.3-sidebars.json, site2/website/versioned_sidebars/version-2.9.0-sidebars.json, site2/website/versioned_sidebars/version-2.9.1-sidebars.json, site2/website/versioned_sidebars/version-2.9.2-sidebars.json
Fixes #14661 
1. Add a new topic about how to use basic authentication
2. Sync the topic in the left navigation and security overview
Note that the changes need to be applied to more historical versions since 2.8 as soon as it gets approved.
=> [feature][doc] Add docs about how to use basic authentication

pulsar-common/src/main/java/org/apache/pulsar/common/util/FutureUtil.java
In https://github.com/apache/pulsar/pull/15329 FutureUtil#waitForAll and FutureUtil#waitForAny methods with List parameter have been removed. 
If an application uses one of that method, it won't be able to switch from 2.10.0 to 2.10.1 (it will get a NoSuchMethodError exception).
Even if those methods are intedend to internal use only, this kind of breaking changes are not justified in a patch release.
For example both Stream Native KoP and Datastax Starlight for Kafka use the `waitForAll` method.
- Re add the List specific version of those methods
=> [branch-2.10][fix][common] Add back FutureUtil#waitForAll and FutureUtil#waitForAny methods with List parameter

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesV2Test.java
Make NamespacesBase deleteSubscribeRate / setSubscribeRate / getSubscribeRate methods to pure async.
=> [improve][broker] Make some operation SubscribeRate methods in Namespaces async

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
Synchronized update `topicPublishRateLimiter` in case of race condtion.  
There is a race condtion when two threads update `topicPublishRateLimiter` concurrency：
* `topicPublishRateLimiter` is null at the beginning
* Thread1 update it with both `publishThrottlingRateInByte < 0` and `publishThrottlingRateInMsg < 0`
* Then thread1 stop at https://github.com/apache/pulsar/blob/7bdfa3a3e5e71c44a174b28d0a843fb6730865fa/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java#L1170
* Thread2 update it with `publishThrottlingRateInByte > 0` or `publishThrottlingRateInMsg > 0`
* And thread2 will set `topicPublishRateLimiter` a new limiter.
* Then Thread1 resume, and  set  it  to `PublishRateLimiter.DISABLED_RATE_LIMITER`. Then the new limiter setted by thread2 will never be …
=> [fix][broker]Sync topicPublishRateLimiter update

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
The number of entries in storage is between `markDeletePosition` and `lastConfirmedEntry`, which the markDeletePosition is excluded, and the `lastConfirmedEntry` in included.
The current algorithm yields 1 more because `ledger.getLastPosition().getNext()` is included.
The right way is to make the algorithm not include `ledger.getLastPosition().getNext()`.
Check the box below and label this PR (if you …
=> [fix][managed-ledger] fix calculation in getNumberOfEntriesInStorage

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java
=> [branch-2.9] Add publishRateLimitedTimes to topic metrics.

pom.xml, pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/BaseJdbcAutoSchemaSink.java, pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/JdbcAbstractSink.java, pulsar-io/jdbc/sqlite/pom.xml, pulsar-io/jdbc/sqlite/src/test/java/org/apache/pulsar/io/jdbc/SqliteJdbcSinkTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/JdbcPostgresSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarIOSinkRunner.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarSinksTest.java
Currently JDBC Sinks only supports Avro or JSON schema.
* Added support for the KeyValue schema. 
* All the fields included in the Key schema and in the JSON schema are collected in a HashMap. Then the value for each JDBC column are looked up by the column name (specified in the Sink config).
* If a value is included in the key and in the value, the value one will be taken.
* If a structured field is read, an error will be thrown
* The Sink now is converted from Sink<GenericRecord> to Sink<GenericObject> (which is a compatible change)
* Added tests in the SQLLite module 
* Added integration tests in the  PostGre sink tester
=> [improve][connector] JDBC Sinks: support KeyValue schema

pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/UserConfigFunction.java
UserConfigFunction example is incorrect as calling `get()` on an empty Optional will raise an exception. Also the result of `get()` will never be null so it's useless to check nullity.
trivial
no
(Please …
=> [fix][function] Fix UserConfigFunction example

site2/docs/security-extending.md, site2/docs/security-overview.md
Fix #15055 
Add information for chained authentication providers.
=> [improve][doc] Add support for chained authentication providers with the same auth method name

site2/docs/admin-api-brokers.md, site2/docs/admin-api-clusters.md, site2/docs/admin-api-functions.md, site2/docs/admin-api-namespaces.md, site2/docs/admin-api-overview.md, site2/docs/admin-api-packages.md, site2/docs/admin-api-permissions.md, site2/docs/admin-api-tenants.md, site2/docs/admin-api-topics.md, site2/docs/administration-geo.md, site2/docs/administration-isolation.md, site2/docs/client-libraries-java.md, site2/docs/concepts-messaging.md, site2/docs/concepts-proxy-sni-routing.md, site2/docs/cookbooks-retention-expiry.md, site2/docs/functions-develop.md, site2/docs/io-overview.md, site2/docs/io-use.md, site2/docs/schema-manage.md, site2/docs/security-encryption.md, site2/docs/security-jwt.md
Fixes #10282
To sync the language tab choices on the same page to provide better experience. See also the original issue for more detail.
Add `groupId` attribute to `<Tabs>`. This PR has been split into 3 commits for easier review, which may be squashed when merging.
Note that some pages use options like `pulsar-admin`, `REST API` and `Java`, while others use `Admin CLI`, `REST API` and `Java Admin API`. Not sure if we should make these options consistent, but I've ensured that the options on the same page is consistent so that the tab choices are synced on the same page.
- The …
=> [feature][doc] Sync language tab choices

pulsar-client-cpp/python/setup.py, pulsar-functions/instance/src/scripts/run_python_instance_tests.sh
Protobuf latest 4.21 version broke compatibility with files generated with protoc < 3.19
As a result all current CI tests fail.
See https://developers.google.com/protocol-buffers/docs/news/2022-05-06
This fix downgrades protobuf python package to 3.20.1.
no …
=> [fix][python]Fix generated Python protobuf code not compatible with latest protobuf package

pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/json/JsonConverter.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java
Avro native objects for Arrays and Maps are not supported by the sink.
If you try to use a Java POJO with a java.util.List/java.util.Set field with Avro Schema, you get:
```
022-04-26T11:56:51.477776276Z Caused by: java.lang.ClassCastException: class org.apache.avro.generic.GenericData$Array cannot be cast to class [Ljava.lang.Object; (org.apache.avro.generic.GenericData$Array is in unnamed module of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
```
For java.util.Map
```
2022-04-26T12:03:34.776219894Z java.lang.IllegalArgumentException: Error while converting a value of type class java.util.HashMap to a MAP: java.lang.ClassCastException: class org.apache.avro.util.Utf8 cannot be cast to class java.lang.String (org.apache.avro.util.Utf8 is in unnamed …
```
=> [fix][kinesis-sink] Handle Avro collections native types (GenericData.Array and Utf8 map keys)

pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientTestFixtures.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImplTest.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/CoordinationServiceImpl.java
Fixes #15850
See #15850 for details. MultiTopicsConsumerImplTest.testParallelSubscribeAsync is flaky and several problems were observed in the test. This PR attempts to fix the issues.
- add preProcessSchemaBeforeSubscribe mocking to prevent `java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.api.Schema.getSchemaInfo()" because "this.schema" is null` NPEs.
- the timeout in testParallelSubscribeAsync method seems to happen because testGetStats continues asynchronously in the background. To fix this issue:
- use arbitrary local ip + port for testGetStats (the test doesn't require a real connection, this should be improved)
- close the resources synchronously in testGetStats method
=> [Tests] Fix flaky MultiTopicsConsumerImplTest

pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConnectionTimeoutTest.java
- the original test assumed that 192.0.2.1 is a "black hole" and can be used for testing
connection timeouts.
This is an assumption which doesn't hold when a firewall blocks such connections. This causes the test to be flaky.
- Refactor ConnectionTimeoutTest
- create a dummy TCP/IP server and fill the backlog so that it won't respond and becomes
a "black hole"
=> [Tests] Fix flaky test ConnectionTimeoutTest

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/MessageDuplicationTest.java
When MessageDeduplication#purgeInactiveProducers:
https://github.com/apache/pulsar/blob/d09c6eb26adcaf0aff2c3464e445eb8df5af70a6/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java#L455-L477
If MessageDeduplication status is not `Enabled`, the cursor will be null. and cause to be NPE at line 475.
See cursor initializes:
https://github.com/apache/pulsar/blob/a43981109a9322d94082ae0d87d0de53b8f237e8/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java#L272-L292
```
May 25, 2022 @ 13:39:04.552	2022-05-25T05:39:04,546+0000 [pulsar-inactivity-monitor-22-1] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught 
May 25, 2022 @ 13:39:04.552		at …
```
=> [fix][broker] Fix NPE in MessageDeduplication.

tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/PulsarIOTestBase.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/RabbitMQSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/RabbitMQSourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/CassandraSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearchSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/HdfsSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/JdbcPostgresSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KafkaSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/OpenSearchSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/SinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/KafkaSourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/SourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMongoDbSourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMsSqlSourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMySqlSourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumOracleDbSourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumPostgreSqlSourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/PulsarIODebeziumSourceRunner.java
Fixes #15853
See #15853 
Fix resources leaks by making SinkTester and SourceTester to implement AutoClosable and handling this in the framework.
=> [Tests] Fix resource leaks in Pulsar IO integration tests

bouncy-castle/bcfips-include-test/src/test/resources/authentication/tls/broker-cert.pem, bouncy-castle/bcfips-include-test/src/test/resources/authentication/tls/cacert.pem, bouncy-castle/bcfips-include-test/src/test/resources/authentication/tls/client-cert.pem, build/regenerate_certs_for_tests.sh, pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthenticationTlsHostnameVerificationTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpClient.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarChannelInitializer.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/NettyClientSslContextRefresher.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/SecurityUtility.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/AdminProxyHandler.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ServiceChannelInitializer.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithAuthorizationTest.java, pulsar-proxy/src/test/resources/authentication/tls/ProxyWithAuthorizationTest/broker-cacert.pem, pulsar-proxy/src/test/resources/authentication/tls/ProxyWithAuthorizationTest/broker-cert.pem, pulsar-proxy/src/test/resources/authentication/tls/ProxyWithAuthorizationTest/client-cacert.pem, pulsar-proxy/src/test/resources/authentication/tls/ProxyWithAuthorizationTest/client-cert.pem, pulsar-proxy/src/test/resources/authentication/tls/ProxyWithAuthorizationTest/proxy-cacert.pem, pulsar-proxy/src/test/resources/authentication/tls/ProxyWithAuthorizationTest/proxy-cert.pem, pulsar-proxy/src/test/resources/authentication/tls/cacert.pem, pulsar-proxy/src/test/resources/authentication/tls/client-cert.pem, pulsar-proxy/src/test/resources/authentication/tls/server-cert.pem
Currently, we perform hostname verification for the Java Client and the Proxy Java Client using a custom Pulsar hostname verifier. In order to simplify the code, I propose that we refactor these clients so they rely on a Netty, its SslHandler, and the JVM, to perform the hostname verification.
When `HTTPS` is configured as the endpoint verification algorithm, it uses [RFC 2818](https://datatracker.ietf.org/doc/html/rfc2818) to perform hostname verification. This is defined by the `Java Security Standard Algorithm Names` documentation for JDK versions 8, 11, and 17. Here are the official docs:
* https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html
* https://docs.oracle.com/en/java/javase/11/docs/specs/security/standard-names.html
* …
=> Switch to rely on Netty for Hostname Verification

conf/broker.conf, conf/functions_worker.yml, conf/proxy.conf, conf/websocket.conf, pulsar-broker/src/main/java/org/apache/pulsar/broker/BookKeeperClientFactoryImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactorTool.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerInternalClientConfigurationOverrideTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PulsarClientConfigurationOverrideTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyConfigurationTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/PulsarAdminBuilder.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImpl.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/internal/PropertiesUtils.java, pulsar-functions/src/test/resources/test_worker_config.yml, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PulsarWorkerService.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerUtils.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/WorkerUtilsTest.java, pulsar-package-management/bookkeeper-storage/src/main/java/org/apache/pulsar/packages/management/storage/bookkeeper/BookKeeperPackagesStorage.java, pulsar-package-management/bookkeeper-storage/src/main/java/org/apache/pulsar/packages/management/storage/bookkeeper/BookKeeperPackagesStorageConfiguration.java, pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/PackagesStorageConfiguration.java, pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/impl/DefaultPackagesStorageConfiguration.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java, site2/docs/reference-configuration.md
The Pulsar broker, proxy, websocket proxy, and function worker each start several clients, including the Pulsar Client, the Pulsar Admin Client, and the Bookkeeper Client. Until now, there hasn't been an easy way to pass arbitrary configuration to these clients, which can cause problems. A recent example is the client memory limit that we fixed here: https://github.com/apache/pulsar/pull/15752. I propose that we enable pass through configuration for these clients, so that users can override any default configuration.
Enable pass through configuration support for the bookkeeper clients created by `DistributedLog` and `BookKeeperPackagesStorage`. This support is already present for the managed ledger bookkeeper client, which takes all `bookkeeper_` prefixed configs. In order to simplify …
=> Configure DLog Bookie, Pulsar, and Admin clients via pass through config

src/owasp-dependency-check-suppressions.xml
Currently, there is a failure in the OWASP dependency check in the CI: https://github.com/apache/pulsar/runs/6648112388?check_suite_focus=true
The openstack-keystone and openstack-swift have been suppressed in https://github.com/apache/pulsar/pull/13926 .
The root cause is that the PR https://github.com/apache/pulsar/pull/15649 had updated the jcloud version but didn't update the version of openstack-keystone and openstack-swift included in jcloud in the file `owasp-dependency-check-suppressions.xml`.
* Add OWASP suppression for openstack-keystone-2.5.0 and openstack-swift-2.5.0.
*(or)* …
=> [fix][dependency] Add OWASP suppression for openstack-keystone-2.5.0 and openstack-swift-2.5.0

site2/docs/io-kafka-sink.md
Fixes #15783 
YAML config is malformed
=> Fix malformed page for kafka-sink

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/SinkRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSource.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/SinkRecordTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/source/PulsarSourceTest.java, pulsar-io/cassandra/src/main/java/org/apache/pulsar/io/cassandra/CassandraAbstractSink.java
The current source  ack type and `ProcessingGuarantees` are forcibly bound together, This is not flexible for implementing a new sink. If sink is Guarantees equals `ATMOST_ONCE`,  it can't be use `acknowledgeCumulative`
https://github.com/apache/pulsar/blob/a0dcab679b1842a2efee4df2f31bf41ef5ab1dd0/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSource.java#L136-L142
- Provide an `ack(boolean cumulative)` method to support the sink to select the ack type
=> [improve][connector] Sink support custom acknowledge type

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationClient.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java
- There's a regression with the tools since the memory limit cannot be adjusted
- It's better to default to the previous setting of disabling memory limits
so that the performance profile doesn't change because of the memory limit.
- Memory limit is enabled by default in "PIP-120: Enable client memory limit by default", #13306 . PR was #13344 .
Set `.memoryLimit(0, SizeUnit.BYTES)` for PulsarClient builders in Cli tools.
#15723 restores the default `maxPendingMessages` & `maxPendingMessagesAcrossPartitions` limits for producers to the defaults used before PIP-120 changes when the memory limit is disabled. That might be necessary in some cases for restoring the pre-PIP-120 behavior.
=> [Cli tools] Disable Pulsar client memory limit by default

.github/workflows/pulsar-ci.yaml, pom.xml
Whenever an OutOfMemoryError happens in a unit test, it's very hard to diagnose without a heap dump.
This PR makes changes in the build and CI to collect heap dumps when OutOfMemoryError happens in unit tests.
- Add `XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp` to test JVM args
- Upload `/tmp/*.hprof` files to GitHub Actions artifacts
=> [CI] Collect heap dumps when OutOfMemoryError happens in unit tests

pulsar-client/src/test/java/org/apache/pulsar/client/impl/BatchMessageContainerImplTest.java
Fixes #15689
Fixes #15793
Fixes #15897
`PulsarByteBufAllocator.DEFAULT` instance was replaced in BatchMessageContainerImplTest, but never restored. This caused strange issues in many unit tests. OutOfMemoryError and NoClassDefFoundErrors  were most likely caused by the BatchMessageContainerImplTest. 
Fix the problems in BatchMessageContainerImplTest and reset the state after the test completes.
The flaky test was introduced by #12170 which has been cherry-picked to branch-2.8, branch-2.9 and included also in branch-2.10 .
=> [Tests] Fix OutOfMemoryError and NoClassDefFoundErrors in tests

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
* When updating topic-level and namespace-level  subscriptions dispatcher rate-limiter,  the code is a little different  but we can unify them as one method, such as `updateSubscriptionsDispatcherRateLimiter()`,  which will make the  code more clear
Create  `updateSubscriptionsDispatcherRateLimiter()` to update subscriptions dispatcher rate-limiter on both topic-level and namespace-level
=> [improve][broker]tidy update subscriptions dispatcher rate-limiter

src/owasp-dependency-check-suppressions.xml
Fix OWASP scan as CVE-2016-1000027 is a false positive for Spring
See https://github.com/spring-projects/spring-framework/issues/24434#issuecomment-1132113566
* Added CVE-2016-1000027 to OWASP suppressions fiile
* Removed old suppressions not used anymore
no …
=> [fix][owasp] Suppress CVE-2016-1000027 detection in Spring dependencies

tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
Related to #15392
- the test is currently the most flaky test and it would be useful to add this logging
so the the problem could be investigated
=> [Tests] Dump function logs when testJavaLoggingFunction test fails

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedCursor.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/proto/MLDataFormats.proto, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorContainerTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorPropertiesTest.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Subscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/CreateSubscriptionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/MockManagedLedger.java
Fixes #15750
The Subscription properties are not properly stored on MetadataService
Store the subscription properties on the MetadataService (ManagedCursorInfo)
This change is already covered by existing tests, I have only added some additional assertions
=> Issue 15750: PIP-105: Store Subscription properties

pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/json/JsonConverterTests.java
Improves test coverage
Added a test
Run JsonConverterTests
no
fix
=> [improve][kinesis-sink] Add unit test for Kinesis sink JsonConverter

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
- `transactionBufferClient` uses the internal Pulsar client and therefore it should be closed before the internal Pulsar client.
- close `transactionsBufferClient` before the internal Pulsar client in `PulsarService`
I noticed the shutdown order inconsistency while investigating the flaky test failure #15920 .
=> [Broker] Close transactionBufferClient before closing the internal Pulsar client

pulsar-client-cpp/tests/AuthPluginTest.cc
Fixes #6298
There's a long outstanding flaky CPP test AuthPluginTest.testAthenz which causes CPP builds to fail frequently.
There's a race condition in the test. mockZTS might not be started. Error message is 
`ERROR [140642816536256] ZTSClient:367 | Response failed for url http://localhost:9999/zts/v1/domain/pulsar.test.provider/token. Error Code 7` . 
Error Code 7 is `CURLE_COULDNT_CONNECT (7) - Failed to connect() to host or proxy.` [in libcurl error codes](https://curl.se/libcurl/c/libcurl-errors.html). 
Wait for mockZTS to start before connecting to it.
=> [CPP tests] Wait for mockZTS to start before connecting to it

site2/docs/admin-api-topics.md, site2/docs/client-libraries-node.md, site2/docs/functions-develop.md, site2/docs/functions-package.md, site2/docs/functions-runtime.md, site2/docs/security-oauth2.md, site2/docs/security-tls-authentication.md, site2/docs/security-tls-transport.md
Fixes #15854 
Code highlighting does not work on some pages like https://pulsar.apache.org/docs/functions-develop because notations like <code>\`\`\`Java</code> instead of <code>\`\`\`java</code> are used in Markdown.
Correct the Markdown syntax.
(Your PR contains doc …
=> [fix][doc] Code highlight not working on some pages

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
Fixes #15916 
- `getLedgerMetadata` is an asynchronous operation and the final result shouldn't complete before the
metadata for all ledgers has been retrieved
- add CompletableFutures for each retrieval of ledger metadata to a map and wait for completion before completing the result of `getManagedLedgerInternalStats`. 
- organize operations in a way that all synchronous calls are made before waiting for the asynchronous operations to complete
managedLedgerInternalStats feature was introduced in #10653 , more additions in #10725
=> [ML] Fix race condition in getManagedLedgerInternalStats when includeLedgerMetadata=true

pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/conf/ClientConfigurationDataTest.java
See #15483 
The `@Secret` annotation works well, and introduced in #8910
- Revert the unneeded `@JsonIgnore`
- remove `Assert.assertFalse(s.contains("Password"));` `Password` is printed in a key. The sensitive field's value is `****`.
=> [Revert] [#15483] Remove sensitive msg from consumer/producer stats log

.github/workflows/pulsar-ci.yaml, build/run_unit_group.sh, pom.xml, pulsar-broker/pom.xml, pulsar-io/pom.xml, pulsar-proxy/pom.xml, pulsar-sql/pom.xml
About 15 minutes of "CI - Unit - Other" build job is spent running pulsar-io unit tests.
It would be an improvement to run pulsar-io tests in a separate build job.
When "CI - Unit - Other" build job fails, it will be quicker to re-run the build job when pulsar-io tests aren't part of it.
- Add new build job "CI - Unit - Pulsar IO"
- add support for group "PULSAR_IO" in `build/run_unit_group.sh` script
- rename `brokerSkipTest` Maven profile to `skipTestsForUnitGroupOther` and use this Maven profile for excluding tests from the OTHER group
- add new profile `pulsar-io-tests` to select pulsar-io modules
=> [CI] Run pulsar-io unit tests in separate build job

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Fixes #15894
`testTriggerCompactionTopic` is flaky, because `createNonPartitionedTopic ` and `compact` use the same response: 
https://github.com/apache/pulsar/blob/ecd275dc21f33483a649e5b872990771257b1d45/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java#L902-L908
they are both return `Status.NO_CONTENT`, so the test fails sporadically with below error:
```
But was 2 times:
-> at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalTriggerCompactionNonPartitionedTopic$309(PersistentTopicsBase.java:3804)
-> at org.apache.pulsar.broker.admin.v2.PersistentTopics.lambda$createNonPartitionedTopic$2(PersistentTopics.java:352)
```
=> [fix][test] Fix flaky test PersistentTopicsTest#testTriggerCompactionTopic

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageCumulativeAckTest.java
* It should fast return if ack type is Cumulative  with illegal `CommandAck`
* Return if `ack.getMessageIdsCount() != 1` or `Subscription.isIndividualAckMode(subType)`
- Add UT for this case `org.apache.pulsar.broker.service.MessageCumulativeAckTest`
=> [fix][broker]Fast return if ack cumulative illegal

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
In KCA connectors when sanitizeTopicName is enabled the topic name saved in the `currentOffsets` is the original one.
This is a problem then because kafka-connect library will be stuck since the offset doesn't move forward (since the topic names don't match) and it will forever log this:
```
2022-06-03T08:13:52,996+0000 [pulsar-io-kafka-adaptor-sink-flush-0] INFO  [org.apache.pulsar.io](http://org.apache.pulsar.io/).kafka.connect.KafkaConnectSink - Task returned empty committedOffsets map; skipping flush; task will retry later
```
* Use the sanitized topic name in the offsets map
=> [fix][connector] KCA sinks: fix offset mapping when sanitizeTopicName=true

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerFactory.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/EntryCache.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/EntryCacheDefaultEvictionPolicy.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/EntryCacheDisabled.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/EntryCacheEvictionPolicy.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/EntryCacheManager.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheManagerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/package-info.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheManagerTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerBkTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/AllocatorStatsGenerator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/metrics/ManagedLedgerCacheMetrics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/v1/V1_ProducerConsumerTest.java
Refactored code to extract an interface for `EntryCacheManager` instead of relying on a concrete class implementation without any functional changes. 
The new interface will be used to add more cache implementations.
=> Extracted interface for EntryCacheManager

pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/TripleLongPriorityQueue.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/TripleLongPriorityQueueTest.java
Support shrinkage in TripleLongPriorityQueue. Avoid memory waste.
When the actual memory usage is less than the threshold, scale down.
Since the thresholds for expansion and contraction may be the same, in order to avoid frequent expansion and contraction, a 10% buffer is reserved.
Verify that it can shrink normally
- [ x ] `doc-not-needed`   
It is a internal class
=> Support shrink for TripleLongPriorityQueue

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java
When there is no configuration in the command line, empty metaStore is set even though it has been configured in proxy.conf
https://github.com/apache/pulsar/blob/67361e8db632b0cd4c23198c5c569f3f2193fc70/pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java#L146-L152
Set the read priority to Command line `metadataStoreUrl `, Command line `zookeeperServers , and Proxy conf `metadataStoreUrl`
=> [fix] [proxy] empty metaStore is set even though it has been configured in proxy.conf

pulsar-client-cpp/lib/auth/AuthOauth2.cc, pulsar-client-cpp/lib/auth/AuthOauth2.h, pulsar-client-cpp/tests/AuthPluginTest.cc
Currently, the well-known OpenID configuration URL generated by issuer_url and suffix (/.well-known/openid-configuration), if the issurer_url end with a slash, the well-known OpenID configuration URL will be not correct.
```
issuer_url: https://dev-kt-aa9ne.us.auth0.com/
openid_url: https://dev-kt-aa9ne.us.auth0.com//.well-known/openid-configuration
```
Making the issuer_url as below could work well.
```
issuer_url: https://dev-kt-aa9ne.us.auth0.com/
issuer_url: https://dev-kt-aa9ne.us.auth0.com
```
Trim the slash if the issuer_url end with a slash.
Add a unit test to verify the method `ClientCredentialFlow::initialize`.
- The default …
=> [fix][auth] Generate correct well-known OpenID configuration URL

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
In current implementation, We have more than one potential NPE relate `ManagedLedgerImpl#startReadOperationOnLedger` method.
**1. Unbox NPE**
https://github.com/apache/pulsar/blob/b13d15c4d6d795f33c6ed23f920fabbb3eeaf745/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L2230-L2244
According to this code, we can know that when the ledger id is null, we will fail `OpReadEntry`. However, there is no direct return here after failure. NPE will be thrown on line 2238. Because we want to unbox `null`.
**2. null `OpReadEntry` context**
According to the code above, we can see when we fail `OpReadEntry`, we pass a null value as context(line 2235). there is an NPE when the dispatcher gets the callback.
https://github.com/apache/pulsar/blob/0975cdc2489739b7518ee7a …
=> [Fix][broker] Fix NPE when ledger id not found in `OpReadEntry`

pulsar-client-cpp/python/pulsar/schema/schema.py, pulsar-client-cpp/python/schema_test.py
Fixes #15844
JsonSchema doesn't remove reserved keys(`_default`,`_required`,`_required_default`) when being encoded. Resulting in confusing encoding output.
Extract a common method to remove reserved keys when JsonSchema is being encoded, and this common method will be called when JsonSchema::encode method is called.
- *Added a unit test method named test_json_schema_encode_remove_reserved_key, see pulsar-client-cpp/python/schema_test.py*
- The rest …
=> [fix][python client] Fixed reserved keys is not removed when JsonSchema being encoded

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
As https://github.com/apache/pulsar/pull/12818 has supported creating topics with metadata, this patch is adding a `get` API to support getting topic properties.
=> [feature][admin] Support to get topic properties.

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSslConfig.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/RestClient.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientSslTests.java, site2/docs/io-elasticsearch-sink.md
There's no way at the moment to connect to a ElasticSearch cluster without checking the SSL certificate.
This is very useful in dev environments when you have to use secure connections.
* New option `disableCertificateValidation` that set the client to not verify ssl certificates. Default is false.
=> [feat][pulsar-io] ElasticSearch Sink: option to disable SSL certificate validation

site2/docs/getting-started-standalone.md
* Port the changes made to 2.10 documentation on installing JDK for Apple M1 chip to Next version
=> [fix][doc] Added Java M1 installation instruction to Next version as well

site2/docs/security-encryption.md
Cosmetic change to clarify that C++ and Python supports only RSA keys
Cosmetic
- [ X ] `doc` 
=> [Improve][Doc] C++ and Python support only RSA

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
Add timeout of sync methods for the AuthoriationService to avoid infinite web thread blocking.
=> [fix][security] Add timeout of sync methods and  avoid call sync method for AuthoriationService

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
https://nvd.nist.gov/vuln/detail/CVE-2019-20444#range-6908693
Upgrade from 2.0.4 to 2.0.6
=> Upgrade Netty Reactive Streams to 2.0.6

docker/pulsar/Dockerfile
Apt-get latest version of python3-yaml is 5.3.1, but this version contains [CVE-2020-14343](https://nvd.nist.gov/vuln/detail/CVE-2020-14343). 
Use pip to install pyyaml in order to get a version without the vulnerability.
Hopefully existing tests verify the functionality that pyyaml is used for.
- Dependencies (does it add or upgrade a dependency): Yes
- The public API: don't know
- The schema: don't know
- The default values of configurations: don't know
- The wire protocol: don't know
- The rest endpoints: don't know
- The admin cli options: don't know
- Anything that affects deployment: don't know
Security fix; …
=> [fix][pulsar] Bump pyyaml from 5.3.1 to 5.4.1 to solve CVE-2020-14343

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/schema/KafkaConnectData.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/PulsarSchemaToKafkaSchemaTest.java
KCA Sink fails on some complex json objects with "org.apache.kafka.connect.errors.DataException: Not a struct schema: Schema{ARRAY}" or similar
Improved handling of all possible (AFAICT) expected kafka schema types and their mapping, conversion of types etc.
Improved test coverage.
This change added tests.
No
(Your PR needs to …
=> [Fix][pulasr-io] KCA Sink: org.apache.kafka.connect.errors.DataException: Not a struct schema: Schema{ARRAY} + tests

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/MessageDispatchThrottlingTest.java
* Cleanup  `DispatchRateLimiter#onPoliciesUpdate` because it is deprecation and nowhere invoke it
* Also `MessageDispatchThrottlingTest#testDispatchRateCompatibility2` has no meaning if it call `DispatchRateLimiter#onPoliciesUpdate` to test compatibility, we need fix this UT
* Cleanup `DispatchRateLimiter#onPoliciesUpdate`
* Fix `MessageDispatchThrottlingTest#testDispatchRateCompatibility2` 
=> [clean][broker]Cleanup DispatchRateLimiter#onPoliciesUpdate

buildtools/pom.xml, distribution/server/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, managed-ledger/pom.xml
We no longer have any library using the log4j 1.2 API after ZooKeeper was upgraded to 3.5.x. We can then remove the compatibility API.
=> Removing log4j-1.2-api from dependencies

conf/pulsar_tools_env.sh
The pulsar_tool_env.sh sets the PULSAR_MEM environment variable without allowing it to be overridden. When running an pulsar-admin function (e.g. running the kafka to pulsar connector) we can hit java memory issues without a way to change the memory settings. This PR resolves this issue.
This change keeps the default value but allows PULSAR_MEM to be overridden which aligns with the
pulsar_env.sh file. This allows adjustments to be made to the memory settings when more memory is needed.
- The …
=> Allow pulsar_tool_env.sh PULSAR_MEM to be Overridden

bin/pulsar-client
Fixes #15349
When using the JDK17, pulsar-client throws exception `module java.base does not export sun.net to unnamed module`, it is good to fix it.
Add `--add-opens java.base/sun.net=ALL-UNNAMED` to java option when using JDK17.
=> [fix][client] Fix JDK17 compatibility issue

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MessageDispatchThrottlingTest.java
* https://github.com/apache/pulsar/pull/15986   modiy the `MessageDispatchThrottlingTest#testDispatchRateCompatibility2` and test failure, which throw `Topic is already fenced` exceptions
* The reason can be  located at line:1381
https://github.com/apache/pulsar/blob/5cbaddcccb7183bedb3e98895c4fb34e84415f9a/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L1361-L1382
because `topicPolicies.getReplicationClusters()` is empty if we just new a `Policies`. And then if we call `topic.onPoliciesUpdate` the topic will be deleted
*  Using `admin.namespaces().getPolicies(namespace)`  instead of `new Policies()`. Because  `topicPolicies#replicationClusters` will be auto created as broker's clusterName if we did't set it manually when creating namespace. …
=> [test][fix]Fix UT MessageDispatchThrottlingTest#testDispatchRateCompatibility2

pulsar-client-cpp/README.md
Fixes #15935 
Currently, the command `sudo cp *.a /usr/lib` in the file `pulsar-client-cpp/README.md` sometimes failed. Because when building gtest and gmock, the libs `*.a` may not always be placed at the source code root path `/usr/src/gtest` and `/usr/src/gmock`. The path depends on the version of the gtest and gmock and depends on the configuration when building. So when the developers use the command `sudo cp *.a /usr/lib` directly, it may fail.
Adjust the command and explain it in the document `pulsar-client-cpp/README.md`.
=> [fix][doc] Adjust the install command of the gtest and gmock in document

conf/broker.conf, conf/standalone.conf, site2/docs/reference-configuration.md, site2/docs/schema-evolution-compatibility.md
Fixes #15855 
1. Add `schemaRegistryCompatibilityCheckers` to `broker.conf` and `standalone.conf`.
2. Refactor the section, add configs and more text for `schemaRegistryCompatibilityCheckers`.
3. Fix grammar issues for other sections.
=> [fix][doc] Add context for schemaRegistryCompatibilityCheckers

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
https://github.com/apache/pulsar/pull/15967 removed the `EntryWrapper`,
which holds an `Entry` instance that is never used. Instead, after the
refactoring, the `MessageMetadata` array is useless, see
https://github.com/apache/pulsar/blob/298a573295f845e46f8a55cee366b6db63e997c2/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java#L517-L519
Each `MessageMetadata` instance in the array is returned by
`peekMessageMetadata`, whose returned value references a thread local
object `Commands#LOCAL_MESSAGE_METADATA`. It brings a problem that if
multiple entries were read, all `MessageMetadata` elements in the array
reference the same object.
However, accidentally, the wrong invocation of `Optional#orElse` saves
it. See …
=> [fix][broker] Avoid storing `MessageMetadata` instances returned by `peekMessageMetadata`

pom.xml, pulsar-io/cassandra/pom.xml, src/owasp-dependency-check-suppressions.xml
that's a regular update, cassanrda driver 3.6.0 is released in year 2018. Keep update.
=> Bump cassandra driver version from 3.6.0 to 3.11.2

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/RestClient.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/elastic/ElasticSearchJavaRestClient.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/opensearch/OpenSearchHighLevelRestClient.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfigTests.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkTests.java, site2/docs/io-elasticsearch-sink.md
ElasticSearch has a size limitation for the document id. The hard limit is 512 bytes. It is not configurable.
>_id is limited to 512 bytes in size and larger values will be rejected.
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html
In order to by-pass this limitation without losing data integrity and uniqueness a new option is introduced to create an hash of the Pulsar record key.
* New option `idHashingAlgorithm`, enum NONE, SHA256, SHA512
* For the hashing computation we use Guava utility class `com.google.common.hash.Hashing`
Note that this option will add a CPU overhead in order to compute the hashed value.
It is suggested to use this option together with `canonicalKeyFields` in order to guarantee the same hashed value for the same key content …
=> [feat][elasticsearch] Add hashed id support

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java
Now， We check pendingIndividualBatchIndexAcks then flush in method `doCumulativeAck`, 
But We only insert data to pendingIndividualBatchIndexAcks when `doIndividualBatchAckAsync`
Remove pendingIndividualBatchIndexAcks in method `doCumulativeAck`
Execute check pendingIndividualBatchIndexAcks in method `doIndividualBatchAckAsync`.
=> [fix][clients]Check pendingIndividualBatchIndexAcks size in doIndividualBatchAckAsync

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketProxyConfiguration.java
#13777 deprecated `zookeeperServers` and `configurationStoreServers`. However, while the former has comments pointing to `metadataStoreUrl` which should be used instead, the latter doesn't have comments about which field to use instead.
Add comments that point users to `configurationMetadataStoreUrl`.
=> Add comment for using `configurationMetadataStoreUrl` instead of `configurationStoreServers`

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
Currently, the `getPublishRate` admin API does not handle the exception when `internalGetPublishRateAsync` exceptionally.
Resume async response exceptionally when `internalGetPublishRateAsync`  method has an exception.
=> [fix][admin] Fix get-publish-rete Admin API handle exception behavior

build/run_unit_group.sh
Fix https://github.com/apache/pulsar/runs/6833250379?check_suite_focus=true
```
Error:  Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 9.736 s <<< FAILURE! - in org.apache.pulsar.broker.service.BrokerServiceBundlesCacheInvalidationTest
Error:  testRecreateNamespace(org.apache.pulsar.broker.service.BrokerServiceBundlesCacheInvalidationTest)  Time elapsed: 0.223 s  <<< FAILURE!
java.lang.NullPointerException
at java.base/java.lang.String.getBytes(String.java:963)
at org.apache.pulsar.client.impl.schema.StringSchema.encode(StringSchema.java:101)
at org.apache.pulsar.client.impl.schema.StringSchema.encode(StringSchema.java:37)
at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.value(TypedMessageBuilderImpl.java:175)
at …
```
=> [branch-2.9] Disable testReuseFork for broker_group_2

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
see #15932
At branch `master` REST API async change, there are many conflicts when cherry-picking #15932 PR, so I  create separate PR to fix branch-2.9
- Swap the execution order of duplicate validation and maximum validation
- Fixed incorrect logs
=> [fix] [admin] [branch-2.9] fix reach max tenants error if the tenant already exists

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
Method `advanceCursorsIfNecessary` has no longer deal with durable cursor, but the comments are not up to date, it is easy to misleading.
https://github.com/apache/pulsar/blob/7c5067461f04a2a4125ca0945a5f7ca9dfcfa9b3/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L2611-L2620
Remove this comment.
=> [cleanup] [broker] delete deprecated comment in ManagedLedgerImpl

pulsar-io/file/src/main/java/org/apache/pulsar/io/file/FileListingThread.java, pulsar-io/file/src/main/java/org/apache/pulsar/io/file/FileSourceConfig.java, pulsar-io/file/src/test/java/org/apache/pulsar/io/file/FileSourceConfigTests.java
Fixes #<xyz>
1. `FileListingThread` doesn't need to do the permission check since the `config.validate()` has already done it. Also, as a ListingThread, it doesn't need the `Write` permission on the directory.
2. `write` permission is needed only when `keepFile` option is set to `false`.
1. only do file writable permission check when `keepFile` is false.
*(or)*
*(or)* …
=> [function] refine file io connector

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientCnxTest.java
When the close consumer command is received, we just disconnected and didn't remove the cache, which will cause us to receive repeated messages.
This case happened in `org.apache.pulsar.broker.service.SubscriptionSeekTest#testSeekByFunctionAndMultiTopic` test of  #15568.
- Use `remove()` instead of `get()`
=> [fix][client] Remove consumer when close consumer command is received

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/LogAppender.java
Fixes #15274
1. create a DefaultErrorHandler during LogAppender initialization.
*(or)*
*(or)*
*(example:)*
- The rest …
=> [Function] provide default error handler for function log appender

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/StreamingStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedConsumerStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedSubscriptionStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ConsumerStats.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionStats.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/ConsumerStatsImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java, pulsar-common/src/main/proto/PulsarApi.proto
add message ack rate metric for consumer
=> [broker][monitoring] add message ack rate metric for consumer

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Replicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorRateLimiterTest.java
* Fix bug: The replicator rate limiter will not be initialized and updated if only topic-level policy is enabled, because  `replicator.getRateLimiter()` is empty for L3067:
https://github.com/apache/pulsar/blob/a43981109a9322d94082ae0d87d0de53b8f237e8/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L3063-L3068
*  Add the method `org.apache.pulsar.broker.service.Replicator#updateRateLimiter` to initialize or update  the replicator rate limiter.
*  Use this method to initialize or update all level replicator rate limiter
- Added UT `org.apache.pulsar.broker.service.ReplicatorRateLimiterTest#testReplicatorRateLimiterWithOnlyTopicLevel`
- Added UT …
=> [fix][broker]Fix topic-level replicator rate limiter not init

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaWithAuthTest.java
Cherry-pick #15956.
Currently, we need admin permissions to operate the schema API. This is because the admin permission was defined when the schema API was first added. See #1381.
Later, then adding authentication granularity with #6428, we don't change the schema API part.  So leave the admin permission today.
But the binary protocol allows the produce/consume permission to get the schema, so change the related method permission to `produce/consume`.
- `get schema` need `GET_METADATA` permission
=> [branch-2.10][fix][admin] Fix producer/consume permission can’t get schema

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientCnxTest.java
When the close producer command is received, we just disconnected and didn't remove the cache.
- Use `remove()` instead of `get()`
=> [fix][client] Remove producer when close producer command is received

.github/workflows/ci-documentbot.yml
Master Issue: #15797
We have implemented the new documentation bot at https://github.com/apache/pulsar-test-infra/pull/43.
Now we can apply it to our workflow.
Replace the old action with the new version of documentation bot.
*(or)*
*(or)*
*(example:)*
- The public API: …
=> [feat][workflow] Upgrade to new version of documentation bot

pulsar-client-cpp/lib/c/c_ProducerConfiguration.cc
Fixes #16030 
Fix symlink error for function pulsar_producer_configuration_get_crypto_failure_action
Rename function name `pulsar_producer_configuration_set_crypto_failure_action` to `pulsar_producer_configuration_get_crypto_failure_action`
=> [fix][c++ client] rename function name: pulsar_producer_configuration_set_crypto_failure_action

pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/v1/TopicLookup.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/v2/TopicLookup.java
Fixes #15973
https://github.com/apache/pulsar/pull/14188 forget to release LookupRequestSemaphore before returning data.
https://github.com/apache/pulsar/blob/91fe3b2ce264c3a51c349b29d86e566633f91d07/pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java#L124-L131
=> [fix][admin] Release LookupRequestSemaphore before returning data.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsumersTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java
* Remove `isDispatchRateNeeded()` and `getTopicPolicyDispatchRate()` and `isDispatchRateNeeded()` in `DispatchRateLimiter`, because it is only invoked by UT to mock. 
* Remove `isDispatchRateNeeded()` and `getTopicPolicyDispatchRate()` and `isDispatchRateNeeded()`  in  `DispatchRateLimiter`
=> [cleanup][broker]Cleanup DispatchRateLimiter isDispatchRateNeeded()

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java
- the script gets stuck unless the JVM is terminated explicitly
Fixes an issue where the `bin/pulsar initialize-cluster-metadata` command gets stuck with these log lines as the last entries:
```
2022-06-13T11:33:41,805+0000 [main-SendThread(pulsar-luna-uswest1-staging-zookeeper-ca.pulsar.svc.cluster.local:2181)] INFO  org.apache.zookeeper.ClientCnxn - Opening socket connection to server pulsar-luna-uswest1-staging-zookeeper-ca.pulsar.svc.cluster.local/10.56.0.47:2181.
2022-06-13T11:33:41,805+0000 [main-SendThread(pulsar-luna-uswest1-staging-zookeeper-ca.pulsar.svc.cluster.local:2181)] INFO  org.apache.zookeeper.ClientCnxn - SASL config status: Will not attempt to authenticate using SASL (unknown error)
2022-06-13T11:33:42,814+0000 …
```
=> [Broker] Terminate JVM when initialize-cluster-metadata command fails

conf/bkenv.sh, conf/pulsar_env.sh
Related to #15670, cc'ing its author @lhotari .
My local JDKs are almost built from the source code, such as [JDK Mainline](https://github.com/openjdk/jdk), so when I use the command `java -version`, I may get the following output message:
```
openjdk version "19-internal" 2022-09-20
OpenJDK Runtime Environment (build 19-internal-adhoc.lgx.jdk)
OpenJDK 64-Bit Server VM (build 19-internal-adhoc.lgx.jdk, mixed mode, sharing)
or
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc.lgx.jdk17u)
OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc.lgx.jdk17u, mixed mode, sharing)
```
Unfortunately, the code of `pulsar_env.sh` which was integrated in #15670 yesterday didn't support it, so when I use `./bin/pulsar standalone` locally, I get the following …
=> [fix][env] Support the java version like 'XX-internal' in env file

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
When you certain admin calls are made with invalid namespace or topic names, the error message is not very helpful. It indicates that a namespace couldn't be created, which implies something different to most users than creating the namespace name object.
Here is a sample stack error log:
```
20:29:19.100 [pulsar-web-40-1] INFO  org.eclipse.jetty.server.RequestLog - 10.233.83.87 - - [03/Jun/2022:20:29:19 +0000] "GET /admin/v2/non-persistent/public/permissions%0A%0A HTTP/1.1" 412 40 "-" "PostmanRuntime/7.28.4" 9
20:29:58.662 [pulsar-web-40-7] WARN  org.apache.pulsar.broker.admin.AdminResource - [cluster_admin] Failed to create namespace with invalid name permissions
java.lang.IllegalArgumentException: Invalid named entity: permissions
at …
```
=> [broker] Make invalid namespace and topic name logs more descriptive

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
When a partitioned topic was created concurrently, especially when
automatically created by many producers. This case can be reproduced
easily by configuring `allowAutoTopicCreationType=non-partitioned` and
starting a Pulsar standalone. Then, run the following code:
```java
try (PulsarClient client = PulsarClient.builder()
.serviceUrl("pulsar://localhost:6650").build()) {
for (int i = 0; i < 10; i++) {
client.newProducer().topic("topic").createAsync();
}
Thread.sleep(1000);
}
```
We can see a lot of "Could not get connection while
getPartitionedTopicMetadata" warning logs at client side, while there
were more warning logs with full stack traces at broker side:
```
2022-06-14T02:04:20,522+0800 [metadata-store-22-1] WARN  org.apache.pulsar.broker.service.ServerCnx - Failed to get …
```
=> [improve][broker] Avoid reconnection when a partitioned topic was created concurrently

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionTlsTest.java, pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/TestPulsarConnector.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
Fixes #<xyz>
Fixing flaky tests.
- improved `PulsarFunctionTlsTests` by reordering tearDown() logic
- improved `ManagedLedgerFactoryImpl.shutdown()` by closing cacheEviction threads early
- improved `TestPulsarConnector` memory consumption by removing unnecessary spy()
- The wire protocol: (yes / …
=> [improve][tests] improved flaky test runs

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
I noticed the missing response type when using the auto-generated client from swagger definitions.
⚠️ I'm not familiar with Java, so probably there is a better fix.
=> [fix][admin] Fix missing response type in swagger definitions

pulsar-client-cpp/lib/auth/AuthOauth2.cc
Clean up C++ client curl configuration.
* Remove some settings
This is a minor change with well known scope. No additional tests are required.
=> Clean up C++ client curl configuration

.github/workflows/ci-documentbot.yml
Fixes #16046
Multiple workflows can be running concurrently while `labeled` event triggered instantly after `opened` event before the docbot workflow is running.
This scenario will cause an inconsistent state of action and confused results.
Added [`concurrency`](https://docs.github.com/en/actions/using-jobs/using-concurrency)
- `concurrency.group` means workflow using the same concurrency group will be pending
- `concurrency.cancel-in-progress` will cancel any currently running job or workflow in the same concurrency group. This option can resolve the inconsistent state issue.
The demo can be found at https://github.com/open-github/pulsar/pull/12
And the workflow status
=> [fix][workflow] Support concurrency group and reusable workflow files in docbot

README.md
Fixes #16052 
The [README.md](https://github.com/apache/pulsar/blob/master/README.md#configure-java-version-for-maven-in-intellij) explains how to configure JDK version for maven, and says the purpose is "uses the Java 11 JDK for running Maven when importing the project to IntelliJ"; However, use project JDK will leverage JDK 17 instead of JDK 11, the project jdk version should be 17 in the context.
Change the version to 17 to make it consistent within README.md
- Anything that affects …
=> [fix][doc] make the JDK version consistent in readme.md

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/RocksdbMetadataStore.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
Fixes #15896
See #15896
When the same key is modified concurrently, there will be LockTimeout exception in `RocksdbMetadataStore`.
The root cause is we haven't get the lock of the key when read old data in `store.getForUpdate(...)`, so the exception throws when two transaction modifies the same key.
Set `exclusive` parameter of `getForUpdate` to `true` in `RocksdbMetadataStore#storePut`.
The same applies to  `RocksdbMetadataStore#storeDelete`.
- org.apache.pulsar.metadata.MetadataStoreTest#testConcurrentPut
- org.apache.pulsar.metadata.MetadataStoreTest#testConcurrentDelete
- The …
=> [Issue 15896] Fix LockTimeout when storePut on the same key concurrently in RocksdbMetadataStore

site2/docs/client-libraries-java.md, site2/website/versioned_docs/version-2.1.1-incubating/client-libraries-java.md, site2/website/versioned_docs/version-2.10.0/client-libraries-java.md, site2/website/versioned_docs/version-2.2.0/client-libraries-java.md, site2/website/versioned_docs/version-2.3.0/client-libraries-java.md, site2/website/versioned_docs/version-2.3.2/client-libraries-java.md, site2/website/versioned_docs/version-2.4.0/client-libraries-java.md, site2/website/versioned_docs/version-2.4.1/client-libraries-java.md, site2/website/versioned_docs/version-2.4.2/client-libraries-java.md, site2/website/versioned_docs/version-2.5.0/client-libraries-java.md, site2/website/versioned_docs/version-2.5.1/client-libraries-java.md, site2/website/versioned_docs/version-2.5.2/client-libraries-java.md, site2/website/versioned_docs/version-2.6.0/client-libraries-java.md, site2/website/versioned_docs/version-2.6.1/client-libraries-java.md, site2/website/versioned_docs/version-2.6.2/client-libraries-java.md, site2/website/versioned_docs/version-2.6.3/client-libraries-java.md, site2/website/versioned_docs/version-2.6.4/client-libraries-java.md, site2/website/versioned_docs/version-2.7.0/client-libraries-java.md, site2/website/versioned_docs/version-2.7.1/client-libraries-java.md, site2/website/versioned_docs/version-2.7.2/client-libraries-java.md, site2/website/versioned_docs/version-2.7.3/client-libraries-java.md, site2/website/versioned_docs/version-2.7.4/client-libraries-java.md, site2/website/versioned_docs/version-2.8.0/client-libraries-java.md, site2/website/versioned_docs/version-2.8.1/client-libraries-java.md, site2/website/versioned_docs/version-2.8.2/client-libraries-java.md, site2/website/versioned_docs/version-2.8.3/client-libraries-java.md, site2/website/versioned_docs/version-2.9.0/client-libraries-java.md, site2/website/versioned_docs/version-2.9.1/client-libraries-java.md, site2/website/versioned_docs/version-2.9.2/client-libraries-java.md
* The shared consumer example comment indicates <code>Both consumer1 and **consumer 2 is** active consumers</code>
* Updated comment section to refer to the proper variable <code>Both consumer1 and **consumer2 are** active consumers</code> …
=> [fix][docs] Corrected comment in shared consumer section

site2/docs/concepts-messaging.md, site2/docs/security-oauth2.md, site2/website/versioned_docs/version-2.10.0/security-oauth2.md, site2/website/versioned_docs/version-2.6.1/security-oauth2.md, site2/website/versioned_docs/version-2.6.2/security-oauth2.md, site2/website/versioned_docs/version-2.6.3/security-oauth2.md, site2/website/versioned_docs/version-2.6.4/security-oauth2.md, site2/website/versioned_docs/version-2.7.0/security-oauth2.md, site2/website/versioned_docs/version-2.7.1/security-oauth2.md, site2/website/versioned_docs/version-2.7.2/security-oauth2.md, site2/website/versioned_docs/version-2.7.3/security-oauth2.md, site2/website/versioned_docs/version-2.7.4/security-oauth2.md, site2/website/versioned_docs/version-2.8.0/security-oauth2.md, site2/website/versioned_docs/version-2.8.1/security-oauth2.md, site2/website/versioned_docs/version-2.8.2/security-oauth2.md, site2/website/versioned_docs/version-2.8.3/security-oauth2.md, site2/website/versioned_docs/version-2.9.0/security-oauth2.md, site2/website/versioned_docs/version-2.9.1/security-oauth2.md, site2/website/versioned_docs/version-2.9.2/security-oauth2.md
1. Add an import statement to the Java code sample for Oauth2, and apply it to more historical versions in maintenance.
2. Correct the system topic name `__transaction_log_${tc_id}` added in #14795.
=> [fix][doc] Add an import statement to the Java code sample for Oauth2

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java
We need check message expiry when topic-level policies updated,  just like when namespace-level updated, line: 2399
https://github.com/apache/pulsar/blob/91cb00eab0fbbc0d519f5ad1ac8ab722da56b349/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L2366-L2399
Invoke `checkMessageExpiry()` when topic-level policies updated.
- Added UT `org.apache.pulsar.broker.service.MessageTTLTest#testTTLPoliciesUpdate`
=> [fix][broker]Fix topic policies update not check message expiry

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationDataSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
The `authenticationData` field in `ServerCnx` is being mutated to add the `subscription` field that will be passed on to the authorization plugin. The problem is that `authenticationData` is scoped to the whole connection and it should be getting mutated for each consumer that is created on the connection. 
The current code leads to a race condition where the subscription name used in the authz plugin is already modified while we're looking at it. Instead, we should create a new object and enforce the final modifier.
=> Avoid AuthenticationDataSource mutation for subscription name

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderToken.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/ProducerConsumerBase.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/TokenExpirationProduceConsumerTest.java
When token expiration, the broker requests the client to refresh the token, then the broker performs `org.apache.pulsar.broker.service.ServerCnx#doAuthentication` when the broker receives the auth response, which uses `org.apache.pulsar.broker.authentication.AuthenticationState#authenticate` to authentication, but the `org.apache.pulsar.broker.authentication.AuthenticationProviderToken.TokenAuthenticationState#authenticate` doesn't do anything, this cause a loop to refresh the token.
Right now the token is only validated in the TokenAuthenticationState constructor, we need to add a check to the authenticate method.
- Add check the token expiration
Fix
=> [fix][broker] Fix token expiration

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/PulsarServerException.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java
This pull request reverts commit #14920 
Revert PR #14920 because it may affect the DLQ when the user enables `auto-creation` and the creative type is `partitioned`.
- Revert the PR #14920.
=> Revert "[fix][broker] Reject auto create partitioned topic when topic name contains ``-partition-`` (#14920)

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTrackerFactory.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/InMemoryDeliveryTrackerTest.java, site2/docs/concepts-messaging.md
The current implementation for `InMemoryDelayedDeliveryTracker` allows messages to deliver early when their `deliverAt` time is within `tickTimeMillis` from now. This is an optimization that ensures messages deliver around the `deliverAt` time. However, some use cases require that messages do not deliver before the `deliverAt` time. (Note that the client api includes a `deliverAfter` method that implies messages won't deliver before some duration of time.)
In order to support this alternative implementation, this PR adds a broker configuration named `isDelayedDeliveryDeliverAtTimeStrict`. When true, messages will only deliver when the `deliverAt` time is greater than or equal to `now`. Note that a tradeoff here is that messages will be later than the `deliverAt` time.
There are two …
=> [broker] Add config to allow deliverAt time to be strictly honored

site2/docs/security-oauth2.md, site2/website/versioned_docs/version-2.10.0/security-oauth2.md, site2/website/versioned_docs/version-2.7.0/security-oauth2.md, site2/website/versioned_docs/version-2.7.1/security-oauth2.md, site2/website/versioned_docs/version-2.7.2/security-oauth2.md, site2/website/versioned_docs/version-2.7.3/security-oauth2.md, site2/website/versioned_docs/version-2.7.4/security-oauth2.md, site2/website/versioned_docs/version-2.8.0/security-oauth2.md, site2/website/versioned_docs/version-2.8.1/security-oauth2.md, site2/website/versioned_docs/version-2.8.2/security-oauth2.md, site2/website/versioned_docs/version-2.8.3/security-oauth2.md, site2/website/versioned_docs/version-2.9.0/security-oauth2.md, site2/website/versioned_docs/version-2.9.1/security-oauth2.md, site2/website/versioned_docs/version-2.9.2/security-oauth2.md
Currently, the oauth2 curl example doc has the wrong URL, if we use the command, we will get error code 1020.
```shell
curl --request POST \
--url https://dev-kt-aa9ne.us.auth0.com \
--header 'content-type: application/json' \
--data '{
"client_id":"Xd23RHsUnvUlP7wchjNYOaIfazgeHd9x",
"client_secret":"rT7ps7WY8uhdVuBTKWZkttwLdQotmdEliaM5rLfmgNibvqziZ-g07ZH52N_poGAb",
"audience":"https://dev-kt-aa9ne.us.auth0.com/api/v2/",
"grant_type":"client_credentials"}'
error code: 1020
```
Fix security-oauth2 docs curl example OAuth URL
=> [fix][doc] Fix security-oauth2 docs curl example OAuth URL

site2/docs/performance-pulsar-perf.md
The link here goes to the not found page: https://pulsar.apache.org/docs/next/performance-pulsar-perf/#transactions
Fixed the link to point to https://pulsar.apache.org/docs/next/txn-why/
=> [doc] Fix broken link to Transactions in the pulsar-perf page

site2/docs/txn-use.md
- Fixed the indentation of the code samples in the page: https://pulsar.apache.org/docs/next/txn-use
=> [doc] Transactions: fix code samples indentation

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
=> [fix][broker] fix npe when doCacheEviction

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
Cherry-pick pull request #15694
=> [branch-2.9][fix][security] Add timeout of sync methods and avoid call sync method for AuthoriationService

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaConnectSinkConfig.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
Record's getRecordSequence() returns non-unique sequenceId for the messages from the same batch.
The root cause is that `FunctionCommon.getSequenceId()` does not account for the index of the message in the batch and only uses ledgerid and entryId.
For the KCA Sink it mean that messages start arriving with the same offset, and some Kafka Sinks will ignore such messages as duplicates.
Changing this behavior in the `FunctionCommon.getSequenceId()` is potentially breaking (requires separate discussion) and I assume it does not affect Pulsar right now. 
Another problem is that we are already packing two longs (ledgerId and entryId) to get one long (sequenceId), batch adds an int to this. With the KCA one can make assumptions around batch size/number of entries in ledger before rotation and …
=> [Fix][pulsar-io] KCA to use index (if available) instead of sequenceId and to handle batched messages non-unique sequenceIds

pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java, pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/utils/FunctionRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/AbstractSinkRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/OutputRecordSinkRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/SinkRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/TargetSinkRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ContextImplTest.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/RecordFunction.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionCommon.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/FunctionCommonTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarFunctionsJavaTest.java
Currently, when a user wants to dynamically set the output topic, the message properties or change the output schema in a Function, the only possibility is to create a Function that returns `Void` , use the Context and manually create a message with `Context::newOutputMessage`.  The [TypedMessageBuilderPublish](https://github.com/apache/pulsar/blob/master/pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/TypedMessageBuilderPublish.java) Function in `pulsar-functions-api-examples` shows how to do that.
This way of doing is not intuitive and it would be better to return a structure like `Record` that carries this info.
This PR adds support for returning `Record` in a Function.
* In `JavaInstanceRunnable::sendOutputMessage`, we check the type of the output …
=> [improve][function] Support Record<?> as Function output type

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerfClientUtils.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceBaseArguments.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java, pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerfClientUtilsTest.java, pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceBaseArgumentsTest.java, pulsar-testclient/src/test/resources/perf_client1.conf, site2/docs/reference-cli-tools.md
`pulsar-perf transaction` does not support tls parameter for the pulsar client like `--trust-cert-file` and `-tls-allow-insecure` as the other perf command do (produce, consume, read) 
* Refactored the common arguments for the perf commands to a single class to avoid code duplication and single point for Pulsar Client and Admin Client creation
* Added `tlsHostnameVerificationEnable` for all the perf commands
* Now commands `consume`, `produce`, `read` and `transaction` share the following client options:
|Flag|Description|Default|
|---|---|---|
|`--auth-params`|Authentication parameters, whose format is determined by the implementation of method `configure` in authentication plugin class. For example, `key1:val1,key2:val2` or `{"key1":"val1","key2":"val2"}`.|| …
=> [improve][pulsar-perf] Transactions: improve client options

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaConnectSinkConfig.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
preCommit() can return offsets earlier than ones KCA requested to flush.
Only ack messages up to the committed offsets to avoid skipping data on connector restart.
code change + test
Added unit test
NO
(Docs have been already …
=> [Fix][pulsar-io] KCA: handle kafka preCommit() returning earlier offsets than requested

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java
`pulsar-perf transaction` uses the PerformanceProducer logger instead of its own.
Move the logger to `PerformanceTransaction.class`
=> [fix][pulsar-perf] Transactions: use the correct logger name

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
The `topicOrderedExecutor` is labeled as an `OrderedExecutor` although it gets instantiated as an `OrderedScheduler`.
`OrderedScheduler` is a super-set of `OrderedExecutor` which includes methods to scheduled delayed task and it has a much higher overhead per task since it has to keep a priority queue. 
We should always use `OrderedExecutor` if we don't need to schedule delayed tasks.
=> Use OrderedExecutor instead of OrderedScheduler for consumer dispatch

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
The managedLedgerInterceptor member variable is initialized twice within the same method.
https://github.com/apache/pulsar/blob/b155d84c2ee397fe8003f452f04ae6cedf229b5c/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L319-L321
https://github.com/apache/pulsar/blob/b155d84c2ee397fe8003f452f04ae6cedf229b5c/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L332-L334
Remove unnecessary code
=> [cleanup][ledger] Remove unnecessary code in ManagedLedgerImpl

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java
If we're not using the future returned by `writeAndFlush()`, we can use a `voidFuture` to prevent any allocations.
=> Avoid some promise object allocations when writing on channel

pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionCoordinatorClientImpl.java
Fixes #15375
the NPE happens because internalPinnedExecutor has not been assigned yet.
Refactor the constructor, in a way that "this" is not accessed from another thread while the constructor is not done yet.
=> Transactions: fix race in TransactionMetaStoreHandler

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
https://github.com/apache/pulsar/blob/732049fc6ca1beb046deb43057be2b130736fbca/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L2645-L2652
`L2468-L2469` make serverCnx disabled auto read, but **there has a beter implements** at `L2723-L2728`:
https://github.com/apache/pulsar/blob/732049fc6ca1beb046deb43057be2b130736fbca/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L2723-L2728
At the better implements, can reduce false statistics( when a serverCnx already disabled auto read, will not increment another once).
=> [cleanup] [broker] when serverCnx disabled auto read use same implements

pulsar-io/canal/pom.xml
This PR is related to #16110.
Fixes CVE-2022-25845.
Update fastjson version to 1.2.83
To fix CVE-2022-25845. It's a patch version bump, which should be safe to apply.
=> [security] Update fastjson version to 1.2.83

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSubscriptionTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/CLITest.java
In PIP-105 we added support for Subscription Properties. You can read them using the "stats" command, but it is not very user friendly.
This patch adds a specific REST API to get the properties and a pulsar-admin command
This change added tests 
REST API and pulsar-admin docs are generated automatically
=> PIP-105: new API to get subscription properties

bin/pulsar, pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarClassLoader.java
Fixes #15978
There's an issue reported about problems in load protocol handler .class file. This PR will specify default tmp dir;
Specify default tmp dir by `-Djava.io.tmpdir=$PULSAR_HOME/tmp`
=> [fix][broker] fix DEFAULT_NAR_EXTRACTION_DIR cause NoClassDefFoundError

site2/docs/concepts-messaging.md
Improve the concepts-messaging docs page.
* Improved English language in a few places
* Fixed the example backoff values
* Made the backoff examples more consistent
*(or)*
*(or)*
*(example:)* …
=> [improve][docs] Improve examples and language

docker/pulsar/scripts/generate-zookeeper-config.sh
This PR requires for : https://github.com/apache/pulsar-helm-chart/pull/269 
Right now, [chart dynamically](https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/zookeeper-statefulset.yaml#L140) creates zk cluster with zk pods initialized in the same namespace. However, for global/configuration zookeeper, user requires to build zk clusters with pods deployed in different namespaces. Therefore, user needs a mechanism to pass an external list of zk-servers to the chart and build zk-cluster with pods across different namespaces.
- Chart should be considering zk-value's configuration for external zookeeper and generate zk-configuration file with appropriate zk-server list and unique id of that zookeeper.
This PR allows user to generate zk-config with external …
=> Support mechanism to provide external zookeeper-server list to build global/configuration zookeeper

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageChunkingTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Master Issue: #12402
This is the same problem as when the consumer inclusive seeks the chunked message.
See more detail in [PIP-107](https://github.com/apache/pulsar/issues/12402)
* Use the first chunk message id as the startMessageId when creating the consumer/reader.
This is a bug fix.
=> [fix][client] Fix the startMessageId can't be respected as the ChunkMessageID

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/LastCumulativeAckTest.java
There were several issues caused by the thread safe issue of
`LastCumulativeAck`, see:
- https://github.com/apache/pulsar/pull/10586
- https://github.com/apache/pulsar/pull/12343
The root cause is that `LastCumulativeAck` could be accessed by
different threads, especially in `flushAsync` method. But the fields are
accessed directly and no thread safety can be guaranteed.
In addition, the current `LastCumulativeAck` class  was added in
https://github.com/apache/pulsar/pull/8996 to hold two object
references, but this modification is wrong.
Before #8996, there are two CAS operations in `doCumulativeAck` method
in case it's called concurretly. Though the composite CAS operation is
not atomic.
However, after #8996, only CAS operation was performed but it's compared
with a `LastCumulativeAck` …
=> [fix][Java Client] Fix thread safety issue of `LastCumulativeAck`

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ConsumerBatchReceiveTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImplTest.java
The consumer will apply the default batch receive policy even if the user will not use the batch receive API.
https://github.com/apache/pulsar/blob/6704f12104219611164aa2bb5bbdfc929613f1bf/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/BatchReceivePolicy.java#L60-L61
This will consume lots of CPU if the client has many consumers (100k consumers)
[consumer-cpu-threads.html.txt](https://github.com/apache/pulsar/files/8948238/consumer-cpu-threads.html.txt)
The Pulsar perf tool can also reproduce the problem if run the test with many consumers
If there is no pending batch receive operation for a consumer, no need to trigger the
batch timeout task periodically. We can only start the timeout check after adding batch
receive request to pending request queue.
Remove the lock in …
=> [improve][java-client] Only trigger the batch receive timeout when having pending batch receives requests

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/batch/BatchSourceExecutor.java, pulsar-io/batch-data-generator/src/main/java/org/apache/pulsar/io/batchdatagenerator/BatchDataGeneratorPushSource.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/elastic/ElasticBulkProcessor.java, pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/sink/HbaseAbstractSink.java, pulsar-io/influxdb/src/main/java/org/apache/pulsar/io/influxdb/BatchSink.java, pulsar-io/mongo/src/main/java/org/apache/pulsar/io/mongodb/MongoSink.java, pulsar-io/redis/src/main/java/org/apache/pulsar/io/redis/sink/RedisSink.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/AbstractHierarchicalLedgerManager.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerManager.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/PulsarZooKeeperClient.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java, tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileStoreBackedReadHandleImpl.java, tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImplV2.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloader.java
`ExecutorService.submit()` creates and returns a `Future` object which is triggered when the task is complete. If we're not checking that future, we can use `execute()` instead which avoids the creation of the future.
=> Use ExecutorService.execute() instead of submit() when possible

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
Fixes #16063 
Server will throw a NPE when `max_topics_per_namespace == null`, because of the `internalGetMaxTopicsPerNamespace` return type is `int`.
```java
2022-06-15T19:57:04,242+0800 [pulsar-web-40-6] WARN  org.eclipse.jetty.server.HttpChannelState - unhandled due to prior sendError
javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "org.apache.pulsar.broker.admin.impl.NamespacesBase.getNamespacePolicies(org.apache.pulsar.common.naming.NamespaceName).max_topics_per_namespace" is null
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162) ~[org.eclipse.jetty-jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
at …
```
=> [fix][broker] Fix NPE when get /admin/v2/namespaces/public/default/maxTopicsPerNamespace

pulsar-client-cpp/include/pulsar/Consumer.h, pulsar-client-cpp/include/pulsar/ConsumerConfiguration.h, pulsar-client-cpp/include/pulsar/Reader.h, pulsar-client-cpp/include/pulsar/ReaderConfiguration.h, pulsar-client-cpp/lib/Consumer.cc
Add getLastMessageId method to C++ Consumer.cc to address the missing part in this PR https://github.com/apache/pulsar/pull/15993
Expose methods to get last message Id in consumer, the C++ client's Consumer class
*(or)*
*(or)*
*(example:)*
- The schema: …
=> [client][c++] add getLastMessageIdAsync in Consumer

site2/docs/client-libraries-dotnet.md
Hello, Apache Pulsar community!
I found a small bracket error in the Create producer DotPulsar code example. I have fixed it by removing the bracket.
Please let me if there is anything I can improve in this PR to get it accepted.
Helping others using Apache Pulsar by improving the docs.
Removed a bracket in client-libraries-dotnet.md
=> [doc] Removed a bracket. That made a code example not compile.

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
When we use `ModualLoadManager` as `LoadManager` in the pulsar cluster, and the load balancer shedding strategy is `ThresholdShedder`, we found that the unloaded bundles might be loaded by another broker which has resource usage above average load, and make the new broker be overloaded again, which frequently causes unloading bundles.
```
loadManagerClassName=org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl
loadBalancerLoadSheddingStrategy=org.apache.pulsar.broker.loadbalance.impl.ThresholdShedder
loadBalancerBrokerThresholdShedderPercentage=10
```
We found that it tooks more than 10 hours and 400+ times to doing load shedding  in the cluster. And the cluster continue to unload bundles when some of topics are lots of traffic  in a short time. Below is the unload metric. …
=> [improve][broker] add switch for enable/disable distribute bundles evenly in LoadManager

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionLocalRunTest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/AbstractPulsarE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionE2ETest.java, pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionCommon.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2ResourceTest.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/FunctionApiV3ResourceTest.java
Currently, not providing the class name works only for builtin Functions.
This allows it also for files loaded through the API or with a package URL
* Use `FunctionCommon::getClassLoaderFromPackage ` instead of `FunctionConfigUtils::validate` in LocalRunner and FunctionsImpl
* Support `ComponentType.FUNCTION` type in `getClassLoaderFromPackage`
Run PulsarFunctionLocalRunTest and PulsarFunctionE2ETest
no …
=> [improve][function] Allow not providing the class name when loading a Function nar file

pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/window/UserConfigWindowFunction.java
UserConfigWindowFunction example is incorrect as calling `get()` on an empty Optional will raise an exception. Also the result of `get()` will never be null so it's useless to check nullity.
trivial
no …
=> [fix][functions] Fix UserConfigWindowFunction

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/BundleSplitterTask.java
The log like "The count of topics on the bundle {} is less than 2, skip split!" is spammy and useless.
Move that line to level "DEBUG"
=> [improvement][broker]: remove spammy log 'The count of topics on the bundle {} is less than 2, skip split!'

conf/functions_worker.yml, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, pulsar-functions/worker/pom.xml, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/FunctionApiV3ResourceTest.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/SinkApiV3ResourceTest.java
Currently, if you register a built-in Function in k8s with `uploadBuiltinSinksSources` set to true (default), there will be a NPE crash in [ComponentImpl:: getFunctionPackageLocation](https://github.com/apache/pulsar/blob/b3cd139335e65c6161abd7653e2c4c0cb61c983f/pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java#L321)
Handle the case where `componentType == FunctionDetails.ComponentType.SOURCE`
Run testRegisterFunctionSuccessK8sNoUpload and testRegisterFunctionSuccessK8sWithUpload
no
- The default values …
=> [fix][functions] Handle uploading of builtin Functions to BK if uploadBuiltinSinksSources is true

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
```
06:03:58.778 [broker-topic-workers-OrderedScheduler-4-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
java.lang.IllegalArgumentException: null
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
at org.apache.pulsar.broker.service.persistent.CompactorSubscription.acknowledgeMessage(CompactorSubscription.java:61) 
at org.apache.pulsar.broker.service.AbstractBaseDispatcher.filterEntriesForConsumer(AbstractBaseDispatcher.java:154) 
at org.apache.pulsar.broker.service.AbstractBaseDispatcher.filterEntriesForConsumer(AbstractBaseDispatcher.java:103)
at org.apache.pulsar.broker.service.persistent.PersistentDispatcherSingleActiveConsumer.internalReadEntriesComplete(PersistentDispatcherSingleActiveConsumer.java:203) 
at …
```
=> Fix compaction subscription acknowledge Marker msg issue.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscribeDispatchLimiterTest.java
* Fix bug: If subscribe dispather limiter is disabled at the beginning, it will not be initilized when updating broker config dynamicly.
* Use `dispatcher.updateRateLimiter()` to initilize and update the dispatch limiter
*(example:)*
- Added UT `org.apache.pulsar.broker.service.SubscribeDispatchLimiterTest`
=> [fix][broker]Fix subscribe dispathcer limiter not be initialized

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceAutoTopicCreationTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/ListNamespaceTopicsOptions.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Mode.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
Since #2025 has added query param - `Mode`,  but the CLI is still not supported.
#15410 has introduced to filter system topic. 
So this patch is supported the above query params for Namespace#getTopics.
=> [feature][CLI] Add query options to the get topics in Namespace.

site2/docs/txn-why.md, site2/website/versioned_docs/version-2.10.0/txn-why.md, site2/website/versioned_docs/version-2.8.0/txn-why.md, site2/website/versioned_docs/version-2.8.1/txn-why.md, site2/website/versioned_docs/version-2.8.2/txn-why.md, site2/website/versioned_docs/version-2.8.3/txn-why.md, site2/website/versioned_docs/version-2.9.0/txn-why.md, site2/website/versioned_docs/version-2.9.1/txn-why.md, site2/website/versioned_docs/version-2.9.2/txn-why.md
The docs has typo <code>...to store the **MessgeID** along...</code>.
Updated to <code>...to store the **MessageID** along...</code>
=> [hotfix][txn-why][docs] Corrected typo

pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ConsumerStats.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionStats.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/ConsumerStatsImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java, site2/docs/admin-api-topics.md, site2/website/versioned_docs/version-2.10.0/admin-api-topics.md, site2/website/versioned_docs/version-2.7.0/admin-api-topics.md, site2/website/versioned_docs/version-2.7.1/admin-api-topics.md, site2/website/versioned_docs/version-2.7.2/admin-api-topics.md, site2/website/versioned_docs/version-2.7.3/admin-api-topics.md, site2/website/versioned_docs/version-2.7.4/admin-api-topics.md, site2/website/versioned_docs/version-2.8.0/admin-api-topics.md, site2/website/versioned_docs/version-2.8.1/admin-api-topics.md, site2/website/versioned_docs/version-2.8.2/admin-api-topics.md, site2/website/versioned_docs/version-2.8.3/admin-api-topics.md, site2/website/versioned_docs/version-2.9.0/admin-api-topics.md, site2/website/versioned_docs/version-2.9.1/admin-api-topics.md, site2/website/versioned_docs/version-2.9.2/admin-api-topics.md
I found the current documentation for `unackedMessages` ambiguous. This PR should make the docs clearer for future users.
* Update Javadocs and docs for `unackedMessages`
* Update Javadocs for subscription stats `type` since it was missing the `Key_Shared` subscription type.
This is a trivial change. I ran some tests to verify that my understanding is correct.
This is not a breaking change.
=> [doc][stats] Improve documentation for unackedMessages stat

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
=> [improve][broker][PIP-149]make getPartitionedTopicList method async

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
Master Issue: #16081
Currently,  we can use `admin.namespaces().getTopics` to get topics under a namespace. But it could only return the non-persistent topics owned by the current broker.
Also, we can use `admin.toipics().getList` to get topics. It can return all non-persistent topics to users.
I think it is reasonable that we should make the data return of these two interfaces consistent.
=> [fix][admin] Fix get non-persistent topics issue in Namespaces.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
While create many consumers (> 10000), the IO thread run into BLOCK state for long time which will
affect the message publish and subsequent consumer creation.
```
"pulsar-io-15-24" #195 prio=5 os_prio=31 cpu=15744.67ms elapsed=272.18s tid=0x00007faaa7183400 nid=0x19c03 waiting for monitor entry  [0x0000700019642000]
java.lang.Thread.State: BLOCKED (on object monitor)
at org.apache.pulsar.broker.service.persistent.PersistentSubscription.lambda$addConsumer$2(PersistentSubscription.java:207)
- waiting to lock <0x0000100015823488> (a org.apache.pulsar.broker.service.persistent.PersistentSubscription)
at org.apache.pulsar.broker.service.persistent.PersistentSubscription$$Lambda$984/0x000000080136d898.apply(Unknown Source)
at java.util.concurrent.CompletableFuture.uniComposeStage(java.base@17.0 …
```
=> [improve][broker] Reduce the consumers list sort by priority level

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
The broker don't need to go through all the consumers to get the ack owner consumer.
Instead, it should check the current consumer first. If the pending acks of current consumer
don't have the ack position, go through all the consumers to find the owner consumer.
Without this PR:
[perf_broker_subscribe_1.html.txt](https://github.com/apache/pulsar/files/8993011/perf_broker_subscribe_1.html.txt)
With this PR:
[perf_broker_subscribe_2.html.txt](https://github.com/apache/pulsar/files/8993012/perf_broker_subscribe_2.html.txt) …
=> [improve][broker] Avoid go through all the consumers to get the message ack owner

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckStore.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/InMemoryPendingAckStore.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStore.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/PendingAckHandleImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentSubscriptionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/util/ExecutorProvider.java, pulsar-client/src/main/java/org/apache/pulsar/client/util/ScheduledExecutorProvider.java
The Scheduled Executor doesn't work very efficiently because each task will add to a DelayedQueue(A priority queue) first even if using the `.execute()` method without any schedule delay.
Profile result: 
[perf_consumer_0.html.txt](https://github.com/apache/pulsar/files/8989093/perf_consumer_0.html.txt)
Running a performance test for single topic max message read rate test:
```
bin/pulsar-perf consume test -q 1000000 -p 100000000
bin/pulsar-perf produce test -r 1000000 -s 1 -mk random -o 10000 -threads 2
```
Without this PR (2.10.1):
```
Profiling started
2022-06-27T13:44:01,183+0800 [main] INFO  org.apache.pulsar.testclient.PerformanceConsumer - Throughput received: 23919664 msg --- 265702.851  msg/s --- 2.027 Mbit/s  --- Latency: mean: 49430.572 ms - med: 49406 - 95pct: 52853 - 99pct: …
```
=> [improve][java-client] Replace ScheduledExecutor to improve performance of message consumption

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
Fix the CPU consumption while having many consumers (> 100k) and enabled dispatch rate limit.
[broker_perf.html.txt](https://github.com/apache/pulsar/files/8991916/broker_perf.html.txt)
- Added `isRescheduleReadInProgress` to ensure the dispatcher only has one pending re-schedule read task at a time.
- Added DEBUG log for the re-schedule read operation …
=> [improve][broker] Reduce the re-schedule message read operation for PersistentDispatcherMultipleConsumers

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageChunkingTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Fixes https://github.com/apache/pulsar/issues/16195
[PIP-132](https://github.com/apache/pulsar/pull/14007) considers the
message metadata size when computing the payload chunk size and the
number of chunks. However, it could make some messages whose size is
less than `maxMessageSize` cannot be sent. There are two reasons:
1. The `MessageMetadata` will be updated after computing the payload
chunk size, i.e. the actual metadata size would be greater.
2. `OpSendMsg#getMessageHeaderAndPayloadSize` doesn't exclude all bytes
other than the metadata and payload, e.g. the 4 bytes checksum field.
For example, if the max message size is 100, send a string whose size is
60 with chunking enabled.
1. The initial metadata size is 25 so the chunk size is 75, the message
won't be spit into chunks.
2. …
=> [fix][Java Client] Fix large message sometimes cannot be split into chunks after PIP-132

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java
When broker do `monitorBacklogQuota`, there may throw NPE.
```
2022-06-24T18:14:38,360-0400 [pulsar-backlog-quota-checker-29-1] ERROR org.apache.pulsar.broker.service.BacklogQuotaManager - [persistent://enmv/epnmccs-yang/ECLIPSE-epnmccs-yang-ms-east-partition-1] Error resetting cursor for slowest consumer [ENMV_CCS_SUBSCRIPTION]
java.lang.NullPointerException: null
at org.apache.pulsar.broker.service.BacklogQuotaManager.dropBacklogForTimeLimit(BacklogQuotaManager.java:247) 
at org.apache.pulsar.broker.service.BacklogQuotaManager.handleExceededBacklogQuota(BacklogQuotaManager.java:127) 
at org.apache.pulsar.broker.service.BrokerService.lambda$monitorBacklogQuota$78(BrokerService.java:1721) 
at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
at …
```
=> [fix][broker] Fix NPE when drop backlog for time limit.

pulsar-io/hdfs2/pom.xml, pulsar-io/influxdb/pom.xml, pulsar-io/nsq/pom.xml, pulsar-io/redis/pom.xml, pulsar-io/solr/pom.xml, pulsar-io/twitter/pom.xml
Use parent `commons-lang3` version instead of define it each module
=> [dependency] Use parent pom commons-lang3 version

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionLowWaterMarkTest.java
when send txn message is lower than low watermark, tb will throw`NotAllowedException`, but now we don't decrease PendingWriteOps, if PendingWriteOps != 0 and managed ledger in `WriteFailed` state, we can't roll over the ledger and create a new ledger.
https://github.com/apache/pulsar/blob/336fcb0cf848d59fde1a35c5618c7a005b7ddfc4/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L492-L507
when tb throw `NotAllowedException`, we should do decrementPendingWriteOpsAndCheck
add the check for pendingWriteOps …
=> [fix][txn] Fix append txn message is lower than lowWaterMark decrease PendingWriteOps

pulsar-common/src/main/java/org/apache/pulsar/common/util/FieldParser.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/FieldParserTest.java
Fixes https://github.com/apache/pulsar/issues/16137
The order of items is not preserved for configuration fields of the type `Set`. Preserving the order of items in the config would make the program behavior to be more predictable, and may potentially make it possible for more operation flexibilities.
Create a `LinkedHashSet` rather than a `HashSet` when converting string to Set.
This change is already covered by existing tests, such as `FieldParserTest.testConversion`.
- The admin cli options: …
=> [improve][broker] Use LinkedHashSet for config items of type Set to preserve elements order

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxAuthorizationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
#16065 fixes the race condition issue, but introduces a new issue. This issue is triggered when the Proxy and Broker work together, when we use the proxy to request the broker to do lookup/subscribe/produce operation, the broker always uses the original authentication data for authorization, not proxy authentication data, which causes this issue.
- Fix passing authentication data, differentiate between original auth data and connected auth data by avoid to use the  `getAuthenticationData()`, this method name is easy to cause confusion and can not correctly get the authentication data
Added unit test.
=> [fix][broker] Fix passing incorrect authentication data

site2/docs/client-libraries-go.md
The official markdown table is a misplaced layout .
fix go docs markdown table layout.
fix go docs markdown table layout.
=> Fix wrong table format in client-libraries-go.md

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
Master Issue: https://github.com/apache/pulsar/issues/14365
* See https://github.com/apache/pulsar/issues/14365
* Make getList async
=> [improve][broker][PIP-149]Make getList async

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
When a client attempts to perform certain actions using the pulsar protocol but is unauthorized, it gets an error that references the proxy, even when the proxy is not in use. This PR improves the clarity of the error message returned to the client.
Sample error from a client that targeted the broker directly:
> Caused by: org.apache.pulsar.client.api.PulsarClientException$AuthorizationException: {"errorMsg":"Proxy Client is not authorized to Get Partition Metadata","reqId":2752438136626111826, "remote":"broker.pulsar.com/10.53.129.179:6650", "local":"/10.233.82.53:63618"}
at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1026)
at org.apache.pulsar.client.impl.ProducerBuilderImpl.create(ProducerBuilderImpl.java:88)
* Remove `Proxy` from error messages …
=> [fix][broker] Improve error msg when client is unauthorized

pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/SinkRecordTest.java, pulsar-io/file/src/test/java/org/apache/pulsar/io/file/FileSourceConfigTests.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/TestPulsarSQLAuth.java
Using TestNG instead of Junit.
=> [cleanup][dependency] Remove use of JUnit

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
`ProducerQueueIsFullError` exception is encountered when sending DLQ, no need to print an exception stack. Because sending DLQ fails, it will be re-delivered.
- Only print exception message instead of exception stack.
=> [improve][java client] No need print exception stack when DLQ send failed.

pom.xml
Fixes #13067 
Bump `os-maven-plugin` version from 1.4.1.Final to 1.7.0 to support build on  RISC-V architecture.
See: https://github.com/trustin/os-maven-plugin/releases/tag/os-maven-plugin-1.7.0
Bump `os-maven-plugin` version from 1.4.1.Final to 1.7.0.
=> [improve][build] Bump os-maven-plugin version from 1.4.1.Final to 1.7.0

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
* AdminApiTest is flaky. The testGetPartitionedStatsInternal test method fails sporadically.  This PR https://github.com/apache/pulsar/pull/13656 has tried to fix the bug, but I find the test `AdminApiTest#testGetPartitionedStatsInternal` can also be failure.
* The root cause is the `availableBookiesFuture#handle` can run before `availableBookiesFuture#whenComplete`. Because there is no guarantee that `CompleteFuture`  will run `handle` and `whenComplete` and so on in order. For example,
```
public static void main(String[] args) {
CompletableFuture<String> future = new CompletableFuture<>();
CompletableFuture<String> appFuture = future.thenApply(s -> s);
appFuture.handle((res, throwable) -> {
System.out.println("handle");
return null;
});
appFuture.whenComplete((res, ex) -> { …
```
=> [fix][broker]Fix getInternalStats occasional lack of LeaderInfo again

pulsar-broker/src/main/java/org/apache/pulsar/broker/ManagedLedgerClientFactory.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
It failed to expose bookkeeper client managed ledger stats to prometheus if setting `bookkeeperClientExposeStatsToPrometheus=true` in `ServiceConfiguration`. Because creating BkClient ignore the `StatsLogger` and use the `NullStatsLogger.INSTANCE` as default.
```java
//class: org.apache.pulsar.broker.BookKeeperClientFactoryImpl
@Override
public BookKeeper create(ServiceConfiguration conf, ZooKeeper zkClient, EventLoopGroup eventLoopGroup,
Optional<Class<? extends EnsemblePlacementPolicy>> ensemblePlacementPolicyClass,
Map<String, Object> properties) throws IOException {
return create(conf, zkClient, eventLoopGroup, ensemblePlacementPolicyClass, properties,
NullStatsLogger.INSTANCE);
}
```
Add `StatsLogger` into BookKeeperClientFactory when creating BkClient.
The screenshot below is the …
=> [fix][broker]fix bug: fail to expose managed ledger client stats to prometheus if bookkeeperClientExposeStatsToPrometheus is true

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractSubscriptionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsumerTest.java
AbstractTopic#getBytesOutCounter and AbstractTopic#getMsgOutCounter
both generate full stats only to pick the single required counter for
the getters. These can be optimised to perform only the necessary work
to calculate the counters.
Provided a scoped implementation of the above methods for the single
counter required for each getter.
Fixes #16214
```
mvn clean install -Pcore-modules,-main -DskipTests
mvn test -pl pulsar-broker -Dtest="AbstractTopicTest,AbstractSubscriptionTest,ConsumerTest"
```
- The default values of configurations: …
=> [improve][broker] Optimise msgOutCounter and bytesOutCounter (#16214)

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java, tests/docker-images/java-test-functions/src/main/java/org/apache/pulsar/tests/integration/io/TestByteStateSource.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarStateTest.java
Fixes #16193 
Now, if put a byte[] type state to a function, they can get an incorrect string type state using admin API.
The root cause is that bytes may not be a well-formed UTF-8 byte sequence, so we should not decode it to a UTF-8 string.
References: 
[Unicode6.2.0](http://www.unicode.org/versions/Unicode6.2.0/ch03.pdf)
Add a check the bytes whether is a well-formed UTF-8 byte sequence when decode the `FunctionState` bytes.
This change is already covered by existing tests, such as `testSourceByteState`, `testBytes2StringNotUTF8`
- The wire protocol: (yes …
=> [fix][function] Ensure bytes is a well-formed UTF-8 byte sequence when decode the `FunctionState` bytes to string

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/BaseGenerateDocumentation.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdGenerateDocument.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdGenerateDocumentation.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/CmdGenerateDocumentation.java
=> When generate doc, ignore the hidden parameters.

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java
we don't handle append tb transaction marker when the ledger in `WriteFailed` throw `ManagedLedgerAlreadyClosedException.` 
When ledger in `WriteFailed,` we need to close the current ledger and create a new ledger, same as https://github.com/apache/pulsar/pull/14738 
change the ledger to the `WriteFailed` state, and it will take automatic recovery, and the commit will be successful
- Does this pull request introduces a new feature? (yes)
- If yes, how is the feature …
=> [fix][txn] Fix TopicTransactionBuffer ledger apend marker throw ManagedLedgerAlreadyClosedException

pom.xml
So that we can work with JDK17; otherwise, it will fail with "Unsupported class file major version 61".
See also https://issues.apache.org/jira/browse/MDEP-742.
Bump maven-dependency-plugin to 3.3.0
=> [improve][dependency] Bump maven-dependency-plugin to 3.3.0

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/PulsarClientImplTest.java
#16236 introduced a new scheduled executor but does not support passing the existing scheduled executor providers like #12037.
=> [improve][java-client] Support passing existing scheduled executor providers to the client

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
In selectBrokerForAssignment, when the broker is selected again, it is not judged whether the selected broker is empty.
=> fix select broker is none

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/StreamingStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedConsumerStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedSubscriptionStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ConsumerStats.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionStats.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/ConsumerStatsImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java, pulsar-common/src/main/proto/PulsarApi.proto
Merge https://github.com/apache/pulsar/pull/15674 and https://github.com/apache/pulsar/pull/16108 into branch-2.9
add metrics for consumer message ack rate
- The wire protocol: (yes)
=> [branch-2.9]add message ack rate

pulsar-broker/src/main/java/org/apache/pulsar/broker/ManagedLedgerClientFactory.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
Cherry-pick   #16219
It failed to expose bookkeeper client managed ledger stats to prometheus if setting `bookkeeperClientExposeStatsToPrometheus=true` in `ServiceConfiguration`. Because creating BkClient ignore the `StatsLogger` and use the `NullStatsLogger.INSTANCE` as default.
```java
//class: org.apache.pulsar.broker.BookKeeperClientFactoryImpl
@Override
public BookKeeper create(ServiceConfiguration conf, ZooKeeper zkClient, EventLoopGroup eventLoopGroup,
Optional<Class<? extends EnsemblePlacementPolicy>> ensemblePlacementPolicyClass,
Map<String, Object> properties) throws IOException {
return create(conf, zkClient, eventLoopGroup, ensemblePlacementPolicyClass, properties,
NullStatsLogger.INSTANCE);
}
```
Add `StatsLogger` into BookKeeperClientFactory when creating BkClient.
The …
=> [Branch-2.9][Cherry-pick] fix bug: fail to expose managed ledger client stats to prometheus if bookkeeperClientExposeStatsToPrometheus is true 

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
During the async create topic we were still calling the blocking `isServiceUnitActive()` which can cause a deadlock:
```
"main-EventThread" #19 daemon prio=5 os_prio=0 cpu=15617.40ms elapsed=277.07s tid=0x00007f2eb267e000 nid=0x56e5 waiting on condition  [0x00007f2e5d0a7000]
at jdk.internal.misc.Unsafe.park(java.base@11.0.15/Native Method)
- parking to wait for  <0x00000007ecf28a48> (a java.util.concurrent.CompletableFuture$Signaller)
at java.util.concurrent.locks.LockSupport.park(java.base@11.0.15/LockSupport.java:194)
at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.15/CompletableFuture.java:1796)
at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.15/ForkJoinPool.java:3128)
at …
```
=> Fixed deadlock when checking topic ownership

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
There are several logs messages, printed during the loading of a topic that are quite redundant in the information they provide.
eg: 
```
2022-07-01T20:58:25,229-0700 [pulsar-io-4-20] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:65427] Subscribing on topic persistent://public/default/my-topic-49642 / sub
2022-07-01T20:58:44,797-0700 [broker-topic-workers-OrderedExecutor-1-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Opening managed ledger public/default/persistent/my-topic-49642
2022-07-01T20:58:45,481-0700 [bookkeeper-ml-scheduler-OrderedScheduler-2-0] INFO  org.apache.bookkeeper.mledger.impl.MetaStoreImpl - Creating '/managed-ledgers/public/default/persistent/my-topic-49642'
2022-07-01T20:58:46,165-0700 [main-EventThread] INFO …
```
=> Reduced level of redundant logs

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
#16334 supports passing scheduled executor to the client. Use a shared scheduled executor
for the broker clients which used by replicator and system topics.
=> [improve][broker] Use shared broker client scheduled executor provider

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/BookKeeperClientFactoryImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/BookKeeperClientFactoryImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java, site2/docs/reference-configuration.md
The broker always uses the broker IO thread pool as the BookKeeper Client IO thread pool.
The PR provides the ability to use a separated IO thread pool for the BookKeeper Client.
Introduced two new configurations but will not change the default behavior.
```
bookkeeperClientNumIoThreads=
bookkeeperClientSeparatedIoThreadsEnabled=false
```
Added a new test to verify the new configuration.
=> [improve][broker] Able to use separated IO threads for BookKeeper Client

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicDispatchRateLimiterTest.java
* Fix dispatch rate limiter doesn't be initialized on broker-level: 
* * If `DispatchRateLimiter`  is disabled at first, then we update only broker-level dispatch rate dynamicly, it will not take affect because `topic.getDispatchRateLimiter().isPresent()` is false, line:2377
https://github.com/apache/pulsar/blob/8914b84115bacaf38fe892d66533c1b70431acbf/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L2370-L2379
*  Create a method `updateDispatchRateLimiter()` to initialize and update the dispatch rate limiter
- *Added UT `TopicDispatchRateLimiterTest`*
=> [Fix][broker]Fix topic dispatch rate limiter not init on broker-level

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
* Fix `org.apache.pulsar.client.admin.Topics#removeReplicationClusters` not taking effect:  Because we have used `HierarchyTopicPolicies` to save topic-level policies,  so we shoud  removing `policies.getReplicationClusters() != null`.
* Removing  `policies.getReplicationClusters() != null` when topic-level policies updating
* Also, we need initialize namespace-policy first and then initialize topic-policy when `PersistentTopic#initialize`.  The reason is that：
* namespace-policy always has local cluster name in `Policies#replication_clusters` when using adminV2.
* topic-policy may not  contains local cluster name in `TopicPolicies#replicationClusters`.
* If we follow the steps listed below, the persistent topic will be deleted unexpectedly, which makes the …
=> [fix][broker]Fix removing replica clusters on topic-policies not take effect

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
Make the below method async:
`getSubscriptionExpirationTime` 
`setSubscriptionExpirationTime` 
`removeSubscriptionExpirationTime`
=> [improve][broker]Make SubscriptionExpirationTime method async

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarChannelInitializer.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarChannelInitializer.java
This is similar to https://github.com/apache/bookkeeper/pull/3383.
When we are writing/reading a lot of small entries, one of the main bottleneck in Pulsar client/broker becomes the CPU usage. A big part of it is caused by the syscall overhead when writing to the socket. 
The reason is that we have many independent (and small) operations happening on the connection and each time we call `writeAndFlush()` on each of them, causing many `write()` calls on the socket.
Netty has a mechanism to consolidate the flushes on the channel and it improves the handling of many small entries.
=> Consolidate Netty channel flushes to mitigate syscall overhead

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java
Fixes #16374 
Fix the flaky test `PatternTopicsConsumerImplTest.testAutoSubscribePatternConsumer`.
=> [fix][flaky-test] Fix failed test PatternTopicsConsumerImplTest.testAutoSubscribePatternConsumer

.github/workflows/ci-cancel-duplicate-workflows.yaml
Master Issue: #15797 
Cancel duplicate docbot workflows.
Add docbot ci to cancel workflow.
*(or)*
*(or)*
*(example:)*
- The …
=> [fix][workflow] Cancel duplicate docbot workflows

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceAutoTopicCreationTest.java
Fixes #16384
Fix flaky test testDynamicConfigurationTopicAutoCreationPartitionedWhenDefaultMoreThanMax.
Make sure the dynamic cache is updated to prevent the flaky test.
=> [fix][flaky-test] Fix flaky test testDynamicConfigurationTopicAutoCreationPartitionedWhenDefaultMoreThanMax

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
Cherry-pick #16201, ignore the test file, which doesn't applicable to this version.
=> [branch-2.7][fix][broker] Fix passing incorrect authentication data

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ServiceChannelInitializer.java
Follow change for https://github.com/apache/pulsar/pull/16361 which commented at https://github.com/apache/pulsar/pull/16361#issuecomment-1173241406
=> [improve][proxy] Consolidate Netty channel flushes to mitigate syscall overhead

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessagesImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
After running the test with the partitioned topic(partitioned topic with only 1 partition) and 4 IO threads.
```
bin/pulsar-perf produce test -r 500000 -s 1 -o 10000 -threads 2
bin/pulsar-perf consume test -q 100000 -ioThreads 4
```
The consumer got a very bad performance:
```
Profiling started
2022-07-01T23:03:13,230+0800 [main] INFO  org.apache.pulsar.testclient.PerformanceConsumer - Throughput received:  216223 msg --- 21517.245  msg/s --- 0.164 Mbit/s  --- Latency: mean: 2702.319 ms - med: 2644 - 95pct: 4594 - 99pct: 4758 - 99.9pct: 4844 - 99.99pct: 4854 - Max: 4854
2022-07-01T23:03:23,494+0800 [main] INFO  org.apache.pulsar.testclient.PerformanceConsumer - Throughput received:  812896 msg --- 58004.006  msg/s --- 0.443 Mbit/s  --- Latency: mean: 9826.540 ms - med: 9992 - 95pct: 12905 …
```
=> [improve][java-client] Improve performance of multi-topic consumer with more than one IO thread

pom.xml, pulsar-client-tools/pom.xml, pulsar-client/pom.xml
---
*Motivation*
We upgrade the Netty Reactive Stream in the PR #15990,
but the asynchttpclient still uses it. We should use
our project dependency to address the CVE.
=> Exclude the Netty Reactive Stream from asynchttpclient

site2/docs/sql-getting-started.md
Master Issue: #16354
After https://github.com/apache/pulsar/pull/15478 gets merged, the zookeeper won't be enabled by default when starting the pulsar standalone. But the pulsar SQL depends on the zookeeper. We need to set`PULSAR_STANDALONE_USE_ZOOKEEPER=1` to enable zookeeper when using the pulsar SQL as mentioned in https://github.com/apache/pulsar/issues/16354#issuecomment-1173092956.
* Add `PULSAR_STANDALONE_USE_ZOOKEEPER=1` before running pulsar standalone in pulsar-sql doc
These changes only need to apply to the doc of pulsar 2.11 and later.
=> [fix][doc] Enable zk when starting standalone in pulsar-sql doc

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
Release the entry after using it in getEarliestMessagePublishTimeOfPos.
=> [fix][managedLedger] Release the entry in getEarliestMessagePublishTimeOfPos.

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
Cherry-pick #13476
Currently, if the last confirmed entry is an empty ledger, getting the last message-id operation will get data from the compact ledger, if the compact ledger is also an empty ledger, it will encounter `IncorrectParameterException`.
**Broker error message**
```
[pulsar-io-29-9] ERROR org.apache.bookkeeper.client.LedgerHandle - IncorrectParameterException on ledgerId:617 firstEntry:-1 lastEntry:-1
```
**Client error log**
```
Exception in thread "main" org.apache.pulsar.client.api.PulsarClientException$BrokerMetadataException: The subscription reader-bf9246cfcb of the topic persistent://public/ns-test/t1 gets the last message id was failed
{"errorMsg":"Failed to read last entry of the compacted Ledger Incorrect parameter input","reqId":79405902881798690, …
```
=> [Branch-2.7][Cherry-pick] Fix getting the last message-id from an empty compact ledger.

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
Cherry-pick #12602
For the non-durable cursor, the ledgers trimming task will cause skip the removed ledgers
to avoid readers introduced backlogs and make sure the data can be removed if over the retention,
more details to see #6787.
But for a topic that enabled compaction, this will lead to the reader skipping the compacted data.
The newly added test can illustrate this problem well. For reading compacted data, reading a message ID
that earlier that the first message ID of the original data is normal behavior, so we should not
move forward the cursor which will read the compacted data.
=> [Branch-2.7][Cherry-pick] Do not move the non-durable cursor position when trimming ledgers while topic with compaction

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
* Fix the following method use `getTopicReferenceAsync`:
*  `internalDeleteSubscriptionForNonPartitionedTopic`
*   `internalUpdateSubscriptionPropertiesForNonPartitionedTopic`
*   `internalDeleteSubscriptionForNonPartitionedTopicForcefully`
* Replace `getTopicReferenceAsync` to `getTopicReference`
=> [fix][broker]Fix async method use getTopicReferenceAsync

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
Master issue： #16327
Make the `unloadNamespaceBundle` method in Namespaces to pure async.
This also fixes broker do rebalance to unload namespace bundle.
```
00:12:31.858 [pulsar-load-manager-1-1] WARN  org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl - Error when trying to perform load shedding on.  xxx/public/0xb0000000_0xc0000000 for broker 10.0.37.216:8080
org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: HTTP 500 Internal Server Error
at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:219) ~[org.apache.pulsar-pulsar-client-admin-original-2.8.0.jar:2.8.0]
```
=> [improve][broker] Make `unloadNamespaceBundle` async.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/CompactorSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java
Cherry-pick #12522
The compactor update the compaction cursor(mark delete) first and then update the `compactionHorizon` of the compacted topic. During the compaction cursor move forward, the original ledger will be removed if no other durable cursors. At the same time, if the reader is reading data from the original ledger, the reader will skip the data while the original ledger been removed, details to see https://github.com/apache/pulsar/pull/6787. So the reader might skip the compacted data since the `compactionHorizon` have not updated yet.
The approach is:
1. Update the `compactionHorizon` before the compaction cursor move forward,
so that the reader will not skip the original data before `compactionHorizon` updated.
If the broker crashes before the new compacted Ledger ID been …
=> [Branch-2.7][Cherry-pick] Fix the reader skips compacted data which original ledger been removed.

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
Cherry-pick #12698
Fix lost compaction data due to compaction properties missed during reset-cursor.
1. The compaction reader will seek to the earliest position to read data from the topic, but the compaction properties missed during the cursor reset, this will lead to the inited compaction subscribe without compaction horizon, so the compaction reader will skip the last compacted data. It will only happen when init the compaction subscription, so can introduced by the loadbalance or topic unloading manually.
2. Advance the cursor should also keep the properties, otherwise, the properties will lost during the cursor trimming.
1. Keep the properties for resetting the cursor while the cursor is for data compaction.
2. Copy the properties to the new mark delete entry while advance the …
=> [Branch-2.7][Cherry-pick] Fix lost compaction data due to compaction properties missed during reset-cursor.

pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java
When using RawReader to read messages, we found some messages are out of order.
For method `tryCompletePending`, we find there are two thread pools to call it, one is `pulsar-client-internal` and the other is `pulsar-io` 
https://github.com/apache/pulsar/blob/aabd5d020543210921f10648caf6720adc41d651/pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java#L131-L164
When triggered by `messageReceived()`, it will use `pulsar-io` thread pool.
https://github.com/apache/pulsar/blob/aabd5d020543210921f10648caf6720adc41d651/pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java#L208-L218
If triggered by `receiveRawAsync`, it will use `pulsar-client-internal` thread pool.
https://github.com/apache/pulsar/blob/aabd5d020543210921f10648caf6720adc41d651/pulsar …
=> [fix][broker] Fix RawReader out of order

.github/workflows/ci-build-multi-os.yaml, .github/workflows/ci-docker-build.yaml, .github/workflows/ci-integration-backwards-compatibility.yaml, .github/workflows/ci-integration-cli.yaml, .github/workflows/ci-integration-function-state.yaml, .github/workflows/ci-integration-messaging.yaml, .github/workflows/ci-integration-process.yaml, .github/workflows/ci-integration-schema.yaml, .github/workflows/ci-integration-sql.yaml, .github/workflows/ci-integration-standalone.yaml, .github/workflows/ci-integration-thread.yaml, .github/workflows/ci-integration-tiered-filesystem.yaml, .github/workflows/ci-integration-tiered-jcloud.yaml, .github/workflows/ci-integration-transaction.yaml, .github/workflows/ci-license.yaml, .github/workflows/ci-shade-test.yaml, .github/workflows/ci-unit-broker-broker-gp1.yaml, .github/workflows/ci-unit-broker-broker-gp2.yaml, .github/workflows/ci-unit-broker-client-api.yaml, .github/workflows/ci-unit-broker-client-impl.yaml, .github/workflows/ci-unit-broker-other.yaml, .github/workflows/ci-unit-proxy.yaml, .github/workflows/ci-unit.yaml
Some workflows do not have set up the Java, we need to add this step. If we do not set up the Java, the workflow uses the built-in Java 8, which seems unstable and causes the TLS tests to fail. I suggest we should use the Eclipse Temurin Java instead of the default Java, and switch Java 11 to Java 8 because Java 11 breaks the TLS test.
- Switch `actions/setup-java` from `v1` to `v3`, and use the Eclipse Temurin Java 8
- Add `actions/setup-java` to the workflow that does not set up the Java version
=> [branch-2.7][improve][ci] Add set up Java

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
`ManagedCursorImpl` maintains a field `waitingReadOp` as the cache of
the `OpReadEntry` created in `asyncReadEntriesOrWait` when there are no
more entries to read. However, there are two cases that the created
`OpReadEntry` are not recycled:
1. `asyncReadEntriesOrWait` is called repeatedly when `waitingReadOp` is
not null and there are no more entries. The new created `OpReadEntry`
cannot pass the CAS check but it's not recycled.
2. `cancelPendingReadRequest` is called. The `waitingReadOp` is just set
with null and the previous reference is not recycled.
For the two cases described above, recycle the `OpReadEntry` objects.
Add `testOpReadEntryRecycle` to reproduce the corner cases and verify the
count of `recycle()` calls.
Need to update …
=> [improve][broker] Recycle OpReadEntry in some corner cases

.asf.yaml
Fixes #16437 
The label check must not be included.
Change `.asf.yaml`
Simple configuration change
=> Remove Label from required checks

pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPoliciesImpl.java
Master Issue: #16432
It's named `managedLedgerDataReadPriority` in ServiceConfiguration , but named `managedLedgerOffloadedReadPriority` in OffloadPoliciesImpl.  So when copy properties, it' can't set the right field and cause OffloadPoliciesImpl to use the default value.
=> [fix][common] Fix setManagedLedgerOffloadedReadPriority not work.

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Some parameters in OpSendMsg are not specified with initialized values. 
These initial values are all relied upon by other codes. Such as here:
https://github.com/apache/pulsar/blob/eec46ddcba4d2b4f956e1b4d63154cc43087f507/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L1409-L1422
* Add the initialization for the OpSendMsg.
=> [fix][client] Add initialization for the OpSendMsg

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
**In the log we found No such ledger exception:**
**The reasons are as follows:**
**1. Frequent Full GC occurs on the broker, causing zk to time out：**
22:29:06.119 [main-EventThread] ERROR org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase - ZooKeeper client connection to the ZooKeeper server has expired!
**2.When the create leadger is completed, the ledger will be put into ledgers and update currentLedger，the updateLedgersListAfterRollover method is executed, and the metadata to zookeeper fails to write：**
https://github.com/apache/pulsar/blob/4c958a9a1a0468656e37851293cf1930041d2c93/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L1484-L1489
**3.In the failure callback method operationFailed, the corresponding ledger will be removed from the …
=> [fix][broker] fix No such ledger exception

site2/docs/client-libraries-java.md
Fixes #16449 
Missing consumer config `ackReceiptEnabled`.
Add doc for `ackReceiptEnabled` config.
=> [fix][doc] Add doc for `ackReceiptEnabled` config

site2/docs/reference-metrics.md
doc for https://github.com/apache/pulsar/pull/15867
=> [doc][broker][monitoring] doc for DelayedDeliveryTracker memory usage

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java
When reading the javadoc of `ackTimeout`, user gets information, that default is 0, but this is not true, when dead letters are enabled.
Also update javadoc grammar in ConsumerBuilder.
Only javadoc extension.
Javadoc extension.
=> [Doc] Describe default ack timeout and update grammar in ConsumerBuilder javadoc

build/run_unit_group.sh
=> [fix][test] Disable ReuseFork for broker group 1

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
That's a regular update, `jcommander` 1.78 was released in 2019.
Bump jcommander version from 1.78 to 1.82
=> Bump jcommander version from 1.78 to 1.82

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LinuxBrokerHostUsageImpl.java
Update cpu ResourceUsage before updating SystemResourceUsage usage.
=> [fix][broker] Update cpu ResourceUsage before updating SystemResourceUsage usage

bouncy-castle/bcfips-include-test/src/test/java/org/apache/pulsar/client/TlsProducerConsumerTest.java, bouncy-castle/bcfips-include-test/src/test/resources/authentication/tls/broker-cert.pem, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthenticationTlsHostnameVerificationTest.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyServiceStarterTest.java
Java breaks the TLS tests, so some tests have been disabled.
=> [branch-2.7][fix][test] Enable ignored tests

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
Cherry-pick #16170 
Currently,  we can use `admin.namespaces().getTopics` to get topics under a namespace. But it could only return the non-persistent topics owned by the current broker.
Also, we can use `admin.toipics().getList` to get topics. It can return all non-persistent topics to users.
I think it is reasonable that we should make the data return of these two interfaces consistent.
=> [Branch-2.10][Cherry-pick] Fix get non-persistent topics issue in Namespaces.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
Cherry-pick #16170 
Currently,  we can use `admin.namespaces().getTopics` to get topics under a namespace. But it could only return the non-persistent topics owned by the current broker.
Also, we can use `admin.toipics().getList` to get topics. It can return all non-persistent topics to users.
I think it is reasonable that we should make the data return of these two interfaces consistent.
=> [Branch-2.9][Cherry-pick] Fix get non-persistent topics issue in Namespaces.

build/run_unit_group.sh, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentDispatcherFailoverConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherFailoverConsumerStreamingDispatcherTest.java
Move `testAddRemoveConsumer` to quarantine group to unblock PRs, https://github.com/apache/pulsar/pull/16473 will continues to fix the test.
=> [fix][flaky-test] Change testAddRemoveConsumer to quarantine group

pulsar-client-tools/pom.xml
`pulsar-client-tools` imports `pulsar-websocket` to run commands using the jetty websocket-client.
`pulsar-websocket` has huge dependencies since it depends on `pulsar-broker-common`.
This is useful in case you want to package the client-tools module in a standalone artifact (like https://github.com/apache/pulsar/pull/16332)
* Import only what needed to make it compilable (websocket client and swagger)
It doesn't affect the runtime execution since the classpath used by the CLI tools is the same as other commands
=> [cleanup] CLI: fix pulsar-websocket dependency importing only needed jars

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationProvider.java, pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java
Reduce build warnings noise.
```
[WARNING] ... AuthorizationProvider.java:[70,40] deprecated item is not annotated with @Deprecated
[WARNING] ... Context.java:[133,33] deprecated item is not annotated with @Deprecated
[WARNING] ... Context.java:[143,33] deprecated item is not annotated with @Deprecated
```
Add deprecation annotations where deprecated in Javadoc only. …
=> [cleanup][pulsar] Add deprecation annotations where deprecated in Javadoc only

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java
Fixes #16460
Fix flaky test `MessageTTLTest.testMessageExpiryAfterTopicUnload`
Remove hard code ledger ID validation
=> [fix][flaky-test] MessageTTLTest.testMessageExpiryAfterTopicUnload

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerStrategy.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerStrategyTest.java
email discussion thread: https://lists.apache.org/thread/36vyyhndr4og175k2bz3mfdf5ctd2xky
See PIP-182 #16274 
See #16274 
The main idea of the new strategy is to unify the requirement of load shedding strategy and bundle placement strategy, which consider the resource usage with weight, including historical observations.
How to calculate a score for a broker ?
- use its historical load and short-term load data with weight, which can solve the case of load jitter in a broker.
How to select a broker for assignning bundle ?
- select a broker based on which one has the least average resource usage with weight.
- the random selection algorithm is better than the `minScore` among low load brokers, and use `loadBalancerAverageResourceUsageDifferenceThresholdShedderPercentage ` to adjust the size …
=> [feature][broker]Provide new load balance placement strategy implementation based on the least resource usage with weight

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckPersistentTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicList.java
now if sub with txn will create pendingAck `managedLedger`, if one consumer use pattern sub by this namespace, will get the pendingAck `managedLedger` and try to sub the pendingAck `managedLedger`. then broker will try to create the pending ack topic, but now the pendingAck topic is forbidden to be created. So the consumer will not sub success.
don't allow the user to get the pendingAck `managedLedger`, and sub the pendingAck `managedLedger`.
filter the topic when users use patterns to get the topic's list.
add the test …
=> [fix][txn] fix pattern sub filter transaction system topic

testmocks/src/main/java/org/apache/zookeeper/MockZooKeeper.java
Catch exception when updating data in `mockZookeeper`. this problem looks like https://github.com/apache/pulsar/pull/15755
And move `lock()` into try/catch block in case of throwing exception from the lock.
https://github.com/apache/pulsar/blob/f519e22823e80c1771716f011ecb6d693d507d2c/testmocks/src/main/java/org/apache/zookeeper/MockZooKeeper.java#L213-L226
Also fix https://github.com/apache/pulsar/issues/16483
- Add catch for MockZookeeper.
*(or)*
*(or)*
*(example:)* …
=> [fix][test] Catch exception when update data in mockZookeeper

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentFailoverE2ETest.java
=> [fix][flaky-test] PersistentFailoverE2ETest.testSimpleConsumerEventsWithPartition

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE, src/owasp-dependency-check-false-positives.xml
Owasp check fails because jetty 9.4.44 is marked as vulnerable due to [CVE-2022-2047](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-2047)
Note that Jetty 9.4.x is EOL after `9.4.48.v20220622` 
* Upgrade to latest 9.4.x (9.4.48.v20220622)
(see https://github.com/eclipse/jetty.project/releases)
=> [fix][security] Upgrade to Jetty to 9.4.48.v20220622 to get rid of CVE-2022-2047

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
The current swagger documentation for the `authoritative` parameter is confusing and misleading. The field is meant to indicate to the serving broker whether the call was redirected by the leader broker. This has certain consequences for cases where topics or namespaces have not yet been assigned to a broker. It's possible for end users to set the field, but it is not recommended. The current documentation almost suggests a security vulnerability, which is why it is especially important to adjust.
This work needs to be cherry picked to all active branches to ensure that the new generated swagger docs are correct.
* Replace `Is authentication required to perform this operation` with `Whether leader broker redirected this call to this broker. For internal use.`
* Additionally, so `isGlobal` …
=> Update/fix Swagger Annotation for param: authoritative

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
Make the below method async:
`getPermissionOnSubscription` 
` grantPermissionOnNamespace` 
` grantPermissionOnSubscription`
`revokePermissionsOnNamespace`
`revokePermissionOnSubscription`
=> [improve][broker] Make some method on permission async

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
call MetadataStore#put without version by `MetadataStore.put(path, data, Optional.empty())` concurrently with same node may get `BadVersionException`
At first the node is not exist, put operation will fail and fall back to create node with `MetadataStore.put(path, data, -1)`.
`version=-1` means create the node, and if the node was just created by other thread, it will thow `BadVersionException`.
Since original call does not set `version`, `BadVersionException` is not excepted for caller.
We could just overwrite the value in this case.
=> [metadata] fix MetadataStore#put may get unexcepted exception

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
The `BacklogQuotaManagerTest` in Broker Group 1 runs for over 10 mins.
Avoid starting the test broker for each test method and reduce the TIME_TO_CHECK_BACKLOG_QUOTA to 2 seconds (Because the backlog check interval is 1 second at minimum, if we can't set TIME_TO_CHECK_BACKLOG_QUOTA to 1 second, the test will become unstable)
After the change, the test will be done in 4 mins.
=> [improve][test] Reduce the time consumption of BacklogQuotaManagerTest

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/NonPersistentTopicE2ETest.java
Stack Trace
```
Error:  Tests run: 10, Failures: 1, Errors: 0, Skipped: 9, Time elapsed: 65.361 s <<< FAILURE! - in org.apache.pulsar.broker.service.NonPersistentTopicE2ETest
Error:  testGC(org.apache.pulsar.broker.service.NonPersistentTopicE2ETest)  Time elapsed: 0.403 s  <<< FAILURE!
java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at org.apache.pulsar.broker.service.NonPersistentTopicE2ETest.testGC(NonPersistentTopicE2ETest.java:202)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeM …
```
=> [fix][flaky-test] NonPersistentTopicE2ETest.testGC

pulsar-client-cpp/lib/ClientImpl.cc, pulsar-client-cpp/tests/ClientTest.cc
Fixes #16509
Since all producers and consumer of the same Client share the same
connection pool, if one failed, the following producer or consumer might
reuse the broken connection and failed with `ResultConnectError`. It
causes the flaky `testWrongListener` because the consumer and reader
would be created after the producer creation failed with
`ResultServiceNotReady`.
Recreate the `Client` for the subsequent creation of `Consumer` and
`Reader` so that new connection pools will be used for them.
There is also a potential bug that makes `Client::shutdown` wait for the
max timeout (3 seconds), this PR also applies the timeout for other
executors.
After this change, I've run the following command in my local env and it
never failed.
```bash
./tests/main …
```
=> [improve][test] Fix flaky C++ ClientTest.testWrongListener

pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/worker/WorkerApiV2ResourceConfigTest.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/FunctionConfigUtilsTest.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SinkConfigUtilsTest.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SourceConfigUtilsTest.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/provider/TieredStorageConfigurationTests.java
Uses `Long`/`Integer.valueOf(...)` over `new` to reduce warning-related build noise:
```
[WARNING] ... Integer(int) in java.lang.Integer has been deprecated and marked for removal
```
To reduce noise when building and elevate the usefulness of warnings.
* `new Long(...)` -> `Long.valueOf(...)`
* `new Integer(...)` -> `Integer.valueOf(...)`
* Used Long literal recommended suffix `L` instead of `l`
* Removed one unused field.
(Your PR needs to …
=> [cleanup][pulsar] Remove warnings for deprecated API use

pulsar-client-api/src/main/java/org/apache/pulsar/common/schema/KeyValue.java
Reduces build noise by silencing expected warnings.
Suppressed a warning generated by a required unchecked conversion.
- The public API:  no
- The schema:  no
- The default values of configurations:  no
- The wire protocol:  no
- The rest endpoints:  no
- Anything that affects deployment:  no
Trivial non-functional change
=> [cleanup][pulsar-client-api] Removes warning of unchecked conversion

site2/docs/reference-metrics.md
There is no metrics document for bookkeeper's recovery yet, this PR is supposed to fix it.
1. Add bookkeeper recovery metrics doc in reference-metrics.md. Referred to: [ReplicationStats.java](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationStats.java)、[LedgerFragmentReplicator.java](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/client/LedgerFragmentReplicator.java)、[ReplicationWorker.java](https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/ReplicationWorker.java)
=> [storage][metrics][recovery][doc] Add bookkeeper recovery metrics doc

pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/BrokerInterceptorTest.java
The `assertTrue` is hard to debug when the assert fails.
Replace assertTrue with assertEquals
=> [refactor][test] Replace assertTrue with assertEquals in BrokerInterceptorTest

pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderTokenTest.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/validator/MultipleListenerValidatorTest.java, pulsar-broker-common/src/test/java/org/apache/pulsar/common/configuration/PulsarConfigurationLoaderTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/naming/NamespaceNameTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSetTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BacklogQuotaCompatibilityTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/LedgerUnderreplicationManagerTest.java
We wish to reduce warnings in the build output that don't add value to decrease build noise and generally increase the usefulness of warnings.
```
[WARNING] /Users/ewest/git/pulsar/pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSetTest.java:[45,13] ConcurrentOpenHashSet(int) in org.apache.pulsar.common.util.collections.ConcurrentOpenHashSet has been deprecated
```
Tests that target deprecated code clearly have a good reason to do so. We should not generate compiler warnings for such code. In one case a monolithic test case has been split up to better target the warning supression.
- …
=> [cleanup][pulsar] Remove warnings when testing deprecated code

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Support `getEarliestTimeInBacklog` at `getPartitionedStats` method.
- Support `getEarliestTimeInBacklog` at `getPartitionedStats` method.
=> [improve][cli] Support `getEarliestTimeInBacklog` at `getPartitionedStats` method.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
Master Issue: https://github.com/apache/pulsar/issues/14365
* See https://github.com/apache/pulsar/issues/14365
* Make `internalGetMessageIdByTimestamp` async
=> [improve][broker][PIP-149]Make GetMessageIdByTimestamp pure async

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/DistributedIdGenerator.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/coordination/CoordinationService.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/CoordinationServiceImpl.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/CounterTest.java
Fixes #16454
See #16454
When starting several brokers concurrently, there is a risk that one will fail with the following error:
```
2022-06-27T16:23:42,169+0000 [main] ERROR org.apache.pulsar.broker.PulsarService - Failed to start Pulsar service: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /counters/producer-name
java.util.concurrent.ExecutionException: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /counters/producer-name
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
at …
```
=> [fix][broker] Retry when DistributedIdGenerator has BadVersion error

pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/v2/TopicLookup.java
Current, Lookup REST Api no swagger docs annotations. will result in not being found on [Pulsar REST Api doc](https://pulsar.apache.org/admin-rest-api/?version=master).
- Add lookup REST Api swagger docs describe
Docs has exist.
=> [improve][rest] Add lookup REST Api swagger docs describe

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerException.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
Related issue: https://github.com/streamnative/kop/issues/1379
KoP uses reader on a single partition of a compacted topic and we
observed a lot of logs like:
> Error reading entries at 928511:1 : We can only have a single waiting callback
It happened on a `ManagedCursorImpl` when `hasMoreEntries` returns
false, `asyncReadEntriesOrWait` is called for multiple times before
`cancelPendingReadRequest` or new messages arrived.
Throw a `ConcurrentWaitCallbackException` instead of a raw
`ManagedLedgerException` when there are more wait callbacks. Then check
this exception type and skip the following steps in
`PersistentDispatcherSingleActiveConsumer#internalReadEntriesFailed`. …
=> [fix][broker] Skip reading more entries for a pending read with no more entries

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
1、This issue is triggered by namespace policies update. When namespace policies updated, `handlePoliciesUpdates` will be called next to update all the topics policies under this namespace. Too many topics would cause metadata-store waiting.
https://github.com/apache/pulsar/blob/318432ed1f16e60a088f3dca1b14891d582726a9/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L2034-L2062
Use thenAcceptAsync instead, execute `update topic policies` in a separated executor.
=> [improve][metadataStore] Update namespace policies would cause metadata-store thread waiting too long

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
=> [improve][broker][PIP-149]make getReplicatorDispatchRate method async

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
=> [improve][broker][PIP-149]make getBacklogQuotaMap method async in Namespaces

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderToken.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/metrics/AuthenticationMetrics.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorUtils.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionLocalRunTest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarBatchSourceE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarSinkE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarSourceE2ETest.java, pulsar-broker/src/test/resources/prometheus_metrics_sample.txt, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/stats/FunctionStatsManager.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/stats/SinkStatsManager.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/stats/SourceStatsManager.java, pulsar-functions/instance/src/main/python/function_stats.py, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyPrometheusMetricsTest.java, pulsar-sql/presto-distribution/LICENSE, site2/docs/reference-metrics.md
- prometheus `simpleclient` has broken api, it makes `pulsar-client-origin` can not well used with other libraries
- specify `OpenMetrics`
This PR contains metric name broken changes.
Bump prometheus client version from 0.5.0 to 0.15.0
- bump the client version
- rename the field prometheus client `UNTYPED` to `UNKNOWN`
- `OpenMetrics`'s counter name needs a `_total` suffix
- rename `pulsar_expired_token_count` to `pulsar_expired_token_total`
- rename `pulsar_authentication_success_count` to `pulsar_authentication_success_total`
- rename `pulsar_authentication_failures_count` to `pulsar_authentication_failures_total`
- rename `pulsar_sink_sink_exceptions_total_1min` to `pulsar_sink_sink_exceptions_1min_total`
- rename `pulsar_source_received_total_1min` to …
=> Bump prometheus client version from 0.5.0 to 0.15.0

site2/website/versioned_docs/version-2.10.0/io-quickstart.md, site2/website/versioned_docs/version-2.10.1/io-quickstart.md, site2/website/versioned_docs/version-2.5.0/io-quickstart.md, site2/website/versioned_docs/version-2.5.1/io-quickstart.md, site2/website/versioned_docs/version-2.5.2/io-quickstart.md, site2/website/versioned_docs/version-2.6.0/io-quickstart.md, site2/website/versioned_docs/version-2.6.1/io-quickstart.md, site2/website/versioned_docs/version-2.6.2/io-quickstart.md, site2/website/versioned_docs/version-2.6.3/io-quickstart.md, site2/website/versioned_docs/version-2.6.4/io-quickstart.md, site2/website/versioned_docs/version-2.7.0/io-quickstart.md, site2/website/versioned_docs/version-2.7.1/io-quickstart.md, site2/website/versioned_docs/version-2.7.2/io-quickstart.md, site2/website/versioned_docs/version-2.7.3/io-quickstart.md, site2/website/versioned_docs/version-2.7.4/io-quickstart.md, site2/website/versioned_docs/version-2.8.0/io-quickstart.md, site2/website/versioned_docs/version-2.8.1/io-quickstart.md, site2/website/versioned_docs/version-2.8.2/io-quickstart.md, site2/website/versioned_docs/version-2.8.3/io-quickstart.md, site2/website/versioned_docs/version-2.9.0/io-quickstart.md, site2/website/versioned_docs/version-2.9.1/io-quickstart.md, site2/website/versioned_docs/version-2.9.2/io-quickstart.md
* The tip section contained partial sentence  `The JDBC sink connector pulls messages from Pulsar topics `.  The rest of the sentence `and persists the messages to ClickHouse, MariaDB, PostgreSQL, or SQlite. ` was below the tip section.
* Moved partial sentence out to the tip section.
(Your PR needs …
=> [fix][io-quickstart][docs] Corrected split sentence in tip

pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/CounterBrokerInterceptor.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
The TransactionTest runs for over 3 minutes. To avoid starting a pulsar cluster for each test method.
```
[INFO] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 186.322 s - in org.apache.pulsar.broker.transaction.TransactionTest
```
After this change, the execution time was reduced to under 1 minute on my laptop
=> [improve][test] Improve the TransactionTest to reduce the execution time

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckPersistentTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java
`TransactionEndToEndTest#testSendTxnMessageTimeout` fails on releases branch after https://github.com/apache/pulsar/pull/16519 has been cherry-picked. 
```
java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at org.apache.pulsar.client.impl.TransactionEndToEndTest.testSendTxnMessageTimeout(TransactionEndToEndTest.java:1099)
```
The reason is that the mock setup must be slightly different since the `ProducerImpl` is not exactly the same between master and branch-2.10.
* Mock other classes that are used in the code path
=> [fix][test][branch-2.10] Fix test TransactionEndToEndTest#testSendTxnMessageTimeout (only release branches)

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
prometheus client 0.16.0 contains some approvements that we can benefit from. Thanks for @dave2wave @michaeljmarshall  the reminder and pointing out.
> [ENHANCEMENT] Reduce the number of core threads in HTTPServer from 5 to 1. The HTTPServer will still start up to 5 threads on demand if there are parallel requests, but it will use only 1 thread as long as requests are sequential (https://github.com/prometheus/client_java/pull/786).
[ENHANCEMENT] Optimize metric name sanitization: Replace the regular expression with a hard-coded optimized algorithm to improve performance (https://github.com/prometheus/client_java/pull/777). Thanks @fwbrasil
See https://github.com/prometheus/client_java/releases
Bump prometheus client version from 0.15.0 to 0.16.0
Check the box below or label this PR …
=> Bump prometheus client version from 0.15.0 to 0.16.0

bin/pulsar-admin-common.sh, bin/pulsar-shell, distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/DocumentTest.java, pulsar-client-tools/pom.xml, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBase.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdConsume.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdGenerateDocumentation.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdProduce.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/AdminShell.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/ClientShell.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/JCommanderCompleter.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/OptionStrictArgumentCompleter.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/PulsarShell.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/ShellCommandsProvider.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/package-info.java, pulsar-client-tools/src/test/java/org/apache/pulsar/shell/JCommanderCompleterTest.java, pulsar-client-tools/src/test/java/org/apache/pulsar/shell/PulsarShellTest.java
Master Issue: #16250 
[Demo](https://gifyu.com/image/SHX88)
* Introduced new command `bin/pulsar-shell`
* Implemented all the basic shell features (autocompletion, persisted history, welcome, quit, ctrl+c trap)
* Implemented wrappers for `pulsar-admin` and `pulsar-client`
* Added JLine3 to the classpath. 
* Refactored `pulsar-client` to use `pulsar-admin-commons.sh` since they file content are nearly equal. Now also the new script use that
Notes:
1. JCommander uses space as option value separator (e.g. `--admin-url http://myhost`). JLine only supports options with `=`. In order to make the completion works when using option, the last one is now accepted by the shell. The first one will works correctly but the completion won't work after that option.
2. ZK Cli uses JLine2. I manually …
=> [feature][cli] Pulsar Shell - pulsar-admin and pulsar-client - part 1

pom.xml, pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/BaseJdbcAutoSchemaSink.java, pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/JdbcAbstractSink.java, pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/JdbcSinkConfig.java, pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/JdbcUtils.java, pulsar-io/jdbc/core/src/test/java/org/apache/pulsar/io/jdbc/BaseJdbcAutoSchemaSinkTest.java, pulsar-io/jdbc/mariadb/src/main/java/org/apache/pulsar/io/jdbc/MariadbJdbcAutoSchemaSink.java, pulsar-io/jdbc/postgres/src/main/java/org/apache/pulsar/io/jdbc/PostgresJdbcAutoSchemaSink.java, pulsar-io/jdbc/sqlite/src/main/java/org/apache/pulsar/io/jdbc/SqliteJdbcAutoSchemaSink.java, pulsar-io/jdbc/sqlite/src/test/java/org/apache/pulsar/io/jdbc/JdbcUtilsTest.java, pulsar-io/jdbc/sqlite/src/test/java/org/apache/pulsar/io/jdbc/SqliteJdbcSinkTest.java, pulsar-io/jdbc/sqlite/src/test/java/org/apache/pulsar/io/jdbc/SqliteUtils.java, site2/docs/io-jdbc-sink.md
Currently JDBC sink will perform an insert query for most of the cases. The only way to execute an UPDATE or DELETE is to pass a specific property in the message properties. This is not handy and requires to all the sources to add this specific option.
The goal is to provide a way to upsert and delete records based on the record content while using key-value records.
1. Upsert: Insert or update the record based on the key fields.
2. Delete: if the value is NULL, delete the record for the given row.
* new config option `insertMode` with values
* INSERT: only perform blindly insert (default, in order to not break upgrades)
* UPDATE: only perform blindly update
* UPSERT: use upsert query. Main issue is that there's no SQL standard so every sink has his own implementation (by default it …
=> [feature][connector] JDBC sinks: support upsert and row deletion

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerManager.java
I observed the following error log in the bookkeeper:
> 2022-07-13T23:42:21,390+0000 [main-EventThread] ERROR org.apache.pulsar.metadata.bookkeeper.PulsarLedgerManager - Could not read metadata for ledger: 154498: java.util.NoSuchElementException: No value present
In looking closer, the error happens because there is a missing return statement after completing a promise.
The bug is cosmetic because the promise is completed with the correct error.
* Add a return statement after completing the promise.
No tests are needed since the effect of this bug is only a confusing log line.
This is not a breaking change.
=> [fix] PulsarLedgerManager: add missed return statement

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TransactionAggregator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/TransactionMetricsTest.java, site2/docs/reference-metrics.md
See https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md
A COUNTER needs `metrics_name_total` or `metrics_name_created`
This PR contains metric name broken changes.
Rename counter's `_count` to `_total`
- rename `pulsar_txn_committed_count` to `pulsar_txn_committed_total`
- rename `pulsar_txn_aborted_count` to `pulsar_txn_aborted_total`
- rename `pulsar_txn_created_count` to `pulsar_txn_created_total`
- rename `pulsar_txn_timeout_count` to `pulsar_txn_timeout_total`
- rename `pulsar_txn_append_log_count` to `pulsar_txn_append_log_total`
As mentioned above, the metrics name has changed
=> Rename Pulsar txn metrics to specify OpenMetrics

site2/docs/getting-started-helm.md, site2/docs/helm-deploy.md, site2/docs/kubernetes-helm.md
The helm option `--set initialize=true` is no longer needed.
See: https://github.com/apache/pulsar-helm-chart/pull/138
Signed-off-by: Paul Gier <paul.gier@datastax.com>
Minor simplification to the docs based on prior improvements to the helm charts.
Just removed some config from the site docs that is no longer needed.
- [ X ] `doc` 
=> [fix][doc] remove unnecessary option from helm install

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java
Fixes #16595
```
doReturn(CompletableFuture.completedFuture(topicNames)).when(nss)
.getListOfPersistentTopics(NamespaceName.get("my-property/my-ns"));
```
=> [fix][flaky-test] testAutoSubscribePatternConsumer

bin/pulsar-shell, distribution/pom.xml, distribution/shell/pom.xml, distribution/shell/src/assemble/README, distribution/shell/src/assemble/shell.xml, pulsar-client-tools/pom.xml
Master Issue: #16250
See master issue under "Distribution" section.
New tarball `pulsar-shell` under `distribution` directory. It generates a tarball with:
- `pulsar-client-tools` dependency (and transitive)
- log dependencies
- README + NOTICE as other packages
- bin/pulsar-shell and bin/pulsar-admin-common.sh scripts
- conf/client.conf for default configuration
=> [improve][cli] Pulsar shell: include pulsar-shell in released tarballs - part 2

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
When a EntryFilter reschedules a message we have a fixed delay of 1 second, that matches the default negativeAck delay on the Java client.
Add a new configuration option `dispatcherFilterRescheduledMessageDelay` to make this delay configurable
=> [enh] Broker/EntryFilter: make the delay for RESCHEDULED messages configurable (dispatcherFilterRescheduledMessageDelay)

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/DelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/InMemoryDeliveryTrackerTest.java
If all the messages in a topic have the same fixed delay, then there is no reason to track the entire set of messages in the priority queue, since the messages will have to be delivered in FIFO order. 
If we identify that this is the case, we need to switch into a different mode, where we pause the scanning of the topic and instead we just rely on the timer task from the delay-tracker which will get triggered for the 1st message to be delivered.
=> Avoid tracking the delays of all the message when we detect that they are fixed

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
Fix `MockStatic` method caused the exception.
```
The used MockMaker PowerMockMaker does not support the creation of static mocks
[3197](https://github.com/apache/pulsar/runs/7358126340?check_suite_focus=true#step:8:3198)
[3198](https://github.com/apache/pulsar/runs/7358126340?check_suite_focus=true#step:8:3199)
Mockito's inline mock maker supports static mocks based on the Instrumentation API.
[3199](https://github.com/apache/pulsar/runs/7358126340?check_suite_focus=true#step:8:3200)
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
[3200](https://github.com/apache/pulsar/runs/7358126340?check_suite_focus=true#step:8:3201)
Note that Mockito's inline mock maker is not supported on Android. …
```
=> [branch-2.9] Fix `MockStatic` method caused the  exception

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/SchemaServiceTest.java, site2/docs/reference-metrics.md
See https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md
A COUNTER needs `metrics_name_total` or `metrics_name_created`
This PR contains metric name broken changes.
Rename counter's `_count` to `_total`
- rename `pulsar_schema_del_ops_failed_count` to `pulsar_schema_del_ops_failed_total`
- rename `pulsar_schema_get_ops_failed_count` to `pulsar_schema_get_ops_failed_total`
- rename `pulsar_schema_put_ops_failed_count` to `pulsar_schema_put_ops_failed_total`
- rename `pulsar_schema_compatible_count ` to `pulsar_schema_compatible_total`
- rename `pulsar_schema_incompatible_count ` to `pulsar_schema_incompatible_total`
As mentioned above, the metrics name has changed
=> Rename Pulsar schema metrics to specify OpenMetrics

.asf.yaml
Notify discussions to dev@pulsar mailing list
Fixes #16275 
Make sure that GitHub Discussions are seen on the dev@pulsar mailing list.
Added the notifications section to `.asf.yaml` with the current setup from https://gitbox.apache.org/schemas.cgi?pulsar and then add a `discussions` section.
It's a repository configuration
=> Enable GitHub Discussions Notifications

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java, site2/docs/reference-metrics.md
See https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md
A COUNTER needs `metrics_name_total` or `metrics_name_created`
This PR contains metric name broken changes.
Rename counter's `_count` to `_total`
- rename `pulsar_lb_unload_broker_count` to `pulsar_lb_unload_broker_total`
- rename `pulsar_lb_unload_bundle_count` to `pulsar_lb_unload_bundle_total`
- rename `pulsar_lb_bundles_split_count` to `pulsar_lb_bundles_split_total`
As mentioned above, the metrics name has changed
=> Rename Pulsar lb metrics to specify OpenMetrics

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/proto/TransactionPendingAck.proto, pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java, pulsar-broker/src/test/resources/configurations/pulsar_broker_test.conf, pulsar-transaction/coordinator/src/main/proto/PulsarTransactionMetadata.proto, site2/website/versioned_docs/version-2.3.0/reference-configuration.md
see #15370
I will complete proposal #15370 with these pull requests( *current pull request is the step-2* ): 
1. Write the batch transaction log handler: `TxnLogBufferedWriter`
2. Configuration changes and protocol changes.
3. `MLPendingAckStore` and `MLTransactionLogImpl` support reading of batched logs.
4. `MLPendingAckStore` and `MLTransactionLogImpl` support the writing of batched logs and support dynamic configuration.
5. Append admin API for transaction batch log and docs( admin and configuration doc ).
6. Append metrics support for transaction batch log.
=> [improve] [txn] [PIP-160] Protocol changes and configuration changes for transaction batch log

.asf.yaml
I notice that GitHub Discussions activities aren't redirected to the mailing list and it's because the yaml section in a wrong indent level.
See also https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Notificationsettingsforrepositories.
=> Set notifications section with correct level

pom.xml
This suppresses the annoying waring about package-info.class file not found.
Reference:
* https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6960424
* https://github.com/checkstyle/checkstyle/pull/11663
=> [improve] Always generate package-info.class file

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
#10788
Updates to `bundlesCache` are asynchronous, Although we use `orderedExecutor`, there is no guarantee that the `bundlesCache` obtained when the split is executed is the latest. So when concurrent split bundles will happen `BadVersionException`.
Although it will retry when `BadVersionException` appears, the retry will be executed quickly and fail (because the `bundlesCache` has not been updated successfully), when the number of retries is exhausted(7 times), the unit test will be failed.
https://github.com/apache/pulsar/blob/c5ccc927ca62ed8911f805e8886b54a4f7fd0822/pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java#L900-L904
It can be seen from the log that when the number of retries is used up, the `bundleCache` is still old. …
=> [fix][broker] BadVersionException when splitting bundles, delay 100ms and try again.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/BundleSplitterTask.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/BundleSplitterTaskTest.java
The configuration loadBalancerNamespaceMaximumBundles is invalid.
example to illustrate:
1. Configure loadBalancerNamespaceMaximumBundles=128
1. The current number of bundles in the namespace is 120
2. According to the current logic, after executing the method findBundlesToSplit, 40 bundles may be found that need to be split;
3. After these bundles, the number of bundles in the namespace will become 120+40=160 > loadBalancerNamespaceMaximumBundles=128
modified logic：
1. When judging whether the number of bundles exceeds the configuration, it is necessary to add the already selected bundles：
(Docs have been already …
=> [fix][broker] The configuration loadBalancerNamespaceMaximumBundles is invalid

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/process/ProcessRuntimeTest.java
DnsResolverUtil fails to get existing DNS TTL settings. This happens in Java 17. 
This has been fixed for the pulsar-client and pulsar launcher scripts in #15349 and #15540
This PR is to do the same for the Runtime java command.
Detect the java version of the function worker and add the JVM flag `--add-opens java.base/sun.net=ALL-UNNAMED` if the version is 9+
fix
=> [fix][functions] Fix netty.DnsResolverUtil compat issue on JDK9+ for the function Runtimes

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/v1/V1_ProducerConsumerTest.java
Fixes #16667 #16673
Fix the consumer does not abide by the max unacks limitation.
The root cause is the dispatcher only cares about the flow permits while
dispatching messages but doesn't care if the dispatched messages
will exceed the max unacks limitation.
The issue is easy to reproduce if max_unacks < receiver_queue_size
Calculate the dispatch messages count for a consumer with
`max_unacks - unacks`
A new test added to verify the consumer will not receive
messages more than max unacks limitation
=> [fix][broker] Fix consumer does not abide by the max unacks limitation for Shared subscription

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
Fixes #16689 
Avoid ConcurrentModificationException for ModularLoadManagerImpl.cleanupDeadBrokersData()
The problem was introduced in https://github.com/apache/pulsar/pull/14411, so we don't need to cherry-pick to release branches.
Make a copy of knownBrokers.
=> [fix][broker] Avoid ConcurrentModificationException for ModularLoadManagerImpl.cleanupDeadBrokersData()

pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriter.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterTest.java
see #15370
In origin implementation, `TxnLogBufferedWriter` has two thread pools:
- `ExecutorService singleThreadExecutorForWrite` is A single-threaded actuator, used to perform Managed Ledger I/O operations. Includes the following tasks:
- `internalAsyncAddData` Each execution of the `asyncAddData` adds a task.
- `doFlush` The execution of `trigFlush` sometimes add a task, and there is also a scheduled task that adds tasks.
- `ScheduledExecutorService scheduledExecutorService` is used to periodically add `doFlush` tasks to the `singleThreadExecutorForWrite`, whether the `singleThreadExecutorForWrite` is idle or not.
If `singleThreadExecutorForWrite` is busy for a period of time, `scheduledExecutorService` will keep adding `doFlush` tasks during that period. Then …
=> [fix] [txn] [PIP-160] Avoid timing task burdens the ledger thread and leads to an avalanche

pom.xml
This fixes CVE-2022-31159. Failure reports at https://github.com/apache/pulsar/runs/7410813199?check_suite_focus=true.
- Dependencies (does it add or upgrade a dependency): (yes, to fix CVE)
=> [improve][security] Upgrade aws-java-sdk-s3 to 1.12.261

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicFactory.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java, site2/docs/reference-configuration.md
Users select the topic type based on the application use case and requirement of topic behavior. However, in some circumstances, users need some additional behavior on top of the existing implementation and even would like to inject custom workflow in existing topic behavior. Such special circumstances are mostly needed when users would like to do smooth migrations of topics or pulsar clusters without impacting producer and consumer applications. In such scenarios, users can override publish or dispatch behavior of the topic and plug in the additional workflow. For example: perform dual write on multiple topics while migration or, skip messages published from the specific source without explicit publish failures, ignore specific subscription source without generating a client-side error, …
=> [pulsar-broker] PIP-100 Support pluggable topic factory

pulsar-broker-common/src/main/java/org/apache/pulsar/common/configuration/PulsarConfigurationLoader.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyEncryptionPublishConsumeTest.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/CryptoKeyReaderFactory.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ProducerHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ReaderHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketProxyConfiguration.java, site2/docs/client-libraries-websocket.md
Websocket proxy can be used by user to deploy at client side to serve as a proxy between client app and broker. However, user also wants to enable encryption by publishing and consuming encrytepd messages. Therefore, user wants to enable encryption at websocket proxy which can encrypt publish/consume messages for user. So, we need encryption support at Websocket proxy which can use user-provided `CryptoKeyReader` implementation and load appropriate encryption keys to publish/consume encrypted message.
- Support configurable `CryptoKeyReaderFactory` at websocket proxy which can create `CryptoKeyReader` for websocket
- websocket producer supports encryption-keys to encrypt message
- websocket consumer supports message decryption
Websocket supports encryption/decryption for …
=> Support encryption in websocket proxy

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerImplTest.java
Add NamespacePolicies check before unload bundle when doLoadShedding.
When unload the broker,  It's better to guarantee there are at least one another broker can load the bundle which satisfy the NamespacePolicies. Otherwise the bundle may not load successfully or turn in the loop which unload from the current broker and load by the broker again cause the client reconnect frequently.
1. add NamespacePolicies check before unload bundle when doLoadShedding in ModularLoadManagerImpl.class.
2. add unit test.
=> [improve][broker]add NamespacePolicies check before unload bundle when doLoadShedding

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/AuthedAdminProxyHandlerTest.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/SuperUserAuthedAdminProxyHandlerTest.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/UnauthedAdminProxyHandlerTest.java
Fixes https://github.com/apache/pulsar/issues/15487
The proxy is configured to preserve the `Host` header when forwarding HTTP requests. However, I haven't found the necessity to do so, and this breaks the virtual host selection when running the proxy on istio.
See https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/proxy/AbstractProxyServlet.html
> By default the Host header sent to the server by this proxy servlet is the server's host name. However, this breaks redirects. Set preserveHost to true to make redirects working, although this may break server's virtual host selection.
This [doc](https://docs.oracle.com/cd/E49933_01/studio.320/studio_install/src/cidi_studio_reverse_proxy_preserve_host_headers.html) gives a brief introduction of how preserving the Host header would …
=> [proxy] Do not preserve host when forwarding admin requests.

bin/pulsar-shell, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/ConfigShell.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/JCommanderCompleter.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/PulsarShell.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/config/ConfigStore.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/config/FileConfigStore.java, pulsar-client-tools/src/main/java/org/apache/pulsar/shell/config/package-info.java, pulsar-client-tools/src/test/java/org/apache/pulsar/shell/ConfigShellTest.java, pulsar-client-tools/src/test/java/org/apache/pulsar/shell/JCommanderCompleterTest.java, pulsar-client-tools/src/test/java/org/apache/pulsar/shell/PulsarShellTest.java
Master Issue: #16250
A common case for Pulsar shell users is to have to manage multiple clusters. 
In order to handle multiple configurations a new concept of `config` is introduced. 
A config is a key-value object where key is a logical name and the value is a client.conf content.
You can now create many configs in the shell and they will be saved in your home directory ($HOME/.pulsar-shell/configs.json)
There's a `default` config which is the config you're passing to pulsar-shell (with `-c`).
The last used config will be used as first config for the new shell session. The info is stored in the json.
New root command: `config`
- config list: list all configs
- config view <configname>: show config value
- config create (--file|--url|--value) <file/url/base64:xx> <configname>: create a …
=> [feature][cli] Pulsar shell - configs to manage multiple clusters/tenants - part 4

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
Fix the managed ledger factory shutdown stuck due to scheduled executor shutdown first
```
2022-07-18T14:03:01,708 - ERROR - [main:MockedBookKeeperTestCase@107] - tearDown Error
java.util.concurrent.TimeoutException: null
at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?]
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?]
at org.apache.bookkeeper.test.MockedBookKeeperTestCase.tearDown(MockedBookKeeperTestCase.java:101) ~[test-classes/:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at …
```
=> [fix][broker] Fix the managed ledger factory shutdown stuck due to scheduled executor shutdown first

site2/website/sidebars.json
`sidebars.json` is broken, if you try to run the ´.start.sh´ command you get 
```
[ERROR] Sidebars file at "/Users/nicolo.boschi/dev/pulsar/site2/.preview/pulsar-site/site2/website-next/sidebars.js" failed to be loaded.
[ERROR] Loading of version failed for version current
[ERROR] SyntaxError: /Users/nicolo.boschi/dev/pulsar/site2/.preview/pulsar-site/site2/website-next/sidebars.json: Unexpected string in JSON at position 5924
```
Fix the json
=> [fix][doc] Fix sidebars.json syntax

pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/JdbcAbstractSink.java, pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/JdbcSinkConfig.java, site2/docs/io-jdbc-sink.md
Fixes #16291
Some JDBC connection (e.g clickhouse) doesn't support transactions, we can add a config for JdbcSinkConfig to avoid it
See:
```java
public void setAutoCommit(boolean autoCommit) throws SQLException {
if (!autoCommit) {
throw new SQLFeatureNotSupportedException("Transactions are not supported");
}
}
```
Add useTransactions config for JdbcSinkConfig, if `useTransactions = false` we do not set `autoCommit = false` and we do not use commit/rollback
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end …
=> [feature][pulsar-io] Support transactions for JDBC connector

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
A follow-up fix https://github.com/apache/pulsar/pull/16670
Update the test testMaxUnAckMessagesLowerThanPermits for support Shared and Key_Shared subscription
=> [fix][broker] Fix consumer does not abide by the max unacks limitation for Key_Shared subscription

pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedLedgerMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStoreProvider.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/InMemTransactionMetadataStoreProvider.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionLogImpl.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStore.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStoreProvider.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionSequenceIdGenerator.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnBatchedPositionImpl.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriter.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterConfig.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/MLTransactionMetadataStoreTest.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStoreProviderTest.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionLogImplTest.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/TxnBatchedPositionImplTest.java
see #15370
I will complete proposal #15370 with these pull requests( *current pull request is the step-3* ): 
1. Write the batch transaction log handler: `TxnLogBufferedWriter`
2. Configuration changes and protocol changes.
3. Transaction log store enables the batch feature.
4. Pending ack log store enables the batch feature.
5. Supports dynamic configuration.
6. Append admin API for transaction batch log and docs( admin and configuration doc ).
7. Append metrics support for transaction batch log.
=> [improve][txn] PIP-160: Transaction log store enables the batch feature

site2/docs/administration-geo.md, site2/website/versioned_docs/version-2.10.0/administration-geo.md
i try to enable the topic level geo-replication in my cluster,
when i execute `./pulsar-admin topics set-replication-clusters public/default/repl-test --clusters standalone,aliyun-test`, i got error:
```java
2022-07-19T09:05:09,444+0000 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/public/default/repl-test/replication] Failed to perform http post request: javax.ws.rs.NotAllowedException: HTTP 405 Topic level policies is disabled, to enable the topic level policy and retry.
Topic level policies is disabled, to enable the topic level policy and retry.
Reason: Topic level policies is disabled, to enable the topic level policy and retry.
```
after enable the topic error, try again, i got a `500` error:
``` …
```
=> [doc][improvement] enable geo-replication at topic level need extra config

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImpl.java
#16374  #16556 #16375 #16599
This is a bug, after [[PIP-145](https://github.com/apache/pulsar/pull/16062)],  `PatternMultiTopicsConsumer` can receive  `CommandWatchTopicUpdate` from broker to subscribe new topic.
But this topic name is with the partition index(case: public/default/test-topic-partition-0), This will produce unexpected behavior when executing the following subscribe method.
https://github.com/apache/pulsar/blob/9c93ab45af80dbeb116bfe9b63ff579ac4e22ce6/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L935-L942
The reasons for these failed unit tests are:
When the client receives the `CommandWatchTopicUpdate` command, it will enter the logic of processing non-partitions, then only process the …
=> [fix][client] Fix subscription topic name error.

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/DynamicSkipUnknownPropertyHandler.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/JsonMapperProvider.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/web/DynamicSkipUnknownPropertyHandlerTest.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminRestTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesV2Test.java
Master Issue: #16135
see #16135
I will complete proposal #16135 with these pull requests( *current pull request is the step-1* ): 
1. Add A Jackson component `DynamicSkipUnknownPropertyHandler` that supports dynamically policy of rejecting unknown parameters. Prints warn log when it receives an unknown parameter.
2. Dynamic configuration.
=> [improve] [admin] [PIP-179] Support the admin API to check unknown request parameters

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
* Fix `org.apache.pulsar.client.impl.ClientCnx#newLookup` throw `TooManyRequestsException` message
* Changing `pendingLookupRequestSemaphore.availablePermits()` to `pendingLookupRequestSemaphore.getQueueLength()`
=> [fix][client]Fix newLookup TooManyRequestsException message

site2/docs/reference-configuration.md, site2/website/versioned_docs/version-2.3.0/reference-configuration.md
Doc of transaction batch incorrectly written in version 2.3.
Move the new doc to master
=> [improve] [txn] [PIP-160] Fix wrong doc(new doc is incorrectly written in version 2.3)

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Reader.java
There are many timestamp formats, we need to specify the required timestamp format for the seek method of the Consumer and Reader.
* Add a description requiring the timestamp format should be Unix Time in milliseconds for the seek method of the Consumer and Reader.
=> [doc][client] Add timestamp format description for seek method of the Consumer and Reader.

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerBkTest.java
Fixes #16729
Master Issue: #16729
Close `cursor` after cursor delete position.
=> [fix][tests]Fix Flaky-test: ManagedLedgerBkTest.asyncMarkDeleteAndClose.

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/MultiRolesTokenAuthorizationProvider.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiRolesTokenAuthorizationProviderTest.java
Fixes #16574 
The `MultiRolesTokenAuthorizationProvider` cannot handle the superuser and tenant admin correctly. It only checks if the role passed in is a superuser, which is incorrect. The correct way is to get a role list from authentication data and then check if the role list contains a superuser.
- Override the `isSuperAdmin`
- Override the `validateTenantAdminAccess`
- Add test for the `MultiRolesTokenAuthorizationProvider`
=> [fix][authorization] Fix multiple roles authorization

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
defaultOffloader will use offloaderStats, it should create after offloaderStats be override.
=> [fix] [broker] Make defaultOffloader create after offloaderStats overrides.

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
Fixes #16733 
This is a flaky test, which looks have the incorrect condition.
=> [fix][flaky-test] Fix BacklogQuotaManagerTest.testConsumerBacklogEvictionTimeQuotaWithEmptyLedge

pulsar-io/common/src/main/java/org/apache/pulsar/io/common/IOConfigUtils.java, pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistory.java, pulsar-io/debezium/core/src/test/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistoryTest.java, pulsar-io/kafka-connect-adaptor/pom.xml, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaWorkerConfig.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStore.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStoreTest.java
Fixes #16674
Allow user customize the reader configs in pulsar-io-debezium and pulsar-io-kafka-connect-adaptor.
- add `offset.storage.reader.config` to `PulsarKafkaWorkerConfig`
- add `pulsar.reader.config` to `PulsarDatabaseHistory`
- add utils to pulsar-io-common
- add pulsar-io-common dependency to pulsar-io-kafka-connect-adaptor
- add tests
*(or)*
*(or)*
*(example:)*
*If `yes` was …
=> [improve][connector] add reader config to `pulsar-io-debezium` and `pulsar-io-kafka-connect-adaptor`

pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedLedgerMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStoreProvider.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/InMemTransactionMetadataStoreProvider.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionLogImpl.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStoreProvider.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriter.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/MLTransactionMetadataStoreTest.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStoreProviderTest.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionLogImplTest.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterTest.java
see #15370
In the original design of the transaction buffered writer, we use a scheduled executor to execute timed tasks. There are no scheduled executors that match this scenario, and It's a little expensive to have a new scheduled executor with 1 millis tick time.
The `PulsarService.brokerClientSharedTimer` is very match to this scenario, so we should reuse it instead to create a new scheduled executor.
So we should make transaction buffered writer supports `io.netty.Timer`.
=> [improve][txn] PIP-160: Transaction buffered writer supports Timer

tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
Related to https://github.com/apache/pulsar/issues/15392 
Add logs to help troubleshoot flaky test https://github.com/apache/pulsar/issues/15392 
=> [improve][test] Print topic stats and internal-stats if cannot receive message in 30s for Function Test

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaSourceConfig.java, pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java
Fixes [#97](https://github.com/streamnative/cloud-support-tickets/issues/97)
Unable to create a Kafka source connector with the UI.
Enable [ACCEPT_EMPTY_STRING_AS_NULL_OBJECT](https://fasterxml.github.io/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/DeserializationFeature.html#ACCEPT_EMPTY_STRING_AS_NULL_OBJECT) when load KafkaSourceConfig from map.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after broker …
=> [fix][connector] Fixed kafka source config for `pulsar-io-kafka` when `consumerConfigProperties`=""

site2/docs/client-libraries-node.md, site2/docs/client-libraries-python.md
The documentation for end-to-end encryption says that producer and consumer need both public and private keys.
However, it is sufficient to set the public key for producer and the private key for consumer.
- fix description
- improve code in tutorial
=> [improve][doc] improve descriptions of configuring end-to-end encryption for Python and Node.js Client

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClient.java
Currently, the ES sink doesn't show any error when any record in a bulk write fails, and the failure may persist until the developer fixed the issue.
Add a warning log when any record in bulk write fails. …
=> [improve][es-sink] Add error log for failed bulk records in ES sink

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java
Server side filters may be very heavy weight, and currently they are running (very often) in the same thread that handles writes and also all the subscriptions.
We want to improve performances in presence of heavy server side filters:
- subscriptions should not impact each other
- dispatching should not impact writes
Add a new flag, `dispatcherDispatchMessagesInSubscriptionThread`, enabled by default, to dispatch messages to consumers in a Shared subscription using a separate thread than the BK executor thread.
With this patch we choose a thread depending on the topic + subscription name and we run the actual dispatching of messages (sendMessagesToConsumers) in such thread.
I did some manual testing with a dummy filter that slows down (Thread.sleep(100)) consumption and even with a simply …
=> [enh] Broker - Shared subscription: run filters in a separate (per-subscription) thread (dispatcherDispatchMessagesInSubscriptionThread)

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderToken.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderTokenTest.java
Fixes #16626 
A scenario that running the standalone Pulsar with WebSocket service, then using the `token` request param in a WebSocket URL gives an unauthorized response, it seems is not working as intended in the [documentation](https://pulsar.apache.org/docs/client-libraries-websocket/#query-param-1), but it works using a separate WebSocket service.
The root cause is that we did not check whether the token is in the HTTP parameters.
- Add `HttpServletRequestWrapper` to support for get token from HTTP params
- Add a test for this changes
=> [improve][authentication] Support for get token from HTTP params

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Chery-pick https://github.com/apache/pulsar/pull/16355 to fix the following issue:
```
Message: null
Stacktrace:
java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.getTopicReference(PersistentTopicsBase.java:4085)
at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalResetCursorForNonPartitionedTopic(PersistentTopicsBase.java:2135)
at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalResetCursor$156(PersistentTopicsBase.java:2112)
at …
```
=> [branch-2.10][improve][broker][PIP-149] Make resetCursor async (#16355)

pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSet.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMap.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSet.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMapTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMapTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSetTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMapTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSetTest.java
Optimize concurrent collection's shrink and clear logic.
This PR was releated to bookkeeper's PR：https://github.com/apache/bookkeeper/pull/3417
1. Reduce the repeated `Arrays.fill` in the clear process
2. When `capacity` is already equal to `initCapacity`,`rehash` should not be executed
3. Reduce the `rehash` logic in the `clear` process
4. Shrinking must at least ensure `initCapacity`, so as to avoid frequent shrinking and expansion near `initCapacity`, frequent shrinking and expansion, additionally opened `arrays` will consume more memory and affect GC.
=> Optimize concurrent collection's shrink logic

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/UnrecognizedPropertyExceptionMapper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminRestTest.java, site2/docs/reference-configuration.md
Master Issue: #16135
see #16135
I will complete proposal #16135 with these pull requests( *current pull request is the step-2* ): 
1. Add A Jackson component `DynamicSkipUnknownPropertyHandler` that supports dynamically policy of rejecting unknown parameters. Prints warn log when it receives an unknown parameter.
2. Dynamic configuration.
=> [improve] [admin] [PIP-179] Dynamic configuration for check unknown request parameters

pulsar-common/src/main/java/org/apache/pulsar/common/util/FutureUtil.java
=> [branch-2.9]Add back FutureUtil#waitForAll and FutureUtil#waitForAny methods with List parameter

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
* Fix https://github.com/apache/pulsar/issues/16665
* The root cause is that: When we called `ManagedLedgerImpl#updateLedgersIdsComplete` -> `OpAddEntry#initiate`, and then If `ledger.asyncAddEntry`(L140) callback successfully, the `OpAddEntry` state will be `COMPLETED` instead of `INITIATED`
https://github.com/apache/pulsar/blob/a1b8476e40b6a40e82062915d13e4dc9d7dff9cb/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java#L125-L140
* Fix https://github.com/apache/pulsar/issues/16665
=> [fix][test]Fix ManagedLedgerTest#avoidUseSameOpAddEntryBetweenDifferentLedger

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
Fixes #16661
*fix stats-internal with option -m can cause active ledger recover then close*
*ManagedLedgerImpl.getLedgerMetadata doesn't call getLedgerHandle from ledgerCache directly, it will use ManagedLedgerImpl.currentLedger if the ledger id is ManagedLedgerImpl.currentLedger*
get newest ledgerid of ManagedLedgerImpl and call getLedgerMetadata with this ledgerid. Then validate ledgerCache donot contain this ledgerid. …
=> fix stats-internal with option -m cause active ledger recover then close

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
=> [improve][broker] make some methods async in Namespaces

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedderTest.java
According to the current logic, if the number of bundles on a broker is 0, the broker will not participate in bundle allocation, so that the newly started broker will not be allocated to the bundle:
https://github.com/apache/pulsar/blob/da325fa64399642700d35b7d538a92b65c604bf5/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java#L78-L82
=> [fix][broker] Fixed that newly added brokers cannot be assigned bundles for UniformLoadShedder

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicStreamingDispatcherTest.java
Fixes: https://github.com/apache/pulsar/issues/16666
Try add the `@BeforeMethod(alwaysRun = true)` to fix the `PersistentTopicStreamingDispatcherTest`.
=> [fix][flaky-test] Fix PersistentTopicStreamingDispatcherTest

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/PositionImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStore.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckMetadataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreTest.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriter.java
see #15370
I will complete proposal #15370 with these pull requests( *current pull request is the step-4* ): 
1. Write the batch transaction log handler: `TxnLogBufferedWriter`
2. Configuration changes and protocol changes.
3. Transaction log store enables the batch feature.
4. Pending ack log store enables the batch feature.
5. Supports dynamic configuration.
6. Append admin API for transaction batch log and docs( admin and configuration doc ).
7. Append metrics support for transaction batch log.
=> [improve][txn] PIP-160: Pending ack log store enables the batch feature

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
When running `bin/bookkeeper shell cookie_update` command, we get the following exception.
```
$ bin/bookkeeper shell cookie_update -h
JMX enabled by default
Exception in thread "main" java.lang.NoSuchMethodError: com.beust.jcommander.JCommander.usage(Ljava/lang/StringBuilder;)V
at org.apache.bookkeeper.tools.framework.Cli.setupCli(Cli.java:142)
at org.apache.bookkeeper.tools.framework.Cli.<init>(Cli.java:53)
at org.apache.bookkeeper.tools.framework.Cli.runCli(Cli.java:243)
at org.apache.bookkeeper.tools.common.BKCommand.apply(BKCommand.java:64)
at org.apache.bookkeeper.tools.cli.helpers.BookieShellCommand.runCmd(BookieShellCommand.java:46)
at org.apache.bookkeeper.bookie.BookieShell.run(BookieShell.java:2235)
at org.apache.bookkeeper.bookie.BookieShell.main(BookieShell.java:2326)
```
The …
=> [branch-2.7] Upgrade the BookKeeper version to 4.12.1

pulsar-broker/src/test/java/org/apache/pulsar/client/api/PartitionedProducerConsumerTest.java
Fixes #16710
Master Issue: #16710
When the partition updates, the internal consumer may not connect to the broker(you can see `onPartitionsChange ` is before `startReceivingMessages`), so `unsubscribe` will throw the exception.
https://github.com/apache/pulsar/blob/bdd87794a0ad6a775a911e9cb27cf6fbaf02d9e8/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L1415-L1425
PartitionedProducerConsumerTest#testPartitionedTopicInterceptor tests for updating the partition, another way to fix is that deleting `consumer.unsubscribe()` at line 1029.
=> [fix][tests] Fix Flaky-test: PartitionedProducerConsumerTest.testPartitionedTopicInterceptor

conf/client.conf, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestRunMain.java, site2/docs/reference-configuration.md, site2/website/versioned_docs/version-2.10.1/reference-configuration.md, site2/website/versioned_docs/version-2.8.3/reference-configuration.md, site2/website/versioned_docs/version-2.9.3/reference-configuration.md
The `pulsar-admin` doesn't support setting the TLS provider. 
Default to OpenSSL implement, which doesn't support the switch to JDK implement, now we add support for this.
- Add `webserviceTlsProvider` to `client.conf` file
- Add setting the TLS provider in `PulsarAdminTool.java`
Add setting the `webserviceTlsProvider` to `reference-configuration#client` section.
=> [improve][admin-cli] Add TLS provider support

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ConsumerStats.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/ConsumerStatsImpl.java
Expose the last consumed flow timestamp for consumer stats.
Currently, we only have `lastConsumedFlowTimestamp` for the subscription.
If a subscription has multiple consumers or the consumers sent flow permits are disconnected.
It is not able to know if the active consumer has sent the flow permits or not.
=> [improve][admin] Expose the last consumed flow timestamp for consumer stats

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
Avoid IllegalStateException while client_version is not set
```
[pod/prod-broker-1/pulsar-broker] 2022-07-25T07:56:43.083238692Z 2022-07-25T07:56:43,082+0000 [pulsar-io-4-1] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.80.10.151:48010] Unable to handleAuthResponse
[pod/prod-broker-1/pulsar-broker] 2022-07-25T07:56:43.083275432Z java.lang.IllegalStateException: Field 'client_version' is not set
[pod/prod-broker-1/pulsar-broker] 2022-07-25T07:56:43.083278245Z        at org.apache.pulsar.common.api.proto.CommandAuthResponse.getClientVersion(CommandAuthResponse.java:16) ~[io.streamnative-pulsar-common-2.9.2.18.jar:2.9.2.18]
[pod/prod-broker-1/pulsar-broker] 2022-07-25T07:56:43.083281031Z        at org.apache.pulsar.broker.service.ServerCnx.handleAuthResponse(ServerCnx.java:899) …
```
=> [fix][broker] Avoid IllegalStateException while client_version is not set

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
see #15051
There have conflicts when cherry-picking #15051 PR (branch 2.8 has no `mock static` support), so I created a separate PR to fix branch-2.8
Swap the execution order of duplicate validation and maximum validation
=> [fix][broker][branch-2.8] Fix potential to add duplicated consumer

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java
Changes: sendMessagesToConsumer must block reads of new entries otherwise we will end up in reading duplicates
Fixes #16802 #16693
As described in #16802 it may happen that multiple calls to `readMoreEntries` are served before the execution of `sendMessagesToConsumer`
Unfortunately there is no control over the execution of `readMoreEntries`, it may happen in many different threadpools
Add a flag to prevent concurrent execution of `sendMessagesToConsumer` with `readMoreEntries`.
Revert aa change to a test modified in #16802 to make the test pass
This change is already covered by existing tests
=> Issue 16802: fix Repeated messages of shared dispatcher

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java
We collect metrics on storage read/write rate, but we do not expose it at the topic level. We already expose it at the namespace level.
* Expose `pulsar_storage_read_rate` and `pulsar_storage_write_rate` in topic level metrics
This change adds two new metrics.
These two metrics are already documented for topic level stats: https://pulsar.apache.org/docs/next/reference-metrics.
=> [Broker] Expose topic level storage write and read rate metrics

site2/docs/client-libraries-python.md
zsh throws `zsh: no matches found: pulsar-client[all]==2.10.0` if we don't quote `[all]`.
... also remove extra blank lines and add missing language options for code block.
cc @momo-jun @Anonymitaet @BewareMyPower
=> [improve][doc] Quote package name to adapt zsh

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerMemoryLimitTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
release memory usage when invalid message.
Only need to release memory usage here, no need to release semaphore. Both add testcases.
coauthored by @pengxiangrui127.
- add unit tests for this change
bug fix, no need doc
=> Forget to update memory usage when invalid message

conf/broker.conf, deployment/terraform-ansible/templates/broker.conf, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerFactoryConfig.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheManagerTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/ManagedLedgerClientFactory.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/ConsumerRedeliveryTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/PartitionCreationTest.java
Current the `cacheEvictionTask` https://github.com/apache/pulsar/blob/4532c15ea705d7b88274025beb1c4913e5069d64/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java#L255
will be executed periodically, the period is calculated by 
```java
double evictionFrequency = Math.max(Math.min(config.getCacheEvictionFrequency(), 1000.0), 0.001);
long waitTimeMillis = (long) (1000 / evictionFrequency);
```
And this task will be executed once and then sleep `waitTimeMillis` before the next round.
We can do some optimizes for this logic.
1. Set the cache eviction task interval directly by addint a new configuration `managedLedgerCacheEvictionIntervalMs`
2. use a `ScheduledExecutorService` to execute the cache eviction task every …
=> [improve][broker] refactor ManagedLedger cacheEvictionTask implement

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
Fixes: #16711
If the meta-ledger fails to be initialized when mark delete is executed, the callback of mark delete will not execute anymore. this case will occur in 1/1000 probability. You can reproduce it by doing this: "Run unit test `ManagedCursorTest.markDeleteWithZKErrors` 1000 times".
This problem also makes unit test `ManagedCursorTest.markDeleteWithZKErrors` flaky. #16711
When the problem occurs, the actual execution process is as follows:
| Time | `cursor mark deleted` | `meta thread` |
| -----------  | ----------- | ----------- |
| 1 | synchronized `pendingMarkDeleteOps` | |
| 2 | check meta-ledger state | |
| 3 | do create ledger |  |
| 4 | append to pending requests queue  |  |
| 4 |  | synchronized `pendingMarkDeleteOps`( <strong>High light</strong> ) |
| 5 |  | create ledger …
=> [fix][broker] ManagedCursor: mark delete no callback when create meta-ledger fail

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java
Add dynamic configuration to UniformLoadShedder.
=> [improve][broker] Add dynamic configuration for UniformLoadShedder

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedderTest.java
In order to control the number of unloaded bundles more accurately each time, the configuration maxUnloadBundleNumPerShedding is added.
The purpose of adding this configuration is to control the number of bundles unloaded at one time, and prevent too many bundles unloaded at one time, resulting in cluster instability.
=> [feature][broker] add config maxUnloadBundleNumPerShedding for UniformLoadShedder

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientAuthenticationTlsTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/SecurityUtility.java
Currently, the Pulsar client requires config the trust certificate. When we use certificates issued by public CA, we do not need to configure the trust certificate.
- Add check whether the trust certificate is configured
=> [fix][client] Fix load trust certificate

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyConnectionTest.java
When the TLS is enabled, the client always uses the non-TLS URL.
- Add check whether using the TLS URL
=> [fix][proxy] Fix client service url

pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java, pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMappingTest.java
The `BookieRackAffinityMapping` class relies on a metadata cache that expires entries after 10 minutes. When an entry expires, the next call to `BookieRackAffinityMapping#getRack` returns an incomplete future (because the entry expired) and the `TopologyAwareEnsemblePlacementPolicy` (bookkeeper class) stores the bookie's network location as `default-rack`.
It is trivial to reproduce the issue. Start a Pulsar cluster, define a rack topology, wait for at least 10 minutes, kill one of the bookies that is not in the default-rack, and observe the broker logs as the bookie comes back. The broker will log that the bookie is a member of the default-rack. When `bookkeeperClientEnforceMinNumRacksPerWriteQuorum` is enabled in the broker, this bug becomes a blocking issue where the only way to …
=> Fix rack awareness cache expiration data race

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Subscription properties are a new feature coming in 2.11. The admin api will allow for properties with commas, but the admin cli tool splits parameters with commas into multiple properties. This PR switches the splitter for the `properties` field and makes it possible to specify any valid property with the cli tool.
Note: there are other properties fields that the CLI tool allows you to set, but because those have already been released, I am not updating those here.
* Use the `NoSplitter.class` as the `splitter` for the subscription `properties` parameter.
* Add test coverage for all changes.
This PR includes new test coverage.
This PR updates a CLI tool method that has not yet been released, so it does not break any existing functionality.
=> [Pulsar Admin CLI Tool] Use NoSplitter for subscription properties

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
Fixes #16839
When `PatternTopicsChangedListener#onTopicsRemoved` triggered,  `removeConsumerAsync` will throw ClassCastException.
When ackTimeoutMillis = 0 (default value), `unAckedMessageTracker` is created with `UnAckedMessageTracker.UNACKED_MESSAGE_TRACKER_DISABLED`
=> [Java Client] fix PatternTopicsChangedListener blocked when topic removed

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientErrorsTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, site2/docs/developing-binary-protocol.md
Related: https://github.com/apache/pulsar/pull/13161 and https://github.com/apache/pulsar/pull/12948
The current Java Client consumer code does not clean up a pending consumer on the server when the client's timeout expires. This creates problems when the client tries to recreate the consumer with a `Subscribe` command. In this case, we see warnings like the following:
>2022-07-13T23:51:53,323+0000 [pulsar-io-12-6] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.249.212.73:41536][persistent://public/default/test][test] Consumer with id is already present on the connection, consumerId=66
* Send `CloseConsumer` command when the `Subscribe` command times out from the client perspective.
This change includes new tests.
This change introduces new recommendation for the Pulsar Protocol, …
=> [Java Client] Send CloseConsumer on client timeout

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerMemoryLimitTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Fix client memory limit `currentUsage` leak in `ProducerImpl`. When our pulsar cluster occur some error,  producer send message fail and we find the `currentUsage` always  keep high value like the leaked, and cause the producer send rate is slow.
And find producer semaphore release duplicated when `createOpSendMsg`  occur some excrption.
Follow 1 point only release the message count semaphore, but not release the memory limit.
**memory limit currentUsage leak point**
https://github.com/apache/pulsar/blob/c217b8f559292fd34c6a4fb4b30aab213720d962/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L2031-L2033
**producer semaphore release duplicated**
https://github.com/apache/pulsar/blob/4d64e2e66689381ebbb94fbfc03eb4e1dfba0405/pulsar-client/src/main/java/org/apache/p …
=> [fix][client]Fix client memory limit currentUsage leak and semaphore release duplicated in ProducerImpl

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java
In the implementation of the function framework, assignments are updated asynchronously to each worker.  When restarting the function, there may be some work in an assignment that does not exist.  This scenario should be printed warn log to the broker.
- When restart function, if assigned work does not exist, print warn log.
=> [improve][function] When restart function, if assigned work does not exist, print warn log.

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdProduce.java
Fix a misleading (incorrect) description for the `--message` parameter of the `pulsar-client produce` command. The description currently states that messages can be comma delimited. However, the splitter on the field is `NoSplitter`, and that means different messages need to be passed as different arguments (e.g. `-m message1 -m message2`).
* Update description.
This is a documentation update.
This is not a breaking change. It simply makes the documentation align with the implementation.
=> [Pulsar Client CLI] Fix incorrect description for producing messages

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Cherry pick #14269 to branch 2.7
When Rest API call `AdminResource#validateGlobalNamespaceOwnership`, broker will execute `PulsarWebResource#checkLocalOrGetPeerReplicationCluster`.
In `PulsarWebResource#checkLocalOrGetPeerReplicationCluster`:
https://github.com/apache/pulsar/blob/6d717a08ef8cfcac032caee06105285594baf09f/pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java#L773-L802
Line 780, 794, and 801 has thrown RestException.
But `validateGlobalNamespaceOwnership ` has wrapped the exception :
https://github.com/apache/pulsar/blob/6d717a08ef8cfcac032caee06105285594baf09f/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java#L202-L216
This could make the user confused that the log printed is not matched with the REST API.
- Add a …
=> [Branch 2.7] Fix validateGlobalNamespaceOwnership wrap exception issue.

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/DynamicReceiverQueueSizeTest.java
#16879 
When `MultiTopicConsumer` is incomingMessages is full, does not mean that all of its `consumers` is `AvailablePermits` must be 0.
The reason the current test sometimes passes is because, it just so happens that all consumer suspended after the last permit request was sent.
- Delete assert availablePermits on testmulitiConsumeImpl
=> [fix][flaky-test] Delete assert availablePermits on testmulitiConsumeImpl

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
The origin PR #12484 is merged into branch 2.7, but reverted in #16882 because Unit test `BrokerBookieIsolationTest#testBookieIsilationWithSecondaryGroup` fails.
The root cause is that `policies` and `localPolicies` are not updated after they are read from async process.
1. Cherry-pick PR #12484
2. Change `optPolicies, optLocalPolicies` to `policies, localPolicies` in 
https://github.com/merlimat/pulsar/blob/f53ddc13d7fb28f4c1bd73b23e7f3d8b7fc35591/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1209
This change is already covered by existing tests, such as BrokerBookieIsolationTest#testBookieIsilationWithSecondaryGroup 
bug fix.
=> [Branch-2.7] Fixed deadlock on metadata cache missing while doing checkReplication

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
See #14365 
Make some methods async in `Namespaces`.
=> [improve][broker][PIP-149]make some police methods async in Namespaces

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerStrategyTest.java
Avoid the bestBroker choice broker exceed candidates when selectBroker in LeastResourceUsageWithWeight.
When loadManager leader running a period of time,   `brokerAvgResourceUsageWithWeight` will contain almost all brokers, the judge will cause we selected broker exceed candidates, it's out of expectation.
1. check if `candidates` contain the broker before add the broker to `bestBrokers`.
=> [fix][broker]avoid the bestBroker choice broker exceed candidates when selectBroker in LeastResourceUsageWithWeight

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java
Fix the zero value as denominator when after `applyNamespacePolicies`  the `candidates` is empty,  then `selectBroker` use `LeastResourceUsageWithWeight`, which will cause `ArithmeticException`
**the cause exception point** 
https://github.com/apache/pulsar/blob/9f7021909486ac97590b17a6c245367900ab989c/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java#L138
1. add  `candidates` empty check;
2. after add `candidates` empty check, remove some unused check;
=> [fix][broker]fix the zero value as denominator cause ArithmeticException when selectBroker use LeastResourceUsageWithWeight

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyConnectionTest.java
Cherry-pick #16834 to branch 2.7
Direct cherry-pick causing compile error in `ProxyConnectionTest#testCreateClientConfiguration`
- Cherry-pick #16834 to branch 2.7
- Add `throws PulsarClientException.UnsupportedAuthenticationException` for `ProxyConnectionTest#testCreateClientConfiguration`
=> [Branch 2.7][fix][proxy] Fix client service url

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationDataHttps.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderToken.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderTokenTest.java
Cherry pick the https://github.com/apache/pulsar/pull/16871.
=> [improve][authentication][branch-2.7] Support for get token from HTTP params

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE, pulsar-sql/presto-distribution/pom.xml
Cherry-pick #11790 to branch 2.7
After directly cherry-pick #11790 , there is a license check issue:
> aircompressor-0.16.jar unaccounted for in lib/presto/LICENSE
The root cause is that in branch 2.7, pulsar-presto-distribution is not a child of Pulsar main project. So the version changes in main pom.xml is not applied to lib/presto/LICENSE.
1. Cherry-pick #11790 to branch 2.7
2. Add dependency of aircompressor-0.20 in pulsar-sql/presto-distribution/pom.xml.
This change is already covered by existing tests, such as CI license check.
bug fix
=> [Branch 2.7] upgrade aircompressor to 0.20

bin/pulsar, pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java, pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandaloneStarter.java
Fixes #16800
The -c option offered in the standalone is missleading.
An error occurs when passing --config to the pulsar standalone:
```
2022-07-26T15:11:40,180+0200 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Can only specify option -c once.
```
* Add `-Dpulsar.config.file` to specify the pulsar standalone config file
* The priority for config file loading: using `-c or --config` > using `-Dpulsar.config.file`
* Fix the standalone still execute after the argument check fails.
This PR will not change the existing behavior.
Execute `bin/pulsar standalone` and `bin/pulsar standalone -c {your-config-file}` to verify this change.
(Your …
=> [fix][broker] Fix misleading -c option in pulsar standalone

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/BaseResources.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/PulsarResources.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TopicResources.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/SystemTopicNames.java
(cherry picked from commit 2a7a8555c0b0296bcaa6a757a8646b8f65185ac6)
In addition to https://github.com/apache/pulsar/pull/16043, this PR fixes https://github.com/apache/pulsar/issues/16861
=> [branch-2.8][improve][broker] Avoid reconnection when a partitioned topic was created concurrently (#16043)

pulsar-io/common/src/main/java/org/apache/pulsar/io/common/IOConfigUtils.java, pulsar-io/common/src/test/java/org/apache/pulsar/io/common/IOConfigUtilsTest.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSinkConfig.java
Currently, `FieldDoc` annotation has `required` and `defaultValue` config. But `IOConfigUtils` didn't deal with those.
The connector we implemented deserialized the configuration using `IOConfigUtils.loadWithSecrets()`
- IOConfigUtils support required and defaultValue annotations.
=> [fix][connector]IOConfigUtils support required and defaultValue annotations.

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/AdminApiKeyStoreTlsAuthTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/PulsarAdminBuilder.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java
This PR is the similar to #15634, supports this feature on the broker.
- Add broker config
- JKS
- brokerClientTlsKeyStoreType
- brokerClientTlsKeyStore
- brokerClientTlsKeyStorePassword
- CAcerts
- brokerClientKeyFilePath
- brokerClientCertificateFilePath
- Split TLS transport encryption support from authentication on the `PulsarAdmin`
Update all TLS related documents.
=> [improve][broker] Split TLS transport encryption support from authentication

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/EntryAndMetadata.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSender.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SharedConsumerAssignor.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SharedConsumerAssignorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageChunkingSharedTest.java, pulsar-client-cpp/lib/ConsumerImpl.cc, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
https://github.com/apache/pulsar/wiki/PIP-37%3A-Large-message-size-handling-in-Pulsar#option-1-broker-caches-mapping-of-message-uuid-and-consumerid
The cons of option 1 described in the original proposal don't exist
for current code because broker keeps redelivered messages into
**sorted** map now.
First of all, to avoid too many code changes, an `EntryAndMetadata`
class is introduced to bind the `Entry` with the associated
`MessageMetadata` to avoid parsing the metadata repeatedly. It also
implements the `Entry` interface, so this PR changes some
`List<Entry>` parameters to `List<? extends Entry>` so that a
`List<EntryAndMetadata>` argument can be accepted.
Then, a `SharedConsumerAssignor` is introduced to assign a list of
entries to all shared consumers.
1. Use a default selector to …
=> [feature][broker] PIP 37: Support chunking with Shared subscription

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, pom.xml
(cherry picked from commit 6cec62e89629c258f9458a726ff8ba3b644788b7)
Compared to #16399, this PR uses PowerMock instead of mockito because
the branch-2.8 doesn't import the `mockito-inline` dependency.
=> [branch-2.8][improve][broker] Recycle OpReadEntry in some corner cases (#16399)

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/BaseResources.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TenantResources.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
(cherry picked from commit 6af365e36aed74e95ca6e088f453d9513094bb36)
Besides resolving the basic conflicts, this PR
- migrate `validateAdminAccessForTenantAsync` from #14149
- migrate `TenantResources#getTenantAsync` from #11693
=> [branch-2.8][fix][security] Add timeout of sync methods and avoid call sync method for AuthoriationService (#15694)

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdGenerateDocument.java
Fixes #12381
Please check out the original issue.
Add `#language` tags in parameter descriptions in `CmdFunctions` so that `CmdGenerateDocument` can generate a new language support column. Works with apache/pulsar-site#154.
Only adjusted existing generation command.
(Docs have been already …
=> [feature][doc] Show language support for pulsar-admin functions flags

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
This PR is part of work of cherry-pick #12340 to branch 2.7
There is a concurrent issue when updating namespace TTL, causing `AdminApiTest#testTopicStatsLastExpireTimestampForSubscription` fails periodically.
The root cause is that in `NamespacesBase#internalSetNamespaceMessageTTL`:
- Step A, we write new namespace policy data to zk
- Step B, we call `policiesCache().invalidate` to disable the cache.
But between Step A and B, `ZooKeeperDataCache` will receive a data change event, and new data of `policiesCache` will be reloaded in `ZooKeeperDataCache#reloadCache`. So this reloaded data will invalidated in Step B. 
And in `PersistentTopic#onPoliciesUpdate` (triggered by Step A) won't be able to get policy data with `policiesCache().getDataIfPresent`, so `checkMessageExpiry` is skipped and …
=> [Branch 2.7] Avoid potentially blocking calls to metadata in PersistentTopic#getMessageTTL

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBookies.java, pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZkBookieRackAffinityMapping.java, pulsar-zookeeper-utils/src/test/java/org/apache/pulsar/zookeeper/ZkBookieRackAffinityMappingTest.java
Cherry-pick #13683 to branch 2.7
When user set rack name to `/` or empty string `""`, it will cause all matched bookies join target rack failed and throw the following exception
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1841) ~[?:?]
at org.apache.bookkeeper.net.NetworkTopologyImpl$InnerNode.getNextAncestorName(NetworkTopologyImpl.java:144) ~[io.streamnative-bookkeeper-server-4.14.3.1.jar:4.14.3.1]
at org.apache.bookkeeper.net.NetworkTopologyImpl$InnerNode.add(NetworkTopologyImpl.java:180) ~[io.streamnative-bookkeeper-server-4.14.3.1.jar:4.14.3.1]
at org.apache.bookkeeper.net.NetworkTopologyImpl.add(NetworkTopologyImpl.java:425) ~[io.streamnative-bookkeeper-server-4.14.3.1.jar:4.14.3.1]
at …
```
=> [Branch 2.7] Fix invalid rack name cause bookie join rack failed

pulsar-client-cpp/lib/ConsumerImpl.cc, pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc, pulsar-client-cpp/lib/PartitionedConsumerImpl.cc, pulsar-client-cpp/tests/ConsumerTest.cc
Fixes #16567 
When PartitionedConsumer is closed, it forgets to close `messages_` leading to the PartitionedConsumer blocking operations can't be interrupted.
Also, we should return `ResultAlreadyClosed` rather than `ResultTimeout` when `state_ != Ready` after `message_.pop()` failed.
* Close `messages_` when PartitionedConsumer is closed.
* Return `ResultAlreadyClosed` when `state_ != Ready` after `message_.pop()` failed.
This change is already covered by existing tests, such as *testPartitionsWithCloseUnblock*.
- The rest …
=> [fix][client-c++] Close `messages_` when PartitionedConsumer is closed

pulsar-broker/src/test/java/org/apache/pulsar/broker/EndToEndMetadataTest.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BKCluster.java
Fixes #16846
The dataDir conflict when starting multiple bookies in the BKCluster.
Add index suffix for per bookie dataDir.
This change is already covered by existing tests, such as *EndToEndMetadataTest.java*.
=> [improve][broker] Support start multiple bookies for BKCluster

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionLocalRunTest.java
Fixes #16753
When `functionConfig.parallelism > 1`, should set `functionConfig.RetainOrdering=true` to ensure process data in the same order as in the input topics.
set `functionConfig.RetainOrdering=true`.
=> [fix][flaky-test]: PulsarFunctionLocalRunTest.testE2EPulsarFunctionLocalRunMultipleInstances

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java
Fixes #9919
Master Issue: #9919
This problem was marked as resolved, but it still exists.
recent failure: https://github.com/apache/pulsar/runs/7564370916?check_suite_focus=true#step:10:950
and this one: https://github.com/apache/pulsar/pull/16841/checks?check_run_id=7566225112
Why is this test flaky？ 
- The ledgerHandle of the cursor, is not accurately closed, even if it is closed, there is no guarantee that `ledgerHandle created` will occur after `cursor.persistentToLedger`.
https://github.com/apache/pulsar/blob/2d6b534ef72824ffb5b2f76568ca8346bbc058c6/pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java#L98-L100
- This line of below could not guarantee that `cursor.persistentToLedger` has been completed, only that the client has received a response. …
=> [fix][flaky-test]ManagedCursorMetricsTest.testManagedCursorMetrics

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
Release MaxQueueSize semaphore when invalid message,  the related PR #16835 only release the memory usage, but the semaphore also need release in here.
The fixed unit test can reproduce it, which only `enableBatching` can invoke the `createOpSendMsg` in `BatchMessageContainerImpl`.
1. add semaphore release;
2. fix unit test;
=> [fix][client]Fix MaxQueueSize semaphore release leak in createOpSendMsg

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerBkEnsemblesTests.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerManager.java
In some situations it is possible to encounter case when deletion of a ManagedLedger deals with cases of already deleted bookie ledgers. 
Such cases currently handled as errors even though they are safe to ignore.
Currently, it is impossible to handle these cases because PulsarManagedLedger returns error that's not mappable into the BK error code end the end user ends up with obscure `UnexpectedConditionException` (error code -999) that cannot be distinguished from ledger already deleted case.
1. Made PulsarManagedLedger return BK error where possible so BK client has a chance to handle/return correct error. 
2. Ignored NoSuchLedgerExistsOnMetadataServerException on delete as it is safe there 
This takes over https://github.com/apache/pulsar/pull/16664
This change added tests and can be …
=> [fix][broker] PulsarLedgerManager to pass correct error code to BK client

pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java
The assertion in `KubernetesRuntimeTest::verifyJavaInstance` was removed by accident in #11417
Put back the `assertEquals`
This change is already covered by existing tests, such as  `KubernetesRuntimeTest`
no
test
=> [improve][functions] Missing assertion in KubernetesRuntimeTest::verifyJavaInstance

conf/broker.conf, conf/proxy.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderBasic.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderBasicTest.java, pulsar-broker-common/src/test/resources/authentication/basic/.htpasswd
Right now the Pulsar only supports getting the basic authentication config from the system properties, I suggest reading it from the Pulsar config file.
- Add the `basicAuthConf` to the config file for use in reading the basic authentication config
- Add Base64 support for basic authentication config
Add `basicAuthConf` to Refrences page.
=> [improve][authentication] Improve get the basic authentication config

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/PendingAckHandleImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckInMemoryDeleteTest.java
now transaction pending ack delete pending ack state position use cursor mark delete position.
now the logic is use foreach, every position in pending ack state need to check the position whether smaller than mark delete position. If the position is smaller than mark delete position, it can be deleted from the pending ack state map.
this map is a skipListMap, the key is the position, so we only need to check if the first entry is better, if it is smaller than mark delete we can continue check, otherwise, we only break the check directly.
chan foreach to use firstkey
add the test for it
- The …
=> [improve][txn] change delete pending ack position from foreach to firstKey

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderBasic.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderBasicTest.java
Fix https://github.com/apache/pulsar/pull/16526#discussion_r920269032, which supports the following config:
```
basicAuthConf=data:;base64,YOUR-BASE64
basicAuthConf=file:///my/basic.conf
basicAuthConf=YOUR-BASE64
basicAuthConf=/my/basic.conf
```
=> [improve][authentication] Adapt basic authentication configuration with prefix

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
Cherry-pick #16917 #16205
```
06:03:58.778 [broker-topic-workers-OrderedScheduler-4-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
java.lang.IllegalArgumentException: null
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:128)
at org.apache.pulsar.broker.service.persistent.CompactorSubscription.acknowledgeMessage(CompactorSubscription.java:61) 
at org.apache.pulsar.broker.service.AbstractBaseDispatcher.filterEntriesForConsumer(AbstractBaseDispatcher.java:154) 
at org.apache.pulsar.broker.service.AbstractBaseDispatcher.filterEntriesForConsumer(AbstractBaseDispatcher.java:103)
at org.apache.pulsar.broker.service.persistent.PersistentDispatcherSingleActiveConsumer.internalReadEntriesComplete(PersistentDispatcherSingleActiveConsumer …
```
=> [Branch-2.8][Cherry-pick] Fix compaction subscription acknowledge Marker msg issue.

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationWithAuthDataTest.java
Fixes: #16283
Add a test to verify the authentication data in the authorization provider.
=> [improve][test] Verify the authentication data in the authorization provider

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyMutualTlsTest.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithAuthorizationTest.java
#15289 has been merged, we need to add TLS transport encryption for the broker client on the proxy.
- Add broker client for TLS transport encryption
=> [improve][proxy] Add TLS transport encryption for broker client

conf/client.conf, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java
We have implemented independent TLS transport encryption configuration on the Admin and Client, now let's support this in the cli.
=> [improve][cli] Add a separate TLS transport encryption configuration

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-functions/secrets/src/test/java/org/apache/pulsar/functions/secretsprovider/EnvironmentBasedSecretsProviderTest.java, pulsar-io/flume/src/test/java/org/apache/pulsar/io/flume/node/TestEnvVarResolverProperties.java
Cherry pick #16884 to branch 2.7
Upgrade log4j2 version to 2.18.0
=> [Branch 2.7][fix][broker] Upgrade log4j2 version to 2.18.0 (#16884)

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationWithAuthDataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
=> [improve][test][branch-2.7] Verify the authentication data in the authorization provider

pulsar-client-cpp/include/pulsar/Authentication.h, pulsar-client-cpp/include/pulsar/c/authentication.h, pulsar-client-cpp/lib/Authentication.cc, pulsar-client-cpp/lib/auth/AuthBasic.cc, pulsar-client-cpp/lib/auth/AuthBasic.h, pulsar-client-cpp/pulsar-test-service-start.sh, pulsar-client-cpp/test-conf/.htpasswd, pulsar-client-cpp/test-conf/standalone-ssl.conf, pulsar-client-cpp/tests/AuthBasicTest.cc
The basic authentication is missed in cpp-client.
- Added the basic authentication implement
- Added the basic authentication test
Add authentication code snippet of cpp-client to the Basic Authentication page.
=> [improve][cpp-client] Add basic authentication

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Fixes #[16796](https://github.com/apache/pulsar/issues/16796)
There is a incorrect out-of-order check for chunked message in `ConsumerImpl`. For the last check should compare the result of `chunkedMsgCtx.chunkedMsgBuffer.readableBytes() + compressedPayload.readableBytes()` with `TotalChunkMsgSize` instead of `ChunkId` with `TotalChunkMsgSize`.
Fix the out-of-order check for chunked message in `ConsumerImpl`.
=> [fix][client] Remove redundant check for chunked message TotalChunkMsgSize in ConsumerImpl

pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java
The pulsar-client-tool should be able to take "tlsTrustCertFilePath" as an input argument as it can be provided by the user.
Add an extra parameter to in the PulsarClientTool.java class.
-*Added unit test to verify if input arguments are parsed correctly. 
- The schema: (no )
(Your PR …
=> [improve][pulsar-client-tool] Add tlsTrustCertFilePath as CLI argument for pulsar-client-tool

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
This PR is part of work of cherry-pick https://github.com/apache/pulsar/pull/16915 to branch 2.7
Release MaxQueueSize semaphore when invalid message.
1. add semaphore release;
2. add unit test;
=> [Branch-2.7][fix][client] Fix MaxQueueSize semaphore release leak in createOpSendMsg.

pulsar-transaction/common/pom.xml, pulsar-transaction/coordinator/pom.xml, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionSubscription.java
Apply Maven Modernizer plugin to enforce we move away from legacy APIs.
Add Maven Modernizer plugin in pulsar-transaction module and fix violation.
=> [cleanup][transaction] Add Maven Modernizer plugin in pulsar-transaction

site2/docs/security-basic-auth.md
Add documentation for #16935, #16526 and #15822.
=> [improve][doc] Add more configuration methods for basic authentication

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
(cherry picked from commit 7a3ad611f51511afca4bcaa1de299517a1907e8e)
In current implementation, We have more than one potential NPE relate `ManagedLedgerImpl#startReadOperationOnLedger` method.
**1. Unbox NPE**
https://github.com/apache/pulsar/blob/b13d15c4d6d795f33c6ed23f920fabbb3eeaf745/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L2230-L2244
According to this code, we can know that when the ledger id is null, we will fail `OpReadEntry`. However, there is no direct return here after failure. NPE will be thrown on line 2238. Because we want to unbox `null`.
**2. null `OpReadEntry` context**
According to the code above, we can see when we fail `OpReadEntry`, we pass a null value as context(line 2235). there is an NPE when the dispatcher gets the …
=> [Branch 2.7][Fix][broker] Fix NPE when ledger id not found in `OpReadEntry` (#15837)

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
* Reduce local REST calll for `org.apache.pulsar.broker.admin.impl.PersistentTopicsBase#internalGetPartitionedStats`
* Call local method if partition is owned by this broker,  or call REST api usng internal `AdminClient`
=> [Improve][Broker]Reduce PartitionedStats local REST call

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
Fixes https://github.com/apache/pulsar/issues/16952
* Fix ConcurrentModificationException when ModularLoadManagerImpl start. The root cause is that `ModularLoadManagerImpl#knownBrokers` can be modified in multi-thread through `ModularLoadManagerImpl#updateAll`
*  Thread-1 is line290:
https://github.com/apache/pulsar/blob/5c09d536304e5873c4e1ceeb8353a1150b5d61f4/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java#L282-L292
*  Thread-2 is line969
https://github.com/apache/pulsar/blob/5c09d536304e5873c4e1ceeb8353a1150b5d61f4/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java#L938-L970
* Changing `ModularLoadManagerImpl#knownBrokers` to `ConcurrentHashMap.newKeySet()`
Check the box below or label this …
=> [fix][broker]Fix ConcurrentModificationException when ModularLoadManagerImpl start

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerMemoryLimitTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
This PR is part of work of cherry-pick #16837 to branch 2.9
Release memory limit `currentUsage` in `failPendingBatchMessages`  and avoid duplicate semaphore release in `batchMessageAndSend`.
1. Release memory limit `currentUsage` in `failPendingBatchMessages`  ;
2. delete duplicate semaphore release in `batchMessageAndSend`;
3. fix unit test;
=> [Branch-2.9][fix][client] Fix client memory limit currentUsage leak and semaphore release duplicated in ProducerImpl.

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
This PR is part of work of cherry-pick https://github.com/apache/pulsar/pull/16837 to branch 2.7, and only contain the fix in duplicate semaphore release.
Avoid duplicate semaphore release in batchMessageAndSend.
1. delete duplicate semaphore release in batchMessageAndSend;
2. add unit test;
=>  [Branch-2.7][fix][client] Fix semaphore release duplicated in ProducerImpl.

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerfClientUtils.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceBaseArguments.java, pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerfClientUtilsTest.java
Expose the maxLookupRequest configuration for pulsar-perf.
Without this configuration, run the pulsar-perf for over 50000 topics will
get exception like followings:
```
2022-08-07T10:31:28,317+0800 [pulsar-timer-7-1] WARN  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/p100k-partition-50393] [standalone-6-0] Could not get connection to broker: org.apache.pulsar.client.api.PulsarClientException$TooManyRequestsException: Requests number out of config: There are {0} lookup requests outstanding and {45000} requests pending. -- Will try again in 0.798 s
```
=> [improve][tool] Able to set maxLookupRequest for pulsar-perf

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SubscribeRateLimiter.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PrecisTopicPublishRateThrottleTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscribeRateTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscribeRate.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/HierarchyTopicPolicies.java
* Cherry-pick https://github.com/apache/pulsar/pull/15789  to branch-2.10
* Because PR-15789 is modified base  on other PR, so the following PR  also need cherry-pick
*  https://github.com/apache/pulsar/pull/15789  
*  https://github.com/apache/pulsar/pull/15604  
*  https://github.com/apache/pulsar/pull/15315   
*  https://github.com/apache/pulsar/pull/15457  
*  https://github.com/apache/pulsar/pull/14890  
*  https://github.com/apache/pulsar/pull/14909 
*  https://github.com/apache/pulsar/pull/14387  
*  https://github.com/apache/pulsar/pull/14342  
*  https://github.com/apache/pulsar/pull/14038  
(Docs have …
=> [Branch-2.10][Cherry-pick] tidy update subscriptions dispatcher rate-limiter

site2/docs/admin-api-topics.md, site2/docs/reference-metrics.md
add reference-metrics doc and admin-api doc for https://github.com/apache/pulsar/pull/16932
=> [doc][broker][monitoring] Add doc for per-subscription EntryFilter metrics

pulsar-function-go/logutil/log.go, pulsar-functions/instance/src/main/python/log.py, pulsar-functions/instance/src/main/python/python_instance_main.py
Signed-off-by: laminar <[tpiperatgod@gmail.com](mailto:tpiperatgod@gmail.com)>
Fixes #16928 
*Currently, if the user wants to output more logging level logs other than INFO, it should provide the log settings for different pulsar function runtimes.*
- modifications to Go functions
Pass in the logging level via environment variable, such as setting `LOGGING_LEVEL`, then add parsing of the `LOGGING_LEVEL` environment variable in `log.go`, , and finally set the logging level.
```go
const (
// environment variable for custom logging level
logLevelEnvName      = "LOGGING_LEVEL"
defaultLogLevel      = …
```
=> [feature][function] add the ability to customize logging level for Go & Python functions

.gitignore
This folder is generated when you work locally with package management service.
=> Add packages-storage folder to gitignore

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractSubscriptionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsumerTest.java
AbstractTopic#getBytesOutCounter and AbstractTopic#getMsgOutCounter
both generate full stats only to pick the single required counter for
the getters. These can be optimised to perform only the necessary work
to calculate the counters.
Provided a scoped implementation of the above methods for the single
counter required for each getter.
(cherry picked from commit 07c46fe9ef42a72de18be3267e70a51bbc883678)
=> [improve][broker] Optimise msgOutCounter and bytesOutCounter (#16214) (#16286)

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
Similar issue: #10696
We found the `StackOverFlow` when redelivering large messages. the log here:
```text
2022-08-01T15:30:08,243+0000 [pulsar-41-1] WARN  org.apache.bookkeeper.mledger.impl.EntryCacheImpl - failed to read entries for 467924-467924:46
java.lang.StackOverflowError: null
at jdk.internal.org.objectweb.asm.ClassWriter.newStringishItem(ClassWriter.java:1189) ~[?:?]
at jdk.internal.org.objectweb.asm.MethodWriter.visitTypeInsn(MethodWriter.java:866) ~[?:?]
at jdk.internal.org.objectweb.asm.MethodVisitor.visitTypeInsn(MethodVisitor.java:430) ~[?:?]
at java.lang.invoke.TypeConvertingMethodAdapter.cast(TypeConvertingMethodAdapter.java:188) ~[?:?]
at java.lang.invoke.TypeConvertingMethodAdapter.convertType(TypeConvertingMethodAdapter.java:241) ~[?:?]
at …
```
=> Prevent `StackOverFlowException` in SHARED subscription.

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
This PR is part of work of cherry-pick https://github.com/apache/pulsar/pull/16915 to branch 2.9
Release MaxQueueSize semaphore when invalid message.
1. add semaphore release;
2. fix unit test;
=> [Branch-2.9][fix][client] Fix MaxQueueSize semaphore release leak in createOpSendMsg. 

site2/docs/security-tls-authentication.md, site2/docs/security-tls-keystore.md, site2/docs/security-tls-transport.md
#16833 and #15634 improve the TLS transport encryption configuration. We need to import the TLS transport encryption and authentication documentation. 
=> [improve][doc] Improve TLS transport encryption and authentication

pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceTransactionTest.java
Fixes https://github.com/apache/pulsar/issues/14109
The transaction commit is async, so the consumer can still receive message when the consumer rebuilds.
Add  Awaitility.await() for check-ing whether the ongoingTxns = 0.
*(or)*
*(or)*
*(example:)*
- The public API: (yes / …
=> [Fix][Flaky-test] Fix testConsumeTxnMessage

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
---
We found there has a block between the pulsar-ordered executor and
the pulsar-stats-updater executor.
The pulsar-ordered executor is trying to createManagedLedgerOffloader,
and the pulsar-stats-updater is getting the compactor. Both them want
to get the lock.
We have an improvement about the `createManagedLedgerOffloader` before.
https://github.com/apache/pulsar/pull/15883
We are using `getCompactor(false)` for the stats related operations.
The `getCompactor` is guarded by `synchronized`. Actually, the stats
just want to get the current compactor without initializing it. We
don't need to use `synchronized` to guard this operation.
Remove unnecessary `synchronized` on the `getCompactor` method.
This change is a trivial rework / code …
=> [improve][broker]Remove unnecessary lock on the stats thread

pulsar-client-cpp/README.md, pulsar-client-cpp/include/pulsar/c/consumer.h, pulsar-client-cpp/lib/c/c_Consumer.cc, pulsar-client-cpp/lib/checksum/crc32c_arm.h, pulsar-client-cpp/python/pulsar/__init__.py, pulsar-client-cpp/python/pulsar_test.py, pulsar-client-cpp/python/src/consumer.cc
Python function getLastMessageId
It is a C binding for https://github.com/apache/pulsar/pull/16182 to implement get_last_message_id() in Python client.
Add Python/C binding code for get_last_message_id()
It compiles.
Python Doc is updated in __init__.py
(Docs have been …
=> [client][python] getLastMessageIdAsync C binding

pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java
Fixes #16829
The root cause is the `ack()` function will be multi-threaded concurrent execution, but `ack++` is not an atomic operation.
Use `LongAdder` instead of `int` to ensure the atomicity.
=> [fix][flaky-test] ElasticSearchClientTests.testBulkBlocking

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerMemoryLimitTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
This PR is part of work of cherry-pick https://github.com/apache/pulsar/pull/16837 to branch 2.8
Release memory limit currentUsage in failPendingBatchMessages and avoid duplicate semaphore release in batchMessageAndSend.
1. Release memory limit currentUsage in failPendingBatchMessages ;
2. delete duplicate semaphore release in batchMessageAndSend;
3. fix unit test;
=> [Branch-2.8][fix][client]Fix client memory limit currentUsage leak and semaphore release duplicated in ProducerImpl

.asf.yaml
See #14226 for original context.
* Add `branch-2.11` to the list of protected branches
=> Update .asf.yaml to protect branch-2.11

pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntimeFactoryTest.java
Master Issue: #16912 
cc @Shoothzj @eolivelli
=> [improve][test] Avoid hacky modify static final field

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
Master Issue: #16979
PR https://github.com/apache/pulsar/pull/12258 made changes to OpAddEntry which causes a memory leak when the entry is already in the cache.
Modifications: Revert PR https://github.com/apache/pulsar/pull/12258 changes to OpAddEntry
=> [fix][broker] Fix memory leak if entry exists in cache

pulsar-broker/pom.xml
`Lookup API` has a superfluous v2 display address on the web page.
- Change swagger base path.
=> [fix][rest] Fix swagger shows lookup API path error.

pulsar-broker-common/src/main/java/org/apache/pulsar/common/configuration/VipStatus.java
Fixes #9201
Master Issue: #9201
If injection fails, Jersey print the error log, see:
https://github.com/javaee/jersey/blame/faa809da43538ce31076b50f969b4bd64caa5ac9/inject/hk2/src/main/java/org/glassfish/jersey/inject/hk2/JerseyErrorService.java#L89
- The method `checkStatus` is not an injection method, remove `@Context`. 
- Print warn log if service has not ready.
=> [fix][broker] remove exception log when access status.html

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicDispatchRateLimiterTest.java
Cherry-pick https://github.com/apache/pulsar/pull/16084
* cherry-pick https://github.com/apache/pulsar/pull/16084 
* Also chery-pick https://github.com/apache/pulsar/pull/15377, which is base on
* There are some modifies in `TopicDispatchRateLimiterTest`:
* Set `SystemTopicEnabled` and `opicLevelPoliciesEnabled` as true, Becasue the default value of both are false on branch-2.10
* Modify `assertTrue(topic.getDispatchRateLimiter().isEmpty())` to `assertFalse(topic.getDispatchRateLimiter().isPresent())`.  Because `java.util.Optional#isEmpty` is present since jdk11,  and branch-2.10 java language level is jdk8.
(Docs …
=> [branch-2.10][cherry-pick] Fix topic dispatch rate limiter not init on broker-level #16084

buildtools/pom.xml
Remove superfluous noise from the build:
```
[WARNING] buildtools-2.11.0-SNAPSHOT.jar, commons-lang3-3.11.jar define 1 overlapping resource:
[WARNING]   - META-INF/MANIFEST.MF
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
```
Explicitly excluded `MANIFEST.MF` file from `commons-lang` during shade so that it doesn't conflict with generated manifest file.
This change is a …
=> [cleanup][buildtools] Prevent shade plugin warning

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
Master Issue: https://github.com/apache/pulsar/issues/16521
- Fixes https://github.com/apache/pulsar/issues/16521
- If the broker responds quickly enough, there may never be concurrency in requests, so we use a `Semaphore` to block the response.
Fix UT  `BrokerServiceTest.testLookupThrottlingForClientByClient`
=> [test]Fix Flaky-test: BrokerServiceTest.testLookupThrottlingForClientByClient

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedderTest.java, pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerData.java
Incorrectly scaled resource load usage(cpu, memory, network usages bigger than 100%) can harm the load computation in the load balancer logics, as the load balancer computation expects all resource usages are normalized to the 100% scale. 
Also, we need more logs to debug load balance issues in the production. For example, we need more logs to investigate why the load balancer does not unload the bundles to the underloaded brokers and etc.
- Added a fall-back logic to ignore any incorrectly scaled resource usage in the load balance computation from ThresholdShedder. 
- Also updated LeastResourceUsageWithWeight.java (used for broker assignment) to ignore such invalid resource usages. 
- Added more logs in load balance logics(ThresholdShedder and Load Report) for better debugging.
This …
=> [fix][load-balancer] skip mis-configured resource usage(>100%) in load balancer

.github/workflows/project-flaky-test.yml
ML discussion: https://lists.apache.org/thread/q49r2blh1wmvnr0mqx2lxxkhd8c306bm
I have created a project for flaky test issues management https://github.com/apache/pulsar/projects/11
Which will help us to track the flaky test better.
Use the Github action to add the flaky test issues and PRs to the flaky test management automatically.
=> [feat][ci] Add flaky test issues and PRs to flaky test project

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Fixes #17014 
The root cause of #17014 is a race condition in the `batchMessageContainer` when discarding the messages and releasing the semaphore. We need to release semaphore first and then discard messages. Otherwise, the user may observe that the semaphore has not been released after receiving the callback of that message.
* Release semaphore before discarding messages in batchMessageContainer
=> [fix][client] Release semaphore before discarding messages in batchMessageContainer

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
Fixes #15891
Master Issue: #15891
Pulsar-manager could see all the topics including the system topic and can terminate them.  If terminates system topic by mistake, there would cause many serious problems.  So it's better not allow to terminate the system topic.
=> [improve][admin] Not allow to terminate system topic.

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/SchedulerManager.java
To reduce warnings generated during compilation by cleaning up the code.
```
[WARNING] /Users/ewest/git/pulsar/pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/SchedulerManager.java:[334,9] finally clause cannot complete normally
[WARNING] /Users/ewest/git/pulsar/pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/SchedulerManager.java:[642,9] finally clause cannot complete normally
```
* Moved `return` from `finally` blocks
* Simplified code through the use of simpler, equivalent language constructs
* Made some constant fields `final` …
=> [cleanup][pulsar-functions] Remove compiler warnings for return from finally

README.md, SECURITY.md, site2/docs/security-policy-and-supported-versions.md, site2/website/versioned_docs/version-2.10.0/security-policy-and-supported-versions.md, site2/website/versioned_docs/version-2.10.1/security-policy-and-supported-versions.md
- the previous description wasn't clear and could cause confusion
- the page https://pulsar.apache.org/docs/security-policy-and-supported-versions/ source is under the last published version and didn't get updated with the last changes made by #16962
(that was only visible in https://pulsar.apache.org/docs/next/security-policy-and-supported-versions/)
- Clarify the security vulnerability process and reporting
- Add information also to SECURITY.md so that the information is available also in cases when pulsar.apache.org isn't reachable or the reader doesn't click on links to read the relevant information. It's better to duplicate information about the vulnerability handling process in SECURITY.md.
=> [docs] Clarify security vulnerability process and reporting

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
- counters could get off a lot when many consumers are reconnecting from time to time
Pulsar increments the counters when the sending is scheduled. Since the dispatching code is asynchronous, it behaves in a way that Pulsar will try to consume all permits and queue as much of messages as possible. Since the counters are incremented before the messages have been written to the TCP/IP socket, this will result in the counters getting out of sync when the connection is disconnected.
- increment counters and update rate after the messages have been successfully written to the TCP/IP connection
=> [fix][broker] Increment topic stats outbound message counters and update rate after messages have been written to the TCP/IP connection

pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterTest.java
Fixes #16989, #16723
Master Issue: #16989, #16723
- #16989: We mocked a BK error, but if an exception occurs, the failure callback will be executed earlier. So the results of the callbacks will be out of order, and mismatch occur.
- #16723: I'm sorry, but after PR #16982 I found another reason makes unit test flaky, Multi threads access to `ArrayList` causes the 'list.size()' to return incorrect results, leading to `Awaitility.await().until(() -> contextArrayOfCallback.size() == writeCmdExecuteCount)` cannot end.
- #16989: If we mocked BK errors, sort the callback results.
- #16723: Make collection objects to thread safety.
- Remove unstable assertions. I will rewrite these two cases after PR #16758, because that PR has really changed a lot
```java
Assert.assertTrue(exceptionCallbackCount …
```
=> [fix][flaky-test]TxnLogBufferedWriterTest.testMainProcess

site2/docs/client-libraries-cpp.md, site2/docs/client-libraries-python.md, site2/docs/client-libraries.md
Related to https://github.com/apache/pulsar-site/issues/146.
* Websocket is not a language but a language-agnostic interface.
1. Separate language-specific and language-agnostic clients.
2. Improve third-party client libraries display - show stars, grouped by languages.
3. Avoid redundant links to doc tools, it's not what users care.
cc @Anonymitaet @momo-jun @shibd @RobertIndie
=> [improve][doc] Separate language-specific and language-agnostic clients

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java
The function worker service in the PulsarFunctionTlsTest hasn't been stopped when tearing down.
* Stop worker services when tearing down PulsarFunctionTlsTest
=> [fix][test] Stop worker services when tearing down PulsarFunctionTlsTest

tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderTest.java
---
Move the close check forward to avoid `getLastAddConfirmed()` get
an NPE.
If the state is closed. That means the resource is closed and the
`OffloadIndexBlock` has been recycled. Which will cause an NPE when
`getLastAddCOnfirmed()`.
move the state check forward
*(or)*
*(or)*
*(example:)*
- Dependencies (does it add or upgrade a …
=> [fix][tiered-storage] move the state check forward

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
Fixes #17050
Master Issue:
-  #17050
If enabled system topic, when a topic is deleted, these events are triggered serially:
- delete topic
- check topic ownership
- load bundle
- trigger event: NamespaceBundleOwnershipListener.onLoad()
- init system topic client
- subscribe system topic
- (<strong>High loght</strong>)create topic: __change_events
Then the exception "Directory not empty" occurs when deleting the namespace.
https://github.com/apache/pulsar/blob/ee0ea3a6f9ffb42d4ec129eb689d3c1059e5f4a8/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java#L1367-L1371
Even if will try to delete topics that type `system` when deleting namespace, there is still the problem of multi-thread concurrency.
https://github.com/apache/pulsar/blob/ee0ea3a6f9ffb42d4ec129eb689d3c105 …
=> [fix][flaky-test]AdminApi2Test.testDeleteTenant

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java
Fixes #16948
Master Issue: #16948
This test is flaky because that BK has not been successfully written when the asset executed
https://github.com/apache/pulsar/blob/e5d5fbe5d023d9df0bf47e73186f3203a1f07c42/pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java#L244-L248
Makes assert execute after BK written
=> [fix][flaky-test]ManagedCursorMetricsTest.testCursorReadWriteMetrics

pom.xml
current PostgreSQL client related to CVE-2022031197(https://github.com/pgjdbc/pgjdbc/security/advisories/GHSA-r38f-c4h4-hqq2), update to newest(https://jdbc.postgresql.org/documentation/changelog.html#version_42.4.1).
=> [security] bump PostgreSQL version

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageWithBatchIndexLevelTest.java
issue: reduce the consumer `unackedCount` use incorrect consumer.
reproduce step
```
for (int i = 0; i < 5; i++) {
producer.newMessage().value(("Hello Pulsar - " + i).getBytes()).sendAsync();
}
// consume-1 receive 5 batch messages
List<MessageId> list = new ArrayList<>();
for (int i = 0; i < 5; i++) {
list.add(consumer1.receive().getMessageId());
}
// consumer-1 redeliver the batch messages
consumer1.negativeAcknowledge(list.get(0));
// consumer-2 will receive the messages that the consumer-1 redelivered
for (int i = 0; i < 5; i++) {
consumer2.receive().getMessageId();
}
// consumer1 ack two messages in the batch message
consumer1.acknowledge(list.get(1));
consumer1.acknowledge(list.get(2));
// consumer-2 redeliver the rest of the messages
consumer2.negativeAcknowledge(list.get(1));
// …
```
=> [fix][broker] fix broker unackmessages number reduce error

pulsar-client-cpp/lib/ConsumerImpl.cc, pulsar-client-cpp/lib/HandlerBase.cc, pulsar-client-cpp/lib/HandlerBase.h, pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc, pulsar-client-cpp/lib/MultiTopicsConsumerImpl.h, pulsar-client-cpp/lib/PartitionedConsumerImpl.cc, pulsar-client-cpp/lib/PartitionedConsumerImpl.h, pulsar-client-cpp/lib/PatternMultiTopicsConsumerImpl.cc, pulsar-client-cpp/lib/ProducerImpl.cc
Now, Use a lot of locks to ensure the atomicity of `state_` in the `ConsumerImpl`, `ProducerImpl`, `PartitionedConsumerImpl`, and `MultiTopicsConsumerImpl`, we can use atomic `state_` instead of the lock to improve performance.
Use an atomic `state_` instead of the lock to improve performance.
*(or)*
*(or)*
*(example:)*
- Dependencies …
=> [improve][client-c++] Use an atomic `state_` instead of the lock to improve performance

pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java
Master Issue: #17081
This patch adds failure details so that we can dig out why the assertion failed.
cc @codelipenghui @BewareMyPower
=> test: print detail failure for testDeleteTopicAndSchemaForV1

pulsar-client-cpp/lib/ProducerImpl.cc
When I investigate the c++ flaky tests, there is no producer id in the log of `closed producer`.
Need to add the producer id like that in the consumer:
https://github.com/apache/pulsar/blob/bc68f02a4060ef0042a50c2b1d834c6ab84cfd13/pulsar-client-cpp/lib/ConsumerImpl.cc#L1064
This will help debug.
* Add producerId to the log of closed producer.
=> [improve][c++] Add producerId to the log of closed producer

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java
Fixes #16488
*(or)*
*(or)*
*(example:)*
- Dependencies …
=> [improve][broker] Improve naming for delete topic error

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
When there are many partitioned topics under a namespace, deleting the namespace forcibly will fail, because many requests update ns policies simultaneously and cause the metadata store throws BadVersionException.
See `internalRemovePartitionsAuthenticationPoliciesAsync`
https://github.com/apache/pulsar/blob/374b3a18155cba33c4b4cfdb18c8119487be565e/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L612-L629
https://github.com/apache/pulsar/blob/374b3a18155cba33c4b4cfdb18c8119487be565e/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L704-L714
When deleting the namespace, there is no need to update namespace policies, we can delete the namespace zk node in the end. …
=> [improve][admin] Unset namespace policy to improve deleting namespace.

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
Fixes #16561
This issue is caused by `Failed to find ownership for ServiceUnit`, We split the bundle with unload option, 
this bundle is not guaranteed to be loaded  before the next split.
use mockWebUrl(localWebServiceUrl, testNs) to ensure this bundle is owned by broker
=> [fix][flaky-test] testSplitBundleForMultiTimes

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java
Master Issue: #17087
*(or)*
*(or)*
*(example:)*
- The …
=> fix: bundle-data metadata leak because of bundlestats was not clean

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheTest.java
Fixes #16979 
https://github.com/apache/pulsar/pull/12258 introduced caching for backlogged consumers. When caching the entry, it is important to duplicate the `ByteBuffer` so that the reader index is not shared. The current code has a race condition where the `ByteBuffer` reference in the cache is shared with the dispatcher. When another consumer reads from the cache, the cache calls `duplicate()` on the shared `ByteBuffer`, which copies the current reader index, which might not be 0 if the original dispatcher read data from the `ByteBuffer`.
Note: it seems like the caching `insert` method creates (or recycles) more `EntryImpl` instances than is really necessary. Changing that is outside this PR's scope, so I am going to leave it as is.
* Create a new `Entry` before inserting it into the …
=> [fix][broker] Duplicate ByteBuffer when Caching Backlogged Consumers

conf/broker.conf, site2/docs/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.10.0/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.10.1/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.7.0/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.7.1/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.7.2/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.7.3/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.7.4/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.8.0/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.8.1/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.8.2/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.8.3/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.9.0/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.9.1/tiered-storage-filesystem.md, site2/website/versioned_docs/version-2.9.2/tiered-storage-filesystem.md
The configuration item `fileSystemProfilePath` in` broker.conf `has the wrong default value: For File System Storage, `fileSystemProfilePath` is the file system profile path; when we use a relative path, the current dir is the pulsar root dir, not `conf/ `dir,so the correct relative path is `conf/filesystem_offload_core_site.xml` not `../conf/filesystem_offload_core_site.xml`.
In addition, this configuration item in our docs also uses the wrong default values.
https://pulsar.apache.org/docs/next/tiered-storage-filesystem#configure-filesystem-offloader-driver
https://pulsar.apache.org/docs/next/tiered-storage-filesystem#step-3-configure-the-filesystem-offloader
https://pulsar.apache.org/docs/next/tiered-storage-filesystem#step-3-configure-the-filesystem-offloader-driver
Fix the wrong …
=> [fix][doc]Fix fileSystemProfilePath wrong default value

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java
Since #3969, `packageUrl` is not set anymore in FunctionDetails so code that depend on it can be removed.
In the case of KubernetesRuntime we currently download the function itself and not the package.
This change doesn't modify this behaviour.
no
(Your PR …
=> [cleanup][functions] Remove unused code

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherMultipleConsumers.java
There are so many dispatcher blocked/unblocked log(more than 30K within 15 min), I supposed change it to debug.
Just change log level
=> [pulsar-broker] Change dispatcher blocked/unblocked log level to debug

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
Minor optimization. The implementation of `getPosition` involves creating a `PositionImpl` object. We don't need to create that object because we have access to the `ledgerId` and the `entryId`.
https://github.com/apache/pulsar/blob/76f41957d3b388d62067704ceb1b693dbd3e372d/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryImpl.java#L134-L137
* Remove unnecessary `getPosition()` call.
=> [imp][managed-ledger] Optimize getting ledger and entry id from entry

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/EntryFilterProducerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java
Calculating avg message per entry using `entries.size()` is incorrect, because the entries may have `null` values.
Calculate avg message per entry using the number of filter-out Non-null value total entries.
=> [fix][broker] Fix calculate avg message per entry

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadSheddingTask.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleLoadManagerImplTest.java
Although the configuration loadBalancerSheddingIntervalMinutes is marked as dynamic=true, it cannot be changed dynamically.
When loadSheddingTask is initialized, the shed interval is fixed:
https://github.com/apache/pulsar/blob/4d64e2e66689381ebbb94fbfc03eb4e1dfba0405/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L1051-L1053
https://github.com/apache/pulsar/blob/4d64e2e66689381ebbb94fbfc03eb4e1dfba0405/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java#L2087-L2093
=> [fix][broker] Support loadBalancerSheddingIntervalMinutes dynamic configuration

build/run_unit_group.sh, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConnectionTimeoutTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImplTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/schema/SchemaHash.java
#11441 supports replicate schema to remote clusters.
But there is a mistake that the returned schema state is incorrect.
https://github.com/apache/pulsar/blob/e826d849ceef9d6aef28569ad57950bba90dfff1/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java#L765-L770
Because the replicator used MessageImpl will not have the schema.
And this will cause the producer to skip the schema upload.
https://github.com/apache/pulsar/blob/e826d849ceef9d6aef28569ad57950bba90dfff1/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L2147-L2149
We should remove
https://github.com/apache/pulsar/blob/e826d849ceef9d6aef28569ad57950bba90dfff1/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java#L766-L768
To return the correct schema state.
And …
=> [fix][broker] Fix schema does not replicate successfully

site2/docs/developing-binary-protocol.md, site2/website/versioned_docs/version-2.1.1-incubating/developing-binary-protocol.md, site2/website/versioned_docs/version-2.10.0/developing-binary-protocol.md, site2/website/versioned_docs/version-2.10.1/developing-binary-protocol.md, site2/website/versioned_docs/version-2.10.x/developing-binary-protocol.md, site2/website/versioned_docs/version-2.2.1/developing-binary-protocol.md, site2/website/versioned_docs/version-2.3.0/developing-binary-protocol.md, site2/website/versioned_docs/version-2.3.1/developing-binary-protocol.md, site2/website/versioned_docs/version-2.3.2/developing-binary-protocol.md, site2/website/versioned_docs/version-2.4.1/developing-binary-protocol.md, site2/website/versioned_docs/version-2.4.2/developing-binary-protocol.md, site2/website/versioned_docs/version-2.5.0/developing-binary-protocol.md, site2/website/versioned_docs/version-2.8.x/developing-binary-protocol.md, site2/website/versioned_docs/version-2.9.x/developing-binary-protocol.md
Fix https://github.com/apache/pulsar/pull/13336#pullrequestreview-1068084883
I do not fix occurrences in `reference-configuration.md` because we're optimizing the workflow (trying to generate docs from code automatically for https://pulsar.apache.org/docs/next/reference-configuration)
=> [fix][doc] correct configuration name to exposingBrokerEntryMetadataToClientEnabled

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherMultipleConsumers.java
NOTE: THIS BUG IS NOT IN ANY RELEASED VERSION OF PULSAR.
While using a streaming dispatcher (`streamingDispatch=true`), the consumer (with a shared subscription) is stuck and it's not able to fully read a topic. That is because after the an entry is read, the `readMoreEntries` method is not triggered anymore. This is a regression introduced in https://github.com/apache/pulsar/pull/16968
* Aligned the new usage of the method `sendMessagesToConsumers` in the `PersistentStreamingDispatcherMultipleConsumers` in the same way it's used in `PersistentDispatcherMultipleConsumers`
* Implemented the option `DispatcherDispatchMessagesInSubscriptionThread` also in the streaming dispatcher - this might be done in another pull but it's a very tiny change - follow up of …
=> [fix][broker] Streaming dispatcher stuck after reading the first entry with SHARED subscriptions

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
Pass subscription name to the auth service.
* Update several methods that need to pass subscription name.
=> [fix][broker] Pass subscriptionName to auth service

pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/BrokerInterceptorTest.java
Fixes: #16516
Client will receive response of `cmd-subscribe` before executed `Interceptor().consumerCreated()`
https://github.com/apache/pulsar/blob/3c3ec49851a05484ef917f0e6d44393c40196ba3/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L1100-L1102
Same thing with `ProducerCreation`.
Use the `counter` to determine if the task is complete.
=> [fix][flaky-test]BrokerInterceptorTest.testProducerCreation

pulsar-common/src/main/java/org/apache/pulsar/common/api/raw/RawMessageImpl.java, pulsar-common/src/test/java/org/apache/pulsar/common/api/raw/RawMessageImplTest.java
Finally I find the bug, which makes `org.apache.pulsar.tests.integration.presto.TestBasicPresto#testForSchema` fail, But I still don't know why other PRs can run it success
* This PR will fix https://github.com/apache/pulsar/issues/16975 OR https://github.com/apache/pulsar/issues/9704
* The root cause is that:
* The `keyByteBuf ` we get from `currentMessage ` is not correct (line545 in code block 1), because we didn't decode the key with Base64 when the message is non-batched published.  Explain in details:
*   As we know `SingleMessageMetadata`  is only set when publish batched messages.  So we will use `RawMessageImpl#singleMessageMetadata` to decode the key when messages is batched, or use `RawMessageImpl#msgMetadata` if messages in non-batched, As line174 in code block 2.
* The …
=> [fix][test][sql]Fix presto sql avro decode error when publish non-batched msgs

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsumedLedgersTrimTest.java
Fixes 
- #11145 
- #10380
- #17044
Master Issue: #11145 #10380 #17044
https://github.com/apache/pulsar/blob/4d7b1acff35a1a131ffeff34e8cec6007f6a2ec9/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsumedLedgersTrimTest.java#L145-L150
In addition to calling `internalTrimLedgers` directly in this unit test, the Broker also has scheduled tasks `consumedLedgersMonitor` calling `internalTrimLedgers`.
(<strong>High light</strong>)See the code above, If `consumedLedgersMonitor` call `internalTrimLedgers` before `line:148`:
the command `topics.getLastMessageId` will return `-1:-1:-1`, then the #11145 #10380 occurs.
https://github.com/apache/pulsar/blob/4d7b1acff35a1a131ffeff34e8cec6007f6a2ec9/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsumedLedgersTrimTest.java#L …
=> [fix][flaky-test]ConsumedLedgersTrimTest

pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java, pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/utils/FunctionRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ContextImplTest.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/RecordFunction.java
Fixes #17114
Change `newOutputRecordBuilder` to `newOutputRecordBuilder(Schema<X> schema)`
This change is already covered by existing tests, such as ContextImplTest and PulsarFunctionsJavaTest::testRecordFunctionTest
- The public API: yes
fix
=> [fix][functions] Make mandatory to provide a schema in Context::newOutputRecordBuilder

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/AbstractSinkRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/OutputRecordSinkRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/SinkRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java, tests/docker-images/java-test-functions/src/main/java/org/apache/pulsar/tests/integration/functions/RemoveAvroFieldRecordFunction.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTestBase.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarFunctionsJavaTest.java
Currently the schema set by a Function returning a Record is not taken into account.
Don't set the schema to the initialized Sink Schema if the record is a OutputRecordSinkRecord
* testGenericObjectRemoveFieldRecordFunction
* testGenericObjectRemoveFieldRecordFunctionKeyValue
no …
=> [fix][function] Use the schema set by the Function when it returns a Record

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
Fixed #16755 
see #16755 
- Close protocol handler before closing broker server. Because the protocol handler service maybe depends on broker service.
- ~~First close the `acceptorGroup` and `workerGroup` service of `BrokerService`. Because they can accept the request from outside.~~
=> [fix][broker]optimize the shutdown sequence of broker service when it close

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
When the server receives a request, it is supposed to check its own state. like `handleAck\handleCloseProducer\handleConnect\handleFlow\handleProducer`
Add ServerCnx state check when server handle request
=> [improve][broker]add ServerCnx state check before server handle request

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
Fixes: #17111
same as #17070, there have two race conditions:
1. delete namespace and asynchronously create topic `__change_event`
2. delete namespace and asynchronously create subscription `__change_event/__compaction`
Make delete namespace after `__change_event` and `__change_event/__compaction` create finish.
=> [fix][flaky-test]AdminApi2Test.testDeleteNamespace

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/SimpleProducerConsumerTestStreamingDispatcherTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
There's a test failing constantly in the flaky suite: 
https://github.com/apache/pulsar/issues/16795
While investigating, I found out a case when it's possible that the dispatcher replays twice the same message to the consumer. This may happens because the message's replay is async and it's done while reading entries.  
I believe that it may be related to recent changes to the dispatcher: 
- https://github.com/apache/pulsar/pull/16603
- https://github.com/apache/pulsar/pull/16812
- https://github.com/apache/pulsar/pull/16968
- https://github.com/apache/pulsar/pull/17143
* Added the same guard inside `readMoreEntries` for the streaming dispatcher
The proof that this fix works is that now the test `SimpleProducerConsumerTest.testSharedSamePriorityConsumer` doesn't fail anymore.
Fix #16795
=> [fix][broker] Avoid messages being repeatedly replayed with SHARED subscriptions (streaming dispatcher) 

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
Fix flaky test  `testBacklogNoDelayedForPartitionedTopic`
```
Error:  testBacklogNoDelayedForPartitionedTopic(org.apache.pulsar.broker.admin.AdminApi2Test)  Time elapsed: 2.24 s  <<< FAILURE!
java.lang.AssertionError: expected [5] but found [6]
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:797)
at org.testng.Assert.assertEquals(Assert.java:807)
at org.apache.pulsar.broker.admin.AdminApi2Test.testBacklogNoDelayedForPartitionedTopic(AdminApi2Test.java:1627)
at …
```
=> [fix][flaky-test] Fix flaky test testBacklogNoDelayedForPartitionedTopic

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
* Cleanup unused param in `org.apache.pulsar.broker.admin.AdminResource#provisionPartitionedTopicPath`
* Removing `asyncResponse` in `provisionPartitionedTopicPath`
=> [cleanup][broker]Cleanup unused param in provisionPartitionedTopicPath

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
There is a typo in ManagedCursorImpl.
Replaced `readPositio` with `readPosition`
=> Fix log typo in ManagedCursorImpl

site2/docs/security-jwt.md
The security-jwt documentation shouldn't include the tls settings.
=> [fix][doc] Remove tls settings from security-jwt doc

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractBaseDispatcherTest.java
`testFilterEntriesForConsumerOfEntryFilter` test  make no sense,  because trackDelayedDelivery always return true.
Even if we remove the all reject entry filters, this test would run successfully.
return false   if `!msgMetadata.hasDeliverAtTime()` in trackDelayedDelivery
=> [fix][test] entry filter makes no sense

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthenticatedProducerConsumerTest.java
In the current implementation, when closing the topic we use `thenAccept` to delete topic policies. It will ignore the exception and do not waiting for the inner `CompletableFuture`.
- Use `thenCompose` to instead of `thenAccept`
- When namespace is marked `deleted`, we don't need to delete topic policies.
=> [fix][broker] Make `deleteTopicPolicies` serialized is executed when close topic.

pulsar-client-tools/src/main/java/org/apache/pulsar/shell/PulsarShell.java
Fixes #17179 
`user.home` property is not set in all the environments. 
* If user.home is empty or equals to "?" now we use the current directory `user.dir`
In the case of Pulsar docker image, it is recommended to always run the shell from the same directory.
For example, if you run it from the default dir (`/pulsar`) it will create the `.pulsar-shell` dir inside it. (`/pulsar/.pulsar-shell`)
=> [fix][cli] Pulsar shell: fix using directory '?' in the docker image

pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java
Fixes #17224
Master Issue:  #17224
From the log, we can see that when we deleted the schema, the schema was re-registered due to the reconnecting of the producer.
>2022-08-23T12:12:32,213 - INFO  - [pulsar-web-32-16:Producer@642] - Disconnecting producer: Producer{topic=PersistentTopic{topic=persistent://public/test-namespace-sfyppbtzkaqjgdgw/test-delete-topic-and-schema}, client=/127.0.0.1:59612, producerName=test-0-0, producerId=0}
2022-08-23T12:12:32,213 - INFO  - [pulsar-web-32-16:Producer@642] - Disconnecting producer: Producer{topic=PersistentTopic{topic=persistent://public/test-namespace-sfyppbtzkaqjgdgw/test-delete-topic-and-schema}, client=/127.0.0.1:59612, producerName=test-0-1, producerId=1}
2022-08-23T12:12:32,217 - INFO  - [pulsar-client-io-37-1:ClientCnx@748] - …
=> [fix][tests] Close producer to avoid create schema again.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
It's not allow to terminate the system topic in pr #17006, but the best position for this logic is at the head of `internalTerminateAsync` to avoid redundant or unnecessary judgments.
- Put the logic of judging whether it is a system theme to the beginning of the `internalTerminateAsync`
=> [improve][broker] Optimize the logic of terminating system topic

bin/pulsar-managed-ledger-admin
In python3.x, long renamed to int, so we should use int instead
of long in scripts.
Traceback (most recent call last):
File "bin/pulsar-managed-ledger-admin", line 247, in deleteMLLedgerIdsCommand
deletLedgerIdSet.add(long(id))
NameError: name 'long' is not defined
- rename long to int
- 
*(or)*
*(or)*
*(example:)*
- Dependencies (does …
=> [fix][tool] Using int instead of long in python scripts

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java
In the master branch, we have supported zk retry logic for connection loss cases, which will reduce data inconsistency for Pulsar broker with Zookeeper. 
https://github.com/apache/pulsar/blob/423ab75425211c52f43384a915fb775b8ecb5070/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java#L163-L169
We backport this feature into branch-2.8
=> [Branch-2.8][improve][broker]Add retry for zk operation on connection loss

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerIdGenerator.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerIdGeneratorTest.java
Fixes #17191
Fix pulsarLedgerIdGenerator can't delete index path when zk metadata store config rootPath.
This problem may lead zk oom if the ManagedLedgerImpl create new ledger too frequent.
=> [fix][broker] Fix pulsarLedgerIdGenerator can't delete index path when zk metadata store config rootPath.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
Because `common-pool` is an uncontrolled thread pool, we need to avoid using it directly.
For the case where the metadata thread will be used here we need to optimize in a later discussion.
- Use the original thread to process the following operation. …
=> [improve][broker] Avoid using `common-pool` when run async method.

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerStrategyTest.java
For a candidate broker, the addition expression maybe results in out of bounds and causes unexpected result when executing the following code.
https://github.com/apache/pulsar/blob/3ecf34abf99afd7c53a681ab82d5bcec2bc499a1/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java#L146-L151
Make the max resource usage as 100% instead of `Double.MAX_VALUE`. …
=> [fix][broker]fix arithmetic exception for LeastResourceUsageWithWeight strategy

pulsar-client-cpp/python/test_producer.py
`test_producer.py` will run failed.
```
Traceback (most recent call last):
File "workspace/github/pulsar/pulsar-client-cpp/python/test_producer.py", line 35, in <module>
batching_type=BatchingType.KeyBased
NameError: name 'BatchingType' is not defined
```
- add import _pulsar.BatchType.
=> [fix][python client]Fix python producer test run failed.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
* There is a bug that the properties of topic will be removed if we update topic partition number using pulsar admin
* Keep the properties in `PartitionedTopicMetadata` when updating it.
- Add UT `org.apache.pulsar.broker.admin.PersistentTopicsTest#testUpdatePartitionedTopicHavingProperties`
=> [broker][fix]Fix update topic remove properties
