apache/pulsar

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiOffloadTest.java

Fixes #17086
Master Issue: #17086
#7883 supports topic-level offload, when it sets the policy, it calls `internalUpdateOffloadPolicies` to update the topic that the current broker owns.  But `pulsar().getBrokerService().getTopicIfExist` will check the topic ownership first, so it may throw the below exception that #17086 occurs.
```
org.apache.pulsar.broker.service.BrokerServiceException$ServiceUnitNotReadyException: Namespace bundle for topic (persistent://ys/ys1/topic1-partition-1) not served by this instance. Please redo the lookup. Request is denied: namespace=ys/ys1
```
As #11051 has changed that `Redirect to the broker which is the owner of the partition-0 for a partitioned topic when setting topic policy`, we'd better keep the same behavior for updating the topic policy.  So remove …

Remove `internalUpdateOffloadPolicies` to keep the same behavior update topic policy

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherSingleActiveConsumer.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SubscriptionMessageDispatchThrottlingTest.java

When invoking `readMoreEntries` we have to check if the `havePendingRead` state is `true` to avoid reading the same position many times in the race condition. 
You can add `invocationCount` on the `Test` annotation to call the new test multiple times to understand the problem.
The relative logs:
```
2022-08-23T19:10:01,016 - INFO  - [pulsar-web-191-16:Slf4jRequestLogWriter@62] - 127.0.0.1 - - [23/Aug/2022:19:10:01 +0800] "GET /admin/v2/namespaces/my-property/throttling_ns/subscriptionDispatchRate HTTP/1.1" 200 124 "-" "Pulsar-Java-v2.11.0-SNAPSHOT" 2
2022-08-23T19:10:01,019 - INFO  - [pulsar-web-191-14:Slf4jRequestLogWriter@62] - 127.0.0.1 - - [23/Aug/2022:19:10:01 +0800] "GET /admin/v2/namespaces/my-property/throttling_ns/dispatchRate HTTP/1.1" 200 123 "-" "Pulsar-Java-v2.11.0-SNAPSHOT" …
```

[fix][broker] Fix dispatch duplicated messages with `Exclusive` mode.

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

- Pulsar 2.9.x use BookKeeper 4.14.5
- BookKeeper 4.14.5 use RocksDB 6.16.4
- Pulsar 2.9.x uses RocksDB 6.10.2
In Pulsar packaging, it uses RocksDB 6.10.2 override 6.16.4, So in our image, BookKeeper uses RocksDB 6.10.2 instead of 6.16.4
Upgrade Pulsar broker-side RocksDB dependency to 6.16.4 to keep sync with BookKeeper.

[Branch-2.9]Upgrade rocksdb version to 6.16.4 to keep sync with bookkeeper

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/InMemoryRedeliveryTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/RedeliveryTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/RedeliveryTrackerDisabled.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/ExposeMessageRedeliveryCountTest.java

Reverts: #5881
The `redeliveryCount` was introduced in [PIP 22](https://github.com/apache/pulsar/wiki/PIP-22%3A-Pulsar-Dead-Letter-Topic) with this PR https://github.com/apache/pulsar/pull/2508. It is an extra field on a message that indicates how many times a message has been redelivered. In the original design, it was only incremented for shared subscriptions when the consumer sent `REDELIVER_UNACKNOWLEDGED_MESSAGES` to the broker.
In #5881, this field's logic changed so that it is incremented each time a broker delivers a message to a consumer (after the initial delivery). The problem with this logic is that it counts messages that are sent to a consumer's `receiveQueue`, but not actually received by the client application, as "delivered" messages. This is especially problematic for …

[fix][broker] Revert 5895: fix redeliveryCount

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerFactoryMXBean.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryMBeanImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheManagerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheManagerTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/RangeCacheTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/metrics/ManagedLedgerCacheMetrics.java
site2/docs/reference-metrics.md

Fixes https://github.com/apache/pulsar/issues/16584
With the `RangeCache`, it is hard to reason about its behavior other than cache hits/misses or the cache's size hitting the limit and triggering a size based eviction. This PR adds 3 new metrics to help provide additional insight into the cache's behavior. It adds `pulsar_ml_cache_inserted_entries_total`, `pulsar_ml_cache_evicted_entries_total`, and `pulsar_ml_cache_entries`.
* Add new metrics for cache insertion, eviction, and current number of entries.
* Add new methods to the `ManagedLedgerFactoryMXBean` interface.
* Update several method return values in the `RangeCache`.
* Update tests.
This change is covered by modified tests that already existed.
There is a breaking change to the `RangeCache` class for the `clear` and the …

[enh][broker] Add metrics for entry cache insertion, eviction

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

When we call `cursor.close` will trigger cursor info persistent, there are two steps to persistence( ensure as little data loss as possible ):
-  try to persist to Bookie
-  if Bookie doesn't work, try to persist to ZK
----
Here's how we want it to work:
1. change state to `closing`
2. try to persist to BK
3. if Bookie doesn't work, try to persist to ZK
4. change state to `closed`
----
(<strong>High light</strong>)But there's something wrong with this code,  here's how it exactly works:
1. change state to `closing`
2. try to persist to BK
3. (<strong>High light</strong>) race condition
3-1. if Bookie doesn't work, try to persist to ZK. (<strong>High light</strong>) this command asynchronously works on thread `bk client worker`, and will fail caused of cursor state check(see code below). …

[fix][broker]Persist cursor info error when cursor close

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

* Maybe this modification should be part of  https://github.com/apache/pulsar/issues/12629 .  As described in the PIP document "These metadata could be set during topic creation and also updated.",  we have implemented the `creation` method, but have not implement  the `updated` method. 
* This PR will implement the topic meta update
* Add a admin api `updateProperties`
- Add UT `org.apache.pulsar.broker.admin.AdminApi2Test#testUpdatePartitionedTopicProperties`
- Add UT `org.apache.pulsar.broker.admin.AdminApi2Test#testUpdateNonPartitionedTopicProperties`

[broker][admin]Add api for update topic properties

---

.github/workflows/ci-documentbot.yml

Randome pick a PR, you will see the docbot CI is always cancelled.
Root cause is using `${{ github.workflow }}-${{ github.ref }}` as id to cancel the docbot task.
The `github.ref` value is always what the PR wants to submit to the base branch like:
```
Canceling since a higher priority waiting request for 'Documentation Bot-refs/heads/master' exists
```
So you saw always cancelled, right now append a PR number to try to fix this issue.
- Append the `github.event.number` to `concurrency.group` value
*(or)*
*(or)*
This change added tests and …

[fix][ci] Fix docbot always cancelled

---

pulsar-config-validation/pom.xml
pulsar-functions/instance/pom.xml
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
pulsar-functions/runtime/pom.xml
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java
pulsar-functions/secrets/pom.xml
pulsar-functions/utils/pom.xml
pulsar-functions/worker/pom.xml
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/SchedulerManager.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/WorkerImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/scheduler/RoundRobinScheduler.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionRuntimeManagerTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/dlog/DLInputStreamTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/executor/MockExecutorController.java
pulsar-metadata/pom.xml
pulsar-package-management/core/pom.xml

Master Issue: https://github.com/apache/pulsar/issues/12271
Applied to following modeules:
pulsar-config-validation
pulsar-functions
pulsar-metadata
pulsar-package-management
*(or)*
*(or)*
*(example:)* …

[Improvement] Apply maven modernizer to remaining modules.

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ServiceChannelInitializer.java

It is necessary to dynamically configure the netty frame size when there are big messages.
add max size of messages property in proxy configuration

[improve][proxy]configure frame size dynamically in proxy

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProduceWithMessageIdTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
pulsar-common/src/main/proto/PulsarApi.proto

Master Issue: #16153
See PIP-180 #16153. Shadow topic requires message id from shadow replicator to update LAC and populate entry cache.
Add `message_id` in CommandSend.
- ProduceWithMessageIdTest
- **The public API: (yes)**
This new field is for …

[feat][client]PIP-180 ShadowTopic - Part II - Add support for messgae_id in CommandSend

---

site2/docs/client-libraries-java.md
site2/website/versioned_docs/version-2.10.0-deprecated/client-libraries-java.md
site2/website/versioned_docs/version-2.10.1-deprecated/client-libraries-java.md

Fixes #16449
The add `ackReceiptEnabled` doc is not correct in PR #16465, need to correct the docs.
Fix `ackReceiptEnabled` doc.

[fix][doc] fix `ackReceiptEnabled` doc

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Functions.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v3/FunctionsApiV3Resource.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/service/api/Functions.java

After adding a nar to the `functions` directory, it is handy to be able to reload the built-in functions in the broker or function worker.
This is the same as `pulsar-admin sinks/sources reload` but for functions.
* Add HTTP endpoint `/admin/v3/functions/builtins/reload` to reload the built-in functions.
* Add Java PulsarAdmin  methods `reloadBuiltInFunctions` and `reloadBuiltInFunctionsAsync` to reload the built-in functions.
* Add CLI command `functions reload` to reload the built-in functions.
yes
- The public API: yes
- The rest endpoints: yes
- The admin cli options: yes
the doc is autogenerated
(Your PR …

[feature][functions] Add HTTP API and CLI to reload built-in functions

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml

JLine3 doesn't work well with current JNA version on Windows. It's a requirement for https://github.com/apache/pulsar/pull/17243
* Upgrade JNA from 4.2.0 to 5.12.1
Note that this lib is also used by the ZK cli. I tested it and it still works correctly after the upgrade.

[improve][dependency] Upgrade JNA to 5.12.1

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java

master branch is broken.
- #17195 changed the method signature that #16605 depended upon
- pass `null` to new argument introduced by #17195

[fix][broker] Fix broken build caused by conflict between #17195 and #16605

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java

When the leader broker is closing, and it will release the ownership of its bundles first. The client will redo topic lookup , and this broker will handle it, resulting in unexpected results. For instance, some unassigned bundles maybe are taken ownership by itself again, but the broker can not server the bundles due to it is closing . see the screenshot log. 
Therefore, it is necessary to check the status of the broker when handling lookup requests.
- Check Pulsar Service state when handling lookup request.
- Add 'Init' state as running state in `PulsarService` since `PulsarFunctionWorker` have to lookup topic when broker is starting.
https://github.com/apache/pulsar/blob/4a28c087fe1308ea4eabc104b3d4889b47316afe/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L855- …

[improve][broker]fix broker irrational behavior when it is closing

---

conf/standalone.conf
pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandaloneBuilder.java
pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandaloneStarter.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/conf/InternalConfigurationData.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PulsarWorkerService.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerUtils.java
pulsar-package-management/bookkeeper-storage/src/main/java/org/apache/pulsar/packages/management/storage/bookkeeper/BookKeeperPackagesStorage.java
pulsar-package-management/bookkeeper-storage/src/main/java/org/apache/pulsar/packages/management/storage/bookkeeper/BookKeeperPackagesStorageConfiguration.java
pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/BookKeeperPackagesStorageTest.java

The `zookeeperServers` already deprecated, we recommend  `metadataStoreUrl`. 
In `BookKeeperPackagesStorage`, it still use `zookeeperServers`, didn't compatible with `metadataStoreUrl`, so it will throw NPE.
I notice that there are two PRs already fix it, but it only in Branch-2.11, so move it to Branch-2.10.
#14384, #14595

[Branch-2.10] [fix] [broker] Fix bookeeper packages npe

---

src/owasp-dependency-check-false-positives.xml

Owasp check fails with 
```
One or more dependencies were identified with known vulnerabilities in Pulsar :: Distribution :: Server:
netty-tcnative-boringssl-static-2.0.52.Final-osx-x86_64.jar (pkg:maven/io.netty/netty-tcnative-boringssl-static@2.0.52.Final, cpe:2.3:a:chromium_project:chromium:2.0.52:*:*:*:*:*:*:*) : CVE-2011-1797
```
It's clearly a false positive https://github.com/jeremylong/DependencyCheck/issues/4776
* Suppress the violation

[cleanup][owasp] Supress false positive netty-tcnative

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxPowerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java

The branch-2.9 test is broken. see [error](https://github.com/apache/pulsar/runs/8062338443?check_suite_focus=true).
```
Error:  Tests run: 75, Failures: 30, Errors: 0, Skipped: 31, Time elapsed: 5.748 s <<< FAILURE! - in org.apache.pulsar.broker.service.ServerCnxTest
Error:  testHandleAuthResponseWithoutClientVersion(org.apache.pulsar.broker.service.ServerCnxTest)  Time elapsed: 0.007 s  <<< FAILURE!
org.mockito.exceptions.base.MockitoException: 
Cannot mock/spy class org.apache.pulsar.common.api.proto.CommandAuthResponse
Mockito cannot mock/spy because :
- final class
at org.apache.pulsar.broker.service.ServerCnxTest.testHandleAuthResponseWithoutClientVersion(ServerCnxTest.java:1968)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at …
```

[branch-2.9] Support mock final class with `PowerMockito`

---

pulsar-sql/presto-distribution/pom.xml

When check the license of branch-2.11, I find there are two versions of `jsr305`:
```
- jsr305-2.0.1.jar
- jsr305-3.0.2.jar
```
`2.0.1` depends from `objectsize`, so when build presto-distribution, the version of `jsr305` is `2.0.1`
`3.0.2` depends from `spotbugs`, so when build presto-pulsar, the version of `jsr305` is `3.0.2`
So we have to exclude the lower version.

[fix][sql] Exclude jsr305 from objectsize.

---

pulsar-sql/presto-distribution/LICENSE

When run license check, it throw the following exception :
```
amqp-client-5.5.3.jar unaccounted for in lib/presto/LICENSE
commons-collections4-4.4.jar unaccounted for in lib/presto/LICENSE
jsr305-2.0.1.jar unaccounted for in lib/presto/LICENSE
log4j-api-2.18.0.jar unaccounted for in lib/presto/LICENSE
log4j-core-2.18.0.jar unaccounted for in lib/presto/LICENSE
log4j-slf4j-impl-2.18.0.jar unaccounted for in lib/presto/LICENSE
metrics-jmx-4.1.12.1.jar unaccounted for in lib/presto/LICENSE
netty-transport-native-epoll-4.1.77.Final.jar unaccounted for in lib/presto/LICENSE
rocksdbjni-6.29.4.1.jar unaccounted for in lib/presto/LICENSE
rxjava-3.0.1.jar unaccounted for in lib/presto/LICENSE
listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar mentioned in lib/presto/LICENSE, but not …
```

[branch-2.11][license] Fix license issue.

---

pulsar-client-cpp/lib/ReaderImpl.cc

Fixes #14848
We should execute `callback` before executing `readerCreatedCallback_`, otherwise, we may get the wrong consumers size. More see:
https://github.com/apache/pulsar/blob/e23d312c04da1d82d35f9e2faf8a446f8e8a4eeb/pulsar-client-cpp/lib/ReaderImpl.cc#L84-L92
https://github.com/apache/pulsar/blob/c48a3243287c7d775459b6437d9f4b24ed44cf4c/pulsar-client-cpp/lib/ClientImpl.cc#L250-L254
execute `callback` before executing `readerCreatedCallback_`

[fix][client-c++] Fix wrong consumers size

---

pom.xml

The master branch build is broken in CI after #17270 changes. The rat check fails with 2 errors.
`**/*.md` files should be excluded from license checks.

[fix][CI] Fix broken CI build: exclude **/*.md files from license and rat check

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java

when `redeliveryCount > deadLetterPolicy.getMaxRedeliverCount()`, the batch message can also be received by the client.
This test passed before because `removeExpiredMessagesFromQueue` removed messages from `incomingMessages`
add the available permits when `redeliveryCount > deadLetterPolicy.getMaxRedeliverCount()` send message to deadLetter topic
1. 
```
redeliveryCount > deadLetterPolicy.getMaxRedeliverCount()
```
don't invoke `executeNotifyCallback(message);`
2. when `redeliveryCount > deadLetterPolicy.getMaxRedeliverCount()` send message to deadLetter topic, increase the available permits
- …

[fix][client] Fix the message present in incoming queue after go to DLQ

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java

See https://github.com/apache/pulsar/issues/14365

[improve][broker][PIP-149]make deletePersistence method async in Namespaces

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerMBeanImpl.java

`ManagedLedgerMBeanImpl` will execute method `refreshStats` immediately after it is created, but if `refreshStats` is executed too fast, will throws `IllegalArgumentException`.
- `refreshStats` execute immediately
https://github.com/apache/pulsar/blob/fd9489771959f3e722656e4b70d4bd891a13f690/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java#L198-L199
- throw `IllegalArgumentException` if executed too fast
https://github.com/apache/pulsar/blob/1de80e0684ec5c13b6edcd217af62d74d8677f04/pulsar-common/src/main/java/org/apache/pulsar/common/stats/Rate.java#L62-L64
`ManagedLedgerMBeanImpl.refreshStats` will immediatelly execute after create
Skip refreshing stats, just like `ManagedLedgerFactoryMBeanImpl.refreshStats` …

[fix][broker]ManagedLedger metrics fail cause of zero period

---

bin/pulsar-admin-common.cmd
bin/pulsar-admin.cmd
bin/pulsar-client.cmd
bin/pulsar-perf.cmd
bin/pulsar-shell.cmd
distribution/shell/src/assemble/shell.xml
pom.xml
pulsar-client-tools/pom.xml
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/PulsarShell.java

Fixes #16688
TL; DR - now Pulsar shell works on Windows
Currently pulsar shell is only runnable on Unix system because the entry point script is written in bash.
1. Provided a new `pulsar-shell.cmd`, `pulsar-admin.cmd`, `pulsar-client.cmd` and `pulsar-perf.cmd` files (written in Windows Command Prompt language) that starts their processes
It implements the exact same configurations from the current pulsar-shell, even the java8 detection. The only thing not implemented is the on-the-fly compile. Actually, the batch script only work if you unzip the distro tarball. Running it from the codebase (so without the `lib` dir) is not supported (and it's okay since currently it's not even possible develop Pulsar on a Win machine)
2. Added the jna lib to make the jline command prompt display colors …

[improve][cli] Pulsar shell, Pulsar admin, Pulsar client and Pulsar perf: support for Windows

---

pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/KinesisSinkTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java

In the kinesis tests we use the latest tag of the localstack docker image. Now kinesis tests are failing in this way
```
java.util.concurrent.ExecutionException: software.amazon.awssdk.core.exception.SdkClientException: Unable to parse date : 1.661885385488E9
```
* Set version to 1.0.4 which works correctly
I suspect that the issue has been caused by a large refactor in the localstack repo around kinesis https://github.com/localstack/localstack/pull/6166
I opened an issue in the localstack repo https://github.com/localstack/localstack/issues/6787

[fix][test] KinesisSink test: use fixed version of localstack docker image

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/PolicyName.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TopicPolicies.java

Master Issue: https://github.com/apache/pulsar/issues/16153
Source topic need to know its shadow topic list to start the ShadowReplicators.
Note: Shadow topic also need to know its source topic, but it can't implemented with topic policy. Because topic policy can only guarantee eventual consistency and shadow topic must know its source topic during initialization. 
Add shadowTopics in TopicPolicy and create/delete/get commands in admin clients.
- TopicPoliciesTest#testShadowTopic
- **The public API**: (yes)
- The wire protocol: …

[feat][broker]PIP-180 ShadowTopic - Part III - Add shadowTopics in TopicPolicy

---

site2/docs/client-libraries-java.md
site2/website/versioned_docs/version-2.10.x/client-libraries-java.md
site2/website/versioned_docs/version-2.9.x/client-libraries-java.md

The Pulsar documentation is missing information and usage examples about `ProducerInterceptor` and `ConsumerInterceptor`.
Added sections for both interceptor types to the java-client documentation.
(Your PR needs to update docs …

[docs][java-client] Add sections for interceptor usage

---

tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java

`testAutoSchemaFunction` is flaky because `ensureSubscriptionCreated` will create a consumer to create the subscription.
By doing so it also adds a schema on the topic.
But that leads to a race when the function consumer uses AUTO_SCHEMA because the new schema is seen as incompatible if the function consumer is already subscribed (We get IncompatibleSchemaException : Topic does not have schema to check).
Note: the issue with the IncompatibleSchemaException is a bug and will be fixed in another PR (see issue https://github.com/apache/pulsar/issues/17354)
Move the call to `ensureSubscriptionCreated` before creating the function.
This change is already covered by existing tests, such as `PulsarFunctionsTest`
no
- Dependencies (does it add …

[fix][flaky] Fix flakyness in testAutoSchemaFunction

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherBlockConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/DispatcherBlockConsumerTest.java

```
java.lang.AssertionError: expected [600] but found [265]
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at org.apache.pulsar.client.api.DispatcherBlockConsumerTest.testBrokerDispatchBlockAndSubAckBackRequiredMsgs(DispatcherBlockConsumerTest.java:1036)
```
In the scope of this test is important to not group acks because the ack for messages may happens after receiving a new message from the topic. If the acks are sent in batch it may happen that the dispatcher is still blocked until it receives the batched acks and the …

[fix][test] Fix flaky test: PersistentStreamingDispatcherBlockConsumerTest.testBrokerDispatchBlockAndSubAckBackRequiredMsgs

---

README.md

Different pulsar version have different JDK version requirement.
Doc updates.

[doc] Add JDK version requirement to build Pulsar

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ParserProxyHandler.java

Fixes #17171
When field 'producer_name' is not set, producer info logging correctly
Set empty string producer_name when field 'producer_name' is not set

[fix][proxy] fix producer info logging fails when proxyLogLevel > 0

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfigTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchExtractTests.java
site2/docs/io-elasticsearch-sink.md

Add the ability to add the key fields to the document. With this option the resulting document will contain both key and value fields if schema is enabled and the message is JSON/Avro format.
* New option `copyKeyFields` default to `false`. If true, the key fields will be copied to the document.
In order to be activated it's required to:
- set `copyKeyFields` to true
- set `schemaEnable` to true
- the message format be in JSON or AVRO
- message value is not null

[feat][connector] ElasticSearch Sink: add a option to copy key fields into the value

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiMultiBrokersTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ExclusiveProducerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicsConsumerImplTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/topics/TestTopicDeletion.java

Forced delete of partitioned topic with active consumer on the namespace where the topic autocreate is enabled leaves the namespace in the state where one cannot create partitioned topic with the same name (because it exists already) and cannot delete it (because it does not exist at the same time)
Don't allow deletion in this case until all consumers/producers disconnected.
I experimented with option to not allow autocreate after deletion of partitioned topics but that ends up in the reasons that led to https://github.com/apache/pulsar/pull/14920 + tricky corner cases between metadata updates.
nothing AFAICT
- The …

[fix] Combination of autocreate + forced delete of partitioned topic with active consumer leaves topic metadata inconsistent.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java

Npe thrown by `getBundleRange `
```
org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: 
Message: Cannot invoke "org.apache.pulsar.common.naming.NamespaceBundle.getBundleRange()" because the return value of "org.apache.pulsar.broker.admin.impl.NamespacesBase.findHotBundle(org.apache.pulsar.common.naming.NamespaceName)" is null
Stacktrace:
java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.common.naming.NamespaceBundle.getBundleRange()" because the return value of "org.apache.pulsar.broker.admin.impl.NamespacesBase.findHotBundle(org.apache.pulsar.common.naming.NamespaceName)" is null
at org.apache.pulsar.broker.admin.impl.NamespacesBase.getBundleRange(NamespacesBase.java:1150)
at …
```

[fix][broker] Fix Npe thrown by splitBundle

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TopicOperation.java

This pr comes from https://github.com/apache/pulsar/pull/17238#discussion_r953462785 and its purpose is to remove the specified key of properties on the topic.
- Add cmd to remove topic properties

[broker][admin] Add cmd to remove topic properties

---

site2/docs/admin-api-namespaces.md

Fixes #17413 
Fix rendering problems of some REST API tabs.
Remove redundant `, rendering correctly:

[fix][doc] REST API render mistake

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientDeduplicationFailureTest.java

This problem may be caused by #16605.
- Fix `ClassCastException`
*(or)*
*(or)*
*(example:)* …

[fix][test] Fix `ClientDeduplicationFailureTest.testClientDeduplicationWithBkFailure`

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java

Since Pulsar is a fully asynchronous project, we need to avoid using thread-blocking methods.
Also, we can see https://github.com/apache/pulsar/issues/14365
- Improve `replicatorDispacherRate` relative endpoint to pure async. …

[Improve][broker] Improve `replicatorDispacherRate` endpoint to pure async.

---

distribution/shell/src/assemble/shell.xml
docker/pulsar/Dockerfile

After #16688 (only for the master branch) all the new Windows scripts are included in the docker image unnecessarly.
Users that want to use the CLI commands can still download the tarballs (server or pulsar-shell)
* Remove *cmd files in the Dockerfile
* Add .cmd files to the pulsar-shell tarball

[fix][cli] Exclude windows script from the docker image

---

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/OutputRecordSinkRecord.java

OutputRecordSinkRecord returns the record schema and value instead of the one passed to the constructor.
It's a problem when a Sink has a transform Function where the record value is re-encoded.
Use the value and schema set by constructor.
fix

[fix][connectors] Fix OutputRecordSinkRecord getValue and getSchema

---

pulsar-client-tools-test/pom.xml
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/utils/CustomCommandFactoryProvider.java

In #17158 the new CLI extensions framework read the nar files from `cliExtensions` by default. This is a bit unusual since the similar nar locations are all lower-case (`filters`, `proxyextensions`, `protocols`...)
Since it hasn't been released yet, we are still in time to change it
* Move from `cliExtensions` to `cliextensions`

[improve][cli] CLI extensions: rename default location to 'cliextensions'

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java

When creating consumer, I find that using common pool thread to create the cursor:
```
2022-09-01T21:12:32,515 - INFO  - [bookkeeper-ml-scheduler-OrderedScheduler-0-0:BrokerService$2@1472] - Created topic persistent://prop/ns-test/topic-1 - dedup is disabled
2022-09-01T21:12:32,528 - INFO  - [ForkJoinPool.commonPool-worker-1:ManagedLedgerImpl@961] - [prop/ns-test/persistent/topic-1] Creating new cursor: sub-2
2022-09-01T21:12:32,529 - INFO  - [ForkJoinPool.commonPool-worker-1:ManagedCursorImpl@631] - [prop/ns-test/persistent/topic-1] Cursor sub-2 recovered to position 3:-1
```
And then find that the thread switches in  `BookkeeperSchemaStorage`.   It's introduced by https://github.com/apache/pulsar/pull/2148.   I think it's no need to use `handleAsync` there.
After changing to `handle`, I …

[improve][broker] Using `handle` instead of `handleAsync` to avoid using common pool thread

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthenticatedProducerConsumerTest.java

Steps to reproduce:
1. grant permission for role1 on topic  "persistent://public/default/test"
2. revoke permission for role1 on topic "persistent://public/default/test"
3. zk remain empty record, as shown in the picture
If the topic has no roles after revoke permission, remove topicKey from TopicAuthenticationMap 
This change is already covered by existing tests, such as *PersistentTopicsTest*.

[improve] clean the empty topicAuthenticationMap in zk when revoke permission

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerMemoryLimitTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/BatchMessageContainerImplTest.java

Fix client memory limit currentUsage and semaphore release when batchMessageContainer add message. 
If `BatchMessageContainerImpl's` add method throw an Exception while adding the first messages, then the `memoryLimitController` `currentUsage` and `MaxQueueSize` `semaphore` not release before discard message.
https://github.com/apache/pulsar/blob/b58439e835ea9c4f492a8c05bdd99047c1233bc2/pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java#L109-L113
1. Release `memoryLimitController` `currentUsage` and `MaxQueueSize` `semaphore`  before discard message.
2. add some unit test.

[fix][broker]Fix memoryLimitController currentUsage and MaxQueueSize semaphore leak when batchMessageContainer add message exception

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithJwtAuthorizationTest.java

related to #16768
should not fail a request that attempts to remove permission from a partition of a topic that was not already granted permission
- The public API:  no
- The schema: no 
- The default values of configurations:  no
- The wire protocol:  no

[fix][broker] fix can not revoke permission after update topic partition

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java

When we call broker#getTopic to get topics, the same topic requests twice, once with the domain and once without the domain, then there will be 2 instances in `topics`. Both instances are associated with the same ManagedLedger. 
Because we put the key `persistent://tn/ns/xxx` and `tn/ns/xxx` into the `topics`.  In this case, when we close the topic, another key related to the topic and the ManagedLedger may cause creating producer/consumer failure. see the below test.

[improve][broker] Using TopicName instead of String as the parameter for `getTopic`.

---

src/owasp-dependency-check-suppressions.xml

This patch cherry-picks #17458 to branch-2.11.
cc @Technoboy-

[improve][sec][BP-2.11] suppress CVE-2021-3563 of openstack-keystone-2.5.0  (#17458)

---

bin/pulsar
conf/log4j2.yaml
distribution/server/pom.xml
distribution/server/src/assemble/LICENSE.bin.txt

Fixes #15392
This reverts commit 1e9a1f087e8c6fd9e78f6e3f0635113ba7927bbf.
When using a `log-topic` in Functions, an appender is added to all loggers to send the logs with the Pulsar client.
To prevent sending logs from the framework, the `LogAppender` is added before the function processing (`JavaInstance::handleMessage`) and removed just after.
This is a problem because since #15188, the logs are sent asynchronously and sometimes we remove the appender before the log is processed by the `LogAppender`.
And this is the reason why we see flakyness in `testJavaLoggingFunction` because me miss some logs.
See also #17471 that proposes another way to solve the issue but that maybe deserves more discussions.
This reverts commit 1e9a1f087e8c6fd9e78f6e3f0635113ba7927bbf.
This change is already …

[fix][functions] Revert "Enable Log4j2 async loggers (#15188)"

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherBlockConsumerTest.java

In https://github.com/apache/pulsar/pull/17161 we moved that class out of the flaky suite because we fixed that single test. But the class is still flaky for this test `testBrokerSubscriptionRecovery ` https://github.com/apache/pulsar/issues/17011
* Move the class to the flaky suite to unblock CI for other pulls

[ci] move back PersistentStreamingDispatcherBlockConsumerTest to the flaky suite

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java

Minor update for proxy `metadataStoreUrl` configuration
Current code of initializing the MetadataStoreUrl
```java
if (!isBlank(metadataStoreUrl)) {
// Use metadataStoreUrl from command line
config.setMetadataStoreUrl(metadataStoreUrl);
} else if (!isBlank(zookeeperServers)){
// Use zookeeperServers from command line if metadataStoreUrl is empty;
config.setMetadataStoreUrl(zookeeperServers);
} else {
// use "metadataStoreUrl" property in "proxy.conf".
}
```
is confusing because the final else is empty.
The priority should be :
1. command line parameters(`zookeeperServers` or `metadataStoreUrl`) have a higher priority than `proxy.conf`
2. if both `zookeeperServers` and `metadataStoreUrl` are provided from the command line, `metadataStoreUrl` has a higher priority
3. if neither …

[refactor][proxy] remove empty else code block when initialize setMetadataStoreUrl 

---

pulsar-client-cpp/lib/PeriodicTask.cc
pulsar-client-cpp/lib/ProducerImpl.cc
pulsar-client-cpp/lib/ProducerImpl.h

Fixes #17392
All timers in `ProducerImpl` are `std::shared_ptr` objects that can be
reset with `nullptr` in `ProducerImpl::cancelTimers`. It could lead to
null pointer access in some cases.
See
https://github.com/apache/pulsar/issues/17392#issuecomment-1233929427
for the analysis.
Generally it's not necessary to hold a nullable pointer to the timer.
However, to resolve the cyclic reference issue, #5246 reset the shared
pointer to reduce the reference count manually. It's not a good solution
because we have to perform null check for timers everywhere. The null
check still has some race condition issue like:
Thread 1:
```c++
if (timer) {  // [1] timer is not nullptr
timer->async_wait(/* ... */);  // [3] timer is null now, see [2] below
}
```
Thread 2:
```c++
timer.reset();  // [2]
```
The …

[fix][cpp] Fix potential segfault when resending messages

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawReaderTest.java

Fixes #17365
The batchingMaxPublishDelay default value is 1ms, it is too short, so change the batchingMaxPublishDelay value to 1min to ensure no individual message was sent.
https://github.com/apache/pulsar/blob/c48a3243287c7d775459b6437d9f4b24ed44cf4c/pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawReaderTest.java#L295-L306

[fix][flaky-test] Fix RawReaderTest.testFlowControlBatch

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerException.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImplV2.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderTest.java

This pr cherry-pick from #17056.

[Branch-2.10] [fix][ML] Fix offload read handle NPE.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java

Since Pulsar is a fully asynchronous project, we need to avoid using thread-blocking methods.
Also, we can see https://github.com/apache/pulsar/issues/14365
- Improve `backlogQuota` relative endpoint to pure async.
(Docs have …

[improve][broker] Improve `backlogQuota` endpoint to pure async.

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageWithBatchIndexLevelTest.java

Fixes 
- #17363
In this test:
1. `receive` and `ack` to make the num of un-ack messages to 16, and verify
2. `receive` and `negative` to make the num of un-ack messages to 0, and verify
3. `receive` to make the num of un-ack messages back to 16, and verify
<strong>(High light)</strong> But in step 2, there has race condition:
- `negative` will make the num of un-ack messages to 0
- `cmd-negative` will trigger another `cmd-receive which will make the num of un-ack messages back to 16, see [Code-1] below
- `cmd-receive` also will trigger another `cmd-receive which will make the num of un-ack messages back to 16, see [Code-2] below
- `receive` pops messages from the queue, when the queue is half empty, the next `receive` will be fired …

[fix][flaky-test]BatchMessageWithBatchIndexLevelTest.testBatchMessageAck

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java

We update some cache dynamic configurations, such as: managedLedgerCacheSizeMB=100, but after we restarted the broker, we found that the dynamically modified cache configuration on zookeeper was invalid, and the value configured in broker.conf took effect.
After restarting, the loading process of config is as follows:
1. Load the broker.conf file and initialize the ServiceConfiguration object;
2. Use the ServiceConfiguration object to build the ManagedLedgerStorage object. When building the managedLedgerClientFactory object, the cache configuration in managedLedgerFactoryConfig is initialized through the conf object:
https://github.com/apache/pulsar/blob/4b757cf9f9046c7143329156b1009fe43217eaea/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L742-L748 …

[fix][broker]After the broker is restarted, the cache dynamic configuration is invalid

---

pulsar-client-cpp/lib/c/c_Authentication.cc
pulsar-client-cpp/python/pulsar/__init__.py
pulsar-client-cpp/python/pulsar_test.py
pulsar-client-cpp/python/src/authentication.cc

Python misses the basic authentication.
Added `test_basic_auth` test to cover this  feature.
Add Python basic authentication documentation.

[feat][python] Add basic authentication

---

site2/docs/security-tls-authentication.md

Fix #11381
When using the TLS authentication, we need to enable the `tlsRequireTrustedClientCertOnConnect` in the config file, this config means the client must provide the TLS certificates.

[fix][doc] Add verifying the client cert

---

site2/docs/getting-started-docker.md
site2/docs/getting-started-helm.md
site2/docs/getting-started-home.md
site2/docs/getting-started-standalone.md

Fixes #17409.
For description, read the issue description and these two comments: https://github.com/apache/pulsar/issues/17409#issuecomment-1234964144 + https://github.com/apache/pulsar/issues/17409#issuecomment-1236839244.
cc @Anonymitaet @momo-jun @DaveDuggins @labuladong @merlimat @TheYonk

[improve][docs] Get started locally

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

Fixes #16082 
* The help option for set retention indicates `-t` option is `Retention time in minutes` but if no time unit is specified, it is assumed to be seconds.
* Updated description for time option and added unit test cases with default value (without time unit suffix) and with seconds time unit.
- Added unit tests for to `PulsarAdminToolTest` with and without time unit suffix. …

[improve][pulsar-client-tools][ISSUE-16082] - Updated set retention time description and added test cases including default time

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricStreams.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTestUtils.java
pulsar-broker/src/test/resources/prometheus_metrics_sample.txt
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyPrometheusMetricsTest.java

When a Pulsar topic is unloaded from a broker, certain metrics related to that topic will appear to remain active for the broker for 5 minutes. This is confusing for troubleshooting because it makes the topic appear to be owned by multiple brokers for a short period of time. See below for a way to reproduce this behavior.
In order to solve this "zombie" metric problem, I propose we remove the timestamps that get exported with each Prometheus metric served by the broker.
Since we introduced Prometheus metrics in #294, we have exported a timestamp along with most metrics. This is an optional, valid part of the spec defined [here](https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information). However, after our adoption of Prometheus metrics, the …

[fix][broker] Remove timestamp from Promtheus metrics

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java

When the `org.apache.pulsar.broker.admin.AdminResource#tryCreatePartitionAsync` method is called, the value of reusefuture passed in is null, which is a bit redundant and can be directly removed
The input parameter reusefuture and the judgment that the parameter is null are removed

[cleanup][broker] remove unnecessary parameters(reusefuture) and related logic

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java

In Pulsar shell the custom commands don't work (PIP-201)
```
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getConstructor(java.lang.Class[])" because the return value of "java.util.Map$Entry.getValue()" is null
at org.apache.pulsar.admin.cli.PulsarAdminTool.addCommand(PulsarAdminTool.java:218)
at org.apache.pulsar.admin.cli.PulsarAdminTool.setupCommands(PulsarAdminTool.java:164)
at org.apache.pulsar.admin.cli.PulsarAdminTool.setupAndRun(PulsarAdminTool.java:224)
at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:229)
at org.apache.pulsar.shell.AdminShell.runCommand(AdminShell.java:72)
at org.apache.pulsar.shell.PulsarShell.run(PulsarShell.java:436)
at org.apache.pulsar.shell.PulsarShell.run(PulsarShell.java:220)
at …
```

[improve][cli] Pulsar shell: fix custom commands execution

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/RangeSetWrapper.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenLongPairRangeSet.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/LongPairRangeSet.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentOpenLongPairRangeSetTest.java

Fixes #17451 
Improve the `ManagedCursorImpl.getNumberOfEntries()` if `isUnackedRangesOpenCacheSetEnabled=true`.
Since the `ConcurrentOpenLongPairRangeSet` has the ability to get the acked count for each Ledger,
the `ManagedCursorImpl` can avoid iterating each range to calculate the acked count. 
Make the `ConcurrentOpenLongPairRangeSet` able to get acked count.
Unit test for the new method introduced in `ConcurrentOpenLongPairRangeSet`
The `getNumberOfEntries()` change is already covered by the existing test
(Just an improvement for the presented implementation)

[improve][broker] Improve cursor.getNumberOfEntries if isUnackedRangesOpenCacheSetEnabled=true

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/NoopLoadManager.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/TopicStats.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java
site2/docs/admin-api-topics.md

Add a new field named `ownerBroker` to topic stats. This is the hostname and port of the broker owning the topic, separated by a colon. This is the same name as the ephemeral node registered under `/loadbalance/brokers/` on ZooKeeper.
```json
{
"msgRateIn" : 0.0,
"msgThroughputIn" : 0.0,
"msgRateOut" : 0.0,
"msgThroughputOut" : 0.0,
...
"compaction" : {
"lastCompactionRemovedEventCount" : 0,
"lastCompactionSucceedTimestamp" : 0,
"lastCompactionFailedTimestamp" : 0,
"lastCompactionDurationTimeInMills" : 0
},
"ownerBroker" : "localhost:8080"
}
```
This is useful to know which broker owns the topic.
Added a method `getLookupServiceAddress()` to the `PulsarService` class. This method returns a string consisting of the advertised address and web service port separated by a colon. The …

[improve][stats] Add ownerBroker field to topic stats

---

site2/website/versioned_docs/version-2.7.0/security-basic-auth.md
site2/website/versioned_docs/version-2.7.1/security-basic-auth.md
site2/website/versioned_docs/version-2.7.2/security-basic-auth.md
site2/website/versioned_docs/version-2.7.3/security-basic-auth.md
site2/website/versioned_docs/version-2.7.4/security-basic-auth.md
site2/website/versioned_docs/version-2.7.5/reference-configuration.md
site2/website/versioned_docs/version-2.7.5/security-basic-auth.md
site2/website/versioned_sidebars/version-2.7.0-sidebars.json
site2/website/versioned_sidebars/version-2.7.1-sidebars.json
site2/website/versioned_sidebars/version-2.7.2-sidebars.json
site2/website/versioned_sidebars/version-2.7.3-sidebars.json
site2/website/versioned_sidebars/version-2.7.4-sidebars.json
site2/website/versioned_sidebars/version-2.7.5-sidebars.json
wiki/release/release-process.md

Since 2.7.5 is released and the doc set is generated, request to pull 2.7.5-specific doc changes to the 2.7.5 doc set.
1. Sync doc changes implemented in https://github.com/apache/pulsar/pull/15818.
2. Sync the topic for the new feature "basic auth" implemented in https://github.com/apache/pulsar/pull/15734.
3. Fix the note layout in the release process topic.

[feature][doc] Sync 2.7.5 specific doc changes

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

variable `maxUnackedMessagesOnSubscriptionApplied` is useless in `PersistentTopic`
remove variable `maxUnackedMessagesOnSubscriptionApplied`

[cleanup][broker]remove unnecessary variable in PersistentTopic

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java

Fixes #17386
In this test, we expect it works like this: 
1. persistent broker data to ZK
2. receive notice: broker data changes, and refresh bundle data in memory 
3. persistent bundle data which already updated in memory to ZK
4. verify bundle data persist correctly
5. delete namespace
6. verify bundle data deleted
But the flow works like this:
1. persistent broker data to ZK
2. <strong> (High light) race condition </strong>
2-x. receive notice: broker data changes, and refresh bundle data in memory 
2-x. persistent bundle data to ZK ( If the data in memory is not updated, it will not be written to ZK )
3. ......
- guarantee `step-3` is always executed after `step-2`
- In this test, the original codes mock `ModularLoadManagerWrapper` to make `isCentralized` always return `true`. But …

[fix][flaky-test]NamespaceServiceTest.flaky/testModularLoadManagerRemoveBundleAndLoad

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DispatcherBlockConsumerTest.java

https://github.com/apache/pulsar/pull/17476 is useless because the test still run on the parent class group
* Move also DispatcherBlockConsumerTest to the flaky test suite

[ci] Move back DispatcherBlockConsumerTest to flaky suite

---

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java

Fixes #15392
When using a `log-topic` in Functions, an appender is added to all loggers to send the logs with the Pulsar client.
To prevent sending logs from the framework, the `LogAppender` is added before the function processing (`JavaInstance::handleMessage`) and removed just after.
This is a problem because since #15188, the logs are sent asynchronously and sometimes we remove the appender before the log is processed by the `LogAppender`.
And this is the reason why we see flakyness in `testJavaLoggingFunction` because me miss some logs.
This is also a problem when using an async Function that returns `CompletableFuture` where the execution of the Function will be done async and probably when the appender is removed.
I had a look and the framework only sends error logs. It may even be …

[fix][functions] Fix Java Function instance LogAppender missing logs

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerImplTest.java

We can see many logs like the following (not master since https://github.com/apache/pulsar/pull/16345 has changed to level to debug)
And it is easy to reproduce. You can just create a geo-replicated cluster
and produce the bytes messages.
It should be related to this change https://github.com/apache/pulsar/pull/17049 (haven't released) which fixed the replicated schema issue.
But we shouldn't get the schema from the broker for the BYTES schema, the client side will not cache the BYTES schema.
So, the replicator tries to get the schema again and again.
https://github.com/apache/pulsar/blob/eab2bb5fe089217d39a71965526729a3d93b74b6/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L756-L763
The fix is the same as the normal messages with AUTO_PRODUCE producer do …

[fix][broker] Fix the replicator unnecessary get schema request for BYTES schema

---

.asf.yaml

Following the action plan defined in https://lists.apache.org/thread/yh72bmlf2w97593c5d5pqf3jz1ldb501 .
A lazy consensus was reached on this matter to fix CI following the action plan.
We need to temporary unblock changes to make the CI more stable
* Keep only the build as a required workflow

[ci] Temporarily remove required jobs to unblock CI

---

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionLocalRunTest.java
pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java

Master Issue: https://github.com/apache/pulsar/issues/16739
This adds support for Transform Function in LocalRunner
see below
* Run testPulsarSinkWithFunction
no
(Docs …

[feature][connectors][PIP-193] Support Transform Function with LocalRunner

---

.github/workflows/ci-pulsarbot.yaml

Currently build jobs in the "Pulsar Bot" workflow will get triggered for all issue/PR comments. This wastes resources since the build jobs will get added to the build queue and this consumes quota.
The "Pulsar Bot" workflow can be optimized to save CI resources.
- move the filter from the build step to the build job
- only start the build job if the comment includes "/pulsarbot"
- no need to checkout code
- no need to run the tune VM action

[improve][CI] Optimize "Pulsar Bot" workflow

---

.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

See https://lists.apache.org/thread/p7rb04vf1mt0kk3v2r7xl9dvb3zkhtxf
Moving flaky suites out of the Pulsar CI will reduce the amount of re-run jobs when triggered by the pulsarbot. For example, if a non flaky suite fails and a contributor trigger the pulsarbot, also the flaky suite is triggered. Extracting to another workflow, will give the possibility to committers to re-run only the non-flaky failed jobs. 
- Extracted flaky suite in a dedicated workflow

[ci] Extract FLAKY tests suite to a dedicated workflow

---

pulsar-client-cpp/.gitignore
pulsar-client-cpp/examples/CMakeLists.txt
pulsar-client-cpp/examples/SampleAsyncConsumerCApi.c
pulsar-client-cpp/include/pulsar/c/consumer.h
pulsar-client-cpp/lib/c/c_Consumer.cc
pulsar-client-cpp/tests/CMakeLists.txt
pulsar-client-cpp/tests/c/c_BasicEndToEndTest.cc

Master Issue: [#14452](https://github.com/apache/pulsar/issues/14452)
I want to rewrite the pulsar-client-node `receive` method to rely exclusively on async operations rather than worker threads.
However, an async receive function is not defined currently in C API.
* Define `pulsar_consumer_receive_async` and `pulsar_receive_callback` to use async receive operation in C API
This change is already covered by existing tests, such as *C++ tests*.
- https://github.com/apache/pulsar/blob/66765afce540998cbc26cda62eb044c947902b21/pulsar-client-cpp/include/pulsar/c/consumer.h#L36
- …

[feat][cpp] Add async receive function to C API

---

.asf.yaml

Add back the protection to the master branch. Basically it reverts https://github.com/apache/pulsar/pull/17547 but using the new job created in https://github.com/apache/pulsar/pull/17541

[ci] Enable required checks status for pulls to the master branch

---

.github/PULL_REQUEST_TEMPLATE.md

1. Highlight to retain the documentation section so that committers can correct it if necessary simply with UI.
2. Few people edit the "affect one of the following parts". Change it to checkboxes for easily applying.
3. Comment out some placeholder.

[improve][misc] Pull request template

---

.github/workflows/ci-owasp-dependency-check.yaml

Branch 2.11 is not included in the owasp check 
Added it to the matrix

[ci] Add branch-2.11 to periodic owasp check

---

.github/workflows/ci-cpp-build.yaml
.github/workflows/ci-cpp.yaml
.github/workflows/ci-documentbot.yml
.github/workflows/ci-go-functions.yaml
.github/workflows/ci-maven-cache-update.yaml
.github/workflows/ci-owasp-dep-check.yaml
.github/workflows/ci-owasp-dependency-check.yaml
.github/workflows/ci-pulsarbot.yaml
.github/workflows/ci-stale-issue-pr.yaml
.github/workflows/pulsar-ci.yaml

Fixes #17560 
It's better to have control over the OS used in the CI in order to explicitly handle upgrades
* Moved ubuntu-latest to ubuntu-20.04
* Moved macos-latest to macos-11

[improve][ci] Replace latest os images with fixed ones (ubuntu and macos)

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java

If `refreshTopicPoliciesCache(msg)` throws any RuntimeException, the policy reader will stop to read messages anymore.
Move `refreshTopicPoliciesCache` to be execute into `thenAccept`.

[fix][broker] Fix potential exception causing the reader to be unable to continue reading

---

.github/workflows/ci-cpp-build.yaml
.github/workflows/ci-cpp.yaml
.github/workflows/ci-go-functions.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

Related to #17567. Post commit builds are triggered for every commit in the master branch and 2.11. Nobody look at them since we validate the changes in the pull. Removing these builds will help a lot reducing the CI load.
* Removed the push trigger and added the `workflow_dispatch`. In this way it's possible to manually run workflows [in this way](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)

[improve][ci] Remove post commit builds and add manual workflows trigger

---

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java
pulsar-client-tools/src/test/java/org/apache/pulsar/shell/PulsarShellTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/PulsarClientImplTest.java

Master Issue: #16912
Remove `WhiteBox` usage in `pulsar-client` and `pulsar-client-tools`. We then have only usages in `pulsar-broker`, `pulsar-io-elastic-search`, and `testmocks`.
cc @nicoloboschi @lhotari @Shoothzj @eolivelli 

[improve][misc] reduce WhiteBox usage

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java

See https://github.com/apache/pulsar/issues/14365

[improve][broker][PIP-149]make setPersistence method async in Namespaces

---

testmocks/src/main/java/org/apache/zookeeper/MockZooKeeper.java

[improve][test] remove WhiteBox on MockZooKeeper

---

.github/workflows/pulsar-ci.yaml

Fixes #17583 
Pulsar CI is broken since "Pulsar CI checks completed" runs too early.
There's another problem that disk space runs out in "Build Pulsar docker image" with error message 
```
Error response from daemon: write /var/lib/docker/tmp/docker-export-3539721826/b4b6ffd2e938fa5512aa646b2c22044e3e0b14e74d3dc8374a9b3723a7235c53/layer.tar: no space left on device
```
- remove "if: always()" since it caused the job to run also when something failed
- release disk space in "Build Pulsar docker image" build job before exporting the docker image 

[fix][CI] Don't run "Pulsar CI checks completed" too early and fix disk space issue in saving docker image 

---

.github/workflows/ci-cpp-build.yaml
.github/workflows/pulsar-ci.yaml

Fixes #17558
There's no need to trigger the build on MacOS for cpp-only changes.
- Skipped the MacOs build in case of cpp-only change
- Improved the name of non required-checks to a friendly name.

[improve][ci] Skip MacOS build for cpp-only changes

---

.github/workflows/pulsar-ci.yaml

- The "Pulsar CI checks completed" gets run too early also with #17584 changes
- another solution is needed to make it work as expected
- use `if: always()` and a solution where each required build is checked explicitly in a bash script. If the requirements aren't fulfilled, the script will fail with error code 1.

[fix][CI] Follow-up fix for don't run "Pulsar CI checks completed" too early

---

.github/ISSUE_TEMPLATE/flaky-test.yml

The ending delimiter for a comment in the flaky test issue template is invalid.
Fix the invalid delimiter: replace `->` with `-->`

[fix][misc] Fix invalid comment ending delimiter in flaky test issue template

---

README.md

1. We don't run Pulsar CI for the master branch, so although we can add a badge for it [![ci](https://github.com/apache/pulsar/actions/workflows/pulsar-ci.yaml/badge.svg)](https://github.com/apache/pulsar/actions/workflows/pulsar-ci.yaml), it's inaccurate.
2. Docker build workflow name has been changed. Also, the workflow doesn't reflect a useful status. Replace it with docker pull statistics.
cc @lhotari @Anonymitaet

[improve][misc] CI status on README.md

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

* Only create extended partitions when update partion number. It' useful for topics having huge partitions when updating partitions
* Also check number of new partitions must be greater than existing number of partitions
- Add more test in `PersistentTopicsTest#testUpdatePartitionedTopic`

[improve][broker]Only create extended partitions when updating partition number

---

pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApi2Test.java

Fixes https://github.com/apache/pulsar/issues/16854
cherry-pick: https://github.com/apache/pulsar/pull/13644
It seems some test cases like `**/*Test2.java` aren't run on the default test lifecycle.
This issue is caused by https://github.com/apache/pulsar/pull/10148. I'd like to fix it.
Originally:
* Rename test file name to `**/*Test.java`
* Fix some codes to follow changes
- https://github.com/apache/pulsar/pull/12687
- https://github.com/apache/pulsar/pull/11693
- https://github.com/apache/pulsar/pull/12663
- https://github.com/apache/pulsar/pull/12749
- https://github.com/apache/pulsar/pull/11640
Additionally:
* Fix conflict and keep existing changes
- https://github.com/apache/pulsar/pull/14657/files#diff-8696b1e2ba4ee355256e31b33ccc4f1cab77f1c6c79f7b4ab508b73d43d8ad55L477-R471
* …

[branch-2.9] Rename test file name from `*Test2.java` to `*Test.java` to run all tests correctly

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

* Reduce local REST calll for `org.apache.pulsar.broker.admin.impl.PersistentTopicsBase#internalGetReplicatedSubscriptionStatus`
* Call local method if partition is owned by this broker,  or call REST api usng internal `AdminClient`
- `ReplicatorSubscriptionTest` has coverd this modification

[Improve][Broker]Reduce GetReplicatedSubscriptionStatus local REST call

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/SystemTopicClientBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/TopicPoliciesSystemTopicClient.java

If the `producer`/`reader` close with the exception, there may exist references that can't remove from the list.

[fix][broker] Fix potential can't remove producer/reader reference

---

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java
pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java

After https://github.com/apache/pulsar/commit/dab0d1f389ee66277c8350072af304895619eb9a#diff-534a0ee16ee831fd0f16fa1230ff3a6e24f6428abd378790f821867f2ec1ffb0R891 ,  functions deployed with `KubernetesRuntimeFactory` doesn't work if the authentication is enabled between components.
```
Was passed main parameter '--auth-plugin' but no main parameter was defined in your arg class
Download File Data from Pulsar
Usage: download [options]
Options:
--destination-file
The file to store downloaded content
--fqfn
The Fully Qualified Function Name (FQFN) for the function
--name
The name of a Pulsar Function
--namespace
The namespace of a Pulsar Function
--tenant
The tenant of a Pulsar Function
--transform-function
Download the transform Function of the connector
Default: false
```
Note that this …

[fix][functions] Fix K8S download function method with auth enabled

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java

* Fix `org.apache.pulsar.client.impl.PulsarClientImpl#scheduledExecutorProvider` not shutdown
* Shut down  `scheduledExecutorProvider`

[fix][client]Fix scheduledExecutorProvider not shutdown

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java

A fix for #17251. There is an error when handling ConflictException. 
The previous unittest can not approve it, so I add another test. 
ex.getCause() -> ex 
add test. 

[fix][broker]fix catching ConflictException when update topic partition

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java

Removing check `finalEx` is null,  because condition `finalEx != null` covered by subsequent condition `finalEx instanceof TimeoutException`
Removing  condition `finalEx != null`

[cleanup][client]Removing null-check finalEx in ProducerImpl.OpSendMsg.sendComplete

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java

When SystemTopicBasedTopicPoliciesService#getTopicPolicies is invoked before SystemTopicBasedTopicPoliciesService#addOwnedNamespaceBundleAsync, it will cause NPE:
```
java.lang.NullPointerException: null
at org.apache.pulsar.broker.service.SystemTopicBasedTopicPoliciesService.addOwnedNamespaceBundleAsync(SystemTopicBasedTopicPoliciesService.java:222) ~[classes/:?]
at org.apache.pulsar.broker.service.SystemTopicBasedTopicPoliciesService$1.onLoad(SystemTopicBasedTopicPoliciesService.java:301) ~[classes/:?]
at org.apache.pulsar.broker.namespace.NamespaceService.notifyNamespaceBundleOwnershipListener(NamespaceService.java:1052) ~[classes/:?]
at org.apache.pulsar.broker.namespace.NamespaceService.onNamespaceBundleOwned(NamespaceService.java:1020) ~[classes/:?]
at …
```

[fix][broker] Fix SystemTopicBasedTopicPoliciesService NPE issue

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java

Fixes #<xyz>
Currently most of the exceptions after proxy lookup throw service not ready, but some clients do not handle this exception, when the user encounters an authentication error, the client will receive the serviceNotReady exception, which makes the user confused
So use getServerError to wrap the exception to avoid always throwing serviceNotReady exception when encountering an exception
Use getServerError to wrap the exception to avoid always throwing serviceNotReady exception when encountering an exception
*(or)*
*(or)*
This change added tests and can be …

[improve][pulsar-proxy] Update proxy lookup throw exception type

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java

Fixes #17588
In Pulsar 2.10.1 with #14730 we introduced a check about concurrent deletion of Namespaces.
This broke the deletion of namespaces in case of a partial failure.
When you delete a namespace we collect all the resources, then we mark the namespace as "deleted", then we do the deletion.
if some failure happens and the procedure does not complete, then the namespaces stays in "deleted" status.
And if you try to delete it again you see the error in #17588 "The namespace is deleted", because getListOfNonPersistentTopics() performs a check about the status of the namespace.  
Do not check the flag "Policies.deleted" while listing non-persistent topics.è
I added a test case that fails without this fix
It is a bug fix for a …

Issue 17588: Allow deletion of a namespace that was left in deleted status

---

site2/docs/reference-configuration.md

The reference link in https://pulsar.apache.org/docs/next/reference-configuration is broken because it's using a relative path, but referring to another site that is not managed by Docusaurus.
Just a quick fix to replace the relative link to an external link.

docs: update the reference link

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java

It is very common, under load, to see this stack trace, this is very annoying and it is scary for system administrator.
```
org.apache.bookkeeper.mledger.ManagedLedgerException: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position. Current mark-delete: 1160:823636 -- attempted mark delete: 1160:823579
Caused by: java.lang.IllegalArgumentException: Mark deleting an already mark-deleted position. Current mark-delete: 1160:823636 -- attempted mark delete: 1160:823579
at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.setAcknowledgedPosition(ManagedCursorImpl.java:1715) ~[com.datastax.oss-managed-ledger-2.10.1.5-SNAPSHOT.jar:2.10.1.5-SNAPSHOT]
at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncMarkDelete(ManagedCursorImpl.java:1855) …
```

[broker] Do not log stacktrace for 'Failed to flush mark-delete position' case

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClient.java

In a Pulsar 2.10.x test environment we ran into an issue where there were 12.3 million ZK WatchEvents in the heap dump. 
The ZK Event thread was blocked and the ZK session had also been expired.
Run callbacks on a separate thread.
PIP-45 changes #12770 and #13296

[fix][metadata] Don't execute Bookkeeper metadata callbacks on Zookeeper event thread

---

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpClient.java
pulsar-client/src/main/java/org/apache/pulsar/client/util/WithSNISslEngineFactory.java

Fixes https://github.com/apache/pulsar/issues/16416
The pulsar admin client and the HTTP lookup service don't add an SNI header when `tlsHostnameVerification` is not enabled.
The async-http-client doesn't split the flag for SNI header and hostname verification, so I added a new SSL engine factory to set the SNI header.

[fix][admin] Add SNI header when tlsHostnameVerification is not enabled

---

pulsar-client-cpp/tests/ClientTest.cc
pulsar-client-cpp/tests/WaitUtils.h

Fixes #14848
There were several fixes on `ClientTest.testReferenceCount` but it's still very flaky.
The root cause is even after a `Reader` went out of the scope and destructed, there was still a `Reader` object existed in the thread of the event loop. See
https://github.com/apache/pulsar/blob/845daf5cac23a4dda4a209d91c85804a0bcaf28a/pulsar-client-cpp/lib/ReaderImpl.cc#L88
To verify this point, I added some logs and saw:
```
2022-09-14 03:52:28.427 INFO  [140046042864960] Reader:39 | Reader ctor 0x7fffd2a7c110
2022-09-14 03:52:28.444 INFO  [140046039774976] Reader:42 | Reader ctor 0x7f5f0273d720 ReaderImpl(0x7f5efc00a9d0, 3)
2022-09-14 03:52:28.445 INFO  [140046042864960] ClientTest:217 | Reference count of the reader: 4
2022-09-14 03:52:28.445 INFO  [140046042864960] ClientImpl:490 | …
```

[fix][cpp] Fix flaky testReferenceCount

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ClusterMetadataSetupTest.java

Fixes #17621 
Only start the ZooKeeper once and clean the ZooKeeper data after the end of each test execution.
And clean useless methods `stop()`.
Execution time after improve test:
```
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 47.734 s - in org.apache.pulsar.broker.zookeeper.ClusterMetadataSetupTest
```

[improve][test] Improve the ClusterMetadataSetupTest to reduce the execution time

---

pulsar-common/src/main/java/org/apache/pulsar/common/util/NettyServerSslContextBuilder.java

As #14569 supported full ssl-provider for broker service, the `constructor` method of NettyServerSslContextBuilder adds a new param `sslProvider`.  Because `sslProvider` can be `null` as the default value, it's better to keep the original `constructor`, then plugins or users do not need to do any changes.  

[improve][broker] Add a constructor method for NettyServerSslContextBuilder.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

After the topic closed failed due to metadata BadVersionException, we should unregister the topic policy listener.
Otherwise, the topic policy listener will get leaked.

[fix][broker] Unregister topic policy listener if managed ledger close failed

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/utils/ClientChannelHelper.java

Inspired by #17085 
When the leader broker is closing, and the client will reconnect and redo lookup, resulting in unexpected results. 
> @codelipenghui 
> Looks like we also need to check other cases (e.g. handleConnect)
> If the broker is shutting down, we should also prevent new connections.
Therefore, it is necessary to check the status of the broker when handling requests, including connect\lookup\partitioned metadata.
The following is the interaction workflow between consumer and broker.
```
Consumer -> Broker: CONNECT
Broker -> Consumer: CONNECTED
Consumer -> Broker: PARTITIONED_METADATA
Broker -> Consumer: PARTITIONED_METADATA_RESPONSE
Consumer -> Broker: LOOKUP
Broker -> Consumer: LOOKUP_RESPONSE
Consumer -> Broker: SUBSCIBE
Broker -> Consumer: SUCCESS
Consumer -> Broker: FLOW …
```

[improve][broker]prevent partitioned metadata lookup request when broker is closing

---

pulsar-client-cpp/lib/ClientConnection.cc

The C++ client is waiting to receive a `Pong` response from broker and if it's not received within 30 seconds, it will forcefully close the connection, assuming the broker is unresponsive. 
Java client was changed, a long time ago, to reset the `havePendingPingRequest` every time some data is read from the socket, instead of just when receiving the Ping response.
In C++, what can happen is that if there is a lot of messages being sent to the broker, and consequently lot of responses from the broker, ***and*** the application callbacks are taking long time (either blocking or just using a lot of CPU), then the Ping response might be sitting behind a lot of broker replies and it might take more than 30 seconds to actually process it.
During this time, we are still reading data from the …

[C++] Reset `havePendingPingRequest` flag for any data received from broker

---

pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc
pulsar-client-cpp/lib/MultiTopicsConsumerImpl.h
pulsar-client-cpp/tests/ConsumerTest.cc

When we start a consumer like the following and publish multiple messages to a topic, ack timeout occurs even though the messages received are immediately acknowledged. This does not occur with normal topics, only with partitioned topics.
```cpp
ClientConfiguration clientConfig;
clientConfig.setMessageListenerThreads(1);
Client client("pulsar://localhost:6650", clientConfig);
ConsumerConfiguration consumerConfig;
consumerConfig.setConsumerType(ConsumerShared);
consumerConfig.setUnAckedMessagesTimeoutMs(10000);
consumerConfig.setMessageListener([](Consumer con, const Message& msg) {
cout << "Received: " << msg.getDataAsString() << endl;
con.acknowledge(msg);
this_thread::sleep_for(chrono::milliseconds(20000));
});
Consumer consumer;
client.subscribe("persistent://public/default/pt4", …
```

[bug][cpp] Fix issue where unexpected ack timeout occurred

---

buildtools/pom.xml
pom.xml

This closes #17047.
Upstream patch is https://github.com/apache/maven-shade-plugin/pull/150.
Bump maven-shade-plugin version to 3.4.0 for the upstream fix.
cc @BewareMyPower @codelipenghui @lhotari @merlimat

[fix][build] duplicate entry when merging services

---

.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

- the if condition was missing for the ssh-access step in pulsar-java-test-image build job
- add the missing if condition to pulsar-java-test-image build job
- add additional condition so that ssh-access is limited to pull requests in a forked repository
- this is a better default

[improve][CI] Ensure that ssh-access is only activated for PRs outside of apache/pulsar repo

---

pulsar-client-cpp/include/pulsar/Result.h
pulsar-client-cpp/lib/BinaryProtoLookupService.cc
pulsar-client-cpp/lib/ClientConnection.cc
pulsar-client-cpp/lib/ClientImpl.cc
pulsar-client-cpp/lib/ClientImpl.h
pulsar-client-cpp/lib/HTTPLookupService.cc
pulsar-client-cpp/lib/HandlerBase.cc
pulsar-client-cpp/lib/Result.cc
pulsar-client-cpp/lib/RetryableLookupService.h
pulsar-client-cpp/lib/ServiceNameResolver.h
pulsar-client-cpp/lib/SynchronizedHashMap.h
pulsar-client-cpp/lib/Utils.h
pulsar-client-cpp/tests/ClientTest.cc
pulsar-client-cpp/tests/LookupServiceTest.cc
pulsar-client-cpp/tests/PulsarFriend.h

Currently the operation timeout only works for requests other than
lookup, like SEND and FLOW. However, the lookup requests, which are sent
by `LookupService`, should also apply the operation timeout, see
https://github.com/apache/pulsar/blob/7075a5ce0d4a70f52625ac8c3d0c48894442b72a/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java#L1019-L1025
In addition, no attempts would be retried if lookup failed even due to a
retryable reason. For example, if some of all configured brokers were
down, the C++ client would fail immediately.
Therefore, this PR intends to retry lookup for some certain cases:
- The connection cannot be established, except connection timeout, which
is controlled by the connection timeout.
- A `ServiceNotReady` error is received, except it's …

[fix][cpp] Support retry and apply operation timeout for lookup requests

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadSheddingTask.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceCloseTest.java

The PR https://github.com/apache/pulsar/pull/16408 supported loadBalancerSheddingIntervalMinutes dynamic configuration, but the scheduled load-shedding task may block pulsar service close operation, the pulsar service need to wait until the scheduled load-shedding task executed or reach broker shutdown timeout. If the load-shedding task interval time and broker shutdown timeout are long, the pulsar service close operation will waste a lot of time.
Cancel the scheduled task when closing the pulsar service.
Add a test to verify the pulsar service could be closed gracefully in time.

[improve][broker] Cancel the loadShedding task when closing pulsar service

---

bin/pulsar-shell
bin/pulsar-shell.cmd

The `pulsar-shell` script doesn't change the working directory to the Pulsar home one. In this way if you configure `cliExtensionsDirectory` with a relative path, it only works if you run pulsar-shell from the pulsar home directory. For instance `cd bin && ./pulsar-shell` is not able to find the cli extensions dir.
* Change directory to pulsar home before starting the java process (in this way it's the same as the other scripts)
The only disadvantage is that the `--file` autocompletion will suggest files from the Pulsar home directory and not from 
the real working dir. (but it's still better than the current behaviour)

[fix][cli] Pulsar shell: support relative paths (cliextensions)

---

pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriter.java

There is a chance that FlushContext is not recycled in case of failure and "flushContext.asyncAddArgsList" is empty or null.
Fix the code

[transactions] Fix minor leak of FlushContext

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java

During the deletion of a namespace we don't want that autoTopicCreation triggers the creation of topics.
This is related to #17308 but it deals only with Namespace and Tenant deletion.
Consider "Policies.deleted" while deciding if autoTopicCreation is available or not
I will add tests

[bugfix] Prevent Automatic Topic Creation during namespace deletion

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java

When a namespace containing partitioned topics is deleted, will throw the topic not found exception.
<strong>(High light)</strong>  Should use API `deletePartitionedTopicAsync` to delete partitioned system topic.
- Use `cmd-deletePartitionedTopicAsync` to delete partitioned system topic.
- Add tests: delete namespace.

[test][admin]add test case: delete namespace when has partitioned system topic

---

pulsar-client-cpp/lib/ReaderImpl.cc

Fixes #17325
Cherry-pick #17325 to branch-2.9

[fix][c++][branch-2.9]Fix wrong consumers size: execute `callback` before executing `readerCreatedCallback_`

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupUsageAggregationTest.java

Fixes #17120 
Master Issue: #17120
The failure assertion is at line 206 :
```
Assert.assertEquals(recvdNumMsgs, topicStats.msgOutCounter);
```
`recvdNumMsgs` must be 10, but `topicStats.msgOutCounter` is from broker side, coming from dispatcher :
```
writeAndFlushPromise.addListener(status -> {
// only increment counters after the messages have been successfully written to the TCP/IP connection
if (status.isSuccess()) {
msgOut.recordMultipleEvents(totalMessages, totalBytes);
msgOutCounter.add(totalMessages);
bytesOutCounter.add(totalBytes);
chunkedMessageRate.recordMultipleEvents(totalChunkedMessages, 0);
}
});
```
So we need to use Awaitility for that assertion.
- Remove `for` block, use Map.`get`.
- Add cleanup logic in order to run the test many times.

[fix][test] Fix flaky test ResourceGroupUsageAggregationTest. testProduceConsumeUsageOnRG

---

bin/pulsar-shell
bin/pulsar-shell.cmd
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/ConfigShell.java
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/JCommanderCompleter.java

After https://github.com/apache/pulsar/pull/17648 it's no more possible to create/update configs from a relative path (at least is not relative to the current directory but from the Pulsar home dir which is not useful)
* Added current dir as system property. Pulsar shell uses it for autocompletion and for resolving the file passed with `--file`

[improve][cli] Pulsar shell: allow to create a new config (--file) with a relative path

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java

Cherry-pick #15755
Master issue #15643, #15753
Blocked at BrokerService#unloadNamespaceBundlesGracefully:
```
2022-05-20T03:37:05.4960249Z "main" #1 prio=5 os_prio=0 cpu=32274.29ms elapsed=2566.54s tid=0x00007fd108024380 nid=0x1af8f waiting on condition  [0x00007fd10fcd0000]
2022-05-20T03:37:05.4960659Z    java.lang.Thread.State: WAITING (parking)
2022-05-20T03:37:05.4961114Z 	at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
2022-05-20T03:37:05.4961875Z 	- parking to wait for  <0x00000000cdf00010> (a java.util.concurrent.CompletableFuture$Signaller)
2022-05-20T03:37:05.4962343Z 	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.3/LockSupport.java:211)
2022-05-20T03:37:05.4963171Z 	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.3/Complet …
```

[branch-2.10][cherry-pick] Fix the broker close hanged issue.

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentSubscriptionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java

Fixes #17572
The `lastActive` in `ManagedCursorImpl` only be updated in 3 places:
- `org.apache.pulsar.broker.service.persistent.PersistentSubscription#addConsumer`
- `org.apache.pulsar.broker.service.persistent.PersistentSubscription#removeConsumer`
- `org.apache.bookkeeper.mledger.impl.ManagedCursorImpl#internalResetCursor`
If there are brokers shutdown with OOM or other situation, which make the broker not shutdown gracefully, the new broker load the topics and then do subscription expiry check soon before consumer reconnected, then the subscription may be deleted unexpectedly.
Need to update `lastActive` in `ManagedCursorImpl` while consuming stably, such as consumer acknowledged messages, which makes `lastActive` closer to the last active meaning.
- Add  `cursor.updateLastActive()` …

[fix][broker] Fix unexpected subscription deletion caused by the cursor last active time not updated in time

---

site2/docs/administration-pulsar-manager.md

change the version number of pulsar-manager from 0.2.0 to 0.3.0 which is recent
Fixes #<xyz>
0.3.0 is the latest version
Documentation changes only
*(or)*
*(or)*
*(example:)*

[Doc] [pulsar-manager] change version number from 0.2.0 to 0.3.0

---

pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
pulsar-common/src/test/java/org/apache/pulsar/common/compression/CommandsTest.java

Fixes #17680 
Master Issue: #17680 
If the `partitionedKey` is encoded with Base64, decode it with Base64.

[fix][common] Fix parsing partitionedKey with Base64 encode issue.

---

bin/pulsar
pom.xml
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/BrokerStatTest.java

Fix the mbeans to JSON.
Broker log:
```
org.glassfish.jersey.server.internal.process.MappableException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Invalid type definition for type `com.sun.management.internal.GcInfoCompositeData`: Failed to construct BeanSerializer for [simple type, class com.sun.management.internal.GcInfoCompositeData]: (java.lang.IllegalArgumentException) Failed to call `setAccess()` on Method 'getGcInfo' (of class `com.sun.management.internal.GcInfoCompositeData`) due to `java.lang.reflect.InaccessibleObjectException`, problem: Unable to make public com.sun.management.GcInfo com.sun.management.internal.GcInfoCompositeData.getGcInfo() accessible: module jdk.management does not "exports com.sun.management.internal" to unnamed module @5bc79255 (through …
```

[fix][cli] Fix mbeans to json

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/conf/InternalConfigurationData.java

After https://github.com/apache/pulsar/pull/14384, the broker and the client expects that the `InternalConfigurationData` contains `metadataStoreUrl` and `configurationMetadataStoreUrl` fields.
However the broker is no more compatible with old clients. 
https://github.com/apache/pulsar/pull/14384 is landed to branch-2.11 and [2.10.2](https://github.com/apache/pulsar/pull/17291)
Example scenario: 
- broker on 2.10.1
- function worker on 2.10.1
1. upgrade fn worker to 2.11.0 or 2.10.2
2. the fn worker starts and download the internal config from the broker
3. broker serves a json with old fields (`zookeeperServers` and `configurationStoreServers`)
4. fn worker reads the json and convert it to a `InternalConfigurationData` instance. It expects to see the fields filled `metadataStoreUrl` and …

[fix][functions] Ensure InternalConfigurationData data model is compatible across different versions

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

`cherry-pick` #17255 to `branch-2.9` for conflict resolution

[branch-2.9][fix][broker]Persist cursor info error when cursor close

---

pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/PendingAckHandleImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/BookKeeperClientFactoryImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceCloseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiGetLastMessageIdTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ExclusiveProducerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicOwnerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionLowWaterMarkTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckInMemoryDeleteTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/v1/V1_ProducerConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/NegativeAcksTracker.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java

[improve][test] remove powermock-reflect dependency

---

pulsar-client-tools/src/main/java/org/apache/pulsar/shell/ConfigShell.java
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/PulsarShell.java
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/config/ConfigStore.java
pulsar-client-tools/src/main/java/org/apache/pulsar/shell/config/FileConfigStore.java
pulsar-client-tools/src/test/java/org/apache/pulsar/shell/ConfigShellTest.java
site2/docs/reference-cli-tools.md

In Pulsar shell you can only update the whole configuration but you can't modify it later. For instance, if I import a new config and then I want to enable a feature or a property, I need to read the config, copy, modify and update.
My use-case is that I want to enable custom commands in a quick way.
* Added new command `config set-property -p <prop> -v <value> <config>`
It updates or creates a new entry in the config. If you modify the current config, the shell will reload applying the new config.  
* Added new command `config get-property -p <prop>  <config>`
Returns the current value for the property of the config
For example, now I can enable a cli extensions directly from the shell:
```
config use my-config
config update-property -p customCommandsFactories -v <extensionname> …
```

[improve][cli] Pulsar shell: add command to set/get property of a config

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/ResourceLockImpl.java

In reading through the `ResourceLockImpl`, I noticed that `revalidateAfterReconnection` is always `false`. This seems like an oversight. It was introduced in #11886. 
* Set `revalidateAfterReconnection = true;` when there is a failure during lock validation.
I am not sure that this change will actually affect anything. In recently looking through the reconnection lo logs, I noticed the following two get logged together: 
```
2022-07-29T19:44:16,904+0000 [metadata-store-coordination-service-5-1] INFO  org.apache.pulsar.metadata.coordination.impl.LockManagerImpl - Metadata store connection has been re-established. Revalidating locks that were pending.
2022-07-29T19:44:16,984+0000 [metadata-store-coordination-service-5-1] INFO  org.apache.pulsar.metadata.coordination.impl.LockManagerImpl - …
```

[fix][metadata] Set revalidateAfterReconnection true for certain failures

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerBkTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/ThrowableToStringUtil.java

See:
-  #16729 
I tried to run it 10,000 times, but could not reproduce the problem. Guessing it is not the problem with the current test, try adding information to determine the problem.
Try adding information to determine the problem.

[flaky-test]Add information in ManagedLedgerBkTest to determine the problem

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java

Fixes #17707
1. Fix the case mentioned in #17707
2. Fix `checkBacklogQuota` fails when both retention.size and backlogQuota.size is -1. Same as time check.
- testRetentionAndBacklogQuotaCheck
bug

[fix][broker] Fix namespace backlog quota check with retention.

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java

- session listener might block further processing, and therefore it's better to run it in another thread
- here's an example of a stacktrace happening in a Bookie with the Pulsar metadata store classes:
- mentioned in [another issue discussion](https://github.com/apache/pulsar/pull/17620#issuecomment-1246303451).
```
metadata-store-zk-session-watcher-21-1  Waiting Thread ID: 60
jdk.internal.misc.Unsafe.park(Unsafe.java)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)
java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)
java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043) …
```

[fix][metadata] Handle session events in a separate thread

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci-cpp-build.yaml
.github/workflows/ci-go-functions.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml
build/pulsar_ci_tool.sh

Mailing list discussion: https://lists.apache.org/thread/gwfmxmxlhtsjn17sxxc367jcs4pcwofz
To reduce resource consumption, PRs would require approval before all tests would be run.
PR authors would be required to run tests in their own forks to make sure that tests pass and
before the PR is approved. Alternatively Apache Pulsar committers can add a ready-to-test label
to the PR to make it eligible for testing.
This way PR authors would have CI feedback without causing resource shortage to apache/pulsar CI.
- stop non-doc CI builds if the PR isn't approved OR doesn't have the "ready-to-test" label. 
- Provide detailed instructions for the PR author for creating PR in their own fork by simply clicking a link.
Contributor guide needs …

[feat][CI] Add approval solution to reduce GitHub Actions resource consumption

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java

Fixes #17681
*(or)*
*(or)*
*(example:)*

[fix][broker] Fix if dynamicConfig item in ZK do not exist in broker cause NPE.

---

.github/workflows/ci-cpp-build.yaml
.github/workflows/ci-go-functions.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml
build/pulsar_ci_tool.sh

- The approval solution doesn't work as expected by approving the PR or by adding the ready-to-test label and adding a comment "/pulsarbot rerun-failure-checks".
The workaround until this PR is merged is to add a "ready-to-test" label to the PR and then close & reopen the PR.
- Fix the ready-to-test label check:
- Refresh PR labels when re-running workflow - when re-running, the event JSON remains the same. The API must be used to fetch the up-to-date JSON for the PR.
- Fix the PR approval check:
- set GITHUB_TOKEN for script so that retrieving the approval status could work
PR in forked repository: https://github.com/lhotari/pulsar/pull/87

[fix][CI] Fix issues with approval solution for GitHub Actions

---

site2/docs/reference-configuration.md
site2/website/sidebars.json

The link `Pulsar reference` points to `/reference`, which is handled by Docusaurus as an SPA page and will result in 404. This is a known limitation of Docusaurus(facebook/docusaurus#3309) and the known workaround does not work well either.
Therefore, we decided to use an external link in the sidebar to redirect users to `/reference` directly.

[fix][doc] Replace reference-configuration page with an external link

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java
pulsar-broker/src/test/java/org/apache/pulsar/schema/compatibility/SchemaCompatibilityCheckTest.java
testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockLedgerHandle.java

in the schema update, will create a `ledgerHandle` and write data to BK, after that `ledgerHandle` is no longer useful and no other object holds references to it. `ledgerHandle` will be recycled with GC, but `ledgerHandle` also hold external connections, which will cause leakage.
https://github.com/apache/pulsar/blob/40b9d7ea50cef54becb09f2543193e08375abe0b/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java#L452-L456
after the schema is updated, close the `ledgerHandle`, just like schema-read:
https://github.com/apache/pulsar/blob/40b9d7ea50cef54becb09f2543193e08375abe0b/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java#L519-L525
- …

[fix][schema]ledger handle leak when update schema

---

pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java

Task "Clear the ledger that has been consumed" will be triggered by `mark delete event` and `retention policy`.
<strong>(High light)</strong>  Because there is no durable cursor(`__compaction` already acknowledged), the ledger will be removed by the asynchronous `clean-ledger-task`, even if the reader is still reading
https://github.com/apache/pulsar/blob/d4beae72d608bafaebe7ac1cff0a258238e84f10/pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java#L754-L778
----
The error execution flow is as follows: 
producer: 
- send 1000 messages ( ledger-1 )
-  unload the topic.
- send 1000 messages (ledger-2)
reader:
- read 500 messages
- auto acknowledgment
- calculate the next read position: 
- `getNextValidPosition(position)` At this time the ledger-1 has been deleted, …

[fix][flaky-test]CompactedTopicTest.testReadCompleteMessagesDuringTopicUnloading

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/BinaryProtoLookupService.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpLookupService.java

The error messages look a little bit wired while I try to use pulsar-client to run some tests.
`PulsarClientException: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException`
During the broker shutdown, the error logs like following
```
2022-09-19T11:37:56,215+0800 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open connection to localhost/<unresolved>:6650 : io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:6650
2022-09-19T11:37:56,215+0800 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/test] [reader-23bc11015c] Error connecting to broker: org.apache.pulsar.client.api.PulsarClientException: …
```

[fix][client] Unwrap completion exception for Lookup Services

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaWithAuthTest.java

Cherry-pick #15956.
Currently, we need admin permissions to operate the schema API. This is because the admin permission was defined when the schema API was first added. See #1381.
Later, then adding authentication granularity with #6428, we don't change the schema API part.  So leave the admin permission today.
But the binary protocol allows the produce/consume permission to get the schema, so change the related method permission to `produce/consume`.
- `get schema` need `GET_METADATA` permission

[branch-2.9][cherry-pick] Fix producer/consume permission can’t get schema.

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SubscriptionMessageDispatchThrottlingTest.java

I found we declared some variables, but does not used these. 
Remove these unnecessary variables.

[cleanup][test]delete unnecessary variables in SubscriptionMessageDispatchThrottlingTest

---

.github/workflows/pulsar-ci.yaml

In https://github.com/apache/pulsar/pull/17571#discussion_r967208132, we remove the canonical name of `cpp-test` due to a deadlock between changing the request statuses and the workflow. Now we add back the canonical name "CI - CPP, Python Tests" to eliminate the trick.
PR in forked repository: trivial to not have one.
cc @lhotari @nicoloboschi

[improve][ci] add back cpp-test name

---

build/pulsar_ci_tool.sh

Pulsar CI shouldn't run builds for PRs which are in draft status or aren't mergeable.
Add additional checks to check draft status and mergeable status.
PR in forked repository: https://github.com/lhotari/pulsar/pull/89

[improve][CI] Don't run CI when PR is in draft status or isn't mergeable

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarVersionStarter.java

The current `bin/pulsar version` script only prints out the version string. When running custom builds of Pulsar, this is sometimes not enough to know which version you have. Since the `PulsarVersion` class already has more information, I propose we print out all of its information in the same format that the broker logs the information.
Here is a sample output for this specific PR:
```shell
$ bin/pulsar version
Current version of pulsar is: 2.11.0-SNAPSHOT
Git Revision 4414e3d76c27e821e75f30eae853862b04e63200
Git Branch print-more-version-info
Built by Michael Marshall <mmarshall@apache.org> on mmarshall-rmbp16 at 2020-01-22T09:10:15-0600
```
* Add more output to the `bin/pulsar version` command.
(Please explain …

[feat][build] Print out more info for bin/pulsar version

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java

we could set namespace level offload-policy's offload-threshold In the following two `pulsar-admin CLI` ways:
1. `pulsar-admin namespaces set-offload-threshold -s $OFFLOAD_THRESHOLD demo/demo`
2. `pulsar-admin namespaces set-offload-policies --offloadAfterThreshold $OFFLOAD_THRESHOLD demo/demo`
while set offload-threshold value , Negative values disable automatic offload. 0 triggers offloading as soon as possible.
but we can't use `pulsar-admin namespaces set-offload-policies` to set offload-threshold'value to negative or 0 , show as follow：
`pulsar-admin namespaces set-offload-threshold` as expected.
we should keep `set-offload-threshold` and `set-offload-policies` CLI behavior consistent.
remove `positiveCheck` process while check offloadAfterThreshold value validity at …

[improve][admin]namespace CLI set-offload-policy's thresholdBytes support negative and 0

---

site2/docs/schema-understand.md

fix doc for consumer receive().getValue API
```
Message<User> message = consumer.receive();
User user = message.getValue();
```
this is the right way
but doc is 
```
User use = consumer.receive();
```
so change to 
```
User user = consumer.receive().getValue();
```

[fix][doc] fix schema get value doc problem

---

docker/pulsar/Dockerfile
docker/pulsar/pom.xml
docker/pulsar/scripts/install-pulsar-client.sh
tests/docker-images/java-test-image/Dockerfile
tests/docker-images/latest-version-image/Dockerfile

This refers to #12944.
```bash
mvn clean install -DskipTests
./build/build_java_test_image.sh                                                
mvn package -Pdocker,-main -am -pl docker/pulsar-all -DskipTests -DpythonClientBuildArch=aarch64
```
PR in forked repository: https://github.com/tisonkun/pulsar/pull/2

[feat][build] Support ARM64-based docker images

---

pulsar-io/hdfs2/pom.xml
pulsar-io/hdfs3/pom.xml
pulsar-io/hdfs3/src/main/java/org/apache/pulsar/io/hdfs3/AbstractHdfsConfig.java
pulsar-io/hdfs3/src/main/java/org/apache/pulsar/io/hdfs3/AbstractHdfsConnector.java
pulsar-io/hdfs3/src/main/java/org/apache/pulsar/io/hdfs3/sink/HdfsAbstractSink.java
pulsar-io/hdfs3/src/main/java/org/apache/pulsar/io/hdfs3/sink/HdfsSinkConfig.java

Fix https://www.cve.org/CVERecord?id=CVE-2022-25168
Upgrade Hadoop client to 2.10.2 for hdfs2 IO connector
Upgrade Hadoop client to 3.3.3 for hdfs3 IO connector
PR in forked repository: https://github.com/codelipenghui/incubator-pulsar/pull/13

[fix][io] Upgrade hadoop client to 3.3.3 and 2.10.2

---

pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStoreProvider.java

Variable `log` in `MLTransactionMetadataStoreProvider` is not used.
remove useless variable.
- https://github.com/poorbarcode/pulsar/pull/4

[cleanup][broker]remove unnecessary variable in MLTransactionMetadataStoreProvider

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerBkEnsemblesTests.java

With the transaction feature, we send and receive messages, and at the same time, execute `admin API: unload namespace` 1000 times. Then the problem occur: Consumer could not receive any message, and there has no error log. After that we tried `admin API: get topic stats`, and the response showed only producers are registered on topic, and no consumers are registered on topic, but consumer stat is `Ready` in the client. This means that the state of the consumer is inconsistent between the broker and the client.
Then we found the problem: Two PersistentTopic which have the same name registered at a broker node, consumer registered on one (aka `topic-c`), and producer registered on another one (aka `topic-p`). At this time, when we send messages, the data flow like this : 
```text
client: …
```

[fix][broker]Consumer can't consume messages because there has two sames topics in one broker

---

site2/website/blog/2022-08-22-pulsar-summit-asia-2022-cfp.md

Add the Pulsar Summit Asia 2022 CFP blog. Replace https://github.com/apache/pulsar/pull/17218
Preview:

[BLOG] Add Pulsar Summit Asia 2022 CFP blog

---

site2/website/versioned_docs/version-2.8.x/admin-api-permissions.md
site2/website/versioned_docs/version-2.8.x/deploy-bare-metal-multi-cluster.md
site2/website/versioned_docs/version-2.8.x/security-tls-keystore.md
site2/website/versioned_docs/version-2.9.x/admin-api-permissions.md
site2/website/versioned_docs/version-2.9.x/client-libraries-java.md
site2/website/versioned_docs/version-2.9.x/deploy-bare-metal-multi-cluster.md
site2/website/versioned_docs/version-2.9.x/security-tls-keystore.md
wiki/release/release-process.md

1. Clarify the term usage for `major/minor release` to avoid misunderstanding.
2. Grammar/style fixes.
3. Fix a few broken links and typos in 2.8.x/2.9.x docs.

[improve][doc] Improve release process document

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ShadowReplicator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/ShadowReplicatorTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMap.java

Master Issue: https://github.com/apache/pulsar/issues/16153
Add ShadowReplicator.
- Add map `PersistentTopic#shadowReplicators`, most of its management just follows `PersistentTopic#replicators`
- Add class `ShadowReplicator`
- ShadowReplicatorTest
None
Internal implementation.

[feat][broker]PIP-180 ShadowTopic - Part IV - Add Shadow Replicator

---

pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc

Capturing shared ptr in the timer function will cause a circular reference.
- Use weak ptr instead shared ptr.

[fix][cpp] Use weak ptr avoid circular references.

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiDelayedDeliveryTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiMaxUnackedMessagesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaValidationEnforcedTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/TlsHostVerificationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/TlsProducerConsumerBase.java

Using this command `find . ! -name '*Test*' -name "*.java" -exec grep -H "@Test" {} \;` I found out that some tests are not running in the CI because they don't match the surefire class name pattern
* Rename those tests adding the "Test" suffix

[fix][tests] Some unit tests are not run by the CI

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MultiTopicsReaderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TableViewTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsReaderImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ReaderImplTest.java

Fixes #<xyz>
https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderImpl.java#L190
```
@Override
public CompletableFuture<Message<T>> readNextAsync() {
CompletableFuture<Message<T>> receiveFuture = consumer.receiveAsync();
receiveFuture.whenComplete((msg, t) -> {
if (msg != null) {
consumer.acknowledgeCumulativeAsync(msg).exceptionally(ex -> {
log.warn("[{}][{}] acknowledge message {} cumulative fail.", getTopic(),
getConsumer().getSubscription(), msg.getMessageId(), ex);
return null;
});
}
});
return receiveFuture;
}
```
I see ack failures due to null message id -- because we release the msg in TableViewImpl before reader.acknowledgeCumulativeAsync.
https://github.com/apache/pulsar/blob/master/pulsar-client/src/mai …

[fix][tableview] fixed ack failure in ReaderImpl due to null messageId

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java
pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleFactory.java

Variable policiesCache in NamespaceBundleFactory is not used.
Variable bundleFactory_ in OwnershipCache is not used.
https://github.com/lordcheng10/pulsar/pull/12

[cleanup][broker]remove unnecessary variable

---

site2/docs/concepts-messaging.md

There is some mistake in the Failover subscription type.
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/liangyepianzhou/pulsar/pull/4
After opening this PR, the build in …

[dox][message]Fix the description of failover subscription in the doc

---

site2/docs/io-debezium-source.md
site2/website/versioned_docs/version-2.10.x/io-debezium-source.md

This PR fixes the link to the Debezium MS SQL integration tests in the docs.
Updated master + 2.10 docs

[fix][docs] Fix link to DebeziumMsSqlSourceTester.java

---

src/owasp-dependency-check-suppressions.xml

Currently owasp ci check fails on branch-2.10.
See https://github.com/Jason918/pulsar/actions/runs/3088190603/jobs/4994380011#step:8:53
```
Error:  Failed to execute goal org.owasp:dependency-check-maven:7.1.0:aggregate (default) on project distribution: 
Error:  
Error:  
Error:  pulsar-presto-distribution.tar.gz: pulsar-presto-distribution.tar: aether-connector-asynchttpclient-1.13.1.jar: CVE-2017-14063(7.5), CVE-2021-43138(7.8)
Error:  pulsar-presto-distribution.tar.gz: pulsar-presto-distribution.tar: async-http-client-1.6.5.jar: CVE-2021-43138(7.8)
Error:  pulsar-presto-distribution.tar.gz: pulsar-presto-distribution.tar: grpc-netty-1.45.1.jar: …
```

[fix][ci][branch-2.10] Fix owasp ci failure on branch-2.10

---

site2/docs/sql-deployment-configurations.md
site2/docs/sql-getting-started.md
site2/docs/sql-overview.md
site2/docs/sql-rest-api.md

* This closes #17576.
* This refers to https://github.com/apache/pulsar/issues/17495.
N/A
cc @nicoloboschi @eolivelli @codelipenghui @merlimat @MarvinCai @momo-jun

docs: Add ceveat to Pulsar SQL overview and update Presto to Trino

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdGenerateDocument.java
pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdGenerateDocumentation.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/CmdGenerateDocs.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/CmdGenerateDocsTest.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/CmdGenerateDocumentation.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/CLITest.java

SignorMercurio#3
Docs for Pulsar CLI tools such as `pulsar-admin`, `pulsar-client`, `pulsar` and `pulsar-perf` are auto-generated but contains redundant steps that will produce complex but not useful TOCs(table of content). This PR aims to remove these steps.
Remove all `---`, `Usage` and `bdocs-tab:example_shell` parts since they are no longer useful.

[fix][doc] Remove redundant steps in doc generation

---

SECURITY.md
site2/docs/administration-proxy.md
site2/website/versioned_docs/version-2.10.0-deprecated/administration-proxy.md
site2/website/versioned_docs/version-2.10.1-deprecated/administration-proxy.md
site2/website/versioned_docs/version-2.10.x/administration-proxy.md
site2/website/versioned_docs/version-2.7.5/administration-proxy.md
site2/website/versioned_docs/version-2.8.3-deprecated/administration-proxy.md
site2/website/versioned_docs/version-2.8.x/administration-proxy.md
site2/website/versioned_docs/version-2.9.2-deprecated/administration-proxy.md
site2/website/versioned_docs/version-2.9.3-deprecated/administration-proxy.md
site2/website/versioned_docs/version-2.9.x/administration-proxy.md

See https://github.com/apache/pulsar/wiki/CVE-2022-24280
Add documentation how to address "Apache Pulsar Proxy target broker address isn't validated (CVE-2022-24280)"

[doc][proxy] Document how to mitigate CVE-2022-24280

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTlsAuthTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminRestTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceOwnershipListenerTests.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupConfigListenerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceBundlesCacheInvalidationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionProduceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTestBase.java

Fixes: flaky test `NamespaceOwnershipListenerTests.testNamespaceBundleOwnershipListener`
- https://github.com/poorbarcode/pulsar/actions/runs/3103585851/jobs/5027176671
```
org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Cannot delete non empty bundle
at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252)
at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:351)
at org.apache.pulsar.client.admin.internal.NamespacesImpl.deleteNamespace(NamespacesImpl.java:226)
at org.apache.pulsar.broker.namespace.NamespaceOwnershipListenerTests.testNamespaceBundleOwnershipListener(NamespaceOwnershipListenerTests.java:104)
at …
```

[fix][flaky-test]NamespaceOwnershipListenerTests.testNamespaceBundleOwnershipListener

---

conf/broker.conf

The default value of the exposeManagedLedgerMetricsInPrometheus field is true, but the comment says that the default value is false.
Correct the comment of exposeManagedLedgerMetricsInPrometheus field.
PR in forked repository: https://github.com/Pomelongan/pulsar/pull/1

[fix][doc]fix comments for exposeManagedLedgerMetricsInPrometheus field

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderList.java

Fixes #<xyz>
In case of chain authentication failure, we should consider adding an metric to report
Add metric to report when chain authentication failed
*(or)*
*(or)*
*(example:)*
(Docs have been already …

[Improve][Auth]Update authentication failed metrics report

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/BaseGenerateDocumentation.java

There are some information that are no longer useful in the generated docs. This PR aims to remove these information in the generation steps.
Unuseful information is deleted from code.
PR in forked repository: SignorMercurio#4

[fix][doc] Remove unuseful info in docs generation

---

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java

With the latest changes to the KCA module (https://github.com/apache/pulsar/pull/16098)  now you get this error if the message is batched:
```
java.lang.ClassCastException: class org.apache.pulsar.client.impl.BatchMessageIdImpl cannot be cast to class org.apache.pulsar.client.impl.MessageIdImpl (org.apache.pulsar.client.impl.BatchMessageIdImpl is in unnamed module of loader java.net.URLClassLoader @2ff4acd0; org.apache.pulsar.client.impl.MessageIdImpl is in unnamed module of loader org.apache.pulsar.common.nar.NarClassLoader @6ff415ad)
at org.apache.pulsar.io.kafka.connect.KafkaConnectSink.getMessageOffset(KafkaConnectSink.java:327) ~[pulsar-io-kafka-connect-adaptor-?.jar]
at org.apache.pulsar.io.kafka.connect.KafkaConnectSink.toSinkRecord(KafkaConnectSink.java:408) …
```

[fix][connector] KCA: use reflection to get pulsar-client impl classes

---

build/pulsar_ci_tool.sh

The GitHub Actions approval solution is also useful for maintenance branches to cut unnecessary builds.
branch-2.11 contains a similar workflow as master branch and it will also be useful to port the approval to other
maintenance branches as a way to prevent unnecessary builds.
Remove the hard coding of master branch in the script which generates the link for opening a PR in your fork.
PR in forked repository: https://github.com/lhotari/pulsar/pull/90

[improve][CI] Support GitHub Actions approval solution on maintenance branches

---

README.md

The Pulsar logo url is broken in [README.md](https://github.com/apache/pulsar#readme)
Reference the logo image in pulsar-site

Fix broken logo image in README.md

---

README.md

- add link to https://github.com/apache/pulsar-client-reactive to README.md

Add link to Reactive Java client to README.md

---

pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ClientConfiguration.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java
site2/docs/client-libraries-java.md
site2/website/versioned_docs/version-2.10.x/client-libraries-java.md
site2/website/versioned_docs/version-2.8.x/client-libraries-java.md
site2/website/versioned_docs/version-2.9.x/client-libraries-java.md

> The maximum number of rejected requests of a broker in a certain time frame (30 seconds) after the current connection is closed and the client creates a new connection to connect to a different broker.
According to code, the time frame should be in the 60s instead of the 30s, see:
https://github.com/apache/pulsar/blob/7913fe5614fed853f91199f658fe2584f10e38b9/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L157
https://github.com/apache/pulsar/blob/7913fe5614fed853f91199f658fe2584f10e38b9/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L1134-L1145
30 seconds -> 60seconds

[fix][doc] Fix maxNumberOfRejectedRequestPerConnection doc

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorUtils.java
pulsar-broker-common/src/test/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorUtilsTest.java
pulsar-broker-common/src/test/java/org/apache/pulsar/broker/stats/prometheus/package-info.java

If `label_cluster` specified `cluster_123`, the expected metrics text is:
```
metrics_xxx_total{cluster="cluster_123"} 1.0
```
but the actual metrics text is :
```
metrics_xxx_totalcluster="cluster_123"} 1.0
```
<strong>High light:</strong> lost a char `{`
Make metrics text generate correct
- https://github.com/poorbarcode/pulsar/pull/5

[fix][metrics]wrong metrics text generated when label_cluster specified

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java

Pulsar cluster can be setup using SNI reverse proxy and Pulsar cluster metadata initialization should support cluster-metadata creation/update using proxy-protocol and URL. It will be also useful in Pulsar-helm-chart installation phase to create cluster metadata with proxy configuration as well.
- Initialize Cluster metadata using Proxy URL and protocol.

[Pulsar-init] Support cluster init using proxy url and protocol

---

site2/docs/client-libraries-cpp.md
site2/docs/client-libraries-python.md

cc @BewareMyPower @shibd @RobertIndie @Demogorgon314 @Anonymitaet 
This closes #17794.
N/A

docs: Updating Python installation section

---

site2/website/sidebars.json

This is a followup to #17284.
cc @DaveDuggins @Anonymitaet @momo-jun @urfreespace 
docs only change

docs: add developers-landing page to sidebars

---

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java
pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaBytesSource.java
pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaSourceConfig.java
pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaStringSource.java
pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/KafkaBytesSourceTest.java
pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java

Fixes #17760
Users of Kafka source today can't access their Kafka headers in Pulsar. This patch adds a config to enable this copy to take place in addition to some standard, useful Kafka headers. 
* A new `KafkaSourceConfig` flag is added: `copyHeadersEnabled` of type `boolean` and default value of `false`
* If the flag is toggle on, the following Kafka headers will be copied over to Pulsars properties.
* `__kafka_topic` : the name of the Kafka topic consumed by the source.
* `__kafka_partition`: the number of paritioed on the consumed kafka topics
* `__kafka_offset`: the current offset of the kafka message currently consumed by the source
* User defined header: The customer headers a Kafka producer could generated as pairs of `<String, byte[]>`. Since Pulsar properties are of type …

[improve][pulsar-io-kafka] Add option to copy Kafka headers to Pulsar properties

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsController.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java

There's a bug in replicated subscriptions snapshotting. Snapshots get continuously created after a topic gets activated and before new messages are published. This is a gap in the logic introduced in #11922.
The intention of the #10292 and #11922 changes were to pause replication snapshots when there are no new messages.
These changes were made to address #6437 and as an alternative to #7299 changes.
- Add condition to skip creating snapshots when the lastDataMessagePublishedTimestamp is 0.
- Modify existing test case `testReplicationSnapshotStopWhenNoTraffic` to verify that snapshots aren't published before messages have been published.

Skip creating a subscription replication snapshot if no messages have been published after the topic gets activated on a broker

---

buildtools/src/main/java/org/apache/pulsar/tests/MockitoCleanupListener.java
buildtools/src/main/java/org/apache/pulsar/tests/MockitoThreadLocalStateCleaner.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxAuthorizationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/TokenExpirationProduceConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java

Fixes #17714
There's a memory leak when using Mockito mocks since all invocations get recorded.
Add multiple solutions for making sure that mocks are cleaned up properly.
Modify MockedPulsarServiceBaseTest to clean up PulsarService and PulsarAdmin mocks since the detected memory leaks are caused by these mocks.
PR in forked repository: https://github.com/lhotari/pulsar/pull/92

[fix][tests] Fix Mockito mocks memory leak

---

bin/pulsar

PIP-45 related PRs #12770 and #13296 introduced changes in Pulsar and Bookkeeper configuration for Pulsar so that Pulsar Metadata driver is used for metadata operations in the bookkeeper client (in broker) and in the bookkeeper server (the bookies).
It would be good to have a way to opt-out of this change and configure Pulsar and Bookies without Pulsar Metadata store and use Zookeeper directly. 
This PR will allow to use Bookkeeper defaults by setting `export BK_METADATA_OPTIONS=none`.
If one would want to configure Bookies without Pulsar Metadata, it is necessary to configure
`metadataServiceUri` in bookkeeper.conf and `bookkeeperMetadataServiceUri` in broker.conf.
For example `bookkeeper.conf`
```properties
metadataServiceUri=zk://<zk_node_1>:2181/ledgers,zk://<zk_node_2>:2181/ledgers,zk …
```

[improve][common] Make Bookkeeper metadata options configurable

---

pulsar-client-cpp/include/pulsar/ConsumerConfiguration.h
pulsar-client-cpp/lib/ClientImpl.cc
pulsar-client-cpp/lib/ConsumerConfiguration.cc
pulsar-client-cpp/lib/ConsumerConfigurationImpl.h
pulsar-client-cpp/lib/ConsumerImpl.cc
pulsar-client-cpp/lib/ConsumerImpl.h
pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc
pulsar-client-cpp/lib/ReaderImpl.cc
pulsar-client-cpp/lib/Synchronized.h
pulsar-client-cpp/python/pulsar_test.py
pulsar-client-cpp/tests/ConsumerTest.cc

Fixes #17186
There are some cases in which it is useful to be able to include current
position of the message when reset of cursor was made.
* Support inclusive seek in c++ consumers.
* Add a unit test to verify.

[feature][client-cpp] Support inclusive seek for cpp client

---

pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/JdbcAbstractSink.java
pulsar-io/jdbc/sqlite/src/test/java/org/apache/pulsar/io/jdbc/SqliteJdbcSinkTest.java

This closes #17713.
PR in forked repository: https://github.com/tisonkun/pulsar/pull/3

fix: SqliteJdbcSinkTest close in order

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentSubscriptionTest.java

Fixes:
- #17755
Concurrent execution of these two instructions will throw an exception:
- Mocked objects are executing methods
- Bind the new mock behavior again
In this test, `cursorMock` triggers this error.
make "binding the new mock behavior" always running after "all methods execute finish"
- https://github.com/poorbarcode/pulsar/pull/14

[fix][flaky-test]PersistentSubscriptionTest.testCanAcknowledgeAndCommitForTransaction

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndWithoutBatchIndexAckTest.java

Fixes
- https://github.com/apache/pulsar/issues/17623
- https://github.com/apache/pulsar/issues/17637
Manually release resources, including `consumer`, `producer`, `pulsar client`, `transaction`, and `topic`. This saves `setup` and `cleanup` time before and after each method. 
- Manually release resources instead of calling `cleanup` & `setup` each method
- remove useless method `markDeletePositionCheck`
- `Integer.valueOf(int)` instead of `new Integer(int)`, because `new Integer(int)` is deprecated
- https://github.com/poorbarcode/pulsar/pull/10

[improve][test] Improve TransactionEndToEndTest to reduce the execution time

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/LookupRetryTest.java

Fixes #17785
The `failureMap` need to be clear after run per unit test.
Clear `failureMap` after run per unit test, and only run once `setup()`/`cleanup()` to reduce execution time.
PR in forked repository: https://github.com/coderzc/pulsar/pull/6

[fix][flask-test] Fix and improve LookupRetryTest

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupServiceTest.java

When the broker closes,  the scheduled task in ResourceGroupService may still execute, and cause NPE:
```
Sep 17 12:09:50 168-15-22-49 pulsar[8900]: 2022-09-17T12:09:50,050+0800 [pulsar-2-4] ERROR org.apache.pulsar.common.util.Runnables - Unexpected throwable caught
Sep 17 12:09:50 168-15-22-49 pulsar[8900]: java.lang.NullPointerException: null
Sep 17 12:09:50 168-15-22-49 pulsar[8900]: at org.apache.pulsar.broker.resourcegroup.ResourceGroupService.aggregateResourceGroupLocalUsages(ResourceGroupService.java:530) 
Sep 17 12:09:50 168-15-22-49 pulsar[8900]: at org.apache.pulsar.common.util.Runnables$CatchingAndLoggingRunnable.run(Runnables.java:54) 
Sep 17 12:09:50 168-15-22-49 pulsar[8900]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
Sep 17 12:09:50 …
```

[fix][broker] Fix NPE when ResourceGroupService execute scheduled task.

---

pom.xml
pulsar-client-all/pom.xml
pulsar-package-management/core/pom.xml

`pulsar-package-core` module is built with the maven compiler release flag equals to 17. However this module is used by the `pulsar-client-admin-original` module and we need to ensure binary compatibility to JDK8 for all the java client artifacts.
See more context here https://github.com/apache/pulsar/pull/17855
I did a simple test simulating an upgrade to Pulsar 2.11.0 in a JDK8 java application, like this
```
public static void main(String[] args) throws Exception {
@Cleanup
final PulsarAdmin admin = PulsarAdmin.builder()
.serviceHttpUrl("http://localhost:8080")
.build();
final PackageMetadata mypackage = admin.packages().getMetadata("mypackage");
}
```
and I got this error
```
java.lang.UnsupportedClassVersionError: org/apache/pulsar/packages/management/core/common/PackageName has been …
```

[branch-2.11] Ensure JDK8 compatibilty for Pulsar java clients

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricStreams.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TransactionAggregator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/PrometheusTextFormatUtil.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricStreamsTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/SimpleTextOutputStream.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/stats/PrometheusTextFormat.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerStatsManager.java

This PR is fully based on https://github.com/apache/pulsar/pull/17618, but the origin PR has a memory leak issue, so it was reverted.
This PR is supposed to fix the memory leak issue.
Why the origin PR has a memory leak issue:
In https://github.com/apache/pulsar/pull/17618, PrometheusMetricsGenerator.java:
```
public static void generate(PulsarService pulsar, boolean includeTopicMetrics, boolean includeConsumerMetrics,
boolean includeProducerMetrics, boolean splitTopicAndPartitionIndexLabel,
OutputStream out,
List<PrometheusRawMetricsProvider> metricsProviders)
throws IOException {
ByteBuf buf = ByteBufAllocator.DEFAULT.heapBuffer();
boolean exceptionHappens = false;
//Used in namespace/topic and transaction aggregators as share metric names
PrometheusMetricStreams metricStreams = new …
```

[branch-2.9] Group prometheus metrics.

---

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactorTool.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorToolTest.java

Improve the compactor tool, using separate TLS config
- Add separate TLS config on the compactor, both Keystore and PEM formats are supported
- Fix correct use of service URL by `brokerConfig.isBrokerClientTlsEnabled()` value
Test has been added.

[improve][cli] Using separate TLS config on the compactor

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/EntryCache.java

The method `invalidateEntries` aims to remove from cache all the entries related to a ledger up to lastPosition. And the `lastPosition` is non-inclusive as opposed to its explanation. See L173.
https://github.com/apache/pulsar/blob/e771fc885afe2cc3807fa491af2510a25377ed57/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java#L161-L173
correct the explanation for `invalidateEntries`
- Anything that …

[fix][doc]correct the explanation for invalidateEntries in the EntryCache

---

pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceTransactionTest.java

Fixes: #14109
The expected execution flow for this test is: 
1. send 505 messages
2. commit 10 transactions, every transaction ack 50 messages
3. receive the last 5 messages in the last transaction, wait for transaction timeout
4. confirm that the last 5 messages can be consumed by new consumer
<strong>(High light)</strong> The default value for transaction TTL is 10 seconds, and the default value for `Awaitility.await` is also 10 seconds,  so this test is not stable.
Note: This is a guess cause, the problem is not reproduced locally. But after transaction TTL is set to 11s, the probability of the problem occurring is 100%.
Fix flaky test
- set transaction TTL to 5s
Other changes
- define a name for the task thread
- acknowledge the last 5 messages
- …

[fix][flaky-test]PerformanceTransactionTest.testConsumeTxnMessage

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStore.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreProvider.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedLedgerMetricsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/TransactionBatchWriterMetricsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckMetadataTest.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/DisabledTxnLogBufferedWriterMetricsStats.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionLogImpl.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStoreProvider.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriter.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterMetricsStats.java
pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/MLTransactionMetadataStoreTest.java
pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionLogImplTest.java
pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterTest.java

- Make transaction `MLTransactionMetadataStoreProvider` & `MLPendingAckStoreProvider` support buffered writer metrics.
- Motivation: #15370
----
- Delete constructor of `TxnLogBufferedWriter` without parameter `metrics`.
- Motivation: it is unnecessary.
---- 
- Add a default `DisabledTxnLogBufferedWriterMetricsStats` implementation.
----
- Previous PR remaining code to optimize: remove the check code `if (metrics != null)`. The motivation see:
- Motivation: https://github.com/apache/pulsar/pull/16758#discussion_r945512673
----
- Make transaction log buffered writer only create by the `MLTransactionMetadataStoreProvider` & `MLPendingAckStoreProvider`. 
- Motivation: https://github.com/apache/pulsar/pull/16758#discussion_r961254161
- …

[improve][txn]PIP-160 make txn components supports buffered writer metrics

---

pulsar-proxy/pom.xml
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyConnectionThrottlingTest.java

Fixes:
- #17665
this test is executed as follows: 
1. set max connection limited 4
2. create two clients and two producers, this will create 4 connections 
3. try to create another client and producer, this will fail cause of reaches the max connections count limit
But the execution logic of `step-3` is like this:
1. increment `DefaultConnectionController.totalConnectionNum`
2. if the state `State.REACH_MAX_CONNECTION_PER_IP` founded, do close connection which will decrement `DefaultConnectionController.totalConnectionNum`
Then the problem is that the connection closes was executed asynchronously(see code below), if the main thread executes fast enough, the assert `Assert.assertEquals(ConnectionController.DefaultConnectionController.getTotalConnectionNum(), 4)` will fail, because the last …

[fix][flaky-test]ProxyConnectionThrottlingTest.testInboundConnection

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerFactory.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/offload/OffloadUtils.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadPrefixTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestBaseOffload.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestFileSystemOffload.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestOffloadDeletionFS.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestS3Offload.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestUniversalConfigurations.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarTieredStorageTestSuite.java

Fixes #9962 
Offloaded ledgers can be orphaned on topic deletion. 
Topic to be truncated before deletion to delete offloaded ledgers properly and fail if truncation fails.
This change added integration tests
Nothing changed in the options but admin CLI will implicitly run truncate before topic delete. 
(Your PR needs to update docs …

[Fix][Tiered Storage] Eagerly Delete Offloaded Segments On Topic Deletion

---

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/PerfToolTest.java

Fixes #17823
If PerformanceReader can read exactly as many messages as specified by `num-messages`, it does not stop but waits for another message.
Check the number of total messages after incrementing the counter.
- Added integration tests for `pulsar-perf read` 
This is a bugfix
PR in forked repository: https://github.com/andrasbeni/pulsar/pull/6

[fix][cli] Check numMessages after incrementing counter 

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java
pulsar-proxy/pom.xml
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyClientCnx.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyRefreshAuthTest.java

Fixes https://github.com/apache/pulsar/issues/10816
The proxy client cannot refresh the user(original) authentication data immediately. If cannot refresh token, the user(original) client and proxy client can work fine based on reconnection, but this will affect the Pulsar performance.
New version:
```
2022-09-23T11:18:36,607 - INFO  - [pulsar-proxy-io-38-2:ProxyConnection@341] - [/127.0.0.1:51556] complete connection, init proxy handler. authenticated with token role client, hasProxyToBrokerUrl: false
2022-09-23T11:18:36,615 - INFO  - [pulsar-proxy-io-38-5:ConnectionPool@245] - [[id: 0x3e7cc63b, L:/127.0.0.1:51557 - R:localhost/127.0.0.1:51549]] Connected to server
2022-09-23T11:18:36,635 - INFO  - [pulsar-io-6-1:ServerCnx@299] - New connection from /127.0.0.1:51557 …
```

[fix][proxy] Fix refresh client auth

---

managed-ledger/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
managed-ledger/src/test/java/org/apache/bookkeeper/test/ZooKeeperUtil.java
pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/BookKeeperPackagesStorageTest.java
pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/bookkeeper/test/BookKeeperClusterTestCase.java
pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/bookkeeper/test/ZooKeeperUtil.java

Fixes: https://github.com/apache/pulsar/issues/15773  https://github.com/apache/pulsar/issues/16863 https://github.com/apache/pulsar/issues/16860
```
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 87.06 s <<< FAILURE! - in org.apache.pulsar.packages.management.storage.bookkeeper.BookKeeperPackagesStorageTest
Error:  setUp(org.apache.pulsar.packages.management.storage.bookkeeper.BookKeeperPackagesStorageTest)  Time elapsed: 13.089 s  <<< FAILURE!
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
at org.apache.bookkeeper.zookeeper.ZooKeeperWatcherBase.waitForConnection(ZooKeeperWatcherBase.java:159)
at …
```

[fix][flaky-test] BookKeeperClusterTestCase.setup()

---

README.md
site2/website/versioned_docs/version-2.10.x/getting-started-standalone.md

Fix the documentation of installing JVM on M1 - remove one installation method of sdkman (using brew) and add the deleted instructions to building Pulsar on README

[fix][doc] Fix M1 JVM Installation Instructions

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ClusterMetadataSetupTest.java

In the actual production environment,  users may only use one default namespace (public/default). 
The number of bundles in this namespace is a default value of 16. 
1. if the cluster has more than 16 brokers, some brokers will serve no traffic 
2. if the topics in these bundles are not equal, the load will be unbalanced
In addition, the manually split bundle is complicated and auto-split may lead to unstable services. 
We expect to set a relatively large number of bundles for the default namespace when the cluster is built.
support setting bundle number for default namespace when setting up cluster metadata 
<strike>and the bundle number is the `defaultNumberOfNamespaceBundles`  from `broker.conf`</strike>
and the bundle number passed by a new option like …

support setting bundle number for default namespace when set up cluster

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/AbstractBatchMessageContainer.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/BatchMessageContainerImplTest.java

When adding messages to `BatchMessageContainerImpl`, it takes a lot of cpu time for the list growing of `BatchMessageContainerImpl#messages`, see below:
* Init `BatchMessageContainerImpl#messages` with capacity.
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/3

[improve][java-client]Add init capacity for messages in BatchMessageContainerImpl

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java

Fixes #17885
Master Issue: #17885
See #17885, And I checked other usages.
- Change rate unit to Mbit.

[fix][loadbalance] Fix the wrong NIC speed rate unit.

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java

Fixes: #16864
I think it is a wrong configuration(`ackTimeout 1s`) when writing the code, the original design is set `negativeAckRedeliveryDelay 1s`
The process expects:
- send 10 messages in one batch
- submit a batch. 
- receive 10 messages, do negative acknowledge
- after `1s`, will trigger `redelivery`
- receive 10 messages again
The real process:
- send 1 message
- Reach the batch time limit, and submit a batch. return `msgId_1`
- send 9 messages in another batch
- submit a batch. return `msgId_2`
- receive 10 messages, do negative acknowledge
- push the `msgId_1` to `negativeAcksTracker`
- push the `msgId_2` to `unAckedMessageTracker`
- after `1s`, will trigger redelivery `msgId_2` by `unAckedMessageTracker`
- receive 9 messages( `msgId_2` ) again
- after `60s`, will trigger …

[fix][flaky-test]NegativeAcksTest.testNegativeAcksWithBatchAckEnabled

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorContainer.java

fix typo error in ManagedCursorContainer

[cleanup][managed-ledger]fix typo error in ManagedCursorContainer

---

.github/workflows/pulsar-ci-flaky.yaml

There's a typo in pulsar-ci-flaky workflow definition which results in the workflow to get run for document only changes.
This was a typo in #17881 at https://github.com/apache/pulsar/pull/17881/files#diff-3559f910180dd3552d2e3708c794b1826ef5ac328ff28657a4fabd1201b61fddR74
- fix typo

[fix][CI] Don't run pulsar-ci-flaky workflow for PRs which contain only document changes

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/FunctionApiV3ResourceTest.java

When `uploadBuiltinSinksSources` is set to false (non-default), the download function is not considering the component type and only looking into the connectors dir. 
Also we are scanning the connectors dir instead of using the info from the ConnectorsManager. 
This change looks at the component type if the download function is called with tenant+ns+name to choose between the ConnectorsManager and the FunctionsManager to get the archive path. 
If the download function is called with a direct path, we look first into the ConnectorsManager then into the FunctionsManager.
* Run tests in `FunctionApiV3ResourceTest`
no
fix
(Your …

[fix][functions] Fix the download of builtin Functions

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/stats/client/PulsarBrokerStatsClientTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ManagedLedgerInternalStats.java

The active state indicates whether a cursor is active. And it affects the cache hit rate, because inactive cursors will be evicted from the entry cache. This active state helps to troubleshoot issues with low cache hit rate.
Also it is meaningful for configuring a suitable values for `managedLedgerCursorBackloggedThreshold` in `ServiceConfiguration`
```
managedLedgerCursorBackloggedThreshold=1000
```
Add active status into cursor stats.
It will get the following sample data when getting the `internalStats` of a partitioned topic.
```
{
"entriesAddedCounter": 6,
"numberOfEntries": 10302152,
"totalSize": 63786554161,
"currentLedgerEntries": 6,
"currentLedgerSize": 31182,
"lastLedgerCreatedTimestamp": "2022-09-29T14:48:52.825+08:00",
"waitingCursorsCount": 0,
"pendingAddEntriesCount": 0, …
```

[improve][broker]add active status into cursor stats

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java

[fix][broker] Fix the broker shutdown issue after the Zookeeper node crashed
The broker was shutdown unexpectedly after the Zookeeper node crashed. I have a test to kill the zookeeper node periodically, sometimes the following logs will appear
```
Sep 30 12:21:33 ip-10-0-0-160.us-west-2.compute.internal pulsar[21529]: 2022-09-30T12:21:33,214+0000 [metadata-store-zk-session-watcher-7-1] WARN  org.apache.pulsar.metadata.impl.ZKSessionWatcher - ZooKeeper client is disconnected. Waiting to reconnect, time remaining = 22.245 seconds
Sep 30 12:21:35 ip-10-0-0-160.us-west-2.compute.internal pulsar[21529]: 2022-09-30T12:21:35,214+0000 [metadata-store-zk-session-watcher-7-1] WARN  org.apache.pulsar.metadata.impl.ZKSessionWatcher - ZooKeeper client is disconnected. Waiting to reconnect, time …
```

[fix][broker] Fix the broker shutdown issue after Zookeeper node crashed

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/AbstractBatchMessageContainer.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/BatchMessageContainerImplTest.java

There will be memory waste when producer publishes messages with batch enable, which may cause some problems, e.g., issue https://github.com/apache/pulsar/issues/17662  and issue https://github.com/apache/pulsar/issues/14943
The PR https://github.com/apache/pulsar/pull/15033 try to fixed the memory waste problem but bringing a significant performance regression.
Here we introduce another way to solve the memory waste problem through shrinking the `maxBatchSize` of `BatchMessageContainerImpl`,  without bringing performance regression,  which will solve the two issues list above.
Following is the test result to approve it：
Reducing the memory waste will be very helpful for this issue:  https://github.com/apache/pulsar/issues/17662
After applying this PR, following the steps of the issue to …

[improve][java-client]Shrink BatchMessageContainer maxBatchSize

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerFactory.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStore.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/ShadowTopicTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

Master Issue: https://github.com/apache/pulsar/issues/16153
The main purpose of this part is to support shadow topic creation.
Note:  
1. A topic must defined as shadow topic at creation, or else it will create its own ledgers. So this PR uses topic property(key="PULSAR.SHADOW_SOURCE", value="$SourceTopic") to identify the topic is shadow topic.
2. shadow topic can't change to non-shadow or change its shadow source in its whole life time. You must delete it first and recreate.
3. Deleting an shadow topic is just like deleting normal topic.
Key changes:
1. Read topic properties from storage before loading a topic, see `checkOwnershipAndCreatePersistentTopic`
2. Add admin interface and cli for `createShadowTopic` and `getShadowSource`
3. Add `ShadowManagedLedgerImpl`, but it's not …

[feat][broker]PIP-180 Shadow Topic - Part V - Support shadow topic creation.

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerException.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/MockManagedLedger.java

Speed up  the process of `PersistentMessageExpiryMonitor` expiring message when ledgers not exist.
For details:
Without consumer acking messages, the `PersistentMessageExpiryMonitor` expires messages process could be very slow if the ledger `PersistentMessageExpiryMonitor`  be read has been deleted from the bookkeeper.
The root cause is that,  when `autoSkipNonRecoverableData` is true and the ledger to be read has been deleted, the `expireMessages` will read entry failed and set the markDeletePosition as the failed position, see Line194.  And then waiting to be scheduled(defalut value is 5min)
https://github.com/apache/pulsar/blob/49eaa548b97eca06a6aff5d79391d49f085adb9e/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java#L186-L196 …

[improve][broker]Improve PersistentMessageExpiryMonitor expire speed when ledger not existed

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BookieServiceInfoSerde.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClient.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClientTest.java

This reverts commit 8d7ac33751c62383b510a04ec223981bd70cd4db.
Fixes #17913
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*

Revert "Make BookieId work with PulsarRegistrationDriver (#17762)"

---

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceBaseArguments.java
pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerfClientUtilsTest.java
pulsar-testclient/src/test/resources/perf_client1.conf

An invalid change introduced to the CI workflow in PR #17881 allowed merging PRs that contained test failures. 
PR #17862 contained some minor gaps in the changes that were introduced and had failing tests. 
This got merged because the "required checks" check was broken in CI.
- add tests
- fix issues in parsing logic
- fix typo in property name
PR in forked repository: https://github.com/lhotari/pulsar/pull/94

[fix][testclient] Fix proxyProtocol parsing when value is empty, fix invalid property name

---

.github/workflows/pulsar-ci.yaml

After https://github.com/apache/pulsar/pull/17881 the "CI checks completed" job only verify the system-tests, bypassing all the other tests. Diff https://github.com/apache/pulsar/pull/17881/files#diff-069360707fedfc682947effc8f7fac874fa378ec5c70abec25f88939c87379d3R959
I noticed it in https://github.com/apache/pulsar/pull/17915
* Restore all the required jobs verification
Also closes #17923

[fix][ci] CI: fix required jobs check

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java

Fixes #17941
I found some typos in ManagedLedgerConfig file. You can search `when when` keyword.
Remove one `when `
This change just removes `when ` from the comment, with no code change.
No document need change.
PR in forked repository: [https://github.com/Hongten/pulsar.git](https://github.com/Hongten/pulsar.git)

[fix][doc] There are some typos in ManagedLedgerConfig

---

site2/docs/client-libraries-node.md

Fixes https://github.com/apache/pulsar/issues/17786
* We want to make compatibility table single source because it is hard to keep all of them up-to-date.
* Make node and c++ client compatibility table a link to github.

[doc]Make node and c++ client compatibility table a link to github

---

pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/Utils.java
pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/UtilsTest.java

In the Kinesis sink with `FULL_MESSAGE_IN_JSON_EXPAND_VALUE`, a message with KeyValue schema and with value=NULL you get this NPE
```
2022-10-07T07:27:33,698+0000 [public/default/kinesis-sink-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Encountered exception in sink write: 
java.lang.NullPointerException: null
at org.apache.pulsar.io.kinesis.Utils.toJsonSerializable(Utils.java:250) ~[HsqgvoaXuefCgCSXYBQtdA/:?]
at org.apache.pulsar.io.kinesis.Utils.serializeRecordToJsonExpandingValue(Utils.java:222) ~[HsqgvoaXuefCgCSXYBQtdA/:?]
at org.apache.pulsar.io.kinesis.KinesisSink.createKinesisMessage(KinesisSink.java:308) ~[HsqgvoaXuefCgCSXYBQtdA/:?]
at org.apache.pulsar.io.kinesis.KinesisSink.write(KinesisSink.java:135) ~[HsqgvoaXuefCgCSXYBQtdA/:?]
at …
```

[fix][connector] Kinesis sink: fix NPE with KeyValue schema and no value

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java

FIx test which was broken by https://github.com/apache/pulsar/pull/17711
```
FAILED: testAckCommand
java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at org.apache.pulsar.broker.service.ServerCnxTest.testAckCommand(ServerCnxTest.java:1387)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at …
```

[test] Fix broken test by PIP-180

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
pulsar-broker/src/test/java/org/apache/pulsar/PulsarStandaloneTest.java

Some namespace policy is ignored if the namespace is created directly by the `NamespaceResources`, because the conf file affects this policy.
- Use `admin` to create a namespace instead of the `NamespaceResources`
https://github.com/nodece/pulsar/pull/4

[fix][broker] Fix create ns

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/PositionImpl.java

Skip numOfEntriesToRead entries instead of skipping a ledger.
When isAutoSkipNonRecoverableData=true, if a NonRecoverableLedgerException exception occurs when reading data, readPosition will automatically adjust to the next ledger to continue reading, which will result in a lot of existing data that cannot be read.
Therefore, the entry skip logic is modified to: only skip numOfEntriesToRead entries instead of skipping a ledger

[improve][broker]Skip numOfEntriesToRead entries instead of skipping a ledger

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java

When the compressed message size exceeds maxMessageSize, the information in the InvalidMessageException may be incorrect.
When the following conditions are met, the message data will be compressed, the string variable compressedStr should be assigned the value "Compressed", but the variable is assigned the empty string:
```
1. isBatchMessagingEnabled() return true;
2. msgMetadata.hasDeliverAtTime() return true;
3. compressedSize > ClientCnx.getMaxMessageSize() is true
4. conf.getCompressionType() != CompressionType.NONE is true;
```
https://github.com/apache/pulsar/blob/9ff9703d740eb8151b8cf2eb1e7faf074e9cf3c7/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L454-L473
We should remove the !isBatchMessagingEnabled() condition when the compressedStr is calculated: …

[fix][client] When the compressed message size exceeds maxMessageSize, the information in the InvalidMessageException may be incorrect

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java

After the bundle is split, update the new bundle information to admin/policies.
PR in forked repository: https://github.com/lordcheng10/pulsar/pull/17

[fix][broker] Update new bundle-range to  policies after bundle split

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java

`org.apache.pulsar.broker.admin.AdminResource#fetchPartitionedTopicMetadataCheckAllowAutoCreation` and `org.apache.pulsar.broker.admin.AdminResource#fetchPartitionedTopicMetadata` are no longer used.
remove `org.apache.pulsar.broker.admin.AdminResource#fetchPartitionedTopicMetadataCheckAllowAutoCreation` and `org.apache.pulsar.broker.admin.AdminResource#fetchPartitionedTopicMetadata`.
PR in forked repository: https://github.com/Pomelongan/pulsar/pull/7

[cleanup][broker]remove methods no longer used in AdminResource #7

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java

The backlog quota in time does not work due to time unit inconsistency in dropping the backlog on a topic.
The unit of backlog quota limit in time is seconds.
https://github.com/apache/pulsar/blob/8d13ff81108b95ae5f63245e4a5edf4e097aaf47/pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/BacklogQuota.java#L47-L52
The time unit inconsistency is here as follows.
https://github.com/apache/pulsar/blob/8d13ff81108b95ae5f63245e4a5edf4e097aaf47/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java#L221-L224
unify time unit.
- The …

[fix][broker]unify time unit at dropping the backlog on a topic

---

pom.xml

`scala-library.version` in pom.xml is no longer used.
remove unused `scala-library.version` from pom.xml
PR in forked repository: https://github.com/Pomelongan/pulsar/pull/6

[clean][pom]remove unused scala-library.version from pom.xml

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java

`org.apache.pulsar.broker.service.persistent.PersistentMessageExpiryMonitor#findEntryFailed` lacks a return, resulting in repeated execution of some codes.
add return for `org.apache.pulsar.broker.service.persistent.PersistentMessageExpiryMonitor#findEntryFailed`
PR in forked repository: https://github.com/Pomelongan/pulsar/pull/3

[fix][broker] add return for PersistentMessageExpiryMonitor#findEntryFailed

---

site2/docs/deploy-docker.md

Master https://github.com/apache/pulsar/issues/17774
The old implementation is incomplete. 
Rewrite it, and add a docker-compose.yaml.

[fix][doc] Rewrite the steps of docker-deploy

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java

Update deleteSubscription returns 404 meaning: Topic or subscription does not exist:
PR in forked repository: https://github.com/lordcheng10/pulsar/pull/24

[fix][broker] Update 404 message for deleteSubscription

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/cache/impl/MetadataCacheImpl.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java

In line 302 of `MetadataCacheImpl#executeWithRetry`,
the result of the future is set to a `null` value, which will lead to getting the result of `readModifyUpdate` and `readModifyUpdateOrCreate` will get a null value.
Fortunately, we haven't used this value for the time being.
https://github.com/apache/pulsar/blob/774c50b955d5be799ffbeee8c10d79f7dcb31d3b/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/cache/impl/MetadataCacheImpl.java#L295-L313
Fix executeWithRetry result is null and modify the test to cover it.
*(or)*
*(or)* …

[fix][broker] Fix executeWithRetry result is null

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
site2/docs/reference-metrics.md
site2/website/versioned_docs/version-2.10.0-deprecated/reference-metrics.md
site2/website/versioned_docs/version-2.6.0/reference-metrics.md
site2/website/versioned_docs/version-2.6.1/reference-metrics.md
site2/website/versioned_docs/version-2.6.2/reference-metrics.md
site2/website/versioned_docs/version-2.6.3/reference-metrics.md
site2/website/versioned_docs/version-2.6.4/reference-metrics.md
site2/website/versioned_docs/version-2.7.0/reference-metrics.md
site2/website/versioned_docs/version-2.7.1/reference-metrics.md
site2/website/versioned_docs/version-2.7.2/reference-metrics.md
site2/website/versioned_docs/version-2.7.3/reference-metrics.md
site2/website/versioned_docs/version-2.7.4/reference-metrics.md
site2/website/versioned_docs/version-2.8.0-deprecated/reference-metrics.md
site2/website/versioned_docs/version-2.8.1-deprecated/reference-metrics.md
site2/website/versioned_docs/version-2.8.2-deprecated/reference-metrics.md
site2/website/versioned_docs/version-2.8.3-deprecated/reference-metrics.md
site2/website/versioned_docs/version-2.9.0-deprecated/reference-metrics.md
site2/website/versioned_docs/version-2.9.1-deprecated/reference-metrics.md
site2/website/versioned_docs/version-2.9.2-deprecated/reference-metrics.md

Suppose there is a non-partitioned topic has more than 1000 producers (1000 is `loadBalancerNamespaceBundleMaxSessions` default value), `pulsar_lb_bundles_split_count` metric will increase constantly due to corresponding bundle reached maxBundleSessions, even the bundle range is 1 (upper - lower) that actually will skip this bundle.
Only increase `pulsar_lb_bundles_split_count` metric if bundle splits succeed.
PR in forked repository: https://github.com/Shawyeok/pulsar/pull/2

[fix][broker] Fix incorrect bundle split count metric

---

.github/PULL_REQUEST_TEMPLATE.md
.github/changes-filter.yaml

This PR adds a reminder for users to attach local preview screenshots to PR descriptions.
Context: https://github.com/apache/pulsar/pull/17853#issuecomment-1274299184

[improve][doc] Add doc preview reminder to PR template

---

.github/workflows/ci-go-functions.yaml
.github/workflows/ci-maven-cache-update.yaml
.github/workflows/ci-owasp-dependency-check.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

- Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- Pulsar uses actions/checkout@v2, actions/cache@v2 and actions/setup-java@v2 which are all deprecated.
- replace `actions/checkout@v2` with `actions/checkout@v3`
- replace `actions/cache@v2` with `actions/cache@v3`
- replace `actions/setup-java@v2` with `actions/setup-java@v3`
PR in forked repository: https://github.com/lhotari/pulsar/pull/101

[fix][ci] Use GitHub Actions versions that aren't deprecated

---

pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java
pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/ConfigurationStringUtil.java
pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java
pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMappingTest.java

When the `metadataServiceUri` or the `zkServers` configuration for `BookieRackAffinityMapping` is provided as a comma delimited list, it is automatically parsed into an ArrayList by the configuration class because the Bookkeeper configuration class relies on the defaults in the `org.apache.commons.configuration.AbstractConfiguration` class. Here is a sample error:
```
2022-07-29T19:25:43,437+0000 [main] ERROR org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Failed to initialize DNS Resolver org.apache.pulsar.zookeeper.ZkBookieRackAffinityMapping, used default subnet resolver
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
```
Also, …

[fix][bookie] Correctly handle list configuration values

---

.github/workflows/ci-semantic-pull-request.yml

cc @nicoloboschi 
Reduce unnecessary workflow trigger. See also https://github.com/apache/pulsar/pull/17961#discussion_r991902240.

[improve][ci] Avoid PR title check on synchronized

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/NamespaceEventsSystemTopicServiceTest.java

Fixes #17979
While upgrading broker version from 2.8.2 to 2.9.3, broker log shows lots of `Unable to read schema` error, which should not happen.
#12598 has tried to fix the same bug but not completely. `schemaCompatibilityStrategy` in `org.apache.pulsar.broker.service.AbstractTopic` is `SchemaCompatibilityStrategy.FULL` defaultly and only be updated in `org.apache.pulsar.broker.service.AbstractTopic#setSchemaCompatibilityStrategy`.
https://github.com/apache/pulsar/blob/4abd4d23e8ab498e0c72c4e062063d6409f66da9/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java#L552-L567
Once `org.apache.pulsar.broker.service.AbstractTopic#setSchemaCompatibilityStrategy` not called, the `schemaCompatibilityStrategy` of system topics will always be …

[fix][broker][branch-2.9] Fix system topic schema not compatible bug

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java

remove unused method getTotalServiceUnitsLoaded.
[[run-tests][clean][broker] remove unused method getTotalServiceUnitsLoaded ](https://github.com/lordcheng10/pulsar/pull/21)

[cleanup][broker] remove unused method getTotalServiceUnitsLoaded

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java

In https://github.com/apache/pulsar/pull/13950, we switched an error log to an info log. @hsaputra requested on Pulsar Slack we use warn level so that alerts still fire in for the case when the topic is not found.
* Replace `info` with `warn` when topic is not found in the `ServerCnx` class.

[improve][broker] ServerCnx: log at warning level when topic not found

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java

```
Error:  Tests run: 52, Failures: 1, Errors: 0, Skipped: 27, Time elapsed: 353.204 s <<< FAILURE! - in org.apache.pulsar.broker.admin.NamespacesTest
Error:  testSplitBundleForMultiTimes(org.apache.pulsar.broker.admin.NamespacesTest)  Time elapsed: 0.326 s  <<< FAILURE!
org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: 
Message: Namespace bundle my-tenant/namespace-86da66f1-e68d-480a-b5bb-9f78a2f52fc9/0x00000000_0x08000000 is being unloaded
Stacktrace:
java.lang.IllegalStateException: Namespace bundle my-tenant/namespace-86da66f1-e68d-480a-b5bb-9f78a2f52fc9/0x00000000_0x08000000 is being unloaded
at org.apache.pulsar.broker.namespace.NamespaceService.lambda$findBrokerServiceUrl$9(NamespaceService.java:419) …
```

[fix][test] Fix flaky test `testSplitBundleForMultiTimes`.

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/BooleanSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ByteBufSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ByteBufferSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ByteSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/BytesSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/DateSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/DoubleSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/FloatSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/InstantSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/IntSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/JSONSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/LocalDateSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/LocalDateTimeSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/LocalTimeSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/LongSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ShortSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/StringSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/TimeSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/TimestampSchema.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/KeyValueSchemaInfoTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/StringSchemaTest.java
pulsar-common/pom.xml
pulsar-common/src/main/java/org/apache/pulsar/client/impl/schema/SchemaInfoImpl.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/schema/SchemaHash.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java

Fixes https://github.com/apache/pulsar/issues/17931
The PR https://github.com/apache/pulsar/pull/17049 bring a significant performance regression for publish throughput. The root cause  is that  `HashFunction#hashBytes(byte[])` takes a lot of cpu time. So we need add a cache for `SchemaHash`. 
For details see line97:
https://github.com/apache/pulsar/blob/8d13ff81108b95ae5f63245e4a5edf4e097aaf47/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java#L85-L99
And we can see that `hashFunction` takes a lot of cpu time from the [flame graph](https://github.com/apache/pulsar/files/9708735/before_revert.html.zip) below
The test result for publish throughput(msgs/s) is below：
| |master branch| master branch revert PR#17049 | master branch apply this patch|
| -- |---|---|---| …

[improve][client] Refactor SchemaHash to reduce call of hashFunction in SchemaHash

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/PendingReadsManager.java

In case of error conditions we are not releasing the entries returned by partial reads. 
Release the entries on the error handling paths.

[fix][broker] Fix memory leak in case of error conditions in PendingReadsManager

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java

Avoid unnecessary creation of BitSetRecyclable objects.
https://github.com/apache/pulsar/blob/5c31c9af04176f81d1616dde64567d0e0ce1f2c8/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L2190-L2196
When batchDeletedIndexes does not contain the given position, the same BitSetRecyclable will be created twice, and the following logic does not need to be executed at this time:
`bitSet.and(givenBitSet);`
PR in forked repository:  https://github.com/lordcheng10/pulsar/pull/25

[improve][broker] Avoid unnecessary creation of BitSetRecyclable objects

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java

In the current implementation, `notifyPendingBatchReceivedCallBack` method always runs on `internalPinnedExecutor` thread, So, no need to use the lock to sync it.
- Remove useless locks in batch receiving.
https://github.com/shibd/pulsar/pull/19

[refactor][client] Remove useless locks in batch receiving

---

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicImplTest.java

`CompactedTopicImpl.findStartPointLoop` uses the binary search, but the implementation had a flaw that caused several more loops to be executed. If an array like this: `[1,2,3...100]`, and we search value `2` in this array, `CompactedTopicImpl.findStartPointLoop` will execute the following loops:
```
start: 0, mid:50, end: 100
start: 0, mid:25, end: 50
start: 0, mid:12, end: 25
start: 0, mid:6, end: 12
start: 0, mid:3, end: 6
start: 0, mid:1, end: 3
start: 1, mid:1, end: 1    bingo!
```
We can optimize the loop like this:
```
start: 0, mid:50, end: 100
start: 1, mid:25, end: 50    bingo!
```
- https://github.com/poorbarcode/pulsar/pull/20

[improve][broker] Make CompactedTopicImpl.findStartPointLoop work more efficiently

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/InMemoryDeliveryTrackerTest.java

In the InMemoryDelayedDeliveryTracker, the `priorityQueue` should be closed after the `timeout` task is canceled, otherwise, we may operate the `priorityQueue` that has been closed.
Close the `priorityQueue` after the `timeout` task is canceled and set timeout=null.
PR in forked repository: https://github.com/coderzc/pulsar/pull/11

[fix][broker] Fix the order of resource close in the InMemoryDelayedDeliveryTracker

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java

Fix system service namespace(heartbeat namespace) creates internal `__change_events` topics:
```
2022-09-28T17:04:24,833 - INFO  - [metadata-store-12-1:ServerCnx@1474] - [/127.0.0.1:50223] Created new producer: Producer{topic=SystemTopic{topic=persistent://pulsar/localhost:50220/healthcheck}, client=/127.0.0.1:50223, producerName=test-0-0, producerId=0}
2022-09-28T17:04:24,845 - INFO  - [pulsar-io-6-3:ConsumerImpl@822] - [persistent://pulsar/localhost:50220/__change_events-partition-0][multiTopicsReader-895a02f0d4] Subscribing to topic on cnx [id: 0xc6ef1b83, L:/127.0.0.1:50223 - R:localhost/127.0.0.1:50218], consumerId 0
2022-09-28T17:04:24,848 - INFO  - [pulsar-io-6-3:ConsumerImpl@822] - [persistent://pulsar/localhost:50220/__change_events-partition-1][multiTopicsReader-895a02f0d4] …
```

[fix][broker] Fix system service namespace create internal event topic.

---

conf/broker.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
site2/docs/administration-zk-bk.md

Important details are missing for documenting ensemble (E) size, write quorum (Qw) size and ack quorum (Qa) size.
For example, it is not well known that there's a rule that E == Qw to use sticky reads or that the max number of bookie failures is Qa-1. Some might realize this only in production when they lose a bookie and cannot recover.
- improve documentation for persistence policies parameters

[improve][docs] Improve docs for persistence policies parameters E, Qw and Qa.

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java

Fixes #17967
Master Issue: #17967
The root cause is here(line-3365)  :
https://github.com/apache/pulsar/blob/08f5766d95034ce27c44ee30e4734d2a8f078e11/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L3364-L3366
The `currentLedgerId` should be : 
```
currentLedgerId = lid != null ? lid : (ledgers.lastKey());
```
PR in forked repository: https://github.com/Technoboy-/pulsar/pull/9

[fix][broker] Fix `getPositionAfterN` infinite loop.

---

.github/PULL_REQUEST_TEMPLATE.md

Whenever a PR changes the threading model we need to make clear that we should track these changes
I want follow changes in the threading model in order to help understand and document Pulsar's internal architecture.
Adding a checkbox should hopefully make developers more thoughtful about explicitly noting changes to the threading model.
Adds a checkbox about "the threading model"
This change is to the PULL REQUEST TEMPLATE no test coverage required.

[improve][misc] Highlight change to threading

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionTest.java

Fixes #17635
- #17635
- Use the `namespace-clean` instead `pulsar-restart`, saves `pulsar.start()` and `pulsar.stop()` time before and after each method. 
After improve, `KeySharedSubscriptionTest` cost  210s
```
[INFO] Tests run: 43, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 210.841 s - in org.apache.pulsar.client.api.KeySharedSubscriptionTest
```
- https://github.com/poorbarcode/pulsar/pull/23

[improve][test] Improve KeySharedSubscriptionTest to reduce the execution time

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

In `org.apache.pulsar.broker.admin.impl.PersistentTopicsBase#createSubscriptions`, when subscriptions are successfully created on the new partitions, the log print content is "successfully created new partitions", not "successfully created subscriptions on new partitions".
In `org.apache.pulsar.broker.admin.impl.PersistentTopicsBase#createSubscriptions`, when subscriptions are successfully created on the new partitions, change the log printing content from "Successfully created new partitions" to "Successfully created subscriptions on new partitions".
PR in forked repository: https://github.com/Pomelongan/pulsar/pull/8

[fix][broker] Update the log print content of createSubscriptions

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleSchemaTest.java

Fixes #17644
- #17644
- Use the `topic-delete` & `client-cache-clean` instead `pulsar-restart`, saves `pulsar.start()` and `pulsar.stop()` time before and after each method. 
After improve, `SimpleSchemaTest` cost 44s
```
[INFO] Tests run: 66, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 44.052 s - in org.apache.pulsar.client.api.SimpleSchemaTest
```
- https://github.com/poorbarcode/pulsar/pull/24

[improve][test] Improve SimpleSchemaTest to reduce the execution time

---

pulsar-io/jdbc/mariadb/src/main/java/org/apache/pulsar/io/jdbc/MariadbJdbcAutoSchemaSink.java

When install `pulsar-io-jdbc-mariadb` module occurred checkstyle error.
> mvn clean install -pl pulsar-io/jdbc/mariadb
```
[INFO] --- maven-checkstyle-plugin:3.1.2:check (checkstyle) @ pulsar-io-jdbc-mariadb ---
[INFO] There is 1 error reported by Checkstyle 8.37 with /Users/zc/IdeaProjects/pulsar/buildtools/src/main/resources/pulsar/checkstyle.xml ruleset.
[ERROR] src/main/java/org/apache/pulsar/io/jdbc/MariadbJdbcAutoSchemaSink.java:[23,8] (imports) UnusedImports: Unused import: java.util.stream.Collectors.
```
Related PR：#17950
Remove unused import statement in the MariadbJdbcAutoSchemaSink.
PR in forked repository: https://github.com/coderzc/pulsar/pull/12

[fix][io] Remove unused import statement in the MariadbJdbcAutoSchemaSink

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SinksImpl.java

Fixes a NPE with transform-function+Sink on k8s because builtin is null in `getFunctionPackageLocation`.
There is no issue when not in k8s because then the packageUrl is used for the packagePath and its value is `builtin://xxx`
Use the builtin from the functionDetails that was previously set in `SinkConfigUtils::convert`
*(or)*
*(or)*
*(example:)*
*If the box was checked, please highlight …

[fix][io] Fix builtin sink transformation on k8s

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/OwnerShipForCurrentServerTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanPausedNamespaceService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/DispatcherBlockConsumerTest.java

Fixes #18029
- #18029
When the `AdminApi2Test` is executed, there have many test methods. When the next method is run, there may be an ongoing but unfinished `NamespaceService.onNamespaceBundleOwned()`, which will create system topic `__change_event`, if the instruction `namespace.delete()` is executed at the same time, the problem occurs.
Create a new class `CanPausedNamespaceService.java` witch can stop the subsequent execution of `NamespaceService.onNamespaceBundleOwned()`. Then, if we want to do `namespace.delete()`, we will do `pause` first.
- https://github.com/poorbarcode/pulsar/pull/25

[fix][test] Fix flaky test AdminApi2Test.resetClusters

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientCnxTest.java

https://github.com/apache/pulsar/blob/b89c1451551a6bbe681465726906a2e61c9d8a69/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L282-L297 
The `pendingLookupRequestSemaphore` will leak when channel inactive. There are `LookUpRequestSemaphore` not released when removing it from `pendingRequests`
We can't easily release the semaphore in `channelInactive`, because there are not only `LookUpRequest`. So release the semaphore when connectionException
Add unit test case to cover this change
bug fixs, no need doc

[fix] [pulsar-client] Fix pendingLookupRequestSemaphore leak when channel inactive

---

wiki/release/release-note-guide.md

Update the workflow of submitting release notes since:
- The automation process still needs to get release notes content from https://github.com/apache/pulsar-site/tree/main/site2/website-next/release-notes/versioned
- C++ and Python release notes can be fetched from their repos

[improve][doc] Update workflow of submitting release note

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java

When reading through the Proxy code, I noticed that the `remoteAddress` was used where it probably makes sense to use the `localAddress`.
After researching it a bit with the AWS docs https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/enable-proxy-protocol.html and the protocol spec http://www.haproxy.org/download/1.8/doc/proxy-protocol.txt, I think this implementation is correct.
* Replace `inboundChannel.localAddress` with `inboundChannel.localAddress`.
* Fix type checking

[cleanup][proxy] Use correct address for HAProxyMessage destination

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/FunctionApiV3ResourceTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/SinkApiV3ResourceTest.java

When using KubernetesRuntime, if uploadBuiltinSinksSources is false (non-default), the originalFileName is not set for builtin components.
But with k8s, we need a filename since the component will be downloaded. 
This results in the component currently being downloaded with the download directory as filename.
Also when using a transform function, we use the originalFileName to know if there's a builtin function to download.
Use the filename from the builtin component archive as originalFileName whether uploadBuiltinSinksSources is true or false.
*(or)*
*(or)* …

[fix][io] Fix builtin connector/function download filename

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml

Fixes CVE-2022-42889
Bump apache commons-text version to 1.10.0.

[fix][sec] Bump commons-text to 1.10.0 fix CVE-2022-42889

---

.github/workflows/ci-go-functions.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

Error message is:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Use the recommended fix by GitHub.
The actions used by Pulsar CI workflows will need to be upgraded to use @actions/core package version v1.10.0 or greater.
For example, paths-filter should be synced with the most recent release that contains the fix, https://github.com/dorny/paths-filter/releases/tag/v2.11.1 .

[fix][ci] Fix deprecation warnings about set-output in GitHub Action workflows

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BookieServiceInfoSerde.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClient.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClientTest.java

In Pulsar 2.10 the custom "BookieId" feature doesn't work anymore because in PulsarRegistrationDriver we are not implementing `getBookieServiceInfo`
This patch also partially resolves https://github.com/apache/pulsar/issues/17759
Implement `getBookieServiceInfo`
This is a new version of https://github.com/apache/pulsar/pull/17762.
The main difference is the additional commit, in which we mimic the original code in BookKeeper
see https://github.com/apache/bookkeeper/blob/034ef8566ad037937a4d58a28f70631175744f53/bookkeeper-server/src/main/java/org/apache/bookkeeper/discover/ZKRegistrationClient.java#L183
We cannot perform reads from the MetadataStore in `getBookieServiceInfo` because it is very likely that 
something will wait for the results of the returned CompletableFuture in a metadata …

Make BookieId work with PulsarRegistrationDriver (second take)

---

conf/broker.conf
conf/proxy.conf
conf/standalone.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderBasic.java
pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderBasicTest.java
pulsar-broker-common/src/test/resources/authentication/basic/.htpasswd
pulsar-common/src/main/java/org/apache/pulsar/client/api/url/URL.java

Cherry pick the #16526 and #16935.

[improve][authentication][branch-2.9] Improve get the basic authentication config

---

site2/docs/cookbooks-retention-expiry.md

I was looking for the default and I didn't notice that over was properly mentioned.
Small improvement to remind about the default behaviour.
Simple modification.
- [ X ] `doc` 
PR in forked repository: https://github.com/AlvaroStream/pulsar/tree/patch-6

[Improve][doc] Insist about default behaviour for retention.

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerBkTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/MultiBrokerBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/AdvertisedListenersTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/protocol/SimpleProtocolHandlerTestsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/PortManager.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/PortManagerTest.java
pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/bookkeeper/test/BookKeeperClusterTestCase.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/extensions/SimpleProxyExtensionTestBase.java

Fixes: https://github.com/apache/pulsar/issues/16544
now in tests, we getFreePort not occupied, just written in configuration, so it may be created repeatedly. If the socket port is repeatedly, the test will become flaky.
when we getFreePort, the port will be occupied and then if you use finished can release this port.
- https://github.com/congbobo184/pulsar/pull/2

[fix][test] AdvertisedListenersTest.setup

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/NamespaceEventsSystemTopicServiceTest.java

Master Issue: #17979
Related to #17986
Add test case to cover system topic schema compatibility.
Add test case (`org.apache.pulsar.broker.systopic.NamespaceEventsSystemTopicServiceTest#testSystemTopicSchemaCompatibility`) to cover system topic schema compatibility.
The `schemaCompatibilityStrategy` of system topic should always be the same as the conf `systemTopicSchemaCompatibilityStrategy`, which is default `SchemaCompatibilityStrategy.ALWAYS_COMPATIBLE`.
- `org.apache.pulsar.broker.systopic.NamespaceEventsSystemTopicServiceTest#testSystemTopicSchemaCompatibility`
PR in forked repository: https://github.com/dragonls/pulsar/pull/2

[improve][broker] Add test case for system topic schema not compatible bug.

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MessageDispatchThrottlingTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SubscriptionMessageDispatchThrottlingTest.java

Fixed
* https://github.com/apache/pulsar/issues/17636
Only execution once `setup`/`clean` and clean `tenants`/`namespaces`/ `config` after the end of each test execution.
Execution time after improve test:
```
Tests run: 60, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 242.091 s - in org.apache.pulsar.client.api.SubscriptionMessageDispatchThrottlingTest
```
PR in forked repository: https://github.com/coderzc/pulsar/pull/14

[improve][test] Improve SubscriptionMessageDispatchThrottlingTest to reduce the execution time

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java

fix when create a lot of producer (> 10000) in the same jvm which will use eventLoop to do task check
Fixes #18055
when broker own a lot of topic ( > 10000 ) and enable txn. 
the producer create for `TransactionBufferSystemTopicClient` enable batch for current code.
which will use broker workerGroup thread to schedule batch check task. which will cause high cpu usage.
use client HashWheelTimer for schedule batch check task and when trigger task execute on pulsarClient internalExecutorPool

[fix][client][txn] Use PulsarClient HashWheelTimer to schedule producer batch trigger task

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

Current version of JacksonXML (2.13.3) is vulnerable to [CVE-2022-42004](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2022-42004)
Note that Pulsar is not directly vulnerable since the CVE exists only if `DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS` is used. And Pulsar doesn't use it.
* Upgrade to 2.13.4. It's a minor

[fix][sec] Upgrade JacksonXML to 2.13.4

---

site2/docs/reference-pulsar-admin.md

I noticed there were some options not shown in the documentation but offered in the help of the tool.
Add the options to stats and partitioned-stats in topics.
- [ X] `doc` 

[improve][doc] Add options to stats and partitioned-stats

---

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/io/ConnectorUtils.java

Improve functions worker bootstrap time with increased number of connectors. Currently all nar files are unpacked during startup to perform validation steps (e.g. if the connector class implements the correct interfaces). For that, the NarClassLoader will unpack all nars to disk sequentially which could delay startup.
On my Machine (Mac M1) I observed an improvement of ~ 3X (from 48 seconds down to 15 seconds). I know the max number of chosen threads (4) is a magic number (I have not seen improvements beyond that number), but if this is the right approach and it is worth it, we can make this number configurable (need guidance on the right config place)
Sample output:
```
2022-09-30T01:22:13,778+0000 [main] INFO  org.apache.pulsar.functions.utils.io.ConnectorUtils - Searching for …
```

[improve][fn] Run connectors extraction in parallel

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java

Fixes #18023
If the namespace policy inits without setting `managedLedgerOffloadThresholdInBytes`(like : if user `setOffloadDeletionLag ` first and then `getOffloadThreshold `), it will cause NPE when get `OffloadThreshold`.
PR in forked repository: https://github.com/Technoboy-/pulsar/pull/12

[fix][admin] Fix NPE when get `OffloadThreshold` on namespace.

---

.github/workflows/pulsar-ci.yaml

The codecov report is also uploaded in personal forks. See https://github.com/nicoloboschi/pulsar/pull/22#issuecomment-1276284696
* Do upload only if the pull is in the apache/pulsar repository

[fix][ci] Upload to codecov only upstream pull requests

---

pom.xml
pulsar-io/dynamodb/pom.xml

In the file tiered storage the hadoop dependency brings in a vulnerable version of jettison ([CVE-2022-40149](https://nvd.nist.gov/vuln/detail/CVE-2022-40149)).
It has been already fixed in the nightly version without any code change (https://github.com/apache/hadoop/pull/4937/files)

[fix][sec] File tiered storage: upgrade jettison to get rid of CVE-2022-40149

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java

After https://github.com/apache/pulsar/pull/17887 there are a lot of failures in the CI 
```
java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.broker.PulsarService.getConfiguration()" because "this.pulsar" is null
at org.apache.pulsar.client.api.SimpleProducerConsumerTest.rest(SimpleProducerConsumerTest.java:138)
```
```
java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.api.PulsarClient.newConsumer()" because "this.pulsarClient" is null
at org.apache.pulsar.client.api.SimpleProducerConsumerTest.testConcurrentConsumerReceiveWhileReconnect(SimpleProducerConsumerTest.java:880)
```
The reason is that the after method is always executed meanwhile the setup method is not+
* Add back `alwaysRun=true` in the setup method

[fix][ci] Ensure to run setup method in SimpleProducerConsumerTest

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/v1/V1_ProducerConsumerTest.java

In PR: https://github.com/apache/pulsar/pull/17273, when the read position is updated, the ManagedLedgerImpl#onCursorReadPositionUpdated method will be called, and finally ManagedCursorContainer#cursorUpdated will be called, thus making the slowestReaderPosition change:
https://github.com/apache/pulsar/blob/0c7a0d144d9e527fbd25a1d738715934fbcf38ab/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L2633-L2639
Therefore, in testActiveAndInActiveConsumerEntryCacheBehavior, as long as the server pushes data to the client, the slowestReaderPosition will change.
So here the receive queue of the slower-subscriber is set to 1 to prevent the slowestReaderPosition from changing even if the subscription is not consumed. …

[fix][test] Fix flaky test V1_ProducerConsumerTest#testActiveAndInActiveConsumerEntryCacheBehavior.

---

.github/workflows/ci-semantic-pull-request.yml

As some patches(like #18078 ) are only for managed-ledger, so add this label.

[improve][ci] Add `ml` for CI semantic check.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreProvider.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStoreProvider.java

Fix #17921 
The test may fails if a previous test in the same fork started the transactions and therefore the transactions metrics are published. In the PulsarService shutdown hooks the metrics are never unregistered.
* Unregister transactions metrics in the PulsarService shutdown

[fix][test] Fix flaky test: PrometheusMetricsTest.testDuplicateMetricTypeDefinitions

---

.github/workflows/ci-semantic-pull-request.yml

Upstream fix: https://github.com/amannn/action-semantic-pull-request/pull/208
cc @lhotari @nicoloboschi

[fix][ci] deprecation warnings about set-output

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/EntryFilterSupport.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/SubscriptionStatsTest.java

A minor improve for entries fiilter by avoid runtime check has filter or not  in `EntryFilterSupport` and make the code more clear.
Add a protected final field `hasFilter` in `EntryFilterSupport`
PR in forked repository:https://github.com/AnonHxy/pulsar/pull/10

[improve][broker]Avoid runtime check hasFilter in EntryFilterSupport

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

Current protobuf version (3.19.2) is vulnerable to [CVE-2022-3171](https://nvd.nist.gov/vuln/detail/CVE-2022-3171)
https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-h4h5-3hr4-j3g2
* Upgrade to latest 3.19.x (3.19.6)

[fix][sec] Upgrade protobuf to 3.19.6 to get rid of CVE-2022-3171

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java

If there are read operation errors when delivery a message that was in the delayed delivery tracker, the message might be not retried again and it would stay in the backlog, until the topic is unloaded.
The message id needs to be inserted into the `redeliverMessages` set so that it will always be picked up the next time we are attempting to dispatch.

[fix] Fixed delayed delivery after read operation error

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaWithAuthTest.java

discuss: https://lists.apache.org/thread/0ts6josxxq4gt3qw2toxf9jd77d7s6kj
Now, we have two authentications for updating the schema
1. producer and consumer can update the schema using TopicOperation
produce or consume when open autoUpdateSchema
2. pulsar admin uses Tenant authentication
This will produce problems when using different authentications to
update the schema.
1. admin use produce permission to update the schema
2. enable autoUpdataSchema, the client can use produce permission to update the schema automatically. When no schema in the topic, consume permission also can first update the schema automatically first 
- https://github.com/congbobo184/pulsar/pull/4

[improve][schema] Change update schema auth from tenant to produce

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java

Fixes #17908
- `ManagedCursorImpl.setReadPosition()` will trigger cleaning of caches smaller than the earliest `readPosition`
- In `ManagedLedgerFactoryImpl`, there is a scheduled task that deletes inactive cache data every second
<strong(High light)></strong>When the `cursor` updates the `readPosition` and clears the outdated ledger cache concurrency, an entry's cache is incorrectly deleted.
E.g.
| `ManagedCursorImpl.setReadPosition` | `ManagedLedgerFactory.doCacheEviction` |
|----|----|
|  | get the first `entry` in the Cache |
| invalidate position `1:1` |  |
| delete `1:1` from `EntryCache` |  |
| recycle `entry` and set `entry.timestamp` to `-1` |  |
|  | check: `entry.timestamp` > `maxTimestamp` |
|  | <strong>(High light)</strong>pop first entry from `EntryCache`: expecting `1:1`, …

[fix][broker]Cache invalidation due to concurrent access

---

conf/zookeeper.conf

Fixes https://github.com/apache/pulsar-helm-chart/issues/285
The current Pulsar SSL Server Contexts always reload certificates from the file system. Zookeeper supports such options, but we do not enable them by default. I propose we do that.
Apache Zookeeper documentation:
> sslQuorumReloadCertFiles : (No Java system property) New in 3.5.5, 3.6.0: Allows Quorum SSL keyStore and trustStore reloading when the certificates on the filesystem change without having to restart the ZK process. Default: false
> client.certReload : (Java system property: zookeeper.client.certReload) New in 3.7.2, 3.8.1, 3.9.0: Allows client SSL keyStore and trustStore reloading when the certificates on the filesystem change without having to restart the ZK process. Default: false
* Enable the Quorum server to …

[feat][zk] Enable certificate refresh for Quorum and Netty Servers

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BKCluster.java

Fixes #16846
Fix unable to start multiple bookies when `clusterConf.dataDir != null`.
The PR #16847 missing this case modification.
Add index subPath for per bookie dataDir.
PR in forked repository: https://github.com/coderzc/pulsar/pull/15

[fix][broker] Fix unable to start multiple bookies for BKCluster

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java

In the current implementation, we call twice `span()` when filtering read entries to avoid NPE, and the `span()` will traverse `rangeBitSetMap` actually, we can only call once `span()`.
https://github.com/apache/pulsar/blob/6c65ca0d8a80bfaaa4d5869e0cea485f5c94369b/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L2329-L2335
Only call once `span()` when filtering read entries.

[improve][ml] Reduce unnecessary calling `span()` when filtering read entries

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApiTest.java

Fixed
* https://github.com/apache/pulsar/issues/17641
Only execution once `setup`/`clean` and clean `namespaces`/ `config`/ `consumer` after the end of each test execution.
Execution time after improve test:
```
Tests run: 45, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 58.58 s - in org.apache.pulsar.broker.admin.v1.V1_AdminApiTest
```
PR in forked repository: https://github.com/coderzc/pulsar/pull/17

[improve][test] Improve V1_AdminApiTest to reduce the execution time

---

pulsar-client-cpp/docker/alpine/Dockerfile
pulsar-client-cpp/docker/alpine/Dockerfile-alpine-3.8
pulsar-client-cpp/docker/manylinux1/Dockerfile
pulsar-client-cpp/docker/manylinux2014/Dockerfile
pulsar-client-cpp/docker/manylinux_musl/Dockerfile
pulsar-client-cpp/python/build-mac-wheels.sh

branch-2.9 python CI jobs has started failing because a new version of ZLib was released and the old one was removed.
https://github.com/codelipenghui/incubator-pulsar/actions/runs/3282737027/jobs/5413121415
- Change the URL to point to the archive so that we won't get in the same situation on next release.

[fix][cpp][branch-2.9] Fix zlib dowload path.

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BKCluster.java

Pulsar standalone is not respecting the bookie config set in `conf/standalone.conf`.

[fix] The Pulsar standalone bookie is not getting passed the config from standalone.conf

---

pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/JdbcUtils.java

Format `JDBCUtils.java`.
- https://github.com/poorbarcode/pulsar/pull/28

[fix] [io] Fix checkstyle issue in JDBCUtils

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClient.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationManager.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClientTest.java

There are some methods in PulsarRegistrationClient that are not still implemented correctly according to [BP-41](https://bookkeeper.apache.org/bps/BP-41-bookieid/) and [BP-38](https://bookkeeper.apache.org/bps/BP-38-bookie-endpoint-discovery/).
- getAllBookies() must return all the bookies, not only the bookies that are up-and-running
- we are not following the changed to the BookieServiceInfo (so if the bookie changes network address it is not possible to connect to the new network address)
Therefore the PulsarRegistrationClient is handling too many notifications about deleted nodes.
* Implement correctly getAllBookies()
* Handle the updates to the Bookie nodes on the MetadataService
* Handle only the deletion of the Bookies nodes
* Add test cases that validate the implementation of …

[fix][broker] PulsarRegistrationClient - implement getAllBookies and follow BookieServiceInfo updates

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MemoryLimitTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/BatchMessageContainer.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/AbstractBatchMessageContainer.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageKeyBasedContainer.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java

We should reserve the allocated buffer in BatchMessageContainer on client memory limitation.
In this patch, we only take care of the buffer init size and final size
* Added a variable `batchAllocatedSize` in `BatchMessageContainer` to record the current allocated buffer size.  It is used to release the allocated buffer size from memory limit controller
* Added a method `reserveBatchAllocatedSizeWhenInit()` in `BatchMessageContainer`, will be call when init the allocated buffer.  This method will initiliaze the `batchAllocatedSize`  and reserve memory to the memory limit controller.
* Added a method `updateBatchAllocatedSizeWhenLeave()` in `BatchMessageContainer`, will be call when the batch leaving the `BatchMessageContainer`. This method will update the final `batchAllocatedSize` as the …

[fix][client] Reserve allocated buffer in BatchMessageContainer on client memory limitation.

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

When accumulating acks, update the batch index in batchDeletedIndexes without checking whether it is greater than the batch index of the previous ack：
https://github.com/apache/pulsar/blob/c73285205dafaf5bed827ad99f7fb8edd3ddb7f2/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L1869-L1872
This may cause the index of ack in the batch to fall back.
Should be modified to:
```
lock.writeLock().lock();
try {
BitSetRecyclable givenBitSet = BitSetRecyclable.create().resetWords(newPosition.ackSet);
batchDeletedIndexes.compute(newPosition,
(k, v) -> v == null || givenBitSet.nextSetBit(0) > v.nextSetBit(0)
? givenBitSet : v);
} finally {
lock.writeLock().unlock();
}
```
PR in forked repository: https://github.com/lordcheng10/pulsar/pull/28

[fix][broker] Compare batch index when accumulating acks and updating batchDeletedIndexes

---

.github/workflows/ci-semantic-pull-request.yml

It seems we missed zookeeper and bookkeeper in the scopes. This PR adds them.

[improve][ci] Add zk and bk for semantic check

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsumedLedgersTrimTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/RetentionPolicies.java

[fix][broker] Fix RetentionPolicies types mismatch.

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java

Support dynamic configuration of exposeBundlesMetricsInPrometheus.
PR in forked repository: https://github.com/lordcheng10/pulsar/pull/35

[improve][broker] Support dynamic configuration of exposeBundlesMetricsInPrometheus

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerStatsManager.java

Prometheus load metrics error.
> curl -s 'http://localhost:8080/metrics/'
This bug introduce from #15558
Remove the space behind the metric type.

[fix][function] Fix invalid metric type "gauge "

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java

In the current implementation, don't pass the `force` parameter to `deleteNamespaceBundle` when deleting namespaces, we should pass the `force` parameter.
Passing `force` parameter to `deleteNamespaceBundle` when delete namespaces.
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/coderzc/pulsar/pull/20

[fix][admin] Passing `force` parameter to `deleteNamespaceBundle` when delete namespaces

---

conf/bookkeeper.conf

Fixes: https://github.com/apache/pulsar/issues/18012
The current Bookkeeper configuration defaults to using `org.apache.bookkeeper.net.ScriptBasedMapping` for the `DNSToSwitchMapping` implementation. However, this default configuration does not align with the Broker's default configuration, which is `org.apache.pulsar.zookeeper.ZkBookieRackAffinityMapping`. As such, the default configuration for a Pulsar cluster does not lead to ideal rack awareness when ledgers need to be recovered. The result is that a user can configure a cluster for rack awareness and the brokers will honor that configuration, but the autorecovery process will not because it does not have the correct bookkeeper cluster topology view.
I propose we configure bookkeeper to use the broker's `ZkBookieRackAffinityMapping` …

[fix][storage] Autorecovery default reppDnsResolverClass to ZkBookieRackAffinityMapping

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/EtcdMetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/LocalMemoryMetadataStore.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/impl/LocalMemoryMetadataStoreTest.java

In the current implementation, the `getChildren` will return incorrect results when getting children paths of `/` and some special path in `MemoryMetadataStore` and `EtcdMetadataStore`, because we use `replace` lead to the `basePath` has been replaced many times.
Use `replaceFirst` instead of `replace`.
This change is already covered by existing tests, such as *testGetChildren*.
PR in forked repository: https://github.com/coderzc/pulsar/pull/16

[fix][meta] fix `getChildren` in MemoryMetadataStore and EtcdMetadataStore

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java

Support setting `ForceDeleteNamespaceAllowed` dynamically.
- [] `doc-required`

[improve][broker] Support setting `ForceDeleteNamespaceAllowed` dynamically

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImplTest.java

Remove unused check for `conf.getTopicNames().isEmpty()`, becase line170 has checked and it's always false here
* Remove unused check for `conf.getTopicNames().isEmpty()`
* Add a test for topicNamesValid
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/11

[improve][client]Remove unused check for topics isEmpty

---

site2/docs/client-libraries-go.md

Master Issue: pulsar-client-go [#865](https://github.com/apache/pulsar-client-go/pull/805)
Add chunking document for go-client. (Do not merge. [#865](https://github.com/apache/pulsar-client-go/pull/805) is under review now.)
Add chunking document for go-client.
PR in forked repository:  https://github.com/Gleiphir2769/pulsar-client-go

[doc] [client] [go] Add chunking to go-client doc

---

pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
pulsar-client-tools/pom.xml
pulsar-sql/pom.xml
pulsar-sql/presto-distribution/LICENSE
tests/integration/src/test/java/org/apache/pulsar/tests/integration/tls/ClientTlsTest.java

Using jline before 3.21.0 may cause a "Bad address" failure on Apple M1 environment. We're using 3.21.0 globally, so forcibly apply this version to pulsar-sql dependencies.
See also https://github.com/scala/scala/pull/9807.

[fix][sql] Fix jline version to 3.21.0

---

.github/workflows/pulsar-ci.yaml
build/run_unit_group.sh

To improve code coverage accuracy and have a view of comparing PR and master branch, we need to run master branch CI daily and except flaky tests. The best way is to run master branch CI after PRs merged, but pulsar's Github action runners have few resource, running daily is a trade-off between cost and accuracy.
- Pulsar CI workflow run daily (12:00, lunch time or sleeping time)
- Except flaky test group to run code coverage, otherwise we cannot get an accurate base coverage.
PR in forked repository: https://github.com/yaalsn/pulsar/pull/14

[improve][ci] Add schedule trigger to get master branch code coverage daily

---

site2/docs/about.md
site2/docs/reference-cli-tools.md

This PR:
1. Removes metadata since it should not be shown on the Reference site
2. Removes `broker-tool` because https://github.com/apache/pulsar/pull/18051#issuecomment-1280297019
3. Update URLs to https://pulsar.apache.org/reference to make it more generic and easier to maintain

[fix][doc] Optimize URLs for CLI tools page

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java

Support setting `forceDeleteTenantAllowed` dynamically.
- [] `doc-required`

[improve][broker] Support setting `forceDeleteTenantAllowed` dynamically

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java

In `org.apache.bookkeeper.mledger.impl.ManagedCursorImpl`, if `config.isDeletionAtBatchIndexLevelEnabled()` is equal to true, the field `batchDeletedIndexes` will not be null. see line 299,301
https://github.com/apache/pulsar/blob/6cc30c93a05bb16b7ef62ffebc15ceb5e6efb502/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L291-L302
so judging `config.isDeletionAtBatchIndexLevelEnabled()` is equal to true can determine that `batchDeletedIndexes` is not null.
However, many logics judge whether `batchDeletedIndexes` is not null when `config.isDeletionAtBatchIndexLevelEnabled()` is equal to true, which is redundant. see line 569,1230
https://github.com/apache/pulsar/blob/6cc30c93a05bb16b7ef62ffebc15ceb5e6efb502/managed-ledger/src/main/java/org/apache/bookkeep …

[improve][ml] Remove the redundant judgment logic of ManagedCursorImpl

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java

Based on #https://github.com/apache/pulsar/pull/18146
https://github.com/apache/pulsar/actions/runs/3281165538/jobs/5414499054
```
Error:  Tests run: 161, Failures: 48, Errors: 0, Skipped: 50, Time elapsed: 48.407 s <<< FAILURE! - in org.apache.bookkeeper.mledger.impl.ManagedLedgerTest
Error:  testDoNotGetOffloadPoliciesMultipleTimesWhenTrimLedgers(org.apache.bookkeeper.mledger.impl.ManagedLedgerTest)  Time elapsed: 0.196 s  <<< FAILURE!
org.mockito.exceptions.verification.TooManyActualInvocations: 
nullLedgerOffloader.getOffloadPolicies();
Wanted 1 time:
-> at org.apache.bookkeeper.mledger.impl.NullLedgerOffloader.getOffloadPolicies(NullLedgerOffloader.java:66)
But was 2 times:
-> at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.internalTrimLedgers(ManagedLedgerImpl.java:2473)
-> …
```

[fix][test] Fix flaky test `testDoNotGetOffloadPoliciesMultipleTimesWhenTrimLedgers`

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerStatsRecorderImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerStatsRecorderImplTest.java

Right now, Producer client stats returns incorrect rate values for partition topic instead giving aggregate value across all partitions. Right now it always returns 0 but it can be aggregated for partition topic and give to client.
Update aggregate rate value for producer stats.
*(or)*
*(or)*
*(example:)*

[improve] [client] support aggregate metrics for partition topic stats

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java

If the namespace is deleted, the `cmd-lookup` will still keep retrying, because the error code sent to the client is `MetadataError`, and the client will retry when it gets `MetadataError`. No matter how many times it tries again, it will not succeed.
https://github.com/apache/pulsar/blob/6cc30c93a05bb16b7ef62ffebc15ceb5e6efb502/pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java#L250-L257
If the namespace is deleted
- the `cmd-lookup` will get the error code `TopicNotFound `
- the rest request will get the response code `404` 
- improve response message for `API topics` and `API namespaces`
- `TODO` I will write a test later
- https://github.com/poorbarcode/pulsar/pull/30

[improve][client]When namespace is deleted, the client is constantly reconnecting

---

pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyAuthenticationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyEncryptionPublishConsumeTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTlsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/v1/V1_ProxyAuthenticationTest.java

Fix flaky tests.
Based on Awaitility to assert. 

[improve][test] Improve websocket.proxy tests based on Awaitility

---

.gitignore
pulsar-io/canal/pom.xml

[CVE-2017-5929](https://www.cve.org/CVERecord?id=CVE-2017-5929)
Introduced through:
com.alibaba.otter:canal.protocol@1.1.5
Fixed in:
ch.qos.logback:logback-classic@1.2.0

[fix][io] exclude logback dependency for canal connector

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DispatcherBlockConsumerTest.java

Fixes #17011
1. In this test, make a batch of messages is acked, and make the remaining messages are redelivered, then try to receive the redelivered messages again. However, the sequence num is used for `cmd-ack`. But if the order of the messages changes, the acked messages will not be the expected messages, which makes the test unstable.
2. There is a bug that caused repeated consumption, PR https://github.com/apache/pulsar/pull/18227 has fixed it.
Use the message content to determine whether the message should `ack`.
- https://github.com/poorbarcode/pulsar/pull/33

[fix][test]Fix flaky test DispatcherBlockConsumerTest.testBrokerSubscriptionRecovery

---

pulsar-io/kafka-connect-adaptor/pom.xml

PR in forked repository: https://github.com/dlg99/pulsar/pull/4
Reducing size of KCA nar and of connectors that use KCA, transitively reducing image size of the docker container that packages connectors.
KCA dependencies removed/exclusions added.
Size changes:
`84M pulsar-io-kafka-connect-adaptor-2.11.0-SNAPSHOT.nar`
to
`27M  pulsar-io-kafka-connect-adaptor-2.11.0-SNAPSHOT.nar`
NO

[improve][io] Reducing size of KCA nar and of connectors that use KCA

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/PulsarResources.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxAuthorizationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java

There is no need  `localStore` in  `NamespaceResources`, so cleanup it.
Remove  `localStore` from `NamespaceResources`
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/12

[cleanup][broker] Cleanup localStore from NamespaceResources

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

Fixes: https://github.com/apache/pulsar/issues/18236
See https://github.com/apache/pulsar/issues/18236 for details on the problematic behavior.
The fundamental problem is that the cursor persists the `readPosition` instead of persisting the `markDeletePosition` in the `ManagedCursor#internalResetCursor` method. This method is only called on specific occasions, the broker persists the correct `markDeletePosition` in zookeeper, and the bookkeeper's cursor data is only used when the broker doesn't update the cursor in zookeeper, so this bug is rare.
I found this bug at first by producing to a newly created topic and subscription where the subscription was set to "latest". In that case, when the broker evaluates the following code, the `position` evaluates to `ledgerId:0` instead of …

[fix][ml] Persist correct markDeletePosition to prevent message loss

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java

In `org.apache.pulsar.broker.PulsarService#start`, two log printing can be combined into one line.
https://github.com/apache/pulsar/blob/b7b923933a5c7594a52c8bb761f80e25ca0065cb/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L905-L907
Combine the two log lines in the `org.apache.pulsar.broker.PulsarService#start` into one line.
PR in forked repository: https://github.com/Pomelongan/pulsar/pull/11

[improve][broker] Optimize the log printing of PulsarService

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSender.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicListService.java

remove duplicate sendSuccess and sendError in PulsarCommandSender
change to `sendSuccessResponse` and `sendErrorResponse`
Fixes #18251

[cleanup][broker] Remove duplicate sendSuccess and sendError in PulsarCommandSender

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
pulsar-broker/src/test/java/org/apache/pulsar/PulsarStandaloneTest.java
pulsar-broker/src/test/resources/configurations/pulsar_broker_test_standalone_with_rocksdb.conf
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BKCluster.java

Fixes #18241
Read local bookie cookie to avoid `InvalidCookieException` when restarting Pulsar standalone.
This change has added a test.
PR in forked repository: https://github.com/labuladong/pulsar/pull/5

[fix][broker] read local cookie when start pulsar standalone

---

pulsar-client/src/main/java/org/apache/pulsar/client/util/ExecutorProvider.java

Fixes #18231 
When using `newThread` in `ExecutorProvider.ExtendedThreadFactory` concurrently, we can return an already running Thread lead to occur `IllegalThreadStateException`.
```java
2022-10-31T18:48:53,562 - WARN  - [pulsar-websocket-web-127-9:AbstractChannel$AbstractUnsafe@490] - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x0ee22409]
java.lang.IllegalThreadStateException: null
at java.lang.Thread.start(Thread.java:793) ~[?:?]
at io.netty.util.concurrent.ThreadPerTaskExecutor.execute(ThreadPerTaskExecutor.java:32) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
at io.netty.util.internal.ThreadExecutorMap$1.execute(ThreadExecutorMap.java:57) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
at …
```

[fix][client] Fix `IllegalThreadStateException` when using newThread in `ExecutorProvider.ExtendedThreadFactory`

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/metadata/v2/TxnIDData.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/transaction/TxnID.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionImpl.java

Fixes #18271
avoid txnid auto box long type to Long in equals
direct compare with ==

[improve][txn] Avoid txn id primitive auto boxing

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiplierRedeliveryBackoff.java

We have missed the redelivery delay validation in the tests. The PR tries to add total redelivery delay validation to make sure the negative backoff is working as expected.
- Add redelivery total delay validation
- Clean up unused methods from MultiplierRedeliveryBackoff.java
- Remove the unused ack timeout configuration for the test

[improve][test] validate redelivery delay for negative backoff

---

.github/ISSUE_TEMPLATE/flaky-test.yml
site2/docs/functions-overview.md
site2/docs/functions-package-python.md

Fix some errors in doc and template.

[fix][doc] fix doc and template error

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ClusterData.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdClusters.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/ClusterDataImpl.java

Add a separate TLS transport configuration to replication client and cluster cli.
:( Need to add the integration tests to verify.
- Add KeyStore and private file and certificate file config to cluster data
- Add manage these configs in cluster cmd
- Using these configs when creating replication client

[improve][broker] Improve tls config on replication client and cluster cli

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKSessionWatcher.java

Right now, zk-quorum recovers after leader restart within zk-session-timeout but still it can cause restart for some brokers even if it's not expected. It's really helpful if zk-session-watcher also prints session-id if it has been changed while disconnecting so, it can help admin to configure right synclimit at zk-server configuration or doing additional debugging.
Printing sessionId when zk is disconnecting.
*(or)*
*(or)*
*(example:)*
- *Extended …

[improve][broker] log sessionId with zk-session-watcher for debugging

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/TopicPolicies.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/impl/AutoSubscriptionCreationOverrideImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicPoliciesImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TopicPolicies.java

Current pulsar only support to set `autoSubscriptionCreation` on broker and namespace level, but we can further set this policy on the topic level.
- Add admin api for topic to set/get/remove autoSubscriptionCreation
- `handleSubscribe` in ServerCnx need to check autoSubscriptionCreation policy of topic
- https://github.com/yuruguo/pulsar/pull/2

[feature][broker] Support `autoSubscriptionCreation` on topic level

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherMultipleConsumers.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java

Fixes #16795
In class `PersistentDispatcherMultipleConsumers`, there is a variable `sendInProgress` that is set to `true` before the `sendMessagesToConsumers` method is executed and to `false` after the `sendMessagesToConsumers` method is executed, thus making the `readMoreEnties` inaccessible during the `sendMessagesToConsumers` method's execution. see: #16812
In subclass `PersistentStreamingDispatcherMultipleConsumers`, when reading batch entries, `sendMessagesToConsumer` is called each entry is read, which causes the variable `sendInProgress` to be set to `true` and `false` multiple times. This results in the method `readMoreEnties` can be accessed when the variable `sendInProgress` is set to false when a batch of entries is reading. This makes repeat delivery of the message, the error …

[fix][broker]fix Repeated messages of shared streaming dispatcher

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java

```
"exception":"java.util.concurrent.CompletionException: java.lang.NullPointerException\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)\n\tat 
java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)\n\tat 
java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)\n\tat 
java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)\n\tat 
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat 
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat 
java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.jav
a:304)\n\tat …
```

[fix][client] Fix NPE of MultiTopicsConsumerImpl due to race condition

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/DelayedDeliveryTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryController.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/utils/ConcurrentBitmapSortedLongPairSet.java

Fixes #18279
change signature from `Set<T>` to `NavigableSet<T>`
which makes the caller to get lowest `PositionImpl` more efficient ( compare with `stream().findfirst()` )

[improve][broker] Get lowest PositionImpl from NavigableSet

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SinksBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SourcesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Functions.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Worker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/WorkerStats.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceTest.java

… and trying to access it
Fixes #<xyz>
When running `pulsar-admin sources list` a HTTP 500 error is returned without an actionable error message.
error logs
```
19:12:01.631 [pulsar-web-36-1057] ERROR org.apache.pulsar.broker.web.AuthenticationFilter - [10.129.9.99] Error performing authentication for HTTP
javax.servlet.ServletException: java.lang.UnsupportedOperationException: Pulsar Function Worker is not enabled, probably functionsWorkerEnabled is set to false
at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.34.jar:?]
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[org.glassfish.jersey.containers-jersey-container-servlet-core-2.34.jar:?]
at …
```

[fix][admin] returns 4xx error when pulsar-worker-service is disabled and trying to access it

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerStatTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerStats.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ProducerStats.java

As discussed in https://github.com/apache/pulsar/pull/18212, that PR introduced support to get partitioned-topic stats with a partitioned-topic stats interface. However, the Producer and Consumer still return [ProducerStats](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Producer.java#L164) and [ConsumerStats](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L658). So, it's better to introduce API to get partitioned-stats in both `ProducerStats` and `ConsumerStats` so, user can call the API without casting to `MultiTopicConsumerStats` or `PartitionedTopicProducerStats`.
1. Add default `getPartitionStats()` API to producer/cosnumer stats which will not impact …

[improve][client] Add partitioned-stats api to avoid partition abstraction

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreTest.java

Fixes #18230
`ManagedCursorImpl` has a known problem: when the `cursor.close` and the `cursor.switchLedger` are concurrent executing, a bad version exception is thrown. see: 
https://github.com/apache/pulsar/blob/0c3c175eb132d4ef0fb3a12842127dcb4fa1933d/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L2595-L2619
In this test, it hit this problem:
- `MlPendingAckStore.clearUselessLogData` will trigger `cursor.switchLedger` if it is the first execute `mard delete`.
- `MlPendingAckStore.close` will trigger `cursor.close`
if `MlPendingAckStore.close` fail, just retry, it will be ok
- https://github.com/poorbarcode/pulsar/pull/36

[fix][test]fix flaky test MLPendingAckStoreTest.testMainProcess

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

In the trimDeletedEntries method, the removed entry is not released：
https://github.com/apache/pulsar/blob/2e878e8aac869bc4500e9d32e5c78bfc5c86614b/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L3307-L3310
https://github.com/apache/pulsar/blob/2e878e8aac869bc4500e9d32e5c78bfc5c86614b/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java#L582-L585
PR in forked repository: https://github.com/lordcheng10/pulsar/pull/38

[fix][broker] In the trimDeletedEntries method, release the removed entry

---

.github/workflows/pulsar-ci.yaml
build/run_unit_group.sh

`pulsar-client` test group is not in CI, but this module is important and we need to make sure of its quality.
PR in forked repository: https://github.com/yaalsn/pulsar/pull/15

[improve][ci] Add pulsar-client test group

---

pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceTransactionTest.java

Fixes #18282
We start 10 transactions and consume 50 messages in every transaction by default.
But notice `-r 10` set the consumption rate limit to be 10 msg per second, so every transaction is about 5 seconds.
In https://github.com/apache/pulsar/pull/17837 we set the transaction TTL to be 5 seconds, so transactions may be timeout randomly, which causes the test to fail.
To prove this, you can try to set `-r 9` or `-tto 4`, which will cause failure 100%.
So remove the `-r` option can fix this issue.
PR in forked repository: https://github.com/labuladong/pulsar/pull/6

[fix][flaky-test] fix flaky test `PerformanceTransactionTest`

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/TokenOauth2AuthenticatedProducerConsumerTest.java

Fix `unable to authentication`:
```
2022-11-03T15:14:46,955 - INFO  - [pulsar-io-6-15:ServerCnx@318] - Closed connection from /127.0.0.1:59327
2022-11-03T15:14:46,956 - WARN  - [pulsar-io-6-14:ClientCnx@751] - [id: 0xe41747d3, L:/127.0.0.1:59327 - R:localhost/127.0.0.1:59298] Received error from server: No anonymous role, and no authentication provider configured
2022-11-03T15:14:46,956 - WARN  - [pulsar-io-6-14:ConnectionPool@285] - [[id: 0xe41747d3, L:/127.0.0.1:59327 - R:localhost/127.0.0.1:59298]] Connection handshake failed: org.apache.pulsar.client.api.PulsarClientException$AuthenticationException: No anonymous role, and no authentication provider configured
2022-11-03T15:14:46,956 - WARN  - [pulsar-io-6-14:PulsarClientImpl@686] - [persistent://my-property/my-ns/__change_events] …
```

[improve][test] Setup broker client for TokenOauth2AuthenticatedProducerConsumerTest

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java

The admin stats command throws NullPointerException when fetching stats for a topic. This PR aims to fix the issue
Stacktrace:
sudo cloud-messaging-admin persistent stats persistent://sessionsearch-k8s/global/search_history/get
java.lang.NullPointerException
at org.apache.pulsar.admin.cli.CmdPersistentTopics$GetStats.run(CmdPersistentTopics.java:349)
at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:87)
at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:290)
at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:339)
Get persistentTopics exclusively if the value is Null.
This change is already covered by existing tests, such as PulsarAdminToolTest.persistentTopics().

[improve][cli] Fix NPE in admin-CLI topic stats command

---

pulsar-client/pom.xml

- After #18298 changes, the pulsar-client tests get run twice, as part of the CLIENT group and as part of the OTHER group
- Add skipTestsForUnitGroupOther maven profile to `pulsar-client/pom.xml` so that the tests don't get run as part of OTHER group.
PR in forked repository: https://github.com/lhotari/pulsar/pull/102

[fix][ci] Skip pulsar-client tests in OTHER group

---

.github/workflows/ci-cpp-build.yaml
.github/workflows/ci-cpp.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/InactiveTopicDeleteTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerStatTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/MultiTopicConsumerStats.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PartitionedTopicProducerStats.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicConsumerStatsRecorderImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedTopicProducerStatsRecorderImpl.java

The current behavior for the `delete_when_subscriptions_caught_up` strategy is not expected. The active consumer will not be closed even if users enable `delete_when_subscriptions_caught_up` and there are no backlogs for the topic.
It should be the part that #6077 has missed. And Sijie has mentioned in the comment https://github.com/apache/pulsar/pull/6077#pullrequestreview-344643883.
To correct the behavior of `delete_when_subscriptions_caught_up`
Close active consumers if `delete_when_subscriptions_caught_up` is applied and there are no backlogs for the topic. So that the topic can be cleaned up properly by the topic GC thread.
Updated the existing test.

[fix][broker][branch-2.11] fix delete_when_subscriptions_caught_up doesn't work while have active consumers

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java

#17862 added support for pulsar-perf CLI tools (with #17930 to fix some gaps).
It would be consistent to add support for specifying  proxyServiceUrl & proxyProtocol in the configuration file also for pulsar-client CLI tool.
Add proxyServiceUrl / proxyProtocol parsing from conf file to pulsar-client CLI.
PR in forked repository: https://github.com/lhotari/pulsar/pull/95

[improve][cli] Add proxyServiceUrl / proxyProtocol parsing from conf file to pulsar-client CLI

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java

Cherry-pick https://github.com/apache/pulsar/pull/18037
Fixes #18036
- The backlog eviction policy should use `asyncMarkDelete` instead of `resetCursor` in order to move the mark delete position.
PR in forked repository: https://github.com/HQebupt/pulsar/pull/5

[cherry-pick][branch-2.9]consumer backlog eviction policy should not reset read position for consumer

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java

A minor improvement by removing check `ack.getMessageIdsCount() == 1` for cumulative ack, making the code more clear and effective. Because we have checked it before at line418
Remove check ack.getMessageIdsCount() == 1 for cumulative ack
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/14

[improve][broker] Remove check ack.getMessageIdsCount() == 1 for cumulative ack

---

pulsar-functions/runtime-all/pom.xml
pulsar-io/debezium/core/pom.xml
pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistory.java
pulsar-io/debezium/mongodb/pom.xml
pulsar-io/debezium/mssql/pom.xml
pulsar-io/debezium/mysql/pom.xml
pulsar-io/debezium/oracle/pom.xml
pulsar-io/debezium/postgres/pom.xml
pulsar-io/kafka-connect-adaptor/pom.xml
pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStore.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/PulsarIOTestBase.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarSinksTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/PulsarDebeziumOracleSourceTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/PulsarDebeziumSourcesTest.java

#18255 removed some dependencies needed by the KCA based connectors to work at runtime. (it only affects current master branch)
* Add back only the needed dependencies. The java function framework already offers some libraries at runtime and those are now set as `provided`. Those are: `pulsar-io-core` and avro/protobuf deps.
* pulsar client is only needed for running an utility method and then all the transitive dependencies have been removed or explictily added
* The above modifications also apply to the debezium-io-core module.
* Moved the debezium integration tests to runtime=PROCESS in order to have a different classpath from the function worker. This will help to prevent any future regressions about these modules
Note that now both KCA and debezium connectors includes the barely …

[fix][io] KCA connectors: fix missing runtime dependencies

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupServiceTest.java

When the broker closes,  the scheduled task in ResourceGroupService may still execute, and cause NPE:
```
Sep 17 12:09:50 168-15-22-49 pulsar[8900]: 2022-09-17T12:09:50,050+0800 [pulsar-2-4] ERROR org.apache.pulsar.common.util.Runnables - Unexpected throwable caught
Sep 17 12:09:50 168-15-22-49 pulsar[8900]: java.lang.NullPointerException: null
Sep 17 12:09:50 168-15-22-49 pulsar[8900]: at org.apache.pulsar.broker.resourcegroup.ResourceGroupService.aggregateResourceGroupLocalUsages(ResourceGroupService.java:530) 
Sep 17 12:09:50 168-15-22-49 pulsar[8900]: at org.apache.pulsar.common.util.Runnables$CatchingAndLoggingRunnable.run(Runnables.java:54) 
Sep 17 12:09:50 168-15-22-49 pulsar[8900]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
Sep 17 12:09:50 …
```

[cherry-pick][branch-2.9] Fix NPE when ResourceGroupService execute scheduled task.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java

Fixes #18023
If the namespace policy inits without setting `managedLedgerOffloadThresholdInBytes`(like : if user `setOffloadDeletionLag ` first and then `getOffloadThreshold `), it will cause NPE when get `OffloadThreshold`.
PR in forked repository: https://github.com/Technoboy-/pulsar/pull/12

[cherry-pick][branch-2.9] Fix NPE when get OffloadThreshold on namespace. 

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java

Fixes #17982 
managed packages should not be deleted automatically when deleting function
remove auto deletion logic for managed package
pr in my forked repo: https://github.com/jiangpengcheng/pulsar/pull/1

[fix][fn] Do not delete managed package when delete function

---

README.md

I tried to build my Pulsar environment by following README.md, but failed. Because I used Powershell to run maven command line on Windows, maven recognized windows and used `rename-netty-native-libs.cmd `, powershell can't run cmd. Even I annotate the windows profile, let maven run `rename-netty-native-libs.sh ` on powershell,  but there is lacking many Linux commands on Powershell, such as `mktemp`.
So I think it is better to clarify the command line running environment in windows to reduce misunderstandings.
Clarify the maven running environments under windows.
Other minor fixes, e.g. first word capitalization this -> This

[improve][doc] Clarify maven running environments under windows

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-broker-shaded/pom.xml
pulsar-client-admin-shaded/pom.xml
pulsar-client-all/pom.xml
pulsar-client-shaded/pom.xml
pulsar-common/pom.xml
pulsar-common/src/main/java/org/apache/pulsar/common/util/netty/EventLoopUtil.java
pulsar-sql/presto-distribution/LICENSE

Allow users to enable IO_uring for BK network transport for broker/proxy, similar to https://github.com/apache/bookkeeper/pull/3595
PR in forked repository: https://github.com/coderzc/pulsar/pull/28

[improve][broker] Allow to use io_uring instead of epoll

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ProducerConfigurationData.java

Fixes #7579
`encryptionKeys` is public data (the name of the keys to use, not the keys themselves) so there's no reason to hide it.
And it's a `Set<String>` so it serializes/deserializes fine with Jackson.
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/cbornet/pulsar/pull/8

[improve][client] Remove JsonIgnore on ProducerConfigurationData.encryptionKeys

---

docker/pulsar-all/pom.xml
docker/pulsar/pom.xml

The current config will build the pulsar and pulsar-all images multiple times.
https://github.com/apache/pulsar/runs/7945037366?check_suite_focus=true#step:10:5675
https://github.com/apache/pulsar/runs/7945037366?check_suite_focus=true#step:10:6760
One is apache/pulsar, and one is without the apache repository, we should only keep an image without the apache repository, it is enough.
When we do release, only use the image without the apache repository. The following commands are from the `docker/publish.sh`.
```
docker tag pulsar:latest ${docker_registry_org}/pulsar:latest
docker tag pulsar-all:latest ${docker_registry_org}/pulsar-all:latest
docker tag pulsar:latest ${docker_registry_org}/pulsar:$MVN_VERSION
docker tag pulsar-all:latest ${docker_registry_org}/pulsar-all:$MVN_VERSION
```
- …

[improve][build] Avoid building image multiple times

---

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceStarter.java

Master Issue: https://github.com/apache/pulsar/issues/18110
When user run pulsar functions directly without `pulsar-admin functions create` or `pulsar-admin functions localrun`, it requires to provide `typeClassName` in `functionDetails`, otherwise the function will failed to start.
try to inferring the `typeClassName` at runtime for Function, Sink and Source.
*(or)*
*(or)*
*(example:)* …

[fix][fn] fix function failed to start if no `typeClassName` provided in `FunctionDetails`

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

Do ` curosr.close` twice.
expect cursor state: `Closed`
actual cursor state: `Closing`
Fixed the state change logic
- https://github.com/poorbarcode/pulsar/pull/37

[fix] [ml] fix wrong cursor state if repeat do close

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/InMemoryRedeliveryTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/RedeliveryTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/RedeliveryTrackerDisabled.java

Fixes #18353
PositionImpl object is just use to pass parameter which can be avoid by direct pass.
change method signature `RedeliveryTracker.getRedeliveryCount`

[improve][broker] Avoid object create in `RedeliveryTracker.getRedeliveryCount`

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TransactionsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v3/Transactions.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/AdminApiTransactionTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Transactions.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/TransactionCoordinatorInfo.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TransactionsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTransactions.java

Fixes #17513 
At the moment there's no way to list all the transaction coordinators and to understand to which broker own.
* New endpoint `transactions/coordinators´ to get all the coordinators
* Under the hood it does a `lookup` to the TC partitioned topic
* New data object ´TransactionCoordinatorInfo´ -> only contains the `brokerServiceUrl` field
* Added the equivalent client call in the pulsar-client admin
* Added the equivalent client call in the pulsar-admin CLI `coordinators-list`

[improve][transactions] Add command to list transaction coordinators

---

site2/docs/concepts-messaging.md

For newcomers this is a question it can be important.
It is mentioned [here](https://pulsar.apache.org/api/client/2.10.1/org/apache/pulsar/client/api/ConsumerBuilder.html#ackTimeout(long,java.util.concurrent.TimeUnit))
The documentation was lacking this default as a note.
Added the information in case somebody *forgets* to configure ackTimeOut.
- [ X ] Make sure that the change passes the CI checks.

[improve][doc] Default behaviour with acknowledge timeout

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java

When using RawReader to read the topic, the getLastMessageId continues to print to the logs, change it to the debug level to avoid printing it too much.
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/zymap/pulsar/pull/42

[improve][client] Change the get lastMessageId to debug level

---

site2/docs/deploy-bare-metal.md
site2/website/versioned_docs/version-2.10.x/deploy-bare-metal.md

On this PR https://github.com/apache/pulsar/pull/13985, `/my-chroot-path` was added to the URLs.
If users follow the document, `bookkeeper.conf` and `broker.conf` lacks the informations about the path and fail to set up the cluster.
Add chroot path related informations to the documents and add `zk://` prefix to metadata URLs.

[improve][docs] Add chroot path related informations

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithJwtAuthorizationTest.java

cherry-pick #17393 to branch-2.9

[branch-2.9][fix][broker] fix can not revoke permission after update topic partition

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/MangedLedgerInterceptorImplTest.java

This PR is fully based on https://github.com/apache/pulsar/pull/17394.
- Remove duplicate release in `ManagedLedgerInterceptor`

[branch-2.9][fix][storage]fix OpAddEntry release error when exception in ManagedLedgerInterceptor

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java

There are duplicate codes in 
`org.apache.pulsar.client.impl.ConsumerBuilderImpl#topic` and `org.apache.pulsar.client.impl.ConsumerBuilderImpl#topics`,
`org.apache.pulsar.client.impl.ConsumerBuilderImpl#topicsPattern(java.util.regex.Pattern)` and `org.apache.pulsar.client.impl.ConsumerBuilderImpl#topicsPattern(java.lang.String)`.
Merge the duplicate codes in 
`org.apache.pulsar.client.impl.ConsumerBuilderImpl#topic` and `org.apache.pulsar.client.impl.ConsumerBuilderImpl#topics`,
`org.apache.pulsar.client.impl.ConsumerBuilderImpl#topicsPattern(java.util.regex.Pattern)` and `org.apache.pulsar.client.impl.ConsumerBuilderImpl#topicsPattern(java.lang.String)`.
PR in …

[cleanup][client] Reduce duplicate code in ConsumerBuilderImpl

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdSerializationTest.java

Fixes https://github.com/apache/pulsar/issues/18395
The old version Pulsar clients might not set the `batch_size` field in a batched message id, it will cause `MessageId#fromByteArrayWithTopic`, which only checks the `batch_index` field, fail with IllegalStateException.
Check if the `batch_size` field exists in `fromByteArrayWithTopic`. If it doesn't exist, create the `BatchMessageIdImpl` instance with the default batch size (0) and the acker (disabled).
Move `MessageIdSerializationTest` to the `pulsar-client` module and add the `testBatchSizeNotSet` to verify the change works.
PR in forked repository: https://github.com/BewareMyPower/pulsar/pull/7

[fix][client] Fixes batch_size not checked in MessageId#fromByteArrayWithTopic

---

pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyAuthenticationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyEncryptionPublishConsumeTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTlsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeWithoutZKTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/v1/V1_ProxyAuthenticationTest.java

Fix websocket.proxy test, thread blocked:
```
"pool-27-thread-1" #270 prio=5 os_prio=0 cpu=2.93ms elapsed=0.33s tid=0x00007fbee9e82a20 nid=0x17a7 in Object.wait()  [0x00007fbc85706000]
java.lang.Thread.State: BLOCKED (on object monitor)
at java.lang.Object.wait(java.base@17.0.4.1/Native Method)
- waiting to re-lock in wait() <0x0000100013da1740> (a java.lang.Thread)
at java.lang.Thread.join(java.base@17.0.4.1/Thread.java:1298)
- locked <0x0000100013da1740> (a java.lang.Thread)
at org.eclipse.jetty.util.thread.QueuedThreadPool.joinThreads(QueuedThreadPool.java:320)
at org.eclipse.jetty.util.thread.QueuedThreadPool.doStop(QueuedThreadPool.java:244)
at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
- locked <0x000010002292cf98> (a java.lang.Object)
at …
```

[fix][test] Fix websocket.proxy test

---

pom.xml

Upgrade debezium to 1.9.7 final to pick up latest fixes.
Dependency upgrade
PR in forked repository: https://github.com/dlg99/pulsar/pull/5

[improve][io] Upgrade Debezium to 1.9.7

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageChunkingTest.java

https://github.com/apache/pulsar/pull/14382 introduced the client-side maxMessageSize for the message chunking. But the parameter `clientSizeMaxMessageSize` in `testLargeMessage` is not respected in that PR. This PR fixes this issue.
* Respect the `clientSizeMaxMessageSize`. The `clientSizeMaxMessageSize` should not be too small because https://github.com/apache/pulsar/pull/14007 has included the metadata when calculating the chunk size.
This change is already covered by existing tests, such as *testLargeMessage*.
PR in forked repository: https://github.com/RobertIndie/pulsar/pull/8

[fix][test] Fix `testLargeMessage` doesn't respect the parameter `clientSizeMaxMessageSize`

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConsumerDedupPermitsUpdateTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java

When the consumer `redeliverUnacknowledgedMessages`, the MultiTopicsConsumerImpl doesn't filter the duplicate message. Also, the ConsumerImpl doesn't check the batched msg-id, this will cause missing msg in the below case :
- Send one msg with batch size of 10.
- Cumulate ack the first one.
- Redeliver the msg.
- The left 9 msg will be filtered(missing).

[fix][client] Fix failover/exclusive consumer with batch cumulate ack issue.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/OverloadShedder.java

In the OverloadShedder#findBundlesForUnloading method, the local bundles are repeatedly filtered twice:
https://github.com/apache/pulsar/blob/dcf0b6069b7dcdf29be94cc341bfdc2785977114/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/OverloadShedder.java#L103-L105
https://github.com/apache/pulsar/blob/dcf0b6069b7dcdf29be94cc341bfdc2785977114/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/OverloadShedder.java#L117-L119
Remove duplicate filters.
PR in forked repository: https://github.com/lordcheng10/pulsar/pull/40

[improve][broker] In OverloadShedder, repeatedly filter local bundles

---

docker/pulsar/Dockerfile

Fixes #18443
I tried to build docker image on my win10, and I use wsl2 for my docker, all my softwares versions are listed on #18443. I have encountered "permission denied" error while running `install-pulsar-client.sh`, seems it happens on some linux kernel. I searched this error on stackoverflow and I got this, https://stackoverflow.com/questions/69323982/permission-denied-in-docker-entrypoint. So I add `RUN chmod +x /pulsar/bin/install-pulsar-client.sh`, and it works fine for me.
Adding this may happen many beginner reduce this kind of problems.
Add `chmod +x` command to dockerfile

[fix][build] fix permission denied error while running `install-pulsar-client.sh`

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java

NPE can occur in extreme cases.
For example: when thread A is executing here: https://github.com/apache/pulsar/blob/b6f0f91e099c47cd18cd901d5e7ebc7c4e5c0406/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L1298
another thread has consumed all `requestTimeoutQueue` data.
Add NPE check

[fix][client] Fix possible npe

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageRedeliveryTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/UnAckedMessageRedeliveryTracker.java

https://github.com/apache/pulsar/pull/17318 has made `internalRedeliverUnacknowledgedMessages` executed by `internalPinnedExecutor` which may cause a deadlock described in https://github.com/apache/pulsar/pull/18462.
So revert this patch and decide to close https://github.com/apache/pulsar/pull/18462.
- Revert https://github.com/apache/pulsar/pull/17318.

[improve][client] Revert "[fix][client] Messages with inconsistent consumer epochs are not filtered when using batch receive and trigger timeout

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/InactiveTopicDeleteTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/InactiveTopicDeleteMode.java

Add subscribing regex topic test for https://github.com/apache/pulsar/pull/18283.

[improve][test] Add subscribing regex topic test for `delete_when_subscriptions_caught_up`.

---

pulsar-common/src/main/java/org/apache/pulsar/common/util/netty/EventLoopUtil.java

https://github.com/apache/pulsar/pull/18385#discussion_r1018185105
improve ENABLE_IO_URING property name

[improve][broker] ENABLE_IO_URING property name

---

site2/docs/security-athenz.md
site2/docs/security-basic-auth.md
site2/docs/security-jwt.md
site2/docs/security-kerberos.md
site2/docs/security-oauth2.md
site2/docs/security-overview.md
site2/docs/security-tls-authentication.md

Authentication documentation has too many duplicate configurations and some unnecessary configurations.

[cleanup][doc] Merge the broker and proxy authentication configuration

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/TransactionBatchWriterMetricsTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/UnAckedMessageTracker.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterMetricsStats.java
pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterTest.java

Fixes: #17921
<strong>Note</strong>: 
This patch will change metrics names `s_bufferedwriter_batch_record_count` and `s_bufferedwriter_batch_oldest_record_delay_time_second`. These two names were first used in this PR #17701, and PR #17701 hasn't cherry-picked any branches yet, so this change will not cause any breaking changes.
https://github.com/poorbarcode/pulsar/actions/runs/3156649582/jobs/5136584463
https://github.com/apache/pulsar/actions/runs/3156649597/jobs/5136596447
If the `Prometheus-Colloctor` which typed `Counter` is named 'xxx_count',  then the output `metrics-api` will be named 'xxx_count_count'.
`TxnLogBufferedWriterMetricsStats` hits this error.
https://github.com/apache/pulsar/blob/fb7307d8f4998e42b18df3a4599fd7ec34cb04a9/pulsar-transaction/coordinator/src/main/java/org/ …

[fix] [txn] Make txn metrics name conforms to the rule

---

site2/docs/client-libraries.md

This is the counterpart of https://github.com/apache/pulsar-site/pull/293.
It's a bit clumsy to update multiple occurrences for the same purpose :/

[fix][doc] Workaround Docusaurus links issue

---

tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlockAwareSegmentInputStreamImpl.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlockAwareSegmentInputStreamTest.java

- BlockAwareSegmentInputStreamImpl never releases the BookKeeper entries in the close method
- This leads to OutOfDirectMemory errors on brokers that run frequently  Offloading activity
Fix the "if" condition.

[fix][offload] Fix memory leak while Offloading ledgers

---

buildtools/src/main/java/org/apache/pulsar/tests/PulsarTestListener.java

PulsarTestListener misses print stacktrace when the test fails.
```
------- Starting test [TestClass name=class org.apache.pulsar.websocket.proxy.v1.V1_ProxyAuthenticationTest].anonymousSocketTest([])-------
2022-11-16T17:50:34,336 - INFO  - [TestNG-method=anonymousSocketTest-1:V1_ProxyAuthenticationTest@127] - Connecting to : ws://localhost:54353/ws/consumer/persistent/prop/use/my-ns/my-topic1/my-sub
!!!!!!!!! FAILURE-- [TestClass name=class org.apache.pulsar.websocket.proxy.v1.V1_ProxyAuthenticationTest].anonymousSocketTest([])-------
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.websocket.proxy.v1.V1_ProxyAuthenticationTest.anonymousSocketTest() didn't finish within the time-out 50
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecut …
```

[improve][test] Print stacktrace when the test fails

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java

Fix some spelling mistakes in ManagedLedgerImpl
Fix some spelling mistakes in ManagedLedgerImpl

[fix][broker] Typos in ManagedLedgerImpl

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

If we call `ledger.openCursor("xxx", null)`,  setting the 2nd paramters `initialPosition` as null,  it will open a cursor at earliest position, but the expected result is the latest position.
The root cause is that Line986 and Line993 are contrary
https://github.com/apache/pulsar/blob/79a97a9a33cfa00d8d6326603032008f4346e5b4/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L984-L997
- Adding test `org.apache.bookkeeper.mledger.impl.ManagedCursorTest#testOpenCursorWithNullInitialPosition`
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/15

[fix][broker] Fix open cursor with null-initialPosition result with earliest position

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationService.java

Unreasonable AuthenticationException reference causes processing logic redundancy
Delete unreasonable exception references

[improve][broker] Unreasonable AuthenticationException reference

---

pom.xml

When releasing branch-2.11, there is a issue when generating Javadoc :
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:javadoc (default-cli) on project pulsar-functions-api: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - Loading source files for package org.apache.pulsar.functions.api...
[ERROR] Loading source files for package org.apache.pulsar.functions.api.utils...
[ERROR] Loading source files for package org.apache.pulsar.functions.api.state...
[ERROR] Constructing Javadoc information...
[ERROR] /Users/tboy/tboy/workspace_3/pulsar/pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java:173: error: cannot find symbol
[ERROR]     <X> FunctionRecord.FunctionRecordBuilder<X> …
```

[improve][build] Add lombok plugin to solve Javadoc issue.

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java

Fixes https://github.com/apache/pulsar/issues/18417
Fixes https://github.com/apache/pulsar/issues/18417
Change `bundles`, `lastBundleGains` and `lastBundleLosses`  from `HashSet` to `ConcurrentHashSet`, and remove the setter methods
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/16

[fix][test] Fix ConcurrentModificationException in testConcurrentWriteBrokerData

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTlsAuthTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminImpl.java
pulsar-client-admin/src/test/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImplTest.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java

Fixes #17333
Master Issue: #17333
Support PulsarAdminBuilderImpl overrides timeout properties passed through config map.

[improve][admin] PulsarAdminBuilderImpl overrides timeout properties passed through config map

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

The `authoritative` parameter of method `PersistentTopicBase.internalSkipAllMessagesForNonPartitionedTopicAsync` is no longer useful.
remove useless arguments for `PersistentTopicBase.internalSkipAllMessagesForNonPartitionedTopicAsync`.
- https://github.com/poorbarcode/pulsar/pull/40

[cleanup] [broker] remove useless argument for PersistentTopicBase.internalSkipAllMessagesForNonPartitionedTopicAsync

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

https://github.com/apache/pulsar/pull/18416 added a new test and missed the `@Test` annotation.
Add the `@Test` annotation.
This PR includes a "new" test.

[cleanup][broker] Add missing @Test annotation

---

build/run_integration_group.sh
buildtools/pom.xml
pom.xml
pulsar-client-admin/pom.xml
pulsar-client-all/pom.xml
pulsar-client/src/test/java/org/apache/pulsar/client/impl/BatchMessageContainerImplTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientBuilderImplTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerStatsRecorderImplTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/TrustManagerProxyTest.java
pulsar-io/kafka/pom.xml
pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/bookkeeper/test/ZooKeeperUtil.java

Bump TestNG to 7.6.1
- Bump TestNG to 7.6.1
- Fix build
PR in forked repository: https://github.com/nodece/pulsar/pull/14

[improve][test] Bump TestNG to 7.6.1

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java

Fixes #18535
in #17905, we enable transaction coordinator in the broker, this will lead to opening a connection in broker, so connection_count should recalculate.
Enable transaction coordinator in broker only in `testDuplicateMetricTypeDefinitions`.
PR in forked repository: https://github.com/coderzc/pulsar/pull/33

[fix][test] Fix PrometheusMetricsTest.testBrokerConnection

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageRedeliveryTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/util/NoOpLock.java

The original patch is https://github.com/apache/pulsar/pull/17318. Revert by https://github.com/apache/pulsar/pull/18475
Messages with inconsistent consumer epochs are not filtered when using batch receive and trigger timeout.
- Add consumer epoch on `notifyPendingBatchReceivedCallBack`.
- Reuse `notifyPendingBatchReceivedCallBack` logic.
- `testBatchReceiveRedeliveryAddEpoch` unit test covers the scene.

[fix][client] Messages with inconsistent consumer epochs are not filtered when using batch receive and trigger timeout

---

pulsar-common/src/main/java/org/apache/pulsar/common/util/SecurityUtility.java

When running tests in Macos Apple silicon, there will be a long stacktrace like this
```
Caused by: java.lang.UnsatisfiedLinkError: no conscrypt_openjdk_jni-osx-aarch_64 in java.library.path: /Users/yaalsn/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429) ~[?:?]
at java.lang.Runtime.loadLibrary0(Runtime.java:818) ~[?:?]
at java.lang.System.loadLibrary(System.java:1989) ~[?:?]
at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54) ~[conscrypt-openjdk-uber-2.5.2.jar:2.5.2]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java: …
```

[improve][test] Remove conscrypt exception stacktrace in Apple silicon

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java

Fixes #15819
The existing code calculates the pulsar_out_bytes_total and pulsar_out_messages_total per subscription metrics by adding the values from the currently connected consumers. This produces incorrect values as soon as one or more of the consumers disconnects from the subscription.
This changes these two metrics to directly use the subscription stats for these values, and match the output of `pulsar-admin topic stats`.
Signed-off-by: Paul Gier <paul.gier@datastax.com>
Fixes #15819
The prometheus metrics for pulsar_out_bytes_total and pulsar_out_messages_total should never decrease,
and they should match the output seen when using pulsar-admin.
Changed the calculation of pulsar_out_bytes_total and pulsar_out_messages_total to directly use the
subscription stats instead of …

[fix][broker] Correctly set byte and message out totals per subscription

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerBkTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java

Fixes #16729
same as #18310
`ManagedCursorImpl` has a known problem: when the `cursor.close` and the `cursor.switchLedger` are concurrent executing, a bad version exception is thrown. see: 
https://github.com/apache/pulsar/blob/0c3c175eb132d4ef0fb3a12842127dcb4fa1933d/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L2595-L2619
- `managedLedger.close` triggers the `cursor.close`, so remove code `cursor.close`
- if `managedLedger.close` fail, just retry, it will be ok
- https://github.com/poorbarcode/pulsar/pull/38

[fix][test] flaky test ManagedLedgerBkTest.asyncMarkDeleteAndClose

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java

remove legacy code
remove legacy code

[cleanup][broker] Remove legacy code

---

site2/docs/admin-api-brokers.md
site2/docs/admin-api-clusters.md
site2/docs/admin-api-functions.md
site2/docs/admin-api-namespaces.md
site2/docs/admin-api-packages.md
site2/docs/admin-api-permissions.md
site2/docs/admin-api-schemas.md
site2/docs/admin-api-tenants.md
site2/docs/admin-api-topics.md
site2/docs/admin-api-transactions.md
site2/docs/getting-started-standalone.md

Fixes #18088
Fixes #18517
Fixes #18514
Fixes #18525
Fixes #18516
Go through the admin document, improve command style and fix errors.

[fix][doc] improve and fix admin interface doc

---

build/run_unit_group.sh

using `-DtestReuseFork=false` slows down test execution significantly.
- this was added in https://github.com/apache/pulsar/pull/17049/files#diff-e6ac90fc5f2373a64dc1ecaa11a9c965f9a22f128cc4ca1265972e0dc4fef9c5R137
remove `-DtestReuseFork=false` for OTHER unit test group
PR in forked repository: https://github.com/lhotari/pulsar/pull/100

[improve][ci] Speed up execution of OTHER unit test group by removing -DtestReuseFork=false

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java

The broker PromtheusMetricsTest should be reliable enough to run in the main broker test group.  This will help prevent future merges from accidentally breaking the broker metrics.
Signed-off-by: Paul Gier <paul.gier@datastax.com>
This just moves some tests out of the flaky group and into the broker group.  This will help ensure that these tests pass before any new code changes.
Changed the test group from flaky to broker for the prometheus metrics test.
PR in forked repository: https://github.com/pgier/pulsar/pull/4

[improve][test] broker: remove prometheus tests from flaky group

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionProduceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java

1. When we delete a namespace by force if the __transaction_buffer_snapshot and __change_events be deleted first, and then the deleting of the normal topic will be failed at clearing the snapshot and clearing topic policies.
2. fix flaky test testCreateTransactionSystemTopic. Test failed due to cleaning up after class.
1. Delete the normal topic and then delete the system topic.
2. The system topic does not need to clean up topic policies.
For modification 2, there is a supported error msg. 
*(or)*
*(or)*
*(example:)*
- *Added …

[fix][broker] Fix can not delete namespace by force

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/RGUsageMTAggrWaitForAllMsgsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerEntryMetadataE2ETest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientDeduplicationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/TopicReaderTest.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolForceBatchNum.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java

Cherry-pick https://github.com/apache/pulsar/pull/16605
Cherry-pick https://github.com/apache/pulsar/pull/16605

[improve][client][branch-2.11]PIP-189: No batching if only one message in batch

---

bouncy-castle/bcfips/pom.xml
pom.xml
pulsar-broker-common/pom.xml
pulsar-common/pom.xml
site2/docs/security-bouncy-castle.md

This supersedes #18558 and fixes CVE-2020-15522. Co-authored by @pen4.

[fix][sec] Upgrade org.bouncycastle:bc-fips to 1.0.2.3

---

pulsar-common/src/main/java/org/apache/pulsar/common/util/netty/DnsResolverUtil.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/netty/DnsResolverTest.java

When the user set DNS cache maxTTl to 0, it will throw below exception :
```
Caused by: java.lang.IllegalArgumentException: maxTtl : 0 (expected: > 0)
at io.netty.util.internal.ObjectUtil.checkPositive(ObjectUtil.java:100)
at io.netty.resolver.dns.DefaultDnsCnameCache.<init>(DefaultDnsCnameCache.java:60)
at io.netty.resolver.dns.DnsNameResolverBuilder.newCnameCache(DnsNameResolverBuilder.java:451)
at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:485)
at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:114)
at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:92)
at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:77)
at …
```

[fix][broker] DnsResolverUtil.TTL should be greater than zero

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java

Master Issue: #18364
It's better not to count the system topic writer/reader connection.

[improve][broker] System topic writer/reader connection not counted.

---

src/stage-release.sh

The current release process doesn't stage the pulsar shell artifacts. Pulsar shell is going to be released in 2.11.0 
* Add the .tar.gz and .zip pulsar shell artifacts to the stage-artifacts procedure
note: we should update the release process in the pulsar-site repository.

[fix][build] Include Pulsar shell in the released artifacts

---

site2/docs/client-libraries-cpp.md

It's a followup PR of https://github.com/apache/pulsar-site/pull/300, which shows the download URLs of the [separated C++ client repo](https://github.com/apache/pulsar-client-cpp). This PR adds the guidance to tell users where to download the new released C++ client (3.0.0 or later).
Reference the download page for the C++ client 3.0.0 or higher and explain the packages simply. Add a section to describe how to install the APK (Alpine Package Keeper) package.
PR in forked repository: This is a pure doc related PR, no matching PR is needed.

[improve][doc] Add documents for C++ client 3.0.0 or later

---

wireshark/README.md

As #18439 said, the lua script may crash in the newest Wireshark. So add some notes and tips to README.

[improve][doc] add notes to wireshark scripts README

---

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/TableViewBuilder.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewBuilderImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewConfigurationData.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/TableViewConfigurationDataTest.java
site2/docs/client-libraries-java.md

TableView does not allow the user to customize the subscription name and is not friendly when clusters have strict permission setups (like the need to create the subscription name manually).
- pass `subscriptionName` to the internal Reader
*(or)*
*(or)*
*(example:)*

[improve][client] allow customize subscription name for TableView

---

site2/docs/functions-deploy-cluster-builtin.md
site2/docs/functions-deploy-cluster.md
site2/docs/functions-package-java.md
site2/website/sidebars.json

PR in forked repository: https://github.com/cbornet/pulsar/pull/9

[improve][doc] Add doc for builtin functions

---

pulsar-broker-common/src/test/java/org/apache/pulsar/broker/web/plugin/servlet/AdditionalServletsTest.java

Fixes #18587
AdditionalServletsTest.testEmptyStringAsExtractionDirectory is flaky because it depends on NarClassLoader#DEFAULT_NAR_EXTRACTION_DIR being initialized after the test is begun. 
Remove the override of the tmp directory from the test.
*(or)*
*(or)*
- *This change only modifies test code*
PR in forked repository: https://github.com/andrasbeni/pulsar/pull/8

[fix][test] Fix flaky test AdditionalServletsTest.testEmptyStringAsExtractionDirectory

---

pom.xml

- attempt to fix StackoverflowError issue in compilation
- upgrade Lombok to 1.18.24 ([release notes](https://projectlombok.org/changelog))
PR in forked repository: https://github.com/lhotari/pulsar/pull/105

[improve][misc] Upgrade Lombok to 1.18.24

---

.github/workflows/ci-go-functions.yaml
.github/workflows/ci-maven-cache-update.yaml
.github/workflows/ci-owasp-dependency-check.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

- For some reason compilation can fail with StackOverflowError with the default settings
- increase thread stack size to 1500k (with -Xss1500k)
[Example failure](https://github.com/lhotari/pulsar/actions/runs/3539467053/jobs/5941406694#step:9:2990):
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project pulsar-broker-common: Fatal error compiling: java.lang.StackOverflowError -> [Help 1]
```
I've created this PR as a draft so that we can use this if we end up needing to address this issue and it reproduces again.
- Add `-Xss1500k` to `MAVEN_OPTS`
PR in forked repository: https://github.com/lhotari/pulsar/pull/104

[fix][ci] Increase thread stack size to 1500k for Maven JVM to prevent StackOverflowError in compilation

---

tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/KafkaSourceTester.java

Fixes #15853
There's a resource leak in KafkaSourceTester which will be fixed by this PR.
Use try-with-resource to close the KafkaProducer after use.

[fix][test] Close KafkaProducer in integration tests to prevent thread leak

---

pulsar-proxy/pom.xml

Fixes Maven build warning
```
Warning:  Some problems were encountered while building the effective model for org.apache.pulsar:pulsar-proxy:jar:2.11.0-SNAPSHOT
Warning:  'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.awaitility:awaitility:jar -> duplicate declaration of version (?) @ line 183, column 17
```
- remove duplicate test dependency org.awaitility:awaitility in pulsar-proxy
PR in forked repository: https://github.com/lhotari/pulsar/pull/106

[fix][proxy] Remove duplicate test dependency org.awaitility:awaitility in pulsar-proxy

---

pom.xml
pulsar-common/pom.xml

Fixes #18530
There's need to add the classes dependency for io-uring in order to always have them in the classpath, even if you're compiling in a platform where native implementation of netty io-uring is not available. 
* Added the `netty-incubator-transport-classes-io_uring` dependency to pulsar-common
Build `pulsar-common` and `distribution` (to generate the classpath.txt) and test the cli tools

[fix][misc] Fix NoClassDefFoundError: io/netty/incubator/channel/uring/IOUringEventLoopGroup

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicListService.java

While reading code in TopicListService, I noticed a race condition that could happen in the case where the connection is closing and there's a TopicListWatcher that is in being initialized. 
Add check to see if the watcherFuture can be completed. If not, deregister the watcher.

[fix][broker] Fix possible race condition in completing topic list watcher

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TopicResources.java

Follow "zero garbage" style on hot code paths.
* In this case, the usage of EnumSet isn't justified since there's only 2 enums to check
* topicListeners is a ConcurrentHashMap, no need for a copy
* skip checks when topicListeners is empty
* optimize TopicResources.handleNotification method.

[improve][broker] Reduce object creation in TopicResources.handleNotification

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java

We have set log4j.shutdownHookEnabled=false, so we need add finally LogManager.shutdown() invoke in PulsarProxy Runtime ShutdownHook. Similar to: #15626

[fix][proxy] Fix logging in shutdown when proxy shutdown

---

pulsar-client-tools/src/main/java/org/apache/pulsar/shell/ConfigShell.java
pulsar-client-tools/src/test/java/org/apache/pulsar/shell/ConfigShellTest.java

Fixes #18175
To simplify adding a new config, it might be useful to clone an existing one and then update the needed fields with `set-property` cmd
* Added `config clone <copyfrom> --name <newconfig>` command
* Also fixed autocomplete in config create to not autocomplete with existing names
https://github.com/apache/pulsar-site/pull/303

[improve][cli] Pulsar shell: allow cloning an existing config

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/KeySharedSubscriptionTest.java

Test leaks a Pulsar client instance
Use the default instance to run the test

[fix][test] Fix Pulsar client leak in KeySharedSubscriptionTest

---

pulsar-client-tools/src/main/java/org/apache/pulsar/shell/PulsarShell.java

In Pulsar shell if there's a command that is running (e.g client consume) and the user send a SIGINT (ctrl+c) the shell should not exit but it should only stop the current command.
* Added native signals to JLine terminal to explictly handle SIGINT and SIGQUIT
Note that ctrl+d (SIGTERM) will let the shell to exit in any case. this is done on purpose 
Run `client consume` without any message in the topic and hit ctrl+c.

[fix][cli] Pulsar shell: do not exit on user interrupt during commands

---

pom.xml
pulsar-io/kafka-connect-adaptor/pom.xml

[netty-bom](https://search.maven.org/artifact/io.netty/netty-bom) includes the correct Netty tcnative version which is compatible with a particular Netty version. Because of this reason, it's an unnecessary overhead to duplicate the information in Pulsar pom.xml .
- remove `netty-tc-native.version` from Pulsar's `pom.xml`
- remove unnecessary dependency management dependencies that are included in netty-bom
- remove unnecessary definition of version for a netty dependency
PR in forked repository: https://github.com/lhotari/pulsar/pull/107

[improve][build] Remove versions that are handled by netty-bom

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/AdminApiTransactionMultiBrokerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/AdminApiTransactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorRemoveClusterTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/TransactionMetricsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionConsumeTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionStablePositionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/coordinator/TransactionCoordinatorConfigTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerCloseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerMemoryLimitTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientInitializationTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerImplTest.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStoreTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyRefreshAuthTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyRolesEnforcementTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithJwtAuthorizationTest.java
pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarAuth.java
pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceTransactionTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/CLITest.java

Pulsar tests leak multiple Pulsar client instances without closing and cleaning up the resources.
Add `@Cleanup` annotations where applicable and use the `replacePulsarClient` method to replace the pulsar client in a 
test that uses MockedPulsarServiceBaseTest as a base class.
PR in forked repository: https://github.com/lhotari/pulsar/pull/108

[fix][test] Fix multiple Pulsar client leaks in tests

---

.asf.yaml

reason: https://lists.apache.org/thread/jcrq9q0k6kh9rvb71dwb9s3mvo5c5dk5
branch-2.9 has reset to commit `5ed247de3a5e0ff67f181b4805fd6140d8174994`, so close force-push

[fix][ci] Disable branch-2.9 force push

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java

cherry-pick: https://github.com/apache/pulsar/pull/18061
Fixes #18023
If the namespace policy inits without setting `managedLedgerOffloadThresholdInBytes`(like : if user `setOffloadDeletionLag ` first and then `getOffloadThreshold `), it will cause NPE when get `OffloadThreshold`.
PR in forked repository: https://github.com/Technoboy-/pulsar/pull/12

[cherry-pick][branch-2.9] Fix NPE when get OffloadThreshold on namespace.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java

This PR is a supplement to #18369.
- `AbstractTopic.isSameAddressProducersExceeded()`
- `AbstractBaseDispatcher.isConsumersExceededOnSubscription()`
- https://github.com/yuruguo/pulsar/pull/1

[improve][broker] System topic writer/reader connection not counted

---

.github/workflows/ci-semantic-pull-request.yml

PR in forked repository: N/A
cc @nicoloboschi @lhotari I tested on the regex101.com the last time, but miss the group number.
Here's a false case: https://github.com/apache/pulsar/actions/runs/3547655293 and should be fixed with this patch.

[fix][ci] Regex syntax

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherSingleActiveConsumer.java

The dispatcher executor of `PersistentDispatcherSingleActiveConsumer` is introduced in #18566.
Since it is only for `PersistentStreamingDispatcherSingleActiveConsumer`, so move it out from the `PersistentDispatcherSingleActiveConsumer`.

[cleanup][broker] Move dispatcherExecutor out from PersistentDispatcherSingleActiveConsumer

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedderTest.java
pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerData.java
pulsar-common/src/test/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerDataTest.java

Discuss is https://github.com/apache/pulsar/issues/18598

[fix][broker] Revert "[fix][load-balancer] skip mis-configured resource usage(>100%) in load balancer

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

Now we only use caffeine in broker module. *caffeine* has a jdk11+ version, which is more proper for jdk11+ project to integrated with.(Spring3.0 uses caffeine 3.X too.) So I think it's worth for us to update caffeine to 3.x
Update caffeine from 2.9.1 to 3.1.2
https://github.com/apache/pulsar/pull/18647

[improve][misc] Update caffeine from 2.9.1 to 3.1.2

---

tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedInputStreamImpl.java

Fixes #18580
Fix numerical overflow bug while reading data from tiered storage.
Fix the `BlobStoreBackedInputStreamImpl.available`.
This change is hard to add test case because it might cause OOM.
PR in forked repository: https://github.com/dragonls/pulsar/pull/5

[fix][offload] Fix numerical overflow bug while reading data from tiered storage

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregatorTest.java

The pulsar_subscription_blocked_on_unacked_messages metric was not scrapped by Prometheus although the dispatcher can be blocked on number of unacked messages:
```
Dispatcher read is blocked due to unackMessages 200010 reached to max 200000
```
When Prometheus scrapes stats topics, the previous logic was relying on the consumer flag to update the subscription  although the subscription configs and logic is independent of the attached consumer. The related config for subscription is `maxUnackedMessagesPerSubscription` and for consumers is `maxUnackedMessagesPerConsumer`
This change just copied over the value from the `SubscriptionStats` to the `AggregatedSubscriptionStats`
This change is a trivial rework / code cleanup without any test …

[fix][monitor] Fix reporting pulsar_subscription_blocked_on_unacked_messages metric

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java

When updating partitions for a topic, the new subscriptions created for new partitions should be replicated if the subscription for the first partition (index 0) is replicated.
- pass replicated parameter to creating subscription
- add test
PR in forked repository: https://github.com/lhotari/pulsar/pull/109

[fix][broker] Create replicated subscriptions for new partitions when needed

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java

It's from a production case in my org, one of our consumer application constantly create consumer instance after increase topic partition due to old pulsar-client bug. The application got OOM eventually and broker publish latency goes more than 30s, so many publish requests timeout, broker latency go back normal after application restart.
It could be reproduce below:
```shell
pulsar-admin namespaces create -b 128 public/perf
pa namespaces set-max-consumers-per-topic -c 0 public/perf
pa namespaces set-max-consumers-per-subscription -c 0 public/perf
pulsar-perf produce -r 1000 persistent://public/perf/perf
pulsar-perf consume -st Shared -n 100000 persistent://public/perf/perf
```
After stop consume program, `pulsar-io` thread will be block for a while, publish latency will be very high …

[improve][broker] Make Consumer#equals more effective

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedderTest.java

More details are here https://github.com/apache/pulsar/issues/18598, so add this test to avoid regression.

[improve][test] Add test `brokerReachThreshold` for ThresholdShedderTest 

---

site2/docs/administration-load-balance.md

Add docs for ThresholdShedder
https://github.com/apache/pulsar/pull/17456

[fix][doc]Add docs for ThresholdShedder

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java

First judge whether config is null when standalone start.

[improve][broker] First judge whether config is null when standalone start

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageChunkingTest.java

Fixes #18570 
The `testMaxPendingChunkMessages` is flaky. This PR use another approach to test the maxPendingChunkMessages configuration.
The original test is a probability test, and it can only succeed with a certain probability. It simulates 25 producers writing to a topic with large messages, each with 5 chunks concurrently. Only if one of these chunked messages appears interleaved will it cause message loss and make the test pass. The success of the test is asserted by the loss of at least one message. The result of the test on my local machine is that only 2 out of 25 messages are lost. So the probability of failure of this test is still relatively high.
Therefore, I choose another approach to rewrite the test and make it deterministic by sending each single chunk manually.
* Fix …

[fix][test] Fix `testMaxPendingChunkMessages`

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java

Fix test testPerTopicStatsReconnect.
The `headersAndPayload` - `msg.bytes` = 42 in 2.10.
1. This is not contained in branch 2.10, which makes the payload of this test message add 8 bytes.
if n=1, batchedMessageMetadataAndPayload size = 10 in master but 12 in breach master. 
https://github.com/apache/pulsar/blob/463f590c8215bdee836ecfe44b83abbbd6ce6fbb/pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java#L146-L151
https://github.com/apache/pulsar/blob/463f590c8215bdee836ecfe44b83abbbd6ce6fbb/pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java#L1776-L1785
2. This code is deleted from the master, which adds 3 bytes.
```java
if (!msgMetadata.hasPublishTime()) {
msgMetadata.setPublishTime(client.getClientClock().millis()); …
```

[fix][branch-2.10]The pulsarMessageOverhead in 2.10 is different

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistry.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManager.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/LoadManagerContext.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLoadData.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLookupData.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/data/TopBundlesLoadData.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/data/package-info.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerFilter.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/package-info.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/package-info.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/reporter/LoadDataReporter.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/reporter/package-info.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/LoadManagerScheduler.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/NamespaceBundleSplitStrategy.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/NamespaceUnloadStrategy.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/package-info.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStore.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreException.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/package-info.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLoadDataTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLookupDataTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/data/TopBundlesLoadDataTest.java
pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerData.java

Master Issue: #16691
The PR adds base classes for the new broker load balance project and does not integrate with the existing load balance logic. This PR should not impact the existing broker load balance behavior.
For the pip-192 project, this PR
* defines the base interface under `org.apache.pulsar.broker.loadbalance.extensible` package.
* defines this `BrokerRegistry` public interface and its expected behaviors.
* defines `BrokerFilter` interfaces.
* defines `LoadDataReporter` interfaces.
* defines `NamespaceBundleSplitStrategy` interfaces.
* defines `LoadManagerScheduler` interfaces.
* defines `NamespaceUnloadStrategy` interfaces.
* defines `LoadDataStore` interfaces.
* defines …

[improve][broker] PIP-192: Define new load manager base interfaces

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java

There exists potential non-durable cursor leak problem, if `deleteCursor` called but without deactive this cursor.
Master branch has fix this issue by #17273
Deactive cursor  in deleteCursor
https://github.com/gaozhangmin/pulsar/pull/2

[branch-2.8]Fix non-durable cursor leak problem

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java

There exists potential non-durable cursor leak problem, if `deleteCursor` called but without deactive this cursor.
Master branch has fix this issue by #17273
Deactive cursor  in deleteCursor
https://github.com/gaozhangmin/pulsar/pull/2

[branch-2.10] Fix no durable cursor leak problem

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java

Making defaultNumberOfNamespaceBundles of `ServiceConfiguration` dynamic.   
The scenario is that we may create  a lot of topics with different namespaces in the future, but finding that the `defaultNumberOfNamespaceBundles` is not suitable, so it's better we could change the `defaultNumberOfNamespaceBundles` dynamic
Make defaultNumberOfNamespaceBundles of `ServiceConfiguration` dynamic. 
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/19

[improve][broker] Making defaultNumberOfNamespaceBundles of ServiceConfiguration dynamic

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java

Some scheduled tasks will be started when the broker starting, including:
```java
// start other housekeeping functions
this.startStatsUpdater(
serviceConfig.getStatsUpdateInitialDelayInSecs(),
serviceConfig.getStatsUpdateFrequencyInSecs());
this.startInactivityMonitor();
this.startMessageExpiryMonitor();
this.startCompactionMonitor();
this.startConsumedLedgersMonitor();
this.startBacklogQuotaChecker();
this.startCheckReplicationPolicies();
this.startDeduplicationSnapshotMonitor();
```
But the interval of these scheduled tasks should be greater than 0, otherwise an exception will be reported during startup, as below:
```
ERROR org.apache.pulsar.broker.PulsarService - Failed to start Pulsar service: null
java.lang.IllegalArgumentException: null
at …
```

[improve][broker] The interval of scheduled task should be greater than 0

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java

This is a trivial cleanup, though it might technically break some deployments. Given that the `getBrokerClientTrustCertsFilePath` takes precedence over the `getTlsCertificateFilePath`, it is unlikely to have been used with any frequency. However, it is better to correctly update the trust certs file path. The consequence of this breaking change will be immediately obvious to any impacted users, as their pulsar clients will not trust certificates that they may have trusted before.
This is not a security vulnerability.
* Replace `getTlsCertificateFilePath` with `getTlsTrustCertsFilePath` when calling `setTlsTrustCertsFilePath` on the pulsar client in the pulsar broker. …

[fix][broker] Use correct file path for tls trust certificates

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java
pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactorTool.java
pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java

So that the default value on the [reference page](https://pulsar.apache.org/reference/) is clear without a machine relative prefix.
Before:
After:

[improve][cli] Better relative path arguments

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java

[PIP-180](https://github.com/apache/pulsar/issues/16153) add shadow topic feature. Shadow topic is read-only, but if I send msg to a shadow topic, the error message is `"Only shadow topic supports sending messages with messageId"`, which is confusing.
PTAL @Jason918

[improve][broker] improve shadow topic error message

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java

There exists potential non-durable cursor leak problem, if `deleteCursor` called but without deactive this cursor.
Master branch has fix this issue by #17273
Deactive cursor  in deleteCursor
https://github.com/gaozhangmin/pulsar/pull/2

[branch-2.9] Fix no durable cursor leak problem

---

pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordCursor.java

Fix message without schema cause BufferUnderflowException. This issue is the same with #15622,  #14626
```
2022-11-22T19:10:31.948653279-05:00 com.google.common.util.concurrent.UncheckedExecutionException: java.nio.BufferUnderflowException
2022-11-22T19:10:31.948663818-05:00 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
2022-11-22T19:10:31.948667961-05:00 	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
2022-11-22T19:10:31.948671522-05:00 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
2022-11-22T19:10:31.948674754-05:00 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
2022-11-22T19:10:31.948678018-05:00 	at org.apache.pulsar.sql.presto.PulsarSqlSchemaInfoProvider.getSchemaByVersion(PulsarSq …
```

[fix][sql] Fix message without schema issue.

---

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java

Improve the comments in ConsumerBuilder.java for clarity and cleanliness.
These can be the first documentation devs see in an IDE, so they should inspire more confidence in users. 
Cleaned up the comments in the ConsumerBuilder.java file. 
*(or)*
*(or)*
*(example:)*

[improve][doc] ConsumerBuilder.java comments

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/ShadowTopicTest.java

Fixes #18705
awaitUntilShadowReplicatorReady check is returned when ShadowReplicator is null
so the replicator is not ready when producer send message.
and the consumer wont get any message.

[fix][test] Flaky-test: ShadowTopicTest.testShadowTopicConsuming

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/schema/SchemaStorage.java

Fixes: #18292
Another solution of #18293
Fix the duplicated schemas creation due to race conditions.
The broker will get all the schemas to check whether or not the given schema exists.
And then put the schema into the schema storage once the schema doesn't exist.
But If there are parallel requests with the same schema. 
The Schema registry will put duplicated same schemas into the
schema storage.
For each schema update, we need to update the schema locator.
The PR uses the Zookeeper data version control to ensure
the schema locator will not be updated based on outdated data.
And will retry to check if schema exists and compatibility while
encountering bad version exceptions.
And the created Ledger with failed locator updating will be removed
to avoid the Ledger leak issue.
Add a new put …

[fix][broker] Fix duplicated schemas creation

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/KeySharedSubscriptionTest.java
pulsar-sql/presto-distribution/LICENSE

Fixes: #18732
Revert #18467 to fix the JVM crash issue, which has been described in #18732
After the CI gets passed. I will create a GitHub issue for the caffeine repo

[fix][test] Revert "[improve][misc] Update caffeine from 2.9.1 to 3.1.2 (#18647)"

---

site2/docs/io-debezium-source.md

This is a follow-up to #18769. Sorry, I miss these lines in the first place.

[cleanup][doc] Remove wrong expressions

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java
pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc

fix cherry-pick #17609 import
fix cherry-pick #17957  import
fix cherry-pick #16878 lose problem
fix cherry-pick #17503 problem

[cherry-pick][branch-2.9] fix cherry-pick #17609 #17957 import

---

bin/pulsar

[improve][cli] Document bin/pulsar envvars

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java

Remove consumer null-check in `PersistentStickyKeyDispatcherMultipleConsumers#trySendMessagesToConsumers`, for we have check it in line220:
https://github.com/apache/pulsar/blob/12b864ef14311fdba5d0b40a8a4f005b262e48c0/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java#L220-L223 
Remove consumer null-check in `PersistentStickyKeyDispatcherMultipleConsumers#trySendMessagesToConsumers`
PR in forked repository:https://github.com/AnonHxy/pulsar/pull/21

[cleanup][broker] Remove consumer null-check in trySendMessagesToConsumers

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java

cherry-pick: #16221
Master Issue: https://github.com/apache/pulsar/issues/14365
* See https://github.com/apache/pulsar/issues/14365
* Make getList async

[cherry-pick][branch-2.9] make getList async #16221

---

bin/pulsar-perf

`pulsar-perf` fails with jdk17.
```
2022-12-06T09:43:53,357-0600 [pulsar-perf-producer-exec-1-1] WARN  io.netty.resolver.dns.DnsServerAddressStreamProviders - Can not find io.netty.resolver.dns.macos.MacOSDnsServerAddressStreamProvider in the classpath, fallback to system defaults. This may result in incorrect DNS resolutions on MacOS.
2022-12-06T09:43:53,369-0600 [pulsar-perf-producer-exec-1-1] WARN  org.apache.pulsar.common.util.netty.DnsResolverUtil - Cannot get DNS TTL settings from sun.net.InetAddressCachePolicy class
java.lang.IllegalAccessException: class org.apache.pulsar.common.util.netty.DnsResolverUtil cannot access class sun.net.InetAddressCachePolicy (in module java.base) because module java.base does not export sun.net to unnamed module @6456fb59
at …
```

[fix][cli] pulsar-perf fails on jdk17

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionProduceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java

Cherry-pick https://github.com/apache/pulsar/pull/18307 for release 2.9.4.
Cherry-pick https://github.com/apache/pulsar/pull/18307 for release 2.9.4.
*(or)*
*(or)*
*(example:)*

[cherry-pick][branch-2.9] Cherry-pick #18307 (Fix can not delete namespace by force)

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/OwnerShipForCurrentServerTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BkEnsemblesTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerBookieIsolationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceAutoTopicCreationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientDeduplicationFailureTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionE2ESecurityTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionLocalRunTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionPublishTest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/AbstractPulsarE2ETest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java

Change the data type of the `allowAutoTopicCreationType` from `String` to `TopicType` enum in Configuration, which could supplement the verification for its value when creating the configuration, so that the broker will stop directly if the value is invalid.
Before this, if the value of `allowAutoTopicCreationType` is illegal but lacks verification, the broker can still start normally but may encounter unexpected results when using this value. 
For example, if the user sets `allowAutoTopicCreation` to `ture` and wants to create the topic automatically as partitioned topic(`allowAutoTopicCreationType = partitioned`) in broker.conf, but mistakenly sets `allowAutoTopicCreationType` to `partition`, the broker can start normally but it is a non-partitioned topic when automatically creating the …

[improve][broker] Change type of `allowAutoTopicCreationType` to TopicType

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java

In `org.apache.pulsar.client.impl.MultiTopicsConsumerImpl#createPartitionedConsumer`, it is more appropriate to change some places to generic format. For example, see line 932, it is better to change`ConsumerConfigurationData` to `ConsumerConfigurationData<T>`.
https://github.com/apache/pulsar/blob/fc655c8897276fbfd961da1d78b7b871fcfb2d4e/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L932-L940
Change some code in `org.apache.pulsar.client.impl.MultiTopicsConsumerImpl#createPartitionedConsumer` to generic mode.
PR in forked repository: https://github.com/Pomelongan/pulsar/pull/16

[improve][client] Optimize code for MultiTopicsConsumerImpl

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LinuxBrokerHostUsageImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LinuxBrokerHostUsageImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/LinuxBrokerHostUsageImplTest.java

This break was introduced by #14648 and affected unreleased 2.11.
- Multiply `overrideBrokerNicSpeedGbps` with the NIC number.

[fix][broker] Fix the wrong behaviour when set `overrideBrokerNicSpeedGbps`

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LinuxBrokerHostUsageImpl.java

As https://github.com/apache/pulsar/issues/14820#issuecomment-1340677223 mentioned, we need to revert this change to fix regression.
For the original issue, the workaround fix is he can divide the target by two. for the fixing, I would like to start a discussion, and I suggest introducing the new config to fix this problem.
- Revert 14829
I'm not sure if we need to notice this problem.

[fix][broker] Revert #14829 Filter the virtual NIC with relative path

---

pulsar-broker-common/src/main/java/org/apache/pulsar/common/configuration/PulsarConfigurationLoader.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyConfigurationTest.java

This regression is introduced by #16234. 
I found it by setting `proxyAdditionalServlets ` on the proxy, I expected it could load the additional servlet, but it didn’t work well. the `proxyConfig.getProperties().getProperty("proxyAdditionalServlets")`  method returns `null` after invoking `PulsarConfigurationLoader#convertFrom`.
After investigating, The root cause is we use the same properties object when we invoke `convertFrom ` method. And then, it set the unknown field to the new config without any type check.
- Don't use the same properties object when converting.

[fix][broker] Fix unexpected behaviour by invoke `PulsarConfigurationLoader#convertFrom`

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java

Fixes 
- #9919
PR #16878 cannot be `cherry-picked` to `branch-2.10`, there will be a conflict. so create this new PR.
----
(<strong>High light</strong>) The logic differs from #16878:
-  after cursor init: metrics `brk_ml_cursor_persistLedgerSucceed` is `0` in `branch-master`. But in current PR, it is `1`
"createNewMetadataLedger" triggers once BK writes
- in `branch-2.10`, "cursor.initialize" triggers the execution of "createNewMetadataLedger". see <strong>[Code in branch-2.10]</strong>
- in `branch-master`, "cursor.initialize" does not triggers the execution of "createNewMetadataLedger". see <strong>[Code in branch-master]</strong>
https://github.com/apache/pulsar/blob/8409652f82b291891fe2670cfef3b869ad264a5a/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorIm …

[branch-2.10][fix][flaky-test] ManagedCursorMetricsTest.testManagedCursorMetrics

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/BaseResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/LocalPoliciesResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TenantResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TopicResources.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java

cherry-pick #12711 #12972
1. According to the previous code logic, if the tenant resource is not forcibly deleted, the zk-node resource will be leaked, because under the condition of **!force**, the `clearTenantPersistence` code logic will not be called.
```
protected void internalDeleteTenant(AsyncResponse asyncResponse, String tenant, boolean force) {
if (force) {
internalDeleteTenantForcefully(asyncResponse, tenant);
} else {
internalDeleteTenant(asyncResponse, tenant);
}
}
```
2. Clear  resource of `/namespace/xxx` z-node 
3. When we run follow command:
```
bin/pulsar-admin tenants delete test2
```
the zk-node of `/admin/partitioned-topics` and `/admin/local-policies` wil not remove, casued by zk-node leak.
PR in forked repository: (https://github.com/congbobo184/pulsar/pull/9)

[cherry-pick][branch-2.8] fix znode leakage caused by deleting tenant #12711#12972

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java

Fix the uncompleted future when getting the topic policies of a deleted topic. 
https://github.com/apache/pulsar/blob/30b52a1ac11b4be485258140a167b5e635586a36/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java#L513-L535
`future.complete(null);` when `msg.getValue() == null`.
*(or)*
*(or)*
*(example:)* …

[fix][broker] Fix uncompleted future when get the topic policies of  a deleted topic

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerStrategyTest.java

As the `brokerAvgResourceUsageWithWeight`  stored the broker's history resource usage, if a broker is high load before restart, after the broker restart always show a high load history resource usage, and `loadBalancerHistoryResourcePercentage = 0.9`, which will cause the first few  times the broker can not be select as best broker to load  bundles. Only when `selectBrokerForAssignment` invoke few time's ,  the `brokerAvgResourceUsageWithWeight` could be neutralized by the current resourceUsage.
But bundles unload is not a frequently operator if not disable `doLoadShedding`,it will wait a long time;  So if a broker restarted we can clean the brokers history resource usage to guaranty the no bundles or no msgRate broker can be select as the one of  best brokers. …

[improve] [broker] improve the restart broker can load bundle as one of the best brokers when selectBroker in LeastResourceUsageWithWeight

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java

Remote test `testGetTopic`, because it was mis cherry-picked by #18181. 
The original pr for this test is #17416

[fix][test][branch-2.10] Remove testGetTopic method

---

buildtools/pom.xml
pom.xml
pulsar-client-tools-customcommand-example/pom.xml

This closes #17754.
See https://github.com/apache/pulsar/pull/17754#issue-1380037910.
Also, this corrects the generated NOTICE year range.
* Set `project.build.outputTimestamp` to `maven.build.timestamp`
* Upgrade plugin for reproducible builds, spotted by `mvn artifact:check-buildplan`
PR in forked repository: https://github.com/tisonkun/pulsar/pull/21

[improve][build] Set correct project.build.outputTimestamp

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionProduceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java

Cherry-pick (#18307) to release 2.11.1.
Cherry-pick (#18307) to release 2.11.1.
*(or)*
*(or)*
*(example:)*

[cherry-pick][branch-2.11] cherry-pick fixing can not delete namespace by force (#18307)

---

site2/docs/cookbooks-compaction.md
site2/website/versioned_docs/version-2.10.x/cookbooks-compaction.md
site2/website/versioned_docs/version-2.8.x/cookbooks-compaction.md
site2/website/versioned_docs/version-2.9.x/cookbooks-compaction.md

[fix][doc] Avoid refer to deprecated classes

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherMultipleConsumers.java

For most case, consumer in `currentRoundRobinIndex` should be available,  so we could avoid some checks in first scan actions  by checking `currentRRConsumer` available first,  also this will make the code more clear
Fast return if validalbe when getNextConsumerFromSameOrLowerLevel
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/22

[improve][broker] Fast return if validalbe when getNextConsumerFromSameOrLowerLevel

---

site2/docs/helm-deploy.md

In the PR https://github.com/apache/pulsar/pull/18015 we agreed to remove the mention on `local_storage` config in the k8s doc https://github.com/apache/pulsar/pull/18015#discussion_r1001671632. 
But seems there is a missing to remove in the samples. 
Remove the `local_storage` config in the samples. 
*(or)*
*(or)*
*(example:)*
PR in …

[fix][doc] remove config `local_storage` in the sampes. 

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java

origin extract entry metadata logic is based on `Optional.map.orElseGet` which can be simplified by if condition and also has better performance on hot code path.
1. use if null check replace Optional code.
2. remove duplicate hasChunk check logic in `PersistentDispatcherMultipleConsumers.trySendMessagesToConsumers`

[cleanup][broker] Simplify extract entryMetadata code in filterEntriesForConsumer

---

site2/docs/administration-pulsar-manager.md
site2/website/versioned_docs/version-2.10.x/administration-pulsar-manager.md
site2/website/versioned_docs/version-2.5.1/administration-pulsar-manager.md
site2/website/versioned_docs/version-2.5.2/administration-pulsar-manager.md

[fix][doc] broken command

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CliCommand.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBase.java

```bash
$ ./bin/pulsar-admin schemas -h
Expected a command, got -h
Invalid command, please use `pulsar-admin --help` to check out how to use
2022-12-09T16:18:27,751+0800 [main] WARN  org.apache.pulsar.common.util.ShutdownUtil - Triggering immediate shutdown of current process with status 1
java.lang.Exception: Stacktrace for immediate shutdown
at org.apache.pulsar.common.util.ShutdownUtil.triggerImmediateForcefulShutdown(ShutdownUtil.java:52) ~[pulsar-common.jar:2.11.0-SNAPSHOT]
at org.apache.pulsar.admin.cli.PulsarAdminTool.exit(PulsarAdminTool.java:309) ~[pulsar-client-tools.jar:2.11.0-SNAPSHOT]
at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:300) ~[pulsar-client-tools.jar:2.11.0-SNAPSHOT]
```
```bash
$ ./bin/pulsar-admin schemas delete -h
null
Reason: …
```

[improve][cli] handle help flag properly

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/PendingAckHandleImpl.java

When initialize PendingAckHandleImpl, it will call
```
pendingAckStoreProvider.checkInitializedBefore(persistentSubscription)
.thenAccept(init -> {
if (init) {
initPendingAckStore();
} else {
completeHandleFuture();
}
});
```
And `pendingAckStoreProvider.checkInitializedBefore(persistentSubscription)` will call `MetadataStore#asyncExists(String ledgerName)`
If MetadataStore no available at that time, it may returns an exception.
If we don't handle the exception when call 
```
pendingAckStoreProvider.checkInitializedBefore(persistentSubscription)
```
the PendingAckHandleImpl cannot completed.
[addConsumer](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java#L214) will always block, the Consumer …

[fix][txn] Fix PendingAckHandleImpl when `pendingAckStoreProvider.checkInitializedBefore` failed

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
pulsar-broker/src/test/java/org/apache/pulsar/PulsarStandaloneTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/standalone/SmokeTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarStandaloneTestBase.java

In the standalone model, when the `admin` client hasn't permission to create the namespace, the Pulsar will exit.
We should keep the same logic with branch-2.10.
https://github.com/apache/pulsar/blob/branch-2.10/pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java#L409-L414
Add `try...catch` to pack.

[fix][broker] Ignore the exception of creating namespace

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java

Optimize the method, fast return when AppendIndexMetadataInterceptor is matched.
1. Fast return when when AppendIndexMetadataInterceptor is matched.
PR in forked repository:https://github.com/Nicklee007/pulsar/pull/6

[improve][broker] Fast return when AppendIndexMetadataInterceptor is matched.

---

buildtools/pom.xml
distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-sql/presto-distribution/LICENSE
src/owasp-dependency-check-false-positives.xml

- Netty 4.1.85 includes an important fix to FlowControlHandler that [is used in Pulsar](https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarChannelInitializer.java), see release notes https://netty.io/news/2022/11/09/4-1-85-Final.html
- Netty 4.1.86 includes a fix for the regression in 4.1.85 in HashedWheelTimer, see release notes https://netty.io/news/2022/12/12/4-1-86-Final.html . It also includes a fix for a security vulnerability, [CVE-2022-41881](https://github.com/netty/netty/security/advisories/GHSA-fx2c-96vj-985v)
- Upgrade Netty to 4.1.86.Final
- Update Netty Tcnative to 2.0.54.Final (referenced in netty-bom)
- Upgrade netty-iouring.version to 0.0.16.Final which is compatible with …

[improve][misc] Upgrade Netty to 4.1.86.Final and Netty Tcnative to 2.0.54.Final

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/PerfToolTest.java

Cherry-pick https://github.com/apache/pulsar/pull/17826 and https://github.com/apache/pulsar/pull/17705 for releasing 2.10.3 and run the tests.
This change is a trivial rework/code cleanup without any test coverage.
*(or)*
*(or)*
*(example:)*

[cherry-pick][branch-2.10] Check numMessages after incrementing counter and NPE cause

---

.github/workflows/pulsar-ci.yaml

- The GitHub Actions workflow "Pulsar CI" is supposed to run OWASP dependency check when pom.xml files are modified. This doesn't currently work. This seems to be a problem in the original change #17568.
- Fix the problem that causes "OWASP dependency check" job to always get skipped.
PR in forked repository: https://github.com/lhotari/pulsar/pull/111 (added some additional changes that contain pom.xml changes)

[fix][ci] Fix running OWASP for PRs that change dependencies

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/GeoPersistentReplicator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java

Fixes #18888
Transaction markers and non committed messages should not being replicated by the geo-replicator.
Those messages must appear as normal messages in the destination clusters.
* Skip txn marker in the replicator
* Skip messages of aborted txn in the replicator
* In the replicator read entries from the maxReadPosition of the topic instead of Latest in order to not read non committed messages
* Remove txn metadata from the message metadata 
Notes: I haven't modified the shadow topic replicator because I'm not sure if that feature is completed or not and in any case it's better to fix it in another pull
https://github.com/nicoloboschi/pulsar/pull/39

[fix][txn] Fix replication of transactional messages

---

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ProducerBuilder.java

Improve the comments in ProducerBuilder.java for clarity and cleanliness.
These can be the first documentation devs see in an IDE, so they should inspire more confidence in users. 
Cleaned up the comments in the ProducerBuilder.java file. 
https://github.com/mendonk/pulsar/pull/1
*(or)*
*(or)*
*(example:)*

[improve][doc] ProducerBuilder.java

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java

Fixes #18802
Sending the event to the __change_events topic is useless if the namespace is deleted (or in the process of).
Also during the namespace deletion procedure, it's not possible to create new topics so if it doesn't exist yet it throws an error.
* Skip sending events for topic policies if the namespace has been deleted

[fix][broker] Fix namespace deletion if __change_events topic has not been created yet

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java
pulsar-client-cpp/lib/MultiTopicsConsumerImpl.cc
pulsar-client-cpp/lib/MultiTopicsConsumerImpl.h
pulsar-client-cpp/tests/ConsumerTest.cc

Cherry-pick https://github.com/apache/pulsar/pull/17503 to release 2.10.3 and run tests.
Cherry-pick https://github.com/apache/pulsar/pull/17503 to release 2.10.3.
*(or)*
*(or)*
*(example:)*

[cherry-pick][branch-2.10] Fix issue where unexpected ack timeout

---

site2/docs/concepts-messaging.md

Key Shared subscription type has multiple algorithms for mapping a message key to a consumer, yet they are not documented, leaving the user with no easy way of knowing how a Key Shared Subscription works and what are the possible options for configuration.
Added documentation under Messaging / Concepts / Subscriptions / Key Shared
PR in forked repository: https://github.com/asafm/pulsar/pull/1

[improve][doc] Added docs for key shared subscription hashing schemes

---

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java
pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceTransactionTest.java

Add option to create replicated subscription in `pulsar-perf transaction`.
- `-rs, --replicated` to create replicated subs. `--replicated` is the same that it's in pulsar-perf consume.
- Added `-rs` also to pulsar-perf consume for consistency 
- FIxed leaks in perf tests

[improve][cli] Option to create replicated subscriptions in pulsar-perf txn

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java

Fixes https://github.com/apache/pulsar/issues/18915
Fix the bug: rest API `partitioned-internalStats` is missing in docs
https://pulsar.apache.org/admin-rest-api
make the rest API `partitioned-internalStats` visiable in docs
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/urfreespace/pulsar/pull/82

[fix][doc] fix rest api `partitioned-internalStats` is missing in docs

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
pulsar-broker/src/test/java/org/apache/pulsar/MockTokenAuthenticationProvider.java
pulsar-broker/src/test/java/org/apache/pulsar/PulsarStandaloneTest.java
pulsar-broker/src/test/resources/configurations/standalone_no_client_auth.conf
tests/integration/src/test/java/org/apache/pulsar/tests/integration/standalone/SmokeTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarStandaloneTestBase.java

Fix the regression brought by #15186. See
https://lists.apache.org/thread/vz3tqpgs5l1r0trq29r4hdf85t0rjc8j for details.
Use `PulsarAdmin` to initialize the metadata so that it would fail if the authentication of the built-in clients were not configured correctly.
Add a `testMetadataInitialization` to avoid the regression. And move the bundle policy test from `SmokeTest` to this test.
PR in forked repository: https://github.com/BewareMyPower/pulsar/pull/14

[fix][broker] Fix the breaking change of standalone metadata initialization

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorUtils.java
pulsar-broker-common/src/test/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorUtilsTest.java
pulsar-broker-common/src/test/java/org/apache/pulsar/broker/stats/prometheus/package-info.java

Cherry-pick https://github.com/apache/pulsar/pull/17704 for release 2.10.3 and run tests.
Cherry-pick https://github.com/apache/pulsar/pull/17704
*(or)*
*(or)*
*(example:)*

[cherry-pick][branch-2.10]wrong metrics text generated when label_cluster specified (#17704)

---

README.md

The Heroku app that was being used to automate the Slack invite of new users has stopped working since Heroku has terminated the free tier. 
I've added a new Slack app that does the email invite.

[fix] Change link to Slack workspace auto-invite

---

.gitignore
pulsar-client-cpp/python/pulsar/__init__.py
pulsar-client-cpp/python/pulsar_test.py
pulsar-client-cpp/python/src/config.cc
pulsar-client-cpp/python/src/utils.h

Cherry-pick  https://github.com/apache/pulsar/pull/16535 for release 2.10.3 and run tests. 
Cherry-pick  https://github.com/apache/pulsar/pull/16535.
*(or)*
*(or)*
*(example:)*

[cherry-pick] [branch-2.10] Better Python garbage collection management for C++-owned objects (#16535)

---

pulsar-io/kafka/pom.xml

Fixes #18920 
Only kafka-schema-registry-client has ASL license and the connector actually needs only it (and serializers, ASL too)
* import `kafka-schema-registry-client ` instead of `kafka-schema-registry`

[fix][io] Only bundle kafka schema registry client

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java

Fixes #xyz
When using pulsar-admin and encountering an exception, first check the body, then check the http text
* Update http response body check
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/AmateurEvents/pulsar/pull/31

[fix][client] Fix update response body text

---

grafana/dashboards/jvm.json

- source metric is not about GC pauses.
- the source metric is "jvm_gc_collection_seconds_sum" which is not the same as "GC pause"
- The metric is defined in Prometheus Java client
- "Time spent in a given JVM garbage collector in seconds."
- source code is https://github.com/prometheus/client_java/blob/e68daf23336eb5de7856df406eb1d497f51ad3be/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot/GarbageCollectorExports.java#L53
- calls GarbageCollectorMXBean.getCollectionTime() - Javadoc https://docs.oracle.com/en/java/javase/11/docs/api/java.management/java/lang/management/GarbageCollectorMXBean.html#getCollectionTime() "Returns the approximate accumulated collection elapsed time in milliseconds."
- Stackoverflow Q&A: https://stackoverflow.com/a/44686539
Replace "GC Pauses" …

[improve][monitor] Rename "GC Pauses" to "GC Time" in Pulsar JVM dashboards

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckHandle.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreProvider.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/PendingAckHandleDisabled.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/PendingAckHandleImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckPersistentTest.java

when `MLPendingAckStoreProvider` init PendingAckStore gets the ManagedLedger config throw exception, we don't handle the exception. and the `pendingAckStoreFeture` can't be complete, topic unload will use this future to close the pendingAck.
https://github.com/apache/pulsar/blob/3011946a5c3b64ed7c08b6bfb1f6492f8aaaca9c/pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreProvider.java#L114-L115
when getting managedledger config to fail, `pendingAckStoreFeture` will `completeExceptionally()`;
when pendingAckStore init fail, close pendingAckHandle success directly
mock get managedLeger config throw exception, then unload can success
https://github.com/congbobo184/pulsar/pull/12

[fix][txn] transaction pending ack store future not completely problem

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java

Fixes #15324
`internalDeleteSubscriptionForcefully ` and `internalDeleteSubscription` have duplicate code, and we should also avoid using synchronization methods like `getTopicReference()`.
-  Merge the duplicate code into `internalDeleteSubscription()`
Just cleanup

[cleanup][broker] Remove duplicate code to improve delete subscription

---

pom.xml
pulsar-io/debezium/core/pom.xml

Pulsar IO debezium sources depends on kafka (the whole server) but it only actually needs kafka-connect framework. 
* Removed kafka dependency from `debezium-core` and all the related dependencies (scala) 
Fork pull: https://github.com/nicoloboschi/pulsar/pull/42

[cleanup][io] Remove useless kafka server dep in debezium sources

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java

When the client wants to write a message within a transaction some checks are performed before the producer (on the broker side) starts writing it. 
In some cases, if the check fails, the error is correctly sent back to the client but the producer continues to write the message.
Those cases are:
- producer (on the broker) is closed (or being closed)
- checksum not valid
- encryption requirements not met
- shadow topics message format
* Block the producer if the checks do not pass. 

[fix][txn] producer may reject a message from client but actually writing it to the topic

---

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java
pulsar-io/docs/src/main/java/org/apache/pulsar/io/docs/ConnectorDocGenerator.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/PulsarZooKeeperClient.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java
pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/BrokerMonitor.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/CmdGenerateDocumentation.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationClient.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationController.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/ManagedLedgerWriter.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceBaseArguments.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java
pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceBaseArgumentsTest.java

Return code -1 is generally considered to be an invalid code. https://tldp.org/LDP/abs/html/exitcodes.html
Replace return code -1 with 1 which is commonly used as a general error.
Fixes #18945
There are a lot of cases in the pulsar cli tools where a `-1` is returned as the return code when there is an error executing the command.  This is generally considered an invalid return code and the code should be an integer between 0 and 255, with `1` commonly used as a general error code when specific error codes are not defined.  Because `-1` is invalid, running a pulsar command which fails will actually return a `255` because `255` is used to indicate that the return code is out of range.
Updated the CLI commands to return `1` instead of `-1` when there is an error.
This change is a trivial …

[improve][cli] pulsar cli: use return code 1 for general error

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java

Since PR #18833 can not cherry-pick to `branch-2.10`, create a separate PR.
- If turn on `transactionCoordinatorEnabled`,  then `TransactionBuffer` will be initialized when a user topic create.
- The `TransactionBuffer` reads the aborted logs of transactions from topic `__transaction_buffer_snapshot`  -- this process is called `recovery`.
- During recovery, the reading from that snapshot ledger is done via a `Reader`; the reader works like this:
```
while (reader.hasMessageAvailable()){
reader.readNext();
}
``` 
- After [pip-14](https://github.com/apache/pulsar/wiki/PIP-14:-Topic-compaction), the consumer that enabled feature read-compacted will read messages from the compacted topic instead of the original topic if the task-compaction is done, and read messages from the original topic if …

[fix] [tx] [branch-2.10] Transaction buffer recover blocked by readNext

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java

Since PR #18833 can not cherry-pick to `branch-2.9`, create a separate PR.
- If turn on `transactionCoordinatorEnabled`,  then `TransactionBuffer` will be initialized when a user topic create.
- The `TransactionBuffer` reads the aborted logs of transactions from topic `__transaction_buffer_snapshot`  -- this process is called `recovery`.
- During recovery, the reading from that snapshot ledger is done via a `Reader`; the reader works like this:
```
while (reader.hasMessageAvailable()){
reader.readNext();
}
``` 
- After [pip-14](https://github.com/apache/pulsar/wiki/PIP-14:-Topic-compaction), the consumer that enabled feature read-compacted will read messages from the compacted topic instead of the original topic if the task-compaction is done, and read messages from the original topic if …

[fix] [tx] [branch-2.9] Transaction buffer recover blocked by readNext

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java

Since PR #18833 can not cherry-pick to `branch-2.11`, create a separate PR.
- If turn on `transactionCoordinatorEnabled`,  then `TransactionBuffer` will be initialized when a user topic create.
- The `TransactionBuffer` reads the aborted logs of transactions from topic `__transaction_buffer_snapshot`  -- this process is called `recovery`.
- During recovery, the reading from that snapshot ledger is done via a `Reader`; the reader works like this:
```
while (reader.hasMessageAvailable()){
reader.readNext();
}
``` 
- After [pip-14](https://github.com/apache/pulsar/wiki/PIP-14:-Topic-compaction), the consumer that enabled feature read-compacted will read messages from the compacted topic instead of the original topic if the task-compaction is done, and read messages from the original topic if …

[fix] [tx] [branch-2.11] Transaction buffer recover blocked by readNext

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/ExceptionHandler.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/BrokerInterceptorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/CounterBrokerInterceptor.java

Fixes #xyz
The pulsar-admin client does not correctly handle error messages from the interceptor response. The interceptor response is a string, but the client tries to parse it as an errorData object
https://github.com/apache/pulsar/blob/master/pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BaseResource.java#L323
Update the response to a json object, update the response to a json object, which shouldn't cause a breaking change. The client will get the error message from the previous `reason-content` to `"{"reason": "reason-content"}"`
*(or)* …

[fix][broker]Update interceptor handler exception

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java

fix multi invocation for ledger `createComplete`
Only call `createComplete` at the point of creating ledger timeout if the ledger is not created normally
This change is a trivial rework without any test coverage.
PR in forked repository: [https://github.com/aloyszhang/pulsar/pull/8]

[fix][broker]fix multi invocation for ledger createComplete

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ConsumerRedeliveryTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ZeroQueueConsumerImpl.java

Fixes https://github.com/apache/pulsar/issues/18910
The root cause is that:
1. When msg0 is processing in the pulsar-external-listener thread,  the `MultiTopicsConsumerImpl` will also poll other messages like msg1, msg2 from the `ConsumerBase#incomingMessages`(Line383). Then msg1, msg2 will be added to the `unAckedMessageTracker`(Line387). Note that msg1, msg2 timeout task starts at this point.
https://github.com/apache/pulsar/blob/01e7eacd34f01a88d201c70329ecacfa581db1a8/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L377-L390
2. All the polled messages will be submitted to the pulsar-external-listener thread pool to process the messages.  As we know, if there was no available threads,  the tasks will be waited in the blocking queue of the thread …

[fix][client] Fix too many redelivered messages when one message acked timeout in listener

---

.github/PULL_REQUEST_TEMPLATE.md
wiki/proposals/PIP.md

Update PR template and PIP for metrics changes according to the [discussion](https://lists.apache.org/thread/bmwtk6zcyt4ft4t95jmz1bnsxbysjw8m) under the mailing list
- Add PIP link option to PR template
- Add metrics change to the checklist of the PR template
- Update PIP.md for requiring PIP for metrics changes

[improve][doc] Update PR template and PIP for metrics changes

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/GetLastMessageIdCompactedTest.java

The method `consumer.getLastMessageId` will return the latest message which can be received.
- If disabled `read compacted`, will return the last confirmed position of `ManagedLedger`.
- If enabled `read compacted`, will return the latest message id which can be read from the compacted topic.
If we send a batch message like this:
```java
producer.newMessage().key("k1").value("v0").sendAsync(); // message-id is [3:1,-1:0]
producer.newMessage().key("k1").value("v1").sendAsync(); // message-id is [3:1,-1:1]
producer.newMessage().key("k1").value("v2").sendAsync(); // message-id is [3:1,-1:2]
producer.newMessage().key("k2").value("v0").sendAsync(); // message-id is [3:1,-1:3]
producer.newMessage().key("k2").value("v1").sendAsync(); // message-id is [3:1,-1:4] …
```

[fix] [broker] getLastMessageId returns a wrong batch index of last message if enabled read compacted

---

buildtools/pom.xml
pom.xml

There are 1 security vulnerabilities found in org.testng:testng 7.6.1
- [CVE-2022-4065](https://www.oscs1024.com/hd/CVE-2022-4065)
Upgrade org.testng:testng from 7.6.1 to  for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
Signed-off-by:pen4<948453219@qq.com>

[fix][sec]: upgrade org.testng:testng to 7.7.0

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/PendingAckHandleImpl.java

Fixes #18988
Based on stacktrace in the issue, in `PendingAckHandleImpl`, if the first time `pendingAckHandleCompletableFuture` is completed via the method `addConsumer` the `PendingAckHandleImpl` object is locked to the current thread because the method `completeHandleFuture` is synchronized. The `addConsumer` then locks the `PersistentSubscription`. In the reverse order the subscription closing procedure locks the `PersistentSubscription` object and then `PendingAckHandleImpl`. 
It's possible that if they run concurrently it ends up in a deadlock 
* Remove synchronized from `completeHandleFuture` methods. In this way the `PendingAckHandleImpl` object isn't locked in the stages chain.
* Moved the init callback to use the internal executor instead of the metadata store executor
I haven't …

[fix][broker] Fix deadlock in PendingAckHandleImpl

---

pulsar-functions/instance/pom.xml
pulsar-io/common/pom.xml
pulsar-io/common/src/main/java/org/apache/pulsar/io/common/IOConfigUtils.java
pulsar-io/nsq/pom.xml

`pulsar-io-common` is a module published as convenience for java connectors to help with loading configuration. 
When a connectors declares it, it brings also `pulsar-common` which contains a lot of other transitive dependencies. (for example, Netty)
We can remove all the non necessary dependencies since it's trivial to replace their usage in the `pulsar-io-common` module. 
* Removed `pulsar-common` and `commons-lang` dependecies and replaced with vanilla methods 100% compatible
* Improve usage of the underlyng ObjectMapper used for read the config

[improve][io] reduce dependencies of pulsar-io-common module

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarHandler.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyClientCnx.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java

The lifecycle of the PulsarDecoder handle* method parameters isn't currently documented.
This PR adds this kind of paragraph:
>  Please be aware that the decoded protocol command instance passed to a handle* method is cleared and reused for the next protocol command after the method completes. This is done in order to minimize object allocations for performance reasons. <b>It is not allowed to retain a reference to the handle* method parameter command instance after the method returns.</b> If you need to pass an instance of the command instance to another thread or retain a reference to it after the handle* method completes, you must make a deep copy of the command instance.
See #18987 or #10215 for a sample issues where a related problem was fixed.
Add Javadoc to PulsarDecoder and …

[improve][broker] Add javadoc for PulsarDecoder handle* method parameter lifecycle

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/PortForwarder.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/PulsarMultiListenersWithInternalListenerNameTest.java

Fixes #19005
See #19005
Change free port allocation so that both ports are detected at once. Use SO_REUSEADDR socket option for PortForwarder.

[fix][test] Fix flaky test PulsarMultiListenersWithoutInternalListenerNameTest.setup

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/BrokerInterceptor.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/BrokerInterceptors.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PreInterceptFilter.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageCumulativeAckTest.java

While fixing a bug, #18987 introduces a performance regression to handleAck method. The copy of the CommandAck instance should only be done if there's a broker interceptor in use.
- Use a null value to indicate that the broker interceptor is missing
- Make changes to handle the null broker interceptor
- Omit making a copy of CommandAck in handleAck method when there are no broker interceptors
PR in forked repository: https://github.com/lhotari/pulsar/pull/114

[improve][broker] Omit making a copy of CommandAck when there are no broker interceptors

---

pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java

Fixes #18927 
There's a direct memory leak in RawReaderImpl, please see #18927 for details.
Override methods org.apache.pulsar.client.impl.ConsumerBase#failPendingReceive and org.apache.pulsar.client.impl.ConsumerBase#clearIncomingMessages in org.apache.pulsar.client.impl.RawReaderImpl.RawConsumerImpl so that cleanup happens properly. Don't create RawMessageImpl instances in messageReceived method if consumer is already closing or closed.
The changes should prevent future direct memory leaks caused by seeks or when the consumer is already closed.
PR in forked repository: https://github.com/lhotari/pulsar/pull/113

[fix][broker] Fix direct memory leak in RawReaderImpl

---

build/run_unit_group.sh
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderBase.java

BlobStoreManagedLedgerOffloader* tests run out of memory and stall the "other" test run.
- fix excludes
- run both BlobStoreManagedLedgerOffloaderTest and BlobStoreManagedLedgerOffloaderStreamingTest separately
- clear the mocked bookkeeper between test methods
PR in forked repository: https://github.com/lhotari/pulsar/pull/116

[fix][test] Run BlobStoreManagedLedgerOffloader* tests separately and reduce memory consumption

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java

- currentLedgerEntries and currentLedgerSize fields in the ManagedLedgerImpl class are currently mutated and read from multiple threads which is a problem.
- one solution is to make the fields volatile
- make fields volatile
PR in forked repository: https://github.com/lhotari/pulsar/pull/93

[fix][broker] Fix thread-safety issue with currentLedgerEntries and currentLedgerSize fields

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/BundleSplitterTask.java

Add logs for why the namespace bundle been split.
With the details logs. Users can tune the load manager options to improve the bundle split.
```
18:28:07.197 [pulsar-modular-load-manager-31-1] INFO  org.apache.pulsar.broker.loadbalance.BundleSplitStrategy - The bundle public/default/0x50000000_0x60000000 is considered to be unload. Topics: 10/1000, Sessions: (10+0)/1000, Message Rate: 49976.285872448774/30000 (msgs/s), Message Throughput: 0.5233347144619912/100 (MB/s)
18:28:07.218 [pulsar-modular-load-manager-31-1] INFO  org.apache.pulsar.broker.loadbalance.BundleSplitStrategy - The bundle public/default/0xd0000000_0xe0000000 is considered to be unload. Topics: 9/1000, Sessions: (8+3)/1000, Message Rate: 39837.6273878898/30000 (msgs/s), Message Throughput: 0.41714825665545885/100 (MB/s) …
```

[improve][broker] Add logs for why namespace bundle been split

---

pulsar-broker/pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/client/impl/CompactionReaderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchMessageContainerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/Compactor.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/StrategicTwoPhaseCompactor.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/CompactionReaderImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerMemoryLimitTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawBatchMessageContainerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TableViewTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionRetentionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/NumericOrderCompactionStrategy.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/StrategicCompactionRetentionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/StrategicCompactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/StrategicCompactorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/TopicCompactionStrategyTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/TableView.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewConfigurationData.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ReaderConfigurationData.java
pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicCompactionStrategy.java

Master Issue: https://github.com/apache/pulsar/issues/18099
This PR supports `TopicCompactionStrategy` in `StrategicTwoPhaseCompactor` and `TableView` for the internal system topics, as proposed in PIP-215.
This PR does not expose StrategicTwoPhaseCompactor for customer topics yet. We want to expose this feature to users after proven to be stable on the new system topic in the new broker load balancer(in PIP-192) first.
This PR adds the following classes to implement `StrategicTwoPhaseCompactor. 
- Added `StrategicTwoPhaseCompactor` that extends `TwoPhaseCompactor`.
- Added `TopicCompactionStrategy` interface.
- Added `TopicCompactionStrategy` logic in `StrategicTwoPhaseCompactor` and `TableViewImpl`.
- Added `CompactionReaderImpl` to scan topic messages in StrategicTwoPhaseCompactor. It …

[improve][broker][client] PIP-215 Added TopicCompactionStrategy for StrategicTwoPhaseCompactor and TableView.

---

pom.xml
pulsar-io/jdbc/clickhouse/pom.xml

This closes #12998.
May or may not we add some docs on this feature. I'm not sure.

[feat][io] Upgarde ClickHouse driver to support loadbalance policy

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

`validateTopicOwnershipAsync`  is called twice both in `internalDeleteSubscriptionAsync`  and `internalDeleteSubscriptionForNonPartitionedTopicAsync ` method.
Remove repeating validateTopicOwnershipAsync action.
*(or)*
*(or)*
*(example:)*
https://github.com/gaozhangmin/pulsar/pull/4

[improve][admin]Remove repeating validateTopicOwnershipAsync action

---

pom.xml
pulsar-io/kafka/pom.xml
tests/integration/pom.xml
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KafkaSinkTester.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/AvroKafkaSourceTest.java

There are multiple Confluent platform versions in use at the moment. 
There's now references to both version 7.0.1 and version 5.3.0 (from July 2019) and this doesn't make much sense.
The Confluent platform version should be compatible with the Kafka client and Kafka connect runtime versions.
Confluent 6.2.x is compatible with Kafka client 2.8.2 . ([release notes of Confluent 6.2.8](https://docs.confluent.io/platform/6.2.8/release-notes/index.html))
- Upgrade Kafka client and Kafka connect runtime to 2.8.2
- Upgrade Confluent version to 6.2.8
PR in forked repository: https://github.com/lhotari/pulsar/pull/117

[improve][io] Upgrade Kafka client, connect runtime to 2.8.2 and Confluent version to 6.2.8

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java

The `validateTopicOperationAsync` method should be used in all cases.
- replace usage of `validateTopicOperation` with `validateTopicOperationAsync` in remaining code locations
- remove the unused `validateTopicOperation` methods
PR in forked repository: https://github.com/lhotari/pulsar/pull/118

[improve][broker] Use validateTopicOperationAsync methods in all cases

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/Bucket.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/ImmutableBucket.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/BucketDelayedDeliveryTrackerTest.java

Master Issue: #16763
#16763
Implement delayed message index bucket snapshot recover
PR in forked repository:  https://github.com/coderzc/pulsar/pull/30

[feat][broker][PIP-195] Implement delayed message bucket snapshot recover - part5

---

pulsar-common/src/main/java/org/apache/pulsar/common/exception/PulsarExceptionBase.java
pulsar-common/src/main/java/org/apache/pulsar/common/exception/package-info.java
pulsar-common/src/test/java/org/apache/pulsar/exception/PulsarExceptionSample.java
pulsar-common/src/test/java/org/apache/pulsar/exception/PulsarExceptionTest.java

We frequently have to pass strings to exceptions, similar to log4j , this allows us to use the same parameterized formatting in both.

[improve] Add PulsarExceptionBase class that supports slf4j like parameterized string formatting

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java

Builds on https://github.com/apache/pulsar/pull/18997. Essentially, we shouldn't get the consumer future when there isn't a broker interceptor.
* Move the conditional check for `brokerInterceptor != null` earlier to prevent unnecessary work.
This is a trivial change.

[improve][broker] Only get consumer future when interceptor not null

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java

(cherry picked from commit a594ca71554a5de0e28564d54da6ffc49202206e)
Update response class for rest api
Fixes #xyz
The rest api was changed from snyc to async, and all responses became void, which caused the swagger file to not generate the correct response object, the purpose of this pr is to generate the correct response object for the swagger file, which is useful for generating client code automatically using code
*(or)*
*(or)*
*(example:)* …

[fix][broker]Update rest api response class

---

.asf.yaml

We create PRs for the release branches once conflicts are not easy to handle when cherry-picking PRs.
Using a PR to resolve the conflicts and get more eyes on the changes to the release branches to reduce the risks that are introduced to the release branches.
But the approvals are not enforced for the release branches when merging PRs so that the committer can merge the PR without any approvals to the release branch.

Update .asf.yaml to avoid merge PRs without approvals to the active release branches

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

- the resulting map isn't thread safe in PartitionedManagedLedgerInfo and it's possible that the results get corrupted.
- it's better to refactor the logic to compose the results after the futures have completed
PR in forked repository: https://github.com/lhotari/pulsar/pull/119

[fix][broker] Fix thread safety issue in info-internal admin api for partitioned topics

---

.asf.yaml

See: https://github.com/apache/pulsar/pull/19024#issuecomment-1363480874
Revert #19024

Revert "Update .asf.yaml to avoid merge PRs without approvals to the active release branches (#19024)

---

pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/DebeziumSource.java
pulsar-io/debezium/mongodb/src/main/java/org/apache/pulsar/io/debezium/mongodb/DebeziumMongoDbSource.java

Currently the Debezium sources don't support loading sensitive configuration from secrets. 
Most sources can rely on `IOConfigUtils.loadWithSecrets` because they provide a specific Config class with `FieldDoc` annotations. The Debezium sources work differently because there is no specific Config class but rather just a Map with some basic validation that is passed to Debezium. Therefore we need to directly get the secrets from the `sourceContext`.
Most of the Debezium sources rely on the same config properties (`database.user`, `database.password`) to configure the connector so I decided to move the secret-handling code into the abstract `DebeziumSource` class that all the individual connectors inherit from. There are exceptions to this, such as the MongoDB source, which uses another set …

[improve][io] Debezium sources: Support loading config from secrets

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java

Check `topicsPattern` is not null or empty when invoking `ConsumerBuilder.topicsPattern`. 
```java
ConsumerBuilder<T> topicsPattern(String topicsPattern);
ConsumerBuilder<T> topicsPattern(Pattern topicsPattern);
```
**case 1:** String topicsPattern is `null`
```
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.pattern" is null
```
**case 2:** String topicsPattern is `empty` or Pattern topicsPattern  regex is `empty`
```
java.lang.IllegalArgumentException: Invalid short topic name '', it should be in the format of <tenant>/<namespace>/<topic> or <topic>
```
Check `topicsPattern` is not null or empty when invoking `ConsumerBuilder.topicsPattern`. 

[improve][client] Check topic pattern when creating consumer

---

.asf.yaml

Mailing list thread: https://lists.apache.org/thread/ny8cz9fj4lwk752m4nylpzdg35lwfn6v
When we first introduced GitHub discussions, we had their notifications go to the dev@ list. That has produced many notifications, and can create duplicate notifications for anyone following the GitHub repo itself.
I propose that we move these notifications to the commits@ list, which is also where we send all other GitHub notifications.
Note that discussions are primarily intended for users to ask questions. Users are free to propose new features/designs, but those proposals should ultimately be directed to the dev list for relevant discussions.

[improve][misc] Send GitHub discussion notifications to commits@

---

pulsar-sql/presto-distribution/LICENSE

Branch 2.11 doesn't bring the correct LICENSE file for Pulsar SQL. 
>➜  pulsar2 git:(v2.11.0-candidate-3) ./src/check-binary-license.sh distribution/server/target/apache-pulsar-2.11.0-bin.tar.gz
failsafe-2.4.4.jar unaccounted for in lib/presto/LICENSE
jersey-entity-filtering-2.34.jar unaccounted for in lib/presto/LICENSE
jersey-media-json-jackson-2.34.jar unaccounted for in lib/presto/LICENSE
jersey-media-multipart-2.34.jar unaccounted for in lib/presto/LICENSE
listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar unaccounted for in lib/presto/LICENSE
netty-transport-native-epoll-4.1.86.Final.jar mentioned in lib/presto/LICENSE, but not bundled
It looks like there are issues with the LICENSE/NOTICE.
* Fix the Pulsar SQL License file
Run ./src/check-binary-license.sh

[fix][build] Fix license issue in 2.11

---

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarServiceNameResolver.java

A call to java.net.InetSocketAddress#getHostName will trigger a reverse DNS lookup when the physical address is an IP address. This is not desired since the DNS resolver will be blocking execution.
Use java.net.InetSocketAddress#getHostString to use the address passed as input (host string or ip address).
PR in forked repository: https://github.com/lhotari/pulsar/pull/120

[fix][client] Prevent DNS reverse lookup when physical address is an IP address

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/BacklogQuota.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/impl/BacklogQuotaImpl.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BacklogQuotaCompatibilityTest.java

limitTime It's a confusing name, without the time unit, it is easy to cause bugs,
so we should deprecate the old name limitTime and introduce a new one limitTimeInSec
change name limitTime to limitTimeInSec
PR in forked repository: https://github.com/StevenLuMT/pulsar/pull/1

[fix][broker] change name limitTime to limitTimeInSec

---

pulsar-broker/pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopicsExt.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

This fixes #18947. As a workaround.
It's not a regression because we cannot doc both endpoint right now.

[fix][doc] Stablize swagger docs

---

site2/docs/admin-api-topics.md
site2/website/versioned_docs/version-2.10.x/admin-api-topics.md
site2/website/versioned_docs/version-2.8.x/admin-api-topics.md
site2/website/versioned_docs/version-2.9.x/admin-api-topics.md

Fixes #xyz
PIP: #xyz 
https://pulsar.apache.org/docs/2.10.x/admin-api-topics/#manage-non-partitioned-topics missed the `stats-internal` API introduction.
https://pulsar.apache.org/docs/2.10.x/admin-api-topics/#internal-stats used the wrong `stats-internal` API, the current API is for the non-partition topic rather than for the partitioned topic. 
Fix the above issues in this document. 
PR preview build:
*(or)*
*(or)*
*(example:)*
- …

[fix][doc] miss stats-internal for non-partition topic and wrong API for paritioned topic stats-internal

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStoreException.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/LockManagerImpl.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/EtcdMetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/LocalMemoryMetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/RocksdbMetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java

After the metadata store is closed, the metadata store will fail all the pending requests, but the new request will be blocked forever for the batched-supported metadata store.
The root cause is we are using a separate thread to flush the requests to the metadata services. The thread will be shutdown after the metadata store has been closed. But the new requests can still add to the pending requests and will never be complete.
So this PR is to prevent the new request to a closed metadata store. The caller will get `AlreadyClosedException` if the requested metadata store is closed 
It will also fix some flaky tests that stuck at the broker shutdown. Here is an example
```
2022-12-20T11:45:12.6521329Z "main" #1 prio=5 os_prio=0 cpu=134299.52ms elapsed=3504.19s tid=0x00007fa37c02ab80 …
```

[fix][broker] Throw AlreadyClosedException while request to a closed metadata store

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java

The SimpleProducerConsumerTest is the very common test for the Pulsar APIs. But it is under the flaky test group, the PR can be merged without this test getting passed. Since we have fixed many flaky tests in the last 3 months. I have run the test on my laptop multiple times. Looks like it works stable for now.
So move the test out of the flaky test group. And it also give us a chance to fix the flaky test in SimpleProducerConsumerTest if there are some tests still flaky.

[improve][test] Move the SimpleProducerConsumerTest out of the flaky test group

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TableViewTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/TableViewBuilder.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewBuilderImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewConfigurationData.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/TableViewBuilderImplTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/TableViewImplTest.java

Fixes #19007
This PR adds support for a `TableView` to read encrypted messages from a topic.
Analogous to `ReaderBuilder`, I've added methods to `TableViewBuilder` that allow to specify a `CryptoKeyReader` and a `ConsumerCryptoFailureAction`. The respective values are stored in `TableViewConfigurationData` and forwarded to the `ReaderBuilder` instance inside `TableViewImpl` when the `Reader` is constructed.
- Added unit tests for `TableViewImpl` and `TableViewBuilderImpl`
- Extended integration test verifying that encrypted messages can be read inside a `TableView`
[PR in forked repository](https://github.com/rbarbey/pulsar/pull/1)

[fix][client] add support to TableView to read encrypted messages

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyServiceStarterTest.java

Fixes: #19011 
Related issue https://github.com/apache/pulsar/issues/19011.
Most of the tests are all based on the class `TestRetrySupport`, which supports resetting the broken test environments, the `ProxyServiceStarter` will register metrics in the default collector registry if we restart the `ProxyServiceStarter`, it will throw the exception like this.
```
java.lang.IllegalArgumentException: Failed to register Collector of type Gauge: jvm_memory_direct_bytes_used is already in use by another Collector of type Gauge
```
Clean up the default collector registry when closing the `ProxyServiceStarter`.
PR in forked repository: https://github.com/gaoran10/pulsar/pull/20

[fix][proxy] Cleanup default collector registry when closing the ProxyServiceStarter

---

pulsar-broker/pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/ExtNonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/ExtPersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

This is a follow-up to #19025. That the swagger plugin is matching by prefix so we have to distinguish the class name in prefix.
Also add back the inherit logic for `NonPersistentTopics` and fix a bug inline.

[fix][client] ExtNonPersistentTopics and prevent prefix match

---

pom.xml

Woodstox 5.3.0 is vulnerable to [CVE-2022-40152](http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2022-40152)
Woodstox core is used in the file system offloader
* Upgrade from 5.3.0 to 5.4.0

[fix][sec] Upgrade woodstox to 5.4.0

---

pom.xml
pulsar-io/hdfs2/pom.xml
pulsar-io/hdfs3/pom.xml

Currently, Hadoop versions for pulsar-io-hdfs2 and hdfs3 is hard-coded in their pom.xml, but it's not so convenient for users who want to build Pulsar against specific version of Hadoop.
This PR defines those versions as Maven properties just like other Pulsar IO modules so that users can easily override them with Maven's `-D` option at compile time.
https://github.com/sekikn/incubator-pulsar/actions/runs/3779316356
There are some failures but all of them seem to be unrelated with this change.
This change is already covered by existing tests, such as unit tests for pulsar-io-hdfs2 and pulsar-io-hdfs3.
PR in forked repository: https://github.com/sekikn/incubator-pulsar/pull/2

[improve][io] Parameterize hadoop version for hdfs2 and hdfs3

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

Fix missing `return null` if throw any exception when `internalGetReplicatedSubscriptionStatus`
Add `return null` when handing exception in `internalGetReplicatedSubscriptionStatus`.
PR in forked repository: https://github.com/hqebupt/pulsar/pull/7

[fix][broker]fix missing return when internalGetReplicatedSubscriptionStatus

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/BaseResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java

This is only a POC, opened for discussion
When a operation is redirected to another broker, it may happen that the local view over metadata on the other broker is not up-to-date with the view seen by the initial broker.
In order to guarantee casual consistency among different peers you have to ways using the ZooKeeper APIs:
- perform a write
- use the sync() API
Both of the two operations force (or wait for) the ZooKeeper server to which the client is connected to be in sync with the Leader ZooKeeper server and also that the local ZooKeeper client is up-to-date.
See more at https://zookeeper.apache.org/doc/r3.8.0/zookeeperProgrammers.html at the "Consistency Guarantees" paragraph.
When the control passes from one broker to another broker the second broker needs to ensure that its local …

[improve] Introduce the sync() API to ensure consistency on reads during critical metadata operation paths

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/resources/findbugsExclude.xml

* This supersedes #11550.
* This closes #11474.
Add a new test `testAutoConsumeSchemaRetryLetter`.

[fix][client] retry letter producer respect auto schema

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/conf/ConfigurationDataUtilsTest.java

I noticed the Java Client (I haven't checked other clients) uses 1 IO thread and 1 listener thread by default. It will require users to update the thread configuration if they have multiple cores and desired high throughput.  Here is the example that we change to 16 IO threads in openmessaging benchmark 
https://github.com/openmessaging/benchmark/blob/master/driver-pulsar/pulsar.yaml#L22 
We can apply the configuration of the threads based on the CPU cores. So that for the most common cases, users don't need to touch the thread configuration.  
``` 
private int numIoThreads = Runtime.getRuntime().availableProcessors(); private int numListenerThreads = Runtime.getRuntime().availableProcessors(); 
```
discussion under the mailing list …

[improve][client] Change default threads from 1 to available processors

---

pulsar-io/hdfs2/src/main/java/org/apache/pulsar/io/hdfs2/Compression.java
pulsar-io/hdfs2/src/test/java/org/apache/pulsar/io/hdfs2/sink/seq/HdfsSequentialSinkTests.java
pulsar-io/hdfs2/src/test/java/org/apache/pulsar/io/hdfs2/sink/seq/HdfsTextSinkTests.java
pulsar-io/hdfs2/src/test/java/org/apache/pulsar/io/hdfs2/sink/text/HdfsStringSinkTests.java
pulsar-io/hdfs3/src/main/java/org/apache/pulsar/io/hdfs3/Compression.java
pulsar-io/hdfs3/src/test/java/org/apache/pulsar/io/hdfs3/sink/seq/HdfsSequentialSinkTests.java
pulsar-io/hdfs3/src/test/java/org/apache/pulsar/io/hdfs3/sink/seq/HdfsTextSinkTests.java
pulsar-io/hdfs3/src/test/java/org/apache/pulsar/io/hdfs3/sink/text/HdfsStringSinkTests.java
site2/docs/io-hdfs2-sink.md
site2/docs/io-hdfs3-sink.md

Recent versions of Hadoop support zstd compression, but it's not enabled in the hdfs2 and hdfs3 pulsar-io, so I'd like to activate it.
Added an enum definition and some unit tests.
I ran the CI on my own GitHub account and it was successful except for the unit tests for broker group 2. I think that failure is irrelevant to this fix.
https://github.com/sekikn/incubator-pulsar/actions/runs/3774398563
```
$ LD_LIBRARY_PATH=$HADOOP_HOME/lib/native ./mvnw test -f pulsar-io/hdfs2/pom.xml
$ LD_LIBRARY_PATH=$HADOOP_HOME/lib/native ./mvnw test -f pulsar-io/hdfs3/pom.xml
```
Zstd compression depends on Hadoop's native libraries, so LD_LIBRARY_PATH should be set for running them. If not, the newly added tests are simply skipped. …

[improve][io] Add zstd support to hdfs2 and hdfs3

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaTest.java
pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java

Fixes [#18825](https://github.com/apache/pulsar/issues/18825)
Admin API can upload `BYTES` schema and store a `NONE` schema in the schema registry, which is inconsistent with the client side. After discussion, we decided to forbid users from uploading `BYTES` schema.
Mail list: https://lists.apache.org/thread/672zmptfblwjmrf9z8336mk12r7csngf
Add a check to reject `BYTES` schema upload.
PR in forked repository: https://github.com/labuladong/pulsar/pull/17

[fix][broker] forbid uploading BYTES schema with admin API

---

distribution/io/src/assemble/io.xml
pulsar-io/alluxio/pom.xml
pulsar-io/alluxio/src/main/java/org/apache/pulsar/io/alluxio/AlluxioAbstractConfig.java
pulsar-io/alluxio/src/main/java/org/apache/pulsar/io/alluxio/package-info.java
pulsar-io/alluxio/src/main/java/org/apache/pulsar/io/alluxio/sink/AlluxioSink.java
pulsar-io/alluxio/src/main/java/org/apache/pulsar/io/alluxio/sink/AlluxioSinkConfig.java
pulsar-io/alluxio/src/main/java/org/apache/pulsar/io/alluxio/sink/package-info.java
pulsar-io/docs/pom.xml
pulsar-io/pom.xml
site2/docs/io-connectors.md

Currently, the alluxio submodule is not included in the Pulsar IO distribution.
```
$ ./mvnw clean install -DskipTests
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12:09 min
[INFO] Finished at: 2022-12-27T11:14:55+09:00
[INFO] ------------------------------------------------------------------------
$ ls -l distribution/io/target/apache-pulsar-io-connectors-2.12.0-SNAPSHOT-bin
total 1721216
-rw-r--r-- 1 sekikn sekikn     13300 12月 27 11:02 LICENSE
-rw-rw-r-- 1 sekikn sekikn   8352752 12月 27 11:02 pulsar-io-aerospike-2.12.0-SNAPSHOT.nar
-rw-rw-r-- 1 sekikn sekikn  15910726 12月 27 11:02 …
```

[fix][io] Include Alluxio in the distribution

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java

- Fix bug: If the input paramter `position` is greater than the greatest ledgerId in `ManagedLedgerImpl#ledgers`,  the `estimateBacklogFromPosition` should return 0,  instead of `getTotalSize()`
- Improve: Using `java.util.NavigableMap#tailMap(K)` to calculate the `size`, which will avoid traversal the whole `ManagedLedgerImpl#ledgers`
- Add ut `ManagedLedgerTest#testGetEstimatedBacklogSize` to test this change
PR in forked repository:  https://github.com/AnonHxy/pulsar/pull/24

[fix][broker] Fix estimateBacklogFromPosition if position is greater than the greatest ledgerId 

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java

`pulsar-admin sources list` has the wrong parameters description.
Should be `pulsar-admin sources list --namespace <The source's namespace> --tenant <The source's tenant>`

[fix][cli] Fix wrong description of pulsar-admin flags

---

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SinkConfigUtilsTest.java

Fixes #18507 
When a user updates inputSpect of a sink by providing both `--inputs` and `--input-specs`, exiting `consumerConfig` will be wiped out.
On the `validateUpdate` code path, there is a logic that populates the `inputSpecs` inside the `newConfig` to empty `consumerConfig`. This will overwrite the existing specs when later on the methods attempts a merge and will also merge in the hard coded consumer configs ignoring any new values the user might've provided. By only setting the consumerConfig to a default value if such config didn't exit, the behavior is similar to what would happen if the user did the update, without providing the `--inputs` specs (which is, newConfig consumer config will overwrite exiting ones.
- Added new …

[fix][admin] Keep new inputSpecs when updating sink configs

---

pom.xml

Jettison 1.5.1 is vulnerable to [CVE-2022-40150](https://nvd.nist.gov/vuln/detail/CVE-2022-40150), [CVE-2022-45685](https://nvd.nist.gov/vuln/detail/CVE-2022-45685) and [CVE-2022-45693](https://nvd.nist.gov/vuln/detail/CVE-2022-45693)
Jettison is a transitive dependency of hadoop, used in the file storage offloader. 
Upgrade from 1.5.1. to 1.5.3

[fix][sec] Upgrade jettison to 1.5.3

---

src/owasp-dependency-check-false-positives.xml

OWASP Dependency Check is failing with some false positives:
```
One or more dependencies were identified with known vulnerabilities in Pulsar :: Distribution :: Server:
commons-cli-1.5.0.jar (pkg:maven/commons-cli/commons-cli@1.5.0, cpe:2.3:a:apache:commons_net:1.5.0:*:*:*:*:*:*:*) : CVE-2021-37533
commons-codec-1.15.jar (pkg:maven/commons-codec/commons-codec@1.15, cpe:2.3:a:apache:commons_net:1.15:*:*:*:*:*:*:*) : CVE-2021-37533
commons-compress-1.21.jar (pkg:maven/org.apache.commons/commons-compress@1.21, cpe:2.3:a:apache:commons_compress:1.21:*:*:*:*:*:*:*, cpe:2.3:a:apache:commons_net:1.21:*:*:*:*:*:*:*) : CVE-2021-37533
commons-configuration-1.10.jar (pkg:maven/commons-configuration/commons-configuration@1.10, cpe:2.3:a:apache:commons_configuration:1.10:*:*:*:*:*:*:*, …
```

[fix][build] Resolve OWASP Dependency Check false positives

---

pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/ClusterDataImpl.java
pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/ClusterDataImplTest.java

In #17962, new configurations were added to the `ClusterDataImpl` without updating the `clone` method. In https://github.com/apache/pulsar/pull/17295, new configurations were incorrectly cloned. None of these "bugs" are in a released version of pulsar.
This PR fixes those issues and adds a test to verify the fixes. One gap on the test is that it won't easily test new fields unless the test is updated. I would guess we need smarter tests to make that work. I'm not aware of any solutions, but if someone has pointers, please let me know.
* Fix `ClusterDataImpl#clone`
A new test is added to cover the changes.
This is an internal change.
PR in forked repository: https://github.com/michaeljmarshall/pulsar/pull/10

[cleanup][broker] Fix ClusterDataImpl#clone and add test

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

PIP: #16763
In #19035, the `skipCondition` parameter returns need to skip entry when reading entry, but the logic now is reversed.
Fix skip logic and add test to cover it.
*testReadEntriesWithSkip*

[fix][broker][PIP-195] fix cursor skip read

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/FaultInjectionMetadataStore.java

There's blind spot in the topic deletion where, if an exception occurs during the partitioned metadata update, the topic ends in a fenced state and it can't be deleted or used. With a broker restarts, the topic is deletable again. However the topic might be in an inconsistent state.
* Removed fenced flag in the topic if an error occurs during the partition metadata update
* Add unit test
* (tests) Fix `FaultInjectionMetadataStore` to be usable also from the MetadataCache methods

[fix][broker] Topic could be in fenced state forever if deletion fails

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/SchemasResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java

We have the INFO log to show the schema not found, or the topic is found.
The error logs for the not found exception are just making noise.
```
2023-01-04T20:33:26,341 - INFO  - [metadata-store-12-1:Slf4jRequestLogWriter@62] - 127.0.0.1 - - [04/Jan/2023:20:33:26 +0800] "GET /admin/v2/schemas/public/default/test111/schema HTTP/1.1" 404 29 "-" "Pulsar-Java-v2.12.0-SNAPSHOT" 118
```

[improve][schema] Do not print error log with stacktrace for 404

---

.github/actions/ssh-access/action.yml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

The ssh access setup step that is part of Pulsar CI can fail in builds that are run in forks. The ssh access feature is active in CI builds run in forks to allow connecting to the running build with ssh for debugging purposes.
This is the ssh access setup step:
https://github.com/apache/pulsar/blob/master/.github/workflows/pulsar-ci.yaml#L88-L93
Sometime this fails with an error message "flag needs an argument: --admin-socket". Example of failure:
https://github.com/michaeljmarshall/pulsar/actions/runs/3833202322/jobs/6527659487#step:4:150
- wait up to 10 seconds for admin socket to appear
- add "continue-on-error: true" to ssh setup step so that errors don't prevent the build from continuing
PR in forked repository: https://github.com/lhotari/pulsar/pull/122

[improve][ci] Improve CI ssh access in forks, don't fail build if setting up ssh access fails

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/BacklogQuota.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/impl/BacklogQuotaImpl.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BacklogQuotaCompatibilityTest.java

This reverts commit fd5037ddeab4746202539509818f2b7977698537.
As described in https://github.com/apache/pulsar/pull/19053#pullrequestreview-1234929550, the commit to be reverted introduced a breaking change in a non-backwards compatible way. This is especially important because the datastructure in question is used for ser/de of zk metadata.  Instead of making one-off changes to variable names, I would prefer to first establish a standard/spec, and then apply it generally to all names. Pulsar certainly has room to improve names, but we must prioritize the user experience when changing these names. We also need to make sure that we cover upgrade and downgrade scenarios so that we do not break environments.
* Revert #19053.
This should be trivial.
This reverts a breaking change.
I'll send …

[revert] "[fix][broker] change name limitTime to limitTimeInSec (#19053)"

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

fix #19131 
fix TTL expiration block due to no-recoverable exception even if autoSkipNonRecoverableData=true
In the logic of message expiration, if met `NonRecoverableLedgerException` when reading the oldest msg, just skip these msgs if autoSkipNonRecoverableData is set to true.
PR in forked repository:[ ]
https://github.com/aloyszhang/pulsar/pull/10

[fix][broker] fix ttl expiration block due to no-recoverable exception even if autoSkipNonRecoverableData=true

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-broker/pom.xml

Add [oshi](https://github.com/oshi/oshi) library to help control OS resources.
ML: https://lists.apache.org/thread/sgod6pk5r8jgzjm6fqkcw10d88hp75t5
- Add dependency oshi

[improve][broker] Add oshi library to help control OS resources.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java

Now, if a topic without partition index provided when querying `internalGetMessageById`,  error `Topic not found` will be thrown out. It will confuse users. 
We'd better forbidden `internalGetMessageById` on partitioned-topic.
If a partitioned-topic is provided, `Status.METHOD_NOT_ALLOWED` will be thrown out
*(or)*
*(or)*
*(example:)* …

[improve][admin]internalGetMessageById shouldn't be allowed on partitioned topic

---

tests/integration/src/test/java/org/apache/pulsar/tests/integration/transaction/TransactionTestBase.java

Transaction's integration tests use the in memory implementation for the txn metadata store.
Since they're very important test to ensure stability of the transactions feature, it's better to use the default store which is actually designed to run in production environments. 
* Do not set `InMemTransactionMetadataStoreProvider` in the integration tests setup

[cleanup][txn] Use MLTransactionMetadataStore in integration tests

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/EmbeddedPulsarCluster.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiClusterTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ZooKeeperSessionExpireRecoveryTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiRolesTokenAuthorizationProviderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionPublishTest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/AbstractPulsarE2ETest.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/ClusterDataImpl.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/URIPreconditions.java
pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/ClusterDataTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/URIPreconditionsTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithAuthorizationTest.java

In the current implementation, we didn't have any cluster data check for `create/update` cluster. it may cause some problems when the user sets the wrong URL.
- Add parameters check.

[improve][broker] Add parameter check for create/update cluster.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSender.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/utils/ClientChannelHelper.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java

When the broker sends the transaction end response which has failed, the least sig bits is not included in the response payload. This also applies to other txn methods. 
This is not a big deal since the java client only uses it for debug logging.
However, thanks to #14613, it's possible to intercept this response payload so it's better to pass the correct value.   
* Set `TxnidLeastBits` in txn response payloads

[fix][txn] Always send correct transaction id in end txn response

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

We can set `updateLocalTopicOnly` when updating partitions by PulsarAdmin like 
```java
admin.topics().updatePartitionedTopic(partitionedTopicName, newPartitions, false, false);
```
But `updateLocalTopicOnly` is not exposed to CLI command `UpdatePartitionedCmd`
```shell
$ bin/pulsar-admin topics update-partitioned-topic
Options:
-f, --force
Update forcefully without validating existing partitioned topic
Default: false
* -p, --partitions
Number of partitions for the topic
Default: 0
```
expose`updateLocalTopicOnly`  to CLI command `UpdatePartitionedCmd` by adding a new option "--update-local-only" or "-ulo".
PR in forked repository:  https://github.com/aloyszhang/pulsar/pull/12

[improve][cli] Expose updateLocalTopicOnly to UpdatePartitionedCmd

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/netty/NettyChannelUtil.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/netty/NettyChannelUtilTest.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java

In the broker and proxy most of the writes callback are not considered. In those cases we can save useless allocations of default channel promises by using the `voidPromise()` method.
* Use `VoidChannelPromise` if the promise result is never checked

[improve][broker,proxy] Use ChannelVoidPromise to avoid useless promise objects creation

---

.github/actions/gradle-enterprise/action.yml
.github/workflows/ci-maven-cache-update.yaml
.github/workflows/ci-owasp-dependency-check.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml
.gitignore
.mvn/ge-extensions.xml
.mvn/gradle-enterprise-custom-user-data.groovy
.mvn/gradle-enterprise.xml
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleSchemaTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleSchemaWithSchemaValidationEnforcedTest.java

ASF Infra team together with Gradle Inc. has setup a dedicated Gradle Enterprise instance for Apache projects at https://ge.apache.org/ .
Gradle Enterprise works for both Gradle builds and Maven builds. There's a Maven extension which provides the integration for Maven builds, https://docs.gradle.com/enterprise/maven-extension/ .
You can find more information about the benefits of Gradle Enterprise on https://gradle.com . Gradle Enterprise is also for Maven builds!
Here's an example of builds scans for all Maven builds that are run as part of Pulsar CI workflow: https://ge.apache.org/scans?search.names=Git%20commit%20id%20short&search.timeZoneId=Europe/Helsinki&search.values=db7ab997&selection.buildScanB=ohtx53k6ymsgc
There are 69 maven builds that are run in total.
The build scans are …

[feat][ci] Add integration to ge.apache.org Gradle Enterprise server

---

pom.xml
src/owasp-dependency-check-false-positives.xml

- 7.4.4 includes fix for issue https://github.com/jeremylong/DependencyCheck/issues/5220
Error:  org.owasp.dependencycheck.data.nvdcve.DatabaseException: Error updating 'CVE-2020-36569' org.owasp.dependencycheck.data.update.exception.UpdateException: org.owasp.dependencycheck.data.nvdcve.DatabaseException: Error updating 'CVE-2020-36569' ...
Caused by: org.h2.jdbc.JdbcBatchUpdateException: Value too long for column "VERSIONENDEXCLUDING CHARACTER VARYING(60)": "'0.0.0-20160722212129-ac0cc4484ad4_before_v0.0.0-20200131131040-063a3fb69896' (75)"; SQL statement:
Upgrade dependency-check maven plugin to 7.4.4 version.
PR in forked repository: https://github.com/lhotari/pulsar/pull/127

[fix][build] Upgrade dependency-check-maven plugin to fix broken OWASP check

---

pulsar-io/alluxio/src/main/java/org/apache/pulsar/io/alluxio/sink/AlluxioSink.java
pulsar-io/alluxio/src/test/java/org/apache/pulsar/io/alluxio/sink/AlluxioSinkTest.java

Currently, the Alluxio sink always refers to localhost regardless of the `alluxioMasterHost` property.
Suppose we have a local Pulsar cluster (192.168.2.2) and a remote Alluxio cluster (192.168.33.10), as follows:
```
$ ip address show
...
2: enp1s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
link/ether e0:4f:43:e8:4c:86 brd ff:ff:ff:ff:ff:ff
inet 192.168.2.2/24 brd 192.168.2.255 scope global noprefixroute enp1s0f1
valid_lft forever preferred_lft forever
...
$ curl -sL http://192.168.33.10:19999/api/v1/master/info | jq .version
"2.7.3"
```
Build the Alluxio sink on the master branch and deploy it to the local Pulsar:
```
$ mvn clean install -DskipTests
...
[INFO] ------------------------------------------------------------------------ …
```

[fix][io] Fix Alluxio sink to respect the alluxioMasterHost property

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryController.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryControllerTest.java

Add ref count for sticky hash to optimize the performance of the Key_Shared subscription.
The root cause is [here](https://github.com/apache/pulsar/pull/10762/files#diff-4c2d35368b21e5c33d65886196e8673c04a69f5c5cb888cdd04c29f8823502fdR97-R100). We are going to go through all the redelivery messages to check if contains the hash from a given sticky hash set.
Introduce a ref count map for the sticky hash set to make the method `containsStickyKeyHashes` works more efficiently.
With this fix
Updated the existing test to cover the new changes.

[improve][broker] Add ref count for sticky hash to optimize the performance of Key_Shared subscription

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

In https://github.com/apache/pulsar/pull/15347, there is a regression where the `subName` needed to be passed to the authorization provider. That PR is not released, so this PR is just cleanup
* Pass `subName` for `validateTopicOperationAsync` in `PersistentTopicsBase#internalDeleteSubscriptionForNonPartitionedTopicAsync`
We should add testing to this part of the code base to prevent future regressions.
This is not a breaking change.

[cleanup][broker] Pass subName to authz provider on unsubscribe

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/BundleSplitStrategy.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/BundleSplitterTask.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/BundleSplitterTaskTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java

Add `NamespacePolicies` and `AntiAffinity` check before unload bundle when `checkNamespaceBundleSplit`.
When unload the bundle after split, It's better to guarantee there are at least one another broker can load those bundle which satisfy the NamespacePolicies and AntiAffinity. Otherwise the bundle may not load successfully and  cause the client reconnect frequently.
1. add NamespacePolicies and AntiAffinity check before unload bundle when `checkNamespaceBundleSplit`.
2. add some unit test.
PR in forked repository:https://github.com/Nicklee007/pulsar/pull/2

[improve][broker]add NamespacePolicies and AntiAffinity check before unload in checkNamespaceBundleSplit

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java

When a cursor is activated, use `cursor.isActive` instead of `activeCursors.get(cursor.getName()) == null` to judge cursor's status. more readable.
Use cursor.isActive instead to judge if cursor is active
*(or)*
*(or)*
*(example:)*
https://github.com/gaozhangmin/pulsar/pull/7

[improve][broker]Use cursor.isActive instead to judge if cursor is active

---

bin/pulsar

The original code can produce:
```
bash: [: missing `]'
```
... if `$FUNCTIONS_LOG_CONF` is not empty.

[fix][cli] Shell syntax

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java

When a DLQ producer connects, it creates a subscription when configured to do so. The `subscriptionName` should be passed to the `authorizationProvider` to properly determine authorization.
* Pass `initialSubscriptionName` to `isTopicOperationAllowed` method in the `ServerCnx`.
I am going to work on generic tests to cover this case (and some others) when I do #19183.
This is not a breaking change.
This only impacts users that have subscription level permissions, which are not well documented. We should improve those docs eventually, but there is no need to fix those docs while making this fix.
PR in forked repository: https://github.com/michaeljmarshall/pulsar/pull/11

[fix][broker] Pass subName for subscription operations in ServerCnx

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPackages.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java

[fix] Some typos in Cmd classes

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationProvider.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java

Mailing list discussion: https://lists.apache.org/thread/sogsqz656cq5xvw1t014khogv6w33br6
With the acceptance of PIP 149, we've made a clear move to remove blocking calls in the Pulsar code base. The `AuthorizationService` and the `AuthorizationProvider` has some unused methods that synchronous wrappers for async methods. Since these methods are unused, I propose we deprecate them in 2.12 and remove them in 2.13.
* Add `@Deprecated` annotation and an updated javadoc.
I relied on IDE's usage finder to indicate that these methods are unused.
This will eventually affect the public API for the `AuthorizationService` and the `AuthorizationProvider`, which only impacts users that are running custom code inside the Pulsar Broker.
I will send an email to the mailing list to make sure this change …

[cleanup][broker] Deprecate blocking AuthorizationService, AuthorizationProvider methods

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java

This behaviour is broken by PR #18193,
In the previous version, we could use the pulsar client to look up the topic with the `-partition-` keyword. Even this topic doesn't have partition metadata. But currently, we can't do that. You can check the test to know the detail.
- Allow user lookup topic name with `-partition-` but no metadata

[fix][broker] Allow user lookup topic name with `-partition-` but no metadata

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

We use `latest` to copy subscriptions from another topic; there is a gap between the topic creation and subscription. In this period, If some new producer sends messages to the new topic partition. There may look like some messages are lost on the user side.
Because there is a new topic partition, I think it's Ok to change `latest` to `earliest`.
- Use `earliest` instead of `latest`.
It's hard to add the test case.

[fix][broker] Fix race condition while updating partition number

---

pom.xml
pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/utils/FunctionRecord.java

* This refers to https://github.com/apache/pulsar/pull/18520
* This refers to https://github.com/apache/pulsar/pull/16041
Verified locally with:
```
mvn -pl pulsar-client-api javadoc:javadoc 
mvn -pl pulsar-client-admin-api javadoc:javadoc
cd ./pulsar-functions 
mvn -pl api-java javadoc:javadoc
```
... results:
```
➜  pulsar git:(fix-javadoc) ls pulsar-client-api/target/site/apidocs
allclasses-index.html   jquery-ui.overrides.css resources
allpackages-index.html  legal                   script-dir
constant-values.html    member-search-index.js  script.js
deprecated-list.html    module-search-index.js  search.js
element-list            org                     serialized-form.html
help-doc.html           overview-summary.html   stylesheet.css
index-all.html          overview-tree.html …
```

[fix][doc] Remove lombok plugin and define FunctionRecordBuilder explicitly

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java

Fixes https://github.com/apache/pulsar/issues/19189
Fixes https://github.com/apache/pulsar/issues/19189
The root cause is that:
1. When msg size is greater than `batchingMaxBytes `,  we will go to line677:
https://github.com/apache/pulsar/blob/4b0dc9ab87b5fa82525514dc37a91e7db0fa95fc/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L645-L678
2. Let go into the method `doBatchSendAndAdd( )`：
2.1 Line882 do nothing and will not trigger the batch flush task;
2.2 Line883 just add the msg into `batchMessageContainer`;
2.3 Note that, the batch flush task doesn't run now. And if there is no successive messages, the msg in `batchMessageContainer` will never be flushed to network
https://github.com/apache/pulsar/blob/4b0dc9ab87b5fa82525514dc37a91e7db0fa95fc/pulsar-client/ …

[fix][client] Fix producer could send timeout when enable batching

---

.mvn/ge-extensions.xml
.mvn/gradle-enterprise.xml

This change updates the Gradle Enterprise configuration in a few small ways to keep the configuration up to date with best practices.
- Update to version 1.16.2 of the Gradle Enterprise Maven Extension
- Use newer syntax for Gradle Enterprise goal input capture
- Only enable the Gradle Enterprise local build cache for non-CI builds
- Disable the Gradle Enterprise remote cache for all builds

[improve][ci] Gradle Enterprise Configuration Tweaks

---

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionLocalRunTest.java

"Pulsar CI Flaky" builds fail with OOMEs and produces heap dumps.
It turns out that #19151 causes a breaking change. 
In PulsarFunctionLocalRunTest, the line 275 `ClusterData clusterData = ClusterData.builder().serviceUrl(urlTls.toString()).build();` didn't cause the test to fail before #19151 changes.
After the changes were made, this test started failing, but the test failure was ignored. 
* Fix the test
* Make changes to the test that prevent the resource leak that leads to a OOME
PR in forked repository: https://github.com/lhotari/pulsar/pull/128

[fix][ci] Fix PulsarFunctionLocalRunTest that broke after ClusterData validation changes

---

pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyPrometheusMetricsTest.java

Fixes #19216
ProxyPrometheusMetricsTest is flaky. Please see #19216 for details.
- unregister collector after the test
- fix retries by adding null checks

[improve][test] Prevent "Failed to register Collector of type Counter"

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/reader/JacksonJsonReader.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/reader/JsonReader.java

- benefits: 
- no need to lookup the type when reading happens. 
- The type gets fetched from cache once. 
- Since a reference is kept, it won't overflow from a busy Jackson TypeFactory LRU cache.
Replace ObjectMapper usage with ObjectReader in JacksonJsonReader and JsonReader classes.

[improve][client] Use Jackson's ObjectReader in Client's JSON readers

---

.github/workflows/ci-maven-cache-update.yaml
.github/workflows/ci-owasp-dependency-check.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

The cache step in GitHub Actions workflows gets sometimes stuck.
Example at https://github.com/apache/pulsar/actions/runs/3905696188/jobs/6673646325#step:6:17
```
Received 1493610815 of 1497805119 (99.7%), 0.5 MBs/sec
Received 1493610815 of 1497805119 (99.7%), 0.5 MBs/sec
Received 1493610815 of 1497805119 (99.7%), 0.5 MBs/sec
Received 1493610815 of 1497805119 (99.7%), 0.5 MBs/sec
Received 1493610815 of 1497805119 (99.7%), 0.5 MBs/sec
Received 1493610815 of 1497805119 (99.7%), 0.5 MBs/sec
Received 1493610815 of 1497805119 (99.7%), 0.5 MBs/sec
Received 1493610815 of 1497805119 (99.7%), 0.5 MBs/sec
Error: The operation was canceled.
```
The cache step runs until the job times out after 60 minutes. 
Add `timeout-minutes: 5` to cache steps to limit the execution time to 5 minutes.

[improve][ci] Limit cache step to 5 minutes to fail faster when it gets stuck

---

buildtools/src/main/java/org/apache/pulsar/tests/FailFastNotifier.java

- cleanup didn't happen for tests after failures when failfast mode is activated
- ignore the failfast solution for @After* methods

[improve][test] Run cleanup methods even when failfast mode is enabled

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/IncrementPartitionsTest.java

we have supported creating a subscription with properties since #15503. It is a good way to support copy subscription properties during updating the topic partition number.
Because #15503 didn't support v1, this PR also just focused on v2. 
- Support copy subscription properties during updating the topic partition number.

[improve][broker] Copy subscription properties during updating the topic partition number.

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminRestTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/MetricsAuthenticationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/TransactionBatchWriterMetricsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyAuthenticationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/v1/V1_ProxyAuthenticationTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyIsAHttpProxyTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyPrometheusMetricsTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyStatsTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithJwtAuthorizationTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/UnauthedAdminProxyHandlerTest.java

Fixes #19216
See https://github.com/apache/pulsar/pull/19217#issuecomment-1381096161 for details of the remaining problem in ProxyPrometheusMetricsTest
- Use Awaitility to wait until metrics are available
- Consistently close JAX-RS clients in all tests

[fix][test] Fix ProxyPrometheusMetricsTest flakiness and consistently close JAX-RS clients in tests

---

.github/workflows/pulsar-ci.yaml
build/pulsar_ci_tool.sh
docker/pulsar/Dockerfile
docker/pulsar/pom.xml
tests/docker-images/java-test-image/Dockerfile
tests/docker-images/java-test-image/pom.xml

There's a problem with azure.archive.ubuntu.com apt mirror that causes many builds to fail. I reported it by adding a comment to an existing issue: https://github.com/actions/runner-images/issues/675#issuecomment-1381389712 . However, there's a need to apply a fix so that apache/pulsar CI doesn't get blocked by the problem.
- use custom shell script to pick the closest available ubuntu mirror if apt-get install fails
-  script is based on https://askubuntu.com/a/719551 with some improvements
- set the chosen mirror to UBUNTU_MIRROR and UBUNTU_SECURITY_MIRROR environment variables to be used in docker image building

[fix][ci] Fix CI issue where ubuntu apt repository azure.archive.ubuntu.com isn't available
