apache/pulsar

pom.xml
Fixes #19227
Builds fail sporadically with error message `An error has occurred in JaCoCo report generation. Error while creating report: Unknown block type 61.` in CI. One possible reason is that jacoco write the coverage file in a shutdown hook and this is terminated when surefire.shutdown is set to `kill`.
- set surefire.shutdown to "exit" when "coverage" profile is active
- jacoco doesn't support using the surefire.shutdown=kill mode
PR in forked repository: https://github.com/lhotari/pulsar/pull/131
=> [fix][build] Fix "An error has occurred in JaCoCo report generation"

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PartitionKeywordCompatibilityTest.java
We allow users to use the client to create the partitioned topic when they enable partitioned type auto-creation. But we didn't support deleting it. 
- Support deleting partitioned topics with the keyword `-partition-`
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Support deleting partitioned topics with the keyword `-partition-`

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/PulsarResources.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyAuthenticationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyAuthorizationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyConfigurationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyEncryptionPublishConsumeTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTlsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeWithoutZKTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/v1/V1_ProxyAuthenticationTest.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Worker.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java
Fixes #16489
Master Issue: #16489
Export config `metadataStoreAllowReadOnlyOperations` and `zooKeeperAllowReadOnlyOperations`.
=> [fix][broker] Support zookeeper read-only config.

build/pulsar_ci_tool.sh
- docker image building fails with https:// mirrors because of missing ca-certificates package
- follow up on #19225 changes
example failure: https://github.com/apache/pulsar/actions/runs/3917809248/jobs/6697895837#step:11:9928
```
[INFO] DOCKER> Err:7 https://mirror.fcix.net/ubuntu focal-backports Release
[INFO] DOCKER> Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 23.152.160.16 443]
[INFO] DOCKER> Err:8 https://mirror.fcix.net/ubuntu focal-security Release
Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 23.152.160.16 443]
[INFO] DOCKER> Reading package …
```
=> [fix][ci] Pick ubuntu mirror that uses http://

distribution/shell/src/assemble/LICENSE.bin.txt
Fix license check issues that occur in #19206, and #19205.
This may introduce by #17779
```
Run src/check-binary-license.sh ./distribution/server/target/apache-pulsar-*-bin.tar.gz && src/check-binary-license.sh ./distribution/shell/target/apache-pulsar-shell-*-bin.tar.gz
snakeyaml-1.32.jar unaccounted for in LICENSE
snakeyaml-1.31.jar mentioned in LICENSE, but not bundled
```
PR in forked repository:  https://github.com/Technoboy-/pulsar/pull/27
=> [branch-2.11][ci] Fix license check issue

pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/DebeziumSource.java, pulsar-io/debezium/mongodb/src/main/java/org/apache/pulsar/io/debezium/mongodb/DebeziumMongoDbSource.java
2.11 backport of https://github.com/apache/pulsar/pull/19004
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/alpreu/pulsar/pull/6
=> [branch-2.11][cherry-pick] Debezium sources: Support loading config from secrets

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PartitionKeywordCompatibilityTest.java
This PR is following up #19230
As @yuruguo mentioned https://github.com/apache/pulsar/pull/19230#issuecomment-1382865057, we can tighten the validation scope.
I've checked the logic and found we have no way to create the partition topic with the `-partition-{index}` template. So we can righten the validation scope.
I will keep working on the partition topic section and try to clarify the concept and logic. Plus, ensuring compatibility.
- tighten the validation scope
=> [improve][broker] Follow up #19230 to tighten the validation scope

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryController.java
Fix compile error caused by cherry-pick #19167 
The commit is https://github.com/apache/pulsar/commit/e310713be433e6e36a4191deb74ae8e5d0a03820
- Use the constructor instead of the builder pattern.
=> [branch-2.9] Fix compile error caused by cherry-pick #19167.

buildtools/src/main/java/org/apache/pulsar/tests/SingletonCleanerListener.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/JSONSchema.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/ObjectMapperFactory.java
Follow up on ObjectMapper sharing changes made in #19160.
- use ObjectMapperFactory.create() to create a new ObjectMapper for JSONSchema
- simplify state clean up methods so that ObjectMapperFactory and JSONSchema both have a single static method "clearCaches()" to clean up state
- this is useful in tests so that classes / classloaders don't leak between tests
- update custom TestNG listener SingletonCleanerListener to call the methods
PR in forked repository: https://github.com/lhotari/pulsar/pull/130
=> [improve][misc] Follow up on ObjectMapper sharing changes

.github/actions/upload-coverage/action.yml, .github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml, build/run_unit_group.sh, codecov.yml, pom.xml
- currently the codecov reporting processes the uploaded coverage reports too early and thus the coverage result is invalid.
- the `after_n_builds` configuration setting should be used for waiting for all builds to finish before merging the coverage reports from parallel builds.
- see https://docs.codecov.com/docs/notifications#preventing-notifications-until-after-n-builds
Set `after_n_builds` to 10.
=> [fix][ci] Fix codecov reporting by configuring to wait for all builds sending coverage

pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyIdleTimeoutTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPingTest.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/AbstractWebSocketHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketProxyConfiguration.java, pulsar-websocket/src/test/java/org/apache/pulsar/websocket/AbstractWebSocketHandlerTest.java
When the WebSocket connection is idle timeout, the server disconnects the client. We need to keep alive between the client and the server.
There are two options:
1. Increasing the idle timeout, but be very unfriendly to users who are not sensitive to time
2. Sending the ping frame to the client
Some client(browser) doesn't support sending the ping frame to the server, which causes idle timeout, so we only add enable ping feature on the server.
**Note:** The Jetty automatically processes ping/pong frames from the client by default.
- Implement sending the ping frame to the client
- Add `webSocketPingDurationSeconds` config to enable the ping feature
=> [improve][websocket] Add ping support

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java
Currently, we didn't close the `TransactionBuffer` after `MessageDeduplication#checkStatus` failed. see: https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1600
it will lead to memory leak.
In `TopicTransactionBuffer`, it will create a `snapshotWrite` in [`SingleSnapshotAbortedTxnProcessorImpl`](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java#L57), and the write will held by [`SystemTopicClientBase#writers`](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/SystemTopicClientBase.java#L76).
If we don't close the `TransactionBuffer` after …
=> [fix][broker] Close transactionBuffer after MessageDeduplication#checkStatus failed

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/GeoPersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ShadowReplicator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/ShadowReplicatorTest.java
The Replication task execution process works like this:
- read messages from the origin cluster
- load schema
- send to the target cluster
Because the network across the cluster is unstable, the sending task may be slower, so if the number of messages being sent is too large, the replication task will be suspended. There is a counter(`pendingMessages `) in `Replicator` indicating the count of sending messages. 
<strong>(Highlight)</strong>There is a problem that causes the counter to be inaccurate when the scheme future is incomplete. If the counter is as large as the config `replicationProducerQueueSize,` the replication task will be stuck. You can reproduce by `ReplicatorTest.testReplicationWillNotStuckByIncompleteSchemaFuture`.
- Make that the counter is correct when exceptions occur …
=> [fix] [broker] Counter of pending send messages in Replicator incorrect if schema future not complete

.github/workflows/pulsar-ci.yaml
- helps investigate issues when there's a JVM crash such as #19250
- upload native crash dump files hs_err_*.log & core.* in CI unit tests
=> [improve][ci] Upload native crash dump files hs_err_*.log & core.* in CI unit tests

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TableViewTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClient.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
Currently, we can use PulsarClient to create `Producer`, `Consumer`, `Reader` and `TableView`, releated method as below:
```
ProducerBuilder<byte[]> newProducer();
<T> ProducerBuilder<T> newProducer(Schema<T> schema);
ConsumerBuilder<byte[]> newConsumer();
<T> ConsumerBuilder<T> newConsumer(Schema<T> schema);
ReaderBuilder<byte[]> newReader();
<T> ReaderBuilder<T> newReader(Schema<T> schema);
<T> TableViewBuilder<T> newTableViewBuilder(Schema<T> schema);
```
However, it is obvious that the method of creating `TableView` is not consistent with other methods, and no method with default scheme is provided.
Add unified `newTableView(Schema)` method and replace `newTableViewBuilder(Schema)`(attach `@Deprecated` annotation to it) in PulsarClient, which could consistent with …
=> [improve][client] Add unified newTableView method in PulsarClient

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
we should check the `destinationBroker` whether is an inactive broker  and  reject the unload request  when the `destinationBroker`  is set as an inactive destination. Otherwise the unload result not satisfied our expectation which will cause the bundle need unload more times.
1. check `destinationBroker` before `setNamespaceBundleAffinity` in `unloadNamespaceBundle`;
2.  add some unit test.
PR in forked repository: https://github.com/Nicklee007/pulsar/pull/7
=> [fix][broker] Avoid bundle unload destination broker be set as an inactive broker.

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java
Fixes #19216 
See #19216 and #19062 . Fixes a problem with pulsar-proxy flakiness related to metrics.
- revert #19062 change that caused #19216 
- fix the problem that #19062 attempted to fix by tracking whether the metrics have already been registered
=> [fix][test] Fix pulsar-proxy test flakiness related to metrics

build/run_integration_group.sh, build/run_unit_group.sh, buildtools/src/main/java/org/apache/pulsar/tests/FailFastNotifier.java, pom.xml
Currently, there's a custom fail fast mode implemented as a TestNG listener in https://github.com/apache/pulsar/blob/master/buildtools/src/main/java/org/apache/pulsar/tests/FailFastNotifier.java. 
The purpose of this is to speed up pull request builds by failing the build at the first error.
Surefire's fail fast feature (`-Dsurefire.skipAfterFailureCount=1`) was unusable because of bug https://issues.apache.org/jira/browse/SUREFIRE-1762, when the solution was implemented.
The FailFastNotifier solution doesn't currently work properly since it doesn't stop parallel test processes.
This PR implements a solution for that gap.
This PR also disables the fail fast mode for all non-PR builds in GitHub Actions so that there will be better coverage for Gradle Enterprise build scans that run for …
=> [improve][ci] Improve test fail fast: disable for non-PR builds, fail parallel forked test procs

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLoadData.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeight.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLoadDataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeightTest.java
This PR moved the common broker load data feature(`weightedMaxEMA`) to `BrokerLoadData`.
As `weightedMaxEMA` is available in the `BrokerLoadData` by this change, this PR
- removed `brokerAvgResourceUsageWithWeight` in LeastResourceUsageWithWeight -- we don't need to separately compute and store `weightedMaxEMA` in `LeastResourceUsageWithWeight and TransferShedder`. 
- refactored BrokerLoadData to precompute the load data features.
- updated the unit tests.
-  Updated unit tests. …
=> [improve][broker] PIP-192 Moved the common broker load data feature(weightedMaxEMA) to BrokerLoadData

.github/actions/upload-coverage/action.yml, .github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml, build/run_integration_group.sh, codecov.yml, pom.xml, tests/docker-images/latest-version-image/conf/bookie.conf, tests/docker-images/latest-version-image/conf/broker.conf, tests/docker-images/latest-version-image/conf/functions_worker.conf, tests/docker-images/latest-version-image/conf/global-zk.conf, tests/docker-images/latest-version-image/conf/local-zk.conf, tests/docker-images/latest-version-image/conf/presto_worker.conf, tests/docker-images/latest-version-image/conf/proxy.conf, tests/docker-images/latest-version-image/conf/websocket.conf, tests/integration/pom.xml, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ChaosContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/PulsarContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ZKContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java
Code coverage metrics don't currently consider integration tests and systems tests that are run as part of the Pulsar CI pipeline. There hasn't been a way to measure the total code coverage of Pulsar CI pipeline tests although it would be useful to see what parts of Pulsar code base are tested and what aren't.
- Add solution to Pulsar Testcontainer based integration tests so that the Jacoco agent gets activated for processes that are run inside Docker containers
- A directory from the host is mounted in the docker container. This directory is used for storing the Jacoco exec files.
- The code coverage should be uploaded to codecov for all public code repositories. This is now changed so that it's possible to get coverage metrics for builds running in a fork.
- Graceful shutdown of Java …
=> [feat][ci] Collect code coverage for integration tests from docker containers

pom.xml
There are 1 security vulnerabilities found in org.postgresql:postgresql 42.4.1
- [CVE-2022-41946](https://www.oscs1024.com/hd/CVE-2022-41946)
Upgrade org.postgresql:postgresql from 42.4.1 to  for vulnerability fix
Ideally, no insecure libs should be used.
=> [fix][sec] upgrade org.postgresql:postgresql to  42.5.1

pom.xml
Currently, the HBase sink uses HBase 2.4.9, which is released over a years ago.
This PR upgrades HBase to the current latest version of the 2.4.x line so that we can ensure the HBase sink works with it.
This change is already covered by existing tests, such as `HbaseGenericRecordSinkTest`.
PR in forked repository: https://github.com/sekikn/incubator-pulsar/pull/8
The CI above failed on the PULSAR_IO_ORA test group, but it's irrelevant to this PR.
=> [improve][io] Upgrade HBase to 2.4.15

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Worker.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java
Fixes #xyz
PIP: #xyz 
This is part 2 for #19156, deprecate `zookeeperAllowReadOnlyOperations` and introduce `metadataStoreAllowReadOnlyOperations`. It needs cherry-pick to branch-2.10 and branch-2.11
*(or)*
*(or)*
*(example:)*
=> [improve] [broker] Introduce `metadataStoreAllowReadOnlyOperations` to deprecate `zookeeperAllowReadOnlyOperations`

pulsar-io/jdbc/openmldb/pom.xml
Fix [CVE-2019-17571](https://www.cve.org/CVERecord?id=CVE-2019-17571)
```
Introduced through: org.apache.pulsar:pulsar-io-jdbc-openmldb@2.12.0-SNAPSHOT › com.4paradigm.openmldb:openmldb-jdbc@0.4.4-hotfix1 › log4j:log4j@1.2.17
Introduced through: org.apache.pulsar:pulsar-io-jdbc-openmldb@2.12.0-SNAPSHOT › com.4paradigm.openmldb:openmldb-jdbc@0.4.4-hotfix1 › org.slf4j:slf4j-log4j12@1.7.21 › log4j:log4j@1.2.17
```
Exclude log4j from openmldb.
=> [fix][sec] Exclude log4j from openmldb

pulsar-common/src/main/java/org/apache/pulsar/common/util/FutureUtil.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStore.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriter.java
In the transaction coordinator code, most of the async execution doesn't properly runtime exceptions that might happens.
The exception is not logged and the `CompletableFuture` is not completed. 
Similar changes in past https://github.com/apache/pulsar/pull/17484
* New utility method `FutureUtil#safeRunAsync(Runnable runnable, Executor executor, CompletableFuture completableFuture)` that completes exceptionally the completablefuture if an error has been caught in the runnable 
* Added in MLTransactionMetadataStore and  TxnLogBufferedWriter
=> [fix][txn] Catch and log runtime exceptions in async operations

pulsar-io/alluxio/src/main/java/org/apache/pulsar/io/alluxio/sink/AlluxioSink.java, pulsar-io/alluxio/src/test/java/org/apache/pulsar/io/alluxio/sink/AlluxioSinkTest.java
Fixes #19174
Currently, the Alluxio sink fails to write messages out after the first file rotation.
This problem is caused by improper reuse of the `CreateFilePOptions.Builder` object. This PR fixes AlluxioSink to instantiate that object for every file creation.
- Extend `writeAndCloseTest` to check subsequent output after the first file rotation.
PR in forked repository: https://github.com/sekikn/incubator-pulsar/pull/7
=> [fix][io] Fix the Alluxio sink to write messages successfully after the first file rotation

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
The `AuthenticationDataSource` variable was added to the `ProxyConnection` class in https://github.com/apache/pulsar/pull/1200. It is no longer needed.
Note that we store this variable in the `ServerCnx` because it is used for authorization. Because we do not do authorization in the proxy, we don't need it.
* Remove unused variable
This is a trivial change.
The only conceivable way this is a breaking change is if a third party implementation implemented their library so that `authState.getAuthDataSource()` has a side effect.
No docs needed.
=> [cleanup][proxy] Remove unused AuthenticationDataSource variable

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/batching/AbstractBatchedMetadataStore.java
When the broker is shutting down AbstractBatchedMetadataStore completes exceptionally the pending operations with a generic IllegalStateException. All the code that is depending on the MetadataStore usually expects instances of MetadataStoreException and they may not properly react to this error.
This is generally not a big deal because the broker is shutting down, but we should improve it 
Complete the pending operations with AlreadyClosedException instead of IllegalStateException
=> [fix][broker] AbstractBatchedMetadataStore - use AlreadyClosedException instead of IllegalStateException

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
When `trim ledgers` and `create new cursor` are executed concurrently, it will cause the `readPosition` of the cursor to point to a deleted ledger.
| time | `trim ledgers` | `create new cursor` |
| 1 | | set read position and mark deleted position |
| 2 | delete ledger | |
| 3 | | add the cursor to `ManagedLedger.cursors` |
----
<strong>(Highlight)</strong>Since the read position of the cursor is pointing at a deleted ledger, so deleted messages will never be consumed or acknowledged. Since the backlog in the API `topics stats` response is calculated as this: `managedLedger.entriesAddedCounter - cursor.messagesConsumedCounter`, the result is: Topics stats show `msgBacklog` but there is reality no backlog.
- `managedLedger.entriesAddedCounter`: Pulsar will set it to `0` …
=> [fix] [ml] Topics stats shows msgBacklog but there reality no backlog

.github/actions/upload-coverage/action.yml, .github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml, build/pulsar_ci_tool.sh, build/run_integration_group.sh, build/run_unit_group.sh, codecov.yml, pom.xml, tests/integration/pom.xml
Currently, jacoco code coverage doesn't get reported for classes that reside in a project other than the test class.
Jacoco includes another goal "report-aggregate" which correctly handles multi-project builds.
Usage example: https://github.com/jacoco/jacoco/blob/master/jacoco-maven-plugin.test/it/it-report-aggregate-customization/report/pom.xml
The first attempt was to use the jacoco:report-aggregate goal:
It has 2 issues:
- 0.8.8 version doesn't yet support the required "includeCurrentProject" feature.
- the dependent projects must be built as part of the same mvn execution and belong to the same maven "reactor"
- this isn't compatible with the way how Pulsar CI builds in "Build and License check" job and reuses
the build results to run unit tests.
In addition, there's an issue with the …
=> [fix][ci] Fix Jacoco code coverage to report classes in dependent projects

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/AbstractWebSocketHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java
#19203 introduces `webSocketPingDurationSeconds` config, but doesn't add this config to the proxy and broker config class.
When the proxy/broker calls the `WebSocketService(ClusterData localCluster, ServiceConfiguration config)`, the ping feature will be broken.
- Add `webSocketPingDurationSeconds` to `ProxyConfiguration`
- Add `webSocketPingDurationSeconds` to `ServiceConfiguration`
- Improve reading the `webSocketPingDurationSeconds`
=> [fix][websocket] Fix webSocketPingDurationSeconds config

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationState.java
PIP 97: https://github.com/apache/pulsar/issues/12105
While working on PIP 97, I noticed that we do not have a clear contract for the `AuthenticationState` interface. We use the interface in one way in the `ServerCnx` class, but some of our official implementations do not align with the usage and the API. The PR itself provides my proposed authoritative documentation.
When we agree on the content of this PR, I will follow up with some changes to the `TokenAuthenticationState` class and potentially others.
* Add documentation on how the `AuthenticationState` interface will be used by Pulsar.
I have studied the code closely to understand how it works, and more importantly, how it should work.
This change could affect how plugins interact with the `AuthenticationState` object.
This is a …
=> [improve][broker] Documentation for AuthenticationState contract

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderToken.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderTokenTest.java
We use the result of `TokenAuthenticationState#getAuthDataSource` to pass to the `AuthorizationProvider`. For custom implementations, it is important that this information is up to date.
The `TokenAuthenticationState` field `AuthenticationDataSource` is set on initialization and never again. Given that tokens can be refreshed, we should update the field `TokenAuthenticationState#authenticationDataSource` when the `authenticate` method is called.
* Update the `authenticationDataSource` when `authenticate` is called.
A new test is added to cover this change.
This change will  only affect third party `AuthorizationProvider` implementations. It's possible that it could break their integration, though unlikely. Note that we update the `authRole` when `authenticate` is called.
We do not …
=> [fix][broker] Let TokenAuthState update authenticationDataSource

.github/actions/upload-coverage/action.yml, build/pulsar_ci_tool.sh, codecov.yml, pom.xml, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/PulsarContainer.java
After reviewing the latest changes made in #19264 for collecting code coverage in a new way, there are a few details that need to be adjusted. 
The Codecov results can be seen for the PR commit at 
https://app.codecov.io/github/apache/pulsar/commit/62060c814bf90de9b8f7cd520e2dc5459b394cbe/tree
The build workflow run contained Jacoco html reports at https://github.com/apache/pulsar/actions/runs/3961486478 .
- use test scope classpath to collect correct dependencies
- exclude test projects so that coverage doesn't get reported for them
- show link to Codecov commit level report
- notify as soon as 4 uploads are completed for the commit
-  ignore the CI status since that is often wrong in Codecov and the notification doesn't appear at all.
- It's sufficient to wait for 4 uploads to happen …
=> [improve][ci] Improve code coverage reporting

.github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml, build/pulsar_ci_tool.sh, build/run_unit_group.sh, pom.xml
Code coverage for master branch need pulsar-ci-flaky to run with a scheduled job since flaky tests are also part of
the coverage. 
This PR contains some improvements and follow up on #19264 and #19296 changes.
- add scheduling to pulsar-ci-flaky
- make Jacoco agent use unique files for forked test processes to reduce chances of file corruption and contention
- don't use failfast mode for flaky tests and quarantined tests since it impacts coverage results
- suppress excessive logging when zipping jacoco html reports
- filter out empty .exec files
- skip uploading pulsar-io META-INF/bundled-dependencies files which take up over 900MB
=> [improve][ci] CI code coverage collecting improvements 

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pulsar-common/pom.xml, pulsar-common/src/main/java/org/apache/pulsar/common/util/ObjectMapperFactory.java
- Jackson contains Java 8 support modules that haven't been added and registered in Pulsar.
- more information about modules: https://github.com/FasterXML/jackson-modules-java8
This change applies to Jackson usage on the server side (Broker, Pulsar Functions etc.) and on the client.
- Add Parameter names, Java 8 Date/time and Java 8 Datatypes modules and register them by default
dev mailing list thread: https://lists.apache.org/thread/9bxs90q0m5phhytz6480b6fcnfclxt3s
This PR depends on #19160 so that the properly configured ObjectMapper instances are used. 
PR in forked repository: https://github.com/lhotari/pulsar/pull/125
=> [improve][misc] Register Jackson Java 8 support modules by default

pom.xml, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/SourceApiV3ResourceTest.java
It's good to keep the Pulsar pom.xml maintained.
Upgrade ASF parent pom version to 29. Upgrade some of the plugins to use the version of certain maven plugins that are used in the ASF parent pom.
It was necessary to update SourceApiV3ResourceTest since Nar unpack no longer fails. There is a separate PR #19304 to make his behavior explicit. 
ASF parent pom version 29 references Jar plugin version 3.3.0 . Before this PR, the Jar plugin version has been 3.2.0 .
This is the issue that was fixed: https://issues.apache.org/jira/browse/MJAR-281 .
PR in forked repository: https://github.com/lhotari/pulsar/pull/126
=> [improve][build] Upgrade ASF Maven parent pom version to 29

.github/workflows/pulsar-ci.yaml
Uploading coverage to Codecov might fail. Uploading requires the intermediate pulsar-maven-repository-binaries.tar.zst so this shouldn't be deleted if one of the upload jobs has failed.
Add proper condition to deletion step. This PR will also skip deletion if owasp-dep-check or flaky-systems-tests fail.
=> [fix][ci] Require coverage upload jobs to succeed before deleting intermediate build artifacts

.github/workflows/ci-go-functions.yaml, .github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml
For GitHub Actions workflows, the docs_only logic should be ignored for scheduled builds since it doesn't make sense to skip the build if the last commit contains only files that match [the docs filter](https://github.com/apache/pulsar/blob/36806853b5a445299d8f9a6ba89905c1915345a3/.github/changes-filter.yaml#L5-L13).
If the event name is 'schedule', always set docs_only to false.
=> [improve][ci] Ignore docs_only logic for scheduled builds

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/OneStageAuthenticationState.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/OneStageAuthenticationStateTest.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
PIP: #12105
In order to implement PIP 97, we must replace `authenticate` calls with `authenticateAsync`. This PR makes those changes for `OneStageAuthenticationState`. It also moves the call to authenticate the `AuthData` out of the constructor and into the `authenticateAsync` method.
One assumption I make in this PR, is that there will not be concurrent calls to the same `AuthenticationState#authenticateAsync` method. That seems like a reasonable assumption because Pulsar uses this state object in the netty eventloop handlers, but please let me know if you disagree.
* Move the `authenticate` call out of the constructor so that authentication is only done on the first pass through the `authenticateAsync` method.
* Make `authenticate` backwards compatible for any plugins that are using it. …
=> [feat][broker] OneStageAuth State: move authn out of constructor

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProvider.java
PIP: #12105 
In order to support `AuthenticationProvider` implementations that only implement `authenticateAsync`, we need to replace the call to `authenticate` with `authenticateAsync` in the default method definition in `AuthenticationProvider#authenticateHttpRequest`.
This PR is necessary to get the tests passing in https://github.com/apache/pulsar/pull/19292.
I should have implemented #19197 this way from the beginning.
* Replace `authenticate` with `authenticateAsync`.
This PR is covered by the tests in `AuthenticationServiceTest`.
This is not a breaking change because the code was only just recently introduced to master branch.
PR in forked repository: this is a trivial change, so adding label to test now
=> [improve][broker] Replace authenticate with authenticateAsync

.github/workflows/ci-owasp-dependency-check.yaml
- "Configure Gradle Enterprise" step fails for other than master branch
- don't run "Configure Gradle Enterprise" step for other branches
- also improve the workflow
- simplify matrix variables
- optimize the "mvn clean install" build by skipping as much as possible
- allow triggering manually (workflow_dispatch)
Test run of "CI - OWASP Dependency Check" in forked repository: 
https://github.com/lhotari/pulsar/actions/runs/3994121428
=> [fix][ci] Fix "CI - OWASP Dependency Check" for other than master branch

.github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml, build/run_unit_group.sh
- this will make it easier to synchronize pulsar-ci.yaml to other branches
- skipping upload jobs was broken for docs_only change since `needs` didn't include `preconditions` for the upload jobs
- add collect_coverage input parameter to workflow_dispatch
- add collect_coverage output parameter to preconditions job
- use collect_coverage parameter as condition for coverage steps and jobs
=> [improve][ci] Disable coverage collection on other than master branch

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockMultiStageAuthenticationProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockMultiStageAuthenticationState.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/utils/ClientChannelHelper.java
PIP: #12105 
When authentication fails in the `ServerCnx`, the state is left in `Start` if the primary `authData` fails authentication and in `Connecting` or `Connected` if the `originalAuthData` authentication fails. To prevent any kind of unexpected behavior, we should go to `Failed` state.
Note that the tests verify the current behavior where a failed `originalAuthData` results first in a `Connected` command from the broker and then an `Error` command. I documented that I think this is sub optimal here https://github.com/apache/pulsar/issues/19311.
* Update `ServerCnx` state to `Failed` when there is an authentication exception during `handleConnect` and during `handleAuthResponse`.
* Update `handleAuthResponse` reply to `"Unable to authenticate"` instead of the `AuthenticationState` …
=> [improve][broker] ServerCnx: go to Failed state when auth fails

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PulsarWorkerService.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerUtils.java
Regression of https://github.com/apache/pulsar/pull/11681
In case of standalone functions worker, the pulsar client connected to the broker doesn't pick up the `brokerClientTrustCertsFilePath` configuration if authentication is disabled.
This causes issues if `TlsEnableHostnameVerification=true` and the certificate is self signed.
I don't think is much critical since non authenticated clusters are very rare when tls is enabled. 
* Pass the `brokerClientTrustCertsFilePath` option if auth is disabled
=> [fix][fn] Fix TLS configuration for fn worker to broker if auth disabled

pulsar-broker/src/test/java/org/apache/pulsar/broker/TestPulsarService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleBrokerStartTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/lookup/http/HttpTopicLookupv2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/OwnershipCacheTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentDispatcherFailoverConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicConcurrentTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentSubscriptionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/web/ProcessHandlerFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientDeduplicationFailureTest.java
Mockito isn't thread safe and excessive usage of Mockito mocks and spies is causing flakiness in tests.
This PR is a follow-up on #19323 and adds more changes. This PR covers also ServerCnxTest which contains
similar flakiness issues as the tests fixed in #19323 . 
Reduce more Mockito spies/mocks in tests.
=> [improve][test] Reduce the use of Mockito spies/mocks in tests

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
In https://github.com/apache/pulsar/pull/19159, we made a change motivated by simplifying the code. However, one problem is that it changed the level of abstraction by calling the `ManagedCursor` class, which could technically have a different definition of `isActive`. In order to retain the original meaning, I am reverting that PR and using a method in the `ManagedLedgerImpl` class to simplify the code.
Other relevant context: https://github.com/apache/pulsar/pull/19159#pullrequestreview-1244210656 and https://github.com/apache/pulsar/pull/19159#discussion_r1067185187
* Revert https://github.com/apache/pulsar/pull/19159
* Use `isCursorActive` method instead.
This is a return to the previous state with a cosmetic change, so the current test coverage should suffice.
No breaking changes.
PR …
=> [improve][ml] Use correct isActive method for cursor

pulsar-broker/src/test/java/org/apache/pulsar/broker/TestPulsarService.java
Cleanup for NonClosableMockBookKeeper is missing in TestPulsarService.
This PR is a follow up for #19323 and #19326 and improves the TestPulsarService that was added in #19323.
- Add cleanup solution to TestPulsarService
- Refactor the brokerServiceFunction (move to the builder)
=> [fix][test] Add cleanup for NonClosableMockBookKeeper in TestPulsarService

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/LedgerOffloaderMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedLedgerMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/MetadataStoreStatsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/SubscriptionStatsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/TransactionBatchWriterMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/TransactionMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerStatTest.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyPrometheusMetricsTest.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyStatsTest.java
Fixes #18300
MetadataStoreStatsTest is very flaky and it causes a lot of builds to fail.
The main reason for the flakiness was the asynchronous broker shutdown.
The solution was to set `brokerShutdownTimeoutMs` to `5000` to prevent the issue where
a metric is unregistered asynchronously while the next method is executing.
There's also a change to log the metrics together with the asserts in MetadataStoreStatsTest. This will help investigate any possible future issues if any remain.
=> [fix][test] Fix flaky MetadataStoreStatsTest and prevent certain flakiness in all metric / stat tests

pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandlerTest.java
If `changeToReadyState` returns false when receiving the `CommandTcClientConnectResponse`, the connection will be closed but the `TransactionMetaStoreHandler` will still be registered.
Add a `registerToConnection` method to handle the case when `changeToReadyState` returns false. In this case, we should fail fast, so complete the `connectFuture` exceptionally and does not register the `TransactionMetaStoreHandler` to `ClientCnx`.
PR in forked repository: https://github.com/BewareMyPower/pulsar/pull/18
=> [improve][txn] Handle changeToReadyState failure correctly in TC client

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicFromMessageTest.java
Fixes #19089
Every manageredLeger has its own thread pool, so there is no ordering guarantee between different topics.
PR in forked repository: https://github.com/labuladong/pulsar/pull/18
=> [fix][test] testSingleTopicConsumerBatchShortName

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Currently, broker allows `bookkeeperEnsemble`,`bookkeeperWriteQuorum`,`bookkeeperAckQuorum` set to <= 0 when set NamespacePersistentPolicies/PersistentTopic policies.
Add value checker to not allow them set to <= 0.
PR in forked repository:  https://github.com/tjiuming/pulsar/pull/16
=> [fix][admin] Fix `validatePersistencePolicies` that Namespace/Topic persistent policies cannot set to < 0 

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java
In the PR https://github.com/apache/pulsar/pull/9302, the property backlog size of each subscription returned in the response of the API topics stats, by default this property is always equal to 0 in response, and this will confuse users. Since the calculation of backlog size is done in broker memory, there is no significant overhead(the process is described in the following section), so I think the correct values should be displayed by default.
- https://lists.apache.org/thread/wvjrp3co9fyl596onwv037944kdz000d
In Pulsar admin API
```
pulsar-admin topics stats persistent://test-tenant/ns1/tp1
--get-subscription-backlog-size
pulsar-admin topics stats persistent://test-tenant/ns1/tp1 -sbs
```
the default value of parameter `--get-subscription-backlog-size` will be `true`
In Pulsar Rest API …
=> [improve] [admin] Make the default value of param --get-subscription-backlog-size of admin API topics stats true

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java
OpReadEntry has been reseted, but count was not reseted.
Reset count to 0
*(or)*
*(or)*
*(example:)*
https://github.com/gaozhangmin/pulsar/pull/9
=> [improve][broker]Fix recycling OpReadEntry without resetting count

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
When there are many concurrent subscriptions in a topic, broker performance degrades because many io-threads are waiting for the lock, `synchronized (activeCursors)` while calling `checkBackloggedCursors`. 
```
"pulsar-io-4-2" #77 prio=5 os_prio=0 cpu=17289.90ms elapsed=170.09s tid=0x00007f85b0085800 nid=0xa2 runnable  [0x00007f859d05e000]
at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.deactivateCursor(ManagedLedgerImpl.java:3526)
- locked <0x00007f8921b24c58> (a org.apache.bookkeeper.mledger.impl.ManagedCursorContainer)
at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.setInactive(ManagedCursorImpl.java:1116)
at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$checkBackloggedCursors$95(PersistentTopic.java:2363)
at …
```
=> [improve][broker] Added isActive in ManagedCursorImpl

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Related to https://github.com/apache/pulsar/pull/19341,
- When there are many concurrent subscriptions in a topic(10k> ), brokers' performance degrades because `checkBackloggedCursors()` iterates all subscriptions for each subscribe call.
```
"pulsar-io-4-2" #77 prio=5 os_prio=0 cpu=17289.90ms elapsed=170.09s tid=0x00007f85b0085800 nid=0xa2 runnable  [0x00007f859d05e000]
at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.deactivateCursor(ManagedLedgerImpl.java:3526)
- locked <0x00007f8921b24c58> (a org.apache.bookkeeper.mledger.impl.ManagedCursorContainer)
at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.setInactive(ManagedCursorImpl.java:1116)
at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$checkBackloggedCursors$95(Persis …
```
=> [improve][broker] Replaced checkBackloggedCursors with checkBackloggedCursor(single subscription check) upon subscription

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Fixes #19265
Reset mock object before reuse.
=> [fix][test] broker.admin.PersistentTopicsTest#testUnloadTopic

pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionCoordinatorClientImpl.java
The parameter `i` passed to `getTCAssignTopicName` cannot be lower than 0. 
Therefore, the method `getTCAssignTopicName` does not need to consider the `partition` < 0. https://github.com/apache/pulsar/blob/ad8d2dfc261b54551d657092165a5b6803b6f4d4/pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionCoordinatorClientImpl.java#L88-L108
https://github.com/apache/pulsar/blob/ad8d2dfc261b54551d657092165a5b6803b6f4d4/pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionCoordinatorClientImpl.java#L115-L122
*(or)*
*(or)*
This change added …
=> [improve][txn]Clean up redundant logic in transaction client

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
In `org.apache.pulsar.broker.admin.AdminResource#internalCreatePartitionedTopic`:
- some logical order can be optimized. For example, can first execute `validateNamespaceOperation` for permission verification.
- some log printing can be merged.see line 596,605,638
https://github.com/apache/pulsar/blob/6a719480b2afc84f5acb85fedf3accf8861eb97a/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java#L612-L622
https://github.com/apache/pulsar/blob/6a719480b2afc84f5acb85fedf3accf8861eb97a/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java#L654-L656
Optimize the logical order and log printing of  `org.apache.pulsar.broker.admin.AdminResource#internalCreatePartitionedTopic`. …
=> [improve][broker] Optimize the logic of internalCreatePartitionedTopic

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
ML uses synchronized to guarantee the atomicity of modifications to variables `ledgers,` `currentLedger`, `currentLedgerEntries` and `currentLedgerSize`, but PR #16420 breaks atomicity, resulting in incorrect results when using those variables(E.g calculate backlog size by special position)
https://github.com/apache/pulsar/pull/16420/files#diff-f6a849bd8fdb782ef6c17a2e07a2c54c3dc7d1655c00ec3546d5f3b3fc61e970L1485-R1499
Make changes to these variables within the synchronized block.
- https://github.com/poorbarcode/pulsar/pull/56
=> [fix] [ml] The atomicity of multiple fields of ml is broken

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsReaderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderImpl.java
In practice, we should release pooled messages in the reader-listener. However, the released message will set `messageId` equals to `null`. And the `acknowledgeCumulativeAsync` method will get this exception.
```java
org.apache.pulsar.client.api.PulsarClientException$InvalidMessageException: Cannot handle message with null messageId
at org.apache.pulsar.client.impl.ConsumerBase.validateMessageId(ConsumerBase.java:392) ~[classes/:?]
at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeCumulativeAsync(ConsumerBase.java:588) ~[classes/:?]
at org.apache.pulsar.client.impl.ReaderImpl$1.received(ReaderImpl.java:105) ~[classes/:?]
at org.apache.pulsar.client.impl.ConsumerBase.callMessageListener(ConsumerBase.java:1124) ~[classes/:?]
at …
```
=> [fix][client] Fix reader listener can't auto ack with pooled message.

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarChannelInitializer.java
Fixes https://github.com/apache/pulsar/issues/13923
When the Java client's `ClientCnx` is initialized, there is a race to set the target broker and the remote hostname. The target brorker is relevant when connecting through the proxy and the remote hostname is relevant for certain kinds of authentication, like SASL. In most cases, this race results in the preferred order where these values are set before the `ClientCnx#channelActive` method is called. However, when that method is called before they are set, problems occur.
This PR ensures that the fields are set before we call `channel.connect(...)`. 
Additional motivation for understanding the correctness of this solution can be found in the relevant netty code:
https://github.com/netty/netty/blob/cbd324c178135a82f23749bc218c2c6ee3a9b140/ …
=> [fix][client] Set fields earlier for correct ClientCnx initialization

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Fix the build error from the pattern-matching variable introduced in https://github.com/apache/pulsar/pull/19343.
the pattern-matching variable is available for java >=14.
Removed the pattern-matching variable.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/25
=> [fix][broker] fixed the build error for pattern matching variable in lower JVM versions

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClient.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionBuilderImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/PulsarClientImplTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/TransactionBuilderTest.java
Submit this PR to discuss if we can accept moving this checked exception into the builder to avoid adding more useless try-catch blocks.
In practice, we should create the new transaction like this:
```java
final TransactionBuilder transactionBuilder;
try {
transactionBuilder = client.newTransaction();
} catch (PulsarClientException e) {
// handle this exception.
return;
}
CompletableFuture<Transaction> txnFuture = transactionBuilder
.withTransactionTimeout(1, TimeUnit.MINUTES)
.build();
```
But this exception only throws by 
```java
public TransactionBuilder newTransaction() throws PulsarClientException {
if (!conf.isEnableTransaction()) {
throw new PulsarClientException.InvalidConfigurationException("Transactions are not enabled");
}
return new TransactionBuilderImpl(this, tcClient);
} …
```
=> [improve][txn] Move checked exception into builder when newTransaction.

conf/broker.conf
Make the `lowerBoundarySheddingEnabled` parameter active.
add lowerBoundarySheddingEnabled config.
=> [improve][broker] Add lowerBoundarySheddingEnabled conf

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java
Cherry-pick https://github.com/apache/pulsar/pull/19157 into branch-2.11
=> [branch-2.11][cherry-pick] Close TransactionBuffer when MessageDeduplication#checkStatus failed

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
If an exception occurs, the compaction task is skipped, but only prints the log at the debug level. It makes compaction that doesn't execute difficult to detect.
change the log level to `warn.`
- https://github.com/poorbarcode/pulsar/pull/59
=> [fix] [broker] print warn log if compaction task skipped cause by ex

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitState.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateCompactionStrategy.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/StrategicTwoPhaseCompactor.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateCompactionStrategyTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/ServiceUnitStateCompactionTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
This PR adds ServiceUnitStateCompactionStrategy.
For the PIP-192, this PR adds the `ServiceUnitStateCompactionStrategy` and its unit tests.
Also, this PR updates the related classes to enable ServiceUnitStateCompactionStrategy:
- Added the `strategicCompactor` member in PulsarService.
- Enabled `ServiceUnitStateCompactionStrategy` for the `tableview` member in ServiceUnitStateChannelImpl.
- Added the `strategicCompactionMap` member in PersistentTopic
- *Added unit tests for the new classes.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/18
=> [improve][broker] PIP-192 Added ServiceUnitStateCompactionStrategy

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/RestClient.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfigTests.java
The current Elasticsearch sink has a setting named `connectionIdleTimeoutInMs`. This setting closes expired and idle http connections opened by the Elasticsearch Rest Client. The current default is 5 milliseconds. With this value, I observed connection issues both for timeouts trying to connect to elasticsearch and errors like "connection reset by peer". When overriding the default to 5 seconds, all errors disappeared. I propose we change it to 30 seconds since even 5 seconds is a little low.
* Change default value for `connectionIdleTimeoutInMs` from 5 millis to 30000 millis
* Remove unnecessary call to `closeExpiredConnections`. This call is unnecessary because the `closeIdleConnections` also closes expired connections. Based on looking at the source code, we iterate over connections …
=> [fix][io] Update Elasticsearch sink idle cnx timeout to 30s

pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStore.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStore.java
Fixes #19200
transaction lasted for long time and will not be aborted, which cause TB's MaxReadPosition do not move and will not take snapshot. With an old snapshot, TB will read a lot of entry while doing recovery.
In worst cases, there are 30 minutes of unavailable time with Topics.
~~make `CoordinatorNotFoundException` retryable.~~
avoid concurrent execution.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/12
=> [fix][txn] fix txn coordinator recover handle committing and aborting txn race condition.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
Since the introduction of the `getTopicPoliciesIfExists` method in #12833. We can use it in other places to avoid catching the exception and to help us better control when to init system client
- Using `getTopicPoliciesIfExists` instead of `getTopicPolicies`.
=> [cleanup][broker] Using `getTopicPoliciesIfExists` to avoid catching the exception

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
Fixes #19366
Admin API `setOffloadThreshold` response before it is finished.
You can reproduce by `AdminApiOffloadTest.testSetNamespaceOffloadPolicies`, If you append `sleep(1000)` after this line(https://github.com/apache/pulsar/blob/1cd1aef3c74fac0a2ded99da05b658578d8481e7/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java#L468), the chances of problems occurring increase to 100%
response after it is finishied
-  https://github.com/poorbarcode/pulsar/pull/60
=> [fix] [admin] setOffloadThreshold response before it's finished

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistry.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryTest.java
This PR should not impact the existing broker load balance behavior.
For the PIP-192 project, this PR
* Implemented broker registry.
* Added units test.
PR in forked repository: https://github.com/Demogorgon314/pulsar/pull/7
=> [improve][broker] PIP-192: Implement broker registry for new load manager

.github/PULL_REQUEST_TEMPLATE.md
=> [cleanup] Remove legacy preview instructions

src/stage-release.sh
The shell distribution files' name are like `apache-pulsar-shell-$VERSION-shell-bin.tar.gz` and `apache-pulsar-shell-$VERSION-shell-bin.zip` which are incorrect in `stage-release.sh`.
Add suffix `-bin`
PR in forked repository: https://github.com/yaalsn/pulsar/pull/17
=> [fix][ci] Fix pulsar shell bin file name

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiOffloadTest.java
https://github.com/apache/pulsar/pull/19370#discussion_r1092918655  Thanks @lhotari  for helping to check
Admin API set offload threshold should fail if namespace policies are read-only.
solve the wrong logic and add test.
- https://github.com/poorbarcode/pulsar/pull/61
=> [fix] [admin] set offload threshold should fail if ns policies is read-only

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
There's a concurrency bug in PersistentTopicsBase#internalGetReplicatedSubscriptionStatus.
A `java.util.HashMap` is used to collect results of concurrent asynchronous method calls. 
- use `ConcurrentHashMap` instead of `java.util.HashMap`
=> [fix][broker] Fix concurrency bug in PersistentTopicsBase#internalGetReplicatedSubscriptionStatus

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
- the possible failure of acknowledging the message isn't handled in ConsumerImpl#processPossibleToDLQ
The `exceptionally` handler in the code below this particular location doesn't get executed, since it's in a different call chain than the `acknowledgeAsync` call. Perhaps that was the author's expectation that the failure would be handled by the `exceptionally` handler.
- complete the future with `false` when there are failures.
=> [fix][client] Fix async completion in ConsumerImpl#processPossibleToDLQ

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
Calling synchronous methods in an async call chain could cause deadlocks and poor performance.
Fix an issue in PersistentTopicsBase#internalSetBacklogQuota
- replace `validatePoliciesReadOnlyAccess` with `validatePoliciesReadOnlyAccessAsync`
=> [fix][broker] Replace sync method in async call chain of internalSetBacklogQuota

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
It is not recommended to run possible blocking operations on Zookeeper event thread, Metadata Store notification thread or Netty IO threads.
Execution could happen unintentionally on these threads since `CompletableFuture` callbacks (`thenCompose`, `thenAccept`, `thenRun`, `whenComplete`, ...) run on the thread that completes the `CompletableFuture`.
In PersistentTopic, there are a few locations where there are potential issues. It's better to run the callbacks on another thread pool when there's a heavy operation or any operation that uses synchronization or locks. 
-  replace `thenAccept` -> `thenAcceptAsync` and `thenRun` -> `thenRunAsync` in a few call chains
- use `brokerService.getTopicOrderedExecutor().chooseThread(topic)` as the executor.
=> [improve][broker] Reduce calls on metadata store / ZK event thread & Netty threads in PersistentTopic

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java
- RangeMap isn't thread safe and should be mutated under the object monitor lock of BucketDelayedDeliveryTracker. Mutating in CompletableFuture callback results in completion of another thread without the lock.
- In Java, it doesn't make sense to use a random object monitor such as `synchronized (this.snapshotSegmentLastIndexTable) {` or `synchronized (this.sharedBucketPriorityQueue) {`. All accesses, both reads and writes should happen under the same object monitor. 
- Possible failures were ignored in the previous code since the removal was executed in `whenComplete` that ignored errors. @coderzc Was this intentional?
- refactor logic in BucketDelayedDeliveryTracker#recoverBucketSnapshot so that asynchronous calls are first waited
to complete and the data structures are updated in the …
=> [fix][broker] Fix currency bug in BucketDelayedDeliveryTracker#recoverBucketSnapshot

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/UnloadDecision.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/NamespaceUnloadStrategy.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLoadDataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java
Master Issue: https://github.com/apache/pulsar/issues/18215
This PR implement PIP-220, https://github.com/apache/pulsar/issues/18215
For the PIP-220(a sub-pip of pip-192, https://github.com/apache/pulsar/issues/16691), this PR implements the TransferShedder and its unit test.
Also, there are minor changes in the related classes:
- Added the `recentlyUnloadedBrokers` input var in NamespaceUnloadStrategy.findBundlesForUnloading(...)
- Added the TransferShedder-related configs in ServiceConfiguration
- *Added unit tests for the new classes.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/16
=> [improve][broker] PIP-220 Added TransferShedder

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java
- there's an incorrect asynchronous composition in admin client's NamespacesImpl#createNamespaceAsync method.
- use `thenCompose` instead of `thenAccept`
=> [fix][client] Fix async method composition in admin client's NamespacesImpl

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
Fixes #19196
The parameters of backlog retention policies need to be clarified. Size limit is only useful in `destination_storage` and time limit is only useful in `message_age`.
1. Make `--limit` optional, because `message_age` doesn't need this parameter but this parameter is `required` now.
2. When the quota type is `message_age`, use the time limit and ignore the size limit. When the quota type is `destination_storage`, use the size limit and ignore the time limit. Don't set them both, which can be confusing for users.
doc update: https://github.com/apache/pulsar-site/pull/394
PR in forked repository: https://github.com/labuladong/pulsar/pull/19
=> [improve][cli] improve admin `set-backlog-quota` more clear

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java
Cherry-pick https://github.com/apache/pulsar/pull/19157 into branch-2.9
=> [branch-2.9][cherry-pick] Close TransactionBuffer when MessageDeduplication#checkStatus failed

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java
Cherry-pick https://github.com/apache/pulsar/pull/19157 into branch-2.10
=> [branch-2.10][cherry-pick] Close TransactionBuffer when MessageDeduplication#checkStatus failed

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryTest.java
Fixes #19401
After unregistering, the other broker registry lock manager's metadata cache might not be updated yet, so we need to wait for it to synchronize.
https://github.com/apache/pulsar/blob/7604d4aef670e31177d803e9f3c4a912be94267f/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/LockManagerImpl.java#L155-L157
Wait for the metadata cache to synchronize after release.
=> [fix][test] Fix flaky test BrokerRegistryTest.testRegisterAndLookup

.github/ISSUE_TEMPLATE/flaky-test.yml
Reporting flaky tests should be simple so that everyone would be reporting flaky tests immediately when they face them.
- provide instructions to copy-paste the stacktrace in a code block
- change the template to a simple code block
=> [improve][misc] Simplify the flaky test issue reporting form

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java, pulsar-broker/src/test/java/org/apache/bookkeeper/mledger/impl/MangedLedgerInterceptorImplTest2.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/MangedLedgerInterceptorImplTest.java
`totalSize` of managed ledger is less than `0`
----
Before writing to BK, `OpAddEntry` records the size of the data to `dataLength`, but if the data is changed by `ManagedLedgerInterceptor.processPayloadBeforeLedgerWrite`, the field `dataLength` of `OpAddEntry` is not changed, which will cause the field `totalSize` and `currentLedgerSize` of managed ledger to be incorrect. 
For example:
1. write data `[1]`, before write BK record the data size by `OpAddEntry.dataLength`.
1-1. now `OpAddEntry.dataLength` is `1`.
2. reset `data` of  OpAddEntry to `[1,2,3...21]` by `ManagedLedgerInterceptor.processPayloadBeforeLedgerWrite`.
2-1. now the actual size of data is `21`, but `OpAddEntry.dataLength` still is `1`.
3. do write BK and switch the ledger
3-1. Create ledger info and put it into …
=> [fix] [ml] Fix the incorrect total size if use ML interceptor

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
Fixes #19418
PersistentTopicTest.testGetReplicationClusters fails consistently. PersistentTopic.initialize() is async and the test didn't wait for it's completion.
replace `topic.initialize()` with `topic.initialize().join()` in PersistentTopicTest class.
=> [fix][test] Fix flaky test PersistentTopicTest.testGetReplicationClusters

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSchemas.java
fix https://github.com/apache/pulsar/issues/19406
change the delete schema command description
change the delete schema command description
=> [improve][doc] Fix delete schema command doc

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java
Found by chance :)
I wonder if it is a real problem, but we judged it in the previous lines. I think the `ex.getCause` probably is null. 
- Avoid NPE
=> [fix][ml]  Fix potential NPE cause future never complete.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Now exceptions that happen in the flow of compaction task are collected into variable `currentCompaction` and don't print any log.
When compaction doesn't work, two reasons come to mind:
- the task skipped by rules.
- the task failed.
We can't determine which causing the problem if there has no log, this increases the difficulty of troubleshooting. 
The API `pulsar-admin topics compaction-status <topic>` lets us see what happens when the last compaction executes, But it can not help us know if there were previous missions that failed.
Print warn log if compaction fails.
- https://github.com/poorbarcode/pulsar/pull/63
=> [improve] [broker] Print warn log if compaction failure

pom.xml
Pulsar build is failing with Java 19 compiler because of an issue in Lombok.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile (default-testCompile) on project pulsar-broker: Compilation failure: Compilation failure:
[ERROR] /Users/mmerli/prg/pulsar/pulsar-broker/src/test/java/org/apache/pulsar/broker/EmbeddedPulsarCluster.java:[38,5] @Builder.Default requires @Builder or @SuperBuilder on the class for it to mean anything.
[ERROR] /Users/mmerli/prg/pulsar/pulsar-broker/src/test/java/org/apache/pulsar/broker/EmbeddedPulsarCluster.java:[41,5] @Builder.Default requires @Builder or @SuperBuilder on the class for it to mean anything.
[ERROR] /Users/mmerli/prg/pulsar/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTes …
```
=> [improve] Upgrade lombok to 1.8.26

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
Upgrade to zk 3.8.1
Release notes: https://zookeeper.apache.org/doc/r3.8.1/releasenotes.html
Among other changes it includes improvement to "Reduce the performance impact of Prometheus metrics".
ZK upgrade
PR in forked repository: https://github.com/dlg99/pulsar/pull/8
=> [improve] Upgrade to zk 3.8.1

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerVersionFilter.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerVersionFilterTest.java
This PR Added `BrokerVersionFilter` to the load balancer extensions and its unit test.
For the pip-192 project, this `BrokerVersionFilter`
- Copy of the existing broker version filter, `org.apache.pulsar.broker.loadbalance.impl.BrokerVersionFilter`.
- Change the interface base on https://github.com/apache/pulsar/pull/18810#discussion_r1053937530
PR in forked repository: https://github.com/Demogorgon314/pulsar/pull/9
=> [improve][broker] PIP-192: Implement broker version filter for new load manager

pom.xml, pulsar-io/debezium/oracle/pom.xml, pulsar-io/debezium/pom.xml
OWASP detects CVE-2022-3143
Upgraded wildfly-eytron (used by debezium) to fix CVE-2022-3143
Upgraded OWASP checker plugin (mainly to pick up version that uses hosted suppressions file to deal with well known false positives).
PR in forked repository: https://github.com/dlg99/pulsar/pull/9
=> [improve] Upgrade wildfly-eytron (used by debezium) to fix CVE-2022-3143

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminImpl.java, pulsar-client-admin/src/test/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImplTest.java, pulsar-client-admin/src/test/java/org/apache/pulsar/client/admin/internal/PulsarAdminImplTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientBuilderImplTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/auth/AuthenticationTokenTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/conf/ClientConfigurationDataTest.java
Authentication for the admin client can not be specified on the `PulsarAdminBuilder` using configuration properties only. 
The `PulsarClientBuilder::authentication` method must be called to set the authentication, currently. 
This is inconsistent w/ the regular PulsarClient which does in fact check for the auth properties [here](https://github.com/apache/pulsar/blob/a2c15340d3a73401b57574a4032ca375bde502bc/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java#L192). 
This works
```java
AuthenticationBasic auth = new AuthenticationBasic();
auth.configure("{\"userId\":\"foo\", \"password\":\"bar\"}");
PulsarAdmin adminWithAuth = PulsarAdmin.builder()
.serviceHttpUrl("...")
.authentication(auth)
.build();
```
This does not work 
```java
Map<String, Object> config = …
```
=> [fix][client] Set authentication when using loadConf in client and admin client

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockAlwaysExpiredAuthenticationProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockAlwaysExpiredAuthenticationState.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
While working on #19409, I noticed we do not have any tests in the `ServerCnxTests` class verifying the `authRole` cannot change. This seems like an oversight, and this PR adds tests to assert the existing behavior works as intended.
* Add new test `AuthenticationProvider` and `AuthenticationState` implementations to simplify testing
* Add two tests to verify the behavior that a connection is closed when the `authRole` changes.
This change is to add tests.
PR in forked repository: Skipping testing in my fork since these are new tests and I got them to pass locally.
=> [improve][broker] Add test to verify authRole cannot change

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
We should reset `individualDeletedMessagesSerializedSize` if all the message is acknowledged. (no more individualDeletedMessages)
- Reset `individualDeletedMessagesSerializedSize=0` when the `individualDeletedMessages.isEmpty()`
=> [fix][ml] Reset individualDeletedMessagesSerializedSize after acked all messages.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java
Close TransactionBuffer when create persistent topic timeout, to learn more context, please see: https://github.com/apache/pulsar/pull/19157
*(or)*
*(or)*
*(example:)*
PR in forked repository:  https://github.com/tjiuming/pulsar/pull/19
=> [fix] Close TransactionBuffer when create persistent topic timeout

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
This PR added operation counters in ServiceUnitStateChannelImpl and its unit test.
- *Added unit tests.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/27
=> [improve][broker] PIP-192 Added operation counters in ServiceUnitStateChannelImpl

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
We have several `Thread.sleep` calls in the `ServerCnxTest` class. Some of them are pretty trivial to remove, and speed the tests up by about 9 seconds when I run on them on my laptop.
* Replace `Thread.sleep(1000)` with `channel.advanceTimeBy(1, TimeUnit.SECONDS);`
This is a change to tests. The tests pass.
PR in forked repository: Skipping because this is a test PR and all modified tests pass on my laptop.
=> [improve][test] Use channel.advanceTimeBy instead of Thread.sleep

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
When an exception occurs in the `canConsumeAsync` method, we should throw that.
=> [fix][authorization] Fix the return value of canConsumeAsync

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckPersistentTest.java
Fixes #19437
The `beforeMethod` doesn't have `alwaysRun=true` so it might happens that the setup is not called, especially in this case since the test class is in `broker` group and the test is in the `quarantine` one
This is probably caused by https://github.com/apache/pulsar/pull/19376/files#diff-ef1ad820ecc095be19dccf2d98e2e3ecd642ca6288d574efc1ee1b643da9e437
* Set `alwaysRun=true`
=> [fix][test] Fix flaky test: PendingAckPersistentTest.testDeleteUselessLogDataWhenSubCursorMoved

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
The intention of https://github.com/apache/pulsar/pull/12780 was to close the whole connection when the client sends an unexpected `Send` command. The goal of that change was to make the broker more defensive to prevent incorrect implementations in the client (see https://github.com/apache/pulsar/pull/12779) from leading to out of order messages.
However, the change in #12780 was too broad. It closes the connection in a very expected case. Specifically, when the server disconnects a producer due to a load balancing or unloading event, the broker sends the client a `CloseProducer` command. If the broker receives any additional messages for that producer, the broker closes the whole connection. This is an expensive interruption for clients with many producers/consumers. Because the Pulsar …
=> [fix][broker] Expect msgs after server initiated CloseProducer

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/bookkeeper/mledger/impl/MangedLedgerInterceptorImplTest2.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/IncrementPartitionsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PartitionKeywordCompatibilityTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/GetLastMessageIdCompactedTest.java
Cherry-pick https://github.com/apache/pulsar/pull/19384 and resolve compatibility issues.
=> [cherry-pick][branch-2.10] Close TransactionBuffer when create persistent topic timeout 

pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarHandler.java
This reverts commit 62e2547bea445c4f67935a57f59886757facbd2d.
The motivation for #12615 relies on an incorrect understanding of Netty's threading model. The `ctx.executor()` is the context's event loop thread that is the same thread used to process messages. The `waitingForPingResponse` variable is only ever updated/read from the context's event loop, so there is no need to make the variable `volatile`.
* Remove `volatile` keyword for `waitingForPingResponse`
Read through all references to the variable.
PR in forked repository: Skipping for this trivial PR.
=> [revert][misc] "modify check waitingForPingResponse with volatile (#12615)"

pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TransactionsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TransactionMetadataStoreServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/TransactionMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/AuthenticatedTransactionProducerConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/TransactionMetadata.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStore.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TxnMeta.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/InMemTransactionMetadataStore.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStore.java, pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/TxnMetaImpl.java, pulsar-transaction/coordinator/src/main/proto/PulsarTransactionMetadata.proto, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/MLTransactionMetadataStoreTest.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStoreProviderTest.java
Super users must be always allowed to abort a transaction even if they're not the original owner.
* Check that only owner or superusers are allowed to perform txn operations (end, add partition and add subscription)
=> [improve][txn] Allow superusers to abort transactions

managed-ledger/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/CounterTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/impl/MetadataStoreFactoryImplTest.java, pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/bookkeeper/test/MockedBookKeeperTestCase.java
We can see that this is a flaky test:
- https://github.com/apache/pulsar/actions/runs/4084265136/jobs/7040983653
When the test is executed, it can be seen from the log that multiple metrics of class `MetadataStoreStats` are registered, and there is one named blank string. So I guess it is caused by other tests not closing `MetadataStoreStats` which is named blank string.
```
pulsar_metadata_store_ops_latency_ms_count{cluster="test",name="",type="get",status="success"} 7.0
pulsar_metadata_store_ops_latency_ms_sum{cluster="test",name="",type="get",status="success"} 0.0
pulsar_metadata_store_ops_latency_ms_created{cluster="test",name="",type="get",status="success"} 1.675430236619E9
pulsar_metadata_store_ops_latency_ms_bucket{cluster="test",name="",type="put",status="fail",le="1.0"} 0.0 …
```
=> [fix] [test] fix flaky test MetadataStoreStatsTest.testMetadataStoreStats

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/BasicKubernetesManifestCustomizer.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/BasicKubernetesManifestCustomizerTest.java
Fixes: https://github.com/apache/pulsar/issues/19478
See issue for additional context. Essentially, we are doing a shallow clone when we needed a deep clone. The consequence is leaked labels, annotations, and tolerations.
* Add a `deepClone` method to the `BasicKubernetesManifestCustomizer.RuntimeOpts` method. Note that this method is not technically a deep clone for the k8s objects. However, based on the way we "merge" these objects, it is sufficient to copy references to the objects.
Added a test that fails before the change and passes afterwards.
This is an internal bug fix. No docs needed.
PR in forked repository: https://github.com/michaeljmarshall/pulsar/pull/27
=> [fix][fn] Fix k8s merge runtime opts bug

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerWrapper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannel.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLoadData.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/AssignCounter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/SplitCounter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/SplitDecision.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/UnloadCounter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/UnloadDecision.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
This PR implemented ExtensibleLoadManagerWrapper.getLoadBalancingMetrics()and its unit test.
- *Added unit tests.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/28
=> [improve][broker] Implemented ExtensibleLoadManagerWrapper.getLoadBalancingMetrics()

pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolTest.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolWsTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/AbstractCmdConsume.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdRead.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java, pulsar-client-tools/src/test/java/org/apache/pulsar/client/cli/TestCmdRead.java
I thought it would be convenient to create a reader easily with CLI, so I added the read command to pulsar-client-tools.
Example of use:
```sh
$ ./bin/pulsar-client read -m 48:-1 -n 5 persistent://public/default/t1
----- got message -----
key:[null], properties:[], content:m0
----- got message -----
key:[null], properties:[], content:m1
----- got message -----
key:[null], properties:[], content:m2
----- got message -----
key:[null], properties:[], content:m3
----- got message -----
key:[null], properties:[], content:m4
```
=> [feat][cli] Add read command to pulsar-client-tools

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ResendRequestTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicsConsumerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ZeroQueueSizeTest.java
We cannot distribute the load of multiple topics to multiple consumers for the Failover subscription because only the first consumer will be taken if the topic is not partitioned.
https://github.com/apache/pulsar/blob/950ff441da28e144bdfb71c317a9bc339d4f05b7/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java#L96-L97
So, if you subscribe with the topic list or topic regex, the first connected consumer will be the active consumer of all the topics. Kafka has a [consumer group coordinator](https://developer.confluent.io/learn-kafka/architecture/consumer-group-protocol/), which can rebalance the load. 
For Pulsar, we don't have a consumer group coordinator. So this PR tries to introduce a consistent hash mechanism to peek the active …
=> [improve][broker] introduce consistent hash ring to distribute the load of multiple topics subscription

conf/log4j2.yaml
Fixes #19494
when we use RollingFile, we found  log4j2 delete strategy does not work, because the configuration item `IfFileName:
glob: "*/${sys:pulsar.log.file}*log.gz"`  in log4j2.yaml  has wrong dir path,  "*/" of IfFileName should be removed  to make log4j2 delete strategy work.  
in the log4j2.yaml :
```
fileName: "${sys:pulsar.log.dir}/${sys:pulsar.log.file}
DefaultRolloverStrategy:
Delete:
basePath: ${sys:pulsar.log.dir}
maxDepth: 2
IfFileName:
glob: "*/${sys:pulsar.log.file}*log.gz"
IfLastModified:
age: 30d
```
DefaultRolloverStrategy's IfFileName  has different dir path with  log fileName,  the "*/" of  IfFileName  in should be removed, when we change it into  `glob: "${sys:pulsar.log.file}*log.gz"`, delete strategy works!
remove  "*/"  of IfFileName in log4j2.yaml
=> [fix][broker]: make log4j2 delete strategy work

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
Fixes #19431 
`authenticationData` is already `volatile`. We use `originalAuthData` when set, so we should match the style. In #19431, I proposed that we find a way to not use `volatile`. I still think this might be a "better" approach, but it will be a larger change, and since we already use `volatile` for `authenticationData`, I think this is the right change for now.
It's possible that this is not a bug, given that the `originalAuthData` does not change frequently. However, we always want to use up to date values for authorization.
* Add `volatile` keyword to `ServerCnx#originalAuthData`.
PR in forked repository: skipping test in fork.
=> [fix][broker] Make ServerCnx#originalAuthData volatile

pulsar-client/src/main/java/org/apache/pulsar/client/impl/AutoClusterFailover.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ControlledClusterFailover.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/AutoClusterFailoverTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ControlledClusterFailoverTest.java
When we use cluster level failover and enabled authentication, we found the authentication couldn't update in the HttpLookupService. The root cause is that the HttpLookupService cached the httpClient, but the `updateServiceUrl` only updates the target serviceUrl for the httpClient, without any updates for authentication.
https://github.com/apache/pulsar/blob/70c4003c5c5ef6d911f639d946c235721b6d0e67/pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpLookupService.java#L65-L75
Call `pulsarClient.reloadLookUp()` to update the authentication manually when the target cluster is switched.
*(or)*
This change is already covered by existing tests, such as *(please …
=> [fix][client] Fix authentication not update after changing the serviceUrl

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
Cleanup `finalPosition` null-check in `asyncFindPosition` method. Because `startPosition` null-check has been checked at line1785.
Cleanup `finalPosition` null-check in `asyncFindPosition` method
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/28
=> [cleanup][broker] Cleanup finalPosition null-check in asyncFindPosition

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerBuilderImplTest.java
Fixes #19134
The java client automatically sets a 30s `ackTimeout` when a `deadLetterPolicy` is configured. This behavior was added before there was any ability to `negativeAcknowledge`. Now that `negativeAcknowledge` exists, it is unnecessary. Furthermore, it is confusing and inconsistent - more details in the issue.
Removed setting `ackTimeoutMillis` in java `ConsumerBuilder` when a `deadLetterPolicy` is set.
This change is already covered by existing tests, such as *ConsumerBuilderImplTest*.
=> [improve][client] Remove default 30s ackTimeout when setting DLQ policy on java consumer

pulsar-sql/pom.xml, pulsar-sql/presto-distribution/LICENSE, pulsar-sql/presto-distribution/pom.xml, pulsar-sql/presto-pulsar/pom.xml
The secure problem CVE-2017-1000487 is caused by the dependency `org.codehaus.plexu:plexus-utils:2.0.6`. Refer to [this](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-1000487).
> CVE-2017-1000487
> Plexus-utils before 3.0.16 is vulnerable to command injection because it does not correctly process the contents of double quoted strings.
The dependency tree is this.
```
io.prestosqlpresto-main:332
-- io.airlift.resolver:resolver:1.5
-- org.apache.maven:maven-core:3.0.4
-- org.codehaus.plexus:plexus-utils:2.0.6
```
I try to exclude `org.codehaus.plexus:plexus-utils:2.0.6` and import `org.codehaus.plexus:plexus-utils:3.0.16`, the Pulsar SQL still work.
Exclude the dependency `org.codehaus.plexus:plexus-utils:2.0.6`, and import `org.codehaus.plexus:plexus-utils:3.0.16`.
*(Please pick …
=> [fix][security] Fix secure problem CVE-2017-1000487

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
I broke all release branches when I cherry picked 2847dd19f6e8a546f4d45bf51eb2b72aae0869ce to them. This change takes some of the underlying logic from #19409, without taking the async logic.
* Make changes to `ServerCnx` to make tests pass
Tests are currently failing, so passing tests will show that this solution is correct.
=> [fix][broker] ServerCnx broken after recent cherry-picks

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
There is a problem in my environment, a bundle cannot be loaded to an empty broker(no bundles on it). 
I found that this empty broker still has preallocatedBundleData on it which caused the score is higher than others.
https://github.com/apache/pulsar/blob/c890a8c15cd9d30518818377c3155776514f5a9c/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastLongTermMessageRate.java#L53-L78
This issue is caused by the preallocatedBundleData is not cleared from brokerData. LINE 573 and LINE 580 is the condition  of clearing preallocatedBundleData.  
There is a corner case, which bundle is unload before broker data reportted to Zookeeper.  the preallocatedBundleData  would never have the chance of clearing from loadData of leader. …
=> [fix][broker] Fix loadbalance score caculation problem

pom.xml
OWASP dependency checks are currently failing on some other PRs (e.g. https://github.com/apache/pulsar/actions/runs/4180151982/jobs/7241507184).
```
Error:  Failed to execute goal org.owasp:dependency-check-maven:8.0.1:aggregate (default) on project pulsar: 
Error:  
Error:  
Error:  kafka-clients-2.8.2.jar: CVE-2023-25194(8.8)
Error:  
Error:  See the dependency-check report for more details.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read …
```
=> [fix][sec] Upgrade kafka client to 3.4.0 to fix CVE-2023-25194

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarServiceNameResolver.java
Fixes #17080
`PulsarServiceNameResolver` is used to randomly select a service name from multiple service names, the logic is:
- select a random index of the service name list
- if the previous service name can not work, use `{previous index} + 1`
But when we call the method `PulsarWebResource.getRedirectionUrl`, it will always create a new `PulsarServiceNameResolver` instance, this reduces the above logic to only randomly select a service name.
You can reproduce by `ReplicatorTest.activeBrokerParse` (the more invalid service names in variable `cluster2ServiceUrls`, the greater the probability of a problem).
But when we call the method `PulsarWebResource.getRedirectionUrl`, reuse the same `PulsarServiceNameResolver` instance.
- …
=> [fix] [broker] Incorrect service name selection logic

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImpl.java
Cleanup ManagedLedgerImpl's nouse method: isLedgersReadonly
Cleanup ManagedLedgerImpl.isLedgersReadonly.
PR in forked repository: https://github.com/StevenLuMT/pulsar/pull/5
=> [cleanup][broker] Cleanup ManagedLedgerImpl's nouse method: isLedgersReadonly

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
see https://github.com/apache/pulsar/pull/19505#discussion_r1107373967
`PulsarServiceNameResolver` is used to randomly select a service name from multiple service names, the logic is:
- select a random index of the service name list
- if the previous service name can not work, use `{previous index} + 1`
But when the cache of`PulsarServiceNameResolver` refreshes, it will create a new `PulsarServiceNameResolver` instance, which will break the logic "if the previous service name can not work, use `{previous index} + 1`"
Make the service name resolver cache of PulsarWebResource expire after access
- https://github.com/poorbarcode/pulsar/pull/69
=> [fix] [broker] Make the service name resolver cache of PulsarWebResource expire after access

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
Fixes #19536
Please check #19536 for details about the problem this PR fixes. 
This backports changes from #19015 to branch-2.10 for replacing a sync method call in async call chain.
In addition, there's a test and an improvement to the #19015 solution which would attempt to execute the call
also for partitioned topics. I'll submit a separate PR to fix that issue in master / branch-2.11.
=> [fix][broker][branch-2.10] Replace sync method call in async call chain to prevent ZK event thread deadlock

pulsar-client-admin-shaded/pom.xml, pulsar-client-all/pom.xml, pulsar-client-shaded/pom.xml
I tried to use the latest Java client with the authentication plugin, but it threw the following exception:
```
Exception in thread "main" org.apache.pulsar.client.api.PulsarClientException$UnsupportedAuthenticationException: java.lang.NoClassDefFoundError: org/apache/pulsar/shade/com/fasterxml/jackson/datatype/jdk8/Jdk8Module
at org.apache.pulsar.client.api.AuthenticationFactory.create(AuthenticationFactory.java:110)
at org.apache.pulsar.client.impl.ClientBuilderImpl.authentication(ClientBuilderImpl.java:138)
at SampleConsumer.main(SampleConsumer.java:42)
Caused by: java.lang.NoClassDefFoundError: org/apache/pulsar/shade/com/fasterxml/jackson/datatype/jdk8/Jdk8Module
at org.apache.pulsar.client.impl.AuthenticationUtil.<clinit>(AuthenticationUtil.java:35)
at …
```
=> [fix][client] Shade com.fasterxml.jackson.datatype.* to prevent ClassNotFoundException

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/InMemoryRedeliveryTracker.java
Currently, the `trackerCache` uses a ConcurrentLongLongPairHashMap that does not shrink, causing `trackerCache` to occupy a large amount of memory and has no way to release it.
By monitoring the market through the JVM, we can see that during that time period, Young GC and Full GC have been frequently triggered, resulting in a large delay in Young GC and Full GC, which in turn affects production and consumption.
But what is interesting is that we can see that after the Young GC and Full GC are triggered many times, the memory in the heap is not reclaimed, so the Young GC and Full GC are triggered frequently.
Therefore, based on the above background, we made a memory dump of the Broker node and found that the set of trackerCache occupies most of the memory and this part of memory uses a …
=> [improve][broker] Use shrink map for trackerCache

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockAuthenticationProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockMutableAuthenticationProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockMutableAuthenticationState.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
In the authentication:
- With the proxy, the broker stores the client authentication to the `originalAuthData` and `originalPrincipal`, and stores the proxy authentication to the `authenticationData` and `authRole`.
- Without the proxy, the broker stores the authentication to the `authenticationData` and `authRole`
When with the proxy, the broker only checks whether `originalAuthData` is expired. If true, the broker sends `AuthChallenge` to the client, then the client sends `CommandAuthResponse`.
In `handleAuthResponse` logic, the broker always stores the authentication to `authenticationData` and `authRole`, without considering the proxy case. When the authorization provider checks the role and authentication data, it is unmatched, this is incorrect behavior, so we need to distinguish …
=> [fix][authentication] Store the original authentication data

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
- resetCursor isn't supported for partitioned topics. However, in the previous async call solution made by #19015, the async call chain wasn't terminated when the condition failed.
- throw the exception instead of completing the async request
- add a test case
=> [fix][broker] Terminate the async call chain when the condition isn't met for resetCursor

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
PIP192 admin API also used `destinationBroker`, we need to refactor the `setNamespaceBundleAffinity` method to `setNamespaceBundleAffinityAsync`, so we can set use `destinationBroker` in the same method.
=> [refactor][admin] Refactor namespace bundle transfer admin api

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
Fixes #19083 
Fixes #11866 
Currently, the force delete namespace operation has the following steps:
1. Do pre-check
2. Get full of topics
3. Mark the namespace as `deleted` to avoid creating the topic again by client lookup or reconnect.
4. Delete all of the user-created topics
5. Delete all system topics.
6. Delete namespace event topics.
7. clean up namespace metadata and resources
A race condition will make step 2 unable to get full of topics. e.g:
| -      | Thread A                                                                                 | Thread B                                                    |
|--------|------------------------------------------------------------------------------------------|-------------------------------------------------------------|
| time 1 | Got …
=> [fix][broker] Fix delete namespace fail by a In-flight topic

conf/bkenv.sh
PIP: #xyz 
In #13025, 
In bkenv.sh, it move `BOOKIE_MEM`, `BOOKIE_GC` out from `BOOKIE_EXTRA_OPTS`.
In bin/bookkeeper, use `OPTS="$OPTS $BOOKIE_MEM $BOOKIE_GC $BOOKIE_GC_LOG $BOOKIE_EXTRA_OPTS"`.
So it works.
In https://github.com/apache/pulsar/commit/1fa9e1e9c9cd662c7db7a6ceec10d96dfa70d981, it cherry-pick to branch-2.9.
It miss the #13025, and remove `BOOKIE_MEM`, `BOOKIE_GC`. So, the param `BOOKIE_MEM`, `BOOKIE_GC` were missed.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment …
=> [fix][Branch-2.9] Fix bookie JVM param `BOOKIE_MEM`, `BOOKIE_GC` miss problem.

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Based on the previous two PRs #9552 and #16228,
Logger.warn usage bug fix: the number is inconsistent for format and arguments
add a argument in Logger.warn's arguments, the value is the dead letter topic's name
PR in forked repository: https://github.com/StevenLuMT/pulsar/pull/6
=> [fix][client] Logger.warn usage bug fix: the number is inconsistent for format and arguments

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerErrorsTest.java, testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockBookKeeper.java, testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockLedgerHandle.java
In the test `ManagedLedgerErrorsTest.recoverLongTimeAfterMultipleWriteErrors`, it mocks two errors of add entries, then verify that the final write succeeds.
But the event of add entry failure triggers two other operations: `delete current ledger` and `create a new ledger`, these two operations have the probability of consuming the error events that were mocked earlier. As a result, the intent of the test is not being performed correctly.  If the error event is consumed by `create a new ledger`, it will make the test unstable， see: https://github.com/apache/pulsar/actions/runs/4195006942/jobs/7274314432
You can reproduce the issue by the test `recoverLongTimeAfterMultipleWriteErrors` in the current PR, adding `sleep(1000)` after line 541 before line 542 increases the probability of …
=> [fix] [test] Wrong mock-fail of the test ManagedLedgerErrorsTest.recoverLongTimeAfterMultipleWriteErrors

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
Fixes #19535
Original code only guarantee one consumer reconnected, the other consumer may not finish reconnecting, so there is only one consumer in subscription. Now use `Awaitility` to guarantee two consumers reconnected.
=> [fix][test] flaky test: testOnlyCloseActiveConsumerForSingleActiveConsumerDispatcherWhenSeek

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentDispatcherFailoverConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentFailoverE2ETest.java
1. The single consumer dispatcher selects consumer according to the name order of consumers. The test `testSimpleConsumerEventsWithPartition` is also written according to this rule. After PR #19502, the dispatcher no longer selects consumers in the order of registration, so the test becomes unstable.
2. And the same thing is true for `PersistentDispatcherFailoverConsumerTest.testAddRemoveConsumerNonPartitionedTopic`
3. In the original implementation, non-partitioned topic did not care about the priority of consumers, but after PR #19502, it began to care about the priority of consumers, which also led to the instability of `PersistentDispatcherFailoverConsumerTest.testAddRemoveConsumerNonPartitionedTopic
` test
- fix flaky test PersistentFailoverE2ETest.testSimpleConsumerEventsWithPartitio …
=> [fix] [test] fix flaky test PersistentFailoverE2ETest.testSimpleConsumerEventsWithPartition

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
Unstable ZK connections can cause these conditions to occur: 
1. add entry timeout(because the connections of BK to ZK is also unstable)
1. write ZK fail when ledger info update
1. delete ledger is delayed(because delete meta is delayed)
1. and so on
When cases `1,2,3` occur at the same time, a ledger that is in use may be deleted. for example:
- add entry(`3:0`) timeout(eventually successful)
- the field `lastConfirmedPosition` of the current ledger is still `-1`
- the ledger info of ML is `[3]` now.
- switch ledger caused by add entry fail, but write ZK is also failure.
- delete ledger `3` async (because `lastConfirmedPosition == -1`), and the operation is delayed.
- topic reload caused by lost ZK connection, close old ML and create new
- execute `ml.recover`
- ledger `3` is not removed …
=> [fix] [ml] topic load fail by ledger lost

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorAdminTlsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorAdminTlsWithKeyStoreTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java
We set the TLS and auth on the `ClusterData`. When using the geo-replication feature, the Broker only read the TLS and auth config from the Pulsar config for creating the admin, and the broker ignores the `ClusterData` config. In fact, the `ClusterData` actually takes precedence over the Pulsar config.
- Fix the auth config, when is `null`, fallback to the Pulsar config
- Fix the TLS config
- When `ClusterData#isBrokerClientTlsEnabled` is `true`, use the TLS config from `ClusterData`
- When `ClusterData#isBrokerClientTlsEnabled` is `false`, fallback to the Pulsar config
This logic is the same with the `org.apache.pulsar.broker.service.BrokerService#getReplicationClient`.
=> [fix][broker] Fix geo-replication admin

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProvider.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationService.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/OneStageAuthenticationState.java
With https://github.com/apache/pulsar/pull/19573, we should replace deprecation warnings that were set to 2.12.0 with 3.0.0.
* Update 4 deprecation warnings.
This is cosmetic.
This is a documentation change.
PR in forked repository: skipping forked PR since this is a trivial change
=> [cleanup][broker] Update deprecation warnings to use 3.0.0

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/PositionAckSetUtil.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/BitSetRecyclableRecyclableTest.java
There're some cases of consumers receiving duplicated messages when there are ongoing transactions within a subscription.
#14327  has fixed this problem partially. But there's still a chance for consumers to receive duplicated messages.
1. For non-batch messages, the dispatcher does not filter messages in the pendingAck state(PendingAckHandleImpl#individualAckPositions)
2. For batch messages,  if the ackSet in pendingAck state is complimentary with the ackSet in the cursor, the broker still dispatches this entry to the consumer.  For example, a batch message has 5 messages internal,  cursor stats has acked `0,1,2` and pendingAck stats has acked `3,4`, this message should not dispatch to the consumer, but actually, it does.
1. filter messages in pendingAck for non-batch messages
2. filter …
=> [fix][txn]fix receive duplicated messages due to pendingAcks in PendingAckHandle

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConnectionPoolTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarChannelInitializer.java
Regression of https://github.com/apache/pulsar/pull/19327 (It only affects **dev** branches since no release have been done containing that pull)
in the client, to understand if is connected through a proxy, it checks the logical address vs the physical one, if they're different it supposes it has to target that specific broker passing through the proxy.
In the above pull request, the comparison logic is changed and the logical address is compared to ONE of the resolved dns names. in case of multiple dns names of the proxy, it might happens that the first resolved dns name doesn't match with the logical proxy address and therefore it's considered to be a broker dns name.
This leads to the proxy to recursive send connections to itself.
These are some logs extracted: 
```
11:02:35.141 …
```
=> [fix][client] Broker address resolution wrong if connect through a multi-dns names proxy

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
In https://github.com/apache/pulsar/pull/19467 we introduced a couple of possible issues about thread-safety of the `BaseCommand` and `ServerCnx` instances.
Original comments from @michaeljmarshall :
- https://github.com/apache/pulsar/pull/19467#discussion_r1101827289
- https://github.com/apache/pulsar/pull/19467#discussion_r1101815870
* Get the auth fields in the same thread of the connection
* Copy partitionList instead of reading it in another thread
=> [fix][broker] Copy command fields and fix potential thread-safety in ServerCnx

wiki/proposals/PIP.md
Mailing list discussion seems to use the prefix "[DISCUSS] PIP-xxx: ", so it makes sense to update the PIP wiki accordingly.
=> [improve][doc] Changing subject prefix for PIPs in the mailing list

wiki/proposals/PIP.md
Clarify in the PIP process where to take the number from.
=> [improve][doc] Clarify where to grab the number for the PIP

pulsar-common/src/main/java/org/apache/pulsar/common/util/keystoretls/KeyStoreSSLContext.java
When the trust store file is empty, we can skip loading the trust store file, because there is using the trust store file from the operating system.
- Add check and load the `tlsTrustStorePath` to the `KeyStoreSSLContext`
=> [fix][client] Fix load the trust store file

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
Relates to: https://github.com/apache/pulsar/pull/19540
We currently filter out the `clientVersion` when it has a `" "` in it. As a consequence, we filter out the go client's version because of how it is made:
https://github.com/apache/pulsar-client-go/blob/dedbdc45c63b06e6a12356785418cd906d6bab3c/pulsar/internal/version.go#L43
Given that we do not have any documented restrictions on the `clientVersion`, I think we should not drop clients that have a space in their name.
I propose that we remove the filter logic to store all "valid" versions supplied by the client.
* Update `ServerCnx` to store `clientVersion` when it has a space in its name.
A new test is added.
This is a backwards compatible change.
PR in forked repository: skipping for this minor change that shouldn't make any tests …
=> [improve][broker] Store nonBlank clientVersions that have spaces

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
I meet a issue that NPE happend in ServerCnx.handleSend() but the debug log does not print stack trace.
print stack trace when got excpetion in ServerCnx
=> [improve][broker] Print stack trace when got excpetion in ServerCnx

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LeastResourceUsageWithWeight.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java, pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerData.java, pulsar-common/src/test/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerDataTest.java
Even for a Broker with a very low load, its memory will grow slowly until GC is triggered. If memory is used as a load calculation item, the Bundle will be unloaded by mistake
Remove memory as load calculation item 
Existing unit tests need to pass all
https://github.com/315157973/pulsar/pull/5
=> [fix][broker] Remove useless load balancer items about MemoryResourceWeight

.github/PULL_REQUEST_TEMPLATE.md
This PR replaces google link with official link.
=> [fix][doc] update link for Pulsar PR Naming Convention Guide

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedSubscriptionStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionStats.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/TopicStats.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java
In #15867, we provide namespace level and topic level metrics for delayedDeliveryTracker's memory usage, but we do not export subscription level metrics, we also should export subscription level metrics.
* Export `pulsar_delayed_message_index_size_bytes` in the subscription level
* Export `delayedMessageIndexSizeInBytes` in the SubscriptionStats and TopicStats
* Unified the variable name: `delayedTrackerMemoryUsage` -> `delayedMessageIndexSizeInBytes`
* Also export `pulsar_delayed_message_index_size_bytes` when use `BucketDelayedDeliveryTracker`
*(or)*
*(or)* …
=> [improve][broker]Export `pulsar_delayed_message_index_size_bytes` in subscription level

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/Stat.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreBatchingTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreExtendedTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
All currently available MetadataStore implementations assign versions to key-value pairs the same way: when a new pair is created, it is assigned version 0, and each subsequent modification increases the version by one. Actually, Pulsar does not need such a strict versioning scheme; it is enough that 
* all versions are positive
* later versions are greater
* and the metadata store can inform us if a given Stat is represents the first version.
Introduced Stat.isFirstVersion that practically defaults to version==0
Relaxed the requirements imposed by the tests to only test what is actually necessary for Pulsar.
This change is already covered by existing tests, such as the test modified by this PR. …
=> [improve][meta]Allow version to start positive and grow by more than one

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ClientCnxTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java
Currently,  the `client_version ` only shows the version information. And clients in different languages use their own separate version numbers. This can lead to conflict. For example, the java client 2.10.2 uses the same value `2.10.2` as the C++ client 2.10.2. And C++ client 3.0.0 may conflict with the future java client 3.0.0. The information of `client_version` is incomplete. We could not determine what language(or specific library) the client uses. This raises inconvenience for debugging.
This PR adopts a new client version format for the Java client.
Please see the discussion: https://lists.apache.org/thread/n59k537fhthjnzkfxtc2p4zk4l0cv3mp
* Change Java client version value to `Pulsar-Java-vXXX`
PR in …
=> [improve][client] Refactor client version format

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
I noticed the following warn log output on a broker server.
```
14:03:44.580 [pulsar-io-24-26] WARN  o.a.pulsar.broker.service.ServerCnx  - [/xxx.xxx.xxx.xxx:35144] Got exception {}
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```
I think the expected behavior is that the summary of the exception `cause` is embedded in the placeholder `{}`, but actually the stacktrace is printed.
https://github.com/apache/pulsar/blob/6d3e483bab0f960b21cb521fb3908eccd55993b6/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L389-L391
Apparently, exceptions are embedded when log4j2 is used, but not when logback is used.
Stringify `cause` to embed it in the placeholder.
=> [fix][broker] Embed stringified exception in placeholder in log message

pom.xml, pulsar-client-auth-athenz/pom.xml
In https://github.com/apache/pulsar/pull/19445, I added import statements for the `com.oath.auth.*` classes to the `AuthenticationAthenz` class. These classes are in a package named `athenz-cert-refresher`, so we should add a dependency on this package. However, due to the indirect dependency, `athenz-cert-refresher` will be installed without doing this and the build will not fail.
=> [fix][client] Add explicit dependency on athenz-cert-refresher

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
- Contains important Netty bug fixes and improvements
- Upgrade Netty to 4.1.89.Final and io_uring transport to 0.0.18.Final
- Release notes: 
- 4.1.88.Final: https://netty.io/news/2023/02/12/4-1-88-Final.html
- 4.1.89.Final: https://netty.io/news/2023/02/13/4-1-89-Final.html
- io_uring 0.0.18.Final: https://netty.io/news/2023/02/22/io_uring_0-0-18-Final.html
=> [improve][misc] Upgrade Netty to 4.1.89.Final

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java
There is a race condition while creating a Connection and putting it into the cache.
The operation may fail before that the CompletableFuture is put into the pool map and so cleanupConnection fails to remove the new connection from the map (because it is not there yet)
This is very likely to happen on k8s while a broker is not "ready"
The problem is that UnknownHostException fails very quickly (probably on the same thread), and the "exceptionally" block is executed before we put the CompletableFuture into the `pool` map, and so the "remove" operation fails
Eagerly remove the CompletableFuture from the cache if it is "failed".
There is no need to retry, the client eventually will retry, and also retrying immediately will probably fail.
I am not adding tests, this race condition is hard to …
=> [fix][client] Fix race condition that leads to caching failed CompletableFutures in ConnectionPool

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
Fixes #xyz
PIP: #xyz 
BookKeeper 4.14.7 has been released and it contains a lot of notable bug fixes. We need to upgrade the BookKeeper dependency from 4.14.5 to 4.14.7.
BookKeeper release notes can be found:
https://github.com/apache/bookkeeper/releases
*(or)*
*(or)*
*(example:)*
=> [improve][branch-2.10]upgrade the bookkeeper version to 4.14.7

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
An minor improvement by replacing `ScheduledExecutorService` to `ExecutorService` in ModularLoadManagerImpl
Replace ScheduledExecutorService to ExecutorService in ModularLoadManagerImpl
https://github.com/AnonHxy/pulsar/pull/30
=> [improve][broker] Replace ScheduledExecutorService to ExecutorService in ModularLoadManagerImpl

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateCompactionStrategy.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateData.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateCompactionStrategyTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateDataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/ServiceUnitStateCompactionTest.java
There is a possible edge case where bundle ownership could be negatively impacted by delayed commands in the new load balancer.
Let's say a (network-partitioned) broker has a delayed `ServiceUnitStateChannel` and triggers a transfer or unload command based on it. This transfer or unload command should be rejected as it is from an outdated context. 
To reject this outdated transition, I propose `versionId` in `ServiceUnitStateData`, which monotonically increases for its subsequent state changes until tombstoned. `ServiceUnitStateCompactionStrategy` can reject messages with older versions than the previous ones(assert prev+1 == cur).
After this PR,
... Owned(versionId=50) -> Transfer_Assigned(versionId=45) // invalid 
... …
=> [improve][broker] PIP-192: Added VersionId in ServiceUnitStateData

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/GetLastMessageIdCompactedTest.java
Branch-2.9 keeps cherry-picking new PRs without build success and leads to new PRs pushed to the branch-2.9 build failed. https://github.com/apache/pulsar/pull/19178. Fix the build issue in that PR doesn't make sense.
Make branch-2.9 build succeed.
=> [Branch-2.9] [build] fix build failed

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/BrokerMonitor.java
This PR 
- added `--extensions` option in BrokerMonitor in order to monitor BrokerLoadData in Load Balance Extension.
```
pulsar %  bin/pulsar-perf monitor-brokers --connect-string pulsar://localhost:6650 --extensions
2023-02-27T18:02:33,417-0800 [pulsar-client-io-1-3] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x330e1af9, L:/127.0.0.1:56972 - R:localhost/127.0.0.1:6650]] Connected to server
2023-02-27T18:02:33,551-0800 [pulsar-client-io-1-3] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [non-persistent://pulsar/system/loadbalancer-broker-load-data][reader-617fc4e8f9] Subscribing to topic on cnx [id: 0x330e1af9, L:/127.0.0.1:56972 - …
```
=> [improve][broker] PIP-192 Added --extensions option in BrokerMonitor

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadSheddingStrategy.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedderTest.java
When a broker in the cluster is not active, its load still remain in the memory of the Leader. 
If deployed in a container, brokers will scale up and down frequently, and the memory of the Leader gradually increase
When a broker is no longer active, delete its load information
https://github.com/315157973/pulsar/pull/6
=> [fix][broker] Fixed history load not releasing

conf/broker.conf, conf/websocket.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactorTool.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketProxyConfiguration.java, pulsar-websocket/src/test/java/org/apache/pulsar/websocket/WebSocketProxyConfigurationTest.java
When we merged #15818 in order to make the broker's client configurable, we did not add an explicit config for hostname verification. This PR adds that config to the broker and the websocket proxy. I chose the name `tlsHostnameVerificationEnabled` because that is what is already used in the proxy. It diverges from the function worker's config of `tlsEnableHostnameVerification`.
Before this PR, you would have enabled hostname verification by configuring `brokerClient_tlsHostnameVerificationEnable=true` in the broker and WS proxy configs. (Note that the variable name is slightly different because the `ClientConfiguration` does not have a `d` at the end of its name.
The remaining follow up work will be to update the `ClusterData` objects to configure hostname verification there to make it …
=> [improve] Simplify enabling Broker, WS Proxy hostname verification

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/LedgerOffloaderStatsImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/LedgerOffloaderMetricsTest.java
The `LedgerOffloaderStatsImpl` singleton close method can't be called twice due to wrong condition in the close method.
Also not every metric is unregistered from the prometheus collector.
Also there might be concurrency issues while closing.
I've noticed that the test `LedgerOffloaderMetricsTest` often fails if the topic test method is executed after the namespace one.
This is because the assertions in the namespace test are not strict enough to catch the error. 
* Set the singleton instance to null after closing
* Unregister all the metrics
* Add `synchronized` to the close method which makes sense since the creation method is synchronized too
* Fix assertion in LedgerOffloaderMetricsTest to be more precise
=> [fix][broker] Fix LedgerOffloaderStatsImpl singleton close method

pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java
A minor typo fix.
Update `ClientConfigurationData` by replacing `proxy` with `client`.
This is a doc change.
=> [fix][client] Fix typo in Java doc for ClientConfigurationData

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitState.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateCompactionStrategy.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateData.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateCompactionStrategyTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateDataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/ServiceUnitStateCompactionTest.java
As part of the PIP implementation: https://github.com/apache/pulsar/issues/16691
I propose switching `Assigning` and `Releasing` state order in the transfer protocol to the following.
Before:
Owned -> Assigning -> Releasing -> Owned
After:
Owned -> Releasing -> Assigning -> Owned
Reasoning:
- The broker states in the assigning state are consistent in both transfer and assign commands in that the dst broker acks the ownership by publishing own message.
- In the future, it will be easier to make the transfer command 2pc (Owned -> Releasing -> Owned) to optimize the transfer protocol latency, if required. For the 2pc, with this change, we can make the src broker publish `Own` message right after `Releasing`(optimistically assuming …
=> [improve][broker] PIP-192 Switched Assigning and Releasing state order in the transfer protocol

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
cherry-pick https://github.com/apache/pulsar/pull/18999
*(or)*
*(or)*
*(example:)*
=> [cherry-pick][branch-2.9] Fix `validatePersistencePolicies` that Namespace/Topic persistent policies cannot set to < 0 

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminSupplier.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestRunMain.java
Right now, PulsarAdmin Tool ignores CLI provided arg for tlsTrustStoreCertPath. This PR fixes and validate it with the testcase.
CLI updates trust-cert path if it's provided in CLI arg.
=> [fix][cli] Fix Pulsar admin tool is ignoring tls-trust-cert path arg

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicList.java
In v2.11.0, the system topic [enables by default](https://github.com/apache/pulsar/pull/15619). This causes the `GET_TOPICS_OF_NAMESPACE ` command to return the system topic redundantly.
And, If the transaction is enabled, the transaction-related system topic will return by the client(`__transaction_buffer_snapshot, __transaction_buffer_snapshot_segments, __transaction_buffer_snapshot_indexes`). This [PR](https://github.com/apache/pulsar/pull/16533) filters some transaction-related topics,  but these are missing.
This causes some incompatibility issues: If consumers use pattern subscribe and the pattern is `/tenant/namespace/.*`, it will subscribe to these system topics.
Discuss mail: https://lists.apache.org/thread/qhm0zbfw0wfd1m5vj977w002qmkr5lt9
- Filter system topic when getting topic …
=> [fix][broker] Filter system topic when getting topic list by binary proto.

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/GrowableArrayBlockingQueue.java
If enabled pooled messages of a consumer, the the passed payload of messages will use the `ByteBuf` which is coming from network and is backed by a direct buffer. But it will not release the buffers in the incoming queue when consumer is closing.
----
see: https://github.com/apache/pulsar/actions/runs/4231062918/jobs/7349401610
Cause: If enabled pooled messages, the ByteBuf named `payload` in `MessageImpl` will be reused if released. So the expression `payload.refCnt()` will not be `0` if it it used by another place.
----
- release the messages in the incoming queue when consumer is closing
- fix flaky test BrokerClientIntegrationTest.testPooledMessageWithAckTimeout
- https://github.com/poorbarcode/pulsar/pull/72
=> [fix] [client] fix memory leak if enabled pooled messages

pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java
Fixes https://github.com/apache/pulsar/pull/19656#issuecomment-1454351762
Replacing `ScheduledExecutorService` to `ExecutorService` in testModularLoadManagerRemoveBundleAndLoad
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/31
=> [fix][test] testModularLoadManagerRemoveBundleAndLoad

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java
After a Topic close failure or a delete failure, the fence state will be reset to get the topic back to work,but it will not reset the fence state of the subscription, which will result in the consumer never being able to connect to the broker.
Reset the fence state of subscriptions if the operation of topic close is failed.
- https://github.com/poorbarcode/pulsar/pull/73
=> [fix] [broker] Topic close failure leaves subscription in a permanent fence state

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
We find that sometimes we can't get the topic policy all the time. After dumping the broker file, we find the namespace value in `policyCacheInitMap`  is false, but the reader was created successfully.
I suspect that there may be some exceptions that occurs in the `refreshTopicPoliciesCache`.
Move the `refreshTopicPoliciesCache` to the `thenAccept` block so we can catch any exceptions.
=> [fix][broker] Fix potential exception cause the policy service init fail.

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaSinkTaskContext.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
Some kafka connectors use topic name to e.g. create table names but pulsar's topic URI does not comply with requirements of the table names. This problems either handled by the connector or by KCA if sanitizeTopicName is set to true.
Some kafka connectors use pause/resume API, in that case sanitized name has to be converted back to original URI to pass to Pulsar's components. 
Provided a way to resolve original topic URI.
Added unit test.
This change added unit test.
NO
PR in forked repository: https://github.com/dlg99/pulsar/pull/10
=> [fix][io] KCA: 'desanitize' topic name for the pulsar's ctx calls

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java
`org.apache.pulsar.broker.namespace.OwnershipCache#getOwnerAsync` will not throw an exception, but it is written in the comment that it will throw an exception, so the comment needs to be corrected. see line 161 162.
https://github.com/Pomelongan/pulsar/blob/fe547c7b7e1d4cb344419cbe37dc2ae771ca630f/pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java#L160-L165
Correct the comments of `org.apache.pulsar.broker.namespace.OwnershipCache#getOwnerAsync` .
PR in forked repository: https://github.com/Pomelongan/pulsar/pull/17
=> [fix][doc] Update the comment of the method of OwnershipCache

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/AdminApiTransactionMultiBrokerTest.java
Fix https://github.com/apache/pulsar/issues/18600
Reason for test failure:
1. Create 16 brokers and 3 transaction coordinator topics. 
2. The 3 transaction coordinator topics are assigned to broker-0.
3. Because the admin is connected to broker-0, we do not hope the topics are assigned to broker-0.
4. Recreate the 3 transaction coordinator topics.
5. The topics are assigned to broker-0 again.
6. Repeat execute steps 3,4,5
7. Timeout
Do not recreate the transaction coordinator topics.
Recreate an admin connect the broker which is not the owner of the transaction coordinator topics.
*(or)* …
=> [fix][test]testRedirectOfGetCoordinatorInternalStats

pulsar-broker/pom.xml
Now that site [admin-rest-api](https://pulsar.apache.org/admin-rest-api) is automatically generated through swagger, each API in the site has its own link that we can walk through, the generated rule of API-link is `https://pulsar.apache.org/admin-rest-api/#operation/{operationId}`, we call the suffix `#operation/{operationId}` of link anchor.
Since the {operationId}'s default value is the method name of the endpoint class, and there has the same method name in the multi endpoint-classes, such as `Namespaces.setDispatchRate` and `PersistentTopics.setDispatchRate`, so these both APIs will generate the same link: `https://pulsar.apache.org/admin-rest-api/#operation/setDispatchRate`.
In the update to version `3.1.8` of `swagger-maven-plugin,` there are another ways to set `operationId`: The …
=> [fix] [doc] fix multiple apis in the automatically generated documentation use the same anchor point

structured-event-log/pom.xml, structured-event-log/src/main/java/org/apache/pulsar/structuredeventlog/Initializer.java, structured-event-log/src/main/java/org/apache/pulsar/structuredeventlog/StructuredEventLog.java, structured-event-log/src/main/java/org/apache/pulsar/structuredeventlog/log4j2/Log4j2Event.java, structured-event-log/src/main/java/org/apache/pulsar/structuredeventlog/log4j2/Log4j2StructuredEventLog.java, structured-event-log/src/main/java/org/apache/pulsar/structuredeventlog/log4j2/package-info.java, structured-event-log/src/test/java/org/apache/pulsar/structuredeventlog/slf4j/StructuredEventLogTest.java
Re-vamping the work on structured logs. Added support for sending events directly to Log4j2 if available, so we can pass all the arguments as a single object without using MDC approach.
=> [StructuredEventLog] Added support for Log4j2 structured logging if available

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/LeaderElectionImpl.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/coordination/impl/LeaderElectionImplTest.java
Master https://github.com/apache/pulsar/pull/19754
This is a namespace bundle double-owners problem. We found it in the memory dumps.
The memory dumps show that the notification thread has been blocked for a long time by the leader election deadlock, And many notifications are blocked in the executor queue. This causes we can't to revalidate the locks, and they are still thinking them working well.
For private reasons, I can't share the namespace bundle snapshot, but the blocked thread easily explains it.
^^ executor queue
- Avoid putting the new task to single thread executor causes deadlock.
(cherry picked from commit cbd799f05eb26aeac5ffd5bbb9751ad9e5928dd3)
*(or)* …
=> [cherry-pick][branch-2.10] Fix deadlock causes session notification not to work (#19754)

pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java
fixes: #19720
This test sets the maximum number of buckets to 10, then creates multiple buckets by writing, then uses the merge mechanism to make the final number of buckets less than or equal to 10.
But `BucketDelayedDeliveryTracker` doesn't guarantee that every merger operation will work, these cases will make the operation fail:
- the last persistention of the bucket has not finished.
- all buckets are full.
- If a maximum of 10 buckets is not guaranteed, then this validation should be removed(which this PR does)
- If want to guarantee a maximum of 10 buckets, then this is a bug that needs to be fixed(should close this PR and create a new PR to fix it)
- x
=> [fix] [test] fix flaky test BucketDelayedDeliveryTrackerTest. testWithBkException

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerStatTest.java
Topic stats have a `msgRateExpired` field. Once this value is greater than 0, it may never return to 0, even though no messages have expired. This is because `PersistentMessageExpiryMonitor#updateRates()` only runs when `PersistentMessageExpiryMonitor#expireMessages()` is executed, not periodically.
For example, if the number of messages in the backlog of a subscription is 0, the execution of `PersistentMessageExpiryMonitor#expireMessages()` will be skipped and `msgRateExpired` will not be updated.
https://github.com/apache/pulsar/blob/cdeef00c5f6a5bd3197b4ca6de0a0505b18835d8/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java#L1062-L1071
As a result, the value of `msgRateExpired` may remain non-zero even though message expiration has not …
=> [fix][broker] Fix issue where msgRateExpired may not refresh forever

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/AbstractKafkaConnectSource.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaSinkTaskContext.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSourceTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/coordination/impl/LeaderElectionImplTest.java
Cherry-picking from master
```
Author: Andrey Yegorov <8622884+dlg99@users.noreply.github.com>
Date:   Fri Mar 10 01:58:40 2023 -0800
[fix][io] KCA: Option to use kafka connector's SourceConnector class to create task and task config (#19772)
(cherry picked from commit 90b0f0a17579d22d413853ed4941d81debbe0cbe)
Author: Andrey Yegorov <8622884+dlg99@users.noreply.github.com>
Date:   Thu Mar 9 01:09:34 2023 -0800
[fix][io] KCA: 'desanitize' topic name for the pulsar's ctx calls (#19756)
(cherry picked from commit d4930a31c052dd8fcd5982b649898967a24f8961)
```
cherry-picks
NO
PR in forked repository: n/a
=> [cherry-pick][branch-2.11] KCA: picking fixes from master

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
A transaction system topic not found exception may occur while deleting the namespace.
**How to happen?**
1. Make sure the topic has a pending ack system topic(`public/default/test-delete-ns-sub__transaction_pending_ack`).
2. Delete the namespace `public/default`.
3. Namespace deletion operation will try to delete the user-created topic `public/default/test-delete-ns` first, at this step, the topic will unsubscribe from all subscriptions, and delete the corresponding pending ack system topic.
4. After the namespace deletion operation delete all user-created topics, it will try to delete all system topics, which contain the pending ack topic `public/default/test-delete-ns-sub__transaction_pending_ack`.
5. The topicNotFound exception occurs.
There are two ways to fix this problem.
1. Remove …
=> [fix][admin] Filter pending ack topic while deleting the namespace

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/intercept/ManagedLedgerInterceptor.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/MangedLedgerInterceptorImplTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/intercept/AppendIndexMetadataInterceptor.java
Line#800 `beforeAddEntry` invokes `interceptor.interceptWithNumberOfMessages(brokerEntryMetadata, numberOfMessages);` to increase the indexGenerator. But it doesn't rollback if entries added failed in LINE#804-813.
This issue will cause the wrong index property set in managed ledger properties map. which would be recovery when managed ledger is initialized.
https://github.com/apache/pulsar/blob/4ed8a871bfa9a7a8e30d86d782e33a556646d7b1/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L799-L816)
Decrease the index generator in `AppendIndexMetadataInterceptor` by
```
public void decreaseWithNumberOfMessages(int numberOfMessages) {
indexGenerator.addAndGet(-numberOfMessages);
}
```
org.apache.pulsar.broker.intercept.MangedLedgerInterceptorImplTest#testAddE …
=> [fix][broker] Fix index generator is not rollback after entries are failed added.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
https://github.com/apache/pulsar/pull/19166/files#r1129126330
- Change the status code from 422 to 409.
=> [fix][broker] Fix admin api status code compatibility

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/manager/SplitManager.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/SplitCounter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/SplitDecision.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/SplitScheduler.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/DefaultNamespaceBundleSplitStrategyImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/NamespaceBundleSplitStrategy.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/manager/SplitManagerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/SplitSchedulerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/DefaultNamespaceBundleSplitStrategyTest.java
This PR implemented 
- SplitScheduler
- DefaultNamespaceBundleSplitStrategyImpl
- SplitManager
-  and their unit test.
- *Added unit tests.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/30
=> [improve][broker] PIP-192 Added SplitScheduler and DefaultNamespaceBundleSplitStrategyImpl

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/AbstractKafkaConnectSource.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaSinkTaskContext.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSourceTest.java
Cherry-picking from master
```
Author: Andrey Yegorov <8622884+dlg99@users.noreply.github.com>
Date:   Fri Mar 10 01:58:40 2023 -0800
[fix][io] KCA: Option to use kafka connector's SourceConnector class to create task and task config (#19772)
(cherry picked from commit 90b0f0a17579d22d413853ed4941d81debbe0cbe)
Author: Andrey Yegorov <8622884+dlg99@users.noreply.github.com>
Date:   Thu Mar 9 01:09:34 2023 -0800
[fix][io] KCA: 'desanitize' topic name for the pulsar's ctx calls (#19756)
(cherry picked from commit d4930a31c052dd8fcd5982b649898967a24f8961)
```
cherry-picks
NO
PR in forked repository: n/a
=> [cherry-pick][branch-2.10] KCA: picking fixes from master

.github/ISSUE_TEMPLATE/pip.yml
PIPs often add new features, and it is always important to consider security during the design and discussion phase of a PIP.
* Add security section to PIP issue template
=> [improve][misc] Add security section to PIP issue template

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/BucketDelayedDeliveryTrackerFactory.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/MutableBucket.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/BucketDelayedDeliveryTest.java
PIP: #16763 
currently, the tracker only cut off snapshot segments according to the time range, to prevent single snapshot segment oversize we should add the max number limitation for snapshot segment.
* Cut off snapshot segment according to config `delayedDeliveryMaxIndexesPerBucketSnapshotSegment`.
* Remove unimplemented configuration `delayedDeliverySharedIndexEnabled`
* Improve variable types
*(or)*
*(or)*
*(example:)*
- *Extended integration test …
=> [improve][broker][PIP-195] Cut off snapshot segment according to maxIndexesPerBucketSnapshotSegment

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/IncrementPartitionsTest.java
This PR is cherry-picking original PR #19223
=> [fix][broker] Copy subscription properties during updating the topic partition number.

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/Bucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/ImmutableBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/MutableBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/BucketDelayedDeliveryTest.java
PIP: #16763  
In #14740, we clean the delayed message tracker when all consumer disconnect to avoid adding duplicated messages,
but BucketDelayedDeliveryTracker uses bitmap to avoid adding duplicated messages. So we don't clean up BucketDelayedDeliveryTracker, otherwise we will lose the bucket snapshot.
* Don't clean up BucketDelayedDeliveryTracker when all consumer disconnect
* Clear missing lastMutableBucketQueue when clear lastMutableBucket
* Fix NPE when clear snapshot
* Add test
*(or)*
*(or)*
*(example:)*
- *Added integration …
=> [fix][broker][PIP-195] Don't clean up BucketDelayedDeliveryTracker when all consumer disconnect

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/LedgerMetadataUtils.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BookkeeperBucketSnapshotStorage.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/Bucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketSnapshotStorage.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/BookkeeperBucketSnapshotStorageTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/MockBucketSnapshotStorage.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java
PIP: #16763 
add topicName and cursorName for BK metadata of bucket snapshot, so we know who is using the ledger.
*(or)*
*(or)*
*(example:)*
=> [improve][broker][PIP-195] Add topicName and cursorName for ledger metadata of bucket snapshot

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannel.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/UnloadScheduler.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStore.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/TableViewLoadDataStoreImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerFilterTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeightTest.java
Based on the current design, only the leader needs to consume the topk bundle load data.
This PR 
- made only the leader consume TopBundlesLoadDataStore
- moved LeaderElectionService to ExtensibleLoadManager from ServiceUnitStateChannel.
- *Updated unit tests.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/37
=> [improve][broker] PIP-192 Made only the leader consume TopBundlesLoadDataStore

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/LockManagerImpl.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/ResourceLockImpl.java
The test `LockManagerTest.updateValueWhenKeyDisappears()` can having infrequent failures, especially when running with Etcd backend. 
The problem is really in the logic of the `ResourceLock` itself. After a normal lock-acquire operation, the test is triggering 2 events at the same time: 
1. A deletion of the lock key-value (eg: the ephemeral node might have disappeared)
2. A `lock.update()` operation to change the value of the lock.
The race condition is due to the fact that operation (1) will trigger a lock revalidation in background and this now happens at the same time as operation (2). 
The result is that it's possible for the ResourceLock to enter into a loop of revalidations and deletions.
eg: 
```
2023-03-14T20:40:40,350 - INFO  - [-8-1:ResourceLockImpl@180] - Acquired resource …
```
=> [fix][meta] Fixed race condition between ResourceLock update and invalidation

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/transaction/Transaction.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionImpl.java
According to the comment https://github.com/apache/pulsar/pull/17423#issuecomment-1235118817, we should cherry-pick https://github.com/apache/pulsar/pull/17423 to branch-2.11
*(or)*
*(or)*
*(example:)*
=> [improve][txn][branch-2.11] Add getState in transaction for client API (#17423)

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedBrokerStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/TransactionMetricsTest.java
For detailed improvement instructions, please refer to issues：
https://github.com/apache/pulsar/issues/18056
original PR：
https://github.com/apache/pulsar/pull/18116
Currently, pulsar does not statistics broker level metrics, and all relevant metrics are 0 by default.
When the number of topic partitions reaches more than 100000 or even millions, and the topic level metrics are exposed (exposeTopicLevelMetricsInPrometheus=true), if you want to query the metrics of the broker dimension, you need to summarize all topics, and the performance becomes very poor, or even the results cannot be queried from the prometheus. Common broker level metrics include:
```
pulsar_topics_count
pulsar_subscriptions_count
pulsar_producers_count
pulsar_consumers_count
pulsar_rate_in
pulsar_rate_out …
```
=> [improve][broker]PIP-214 Add broker level metrics statistics and expose to prometheus

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PartitionKeywordCompatibilityTest.java
This PR is following up #19230
As @yuruguo mentioned https://github.com/apache/pulsar/pull/19230#issuecomment-1382865057, we can tighten the validation scope.
I've checked the logic and found we have no way to create the partition topic with the `-partition-{index}` template. So we can righten the validation scope.
I will keep working on the partition topic section and try to clarify the concept and logic. Plus, ensuring compatibility.
- tighten the validation scope
(cherry picked from commit 246c2701e5c43e02e9783c82d4d107d06b019951)
=> [improve][broker] Follow up #19230 to tighten the validation scope (#19234)

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authorization/AuthorizationServiceTest.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authorization/MockAuthorizationProvider.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationTest.java
In #19455, I made a change to require that only a role in the broker's `proxyRoles` configuration could provide an original principal. Because this change can break certain installations on patch upgrades, a better temporary solution is to always authorize the `originalPrincipal` when present and to allow non proxy roles to supply the original principal.
* Update the `AuthorizationService#isValidOriginalPrincipal` to allow non proxy roles to supply an original principal. I added a log line in place of the previous failure.
* Update all calls to `ServiceConfiguration#getProxyRoles()` to also check if the original principal is not blank. When it is not blank, we will authorize both roles. Note that this is consistent with the logic in the `AuthorizationService#isValidOriginalPrincipal` …
=> [improve][broker] Authorize originalPrincipal when provided

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/MetadataStoreStatsTest.java
MetadataStoreStatsTest is flaky, move to the `flaky` group to avoid blocking PRS.
=> [fix][test] Move MetadataStoreStatsTest to flaky group to avoid blocking merge.

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/manager/UnloadManager.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/UnloadCounter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/UnloadDecision.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/policies/AntiAffinityGroupPolicyHelper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/NamespaceUnloadStrategy.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/UnloadScheduler.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/manager/UnloadManagerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/UnloadSchedulerTest.java
We need to support metrics for unload/transfer operations in Load Manager Extension.
In this PR:
* Change the `findBundlesForUnloading` method return type from `UnloadDecision` to `Set<UnloadDecision>`.
* The `UnloadDecision` no longer contains all unload objects. Each unload object has its own reason.
* Add units test to verify the unload counter.
=> [improve][broker] PIP-192: Add metrics for unload operation

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientDeduplicationTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Cherry-pick a [fix](https://github.com/apache/pulsar/pull/17836) to branch-2.11
*(or)*
*(or)*
*(example:)*
=> [fix][client][branch-2.11] moving get sequenceId into the sync code segment (#17836)

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ManagedLedgerCompressionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/MetadataStoreStatsTest.java
The test `MetadataStoreStatsTest` is flaky because some MetadataStores in tests don't have a metadata name.
Actually, in this test, we only need to care about metrics with names `metadata-store` and `configuration-metadata-store`.
Only calculate metrics with names `metadata-store` and `configuration-metadata-store`.
Increase timeout for test `ManagedLedgerCompressionTest#testRestartBrokerEnableManagedLedgerInfoCompression`.
PR in forked repository: https://github.com/gaoran10/pulsar/pull/25
=> [fix][test] Fix flaky MetadataStoreStatsTest 

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiClusterTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/URIPreconditions.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/URIPreconditionsTest.java
When creating the cluster, if the `serviceUrlTls` is empty in the `ClusterData`, I got `Illegal service tls url, example: https://pulsar.example.com:8443`. I expect the Pulsar works fine.
#19151 breaks this behavior, see the following code:
```
public static void checkURIIfPresent(@Nullable String uri,
@Nonnull Predicate<URI> predicate,
@Nullable String errorMessage) throws IllegalArgumentException {
if (uri == null) {
return;
}
checkURI(uri, predicate, errorMessage);
}
```
This check should also ignore the empty URL.
- Ignore checking the empty URL
Added `testCreateCluster` test.
=> [fix][broker] Fix create cluster with empty url

pulsar-common/src/main/java/org/apache/pulsar/common/util/FutureUtil.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/FutureUtilTest.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/LockManagerImpl.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/ResourceLockImpl.java
This PR is following up the PR #19817.  It includes three parts as follows:
1. Fix the previous PR's incompletable future problem.
2. Split `revalidate` into two methods to eliminate some flags. 
3. Add strict revalidation state check to avoid revalidating expired lock.
1. Fix the previous PR's incompletable future problem.
2. Split `revalidate` into two methods to eliminate some flags. 
3. Add strict revalidation state check to avoid revalidating expired lock.
=> [fix][meta] Follow up #19817, Fix race condition between ResourceLock update and invalidation

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicTxnBufferSnapshotService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SnapshotSegmentAbortedTxnProcessorImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/SegmentAbortedTxnProcessorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionBufferCloseTest.java
The transaction buffer(short for TB) snapshot topic is used to persistent snapshot data for TB, the snapshot can reduce read data when recovering.
Currently, if enable the transaction feature, every topic will create a TB snapshot producer, the topic of the producer is a namespace system topic, so we don't need to create a producer for every topic, one producer per namespace is enough.
Add a new inner class `ReferenceCountedWriter`, if the `ReferenceCountedWriter` for one namespace does not exist, it will be initialized, or else its reference count will be increased, if the reference count reduces to 0, it will be removed from map-cache.
PR in forked repository: https://github.com/gaoran10/pulsar/pull/23
=> [feat][txn] Transaction buffer snapshot writer reuse

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
Cherry-pick #18823 to branch-2.11
*(or)*
*(or)*
*(example:)*
=> [fix][branch-2.11] Fix delete system topic clean topic policy (#18823)

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
The `DirectProxyHandler` and the `ProxyConnection` are run in the same event loop to prevent context switching. As such, we do not need to schedule an event onto an event loop that is in fact the same event loop. Further, scheduling on that event loop could have resulted in uncaught failures because the method was run without any error handling.
Additionally, we can use `assert` to verify that we are in the event loop. Netty makes extensive use of this paradigm, as described in this PR #19653. The primary benefit here is that we skip some unnecessary volatile reads when running the code in production.
* Replace `checkState` with `assert` in `ProxyConnection` class
* Remove unnecessary event execution in callback when starting up the `DirectProxyHandler`.
This change is covered by the …
=> [improve][proxy] Remove unnecessary executor callback; use assert

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/schema/KafkaConnectData.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/schema/PulsarSchemaToKafkaSchema.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
When using a KCA based sink connector with a topic with schema KeyValue<Avro, Avro>, if a message has a null value, the connector throws:
```
023-03-15T08:00:22,139+0000 [public/default/sink] ERROR org.apache.pulsar.io.kafka.connect.KafkaConnectSink - Error sending the record SinkRecord(sourceRecord=PulsarRecord(topicName=Optional[persistent://public/default/data-baselines.keyvalue_short_tests], partition=0, message=Optional[org.apache.pulsar.client.impl.MessageImpl@2ddf2db4], schema=KeyValueSchema(SEPARATED,org.apache.pulsar.client.impl.schema.generic.GenericAvroSchema@33df2fa0,org.apache.pulsar.client.impl.schema.generic.GenericAvroSchema@359ba6c9), failFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$264/0x00000008404bb440@227fd2ce, …
```
=> [fix][io] KCA sink: handle null values with KeyValue<Avro,Avro> schema

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/TopKBundles.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/policies/AntiAffinityGroupPolicyHelper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/reporter/TopBundleLoadDataReporter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/AntiAffinityNamespaceGroupExtensionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/models/TopKBundlesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/reporter/TopBundleLoadDataReporterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java
Bundles with isolation policies or anti-affinity-group policies are not ideal targets to auto-unload as destination brokers are limited. 
This PR 
- Excluded bundles with isolation policy or anti-affinity-group policy from topk load bundles
- Introduced a config `loadBalancerSheddingBundlesWithPoliciesEnabled ` to control this behavior.
- *Updated unit tests.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/38
=> [improve][broker] PIP-192 Excluded bundles with isolation policy or anti-affinity-group policy from topk load bundles

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
If the same cursor is deleted concurrently due to multiple tasks, it will return a failure even if the deletion succeeded. Such a task has these: 
- cancel geo-replication will trigger the delete operation of the cursor `rep.x`
- cancel the dedup task will trigger the delete operation of the cursor `dedup`
- unsubscribe
- delete topic
If the task `delete topic` and the above three tasks are concurrently executing, it will fail.
When deleting the zk node of the cursor, if exception `MetadataStoreException.NotFoundException`  occurs, the deletion is considered successful
- https://github.com/poorbarcode/pulsar/pull/77
=> [fix] [ml] make the result of delete cursor is success if cursor is deleted

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
As expected, If geo-replication is enabled, a topic cannot be deleted. However deleting that topic returns a 500, and no further info.
```
2023-03-21T18:09:57,909 - INFO  - [pulsar-web-75-16:Slf4jRequestLogWriter@62] - 127.0.0.1 - - [21/3月/2023:18:09:57 +0800] "DELETE /admin/v2/persistent/pulsar/ns/tp_e82c0505-d47f-4e4a-8a62-9fa8d6341b76-d6d75112-fbe3-419d-a2d4-2186707185db?force=false&deleteSchema=true HTTP/1.1" 500 6641 "-" "Pulsar-Java-v3.0.0-SNAPSHOT" 11
```
In this case, we should give an error of 400 instead of 500.
Make response code to 400 instead of 500 when delete topic fails due to enabled geo-replication
```
2023-03-21T18:13:10,840 - WARN  - [AsyncHttpClient-236-1:BaseResource$4@236] - [http://localhost:64881/admin/v2/persistent/pulsar/ns/tp_630d809a-6874-4c1b-99ad-5f5e0147950a …
```
=> [fix] [admin] Make response code to 400 instead of 500 when delete topic fails due to enabled geo-replication

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientErrorsTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
If the message field of ErrorCommand is null value, the ErrorCommand can't be created successfully, leading to the client can't receive ErrorCommand.
In general, we send ErrorCommand in the `exceptionally` block, so the NPE has been ignored.
Use empty string instead of null value to avoid ErrorCommand creation failure.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Fix can't send ErrorCommand when message is null value

.github/workflows/ci-go-functions.yaml, .github/workflows/ci-maven-cache-update.yaml, .github/workflows/ci-owasp-dependency-check.yaml, .github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml
In CI, there are some occurrences of failed maven downloads. [For example](https://github.com/apache/pulsar/actions/runs/4489637889/jobs/7896090250#step:11:74):
```
Error:  Failed to execute goal on project pulsar-broker: Could not resolve dependencies for project org.apache.pulsar:pulsar-broker:jar:3.0.0-SNAPSHOT:
Could not transfer artifact org.eclipse.jetty:jetty-http:jar:9.4.48.v20220622 from/to central (https://repo1.maven.org/maven2): 
transfer failed for https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-http/9.4.48.v20220622/jetty-http-9.4.48.v20220622.jar: 
Connect to repo1.maven.org:443 [repo1.maven.org/151.101.40.209] failed: 
Connection timed out -> [Help 1]
```
Retries are enabled, but it turns out that there 
are additional settings in Maven for configuring retries when …
=> [improve][ci] Handle retry of maven downloads for more failure cases

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/ImmutableBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/MutableBucket.java, pulsar-broker/src/main/proto/DelayedMessageIndexBucketSnapshotFormat.proto, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/BookkeeperBucketSnapshotStorageTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java
PIP: #16763 
* Make bucket merge operation asynchronous.
* Optimize the logic of selecting bucket, find two adjacent buckets with the min schedule time and the least number of indexes to merge, avoid preload indexes that have not expired for a long time.
* Add min_schedule_timestamp in SnapshotSegmentMetadata (It is also used later to implement lazy load)
* Fix leak in snapshotSegmentLastIndexTable
*(or)*
*(or)*
*(example:)*
- *Extended integration …
=> [improve][broker][PIP-195] Make bucket merge operation asynchronous

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/DelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/Bucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/ImmutableBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/MutableBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Dispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/BucketDelayedDeliveryTest.java
PIP: #16763 
* Make clear delayed message operation asynchronous
* Clear delayed message when unsubscribe to avoid residual snapshot
* Make update cursor property operation serialization by `FutureUtil.Sequence` (close PR https://github.com/apache/pulsar/pull/19850)
* Use `immutableBuckets.asMapOfRanges().remove()` instead of `immutableBuckets.remove()`
*(or)*
*(or)*
*(example:)*
PR in …
=> [improve][broker] Clear delayed message when unsubscribe &  Make clear operation asynchronous

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsumedLedgersTrimTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/RetentionPolicies.java
Fixes https://github.com/apache/pulsar/issues/18112
In the `RetentionPolicies`, the type of the `retentionSizeInMB` field does not match that of the `retentionSizeInMB` type from the `constructor`.
A simple solution is to fix the constructor, `long` can be compatible with `int`, so just use the `long`.
In #18114, the type of the `retentionSizeInMB` field was changed to `int`, I don't think this is correct, and it introduces a bug: https://github.com/apache/pulsar/blob/75d58fda2fe99471abddc60f7ed671aaa6073e66/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java#L381-L382
`retention.getRetentionSizeInMB() * 1024 * 1024` can be overflowing, and then the result is 0.
Please use the following code to verify that:
```java
int retentionSize = 102400; // 12G
var n = …
```
=> [fix][broker] Fix RetentionPolicies constructor

pulsar-client/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationDataBasic.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionCommon.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/FunctionCommonTest.java
* This fixes https://github.com/apache/pulsar/issues/7354.
* This fixes #19910.
When registering or updating a function via the REST API using a jar url that has the user:pass basic auth scheme is unsupported.
Adding `Authorization` header if detected basic auth in URL
=> [improve] Allow download link with basic auth

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ConsumerAckListTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
For a multi-topics consumer, when it acknowledges a single message, it will first find the owner topic from its message ID. If the owner topic is not subscribed by the consumer, `NotConnectedException` will be thrown.
However, when it acknowledges multiple messages, if any of them is the message whose owner topic is not subscribed by the consumer, NPE will happen instead.
When acknowledging multiple messages, if there is any message ID whose owner topic is not subscribed, fail the whole acknowledgment. `testAckMessageInAnotherTopic` is added to cover this case.
There are many other places that do not check if `consumers.get` returns `null`, like `doReconsumeLater`, `negativeAcknowledge`, etc. This patch does not cover them. …
=> [fix][client] Fix NPE when acknowledging multiple messages

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
In the updateBundleData method, when the following code is executed:
https://github.com/apache/pulsar/blob/30d2469086fea989ac8baf059df8e69c66a68d89/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java#L591-L592
In the reset method, information such as longTermMsgRateIn will be recalculated:
At this time, if brokerData.getTimeAverageData() is called in the LeastLongTermMessageRate#getScore method, the calculated score will be inaccurate：
Create a new TimeAverageBrokerData object and perform a reset update. After the update is complete, call setTimeAverageData:
```
TimeAverageBrokerData timeAverageData = new TimeAverageBrokerData();
timeAverageData.reset(statsMap.keySet(), bundleData, defaultStats);
brokerData.setTimeAverageData(timeAverageData); …
```
=> [fix][broker] Fix the thread safety issue of BrokerData#getTimeAverageData access

pulsar-function-go/pb/Function.pb.go
Master branch build fails with this error message:
```
Error: pf/instance.go:158:15: SA1019: gi.context.instanceConf.funcDetails.AutoAck is deprecated: Do not use.  (staticcheck)
autoAck := gi.context.instanceConf.funcDetails.AutoAck
^
Error: pf/instance.go:364:[13](https://github.com/apache/pulsar/actions/runs/4497924735/jobs/7913997105?pr=19903#step:7:14): SA1019: gi.context.instanceConf.funcDetails.AutoAck is deprecated: Do not use.  (staticcheck)
autoAck := gi.context.instanceConf.funcDetails.AutoAck
^
Error: pf/instanceConf.go:105:6: SA1019: instanceConf.funcDetails.AutoAck is deprecated: Do not use.  (staticcheck)
if !instanceConf.funcDetails.AutoAck &&
^
Error: Process completed with exit code 1.
```
- change was made in #19470
- it was possible to merge the change because of this …
=> [fix][fn] Revert change to deprecation since it broke the master branch

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/LocalPoliciesResources.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTenantTest.java
Fixes #19921
Failed to delete tenant, see log:
```
2023-03-25T18:40:15,174+0800 [pulsar-web-48-12] ERROR org.apache.pulsar.broker.admin.impl.TenantsBase - [null] Failed to delete tenant newtenant
org.apache.pulsar.metadata.api.MetadataStoreException$NotFoundException: path /admin/local-policies/newtenant not found.
at org.apache.pulsar.metadata.impl.RocksdbMetadataStore.storeDelete(RocksdbMetadataStore.java:480) ~[pulsar-metadata.jar:3.0.0-SNAPSHOT]
at org.apache.pulsar.metadata.impl.AbstractMetadataStore.deleteInternal(AbstractMetadataStore.java:386) ~[pulsar-metadata.jar:3.0.0-SNAPSHOT]
at org.apache.pulsar.metadata.impl.AbstractMetadataStore.delete(AbstractMetadataStore.java:373) ~[pulsar-metadata.jar:3.0.0-SNAPSHOT]
at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.delete(Meta …
```
=> [fix][admin] Fix delete tenant

pulsar-client-all/pom.xml
This closes https://github.com/apache/pulsar/issues/19484.
The root cause may be https://github.com/apache/bookkeeper/commit/f0988ddf250440813866849cef4f734174a48fc4#r106236889 and we bump to affected BK version in Pulsar 2.11.
Avoid pull in log4j-slf4j-impl in pulsar-client-all.
*(or)*
*(or)*
*(example:)*
=> [improve][client] Exclude log4j-slf4j-impl from compile dep in pulsar-client-all

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationData.java
Fix typo in ConsumerConfigurationData and ServiceConfiguration.
threashold --> threshold
aconsumer --> a consumer
createdif --> created if
*(or)*
*(or)*
*(example:)*
https://github.com/SeasonPanPan/pulsar/pull/1
=> [fix][doc] fix typo in ConsumerConfigurationData and ServiceConfiguration.

buildtools/pom.xml, buildtools/src/main/java/org/apache/pulsar/tests/JacocoDumpListener.java, pom.xml
Fixes #19931
See #19931. Sometimes the default Jacoco shutdown hook doesn't run and there's no coverage data. This causes the Codecov upload to fail since there's no Jacoco coverage report available.
- enable Jacoco agent's JMX interface
- Dump Jacoco coverage to file with JMX interface in TestNG listener
PR in forked repository: https://github.com/lhotari/pulsar/pull/145
=> [fix][build] Dump Jacoco coverage data to file with JMX interface in TestNG listener

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/ReplicatorStatsImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java
Pulsar will merge the variable `PartitionedTopicStatsImpl.replication[x].connected` by the way below when we call `pulsar-admin topics partitioned-stats`
``` java
this.connected = this.connected & other.connected
```
But the variable `connected` of `PartitionedTopicStatsImpl.replication` is initialized `false`, so the expression `this.connected & other.connected` will always be `false`.
Then we will always get the value `false` if we call `pulsar-admin topics partitioned-stats`.
make the variable `` of `PartitionedTopicStatsImpl` is initialized `true`
- https://github.com/poorbarcode/pulsar/pull/82
=> [fix] [admin] fix incorrect state replication.connected on API partitioned-topic stat

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
When the class(PerformanceProducer) destroy, shutdown the executor
final shutdown executor when the class(PerformanceProducer) is destroyed
PR in forked repository: https://github.com/StevenLuMT/pulsar/pull/7
=> [fix][test] final shutdown executor when the class(PerformanceProducer) is destroyed

pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ClientConfiguration.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java
=> [fix][client] Fix client erroneous code comments

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/CombinedSegmentDelayedIndexQueue.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/DelayedIndexQueueTest.java
PIP: #16763 
Currently, we select two buckets at once to merge, which causes the merge operation to be frequently triggered. We should merge multiple buckets at once to avoid frequent merges.
* Use k-way merge to implement `CombinedSegmentDelayedIndexQueue`
* Merge multiple buckets at once, the default select 4 buckets to merge. If the tracker can't find able merged buckets will try to reduce the number of merged buckets.
* Improve clear code
* Improve logs
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end …
=> [improve][broker][PIP-195] Merge multiple buckets at once

pulsar-io/kafka-connect-adaptor/pom.xml, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaConnectSinkConfig.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java
Work-around for https://github.com/apache/pulsar/issues/19922 for KCA-based sinks.
Option to collapse topic name with "-partition-" and pass it to Kafka connector.
This change added unit tests.
PR in forked repository: https://github.com/dlg99/pulsar/pull/13
=> [improve][io] KCA: option to collapse partitioned topics

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannel.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLoadData.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/TopKBundles.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/UnloadCounter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/UnloadDecision.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/reporter/BrokerLoadDataReporter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/reporter/TopBundleLoadDataReporter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/NamespaceUnloadStrategy.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/SplitScheduler.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/UnloadScheduler.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/DefaultNamespaceBundleSplitStrategyImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeight.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLoadDataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/models/TopKBundlesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/reporter/BrokerLoadDataReporterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/reporter/TopBundleLoadDataReporterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/UnloadSchedulerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/DefaultNamespaceBundleSplitStrategyTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/policies/data/loadbalancer/NamespaceBundleStats.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/policies/data/loadbalancer/ResourceUsage.java
Master Issue: Master Issue: https://github.com/apache/pulsar/issues/16691, https://github.com/apache/pulsar/issues/18099
Raising a PR to implement Master Issue: https://github.com/apache/pulsar/issues/16691, https://github.com/apache/pulsar/issues/18099
We want to reduce unload frequencies from flaky traffic.
This PR 
- Introduced a config `loadBalancerSheddingConditionHitCountThreshold` to further restrict shedding conditions based on the hit count.
- Normalized offload traffic
- Lowered the default `loadBalanceSheddingDelayInSeconds` value from 600 to 180, as 10 mins are too long. 3 mins can be long enough to catch the new load after unloads.
- Changed the config `loadBalancerBundleLoadReportPercentage` to `loadBalancerMaxNumberOfBundlesInBundleLoadReport` to make the topk bundle count …
=> [improve][broker] PIP-192 Improved Auto Unload Logic

pulsar-client-all/pom.xml
This fixes https://github.com/apache/pulsar/issues/19918
Create source jar for debugging and IDE integration.
Set `createSourceJar` and `shadeSourcesContent` to `true` following https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html.
=> [improve][build] Create source jar for pulsar-client-all shaded jar

pom.xml, tiered-storage/file-system/pom.xml
Currently the file-system tiered storages brings in the following CVEs:
- CVE-2023-1436 (from jettison)
- CVE-2023-1370 (from json-smart)
- sonatype-2022-5820 (from hadoop 3.3.3)
All the above are depending from hadoop.
- Upgraded hadoop from 3.3.3 to 3.3.5 - removed the jersey-json override since the dependency has changed (https://issues.apache.org/jira/browse/HADOOP-15983)
- Upgraded jettison from 1.5.3 to 1.5.4
- Upgraded json-smart from 2.4.7 to 2.4.10
=> [fix][sec] Fix transitive critical CVEs in file-system tiered storage

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSink.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaConnectSinkConfig.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/schema/PulsarSchemaToKafkaSchema.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/PulsarSchemaToKafkaSchemaTest.java
Kafka's schema has "Optional" flag that used there to validate data/allow nulls.
Pulsar's schema does not have such info which makes conversion to kafka schema lossy.
Added a config parameter that lets one force primitive schemas into optional ones.
KV schema is always optional.
Default is false, to match existing behavior.
This change updated tests.
PR in forked repository: https://github.com/dlg99/pulsar/pull/12
=> [improve][io] KCA: flag to force optional primitive schemas

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/StatsBuckets.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/DelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BookkeeperBucketSnapshotStorage.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedMessageIndexStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/ImmutableBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/MutableBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedSubscriptionStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/MockBucketSnapshotStorage.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/BucketDelayedDeliveryTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicMetricBean.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java
PIP: #16763
Add metrics for bucket delayed message tracker.
The new metrics and change metrics:
| **Name**                                                | **Type**  | **Description**                                              |
| :------------------------------------------------------ | --------- | ------------------------------------------------------------ |
| pulsar_delayed_message_index_bucket_total               | Gauge     | The number of delayed message index buckets (immutable buckets + LastMutableBucket ) |
| pulsar_delayed_message_index_loaded                     | Gauge     | The total number of delayed message indexes for in the memory. |
| pulsar_delayed_message_index_bucket_snapshot_size_bytes | Gauge     | The total size of delayed message index bucket snapshot (in …
=> [feat][broker][PIP-195] Add metrics for bucket delayed message tracker

pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
1. There is a topic1 with a protobuf schema.
2. Create a producer1 with AutoProduceBytes schema.
3. The producer1 will be created failed because the way to get the schema of protobuf schema is not supported. ### ### 
Because the Protobuf schema is implemented from the AvroBaseStructSchema. So we add a way to get Protobuf schema just like the AvroSchema.
*(or)*
*(or)*
*(example:)*
*If the …
=> [fix][schema]Fix AutoProduceBytes producer can not be created to a topic with ProtoBuf schema

src/get-project-version.py, src/stage-release.sh
1. Upgrade python to python3
2. Remove the cpp-related command
=> [fix][ci][branch-2.10] Fix the release tools

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarStats.java
When the updateStats method is executed periodically, bundleStats will be cleaned up;
At this time, call the getBundleStats method to report the bundle stats data to zookeeper, and the bundle stats data may be lost:
https://github.com/apache/pulsar/blob/30d2469086fea989ac8baf059df8e69c66a68d89/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarStats.java#L105-L117
https://github.com/apache/pulsar/blob/30d2469086fea989ac8baf059df8e69c66a68d89/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java#L1078-L1082
https://github.com/apache/pulsar/blob/30d2469086fea989ac8baf059df8e69c66a68d89/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java#L1000-L1005 …
=> [fix][broker] Fix the loss of bundle stats data reported to zookeeper, when the updateStats method is executed

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
While debugging an issue, I noticed that we call `super.exceptionCaught(ctx, cause);` in the `ProxyConnection` class. This leads to the following log line:
> An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
Because we always handle exceptions, there is no need to forward them to the next handler.
* Remove a single method call
This is a trivial change. Note that we do not call the super method in any other handler implementations in the project.
PR in forked repository: skipping PR for this trivial change
=> [cleanup][proxy] ProxyConnection should not call super.exceptionCaught

pulsar-broker-auth-sasl/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderSasl.java, pulsar-broker-auth-sasl/src/test/java/org/apache/pulsar/broker/authentication/ProxySaslAuthenticationTest.java
This is A follow-up for cherry-pick #15121
After [DIscuss: Cherry-pick #15121 into branch-2.10 to solve the issue sasl authentication failure](https://lists.apache.org/thread/pv65nq9y4ohy9yw4h4nqrz4g50gtft56), we will do a follow-up process to keep the new configuration `saslJaasServerRoleTokenSignerSecretPath` forward compatible: make this config optinal.
Make the config `saslJaasServerRoleTokenSignerSecretPath` optinal
-
=> [branch-2.10] [fix] [auth] fix not forward compatible config saslJaasServerRoleTokenSignerSecretPath after cherry-pick #15121

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java
Sometimes when a remote cluster is deleted, the replication cursor might still exist for some topics. In this case, creating producers or consumers on these topics will fail.
Here is a log observed in a production environment:
> WARN  org.apache.pulsar.broker.service.BrokerService - Replication or
> dedup check failed. Removing topic from topics list
> persistent://public/__kafka/__consumer_offsets-partition-40,
> java.util.concurrent.CompletionException: java.lang.RuntimeException:
> org.apache.pulsar.metadata.api.MetadataStoreException$NotFoundException:
> kop
If it happened, unloading the topic or restarting the broker could not help. We have to remove the cursor manually.
In `addReplicationCluster`, before getting the replication client, check the namespace policy and topic policy …
=> [fix][broker] Ignore and remove the replicator cursor when the remote cluster is absent

src/owasp-dependency-check-suppressions.xml
- Fix OWASP dependency check for master branch
- The vulnerable method is deprecated in Guava, but isn't removed. It's necessary to suppress this CVE. See https://github.com/google/guava/issues/4011
- suppress CVE-2020-8908
=> [fix][build] Suppress Guava CVE-2020-8908 in OWASP dependency check

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/AntiAffinityGroupPolicyFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerIsolationPoliciesFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerMaxTopicCountFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerVersionFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/policies/AntiAffinityGroupPolicyHelper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/policies/IsolationPoliciesHelper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/AntiAffinityNamespaceGroupExtensionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerIsolationPoliciesFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java
The PIP-192 introduced transfer to transfer the bundle from ower broker to a specific broker without unloading,
But the dest broker is not filtered by the broker filter.
* Filter out the dest broker by broker filter.
=> [improve][broker] PIP-192: Filter the transfer dest broker

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Fixes #19784
when create consumer using avro schema. and enable dlqPolicy. the producer creation callback maby block the client io thread. (which is only one thread by default.)
```
"pulsar-client-io-1-1" #120 prio=5 os_prio=0 cpu=30919.69ms elapsed=151047.72s allocated=104M defined_classes=415 tid=0x00007f03824d7010 nid=0x84 waiting on condition  [0x00007f02e39f7000]
at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
- parking to wait for  <0x00000000ad6fd400> (a java.util.concurrent.CompletableFuture$Signaller)
at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:211)
at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.2/CompletableFuture.java:1864)
at …
```
=> [fix][client] Fix DeadLetterProducer creation callback blocking client io thread.

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/AssignCounter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/DefaultNamespaceBundleSplitStrategyImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/DefaultNamespaceBundleSplitStrategyTest.java
Raising a PR to implement: https://github.com/apache/pulsar/issues/16691
This PR 
- Added `Override` EventType metrics
- Made ExtensibleLoadManager.selectAsync for cleanup broker selector.
- *Updated unit tests.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/40
=> [improve][broker] PIP-192 updated metrics and cleanup broker selector

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java
Pulsar Proxy's shutdown isn't graceful. It doesn't close the Proxy to Broker connections before shutdown.
This might lead to issues with exclusive producers, consumers and key shared consumers.
- close all connections and wait for graceful shutdown before returning from close method
=> [improve][proxy] Implement graceful shutdown for Pulsar Proxy

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
If we deploy the new LB or rollback to the old LB. We need to isolate broker-bundle assignments to those brokers that configure the matching LM.
* Use a new zk path to store the available broker use by the new load manager.
=> [improve][broker] PIP-192: Update the lookup data path to support deploy and rollback

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/AdminApiTransactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
In #19455, I added a requirement that only the proxy role could supply an original principal. That check is only supposed to apply when the broker has authorization enabled. However, in one case, that was not the case. This PR does a check and returns early when authorization is not enabled in the broker.
See https://github.com/apache/pulsar/pull/19830#issuecomment-1492262201 for additional motivation.
* Update the `PulsarWebResource#validateSuperUserAccessAsync` to only validate when authentication and authorization are enabled in the configuration.
This is a trivial change. It'd be good to add tests, but I didn't include them here because this is a somewhat urgent fix. There was one test that broke because of this change, so there is at least some existing coverage.
PR in forked …
=> [fix][broker] Only validate superuser access if authz enabled

pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
The producers ["retryLetterProducer", "deadLetterProducer"] will be auto-created by consumers if enabled `DLQ`, but these producers will not close after consumers are closed.
Auto close "retryLetterProducer" and "deadLetterProducer" after the primary consumer is closed
- https://github.com/poorbarcode/pulsar/pull/79
=> [fix][client] Release the orphan producers after the primary consumer is closed

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentDispatcherFailoverConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsumersTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java
We should  disconect the consumer and return if `AbstractDispatcherSingleActiveConsumer` is closed
Return after consumer disconnect
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/33
=> [fix][broker] Return if AbstractDispatcherSingleActiveConsumer closed

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerMXBean.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerMBeanImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/EntryCacheDisabled.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/metrics/ManagedLedgerMetrics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedBrokerStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/ManagedLedgerStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
When there are too many read request to bookie server,  we need find out which ledger is reading without cache.  So here we add  a `storage_read_cache_misses_rate` for ledger level.
Add a metric `storage_read_cache_misses_rate` for ledger level.
- Add UT `org.apache.pulsar.broker.stats.PrometheusMetricsTest#testStorageReadCacheMissesRate` to verify it
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/34
=> [improve][ml] Add Read cache misses metric for ledger

pom.xml
OWASP Dependency Check is failing with this error:
```
Error:  
Error:  spring-core-5.3.20.jar: CVE-2023-20860(7.5)
```
- Upgrade Spring dependency to 5.3.26
- Pulsar is not vulnerable to CVE-2023-20860
=> [fix][sec] Upgrade Spring dependency to 5.3.26 to fix OWASP Dependency Check

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateData.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/Split.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/Unload.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/DefaultNamespaceBundleSplitStrategyImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleFactory.java, pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleSplitAlgorithm.java, pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithm.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/models/SplitTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/SplitSchedulerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/DefaultNamespaceBundleSplitStrategyTest.java, pulsar-broker/src/test/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithmTest.java
Raising a PR to implement: https://github.com/apache/pulsar/issues/16691
This PR 
- Makes split handler idempotent .
- Makes Leader's orphan monitor keep trying to send split msg until finished.
- Select bundle boundaries at the SplitScheduler to have the same split boundaries for each Split handler retry.
- Adds a split condition to check if the parent's Splitting state has moved.
- Made Admin Unload command forceful to unload any bundles in invalid states.
- *Updated unit tests.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/41
=> [improve][broker] PIP-192 made split handler idempotent

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/ConfigurationResource.java
The `/version` endpoint for functions currently returns `{"version":"version.number"}` instead of an actual version number. This PR fixes that.
One observation is that the broker's `/version` endpoint returns a plain string:
https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java#L527-L535
* Return the actual version.
* Use a static field to decrease the cost of this endpoint.
This is a trivial change.
This fixes an endpoint, no docs are needed.
PR in forked repository: Skipping PR since this is so trivial
=> [fix][fn] Make /version return correct version

pom.xml, pulsar-sql/pom.xml, pulsar-sql/presto-distribution/LICENSE, pulsar-sql/presto-distribution/pom.xml, pulsar-sql/presto-pulsar/pom.xml, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/avro/PulsarAvroColumnDecoder.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/json/PulsarJsonFieldDecoder.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/json/PulsarJsonRowDecoderFactory.java, pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/decoder/DecoderTestUtil.java, pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/decoder/avro/TestAvroDecoder.java
This is a follow-up to https://github.com/apache/pulsar/pull/16683.
And it fixes one of the breaking changes noted at https://github.com/apache/pulsar/pull/16494.
The final goal should be catching up to the latest trino version. For compatibility, the Trino community says:
> We generally do our best to avoid making breaking changes in SPI, but we still do them from time to time.
>
> There is a revapi test in SPI which provides compatibility guarantees one version back, but we sometimes have to do exclusions there to enable innovation.
>
> TL;DR is it’s recommended to build a plugin version for a specific Trino version
So it seems the breaking changes and incompatibility is how Trino users should be familiar with.
PR in forked …
=> [feat][sql] Bump Trino version to 368 and fix Decimal breaking change

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MutualAuthenticationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java
https://github.com/apache/pulsar/issues/19705
- Add the `ClientBuilderImpl#description` method to add the description to the original client version string that is set in `CommandConnect` and `CommandAuthResponse`.
- Add `testClientVersion` to cover these two cases.
PR in forked repository: https://github.com/BewareMyPower/pulsar/pull/21
=> PIP-254: Support configuring client version

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloaderFactory.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloaderStatsDisable.java, tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/FileSystemLedgerOffloaderFactory.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/JCloudLedgerOffloaderFactory.java
The fork pr: https://github.com/horizonzy/pulsar/pull/12
After #13833, we change the signature of LedgerOffloaderFactory#create.
Before: no offloaderStats.
```
default T create(OffloadPoliciesImpl offloadPolicies,
Map<String, String> userMetadata,
SchemaStorage schemaStorage,
OrderedScheduler scheduler)
throws IOException {
return create(offloadPolicies, userMetadata, scheduler);
}
```
After: add offloaderStats.
```
default T create(OffloadPoliciesImpl offloadPolicies,
Map<String, String> userMetadata,
SchemaStorage schemaStorage,
OrderedScheduler scheduler,
LedgerOffloaderStats offloaderStats)
throws IOException {
return create(offloadPolicies, userMetadata, scheduler, offloaderStats);
}
```
And in PulsarService#createManagedLedgerOffloader line_1402, it changes the way to create an …
=> [fix][broker]Make LedgerOffloaderFactory can load the old nar.

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/Topics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java
In #19975, we introduced a wrapper for all authentication parameters. This PR adds that wrapper to the Rest Producer.
* Use `AuthenticationParameters` to simplify parameter management in Rest Producer.
* Add method to the `AuthorizationService` that takes the `AuthenticationParameters`.
* Update annotations on Rest Producer to indicate that a 401 is an expected response.
This change is covered by the `TopicsAuthTest`.
This is an internal change that does not need to be documented.
PR in forked repository: skipping PR since the relevant tests pass locally
=> [refactor][broker] Use AuthenticationParameters for rest producer

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TableViewTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/TableView.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
If TableView is interrupted while readTailMessages, it will soon have outdated data as it stops reading more messages. Instead, in this case, TableView needs to retry.
Changed readTailMessages to run indefinitely even if it fails to read.
- Added a unit test.
PR in forked repository: skipped as this is a simple change.
=> [improve][client] Add retry when readTailMessages fails

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
In the method `MetaStoreImpl. asyncRemoveCursor`: 
```java
SafeRunnable.safeRun(() -> callback.operationFailed(getException(ex))); 
```
just creates a runnable but will not execute it.
do run the task
- https://github.com/poorbarcode/pulsar/pull/86
=> [fix] [ml] Fix uncompleted future when remove cursor

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Replicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java
This completes https://github.com/apache/pulsar/issues/16551 and extension to this part-1 pr https://github.com/apache/pulsar/pull/17962
This handles Replicator and message ordering guarantee part for blue-green deployment. 
**Replicator and message ordering handling**
A. Incoming replication messages from other region's replicator producers to Blue cluster
This will not impact ordering messages coming from the other regions to blue/green cluster. After marking blue cluster, blue cluster will reject replication writes from remote regions and redirects remote producers to the Green cluster where new messages will be written. Consumers of Blue clusters will only be redirected to green once they received all messages from blue. So, migration gives an ordering guarantee for messages …
=> [feat] [broker] PIP-188 support blue-green cluster migration [part-2]

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Dispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeExclusiveStickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/StickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TransportCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractBaseDispatcherTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/HashRangeExclusiveStickyKeyConsumerSelectorTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarHandler.java, pulsar-proxy/pom.xml, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyStuckConnectionTest.java
In Kubernetes upgrades, it's possible to get into a state where a TCP/IP connection seems to be alive on the broker. The connection is orphaned and therefore consuming resources and causing resource conflicts with producers and consumers. 
This PR intends to target the issue with consumers that are using the Key shared subscription type with sticky hash ranges. The prevents the issue of "Range conflict with consumer ..." which happens when the previous connection from the client is still active on the broker while the client is reconnecting on a new connection. 
- make `Dispatch.addConsumer` and `StickyKeyConsumerSelector.addConsumer` asynchronous
- add connectionLivenessCheckTimeoutMillis setting that defaults to 5000ms
- when a conflicting consumer is found, first do an active check …
=> [improve][broker] Prevent range conflicts with Key Shared sticky consumers when TCP/IP connections get orphaned

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
When using externalExecuror, the scheduled runnables were never run.
Fixes https://github.com/apache/pulsar/issues/20042
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
=> [fix] Use scheduled executor in BinaryProtoLookupService

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java
After PR #8611, the acquiring permits can be larger than configured msg-rate if used by subscribing. But doc was not updated in time.
fix the outdated doc
- no needed.
=> [fix] [doc] Fix outdated java-doc of rate limiter

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
The Pulsar Proxy has two modes for proxying requests. The first is to proxy lookup requests and the second is to proxy bytes. In the lookup case, the proxy handles redirects transparently to the client and only responds with the final result. In the proxying bytes case, the proxy connects to one upstream broker and forwards bytes between the client and the server.
The only mode where a proxy needs a connection pool is the lookup proxy mode (the `ProxyLookupRequests` state). As such, I propose we only create a `ConnectionPool` when that is the state.
* Relocate the initialization of `ConnectionPool` so that we only create it when the state is `ProxyLookupRequests`.
* Added an assertion that the `completeConnect()` method is only called when the state is `Connecting`.
* Change some logic in …
=> [improve][proxy] Only create ConnectionPool when needed

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
Cherry-pick #19017
In release 2.11.1, I found that `testGetEstimatedBacklogSize` was failed, and then I found that the logic of the #19017 change did not reach branch2.11, but the test did. So cherry pick this to branch-2.11
- Fix bug: If the input paramter `position` is greater than the greatest ledgerId in `ManagedLedgerImpl#ledgers`,  the `estimateBacklogFromPosition` should return 0,  instead of `getTotalSize()`
- Improve: Using `java.util.NavigableMap#tailMap(K)` to calculate the `size`, which will avoid traversal the whole `ManagedLedgerImpl#ledgers`
- Add ut `ManagedLedgerTest#testGetEstimatedBacklogSize` to test this change
=> [branch-2.11] [fix] [broker] Fix estimateBacklogFromPosition if position is greater than the greatest ledgerId

conf/pulsar_tools_env.sh
After #15868, we allow `PULSAR_MEM` & `PULSAR_GC` to be overridden in `pulsar_tool_env.sh`.
Many users set `-Xms` to `2G` or larger in `PULSAR_MEM`, this will make the tools(such as `pulsar-admin`) cost a lot of memory, and if users execute `pulsar-admin` or another tool on the machine where the Broker is deployed, the current device will not have enough memory to allocate, resulting in a broker crash.
When `PULSAR_MEM` is overridden  in `pulsar_tool_env.sh`, delete parameter `-Xms`
- https://github.com/poorbarcode/pulsar/pull/85
=> [fix] [cli] Fix Broker crashed by too much memory usage of pulsar tools

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
In the broker logs this malformed message could be print by the broker
```
[main-EventThread] INFO  org.apache.pulsar.broker.PulsarService - This broker is a follower. Current leader is Optional.empty
```
Fix proper message without calling Optional.toString
=> [fix][broker] Fix leader broker log

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LeaderElectionService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/NoopLoadManager.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLookupData.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerLoadManagerClassFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/manager/RedirectManager.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/BrokerLoadManagerClassFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLookupDataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerFilterTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerIsolationPoliciesFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerLoadManagerClassFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/BrokerLoadManagerClassFilterTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/policies/data/loadbalancer/ServiceLookupData.java, pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LoadReport.java, pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerData.java
Currently, when we are deploying or rollback the load manager, 
we might get a different bundle owner from the old and new broker,
it will cause producer or consumer to fail.
After this PR, when do the lookup, it will check if we are doing deploy or rollback,
and forward the request to the correct broker.
=> [improve][broker] PIP-192: Redirect the request to current load manager

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
BK deployed with Pulsar fail on start with
```
ERROR org.apache.bookkeeper.common.component.AbstractLifecycleComponent - Failed to start Component: http-service
java.lang.NoSuchMethodError: 'io.vertx.core.Future io.vertx.core.Vertx.deployVerticle(io.vertx.core.Verticle)'
at org.apache.bookkeeper.http.vertx.VertxHttpServer.startServer(VertxHttpServer.java:93) ~[org.apache.bookkeeper.http-vertx-http-server-4.16.0.jar:4.16.0]
at org.apache.bookkeeper.server.service.HttpService.doStart(HttpService.java:62) ~[org.apache.bookkeeper-bookkeeper-server-4.16.0.jar:4.16.0]
at org.apache.bookkeeper.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:83) ~[org.apache.bookkeeper-bookkeeper-common-4.16.0.jar:4.16.0]
at …
```
=> [fix] Upgrade Vertx to match BK's version (otherwise BK does not work)

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MockBrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/MockBrokerServiceHooks.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Fixes #19928
When use Schema.BYTES consumer and enable retry and dlq policy.
need cache the empty schema version to avoid send a lot of GetOrCreateSchema request to retrieve the schema version.
1. Cache empty schema version in ProducerImpl schemaCache.
2. When read from schemaCache, check if the schema version means empty.
=> [fix][client] Cache empty schema version in ProducerImpl schemaCache.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Fixes #17878 
The Pulsar documentation currently states that partition update works only for non-global topics. This statement seems to be incorrect as per the below PR:
#5306 
Updated the code comments as well as modified the API documentation for the swagger generation.
PR in forked repository: https://github.com/Apurva007/pulsar/pull/1
=> [Fix][Doc] Update docs for Partition increase command

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java
Fixes #20061
Loads custom factories in pulsar shell only once because multiple loads are redundant, and the lifecycle of classes in the NAR class loader (child) and the App Class Loader (parent) could be out of sync if the custom command has a dependency that is available on the parent loader. In this case, the "dependent" class will be recycled between the shell commands, but not the "dependency" class which could lead to leaking static resources.
Made the logic to load the custom command factory singleton
- Added `customCommandsFactorySingleton` unit test to verify singleton property 
- [manual] Did manual testing locally with a scenario that has a dependency on the parent class …
=> [improve][pulsar-shell] Use singleton custom command factories

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchMessageContainerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/StrategicTwoPhaseCompactor.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawBatchMessageContainerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/GetLastMessageIdCompactedTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/ServiceUnitStateCompactionTest.java
Raising a PR to implement: https://github.com/apache/pulsar/issues/16691
This PR 
- Supports compressed payload from `getLastMessageId `, which I think is a regression from this PR, https://github.com/apache/pulsar/pull/18877
- Adds `ZSTD` compression for the load balance extension system topic, persistent://pulsar/system/loadbalancer-service-unit-state 
- Adds batch size limits in StrategicTwoPhaseCompactor: MAX_NUM_MESSAGES_IN_BATCH = 1000; MAX_BYTES_IN_BATCH = 128 * 1024;  Without these limits, the BK entry from this batcher logic can be larger than 5mb, and also the addEntry operation will keep on failing without halt. (we need a separate fix for this on the bookkeeper layer) 
Broker AddEntryOp Continues to fail more than 20 …
=> [improve][broker] PIP-192 Fix getLastMessageId for compressed payload(And add compression and maxBatchSize for the load balance system topic)

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/BucketDelayedDeliveryTrackerFactory.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/Bucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/BucketDelayedDeliveryTest.java
PIP: #16763 
If `newTracker()` throws an exception, then the future will can't complete forever, this will lead to the topic can't be deleted until restart broker. 
Use `cleanResidualSnapshots` instead of creating a tracker to clear residual snapshots if the tracker does not exist.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Fix avoid future of clear delayed message can't complete

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java
PIP: #16763 
If the future of load segment timeout but, In fact load segment is successful then we need to ensure the previous delayed index is removed from snapshotSegmentLastIndexTable, otherwise, tracker will load the next segment even though we don't need it yet.
* Ensure the previous delayed index is removed from snapshotSegmentLastIndexTable when succeeding to load the segment
* Make load operate asynchronous to avoid block thread
*(or)*
*(or)*
*(example:)* …
=> [fix][broker] Ensure previous delayed index be removed from snapshotSegmentLastIndexTable & Make load operate asynchronous

pulsar-io/docs/src/main/java/org/apache/pulsar/io/docs/ConnectorDocGenerator.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java
Java 9 changes ThreadContextClassLoader and SystemClassLoader to AppClassLoader from URLClassLoader.
We should use `java.class.path` instead to get the related URLs.
=> [fix][doc] ConnectorDocGenerator support Java 9+

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-broker-auth-oidc/pom.xml, pulsar-functions/runtime/pom.xml, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/auth/KubernetesSecretsTokenAuthProvider.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/auth/KubernetesSecretsTokenAuthProviderTest.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactoryTest.java, pulsar-functions/secrets/pom.xml, pulsar-io/kafka-connect-adaptor/pom.xml, pulsar-sql/presto-distribution/LICENSE, src/owasp-dependency-check-suppressions.xml
To avoid [CVE-2022-1471](https://nvd.nist.gov/vuln/detail/CVE-2022-1471)
Jackson needs to upgrade to 2.14.2 and kubenate-client needs to upgrade 18.0.0 to match the snakeyaml version.
When upgrading kubenate-client to 18.0.0, some APIs have changed, so we need to change some related classes.
This closes #20013.
=> [improve][build] Upgrade snakeyaml version to 2.0

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BookkeeperBucketSnapshotStorage.java
add close ledger logic to close temporary opened ledger.
and if close throws exception won't be returned. 
=> [improve] [broker] Close temporary open ledger in BookkeeperBucketSnapshotStorage

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
Currently, when we execute the logic of Broker Close, we first shut down the Broker Service, and then close the LoadManagerTask. This will cause the Broker to be assigned to a new bundle during the shutdown of the Broker, resulting in an inelegant shutdown of the Broker. , eventually triggering brokerShutdownTimeoutMs to forcibly shut down the Broker, causing the Client to fail to produce or consume messages over time.
When shutting down the Broker, we will first remove the temporary node of the current Broker from zookeeper, which is the logic we expect. We expect that the broker will not allocate new bundles during active shutdown of the broker. However, since the task of loadManagerExecutor has been regularly executed to report its own Load information to zookeeper, this will cause the …
=> [improve] [broker] Fix broker restart logic

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/auth/KubernetesSecretsTokenAuthProvider.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/auth/KubernetesSecretsTokenAuthProviderTest.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactoryTest.java, pulsar-functions/secrets/pom.xml, pulsar-sql/presto-distribution/LICENSE, src/owasp-dependency-check-suppressions.xml
Cherry-pick #20085 
To avoid [CVE-2022-1471](https://nvd.nist.gov/vuln/detail/CVE-2022-1471)
Jackson needs to upgrade to 2.14.2 and kubenate-client needs to upgrade 18.0.0 to match the snakeyaml version.
When upgrading kubenate-client to 18.0.0, some APIs have changed, so we need to change some related classes.
This closes #20013.
=> [branch-2.10][improve][build] Upgrade snakeyaml version to 2.0

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateCompactionStrategy.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/StrategicTwoPhaseCompactor.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateCompactionStrategyTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/ServiceUnitStateCompactionTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
Raising a PR to implement: https://github.com/apache/pulsar/issues/16691
After the compaction, the cursor can fast-forward to the compacted horizon when a large number of messages are compacted before the next read. Hence, ServiceUnitStateCompactionStrategy also needs to cover this case. Currently, the existing and slow(their states are far behind) tableviews with ServiceUnitStateCompactionStrategy could not accept those compacted messages. In the load balance extension context, this means the ownership data could be inconsistent among brokers.
This PR 
- fixes ServiceUnitStateCompactionStrategy to accept the state data if its version is bigger than the current version +1.
- (minor fix) does not repeatedly update the …
=> [improve][broker] Fix ServiceUnitStateCompactionStrategy to cover fast-forward cursor behavior after compaction

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/auth/KubernetesSecretsTokenAuthProvider.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/auth/KubernetesSecretsTokenAuthProviderTest.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactoryTest.java, pulsar-functions/secrets/pom.xml, pulsar-sql/presto-distribution/LICENSE, src/owasp-dependency-check-suppressions.xml
Cherry-pick #20085 
To avoid [CVE-2022-1471](https://nvd.nist.gov/vuln/detail/CVE-2022-1471)
Jackson needs to upgrade to 2.14.2 and kubenate-client needs to upgrade 18.0.0 to match the snakeyaml version.
When upgrading kubenate-client to 18.0.0, some APIs have changed, so we need to change some related classes.
This closes #20013.
=> [branch-2.11][improve][build] Upgrade snakeyaml version to 2.0

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
Fixes #20088
While evaluating Pulsar Functions for our data transformation purposes we ran into an issue where the Kotlin runtime of the function clashed with the runtime provided by Pulsar which is a bit outdated (1.4.32).
Upgraded Kotlin to 1.8.20 in the root pom.xml.
PR in forked repository: (https://github.com/gmiklos-ltg/pulsar/pull/4)
=> [improve][fn] Upgrade Kotlin version from 1.4.32 to 1.8.20. (targeted for master)

pulsar-client-admin-shaded/pom.xml, pulsar-client-all/pom.xml
Fixes #19856
`javax.xml.bind:jaxb-api` didn't package into the shade package.
Add a context, why add `javax.xml.bind:jaxb-api` to the admin module, see https://www.jesperdj.com/2018/09/30/jaxb-on-java-9-10-11-and-beyond/
Add `javax.xml.bind:jaxb-api` to  `pulsar-client-admin-shaded/pom.xml`.
=> [fix][admin] Add javax.xml.bind:jaxb-api to shade

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSource.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/ErrRecFileStreamSourceTask.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSourceErrRecTest.java
Support Kafka sources that use commitRecord() and do not implement commit()
added calls to commitRecord() in ack
added basic unit test
PR in forked repository: https://github.com/datastax/pulsar/pull/176
=> [fix][io] KCA: handle kafka sources that use commitRecord

pulsar-broker-auth-oidc/src/test/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenIDIntegrationTest.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderList.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderListTest.java
PIP: #12105 and #19771 
With the implementation of asynchronous authentication in PIP 97, I missed a case in the `AuthenticationProviderList` where we need to implement the `authenticateAsync` methods. This PR is necessary for making the `AuthenticationProviderToken` and the `AuthenticationProviderOpenID` work together, which is necessary for anyone transitioning to `AuthenticationProviderOpenID`.
* Implement `AuthenticationListState#authenticateAsync` using a recursive algorithm that first attempts to authenticate the client using the current `authState` and then tries the remaining options.
* Implement `AuthenticationProviderList#authenticateAsync` using a recursive algorithm that attempts each provider sequentially.
* Add test to `AuthenticationProviderListTest` that exercises this …
=> [fix][broker] Implement authenticateAsync for AuthenticationProviderList

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaTest.java, pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java
This reverts commit ea4d3b4840ba57cfb8edfcf14b6e28e859fdce9b.
Follow the discussion thread https://lists.apache.org/thread/672zmptfblwjmrf9z8336mk12r7csngf to check the details.
=> [fix][broker] Revert : Forbid uploading BYTES schema with admin API (#18995)

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
Fixes #20088
While evaluating Pulsar Functions for our data transformation purposes we ran into an issue where the Kotlin runtime of the function clashed with the runtime provided by Pulsar which is a bit outdated (1.4.32).
Upgraded Kotlin to 1.8.20 in the root pom.xml.
PR in forked repository: (https://github.com/gmiklos-ltg/pulsar/pull/1)
=> [improve][fn] Upgrade Kotlin version from 1.4.32 to 1.8.20.

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java
Make the timer execute immediately after the load index.
Improve method name
*(or)*
*(or)*
*(example:)*
=> [improve][broker] Make timer execute immediately after load index

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyAuthorizationTest.java
Fixes #20066 
Fixes the bug that producers/consumers will all disconnect while using tenant admin to produce/consume.
The root cause is that the permission check logic is not the same bewteen `org.apache.pulsar.broker.service.ServerCnx` and `org.apache.pulsar.broker.service.persistent.PersistentTopic#onPoliciesUpdate`.
In `org.apache.pulsar.broker.service.ServerCnx`, while `handleProducer` and `handleSubscribe`, the permission check will go to `isTopicOperationAllowed` and finally be processed by `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#allowTopicOperationAsync`, which will `validateTenantAdminAccess`. Everything is fine.
In `org.apache.pulsar.broker.service.persistent.PersistentTopic#onPoliciesUpdate`, it checks the permission by …
=> [fix][broker] Fix tenant admin authorization bug.

pulsar-broker-auth-oidc/src/main/java/org/apache/pulsar/broker/authentication/oidc/JwksCache.java, pulsar-broker-auth-oidc/src/main/java/org/apache/pulsar/broker/authentication/oidc/OpenIDProviderMetadataCache.java
The `AuthenticationProviderOpenID` error logs from the Kubernetes client are not very helpful in certain cases because we only get the error's message and not the error's response body. See https://github.com/kubernetes-client/java/issues/2066 for details on the solution.
Here is an example of a problematic error:
```
org.apache.pulsar.broker.authentication.AuthenticationProviderList - Authentication failed for auth provider class org.apache.pulsar.broker.authentication.oidc.AuthenticationProviderOpenID:
javax.naming.AuthenticationException: Error retrieving OpenID Provider Metadata from Kubernetes API server:
at org.apache.pulsar.broker.authentication.oidc.OpenIDProviderMetadataCache$1.onFailure(OpenIDProviderMetadataCache.java:174) …
```
=> [improve] AuthenticationProviderOpenID k8s error logs

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java
PIP: #19849 
The new `KubernetesServiceAccountTokenAuthProvider` introduced by #19888  does not configure the authentication for download because there is an unnecessary check that the `getFunctionAuthenticationSpec` is not `null`. Given that we do not use this spec in creating the auth, it is unnecessary to use here. Further, when we construct the function's authentication, we do not have this null check. See:
https://github.com/apache/pulsar/blob/ec102fb024a6ea2b195826778300f20e330dff06/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java#L411-L417
* Update the `KubernetesRuntime` to add authentication params to the download command when provided.
A new test is added.
PR in forked repository: Skipping for this trivial PR
=> [fix][fn] Supply download auth params when provided for k8s runtime

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BookkeeperBucketSnapshotStorage.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/BookkeeperBucketSnapshotStorageTest.java
PIP: #16763 
https://github.com/apache/pulsar/pull/20111#pullrequestreview-1386658536
Cache this ledger in BookkeeperBucketSnapshotStorage
*(or)*
*(or)*
*(example:)*
=> [improve][broker] Cache LedgerHandle in BookkeeperBucketSnapshotStorage

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyAuthorizationTest.java
This reverts commit fc17c1d98a3c1edd975c131d174a9ef69887d9cd.
In https://github.com/apache/pulsar/pull/20068 we changed the way that the `AuthorizationService` is implemented. I think this approach could have unintended consequences. Instead, I think we should change the `Consumer` and the `Producer` logic to call the correct `AuthorizationService` method. I propose an update to the `Consumer` and `Producer` logic here #20142.
Given that our goal is to deprecate the `AuthorizationService` methods for `canProduce` and `canConsume`, I think we should not change their implementations.
* Revert https://github.com/apache/pulsar/pull/20068
This change is trivial. It removes certain test changes that were only made to make the previous PR work.
PR in forked repository: Skipping PR as I ran tests …
=> [revert] "[fix][broker] Fix tenant admin authorization bug. (#20068)"

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/SubscriptionStatsTest.java
The non-persistent topic can't support the entry filter feature, because the entry list of the non-persistent topic is a `SingletonList`, it doesn't support the `set` method. We'll encounter this exception when using the entry filter feature on a non-persistent topic.
```
2023-04-19T23:52:11,689 - INFO  - [pulsar-io-83-8:EntryFilterTest@40] - filterEntry for {}
2023-04-19T23:52:11,690 - INFO  - [pulsar-io-83-8:EntryFilterTest@54] - metadata {} key REJECT debug '-' outcome REJECT
2023-04-19T23:52:11,690 - WARN  - [pulsar-io-83-8:ServerCnx@406] - [/127.0.0.1:58969] Got exception java.lang.UnsupportedOperationException
at java.base/java.util.AbstractList.set(AbstractList.java:136)
at org.apache.pulsar.broker.service.AbstractBaseDispatcher.filterEntriesForConsumer(AbstractBaseDispatcher.java:1 …
```
=> [fix][broker] Fix entry filter feature for the non-persistent topic

pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java
most method in `ManagedLedgerInterceptorImpl` is just iterate all the interceptors to find the `AppendIndexMetadataInterceptor` which is unnessary.
just save `AppendIndexMetadataInterceptor` to field when needed just call interceptor directly.
=> [improve] [broker] Pin AppendIndexMetadataInterceptor to field in `ManagedLedgerInterceptorImpl`

pulsar-broker/pom.xml, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BookkeeperBucketSnapshotStorage.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/Bucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketSnapshotStorage.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/CombinedSegmentDelayedIndexQueue.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/ImmutableBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/MutableBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/TripleLongPriorityDelayedIndexQueue.java, pulsar-broker/src/main/proto/DelayedMessageIndexBucketMetadata.proto, pulsar-broker/src/main/proto/DelayedMessageIndexBucketSegment.proto, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/BookkeeperBucketSnapshotStorageTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/MockBucketSnapshotStorage.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/DelayedIndexQueueTest.java
Optimization protobuf code in the bucket delayed tracker
* Split `DelayedMessageIndexBucketSnapshotFormat.proto` to `DelayedMessageIndexBucketMetadata.proto` and `DelayedMessageIndexBucketSegment.proto`.
* Use `lightproto-maven-plugin` to generate `DelayedMessageIndexBucketSegment.proto` code (Due to `lightproto-maven-plugin` don't support `map` type so keep using `protobuf-maven-plugin` to generate DelayedMessageIndexBucketMetadata.proto code)
* Reduce data copy in the deserialize
* Add `popToObject`  and `peekTimestamp` method in the DelayedIndexQueue to reduce object create
*(or)* …
=> [improve][broker] Optimization protobuf code in the bucket delayed tracker

pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicMessageIdImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/TopicMessageIdImplTest.java
https://github.com/apache/pulsar/pull/19414 introduces a breaking change for the deprecated `TopicMessageIdImpl#getInnerMessageId` method. It does not return the inner message id, instead, it creates a new `MessageIdImpl`.
Fix the `getInnerMessageId` method and add tests for these deprecated methods.
PR in forked repository: https://github.com/BewareMyPower/pulsar/pull/28
=> [fix][client] Fix breaking changes for the deprecated methods of TopicMessageIdImpl

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE, src/owasp-dependency-check-suppressions.xml
Upgrade the jetty server version to avoid [CVE-2023-26048](https://access.redhat.com/security/cve/CVE-2023-26048)
Upgrade kotlin version to avoid [CVE-2022-24329](https://access.redhat.com/security/cve/CVE-2022-24329)
=> [branch-2.10][improve][build] Upgrade dependencies to reduce CVE.

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
PersistentTopicsTest#testExamineMessage:
testcase's expect is fail,so running successfully is unexpect
when running successfully is unexpect, so assert.fail
PR in forked repository: https://github.com/StevenLuMT/pulsar/pull/8
=> [fix][test] fix bug for testcase(PersistentTopicsTest#testExamineMessage)

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/TopicNameForInfiniteHttpCallGetSubscriptionsTest.java
It works like this:
1. getSubscriptions( `tp1` )
2. is partitioned topic? 
`no`: return subscriptions
`yes`: getSubscriptions(`tp1-partition-0`)....getSubscriptions(`tp1-partition-n`)
--- 
```java
String partitionedTopic = "tp1-partition-0-DLQ";
TopicName partition0 = partitionedTopic.getPartition(0);// Highlight: the partition0.toString() will be "tp1-partition-0-DLQ"(it is wrong).The correct value is "tp1-partition-0-DLQ-partition-0"
```
see: 
https://github.com/apache/pulsar/blob/da788794ebe211bc96d4d961de49ffeeb473ffad/pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java#L233-L237
Therefore, if there has a partitioned topic named `tp1-partition-0-DLQ`, the method `PersistentTopics.getSubscriptions` will works like this:
1. call Admin API …
=> [fix] [broker] Fast fix infinite HTTP call getSubscriptions caused by wrong topicName

pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java
Use `bin/pulsar-admin topics partitioned-stats` get partitioned topic stats, subscription's `messageAckRate` always be 0.
Fix the aggregation logic of subscription stats. 
According to the code, `chunkedMessageRate` has same issue.
=> [fix][broker] Fix getPartitionedStats miss subscription's messageAckRate

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeight.java
fix #20160
LeastResourceUsageWithWeight is an stateful object and current code will be accessed by multithread.
thread 1: is execute https://github.com/apache/pulsar/blob/2b41e4eafb1cba0e548dd90df60e8cdbb24cd490/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeight.java#L89-L91
and thread 2: is execute https://github.com/apache/pulsar/blob/2b41e4eafb1cba0e548dd90df60e8cdbb24cd490/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeight.java#L147-L150
so an IndexOutOfBound occurs.
change the state to `ThreadLocal`
=> [fix] [broker] Make `LeastResourceUsageWithWeight` thread safe

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKSessionWatcher.java
Fixes #[20105](https://github.com/apache/pulsar/issues/20105)
The deadlock is caused by the different acquiring lock order in zkwatcher callback and connection check thread in zkSessionWatcher. Meanwhile, the lock of ZkSessionWatch is intending to  project the currentStatus field,  no need  to perform a lock operation when executing checkConnectionStatus method.  
1. don't perform a lock operation in ZKSessionWatcher.checkConnectionStatus method, which runs in single thread.
2. perform a lock operation in ZKSessionWatcher.checkStatus method.
=> [fix][meta] deadlock of zkSessionWatcher when zkConnection loss

pulsar-broker/src/main/proto/DelayedMessageIndexBucketSegment.proto
Remove the useless (not supported)field in the DelayedMessageIndexBucketSegment.proto, It was introduced by PR #20158
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Remove useless field in the DelayedMessageIndexBucketSegment.proto

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BookkeeperBucketSnapshotStorage.java
Release EntryBuffer after parsing the proto object,  It was introduced by PR #20158
Reduce data copy on the addEntry
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Release EntryBuffer after parse proto object

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
Upgrade swagger version to fix CVE-2022-1471
=> [branch-2.10][fix][build] Upgrade swagger version to fix CVE-2022-1471

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-common/src/main/java/org/apache/pulsar/common/util/FieldParser.java, pulsar-sql/presto-distribution/LICENSE
- Upgrade jackson version to 2.15.0 
*(or)*
*(or)*
*(example:)*
=> [improve][build] Upgrade jackson version to 2.15.0 for CVE-2022-1471

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-common/src/main/java/org/apache/pulsar/common/util/FieldParser.java, pulsar-sql/presto-distribution/LICENSE
This reverts commit fd60e9e8380af1c7680999cbb5bff8160ba3571a.
There's a regression of Jackson. 
https://github.com/FasterXML/jackson-databind/issues/3874
- Revert upgrading operation
=> [improve][build] Revert "Upgrade jackson version to 2.15.0 for CVE-2022-1471 (#20177)"

pulsar-broker/src/test/java/org/apache/pulsar/utils/ConcurrentBitmapSortedLongPairSetTest.java
https://github.com/apache/pulsar/actions/runs/4751705649/jobs/8462387478?pr=20122
```
Error:  Tests run: 7, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 0.176 s <<< FAILURE! - in org.apache.pulsar.utils.ConcurrentBitmapSortedLongPairSetTest
Error:  concurrentInsertions(org.apache.pulsar.utils.ConcurrentBitmapSortedLongPairSetTest)  Time elapsed: 0.038 s  <<< FAILURE!
java.lang.AssertionError: expected [8000] but found [7999]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at …
```
=> [fix][test] Fix flaky test `ConcurrentBitmapSortedLongPairSetTest`

conf/functions_worker.yml, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/InstanceConfig.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceRunnableTest.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceStarter.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java, pulsar-io/alluxio/src/main/resources/META-INF/services/pulsar-io.yaml, pulsar-io/dynamodb/src/main/resources/META-INF/services/pulsar-io.yaml, pulsar-io/jdbc/clickhouse/src/main/resources/META-INF/services/pulsar-io.yaml, pulsar-io/jdbc/mariadb/src/main/resources/META-INF/services/pulsar-io.yaml, pulsar-io/jdbc/openmldb/src/main/resources/META-INF/services/pulsar-io.yaml, pulsar-io/jdbc/postgres/src/main/resources/META-INF/services/pulsar-io.yaml
Most of the java connectors (sinks and sources) map the configuration to a java class. Pulsar exposes a method to convert the configuration (`IOConfigUtils#loadWithSecrets`) using a jackson mapper. However is up to the connector to decide how to convert the configuration.
Most of the builtin java connectors do not allow unknown fields in their configuration. This is usually a good thing since it alerts the user that something is malconfigured. But this doesn't leave space for connectors' rollbacks.
The scenario which is not possible to cover is:
- Upgrade a builtin connector which has a new config property
- Upgrade existing connectors and use this new property
- For some reasons, the connectors must be rollbacked. In order to let the connector work, it's required to rollback also the …
=> [improve][fn] Allow unknown fields in connectors config

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
If the total messages is zero, we should throw exception fast, insteading  throwing exception when reading from the ledger.
If the total messages is zero, throw exception
- org.apache.pulsar.broker.admin.PersistentTopicsTest#testExamineMessage will cover this test
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/36
=> [fix][admin] Fix examine messages if total message is zero

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java
When there is only one broker alive in the cluster, the split bundle makes no sense and the `unload bundle` event is triggered, making it even more unstable.
Skip split bundle if only one broker
- 1
=> [improve] [broker] Skip split boundle if only one broker

.github/workflows/ci-go-functions.yaml, .github/workflows/ci-maven-cache-update.yaml, .github/workflows/ci-owasp-dependency-check.yaml, .github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml
- Maven http connection pooling was originally disabled with #8921 to prevent download issues (TCP connection reset) on GitHub Actions VMs.
- Maven is switching to "Maven Resolver" ("aether") in newer versions instead of using Wagon.
- Disable Maven http connection pooling also for aether
- Set request timeout to 60000ms also for aether
=> [improve][ci] Disable Maven http connection pooling on CI also for newer Maven versions

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
Improve knowBrokers update
Improve knowBrokers update
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/37
=> [improve][broker] Improve knownBrokers update in ModularLoadManagerImpl

wiki/proposals/PIP.md
We merged the new PIP template as a GitHub issue template, but forgot to remove the inline template.
The new PIP template was merged as GitHub Issue template, but forgot to remove inline template.
=> [fix][docs] Remove old template inlined

pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/SchemaDefinitionBuilderImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/KeyValueSchemaTest.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java
This closes #20093.
Explicit property name typo.
Fix typo and remove unused variable.
Add test `testOverwriteSchemaDefaultProperties`.
=> [fix][client] SchemaDefinition handle JSR310_CONVERSION_ENABLED property

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE, src/owasp-dependency-check-suppressions.xml
Cherry-pick #20162, #20172 
Upgrade the jetty server version to avoid [CVE-2023-26048](https://access.redhat.com/security/cve/CVE-2023-26048)
Upgrade kotlin version to avoid [CVE-2022-24329](https://access.redhat.com/security/cve/CVE-2022-24329)
Upgrade swagger version to fix [CVE-2022-1471]((https://access.redhat.com/security/cve/CVE-2022-24329))
=> [improve][build] Upgrade dependencies to reduce CVE

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java
A producer of the remote cluster is automatically created when replication is turned on. But we can't see anything about it from the response of `(remote cluster) pulsar-admin topic stats`
Make this producer displayed in the topic stats
- x
=> [fix] [broker] Producer created by replicator is not displayed in topic stats

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
In the scenarios<sup>[1]</sup> below, the replicator only acknowledges messages and does not replicate them, but if the topic is closing now, the operation acknowledge(in other words: `cursor.asyncDelete`) will be failed by the error `Cursor was already closed`, then it will retry again(see the code <sup>[2]</sup>) and fail again....loop.
<strong>[1]</strong>: scenarios of skip messages:
- the message can not be deserialized.
- the entry is a transaction marker.
- the message has been aborted by the transaction.
- the message is repeated from another cluster.
- the message is expired(see the retention policy).
- the message specifies the target cluster, but the replicator is not the owner of the target cluster.
<strong>[2]</strong>: Code of retry to acknowledge messages. …
=> [fix] [broker] Fix infinite ack of Replicator after topic is closed

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
…cksDB version
Fixes #xyz
PIP: #xyz 
Ugrade the RocksDB's version to 6.29.4.1 to keep in sync with BookKeeper's RocksDB version
*(or)*
*(or)*
*(example:)*
=> [fix] [broker] [Branch-2.10] Upgrade rocksDB version to 6.29.4.1 to keep in sync with BookKeeper's RocksDB version

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionProduceTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionImpl.java
This commit migrates https://github.com/apache/pulsar/pull/20055 to branch-2.10.
=> [fix][txn][branch-2.10] Fix transaction is not aborted when send or ACK failed

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerImplTest.java
Fixes #19671
To resolve the thread-safety issue around Java client's seek logic identified by apache/pulsar#19671.
- Made ConsumerImpl immediately log, cancel future and then return if `duringSeek` flag is not false.
- by canceling the seekFuture, the client ensures that the current operation does not interfere with the ongoing seek operation and avoids any errors or inconsistencies that might otherwise occur.
> - [ ] Make sure that the change passes the CI checks.
I am not sure if my PR went through the intended CI checks...?
*(or)* …
=> [fix][client] Java Client's Seek Logic Not Threadsafe #1

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationService.java
Fixes #20236 
PIP: #19409 
In the `AuthenticationService`, we are currently using the deprecated `authenticate` methods. As a result, we hit the `Not Implemented` exception when using the `AuthenticationProviderOpenID`. This PR updates the implementation so that we're able 
This solution isn't ideal for two reasons.
1. We are not using the `authenticationHttpRequest` method, which seems like the right method for the WebSocket proxy. However, this is not a viable option, as I documented in #20237.
2. We are calling `.get()` on a future. However, it is expected that the `AuthenticationProvider` not block forever, so I think this is acceptable for now. Please let me know if you disagree.
* Replace `authenticate` with `authenticateAsync`.
This change is a trivial rework / code cleanup without …
=> [feat][ws] Use async auth method to support OIDC

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionTest.java
Fixes #8703
Fixed the unexpected consumer stuck issue of Key_Shared subscription by delayed messages.
The issue can be reproduced by the test provided in #8703.
- Suppose we have 10 messages 0,1,2,3,4,5,6,7,8,9, and 2 consumers, consumer-A and consumer-B
- Only consumer-A connected to the topic and read 5 messages from the topic, 0,1,2,3,4, but haven’t acknowledged
- Now, consumer-B joined, it will try to read messages from 5, but due to 0,1,2,3,4 are not being acknowledged, consumer-B can’t process new messages at this point because it might break the order(1 and 5 are from the same message key, we don’t know which one will be processed first in 2 instances)
- So, the solution to guarantee the ordering dispatch is to pause the message dispatch for consumer-B until all the messages before …
=> [fix][broker] Fix the behavior of delayed message in Key_Shared mode

pulsar-broker/src/test/java/org/apache/pulsar/RoaringbitmapTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/transaction/TxnID.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionImpl.java
Cherry-pick #17777, #18270
The TransactionImpl stores a lot of future. This uses a lot of memory, and can be optimized to two futures. ### Modification
Optimize the future list to single future.
PR in forked repository: https://github.com/liangyepianzhou/pulsar/pull/5
=> [fix][txn] optimize the ack/send future in TransactionImpl

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
The branch master has an NPE check in the `BrokerService::checkOwnershipAndCreatePersistentTopic`, but it will lead to a `UnsupportedOperationException`. The returned map might be an unmodifiable `Collections.emptyMap()`. The call chain involved is as follows:
1. `BrokerService::checkOwnershipAndCreatePersistentTopic`
2. `BrokerService::fetchTopicPropertiesAsync`
3. `ManagedLedgerFactory::getManagedLedgerPropertiesAsync`
4. `MetaStoreImpl::getManagedLedgerPropertiesAsync`
5. `operationFailed`
```java
public void operationFailed(MetaStoreException e) {
if (e instanceof MetadataNotFoundException) {
result.complete(Collections.emptyMap());
} else {
result.completeExceptionally(e);
}
}
```
Make the getManagedLedgerPropertiesAsync return a modifiable map.
*(Please pick either of the following …
=> [fix][broker] Fix `UnsupportedOperationException` when update topic properties.

pom.xml, pulsar-io/jdbc/core/pom.xml, pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/BaseJdbcAutoSchemaSink.java
- tested with jdbc clickhouse on pulsar 2.11.1
Fixes #20247
*(or)*
*(or)*
*(example:)*
=> [fix][io] add protobuf ByteString to pulsar-io jdbc core

.mvn/extensions.xml, buildtools/pom.xml, pom.xml, pulsar-client-tools-customcommand-example/pom.xml
- get rid of some warnings in maven 3.9.x
- upgrade Maven surefire to a stable version
- Pulsar was stuck on Maven surefire version 3.0.0-M3 for a very long time
- upgrade other build/test related plugins
- upgrade Gradle Enterprise maven extension to 1.17.1
- upgrade TestNG version to 7.7.1
PR in forked repository: https://github.com/lhotari/pulsar/pull/146
=> [improve][build] Upgrade maven surefire plugin and other build/test plugins/libs including TestNG version

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricStreams.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
If you create a topic with the double quote in the name (e.g. `public/default/"mytopic`) then there are some metrics that are generated in a broken format. 
```
pulsar_subscriptions_count{cluster="mycluster",namespace="namespace1",topic="persistent://public/default/"mytopic"} 0.0
```
This leads to errors in the grafana dashboards. 
* Escape all label values when generating the metrics
=> [fix][monitor] topic with double quote breaks the prometheus format

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerBookieIsolationTest.java
Fixes #20194 
Motivation & Modifications:
After creating the namespace, if the bookie affinity is set for the namespaces, before setting the namespace policies, then for setting bookie Affinity currently the code directly uses the default bundle of size 1 instead of reading the configuration to get the default bundle size while creating the namespaces. 
The change fixes that and uses the user-provided value from the broker configurations to set the bundles.
The tests are already in place to create the bookie affinity group in `BrokerBookieIsolationTest.java` . So Just added a check to get the bundle size that was missing earlier.
=> [fix][broker] Fix default bundle size used while setting bookie affinity

pulsar-function-go/conf/conf.go, pulsar-function-go/conf/conf.yaml, pulsar-function-go/pf/instance.go, pulsar-function-go/pf/instanceConf.go, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/go/GoInstanceConfig.java, pulsar-functions/instance/src/main/resources/findbugsExclude.xml, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTestBase.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/go/PulsarFunctionsGoTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarFunctionsJavaTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/python/PulsarFunctionsPythonTest.java
Fixes #19981
PIP: #xyz 
The Go runtime doesn't support multi-input topics, 
Add a map<string, string> field `SourceInputSpecs` to the `GoInstanceConfig`, while the key is topic name, and value is the json string of `ConsumerSpec`, so that the Go instance can unmarshal it to a `map[string]ConsumerSpec` and support multiple input topics
- *Added integration tests for GO with multiple input topics*
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/10
=> [fix][fn] Support multiple input topics for Go runtime

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
Fixes #18966
PIP: #xyz 
pulsar-admin functions update doesn't support package URL for python and golang
Fix
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/9
=> [fix][fn] Make pulsar-admin support update py/go with package url

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-broker/src/test/java/org/apache/pulsar/RoaringbitmapTest.java, pulsar-sql/presto-distribution/LICENSE
This reverts commit f88a49e2842f19ce8028cebf2fef1675db50c775.
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
=> Revert "[fix] [broker] [branch-2.10] Upgrade rocksDB version to 6.29.4.1 to keep in sync with BookKeeper's RocksDB version 

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConnectionPoolTest.java
Fixes #20290
The test ConnectionPoolTest.testSetProxyToTargetBrokerAddress is flaky
Modify test so that it's not flaky. Use separate `broker1` and `broker2` since the connection pool doesn't contain handling for separating direct and proxied connections to a broker. 
The key in the connection pool is the "logical address" which is the target broker. It doesn't take the "physical address" into account.
=> [fix][test] Fix flaky test ConnectionPoolTest.testSetProxyToTargetBrokerAddress

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
Fixes #20301
`topicPublishRateLimiter` in `org.apache.pulsar.broker.service.AbstractTopic` can only be set in `updatePublishDispatcher`. So the `topicPublishRateLimiter` in topic can shortly be `null` just when the topic object is created and before `initialize`. At this time, if the broker service starts to do `checkTopicPublishThrottlingRate` (`org.apache.pulsar.broker.service.BrokerService#setupTopicPublishRateLimiterMonitor`), which will cause NPE.
Error log sample:
```
2023-05-11T14:18:10,426+0800 [pulsar-topic-publish-rate-limiter-monitor-39-1] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
java.lang.NullPointerException: null
at org.apache.pulsar.broker.service.AbstractTopic.checkTopicPublishThrottlingRate(AbstractTopic.java:843) …
```
=> [fix][broker] Fix NPE cause by topic publish rate limiter.

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java
The `initializeWorkerConfigFromBrokerConfig` method converts a `ServiceConfiguration` object to a `WorkerConfig`. This is used when the function worker is running within the broker and when pulsar is running in standalone mode. The TLS certificates that are trusted by the broker should also be trusted by the function worker, and the TLS certificates that are trusted by the broker client should be trusted by the function worker's client.
* Improve the `PulsarFunctionTlsTest` test by adding awaitility. Before this change, the test was flaky on my machine.
* Fix the mapping of broker config to function worker config.
A test is added. Note that the old test doesn't technically fail due to the misconfiguration at the moment. The error is in the logs. Here is one of the stack traces that is …
=> [fix][fn] Correct TLS cert config translation from broker to fn worker

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
After initiating the snapshot segment function, deletion of topics necessitates the activation of readers. Furthermore, these readers should be opened and deleted as they are used, which implies that we should not pre-store readers. However, after initiating the deletion of namespaces currently, it is not allowed to obtain the metadata of partition topics or lookup, making it impossible to create readers. This results in the inability to delete namespaces.
Allow the acquisition of system topic metadata after initiating namespace deletion, thus creating readers to clean up topic data.
*(or)* …
=> [fix][broker] Allow Access to System Topic Metadata for Reader Creation Post-Namespace Deletion

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
Fixes #xyz
PIP: #xyz 
Pulsar 2.10 uses BookKeeper 4.14.7, and BookKeeper 4.14.7 uses RocksDB 6.16.4. 
However, Pulsar also introduced RocksDB dependency and uses 6.10.2. When packaging all the dependencies into the Pulsar release package, the RocksDB 6.10.2 in Pulsar will override the RocksDB 6.16.4 in BookKeeper. The Pulsar release package will only contain RocksDB 6.10.2 in the end.
We encountered a RocksDB 6.10.2 memory leak issue when upgrading from Pulsar 2.9.x to 2.10.x, but still have not found any related issues in RocksDB. Pulsar 2.9.x uses RocksDB 6.16.4. One related issue is https://github.com/apache/bookkeeper/issues/3507
The reason why we revert https://github.com/apache/pulsar/pull/20287 is that we found the bookie throws method not found exception when …
=> [fix] [broker] [branch-2.10] Upgrade rocksDB version to 6.16.4 to keep sync with BookKeeper 4.14.7

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
Fixes https://github.com/apache/pulsar/issues/20285
Fix Flaky-test: `SimpleProducerConsumerTestStreamingDispatcherTest.rest`
`org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest#pulsar` shoudn't be set as null in test method
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/39
=> [fix][test] Flaky-test: SimpleProducerConsumerTestStreamingDispatcherTest. rest

.asf.yaml
For example https://github.com/apache/pulsar/pull/20321.
Most of the time we use squash and merge, but rebase and merge help sometimes to keep commits separate while reviewing them at once.
=> [improve][misc] Enable rebase and merge to handle one PR of multiple semantic commits

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
when ledger close or rollover. ml will change to ClosingLedger state and close current ledger.
and call `ledgerClosed` method.
the `inactiveLedgerRollOverTimeMs` task didn't follow this routinue.
patch the close logic when enable `inactiveLedgerRollOverTimeMs` this option
add unit test to check all ledger is closed.
PR in forked repository: (https://github.com/lifepuzzlefun/pulsar/pull/18)
=> [fix][ml] Fix ledger left in OPEN state when enable `inactiveLedgerRollOverTimeMs`

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java
Master Issue: #19671 
Improves JavaDoc describing changes made by PR #20242 as suggested by in [review](https://github.com/apache/pulsar/pull/20242#pullrequestreview-1417853594)
**EDIT:** modified JavaDoc to also cover https://github.com/apache/pulsar/pull/20321 accordingly
Add JavaDoc regarding thready-safety to the methods in scope of #20242
This change is a trivial rework only adds JavaDoc
PR in forked repository: https://github.com/JooHyukKim/pulsar/pull/2
=> [improve][client] Document Java Client's Seek logic thread-safety improved in #20242

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BaseMetadataStoreTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/coordination/impl/LeaderElectionImplTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/impl/EtcdMetadataStoreTest.java, pulsar-sql/presto-distribution/LICENSE, src/owasp-dependency-check-suppressions.xml
Fixes #20308
As described in #20308, we have test flakiness because of an issue in the etcd dependency. This PR upgrades etcd to fix the test.
I am not familiar with this integration. If there is any reason we should avoid this upgrade, please comment as much.
* Upgrade etcd dependency from 0.5.11 to 0.7.5
* Update license files
* Increase test timeout since it was failing during docker pull on my local machine
* Replace code with the new methods/classes
Tests passing should be sufficient.
PR in forked repository: https://github.com/michaeljmarshall/pulsar/pull/49
=> [feat][meta] Upgrade to jetcd to 0.7.5

pulsar-broker-auth-oidc/src/main/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenID.java, pulsar-broker-auth-oidc/src/main/java/org/apache/pulsar/broker/authentication/oidc/JwksCache.java, pulsar-broker-auth-oidc/src/test/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenIDIntegrationTest.java
When the `AuthenticationProviderOpenID` encounters an unknown Key ID (known as the `kid` in the JWT) for a trusted token issuer, the token is rejected with the following error `java.lang.IllegalArgumentException: No JWK found for Key ID <kid>`. This behavior is technically valid, but it isn't ideal because it is possible that the Identity Provider has issued new signing keys and started using them before the Pulsar authentication provider has refreshed its cache. This PR introduces a behavior to retrieve 
This PR adds a configuration called `openIDKeyIdCacheMissRefreshSeconds` that represents the length of time that must pass before the provider will reload the JWKS from the Identity Provider. The `openIDKeyIdCacheMissRefreshSeconds` setting limits the impact of an attacker invalidating …
=> [feat] OIDC: support JWKS refresh for missing Key ID

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadReportNetworkLimitTest.java
@dave2wave recently encountered this test failure:
```
20:46:55  [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 15.301 s <<< FAILURE! - in org.apache.pulsar.broker.loadbalance.LoadReportNetworkLimitTest
20:46:55  [ERROR] checkLoadReportNicSpeed(org.apache.pulsar.broker.loadbalance.LoadReportNetworkLimitTest)  Time elapsed: 0.142 s  <<< FAILURE!
20:46:55  java.lang.AssertionError: expected [1.6200000000000004E7] but found [1.62E7]
20:46:55  	at org.testng.Assert.fail(Assert.java:99)
20:46:55  	at org.testng.Assert.failNotEquals(Assert.java:1037)
20:46:55  	at org.testng.Assert.assertEquals(Assert.java:701)
20:46:55  	at org.testng.Assert.assertEquals(Assert.java:712)
20:46:55  	at org.apache.pulsar.broker.loadbalance.LoadReportNetworkLimitTest.checkLoadReportNicSpee …
```
=> [fix][test] Use delta when comparing doubles in checkLoadReportNicSpeed

src/owasp-dependency-check-suppressions.xml
These CVEs were introduced by #20339. We upgraded to the latest version of jetcd, so I am suppressing the related CVEs.
OWASP is currently failing with:
> Error:  jetcd-core-0.7.5.jar: CVE-2020-15113(7.1)
Error:  jetcd-grpc-0.7.5.jar: CVE-2017-8359(9.8), CVE-2020-15113(7.1), CVE-2020-7768(9.8), CVE-2017-7861(9.8), CVE-2017-9431(9.8), CVE-2017-7860(9.8)
A subsequent run had the following failure:
>Error:  jetcd-api-0.7.5.jar: CVE-2020-15113(7.1)
And another error:
>Error:  jetcd-common-0.7.5.jar: CVE-2020-15113(7.1)
I retrieved the jar checksums from these two links:
* https://repo1.maven.org/maven2/io/etcd/jetcd-core/0.7.5/jetcd-core-0.7.5.jar.sha1
* https://repo1.maven.org/maven2/io/etcd/jetcd-grpc/0.7.5/jetcd-grpc-0.7.5.jar.sha1
* …
=> [improve][sec] Suppress etcd CVE warnings

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
Fixes https://github.com/apache/pulsar/issues/20278
Motivation
Motivation & Modifications:
1. When creating a namespace anti-affinity group with the default local policies, use the bundle size supplied by the user.
2. use OrElseGet instead of OrElse
=> [fix][broker] When creating a namespace anti-affinity group with the default local policies, use the bundle size supplied by the user.

pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ProducerHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ReaderHandler.java
Similar to: https://github.com/apache/pulsar/pull/20142
In https://github.com/apache/pulsar/pull/20142 we changed the `Consumer` and the `Producer` logic to call the correct `AuthorizationService` method.
Our goal is to deprecate the `AuthorizationService` methods for `canProduce` and `canConsume`, so this change helps us move in the right direction.
This PR follows the same logic and updates the WebSocket proxy to remove all calls to the `can*` methods in the `AuthorizationService`
* Update `ProducerHandler`,  `ConsumerHandler`, and `ReaderHander` in the WebSocket Proxy to call the `AuthorizationService#allowTopicOperationAsync` method.
This change is trivial.
PR in forked repository: Skipping PR as I ran tests locally.
=> [improve][ws] Use allowTopicOperationAsync for authz checks

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ProducerHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ReaderHandler.java
Relates to: #20299
We have several catch blocks that are dedicated to providing meaningful logs about timeouts. As such, we should catch the `TimeoutException`, not the `InterruptedException`, in order to ensure accurate logs.
* Replace `InterruptedException` with `TimeoutException`
=> [cleanup] Catch TimeoutException when logging about time outs

pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithoutServiceDiscoveryTest.java
The `ProxyWithoutServiceDiscoveryTest` is documented to verify `e2e tls + Authentication + Authorization (client -> proxy -> broker)`. However, the TLS is insecure and authorization is disabled. This PR cleans up that test.
* Enable authorization in the broker config.
* Replace the certs with ones provided by the parent class.
* Add `proxyRoles` so authorization will pass.
* Update the `superUserRoles` because the different certs have different CNs.
* Enable secure TLS
The test passes locally and the logs look right.
=> [fix][test] ProxyWithoutServiceDiscoveryTest should enable authz

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java
- https://github.com/apache/pulsar/pull/7105 provide a mechanism to avoid a stuck consumer affecting the consumption of other consumers: 
- if all consumers can not accept more messages, stop delivering messages to the client.
- if one consumer can not accept more messages, just read new messages and deliver them to other consumers.
- https://github.com/apache/pulsar/pull/7553 provide a mechanism to fix the issue of lost order of consumption: If the consumer cannot accept any more messages, skip the consumer for the next round of message delivery because there may be messages with the same key in the replay queue.
- https://github.com/apache/pulsar/pull/10762 provide a mechanism to fix the issue of lost order of consumption: If there have any messages with the same key in the replay …
=> [fix] [broker] In Key_Shared mode: remove unnecessary mechanisms of message skip to avoid unnecessary consumption stuck

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerWrapper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannel.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
Load balancer extension needs to shut down gracefully, especially when shutting down the leader broker. When the leader broker closes the leader election service too late, service unit lookups to the leader broker could fail during the shutdown. This could delay client reconnection time.
Lookup failure logs
```
(shutdown starts)
pulsar-broker-8 pulsar-broker 2023-04-22T00:19:52,630+0000 [pulsar-service-shutdown] INFO  org.apache.pulsar.broker.PulsarService - Closing PulsarService
pulsar-broker-3 pulsar-broker 2023-04-22T00:19:52,690+0000 [pulsar-io-4-5] INFO  org.apache.pulsar.client.impl.ConnectionHandler - [persistent://pulsar/system/loadbalancer-service-unit-state] [pulsar-18-9] Closed connection [id: 0x907e74b0, L:/10.0.13.6:35838 ! …
```
=> [improve][broker] Gracefully shut down load balancer extension

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerLoadManagerClassFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/manager/RedirectManager.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/BrokerLoadManagerClassFilter.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerLoadManagerClassFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/manager/RedirectManagerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/BrokerLoadManagerClassFilterTest.java
When upgrading the pulsar version and changing the pulsar load manager to `ExtensibleLoadManagerImpl` it might cause NPE. The root cause is the old version of pulsar does not contain the `loadManagerClassName` field.
```
2023-05-18T05:42:50,557+0000 [pulsar-io-4-1] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.6:51345] connected with role=[pulsarinstance-v3-0-n@test.dev](mailto:pulsarinstance-v3-0-n@test.dev) using authMethod=token, clientVersion=Pulsar Go 0.9.0, clientProtocolVersion=18, proxyVersion=null
2023-05-18T05:42:50,558+0000 [pulsar-io-4-1] WARN  org.apache.pulsar.broker.lookup.TopicLookupBase - Failed to lookup [pulsarinstance-v3-0-n@test.dev](mailto:pulsarinstance-v3-0-n@test.dev) for topic persistent://xxx with …
```
=> [fix][broker] Fix broker load manager class filter NPE

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
Mutable objects shouldn't be static fields in BrokerService
Drop `static` definition and make them ordinary instance fields.
=> [fix][broker] Change some static fields referencing mutable objects to ordinary instance fields in BrokerService

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
We need to create system topics without partitions explicitly. Currently, we do not support partitioned system topics.
create system topics without partitions explicitly
=> [fix][broker] pre-create non-partitioned system topics for load balance extension

pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java
If there are no retained messages, the memory of brokerMeta will leak.
Retain brokerMeta when it really needs.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Fix memory leak when rebatchMessage

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java
Master Issue: #19486
Remove ambiguity around this setting being 30s default per the other docs
Updated the javadoc to align with the current implementation and as described in other areas of the documentation.
[x] This change is a trivial rework / code cleanup without any test coverage.
=> [improve][doc] Remove javadoc reference to old default 30s ack timeout impl

pulsar-common/src/main/java/org/apache/pulsar/common/stats/JvmMetrics.java
Add `jvm_start_time` to help user get this metric even more accessible than though mbeans
=> [improve][monitor] Add JVM start time metric

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceStarter.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntimeFactory.java
Fixes #19885
PIP: #xyz 
JavaInstanceStarter still cannot infer type class name
1. create a new `FunctionCacheManager` in `JavaInstanceStarter` to create the function class loader and pass this `fnCache` to `ThreadRuntimeFactory`'s constructor method.
2. create a new constructor method for `ThreadRuntimeFactory`, which add a `fnCache` parameter so that it can reuse the `fnCache` created in `JavaInstanceStarter`
3. make `ThreadRuntime#loadJars` public so it can be called in the `JavaInstanceStarter`
4. use the function class loader to infer type class instead of the instance class loader(which cannot load the user's function class)
5. check whether `userConfigs` is null before calling `userConfigs.containsKey`
6. use `functionDetailsBuilder.getSink().getClassName()` to …
=> [fix][fn] Fix JavaInstanceStarter inferring type class name error

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java
* This fixes #13489
* This fixes #14779
There is a chance if a topic reassign to a broker that owned this topic once, consumer reconnect will failure with `BadVersionException`, here's detail: https://github.com/apache/pulsar/issues/14779#issuecomment-1554473113
Reproduce steps:
1. a topic deleted in broker1
2. recreate the topic in broker2, start a consumer with it
3. broker crash or bundle split, topic reassign to broker1, by now consumer will reconnect failure
Cleanup metadata children cache if managed-ledger key deleted
PR in forked repository: https://github.com/Shawyeok/pulsar/pull/7
=> [fix][broker] Invalidate metadata children cache after key deleted

.github/workflows/pulsar-ci.yaml, build/run_unit_group.sh, pom.xml, pulsar-io/pom.xml
- the tests in Pulsar IO are extremely slow and could cause the current 75 minute limit to exceed.
- elastic-search tests are the slowest Pulsar IO tests
- Elasticsearch tests took over 12 minutes here: https://ge.apache.org/s/ge3kvi7torsxq/performance/execution#goal-mlju2z5u77bvw 
- Also seen here: https://ge.apache.org/s/ge3kvi7torsxq/tests/overview 
- Kafka Connect Adaptor & Debezium tests are another set of slow tests
- add new maven profile pulsar-io-elastic-tests that can be used to target Elasticsearch tests
- run Elasticsearch tests in a separate build job
- add new maven profile pulsar-io-kafka-connect-tests that can be used to target Kafka Connect related tests
- run Kafka Connect adaptor tests in a separate build job
=> [improve][ci] Split Pulsar IO unit test job to multiple jobs

pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java
Fixes #20386
See #20386
Use Awaitility in test. Consume and acknowledge messages with messageListener.
=> [fix][test] Fix flaky test NonPersistentTopicTest.testMsgDropStat

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java
Due to PIP-195 introducing `BucketDelayedDeliveryTracker`, some document descriptions need to be changed.
Improve doc for delayed message tracker.
=> [improve][doc] Improve doc for delayed message

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/SystemTopicNames.java, pulsar-common/src/test/java/org/apache/pulsar/common/naming/SystemTopicNamesTest.java
Fixes #20376 
The `__change_events` system topic is created in each namespace. It is used for topic policies. The `SystemTopicNames#isSystemTopic` classifies partitioned and non-partitioned `__change_events` topics as system topics. The `SystemTopicNames#isTopicPoliciesSystemTopic` only classifies non-partitioned `__change_events` topics as topic policies system topics. I think this is a bug, and we need to make sure that parititioned `__change_events` topics are topic policies system topics.
Note: I am not sure that it is recommended to use a partitioned topic for the topic policies, but for backwards compatibility, I think we have to classify a partitioned `__change_events` topic as a topic policies topic. Since https://github.com/apache/pulsar/pull/10850, we test partitioned …
=> [fix][broker] partitioned __change_events topic is policy topic

pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java
Fixes #20386
- the previous attempt #20387 to fix the flakiness wasn't effective
- improve the fix and rely on the fact that entryId is -1 when the message is dropped in the broker
code: https://github.com/apache/pulsar/blob/091ee2504ffbe6ec98e354b76e7f4c045e1914aa/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L1699-L1711
=> [fix][test] Fix flaky test NonPersistentTopicTest.testMsgDropStat, follow up

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
- mutating the singleton base cursor properties accidentally would cause a hard-to-debug bug
- use immutable maps for base cursor properties which are shared singletons
=> [improve][broker] Use immutable base cursor properties

pom.xml
```
Error:  Failed to execute goal org.owasp:dependency-check-maven:8.1.2:aggregate (default) on project pulsar: 
Error:  
Error:  
Error:  sqlite-jdbc-3.36.0.3.jar: CVE-2023-32697(8.8)
```
Upgrade sqlite-jdbc
=> [fix][sec] Upgrade sqlite-jdbc to resolve CVE-2023-32697

.github/workflows/pulsar-ci.yaml
OWASP dependency check within Pulsar CI workflow is really slow.
- speed up check in Pulsar CI workflow
- don't build artifacts when running dependency check
=> [improve][ci] Speed up OWASP dependency check in Pulsar CI workflow

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerMBeanImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/EntryCacheDisabled.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java
ledger cache miss rate should be same as ledgerFactory cache miss rate.  For details, the major fix is that the `count` always increace 1 when `entriesToReturn.size()` is greater thant one, e.g., line453 at `RangeEntryCacheImpl.java`
ledger cache miss rate should be same as ledgerFactory cache miss rate
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/38
=> [fix][broker] Fix ledger cachemiss size metric

buildtools/src/main/java/org/apache/pulsar/tests/FailFastNotifier.java, buildtools/src/main/java/org/apache/pulsar/tests/PulsarTestListener.java
In order to investigate some flaky test failures such as #20386, it is necessary to add logging to find out what was the failure of the first attempt. In some cases, the exception in the test retry is not the root cause.
In the case of #20386, there's "Index 0 out of bounds for length 0" recorded in the skip message:
```
<testcase name="testMsgDropStat" classname="org.apache.pulsar.client.api.NonPersistentTopicTest" time="0">
<skipped message="Index 0 out of bounds for length 0"/>
```
However, the full exception isn't logged. 
- Log possible exceptions before retrying a test run
- this will help debug issues when tests are retried
- Don't log anything when skipping is a result of fail fast mode (SkipException)
- Execute cleanup methods when using fail fast mode
- the change in #19252 …
=> [improve][ci] Improve TestNG test execution to debug flaky test failures

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
`PersistentSubscription.expireMessages` will first backlog is zero and if not will check if backlog is below threshold.
those two check should be save in variable to avoid check twice. 
save backlog to variable.
=> [improve] [broker] Avoid `PersistentSubscription.expireMessages` logic check backlog twice.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/StringInterner.java
It is not recommended to use `String.intern()` at all. Guava contains a better replacement in it's Interner class.
One of the problems with `String.intern()` is that it could expose the server to a certain type of Denial of Service (DoS) attack. Any String instance that is interned with String.intern(), will remain in memory until the JVM is restarted. An attacker can use this to cause a denial of service. With Guava's weak reference based interner `Interners.newWeakInterner()`, there is no such problem.
`String.intern()` might cause memory leaks outside of DoS attacks since the instances will never be collected by GC.
That's one of the reasons why Guava's weak reference based solution is more robust.
Gradle build tool has been using Guava's interner for years (since it was introduced in …
=> [improve][broker] Replace String.intern() with Guava Interner

pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java
Fixes #20386
- the previous attempts #20387 and #20401 to fix the flakiness weren't effective alone
- add `.ignoreExceptions()` to Awaitility call
- underlying issue was IndexOutOfBoundsException which doesn't get retried by Awaitility unless `.ignoreExceptions()` has been called. The root cause was hidden by TestNG retries. There's another PR to improve this by adding some logging, #20425
- docs for `ignoreExceptions()`: https://github.com/awaitility/awaitility/wiki/Usage#ignoring-exceptions
- general test logic improvements
- use unique topic name
- use Closeable to close producer and consumers
- assert that the latch was triggered
=> [fix][test] Fix flaky test NonPersistentTopicTest.testMsgDropStat, 3rd attempt

pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java
Fixes #20395
org.apache.pulsar.broker.TransactionMetadataStoreService#handleTcClientConnect
The real cause may be wrapped in the CompletionException, we should unwrap the real cause from CompletionException and complete the request with real causes like this:
unwrap the completion exception to retrieve real cause.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/22
=> [Fix] [Txn] unwrap the completion exception.

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
#5358 makes the thread switch to the metadata store thread after the ZK operation.
#13043 Add the feature `batch operation` for `ZKMetadataStore`, but after the batch operation is done, the thread is not switched back.
Now, if we call `put /a`, it will use the `event thread` of the ZK client after the operation; but if we call `put /a/b/c`(the node `/a` is not exists), it will use the `metadata store thread`  after the operation.
- Switch to the metadata store thread after the batch operation.
- If there has any exception, error handling also uses the metadata store thread
- x
=> [fix] [meta]Switch to the metadata store thread after zk operation

pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BaseMetadataStoreTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
This pr is follow suggestion from https://github.com/apache/pulsar/pull/20363#issuecomment-1566419553, add unit test for #20363
- Add `MetadataStoreTest#testExistsDistributed` for distributed metaStore implementations only
- Add `MetadataStoreTest#testGetChildrenDistributed` for distributed metaStore implementations only
PR in forked repository: https://github.com/Shawyeok/pulsar/pull/8
=> [improve][test] Add unit test for metadata cache #20363

conf/broker.conf, conf/standalone.conf, deployment/terraform-ansible/templates/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/BookKeeperClientFactoryImplTest.java
Since https://github.com/apache/bookkeeper/pull/3719 has set limitStatsLogging config default true in bookie, it is better to also set it default true in broker config.
PR in forked repository: https://github.com/TakaHiR07/pulsar/pull/8
=> [improve][broker] Change limitStatsLogging config default value to true

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SinksImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SourcesImpl.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
Fixes #19721 
PIP: #xyz 
functions are failed to update when `--py|--go|--jar` is specified
add 1 to functions' version when uploading package while updating functions
*(or)*
*(or)*
- *Added integration tests for updating function code file*
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/8
=> [fix][fn] Fix function update error

pulsar-function-go/pf/instance.go, pulsar-function-go/pf/util.go
Fixes #19367
Retrieve consumers from the index based off of non-partitioned topic name.
**Note**: there is no e2e for Go pulsar functions. Verifying this change is a matter of not having panics when using pulsar functions with partitioned topics.
PR in forked repository: https://github.com/flowchartsman/pulsar/pull/3
=> [fix][fn] Go functions must retrieve consumers by non-particioned topic ID

pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java, pulsar-common/src/test/java/org/apache/pulsar/common/naming/TopicNameTest.java, tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileStoreBackedReadHandleImpl.java, tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java, tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloaderTest.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedInputStreamImpl.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImplV2.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloader.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlockAwareSegmentInputStreamImpl.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderTest.java
Related issue #20355 
The current implementation has the following issues:
1. When constructing offload metrics, using the managedLeger name as topicName results in an incorrect format, causing abnormal display of metrics on Grafana.
2. When calculating offload bytes for Filesystem offload, it incorrectly calculates the actual write value, resulting in much larger metrics than the actual value.
1. Add the `fromPersistenceNamingEncoding` method to `TopicName` and use mlname to obtain the topic name.
2. Replace the part of using mlname in the logic of topic label before offload metrics with using topicname.
3. Modify the logic of `recordOffloadBytes` in filesystem offloader, change `entry.getLength()` to `entry.getEntryBytes().length`.
*If …
=> [fix][offload] fix offload metrics error

pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java
The `bucketDelayedIndexStats` is an internal statistic, we don't expose to the user.
Add the @JsonIgnore annotation to the above fields.
=> [improve][broker] Do not expose bucketDelayedIndexStats

pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
After the PR #20303 was cherry-picked inti `branch-2.11`, the test `testThreadSwitchOfZkMetadataStore` was failed.
The root cause: the attribute `metadataStoreName` is a new attribute provided by the PR https://github.com/apache/pulsar/pull/17041, at it released at `3.0.0`, so it is not included in `branch-2.11`, so the name of thread-pool of Metadata store is a fixed value `metadata-store`
```java
protected AbstractMetadataStore() {
this.executor = Executors
.newSingleThreadScheduledExecutor(new DefaultThreadFactory("metadata-store"));
registerListener(this);
...
}
```
Instead of a special value, verify the name of the thread pool by the fixed value `metadata-store`
=> [fix][test] Fix test `testThreadSwitchOfZkMetadataStore`

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
Fixes #20262
When there are hole messages, there is a bug in the API of skipping the message, please refer to the [issue](https://github.com/apache/pulsar/issues/20262) for the specific reason
Remove `recyclePositionRangeConverter`,  revert to normal loop.
PR in forked repository: (https://github.com/crossoverJie/pulsar/pull/8)
=> [fix][broker] Fix skip message API when hole messages exists

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceBundleSplitListener.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceCreateBundlesTest.java
PIP: #19806
In PIP-219, we want to make the partition assignment strategy pluggable.
First, we need to add listener interface for namespace service
=> [feat][broker]PIP-255 Part-1: Add listener interface for namespace service

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerFactoryConfig.java
Cleanup `numManagedLedgerWorkerThreads` from `ManagedLedgerFactoryConfig`. Because it was never used anywhere
Cleanup `numManagedLedgerWorkerThreads` from `ManagedLedgerFactoryConfig`
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/40
=> [cleanup][ml] cleanup numManagedLedgerWorkerThreads

pulsar-function-go/pf/instance.go
Fix apache/pulsar#20449
Master Issue: #20449
PR in forked repository: https://github.com/flowchartsman/pulsar/pull/5
=> [fix][fn]Reset idle timer correctly

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE, pulsar-sql/presto-distribution/pom.xml
Upgrade Guava to 32.0.0 to address CVE-2023-2976
More details in Guava 32.0.0 release notes: https://github.com/google/guava/releases/tag/v32.0.0
=> [fix][sec] Upgrade Guava to 32.0.0 to address CVE-2023-2976

pulsar-functions/utils/pom.xml, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/FunctionCommonTest.java
Fixes #20463
CI is broken at the moment since one of the test depends on an online service httpbin.org that is currently unavailable.
```
Error:  Tests run: 15, Failures: 1, Errors: 0, Skipped: 13, Time elapsed: 32.262 s <<< FAILURE! - in org.apache.pulsar.functions.utils.FunctionCommonTest
Error:  org.apache.pulsar.functions.utils.FunctionCommonTest.testDownloadFileWithBasicAuth  Time elapsed: 10.029 s  <<< FAILURE!
java.io.IOException: Server returned HTTP response code: 504 for URL: ***httpbin.org/basic-auth/foo/bar
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2000)
at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputS …
```
=> [fix][test] Remove dependency on httpbin.org service in FunctionCommonTest

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
Jetty contains new vulnerabilities CVE-2023-26048 and CVE-2023-26049.
Upgrade to 9.4.51.v20230217 to address the vulnerabilities.
=> [fix][sec] Upgrade Jetty to address CVEs

pulsar-broker/pom.xml, pulsar-broker/src/test/java/org/apache/pulsar/client/api/TokenOauth2AuthenticatedProducerConsumerTest.java
Fixes #19330 
Replace calls to Auth0 with calls to a local WireMock server. The server behaves in essentially the same way as Auth0.
Update `TokenOauth2AuthenticatedProducerConsumerTest`.
The modified test passes and still covers the same code.
=> [fix][test] Replace test call to Auth0 with call to WireMock

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java
When `ThresholdShedder` unloads namespace bundles from an overloaded broker, it would be useful to log resource usage of that broker. This is the same change I made to `OverloadShedder` earlier: https://github.com/apache/pulsar/pull/6152
=> [improve][broker] Log resource usage rate of brokers that need to be offloaded in ThresholdShedder

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationProvider.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java
Current AuthorizationProvider does not actually fully support the revocation of ACLs :
- Revocation is only supported for subscription-specific ACLs on a namespace
-  When we revoke the permission on Pulsar admin REST API, the handler will always try to remove it from the namespace policies ([https://github.com/apache/pulsar/blob/242758d5770de46e506855ff881472cbc274cedb/pul[…]in/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java](https://github.com/apache/pulsar/blob/242758d5770de46e506855ff881472cbc274cedb/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L655)), instead of asking the AuthorizationProvider to do so.
=> [improve][broker] Support revoking permission for AuthorizationProvider

build/docker/Dockerfile
It's usually suggested to add `--no-cache-dir` in dockerfile because PIP cache is useless in image and we can also reduce the image size by disabling the cache. 
Add the `--no-cache-dir` in dockerfile pip3 command. 
*(or)*
*(or)*
*(example:)*
=> [improve][build] add `--no-cache-dir` in dockerfile to disable the pip cache

tests/integration/src/test/java/org/apache/pulsar/tests/integration/bookkeeper/BrokerInstallWithEntryMetadataInterceptorsTest.java
Fixes [20091](https://github.com/apache/pulsar/issues/20091)
This adds an important regression test preventing the error reported by https://lists.apache.org/thread/f2fhvyx202xzxbho909j430h63yvwjlo. 
*(example:)*
1. `PULSAR_TEST_IMAGE_NAME=massimilianomirelli/pulsar-test-latest-version:bad-20091 mvn -f tests/pom.xml test -Dtest=BrokerInstallWithEntryMetadataInterceptorsTest -DintegrationTests` -> expected: fail
2. `mvn -f tests/pom.xml test -Dtest=BrokerInstallWithEntryMetadataInterceptorsTest -DintegrationTests` -> expected: pass
I verified that 1. fails outputting the error as per the description posted by @michaeljmarshall on the mailing list:
```
2023-05-25T06:16:10,753+0000 [broker-topic-workers-OrderedExecutor-5-0] ERROR …
```
=> [improve][test] Implement broker integration test with entry metadata interceptors enabled

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java
We support configuring custom TLS trusted certs when running functions, but not when downloading them. This PR fixes that by mapping the configuration in the same way we do with functions:
https://github.com/apache/pulsar/blob/f04252b84a8b594ea371645e367c491aa8e2dd80/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java#L425-L434
* Configure using TLS, allowing insecure TLS, hostname verification, and the custom trusted cert path
I added a new test.
=> [fix][fn] Support customizing TLS config for function download command

pulsar-function-go/conf/conf.go, pulsar-function-go/pf/instanceConf.go, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/go/GoInstanceConfig.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/RuntimeUtilsTest.java
Fixes #20442
In order to give Go functions access to state, and admin services, they need to be exposed to them. There's no particular reason not to ship these to the Go instance, and they will be needed to develop these features.
- Extended runtimeutl tests
PR in forked repository: https://github.com/flowchartsman/pulsar/pull/4
=> [feat][fn] Add stateStorageURL and pulsarWebService URL to go InstanceConfig

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java, pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java
=> [fix][io] Close the kafka source connector if there is uncaught exception

pom.xml, src/owasp-dependency-check-suppressions.xml
OWASP dependency check fails because of false positives.
- jetcd shouldn't match etcd or grpc CVEs
- add proper suppression rules that cover this
- keep OWASP Dependency Check version up-to-date
- Upgrade to 8.2.1 version
=> [fix][ci] Fix OWASP dependency check suppressions

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
Fixes #20492
The test BrokerServiceTest#testBrokerStatsTopicLoadFailed introduced in #19236 is invalid. 
* It modifies the current shared state and that causes other tests to fail. 
* The test uses Awaitility with a 2 minute timeout. That is too long for unit tests.
- disable the test until it is fixed
=> [fix][test] Disable invalid test BrokerServiceTest#testBrokerStatsTopicLoadFailed

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java
Minor optimization for metrics generation in functions. String concatenation is faster than string format. This is valuable in the context of metrics where we can generate many strings in a tight loop.
* Replace `String.format` with string concatenation in several locations.
* Only create metrics prefix once.
=> [improve][fn] Optimize string concatenation in user metrics gen

build/docker/Dockerfile, docker/pulsar/Dockerfile, pom.xml, tests/docker-images/java-test-image/Dockerfile
Upgrade Ubuntu to 22.04 to fix some CVEs
- CVE-2017-14063: https://nvd.nist.gov/vuln/detail/cve-2017-14063
- CVE-2021-27291: https://nvd.nist.gov/vuln/detail/CVE-2021-27291
- CVE-2021-20270: https://nvd.nist.gov/vuln/detail/CVE-2021-20270
=> [fix][misc] Use ubuntu 22.04 for Pulsar images

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockOIDCIdentityProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/TokenOauth2AuthenticatedProducerConsumerTest.java, pulsar-broker/src/test/resources/authentication/token/credentials_file.json, pulsar-proxy/pom.xml, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTlsTestWithAuth.java, pulsar-testclient/pom.xml, pulsar-testclient/src/test/java/org/apache/pulsar/testclient/Oauth2PerformanceTransactionTest.java, pulsar-testclient/src/test/resources/authentication/token/credentials_file.json
Fixes #20473 
Our tests should be independent of external services like Auth0. We can use `WireMock` to create a server that responds to all OAuth2 requests. This PR removes calls to Auth0.com and replaces them with calls to a wiremock server.
* Add a generic class to create an OIDC/OAuth2 wiremock server that can be used to get tokens.
Tests are modified and still pass.
=> [fix][test] Replace calls to Auth0 with calls to wiremock

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
Currently deleted messages are checked in the order that individual messages are checked first and then comparing the mark delete position after this. Since the check for the mark delete position is a simple check, it's more efficient to check that first.
- change order of condition evaluation
- omit creation of PositionImpl instances in trimDeletedEntries
=> [improve][broker] Improve efficiency of checking message deletion

.github/workflows/ci-license.yaml, pom.xml
There is an error in the ci-license on branch-2.10:
```
Error:  Failed to execute goal org.apache.nifi:nifi-nar-maven-plugin:1.5.0:nar (default-nar) on project tiered-storage-jcloud: The plugin org.apache.nifi:nifi-nar-maven-plugin:1.5.0 requires Maven version 3.6.3 -> [Help 1]
```
More detail [here](https://github.com/apache/pulsar/actions/runs/5175944795/jobs/9324167082#step:9:8).
* Use maven 3.6.3 in ci-license
=> [fix][build][branch-2.10] Fix ci-license check

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java, pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java
=> [fix][io][branch-2.10] Close the kafka source connector if there is uncaught exception

docker/build.sh, docker/get-version.sh, docker/pom.xml, docker/publish.sh, docker/pulsar-all/Dockerfile, docker/pulsar-all/pom.xml, docker/pulsar/pom.xml, pom.xml, pulsar-common/pom.xml
Fixes #20420
When building the release candidate, the release mangers use their own account name to build and push the pulsar image. But currently the `pulsar-all` image always use `apachepulsar/pulsar` as the upstream image. And it may won't use the locally built image, which causes the issue.
* Specify the correct image name for `pulsar` image to build `pulsar-all`
* Remove the `latest` version from the build. The `latest` tag should only point to the latest major version. It's better to let the release manager specify the latest tag manually.
* Add github commit id to the image tag.
The image would like: apachepulsar/pulsar:3.1.0-SNAPSHOT-97a1a87
* Prepare the `pulsar` image: `docker tag apachepulsar/pulsar:3.0.0 snzkyang/pulsar:3.1.0-SNAPSHOT-97a1a87` 
* Run the build command of …
=> [fix][build] Fix the pulsar-all image may use the wrong upstream image

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PartitionKeywordCompatibilityTest.java
Same as #19230, We allow users to use the `Client API` to create the partitioned topic which name contains `-partition-{not-number}` when they enable partitioned type auto-creation. 
But we didn't get stats and update it.
Support getting stats and updating partitioned topics with the keyword `-partition-{not-number}`
=> [fix][broker] Support getStats/update partitioned topic with `-partition-`

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java
#20482 broke the function download command with this error:
```
Expected a command, got false
Usage: pulsar-admin [options] [command] [command options]
Options:
--admin-url
Admin Service URL to which to connect.
Default: http://localhost:8080/
```
The problem is that the TLS args for hostname verification and for insecure TLS are zero arity, and therefore, we should not add the `false` or the `true` arguments.
* Correct the changes made to the TLS args passed to the `pulsar-admin` CLI tool
=> [fix][fn] TLS args admin download command use zero arity

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdSources.java
Fixes #20485
As title describes, to help users be informed about failed command immediately (presumably automatically, for instances where scripts are written and used).
Currently, when `CmdSources` commands fail, process returns exit code `0` even though the log shows it is apparently an error.  For example, following command `bin/pulsar-admin sources create --source-config-file NON-EXISTENT-FILE.yaml` will log all error messages, but exit with code 0.
Such current behavior is rooted in `CmdSources.BaseCommand.run()` method, where `Exception` thrown by `processArguments()` is caught and "just" returns. This PR changes that.
- `CmdSources` : `run()` to throw exceptions instead of silent-catch and return.
PR in forked repository: https://github.com/JooHyukKim/pulsar/pull/6
=> [fix][admin] Make failed `bin/pulsar-admin source` command exit with code `1 (failed)`  instead of `0 (success)`

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerBkEnsemblesTests.java
It's possible to get into a situation where there are multiple topic instances for the same topic getting unloaded and loaded in the same broker concurrently. 
A solution for addressing this problem was introduced in #17526.
However, the solution was removed in #17736 since the call `brokerService.removeTopicFromCache(PersistentTopic.this)` was replaced with the call `brokerService.removeTopicFromCache(topic)` since there was the old method signature available in the class. 
- restore the call to `brokerService.removeTopicFromCache(PersistentTopic.this)` 
- remove the method with the incorrect method signature
=> [fix][broker] Restore solution for certain topic unloading race conditions

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java
Fixes #20376
AdminApi2Test is extremely flaky and causes most builds to fail. 
- calling resetConfig method between test methods is the wrong solution since it creates a new instance and the running broker will keep using the old instance
- reset properties on the existing conf instance
- use unique tenants and namespaces to make it easier to track where the possibly conflicting topics were created, if the problems preserve
- add a better solution for resetting state between test methods when it is needed
- catch exceptions in deletion and restart the cluster in the case of exceptions
- this will handle the flakiness with resetClusters. 
- The tradeoff is that it could hide some problems that the flakiness is revealing.
=> [fix][test] Reduce flakiness of AdminApi2Test

pom.xml
- keep the dependency up-to-date
Upgrade Testcontainers to 1.18.3 and docker-java to 3.3.0 .
docker-java version has to be kept in sync with Testcontainers version.
The correct version can be found in the testcontainers pom. For example for 1.18.3, one can find the docker-java version here: https://repo1.maven.org/maven2/org/testcontainers/testcontainers/1.18.3/testcontainers-1.18.3.pom
=> [improve][build] Upgrade Testcontainers to 1.18.3 & docker-java to 3.3.0

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/EntryFilterSupport.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SystemTopic.java
Applying EntryFilters for system topics is not very useful and could cause problems.
I noticed this while investigating the flaky AdminApi2Test. 
Skip applying entry filters for system topics.
=> [fix][broker] Disable EntryFilters for system topics

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
When using `ExtensibleLoadManager` and list in bundle admin API,
it will redirect forever because `isServiceUnitOwned` method is checking the `ownershipCache` as the ownership storage, however, when using `ExtensibleLoadManager`, it stored the ownership to table view.
* Call `isServiceUnitOwnedAsync ` when using `isServiceUnitOwned `.
* Add unit test to cover this case.
=> [fix][broker] Fix redirect loop when using ExtensibleLoadManager and list in bundle admin API

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CliCommand.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBookies.java
Pretty print the output from "bin/pulsar-admin bookies racks-placement" command so that it is in a more readable format 
Use Gson package to pretty print the output of the above command
This change is already covered by existing tests, such as bookies() testcase in PulsarAdminToolTest.java
=> [improve][admin] Pretty print bookies racks-placement command output

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PackagesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/PackagesApiTest.java, pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/impl/PackagesManagementImpl.java
Make the Exception more clear.
Return the `409 Conflict` instead of `404 NoFound` when metadata already exists.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Should not throw NotFoundException when metadata already exists.

pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java
Fixes #20536
When disabling HTTP ports in the Pulsar broker, the [REST Client Producer](https://pulsar.apache.org/docs/3.0.x/client-libraries-rest/) fails to produce messages. For reproduction steps, please reference issue details.
Change the following lines:
```java
LookupResult result = optionalResult.get();
if (result.getLookupData().getHttpUrl().equals(pulsar().getWebServiceAddress())) {
// Current broker owns the topic, add to owning topic.
```
To:
```java
LookupResult result = optionalResult.get();
if (result.getLookupData().getHttpUrl().equals(pulsar().getWebServiceAddress())
|| result.getLookupData().getHttpUrlTls().equals(pulsar().getWebServiceAddressTls())) {
// Current broker owns the topic, add to owning topic.
```
This change is a trivial rework / code cleanup without any …
=> [fix][broker] REST Client Producer fails with TLS only

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
Some pulsar plugins like [KoP](https://github.com/streamnative/kop) require using the namespace bundle listener to be aware of the bundle load or unload event. In KoP it will use to immigrate or emigrate the group/txn coordinator data.
But in the extensible load manager, we do not trigger the event.
* Trigger the unload/load/split event when using the extensible load manager.
* Add unit test to verify this feature.
=> [improve][broker] Emit the namespace bundle listener event on extensible load manager

pom.xml
Follow up on #20435 changes to fix build that could fail with git describe error "fatal: No names found, cannot describe anything."
Full error message:
```
19:01:27  [ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.9.10:revision (git-info) on project 
docker-images: Could not complete Mojo execution... pl.project13.core.NativeGitProvider$NativeCommandException: 
Git command exited with invalid status [128]: directory: `/home/ubuntu/workspace/Apache_Pulsar__Deploy_branch-3.0/docker`, 
command: `git describe --dirty=-dirty --match=* --abbrev=7`, stdout: ``,
stderr: `fatal: No names found, cannot describe anything.` -> [Help 1]
```
- Configure git-commit-id-plugin to skip "git describe"
- Ignore errors when git-commit-id-plugin fails too run the git command
- similar …
=> [fix][build] Configure git-commit-id-plugin to skip git describe

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
When topic load fail to acquire semaphore. a TopicLoadingContext is push into pendingLoadQueue, current TopicLoadingContext should also save the createIfMissing param in the TopicLoadingContext.
add field in TopicLoadingContext.
=> [improve][broker] Save createIfMissing in TopicLoadingContext

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
Move the authorization check a few steps earlier in the delete subscription admin endpoint.
* Move the authz check earlier
We do not have any tests for these endpoints. We should add them. This change is trivial enough that I think it is fine to defer on testing the authz change.
=> [cleanup][broker] Validate authz earlier in delete subscription logic

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdGenerateDocument.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/CmdGenerateDocs.java
https://github.com/apache/pulsar-site/pull/603
To make the navigation bar work better, I changed the method of generating reference docs titles.
just modified the logic of reference docs generation. Other words: ### <em>title</em> ---> ### title
Hi @tisonkun PTAL.
and I didn't find the generating method for `bookkeeper`, `pulsar-daemon` and `pulsar-shell`, are they also automatically generated?
=> [fix][doc] change the method of generating reference docs titles.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
Currently, all subscriptions of one topic will do `consuemrFlow` action in a single thread, which is chosen by topicName:
```
this.topicExecutor = topic.getBrokerService().getTopicOrderedExecutor().chooseThread(topicName);
```
If there is a large number of subscriptions in a topic,  all the work will focus on one thread ---- the chosen thread, which will reduce the consume performance.  So this this patch , I'd like to choose a ramdom thread for `consumerFlow` in `PersistentDispatcherSingleActiveConsumer` to improve the consume performance.
*  `topic.getBrokerService().getTopicOrderedExecutor().chooseThread(topicName);` -> `topic.getBrokerService().getTopicOrderedExecutor().chooseThread();`
*  `this.topicExecutor ` -> `this.executor` …
=> [improve][broker] Choose random thread for consumerFlow in PersistentDispatcherSingleActiveConsumer

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
The `ExtensibleLoadManager` does not handle the `GetOwnedServiceUnits` method and `GetOwnedNamespaceStatus` method. 
Since the `ServiceUnitStateChannel` will store all the owner status, we need to filter all the other brokers when get owned service units to make the behavior the same as `OwnershipCache`
* Support `GetOwnedServiceUnits` method to get current broker ownership.
* Support getOwnedNamespaces admin API.
* When enabling `ExtensibleLoadManager` make sure we handled all unloading calls.
=> [improve][broker] Handle get owned namespaces admin API in ExtensibleLoadManager

tests/integration/src/test/java/org/apache/pulsar/tests/integration/auth/token/PulsarTokenAuthenticationBaseSuite.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/ClientToolTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/PerfToolTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/CSContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ZKContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java
Code cleanup so that we read code more smoothly ..
=> [cleanup][test] CSContainer needs not to inherit from ZKContainer

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
Example Error Logs
```
Caused by: org.apache.pulsar.client.api.PulsarClientException$BrokerMetadataException: The subscription __compaction of the topic persistent://pulsar/system/loadbalancer-service-unit-state-partition-0 gets the last message id was failed
{"errorMsg":"Failed to get batch size for entry org.apache.bookkeeper.mledger.ManagedLedgerException: Error while reading ledger error code: -1","}
at org.apache.pulsar.client.api.PulsarClientException.wrap(PulsarClientException.java:977) 
at org.apache.pulsar.client.impl.ConsumerImpl.lambda$internalGetLastMessageIdAsync$61(ConsumerImpl.java:2424)
... 29 more
```
This system topic `persistent://pulsar/system/loadbalancer-service-unit-state-partition-0` should be a non-partitioned topic after this fix …
=> [fix][broker] new load balancer system topic should not be auto-created now

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
The heartbeat namespace bundle requires acquiring ownership when broker starts,
however, the `ExtensibleLoadManager` does not handle this case,
we should register the heartbeat namespace to let the health check work.
* Add `tryAcquiringOwnership` method to acquire the local broker ownership
=> [fix][broker] Handle heartbeat namespace in ExtensibleLoadManager

pip/README.md
Added a small step in the PIP process to explain the body of the message for a vote message.
=> [fix][doc] Explain vote email body in pip process

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractReplicatorTest.java
Cherry-pick #20567
When the `replicator.producer` retries to start<sup>[1]</sup> the topic close<sup>[2]</sup> executed concurrently, there is an orphan replicator after this topic is closed. You can reproduce by the test `testRetryStartProducerStoppedByTopicRemove `
| time | `restart producer of a replicator` | `topic.close` |
| 1 | Compare and set state: `Starting -> Stopped` | 
| 2 | Add a delay task to try to start the producer again |
| 3 | | Close topic |
| 4 | The delayed task executed |
| 5 | If fail, retry again and loop |
**[1]**: https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java#L151
**[2]**: https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsa …
=> [fix][broker] Release orphan replicator after topic closed

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SnapshotSegmentAbortedTxnProcessorImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionBufferClientTest.java
During the recovery process, if the system topic `__transaction_buffer_snapshot` is not located on the same broker as the common topic, it can cause issues and result in a `ServiceUnitNotReadyException`, leading to recovery failure. The current approach of using `topic.getBrokerService().getTopic()` to check the existence of the system topic can trigger errors during the `checkTopicNsOwnership` step. 
To avoid potential recovery failures and ensure a reliable check for topic existence, we should use the `pulsarResource` feature. By utilizing `pulsarResource`, we can list the persistent topics in the namespace and verify whether the system topic exists on any broker. This approach provides a more robust solution, preventing the occurrence of `ServiceUnitNotReadyException` and ensuring …
=> [fix][txn] Use PulsarResource  check for topic existence instead of brokerservice.getTopic()

tiered-storage/file-system/pom.xml
Fixes #16955 
fix the problem about Failing to start standalone pulsar service with tiered storage due to class not found problem
The reason is the lack of dependencies for the `org.apache.hadoop.hdfs.DistributedFileSystem` class.
add DistributedFileSystem class dependency `hadoop-client` in pom.xml
PR in forked repository:  https://github.com/ethqunzhong/pulsar/pull/5
=> [fix][offload] use filesystem offloader with class not found error

.github/PULL_REQUEST_TEMPLATE.md
As title describes. Same as to why Github stopped using `master` as default branch. I believe `parent` issue will suffice.
- Modified `PULL_REQUEST_TEMPLATE.md`
I don't think we need one here.
=> [improve][ci] Move away from using the term `master` in PR template 

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
The issue should only happen on the topic with many producers, and the max producer limitation is enabled. When a new producer is added, the broker will check all the existing producers and filter out the remote producer (from the replicator), which will run out of the CPU resource for a short period of time.
[profiler.html.txt](https://github.com/apache/pulsar/files/11788992/profiler.html.txt)
A counter will be much more efficient instead of going through all the producers. So a new userCreatedProducerCount is added to the topic.
The existing tests already covered the max producer limitation. The change will not affect the correctness.
=> [fix][broker]fix the publish latency spike issue with large number of producers

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
Remove unused cache executor in PulsarService
=> [cleanup][broker] Remove unused cache executor in `PulsarService`

pom.xml, tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java
Fixes #20608
ExtensibleLoadManagerTest.testIsolationPolicy is flaky
- make condition match what the error is in the flaky case
- cleanup admin client resources
=> [fix][test] Fix flaky test ExtensibleLoadManagerTest.testIsolationPolicy

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
OWASP dependency check has detected multiple CVEs in snappy-java
- Upgrade snappy-java to 1.1.10.1 to address multiple CVEs:
- CVE-2023-34453 
- CVE-2023-34454
- CVE-2023-34455
See https://github.com/xerial/snappy-java/releases/tag/v1.1.10.1
=> [fix][sec] Upgrade snappy-java to address multiple CVEs

src/owasp-dependency-check-suppressions.xml
OWASP dependency check is failing because of CVE-2023-35116 in jackson-databind
Suppress false positive CVE-2023-35116 in jackson-databind
- see https://github.com/FasterXML/jackson-databind/issues/3972#issuecomment-1596604021
=> [fix][sec] Suppress false positive CVE-2023-35116 in jackson-databind

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
When using KoP protocol, the KoP will `NamespaceService#addNamespaceBundleOwnershipListener` before the broker start, however, at this time, the `ExtensibleLoadManagerImpl` not start yet. So it will cause NPE.
We should return an empty set when `ExtensibleLoadManagerImpl` does not start.
* Add a check when `getOwnedServiceUnits`.
* Add units test to cover this case.
=> [fix][broker] Fix get owned service units NPE

pip/pip-275.md
This is a pip to Introduce `topicOrderedExecutorThreadNum` to deprecate `numWorkerThreadsForNonPersistentTopic`
=> [pip][design] PIP-275: Introduce topicOrderedExecutorThreadNum to deprecate numWorkerThreadsForNonPersistentTopic in configuration

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
OWASP dependency check fails because of CVE-2023-34462
```
Error:  netty-handler-4.1.93.Final.jar: CVE-2023-34462(8.8)
```
Upgrade Netty to 4.1.94.Final
Release notes: https://netty.io/news/2023/06/19/4-1-94-Final.html
=> [fix][sec] Upgrade Netty to 4.1.94.Final to address CVE-2023-34462

bouncy-castle/bc/LICENSE, bouncy-castle/bc/pom.xml, distribution/server/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-broker-auth-athenz/pom.xml, pulsar-client-auth-athenz/pom.xml, pulsar-client-messagecrypto-bc/src/main/java/org/apache/pulsar/client/impl/crypto/MessageCryptoBc.java, pulsar-io/aerospike/pom.xml, pulsar-sql/presto-distribution/LICENSE, tests/integration/pom.xml, tiered-storage/file-system/pom.xml
OWASP Dependency Check fails
```
Error:  bcprov-ext-jdk15on-1.69.jar: CVE-2023-33201(6.5)
Error:  bcprov-jdk15on-1.69.jar: CVE-2023-33201(6.5)
```
Upgrade Bouncycastle to 1.75 to address [CVE-2023-33201](https://github.com/bcgit/bc-java/wiki/CVE-2023-33201).
Bouncycastle has switched to Java 8 (1.8) as the baseline since 1.71. When upgrading to 1.75, it is necessary to
exclude the`bc*-jdk15on` dependencies and instead use the `bc*-jdk18on` dependencies. Since many libraries 
have the jdk15on dependency as a transient dependency, it is necessary to handle the exclusions while upgrading.
=> [fix][sec] Upgrade Bouncycastle to 1.75 to address CVE-2023-33201

conf/broker.conf, conf/standalone.conf, deployment/terraform-ansible/templates/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/EmbeddedPulsarCluster.java
PIP: https://github.com/apache/pulsar/pull/20507
See https://github.com/apache/pulsar/pull/20507
Introduce `topicOrderedExecutorThreadNum ` to deprecate `numWorkerThreadsForNonPersistentTopic`
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/41
=> [improve][broker] PIP-275:Introduce topicOrderedExecutorThreadNum to deprecate numWorkerThreadsForNonPersistentTopic

pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchTestBase.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearch7SinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearch8SinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearchSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/OpenSearchSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java
Fixes #20661
master branch is blocked by PulsarSinksTest.testElasticSearch8Sink failing, see #20661
- disable downloading of geoip database when Elastic container starts
- enable logging of Elastic container output
- upgrade Elastic 8 container version from 8.5.1 to 8.5.3
- allow disk usage to go beyond 90% when running Elastic in integration tests
PR in forked repository: https://github.com/lhotari/pulsar/pull/151
=> [improve][test] Disable disk usage threshold & geoip download and enable logging for Elastic Testcontainers

pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchTestBase.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/ElasticSearchSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java
- backports #20671 to branch-2.10
=> [improve][test][branch-2.10] Backport disabling disk usage threshold for Elastic Testcontainers

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
Fix a deadlock of the consumer when the consumer tries to subscribe to partitioned topics and non-partitioned topics if the Pulsar Client uses multiple IO threads (default is 1 thread).
```
Found one Java-level deadlock:
=============================
"pulsar-client-io-1-2":
waiting to lock monitor 0x00007f716c00ae80 (object 0x00000004312d0940, a java.util.concurrent.ConcurrentHashMap$Node),
which is held by "pulsar-client-io-1-3"
"pulsar-client-io-1-3":
waiting to lock monitor 0x00007f6f8c009900 (object 0x000000042cf2ed28, a java.lang.Object),
which is held by "pulsar-client-io-1-4"
"pulsar-client-io-1-4":
waiting to lock monitor 0x00007f716c00ae80 (object 0x00000004312d0940, a java.util.concurrent.ConcurrentHashMap$Node),
which is held by "pulsar-client-io-1-3"
Java stack information for …
```
=> [fix][client]Fix deadlock issue of consumer while using multiple IO threads

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/MessageDuplicationTest.java
This issue has occurred with a topic that has many producers, where the P99 publish latency of the broker will increase to hundreds of milliseconds when many producers connect or disconnect from the topic. This level of latency is unacceptable for a messaging system.
In this case, each producer add or remove operation goes to MessageDeduplication to update a map for inactive producers, regardless of whether message deduplication is enabled or disabled. My initial impression is that if message deduplication is disabled, it should not go to MessageDeduplication. However, users can enable message deduplication for an active topic, which may be the reason why this is happening. @merlimat, do you have any additional context on this matter? We may also need to find a solution to avoid any …
=> [fix][broker] Fix the publish latency spike from the contention of MessageDeduplication

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/BrokerOperabilityMetrics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/DimensionStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
Fix [PIP-273](#20476)
`topic_load_times` was added by #507,  it's too earlier. And then we added the `pulsar` prefix for all the metrics, but leaves it. So in order to keep the same prefix, we'd better update it.
=> [improve][broker] Add metric prefix for `topic_load_times`

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationManager.java
Adding the missed bookie id in the registration manager.
- Adding the missed bookie id in the registration manager.
=> [fix][meta] Adding the missed bookie id in the registration manager.

pulsar-sql/presto-distribution/src/main/resources/conf/catalog/pulsar.properties, pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/TestPulsarConnectorConfig.java
In PR https://github.com/apache/pulsar/pull/14506, we remove the useless config `managedLedgerNumWorkerThreads` 
but we didn't remove the config from the config file, if users use this configuration, the Pulsar SQL can't startup due to `strictConfig` mode, remove this useless configuration for Pulsar SQL.
```
// at this point all config file properties should be used
// so we can calculate the unused properties
unusedProperties.keySet().removeAll(configurationFactory.getUsedProperties());
for (String key : unusedProperties.keySet()) {
Message message = new Message(format("Configuration property '%s' was not used", key));
(strictConfig ? errors : warnings).add(message);
}
// If there are configuration errors, fail-fast to keep output clean
if (!errors.isEmpty()) {
throw new …
```
=> [fix][sql] Remove useless configuration for Pulsar SQL

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdProduce.java, pulsar-client-tools/src/test/java/org/apache/pulsar/client/cli/TestCmdProduce.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoProduceBytesSchema.java
Currently you can produce AVRO messages only by passing a binary payload. This is pretty awkward.
It would be very nice to allow users to encode the AVRO message using JSON when passing the payload from the CLI.
- When you send a message using `bin/pulsar-client produce -m` decode the string using the AVRO JSONDecoder utility and set the result into the payload
- Fix a big in AutoProducesByteSchema#getNativeSchema
```
bin/pulsar-client produce  -vs 'avro:{"type":"record","namespace":"com.example","name": "FullName", "fields": [{"name":"a","type":"string"},{"name":"b","type":"int" }]}' -s NOSEPARATOR -m '{"a":"b","b":1}' test
```
```
bin/pulsar-client consume -st auto_consume -s sub -p Earliest test 
``` …
=> [improve][cli] pulsar-client produce: allow to produce AVRO message from strings

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
See: https://github.com/apache/pulsar/issues/14365, and fix when using `ExtensibleLoadManagerImpl` and `validateNamespaceBundleOwnershipAsync` methods. It should redirect to the owner broker.
Make `NonPersistentTopics#getListFromBundle` to pure async.
=> [improve][broker] Make get list from bundle Admin API async

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerStatTest.java
Fixes #20615
`SimpleProducerConsumerStatTest#testMsgRateExpired` seems flakey, so I'll try to improve it.
Before this fix, we checked if the messages expired by referring to the `msgRateExpired` value in the subscription stats. However, this value resets to 0 over time, so we instead refer to the `totalMsgExpired` value, which never resets.
Additionally, we get the stats directly from the instances in the broker server and not from the admin API.
=> [improve][test] Fix flaky test SimpleProducerConsumerStatTest#testMsgRateExpired

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
If listener.onUpdate has any exception, the future can not be complete.  We should catch the exception and make the method more safety, otherwise thread would be block.
=> [fix][broker] Topic policy can not be work well if replay policy message has any exception.

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateCompactionStrategy.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/TopicCompactionStrategyTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicCompactionStrategy.java
When topic lookups race(and the first lookup returns too fast before the second request gets deduped), the later lookup requests can timeout because the skipped messages are ignored at the table view and do not notify the service unit state channel.
ex:
m1: assign to b1 -> m2: owned by b1 -> m3: assign to b2 // m3 is skipped at the tableview
When m3 is skipped, we better get the channel notified to return the lookup request with the current owner(b1) instead of letting the request time out.
- Added the `handleSkippedMessage` and `setSkippedMsgHandler` in `TopicCompactionStrategy`. 
- `ServiceUnitStateChannel` registers `ServiceUnitStateChannel.handleSkippedEvent` to `ServiceUnitStateCompactionStrategy` by `setSkippedMsgHandler`.
- TableView calls …
=> [fix][broker] Added the skipped message handler for ServiceUnitStateChannel

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
When init in PersistentReplicator, the field of `PersistentSubscription` is null. 
see : https://github.com/apache/pulsar/blob/37ae858cbf8a0dfe32bad0cbdc3fdf99dad58bbb/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java#L119-L120
https://github.com/apache/pulsar/blob/37ae858cbf8a0dfe32bad0cbdc3fdf99dad58bbb/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java#L60-L62
so an NPE throws when executing `expireMessages(Position messagePosition)`:
https://github.com/apache/pulsar/blob/37ae858cbf8a0dfe32bad0cbdc3fdf99dad58bbb/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java#L99-L108
save PersistentTopic in `PersistentMessageExpiryMonitor` …
=> [fix][broker] Fix NPE when reset Replicator's cursor by position.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
When a retention policy exists, the command `pulsar-admin namespaces set-backlog-quota` does not take effect.
In the PR https://github.com/apache/pulsar/pull/17383: it only checked the compatibility of `retention` and `backlog quota`, and it was not set.
Fix the bug.
=> [fix] [admin] set ns level backlog quota does not take effect if retention exists

pulsar-broker/src/main/java/org/apache/pulsar/broker/BookKeeperClientFactoryImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/ManagedLedgerClientFactory.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadManager.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/RequestWrapper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/ResponseHandlerFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/RestException.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java
Remove warnings in IDEA
PR in forked repository: https://github.com/cbornet/pulsar/pull/14
=> [cleanup][broker] Various cleanups

pulsar-functions/runtime-all/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceMain.java
Fixes: https://github.com/apache/pulsar/issues/20688
When a function throws an exception that ends processing, we should exit the JVM.
* Update `JavaInstanceMain` so that an exception leads to exiting the JVM. Since the class does not use any dependencies (see the class's Javadoc), we use reflection to shutdown logging.
=> [fix][fn] Exit JVM when main thread throws exception

pulsar-io/kafka/pom.xml, pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java, pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java
https://github.com/apache/pulsar/discussions/19880#discussioncomment-6026807 When Kafka connector is closing, it waits for the `runnerThread` to stop, but the task-close is running at the same thread, so it will be stuck.
run `close` in another thread.
=> [fix][io] Close the kafka source connector got stuck

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/AntiAffinityGroupPolicyFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerIsolationPoliciesFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerLoadManagerClassFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerMaxTopicCountFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerVersionFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/policies/AntiAffinityGroupPolicyHelper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/policies/IsolationPoliciesHelper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleResourceAllocationPolicies.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/AntiAffinityNamespaceGroupExtensionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerIsolationPoliciesFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerLoadManagerClassFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerMaxTopicCountFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerVersionFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java
Currently, the filter has some block methods, e.g.,`getIsolationDataPolicies` method. When calling the block method in the metadata-store thread, it might cause a deadlock. For more detail, see: https://github.com/apache/pulsar/pull/20130
```
"configuration-metadata-store-186-1@14606" prio=5 tid=0x175 nid=NA runnable
at org.apache.pulsar.broker.resources.BaseResources.get(BaseResources.java:88)
at org.apache.pulsar.broker.resources.NamespaceResources$IsolationPolicyResources.getIsolationDataPolicies(NamespaceResources.java:177)
at org.apache.pulsar.broker.loadbalance.impl.SimpleResourceAllocationPolicies.getIsolationPolicies(SimpleResourceAllocationPolicies.java:49)
at org.apache.pulsar.broker.loadbalance.impl.SimpleResourceAllocationPolicies.areIsolationPo …
```
=> [improve][broker] Make ExtensibleLoadManagerImpl's broker filter pure async

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
Currently, some `synchronized` is used in CompactedTopicImpl to avoid data contention, but it does not completely avoid data contention due to asynchronous operations and may lead to cursor skipping some data.
The cursor may skip some data due to `compactionHorizon` be updated:
https://github.com/apache/pulsar/blob/e360379cae536924ad1aebeda17e335cb9d61d6b/pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java#L114
* Remove unnecessary `synchronized`.
* Make `compactionHorizon` unchanged when reading compacted data.
* Add `volatile` for  `compactedTopicContext`.
*(or)* …
=> [improve][broker] Improve CompactedTopicImpl lock

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Fixes error messages `CmdNameSpaces` and `CmdTopics` that describe opposite of what really happens.
Same as title.
=> [fix][cli] Fix error messages in `CmdNameSpaces` and `CmdTopics`

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
When `deleteNamespace`,  we will get all the topics, see:
https://github.com/apache/pulsar/blob/1211b14820467750af77a1b28cf0ba9c468d374c/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L216-L234
if the topic is partitioned-topic, eg :  "persistent://public/default/__change_events" with 3 partitions,
then the `topicsSum` will contain:
```
persistent://public/default/__change_events-partition-0
persistent://public/default/__change_events-partition-1
persistent://public/default/__change_events-partition-2
persistent://public/default/__change_events
```
So cause `topicPolicy` with :
```
persistent://public/default/__change_events-partition-0
persistent://public/default/__change_events-partition-1
persistent://public/default/__change_events-partition-2
``` …
=> [improve][admin] Remove duplicate topics name when `deleteNamespace`

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
When use pulsar-admin to get help of topic's operations, we can get the output:
It's a bit confusing.
It seems the description of '-s' is copied from reset-cursor
=> [fix][doc] Fix doc of admin cli create-subscription 

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PublishRateLimiterTest.java
The resources were not released after the test, resulting in "Refresh permit" keep printing on the console
release the resource after method
https://github.com/315157973/pulsar/pull/11
=> [fix][test]Fix resource not close after method

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/BrokerInterceptors.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/BrokerInterceptorTest.java
After merging #20422 , the 2.11 may encounter NPE when config :
```
brokerInterceptors = xxx-interceptor
disableBrokerInterceptors = true
```
```
2023-07-03T10:26:00,507+0000 [main] INFO  org.apache.pulsar.broker.intercept.BrokerInterceptors - Skip loading the broker interceptors when disableBrokerInterceptors is true
```
See code of branch-2.11
https://github.com/apache/pulsar/blob/dc258107d5019f513e2242eccb1551c956c72fed/pulsar-broker/src/main/java/org/apache/pulsar/broker/web/ProcessHandlerFilter.java#L38-L53
https://github.com/apache/pulsar/blob/dc258107d5019f513e2242eccb1551c956c72fed/pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/BrokerInterceptors.java#L60-L64
The master branch has fixed the NPE by #19376. it's hard to cherry-pick that to branch-2.11.
So in order to …
=> [fix][broker] Revert "Skip loading broker interceptor when disableBrokerInterceptors is true #20422"

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE, pulsar-sql/presto-distribution/pom.xml
The OWASP dependency check failed. Link: https://github.com/apache/pulsar/actions/runs/5424405010/jobs/9865506786?pr=20698
```
Error:  Failed to execute goal org.owasp:dependency-check-maven:8.2.1:aggregate (default) on project pulsar: 
Error:  
Error:  
Error:  canal.client-1.1.5.jar/META-INF/maven/com.google.guava/guava/pom.xml: CVE-2023-2976(7.1)
Error:  clickhouse-jdbc-0.4.6-all.jar/META-INF/maven/com.google.guava/guava/pom.xml: CVE-2023-2976(7.1)
Error:  
Error:  See the dependency-check report for more details.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X …
```
=> [fix][sec] Upgrade Guava to 32.1.1 to address CVE-2023-2976

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
Support delay messages in a random number of seconds by the range for our testing performance producer.
- Support delay messages in a random number of seconds by the range for our testing performance producer.
=> [feat][test] Support delay messages in a random number of seconds by the range

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java
---
Fixes #xyz
PIP: #xyz 
When seeing the warning log, there should have a reason why it shows. But the cause is empty, and the logic is running correctly. We should only print them when the exception is not null.
*(or)*
*(or)*
*(example:)*
=> [fix][schema] Only handle exception when there has

docker/pulsar/pom.xml
Fixes #20725
Fixes the docker image build which has been broken since the upgrade to Ubuntu 22.04
Updating the pom file arguments to the build_wheel script.
This change is already covered by existing tests, such as the docker build itself.
=> [fix][build] Update Python Wheel to 3.10

pulsar-broker-auth-oidc/pom.xml, pulsar-broker-auth-oidc/src/test/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenIDIntegrationTest.java, tests/certificate-authority/generate_keystore.sh, tests/certificate-authority/jks/broker.truststore.pem
While investigating https://stackoverflow.com/questions/76631732/apache-pulsar-unable-to-validate-issuer-certificate-when-attempting-to-load-open, I got the integration tests working using HTTPS.
* Update the tests for OIDC to use HTTPS
=> [improve] Use HTTPS in OIDC Identity Provider Integration Tests

docker/pulsar/pom.xml
Reverts apache/pulsar#20728
This setup is too intertwined with the `apachepulsar/pulsar-build` docker image
```
```
=> Revert "[fix][build] Update Python Wheel to 3.10"

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java, pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceProducerTest.java
Fix the RangeConvert parse issue in the PerformanceProducer
*(or)*
*(or)*
*(example:)*
=> [fix][test] Fix RangeConvert parse issue in the PerformanceProducer

build/docker/Dockerfile, docker/pulsar/Dockerfile, docker/pulsar/scripts/install-pulsar-client.sh, tests/docker-images/java-test-image/Dockerfile
Fixes #20725
Building the Docker image of Pulsar 2.11 was broken due to an incompatible wheel file. The wheel made on the manylinuz apachepulsar/pulsar-build image is compatible with Ubuntu 20.04, but is not compatible with Ubuntu 22.04.
Reverting the changes to use Ubuntu 22.04 in Dockerfiles back to Ubuntu 20.04.
Added some print.
=> [Revert][Build] Ubuntu 22.04 was not compatible with Python Client Wheel

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationProvider.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionBufferCloseTest.java, pulsar-websocket/src/main/resources/findbugsExclude.xml
This is a follow-up improvement for AuthorizationProvider.  As discussed in the [#20478-comment](https://github.com/apache/pulsar/pull/20478#issuecomment-1575333713), we need more methods to avoid admin handling permissions directly.
1. Add `removePermissionsAsync`: when deleting partitioned topics, we need to delete the authentication data.
2. Add `getPermissionsAsync`: we have topic level API to get all the permissions. so we need this.
3. Add `getSubscriptionPermissionsAsync`: we have topic level API to get all subscription permissions.
4. Add `getPermissionsAsync`: we have namespace level API to get all the permissions.
=> [improve][broker] Support get/remove permissions for AuthorizationProvider

build/docker/Dockerfile, docker/pulsar/Dockerfile, docker/pulsar/pom.xml, docker/pulsar/scripts/install-pulsar-client.sh, tests/docker-images/java-test-image/Dockerfile
We don't need python client building in pulsar Dockerfile anymore and we can use pulsar-client which was published in pypi.
=> [fix][build] Update base image to 22.04 and remove the python client building

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
The BrokerService should not throw RestException, as the method is not only called by the admin tool. When a topic is auto-created during the creation of a consumer/producer and exceeds the maximum number of topics allowed in the namespace, returning a RestException (UnknownError received by the client) would be considered a retryable error. 
To address this issue, the BrokerService will now return a NotAllowException instead of a RestException when the topic count exceeds the maximum limit allowed in the namespace.
*(or)*
*(or)* …
=>  [fix][broker] Avoid throwing RestException in BrokerService

tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java
```
2023-07-10T09:35:33,940 - INFO  - [main:ThreadLeakDetectorListener@40] - Capturing identifiers of running threads.
2023-07-10T09:35:33,957 - WARN  - [main:ThreadLeakDetectorListener@55] - Tests in class ExtensibleLoadManagerTest created thread id 406 with name 'Thread[jersey-client-async-executor-7,5,main]'
2023-07-10T09:35:33,957 - WARN  - [main:ThreadLeakDetectorListener@55] - Tests in class ExtensibleLoadManagerTest created thread id 407 with name 'Thread[jersey-client-async-executor-5,5,main]'
2023-07-10T09:35:33,957 - WARN  - [main:ThreadLeakDetectorListener@55] - Tests in class ExtensibleLoadManagerTest created thread id 408 with name 'Thread[jersey-client-async-executor-6,5,main]'
2023-07-10T09:35:33,957 - WARN  - [main:ThreadLeakDetectorListener@55] - Tests in class …
```
=> [fix][test] Close the resource after the test

pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPoliciesImpl.java, pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/OffloadPoliciesTest.java
Fixes #xyz
PIP: #xyz 
In pulsar offload, we will check if the specified offload driver is supported. But our offload can extend by implementing the offload interface. For easier to specify the other offload name, we should provide a way to configure the offload driver name. We are limiting the offload driver name by an immutable list. Making it can accept more offload driver names by properties.
*(or)*
*(or)*
*(example:)*
- *Extended …
=> [improve][offload] Support to configure more offload driver

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
Cherry-pick https://github.com/apache/pulsar/pull/20597 and guarantee compatibility.
*(or)*
*(or)*
*(example:)*
=> [fix][broker][branch-2.10] Fix NPE when reset Replicator's cursor by position. (#20597)

pip/pip-280.md
=> [pip][design] PIP-280: Refactor CLI for measurement units (time, byte)

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/RuntimeUtilsTest.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java
Fixes #20789
See #20789
Sanitize the original code filename and tranformer file name in Kubernetes Runtime.
=> [fix][fn] Pulsar Function Kubernetes Runtime fails to start function that contains parenthesis in original jar filename

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsController.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java
If there are two clusters and enabled replication, and we can not consume all messages in this flow:
- create consumer and producer on the active cluster
- send 100 messages
- consume 10 messages
- switch the consumer to the standby cluster
- **(Highlight)** there are no messages on the standby cluster because the `mark deleted position` has been set to `Lastest`.
set `mark deleted position` to `Earliest` when auto creates subscription on the standby cluster.
=> [fix] [broker] Can not receive any messages after switch to standby cluster

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
log should tell us which topic and subscription is enabled rate limit.
add topic field.
=> [improve][broker] Add log on topic or subscription when enable rate limit.

pulsar-io/core/src/main/java/org/apache/pulsar/io/core/AbstractPushSource.java, pulsar-io/core/src/main/java/org/apache/pulsar/io/core/PushSource.java, pulsar-io/core/src/test/java/org/apache/pulsar/io/core/PushSourceTest.java
If one source connector extends `PushSource`. An exception was encountered when this source connector consumed the source system data, it had no way to notify the function framework to restart this connector.
- Abstract `BatchPushSource` logic to `AbstractPushSource`.
- Let `PushSource` to extends `AbstractPushSource` to extend a new method(**notifyError**).
- Add `PushSourceTest` to cover it.
=> [improve][io] Add notifyError method on PushSource.

tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloader.java
Fixes #xyz
PIP: #xyz 
When creating a topic, it will create the offload resources. The offload resources are only used when the offload is triggered. When the broker restarts, there have a lot of topics loading.
Create offload blobstore lazily to avoid creating too many resources when the broker restarts.
*(or)*
*(or)*
*(example:)* …
=> [improve][offload] Create offload resources lazily

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java, pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java
When Kafka source poll message exception, it will throw it to the function framework, and not trigger the restart function instance.
After #20424, it just closes the Kafka source connector poll thread, and not will trigger restart instance.
- When Kafka consumer gets an exception, call `notifyError` to notify this exception, and when the function framework next calls `consumer.read` method, it will trigger instance restart.
- Change `closeConnectorWhenUnexpectedExceptionThrownTest` to cover it.
=> [fix][io] Not restart instance when kafka source poll exception.

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java, pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkTests.java
If a producer use `Schema.JSON(String.class)` schema, es sink connector will throw `ClassCastException`.
1. Create a producer.
```java
Producer<String> producer = client.newProducer(Schema.JSON(String.class))
.topic("test-es")
.create();
MessageId msgID = producer.send({\"a\":1});
```
2. When es sink connector handle this message, it will throw `ClassCastException`.
```
java.lang.ClassCastException: class java.lang.String cannot be cast to class com.fasterxml.jackson.databind.JsonNode (java.lang.String is in module java.base of loader 'bootstrap'; com.fasterxml.jackson.databind.JsonNode is in unnamed module of loader 'app')
```
Exception throws on here:
https://github.com/apache/pulsar/blob/593fcb87b6d3bd6401eb4ffa4c25d8b3f724e49d/pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io …
=> [fix] [io] elastic-search sink connector not support JSON.String schema.

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/AbstractTestPulsarService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/NonStartableTestPulsarService.java
Fixes #20797
See #20797. There's a resource leak in PulsarTestContext which was introduced in #19337 and #19376.
PulsarTestContext was a solution that was made to reduce the usage of Mockito so that issues like #13620 could be fixed. Mockito is not thread safe and that is the reason why PulsarTestContext was needed.
- use fields in super class to hold resources instead of having duplicates
- all fields in PulsarService have protected setters due to `@Setter(AccessLevel.PROTECTED)`
- this fact was missed in the original implementation of PulsarTestContext
PR in forked repository: https://github.com/lhotari/pulsar/pull/152
=> [fix][test] Fix resource leak in PulsarTestContext

pulsar-io/mongo/pom.xml
After updating the branch to 2.10.5 to prepare for release cycle the build fails.
Update the missed change to `pulsar-io/mongo/pom.xml`
=> [fix][build] Mongo is fixed for 2.10.5

pulsar-functions/instance/src/main/python/python_instance.py, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/python/PulsarFunctionsPythonTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/utils/CommandGenerator.java
Currently in the Pulsar Python Function runtime the flag `--retain-key-ordering` can't be enabled since the logic for the subscription type is not implemented with that flag. 
* Apply the same logic from the java runtime and, in case of `retainKeyOrdering: true`, use a KEY_SHARED subscription for the source
* Added integration tests both for --retain-ordering and --retain-key-ordering 
*
=> [improve][fn] Support --retain-key-ordering (KEY_SHARED sub) in Python functions

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/NegativeAcksTracker.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/UnAckedMessageTracker.java
When calling the `negativeAcknowledge` method, the message is supposed to be re-delivered only one time.
But, actually,  it may be re-delivered twice.
There are two problems:
1. For `MultiTopicsConsumerImpl`, when calling `negativeAcknowledge`, we didn't remove the message from `UnAckedMessageTracker`, so this message will be re-delivery by both `UnAckedMessageTracker` and `NegativeAcksTracker`
2. For `ConsumerImpl`, when calling `negativeAcknowledge`, if the message id is a BatchMessageIdImpl, the messageId will be not removed from the `UnAckedMessageTracker`, there is because the removing MessageId type(BatchMessageIdImpl) is not the MessageId type of add(MessageIdImpl).
See:
- add to `UnAckedMessageTracker`
```java
protected void trackMessage(MessageId messageId, int redeliveryCount) { …
```
=> [fix][client] fix negative message re-delivery twice issue

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicsConsumerImplTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImpl.java
Disable polling pattern topics task when TopicListWatcher is enabled.
The current tests have covered the cases.
=> [improve][client] Disable polling pattern topics when TopicListWatcher is enabled.

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java, pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaPushSource.java, pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java
When Kafka source poll message exception, it will throw it to the function framework, and not trigger the restart function instance.
#20795 uses a new method on PulsarSource #20791 to fix it on master branch.  To maintain compatibility, we can't cherry-pick it to the historical version, so the class is implemented in the Kafka source connector.
- Let consumer.subscribe run on the start thread, which can quickly fail when subscribe exception.
- Add new class `KafkaPushSource` on Kafka source connector.
- When Kafka consumer exception, it will call `notifyError` to report the exception to the io connector framework.
=> [fix][io][branch-3.0] Not restart instance when kafka source poll exception.

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerConsumerInternalTest.java
**Background**
- When the customer disconnects, the consumer automatically tries to reconnect.
- When a connection is disconnected, the broker will remove the consumer related to this connection.
- The client does not reconnect when it receives a `ConsumerBusyException`.
---
**Issue**
| time | `client disconnect` | `broker disconnect` |
| 1 | disconnect | 
| 2 | reconnect |
| 3 | Send `cmd-sub` to the broker | disconnect |
| 4 | Since the old consumer has not been removed in the broker memory, get a consumer busy error |
| 5 | | Remove the old consumer in memory |
| 6 | Stop reconnect |
At this time, there is no consumer under this subscription.
---
**A mechanism to fix the issue above**
Once a consumer has subscribed successfully, the consumer will try to retry …
=> [improve][test] add a test to ensure the exclusive consumer will reconnect even if received ConsumerBusy error

pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPoliciesImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/FieldParser.java, pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/OffloadPoliciesTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/FieldParserTest.java
Fixes #xyz
PIP: #xyz 
The offload policies have limited the configurations for the offloaders.  That means if the offloader needs more configurations, we need to extend more fields in the OffloadPoliciesImpl. That doesn't make sense. We should make it extendable easily. Add a configuration map support to allow it to set more configurations.
*(or)*
*(or)*
*(example:)*
*If …
=> [improve][offload] Extend the offload policies to allow specifying more conf

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java, pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaPushSource.java, pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java
When Kafka source poll message exception, it will throw it to the function framework, and not trigger the restart function instance.
#20795 uses a new method on PulsarSource #20791 to fix it on master branch.  To maintain compatibility, we can't cherry-pick it to the historical version, so the class is implemented in the Kafka source connector.
- Let consumer.subscribe run on the start thread, which can quickly fail when subscribe exception.
- Add new class `KafkaPushSource` on Kafka source connector.
- When Kafka consumer exception, it will call `notifyError` to report the exception to the io connector framework.
=> [fix][io][branch-2.10] Not restart instance when kafka source poll exception.

docker/pulsar/Dockerfile, docker/pulsar/scripts/gen-yml-from-env.py
See https://github.com/yaml/pyyaml/issues/724 .
We need to upgrade pyyaml to 6.0.1 to resolve this issue .
```
[INFO] DOCKER> Step 21/30 : RUN pip3 install pyyaml==5.4.1
[INFO] DOCKER> 
[INFO] DOCKER> ---> Running in ef1c59ec2468
[INFO] DOCKER> Collecting pyyaml==5.4.1
[INFO] DOCKER> Downloading PyYAML-5.4.1.tar.gz (175 kB)
[INFO] DOCKER> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 KB 4.4 MB/s eta 0:00:00
[INFO] DOCKER> 
[INFO] DOCKER> Installing build dependencies: started
[INFO] DOCKER> Installing build dependencies: finished with status 'done'
[INFO] DOCKER> Getting requirements to build wheel: started
[INFO] DOCKER> Getting requirements to build wheel: finished with status 'error'
[INFO] DOCKER> [91m  error: subprocess-exited-with-error
× Getting requirements to build wheel …
```
=> [fix][build] Upgrade PyYaml version to 6.0.1

conf/websocket.conf, pulsar-websocket/src/test/java/org/apache/pulsar/websocket/WebSocketProxyConfigurationTest.java
Since the PR https://github.com/apache/pulsar/pull/16234 add the prop `cryptoKeyReaderFactoryClassName` for the WebSocket Proxy, but did not add this prop to `websocket.conf`.  This can make the script which try to replacement attribute a bit difficult to write
add the conf `cryptoKeyReaderFactoryClassName` into the file `websocket.conf`
=> [improve] [ws] add cryptoKeyReaderFactoryClassName into the file websocket.conf

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/SegmentedLongArray.java
[There](https://github.com/apache/pulsar/blob/57fbee446aebb5c9f4db3bed559cb7bef3749731/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java#L205C16-L205C16) is a memory leak if the delayed tracker throws an `OutOfDirectMemory` exception. The entries will never release. 
Plus, with the OOM exception thrown in the thread, the broker will not shut down.
```
Jul 16, 2023 @ 18:35:58.575 | 2023-07-16T10:35:58,574+0000 [broker-topic-workers-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.common.util.SingleThreadExecutor - Error while running task: failed to allocate 16777216 byte(s) of direct memory (used: 847249415, max: 858993459)
  | Jul 16, 2023 @ 18:35:58.575 | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) …
```
=> [fix][broker] Fix direct memory leak by delayed index OutOfDirectMemory

pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Markers.java, tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileStoreBackedReadHandleImpl.java
Follow up PR #4196 to use `PulsarByteBufAllocator` handle OOM
- Use `PulsarByteBufAllocator` to instead `PooledBytebufAllocator`
=> [improve][broker] Follow up #4196 use `PulsarByteBufAllocator` handle OOM

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/HierarchyTopicAutoCreationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/HierarchyTopicAutoCreationTest.java
`Auto-creation topics` mechanism relies on namespace policies which are very important for the broker to determine if we should auto create `partitioned` topic or `non-partitioend` topic.
We can't rely on the cache to get the random result. We should always load data from zk if the cache is missed to avoid fallback to broker default configuration.
e.g.  If the metadata cache is missed, the logic will fallback to use broker configuration.
Broker configuration:
```
allowAutoTopicCreation=true
allowAutoTopicCreationType=non-partitioned
```
Namespace policies:
```
allowAutoTopicCreation=true
allowAutoTopicCreationType=partitioned
```
- Load cache if the policy does not exist in the metadata cache.
- Change some code style to pass checkstyle.
=> [fix][broker] Inconsistent behaviour for topic auto_creation

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/BaseResources.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Right now, Pulsar service loads namespace policies cache on startup or namespace policy update. However, it doesn't consider v1 namespaces, don't load v1 namespace policy cache and also try to deserialize incorrect znode of v1 namespace policy path which causes below exception during server startup if you have v1 namespace: `/admin/policies/prop/us-east1/nsv1`
```
00:57:11.633 [ForkJoinPool.commonPool-worker-23] ERROR org.apache.pulsar.broker.resourcegroup.ResourceGroupNamespaceConfigListener - Exception when getting namespace weather/global
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/admin/policies/prop/us-east1'
at …
```
=> [fix][broker] Broker failed to load v1 namespace resources cache

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicUtils.java
When we read compacted entries, we miss `bytesToRead`, we should pass it.
Pass `bytesToRead` when reading compacted entries.
Add wait parameter to make the method support non-wait mode.
=> [fix][broker] Pass `bytesToRead` when reading compacted entries

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationProvider.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationWithAuthDataTest.java
https://github.com/apache/pulsar/pull/20496 introduced a breaking change that if the custom authz provider does not implement the `removePermissionsAsync` method, the built-in admin will fail to delete a topic. It's because `BrokerService#deleteTopicAuthenticationWithRetry` calls `authorizationService.removePermissionsAsync`.
To make it backward compatible, return a normal completed future in `removePermissionsAsync`. Verify the change by deleting a topic in `AuthorizationWithAuthDataTest#testAdmin`.
=> [fix][broker] Fix the built-in admin failed to delete a topic with a custom authz provider

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
Avoid printing redirect exception log when get list from bundle.
=> [improve][broker] Avoid print redirect exception log when get list from bundle

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/AntiAffinityGroupPolicyFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerIsolationPoliciesFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerLoadManagerClassFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerMaxTopicCountFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerVersionFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/AntiAffinityNamespaceGroupExtensionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerIsolationPoliciesFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerLoadManagerClassFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerMaxTopicCountFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerVersionFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java
In https://github.com/apache/pulsar/pull/20666, we changed the broker filter API to async. Although, the broker filter can't implement by users is self. But to guarantee API compatibility, we should keep the old API, mark it as deprecated, and add a new API instead.
Add the broker filter sync API back.
=> [improve][broker] Add broker filter sync method back to guarantee the API compatibility

pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicCompactionStrategy.java
Add `Audience.Private` annotation for topic compaction strategy. Since this interface only uses for load manager, other users should not use this interface.
=> [improve][broker] Add annotation for topic compaction strategy

.github/workflows/ci-semantic-pull-request.yml
Per the PIP process (new) as you see [here](https://github.com/apache/pulsar/blob/master/pip/README.md) title should start with "|[pip][design] PIP- -"  But the check rule of PR title is not supported
Add new a scope `pip` for the check pull request title
=> [improve][ci]Add "pip" into the scope of the pull request title check rule

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicUtils.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicUtilsTest.java
Fix IndexOutOfBoundsException in the CompactedTopicUtils
if entries are empty, then early return
=> [fix][broker] Fix IndexOutOfBoundsException in the CompactedTopicUtils

pip/pip-279.md
This is a PIP to reformat property in generateResponseWithEntry. The PR contents have the motivation.
PR in forked repository: #20481
=> [pip][design] PIP-279: Reformat property in generateResponseWithEntry

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java
In the replication scenario, we want to produce messages on the native cluster and consume messages on the remote cluster, the producer and consumer both use a same schema, but the consumer cannot be registered if there has no messages in the topic yet.
The root cause is that for the remote cluster, there is a producer who has been registered with `AUTO_PRODUCE_BYTES` schema, so there is no schema to check the compatibility.
If there is no schema and only the replicator producer was registered, skip the compatibility check.
=> [fix][broker] In replication scenario, remote consumer could not be registered if there has no message was sent

pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java
Main Issue: https://github.com/apache/pulsar/issues/20851
When the Proto version does not allow us to send TcClientConnectRequest to the broker, we should add a log to debug it.
Add a waining log.
*(or)*
*(or)*
*(example:)*
=> [improve][txn]Add log when can't send TcClientConnectRequest to broker.

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImplTest.java
(cherry picked from commit 3f637680bbbc268d4801172d3212279ace38c4d4)
The bundle ownership assignment logic doesn't know the previous unloaded broker when unloading happens. It might assign the bundle to the same broker. In this case, it might cause an infinite bundle unloading loop.
To resolve this issue, we can check the destination broker when doing the `doLoadShedding` stage. When the destination broker is the same as the current owner broker, we can skip this unload, and if it is different, we set the new owner in this stage.
* Transfer the bundle to the new owner when needed to unload.
See the `ModularLoadManagerImplTest#testLoadShedding` unit test.
=> [branch-2.11][fix][broker] Avoid infinite bundle unloading (#20822)

pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordCursor.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarSqlSchemaInfoProvider.java
fix the wrong format of the logs.
`{}` -> `%s`
=> [improve][sql] Fix the wrong format of the logs

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SubscribeRateLimiter.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/lookup/http/HttpTopicLookupv2Test.java
=> [branch-2.11][fix][broker] Fix inconsensus namespace policies by getPoliciesIfCached 

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/TopicDuplicationTest.java
Fixes #20904
when enable broker level deduplication and disable namespace level deduplication.
the brokerService checkSnapshotTask will throw npe.
if the topic disable deduplication. skip take snapshot of deduplication.
add unit test in this patch.
=> [fix][broker] fix MessageDeduplication throw NPE when enable broker dedup and set namespace disable deduplication.

pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ReaderConfigurationData.java
When releasing 3.1.0, it occurs below error:
=> [fix][build] Fix generating javadoc issue

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerfClientUtils.java
Fix the perf-producer to get direct memory OOM with high publish latency.
The root cause is the perf-producer without any memory limitation and pending
queue size limitation by default.
You can try to set the max pending queue size for a workaround. 
Use the default configuration of the PulsarClient instead of removing the memory
limitation in pulsar-perf.
We should also provide an option to specify the max memory for the perf tool.
But it will introduce new public API changes to the perf tool, so it should only be available
in the feature release. This PR is focused on the BUG fix to avoid confusing users
with OOM.
=> [fix][client] Fix perf-producer get OOM with high publish latency

pip/README.md
After [discussed with the keyword of PIP's title](https://github.com/apache/pulsar/pull/20560#issuecomment-1619746257), we came to a consensus: use `[improve] [pip]` instead of `[pip] [design]`
Change the wiki [Pulsar Improvement Proposal (PIP)](https://github.com/apache/pulsar/blob/master/pip/README.md)
=> [improve] [doc] improve the wiki Pulsar Improvement Proposal (PIP)

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImplTest.java
(cherry picked from commit 3f637680bbbc268d4801172d3212279ace38c4d4)
The bundle ownership assignment logic doesn't know the previous unloaded broker when unloading happens. It might assign the bundle to the same broker. In this case, it might cause an infinite bundle unloading loop.
To resolve this issue, we can check the destination broker when doing the `doLoadShedding` stage. When the destination broker is the same as the current owner broker, we can skip this unload, and if it is different, we set the new owner in this stage.
* Transfer the bundle to the new owner when needed to unload.
See the `ModularLoadManagerImplTest#testLoadShedding` unit test.
=> [branch-2.10][fix][broker] Avoid infinite bundle unloading (#20822)

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/SegmentAbortedTxnProcessorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionProduceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionBufferClientTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionLowWaterMarkTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionStablePositionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/KeySharedSubscriptionTest.java
When fixing the flaky test `testCloseTransactionBufferWhenTimeout`, I see many producers/consumers not closed after the test.  Some related fixing #20799, #20778
Fix `KeySharedSubscriptionTest`
https://github.com/apache/pulsar/actions/runs/5804173763/job/15735680439?pr=20952
https://github.com/apache/pulsar/actions/runs/5804311503/job/15733845297?pr=20963
https://github.com/apache/pulsar/actions/runs/5796922794/job/15735725061?pr=20943
=> [fix][test] Fix flaky test `testCloseTransactionBufferWhenTimeout` and close producer/consumer

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/MultiRolesTokenAuthorizationProvider.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authorization/MultiRolesTokenAuthorizationProviderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/KeySharedSubscriptionTest.java
My repo pr https://github.com/AmateurEvents/pulsar/pull/35
Fixes https://github.com/apache/pulsar/issues/20938
Main Issue: https://github.com/apache/pulsar/issues/20938
PIP: #xyz 
Support super user role check
*(or)*
*(or)*
*(example:)*
=> [fix][broker]Check that the super user role is in the MultiRolesTokenAuthorizationProvider plugin

pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java
Minor improve `getIsolationGroup` by avoid creating arrayList. And it'  beneficial to GC
`new HashSet<>(Arrays.asList(...))` -> `Sets.newHashSet(...)`
PR in forked repository: https://github.com/AnonHxy/pulsar/pull/43
=> [improve][bk] Improve getIsolationGroup by avoid creating arrayList

bouncy-castle/bc/LICENSE, pom.xml, pulsar-functions/secrets/pom.xml, pulsar-io/aerospike/pom.xml, tiered-storage/file-system/pom.xml
There are multiple versions of bouncy-castle libraries.
```
[INFO] |  +- io.grpc:grpc-all:jar:1.45.1:compile
[INFO] |  |  +- io.grpc:grpc-api:jar:1.45.1:compile
[INFO] |  |  +- io.grpc:grpc-auth:jar:1.45.1:compile
[INFO] |  |  |  \- com.google.auth:google-auth-library-credentials:jar:1.4.0:compile
[INFO] |  |  +- io.grpc:grpc-context:jar:1.45.1:compile
[INFO] |  |  +- io.grpc:grpc-core:jar:1.45.1:compile
[INFO] |  |  |  +- com.google.code.gson:gson:jar:2.8.9:compile
[INFO] |  |  |  +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime
[INFO] |  |  +- io.grpc:grpc-grpclb:jar:1.45.1:compile
[INFO] |  |  |  \- com.google.protobuf:protobuf-java-util:jar:3.19.6:compile
[INFO] |  |  +- …
```
=> [branch-2.11] [fix] [broker] fix multiple versions of bouncy-castle

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
When get partitioned metadata not found, it will print the full stacktrace. 
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
2023-08-11T11:29:57,255+0000 [pulsar-web-38-8] ERROR org.apache.pulsar.broker.admin.v2.PersistentTopics - [null] Failed to get partitioned metadata topic persistent://public/default/test-topic
java.util.concurrent.CompletionException: org.apache.pulsar.broker.web.RestException: Topic persistent://public/default/test-topic not found
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:761) ~[?:?]
at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
at …
=> [cleanup][admin] Do not print full stacktrace when get partitioned metadata not found

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/PulsarTopicCompactionService.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/TopicCompactionServiceTest.java
Currently, the number of read compacted entries is wrong, which is one more than the specified number.
Fix incorrect number of read compacted entries.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Fix incorrect number of read compacted entries

pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
If a batch contains a message with a null value (i.e. payloadSize == 0) and `PhaseOneResult.from` haven't been set, then the compactor may skip the whole batch message according to `PhaseOneResult.from` in phase two, which will lead to message loss during the topic compact. The root cause is `deletedMessage` of whole batch be marked `true` when the batch contains one message with a null value.
Also, `PhaseOneResult.to` has the same problem, when finding the value of the message is null, `PhaseOneResult.to` will not be updated.
https://github.com/apache/pulsar/blob/98628845aa94b416b0c3711b5a15819ade549c57/pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java#L126-L166
* Fix `deletedMessage` calculate in the batch message,  just when delete times are equal to the …
=> [fix][broker] Fix message loss during topic compaction

pip/pip-281.md
Refer to `pip-281.md`
BTW: This is a very simple change and is forward compatible. Sorry, I didn't notice that this change requires PIP before, so the related PRs have been merged.
- https://github.com/apache/pulsar/pull/20791
If this PIP vote does not pass, I revert this PR after that.
=> [pip][design] PIP-281: Add notifyError method on PushSource

pip/pip-289.md
Fixes: https://github.com/apache/pulsar/issues/20862
PIP for improving connector configuration security. See content for details.
Add the design doc for PIP 289.
Current implementation PRs:
* https://github.com/apache/pulsar/pull/20901
* https://github.com/apache/pulsar/pull/20902
=> [pip][design] PIP 289: Secure Pulsar Connector Configuration

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java
In #20697, we remove the lock of get compactedTopicContext and asyncReadEntries, but `compactionHorizon` has been updated before  `compactedTopicContext` is updated. In concurrent cases, this may lead to cursor skip messages of newly compacted or getting an NPE when reading compacted entries.
Ensure `compactionHorizon` is updated after `compactedTopicContext`.
*(or)*
*(or)*
*(example:)* …
=> [fix][broker] Fix get outdated compactedTopicContext after compactionHorizon has been updated

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Subscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java
Right now, when we mark topic migrated during blue-green cluster migration then broker disconnects consumers of the subscriptions once it reaches end of managed-leger data and consumer will be redirected to green cluster. However, if consumer is connected to topic without any backlog then consumer stays connected and broker didn't trigger consumer migration. Therefore, this PR makes sure that all the consumers of subscriptions which are not having backlog will be migrated and broker also checks topic migration when new consumer connects and notifies those consumers immediately if there is no backlog on that subscription.
1. Add a function "checkAndApplyTopicMigration" to check and disconnect consumers if subscription is already migrated under Consumer.java. 
2. Call the function in …
=> [fix][broker] Fix consumers are not redirected to migrated cluster

tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java
Fixes [#19908](https://github.com/apache/pulsar/issues/19908)
Fixes the flaky test.
Wrap the assertion statement in the Awaitility loop in case `admin.namespaces().getBundles(DEFAULT_NAMESPACE);` returns old bundle split state.
I tried to run this test in my local fork, https://github.com/heesung-sn/pulsar/pull/51, with invocation=30.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/51
=> [fix][test] fix flaky testSplitBundleAdminApi

conf/proxy.conf, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/WebServer.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/stats/ProxyStats.java
In certain deployments, it is preferable to be able to disable the `/proxy-stats`, `/metrics`, and `/status.html` endpoints.
* Add configuration named `enableProxyStatsEndpoints` to the proxy configuration. When true (default), the endpoints are all exposed. When false, they are not served.
* Fix some implementation details for the proxy stats servlet configuration and the endpoints themselves
This is a minor change.
=> [improve][proxy] Support disabling metrics endpoint

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
**Background**: when calling `pulsar-admin topics stats --get-earliest-time-in-backlog <topic name>`, Pulsar will read the first entry which is not acknowledged, and respond with the entry write time. The flow is like this:
- get the mark deleted position of the subscription
- if no backlog, response `-1`
- else read the next position of the mark deleted position, and respond with the entry write time.
**Error logs**
```
org.apache.bookkeeper.mledger.ManagedLedgerException: Error while reading ledger
2023-08-03T13:44:25,120+0000 [pulsar-web-36-13] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Error read entry for position 1739429:37881	
2023-08-03T13:44:25,120+0000 [pulsar-web-36-13] ERROR org.apache.pulsar.broker.service.persistent.PersistentTopic - …
```
=> [fix] [admin] Fix get topic stats fail if a subscription catch up concurrently

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerUnderreplicationManager.java
When the user config `-Dbookkeeper.metadata.client.drivers=org.apache.pulsar.metadata.bookkeeper.PulsarMetadataClientDriver`, the AutoRecovery will use PulsarLedgerUnderreplicationManager.
https://github.com/apache/bookkeeper/blob/f30ff4f2ad4778f1f73b29872e2a95adb22ca116/bookkeeper-server/src/main/java/org/apache/bookkeeper/replication/Auditor.java#L396-L397.
In Auditor start, it will register a UnderReplicatedLedgersChangedCb to PulsarLedgerUnderreplicationManager,
PulsarLedgerUnderreplicationManager will register a watcher to watch the zk event. 
When the event path matches `underreplication`, callback UnderReplicatedLedgersChangedCb, the callback executor is metadata-store executor.
https://github.com/apache/pulsar/blob/0cb1c780412ca3cc1d421fe6ebb5de95cf7392fa/pulsar-metadata/src/main/j …
=> [fix][meta] Fix deadlock in AutoRecovery.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
Fixes #20982
do not delete compaction cursor when enable subscription inactive check.
if subscription is compaction subscription skip check inactive check.
add unit test to check this. see `testCheckInactiveSubscriptionsShouldNotDeleteCompactionCursor`
=> [fix][broker] Fix compaction subscription delete by inactive subscription check.

conf/bookkeeper.conf
Fixes #xyz
PIP: #xyz 
If we want to use `PulsarMetadataClientDriver` in BookKeeper server, the document in conf/bookkeeper.conf is confused and it's hard for users to configure the right `metadataServiceUri` format.
Add a document in `conf/bookkeeper.conf` to guide users to configure the right `metadataServiceUri` format.
*(or)*
*(or)*
*(example:)* …
=> [fix] [doc] Update BookKeeper metadataServiceUri doc

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/BrokerInterceptorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/ExceptionsBrokerInterceptorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/web/ProcessHandlerFilterTest.java
PIP: [#293](https://github.com/apache/pulsar/pull/20993)
=> [improve][broker] PIP-293: Delete config disableBrokerInterceptors 

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerImplTest.java
Currently, only `seek` doesn't support backoff in consumer side, see :
https://github.com/apache/pulsar/blob/2ab184e49a036a1dd10dc537bef4ab034a5ad5e0/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L2151-L2166
=> [improve][client] Add backoff for `seek`

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java
Fixes #20968 
As described in 20968, even if the retention policy is set at the topic level, the ledger is still deleted. See the above log.
For `onUpdate` , there are two issues: 
https://github.com/apache/pulsar/blob/ee91edc3e08c87db1e5662a553ff62af0c1886e5/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L3493-L3522
1.  We print `Policies updated successfully` in method `checkReplicationAndRetryOnFailure`. it confuses users.
2.  If the topic is loaded before `reader` read the policies and `checkPersistencePolicies` throw exception, then the retention policy will not apply to ManagedLedger config. So trim ledger will still use previous polices.  And here will cause the above issue.
1. print `Policies updated successfully` in the end.
2. Use …
=> [fix][broker] Fix potential case cause retention policy not working on topic level

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java
Right now after we mark the topic migrated, replicators do not get disconnected from blue cluster and subscriptions are not deleted even after the backlog is drained and all consumers are disconnected. This pr takes care of this by asynchronously disconnecting replicators and deleting subscriptions once the backlog is drained and all consumers are disconnected when checkClusterMigration API is called.
Replicators without backlog are disconnected and subscriptions without consumers are deleted and eventually topic is garbage collected in the blue cluster.
Call checkAndDisconnectReplicators() and checkAndUnsubscribeSubscriptions() in checkClusterMigration() periodic job.
Added unit tests to verify the change
*If the box was checked, …
=> [fix][broker]Delete subscription and disconnect replicators after topic migration

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
Removing `webUrl` null-check, because it couldn't be null.
Removing `webUrl` null-check
PR in forked repository:  https://github.com/AnonHxy/pulsar/pull/44
=> [improve][broker] Removing webURL check null

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
As per backlog quota logic, Producer is blocked on creation  when 
1. backlog exceeded on topic
2. dedup is enabled 
3. no producer is there.
Especially, producer creation is indefinitely blocked when there brokerDeduplicationEnabled=false(default=false), which disables periodic dedup map snapshots every 2mins.
When checking backlog size, the logic computes the backlog size against the slowest consumer on the topic. Unfortunately, the dedup system consumer(for the dedup map recovery) is usually behind the latest position -- the broker takes deup recovery map snapshot every 1000 entry(by default, `brokerDeduplicationEntriesInterval`) or every 2 mins(by default) when `brokerDeduplicationEnabled` is enabled(default is false), so before the next snapshot cycle, the dedup system consumer's …
=> [fix] [broker] Producer is blocked on creation because backlog exceeded on topic, when dedup is enabled and no producer is there

pulsar-broker-auth-sasl/src/main/java/org/apache/pulsar/broker/authentication/SaslRoleTokenSigner.java
Fixes #21053
Main issue #21053 
I may have discovered a method in the newest version of [pulsar](https://github.com/apache/pulsar), which has "Observable Timing Discrepancy" vulnerability. The vulnerability is located in the method org.apache.pulsar.broker.authentication.SaslRoleTokenSigner.verifyAndExtract(String signedStr) . The vulnerability bears similarities to a recent CVE disclosure https://github.com/advisories/GHSA-54g4-5cf6-hjp3 in the "apache/hive" project.
The source vulnerability information is as follows:
> ​	**Vulnerability Detail:**
>
> ​	**CVE Identifier:** CVE-2020-1926
>
>  	**Description**:Apache Hive cookie signature verification used a non constant time comparison which is known to be vulnerable to timing attacks. This could allow recovery of another users cookie …
=> [fix][broker] Use MessageDigest.isEqual when comparing digests

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BkEnsemblesChaosTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataCache.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClient.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java
After [PIP-118: reconnect broker when ZooKeeper session expires](https://github.com/apache/pulsar/pull/13341), the Broker will not shut down after losing the connection of the local metadata store in the default configuration.
However, before the ZK client is reconnected, the events of BK online and offline are lost, resulting in incorrect BK info in the memory. You can reproduce the issue by the test `BkEnsemblesChaosTest. testBookieInfoIsCorrectEvenIfLostNotificationDueToZKClientReconnect`(90% probability of reproduce of the issue, run it again if the issue does not occur)
Refresh BK info in memory after the ZK client is reconnected.
=> [fix] [bk] Correctct the bookie info after ZK client is reconnected

pulsar-broker-common/src/test/java/org/apache/pulsar/broker/web/plugin/servlet/AdditionalServletUtilsTest.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/BrokerInterceptorUtilsTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/LocalMemoryMetadataStore.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/RocksdbMetadataStore.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/batching/AbstractBatchedMetadataStore.java
Fixed some files where "listener" was mistyped as "lister".
=> [fix][broker] Fix typos: lister -> listener

pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java
The previous write may not be complete by the time compaction is completed, we should wait for all inflight writes to have finished.
https://github.com/apache/pulsar/pull/20988#discussion_r1293844204
Make sure all inflight writes have finished before going to before completion of compaction.
*(or)*
*(or)*
*(example:)*
PR in forked …
=> [fix][broker] Make sure all inflight writes have finished  before completion of compaction

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
- [CVE-2023-3635](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2023-3635)
- Updated okio version to 3.4.0
=> [fix][misc] Bump broker okio version to 3.4.0

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceChaosTest.java
If we set `allowAutoTopicCreationType` to `PARTITIONED`, the flow of the create topic progress is like the below:
1. `Client-side`: Lookup topic to get partitioned topic metadata to create a producer.
1. `Broker-side`: Create partitioned topic metadata.
1. `Broker-side`: response `{"partitions":3}`.
1. `Client-side`: Create separate connections for each partition of the topic.
1. `Broker-side`: Receive 3 connect requests and create 3 partition-topics.
In the `step 2` above, the flow of the progress is like the below:
1. Check the policy of topic auto-creation( the policy is `{allowAutoTopicCreationType=PARTITIONED, defaultNumPartitions=3}` )
1. Check the partitioned topic metadata already exists.
1. Try to create the partitioned topic metadata if it does not exist.
1. If created failed by …
=> [improve] [broker] Improve cache handling for partitioned topic metadata when doing lookup

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java, pulsar-sql/presto-distribution/LICENSE
- [CVE-2023-1428](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2023-1428) 
- [CVE-2023-32731](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2023-32731)
- [CVE-2023-32732](https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2023-32732)
- Upgrade `GRPC` version to 1.53.0
- Upgrade `io.perfmark-perfmark-api` to 0.26.0
=> [fix][misc] Bump GRPC version to 1.55.3 to fix CVE

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE, pulsar-sql/presto-distribution/pom.xml
Upgraded Guava to `32.1.2-jre`. This version includes a fix for an issue where building with Gradle may fail.
https://github.com/google/guava/commit/9ed0fa65ab0ecdf2f10d506e7dffeb3595953777
=> [fix][build] Upgrade Guava to 32.1.2-jre

pom.xml
Fix [🔗build failure](https://github.com/apache/pulsar/actions/runs/5952090719/job/16147560621?pr=20764) in #20764, 
As title describes. Current change should have been part of #20782, my apologies for missing out 🙏🏼.
As title describes.
PR in forked repository: https://github.com/JooHyukKim/pulsar/pull/22
=> [refactor][cli][PIP-280] Add missing `pulsar-cli-utils` module registration in Maven `core-modules` profile

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/UnAckedMessageTracker.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/UnAckedMessageTrackerTest.java
Fixes https://github.com/apache/pulsar/issues/20934
If the consumer receives a chunked message, it currently couldn't retry it or send it to the DLQ. It will throw an exception like this:
```
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$InvalidMessageException: The producer xxx of the topic persistent://a/b/c sends a message with 8085120 bytes that exceeds 5242880 bytes
```
This is because we don't enable the chunking for the retry producer and the DLQ producer in the consumer.
This PR enables the chunking feature for retry and DLQ producers. However, we cannot enable both chunking and batching simultaneously. Therefore, the trade-off of this change is that we have to turn off the batching for the DLQ producer, while the retry producer has …
=> [fix][client] Fix cannot retry chunk messages and send to DLQ

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/PulsarResources.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/resources/NamespaceResourcesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java
When deleting a namespace, we will delete znode under the path `/loadbalance/bundle-data` in `local metadata store` instead of `global metadata store`.
Delete bundle data znode in local metadata store.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/26
=> [fix] [broker] remove bundle-data in local metadata store.

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerUnderreplicationManager.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/LedgerUnderreplicationManagerTest.java
Fixes #21058
Main Issue: #21058
=> [fix] [auto-recovery] Improve to the ReplicaitonWorker performance by deleting invalid underreplication nodes

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SinkConfigUtilsTest.java
Fixes #xyz
PIP: #xyz 
The `RetainOrdering` and `RetainKeyOrdering` in `SinkConfig` are not passed to `FunctionDetails`, so they are not working at all
Pass these two configs to `FunctionDetails` if they are set
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/16
=> [fix][io] Fix --retain[-key]-ordering not working error for sink

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SourceConfigUtils.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/FunctionConfigUtilsTest.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SourceConfigUtilsTest.java
Fixes #21036 
PIP: #xyz 
while merging existing config with new config for updating, it doesn't check whether the new config has set the `ProducerConfig`, which makes the merged config always use the `ProducerConfig` from the existing config
set the `producerConfig` when updating `functions/sources` if the `ProducerConfig` is specified
*(or)*
*(or)*
*(example:)*
*If the …
=> [fix][fn] Fix ProducerConfig cannot update error

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
The progress Persist mark deleted position is like this:
- persist to BK
- if failed to persist to BK, try to persist to ZK
But in the current implementation: if the cursor ledger was created failed, Pulsar will not try to persist to ZK. It makes if the cursor ledger created fails, a lot of ack records can not be persisted, and we will get a lot of repeat consumption after the BK recover.
Try to persist the mark deleted position to ZK if the cursor ledger was created failed
=> [improve] [ml] Persist mark deleted ops to ZK if create cursor ledger was failed

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicUtils.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicUtilsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/StrategicCompactionTest.java
In https://github.com/apache/pulsar/pull/7060, we allow managed cursor to specify the max read batch in bytes to avoid reading too large data at a time, but reading compacted entries did not consider maxReadSizeBytes, we should make reading compacted entries also support maxReadSizeBytes limitation.
* Using the `applyMaxSizeCap` method to recalculate `numberOfEntriesToRead` before reading compacted entries.
* Update read stats after completion of reading compacted entries.
*(or)*
*(or)*
*(example:)* …
=> [improve][broker] Make read compacted entries support maxReadSizeBytes limitation

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerBkEnsemblesTests.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java
Fixes #21075 
When the topic is loaded, it will delete the topic-level policy if it is enabled. But if the topic is not loaded, it will directly delete through managed ledger factory. But then we will leave the topic policy there. When the topic is created next time, it will use the old topic policy
When deleting the topic, delete the schema and topic policies even if the topic is not loaded.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for …
=> [fix][broker] Fix deleting topic not delete the related topic policy and schema.

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageChunkingTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Handle ack hole case:
For example:
```markdown
Chunk-1 sequence ID: 0, chunk ID: 0, msgID: 1:1
Chunk-2 sequence ID: 0, chunk ID: 1, msgID: 1:2
Chunk-3 sequence ID: 0, chunk ID: 0, msgID: 1:3
Chunk-4 sequence ID: 0, chunk ID: 1, msgID: 1:4
Chunk-5 sequence ID: 0, chunk ID: 2, msgID: 1:5
```
Consumer ack chunk message via ChunkMessageIdImpl that consists of all the chunks in this chunk
message(Chunk-3, Chunk-4, Chunk-5). The Chunk-1 and Chunk-2 are not included in the
ChunkMessageIdImpl, so we should process it here.
Ack chunk-1 and chunk-2.
*(or)*
*(or)*
This change added tests and can …
=> [fix][client] Avoid ack hole for chunk message

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchMessageContainerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/StrategicTwoPhaseCompactor.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawBatchMessageContainerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/StrategicCompactionRetentionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/StrategicCompactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/StrategicCompactorTest.java
Currently, the `ServiceUnitStateChannelImpl` will send batch messages to `loadbalancer-service-unit-state` topic,
and the `StrategicTwoPhaseCompactor` will consume the message and rebatch the message to a new batch.
However, the `StrategicTwoPhaseCompactor` may write messages from the same batch into different entries, which will result in skipping some messages when reading compacted entries.
For example, we have a batch: `[(3:0:-1:0, k1), (3:0:-1:1, k2)]`, after compact, the batch maybe `[3:0:-1:0, k1]` and `[3:0:-1:0, k2]` , then if we only read one entry, the `readPosition` will be updated to `3:1` , so the `[3:0:-1:0, k2]` will be skipped.
* Check the add message `entryId` and `ledgerId` before adding a message to `RawBatchMessageContainerImpl`.
* Remove size limit for …
=> [fix][broker] Avoid splitting one batch message into two entries in StrategicTwoPhaseCompactor

pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
Currently, the compactor will write duplicate entries into the compacted ledger after RawReader reconnects on phase two.
If the messageId read is less than or equal to lastCompactedMessageId then the entry is skipped.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Fix write duplicate entries into the compacted ledger after RawReader reconnects

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/InactiveTopicDeleteTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
Currently, when `ServiceUnitStateChannelImpl#doCleanup(String broker)` method gets called, it always uses the current broker address to build the heartbeat namespace. We should build the namespace by the parameter. Otherwise, if the heartbeat namespace bundle ownership is not cleaned properly, the broker might start to fail.
Error log:
* Cleanup correctly heartbeat bundle ownership when handling broker deletion event
* Add unit test to verify.
=> [fix][broker] Cleanup correctly heartbeat bundle ownership when handling broker deletion event

pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java, pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicyTest.java
When upgraded the pulsar version from 2.9.2 to 2.10.3, and the isolated group feature not work anymore.
Finally, we found the problem. In IsolatedBookieEnsemblePlacementPolicy, when it gets the bookie rack from the metadata store cache, uses future.isDone() to avoid sync operation. If the future is incomplete, return empty blacklists. 
The cache may expire due to the caffeine cache `getExpireAfterWriteMillis` config, if the cache expires, the future may be incomplete. (#21095 will correct the behavior)
In 2.9.2, it uses the sync to get data from the metadata store, we should also keep the behavior.
=> [fix] [broker] Fix isolated group not work problem.

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/FunctionConfigUtilsTest.java
Fixes #21022 
PIP: #xyz 
the `--batch-builder` argument not working for functions, the reason is that it just save it to the `FunctionConfig`, and the backend doesn't use the `FunctionConfig.batchBuilder`.
check the `FunctionConfig.batchBuilder` in `FunctionConfigUtils#convert` method to set batch builder for the producer spec
*(or)*
*(or)*
*(example:)* …
=> [fix][fn] Fix the --batch-builder not working error for functions

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
Related to https://github.com/apache/pulsar/pull/20683. When reading the code of master-branch and branch-2.10, I found we can not remove duplicate topics name when deleteNamespace, because the implementation of internalDeletePartitionedTopicsAsync() is different in two branch. In master-branch, if we remove topics name in allUserCreatedTopics and allSystemTopic, we actually not delete the topic. So the first time delete namespace will throw exception exactly. 
revert the modification.
PR in forked repository: https://github.com/TakaHiR07/pulsar/pull/14
=> [fix][broker] revert remove duplicate topics name when deleteNamespace

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/AdminProxyHandler.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/AdminProxyHandlerKeystoreTLSTest.java
Fixes #21076
Pulsar Cluster has TLS enabled. Pulsar proxy is used to connect to it using keystore TLS. Producer and Consumer API works properly. But when the admin API is used, it returns 502 gateway error.
Steps to Reproduce:
1. Setup broker with TLS on webserviceport
2. Setup proxy with TLS enabled with keystore.
3. Run admin commands against proxy
Eg. bin/pulsar-admin --admin-url https://localhost:8443 tenants list
HTTP 502 Bad Gateway
Reason: HTTP 502 Bad Gateway
Found the following exception on debugging further with the JVM arguments on Proxy: -Dorg.eclipse.jetty.util.log.class=org.eclipse.jetty.util.log.StdErrLog -Dorg.eclipse.jetty.LEVEL=ALL
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find …
=> [fix][proxy] Fix Proxy 502 gateway error when it is configured with Keystore TLS and admin API is called

.github/ISSUE_TEMPLATE/pip.md
No need for that anymore. We have moved to submitting PIPs using PRs.
Delete issue template named PIP.
=> [cleanup][misc] Delete .github/ISSUE_TEMPLATE/pip.md

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorTest.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
- The log of `NonDurableCursorImpl` does not print the cursor name
- When catching exception `ConsumerBusyException`, no specific details were printed
Improve logs for troubleshooting
=> [improve] [broker] Improve logs for troubleshooting

pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicsWithoutTlsTest.java
Related to #20535,  if the web tls url is null, it will cause NPE:
=> [fix][broker] Fix web tls url null cause NPE

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdClusters.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdClusters.java
=> [improve][cli] Add current option in the Clusters list cmd

pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSet.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMap.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSet.java
Fixes #21109 
Fixes #21113
There is bug in `forEach` method in util class like `ConcurrentLongLongPairHashMap`.
When it detect there is another thread acquire the write lock, it will fall back to acquire the read lock, which is right. But, it will continue to iterate the array from the last time. 
1. As another thread may write the new value before the current index for iterate, it may miss the new value.
There are posibilities that it may read the new value or can't read the new value, which may volilate the consistence of data. This is the problem discribed in #21109.
2. As the time spent on 
https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java#561
```
processor.accept(storedKey1, …
```
=> [improve] [doc] Add doc for customized util class 

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageWithBatchIndexLevelTest.java
Unack count is wrong when mixing non batch index and batch index acks in one CommandAck.
Check ack type for every MessageIdData.
- Added test testMixIndexAndNonIndexUnAckMessageCount
PR in forked repository: https://github.com/erobot/pulsar/pull/3
=> [fix][broker] Fix unack count when mixing non batch index and batch index acks

conf/bookkeeper.conf
Fixes #xyz
PIP: #xyz 
When the ledger disk usage reaches 95%, the bookie will run into read-only mode. At the same time, the minor and major compaction will be disabled, which means there is no way to trigger the bookie garbage collection except by increasing the ledger disk size. It will be hard for the Pulsar Ops guys to maintain the BookKeeper cluster.
In order to support trigger major/minor compaction through REST API when the bookie disk usage reaches 95%, I pushed one PR on BookKeeper https://github.com/apache/bookkeeper/pull/3205. However, it still needs to enable the `forceAllowCompaction` in the BookKeeper configuration.
Enable the `forceAllowCompaction` by default in the BookKeeper configuration `conf/bookkeeper.conf`
*(Please pick either of the following …
=> [improve] [bookie] Enable forceAllowCompaction by default

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedderTest.java
Fixes #21016 
fix UniformLoadShedder select the wrong overloadbroker and underloadbroker
1. correct the procedure of selecting overload and underload broker
2. separating msgRate and msgThrought, and msgRate has higher priority(same as before)
PR in forked repository: https://github.com/aloyszhang/pulsar/pull/19
=> [fix][broker] fix UniformLoadShedder selecet wrong overloadbroker and underloadbroker

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/BrokerOperabilityMetrics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
As talked in [PIP-276](https://github.com/apache/pulsar/pull/20518),  we will remove `topic_load_times` after release 3.1.0
=> [cleanup][monitor] Remove metric `topic_load_times`

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ReadOnlyManagedLedgerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SnapshotSegmentAbortedTxnProcessorImpl.java
```
2023-09-12T05:35:43,141+0000 [pulsar-msg-expiry-monitor-25-1] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/xxx] Failed to get message with ledger 7213399:0 the ledgerId does not belong to this topic or has been deleted.
2023-09-12T05:35:43,141+0000 [pulsar-msg-expiry-monitor-25-1] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/xxx] Error while getting the oldest message
2023-09-12T05:35:43,292+0000 [pulsar-msg-expiry-monitor-25-1] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/default/xxx] Error while getting the oldest message
2023-09-12T05:35:43,292+0000 [pulsar-msg-expiry-monitor-25-1] ERROR org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - …
```
=> [improve] [broker] improve read entry error log for troubleshooting

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerConsumerInternalTest.java
```
2023-09-12T07:17:05,388+0000 [pulsar-web-37-4] INFO  org.apache.pulsar.broker.service.Producer - Disconnecting producer: Producer{topic=PersistentTopic{topic=persistent://public/default/tp1}, client=/127.0.0.6:36433, producerName=st-0-5, producerId=87}
2023-09-12T07:38:55,707+0000 [pulsar-io-4-1] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.6:37543][persistent://public/default/tp1] Creating producer. producerId=87
2023-09-12T07:38:55,707+0000 [pulsar-io-4-1] WARN  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.6:37543] Failed to add producer to topic persistent://public/default/tp1: producerId=87, Producer with name 'st-0-5' is already connected to topic
2023-09-12T07:38:55,916+0000 [pulsar-io-4-1] INFO  org.apache.pulsar.broker.service.ServerCnx - …
```
=> [fix] [broker] Make specified producer could override the previous one

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/BrokerOperabilityMetrics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
When generating broker basic metrics, it misses some metrics in the BrokerOperabilityMetrics.
=> [fix][broker] Fix missing generate some metrics in BrokerOperabilityMetrics

conf/bookkeeper.conf
Fixes #xyz
PIP: #xyz 
In `conf/bookkeeper.conf`, the document and default values of `diskUsageWarnThreshold` and `diskUsageLwmThreshold` are not synced with the code.
Update the document and default value of `diskUsageWarnThreshold` and `diskUsageLwmThreshold`
*(or)*
*(or)*
*(example:)*
=> [improve] [bk] Update the document of diskUsageWarnThreshold

pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/BaseContext.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ContextImplTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceRunnableTest.java, pulsar-io/common/src/test/java/org/apache/pulsar/io/common/IOConfigUtilsTest.java, pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/sink/KafkaAbstractSinkTest.java
PIP: #21079 
Please see PIP-297:
https://github.com/apache/pulsar/blob/3cb79264c4476a2cd34b0807133afc29750c047d/pip/pip-297.md?plain=1#L71-L91
https://github.com/apache/pulsar/blob/3cb79264c4476a2cd34b0807133afc29750c047d/pip/pip-297.md?plain=1#L108-L112
This change added tests.
=> [improve][io] PIP-297: Support terminating Function & Connector with the fatal exception

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
As shown in the following figure, the throughput in/out, message in/out, bandwidht in/out usage and CPU usage go up and down periodically as time goes by, while the memory usage and direct memory usage has nothing to do with the actual load.
Using memory usage and direct memory usage to score the broker load will result into wrong result.
~~Removing memory usage and direct memory usage for scoring.
As [PR#19559 ](https://github.com/apache/pulsar/pull/19559) has removed memory usage, i will remove direct memory usage for scoring.~~
Change the default value of `loadBalancerDirectMemoryResourceWeight`.
PR in forked …
=> [improve] [broker] disable balancing based on DirectMemory.

conf/bookkeeper.conf
Fixes #xyz
PIP: #xyz 
We set `flushEntrylogBytes` to 256MB in https://github.com/apache/pulsar/pull/6915, however, this value is good for HDD but not SSD. SSD has better performance on small IOs. In order to balance the performance on SSD and HDD, we'd better reduce the value to 32MB.
Change flushEntrylogBytes default value from 256MB to 32MB
*(or)*
*(or)*
*(example:)* …
=> [improve] [bookie] Change flushEntrylogBytes default value from 256MB to 32MB

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/AdvertisedListenersTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/OwnerShipForCurrentServerTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientAuthenticationTlsTest.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyRefreshAuthTest.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyServiceTlsStarterTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/BrokerContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ProxyContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/tls/ClientTlsTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarClusterSpec.java
=> [fix][broker]  Fix PulsarService.getLookupServiceAddress returns wrong port if TLS is enabled

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/KeySharedSubscriptionTest.java, pulsar-sql/presto-distribution/LICENSE
Fixes #xyz
PIP: #xyz 
BookKeeper 4.14.8 has been released: https://github.com/apache/bookkeeper/pull/4053/files
It contains many critical bug fixes and improvements. We need to upgrade the BookKeeper dependency for Pulsar.
- Upgrade BookKeeper dependency from 4.14.7 to 4.14.8
- Upgrade RocksDB dependency from 6.16.4 to 6.29.4.1
*(or)*
*(or)*
*(example:)* …
=> [Branch-2.10] [imporve] [bookie] Upgrade BookKeeper dependency to 4.14.8 for branch 2.10

docker/pulsar/Dockerfile
Fixes #21206 
When autoscaling brokers, the [current default negative ttl is 10 seconds](https://github.com/apache/pulsar/blob/eefc51712c97515e5913f6e5fceb4e98f5cd3b18/pulsar-common/src/main/java/org/apache/pulsar/common/util/netty/DnsResolverUtil.java#L35-L36) so it might take up to 10 seconds before the proxy realizes the broker was available and this could lead to errors at the pulsar client if the operation timeout was below 10 seconds .
Similarly this should have positive impact for broker --> bookie (when new bookies are autoscaling).
Added a line to the Dockerfile to override the negative.ttl in the `java.security` file
*(or)*
This change is already covered by …
=> [improve][proxy] When adding new brokers resolve the DNS name more quickly

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
Replicator not removed from the replicators map when call removeReplicator in class NonPersistentTopic.
Remove replicator from replicators when call removeReplicator in class NonPersistentTopic.
=> [fix][broker] replicator leak when removeReplicator in NonPersistentTopic

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyLookupThrottlingTest.java
**Background**: The Pulsar client will close the socket if it receives a `ServiceNotReady` error when doing a lookup. 
see https://github.com/apache/pulsar/blob/af20a8a8623055bab665e566b3f54f6f884d121d/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L1193-L1200
The Broker will respond to the client with a `TooManyRequests` error if there are too many lookup requests in progress, but the Pulsar Proxy responds to the client with a `ServiceNotReady` error in the same scenario.
Make Pulsar Proxy respond to the client with a `TooManyRequests` error if there are too many lookup requests in progress.
=> [improve] [proxy] Not close the socket if lookup failed caused by too many requests

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/StrategicCompactionTest.java
Cherry-pick https://github.com/apache/pulsar/pull/21065 into branch-3.0
=> [improve][broker][branch-3.0] Make read compacted entries support maxReadSizeBytes limitation (#21065)

pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BinaryProtoLookupService.java
Multiple consumers and producers can be maintained by the same Pulsar Client. In some cases, multiple consumers or producers might attempt to connect to the same topic. To optimize the process, it is recommended to perform the topic lookup only once for each topic.
- Merge lookup requests for the same topic.
- Merge get partitioned metadata request for the same partitioned topic.
=> [improve] [client] Merge lookup requests for the same topic

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java
see: https://github.com/apache/pulsar/actions/runs/6257755998/job/16993960633?pr=21216
```
Error:  org.apache.pulsar.client.impl.PatternTopicsConsumerImplTest.testAutoSubscribePatterConsumerFromBrokerWatcher  Time elapsed: 10.152 s  <<< FAILURE!
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a org.apache.pulsar.client.impl.PatternTopicsConsumerImplTest expected [4] but found [0] within 10 seconds.
at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactor …
```
=> [fix] [broker] fix flaky test PatternTopicsConsumerImplTest

pulsar-broker/pom.xml, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStatsTest.java
AggregatedNamespaceStats is the object used when topic-level metrics are aggregated into namespace level, specifically when `exposeTopicLevelMetricsInPrometheus=false`.
There is a loop which runs over all namespaces, and for each one, the same object is used, by first resetting it and then adding each topic metrics to it. 
The existing `reset()` method lacks all fields hence some fields were accumulating over round of metrics reporting to prometheus metrics servlet, good example for it would be `pulsar_out_bytes_total`.
I've fixed AggregatedNamespaceStats.reset() by including all the fields that were missing from it.
* Added `testReset()` method. I may add in subsequent PR a more …
=> [fix][broker] Fixed reset for AggregatedNamespaceStats

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
My repo pr https://github.com/AmateurEvents/pulsar/pull/36
Fixes #xyz
PIP: #xyz 
Implement the same logic as here https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L1010
When anonymousUserRole is enabled, pulsar-admin can successfully fetch cluster resources without authenticationProvider, but pulsar-client can't produce and consume data, this pr fixes that behavior, If the cluster is configured with anonymousUserRole, it should skip the authenticationProvider's checks
*(or)*
*(or)*
This change …
=> [fix][broker]Fixed produce and consume when anonymousUserRole enabled

pip/pip-301.md
[DISCUSS thread](https://lists.apache.org/thread/7ngw9dc62tj2c4c5484dgsnlwgtstpbj)
[VOTE thread](https://lists.apache.org/thread/26dc8r6hnp7owdsq1hpzb48g8vlfrtxt)
=> [improve][pip] PIP-301: Introduce LoadBalanceResources to unify the load-date CRUD

conf/functions_log4j2.xml
In the current function_log4j2.xml deletion policy, the matching rules for log files are incorrect. This will cause log cleaning to fail.
The previous PR [https://github.com/apache/pulsar/pull/19495] fixed the broker’s log cleaning configuration. But the function’s log configuration file is still wrong.
remove "*/" of IfFileName in function_log4j2.xml
=> [fix][fn] fix functions_log4j2.xml delete strategy config
