pip/pip-286.md

* Mailing List discussion thread: https://lists.apache.org/thread/85o3sx6rhohvc370j4r7yd2nb1tx736c
* Mailing List voting thread: https://lists.apache.org/thread/q27zg49mpr8otwh29s3sncdcx8ly7ws6

[improve][pip] PIP-286: Make the TopicCompactionService to support find entry based on publishTime or index

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java

https://github.com/apache/pulsar/pull/19581 filter messages in dispatcher. However, it filters out duplicate messages after calculating `totalMessages`, which results in occupying permits even though the messages were not sent to the consumer. This could potentially cause the consumer to be stuck and unable to consume.
Calculate totalMessages after filtering out the messages.
- Added test in `org.apache.pulsar.client.impl.TransactionEndToEndTest#testMsgsInPendingAckStateWouldNotGetTheConsumerStuck`
PR in forked repository: https://github.com/hrzzzz/pulsar/pull/2

[fix][txn] fix the consumer stuck due to deduplicated messages in pending ack state

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/ServiceUnitUtils.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LeaderElectionServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java

**Background**: The Pulsar client will close the socket if it receives a ServiceNotReady error when doing a lookup. 
see https://github.com/apache/pulsar/blob/af20a8a8623055bab665e566b3f54f6f884d121d/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L1193-L1200
Closing the socket causes the other consumer or producer to reconnect and does not make the lookup more efficient.
There are two cases that should be improved:
- If the broker gets a metadata read/write error, the broker responds with a `ServiceNotReady` error, but it should respond with a `MetadataError`
- If the topic is unloading, the broker responds with a `ServiceNotReady` error.
- Respond to the client with a `MetadataError` if the broker gets a metadata read/write error.
- Respond to the client with a …

[improve] [broker] Not close the socket if lookup failed caused by bundle unloading or metadata ex

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonDurableSubscriptionTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java

Reproduce steps:
- Create a reader.
- Reader pulls messages into `incoming queue`, do not call `reader.readNext` now.
- Trim ledger task will delete the ledgers, then there is no in the topic.
- Now, you can get messages if you call `reader.readNext`, but the method `reader.hasMessageAvailable` return `false`
Note: the similar issue of `MultiTopicsConsumerImpl` has been fixed by https://github.com/apache/pulsar/pull/13332, current PR only trying to fix the issue of `ConsumerImpl`.
Make `reader.hasMessageAvailable` return `true` when `incoming queue` is not empty.

[fix] [client] fix reader.hasMessageAvailable return false when incoming queue is not empty

---

src/owasp-dependency-check-suppressions.xml

OWASP dependency check report ([example](https://github.com/apache/pulsar/actions/runs/6345669507/job/17238038834)) has some CVEs that can be suppressed.
- add 2 suppressions
- CVE-2023-37475 is a false positive
- CVE-2023-4586 is about Netty hostname verification and that is already covered in Pulsar code base with https://github.com/apache/pulsar/pull/15824 changes.
- Please notice that hostname verification is not enabled by default in Pulsar. Please see PIP-273 to change the default. #20453

[fix][sec] Add OWASP Dependency Check suppressions

---

pom.xml

Lombok 1.8.30 brings in the support for compiling with JDK 21.
Release notes at https://projectlombok.org/changelog
Upgrade Lombok to 1.18.30

[fix][build] Upgrade Lombok to 1.18.30 to support compiling with JDK21

---

buildtools/pom.xml
distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

Keep Netty dependency up-to-date to get improvements. 
- release notes since 4.1.94: 
- https://netty.io/news/2023/09/21/4-1-99-Final.html
- https://netty.io/news/2023/09/21/4-1-98-Final.html
- https://netty.io/news/2023/08/23/4-1-97-Final.html
- https://netty.io/news/2023/07/27/4-1-96-Final.html
- https://netty.io/news/2023/07/20/4-1-95-Final.html
The most relevant improvement seems to be the SSLHandler allocation improvements that came in [4.1.95](https://netty.io/news/2023/07/20/4-1-95-Final.html), https://github.com/netty/netty/pull/13472 .
Upgrade Netty to 4.1.99.Final (from 4.1.94.Final).

[improve][misc] Upgrade Netty to 4.1.99.Final

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

snappy-java 1.1.10.1 contains CVE-2023-43642 . Upgrade the dependency to 1.1.10.5 to get rid of the CVE.
Upgrade the dependency to 1.1.10.5 to get rid of the CVE.

[fix][sec] Upgrade snappy-java to 1.1.10.5

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java

Fixes #21301 
Fixes #10433
There are 2 thread safety issues in RangeCache. 
`RangeCache.put`:
https://github.com/apache/pulsar/blob/643428bb295ee4781e86aa2c72e5ad5d61b98870/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java#L76-L84
`computeIfAbsent` doesn't lock the key when ConcurrentSkipListMap is used. 
You can see this in the source code of `ConcurrentMap`:
```
default V computeIfAbsent(K key,
Function<? super K, ? extends V> mappingFunction) {
Objects.requireNonNull(mappingFunction);
V oldValue, newValue;
return ((oldValue = get(key)) == null
&& (newValue = mappingFunction.apply(key)) != null
&& (oldValue = putIfAbsent(key, newValue)) == null)
? newValue
: oldValue;
}
```
On the other hand, ConcurrentHashMap.computeIfAbsent does lock the key and …

[fix][ml] Fix thread safe issue with RangeCache.put and RangeCache.clear

---

pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java
pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMappingTest.java

https://github.com/apache/pulsar/pull/14248 fix rackaware placement policy does not take effect after delete rack configuration. But after https://github.com/apache/pulsar/pull/16825, this fix is ineffective when delete zk rack info after bkclient initialize. 
The reason is "register available bookie" is after "BookieRackAffinityMapping#setConf" in bookieClient constructor. So updateRacksWithHost(racksWithHost) would throw BookieIdNotResolvedException, make "racksWithHost" become null. "racksWithHost" is updated until "watchAvailableBookies()" listener is trigger.
I add some log of unittest testRackUpdate() to show the order of bookieClient constructor:
```
2023-08-07T15:47:23,540+0800 [main] INFO  org.apache.pulsar.bookie.rackawareness.BookieRackAffinityMapping - …
```

[fix][broker] rackaware policy is ineffective when delete zk rack info after bkclient initialize

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonDurableSubscriptionTest.java

After trimming ledgers, the variable `lastConfirmedEntry` of the managed ledger might rely on a deleted ledger(the latest ledger which contains data).
There is a bug that makes pulsar allow users to set the start read position to an unexisting ledger or a deleted ledger when creating a subscription. This makes the `backlog` and `markDeletedPosition` wrong. 
See: https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L3630-L3654
```java
public boolean isValidPosition(PositionImpl position) {
...
...
...
} else if (position.getLedgerId() == lastConfirmedEntry.getLedgerId()) {
return position.getEntryId() <= (lastConfirmedEntry.getEntryId() + 1);
} else {
...
...
...
}
``` 
Fix the bug.

[fix] [ml] Reader can set read-pos to a deleted ledger

---

managed-ledger/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
pulsar-metadata/pom.xml
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorBookieTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTaskTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicBookieCheckTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTaskTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTaskTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorRollingRestartTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuthAutoRecoveryTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AutoRecoveryMainTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/BookKeeperClusterTestCase.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/BookieAutoRecoveryTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/BookieLedgerIndexTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/TestAutoRecoveryAlongWithBookieServers.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/ZooKeeperUtil.java
pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/bookkeeper/test/BookKeeperClusterTestCase.java
testmocks/src/main/java/org/apache/bookkeeper/client/BookKeeperTestClient.java

[fix] [metadata] Fix zookeeper related flacky test

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonDurableSubscriptionTest.java

- But after trimming ledgers, `ml.lastConfirmedPosition` relies on a deleted ledger when the current ledger of ML is empty. 
- Cursor prevents setting `markDeletedPosition` to a value larger than `ml.lastConfirmedPosition`, but there are no entries to read<sup>[1]</sup>.
- The code description in the method `advanceCursors` said: do not make `cursor.markDeletedPosition` larger than `ml.lastConfirmedPosition`<sup>[2]</sup>
If there is no durable cursor, the `markDeletedPosition` might be set to `{current_ledger, -1}`, and `async mark delete` will be prevented by the `rule-2` above. So he `backlog`, `readPosition`, and `markDeletedPosition` of the cursor will be in an incorrect position after trimming the ledger. You can reproduce it by the test `testTrimLedgerIfNoDurableCursor`
--- …

[fix] [ml] fix wrong msg backlog of non-durable cursor after trim ledgers

---

pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/avro/PulsarAvroColumnDecoder.java
pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/avro/PulsarAvroRowDecoderFactory.java
pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/json/PulsarJsonFieldDecoder.java
pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/json/PulsarJsonRowDecoderFactory.java
pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/decoder/DecoderTestMessage.java
pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/decoder/avro/TestAvroDecoder.java
pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/decoder/json/TestJsonDecoder.java

As https://pulsar.apache.org/docs/3.1.x/sql-overview/, Pulsar SQL is based on [Trino (formerly Presto SQL)](https://trino.io/), which supports UUID type. But now, the UUID field in Avro or JSON schema will be interpreted as VARCHAR.
Support decoding UUID form AVRO or JSON schema.
*(or)*
*(or)*
*(example:)*

[feat][sql] Support UUID for json and avro

---

pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java

Temporarily move to the flaky group to avoid the CI being blocked.
See https://github.com/apache/pulsar/issues/21291
- Move NarUnpackerTest to flaky group

[fix][test] Move NarUnpackerTest to flaky group

---

pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java

Fixes #21291
Fixes #21285
NarUnpackerTest is really flaky. See the above isues that this PR fixes. 
When investigating the problem, I was able to reproduce the issue by running the test within Docker with constrained resources. There's a 30 second timeout in the shouldExtractFilesOnceInDifferentProcess test for the 10 different processes to complete. This takes much longer since each process uses significant amount of CPU. The fix is to reduce the CPU consumption by reducing the test data size, reducing the number of processes and tuning the JVM parameters for the forked processes.
- reduce number of processes from 10 to 5
- reduce the number of files in the sample zip from 10000 to 5000
- make the test use less CPU resources so that it will run in CI with constrained resources
- make JIT …

[fix][test] Fix flaky test NarUnpackerTest

---

pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java

Fixes #21284
CompactionTest.testDispatcherMaxReadSizeBytes is extremely flaky and blocks CI very often.
The test had a race condition in the way how the spy was injected into the PersistentTopic instance. 
This problem has been fixed now.

[fix][test] Fix flaky CompactionTest.testDispatcherMaxReadSizeBytes

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java

Fixes #21331
OneWayReplicatorTest.testReplicatorProducerStatInTopic is flaky
Remove the explicit creation of topics and subscriptions since it's not relevant for this test.

[fix][test] Fix flaky OneWayReplicatorTest.testReplicatorProducerStatInTopic

---

pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java

Fix the var name for IsolationGroups.   The name `allBookies` is a little confused.
`allBookies` -> `allGroups`
PR in forked repository:  -

[fix][bk] Fix the var name for IsolationGroups

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiMaxUnackedMessagesTest.java

Fixes #21330
AdminApiMaxUnackedMessagesTest.testMaxUnackedMessagesPerConsumerPriority is flaky.
Increase receive timeout to reduce flakiness in AdminApiMaxUnackedMessagesTest.

[fix][test] Fix flaky AdminApiMaxUnackedMessagesTest.testMaxUnackedMessagesPerConsumerPriority

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/BookKeeperClientFactoryImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/BookKeeperClientFactoryImplTest.java

[fix] [bk-client]  Fix bk client MinNumRacksPerWriteQuorum and EnforceMinNumRacksPerWriteQuorum not work problem. 

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLayoutManager.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerAuditorManager.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerManager.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorBookieCheckTaskTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorBookieTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTaskTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicBookieCheckTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPeriodicCheckTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTaskTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTaskTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorRollingRestartTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuthAutoRecoveryTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AutoRecoveryMainTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/BookieAutoRecoveryTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/BookieLedgerIndexTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/ReplicationTestUtil.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/TestAutoRecoveryAlongWithBookieServers.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/TestReplicationWorker.java

[improve] [auto-recovery] [branch-3.1] Migrate the replication testing from BookKeeper to Pulsar. 

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerFactory.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreProvider.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/OwnerShipCacheForCurrentServerTest.java

There's a synchronous method that is called from a thread which shouldn't be blocked. This happens in `ManagedCursorImpl.persistPositionMetaStore` method when the blocking `ledger.mlOwnershipChecker.get()` call is made. `mlOwnershipChecker` was introduced in #5604 and perhaps at that time, the method never blocked. This has changed and for example the flaky test #20157 has shown that this blocking happens in practice and causes deadlocks as reported in #21332.
- change the existing `Supplier<Boolean> mlOwnershipChecker` to an asynchronous `Supplier<CompletableFuture<Boolean>> mlOwnershipChecker`
- fix a race condition in `ManagedCursorImpl.persistPositionMetaStore` so that the callback for the top level method isn't called before the refreshing has occured.

[fix][ml] Make mlOwnershipChecker asynchronous so that it doesn't block/deadlock threads

---

pip/pip-299.md

- [DISCUSS](https://lists.apache.org/thread/2fzo1gnlyd1t5o80g1polbvbx4699r09)
- [VOTE](https://lists.apache.org/thread/j3k97599b3qq0lhmgyp5f93o6ny99cdt)

[improve] [pip] PIP-299: Stop dispatch messages if the individual acks will be lost in the persistent storage

---

.github/actions/clean-disk/action.yml
.github/workflows/pulsar-ci.yaml

The docker image building in Pulsar CI started failing recently with an error that can be seen in the summary view
`Unhandled exception. System.IO.IOException: No space left on device : '/home/runner/runners/2.309.0/_diag/Worker_20231013-122508-utc.log'`
The reason seems to be that there's less disk space available for the build. 
There used to be [32717 MB of free disk space before starting the build](https://github.com/apache/pulsar/actions/runs/6469034273/job/17562750174#step:5:140). In that case, the docker image building would complete. There's now [32001 MB of free disk space](https://github.com/apache/pulsar/actions/runs/6508004785/job/17677042855#step:5:137) and in that case, the disk space runs out.
Pass `mode: full` parameter to the [clean-disk action so that it also deletes …

[fix][ci] Fix docker image building by releasing more disk space before building

---

pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/NonPersistentTopicStatsImpl.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java

- `getPublishers` method gets called twice for every single publisher when aggregating topic stats in the `add` method of `TopicStatsImpl`:
https://github.com/apache/pulsar/blob/1a352f178590a210a9200dfee135089155c2f168/pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java#L262-L263
This is a slight problem since `getPublishers` method is fairly costly and causes unnecessary garbage:
https://github.com/apache/pulsar/blob/1a352f178590a210a9200dfee135089155c2f168/pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java#L152-L158
- The code for aggregating subscription and replication stats is unnecessarily complex.
- extract a variable before the loop to eliminate the problem mentioned above.
- refactor the code for …

[improve][broker] Optimize and clean up aggregation of topic stats

---

conf/broker.conf
conf/standalone.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ClusterData.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdClusters.java
pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/ClusterDataImplTest.java

Right now, topic migration requires pre-req manual steps for admin to create migrated topic's resources into green cluster such as tenant, namespaces, namespace policies, and subscriptions. This PR allows admin to automate this process and perform migration without any manual intervention.
- add config to control auto resource creation for topic migration
- perform topic resource creation at migrated green cluster before starting topic migration
```
./bin/pulsar-admin clusters update-cluster-migration $blueClusterName \
--service-url ${greenClusterServiceURL} \
--broker-url ${greenClusterURL} \
--broker-url-secure ${greenClusterURL} \
--migrated
```
Broker manages topic resource creation at new migrated/green cluster and then perform topic migration without losing data.
*(Please pick …

[feat] [broker] PIP-188 Add support to auto create topic resources into green cluster before migration [part-3]

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java

Right now, #20747 has a limitation where closing producer has to be called from the same executor of the connection-ctx which might not be always true for usecases where async operation can be completed by a different thread. #20747 was added to store value in closed-producer map thread safely so, the correct fix is to make the map thread-safe to avoid duplicate efforts during storing into the map which will remove the above limitation.
Make `recentlyClosedProducers` thread-safe as it can be accessed by multiple threads.
*(or)*
*(or)* …

[fix][broker] make closing producer thread-safe while updating recently closed producer

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/LookupService.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java

Right now, during blue-green cluster migration, broker sends redirect url of green cluster to the client and producer/consumer tries to reconnect with new URL to create producer or subscribe consumer. However, it doesn't perform lookup so, if topic is not loaded on the green cluster then green cluster never perform topic assignment and client will keep seeing below error that topic is not owned by the new cluster
```
2023-05-16T18:23:16,859-0700 [pulsar-client-io-1-1] WARN  org.apache.pulsar.client.impl.ClientCnx - [id: 0xb4862e31, L:/127.0.0.1:63224 - R:localhost/127.0.0.1:6652] Received error from server: Namespace bundle for topic (persistent://migration-test1/ns1/t1-2) not served by this instance. Please redo the lookup. Request is denied: namespace=tenant/ns1
```
Therefore, client …

[fix][client] fix producer/consumer perform lookup for migrated topic

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/Policies.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdClusters.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java

Currently the blue-green migration functionality is available at the cluster level. Need a controlled strategy to migrate the topics at namespace level.
Add config to namespace policy to enable topic migration at the namespace level.
./bin/pulsar-admin namespaces update-migration-state $namespace --migrated
Once the namespace migration is enabled, all the topics within the namespace will be migrated to the green cluster.
*(example:)*

[fix][broker]Support to migrate topics from  blue to green cluster per namespace

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java

At the branch master, the test can be passed, 
At branch-2.11, the `NamespaceStatsAggregator#printDefaultBrokerStats` will append the `pulsar_subscriptions_count`. This logic has been removed at the master branch.
https://github.com/apache/pulsar/blob/2a3b96a39c6595d7ac978e22284ac315784f25d8/pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java#L309C30-L309C56
At the topic level, it will also print `pulsar_subscriptions_count`. So the test will be failed.
The failed test:
```
Error:  testEscapeLabelValue(org.apache.pulsar.broker.stats.PrometheusMetricsTest)  Time elapsed: 0.146 s  <<< FAILURE!
java.lang.AssertionError: expected [1] but found [2]
at …
```

[fix] [test] [branch-2.11] fix testEscapeLabelValue failed

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java

Running ClusterMigrationTest could fail with OOME.
When investigating the problem, it showed up that ClusterMigrationTest's TestBroker inner class doesn't clean up resources properly. The admin clients weren't closed.
* Call `super.internalCleanup()` in the `cleanup` method.
* Close admin clients in the test cleanup method

[fix][test] Fix a resource leak in ClusterMigrationTest

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java

Right now, blue broker deletes the topic once all producers and subscriptions are migrated to green cluster. Blue cluster persist topic's migration state into zk with managed-ledger metadata. However, once topic fully migrates to green cluster, blue cluster broker deletes the topic and deletes the topic's managed-ledger metadata because of that next time if client connects to blue-broker on the same topic, blue broker recreates the same topic again which can cause incorrect connection and data loss during migration. Therefore, blue broker should not allow any new topic creation if migration is started for that namespace to avoid such data loss and incorrect connection. This PR depends on #21354
Broker fails to create topic if migration is enabled for that namespace and sends migration …

[fix][broker] Fix avoid creating new topic after migration is started

---

pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/ServiceUnitStateCompactionTest.java

There are some resource leaks in compaction tests when the bookkeeper client isn't closed.
Close the bookkeeper client.

[fix][test] Fix some resource leaks in compaction tests

---

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionE2ESecurityTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionPublishTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarWorkerAssignmentTest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/AbstractPulsarE2ETest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionAdminTest.java

Fix resource leaks with Pulsar Functions tests
Remove the duplicate call to PulsarWorkerService.init

[fix][test] Fix resource leaks with Pulsar Functions tests

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/coordinator/TransactionMetaStoreTestBase.java

TransactionCoordinatorClientTest doesn't properly close all resources.
Close transactionCoordinatorClient and stop bkEnsemble

[fix][test] Fix resource leak in TransactionCoordinatorClientTest

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceTest.java

PulsarServiceTest leaks 141 threads currently.
Properly close resources in the test.

[fix][test] Fix resource leak in PulsarServiceTest

---

pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMapTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMapTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSetTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMapTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSetTest.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/LedgerManagerIteratorTest.java

In some tests there are are executors created with `ExecutorService executor = Executors.newCachedThreadPool();` which aren't closed.
Add `@Cleanup("shutdownNow")` Lombok annotation to take care of closing the executor.

[fix][test] Cleanup cached executors in tests

---

pulsar-client/src/test/java/org/apache/pulsar/client/impl/AutoClusterFailoverTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientTestFixtures.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ControlledClusterFailoverTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerStatsRecorderImplTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/PulsarClientImplTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/auth/AuthenticationTokenTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/conf/ConfigurationDataUtilsTest.java

Tests should properly cleanup and close test resources. 
Cleanup and close test resources in the tests that are in the pulsar-client module.

[fix][test] Cleanup test resources in pulsar-client module

---

.mvn/extensions.xml

- currently used version fails with exception about "Unsupported class file major version 65" in Gradle Enterprise Maven extension's `gradle-enterprise-custom-user-data.groovy` evaluation.
- prepare for Java 21 compatibility by upgrading Gradle Enterprise Maven extension libraries

[improve][ci] Upgrade Gradle Enterprise Maven extension

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadData.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/TopKBundles.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java

(cherry picked from commit f85e0dc085d47587037cbc3f7d5443745384d350)
Currently, if the cluster has multiple brokers, and the cluster is doing rolling restart, the heartbeat namespace topic's lookup result might be wrong, because the `ExtensibleLoadManagerImpl` does not check the heartbeat and SLA namespace bundle lookup candidate broker to let them own by the specified broker.
This ownership selection is wrong:
```
2023-09-20T08:27:32,188+0000 [ForkJoinPool.commonPool-worker-1] INFO  org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImpl - Selected new owner broker: broker-2:8080 for bundle: pulsar/broker-0:8080/0x00000000_0xffffffff.
```
After the ownership assignment, the broker-0 will fail to start.
```
pulsar-broker 2023-09-20T08:27:54,707+0000 [main] INFO …
```

[fix][broker][branch-3.1] Fix lookup heartbeat and sla namespace bundle when using extensible load manager (#21213)

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTenantTest.java

There's a resource leak in AdminApiTenantTest
`cleanup` method should use `@After*` annotation instead of `@Before*` annotation, change it to use the correct annotation.

[fix][test] Fix resource leak in AdminApiTenantTest

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/util/RetryMessageUtil.java

Add `REAL_SUBSCRIPTION` when produces msg to DLQ to support subscribing regex DLQ topics

[improve][client] Add `REAL_SUBSCRIPTION` when produces msg to DLQ

---

pip/pip-302.md

Reopen https://github.com/apache/pulsar/pull/21166
**Prerequisite:** Since messages are constantly being written into the Topic and there is no read-write lock guarantee, we cannot assure the retrieval of the most up-to-date value.
**Implementation Goal:** Record a checkpoint before reading and ensure the retrieval of the latest value of the key up to this checkpoint.
**Use Case:** When read and write operations for a certain key do not occur simultaneously, we can refresh the TableView before reading the key to obtain the latest value for this key.
Introduce a new API `refreshAsync`.
*(or)* …

[improve][pip] PIP-302 Introduce refreshAsync API for TableView

---

pulsar-config-validation/src/main/java/org/apache/pulsar/config/validation/Validator.java

Fix typos in doc for Validator class
`belogs` => `belongs`

[fix][doc] Fix typos in doc for Validator class

---

pulsar-broker/src/main/java/org/apache/pulsar/compaction/PulsarTopicCompactionService.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/TopicCompactionService.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/TopicCompactionServiceTest.java

PIP: #20867 
#20867 
Add `findEntryByPublishTime` and `findEntryByEntryIndex`  in the TopicCompactionService API.
Implement them in the PulsarTopicCompactionService using binary search.
*(or)*
*(or)*
*(example:)*

[improve][broker][PIP-286] Make the TopicCompactionService to support find entry based on publishTime or index

---

pom.xml

As a preparation for future Java 21 support, it's useful to upgrade library versions to such that support Java 21 for building and running tests. Jacoco version should be upgraded to 0.8.11 to support Java 21.
Jacoco 0.8.11 release notes: https://github.com/jacoco/jacoco/releases/tag/v0.8.11
Upgrade Jacoco to 0.8.11 version

[improve][build] Upgrade Jacoco version to 0.8.11 to support Java 21

---

.github/workflows/pulsar-ci.yaml
build/run_unit_group.sh
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java

There are too many tests in the "broker" TestNG test group which gets executed in the "Broker Group 1" CI job.
The tests could take over 60 minutes to run and that is currently the timeout.
Add a new "Broker Group 4" unit test group and build job.
Move one of the slowest tests "ClusterMigrationTest" to "cluster-migration" TestNG test group. Assign "cluster-migration" to "Broker Group 4".

[improve][ci] Add new CI unit test group "Broker Group 4" with cluster migration tests

---

pom.xml
pulsar-client/src/main/resources/findbugsExclude.xml

When building with Java 21, it currently fails in spotbugs with  "Unsupported class file major version 65".
- upgrade spotbugs maven plugin version to 4.7.3.6 
- fix new spotbugs errors by adding excludes

[improve][build] Upgrade spotbugs maven plugin version for Java 21 compatibility

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java

If we set transactionCoordinatorEnabled=true, heartbeat namespace create __transaction_buffer_snapshot topic. 
Actually heartbeat namespace should not create transaction internal topic.
```
2023-10-12T11:24:44,738+0800 [bookkeeper-ml-scheduler-OrderedScheduler-2-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl - [pulsar/localhost:59381/persistent/healthcheck] Successfully initialize managed ledger
2023-10-12T11:24:44,809+0800 [bookkeeper-ml-scheduler-OrderedScheduler-2-0] INFO  org.apache.pulsar.broker.systopic.NamespaceEventsSystemTopicFactory - Create transaction buffer snapshot client, topicName : persistent://pulsar/localhost:59381/__transaction_buffer_snapshot
2023-10-12T11:24:44,839+0800 [broker-topic-workers-OrderedExecutor-7-0] INFO …
```

[fix][broker] Fix heartbeat namespace create transaction internal topic

---

build/run_integration_group.sh
buildtools/pom.xml
pom.xml
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentDispatcherFailoverConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java
pulsar-client-tools/src/test/java/org/apache/pulsar/shell/ConfigShellTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerBuilderImplTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionMetaDataManagerTest.java
pulsar-sql/presto-distribution/LICENSE

The current Mockito version isn't compatible with Java 21 and crashes with exception about "Unsupported class file major version 65".
- Upgrade Mockito to 5.6.0
- mockito-inline has been removed is part of mockito-core
- upgrade Objenesis to 3.3 which is the version that mockito-core depends on
- replace `anyObject()` -> `any()` since `anyObject()` has been removed
- Fix Mockito usage errors such as 
- "IllegalArgument Please don't pass mock here. Spy is not allowed on mock." 
- "Actual invocations have different arguments" where ArgumentCaptor type doesn't match the captured instance type

[improve][test] Upgrade Mockito to 5.6.0 for Java 21 compatibility

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java

1. Heartbeat namespace should not create __change_events topics. But if we call admin.topics.getRetention(persistent://pulsar/localhost:65213/healthcheck) , or other admin topic api, event topic still be created. we'd better avoid this case, although in most time we would not call admin api for healthcheck topic.
```
2023-10-12T11:52:59,499+0800 [pulsar-io-8-3] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [12/10月/2023:11:52:59 +0800] "GET /admin/v2/brokers/health?topicVersion=V2 HTTP/1.1" 200 2 "-" "Pulsar-Java-v3.2.0-SNAPSHOT" 426
2023-10-12T11:52:59,508+0800 [bookkeeper-ml-scheduler-OrderedScheduler-6-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Opening managed ledger pulsar/localhost:54480/persistent/__change_events-partition-1 …
```

[fix][broker] Fix heartbeat namespace create event topic and cannot delete heartbeat topic

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/manager/UnloadManager.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java

Fix #20157
When enabling the topic level policies in `ExtensibleLoadManagerImplTest`, the unload operation will get stuck
The root cause is when unloading the bundle, it will close the topic, and if `UpdateCursorInfo` fails, it will call the `ledger.mlOwnershipChecker.get()`.
https://github.com/apache/pulsar/blob/8438e43fb02b6d8df29672c6460a2f3da924ab60/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L2692-L2694
The `mlOwnershipChecker` will check the topic owner again.
https://github.com/apache/pulsar/blob/8438e43fb02b6d8df29672c6460a2f3da924ab60/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1751
Since the current state is `Releasing`, this feature will not be complete since the `closeServiceUnit` is incomplete, …

[fix][broker] Fix unload operation stuck when use ExtensibleLoadManager

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

OWASP dependency check reports CVE-2023-44487 for Jetty (and also Netty).
Upgrade Jetty to 9.4.53.

[fix][sec] Upgrade Jetty to 9.4.53 to address CVE-2023-44487

---

buildtools/pom.xml
distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

OWASP dependency check reports CVE-2023-44487 for Netty (and also Jetty).
Upgrade Netty to 4.1.100.
Release notes: https://netty.io/news/2023/10/10/4-1-100-Final.html

[fix][sec] Upgrade Netty to 4.1.100 to address CVE-2023-44487

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

OWASP dependency check reports CVE-2023-44981 for Zookeeper.
Upgrade Zookeeper to 3.8.3.
Release notes: https://zookeeper.apache.org/doc/r3.8.3/releasenotes.html

[fix][sec] Upgrade Zookeeper to 3.8.3 to address CVE-2023-44981

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadData.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/models/TopKBundles.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java

(cherry picked from commit f85e0dc085d47587037cbc3f7d5443745384d350)
Currently, if the cluster has multiple brokers, and the cluster is doing rolling restart, the heartbeat namespace topic's lookup result might be wrong, because the `ExtensibleLoadManagerImpl` does not check the heartbeat and SLA namespace bundle lookup candidate broker to let them own by the specified broker.
This ownership selection is wrong:
```
2023-09-20T08:27:32,188+0000 [ForkJoinPool.commonPool-worker-1] INFO  org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImpl - Selected new owner broker: broker-2:8080 for bundle: pulsar/broker-0:8080/0x00000000_0xffffffff.
```
After the ownership assignment, the broker-0 will fail to start.
```
pulsar-broker 2023-09-20T08:27:54,707+0000 [main] INFO …
```

[fix][broker][branch-3.0] Fix lookup heartbeat and sla namespace bundle when using extensible load manager (#21213)

---

.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml
build/docker/Dockerfile
docker/pulsar/Dockerfile
docker/pulsar/pom.xml
tests/docker-images/java-test-image/Dockerfile
tests/docker-images/java-test-image/pom.xml

When preparing for Java 21, it is useful to be able to run the Pulsar build and tests with Java 21. 
Parameterize the JDK version in the GitHub Actions Pulsar CI workflow so that Java 21 can be selected when triggering the workflow manually:

[improve][ci] Parameterize CI build so that Java 21 can be selected for manual runs

---

.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

Run a scheduled daily Java 21 CI build to ensure that Java 21 support doesn't break in master branch. 
apache/pulsar master branch currently supports compiling and running all tests with Java 21. A scheduled build with Java 21 will help prevent possible regressions. 
- add new scheduled build to pulsar-ci.yaml and pulsar-ci-flaky.yaml which will use Java 21
- cancel scheduled builds in forks by default so that forks don't waste resources on scheduled Pulsar CI builds

[improve][ci] Schedule daily Pulsar CI build with Java 21

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/LoadBalanceResources.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImplTest.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/BrokerMonitor.java

See pip: https://github.com/apache/pulsar/pull/21129
Add  `BrokerTimeAverageDataResources`
https://github.com/AnonHxy/pulsar/pull/46

[refactor][broker ] PIP-301 Part-2: Add BrokerTimeAverageDataResources

---

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/AuthenticationDataProvider.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationDataTls.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/NettyClientSslContextRefresher.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/FileModifiedTimeUpdaterTest.java

Fix typos in AuthenticationDataProvider interface
Modify the interface name from `getTlsCerificateFilePath` to `getTlsCertificateFilePath`

[fix][client] Fix typos in AuthenticationDataProvider interface

---

pulsar-broker/src/main/java/org/apache/pulsar/zookeeper/LocalBookkeeperEnsemble.java
pulsar-broker/src/test/java/org/apache/pulsar/zookeeper/LocalBookkeeperEnsembleTest.java

LocalBookkeeperEnsemble leaks threads and memory.
The way it leaks threads is when `portManager` is set to `() -> 0`, the metadata in Zookeeper will conflict and the bookies that start after the first bookie will first throw InvalidCookieException. When the InvalidCookieException is thrown, threads are leaked since the embedded bookie server doesn't close the Zookeeper client in that case.
Another problem is the memory leak that happens via shutdown hooks when Bookkeeper's `ComponentStarter` class is used to start each bookie. That registers a shutdown hook which essentially causes a memory leak.
To fix the issue with the invalid cookie, set a unique bookie id for each bookie.
The solution to the memory leak via the shutdown hook is to start the component directly without the …

[fix][test] Fix LocalBookkeeperEnsemble resource leak in tests

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java
pulsar-broker-common/src/test/java/org/apache/pulsar/broker/resources/NamespaceResourcesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java

https://github.com/apache/pulsar/pull/21078

[cherry-pick][branch-2.11] [fix] [broker] remove bundle-data in local metadata store.

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java

Tests that support retries with TestRetrySupport class should call `incrementSetupNumber` method as part of initialization so that while retrying the test, it can be detected that the initialization methods should be called before retrying. This support is needed when BeforeClass/AfterClass methods are used for initializing the test state.
Some tests which extend `MockedPulsarServiceBaseTest` call the `init` method instead of using `internalSetup` where the `incrementSetupNumber` method is called. By moving the call to the `init` method, these tests will also properly handle test retries where initialization is done in a method annotated with `@BeforeClass`.
Move the `incrementSetupNumber` call in `MockedPulsarServiceBaseTest` from the `internalSetup` method to `init` method.

[improve][test] Fix test retries for tests that don't call internalSetup

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/UnloadSchedulerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientDeduplicationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ClientCnxTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConnectionHandlerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RetryUtilTest.java
pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeClientSideEncryptionTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/FutureUtilTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/TrustManagerProxyTest.java
tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/FileStoreTestBase.java
tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloaderTest.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderTest.java

There are thread leaks in tests caused by executors (thread pools) that aren't shutdown properly. 
Properly shutdown executors that have been created during test execution.

[fix][test] Fix thread leaks in tests by closing executors properly

---

pip/pip-298.md

This pip is to implement Read Committed and Read Uncommitted isolation levels for Pulsar transactions, allow consumers to configure isolation levels during the building process.
For more details, please refer to `pip-298.md`

[improve] [pip] PIP-298 Consumer supports specifying consumption isolation level

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
managed-ledger/src/test/java/org/apache/bookkeeper/test/MockedBookKeeperTestCase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/BookKeeperClusterTestCase.java
pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/test/MockedBookKeeperTestCase.java

Managed Ledger tests leak threads. 
- remove duplicate shutdown code in ManagedLedgerFactoryImpl
- shutdownAsync and shutdown contained almost identical code. Make shutdown use shutdownAsync instead of duplicating the code 
- Fix an issue in the async shutdown code where the executor couldn't be closed since it was called from one of the executor threads
- fix issue in MockedBookKeeperTestCase cleanup where the metadata store didn't get closed when the factory had already been shutdown in the test
- add diagnostics to metadata store threadpool to identify which test created the metadata store
- metadata store threads didn't have an identifier when the metadata store name was empty. Fix this issue.
- the changes in metadata store naming will help identify the threads in the future

[fix][test] Fix thread leaks in Managed Ledger tests and remove duplicate shutdown code

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/WebServer.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithJwtAuthorizationTest.java

Some vendors don’t support health checks with authentication like AWS health checks. Which will make it hard to integrate with the vendor.
- Move the status.html endpoint out of auth coverage.
The tests will be run in the forked repository until all PR review comments have
been handled, the tests pass and the PR is approved by a reviewer.
-->

[fix][proxy] Move status endpoint out of auth coverage

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/MultiBrokerTestZKBaseTest.java

MultiBrokerLeaderElectionExpirationTest and MultiBrokerLeaderElectionTest both leak over 70 threads. They use MultiBrokerTestZKBaseTests as the base class. There's an issue that the base test creates metadata store instances, but doesn't close them. 
Close metadata stores instances created in the test.

[fix][test] Close metadata stores in MultiBrokerTestZKBaseTests

---

pip/pip-305.md

A PIP for making Pulsar Client used DNS servers configurable.
PR in forked repository: https://github.com/apache/pulsar/pull/21227

[improve][pip] PIP-305: Customize DNS servers to use for Pulsar Client

---

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientBuilderImplTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/PulsarClientImplTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/conf/ConfigurationDataUtilsTest.java

This closes #21226
Currently is not possibile to configure one or more dns servers that will be used by the client to resolve hostnames.
Added an optional configuration ClientConfigurationData.dnsServerAddresses to allow to configure custom DNSs. It not provided or empty will default to the existing behaviour.
Handled the new conf in ConnectionPool.
- *Added unit test on ClientBuilderImplTest with configuration of both good or wrong dns servers*
- *Added integration test on PulsarClientImplTest with a custom configured dns servers list*
- *Added unit test on ConfigurationDataUtilsTest about the new configuration loading*

[improve][client] Add a way to configure which DNS use

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java

This PR #14648 is incorrectly introduced, causing broker service unavailability while upgrading brokers in heterogeneous hardware config clusters. Sometime broker can’t find nic speed as it’s not defined into multiple types of VM which is very well know behavior and that’s why broker handles such usecase while managing load report by avoiding n/w bandwidth metrics.
This PR #14648 was introduced by completely ignoring heterogeneous hardware configuration cluster usecase because of that broker upgrade in that cluster has brought down all those VM brokers and can cause the outage. that PR also had test cases failing due to the same reason and it was addressed by another hack by configuring `loadBalancerOverrideBrokerNicSpeedGbps`. again `loadBalancerOverrideBrokerNicSpeedGbps` doesn’t work …

[fix][broker] Allow broker deployment in heterogeneous hw config cluster without restricting nic speed detection

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

No issue for this yet, just a small improvement
Some of the current error messages have grammar errors or are hard to understand
Fix error messages when updating partition count for a topic
PR in forked repository: https://github.com/alpreu/pulsar/pull/10

[improve][broker] Improve error messages when updating partition count

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/ClusterResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/PulsarResources.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Clusters.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ClusterData.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ClusterPolicies.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ClustersImpl.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdClusters.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/ClusterDataImpl.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/ClusterPoliciesImpl.java
pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/ClusterDataImplTest.java

Right now, when blue and green cluster shares the same global-zookeeper/configuration-metadata store to persist cluster metadata and migration metadata then cluster migration state also impact green cluster incorrectly as they both the same metadata because of that it also makes green cluster to start migration. Therefore, store cluster migration metadata to local metadata-store with name cluster policies.
Add cluster policies into local metadatastore and avoid cyclic cluster migration for green cluster. 
It depends on #21354
*(or)*
*(or)* …

[feat] [broker] PIP-188 Fix cluster migration state store into local metadatastore 

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java

Cherry-pick #21065 to branch-2.11

[improve][broker][branch-2.11] Make read compacted entries support maxReadSizeBytes limitation (#21065)

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/BrokerInterceptorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/CounterBrokerInterceptor.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java

The broker misses intercept the `REDELIVER_UNACKNOWLEDGED_MESSAGES` command.
- Call `safeInterceptCommand()` to intercept the `REDELIVER_UNACKNOWLEDGED_MESSAGES` command

[fix][broker] Intercept REDELIVER_UNACKNOWLEDGED_MESSAGES command

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/Policies.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/LocalPolicies.java

Right now, Namespace policies are stored in global metadata store which can be shared by blue and green cluster during migration which incorrectly cause migration in green cluster as well so, we need to store namespace migration policies in the local metadata store so, that each cluster can manage its own migration state and it can avoid cyclic migration impact in green cluster as well.
Add namespace policies into local policies and avoid cyclic cluster migration for green cluster.
It depends on https://github.com/apache/pulsar/pull/21354
*(or)*
*(or)*
This change added tests and can …

[feat] [broker] PIP-188 Fix cluster migration state store into local namespace policies

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java

LoadBalancerTest leaks some threads. 
- remove the unused thread pool
- while debugging, it revealed that testLeaderElection method caused some thread leaks. 
- the logic to prevent duplicate calls to `PulsarService.close()` isn't needed anymore. 
- removing this logic fixed the issue although it doesn't seem to be obvious from the code since it looks like cleanup was happening properly also before making these changes.

[fix][test] Fix resource leaks in LoadBalancerTest

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java

Right now, there is no way to create v1/namespace with policies. Added support to create v1/namespace with policies.
Added a new endpoint /{property}/{cluster}/{namespace}/policy  to  support creation of v1/namespace with policies
- Added tests to create v1/namespace with policies

[fix][broker]Create v1/namespace with Policies

---

pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMapTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSetTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMapTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSetTest.java

Concurrent collections tests continue to leak threads. 
- replace `while (true)` with `while (!Thread.currentThread().isInterrupted())` so that the thread has a chance to exit when the thread pool is shutdown.

[fix][test] Fix thread leak in concurrent collections tests

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java

The documentation inaccurately represents the unit for loadBalancerReportUpdateMaxIntervalMinutes - it is actually in minutes, not seconds. Additionally, the explanation for loadBalancerBrokerLoadDataTTLInSeconds is unclear.
```
"The current default is loadBalancerReportUpdateMaxIntervalMinutes * 2. "
```
Actually, it numerically equates to loadBalancerReportUpdateMaxIntervalMinutes * 120.
- Correct the documentation

[fix] Fix incorrect unit and doc for `loadBalancerReportUpdateMaxIntervalMinutes`

---

pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyEncryptionPublishConsumeTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeClientSideEncryptionTest.java
pulsar-websocket/src/test/java/org/apache/pulsar/websocket/AbstractWebSocketHandlerTest.java
pulsar-websocket/src/test/java/org/apache/pulsar/websocket/WebSocketHttpServletRequestWrapperTest.java

There are a few tests where threads are leaked since WebSocketService isn't closed.
This type of issues can now be detected with #21450 improvements to CI. 
Close WebSocketService properly in tests.

[fix][test] Fix thread leaks related to unclosed WebSocketService

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PulsarTestClient.java

PulsarTestClient used in tests leaks resources.
- close the resources when the client is closed or shutdown

[fix][test] Fix resource leak when PulsarTestClient is closed or shutdown

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java

PulsarTestContext leaks resources when starting PulsarService fails. This happens at least in ManagedLedgerCompressionTest.
Improve logic when PulsarService.start fails. Improve logic to chain closing of another PulsarTestContext.

[fix][test] Cleanup resources if starting PulsarService fails in PulsarTestContext

---

pulsar-broker-auth-oidc/src/main/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenID.java
pulsar-broker-auth-oidc/src/test/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenIDIntegrationTest.java
pulsar-broker-auth-oidc/src/test/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenIDTest.java
pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandaloneStarter.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/CreateSubscriptionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/InvalidBrokerConfigForAuthorizationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/ExceptionsBrokerInterceptorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentDispatcherFailoverConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/StandaloneTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/ServiceUnitStateCompactionTest.java

Each test should properly close the resources that it creates. Leaked resources consume memory and can also consume CPU and cause test flakiness. This PR continues fixing thread leaks in tests detected with the thread leak detection solution part of PR #21450.
Property close resources in tests.

[fix][test] Fix multiple thread leaks in tests

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/utils/ClientChannelHelper.java

There is an issue similar to the https://github.com/apache/pulsar/pull/21155 fixed one.
The client assumed the connection was inactive, but the Broker assumed the connection was fine. The Client tried to  use a new connection to reconnect an exclusive consumer, then got an error `Exclusive consumer is already connected`
- Check the connection of the old consumer is available when the new one tries to subscribe

[fix] [broker] Make the new exclusive consumer instead the inactive one faster

---

pulsar-io/elastic-search/pom.xml
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchAuthTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkRawDataTests.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkTests.java

pulsar-io/elastic-search tests leak containers since the method initBeforeClass has the `@BeforeMethod` annotation when it should be `@BeforeClass`.
- rename `@BeforeMethod` -> `@BeforeClass` for the `initBeforeClass` methods
- remove the `testReuseFork=false` workaround
- add `testcontainers-ryuk` to ignored threads in `ThreadLeakDetectorListener`

[fix][ci] Use correct annotation to prevent resource leaks in Elastic integration tests

---

.mvn/gradle-enterprise.xml

The Gradle Enterprise Maven extension is active even when it's not needed. 
Some PR builds failed with this kind of exception.
```
Error: [ERROR] Internal error in Gradle Enterprise Maven extension: Failed to capture test events
com.gradle.maven.common.logging.GradleEnterpriseException: Internal error in Gradle Enterprise Maven extension: Failed to capture test events
at com.gradle.maven.common.logging.GradleEnterpriseException.a (SourceFile:19)
at com.gradle.maven.scan.extension.internal.capture.r.i.a (SourceFile:189)
at com.gradle.maven.cache.extension.d.h.a (SourceFile:31)
at com.gradle.maven.cache.extension.d.m.a (SourceFile:27)
at com.gradle.maven.cache.extension.d.a.c (SourceFile:115)
at com.gradle.maven.cache.extension.d.a.a (SourceFile:61)
at com.gradle.maven.cache.extension.d.e.a …
```

[improve][ci] Disable Gradle Enterprise unless GRADLE_ENTERPRISE_ACCESS_KEY is set

---

buildtools/src/main/java/org/apache/pulsar/tests/ThreadLeakDetectorListener.java

Testcontainers background threads get reported as leaked threads by ThreadLeakDetectorListener. These threads aren't actual leaks and should be ignored.
- Add rule to ignore Testcontainers background threads in ThreadLeakDetectorListener
- Also ignore "JNA Cleaner" which is unrelated to Testcontainers
There might be more threads that need to be ignored, but let's see if those appear.
Examples from other OSS projects:
- https://github.com/apache/cassandra/blob/trunk/test/unit/org/apache/cassandra/tools/OfflineToolUtils.java
- https://github.com/apache/activemq-artemis/blob/main/artemis-unit-test-support/src/main/java/org/apache/activemq/artemis/utils/ThreadLeakCheckRule.java

[improve][ci] Ignore Testcontainers background threads in ThreadLeakDetectorListener

---

pulsar-metadata/pom.xml
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorCheckAllLedgersTaskTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorPlacementPolicyCheckTaskTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorReplicasCheckTaskTest.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/BookKeeperClusterTestCase.java
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/BookieLedgerIndexTest.java

There are multiple resource leaks in pulsar-metadata bookkeeper.replication tests.
- Introduce the `registerCloseable` solution to `BookKeeperClusterTestCase` to conveniently handle closing of resources in the tearDown method.
- Use this in the tests to close resources properly.
- also change testForkCount to 2 since there's a sporadical error the pulsar-metadata tests fail with OOM error code 134.

[fix][test] Fix resource leaks in pulsar-metadata bookkeeper.replication tests

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/WebServer.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithJwtAuthorizationTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/UnauthedAdminProxyHandlerTest.java

[branch-2.10][fix][proxy] Move status endpoint out of auth coverage

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java

PulsarService shutdown leaks threads in tests when execution is slow enough that the thread gets interrupted before the second phase of the shutdown is executed. It is hard to reproduce this issue on an ordinary developer machine because execution completes so quickly that the path where the thread has already been interrupted doesn't happen. In CI, there's 2 cores and 4 test processes running concurrently and the problem occurs fairly often. For example, the thread leak detector reported that ServerCnxTest leaked 144 threads [in this build](https://github.com/apache/pulsar/actions/runs/6710630191/job/18242485629#step:16:201):
```
Tests in class ServerCnxTest created thread id 10950 with name 'Thread[broker-topic-workers-OrderedExecutor-0-0,5,main]'
Tests in class ServerCnxTest created …
```

[fix][broker] Fix PulsarService/BrokerService shutdown when brokerShutdownTimeoutMs=0

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java

See https://github.com/apache/pulsar/pull/21155#discussion_r1328892859
If a producer establishes a new connection when it is reconnecting, while the previous connection is now inactive, the initial request made on the new connection will fail.  This failure will trigger the topic of cleaning up the inactive producers.  However, upon making a second request, the producer will be able to successfully establish a connection and proceed with the operation.
Make the initial request made on the new connection success.

[improve] [broker] Let the producer request success at the first time if the previous one is inactive

---

buildtools/src/main/java/org/apache/pulsar/tests/ThreadLeakDetectorListener.java

The thread leak detection added in #21450 reports some Testcontainer threads as leaks. These threads can be safely ignored since they will be terminated eventually.
- detect threads where the Runnable class is under "org.testcontainers" package. Some threads don't have an unique name and the only way to detect them is to check the Runnable's class name.
- ignore threads where the name starts "testcontainers-wait-"

[improve][ci] Improve thread leak detection by ignoring more Testcontainers threads

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/MultiRolesTokenAuthorizationProvider.java
pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authorization/MultiRolesTokenAuthorizationProviderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiRolesTokenAuthorizationProviderTest.java

Avoid passing the `null` role in `MultiRolesTokenAuthorizationProvider` when the JWT token does not have a corresponding claim.
```
2023-10-31T06:24:46,838+0000 [pulsar-io-4-1] DEBUG org.apache.pulsar.broker.service.ServerCnx - [/10.xx.xx.xx:52096] Authenticate role : admin
2023-10-31T06:24:46,839+0000 [pulsar-io-4-1] DEBUG org.apache.pulsar.broker.service.ServerCnx - [/10.xx.xx.xx:52096] Authenticate original role : d8a70f89-062f-4d9e-9ca5-024d8c5342ec
2023-10-31T06:24:46,839+0000 [pulsar-io-4-1] DEBUG org.apache.pulsar.broker.service.ServerCnx - Authenticate using original auth state : false, role = null
2023-10-31T06:24:46,839+0000 [pulsar-io-4-1] WARN  org.apache.pulsar.broker.authorization.AuthorizationService - [/10.xx.xx.xx:52096] Non-proxy role [admin] passed originalPrincipal …
```

[fix][broker] Avoid pass null role in MultiRolesTokenAuthorizationProvider

---

pom.xml

Pulsar depends on multi-version `org.checkerframework:checker-qual`
Unified the version of the library `org.checkerframework:checker-qual`

[fix] [build] Unified the version of the library org.checkerframework

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupRateLimiterTest.java

Fixes #20385
The test wait time is too short.
*(or)*
*(or)*
*(example:)*

[fix][test] Fixed too short wait in ResourceGroupRateLimiterTest

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TransactionBufferHandlerImpl.java

Fixes #21504 
Main Issue: #21504 
fix OpRequestSend reuse problem cause tbClient commitTxnOnTopic timeout unexpectedly
do not use op.requestId in timeout. Because when timeout task trigger, the OpRequestSend object may has changed. 
PR in forked repository: https://github.com/TakaHiR07/pulsar/pull/18

[fix][txn] OpRequestSend reuse problem cause tbClient commitTxnOnTopic timeout unexpectedly

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicUtils.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicUtilsTest.java

Fixes #21464
The consumer shouldn't read ongoing messages from compacted topic.
Pass `topic.getMaxReadPosition()` to cursor when reading messages from the compacted topic.
*(or)*
*(or)*
*(example:)*

[fix][broker] Fix issue with consumer read uncommitted messages from compacted topic

---

.github/workflows/pulsar-ci.yaml
build/run_unit_group.sh
pulsar-metadata/pom.xml

The test JVM crashes frequently in pulsar-metadata tests due to #19307 . Since metadata unit tests are part of the OTHER group, there's a need to re-run all tests in that group. The OTHER group is already slow so this wastes resources and adds delay. 
- move pulsar-metadata unit tests from OTHER to new METADATA group

[improve][ci] Move pulsar-metadata unit tests from OTHER to new METADATA group

---

conf/bookkeeper.conf

The AutoRecovery would move the data to another alive bookie to ensure the data replicas. So it will read data from the alive bookie at the ensemble, then write the data to the new bookie.
When reading data, it will choose the bookie in the ensemble randomly, so it may choose the bookie that may be already shut down, and then print many warm logs.
If we make `stickyReadSEnabled=true`, it will read the data from the alive bookie continually, and won't print any warm log, and the stickyReadS can improve hit rate of the bookie server read cache, speed the read operation.

[improve] [auto-recovery] Make AutoRecovery enable stickyReadS as default.

---

buildtools/src/main/java/org/apache/pulsar/tests/ThreadLeakDetectorListener.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApiTest.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerAuditorManagerTest.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/impl/RocksdbMetadataStoreTest.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithAuthorizationTest.java
pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterTest.java

There are thread leaks in tests reported by the thread leak detection added in #21450.
Fix multiple thread leaks in unit tests.

[fix][test] Fix multiple thread leaks in tests, part 2

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/MockManagedLedger.java

Right now, the broker is failing to create a reader for a topic that is inactive and has deleted the inactive ledger as it has reached the inactive-ledger-timeout threshold. inactive-ledger-deletion task deletes inactive ledger but it doesn't create a new ledger because of that such topic stays with `LedgerClosed` state and without active ledger, and meanwhile if any reader tries to connect on that topic then reader creation fails with below error
```
09:55:28.217 [pulsar-io-4-26] WARN  org.apache.pulsar.broker.service.ServerCnx - [/67.195.180.205:57218][persistent://tenant1/us-east1/ns1/t1][rea
der-8a3095b8c5] Failed to create consumer: consumerId=15, null
java.util.concurrent.CompletionException: java.util.NoSuchElementException
at …
```

[fix][broker] Fix failure while creating non-durable cursor with inactive managed-ledger

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannel.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnedBundle.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TransportCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/OwnershipCacheTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
pulsar-common/src/main/proto/PulsarApi.proto

PIP: #20748 
Please refer to the pip https://github.com/apache/pulsar/pull/20748
There will be a separate PR for the similar changes on `CloseConsumerCmd`.
Please refer to the pip https://github.com/apache/pulsar/pull/20748
- Added assignedBrokerUrls to CloseProducerCmd to skip client lookups upon producer reconnections during topic unloading
- Upon bundle transfer, `topic.close(..)` will be called  at the source broker two times:
- At `Releasing`, without disconnecting producers
- At `Owned`, to fully close the producers with assigned broker information
Added new tests In `ExtensibleLoadManagerTest` to cover this logic.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/53

[improve][broker] PIP-307 Added assignedBrokerUrl to CloseProducerCmd to skip lookups upon producer reconnections during unloading

---

.asf.yaml

Discussion: https://lists.apache.org/thread/6hsv4lsrx00ztd7cw6b00xjr1w6tgcjg.
The Pulsar repo needs to prevent accidental unsquashed PR merges. As discussed, we could reenable this `rebase and merge` option if there is strong demand(currently this merge option is rarely used)

[improve][misc] Disable rebase and merge to prevent unsquashed PRs

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TableViewTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java

Reopen https://github.com/apache/pulsar/pull/21170
If a topic persistently experiences a substantial quantity of data inputs,  the act of reading all the messages present in this topic to build a TableView can take an excessive amount of time.
In the process of constructing the TableView, initially, the last message ID of the current topic is procured. Consequently, once this last message ID has been reached, the creation ensues to its completion.
*(or)*
*(or)*
*(example:)* …

[fix][client] Avert extensive time consumption during table view construction

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTest.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/AbstractWebSocketHandler.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/MultiTopicConsumerHandler.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketMultiTopicConsumerServlet.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketServiceStarter.java
pulsar-websocket/src/main/resources/findbugsExclude.xml
pulsar-websocket/src/test/java/org/apache/pulsar/websocket/AbstractWebSocketHandlerTest.java

[PIP-307](https://github.com/apache/pulsar/pull/21390)
Support subscribing multi/pattern topic for WS.
The new sub-path could be :
```
/ws/v3/consumer/subscription?topicsPattern="a.*" /ws/v3/consumer/subscription?topics="a,b,c"
```

[improve][ws] Support subscribing multi/pattern topic for Websocket

---

build/pulsar_ci_tool.sh
docker/pulsar/Dockerfile
docker/pulsar/pom.xml
tests/docker-images/java-test-image/Dockerfile

- Building the docker image gets stuck very often with the default value of mirror://mirrors.ubuntu.com/mirrors.txt
- change the default value to be the Ubuntu default.
- Extract reusable `ci_find_fast_ubuntu_mirror` shell function for picking the fastest mirror. This can be used in custom builds of Pulsar.

[improve][build] Change UBUNTU_MIRROR default value

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java

Fixes #21469
Fixes #21476
The `__change_events` topic will be owned before the test method starts, so the `testMoreThenOneFilter` and `testCheckOwnershipAsync` might be flaky since the bundle is already owned.
* Use `getBundleIsNotOwnByChangeEventTopic` to get not `__change_events` owns bundle.

[fix][test] Fix ExtensibleLoadManagerImplTest flaky test

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionConsumeTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java

Now, only the last chunk will be acknowledged when acknowledging chunk messages with transactions.
If the messageId is a `ChunkMessageIdImpl`, the ledger ID and entry ID will belong to the `lastChunkMsgId`.
https://github.com/apache/pulsar/blob/2b5c199053a5b2d7f849e6604d619bae9197a8c9/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L2791-L2814
https://github.com/apache/pulsar/blob/2b5c199053a5b2d7f849e6604d619bae9197a8c9/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ChunkMessageIdImpl.java#L30-L33
Flow the common message acknowledge logic, ack all the chunks when acknowledging messages with transactions.
*(or)*
This change is …

[fix][txn] Ack all message ids when ack chunk messages with transaction.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceUnloadingTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolTest.java

PR https://github.com/apache/pulsar/pull/21231 made user topic creation rely on system topic `__change_event` if the user is enabling `topicLevelPoliciesEnabled`.
It will introduce a race condition with namespace bundle unloading. All creating topics want to create `__change_event` reader but constantly fail by namespace-bundle inactive and retry mechanism. Unfortunately, the namespace-bundle unloading operation is waiting for all the topics to be completed and then release inactive status. Therefore, they will be stuck in a deadlock until one gets a timeout.
- Get the topic policy before loading.

[fix][broker] Fix namespace bundle stuck in unloading status

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryShutdownTest.java
pulsar-broker-auth-sasl/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderSasl.java
pulsar-broker-auth-sasl/src/test/java/org/apache/pulsar/broker/authentication/SaslAuthenticateTest.java
pulsar-broker-common/src/test/java/org/apache/pulsar/jetty/tls/JettySslContextFactoryTest.java
pulsar-broker-common/src/test/java/org/apache/pulsar/jetty/tls/JettySslContextFactoryWithKeyStoreTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageTest.java
pulsar-client-auth-sasl/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationSasl.java
pulsar-common/src/main/java/org/apache/pulsar/common/sasl/TGTRefreshThread.java
pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceRunnableTest.java
pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/windowing/WaterMarkEventGeneratorTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionRuntimeManagerTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/MembershipManagerTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClientTest.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java
pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceProducerTest.java
pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/MLTransactionMetadataStoreTest.java
pulsar-websocket/src/test/java/org/apache/pulsar/websocket/PingPongSupportTest.java
tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java
tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/FileStoreTestBase.java
tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloaderTest.java

There are thread leaks in tests reported by the thread leak detection added in #21450.
Fix multiple thread leaks in unit tests.

[fix][test] Fix multiple thread leaks in tests, part 3

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java

Fix create a topic with different auto creation strategies causes race conditions.
the problem happened steps are as follows:
(1) Two clients
- consumer
- admin
(2) Admin call `getSubscritpions` and then call broker internal `getTopicIfExists` method.
(3) `getTopicIfExists` method will put a future to `topics` map and then try to open the managed ledger.
(4) Consumer subscription requests get this future from the `topics` map and then wait for the future result.
(5) The topic does not exist. so, it will complete the future with an empty optional object and then trigger the callback.
(6) Callback to admin requests to return a 404 HTTP code.
(7) Callback to consumer subscription requests to return a topic does not exist exception.
But this broker has an auto-creation configuration, so, it …

[fix][broker] Fix create topic with different auto creation strategies causes race condition

---

pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java
pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMappingTest.java

Fixes #21480
Fix the deadlock when using `BookieRackAffinityMapping` with rackaware policy.
This is a race condition here and executing the following two operations in parallel may trigger the deadlock:
* Using set-bookie-rack to update rack config
* New bookie added
The deadlock is caused by aquiring two locks with different order. Calling `rackawarePolicy.onBookieRackChange()` without locking `BookieRackAffinityMapping` can prevent deadlock from happening.
Remove the locking may let BookieRackAffinityMapping and Rackaware Policy out of consistency in a very short period of time, but I think it is acceptable:
* Bookie rack config update should be low frequency
* If wrong placement occurs, it should be fixed by autorecovery eventually 
This change added a test and can be verified as …

[fix][broker] Fix the deadlock when using BookieRackAffinityMapping with rackaware policy

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java

#7131 introduced an unfinished callback.
- Complete the callback with an exception to let the user retry.

[fix][ml] Fix unfinished callback when deleting managed ledger

---

pulsar-broker/src/test/java/org/apache/bookkeeper/mledger/impl/MangedLedgerInterceptorImpl2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionLocalRunTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/TestPulsarFunctionUtils.java
pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarBatchSourceE2ETest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionE2ETest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarSinkE2ETest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarSourceE2ETest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyKeyStoreTlsWithAuthTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyKeyStoreTlsWithoutAuthTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTlsWithAuthTest.java

It seems some test cases like `**/*Test2.java` aren't run on the default test lifecycle.
This issue is caused by https://github.com/apache/pulsar/pull/10148 .
This issue was fixed by changing test file name as follows. However, some developers committed unexpected file name after them.
* https://github.com/apache/pulsar/pull/13644
* https://github.com/apache/pulsar/pull/17767
* Rename files as expected in config
PR in forked repository: https://github.com/equanz/pulsar/pull/3

[fix][test] Fix that some test cases are not running as expected on CI

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedProducerImpl.java

Fixes https://github.com/apache/pulsar/issues/21484
We will encounter an error log 'Auto getting partitions failed' when expend partition.
When null is returned in method `thenCompose` we will encounter an NPE exception. Because the returned value will be applied to the next stage.
We use `future` instead of `null` as the return value.

[fix][client] Fix print error log 'Auto getting partitions failed' when expend partition.

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java

When an ML tries to create a new ledger, it will create a delay task to check if the ledger create request is timeout<sup>[1]</sup>.
However, we should cancel this delay task after the request to create new ledgers is finished. Otherwise, these tasks will cost unnecessary CPU resources<sup>[2]</sup>.
**[1]**: https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L4070-L4082
```java
bookKeeper.asyncCreateLedger(config.getEnsembleSize(), config.getWriteQuorumSize(), config.getAckQuorumSize(), digestType, config.getPassword(), cb, ledgerCreated, finalMetadata);
scheduledExecutor.schedule(() -> {
if (!ledgerCreated.get()) {
cb.createComplete(BKException.Code.TimeoutException, null, ledgerCreated);
}
}, …
```

[fix] [ml] Fix orphan scheduled task for ledger create timeout check

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/OrphanPersistentTopicTest.java
testmocks/src/main/java/org/apache/zookeeper/MockZooKeeper.java

In the current implementation, the Broker just removes `topicFuture` from the mapping `BrokerService.topics` and never closes it<sup>[1]<sup>. 
The orphan topics will be depended on by `SystemTopicBasedTopicPoliciesService.listeners`, which is for notice of topic policy changes. This issue would cause OOM<sup>[2]</sup>.
**[1]**: https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1725-L1748
```java
...
persistentTopic.stopReplProducers().whenCompleteAsync((v, exception) -> {
topics.remove(topic, topicFuture);
}, executor());
}).exceptionally((ex) -> {
...
persistentTopic.stopReplProducers().whenCompleteAsync((v, exception) -> {
topics.remove(topic, topicFuture);
topicFuture.completeExceptionally(ex);
}, executor()); …
```

[fix] [broker] Fix thousands orphan PersistentTopic caused OOM

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java

Fixes #21506
fix  setReplicatedSubscriptionStatus Incorrect behavior, when unenable enableReplicatedSubscriptions.
when unenable enableReplicatedSubscriptions, set replicatedSubscription status  to ture, should throw an exception.
*(or)*
*(or)*
*(example:)*

[fix][broker] Fix setReplicatedSubscriptionStatus incorrect behavior

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/BrokerInterceptorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/CounterBrokerInterceptor.java

In `BrokerInterceptorTest.java`, we directly set `CounterBrokerInterceptor` as the broker interceptor, which is different from the loading mechanism of the production broker. The production broker uses the `BrokerInterceptors` to load multiple broker interceptors. When we didn't override the intercept method in `BrokerInterceptors`, this test case still passed.
The following is the process of the broker calls a custom interceptor:
`BrokerInterceptors` -> `BrokerInterceptorWithClassLoader` -> `MyBrokerInterceptor`
- Use `BrokerInterceptors` to load `CounterBrokerInterceptor` in `BrokerInterceptorTest.java`
- Fix Assertions in `testMessagePublishAndProduced`

[improve][test] Use BrokerInterceptors to load CounterBrokerInterceptor

---

pip/pip-318.md

Motivation & Modifications
Start a PIP: Don't retain null-key messages during topic compaction

[improve][pip] PIP-318: Don't retain null-key messages during topic compaction

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceUnloadingTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolTest.java

Cherry-pick #21445 to branch-2.10

[fix][broker] Fix namespace bundle stuck in unloading status (#21445)

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImplTest.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationController.java

Fix the `resource_quota_zpath` in `LoadSimulationController` and `ModularLoadManagerImpl`.
As we can see from the `BundlesQuotas`(line30) that the `resource_quota_zpath` should be `/loadbalance/resource-quota`, not `/loadbalance/resource-quota/namespace`. so here we fix it.
https://github.com/apache/pulsar/blob/e55de39e358e18a72b4156c7cd4ac4831a573864/pulsar-broker/src/main/java/org/apache/pulsar/broker/cache/BundlesQuotas.java#L30-L32
Fix resource_quota_zpath
https://github.com/AnonHxy/pulsar/pull/47

[fix][broker] Fix resource_quota_zpath

---

conf/broker.conf
conf/standalone.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java

PIP: #21541 
Implement #21541 
* Add config `topicCompactionRemainNullKey` in the broker.conf, the default value is false.
* If not retaining null-key message, add an empty single message placeholder to result when rebatching the message.
* If the message with null-key, then add a null-key value to the result list of extractIdsAndKeysAndSize and record the delete event.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after broker …

[improve][broker][PIP-318] Support not retaining null-key message during topic compaction

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedProducerImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java

an NPE exception is generated when the method return null
Add related test for #21485 
Fixes  #21559 
Add a unit test to detect if an empty object is returned
The OnTopicsExtended method might return an empty object, which is not allowed,
Because the returned value will be applied to the next stage.
We use future instead of null as the return value.
The test shows that we are not returning an empty object

[fix][test] Detects whether an empty object is returned, prevent NPE exception

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/BucketDelayedDeliveryTrackerFactory.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/BucketDelayedDeliveryTest.java

**Background:**
- `BucketDelayedDeliveryTrackerFactory` was added with [PIP-195: New bucket based delayed message tracker](https://github.com/apache/pulsar/issues/16763)
-  `BucketDelayedDeliveryTrackerFactory` will be initialized if setting config `setDelayedDeliveryTrackerFactoryClassName` to `BucketDelayedDeliveryTrackerFactory`
- Pulsar will delete the delay message indexes bucket when a subscription is unsubscribing.
**Issue:**
There is an NPE that causes the Future of Delay message indexes bucket deletion to be no longer complete, which leads to the topic deletion timeout. You can reproduce this issue by the test `testDeletePartitionedTopicIfCursorPropsEmpty` and `testDeleteTopicIfCursorPropsEmpty`
**Issue logs:**
```
2023-11-16T17:53:00,154+0000 [delayer-53-1] WARN …
```

[fix] [broker] Delete topic timeout due to NPE

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java

Fixes #21441
Related PR: https://github.com/apache/pulsar/pull/21507
Add producerName for dead letter producer, easier to locate problems.
```java
.producerName(String.format("%s-%s-DLQ", this.topicName, this.subscription))
```
When creating a `deadLetterProducer`, specify the `producerName` to replace the randomly generated name.
PR in forked repository: https://github.com/crossoverJie/pulsar/pull/16

[improve] [client] Add producerName for deadLetterProducer

---

conf/broker.conf
conf/standalone.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java

PIP: #21541
Cherry-pick #21578 into branch-3.1 with `topicCompactionRemainNullKey=true` default.

[improve][broker][branch-3.1] Support not retaining null-key message during topic compaction (#21578)

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java

Main Issue: #21603 
The root cause is `timeSinceLedgerCreationMs` > `minimumRolloverTimeMs` and the ledger is not rollover
see:
https://github.com/apache/pulsar/blob/d1b7d0b7d86a7a8883407d3dc054bb8e21f96d60/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L3809-L3836
log:
```
2023-11-22T15:53:43,503 - INFO  - [test-OrderedScheduler-0-0:ManagedLedgerImpl@1574] - [test_managedLedger_rollOver] Created new ledger 4
2023-11-22T15:53:43,510 - INFO  - [test-OrderedScheduler-0-0:ManagedLedgerImpl@3826] - Diff: 1, threshold: 1 -- switch: false
2023-11-22T15:53:43,512 - INFO  - [test-OrderedScheduler-0-0:ManagedLedgerImpl@3826] - Diff: 3, threshold: 1 -- switch: true
2023-11-22T15:53:43,514 - INFO  - [test-OrderedScheduler-0-0:OpAddEntry@245] - …
```

[fix][test] Fix flaky test ManagedLedgerTest#testManagedLedgerRollOverIfFull

---

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java

If I run the command `bin/pulsar-perf produce my-topic -time 5`, it returns a `java.lang.InterruptedException` before it exits.
The reason is that `doneLatch`  will be zero before `sleep(5000)`, and the main thread exits 0 when `doneLatch<=0`, so the `pulsar-perf-producer-exec` thread pool will be terminated and has a chance to throw an `InterruptedException` if it starts to run `sleep(5000)`.
https://github.com/apache/pulsar/blob/d1b7d0b7d86a7a8883407d3dc054bb8e21f96d60/pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java#L583-L584
https://github.com/apache/pulsar/blob/d1b7d0b7d86a7a8883407d3dc054bb8e21f96d60/pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java#L381-L390 …

[improve][client] Ignore InterruptedException when pulsar-perf finishing

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicMessageImpl.java

[PIP-224](https://github.com/apache/pulsar/pull/19158) introduces a breaking change for the  API `getTopicName` of `TopicMessageImpl`. 
Originally, the return value of `getTopicName`  did not carry partition information. 
https://github.com/apache/pulsar/blob/d37b8ea80e6a0206699cc4313e118217b3eeecab/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L304-L308
After introducing this proposal, it carried partition information and the `getTopicPartitionName` was deprecated.
https://github.com/apache/pulsar/blob/2a5aa44338f334afa6c9b9d4918bf031f40c83b2/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L292-L295
https://github.com/apache/pulsar/blob/2a5aa44338f334afa6c9b9d4918bf031f40c83b2/pulsar-client/src/main/java/org/a …

[cleanup][client] Fix inconsistent API annotations of `getTopicName`

---

distribution/server/pom.xml
distribution/server/src/assemble/LICENSE.bin.txt
managed-ledger/pom.xml
pom.xml
pulsar-sql/presto-distribution/LICENSE

owasp-dependency-check failed due to [CVE-2023-46120](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-46120).
All the releases between 5.5.3 and 5.18.0 are maintenance releases with usability improvement, bug fixes, and dependency upgrades. All users are encouraged to upgrade.
Release notes: 
https://github.com/rabbitmq/rabbitmq-java-client/releases?page=3
Upgrade rabbitmq client to 5.18.0.
*(or)*
*(or)*
*(example:)*
- *Extended integration …

[fix][sec] Upgrade rabbitmq client to address CVE-2023-46120

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TransactionsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiGetLastMessageIdTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/AdminApiTransactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerDisallowAutoCreateTopicTest.java

When I did this test below and got the error "Topic not found".
```java
pulsarAdmin.topics().createNonPartitionedTopic("persistent://public/default/tp_1");
Consumer consumer = null;
Consumer consumer = pulsarClient.newConsumer()
.topic("persistent://public/default/tp_1")
.subscriptionName("s1")
.enableRetry(true)
.subscribe();
```
I do create the topic `persistent://public/default/tp_1` first but got a response "Topic not found", it is confusing. 
The root cause is the retry letter topic `persistent://public/default/tp_1-sub1-RETRY` was not created. 
clear the vague response if the topic is not founded.

[fix] [log] fix the vague response if topic not found

---

pulsar-broker/src/test/java/org/apache/pulsar/security/tls/MockedPulsarStandalone.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/keystoretls/KeyStoreSSLContext.java

The current default behavior of Netty and Jetty's SSLContext implementation is that the server will request the client certificate, and the client can optionally pass it on.
[Netty SSL Context](https://github.com/apache/pulsar/blob/e1d06b5f54f08c09debab7a9a513b7c173c1779b/pulsar-common/src/main/java/org/apache/pulsar/common/util/SecurityUtility.java#L575) 
[Jetty SSL Context](https://github.com/apache/pulsar/blob/e1d06b5f54f08c09debab7a9a513b7c173c1779b/pulsar-broker-common/src/main/java/org/apache/pulsar/jetty/tls/JettySslContextFactory.java#L106)
But the implementation of keystore is inconsistent. It will lead the server not to request the client certificate and can not do authentication without `tlsRequireTrustedClientCertOnConnect` configuration.
- set `sslEngine.setWantClientAuth` …

[improve][sec] Align the default mechanism for server to request certificates

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/SchemaServiceTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpLookupService.java
pulsar-common/src/main/java/org/apache/pulsar/client/impl/schema/SchemaUtils.java

[fix][broker] Fixed getting incorrect KeyValue schema version

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerStatTest.java

Fixes #21614 
The root cause is that we can't keep the order of the msgs from the partitioned topic. We just keep the order of the msg in single partition.

[fix][test] Fix flaky test SimpleProducerConsumerStatTest#testPartitionTopicStats

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/SchemaServiceTest.java

[fix][admin] Fix KeyValue schema compatibility check caused OOM

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java

Fixes #21568
Fix incorrect unack count when using shared subscription on non-persistent topic
In the case of a non-persistent topic, the consumer does not send an ack to the broker (see `org.apache.pulsar.client.impl.NonPersistentAcknowledgmentGroupingTracker# addAcknowledgment`)
To work around this, we can update `unackedMessages` when the broker sends a message to the consumer successfully.
https://github.com/1Jack2/pulsar/pull/5

[fix][broker] Fix incorrect unack count when using shared subscription on non-persistent topic

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/GetStatsOptions.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java

PIP: https://github.com/apache/pulsar/pull/21228 
https://github.com/crossoverJie/pulsar/blob/c97cdf3d535e90cb725cbf6016cc8ecc2570ce9a/pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java#L1050-L1130
PR in forked repository: https://github.com/crossoverJie/pulsar/pull/17

[improve][broker] Add optional parameters for getPartitionedStats

---

pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/StrategicCompactionTest.java

Fixes #21537
Because of https://github.com/apache/pulsar/issues/21536 . The consumer with the subscription name `__compaction` can not reconnect. Therefore, the compaction task triggered before the topic unload fails. In this case, a compaction task can be triggered again after unload.
After unload the topic, make sure that the topic has been initialized correctly. Then trigger compaction again after previous task failed.
*(or)*
*(or)*
*(example:)*
- …

[fix][test] Fix the bug caused by unload topic and compaction task failure after task is triggered

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java

Add clusters check logic when set namespace/topic replication clusters.

[improve][admin] Add clusters check when set replication clusters

---

pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java

Found the following error log in  `CompactionTest.testCompactionDuplicate`:
```java
2023-11-30T12:48:53,002 - ERROR - [pulsar-client-io-692-4:ResourceLeakDetector@337] - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
io.netty.buffer.AdvancedLeakAwareByteBuf.readByte(AdvancedLeakAwareByteBuf.java:401)
org.apache.pulsar.common.api.proto.LightProtoCodec.readVarInt(LightProtoCodec.java:140)
org.apache.pulsar.common.api.proto.MessageMetadata.parseFrom(MessageMetadata.java:1315)
org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:459)
org.apache.pulsar.common.protocol.Commands.parseMessageMetadata(Commands.java:446) …
```

[fix][broker] Fix memory leak during topic compaction

---

pom.xml

Fixes https://github.com/apache/pulsar/issues/21658
Fixes https://github.com/apache/pulsar/issues/21658
We could find the similar issue from here : https://github.com/IQSS/dataverse/issues/9771 .  And we could fix this issuse by  
updating the `fabric8` to `0.43.3`
bump io.fabric8 docker-maven-plugin to `0.43.3`

[fix][build] Fix Stage Docker images fail on M1 Mac

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java

In https://github.com/apache/pulsar/pull/21595, we lost the recoverBucketSnapshot log.
Print recoverBucketSnapshot log if cursorProperties are empty.

[improve][broker] Print recoverBucketSnapshot log if cursorProperties are empty

---

conf/bookkeeper.conf
conf/broker.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java

Fixes #xyz
PIP: #xyz 
If one ledger's ensemble is [bk0, bk1] and bk0 is down, the bookie client may send a read request to bk0 first then fail with the following errors, and resend the read request to bk1 in the end. 
```
2023-10-19T18:33:52,042 - ERROR - [BookKeeperClientWorker-OrderedExecutor-3-0:PerChannelBookieClient@563] - Cannot connect to 192.168.31.216:3181 as endpoint resolution failed (probably bookie is down) err org.apache.bookkeeper.proto.BookieAddressResolver$BookieIdNotResolvedException: Cannot resolve bookieId 192.168.31.216:3181, bookie does not exist or it is not running
2023-10-19T18:33:52,042 - INFO  - [BookKeeperClientWorker-OrderedExecutor-3-0:DefaultBookieAddressResolver@77] - Cannot resolve 192.168.31.216:3181, bookie is unknown …
```

[improve] [bookie] Enable reorder read sequence for bk client by default

---

conf/broker.conf
conf/standalone.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java

Cherry-pick #21578 into branch-3.0

[improve][broker] Support not retaining null-key message during topic compaction (#21578)

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/LoadBalanceResources.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/cache/BundlesQuotas.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/cache/BundlesQuotasTest.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationController.java

See pip: https://github.com/apache/pulsar/pull/21129
Add  `QuotaResources`
https://github.com/AnonHxy/pulsar/pull/48

[refactor][broker] PIP-301 Part-3: Add QuotaResources

---

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java

If there's no message to consume, the listener won't be invoked, so the main thread will still run in the loop even if time reaches the limit. 
PR in forked repository: https://github.com/yaalsn/pulsar/pull/4

[fix][client] Exit when no msg to consume if time reaches the limit

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/lookup/http/HttpTopicLookupv2Test.java

Fixes: #21661
PIP: #21646 
Function internalLookupTopicAsync is invoked by http protocol topic lookup request. The lookupRequestSemaphore would leaked when lookuping topic is not exist.
Now use a unit test to see if it is actually released
Add a unit test to simulate this process, and the state should be the same

[fix][test] add unit test to testing the lookupRequestSemaphore would leaked when lookuping topic is not exist.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdClusters.java
pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdClusters.java

#21359 forget to add `get-cluster-migration` cmd . And also make `getClusterMigration` async

[fix][cli] Add `get-cluster-migration` cmd

---

docker/pulsar/Dockerfile
tests/docker-images/java-test-image/Dockerfile
tests/docker-images/latest-version-image/Dockerfile

Currently, the user pulsar is in the root group, it would be better to use the non-root group to keep more safety. 
- Add group pulsar (GID 10000) 
- Add user pulsar (UID 10000) to group pulsar

[improve][sec] Add group pulsar and add user pulsar to it instead of root

---

conf/broker.conf
conf/standalone.conf
pip/pip-318.md
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java

https://github.com/apache/pulsar/pull/21578#discussion_r1416731165
Since we haven't had a release since #21578 merged, so we can just fix it.
`topicCompactionRemainNullKey` -> `topicCompactionRetainNullKey`.

[fix][broker] Fix typo in the config key

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/GeoPersistentReplicator.java

`GeoPersistentReplicator.msgOut` metric records the message output data from the local cluster to the remote cluster. Right now, this metric has been updated before getting the shema. If it fails,  we don't send the message to the remote cluster, so I don't think the metric should be updated.
`GeoPersistentReplicator.msgOut` should be recorded before `producer#sendAsync`.
Move `msgOut.recordEvent(headersAndPayload.readableBytes());` before `producer#sendAync`.

[fix][broker] Record GeoPersistentReplicator.msgOut before producer#sendAsync

---

pulsar-client-messagecrypto-bc/src/main/java/org/apache/pulsar/client/impl/crypto/MessageCryptoBc.java

Fix typos in doc for MessageCryptoBc class
`retruns` => `returns`

[fix][doc] Fix typos in doc for MessageCryptoBc class

---

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/LeaderService.java

Fixes #21501
No need to `synchronized` the method `isLeader` in LeaderService
See the deadlock stack :
```
"pulsar-external-listener-44525-1":
at org.apache.pulsar.functions.worker.FunctionMetaDataManager.giveupLeadership(FunctionMetaDataManager.java)
- waiting to lock <0x0000100013535c90> (a org.apache.pulsar.functions.worker.FunctionMetaDataManager)
at org.apache.pulsar.functions.worker.LeaderService.becameInactive(LeaderService.java:167)
- locked <0x000010001344c6d8> (a org.apache.pulsar.functions.worker.LeaderService)
at org.apache.pulsar.client.impl.ConsumerImpl.lambda$activeConsumerChanged$27(ConsumerImpl.java:1136)
at org.apache.pulsar.client.impl.ConsumerImpl$$Lambda$2606/0x00007f854ce9cb10.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.8.1/ …
```

[fix][fn] Fix Deadlock in Functions Worker LeaderService

---

pulsar-io/hdfs2/pom.xml
pulsar-io/hdfs3/pom.xml

Fix [CVE-2023-39410](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-39410).
This issue affects Java applications using Apache Avro Java SDK up to and including 1.11.2
```
org.apache.pulsar:pulsar-io-hdfs3:jar:3.2.0-SNAPSHOT
\- org.apache.hadoop:hadoop-client:jar:3.3.5:compile
\- org.apache.hadoop:hadoop-common:jar:3.3.5:compile
\- org.apache.avro:avro:jar:1.7.7:compile
```
Exclude `Avro` from `Hadoop-client`.
*(or)*
*(or)*
*(example:)*
- …

[fix][sec] Exclude avro from hadoop-client

---

pip/pip-320.md
pip/pip-xxx.md

Adding PIP-320, which a sub-PIP of PIP-264 (Implementation tracked at #21121).
This PIP is about adding the infrastructure to use OpenTelemetry in Pulsar broker, proxy and function worker.

[improve][pip] PIP-320: OpenTelemetry Scaffolding

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdTopics.java

PIP: https://github.com/apache/pulsar/issues/20225
The current implementation of the `DeleteCmd` class in the Pulsar CLI does not provide the flexibility to delete multiple topics at once using a regex or a file containing a list of topics. This can be inconvenient and time-consuming in environments where there are many topics that need to be deleted. 
To address this, we have added three new parameters to the `DeleteCmd` class:
1. `-r` or `regex`: This parameter allows the user to specify a regex to match multiple topics for deletion.
2. `--from-file`: This parameter allows the user to read a list of topics from a file for deletion.
Additionally, we have written unit tests to ensure the correct behavior of these new features. These tests cover the deletion of a single topic, multiple …

[improve][cli]Introduce Regex and File Input Parameters for Enhanced Topic Deletion Command

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java

There is a regression in the previous PR, https://github.com/apache/pulsar/pull/21213/files#r1425693449.
We should tombstone only inactive bundle states by the bundle state channel monitor thread. Currently, active bundle states(including the `Owned` state) are tombstoned(cleaned), which incurs new bundle assignments. 
This change is already covered by existing tests. Please refer to the test changes in the PR.

[fix][broker] Fixed ServiceUnitStateChannel monitor to tombstone only inactive bundle states

---

pip/pip-322.md

This contains PIP-322: Pulsar Rate Limiting Refactoring. Check the [pip-322.md](https://github.com/lhotari/pulsar/blob/lh-ratelimiter-refactoring-pip/pip/pip-322.md) document for details.

[improve][pip] PIP-322: Pulsar Rate Limiting Refactoring

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

Fixes #21653 
Reproduce process:
https://github.com/apache/pulsar/issues/21653#issuecomment-1842962452
The `registerTopicPolicyListener()` function was moved from `PersistentTopic()` to `initTopicPolicy()`.
Flow diagram:
Current:
After:
PR in forked repository: https://github.com/crossoverJie/pulsar/pull/19

[fix][broker] Fix the issue of topics possibly being deleted.

---

docker/pulsar/Dockerfile
tests/docker-images/java-test-image/Dockerfile

java-test-image docker image build fails fairly often
```
[INFO] DOCKER> Err:30 https://packages.adoptium.net/artifactory/deb jammy/main amd64 temurin-17-jdk amd64 17.0.9.0.0+9
403  Forbidden [IP: 146.75.31.42 443]
[INFO] DOCKER> Fetched 6128 kB in 0s (15.7 MB/s)
[INFO] DOCKER> [91mE: Failed to fetch https://packages.adoptium.net/artifactory/deb/pool/main/t/temurin-17/temurin-17-jdk_17.0.9.0.0%2b9_amd64.deb  403  Forbidden [IP: 146.75.31.42 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```
example: https://github.com/apache/pulsar/actions/runs/7194966954/job/19597006556#step:10:10074
- configure https timeout for apt
- copy `/etc/apt/apt.conf.d/99timeout_and_retries` configuration to java-test-image

[improve][build] Configure https timeout for apt, copy config to java-test-image

---

pip/pip_313.md

Fixes https://github.com/apache/pulsar/issues/21451
*(or)*
*(or)*
*(example:)*

[improve][pip] PIP-313 Support force unsubscribe using consumer api

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java

Fixes #21712
The consumer should receive 10 msgs, but received is less than 10.
Add some logs and find that the received time is short, so increase the received time.
```
2023-12-12T14:47:47,632 - INFO  - [PulsarTestContext-executor-OrderedExecutor-0-0:Slf4jRequestLogWriter@62] - 127.0.0.1 - - [12/Dec/2023:14:47:47 +0800] "POST /admin/v2/persistent/prop/ns-abc/topicbd6c9c99-226e-4ff7-8c7c-e66af068aebc/subscription/sub/analyzeBacklog HTTP/1.1" 200 256 "-" "Pulsar-Java-v3.2.0-SNAPSHOT" 13
2023-12-12T14:47:47,634 - INFO  - [main:FilterEntryTest@261] - received : 3:0:-1
2023-12-12T14:47:47,675 - INFO  - [PulsarTestContext-executor-OrderedExecutor-0-0:PulsarMockBookKeeper@123] - Creating ledger 5
2023-12-12T14:47:47,676 - INFO  - [main:FilterEntryTest@261] - received : 3:1:-1 …
```

[fix][test] Fix flaky test FilterEntryTest.testFilter

---

pulsar-io/alluxio/pom.xml

Upgrade to Netty 4.1.103.Final fails with errors in pulsar-io/alluxio (see comments in #21723). Prepare for the upgrade by pinning the Netty version in pulsar-io/alluxio.
- Use dependencyManagement to pin versions
- Use 4.1.100.Final since it should be compatible

[improve][misc] Pin Netty version in pulsar-io/alluxio

---

docker/pulsar/Dockerfile
tests/docker-images/java-test-image/Dockerfile

Creating docker images continue to fail with network errors. #21724 didn't resolve the issues.
apt's initial timeout is 250ms and then 30 seconds by default. The initial 250ms timeout is too short and could be causing problems. 
Logic:
https://salsa.debian.org/apt-team/apt/-/blob/c555d8f1ae31d1f511bf811640423231b75a8e13/methods/connect.cc#L457-464
Set ConnectionAttemptDelayMsec to 2000
Increase Retries to 15

[improve][build] Increase apt's initial timeout from 250ms to 2000ms and increase retries

---

pom.xml

The currently used version of `org.bouncycastle:bc-fips` has the following vulnerability and should be upgraded to 1.0.2.4.
https://github.com/bcgit/bc-java/wiki/CVE-2022-45146
https://nvd.nist.gov/vuln/detail/CVE-2022-45146

[fix][sec] Upgrade org.bouncycastle:bc-fips to 1.0.2.4

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceAutoTopicCreationTest.java

For our load data system topics such as, `non-persistent://pulsar/system/loadbalancer-broker-load-data`, `allowAutoTopicCreationType=partitioned` causes other broker's producer creation to incorrectly create a new partitioned topic (although we pre-create the system topics as non-partitioned topics). Because of this, the leader broker cannot collect all brokers' load data as the other brokers publish the load data in different topics(partitioned topics).
Producer creation first fetches the partitionMedatadata from the broker, and when fetching this partitionMedatadata, brokers automatically create a new one with the conditions like the below code. The problem is that the broker serving `handlePartitionMetadataRequest` might not be the owner broker (I don't see `checkBundleOwnership` in …

[fix][broker] Skip topic auto-creation for ExtensibleLoadManager internal topics

---

buildtools/pom.xml
distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

Keep Netty and Netty's io_uring libraries up-to-date. 
Release notes since last upgrades:
- https://netty.io/news/2023/12/15/4-1-104-Final.html
- https://netty.io/news/2023/12/13/4-1-103-Final.html
- https://netty.io/news/2023/11/09/4-1-101-Final.html
- https://netty.io/news/2023/11/17/io_uring_0-0-24-Final.html
- https://netty.io/news/2023/10/02/multiple_releases_incubator.html
- Upgrade Netty to 4.1.104.Final (from 4.1.100.Final)
- Upgrade Netty io_uring to 0.0.24.Final (from 0.0.21.Final)

[improve][misc] Upgrade Netty to 4.1.104 and io_uring to 0.0.24

---

pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchExtractTests.java
pulsar-io/rabbitmq/src/test/java/org/apache/pulsar/io/rabbitmq/source/RabbitMQSourceTest.java

[CI - Unit - Pulsar IO - Elastic Search](https://github.com/apache/pulsar/actions/runs/7218881587/job/19669156306#step:16:181)
Summary: Tests in class org.apache.pulsar.io.elasticsearch.ElasticSearchRawRecordTests created 96 new threads. There are now 151 threads in total.

[fix][test] Close the resource after the test.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Subscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
pulsar-common/src/main/proto/PulsarApi.proto

PIP: #21452 
As discussed in Issue: https://github.com/apache/pulsar/issues/21451
Apache Pulsar provides a messaging queue using a Shared subscription to process unordered messages in parallel using multiple connected consumers. Shared subscription is also commonly used in data processing pipelines where they need to forcefully unsubscribe from the subscription after processing messages on the topic. One example is Pulsar-Storm adapter where [Pulsar spout](https://github.com/apache/pulsar/blob/branch-2.4/pulsar-storm/src/main/java/org/apache/pulsar/storm/PulsarSpout.java#L126) creates Pulsar consumers on a shared subscription for distributed processing and then unsubscribe on the topic. 
However, PulsarSpout always fails to unsubscribe shared subscriptions and it also doesn't close the …

[improve][client] PIP-313 Support force unsubscribe using consumer api

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentDispatcherFailoverConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java

Fixes #21754
PersistentTopicTest.setup is flaky.
No need to mock getNamespaceService() method since it's already returning a spy by default.

[fix][test] Fix flaky PersistentTopicTest.setup

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Dispatcher.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SubscriptionMessageDispatchThrottlingTest.java

Fixes #21756
Closing of AbstractDispatcherSingleActiveConsumer should also close the underlying rate limiter. This will leaks resources in rate limiters that hold on resources (before PIP-322 changes, thus relevant to maintenance branches). The SubscriptionMessageDispatchThrottlingTest consistently fails since closing is missing.
In addition to this, reduce flakiness in SubscriptionMessageDispatchThrottlingTest. 
Often the timeouts are too short. There shouldn't be a need to have strict 500 ms timeouts in tests. Remove Awaitility "atMost" timeouts and rely on default (10 secs). Change all test timeouts to 30 seconds in the class.
It looks like PR #21682 changes broke closing in certain cases. That problem is now fixed in this PR.
This impacted …

[fix][broker] Fix closing of AbstractDispatcherSingleActiveConsumer and reduce flakiness of test

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java

If the last message to compact is a marker, then the compaction task will stuck until timeout fails. The root cause is that the marker has been filtered out by the dispatcher, and the compaction reader will not read the last message.
```java
WARN  - [broker-client-shared-internal-executor-18-1:PersistentTopic@3432] - [persistent://tnx/ns-prechecks/test_transaction_topic211ca13d-f8a4-4648-a7b9-bd2f679e0f3b] Compaction failure.
java.util.concurrent.CompletionException: org.apache.pulsar.common.util.FutureUtil$LowOverheadTimeoutException: Timeout
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347) ~[?:?]
at …
```

[fix][broker] Avoid compaction task stuck when the last message to compact is a marker

---

conf/proxy.conf
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java

The solution added in #21031 was modified in #21428, but the comment wasn't updated to reflect the change.
Update the comment about enableProxyStatsEndpoints

[improve][proxy] Fix comment about enableProxyStatsEndpoints

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthenticatedProducerConsumerTest.java

fix unittest testCleanupEmptySubscriptionAuthenticationMap. getTlsFileForClient method not exist in branch-3.0

[fix][test][branch-3.0] fix  testCleanupEmptySubscriptionAuthenticationMap

---

pip/pip-323.md

PIP-323 is introduced to fill the gap of backlog quota telemetry. It allows the user to know when a time-based backlog quota is about to exceed, and how many times it exceeded. It also adds backlog quota check duration metric allowing the user to configure the interval for that check based on data. Once this is implemented, the user can finally create and alert to know when a certain topic is about to exceed its defined backlog quota limit, alert on it, and using topic stats Admin API to grab the subscription name causing it.
Adding PIP-323

[improve][pip] PIP-323: Complete Backlog Quota Telemetry

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStore.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/TableViewLoadDataStoreImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerFilterTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeightTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java

After this fix, https://github.com/apache/pulsar/pull/21729, we need to recreate the non-persistent internal system topics when the leadership changes because we disabled the auto-creation of the non-persistent internal system topics. 
Also, the non-persistent consumers and producers might be in a closed state, as they could receive `TopicNotFoundException` when the new leader broker has not created the internal topics yet. To cover this case, we need to update the leader and follower role change logic to be more idempotent.
- Make the new leader always try to create internal non-persistent system topics.
- Init the load data stores whenever the leader broker has changed.
ExtensibleLoadManager.testIsolationPolicy test was flaky because of the this issue. …

[fix][broker] Fixed the ExtensibleLoadManagerImpl internal system getTopic failure when the leadership changes

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

Fixes #21768
See #21768 . PersistentTopicsTest is flaky because of the invalid reuse of AsyncResponse mocks.
- don't reuse AsyncResponse mocks.

[fix][test] Don't reuse AsyncResponse mocks in PersistentTopicsTest

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/MessageDuplicationTest.java

Fixes #21192
Short alive producer (create, send message, close) will create a lot record in deduplication inactiveproducers.
even there is clear logic but default interval is too long and is broker level.
if deduplication is disabled do not record producer in inactive producers.

[improve][broker] Avoid record inactiveproducers when deduplication is disable.

---

pip/pip-282.md

[improve][pip] PIP-282: Change definition of the recently joined consumers position

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/TableViewLoadDataStoreImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreTest.java

```
2023-12-21T06:06:15,824+0000 [broker-client-shared-internal-executor-5-1] ERROR org.apache.pulsar.broker.loadbalance.extensions.channel.StateChangeListeners - StateChangeListener: org.apache.pulsar.broker.loadbalance.extensions.reporter.BrokerLoadDataReporter@6ad7c72 exception while handling ServiceUnitStateData[state=Owned, dstBroker=pulsar-broker-1:8080, sourceBroker=pulsar-broker-2:8080, splitServiceUnitToDestBroker=null, force=true, timestamp=1703138775734, versionId=3] for service unit my-tenant/my-namespace/0x66666640_0x68f5c268
java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.api.Producer.newMessage()" because "this.producer" is null
at org.apache.pulsar.broker.loadbalance.extensions.store.TableViewLoadDataStoreImpl.removeAsync(TableViewLoadDataStoreImpl.j …
```

[fix][broker] Fix TableViewLoadDataStoreImpl NPE

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerMemoryLimitTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MemoryLimitController.java

When the modification of the current PR is rolled back, the following unit test will fail, and the main producer thread will be stuck forever in org.apache.pulsar.client.impl.MemoryLimitController#reserveMemory condition.await();
```java
@Test(timeOut = 10_000)
public void testProducerBlockReserveMemory() throws Exception {
replacePulsarClient(PulsarClient.builder().
serviceUrl(lookupUrl.toString())
.memoryLimit(1, SizeUnit.KILO_BYTES));
@Cleanup
ProducerImpl<byte[]> producer = (ProducerImpl<byte[]>) pulsarClient.newProducer()
.topic("testProducerMemoryLimit")
.sendTimeout(5, TimeUnit.SECONDS)
.compressionType(CompressionType.SNAPPY)
.messageRoutingMode(MessageRoutingMode.RoundRobinPartition)
.maxPendingMessages(0)
.blockIfQueueFull(true)
.enableBatching(true)
.batchingMaxMessages(100) …
```

[fix][client] Fix producer thread block forever on memory limit controller

---

doap_Pulsar.rdf

To be properly listed on the projects.apache.org, the project must have a DOAP file. More info: https://projects.apache.org/create.html
Fixes #xyz
PIP: #xyz 
The project has an entry here:
https://projects.apache.org/projects.html?name
but hasn't here: https://projects.apache.org/projects.html?language
and here: https://projects.apache.org/projects.html?category
@lhotari explained to me how to fix that here: https://lists.apache.org/thread/1q90j40vv6fb729fwlmc9npd6y2ws529
*(or)*
*(or)*
*(example:)*
- *Added …

[improve][misc] List Pulsar at the https://projects.apache.org

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MemoryLimitController.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/MemoryLimitControllerTest.java

**Context** : The previous PR is https://github.com/apache/pulsar/pull/21790
**Background of MemoryLimitController**
- When there is not enough memory to use, the method `MemoryLimitController.reserveMemory` will stuck until some memory is released<sup>[1]</sup>.
- After calling `MemoryLimitController.releaseMemory`, it would wake up all stuck threads.
**Issue**
- the method `tryReserveMemory`, `reserveMemory`, `forceReserveMemory` will also release the memory if it accepted a negative value, but it will not wake up the stuck threads. This would cause the stuck threads to remain stuck forever.
- https://github.com/apache/pulsar/pull/17936  used this method incorrectly and caused a Producer stuck bug that fixed by https://github.com/apache/pulsar/pull/21790.
**Make sure that all use cases …

[improve] [client] Prevent reserve memory with a negative memory size to avoid send task stuck

---

tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java

We can’t use the admin client in the integration test because the test is running locally(outside the container). It can’t resolve the hostname. So when the admin receives the redirect response, the admin request will fail because the hostname cannot be resolved.
Example fail logs:
```
2023-12-22T20:53:45,390 - WARN  - [AsyncHttpClient-31-2:BaseResource$1@135] - [http://localhost:53650/admin/v2/persistent/my-tenant/my-namespace/testSplitBundleAdminApi] Failed to perform http put request: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: Connection refused: pulsar-broker-1/198.18.193.132:8080
```
* Use docker cmd execute admin …

[fix][test] Fix ExtensibleLoadManager flaky integration test

---

pom.xml
pulsar-io/debezium/core/pom.xml
pulsar-io/kafka-connect-adaptor/pom.xml
pulsar-io/kafka/pom.xml
pulsar-io/solr/pom.xml

Fixes #21787
We use jose4j for 0.9.3 version, these two versions are existed by dependencies.
```
jose4j-0.6.5.jar: CVE-2023-31582(7.5)
jose4j-0.7.9.jar: CVE-2023-31582(7.5)
```
Exclude jose4j to avoid [CVE-2023-31582](https://nvd.nist.gov/vuln/detail/CVE-2023-31582)

[improve][ci] Exclude jose4j to avoid CVE-2023-31582

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStore.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/TableViewLoadDataStoreImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerFilterTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeightTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java

Cherry-pick #21764 to branch-3.1

[fix][broker] Fixed the ExtensibleLoadManagerImpl internal system getTopic failure when the leadership changes #21764

---

.github/workflows/ci-owasp-dependency-check.yaml
pom.xml
src/owasp-dependency-check-false-positives.xml

OWASP dependency check improvements:
- restore checks for distribution/offloaders and distribution/io which were accidentially removed by #21795
- upgrade OWASP version to keep up-to-date
- add suppression for false positive in jetty-servlets jar
- scan branch-3.2
- remove scanning of EOL branches branch-2.8 and branch-2.9

[improve][ci] Improve OWASP dependency checks

---

.github/workflows/ci-owasp-dependency-check.yaml

Currently the OWASP dependency check won't run for distribution/offloaders and distribution/io (Pulsar IO connectors) when the main distribution's check fails. Example: https://github.com/apache/pulsar/actions/runs/7352401899/job/20017097977
Follow up for #21817.
Add `if: !cancelled()` to run the second step also when the first step fails. ([GitHub Actions docs](https://docs.github.com/en/actions/learn-github-actions/expressions#always))

[improve][ci] Run OWASP dependency check for offloaders and pulsar-io even when main check fails

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerWrapper.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java

When a broker shutdown or gets killed, the leader broker will get notified and soon reassign the orphan bundle ownerships. Meanwhile, the ownership lookup to these orphan bundles should be deferred til the new brokers own them. This will further reduce the lookup request retries when brokers are shutdown or get killed.
- In `ServiceUnitStateChannelImpl.getOwnerAsync`, additionally, check if the current owner broker is active or not in the broker registry. If active, return the current owner. Otherwise, defer the ownership lookup requests til the new owner owns it.
- During the orphan ownership cleanup, when there is no selected owner, the leader overrides the orphan states to `Free`.
- Do not throw exception from `writeLoadReportOnZookeeper` `writeResourceQuotasToZooKeeper`
Added a test …

[improve][broker] defer the ownership checks if the owner is inactive (ExtensibleLoadManager)

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SnapshotSegmentAbortedTxnProcessorImpl.java

Fix the String wrong format  introduced by this PR https://github.com/apache/pulsar/pull/21169
`String.format("xxx {} xxxx", "xxx")` ->  `String.format("xxx %s xxxx", "xxx")`

[fix][broker] Fix String wrong format

---

.github/workflows/ci-owasp-dependency-check.yaml
.github/workflows/pulsar-ci.yaml

- Fix ["Invalid workflow file" error](https://github.com/apache/pulsar/actions/runs/7380947338)
- follow up for #21826
- GHA requires "if: ${{ !cancelled() }}"
- The scan results for offloaders and pulsar-io don't contain any results when the distributions are scanned. It is necessary to scan each individual project. 
- `if: !cancelled()` -> `if: ${{ !cancelled() }}`
- Modify tiered-storage and pulsar-io scanning to scan each individual project.
- Add caching for vulnerability database download

[fix][ci] Fix OWASP dep check GH actions workflow

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml

The errorprone maven profile is currently broken and doesn't work.
- update to work with JDK17
- upgrade errorprone to latest version
use `mvn -Perrorprone,core-modules,-main compile` to run

[fix][build] Fix the errorprone maven profile

---

.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

- upgrade GitHub Actions workflows to use actions/upload-artifact@v4
- benefit: artifacts are available for download immediately
- more details: https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/

[improve][ci] Upgrade to actions/upload-artifact@v4

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/FutureUtil.java

After the topic policies update, there are many components will be updated one by one, even if the config of components has not been modified. There are the 11 components that need update:
- `7` rate limiters(`publish`, `dispatch topic-level`, `dispatch subscription-level`,  `dispatch resourceGroup-level`, `subscribe API`, `replication`, `shadow topic replication`)
- update ManagedLedger configs(`retention`, `offloader`)
- start/stop replication
- start/stop compaction
- start/stop deduplication
Once a component update fails, the following update will be skipped. It would cause a confusing thing: you want to set a retention policy, but it will be skipped due to the `update subscribe rate limiter` failure (you did not edit the `subscribe rate limitation policy`)
Since none of the …

[fix] [broker] Update topic policies as much as possible when some ex was thrown

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerWrapper.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImplTest.java

If webServicePort and webServicePortTls are set at the same time and create an admin using webServiceAddress to access the topic, you will be stuck in an infinite redirect, the root cause is that the webServiceUrl always returns an https url even if the request is HTTP. 
It's the same with #21633

[fix][broker] Fix returns wrong webServiceUrl when both webServicePort and webServicePortTls are set

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Dispatcher.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SubscriptionPauseOnAckStatPersistTest.java

The part 3 of [PIP-299](https://github.com/apache/pulsar/pull/21118/files?short_path=cf766b5#diff-cf766b5d463b6832017e482baad14832f6a4d41dc969da279b98b69e26ec6f6a): the implementation of "Add dynamic config support: dispatcherPauseOnAckStatePersistentEnabled"
Related PRs:
- part-4: Topic policies support.
- part-5: Doc

[improve] [broker] PIP-299-part-3: Add dynamic config support: dispatcherPauseOnAckStatePersistentEnabled

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/DispatcherBlockConsumerTest.java

Pulsar has the limit of max unacked messages at 
- broker level
- subscription level
- consumer level
In the product environment(`maxUnackedMessagesPerBroker` > 0), we met the subscription blocked unexpectedly even if we have set the limit of max un-ack for subscription and consumer big enough.
After troubleshooting, this is caused by the wrong default value of `maxUnackedMessagesPerSubscriptionOnBrokerBlocked` which is 0.16 now. 
For example, if set `maxUnackedMessagesPerBroker` to 60000, the `BrokerService#maxUnackedMsgsPerDispatcher ` should be 60000 * 1/6 = 10000 by default, but now it's 600
```java
this.maxUnackedMessages = pulsar.getConfiguration().getMaxUnackedMessagesPerBroker();
this.maxUnackedMsgsPerDispatcher = maxUnackedMessages
* …
```

[fix][broker] fix the wrong value of BrokerSrevice.maxUnackedMsgsPerDispatcher

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherMultipleConsumers.java

Fixes #20924
https://github.com/apache/pulsar/blob/67eb3c463a535941e1f7996d827dab294925c018/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherMultipleConsumers.java#L195
The root cause is that :  when call `getNextConsumer ()`, we don't have any lock, the `consumerList` has changed after line-120.
https://github.com/apache/pulsar/blob/67eb3c463a535941e1f7996d827dab294925c018/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherMultipleConsumers.java#L114-L127
```
2023-07-28T09:13:34,703+0800 [pulsar-io-12-13] WARN  org.apache.pulsar.broker.service.ServerCnx - [/10.65.17.39:65308] Got exception java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at …
```

[fix][broker]Fix NonPersistentDispatcherMultipleConsumers ArrayIndexOutOfBoundsException

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicListWatcher.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/TopicListWatcherTest.java

- Start a consumer subscribe with regexp `public/default/*`
- Create a new topic `public/default/tp-1`
- Send messages to the new topic
- Consumers will not receive any messages, and the messages will be deleted due to there are no subscription.
**Case-1:**
| Time | Thread `start consumer` | Thread `create topic` |
| 1 | Start subscribe |
| 2 | Start to register `TopicListWatcher` | Create new topic |
| 3 | | Topic created |
| 4 | | Since there are no listeners registered, there is no need to notice clients |
| 5 | `TopicListWatcher` registered, the consumer will not receive any messages from the new topic |
**Case-2:**
| Time | Thread `TopicListWatcher reconnect` | Thread `create topic` |
| 1 | Start reconnect |
| 2 |  | Create new topic |
| 3 | | …

[fix] [client] Messages lost due to TopicListWatcher reconnect

---

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java

Fixes #21838 
From the implementation, the maximum number of messages actually cached by multi-topics consumer is approximately receiverQueueSize+maxTotalReceiverQueueSizeAcrossPartitions.This seems to go against the case described in the documentation.
Please see more details in https://github.com/apache/pulsar/issues/21838
- Improve the doc to clarify the correct behavior of `maxTotalReceiverQueueSizeAcrossPartitions`

[improve][doc] Improve doc for `maxTotalReceiverQueueSizeAcrossPartitions` and `receiverQueueSize` of ConsumerBuilder

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/offload/OffloadUtils.java

A coding mistake makes the retry mechanism of deleting the ledger to invalidate
Fix the bug.

[fix] [ml] Fix retry mechanism of deleting ledgers to invalidate

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/CompactorSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicInitializeDelayTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java

Cherry-pick #21745 into branch-2.11
*(or)*
*(or)*
*(example:)*

[fix][broker]Delete compacted ledger when topic is deleted (#21745)

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/UnloadScheduler.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithExtensibleLoadManagerTest.java

The log message printed when failing to create the `NamespaceUnloadStrategy` class instance mistakenly references a different config option.
Additionally fixes setup for tests in `ProxyWithExtensibleLoadManagerTest`, where the option was defaulting to value `org.apache.pulsar.broker.loadbalance.impl.ThresholdShedder`, which is incompatible with the extensible load manager, and was producing the following error message during test runs:
```
2024-01-10T14:57:28,347 - ERROR - [main:UnloadScheduler@222] - Error when trying to create namespace unload strategy: org.apache.pul
sar.broker.loadbalance.impl.LeastLongTermMessageRate
java.lang.RuntimeException: org.apache.pulsar.broker.loadbalance.impl.ThresholdShedder does not implement org.apache.pulsar.broker.l …
```

[improve][broker] Improve NamespaceUnloadStrategy error message

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/EnableProxyProtocolTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/InjectedClientCnxClientBuilder.java

InjectedClientCnxClientBuilder leaks threads since it doesn't close the resources that it creates.
The clients aren't properly closed in EnableProxyProtocolTest which is another issue.
InjectedClientCnxClientBuilder is also used in PatternTopicsConsumerImplTest and this PR will also fix the leak in that test.
- add closing of the cnxPool and eventLoopGroup to clients created with InjectedClientCnxClientBuilder
- add `Cleanup` annotations to clients created in EnableProxyProtocolTest

[fix][test] Fix thread leak in InjectedClientCnxClientBuilder and EnableProxyProtocolTest

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/GeoPersistentReplicator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ShadowReplicator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java

When expiring messages during compaction, we may lose the middle message due to `__compaction` cursor mark-delete position being advanced. So I think we should skip TTL check for `__compaction`.
replicators also have a similar problem, so also skip the expiration check of replicator
* Skip TTL check for `__compaction` and skip expire `__compaction` subscriptions.
* Passing lost `cursor.properties` when the mark deletes for the cursor.
* Skip TTL check for `replicator`, and remove the expired message replicator.
*(or)*
*(or)* …

[fix][broker] Fix compaction/replication data loss when expire messages

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java

The 'pulsar-admin namespaces unload' cli silently ignores --destinationBroker when --bundle is empty. I think we can error out in this case and clarify the usage of destinationBroker.
- error out when --destinationBroker is set when --bundle is empty
- updated the --destinationBroker option description.

[improve][cli] error out when --destinationBroker is set when --bundle is empty

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java

PIP: [PIP-307](https://github.com/apache/pulsar/blob/master/pip/pip-307.md)
This PR adds a non-dynamic option `loadBalancerMultiPhaseBundleUnload` that allows administrators to enable/disable the graceful producer/consumer shutdown upon bundle unloading (PIP-307). Without this, the only means to disable the new mechanism would be disabling the new Extensible Load Manager altogether, which might otherwise work as expected.
Adds configuration option `loadBalancerMultiPhaseBundleUnload` with the default value set to true, enabling the mechanism described in PIP-307 out-of-the-box. With the flag disabled, the clients are disconnected immediately on the source broker upon reaching the `RELEASE` state in the service channel. No lookup information is forwarded to the clients, causing them to …

[improve][broker] PIP-307: Add feature flag config option

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java

Fixes #21888
The root cause of #21888  is that a regression bug is introduced in https://github.com/apache/pulsar/pull/21589. The producer name will be conflicted when multiple consumers in the same topic and subscription send messages to DLQ concurrently.
- Use `{topic}-{subName}-{consumerName}-DLQ` as the deadLetterProducer name. For instance, it could be `my-topic-partition-0-mySub-myConsumer-DLQ`

[fix][client] Fix DLQ producer name conflicts when multiples consumers send messages to DLQ

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SubscriptionPauseOnAckStatPersistTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/TopicPolicies.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicPoliciesImpl.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java

The part 3 of [PIP-299](https://github.com/apache/pulsar/pull/21118/files?short_path=cf766b5#diff-cf766b5d463b6832017e482baad14832f6a4d41dc969da279b98b69e26ec6f6a): the implementation of "Add dynamic config support: dispatcherPauseOnAckStatePersistentEnabled"
Related PRs:
- **(Current PR)** part-4: Topic level policies support.
- part-5: Namespace level policies support
- part-6: Doc

[improve] [broker] PIP-299-part-4: Add topic-level policy: dispatcherPauseOnAckStatePersistent

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java

When `managedLedgerInactiveLedgerRolloverTimeSeconds` is set, let's say to `300` (5 minutes), the ledger will get rolled also in the case when no new entries (messages) were added to the ledger. This doesn't make sense.
Empty ledgers are deleted, but having this extra churn is causing extra load on brokers, bookies and metadata store (zookeeper).
Skip rolling the ledger if it is empty.

[improve][broker] Don't rollover empty ledgers based on inactivity

---

pip/pip-325.md

Releted PR: https://github.com/apache/pulsar/pull/21630

[improve][pip] PIP-325: Add command to abort transaction

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicList.java

- Before [PIP-145](https://github.com/apache/pulsar/issues/14505), it used the Partitioned topic name to match the Regexp. For example, the partitioned topic `public/default/tp` has one partition named `public/default/tp-partition-0`. Pulsar will use `public/default/tp` to match the Regexp<sup>[1]</sup>.
- After [PIP-145](https://github.com/apache/pulsar/issues/14505), it used the partition name to match the Regexp. For example, the partitioned topic `public/default/tp` has one partition named `public/default/tp-partition-0`. Pulsar will use `public/default/tp-partition-0` to match the Regexp<sup>[2]</sup>.
It is a break change that is not expected; these changes are due to a mistake, and we should correct it.
If a consumer tries to subscribe to a partitioned topic with a suffix-matched …

 [fix] [broker] Fix break change: could not subscribe partitioned topic with a suffix-matched regexp due to a mistake of PIP-145

---

pom.xml

Currently pulsar-client-python 3.2.0 is used for Python Functions in Pulsar images, which suffers the CVE-2023-1428 due to the old `grpc.io` dependency.
Upgrade the depended pulsar-client-python version to include https://github.com/apache/pulsar-client-python/pull/174

[improve][ci] Upgrade pulsar-client-python to 3.4.0 to avoid CVE-2023-1428

---

pip/pip-330.md

A PIP proposal adds a new `getMessagesById` to get all messages.

[improve][pip] PIP-330: getMessagesById gets all messages

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TransactionsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v3/Transactions.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/AdminApiTransactionTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Transactions.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TransactionsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTransactions.java

Fixes #xyz
PIP: #xyz 
In the implementation of Pulsar  transaction, if we have a stuck transaction, then the transactions after this one cannot be consumed by the consumer even if they have been committed. The consumer will be stuck until the stuck transaction is aborted due to timeout, and then it will continue to consume messages. Therefore, we need to provide an admin command to proactively abort the transaction in such situations.
Introduce a new API for aborting transaction.
*(or)*
*(or)*
- Added test in …

[improve][txn] Add command to abort transaction

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarStateTest.java

500 error is returned for `querystate` when the key doesn't exist.
it's related to https://github.com/apache/pulsar/pull/21597
return 404 error when key doesn't exist
- org.apache.pulsar.tests.integration.functions.PulsarStateTest.testSourceState
- org.apache.pulsar.tests.integration.functions.PulsarStateTest.testSinkState
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/22

[fix][fn] Throw 404 RestException when state key not found

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java

When using ` bin/pulsar-admin topics get-message-by-id public/default/my-topic-1 -e 0 -l 1024` with a non-existent ledger, I expect to throw the 400 error instead of 500.
CLI log:
```
$ bin/pulsar-admin topics get-message-by-id public/default/my-topic-1 -e 0 -l 1024
Message: Message not found, the ledgerId does not belong to this topic or has been deleted
Stacktrace:
org.apache.bookkeeper.mledger.ManagedLedgerException$LedgerNotExistException: Message not found, the ledgerId does not belong to this topic or has been deleted
Reason: 
Message: Message not found, the ledgerId does not belong to this topic or has been deleted
Stacktrace: …
```

[fix][broker] Fix getMessageById throws 500

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml

Release note :
https://netty.io/news/2024/01/16/4-1-105-Final.html
- Upgrade Netty to 4.1.105.Final (from 4.1.104.Final)

[improve][misc] Upgrade Netty version to 4.1.105.Final

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/PulsarTopicCompactionService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

Currently, if topic compaction is enabled and the original ledger is trimmed, we won't be able to get the correct messageID by `publishTime`, we should first try to find messageID from the compacted ledger. Since we introduced the findEntryByPublishTime method in [PIP-286](https://github.com/apache/pulsar/pull/20867), we can easily implement it.
* Try to find messageID from the compacted ledger when getting messageID by publishTime.
* Move `findFirstMatchEntry` and `findFirstMatchIndexLoop` methods to `CompactedTopicImpl` to cherry-pick this change into branches before 3.1.
*(or)* …

[fix][broker] Fix issue with GetMessageIdByTimestamp can't find match messageId from compacted ledger

---

pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorTest.java

Fixes #21916 
The method `reader.hasMessageAvailable()` return true, but `reader.readNext` can't return any messages because the messages in compacted topic are all compacted out.
Check if the message without partition key is a valid message.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/33

[fix] [broker] fix write all compacted out entry into compacted topic

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/AntiAffinityNamespaceGroupTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AdvertisedAddressTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Brokers.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BrokersImpl.java

The "lookup service address" format was changed in PR #21015 based on an invalid issue report #21012.
"lookup service address" has been renamed to "brokerId" in #21894 to reduce confusion.
The value is not a service address to be used by any connections to the broker. It is used in the Pulsar load manager as
a unique runtime identifier for a broker instance.
It's better to not change the broker id format since there isn't a reason to do this. The format used in existing Pulsar releases should be restored and that's the motivation for this PR.
There was a misconception that PR #17136 would have changed the format in Pulsar 2.11 release. That PR didn't change the format. It can be verified [from the diff](https://github.com/apache/pulsar/pull/17136/files).
- restore the broker id format to …

[fix][broker] Restore the broker id to match the format used in existing Pulsar releases

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

Broker may throw the following exception when deleting topic
```shell
ERROR org.apache.pulsar.broker.admin.v2.PersistentTopics - [null] Failed to delete topic persistent://test/test/t-partition-17
java.lang.UnsupportedOperationException: Topic policies service is disabled.
at org.apache.pulsar.broker.service.TopicPoliciesService$TopicPoliciesServiceDisabled.deleteTopicPoliciesAsync(TopicPoliciesService.java:146) ~[pulsar-broker.jar:2.12.0-SNAPSHOT]
at org.apache.pulsar.broker.service.BrokerService.deleteTopicPolicies(BrokerService.java:3345) ~[pulsar-broker.jar:2.12.0-SNAPSHOT]
at org.apache.pulsar.broker.service.AbstractTopic.deleteTopicPolicies(AbstractTopic.java:1240) ~[pulsar-broker.jar:2.12.0-SNAPSHOT]
at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$delete$31(Per …
```

[fix][broker] unify topic-level policies enable judgment conditions

---

conf/broker.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java

Configuratioin `brokerServiceCompactionPhaseOneLoopTimeInSeconds` is defined as the total timeout of phase one.
```
@FieldContext(
category = CATEGORY_SERVER,
doc = "Timeout for the compaction phase one loop, If the execution time of the compaction "
+ "phase one loop exceeds this time, the compaction will not proceed."
)
private long brokerServiceCompactionPhaseOneLoopTimeInSeconds = 30;
```
But current implementation just set a timeout for a single message read operation, which is different with the meaning of `brokerServiceCompactionPhaseOneLoopTimeInSeconds` and will result into thousands of timer tasks be scheduled and cancelled in the scheduler because we may iterate many messages.
Set a timer task for the tatol phase one.
This change …

[fix] [broker] correct compaction phase one timeout meaning

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTopicApiTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java

PIP: #21873 
The `org.apache.pulsar.client.admin.Topics` provides `getMessageById(java.lang.String, long, long)` method to get the
message, which returns one message. If the message id refers to a batch message, we can only get the first message, not
all messages.
This behavior affects our analysis of messages by the message id.
- Add `getMessagesById` and `getMessagesByIdAsync` methods to the `org.apache.pulsar.client.admin.Topics` interface.
- Implement new methods in the `org.apache.pulsar.client.admin.internal.TopicsImpl`
The `testGetMessagesId` test has been added.

[feat][admin] PIP-330: getMessagesById gets all messages

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java

Running test code `org.apache.pulsar.broker.transaction.TransactionTest`, exceptions will be throw as:
```
org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Namespace already exists
at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252)
at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:352)
at org.apache.pulsar.client.admin.internal.NamespacesImpl.createNamespace(NamespacesImpl.java:211)
at org.apache.pulsar.broker.transaction.TransactionTest.testReadCommittedWithCompaction(TransactionTest.java:1858)
```
This is because the previous test code has created the same namespace.
Using a different namespace to avoid confliction. …

[fix] [test] fix test code create namespace conflict

---

pip/pip-321.md

Because the configurations of clusters at the namespace level are unclear, some flexible topic policies can not work as expected, e.g. geo-replication at the topic level. see more information about the bug at https://github.com/apache/pulsar/pull/21564.
Use `replication-clusters`, `allowed-clusters`, and `topic-policy-synchronized-clusters` to replace a single `replication-clusters` originally in the namespace policy.
See more explanation in the proposal.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end …

[improve][pip] PIP-321  Introduce `allowed-cluster` at the namespace level

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroup.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceQuotaCalculatorImpl.java

When a ResourceGroup doesn't have any throughput, the `resourceUsagePublishTask` doesn't report the throughput data to the `RESOURCE_USAGE_TOPIC` topic,  which causes the `calculateQuotaPeriodicTask` will print the following logs.
```
2024-01-23T09:19:10,164+0000 [pulsar-2-5] INFO  org.apache.pulsar.broker.resourcegroup.ResourceGroupService - getLocalUsageStatsFromBrokerReports: no usage report found for broker=pulsar://broker-a-2:6650 and monClass=Dispatch
2024-01-23T09:19:10,164+0000 [pulsar-2-5] INFO  org.apache.pulsar.broker.resourcegroup.ResourceGroupService - getLocalUsageStatsFromBrokerReports: no usage report found for broker=pulsar://broker-a-2:6650 and monClass=Publish
2024-01-23T09:19:10,164+0000 [pulsar-2-5] INFO  org.apache.pulsar.broker.resourcegroup.ResourceGroupService - …
```

[improve][broker] Reduce ResourceGroup log

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java

A change in #21068 has renamed a protected methods in `AbstractMetadataStore`.  This was done in 3.1 and 3.2 as well as master branch. 
The problem with this change is that external metadata provider plugins cannot easily target 3.0/3.1 release because of the method name change. We shouldn't be renaming methods part of the plugin APIs. Instead we can mark them as deprecated and maintain compatibility. 
*(or)*
*(or)*
*(example:)*
- *Extended …

[fix] Restored method as deprecated in AbstractMetadataStore

---

pom.xml
pulsar-broker/pom.xml
pulsar-common/pom.xml
pulsar-transaction/coordinator/pom.xml

Currently, protobuf messages are built by lightproto. Lightproto uses protostuff in build. Protostuff can be configured using system property as follows:
https://github.com/apache/pulsar/blob/e1d06b5f54f08c09debab7a9a513b7c173c1779b/pulsar-broker/pom.xml#L610-L633
https://github.com/apache/pulsar/blob/e1d06b5f54f08c09debab7a9a513b7c173c1779b/pulsar-transaction/coordinator/pom.xml#L84-L107
These configs are held as a static field, so it is impossible to separate each module's settings in a single build phase.
https://github.com/protostuff/protostuff/blob/protostuff-1.7.2/protostuff-parser/src/main/java/io/protostuff/parser/DefaultProtoLoader.java#L38-L39
https://github.com/protostuff/protostuff/blob/protostuff-1.7.2/protostuff-parser/src/main/java/io/protostuff/parser/DefaultProtoLoader.jav …

[fix][build] Fix potential insufficient protostuff-related configs

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java

**Steps to reproduce the issue**
- Enable replication.
- Send `10` messages to the local cluster then close the producer.
- Call `pulsar-admin topics unload <topic>` and get an error due to the internal producer of the replicator close failing. 
- The topic closed failed, so we assumed the topic could work as expected, but the replication stopped.
**Root cause**
- `pulsar-admin topics unload <topic>`  will wait for the clients(including `consumers & producers & replicators`) to close successfully, and it will fail if clients can not be closed successfully.
- `replicator.producer` close failed causing the Admin API to fail, but there is a scheduled task that will retry to close `replicator.producer` which causes replication to stop. see …

[fix] [broker] Replication stopped due to unload topic failed

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/TransactionBuffer.java

~~The argument `PositionImpl readPosition` of method `org.apache.pulsar.broker.transaction.buffer.TransactionBuffer#isTxnAborted` is weird and unneccessary, we have better remove it to avoid confusion.~~
Argument `PositionImpl readPosition` is used for future.
~~Remove the argument `PositionImpl readPosition`.~~
fix the doc and add to-do to avoid confusion.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/36

[cleanup] [broker] fix doc for TransactionBuffer#isTxnAborted

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java

- PulsarSQL / Trino tests in branch-3.1 fail with this error log: 
```
FATAL: io.trino.testng.services.ReportUnannotatedMethods: Test class org.apache.pulsar.sql.presto.TestPulsarAuth has methods which are public but not explicitly annotated. Are they missing @Test?
public void org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.reconnectAllConnections() throws java.lang.Exception
JVM will be terminated
```
- make `reconnectAllConnections` method `protected` and the static method `private`.

[fix][test] Make base test class method protected so that it passes ReportUnannotatedMethods validation

---

.github/workflows/ci-go-functions.yaml
.github/workflows/ci-maven-cache-update.yaml
.github/workflows/ci-owasp-dependency-check.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

There's now a warning message for GitHub Actions:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, actions/setup-java@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Upgrade to actions/checkout@v4, actions/cache@v4 and actions/setup-java@v4

[improve][ci] Upgrade GitHub Actions versions to fix deprecation warning

---

pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/state/ByteBufferStateStore.java
pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/state/StateValue.java
pulsar-functions/api-java/src/main/resources/findbugsExclude.xml
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/state/BKStateStoreImpl.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/state/PulsarMetadataStateStoreImpl.java
pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/state/BKStateStoreImplTest.java
pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/state/PulsarMetadataStateStoreImplTest.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarStateTest.java

Fixes #xyz
PIP: #xyz 
https://github.com/apache/pulsar/pull/21597 introduce a change that always uses `null` for the `version` field for the `querystate` API. This may break users' behavior, need to add it back
1. Add a new class `org.apache.pulsar.functions.api.state.StateValue`, which contains `value`, `version`, and `isNumber` fields.
2. Add two new methods to the `org.apache.pulsar.functions.api.state.ByteBufferStateStore` interface, both of which return a `StateValue`:
1. default StateValue getStateValue(String key)
2. default StateValue getStateValueAsync(String key)
3.  Use `DefaultStateStore#getStateValue` method instead of `DefaultStateStore#get` in `org.apache.pulsar.functions.worker.rest.api.ComponentImpl` to get the `version` field from the backend state store …

[fix][fn] Add missing `version` field back to `querystate` API

---

docker-compose/kitchen-sink/docker-compose.yml

Fixes #xyz
PIP: #xyz 
When I try to start the docker-compose after the error is as follows:
Remove duplicate mapping key in `docker-compose/kitchen-sink`
*(or)*
*(or)*
*(example:)*

[fix][build] Remove duplicate mapping key in docker-compose yaml file

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorLedgerCheckerTest.java

Fixes #xyz
PIP: #xyz 
BookKeeper 4.16.4 has been released and upgrade the BookKeeper dependency to 4.16.4
*(or)*
*(or)*
*(example:)*

[improve] [bk] Upgrade BookKeeper dependency to 4.16.4

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java

Potentially related to
https://github.com/apache/pulsar/issues/15267
https://github.com/apache/pulsar/issues/14592
Broker returns this error,  `No such ledger exists on Metadata Server` to client when deleting a partitioned topic with many partitions and schema.
The root cause is that 
- the current code tries to delete the same schema for each topic partition, when that topic partition's reference is not ready.
- the delete schema operation is not idempotent enough, passing the 'No such ledger exists on Metadata Server' bk error to the client, when the schema is not found.
reproduce steps
```
bin/pulsar-admin namespaces create test/test-traffic --bundles 1
bin/pulsar-admin topics create-partitioned-topic persistent://test/test-traffic/test-topic -p 500
bin/pulsar-admin schemas upload …
```

[fix][broker] Fix schema deletion error when deleting a partitioned topic with many partitions and schema

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java

Fixes #21971
In summary, `jackson-annotations:2.12.0` or later is now required for `pulsar-client 3.0.x`, and this also applies to versions `3.1.x` and `3.2.x`.
Otherwise, `ConsumerBuilderImpl#subscribe` may become stuck without displaying any error message.
Modify the `whenComplete` to a combination of `thenAccept` and `exceptionally`. The modification is harmless.
PR in forked repository: https://github.com/Shawyeok/pulsar/pull/11

[fix][client] Fix ConsumerBuilderImpl#subscribe silent stuck when using pulsar-client:3.0.x with jackson-annotations prior to 2.12.0

---

conf/proxy.conf
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyConfigurationTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyServiceStarterTest.java

At the beginning of the design, these two configurations(`brokerServiceURL & brokerServiceURLTLS`) do not support setting multiple broker addresses, which should instead be set to a “discovery service provider.” see: https://github.com/apache/pulsar/pull/1002 and https://github.com/apache/pulsar/pull/14682
Users will get the below error if they set A to a multi-broker URLs
```
"2024-01-09 00:20:10,261 -0800 [pulsar-proxy-io-4-7] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: port out of range:-1
at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143) ~[?:?]
at …
```

[improve] [proxy] Add a check for brokerServiceURL that does not support multi uri yet

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/GetLastMessageIdCompactedTest.java

`reader.hasMessageAvailable()` rely on `getLastMessageId` to determine whether there are any messages available to read.
`org.apache.pulsar.broker.service.ServerCnx#handleGetLastMessageId` will read the last message from compacted topic in some cases without check if the consumer is in read compact mode. 
If the consumer/reader disable the read compact mode, and the cluster enable the compaction feature, messages will be compacted into the compacted topic, but the dispactcher will not dispatch messages from compacted topic to consumer. If the messages in the original topic is expired and the consumer has nothing to be read, while the messages in the compacted topic retain alive. 
**`reader.hasMessageAvailable()` will return true as there are messages in the compacted topic, but …

[fix] [broker] reader stuck when read from compacted topic with read compact mode disable

---

pip/pip-329.md

There is a gap in our current release process concerning the
pushing of the latest tag to our Docker images. Specifically, we need
to decide which version of Pulsar the latest tag should point to.
We've had initial agreement from previous discussions, found
here: https://lists.apache.org/thread/h4m90ff7dgx0110onctf5ntq0ktydzv1.
Now, we need to formally propose a PIP to address this.
- Define the strategy for maintaining the latest tag to Pulsar docker images in the release process

[improve][pip] PIP-329: Strategy for maintaining the latest tag to Pulsar docker images

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicsConsumerImplTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java

The multi-topics consumer supports seeking all internal consumers when accepting a timestamp as the argument. However, the multi-topics consumer could still read from earliest after seeking to a specific position. There are two reasons:
1. `incomingMessages` is not cleared before `seek(long timestamp)`
2. A race condition for a consumer whose start message ID is earliest:
1. `seekAsync` was called and then `incomingMessages` was cleared
2. Messages from the earliest position were prefetched to internal consumers and then added to `incomingMessages`
3. Internal consumers were disconnected from the broker and then broker reset cursors
4. Messages from the seek position were added to `incomingMessages`
5. After `seekAsync` completed, `Consumer#receive` will poll the messages fetched before …

[fix][client] Fix multi-topics consumer could receive old messages after seek

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/TopicNameForInfiniteHttpCallGetSubscriptionsTest.java

Similar to: #20131
The master branch has fixed the issue by https://github.com/apache/pulsar/pull/19841( Since it will makes users can not receive the messages which created in mistake, we did not cherry-pick https://github.com/apache/pulsar/pull/19841 into other branches, see detail https://github.com/apache/pulsar/pull/19841)
It works like this:
1. createSubscription( `tp1` )
2. is partitioned topic? 
`no`: return subscriptions
`yes`: createSubscription(`tp1-partition-0`)....createSubscription(`tp1-partition-n`)
--- 
```java
String partitionedTopic = "tp1-partition-0-DLQ";
TopicName partition0 = partitionedTopic.getPartition(0);// Highlight: the partition0.toString() will be "tp1-partition-0-DLQ"(it is wrong).The correct value is "tp1-partition-0-DLQ-partition-0"
```
Therefore, if there …

[fix] [broker] [branch-3.0] Fast fix infinite HTTP call createSubscriptions caused by wrong topicName

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiHealthCheckTest.java

The logic of these three methods `testHealthCheckup`, `testHealthCheckupV1`, `testHealthCheckupV2` are same except the `TopicVersion` variable, we can introduce a `@DataProvider` to replace them.
introduce 
```
@DataProvider(name = "topicVersion")
public static Object[][] topicVersions() {
return new Object[][] {
{ null },
{ TopicVersion.V1 },
{ TopicVersion.V2 },
};
}
```
PR in forked repository: https://github.com/thetumbled/pulsar/pull/40

[improve] [test] Remove redudant test code

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java

Fixes #21931
PIP: #xyz 
when function/sink/source is using pulsar packages as the code file, it still use the old way to download it if the `functionsWorkerEnablePackageManagement` is false
Use the "unified PackageManagement service" to download pulsar packages regardless of the`functionsWorkerEnablePackageManagement` config
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/23

[fix][fn] Use unified PackageManagement service to download packages

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/server/src/assemble/bin.xml

The server distribution assembly does not currently include artifact runtime dependencies, pulling only the compile dependencies instead. While this has not impacted the customers, a class loading issue can always crop up. This is what happened while importing OpenTelemetry dependencies related to PIP-320. OpenTelemetry itself marks its many dependencies as `runtime` (see, for instance, https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-exporter-otlp/1.34.1). Including each of them manually in our POM is both tedious and error-prone.
- Reverts the dependency scope for the server assembly to the default value, `runtime`.
- Manually excludes some of the libraries that would be needlessly pulled.
- Allows `org.roaringbitmap-shims-0.9.44.jar` to be included in the assembly.
- …

[improve][broker] Include runtime dependencies in server distribution

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java

When a broker restarted, there is a case in
`NamespaceService#findBrokerServiceUrl`:
1. `ownershipCache.getOwnerAsync(bundle)` got an empty data, then `searchForCandidateBroker` will be called
2. The broker itself was elected as the candidate broker.
3. Meanwhile, the other broker has acquired the distributed lock of the bundle, then `ownershipCache.tryAcquiringOwnership` will fail with
```java
lookupFuture.completeExceptionally(new PulsarServerException(
"Failed to acquire ownership for namespace bundle " + bundle, exception));
```
See https://github.com/apache/pulsar-client-cpp/pull/390 for the real world case.
Then in `TopicLookupBase#handleLookupError`, this exception will be wrapped into a `ServiceNotReady` error to client.
This case happens very frequently in our production …

[improve][broker] Do not close the socket if lookup failed due to LockBusyException

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java

Large floats may fail to convert because of commas in the string
Change to BigDecimal
PR in forked repository: [](https://github.com/315157973/pulsar/pull/15)

[fix] [test] Fix flaky test testPerTopicExpiredStat

---

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java

Fixes: #21922
Clarify when priorityLevel is active for failover subscriptions.
Update javaDoc comment to specify paritioned topics and indicate insignificance for non-partitioned.
PR in forked repository: N/A

[improve][client] Mention partitioning in failover priorityLevel javaDoc

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionRetentionTest.java

For some use case, the users need to store all the messages even though these message are acked by all subscription.
So they set the retention policy of the namespace to infinite retention (setting both time and size limits to `-1`).  But the data in the system topic does not need for infinite retention. 
For system topics, do not retain messages that have already been acknowledged.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …

[improve][broker] Do not retain the data in the system topic

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/timeout/TransactionTimeoutTrackerImpl.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionTimeoutTracker.java
pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/MLTransactionMetadataStoreTest.java

According to the method signature, we should return true when the transaction is added to the tracker.
```
/**
* Add a txnID to the tracker.
*
* @param sequenceId
*            the sequenceId
* @param timeout
*            the absolute timestamp for transaction timeout
*
* @return true if the transaction was added to the tracker or false if had timed out
*/
CompletableFuture<Boolean> addTransaction(long sequenceId, long timeout);
```
But actually, we return false for any cases.
Update: Moreover, we do not use the return value anyway, it is useless. We have better remove it.
~~Return true when the transaction is added to the tracker.~~
Remove the return value as it is useless.
This change is a trivial rework / code cleanup without any test …

[cleanup] [broker] fix return value of TransactionTimeoutTrackerImpl#addTransaction

---

pip/pip-335 Oxia metadata plugin.md

Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*

[feat] PIP-335: Oxia metadata plugin

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-broker/pom.xml
pulsar-metadata/pom.xml
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/MetadataStoreFactoryImpl.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/OxiaMetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/OxiaMetadataStoreProvider.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/package-info.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BaseMetadataStoreTest.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataBenchmark.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java

Add support for Oxia (https://github.com/streamnative/oxia) as a possible metadata store backed.
*(or)*
*(or)*
*(example:)*

[feat] PIP-335: Add support Oxia as a metadata store

---

docker/pulsar/scripts/apply-config-from-env-with-prefix.py
docker/pulsar/scripts/apply-config-from-env.py

Fixes #22043 
See #22043 
- add value sanitization logic to `apply-config-from-env.py` script
- refactor the script
- add support for passing the prefix so that there isn't a need for code duplication in the apply-config-from-env-with-prefix.py script. That can be deprecated.

[fix][broker] Sanitize values before logging in apply-config-from-env.py script

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelector.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelectorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java

Fixes #22050
See #22050, there's a hash collision in ConsistentHashingStickyKeyConsumerSelector when the consumer name ends with a number for example "consumer1" and "consumer11" would collide for the key "consumer111" (consumer1, i=11 & consumer11, i=1).
Fix hash collision by adding a separator between the 2 fields used in the hash calculation. Use the NUL character (`\0`) as a separator.

[fix][broker] Fix hash collision when using a consumer name that ends with a number

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java

When the `ExtensibleLoadManagerImpl.java` fails to start, it will close `brokerRegistry`. But we cannot directly determine why the broker register is closed. 
```log
2024-02-15T20:09:18,675+0000 [main] ERROR org.apache.pulsar.broker.namespace.NamespaceService - java.lang.IllegalStateException: The registry already closed.
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: The registry already closed.
at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
at org.apache.pulsar.broker.namespace.NamespaceService.registerNamespace(NamespaceService.java:380) ~[io.streamnative-pulsar-broker-3.1.2.1.jar:3.1.2.1]
at …
```

[improve][broker] Add an error log to troubleshoot the failure of starting broker registry.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupPublishLimiter.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PrecisePublishLimiter.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupRateLimiterTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PrecisTopicPublishRateThrottleTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/RateLimiter.java

We found the following error logs on the broker when we used ResourceGroupPublishLimiter. This root cause is `tryAcquire` method has a race condition with the `replaceLimiters` method, leading to publishRateLimiter using an already closed RateLimiter. PrecisePublishLimiter also has the same issue.
```java
[pulsar-io-4-54] WARN  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.6:59173] Got exception java.lang.IllegalArgumentException: Rate limiter is already shutdown
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
at org.apache.pulsar.common.util.RateLimiter.tryAcquire(RateLimiter.java:176)
at org.apache.pulsar.broker.resourcegroup.ResourceGroupPublishLimiter.tryAcquire(ResourceGroupPublishLimiter.java:138)
at …
```

[fix][broker][branch-3.1] Avoid PublishRateLimiter use an already closed RateLimiter

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TopicResources.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicListService.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicListWatcher.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationData.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java

If a consumer tries to subscribe to a partitioned topic with a suffix-matched regexp, it does not work.
- create topic `persistent://public/default/tp`
- create a consumer with regexp `persistent://public/default/tp$`
- the pattern consumer has no internal consumers.
You can reproduce the issue by the test `testPreciseRegexpSubscribe`.
- it can work when using `2.10.x`
- it can not work when using `>=2.11.0`, it is a break change due to [PIP-145](https://github.com/apache/pulsar/issues/14505)
https://github.com/apache/pulsar/pull/21885 fixed one wrong logic [here](https://github.com/apache/pulsar/pull/21885/files#diff-a36b69990c877e8ddc805bab84f15c3b119d42e152ba137d17e02e6909b0089cR54-R58), but there is still another wrong logic, see …

[fix] [broker] Fix can not subscribe partitioned topic with a suffix-matched regexp

---

.github/workflows/ci-integration-backwards-compatibility.yaml
.github/workflows/ci-integration-pulsar-io-ora.yaml
.github/workflows/ci-integration-pulsar-io.yaml
distribution/server/src/assemble/LICENSE.bin.txt
managed-ledger/src/test/java/org/apache/bookkeeper/test/ZooKeeperUtil.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckPersistentTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionRetentionTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/events/EventsTopicNames.java
pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java
pulsar-sql/presto-distribution/LICENSE

For some use case, the users need to store all the messages even though these message are acked by all subscription. So they set the retention policy of the namespace to infinite retention (setting both time and size limits to `-1`).  But the data in the system topic does not need for infinite retention.
For system topics, do not retain messages that have already been acknowledged.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery …

[branch-2.10][improve][broker] Do not retain the data in the system topic

---

buildtools/src/main/java/org/apache/pulsar/tests/ThreadLeakDetectorListener.java

[fix][test] Fix Thread.getThreadGroup().getName() NPE

---

docker/pulsar/Dockerfile

Currently Pulsar's docker image must be run with gid=0. There are environments where the group id 0 is prohibited by default. One example is Tanzu Kubernetes Grid <=1.24 where a default Pod Security Policy called `vmware-system-restricted` is used. That PSP contains this type of rule:
```yaml
supplementalGroups:
rule: MustRunAs
ranges:
- min: 1
max: 65535
runAsUser:
rule: MustRunAsNonRoot
fsGroup:
rule: MustRunAs
ranges:
- min: 1
max: 65535
```
In this case, it's not possible to use Pulsar's docker image since Pulsar needs write access to a few directories.
change the owner of the writable directories to user id 10000.
This will allow Tanzu to work with this type of securityContext for each Pulsar component (Broker, Zookeeper, Bookkeeper)
```
securityContext:
runAsNonRoot: true …
```

[fix][broker] Support running docker container with gid != 0

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-functions/runtime-all/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceDepsTest.java

commons-compress 1.21 has the following vulnerability and should be upgraded to 1.26.0.
https://nvd.nist.gov/vuln/detail/CVE-2024-25710

[fix][sec] Upgrade commons-compress to 1.26.0

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java

Max read position is before the first ongoing txn's position. But the entry id of the first message may be 0, calculate the max read position by `entry id - 1` is unsafe.
Calculate the max read position by method `managedLedger.getPreviousPosition`.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/42

[fix] [txn] Get previous position by managed ledger.

---

.mvn/extensions.xml
.mvn/gradle-enterprise.xml

- keep the Gradle Enterprise maven extension version up-to-date
- skip activating Gradle Enterprise maven extension for builds in GitHub Actions when the pull request branch or forked repository has a name that indicates it's a work in progress.
- it's better not to clutter the GE server with unnecessary builds for experiments.

[improve][ci] Upgrade Gradle Enterprise maven extension version

---

docker/pulsar/pom.xml
pom.xml
tests/docker-images/java-test-image/pom.xml

In the current build, it is necessary to set IMAGE_JDK_MAJOR_VERSION environment variable. It's better to have the values set by default
- add a solution to properly set defaults for `IMAGE_JDK_MAJOR_VERSION`, `UBUNTU_MIRROR` and `UBUNTU_SECURITY_MIRROR`.

[fix][build] Fix building java-test-image without setting IMAGE_JDK_MAJOR_VERSION

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreFactory.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/TableViewLoadDataStoreImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchMessageContainerImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/store/LoadDataStoreTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TableViewImpl.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java

We better set the compaction threshold of the serviceUnitStateChannel topic instead of relying on other components' init.
Also, we need to fix the issue that lookup and unload often timeout with  500 error.
- Set the compaction threshold of the serviceUnitStateChannel topic in the monitor thread
- Release metadataAndPayload buffer in RawBatchMessageContainerImpl.
- Automatically restart load data store producer and table view if inactive.
- Updated getOwnerAsync for better synchronization of ownership checks, deferred lookups and active broker checks
- added minor retry logic in the ExtensibleLoadManager tests
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/61

[fix][broker] Set ServiceUnitStateChannel topic compaction threshold explicitly, improve getOwnerAsync, and fix other bugs

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java

---
Fixes #xyz
PIP: #xyz 
We have two configurations to trigger the offload automatically, time and bytes. We only expose the bytes in the admin but didn't expose the time in the admin. When we want to disable it, we need to set both of them to the -1. But we didn't expose the time settings, the offload will never be disabled.
*(or)*
*(or)*
*(example:)* …

[improve][admin] Expose the offload threshold in seconds to the amdin

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/TopicEventsListenerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java

When we call `pulsar-admin topics stats <topic name>`, Pulsar will try to open a managed ledger even if the topic metadata does not exist.
It costs a lot of resources when there are many requests trying to call `pulsar-admin topics stats <topic name>` on a deleted partition.
```
2024-01-30T15:52:17,143+0000 [bookkeeper-ml-scheduler-OrderedScheduler-2-0] ERROR org.apache.pulsar.broker.admin.v2.PersistentTopics - [flink-cluster@belvedere.auth.streamnative.cloud] Failed to get stats for persistent://xx/xx/xx-partition-0
java.util.concurrent.CompletionException: org.apache.pulsar.broker.web.RestException: Topic partitions were not yet created
at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
at …
```

[improve] [broker] Do not try to open ML when the topic meta does not exist and do not expect to create a new one. #21995

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/TopicPoliciesSystemTopicClient.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java

Fixes #22087
Cache the internal writer when sent to system topic.

[improve][broker] Cache the internal writer when sent to system topic.

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarStateTest.java

Fixes https://github.com/apache/pulsar/issues/22108
PIP: #xyz 
Before https://github.com/apache/pulsar/pull/21597, The implementation of `getStateStore` for `BKStateStoreProviderImpl` will be called once by `JavaInstanceRunnable` to create the stream table once the instance gets started. But after #21597, the `getStateStore` will be called via the `putstate` and `getstate` APIs without any check, this will cause the creation of a stream table for non-existent functions and connectors.
- add function instance check before `getStateStore`
*(or)*
*(or)*
This change added …

[fix][fn] Prevent create state table from API calls for non-exists instances

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageWithBatchIndexLevelTest.java

Context:
- After a consumer closes, it may leave an in-progress acknowledge task.
Issue:
- There are two consumers: `c1` and `c2`
- `c1` received a batch message: `ledger: L1, entry: E1, batch-size: 100`.
- `c1` was closed, after leaving an in-progress task to acknowledge `{L1, E1, batch_index: 1}`
- Pulsar read `{L1, E1}` and tries to delivery to `c2`.
- The acknowledgement `{L1, E1, batch_index: 1}` is finished.
- `c2` gets `100` messages, but `unackedMessages` of `c2` is `98`.
We can always get the warn logs like below:
```
07:01:11.037 [pulsar-io-4-17] WARN  org.apache.pulsar.broker.service.Consumer - unackedMsgs is : -1,
```
Fix the bug.

[fix] [broker] Enabling batch causes negative unackedMessages due to ack and delivery concurrency

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerServiceException.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java

Fixes #21839 
In scenarios where subscriptions are made via WebSockets and are proxied through a proxy, addressing the issue of non-existent subscriptions causing consumer clients to continuously retry and not being restricted by the number of subscription consumers, can result in excessive consumption of CPU and memory resources by the proxy.
When the subscription does not exist and automatic creation is not permitted, no retries are attempted.
*(or)*
*(or)*
*(example:)* …

[fix] [client] Do no retrying for error subscription not found when disabled allowAutoSubscriptionCreation

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageWithBatchIndexLevelTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java

Context:
- The broker decreases the permits after delivering messages to the client.
-  It only decreases the un-acked part for permits when delivering batched messages to the client.
- The client acquires more permits after consuming messages.
- **(Highlight)** It acquires the whole batch for permits even if it only received half of the batched message.
Reproduce step:
- The permits were initialized as `1000`
- Send a batch message containing 100 single messages.
- Ack a half of batched messages(`2` single messages).
- Redeliver the batch message.
- Receive the `98` messages left on the topic.
- **(Highlight)** permits is `1002`.
One our ENV, the permits went to `100,000+`(it was initialized as `50`), and leading the set `pendingAcks` went to a huge value. This may causes a client side …

[fix] [client] fix huge permits if acked a half batched message

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionBufferClientTest.java

The metric in the `testTransactionBufferMetrics` will be impact by the other tests, so we should restart before running this test.
```
java.lang.AssertionError:
Expected :1.0
Actual   :3.0
<Click to see difference>
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEquals(Assert.java:727)
at org.testng.Assert.assertEquals(Assert.java:774)
at org.apache.pulsar.broker.transaction.buffer.TransactionBufferClientTest.testTransactionBufferMetrics(TransactionBufferClientTest.java:251)
```
Restart before running this test.
*(or)* …

[fix][test] Fix test testTransactionBufferMetrics

---

.github/actions/upload-coverage/action.yml

In GitHub Actions workflows there's a warning about codecov-action@v3:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: codecov/codecov-action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
- upgrade codecov-action to v4

[improve][ci] Upgrade codecov-action version

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarStateTest.java

Fixes https://github.com/apache/pulsar/issues/22126
PIP: #xyz 
When submitting the `putstate` requests with other libs such as pulsar-admin-go, the `FunctionState` JSON string may contain the default value of string or int, so the functions worker may use an incorrect value when the user submits with `bytesString`. See https://github.com/apache/pulsar-client-go/issues/1184 for more details.
- Fix the logic
- Add more tests
*(or)*
*(or)*
*(example:)* …

[bug][fn] Prevent `putstate` uses empty values

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionStablePositionTest.java

1. Change to None state before invoking the recovery.
2. Improve the method `checkTopicTransactionBufferState` to see the test result easier. 
```
org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.broker.transaction.buffer.TransactionStablePositionTest was not fulfilled within 10 seconds.
at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
at org.apache.pulsar.broker.transaction.buffer.TransactionStablePositionTest.checkTopicTransactionBufferState(Tra …
```

[fix][test] fix test testSyncNormalPositionWhenTBRecover

---

pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceTest.java

The assert `Assert.assertEquals(request.getProcessResult().get(), testString + "-lambda");` will wait for the function process completely, so the following ones are also processed completely. And the pending requests will be removed. Which will cause an NPE when doing the next verify.
```
2024-02-26T15:12:22,054 - INFO  - [main:JavaInstanceTest@195] - input string: ABC123
2024-02-26T15:12:22,062 - INFO  - [main:JavaInstanceTest@195] - input string: ABC123
2024-02-26T15:12:22,064 - INFO  - [main:JavaInstanceTest@195] - input string: ABC123
java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.functions.instance.JavaInstance$AsyncFuncRequest.getProcessResult()" because "request" is null
at org.apache.pulsar.functions.instance.JavaInstanceTest.testAsyncFunctionMaxPending(JavaInstan …
```

[fix][test] Fix test testAsyncFunctionMaxPending

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java

Upon Assigning and Releasing, if this broker is not the dst broker, return the dst broker as the owner(or empty). Clients need to connect(redirect) to the dst broker anyway and wait for the dst broker to receive `Owned`. This is also required to return getOwnerAsync on the src broker immediately during unloading. Otherwise, topic creation(getOwnerAsync) could block unloading bundles, if the topic creation(getOwnerAsync) happens during unloading on the src broker.
Found a case that the broker role might change in the middle while running playLeader or playFollower. In this case, we need to break the init loop and restart playLeader or playFollower according to the current role.
- Return getOwnerAsync without waiting on source broker upon Assigning and Releasing
- Updated role change logic …

[fix][broker] Return getOwnerAsync without waiting on source broker upon Assigning and Releasing and handle role change during role init

---

.github/workflows/codeql.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

Improvements to CI:
- run CodeQL within Pulsar CI workflow for PRs
- This ensures that the PR cannot be merged unless the CodeQL step passes
- don't run CodeQL scheduled build for forked repositories
- enable Pulsar CI for branches
- for some reason CI didn't run for this PR in branch-3.0: #22130
- cancel duplicate builds running CodeQL

[improve][ci] Run CodeQL within Pulsar CI workflow as mandatory check

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml

Upgrade Jetty to 9.4.54.v20240208 to address CVE-2024-22201

[fix][sec] Upgrade Jetty to 9.4.54.v20240208 to address CVE-2024-22201

---

.github/changes-filter.yaml
.github/workflows/pulsar-ci.yaml

For Pull Requests, running CodeQL isn't necessary when there isn't changes to production (non-test) java code.
Only run CodeQL when the PR contains changes to files matching `**/src/main/java/**/*.java`.

[improve][ci] Only run CodeQL when the PR contains changes to non-test java code

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdNamespaces.java

Fixes #22138
When specified with -s with `-xT`, it will overflow when convert long to int.

[fix][cli] Fix the bug when set-retention specified size with -T

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PulsarWorkerService.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java

Fixes #xyz
PIP: #xyz 
While debugging an error for function trigger, the logs only print: `Function in trigger function is not ready @ /public/default/test`, which is useless without the error stack trace, it's better to add it, I also found other `log.error` missed the "exception" argument while most of `log.error` has it.
Add exception as the last argument to calling of `log.error` which missed it

[improve][fn] Add missing "exception" argument to some `log.error`

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L2968-L2983
```
replCloseFuture.thenCompose(v -> delete())
.thenApply((res) -> tryToDeletePartitionedMetadata()) // This line lost the error throws by "tryToDeletePartitionedMetadata"
.exceptionally(e -> {
log.warn("[{}] Inactive topic deletion failed", topic, e);
});
}
```
The line `thenApply((res) -> tryToDeletePartitionedMetadata()) ` lost the error throws by "tryToDeletePartitionedMetadata", makes these two issues:
- No log was printed when deleting partitioned metadata failed.
- The `future` of `delete the topic and delete partitioned topic metadata if needed` only indicates `delete topic partition`, not `delete topic and metadata`. BTW, this …

[fix] [broker] print non log when delete partitioned topic failed

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesAuthZTest.java
pulsar-broker/src/test/java/org/apache/pulsar/security/MockedPulsarStandalone.java
pulsar-broker/src/test/java/org/apache/pulsar/security/tls/ec/TlsWithECCertificateFileTest.java
pulsar-broker/src/test/java/org/apache/pulsar/security/tls/ec/TlsWithECKeyStoreTest.java

Add fine-grain authorization to retention admin API so that it can be controlled at a more fine-grain level.
- Update getRetention, add PolicyName.RETENTION with READ check
- Update setRetention & removeRetention, add PolicyName.RETENTION with WRITE check

[improve][broker] Add fine-grain authorization to retention admin API

---

pulsar-common/src/main/java/org/apache/pulsar/common/util/FutureUtil.java
tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileStoreBackedReadHandleImpl.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImplV2.java

Fixes https://github.com/apache/pulsar/pull/22035
PIP: #xyz 
Make `FileStoreBackedReadHandleImpl`, `BlobStoreBackedReadHandleImpl` and `BlobStoreBackedReadHandleImplV2`
`closeAsync` method can be called multi times. 
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/dao-jun/pulsar/pull/9

[fix][offload] Fix Offload readHandle cannot close multi times.

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java

Fixes #xyz
PIP: #xyz 
cherry-pick https://github.com/apache/pulsar/pull/22101
*(or)*
*(or)*
*(example:)*

[improve][admin][branch-3.0] Expose the offload threshold in seconds to the admin

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceAutoSubscriptionCreationTest.java

Fixes #22188
```
Error:  Tests run: 11, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 10.526 s <<< FAILURE! - in org.apache.pulsar.broker.service.BrokerServiceAutoSubscriptionCreationTest
Error:  org.apache.pulsar.broker.service.BrokerServiceAutoSubscriptionCreationTest.testDynamicConfigurationTopicAutoSubscriptionCreation  Time elapsed: 0.193 s  <<< FAILURE!
org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException$SubscriptionNotFoundException: {"errorMsg":"Subscription does not exist","reqId":1263382438898186087, "remote":"localhost/127.0.0.1:39313", "local":"/127.0.0.1:55306"}
at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1131)
at …
```

[fix][test] Fix flaky test BrokerServiceAutoSubscriptionCreationTest

---

conf/functions_worker.yml
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionE2ESecurityTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionPublishTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/AbstractPulsarE2ETest.java
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PackageUrlValidator.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PulsarWorkerService.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SinksImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SourcesImpl.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionActionerTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionRuntimeManagerTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/AbstractFunctionApiResourceTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/AbstractFunctionsResourceTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/SinkApiV3ResourceTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/SourceApiV3ResourceTest.java

Currently the configuration is missing for enabling and disabling connector and function package url sources.
- Add configuration for enabling connector and functions package urls in functions_worker.yml
- Add checking of package urls in required locations in Function Worker code

[improve][fn] Add configuration for connector & functions package url sources

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplWithTransactionCoordinatorTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/messaging/MessagingSmokeTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarClusterTestBase.java
tests/integration/src/test/resources/pulsar-messaging.xml

Cherry-picking https://github.com/apache/pulsar/pull/22139 into `branch-3.1`.

[fix][broker][branch-3.1] Fix broker not starting when both transactions and the Extensible Load Manager are enabled

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/AutoCloseUselessClientConSupports.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java

Context: https://github.com/apache/pulsar/pull/22085/files#r1497008116
Currently, the connection pool key does not include physicalAddress (currently logicalAddress + keySuffix). This can be a problem when the same logicalAddresses are in the migrated(green) cluster. (the connection pool will return the connection to the old(blue) cluster)
Add physicalAddress as part of the connection pool key

[improve][client] add physicalAddress as part of connection pool key

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedCursor.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java

Cherry-pick #21187 into branch-3.0

[fix][broker][branch-3.0] Avoid consumers receiving acknowledged messages from compacted topic after reconnection (#21187)

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericProtobufNativeSchema.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/generic/GenericProtobufNativeReaderTest.java

GenericProtobufNativeSchema not implement getNativeSchema method.
Add `getNativeSchema` implement for `GenericProtobufNativeSchema`.
Add `testGetNativeSchema` to cover it.

[fix][client] GenericProtobufNativeSchema not implement getNativeSchema method.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java

cherry-pick PR https://github.com/apache/pulsar/pull/21940
cherry picked from commit 861618a8120901a4042e99243d8fa539449d7f60

[fix] [broker][branch-3.0] Expire messages according to ledger close time to avoid client clock skew (#21940)

---

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java
pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerfClientUtilsTest.java

Repeat with the code here:
https://github.com/apache/pulsar/blob/c7cedc6828e08765e6a14335bb5a00cf23f0cfa3/pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerfClientUtils.java#L69-L70
Remove duplicate code:
```java
.memoryLimit(arguments.memoryLimit, SizeUnit.BYTES)
```
PR in forked repository: https://github.com/crossoverJie/pulsar/pull/20

[improve][cli] Remove cli unnecessary code

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java

Some vendors' environments do not support reading virtual NIC type. The broker will constantly print the useless warning log, which will increase the storage cost.  
The demo logs is as follows:
```
[pulsar-load-manager-1-1] WARN  org.apache.pulsar.broker.loadbalance.LinuxInfoUtils - [LinuxInfo] Failed to read /sys/class/net/nc1 NIC type, the detail is: /sys/class/net/nc1/type: Not a directory
[pulsar-load-manager-1-1] WARN  org.apache.pulsar.broker.loadbalance.LinuxInfoUtils - [LinuxInfo] Failed to read /sys/class/net/nc1 NIC type, the detail is: /sys/class/net/nc1/type: Not a directory
[pulsar-load-manager-1-1] WARN  org.apache.pulsar.broker.loadbalance.LinuxInfoUtils - [LinuxInfo] Failed to read /sys/class/net/nc1 NIC type, the detail is: /sys/class/net/nc1/type: Not a directory
```
- …

[improve][broker] Change log level to reduce duplicated logs

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

If schema ledger is lost, when we call the admin interface "topics stats-internal", the server only has the following error log:
However, this log does not clearly indicate which ledger is lost. We don’t even know whether the ledger of topic, cursor or schema is lost. Therefore, it brings challenges to quickly locate the problem.
When failed to get ledger metadata for the schema ledger, add logs to quickly locate problem:
` log.info("[{}] Failed to get ledger metadata for the schema ledger {}", topic, ledgerId, e);`
At this time, we can see the following log, and we can quickly and clearly know that the problem is caused by schema ledger is lost.

[improve][broker] Add logs to `getInternalStats` for quickly locate problem when schema ledger is lost

---

.github/workflows/ci-maven-cache-update.yaml
.github/workflows/ci-owasp-dependency-check.yaml
.github/workflows/codeql.yaml
.github/workflows/pulsar-ci-flaky.yaml
.github/workflows/pulsar-ci.yaml

We are using the corretto JDK in our [image](https://github.com/apache/pulsar/pull/22054/files#diff-270c05dd38d726acf0a365e3a8e35c3d28b8314b0ea0efa2acd8f631456c8cd4R73), so I think we also Switch JDK distribution from temurin to corretto in the CI.
Use corretto instead temurin.

[improve][ci] Switch JDK distribution from temurin to corretto

---

docker/pulsar/Dockerfile
docker/pulsar/build-scripts/remove-unnecessary-native-binaries.sh

The RocksDB jar that we are including in our Docker image is ~55 MB in size because it includes native library of RocksDB compiled for many different platforms. 
In reality, our Docker image is going to be used exactly on one single platorm, either `linux/x86-64` or `linux/arm64`. 
Therefore we can remove all the other RocksDB compiled libraries from the image. The resulting RocksDB jar is shrunk to 4.6 MB.
Similarly, we can remove Netty TC natives jar that are not relevant for the container.
Added a script to remove the unnecessary libraries.
*(or)*
*(or)*
This change added tests and …

[improve] Removed unnecessary native libraries from Docker images

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java

The test environment in the TransactionTest will not be reset for each test.
If the tests use the same namespace name, they will interfere with each other.
```
org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Namespace already exists
at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252)
at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:352)
at org.apache.pulsar.client.admin.internal.NamespacesImpl.createNamespace(NamespacesImpl.java:211)
at org.apache.pulsar.broker.transaction.TransactionTest.testEncryptionRequired(TransactionTest.java:1670)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAcce …
```

[fix][test] fix the tests with same namespace name

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/MultiBrokerTestZKBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/SpyConfig.java

Fixes #22239 
The AdvertisedListenersMultiBrokerLeaderElectionTest test is flaky since it times out.
I profiled the test with Async Profiler on Linux by adding this to pom.xml in `<test.additional.args>`
```
<test.additional.args>
-agentpath:/home/lari/tools/async-profiler-3.0-linux-x64/lib/libasyncProfiler.so=start,event=cpu,jfr,file=/tmp/profile${maven.build.timestamp}_${surefire.forkNumber}.jfr
```
and converting the `.jfr` file to `.html` with `java -jar tools/async-profiler-3.0-macos/lib/converter.jar jfr2flame profile2024-03-12T10:44:25Z_1.jfr output.html` and `java -jar tools/async-profiler-3.0-macos/lib/converter.jar jfr2flame --threads profile2024-03-12T10:44:25Z_1.jfr output_threads.html`. 
In the profile, I could see that Mockito was causing a lot of overhead to the execution. …

[improve][test] Don't configure Mockito spying for MultiBrokerTestZKBaseTest

---

buildtools/src/main/resources/log4j2.xml
pulsar-broker/src/test/resources/log4j2.xml
tiered-storage/jcloud/src/test/resources/log4j2-test.yml

- tests use a logging configuration where the location of the log statement is logged. this is very expensive and unnecessary. 
- this was noticed in test profiling (see #22250 for details of how profiling was performed)
- don't log the location where the log was added since this causes a high overhead
- The overhead is explain in https://logging.apache.org/log4j/2.x/manual/layouts.html#location-information

[improve][test] Reduce logging overhead in tests

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/RGUsageMTAggrWaitForAllMsgsTest.java

Fixes #17126
RGUsageMTAggrWaitForAllMsgsTest is flaky
- wait until the consumer thread completes before reading the counters
- make fields volatile (however this might not be necessary since thread is joined before reading fields)
- move the tests to flaky tests since it remains flaky after the above modifications

[fix][test] Fix flaky RGUsageMTAggrWaitForAllMsgsTest

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/MultiBrokerLeaderElectionTest.java

Fixes #22239
The test shouldProvideConsistentAnswerToTopicLookupsUsingAdminApi failed too many times in the GitHub CI because of too many topics and too little runtime.
https://github.com/apache/pulsar/actions/runs/8245776074/job/22550815658?pr=22034
https://github.com/apache/pulsar/actions/runs/8234998047/job/22547427391?pr=22243
```log
org.apache.pulsar.broker.loadbalance.AdvertisedListenersMultiBrokerLeaderElectionTest.shouldProvideConsistentAnswerToTopicLookupsUsingAdminApi  Time elapsed: 60.005 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.broker.loadbalance.MultiBrokerLeaderElectionTest.shouldProvideConsistentAnswerToTopicLookupsUsingAdminApi() didn't finish within the time-out 60000
at …
```

[fix][test] fix flaky test shouldProvideConsistentAnswerToTopicLookupsUsingAdminApi

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesAuthZTest.java

```
Summary: Tests in class org.apache.pulsar.broker.admin.TopicPoliciesAuthZTest created 24 new threads. There are now 34 threads in total.
```
Close the resource that have been created in the test.

[fix][test] Fix thread leak in TopicPoliciesAuthZTest

---

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java

[fix] [broker] Fix typo in CompactedTopicImpl.

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/MultiBrokerLeaderElectionTest.java

AdvertisedListenersMultiBrokerLeaderElectionTest is flaky. This change is to reduce issues and this change isn't harmful. 
The thread leak detector reported leaked threads. The way this could help is that when the test fails, cleanup would happen properly and the test retry could pass with better chance. 
There's no guarantee that this would eliminate the flakiness problem, but it's useful for cleanups related to test retries.
- shutdown executors immediately by calling `.shutdownNow()` instead of `.shutdown()`
- ensure that all threads waiting on the phaser instance would terminate by calling `.forceTermination()` on the phaser instance (this could also be taken care by `.shutdownNow()`.

[improve][test] Reduce AdvertisedListenersMultiBrokerLeaderElectionTest flakiness

---

pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/io/SinkConfig.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/io/SourceConfig.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SourceConfigUtils.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SinkConfigUtilsTest.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SourceConfigUtilsTest.java

Fixes #xyz
PIP: #22071 
*(example:)*
- *Added unittests for setting log-topic and update log-topic*
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/27

[improve][pip] PIP-339: Introducing the --log-topic Option for Pulsar Sinks and Sources

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/KeySharedSubscriptionTest.java

Cherry-pick #20990 to branch-2.10
*(or)*
*(or)*
*(example:)*

[fix][broker] Fix incorrect unack msk count when dup ack a message (#20990)

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java

Cherry-pick #21640 to branch-2.11

[improve][sec][branch-2.11] Align some namespace level policy authorisation check (#21640)

---

pip/pip-343.md

Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*

[improve][pip] PIP-343: Use picocli instead of jcommander

---

pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ProducerHandler.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketServiceStarter.java

Now if user start a websocket service without `clusterName`, service will be started as normal, but it'll get NPE in the after produce request.
The websocket service will log this line below:
```
2024-03-09T16:53:22,468 - WARN  - [pulsar-websocket-web-1-1:ProducerHandler@129] - \
[[0:0:0:0:0:0:0:1]:49221] Failed in creating producer on topic persistent://public/non-exist/my-topic: java.lang.NullPointerException
```
<details>
<summary>The NPE stacktrace (which is missing in log)</summary>
<pre>
org.apache.pulsar.broker.PulsarServerException: java.lang.NullPointerException
at org.apache.pulsar.websocket.WebSocketService.retrieveClusterData(WebSocketService.java:261) ~[classes/:?]
at org.apache.pulsar.websocket.WebSocketService.getPulsarClient(WebSocketService.java:185) ~[classes/:?]
at …

[fix][ws] Check the validity of config before start websocket service

---

pulsar-broker/src/main/java/org/apache/pulsar/client/api/RawReader.java
pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/Compactor.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawReaderTest.java

In #21745, we disabled the createTopicIfDoesNotExists of RawReader to avoid the compactor‘s RawReader will create the topic again after the topic has been deleted.
Because the RawReader is a public API, so we'd better not change the default behavior. we can add an option for RawReader.
Add createTopicIfDoesNotExist option to RawReader constructor.
Revert RawReader to default behavior (auto create topic)
*(or)*
*(or)*
*(example:)*
- *Extended …

[improve][broker] Add createTopicIfDoesNotExist option to RawReader constructor

---

.github/ISSUE_TEMPLATE/bug-report.yml

The GitHub issue template doesn't contain information about the Pulsar release policy.
This results in users reporting issues against old versions of Pulsar, which is a waste of time for everyone involved.
Optimally, issue reporters would first upgrade their Pulsar client and broker version to a supported version and if the problem isn't fixed, they would report the issue.
Update the GitHub issue template.

[improve][misc] Add mandatory checkbox about release policy in the issue template

---

src/set-project-version.sh

- pulsar-bom didn't get published in 3.2.1 release since the version hadn't been updated in pom.xml
- add special handling for pulsar-bom in set-project-version.sh script

[fix][build] Add special handling for pulsar-bom in set-project-version.sh

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml

- Address CVE-2024-23944 described in [the announcement email](https://lists.apache.org/thread/96s5nqssj03rznz9hv58txdb2k1lr79k).
- based on the description, this has no direct impact for Pulsar users. 
- it's necessary to make the upgrade so that vulnerability scanning stays clean for Pulsar artifacts.
- upgrade Zookeeper to 3.9.2

[fix][sec] Upgrade Zookeeper to 3.9.2 to address CVE-2024-23944

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml

Pin Jose4j library lib to latest version. This is a dependency of K8S Java client API. 
`org.bitbucket.b_c:jose4j:jar:0.9.4:compile` which has a fix for:
```
┌──────────────────────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────────┐
│               Library                │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                            Title                            │
├──────────────────────────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼─────────────────────────────────────────────────────────────┤
│ org.bitbucket.b_c:jose4j             │ CVE-2023-51775 │ MEDIUM   │ fixed  │ 0.9.3             │ 0.9.4         │ …
```

[fix] Upgrade jose4j to 0.9.4

---

pulsar-client-messagecrypto-bc/src/main/java/org/apache/pulsar/client/impl/crypto/MessageCryptoBc.java
pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java

- CodeQL warns about using MD5 in 2 locations in the Pulsar code base
- Dismiss warning about MD5 since it's sufficient for these use cases
- Dismissing warnings is mentioned [in CodeQL changelog](https://github.com/github/codeql/blob/main/java/ql/src/CHANGELOG.md#minor-analysis-improvements-14).
- CodeQL Java support's test case contains [examples of supported syntax](https://github.com/github/codeql/blob/daee22d38cdfedb110ff3e807df83d6149c904c9/java/ql/test/query-tests/AlertSuppression/Test.java).

[fix][sec] Dismiss warning about MD5 since it's sufficient for these use cases

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java

The access on `readOnActiveConsumerTask` is not thread safe.
```java
if (readOnActiveConsumerTask != null) {
return;
}
readOnActiveConsumerTask = topic.getBrokerService().executor().schedule(() -> {/* ... */});
```
There is a case that:
| Steps | Thread 1 | Thread 2 |
| :- | :- | :- |
| 1 | Read `readOnActiveConsumerTask`: null | |
| 2 | call `schedule` | |
| 3 | | Read `readOnActiveConsumerTask`: null |
| 4 | | call `schedule` |
| 5 | Write `readOnActiveConsumerTask` to the result of `schedule` | |
| 6 | | Write `readOnActiveConsumerTask` to the result of `schedule` |
Then `schedule()` will be called twice and only one result (it could be either step 5 or 6) will be assigned to `readOnActiveConsumerTask`.
Follow the double-checked locking when `readOnActiveConsumerTask` is null to ensure …

[fix][broker] Fix wrong double-checked locking for readOnActiveConsumerTask in dispatcher

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java

If the namespace has been deleted,` prepareInitPoliciesCacheAsync` should not be executed.
**More detailed description:**
When the namespace is forcibly deleted, if a topic exists and the own bundle of the topic is not loaded into the memory, deleting the namespace will trigger the loading of the bundle, which will trigger the execution of `prepareInitPoliciesCacheAsync`(load topic policies). However, at this time, due to the namespace is already in a deleted state, so execution will print the following exception log.
**Minimal reproduce step:**
1.Start a single broker node and create a tenant `test-tenant`
2.Create a new namespace and a  new partitioned topic.
sh bin/pulsar-admin namespaces create test-tenant/test-ns
sh bin/pulsar-admin topics create-partitioned-topic …

[fix][broker] Avoid execute prepareInitPoliciesCacheAsync if namespace is deleted

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml

Keep the Jersey up-to-date.
Release note: https://github.com/eclipse-ee4j/jersey/releases/tag/2.41
- Upgrade Jersey from 2.34 to 2.41

[improve][misc] Upgrade jersey to 2.41

---

pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/AuditorBookieCheckTaskTest.java

Do not use `com.beust.jcommander.internal` package.
- Use `new ArrayList()` instead of `Lists.newArray()`
- Use `new HastSet()` instead of `Sets.newHashSet()`

[cleanup][meta] Remove com.beust.jcommander.internal import

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java

When I create a MultiTopicsConsumer using the two same topics, I get a warning log `Topic is already being subscribed for in another thread`, which is not clear.
- `persistent://public/default/tp`
- `public/default/tp`
```
2024-03-13T00:27:42,785 - INFO  - [pulsar-client-io-35-2:ConsumerImpl@938] - [persistent://public/default/tp-8446b215-9f1d-470f-af07-eb9be8b15415][s1] Subscribed to topic on localhost/127.0.0.1:49225 -- consumer: 0
2024-03-13T00:27:42,785 - WARN  - [pulsar-client-io-35-2:MultiTopicsConsumerImpl@186] - [MultiTopicsConsumer-2d576] Failed to subscribe topics: org.apache.pulsar.client.api.PulsarClientException: [MultiTopicsConsumer-2d576] Failed to subscribe for topic [persistent://public/default/tp-8446b215-9f1d-470f-af07-eb9be8b15415] in topics consumer. Topic is already …
```

[fix] [client] Unclear error message when creating a consumer with two same topics

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java

The modifications on
`AbstractDispatcherSingleActiveConsumer#activeConsumer` only happen on `pickAndScheduleActiveConsumer`, which is only called in `addConsumer` and `removeConsumer`. However, both `addConsumer` and `removeConsumer` are synchronized methods so that we don't have to perform an atomic operation on `activeConsumer`.
The composite operations on `activeConsumer` also happen on synchronized methods like `disconnectActiveConsumers`. The only access to `activeConsumer` that is not synchronized is the read on `activeConsumer` like `getActiveConsumer()` and `isConsumerConnected()`.
Remove the `ACTIVE_CONSUMER_UPDATER` and note some methods are not thread safe or there is no need to make them thread safe.
Besides, since `pickAndScheduleActiveConsumer` is never called concurrently, …

[improve][broker] Remove the atomicity on active consumer of a dispatcher

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespaceAuthZTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAuthZTest.java

Add fine-grain authorization to ns/topic management endpoints so that it can be controlled at a more fine-grain level.
- `TRIM_TOPIC` was missing, this would cause the normal user throw `IllegalStateException` not NotAuthorizedException.
- adding fine-grain authorization to `internalSetProperty`, `internalSetProperties`, `internalGetProperty`, `internalGetProperties`, `internalRemoveProperty`, `internalClearProperties`, `internalUnloadTopic`,`internalGetManagedLedgerInfo`, `internalGetPartitionedStats`, `internalGetPartitionedStatsInternal`, `internalCreateSubscription`, `internalUpdateSubscriptionProperties`, `internalAnalyzeSubscriptionBacklog`, `internalGetSubscriptionProperties`, `internalCreateMissedPartitions`
- Add fine-grain authorization test coverage to `NamespaceAuthZTest` and …

[improve][broker] Add fine-grain authorization to ns/topic management endpoints

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java
pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java

```
curl -X GET https://127.0.0.1:443/admin/v2/schemas/public/default/tp1/schema 
Response:
HTTP/1.1 200 OK
Content-Encoding: application/json
Content-Type: application/json
Server: Jetty(9.4.51.v20230217)
Content-Length: 403
```
The HTTP response header `Content-Encoding` is wrong and unnecessary. The other branches have been fixed by https://github.com/apache/pulsar/pull/16018 and can not cherry-pick into `branch-2.10`, see detail [here](https://github.com/apache/pulsar/pull/16018#issuecomment-1820357348)
Remove the unnecessary HTTP response header: Content-Encoding

[fix] [broker] [branch-2.10] Remove the unnecessary HTTP response header: Content-Encoding when calling getSchema

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespaceAuthZTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAuthZTest.java

This is cherry-picking #22305
Add fine-grain authorization to ns/topic management endpoints so that it can be controlled at a more fine-grain level.
- `TRIM_TOPIC` was missing, this would cause the normal user throw `IllegalStateException` not NotAuthorizedException.
- adding fine-grain authorization to `internalSetProperty`, `internalSetProperties`, `internalGetProperty`, `internalGetProperties`, `internalRemoveProperty`, `internalClearProperties`, `internalUnloadTopic`,`internalGetManagedLedgerInfo`, `internalGetPartitionedStats`, `internalGetPartitionedStatsInternal`, `internalCreateSubscription`, `internalUpdateSubscriptionProperties`, `internalAnalyzeSubscriptionBacklog`, `internalGetSubscriptionProperties`, `internalCreateMissedPartitions`
- Add fine-grain authorization test …

[improve][broker][branch-3.0] Add fine-grain authorization to ns/topic management endpoints

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

If the topic metadata doesn't exist, it will create a new PartitionedTopicMetadata with 0 partition. If user use the cli to create missing partitions, it will response `OK`, which may confuse user.
When the metadata partition is 0, throw the NotFound exception to tell the user the topic not existed.

[improve][admin] Fix the `createMissingPartitions` doesn't response correctly

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerMemoryLimitTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/AbstractBatchMessageContainer.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java

We are using two PulsarClients within the same process to connect to cluster A (maxMessageSize=5M) and cluster B (maxMessageSize=16M), and sometimes the following error occurs.
`Got corrupted payload message size 5251327 at org.apache.pulsar.common.api.proto.MessageIdData@5e940463`
I think the root cause is that the client's `org.apache.pulsar.client.impl.ClientCnx#maxMessageSize` variable is static, which does not support different configurations of two clusters at the same time.
1. change the `org.apache.pulsar.client.impl.ClientCnx#maxMessageSize` variable to be non-static, share this variable only within the same connection.

[fix][client]Fixed getting an incorrect `maxMessageSize` value when accessing multiple clusters in the same process

---

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/AbstractCmdConsume.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/ClientToolTest.java

CmdConsume print publishTime And eventTime info.

[improve][cli] CmdConsume print publishTime And eventTime info.

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pulsar-common/pom.xml

When running Pulsar in Docker on MacOS Apple Silicon M3, I get this error message:
```
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll_aarch_64.so
at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186) ~[io.netty-netty-common-4.1.100.Final.jar:4.1.100.Final]
at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:323) ~[io.netty-netty-transport-classes-epoll-4.1.100.Final.jar:4.1.100.Final]
at io.netty.channel.epoll.Native.<clinit>(Native.java:85) ~[io.netty-netty-transport-classes-epoll-4.1.100.Final.jar:4.1.100.Final]
at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:40) ~[io.netty-netty-transport-classes-epoll-4.1.100.Final.jar:4.1.100.Final]
at org.apache.pulsar.common.util.netty.EventLoopUtil.newEventLoopGrou …
```

[improve][misc] Include native epoll library for Netty for arm64

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumersTest.java

```
2024-03-13T07:47:36,071+0000 [pulsar-inactivity-monitor-25-1] INFO  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://{tenat}/{ns}/{topic name}] Global topic inactive for 86400 seconds, closed repl producers
2024-03-13T07:47:36,073+0000 [pulsar-inactivity-monitor-25-1] INFO  org.apache.pulsar.broker.service.Consumer - Disconnecting consumer: Consumer{subscription=PersistentSubscription{topic=persistent://{tenat}/{ns}/{topic name}, name={subscription}}, consumerId=5, consumerName=082c9, address=/127.0.0.6:34293}
2024-03-13T07:47:36,074+0000 [pulsar-inactivity-monitor-25-1] INFO  org.apache.pulsar.broker.service.Consumer - Disconnecting consumer: Consumer{subscription=PersistentSubscription{topic=persistent://{tenat}/{ns}/{topic name}, name={subscription}}, …
```

[fix] [broker] Close dispatchers stuck due to mismatch between dispatcher.consumerList and dispatcher.consumerSet

---

pip/pip-344.md

- [DIscussion](https://lists.apache.org/thread/z693blcxoqk0mj0rzyt1k7nvy72j18t5)
- [Vote](https://lists.apache.org/thread/4x3rgxygt2x8vtd6lnn53bskdhgmvy2v)

[improve] [pip] PIP-344 Correct the behavior of the public API pulsarClient.getPartitionsForTopic(topicName)

---

pulsar-functions/instance/pom.xml
pulsar-functions/localrun-shaded/pom.xml
pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java
pulsar-functions/runtime/pom.xml
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceStarter.java
pulsar-io/docs/src/main/java/org/apache/pulsar/io/docs/ConnectorDocGenerator.java

PIP: #22181 
Improve CLI user experience.
- Use picocli instead of jcommander in pulsar-function

[improve][cli] PIP-343: Use picocli instead of jcommander in pulsar-function

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroup.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupReportLocalUsageTest.java

1. `org.apache.pulsar.broker.resourcegroup.ResourceQuotaCalculator#needToReportLocalUsage` determine whether sending the current report of local usage can be suppressed (to reduce network communication), when returns true, we need to report the local usage to resourcegroup topic and reset some status, but now we always reset that, please see https://github.com/apache/pulsar/blob/v3.0.3/pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroup.java#L452-L457
2. Now the `maxIntervalForSuppressingReportsMSecs` is in seconds, and is used to comparing with milliseconds, so the local usage is always reported, please see https://github.com/apache/pulsar/blob/v3.0.3/pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceQuotaCalculatorImpl.java#L99-L103 …

[fix][broker] Fix ResourceGroup report local usage

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupConfigListener.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupConfigListenerTest.java

When the Pulsar starts up, the `ResourceGroupConfigListener.java` and `ResourceGroupNamespaceConfigListener.java` cache ResourceGroup and Namespace resources into memory for binding relationships. But this cache is loaded asynchronously, causing Namespace sometimes unable to find ResourceGroup.
```
2023-12-21T09:41:18,749+0000 [ForkJoinPool.commonPool-worker-2] ERROR org.apache.pulsar.broker.resourcegroup.ResourceGroupNamespaceConfigListener - Failed to register namespace my-tenant/my-namespace with resource group rg-1
org.apache.pulsar.client.admin.PulsarAdminException: Resource group does not exist: rg-1
at org.apache.pulsar.broker.resourcegroup.ResourceGroupService.checkResourceGroupExists(ResourceGroupService.java:417) ~[org.apache.pulsar-pulsar-broker-3.1.1.jar:3.1.1]
at …
```

[fix][broker] Fix ResourceGroups loading

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java
pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdSinks.java

Fix typos in CmdSinks class
fix typos: `specfied` => `specified`

[fix][cli] Fix typos in CmdSinks class

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java

**Flaky test logs**
https://github.com/apache/pulsar/actions/runs/8416664128/job/23064867159?pr=22283
**Issue**
- After https://github.com/apache/pulsar/pull/22034, Managedledger will always create a new ledger after the previous closed
- The test `testGetNumberOfEntriesInStorage` force set `ML.state` to `LedgerOpened,` which breaks the mechanism to guarantee no concurrent ledger switching. This leads to an unexpected empty `ledgerInfo` in the ledger list. 
- In expected, the ledgers should be `[{id: 1, entries: 5}, {id: 2, entries: 5}, {id: 3, entries:0}]` 
- Current behavior: `[{id: 1, entries: 5}, {id: 2, entries: 5}, {id: 3, entries:0}, {id: 4, entries:0}]` 
**Reproduce**
You can reproduce the flaky test by running it about 10 times.
Remove the unnecessary ledger switching.
PR in …

[fix] [test] Fix flaky test ManagedLedgerTest.testGetNumberOfEntriesInStorage

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerErrorsTest.java

Fixes #22348 
ManagedLedgerErrorsTest.recoverAfterZnodeVersionError is flaky. The problem can be reproduced consistently by adding a short delay (such as 1000ms) after the first add in the test case.
- remove extra condition since this is flaky due to a race condition
- this depends on having a pending add so that the exception gets propagated to the addEntry operation when the asyncUpdateLedgerIds gets executed

[fix][test] Fix flaky ManagedLedgerErrorsTest.recoverAfterZnodeVersionError

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java

After seeking by timestamp, `hasMessageAvailable()` and `readNext()` could return wrong values.
The 1st bug was a regression introduced by
https://github.com/apache/pulsar/pull/22201, which modifies `startMessageId` to `seekMessageId` before a seek operation is done. However, the previous behavior is also a bug but accidentally works in this case. When seeking by timestamp, the `seekMessageId` is modified to `earliest`, which should not be compared with `lastMessageIdInBroker` because the actual start position is determined by the seek timestamp, not the `earliest` message id.
The 2nd bug was caused by https://github.com/apache/pulsar/pull/9652, when `startMessageIdInclusive()` is configured to create a reader, it could seek to the position of the latest message when …

[fix][client] Fix wrong results of hasMessageAvailable and readNext after seeking by timestamp

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java

Fixes #22365
Introduced by #19035
- Move `skipCondition = null` before `recyclerHandle.recycle(this);`

[fix][broker] Fix OpReadEntry.skipCondition NPE issue

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java
pulsar-common/src/main/java/org/apache/pulsar/client/api/MessageIdAdv.java

Fixes #22352 
Add synchronize protection on bitset operations acknowledge with batch message
- *Added unit test for MessageIdAdvUtilsTest#acknowledge in multi-thread scenario*
PR in forked repository: https://github.com/Shawyeok/pulsar/pull/15

[fix][client] Consumer lost message ack due to race condition in acknowledge with batch message

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java

When executing the method `internalDeleteDynamicConfigurationOnMetadataAsync`. If the `configName` is not a dynamic configuration, the returned exception information is inaccurate.
Modify error message from ` Can't update non-dynamic configuration` to `Can't delete non-dynamic configuration`.

[improve][broker] Optimize web interface deleteDynamicConfiguration return error message

---

pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentBitSet.java

Fixes #22360
ConcurrentBitSet isn't thread safe although it claims this in the javadoc. This is causing concurrency issues in Pulsar. See #22360 for examples.
- Fix usage of StampedLock in ConcurrentBitSet
- modifications must use the write lock
- read operations must use the read lock

[fix][misc] Make ConcurrentBitSet thread safe

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml

- keep Netty and tcnative updated so that we catch possible regressions early and so that we get bug fixes
- release notes:
- https://netty.io/news/2024/03/21/4-1-108-Final.html
- https://netty.io/news/2024/02/13/4-1-107-Final.html
- https://netty.io/news/2024/01/19/4-1-106-Final.html
- https://github.com/netty/netty-tcnative/compare/netty-tcnative-parent-2.0.61.Final...netty-tcnative-parent-2.0.65.Final
- contains a fix https://github.com/netty/netty/pull/13848 to issue https://github.com/netty/netty/issues/13831 reported by @nodece to address #22015
- upgrade Netty to 4.1.108.Final
- This pulls in Netty tcnative version 2.0.65.Final

[improve][misc] Upgrade to Netty 4.1.108 and tcnative 2.0.65

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java

#21940 introduced a way to expire messages based on ledger closure time, but can't exclude unclosed ledgers because the ledger's timestamp has a default value of `0`. This will result in the following warn log when trying to expire an unclosed ledger.
```java
2024-03-25T13:31:30,095 - WARN  - [main:PersistentMessageExpiryMonitor] - [topicname][testCheckExpiryByLedgerClosureTimeWithAckUnclosedLedger] Message expiry failed - mark delete failed
org.apache.bookkeeper.mledger.ManagedLedgerException: org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$MarkDeletingMarkedPosition: Mark deleting an already mark-deleted position. Current mark-delete: 4:1 -- attempted mark delete: 4:-1
Caused by: org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$MarkDeletingMarkedPosition: Mark deleting an …
```

[fix][broker] Avoid expired unclosed ledgers when checking expired messages by ledger closure time

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java

Fixes #22157
The root cause :
There is a race condition between the `consumer.close` and `checkForNewEntries`.
When the consumer is closed, the `waitingCursor` may be empty.
https://github.com/apache/pulsar/blob/ccc2ea67c192b4771c9af30c6eaf994fe01958e5/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java#L298-L313. 
Then after executing line-311, the cursor was added to `waitingCursor`.

[fix][broker] Check cursor state before adding it to the `waitingCursors`

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

Fix typos in PersistentTopic class
fix typos: `migraiton` => `migration`

[fix][broker] Fix typos in PersistentTopic class

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java

When the consumer uses AUTO_CONSUME to subscribe to PatternTopic, we get the `Field 'topic' is not set` error. The root cause is that we incorrectly used the `commandGetSchema` variable, which is a shared variable in the thread, but we're passing it on to another thread, this is unsafe since next request will clear this command data, this case only occurs when the topic does not exist or the scheme does not exist when request `GetSchema`. This issue Introduced from https://github.com/apache/pulsar/pull/20932
```java
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException: {"errorMsg":"java.lang.IllegalStateException: Field 'topic' is not set","reqId":3644652631296588088, "remote":"localhost/127.0.0.1:62361", "local":"/127.0.0.1:62369"}
at …
```

[fix][broker] Fix issue of field 'topic' is not set when handle GetSchema request

---

.github/workflows/ci-trivy-container-scan.yaml

This commit introduces a Github Actions workflow that runs a Trivy container scan on the following Docker containers:
- apachepulsar/pulsar:3.2.0
- apachepulsar/pulsar-all:3.2.0
The workflow runs daily @ 0800 UTC and if it finds any vulnerabilities of HIGH or CRITICAL severity it sends an email including the report to the Pulsar DEV mailing list as well as upload the report to the workflow run in Github.
Our dependencies are currently scanned via the OWASP dependency checker but we have nothing checking on the vulnerability of our published Docker containers. 
As described in the summary, this adds a scheduled workflow that uses [Trivy](https://trivy.dev/) to run a scan against our published Docker containers. 
As always, Github Actions workflow are a pain to test. I have tested this one …

[feat][ci] Add Trivy container scan Github workflow

---

pulsar-io/jdbc/core/pom.xml
pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/BaseJdbcAutoSchemaSink.java
pulsar-io/jdbc/core/src/test/java/org/apache/pulsar/io/jdbc/BaseJdbcAutoSchemaSinkTest.java
pulsar-io/jdbc/sqlite/src/test/java/org/apache/pulsar/io/jdbc/SqliteJdbcSinkTest.java

Currently implemented for `JdbcAutoSchemaSink` connector,  It utilizes `GenericRecord.getField` to find fields with the same table column names. 
https://github.com/apache/pulsar/blob/849cbf3a46cc7e85fca6500c08ab6efb8697f12e/pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/BaseJdbcAutoSchemaSink.java#L140
However, the return value of the [primitive type](https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/GenericObjectWrapper.java#L63-L65) schema is always null. This results in null data being inserted into the table, thereby causing errors.
- For the primitive type of schema, throw a clear exception to inform the user that it is not supported.
- Add `testNotSupportPrimitiveSchema ` to …

[improve][io]: Add validation for JDBC sink not supporting primitive schema

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryController.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/ProducerConsumerBase.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SubscriptionPauseOnAckStatPersistTest.java

When using `Key_Shared` subscription, the broker may discard a part of the result reading from BK to avoid breaking the order of consumption, but this may cause repeated Read-and-discard, which wastes a lot of BK traffic.
- Read entries from the Replay queue.
- The entries can not be sent to the consumer due to they are larger than `consumer.maxReadPosition`
- Nothing was delivered to the client, but the Broker did more and more BK readings.
You can reproduce the issue by `testNoRepeatedReadAndDiscard `
Before reading the BK, filter out the positions that will be discarded.

[improve] [broker] Avoid repeated Read-and-discard when using Key_Shared mode

---

pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionStats.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java
pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerData.java

Fix https://github.com/apache/pulsar/security/code-scanning/20, https://github.com/apache/pulsar/security/code-scanning/7
The implicit casting of source type double/long to narrower destination type int can result in information loss and numeric errors such as overflows.
Ensure that the type of the left-hand side of the compound assignment statement is at least as wide as the type of the right-hand side.
*(or)*
*(or)*
*(example:)*
- *Extended …

[fix][sec] implicit narrowing conversion in compound assignment

---

pulsar-function-go/conf/conf.go
pulsar-function-go/pf/instanceConf.go
pulsar-function-go/pf/instanceConf_test.go
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/go/GoInstanceConfig.java
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java
pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java

Fixes #22349 
PIP: #xyz 
The Go instance doesn't get the full `FunctionDetails`, which makes it missing many features like Java and Python
Pass the `FunctionDetails` string directly to Go and unmarshal it to the `FunctionDetails` struct
- *org.apache.pulsar.tests.integration.functions.go.PulsarFunctionsGoProcessTest*
- *org.apache.pulsar.tests.integration.functions.go.PulsarFunctionsGoThreadTest*
- *org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeTest*
- *Added unit test for config with valid, invalid, and empty "FunctionDetails"*
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/31

[improve][fn] Pass FunctionDetails to Go instance

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java

We should not rollover inactive ledgers when metadata service is invailable.
Checking metadata service is vailable when schedule `checkInactiveLedgerAndRollOver`
- Add UT
`org.apache.bookkeeper.mledger.impl.ManagedLedgerTest#testDontRollOverInactiveLedgersWhenMetadataServiceInvalid`
https://github.com/AnonHxy/pulsar/pull/49

[fix][ml] No rollover inactive ledgers when metadata service invalid

---

buildtools/pom.xml
conf/log4j2.yaml
distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml

Keep up-to-date, and then upgrade the slf4j to 2.x.
Release notes: https://logging.apache.org/log4j/2.x/release-notes.html
- Upgrade log4j2 from 2.18.0 to 2.23.1
- `Configuration.status` from `INFO` to `ERROR` in the `log4j2.yaml`
- Because `Configuration.packages` has been deprecated, the log4j2 prints the warn log, this breaks our test.
- The `simpleclient_log4j2` is no longer updated and doesn't provide `Log4j2Plugins.dat`, we can only suppress this warn log.

[improve][misc] Upgrade log4j2 to 2.23.1

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAuthZTest.java

The main thing is to align the auth operation and put the auth checking operation at the first position.
- `getPartitionedTopicMetadat`, `internalGetPropertiesAsync`, `internalUpdatePropertiesAsync `, `internalRemovePropertiesAsync`, `internalDeletePartitionedTopic`, `internalGetSubscriptions`, 
`internalGetStatsAsync`, `internalSkipMessages`, `internalSkipAllMessages`, `internalPeekNthMessageAsync`, `internalExamineMessageAsync`, `internalExpireMessagesByPosition`, `internalResetCursorAsync`, `internalResetCursorOnPosition`, `internalGetMessageById`,
`internalExpireMessagesByTimestamp`
And add related auth test.

[improve][admin] Align the auth and check it at the first place for topic related API 

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java

- `brokerClientAuthenticationParameters` and `bookkeeperClientAuthenticationParameters` shouldn't be logged by default since they could include secrets
- exclude the fields from the `toString` implementation by added `@ToString.Exclude` annotations

[improve][broker] Don't log brokerClientAuthenticationParameters and bookkeeperClientAuthenticationParameters by default

---

docker/pulsar/Dockerfile

https://github.com/apache/pulsar/pull/21207 introduces the `networkaddress.cache.negative.ttl config` config, which also introduces a bug that appends the "\\" at the end:
```
2024-04-02T15:00:10,494+0000 [pulsar-perf-producer-exec-1-1] INFO  org.apache.pulsar.testclient.PerformanceProducer - Started performance test thread 0
2024-04-02T15:00:10,671+0000 [pulsar-perf-producer-exec-1-1] WARN  org.apache.pulsar.common.util.netty.DnsResolverUtil - Cannot get DNS TTL settings
java.lang.NumberFormatException: For input string: "1 RUN apt-get -y --purge autoremove"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
at java.lang.Integer.valueOf(Integer.java:973) ~[?:?]
at …
```

[fix][build] Fix networkaddress.cache.negative.ttl config

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java
pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java
pulsar-broker/src/main/java/org/apache/pulsar/PulsarVersionStarter.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactorTool.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionWorkerStarter.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketServiceStarter.java

Right now, the command with `-h` doesn't work:
```
❯ ./bin/pulsar initialize-cluster-metadata -h                                                    
picocli.CommandLine$MissingParameterException: Missing required options: '--cluster=<cluster>', '--web-service-url=<clusterWebServiceUrl>'
Exception in thread "main" picocli.CommandLine$MissingParameterException: Missing required options: '--cluster=<cluster>', '--web-service-url=<clusterWebServiceUrl>'
at picocli.CommandLine$MissingParameterException.create(CommandLine.java:18661)
at picocli.CommandLine$MissingParameterException.access$21200(CommandLine.java:18649)
at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13651)
at picocli.CommandLine$Interpreter.parse(CommandLine.java:13614)
at …
```

[fix][cli] Fix help option

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v3/Transactions.java

Fixes #22409 
If Admin API request is sent to the broker and it responds with 307-redirect (for example in case of the bundle is not served by this broker) then ERROR is written into the broker log file. And there are quite a lot of these errors.
```
> GET https://current-pulsar-server:8443/admin/v2/non-persistent/tenant/namespace/0x00000000_0x40000000
< HTTP/1.1 307 Temporary Redirect
< Date: Tue, 02 Apr 2024 11:19:32 GMT
< Location: https://another-pulsar-server:8443/admin/v2/non-persistent/tenant/namespace/0x00000000_0x40000000?authoritative=false
< Content-Length: 0
```
broker log:
```
11:18:57.455 [pulsar-web-36-6] ERROR org.apache.pulsar.broker.admin.v2.NonPersistentTopics - [superuser] Failed to list topics on namespace bundle tenant/namespace/0x00000000_0x40000000 …
```

[fix][broker] Fix invalid condition in logging exceptions

---

pulsar-broker-auth-oidc/src/main/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenID.java
pulsar-broker-auth-oidc/src/test/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenIDIntegrationTest.java

Fixes #22419
See #22419. "alg" field is optional in JWK spec. 
- allow missing "alg" field
- add test case

[fix][broker] Support OIDC providers with JWK without alg field set in keys

---

src/rename-netty-native-libs.cmd
src/rename-netty-native-libs.sh

- some Netty native libraries weren't renamed as part of the shading
- add missing libraries to renaming
- keep the Powershell script in sync with the bash script

[fix][misc] Rename all shaded Netty native libraries

---

pom.xml

Java 22 has been released. Lombok 1.18.32 comes with Java 22 support.
Lombok changelog: https://projectlombok.org/changelog
Upgrade Lombok to 1.18.32

[improve][build] Upgrade Lombok to 1.18.32 for Java 22 support

---

.github/ISSUE_TEMPLATE/flaky-test.yml

The labels in the flaky test issue template are invalid.
Use the correct labels in the template.

[fix][ci] Fix labels for flaky test GitHub issue template

---

src/rename-netty-native-libs.cmd

- follow up on #22415 where the typo slipped in

[fix][build] Fix typo in rename script for windows cmd

---

build/run_unit_group.sh
buildtools/src/main/java/org/apache/pulsar/tests/AnnotationListener.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
pom.xml
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiMultiBrokersTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAuthZTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerConsumerInternalTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndWithoutBatchIndexAckTest.java

Move most flaky tests to flaky group until they are fixed since this causes a lot of delays and unnecessary builds.
Issues to track the moved tests:
- #22351
- #22428
- #22429
- #22430 
- #22422
- #22431
- #21536
- #22432
The solution for excluding methods added to the "flaky" group at the method level with `@Test(groups = "flaky")` didn't work. This PR contains changes to ensure that flaky test methods are isolated.
Flaky group was previously only support in the pulsar-broker module. However some flaky tests are in the managed-ledger module. This PR contains changes to run tests in all other modules too.

[improve][test] Move most flaky tests to flaky group

---

docker/pulsar/Dockerfile

A default user was added to the docker image #21695. The problem is that the home directory for the user is invalid.
This causes issues such as #22440 .
The home directory for the `pulsar` user is `/home/pulsar`, which is invalid.
```
❯ docker run --rm -it apachepulsar/pulsar:3.0.4 bash -c "cat /etc/passwd|grep pulsar"
pulsar:x:10000:0::/home/pulsar:/bin/sh
```
Make the home directory `/pulsar/data` for the `pulsar` user.

[improve][misc] Specify valid home dir for the default user in the Ubuntu based docker image

---

docker/pulsar/Dockerfile

In #22446, the home directory for the default user `pulsar` is set to `/pulsar/data` in the Ubuntu based image. For consistency, it makes sense to use the same directory in the Alpine based image.
In the Alpine image `adduser` seems to create the `/home/pulsar` directory so the directory is valid and the problem is different than with the Ubuntu image used in the maintenance branches.
Specify /pulsar/data as the home dir for the created default user.

[improve][misc] Specify /pulsar/data as the home dir for the user in the Alpine based image

---

.github/actions/tune-runner-vm/action.yml
.github/workflows/pulsar-ci.yaml
README.md
build/build_java_test_image.sh
pom.xml

- drop tuning for docker since it's no longer needed
- image squashing is deprecated and it's no longer used in the build to build the docker image
- sometimes builds have been failing due to the docker service not restarting

[improve][ci] revisit tune-runner-vm action,  drop tuning for docker

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java

https://github.com/apache/pulsar/pull/8976 introduced an `enableNamespaceIsolationUpdateOnTime` config, which is useless after https://github.com/apache/pulsar/pull/15527. This config actually does not make sense because it should always be true, while it's false by default just to keep the meaningless compatibility.
Deprecate this config and strength the
`brokerNamespaceIsolationPoliciesUpdateOnTime` test.

[improve][broker] Deprecate unused enableNamespaceIsolationUpdateOnTime config

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java

Fixes #22435
When the backlog size > `managedLedgerCursorBackloggedThreshold` (default 1000), the cursor will be set inactive first. so this will cause the non-durable cursor not to add to the `waiting cursor.` This leads to the consumer stopping to receive messages.
https://github.com/apache/pulsar/blob/2469b97b7e4de10fec64cc7ff1f4f46a410ad125/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L3082-L3090
https://github.com/apache/pulsar/blob/2469b97b7e4de10fec64cc7ff1f4f46a410ad125/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L3816-L3824

[fix][broker] Fix consumer stops receiving messages when with large backlogs processing

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

These notes are introduced by https://github.com/apache/pulsar/pull/9490, and the related code has been removed. We have better remove these remaining notes in case of confusion.
Remove notes.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/46

[cleanup][broker] remove useless code comment

---

docker/pulsar/Dockerfile

```
58a588ac742d:/pulsar# ./bin/pulsar-daemon start zookeeper
doing start zookeeper ...
starting zookeeper, logging to /pulsar/logs/pulsar-zookeeper-58a588ac742d.log
Note: Set immediateFlush to true in conf/log4j2.yaml will guarantee the logging event is flushing to disk immediately. The default behavior is switched off due to performance considerations.
ps: unrecognized option: p
BusyBox v1.36.1 (2023-11-07 18:53:09 UTC) multi-call binary.
Usage: ps [-o COL1,COL2=HEADER] [-T]
Show list of processes
-o COL1,COL2=HEADER	Select columns for display
-T
```
ps command doesn't include `-p` option.
- Add `procps` package to fix the ps command
- Set the `PULSAR_PID_DIR` environment variable, and default to `/pulsar/logs` in the docker environment.

[fix][build] Fix ps command

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespaceAuthZTest.java

Add operation authentication test for namespace API.
Check AuthAction and Operation for API
Covered API: `setProperties`, `removeProperty`, `clearProperties`, `getProperty`, `getTopics`, `getBundles`, `unloadNamespaceBundle`, `splitNamespaceBundle`, `grantPermissionOnNamespace`, `getPermissions`, `revokePermissionsOnNamespace`, `grantPermissionOnSubscription`, `getPermissionsOnSubscription`, `revokePermissionsOnSubscription`, `clearNamespaceBacklog`, `unsubscribeNamespace`, `unsubscribeNamespaceBundle`, `upload`, `download`, `listPackages`, `listPackageVersions`, `getMetadata`,
`setBookieAffinityGroup`, `getBookieAffinityGroup`, `deleteBookieAffinityGroup`.
*(or)*
This …

[improve][test] Add operation authentication test for namespace API

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/web/WebServiceTest.java

- it's not a good practice to use curl in Java tests
- the previous tests leaked some InputStream instances
- replace `curl` usage with Java's built-in `HttpURLConnection` http client
- use try-finally blocks for closing InputStreams

[improve][test] Replace usage of curl in Java test and fix stream leaks

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java

msgDrop record message drop rate when non-persist message reached max concurrent-message limit in producer. 'valueRate' in msgDrop stands for message drop rate, and 'rate' stands for batch drop rate, and shoud get valueRate in publisherStats. 
get valueRate instead

[fix][broker] Fix message drop record in producer stat

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java
pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java

Right now, broker failed to create schema-consumer if the topic's schema ledger is already deleted and broker is not able to recover that ledger. In that case, client will keep receiving below error message and will never be able to consumer on that topic.
```
2024-04-09T23:17:00,140 - INFO  - [pulsar-client-io-35-3:ConsumerImpl] - [persistent://my-prop/ns1/t1][test] Subscribing to topic on cnx [id: 0x59ed6366, L:/127.0.0.1:60336 - R:localhost/127.0.0.1:60330], consumerId 1
2024-04-09T23:17:00,141 - INFO  - [pulsar-io-8-1:ServerCnx] - [[id: 0x92bca72e, L:/127.0.0.1:60330 - R:/127.0.0.1:60336]] Subscribing on topic persistent://my-prop/ns1/t1 / test. consumerId: 1
2024-04-09T23:17:00,142 - WARN  - [PulsarTestContext-executor-OrderedExecutor-0-0:ServerCnx] - …
```

[improve][broker] Recover susbcription creation on the broken schema ledger topic

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

Fixes #22474
Currently, when backlog quota limit exceeded and producers still send messages, it generates lot of logs in short period of time. The logs are logged with `info`. We can use `debug` instead of `info`.
- Replaced the `info` with `debug` for logs when the backlog quota limit exceeded.
This change is a rework/code-cleanup without any test coverage.

[improve][broker] backlog quota exceed limit log replaced with `debug`

---

pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/PulsarAdminBuilder.java
pulsar-client-admin/pom.xml
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnectorProvider.java
pulsar-client-admin/src/test/java/org/apache/pulsar/client/admin/internal/PulsarAdminGzipTest.java

Gzip compression can reduce the amount of bytes transferred in the Pulsar Admin API. 
The broker-side support for Gzip compression was added as part of #21667. 
This PR adds support for Gzip compression to the Pulsar Admin Java client. 
- By default, include "Accept-Encoding: gzip" header in HTTP requests
- Support for controlling whether the header is added or not

[feat][admin] Enable Gzip Compression by Default in Admin Client

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java

https://github.com/apache/pulsar/pull/8101 adds the null check for `LeaderElectionService` in `searchForCandidateBroker` to avoid a null leader election service is accessed because the broker service starts before the leader election service. However, https://github.com/apache/pulsar/pull/8273 adds the null check again.
Only retain one null check.

[improve][broker] Reduce the duplicated null check for LeaderElectionService

---

managed-ledger/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java

- impacts ManagedLedgerBkTest.tearDown and ManagedLedgerFactoryChangeLedgerPathTest.tearDown
```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.278 s <<< FAILURE! - in org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryChangeLedgerPathTest
Error:  org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryChangeLedgerPathTest.tearDown  Time elapsed: 0.186 s  <<< FAILURE!
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ExecutorService.shutdownNow()" because "this.executor" is null
at org.apache.bookkeeper.test.BookKeeperClusterTestCase.tearDown(BookKeeperClusterTestCase.java:225)
```
and 
```
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.573 s <<< FAILURE! - in org.apache.bookkeeper.mledger.impl.ManagedLedgerBkTest …
```

[fix][test] Fix NPE in BookKeeperClusterTestCase tearDown

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java

- this test is flaky, let's categorize it as flaky until it is stable
- logs for [most recent case](https://github.com/apache/pulsar/actions/runs/8664728390/job/23762246664?pr=22494#step:11:716): https://gist.github.com/lhotari/25d618984841eae4b7fd51ae3908e5d7
- Move ExtensibleLoadManagerImplTest to flaky tests

[fix][test] Move ExtensibleLoadManagerImplTest to flaky tests

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/OwnershipCacheTest.java

https://github.com/apache/pulsar/pull/11012 removes all uses of the `NamespaceBundleFactory` field in `OwnershipCache` and https://github.com/apache/pulsar/pull/17768 removes that field. However, the constructor of `OwnershipCache` still has the
`NamespaceBundleFactory` parameter.
Remove that parameter from the constructor.

[cleanup][broker] Remove unused NamespaceBundleFactory parameter when creating OwnershipCache

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java

#22351
#22432
After #22034, the calculation method for the ledger number should be: `totalEntries / entriesPerLedger + 1`, However, since the creation of the ledger is asynchronous, sometimes the last ledger is not created before the function returns.
https://github.com/apache/pulsar/blob/57a616eaa79096af5b49db89c99cd39ccc94ec00/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L1775-L1778
- Add `retryStrategically((test) -> ledger.getState() == ManagedLedgerImpl.State.LedgerOpened,10, 200)` to make sure last ledger creates success.
- Modify the ledger quantity and assertions related to `makePosition`.
- After running it 100 times locally, this test is stable.

[fix][test] Flaky-test: testMessageExpiryWithTimestampNonRecoverableException and testIncorrectClientClock

---

bouncy-castle/bc/LICENSE
distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml

Upgrade Bouncy Castle to 1.78 to address CVEs
https://bouncycastle.org/releasenotes.html#r1rv78
- https://www.cve.org/CVERecord?id=CVE-2024-29857 (reserved)
- https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6613079
- https://www.cve.org/CVERecord?id=CVE-2024-30171 (reserved)
- https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6613076
- https://www.cve.org/CVERecord?id=CVE-2024-30172 (reserved)
- https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6612984
PR in forked repository: https://github.com/izumo27/pulsar/pull/4

[fix][sec] Upgrade Bouncycastle to 1.78

---

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java
pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java

The current implementation of Kafka source connector, that `KafkaRecord` does not implement the `fail()` method. 
https://github.com/apache/pulsar/blob/bbae607fb174d2f6f9b94d897903b8d24cece7dc/pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java#L222
If `PulsarSink` send a message to pulsar failed, will call `record.fail()`.  
https://github.com/apache/pulsar/blob/43a989862f548fa3f67708a5fff62eb764af878c/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java#L194-L196
But because KafkaRecord does not implement it, this `futures` will never end.
https://github.com/apache/pulsar/blob/495b141c7bebc0356297546e9db88c9e087f5039/pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaAbstractSource.java#L178
This causes the …

[fix][io] Kafka Source connector maybe stuck

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorGlobalNSTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java

Noticed that Replicated Topic is not unloaded upon setNamespaceReplicationClusters when ExtensibleLoadManager is enabled. 
- Fix unloading bundles upon namespace policy update. (isNamespaceBundleOwned didn't check the bundle ownership properly when ExtensibleLoadManager is enabled.)
- Do not replicate ExtensibleLoadManager internal topics (bundle state, broker and bundle load data topics) because they are only used for the local cluster.
- Copy ReplicatorGlobalNSTest for ExtensibleLoadManager.

[fix][broker] Fix Replicated Topic unload bug when ExtensibleLoadManager is enabled

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java

The `runtimeFlags` is been used to allow user to customize the java options for both Kubernetes Runtime & Process runtime, the config can be passed by YAML or JSON via pulsar-admin, but not been exposed as any option in CLI.
*(or)*
*(or)*
*(example:)*

[improve][fn] Expose `RuntimeFlags` as CLI option for Pulsar Functions and Connectors

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java

Fixes #22470
Related to #17887. After executing the test method once does not clean up the pulsarClient, causing the AutoConsumeSchema to be reused. When the schemaMap in the first AutoConsumeSchema is set to AvroSchema.
https://github.com/apache/pulsar/blob/982d94d15465ff5fcea192e9a8b6b25d2d1c55b6/pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java#L149-L169
https://github.com/apache/pulsar/blob/982d94d15465ff5fcea192e9a8b6b25d2d1c55b6/pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java#L202-L206
The second execution of the test method will also use the AvroSchema instead of the JsonSchema. Because the schema will not be fetched again.
https://github.com/apache/pulsar/blob/af1360fb167c1f9484fda5771df3ea9b21d1440b/pu …

[fix][test] SchemaMap in AutoConsumeSchema has been reused

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java

Referring to: https://github.com/apache/pulsar/issues/22477#issuecomment-2050141202
*(or)*
*(or)*
*(example:)*

[improve] Make the config `metricsBufferResponse` description more effective

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsServlet.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/GzipHandlerUtil.java
pulsar-broker-common/src/test/java/org/apache/pulsar/broker/web/GzipHandlerUtilTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PulsarPrometheusMetricsServlet.java
pulsar-broker/src/test/java/org/apache/pulsar/PrometheusMetricsTestUtil.java

gzip compression is now enabled by default for the /metrics endpoint. To further optimize /metrics endpoint 
performance, this PR adds sharing of the gzip compressed result with the in progress results so that concurrent requests will share the result of a single gzip compression task.
This is a follow up on #22494 and ensures that gzip compression doesn't add extra load when multiple clients are making requests to the /metrics endpoint and requesting gzip encoding.
- refactor solution to asynchronously compress the Netty buffer 
- add helper for compressing a Netty buffer in GZIP format using JVM's default java.util.zip.Deflater class and nio ByteBuffer support that has been added in Java 11.

[improve][broker] Optimize gzip compression for /metrics endpoint by sharing/caching compressed result

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImplTest.java

ShadowManagedLedgerImplTest.testShadowWrites is very flaky and fails often.
This issue has been reported as #22345.
Move the test to the flaky group so that it doesn't block the build.

[improve][test] Move ShadowManagedLedgerImplTest to flaky tests

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java

Check the broker is available for the SLA monitor bundle when the `ExtensibleLoadManager` is enabled to ensure the behavior same.
* Remove the `candidateBroker.substring(candidateBroker.lastIndexOf('/') + 1);`, because the https://github.com/apache/pulsar/pull/21894 already changed format.
* Check the broker is available for the SLA monitor bundle when the `ExtensibleLoadManager` is enabled

[fix][broker] Check the broker is available for the SLA monitor bundle when the ExtensibleLoadManager is enabled

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java

Found a deadlock case in SystemTopicBasedTopicPoliciesService during NamespaceEventsSystemTopicFactory init
```
Deadlock case
"thread-1":
t1: prepareInitPoliciesCacheAsync(SystemTopicBasedTopicPoliciesService.java:338) (acquired the `policyCacheInitMap` lock)
t2: createSystemTopicFactoryIfNeeded(SystemTopicBasedTopicPoliciesService.java:599) (waiting for the `synchronized (this)` lock)
"thread-2":
t1: addOwnedNamespaceBundleAsync(SystemTopicBasedTopicPoliciesService.java:322) (acquired the `synchronized (this)` lock
t2: prepareInitPoliciesCacheAsync(SystemTopicBasedTopicPoliciesService.java:338) (waiting for the `policyCacheInitMap` lock)
```
- Use a separate lock for the singleton NamespaceEventsSystemTopicFactory init by org.apache.commons.lang3.concurrent.LazyInitializer.
*If the box …

[fix][broker] Fix a deadlock in SystemTopicBasedTopicPoliciesService during NamespaceEventsSystemTopicFactory init

---

pom.xml

- keep version up-to-date
- newer versions typically fix bugs in reporting such as false positives
- changelog: https://github.com/jeremylong/DependencyCheck/blob/main/CHANGELOG.md#change-log
- Upgrade dependency-check-maven.version to 9.1.0

[improve][build] Upgrade OWASP Dependency check version to 9.1.0

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionTest.java

In Key_Shared mode, the variable `recentlyJoinedConsumers` of `PersistentStickyKeyDispatcherMultipleConsumers` will always be null when enabling the config below.  #22245 introduced a NPE if set `allowOutOfOrderDelivery` to true, which will lead dispatching stuck.
```
// The default value is false.
pulsarClient.newConsumer().keySharedPolicy(KeySharedPolicy.setAllowOutOfOrderDelivery(true))
```
**error logs**
```
Message: org.apache.bookkeeper.mledger.ManagedLedgerException: Other exception
Stacktrace:
org.apache.pulsar.broker.service.BrokerServiceException: org.apache.bookkeeper.mledger.ManagedLedgerException: Other exception
at org.apache.pulsar.broker.service.persistent.PersistentSubscription$6.findEntryFailed(PersistentSubscription.java …
```

[fix][broker] Fix NPE causing dispatching to stop when using Key_Shared mode and allowOutOfOrderDelivery=true

---

tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedInputStreamImpl.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImplV2.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/BlobStoreBackedInputStreamTest.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderStreamingTest.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderTest.java

In the implementation of tiered storage, if a `blob` in blob storage is lost unexpectedly, reading it will cause a `NullPointerException`, causing a subscription block.
```
116 Caused by: java.lang.NullPointerException
117 2023-08-28T02:35:23,544+0000 [offloader-OrderedScheduler-0-0] WARN  org.apache.bookkeeper.mledger.impl.OpReadEntry - [test/test/persistent/test-partition-1][test-consume] read failed from ledger at position:1358058:0
118 org.apache.bookkeeper.mledger.ManagedLedgerException: Other exception
119 Caused by: java.io.IOException: Error reading from BlobStore
120         at org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreBackedInputStreamImpl.refillBufferIfNeeded(BlobStoreBackedInputStreamImpl.java:91) ~[?:?]
121         at …
```

[improve][offload] Apply autoSkipNonRecoverableData configuration to tiered storage

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerInternalClientConfigurationOverrideTest.java

Fixes https://github.com/apache/pulsar/issues/22534
Again we have a broken version compatibility change in Pulsar which is causing issues for systems which are running old Pulsar versions and upgrading them to >=2.10.
After upgrading from Pulsar-2.7 to >= Pulsar-2.10 broker, broker is not considering various broker configuration threshold and one of them is `maxUnackedMessagesPerSubscription`. We have broker configured with `MaxUnackedMessagesPerSubscription=200000` and after sub reaches 200K unack messages, broker blocks the dispatching. It was working fine till broker-2.7 but it stopped working after upgrading to Pulsar-2.10 and higher version.
```
subscriptions" : {
"UnackMsgConsumersSubscription" : {
"msgRateOut" : 41.66667806597534,
"msgThroughputOut" : 63924.01748854578, …
```

[fix][broker] Fix broken topic policy implementation compatibility with old pulsar version

---

conf/broker.conf
conf/functions_worker.yml
conf/proxy.conf
conf/standalone.conf
conf/websocket.conf
pom.xml
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/JettyRequestLogFactory.java
pulsar-broker/pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/web/WebServiceOriginalClientIPTest.java
pulsar-broker/src/test/resources/log4j2.xml
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/WorkerServer.java
pulsar-proxy/pom.xml
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyServiceStarter.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/WebServer.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyOriginalClientIPTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyServiceStarterDisableZeroCopyTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyServiceStarterTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyServiceTlsStarterTest.java
pulsar-proxy/src/test/resources/log4j2.xml
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/ProxyServer.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketProxyConfiguration.java

Fixes #22512
See #22512. In some environments, there's a HTTP reverse proxy in front of Pulsar Proxy or Pulsar Broker and there's a desire to log the actual client IP addresses instead of the reverse proxy's IP address. For this purpose, it's now possible to configure the broker or proxy to trust the value of the X-Forwarded-For header. 
X-Forwarded-For support is also useful when Pulsar Proxy is in front of Pulsar Broker. Pulsar Proxy already adds the X-Forwarded-For headers to the request. This change will allow propagating the original client IP from the Pulsar Proxy to the Pulsar Broker as well.
For supporting Layer 4 (TCP) proxies, this PR also includes[ HA Proxy Protocol v1 and v2 support](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) for resolving the original client …

[improve][broker] Support X-Forwarded-For and HA Proxy Protocol for resolving original client IP of http/https requests

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AuthZTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAuthZTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TransactionAndSchemaAuthZTest.java

Add test for topic policies.
- Add test for topic policy.
- Separate transaction and schema test to a new class 

[improve][test] Add topic policy test for topic API

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

Since managedLedger does not create a new ledger when recovering a terminated managed ledger, lead to getValidPositionAfterSkippedEntries will get an NPE.
```
org.apache.bookkeeper.mledger.ManagedLedgerException$MetaStoreException: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.apache.bookkeeper.client.LedgerHandle.getId()" because "this.currentLedger" is null
Caused by: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.apache.bookkeeper.client.LedgerHandle.getId()" because "this.currentLedger" is null
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) …
```

[fix][ml] Fix NPE of getValidPositionAfterSkippedEntries when recovering a terminated managed ledger

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml

Before releasing Pulsar 3.3.0, there has been a plan to upgrade Bookkeeper version to 4.17.0 so that GRPC and Protobuf versions can be upgraded.
- Upgrade Bookkeeper version to 4.17.0
- Upgrade GRPC version to 1.56.0
- Upgrade Protobuf version to 3.22.3

[improve][misc] Upgrade to Bookkeeper 4.17.0

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/LeastResourceUsageWithWeight.java

Info logs are not printed in `LeastResourceUsageWithWeight` even if `loadBalancerDebugModeEnabled` is true.
Fix the TODO in `LeastResourceUsageWithWeight`.

[improve][broker] Apply loadBalancerDebugModeEnabled in LeastResourceUsageWithWeight

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/BrokerSelectionStrategyFactory.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/strategy/CustomBrokerSelectionStrategyTest.java

When users want to extend the `ExtensibleLoadManagerImpl`, the `BrokerSelectionStrategy` cannot be customized, so users have to write much duplicated code for a customized broker selection strategy.
Add a stable interface `BrokerSelectionStrategyFactory` and implements this interface in `ExtensibleLoadManagerImpl` with the default implementation that returns a `LeastResourceUsageWithWeight` instance by default. Add `CustomBrokerSelectionStrategyTest` to show how to customize the broker selection strategy and verify it works.

[improve][broker] Make BrokerSelectionStrategy pluggable

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TopicResources.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationTest.java

Can't delete tenant for v1.  Find this bug when fixing #22547. 
```
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/admin/policies/p1/c1'
at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:115)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
... 12 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
at [Source: (byte[])""; line: 1, column: 0]
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(Deserializat …
```

[fix][admin] Fix can't delete tenant for v1

---

distribution/shell/src/assemble/LICENSE.bin.txt
pulsar-client/pom.xml

Fixes: #21962
#20700 marked the swagger-annotation with scope `provided` in the `pulsar-client` pom. The side effect is that the library is not getting included when the shading happens, though its symbols are being relocated. That is causing warning with Gradle bulds and errors with Bazel.
Make sure the swagger annotations are included in the shaded jar (with the renamed symbols).

[fix] Include swagger annotations in shaded client lib

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/elastic/ElasticSearchJavaRestClient.java
pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/opensearch/OpenSearchHighLevelRestClient.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java

We observed that the traffic passing through the `es-sink` was amplified by 8 times, and it didn't work even if enable `compression`.
The root cause is here configure `response` compression not `request`. Refer to this [discuss](https://discuss.elastic.co/t/compress-elasticsearch-bulkrequest-using-java-high-level-rest-client-and-bulk-processor/280425/3).
https://github.com/apache/pulsar/blob/45fdbac0fa9d535d3d3326ab504321210d8d45a4/pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/elastic/ElasticSearchJavaRestClient.java#L83
- Set compression for request.
Before this change: 
After this change:

[fix][io] CompressionEnabled didn't work on elasticsearch sink

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Replicator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java

There is a race condition that makes an orphan replicator in the original owner of a topic, and causes the new owner of the topic can not start a replicator due to `org.apache.pulsar.broker.service.BrokerServiceException$NamingException Producer with name 'pulsar.repl.{local_cluster}-->{remote_cluster}' is already connected to topic`.
**Scenario 1**
- Thread-1: start/restart the producer of the replicator.
- Thread-2: unloading bundles.
**Scenario 2**
- Thread-1: start a new replicator after updated `replication_clusters`.
- Thread-2: unloading bundles.
After we solved the scenario 1 by https://github.com/apache/pulsar/pull/21946, the current PR is focusing on the scenario 2:
Current PR is focusing on Scenario 2.
**Steps of Scenario 2**
| time  | `thread enable replication` |  thread …

[fix] [broker] Part-2: Replicator can not created successfully due to an orphan replicator in the previous topic owner

---

buildtools/pom.xml
distribution/server/pom.xml
distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/pom.xml
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-client-all/pom.xml
pulsar-functions/instance/pom.xml
pulsar-functions/localrun/pom.xml
pulsar-functions/runtime-all/pom.xml
pulsar-io/alluxio/pom.xml
pulsar-io/hdfs2/pom.xml
pulsar-io/hdfs3/pom.xml
pulsar-io/rabbitmq/pom.xml
pulsar-io/rabbitmq/src/test/java/org/apache/pulsar/io/rabbitmq/RabbitMQBrokerManager.java
pulsar-io/solr/pom.xml
structured-event-log/pom.xml
tiered-storage/file-system/pom.xml

Keep up-to-date, and this version supports [fluent logging api](https://www.slf4j.org/manual.html#fluent).
- Upgrade slf4j from 1.7.32 to 2.0.13
- Upgrade qpid-server to adapt the slf4j 2
- Use log4j-slf4j2-impl instead log4j-slf4j-impl
- Exclude the log4j-slf4j-impl and slf4j from some library

[improve][misc] Upgrade slf4j to 2.0.13

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorTest.java

Fixes #22575
See #22575 . This is a bug introduced by #22521. While fixing the bug, another related bug was revealed where it resulted in a EOFException when reading the gzipped content. 
While working on this PR, another unrelated issue in the metrics output buffer pre-allocation was detected. It is also fixed in this PR. The impact of this is about 2x direct memory allocation since the pre-allocated buffers weren't used at all.
- Properly handle boundary conditions where the compression buffer is full. 
- Properly handle the compression state and usage of java.util.zip.Deflater
- Properly handle writing of the gzip trailer
- Fix unrelated issue in CompositeBuffer pre-allocation. Use the `capacity` method to pre-allocate the buffer.
- The problem was that `.setIndex(0, chunkSize)` should …

[fix][broker] Fix BufferOverflowException and EOFException bugs in /metrics gzip compression

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java

Unit test group 1 fails often with OOME. ([example](https://github.com/apache/pulsar/actions/runs/8832004077/job/24248784784?pr=22585))
The issue is most like related to https://github.com/apache/pulsar/pull/21495 and org.apache.pulsar.broker.service.ReplicatorSubscriptionTest#testWriteMarkerTaskOfReplicateSubscriptions .
Disable the test until the problem has been resolved.

[improve][ci] Disable test that causes OOME until the problem has been resolved

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/MultiBrokerTestZKBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/SLAMonitoringTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LeaderElectionServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/BundleSplitterTaskTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AdvertisedAddressTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BkEnsemblesTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerBookieIsolationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MaxMessageSizeTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicOwnerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/coordinator/TransactionMetaStoreTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/ClientDeduplicationFailureTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionE2ESecurityTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionPublishTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionTlsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarWorkerAssignmentTest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/AbstractPulsarE2ETest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionAdminTest.java
pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionTlsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/zookeeper/ZookeeperServerTest.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/TestZKServer.java

- TestNG keeps a reference to the test instance and this will cause a OOME in some cases
- Clear instances in the test classes that showed up as dominators in a heap dump

[fix][test] Clear fields in test cleanup to reduce memory consumption

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespaceAuthZTest.java

Namespace admin API should return `NotAuthorizedException` when verification of permissions failed, but `SetOffloadThresholdInSeconds` return `ServerSideErrorException`.
* Return correct exception response.
* Using `validateNamespacePolicyOperation` instead of `validateNamespacePolicyOperationAsync` to avoid exceptions being ignored
*(or)*
*(or)*
*(example:)*
*If the box was checked, …

[fix][admin] Fix namespace admin api exception response

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaWithAuthTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthenticatedProducerConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyAuthorizationTest.java

The get/grant/revoke permissions to a non-existed topic will be ok which may confuse the user. So it's better to check the topic existed before the grant permissions.

[improve][admin] Check if the topic existed before the permission operations

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java

`TestAuthorizationProvider2` is useless, no need to retain.
Remove it.

[cleanup] [test] remove useless TestAuthorizationProvider2

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java

A batch operation might cause a  connection to break which is a severe issue. It's better to log a warning whenever this happens instead of silently ignoring it.
- Log a warning when a batch operation fails with connectionloss.
- Add summary information to the log message.

[improve][meta] Log a warning when ZK batch fails with connectionloss

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerServiceException.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

When topic is closing and throws an exception, the exception isn't logged and it's swallowed.
It's better to propagate the cause in TopicBusyException in these cases.
- Add support for cause exception to TopicBusyException
- Propagate the cause when closing throws an exception

[improve][broker] Propagate cause exception in TopicBusyException when applicable

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/TableViewLoadDataStoreImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerCloseTest.java

Fixes https://github.com/apache/pulsar/issues/22569
`BrokerService#closeAsync` calls `unloadNamespaceBundlesGracefully` to unload namespaces gracefully. With extensible load manager, it eventually calls `TableViewLoadDataStoreImpl#validateProducer`:
```
BrokerService#unloadNamespaceBundlesGracefully
ExtensibleLoadManagerWrapper#disableBroker
ExtensibleLoadManagerImpl#disableBroker
ServiceUnitStateChannelImpl#cleanOwnerships
ServiceUnitStateChannelImpl#doCleanup
TableViewLoadDataStoreImpl#removeAsync
TableViewLoadDataStoreImpl#validateProducer
```
In `validateProducer`, if the producer is not connected, it will recreate the producer synchronously. However, since the state of `PulsarService` has already been changed to `Closing`, all connect or lookup requests will fail with …

[fix][broker] Avoid being stuck when closing the broker with extensible load manager

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

```
2024-04-26T09:36:28,397 - ERROR - [ForkJoinPool.commonPool-worker-10:PersistentTopic] - [persistent://pulsar/global/removeClusterTest/__change_events] Error closing clients
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Executor is shutting down
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:823) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:803) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.thenRunAsync(CompletableFuture.java:2204) ~[?:?]
at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$delete$44(PersistentTopic.java:1430) …
```

[fix][broker] Continue closing even when executor is shut down

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicTxnBufferSnapshotService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicPoliciesService.java

There doesn't seem to be a proper handling for TopicPoliciesService shutdown.
This would be needed to allow the Pulsar broker to shutdown gracefully.
This also prevents memory leaks in tests. This problem was detected during the investigation of test OOMEs.
See #22588 for details.
- Add close method to TopicPoliciesService and implement it
- Prevent creating new cached writers or readers after the service has been closed
- Use Pulsar's executor for the AsyncLoader in TopicPoliciesService
- make shutdown synchronous
- Improve the close method of SystemTopicTxnBufferSnapshotService

[improve][broker] Close TopicPoliciesService to allow Pulsar broker graceful shutdown

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/PulsarResources.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java

While investigating some recent test failures and Pulsar CI OOME issues, #22588, the heap dumps revealed that
the ForkJoin pool's work queue is retaining a lot of CompletableFuture related instances. 
The heap dump confirms that these are originating from `NamespaceResources.PartitionedTopicResources#runWithMarkDeleteAsync` method in this location:
https://github.com/apache/pulsar/blob/bbdc173e80157296ff0475cfdc4e36f5d063a7df/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java#L345-L374
The assumption is that graceful shutdown in tests without causing memory leaks will be more achievable with the provided executor since the instance isn't shared like the Fork join common pool executor.
Instead of using the forkjoin pool by default in …

[improve][broker] Don't use forkjoin pool by default for deleting partitioned topics

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsumers.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsumersTest.java

perf optimization
do not repeat StickyKeyHash calculations twice
NO
PR in forked repository: https://github.com/dlg99/pulsar/pull/15

[improve][broker] perf: Reduce stickyHash calculations of non-persistent topics in SHARED subscriptions

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java

#22430
After #22034, When the ledger is closed due to full entry,  will trigger create a new ledger, However, since the creation of the ledger is asynchronous, sometimes the last ledger is not created before the function returns.
https://github.com/apache/pulsar/blob/57a616eaa79096af5b49db89c99cd39ccc94ec00/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L1775-L1778
For this test: `ml.close();` is no make sure that the `currentLedger` switch successful, and there are two possible case:
- Case1:  **[Ledger01{entry1}], [Ledger02{entry1}], [Ledger03{}]**  
- Case2:  **[Ledger01{entry1}], [Ledger02{entry1}]** 
**Case 1** will cause the test to fail.
When `ml.close` to reopen a new `ManagerLedger` that will make sure into `Case1`, and then to assert …

[fix][test] Flaky-test: ManagedLedgerTest.testTimestampOnWorkingLedger

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/ManagedLedgerImplUtils.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/ManagedLedgerImplUtilsTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionWithTransactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TopicTransactionBufferTest.java

#22571
When enabling `replicateSubscriptionState` will use topic to sync subscription state, and make these message metadata as [Marker](https://github.com/apache/pulsar/blob/ac94296d2488b2b13d76fa2b1bfa71e9e3cfbb45/pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Markers.java#L107-L120)
These `marker` messages will not be sent to the consumer by the topic, and will automatically ack them.
https://github.com/apache/pulsar/blob/fc393f69043be6eb1b2572a27f131656a2cbc7f6/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java#L202-L217
But `getLastMessageId` will always return the last message position, regardless of whether the last message is `marked` or `not`. This will cause the reader stuck.
```java
while (reader.hasMessageAvailable()) {  // …
```

[fix][broker] Reader stuck after call hasMessageAvailable when enable replicateSubscriptionState

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/ManagedLedgerImplUtilsTest.java

If the trim ledger happened before get the `ManagedLedgerImplUtils.asyncGetLastValidPosition()`, the returned message ID will not be the message ID returned to the writer because messages are deleted by the trimming task.
```
2024-04-29T09:29:18,911 - INFO  - [test-OrderedScheduler-0-0:PulsarMockBookKeeper@123] - Creating ledger 4
2024-04-29T09:29:18,911 - INFO  - [test-OrderedScheduler-0-0:ManagedLedgerImpl@1529] - [testReverseFindPositionOneByOne] Created new ledger 4
2024-04-29T09:29:18,919 - INFO  - [test-OrderedScheduler-1-0:OpAddEntry@231] - [testReverseFindPositionOneByOne] Closing ledger 4 for being full
2024-04-29T09:29:18,920 - INFO  - [bookkeeper-ml-scheduler-OrderedScheduler-1-0:ManagedLedgerImpl$17@2686] - [testReverseFindPositionOneByOne] End TrimConsumedLedgers. ledgers=1 …
```

[fix][test] Fix the flaky tests of ManagedLedgerImplUtilsTest

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/FutureUtil.java

With the transaction feature, we send and receive messages, and at the same time, execute `admin API: unload namespace` 1000 times. Then the problem occur: Consumer could not receive any message, and there has no error log. After that we tried `admin API: get topic stats`, and the response showed only producers are registered on topic, and no consumers are registered on topic, but consumer stat is `Ready` in the client. This means that the state of the consumer is inconsistent between the broker and the client.
Then we found the problem: Two PersistentTopic which have the same name registered at a broker node, consumer registered on one (aka `topic-c`), and producer registered on another one (aka `topic-p`). At this time, when we send messages, the data flow like this : 
```text
client: …
```

[fix][broker] One topic can be closed multiple times concurrently

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorGlobalNSTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java

There are two tests that are not normal operations when using Geo-Replication with a global metadata store, which is should be denied in a production pulsar cluster. they are very dangerous, which leads to a lot of topic deletion and makes namespace policies being incorrect, making other tests in the same class flaky
- `Replicatortest.testConfigChange`
- `ReplicatorGlobalNSTest .testRemoveLocalClusterOnGlobalNamespace`
- Add a description on the class `ReplicatorGlobalNSTest` to describe it as the class to run no-normal tests.
- Move `Replicatortest.testConfigChange` into `ReplicatorGlobalNSTest`
- Move the normal test `ReplicatorGlobalNSTest. testForcefullyTopicDeletion` into `Replicatortest`

[fix] [test] Fix flaky test ReplicatorTest

---

.github/workflows/ci-go-functions.yaml
.github/workflows/ci-semantic-pull-request.yml
.github/workflows/labeler.yml
.github/workflows/pulsar-ci.yaml

In GitHub Actions workflows there are a few warnings about deprecated actions. 
Upgrade GitHub Actions to supported versions

[improve][ci] Upgrade deprecated GitHub Actions to supported versions

---

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java

Fixes #xyz
PIP: #xyz 
https://github.com/apache/pulsar/pull/20115 fixes the classloader in TopicSchema, but for Kubernetes Runtime, the classloader may be different from the other runtimes. Which caused the SerDe to fail to init in Kubernetes Runtime. 
- make sure the classloader always be `functionClassLoader` when init the context
*(or)*
*(or)*
*(example:)*
*If the box …

[fix][fn]make sure the classloader for ContextImpl is `functionClassLoader` in different runtimes

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedCursor.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerBkTest.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java

Each ManagedCursor stores its own status on a BookKeeper ledger and this ledger is rolled over when one of these conditions are met: some time passed or too many entries have been written.
The problem is that the condition is checked only while writing to the ledger: if no consumer sends acknowledgments then the ledger is never rolled over.
This may become a problem because there will be a long lived ledger that doesn't respect the configuration set by the administrator for "ledger rollover".
Creating a new ledger allows the Bookies to reclaim space, especially thanks to the GC (Garbage collection) mechanism, and then with the Compaction.
Having a long lived ledger prevents the Bookie to release disk space promplty with the GC, and so only Compaction can release space, but compaction is …

[improve][storage] Periodically rollover Cursor ledgers

---

.github/labeler.yml

[labeler action](https://github.com/actions/labeler) was upgraded from v4 to v5 in #22620. The configuration format has changed in v5.
adapt to v5 configuration format

[fix][ci] Fix labeler GitHub Actions workflow, adapt to v5 configuration format

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java

The change in #22500 is leaving the `pulsarClient` object as null and other tests are bound to fail
Ensuring the `pulsarClient` variable is always restored to a valid instance.
*(or)*
*(or)*
*(example:)*

[fix] Test was leaving client instance to null

---

conf/standalone.conf
pulsar-broker/src/main/java/org/apache/pulsar/zookeeper/LocalBookkeeperEnsemble.java

```
java.lang.NullPointerException: Cannot invoke "org.apache.bookkeeper.common.component.LifecycleComponent.close()" because "bookie" is null
at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.stop(LocalBookkeeperEnsemble.java:501) ~[pulsar-broker-3.2.2.jar:3.2.2]
at org.apache.pulsar.PulsarStandaloneStarter.lambda$new$0(PulsarStandaloneStarter.java:123) ~[pulsar-broker-3.2.2.jar:3.2.2]
at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
- Fix NPE while closing pulsar standalone and bookies are not completed initialized yet

[fix][misc] NPE during standalone shutdown

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ConsumerBatchReceiveTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java

Fixes #22618
The consumer doesn't consider batch-receive policy and doesn't return number of batch-receive messages based on user configured number when max-batch messages are higher than internal queue size because consumer stops consuming messages when it hits internal receiver queue size and application always receives incorrect number of messages which can impact user application. Users are not aware of the internal client implementation and consumer client should work based on consumer configuration values.
When user configures batch-receive max messages higher than the internal queue size then to support batch-receive configuration consumer should adjust the internal queue size accordingly to return expected batch-receive messages. …

[fix] [client] Fix Consumer should return configured batch receive max messages

---

buildtools/pom.xml
pom.xml

slf4j 2.0.x comes with slf4j-bom which can be used to align slf4j library versions.
use slf4j-bom to align slf4j versions

[improve][build] Use slf4j-bom to align slf4j versions

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/LeaderElectionImpl.java

It's useful to have more visibility to leader election. Adding logging to different conditions will be useful especially when debugging issues. 
- add broker ids to the leader election logging in PulsarService
- this is useful in multi-broker tests
- add low level logging to LeaderElectionImpl

[improve][broker] Add logging to leader election

---

pom.xml
pulsar-io/debezium/oracle/pom.xml

Fixes https://github.com/apache/pulsar/issues/22626
Avoid CVE-2023-4586
Upgrade debezium-oracle-connector version to 2.2.0.Final
which avoids `org.infinispan:infinispan-client-hotrod@14.0.4.Final` which has the vulnerability and uses `org.infinispan:infinispan-client-hotrod-jakarta@14.0.4.Final` instead, which has no vulnerabilities.

[fix][sec] Upgrade Debezium oracle connector version to avoid CVE-2023-4586

---

pom.xml

Fixes https://github.com/apache/pulsar/issues/21783 & 
Could fix some of the vulnerabilities on https://github.com/apache/pulsar/issues/21782
Avoid CVE-2023-4043
Upgrade elasticsearch-java version to 8.12.1
which uses org.eclipse.parsson:parsson@1.0.5 which no longer has the vulnerability.

[fix][sec] Upgrade elasticsearch-java version to avoid CVE-2023-4043

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-broker/pom.xml
pulsar-client/pom.xml
pulsar-client/src/main/java/org/apache/pulsar/client/impl/metrics/Counter.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/metrics/LatencyHistogram.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/metrics/UpDownCounter.java

In Pulsar, a long waited improvement to Otel, metric exporter REUSABLE_DATA memory mode, contributed by @asafm, has been released in [1.37.0 version](https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.37.0).
In addition, it's a good practice to stay updated with the experimental API changes within OTel. 
For example, in 1.37.0, the opentelemetry-extension-incubator got renamed to opentelemetry-api-incubator and the package name also changed. This impacts the Pulsar client OTel support (PIP-342, #22179).
- upgrades
- opentelemetry.version: 1.34.1 -> 1.37.0
- opentelemetry.instrumentation.version: 1.32.1-alpha -> 1.33.2
- opentelemetry.semconv.version: 1.23.1-alpha -> 1.25.0-alpha
- start using opentelemetry-instrumentation-bom / opentelemetry-instrumentation-bom-alpha
- …

[improve][build] Upgrade OTel library versions

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ReadOnlyManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ReadOnlyManagedLedgerImplTest.java

Fixes: https://github.com/apache/pulsar/issues/22606
Main Issue: ReadonlyManagedLedger initialization does not fill in the properties.
*(or)*
*(or)*
*(example:)*

[fix][storage] ReadonlyManagedLedger initialization does not fill in the properties

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/client/elastic/ElasticSearchJavaRestClient.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSinkTests.java

https://github.com/apache/pulsar/pull/14383 introduces the event-time-based index name, it works fine. 
This behavior has been broken by https://github.com/apache/pulsar/pull/14805. 
Elasticsearch sink yaml:
```yml
configs:
elasticSearchUrl: "http://localhost:9200"
indexName: "test-index-%{+yyyy-MM-dd}"
createIndexIfNeeded: true
compatibilityMode: ELASTICSEARCH
```
When the index name equals to the `test-index-%{+yyyy-MM-dd}`, the es index creation fails:
```
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/index] failed: [invalid_index_name_exception] Invalid index name [test-index-%{+yyyy-MM-dd}], must be lowercase
at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345) ~[elasticsearch-java-8.12.1.jar:?]
at …
```

[fix][io] Fix es index creation

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java

Follow up on #22583. TestNG keeps strong references to test class instances for the duration of the test run. (https://github.com/testng-team/testng/issues/1461)
This causes OOM issues. 
Clear remaining fields in MockedPulsarServiceBaseTest to prevent test runtime memory leak.

[fix][test] Clear MockedPulsarServiceBaseTest fields to prevent test runtime memory leak

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java

When investigating OOM issues in tests, I noticed that some memory leaks were related to references via LoadSheddingTask
There are 2 problems:
- the fields aren't accessed in a thread safety way
- because of races, it's possible that the task gets started when the instance is already shutting down.
- extract methods for cancelling and creating the loadSheddingTask and loadResourceQuotaTask instances
- make the methods synchronized to fix the thread safety issue
- before creating the instances, check that PulsarService is running

[fix][broker] Fix thread safety of loadSheddingTask and loadResourceQuotaTask fields

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java

Fixes #22442
Please refer to #22442.
Exclude producers for geo-replication from the `publishers` field in topic-stats and broker-stats.

[improve][broker] Exclude producers for geo-replication from publishers field of topic stats

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java

**Background**
- Cursor switches cursor ledgers if full, and there is a condition: no in-progress BK writing.
- The variable `inProgressMarkDeletePersistPosition` is used to trace whether there is an in-progress BK writing, it increases when starting a BK writing, and decreases when the writing is completed.
**Issue**
https://github.com/apache/pulsar/pull/20935 forgot to decrease the variable `inProgressMarkDeletePersistPosition` when writing fails, leading to the cursor ledger switching to stuck, because the cursor assumes there is always an in-progress BK writing.
Fix the bug.

[fix] [ml] Mark delete stuck due to switching cursor ledger fails

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SystemTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/MessageDuplicationTest.java

Disable deduplication on system topic to avoid recovering deduplication WAL (especially from offloaded topic). Because the system topic usually is a precondition to other topics. Therefore, we should pay attention to topic loading time.
Note: If the system topic loading timeout may cause dependent topics to fail to run.
Dependency diagram: normal topic --rely on--> system topic --rely on--> deduplication recover --may rely on--> (tiered storage)
- MessageDeduplication use `Topic#isDeduplicationEnabled` to judge if we should enable deduplication.
- System topic overrides the `Topic#isDeduplicationEnabled` to return `false`.

[fix][broker] Disable system topic message deduplication

---

conf/broker.conf
conf/standalone.conf
conf/websocket.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketProxyConfiguration.java

There's no explicit flow control in the Websocket proxy for producers. If too many messages are pushed, the proxy (or broker, if ws proxy runs with the broker) will run out of memory.
add `webSocketPulsarClientMemoryLimitInMB` configuration option to limit the memory.
by default, it is unlimited. Can be set to a value such as `64` to keep the direct memory used by the Pulsar client under 64 MB.

[improve][ws] Add memory limit configuration for Pulsar client used in Websocket proxy

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerTestBase.java

Avoid setting broker internal system topics using off-loader because some of them are the preconditions of other topics. The slow replying log speed will cause a delay in all the topic loading.(timeout)
- Add a condition check for offload policies.

[fix][broker] avoid offload system topic

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java
pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdSinks.java
pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdSources.java

After migrating to picocli, which does not allow passing unknown options:
```
bin/pulsar-admin sinks localrun --archive $PWD/connectors/pulsar-io-elastic-search-3.3.0-SNAPSHOT.nar --tenant public --namespace default --name elasticsearch-test-sink --sink-config-file $PWD/es-sink.yml --inputs elasticsearch_test
Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException: Unknown options: '--deprecatedBrokerServiceUrl', 'pulsar://localhost:6650/'
```
The previous version had a filtering mechanism, but the implementation was incorrect.
- Fix deprecated check

[fix][admin] Fix deprecated check

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java

Though `changeMaxReadPositionAndAddAbortTimes` is described as: increment when change the max read position or add a abort txn. 
In inplementation, we only increment it when change the max read position. 
Rename `changeMaxReadPositionAndAddAbortTimes` to `changeMaxReadPositionTimes`.

[fix] [broker] rename to changeMaxReadPositionCount

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java

`managedLedgerInterceptor` of `ManagedLedgerImpl` initialized twice, remove one
*(or)*
*(or)*
*(example:)*

[fix][ml] Remove duplicated field initialization of ML

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroup.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupReportLocalUsageTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupServiceTest.java

`org.apache.pulsar.broker.resourcegroup.ResourceGroup.PerMonitoringClassFields#usedLocallySinceLastReport` holds the usage rate of ResourceGroup in the current cycle.
When the report thread calls the `org.apache.pulsar.broker.resourcegroup.ResourceGroup#rgFillResourceUsage` to report the ResourceGroup usage, the `usedLocallySinceLastReport` should be reset.
Right now, this value will be reported every 2 cycles. The correct behavior should be to report the current rate only when it exceeds or falls below 5% of the last reported value.
https://github.com/apache/pulsar/pull/22340 breaks this behavior.
- Always reset `org.apache.pulsar.broker.resourcegroup.ResourceGroup.PerMonitoringClassFields#usedLocallySinceLastReport` in the `org.apache.pulsar.broker.resourcegroup.ResourceGroup#setUsageInM …

[fix][broker] usedLocallySinceLastReport should always be reset

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java

When we only set the TLS URLs for `ClusterData` and set the `brokerClientTlsEnabled` to `true`, the admin client for geo-replication will be failed to create because the else if block(`StringUtils.isEmpty(data.getServiceUrl())`) logic is wrong.
* Allow the cluster data only set tls url

[fix][broker] Fix geo-replication admin client url

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloaderFactory.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/offload/Offloaders.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/JCloudLedgerOffloaderFactory.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloader.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/OffsetsCache.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderBase.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderStreamingTest.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderTest.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/OffsetsCacheTest.java

In #16417 a cache was added for caching offsets. The problem with this implementation is that in some cases, the 
memory consumption can go very high and cause OOM.
- Move the cache to the org.apache.bookkeeper.mledger.offload.jcloud.JCloudLedgerOffloaderFactory level and share it across all offloaded ledgers.
- Add a default maximum size of 1M entries. This consumes about 60MB of heap at maximum.
- add system property `pulsar.jclouds.readhandleimpl.offsetsscache.max.size` to adjust this, however there shouldn't be a need to tune it.
- Add scheduler to run the cleanup job periodically so that the TTL limit will be enforced in all cases.

[fix][offload] Fix OOM in tiered storage, caused by unbounded offsets cache

---

tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/OffsetsCache.java

When cherry-picking #22679 to branch-3.0, the build failed. 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project tiered-storage-jcloud: Compilation failure
[ERROR] /Users/lari/workspace-pulsar/pulsar-branch-3.0/tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/OffsetsCache.java:[23,53] package io.grpc.netty.shaded.io.netty.util.concurrent does not exist
```
I had made a mistake and used a shaded class in OffsetsCache
- replace with Guava's ThreadFactoryBuilder since Guava is already available in the tiered storage dependencies

[improve][offload] Replace usage of shaded class in OffsetsCache

---

pip/pip-349.md

Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*

[improve] [pip] PIP-349: Add additionalSystemCursorNames ignore list for TTL check

---

conf/broker.conf
conf/standalone.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java

Fixes #xyz
PIP: #xyz 
Message TTL will move the cursors based on the configured `ttlDurationDefaultInSeconds`. However, for those system topics' cursors, such as compaction service cursor, transaction system topic cursor, and even some third-party plugins cursors, should not or don't want to be impacted by the TTL. 
We have one PR https://github.com/apache/pulsar/pull/21865 to filter the compaction service cursors for TTL check, but doesn't cover other system topics cursors. To provide a general solution and support third-party plugin cursors not impacted by TTL, I proposed to add a systemCursorNames ignore list  to filter the TTL check.
Add a configuration in `conf/broker.conf` to support filter subscriptions for TTL check. …

[improve] [broker] Add additionalSystemCursorNames ignore list for TTL check

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopicTest.java

https://github.com/apache/pulsar/pull/20607 introduced the variable `userCreatedProducerCount` to track the number of producers created by users. Concurrently, the `removeProducer` method in `AbstractTopic` decreases the count of `userCreatedProducerCount `using `USER_CREATED_PRODUCER_COUNTER_UPDATER.decrementAndGet(this)` when a producer is removed. However, `NonPersistentTopic` overrides the `removeProducer` method of `AbstractTopic`, and the overridden `removeProducer` method in `NonPersistentTopic` does not decrease the count of `userCreatedProducerCount`. As a result, when `maxProducersPerTopic` is set, this incorrect value of `userCreatedProducerCount` can lead to a `ProducerBusy` error when creating a producer.
Since the `NonPersistentTopic` class extends the `AbstractTopic` class …

[fix][broker] Fix ProducerBusy issue due to incorrect userCreatedProducerCount on non-persistent topic

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorMXBeanImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/RangeSetWrapper.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ReadOnlyCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ReadOnlyManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorIndividualDeletedMessagesTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerBkEnsemblesTests.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java

When the ledger opens a cursor,  the cursor uses a field to hold a managed ledger configuration. Once the managed ledger configuration is renewed(The managed ledger configuration will be renewed when the namespace/topic policies change) in the managed ledger, the cursor cannot use the latest ledger config.
This will break the ledger feature like `autoSkipNonRecoverableData`.
- Remove the config parameter in the  constructor of ManagedCursorImpl and NonDurableCursorImpl
- Use `cursor.getConfig` instead of `cursor.config`, which method always gets the managed ledger config for managed ldeger.

[fix][broker] Fix cursor should use latest ledger config

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/TransactionBuffer.java

The full qulified path of the exception in transaction module is wrong, need to fix it.
Correct the full qulified path of the exception.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/50

[fix] [doc] fix the class name of transaction exception.

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderBuilderImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/BuildersTest.java

Fixes #22638
Currently when Reader Builder is used to create Reader with `startMessageFromRollbackDuration` and if it fails due to connection issue and application retries to create a new Reader again then it throws IllegalArgument Exception even though Reader doesn't have any incorrect argument and that confuses the users.
Application should be able to retry and able to recreate Reader using the ReaderBuilder if it fails due to connection issue.
*(or)*
*(or)*
*(example:)* …

[fix][client] Fix ReaderBuilder doest not give illegalArgument on connection failure retry

---

pom.xml

Fixes https://github.com/apache/pulsar/issues/22625
Avoid CVE-2024-1597
Upgrade postgresql version to 42.5.5

[fix][sec] Upgrade postgresql version to avoid CVE-2024-1597

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnxThrottleTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicListService.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarHandler.java

`PulsarHandler.remoteAddress` is the socket address of the Proxy when enabled `haProxyProtocolEnabled`, we'd better print three addresses: `local address`, `remote address`, `source remote address` in the log.
Print three addresses: `local address`, `remote address`, `source remote address` in the log.
After this PR, the demo of addresses in the log is below:
- `Demo: [id: 0x2561bcd1, L:/10.0.136.103:6650! R:/240.240.0.5:58038] [SR:/240.240.0.5:58038]`
- `L`: local Address
- `R`: remote address
- `SR`: source remote address. It is the source address when enabled "haProxyProtocolEnabled".

[improve] [log] Print source client addr when enabled haProxyProtocolEnabled

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/OpenTelemetryConsumerStats.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/OpenTelemetryConsumerStatsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java
pulsar-opentelemetry/src/main/java/org/apache/pulsar/opentelemetry/OpenTelemetryAttributes.java

Using OpenTelemetry, exposes the current consumer-level metrics emitted by the broker and described in the [doc](https://pulsar.apache.org/docs/next/reference-metrics/#consumer-metrics).
Similar to topic metrics PR https://github.com/apache/pulsar/pull/22467, navigate all the current consumers connected to the broker and expose their respective metrics in OpenTelemetry format.
The metric details can be consulted in the doc PR: https://github.com/apache/pulsar-site/pull/896. Prometheus metric `pulsar_consumer_blocked_on_unacked_messages` has been dropped in favor of OpenTelemetry boolean attribute `pulsar.consumer.blocked` on metric `pulsar.broker.consumer.message.unack.count`, as these values are tightly related.
This …

[feat][broker] PIP-264: Add OpenTelemetry consumer metrics

---

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationData.java

fix comment of patternAutoDiscoveryPeriod in ConsumerConfigurationData class.
`The default and minimum value is 1 minute.` -> `The default value is 1 minute, with a minimum of 1 second.`

[fix][misc] Correct the description of patternAutoDiscoveryPeriod

---

pip/pip-348.md

Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*

[improve] [pip] PIP-348: Trigger offload on topic load stage

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/BaseResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/LocalPoliciesResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TopicResources.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java

Deleting a namespace sometimes fails and leaves znodes around, especially the "bundle owner" nodes `/namespace/NAMESPACE/xxxxxx `
- ensure that all the children of /namespace/NAMESPACE are deleted, especially the ephemeral nodes for ownership
- ensure that on the code path that handles the deletion of the namespace we make progress, the main fact is about not relying on "cache.exists" before using a "delete": the new code is more pessimistic that goes with "deleteIfExists", handling "NotFound" gracefully
- add more logs about the delete namespace execution path
- delete namespace seems to consistently work
- there are no more spammy logs about errors around the topic policies event reader (changelog_events...)
- in case we see an error we log at which point the procedure was (because we …

[improve][broker]Ensure namespace deletion doesn't fail

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsController.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatedSubscriptionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatedSubscriptionWithTransactionTest.java

fix typo and useless local variable.
fix typo and useless local variable.

[fix] [broker] fix typo and useless local variable.

---

pip/pip-347.md

pip-347
implementation pr：https://github.com/apache/pulsar/pull/22562
*(or)*
*(or)*
*(example:)*

[improve][pip] PIP-347: add role field in consumer's stat

---

pip/pip-350.md

---
Allow to disable the managedLedgerOffloadDeletionLagInMillis
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*

[improve][pip] PIP-350: Allow to disable the managedLedgerOffloadDeletionLagInMillis

---

docker/pulsar-all/pom.xml
docker/pulsar/pom.xml
pom.xml
tests/docker-images/java-test-image/pom.xml
tests/docker-images/latest-version-image/Dockerfile
tests/docker-images/latest-version-image/pom.xml

When pushing pulsar and pulsar-all to a custom repository, I don't want to use the original name. If we can support custom image and label names, it will reduce the workload of copying.
- Add `docker.image` property to define the image name, default to `pulsar`
- Add `docker.tag` property to define the tag name, default to `latest`
- Apply `docker.image` and `docker.tag` to the pulsar, pulsar-all, java-test-image, latest-version-image

[improve][build] Support custom image and label names

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicDefaultMultiPartitionsTest.java

Discussion: https://lists.apache.org/thread/t756oy8881vqf9fz2zzgk3y04zsyykbh
After you set `defaultNumPartitions` to `16`, you will get `16` partitions per topic, and `16*16` DLQ partitions per subscription, you will get a huge number of DLQs if you have more than one subscription under one topic.  For example: 
- create topic `t1` with `16` partitions
- you will get `t1-partition-0`, `t1-partition-1`...`tp-partition-15`.
- after you enable DLQ, you will get the following `16*16` DLQs per subscription
- `t1-partition-0-{subscription}-DLQ-partition-0`
- `t1-partition-0-{subscription}-DLQ-partition-1`
- ...
- `t1-partition-15-{subscription}-DLQ-partition-15`
- `t1-partition-1-{subscription}-DLQ-partition-0`
- `t1-partition-1-{subscription}-DLQ-partition-1`
- ...
- ...
- ...
- …

[improve] [broker] [break change] Do not create partitioned DLQ/Retry topic automatically

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/AvroSchemaBasedCompatibilityCheck.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/ProtobufNativeSchemaCompatibilityCheck.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/exceptions/IncompatibleSchemaException.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/SchemaServiceTest.java

Encounter a `Do not have existing schema` exception when checking schema compatibility on a schema-less topic via [REST API](https://pulsar.apache.org/admin-rest-api/?version=2.11.4#operation/testCompatibility)
- Allow the compatibility check to succeed on a schema-less topic via REST API.
- Optimize incompatible exception msg.
- Add unit test to cover this bug.

[fix][schema] Error checking schema compatibility on a schema-less topic via REST API

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java

Pulsar Metadata Store Callbacks shouldn't be a blocking call. Otherwise, this blocking call could block the Metadata executor thread.
- Make ExtensibleLoadManagerImpl.getOwnedServiceUnits async

[fix][broker] Make ExtensibleLoadManagerImpl.getOwnedServiceUnits async

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/SubscriptionPauseOnAckStatPersistTest.java

The method `cursor.isCursorDataFullyPersistable` was added with [PIP-299-part-1: Stop dispatch messages if the individual acks will be lost in the persistent storage](https://github.com/apache/pulsar/pull/21423), it used to check if the dispatching should be pause. 
Calling `cursor.isCursorDataFullyPersistable` will loop the collection `cursor.individualDeletedMessages`. It is
not a light method. If never enabled "dispatcherPauseOnAckStatePersistentEnabled", should avoid calling `cursor.isCursorDataFullyPersistable`.
Avoid calling `cursor.isCursorDataFullyPersistable`  if disabled `dispatcherPauseOnAckStatePersistentEnabled`

[improve] [broker] Do not call cursor.isCursorDataFullyPersistable if disabled dispatcherPauseOnAckStatePersistentEnabled

---

docker/pulsar/Dockerfile

Many components need to rely on curl command when testing, so we should add curl command to the pulsar image.
More context:
https://lists.apache.org/thread/mkxsz2tjbmlmqpsbh77sdll9b36o8pgv
Add curl command for pulsar image
*(or)*
*(or)*
*(example:)*

[fix][build] Add curl command for pulsar image

---

conf/broker.conf
conf/standalone.conf
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java

Fixes #xyz
PIP: [PIP-348](https://github.com/apache/pulsar/pull/22650)
Implement of [PIP-348](https://github.com/apache/pulsar/pull/22650)
*(or)*
*(or)*
*(example:)*

[improve] [broker] Trigger offload on topic load

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthorizationTest.java

Fixes #22712 
AuthorizationTest.testGetListWithGetBundleOp is flaky.
Remove unnecessary call which causes issues, see #22712 for stack trace. [Mockito isn't thread safe](https://github.com/mockito/mockito/wiki/FAQ#is-mockito-thread-safe). The removed line seems unnecessary in the test since the test passes without it.

[fix][test] Fix flaky AuthorizationTest.testGetListWithGetBundleOp

---

docker/pulsar/Dockerfile

The grpcio@1.59.3 is installed by apk, and Pulsar-client@3.4.0 requires grpcio>=1.60.0, which causes the grpcio to be reinstalled by pip, but the grpcio doesn't provide the arm64 wheel, and then pip3 will take a long time to compile the grpcio locally, please see [job](https://github.com/nodece/pulsar-python-deps-build/actions/runs/8891459473/job/24418839959#step:6:315) for detailed compilation information.
Contexts:
- https://github.com/apache/pulsar/pull/22613
- https://github.com/apache/pulsar-client-python/pull/211
- https://lists.apache.org/thread/cknro58cty8xjpf8zsb2p02flw6wqs2h
- `pip install` with `--only-binary` option avoids compiling the grpcio locally, so the python-deps stage is unnecessary
- Use independent installation instead of pulsar-client[all]
Verified locally and …

[fix][build] Fix pulsar-client-python installation on ARM arch

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java

Fix deadlock when disabling topic level Geo-Replication, which is using the metadata store thread to call another metadata reading(`clusters list`).
You can reproduce the issue by `OneWayReplicatorUsingGlobalZKTest.testDeleteNonPartitionedTopic`
logs
```
2024-05-17T18:50:58,304 - ERROR - [configuration-metadata-store-147-1:PersistentTopicsBase] - [null] Failed to perform setReplicationClusters on topic persistent://public/default/tp_-8fb2b1c4-fb11-4e64-ba7f-7f4d36a0b184
org.apache.pulsar.broker.web.RestException: HTTP 500 Failed to get children of /admin/clusters
at org.apache.pulsar.broker.admin.AdminResource.clusters(AdminResource.java:460) ~[classes/:?]
at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalSetReplicationClusters$315(PersistentTopicsBase.java:3272) …
```

[fix] [broker] fix deadlock when disable topic level Geo-Replication

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/utils/AuthTokenUtils.java
pulsar-broker/src/main/java/org/apache/pulsar/utils/auth/tokens/TokensCliUtils.java
pulsar-broker/src/test/java/org/apache/pulsar/utils/auth/tokens/TokensCliUtilsTest.java

Currently, the tool that generates the token cannot attach headers. We should support it. For example, it makes sense to attach a [kid](https://www.rfc-editor.org/rfc/rfc7515#section-4.1.4) field for JWKS.
Supports creating tokens with additional headers
*(or)*
*(or)*
*(example:)*

[improve][cli] Supports creating tokens with additional headers

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java

Fixes #20553
SimpleProducerConsumerTest is flaky. deleteNamespaceWithRetry often times out. It seems that this became more flaky after #22627.
* When the timeout happens, restart the broker.
* rename the method `rest()` to `cleanupAfterMethod()`
* capture a thread dump to find out if there's a deadlock when the timeout happens

[improve][test] Restart broker in SimpleProducerConsumerTest if ns deletion times out

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java

During the recovery of the cursor, if the stored position points to a non existent ledger, the cursor is rewinded to the oldest position. In this case the subscription properties won't be stored in the managedcursor info on the metadata store
* Pass the cursorProperties instead of an empty map during recovery

[fix][ml]: subscription props could be lost in case of missing ledger during recovery

---

pulsar-client/src/main/java/org/apache/pulsar/client/util/MessageIdUtils.java
pulsar-io/kafka-connect-adaptor/pom.xml
pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaSinkTaskContext.java
pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSinkTest.java

After discussing [here](https://github.com/apache/pulsar/pull/22698#discussion_r1597445741),  the pulsar client shouldn't expose the `offset` term to users.
- Deprecate `MessageIdUtils.getOffset` and `MessageIdUtils.getMessageId`
- For connectors, use `FunctionCommon.getOffset` and `FunctionCommon.getMessageId`

[improve][client] Deprecate `MessageIdUtils.getOffset` and `MessageIdUtils.getMessageId`

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImpl.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockBookKeeper.java
testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockLedgerHandle.java

**Background: Flow when adding entry failed**
- Switch to a new ledger
- Close and duplicate all the pending add requests<sup>[3]</sup>
- The callback of the add entry request will be discarded because it is closed. 
- Redo all the pending add requests.
**Issue**
| time | add entries failed | switch ledger |
| 1 | add the first entry failed | 
| 2 | | start to switch ledger, new ledger was created |
| 3 | | close all pending OpAddEntry<sup>[3]</sup> |
| 4 | recycle OpAddEntry due to change state to `COMPLETED` failed<sup>[4]</sup> |
| 5 | | get an NPE when duplicating pending OpAddEntry |
**Reproduce:** no test to reproduce this case yet.
---
**Background: Flow when adding entry timeout**
- **(Highlight)** Close the first add entry request<sup>[1]</sup>.
- Switch to a …

[fix] [ml] Add entry fail due to race condition about add entry failed/timeout and switch ledger

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/manager/SplitManager.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/manager/UnloadManager.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/manager/SplitManagerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/manager/UnloadManagerTest.java

- Extensible Load Balancer cannot split bundles when a namespace is recreated. The old parent bundle before split (in the Deleted state) could block the next split operation until they are tombstoned by the leader monitor bundle  cleanup job.
-  Extensible Load Balancer delays bundle cleanups when a namespace is deleted.  Those deleted bundles are stuck in Free state until they are tombstoned by the leader monitor bundle cleanup job. Although this delayed tombstone was introduced for non-transfer unloading, these lingering bundles are not ideal when the namespace is deleted.
- Immediately tombstone Deleted state bundles
- Set ServiceUnitStateData.force=true when deleting(unloading) namespace bundles. Then, immediately tombstone Free state bundles if force is true.
*If the box was checked, …

[fix][broker] Immediately tombstone Deleted and Free state bundles

---

pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java

BROKER_ENTRY_METADATA is a thread local that contains the reused BrokerEntryMetadata instance.
It should be cleared before reusing.
- call `.clear()` before reusing the instance.

[improve][broker] Clear thread local BrokerEntryMetadata instance before reuse

---

conf/broker.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java

It is `TransferShedder`, not `TransferSheddeer`.
Replace `TransferSheddeer` with `TransferShedder`.

[fix] [conf] fix typo for TransferShedder.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/GetPartitionMetadataTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceAutoTopicCreationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceThrottlingTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionLowWaterMarkTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClient.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/BinaryProtoLookupService.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpLookupService.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/LookupService.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionCoordinatorClientImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImplTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/PulsarClientImplTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/FutureUtil.java
pulsar-common/src/main/proto/PulsarApi.proto
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java

see also [PIP-344 Correct the behavior of the public API pulsarClient.getPartitionsForTopic(topicName)](https://github.com/apache/pulsar/pull/22182)
- When calling `pulsarClient.getPartitionsForTopic(topicName)`, Pulsar will automatically create the partitioned topic metadata if it does not exist, either using `HttpLookupService` or `BinaryProtoLookupService`.
- The partitioned topic auto-creation is dependent on `pulsarClient.getPartitionsForTopic`
- It triggers partitioned metadata creation by `pulsarClient.getPartitionsForTopic`
- And triggers the topic partition creation by producers' registration and consumers' registration.
Since the method `pulsarClient.getPartitionsForTopic` is a public API, and it is named `getxxx,` it should edit nothing.
- Do not create partitioned metadata …

[fix] [client] PIP-344 Do not create partitioned metadata when calling pulsarClient.getPartitionsForTopic(topicName)

---

pip/pip-353.md

Improve transaction message visibility for peek-messages

[improve][PIP] PIP-353: Improve transaction message visibility for peek-messages

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokerStatsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/BrokerStats.java

#22770
- Clearly define REST API on Open API for `Bookies`, `Brokers`, `Clusters`, `BrokerStats`
Local validation confirmed that the generated swagger.json file displays well on the web page.

[fix][admin][part-1]Clearly define REST API on Open API

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/TenantTest.java

[fix][admin] Tenant AdminRoles can not contains whitespace in the beginning or end.

---

pip/pip-354.md

PIP-354
Implementation PR: https://github.com/apache/pulsar/pull/22753
As every bundle in the cluster corresponds to a zk node, it is common that there are thousands of zk nodes in a cluster, which results into thousands of read/update operations to zk. This will cause a lot of pressure on zk.
**As All Load Shedding Algorithm pick bundles from top to bottom based on throughput/msgRate, bundles with low throughput/msgRate are rarely be selected for shedding. So that we don't need to contain these bundles in the bundle load report.**

[improve] [pip] PIP-354: apply topK mechanism to ModularLoadManagerImpl

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java

#22770
- Clearly define REST API on Open API for Namesaces@v2
- Local validation confirmed that the generated swagger.json file displays well on the web page.

[fix][admin][part-2]Clearly define REST API on Open API for Namesaces@v2

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SinksBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SourcesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/ResourceGroups.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/ResourceQuotas.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Worker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v3/Packages.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v3/Transactions.java

#22770
- Clearly define REST API on Open API for Topics
- Local validation confirmed that the generated swagger.json file displays well on the web page.

[fix][admin][part-4]Clearly define REST API on Open API

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java

#22770
- Clearly define REST API on Open API for Topics
- Local validation confirmed that the generated swagger.json file displays well on the web page.

[fix][admin][part-3]Clearly define REST API on Open API for Topics

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java

1. The topic partitions on the remote cluster will be expanded when namespace level Geo-Replication is enabled, even if the topic level Geo-Replication is disabled. It is not correct.
2. The topic partitions on the remote cluster will not be expanded if the topic level Geo-Replication is enabled. It is not correct.
Fix the two issues.

[fix] [broker] fix topic partitions was expanded even if disabled topic level replication

---

pip/pip-353.md
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/AdminApiTransactionTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/SubscriptionIsolationLevel.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/TransactionIsolationLevel.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

#22746 
- Support `--show-server-marker` and `--transaction-isolation-level` flags for peek-messages cmd.
- Add `testPeekMessageForSkipTxnMarker`, `testPeekMessageForSkipAbortedAndUnCommittedMessages` and `testPeekMessageForShowAllMessages` unit test to corver this change. 
PR in forked repository: https://github.com/shibd/pulsar/pull/34

[improve][cli] PIP-353: Improve transaction message visibility for peek-message

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java

Currently, we only support configure one single loadSheddingStrategy and there is no any plan for supporting multiple LoadSheddingStrategy, but `ModularLoadManagerImpl` use a `List<LoadSheddingStrategy>` to hold the LoadSheddingStrategy.
Replace `List<LoadSheddingStrategy>` with `LoadSheddingStrategy`.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/53

[fix] [broker] replace loadSheddingPipeline with loadSheddingStrategy.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterWithClassLoader.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/SubscriptionStatsTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarClassLoader.java

When unloading a topic the `EntryFilterWithClassLoader` instance closes the NarClassLoader that loaded the filter, preventing any further loading of classes.
This is a regression introduced in 3.0.0 by https://github.com/apache/pulsar/pull/19364
Reproducer:
- configure one EntryFilter in broker.conf
- create a topic (this in turn creates an `EntryFilterWithClassLoader` instance)
- do not use the EntryFilter (don't consume messages)
- unload the topic (this calls EntryFilterWithClassLoader.close() that calls ClassLoader.close())
- consume data from any topic that uses the entry filter
- CRASH ! because the Classloader is closed and it cannot load any other classes
Sample Stacktrace (this is from the DataStax fork, but it shows the problem):
```
2024-05-09T13:16:13,145+0000 …
```

[fix][broker] EntryFilters fix NoClassDefFoundError due to closed classloader

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java

Main Issue: https://github.com/apache/pulsar/issues/21324
Fix can not cleanup heartbeat data if scaling down broker
when close the broker, delete heartbeat resource. 
If the broker restart, the heartbeat resource would be recreate.
- [] Make sure that the change passes the CI checks.
PR in forked repository: https://github.com/TakaHiR07/pulsar/pull/21

[fix][broker] fix can not cleanup heartbeat data if scaling down broker

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/RangeCacheTest.java

The RangeCache class contains several race conditions which cause instability.
When one thread removes the entry and another one uses it, that will become a problem. 
The `cacheEvictionIntervalMs` setting is 10 ms by default. This results in the 
`RangeCache.evictLEntriesBeforeTimestamp` method getting called about 100 times per second.
The default expiration is `managedLedgerCacheEvictionTimeThresholdMillis` which is 1000 ms by default.
It's also possible that 2 threads remove the entry at the same time. `ManagedLedgerImpl.invalidateEntriesUpToSlowestReaderPosition` will result in calls to `RangeCache.removeRange` method. These calls happen independently of the `RangeCache.evictLEntriesBeforeTimestamp` calls so there's a chance for race conditions.
- Add checks to validate that the value …

[fix][ml] Fix race conditions in RangeCache

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheManagerTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/RangeCacheTest.java

Follow up on #22789. Test a few basic race conditions. 
The solution in #22789 could lead to an endless loop. This PR fixes this problem.
Race conditions are logged with info level, for example:
```
2024-05-31T08:57:44,823 - INFO  - [pool-2-thread-4:RangeCache@308] - Value was already released for key 59, removing entry without releasing the value
2024-05-31T08:57:44,824 - INFO  - [pool-2-thread-4:RangeCache@308] - Value was already released for key 153, removing entry without releasing the value
2024-05-31T08:57:44,824 - INFO  - [pool-2-thread-7:RangeCache@308] - Value was already released for key 153, removing entry without releasing the value
2024-05-31T08:57:44,824 - INFO  - [pool-2-thread-8:RangeCache@308] - Value was already released for key 60, removing entry without releasing the …
```

[improve][ml] RangeCache refactoring: test race conditions and prevent endless loops

---

bin/pulsar
docker/pulsar/Dockerfile
docker/pulsar/pom.xml

From branch-3.3, pulsar starts to use alpine as base image, but it throws exception when using snappy-java lib. 
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.10-4b05b6fe-7374-45fc-b770-7e3728aa63de-libsnappyjava.so: Error relocating /lib/ld-linux-x86-64.so.2: unsupported relocation type 37 [in thread "pulsar-offload-write-OrderedExecutor-1-0"]
```
The reason is that alpine is musl-based OS while snappy-java lib built-in libsnappyjava.so is compiled with glibc.
In order to fix this issue, we need to re-compile the snappy-java native lib in alpine docker.
PR in forked repository: https://github.com/yaalsn/pulsar/pull/2

[fix][ci] Fix snappy-java native lib fails to load in x86 alpine

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java
pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerData.java

The doc of `ThresholdShedder` refer a wrong method, which is useless.
Fix the doc and remove useless method.

[fix] [broker] Fix doc of ThresholdShedder and remove useless method.

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/proto/MLDataFormats.proto
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java

PR https://github.com/apache/pulsar/pull/17573 has fixed cases that consumer commit offset periodically. It update `lastActive` field of cursor when consumer commit the offset.
But there is still corner case that the consumer do not commit the offset for any reason. For example,  there is no content in the topic could be read, so the consumer do not commit the offset reasonably. In such case we has no reason delete the subscription.
Anyway, **we should be cautious with the delete operation, which could result into data duplication or loss.**
This is the second solution trying to solve problem described in https://github.com/apache/pulsar/pull/21692.
PR https://github.com/apache/pulsar/pull/21692 try to update the last active info every time broker do expiration check.
But strictly …

[fix] [broker] maintain last active info in memory only.

---

pulsar-broker/src/main/java/org/apache/pulsar/utils/auth/tokens/TokensCliUtils.java
pulsar-broker/src/test/java/org/apache/pulsar/utils/auth/tokens/TokensCliUtilsTest.java

Fixes #22811 
This fix addresses a regression caused by changes in this [pull request](https://github.com/apache/pulsar/pull/21412/files). It’s crucial for users who rely on `bin/pulsar tokens create` for creating JWT tokens.
The versions affected 3.2.0 3.2.1 3.2.2 and 3.2.3
In this fix, I have changed it back to use seconds and added additional tests to prevent similar issues in the future.

[fix][cli] Fix expiration of tokens created with "pulsar tokens create"

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java

#22814 added synchronized usage to RangeCache to ensure consistency. Synchronized usage can be avoided by the use of StampedLock
Replace synchronized with StampedLock

[improve][ml] RangeCache refactoring follow-up: use StampedLock instead of synchronized

---

bouncy-castle/bc/LICENSE
distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml

- org.bouncycastle:bc-fips:1.0.2.4 contains CVE-2024-29857. 
Upgrade to org.bouncycastle:bc-fips 1.0.2.5.
- also update
- org.bouncycastle:bcpkix-fips to 1.0.7
- non-fips version to 1.78.1 (from 1.78)
- remove bcprov-ext-jdk18on since it has been relocated to bcprov-jdk18on

[fix][sec] Upgrade Bouncycastle libraries to address CVEs

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pom.xml

https://github.com/apache/pulsar/pull/22649#issuecomment-2143514831
- Upgrade OTel library version to 1.38.0
-  release notes: https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.38.0
- Bump instrumentation library version to 1.33.3
-  release notes: https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.33.3

[improve][misc] Upgrade OTel library to 1.38.0 version

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/ExceptionHandler.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java
pulsar-package-management/filesystem-storage/src/main/java/org/apache/pulsar/packages/management/storage/filesystem/FileSystemPackagesStorage.java

For Python & Go functions, validate that the filename provided does not look into a parent directory.

[improve] Validate user paths in Functions utils

---

conf/standalone.conf
deployment/terraform-ansible/templates/broker.conf

PR https://github.com/apache/pulsar/pull/21168 has disable `loadBalancerDirectMemoryResourceWeight` by default.  But there is still some places not changed.
Change the default value of all places to 0.

[fix] [broker] disable loadBalancerDirectMemoryResourceWeight by default

---

deployment/terraform-ansible/templates/broker.conf

Some conf name is spell incorrectly in conf file `deployment/terraform-ansible/templates/broker.conf`, and there are many typo errors.
- correct the conf name: `replicatioPolicyCheckDurationSeconds` to `replicationPolicyCheckDurationSeconds`.
- fix the typo errors.

[fix] [conf] fix configuration name and typo.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TransactionsBase.java

Instead of silently dropping bits in the casting, validate upfront and fail if out of range.

[improve] Validate range of argument before long -> int conversion

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
tests/integration/pom.xml
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/PulsarIOTestRunner.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/PulsarIOSinkRunner.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/PulsarIOSourceRunner.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/PulsarIODebeziumSourceRunner.java

Upgrade Jetcd so that we can later upgrade Vertx, which contains a security issue.
This is replacing #21896 & #22427.

[improve] Upgrade Jetcd to 0.7.7 and VertX to 4.5.8

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/OpenTelemetryConsumerStats.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/OpenTelemetryConsumerStatsTest.java
pulsar-opentelemetry/src/main/java/org/apache/pulsar/opentelemetry/OpenTelemetryAttributes.java

PR https://github.com/apache/pulsar/pull/22693 introduced OpenTelemetry consumer stats. Two issues surfaced as part of a follow-up review:
1. The attribute sets are immutable and should be cached, such that they are not allocated on each metric collection run.
2. Too many attributes are being exposed, potentially slowing down the metric pipeline as a result. Many of these attributes are currently being emitted as 'string' metrics in Prometheus.
1. Cache the attribute sets in the Consumer class, using lazy initialization to conserve memory if OTel is disabled.
2. Remove consumer attributes `pulsar.consumer.connected_since`, `pulsar.consumer.metadata`, `pulsar.client.address`, and `pulsar.client.version`.
3. Extract attribute `pulsar.consumer.blocked` from metric …

[improve][broker] Reduce number of OpenTelemetry consumer attributes

---

conf/broker.conf
conf/standalone.conf
deployment/terraform-ansible/templates/broker.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java

We have deprecated `loadBalancerMemoryResourceWeight` in PR: https://github.com/apache/pulsar/pull/19559, because the memory usage increase all the way until the GC reclaim the space, thus there is no relation between the actual load with the memory usage.
But PR: https://github.com/apache/pulsar/pull/19559 don't remove all usage of this conf, there is still some logic using this deprecated conf. Meanwhile, there is a try to enhance the memory usage collection by Lari (https://github.com/apache/pulsar/issues/21973), so there is possibilty that we may enable this conf again if the memory usage is proved to be related with the actual load.
Based on info aboved, i think that we have better to make the default value of deprecated `loadBalancerMemoryResourceWeight` to 0, in such way we can …

[fix] [broker] disable loadBalancerMemoryResourceWeight by default

---

pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java
pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/IsolatedBookieEnsemblePlacementPolicy.java

There are a couple of blocking calls to metadata in `BookieRackAffinityMapping` class, in places where we're not supposed to make any blocking calls.
This is made a bit hard by the BK rack-affinity interface that doesn't allow to use futures.
During the initial `setConf()` load the list of bookie-racks info asynchronously, and set up the async watch. This seems the most sensible approach, barring a complete redesign of the rack-affinity interface in BK.

[fix] Remove blocking calls from BookieRackAffinityMapping

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

It fixes #22844 
Topic stats-internal with broken schema ledger gives below error
```
./bin/pulsar-admin stats-internal persistent://prop/ns1/t1
No such ledger exists on Metadata Server
Reason: No such ledger exists on Metadata Server
```
```
Caused by: org.apache.bookkeeper.client.BKException$BKNoSuchLedgerExistsOnMetadataServerException: No such ledger exists on Metadata Server
at org.apache.pulsar.metadata.bookkeeper.PulsarLedgerManager.lambda$readLedgerMetadata$2(PulsarLedgerManager.java:208) ~[pulsar-metadata-x.jar:x]
at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?] …
```

[fix] [broker] Fix Broker was failing to load stats-internal with broken schema ledger

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/RocksdbMetadataStore.java

Fixes #19250
Accessing a closed RocksDb database will crash the JVM. See #19250
- Check if the metadata store is closed after acquiring the read lock.

[fix][meta] Check if metadata store is closed in RocksdbMetadataStore

---

docker/pulsar-all/pom.xml
docker/pulsar/pom.xml

git supports sharing a single local directory across multiple working directories as explained in https://pulsar.apache.org/contribute/setup-git/#checking-out-each-pulsar-maintenance-branch-in-a-separate-working-directory . This makes it easier to maintain multiple Pulsar branches since each maintenance branch will be checked out in it's own working directory and could be open simultaneously in IntelliJ.
However, building docker images has been broken when using `git worktree` working directory. This is fixed with this PR.
- fix the check for git repository existence

[improve][build] Support git worktree working directory while building docker images

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/WebExecutorThreadPoolStats.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebExecutorStats.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/web/WebServiceTest.java

Adds metrics for the web service executor thread pool, as currently described [here](https://pulsar.apache.org/docs/next/reference-metrics/#web-service-executor-metrics). Reference documentation for the new metrics can be found in the respective PR: https://github.com/apache/pulsar-site/pull/907.
Expose the respective OpenTelemetry metrics in new class `org.apache.pulsar.broker.web.WebExecutorThreadPoolStats#WebExecutorThreadPoolStats`.
- Extended test `org.apache.pulsar.broker.web.WebServiceTest#testWebExecutorMetrics` to validate the OpenTelemetry metrics
PR in forked repository: https://github.com/dragosvictor/pulsar/pull/27

[feat][broker] PIP-264: Add broker web executor metrics

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerOfflineBacklog.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/BookKeeperClientFactory.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/BookKeeperClientFactoryImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/ManagedLedgerClientFactory.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/bucket/BookkeeperBucketSnapshotStorage.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java
pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactorTool.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/MockedBookKeeperClientFactory.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/MockBookKeeperClientFactory.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionRetentionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/ServiceUnitStateCompactionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/compaction/TopicCompactionServiceTest.java

Fixes #22840 
Fixes #22699
BK client creation can be blocking when it's configured with rack-awareness policy. 
This, combined with per-namespace BK client policies, can lead to deadlock situations as explained in #22840
1. Changed the BK client factory to return a future for BK client creation
2. Internally create the BK client in background 

[improve] Refactored BK ClientFactory to return futures

---

.github/workflows/pulsar-ci.yaml

Verify the arm64 image build.
- Use the matrix feature to verify the build of the linux/amd64 and linux/arm64 images.

[improve][ci] Add arm64 image build

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/manager/UnloadManager.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/manager/UnloadManagerTest.java

NPE will happen in `UnloadManager#handleEvent` after https://github.com/apache/pulsar/pull/22743. It's because the `Init` state is always associated with a null `ServiceUnitStateData`.
```
java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.broker.loadbalance.extensions.channel.ServiceUnitStateData.force()" because "data" is null
at org.apache.pulsar.broker.loadbalance.extensions.manager.UnloadManager.handleEvent(UnloadManager.java:204) ~[classes/:?]
at org.apache.pulsar.broker.loadbalance.extensions.channel.StateChangeListeners.lambda$notify$3(StateChangeListeners.java:74) ~[classes/:?]
at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[?:?]
at org.apache.pulsar.broker.loadbalance.extensions.channel.StateChangeListeners.notify(Stat …
```

[fix][broker] Fix NPE after publishing a tombstone to the service unit channel

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java

https://github.com/apache/pulsar/commit/704630b35fcf23d802ad1fc9bc27d592189a53a4 breaks the testPerTopicStats test.
Remove the suffix `_total` from `topic_load_failed_total` metric name.

[fix][test] Fix testPerTopicStats

---

bin/bookkeeper
bin/pulsar

- parameters with whitespaces won't be properly passed through to the actual command unless "$@" is used (instead of $@ without double quotes.
- fixes shellcheck warning https://github.com/koalaman/shellcheck/wiki/SC2068
- replace `$@` with `"$@"` in `bin/pulsar` and `bin/bookkeeper`

[fix][cli] Fix the shell script parameter passthrough syntax

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java

Fixes #22871
As https://github.com/apache/pulsar/pull/22820 set the default value of `LoadBalancerMemoryResourceWeight` to 0, some behavior changes resulting into the failure of `org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest#testGetMetrics`.
Set the value of `LoadBalancerMemoryResourceWeight` to 1 to pass the test.

[fix] [test] fix testGetMetrics in ExtensibleLoadManagerImplTest.

---

pulsar-opentelemetry/src/main/java/org/apache/pulsar/opentelemetry/OpenTelemetryService.java

JFR based telemetry collection consumes resources. We don't currently use the metrics for anything. 
This happens in MultiBrokerLeaderElectionTest which starts 10 embedded brokers in the test. The test JVM often fails with OOM.
&nbsp;
- disable JFR based telemetry collection since it's not used at the moment.

[fix][misc] Disable JFR based telemetry collection since it's not used

---

docker/pulsar/scripts/pulsar-zookeeper-ruok.sh

Fixes #22872 
pulsar-zookeeper-ruok.sh script doesn't work in the latest apachepulsar/pulsar:3.3.0 image.
- make the script compatible with Alpine's default busybox nc (so that it isn't necessary to install `netcat-openbsd`)
- replace "-q 1" with "sleep 1" in the input
- replace "localhost" with "127.0.0.1" (so that IPv4 gets selected?)

[fix][cli] Fix healthcheck script pulsar-zookeeper-ruok.sh

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplWithAdvertisedListenersTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplWithTransactionCoordinatorTest.java

PIP: https://github.com/apache/pulsar/blob/master/pip/pip-307.md
- PIP-307 does not cover advertised listeners. This PR is trying to support advertised listeners when gracefully transferring topics (ExtensibleLoadManagerImpl only)
By utilizing serverCnx.listenerName, added by https://github.com/apache/pulsar/pull/12056, brokers return advertised listener broker urls in the producer|consumer close commands, if the connection is through the listenerName.
```
if(serverCnx.listenerName != null){
listener =  lookup.getAdvertisedListener(serverCnx.listenerName)
return listener's brokerServiceUrl and brokerServiceUrlTls
} else {
return  lookup.pulsarServiceUrl and lookup.pulsarServiceUrlTls
}
``` …

[fix][broker] Support advertised listeners when gracefully transferring topics (ExtensibleLoadManagerImpl only)

---

pom.xml

Fixes #22874
Building Pulsar is supported with either Java 17 or Java 21. This should be enforced so that there's a clear error message when the build is run on an unsupported Java version.
Change the version range for enforcer plugin to allow all Java 17 versions and all Java 21 versions.

[improve][build] Require Java 17 or Java 21 for building Pulsar

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PersistentTopicAttributes.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicAttributes.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/OpenTelemetryTopicStats.java
pulsar-opentelemetry/src/main/java/org/apache/pulsar/opentelemetry/OpenTelemetryAttributes.java

Fixes https://github.com/apache/pulsar/issues/22817
Successive collections of OpenTelemetry metrics re-allocate all attribute sets related to a topic. Since topics are a high-cardinality object in Pulsar, this puts pressure on the GC. This PR proposes caching these attribute sets.
- Adds classes `TopicAttributes` and `PersistentTopicAttributes` to store all attribute sets relevant for a topic.
- Add and lazily initialize these attribute fields in the `NonPersistentTopic` and `PersistentTopic` objects. If OpenTelemetry is not enabled, these objects never get created, saving memory.
- Modify `OpenTelemetryTopicStats` to use the cached objects instead of re-allocating them every run.
- Relocate some of the attributes into interface `OpenTelemetryAttributes`, for a cleaner design.
This change …

[improve][broker] Reuse topic OpenTelemetry attributes

---

docker/pulsar/Dockerfile

Fixes: #22877 
The default `nslookup` in Alpine is based on busybox and it isn't compatible with Kubernetes. See #22877 for more details.
Install `bind-tools` package to get proper `nslookup`

[fix][misc] Add proper nslookup (included in bind-tools) to docker image

---

pulsar-client-admin-shaded/pom.xml
pulsar-client-all/pom.xml
pulsar-client-shaded/pom.xml
pulsar-common/pom.xml
pulsar-common/src/main/java-templates/org/apache/pulsar/PulsarVersion.java

Follow up on #22829 changes
I noticed that pulsar-common didn't have an explicit re2/j dependency and client shading configs were missing. I also noticed that PulsarVersion should continue to use plain `java.util.regex.Pattern`.
- add explicit dependency to `com.google.re2j:re2j` to pulsar-common module
- relying on an external transient dependency isn't recommended
- add shading configs for `com.google.re2j:re2j` to pulsar-client-admin-shaded, pulsar-client-all and pulsar-client-shaded
- revert changes to PulsarVersion since it doesn't contain user provided regex

[fix][build] Add re2/j dependency to pulsar-common and client shading

---

pip/pip-351.md

Fixes #xyz
Main Issue: #22678
PIP: #xyz 
If you want to create a TestClient which uses AuthenticationKeyStoreTls as its authPlugin, Pulsar Test Admin/Client utilized in Pulsar-perf is unable to setup a vaild SSL context due to the requirement of the property "useKeyStoreTls" to be "true" for using keystores properly.
Moreover, utilizing the property "useKeyStoreTls" requires the use of trust-store and not trust certificates, therefore requiring additional trustStoreType, trustStorePath and trustStorePass as parameters to be available, to utilize PulsarPerf.
Added PIP.
*(or)*
*(or)* …

[improve][pip] PIP-351: Additional options for Pulsar-Test client to support KeyStore based TLS

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
pulsar-broker/src/main/java/org/apache/pulsar/zookeeper/LocalBookkeeperEnsemble.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BKCluster.java

Fixes #22881
See #22881. The issue wasn't fully addressed in the previous fix for #16741 in #16744. That fix only deletes Bookie data, but not the RocksDB based metadata store.
- Handle deleting the RocksDB metadata store
- Add logging to all locations when data is wiped

[fix][cli] Fix Pulsar standalone "--wipe-data"

---

pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java
pulsar-common/src/test/java/org/apache/pulsar/common/naming/TopicNameTest.java

The methods `TopicName#getPersistenceNamingEncoding` and `TopicName#fromPersistenceNamingEncoding` should be symmetric. Currently, the `localName` part of the topic name is encoded into the persistence name, but it is not decoded back properly.
This update add decoding logic for the `localName` part of the topic name.
- A new test case has been added to `org.apache.pulsar.common.naming.TopicNameTest#testFromPersistenceNamingEncoding` that includes topic names with special characters.
PR in forked repository: https://github.com/Shawyeok/pulsar/pull/16

[fix][misc] Topic name from persistence name should decode local name

---

pip/pip-355.md

Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*

[improve] [pip] PIP-355: Enhancing Broker-Level Metrics for Pulsar

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/InMemTransactionBuffer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TransactionBufferDisable.java

[PersistentTopic#getLastDispatchablePosition](https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L3776-L3788) is using by 
[Reader#hasMessageAvailable](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Reader.java#L116) , [ConsumerImpl#hasMessageAvailable](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L2440-L2448), [Consumer#getLastMessageIdAsync](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L591-L615). 
The current implementation is read entries from Bookkeeper(or sth else), which leads to low …

[improve][broker] Optimize PersistentTopic.getLastDispatchablePosition

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java

There are two error in method `org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl#createLoadSheddingStrategy`.
- log `LoadSheddingStrategy` instead of `PlacementStrategy`.
- create `ThresholdShedder` by default instead of `OverloadShedder`.
~~Fix these two errors.~~
Fail fast when it failed to create LoadSheddingStrategy.

[improve] [broker] Fail fast when it failed to create LoadSheddingStrategy instance

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/OrphanPersistentTopicTest.java

We observe that a `normal topic` might reference a `closed ledger` and it never auto recover. will cause the producer and customer stuck.
The root cause is related to `topic create timeout`. Assuming we have two concurrent requests to create a topic: `firstCreate(Thread-1)`, `secondCreate(Thread-2)`
| Thread-1                                            | Thread-2                                                                      |
|----------------|-------------------------------------------------|
| firstCreate topic timeout                              |                                                                               |
|                                                     | [remove this old topic and recreate a new …

[fix][broker] The topic might reference a closed ledger

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java

- The broker could falsely return that brokers were inactive too soon if the broker registry cache was empty. 
- Asynchronously return `brokerRegistry.lookupAsync` instead of using `future.getNow`.

[fix][broker] Asynchronously return brokerRegistry.lookupAsync when checking if broker is active(ExtensibleLoadManagerImpl only)

---

bin/pulsar-daemon

Using `bin/pulsar-daemon start standalone` can't start pulsar due to https://github.com/apache/pulsar/pull/22867 changing `bin/pulsar` parameter passthrough syntax.
replace `"$1"` with `"$@"` in bin/pulsar
*(or)*
*(or)*
*(example:)*

[fix][cli] Fix the pulsar-daemon parameter passthrough syntax

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java

The #21816 introduces the `pulsar_storage_backlog_age_seconds` metrics, and refactors logic for `checkTimeBacklogExceeded`. It has two problems:
1. Even if the consumers under the topic have consumed all the data, `pulsar_storage_backlog_age_seconds` will not become **0** and will continue to increase over time. This is because its calculation: `current time - publish time of the last message`.
2. If the user has configured [BacklogQuota.message_age](https://github.com/apache/pulsar/blob/17bb3227536f891d4f2ef234da596bdb5bb46bbb/pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java#L1651-L1652), it will also affect the ability of producers to continue sending messages, even if there is currently no backlog under this topic.
1. In …

[fix][broker] Fix topic status for oldestBacklogMessageAgeSeconds continuously increases even when there is no backlog.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

[fix] [broker] Fix typo in PersistentTopicsBase

---

conf/client.conf
deployment/terraform-ansible/templates/client.conf
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/ClusterDataImpl.java

Correct the comment of tlsAllowInsecureConnection in ClusterDataImpl class.
Remove duplicated 'be'.
`Allow TLS connections to servers whose certificate cannot be be` -> 
`Allow TLS connections to servers whose certificate cannot be`

[fix][misc] Correct the comment of tlsAllowInsecureConnection in ClusterDataImpl class.

---

pulsar-opentelemetry/src/main/java/org/apache/pulsar/opentelemetry/OpenTelemetryService.java

PIP: https://github.com/apache/pulsar/blob/master/pip/pip-264.md
The recently added OpenTelemetry 'reusable data' memory mode allows the OpenTelemetry SDK to reduce the number of memory allocations in between collector runs, at the expense of parallel collection. This is a fair compromise given Pulsar's use-case, and it promises to significantly improve the performance of the metric pipeline.
Enables, by default, the OpenTelemetry 'reusable data' export mode. This can be overridden by the user at runtime via Java system property `otel.java.experimental.exporter.memory_mode` or environment variable `OTEL_JAVA_EXPERIMENTAL_EXPORTER_MEMORY_MODE`. See https://opentelemetry.io/docs/languages/java/configuration/#exporters for a few more details on the config.
This change is already covered by …

[feat][broker] PIP-264: Enable OpenTelemetry reusable data memory mode

---

bin/bookkeeper
bin/pulsar

This reverts commit c81c0f684f8c55c2e39739c6e1de935dff2085d6.
Fixes #xyz
PIP: #xyz 
#22867 introduced some break changes, such as `bin/pulsar zookeeper-shell --run-one "ls /ledgers"` can't work after introduced 22867.
Revert #22867
*(or)*
*(or)*
*(example:)*

[fix] Revert "[fix][cli] Fix the shell script parameter passthrough syntax (#22867)"

---

pip/pip-358.md

Implementation PR: https://github.com/apache/pulsar/pull/22888
Initially, we introduce `loadBalancerCPUResourceWeight`, `loadBalancerBandwidthInResourceWeight`, `loadBalancerBandwidthOutResourceWeight`, `loadBalancerMemoryResourceWeight`, `loadBalancerDirectMemoryResourceWeight` in `ThresholdShedder` to control the resource weight for different resources when calculating the load of the broker. 
Then we let it work for `LeastResourceUsageWithWeight` for better bundle placement policy.
But https://github.com/apache/pulsar/pull/19559 and https://github.com/apache/pulsar/pull/21168 have point out that the actual load of the broker is not related to the memory usage and direct memory usage, thus we have changed the default value of `loadBalancerMemoryResourceWeight`, …

[improve] [pip] PIP-358: let resource weight work for OverloadShedder, LeastLongTermMessageRate, ModularLoadManagerImpl.

---

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java
pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java
pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/process/ProcessRuntimeTest.java

Fixes #22909 
Netty's optimized direct byte buffer support is needed for high performance. Currently these debug messages will get logged when Netty library gets initialized:
* "direct buffer constructor: unavailable: Unable to make private java.nio.DirectByteBuffer(long,int) accessible: module java.base does not "opens java.nio" to unnamed module"
* "jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: class io.netty.util.internal.PlatformDependent0$7 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module"
* "java.nio.DirectByteBuffer.<init>(long, {int,long}): unavailable {}"
Another detail is that Pulsar uses com.scurrilous.circe.checksum.Crc32cIntChecksum class for checksum …

[fix][fn] Enable optimized Netty direct byte buffer support for Pulsar Function runtimes

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/TopicExistsInfo.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/GetPartitionMetadataMultiBrokerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/GetPartitionMetadataTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/lookup/http/HttpTopicLookupv2Test.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicGCTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java

Section [Instead of returning a 0 partitioned metadata, respond to a not found error when calling pulsarClient.getPartitionsForTopic(String) if the topic does not exist.](https://github.com/apache/pulsar/blob/master/pip/pip-344.md#goals)
Main PIP: [PIP-344 Correct the behavior of the public API pulsarClient.getPartitionsForTopic(topicName)](https://github.com/apache/pulsar/pull/22182)

[fix] [broker] response not-found error if topic does not exist when calling getPartitionedTopicMetadata

---

pulsar-client/src/test/java/org/apache/pulsar/client/impl/TableViewBuilderImplTest.java

Running the test TableViewBuilderImplTest results in an NPE and infinite loop.
Properly mock readNextAsync by returning an uncompleted CompletableFuture so that it doesn't cause an infinite loop.
Complete the CompletableFuture with AlreadyClosedException in test cleanup to properly close resources.

[fix][test] Fix TableViewBuilderImplTest NPE and infinite loop

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/store/TableViewLoadDataStoreImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/protocol/PulsarClientBasedHandlerTest.java

Found that init and shutdown time and other minor logic could be further improved.
- remove OWNERSHIP_CLEAN_UP_CONVERGENCE_DELAY_IN_MILLIS
- pass timeout var to unloadNamespaceBundleAsync
- pass the default bundle config when creating system namespace
- check the channel ownership before running the broker cleanup
- put timeout when init broker/bundle load store
- run cleanUnloadedTopicFromCache when bundle unload fails when disconnectClients = false

[fix][broker] Update init and shutdown time and other minor logic (ExtensibleLoadManagerImpl only)

---

pulsar-common/src/test/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerDataTest.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/BrokerMonitor.java

Use `LoadManagerReport` instead of Object.
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/crossoverJie/pulsar/pull/27

[improve][cli] Use LoadManagerReport instead of Object

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionImpl.java

Remove unneeded sync scope in TransactionImpl
*(or)*
*(or)*
*(example:)*

[cleanup][client] Remove unneeded sync scope in TransactionImpl

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java

**Background**
1. the method `PersistentTopic.addReplicationCluster` will remove orphan replication cursors, see https://github.com/apache/pulsar/pull/19972
2. when a topic is loading up, it will initialize replicators by the cursors named `pulsar.repl.<remote cluster>`
**Issue**
- Mechanism `2` was called before topic-level policies initializing, so it will remove the replicator and cursor when a topic is loading up. 
- After the topic level policies are initialized, the broker will create a new replicator with a new cursor(start at the `latest position`), and all the messages in backlog are lost.
This issue may cause messages to be lost when using topic-level Geo-Replication. For example:
- Enable topic level Geo-Replication
- Send messages on this topic
- There are 3 ledgers under the …

[fix] [broker] Messages lost on the remote cluster when using topic level replication

---

bin/bookkeeper
bin/function-localrunner
bin/pulsar
bin/pulsar-admin-common.cmd
bin/pulsar-admin-common.sh
bin/pulsar-admin.cmd
bin/pulsar-client.cmd
bin/pulsar-perf
bin/pulsar-perf.cmd
bin/pulsar-shell.cmd

* Netty's optimized direct ByteBuffer support requires passing certain parameters to the JVM.
* The legacy solution `IS_JAVA_8` should be replaced with the JAVA_MAJOR_VERSION detection solution so that parameters could be correctly set for newer Java version.
* Pulsar server side code doesn't support JVMs before 17 version. The script should exit when an older JVM is detected.
* Many of the Windows .cmd scripts were broken
- refactor scripts to use JAVA_MAJOR_VERSION
- consistently pass required JVM arguments so that Netty's optimized direct ByteBuffer gets used.
- Fixed Windows .cmd scripts and made the logic match the bash scripts.

[fix][cli] Refactor scripts to detect major Java version and pass correct add-opens parameters

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java

[PIP-356 Support Geo-Replication starts at earliest position](https://github.com/apache/pulsar/blob/master/pip/pip-356.md)
Implement_ for the broker-level config

[improve] [broker] PIP-356 Support Geo-Replication starts at earliest position

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java

Fixes #22915
Broker log a full thread dump when a deadlock is detected in healthcheck every time.
**Our expectation is：**
First detection of deadlock printing full thread dump, then printing at the interval between parameter settings in 
```java
// org.apache.pulsar.broker.admin.impl.BrokersBase.java
private static final long LOG_THREADDUMP_INTERVAL_WHEN_DEADLOCK_DETECTED = 600000L;
```
1. class：`org.apache.pulsar.broker.admin.impl.BrokersBase.java ` Variable `threadDumpLoggedTimestamp ` decorated with `static` keyword. Avoid initializing parameters with a value of 0 every time the interface is called.
2. Method `checkDeadlockedThreads` comparison before and after modification:
(1) before:
```java
private void checkDeadlockedThreads() {
ThreadMXBean threadBean = …
```

[fix] [broker] broker log a full thread dump when a deadlock is detected in healthcheck every time

---

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ProducerBuilderFactory.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java
pulsar-functions/instance/src/main/resources/findbugsExclude.xml
pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ContextImplTest.java
pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ProducerBuilderFactoryTest.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SourceConfigUtils.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/FunctionConfigUtilsTest.java

Fixes #22948
See #22948. There are 2 locations in code where producers are created in Pulsar Functions and Connectors.
The other location has been ignored for compression type support in #19470 and for crypto config in #8432.
- Refactor code to remove code duplication.
- Create ProducerBuilderFactory class
- Move crypto initialization to this class
- Move ProducerBuilder configuration to this class
- Use ProducerBuilderFactory to create ProducerBuilders

[fix][fn] Support compression type and crypto config for all producers in Functions and Connectors

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java

https://github.com/apache/pulsar/pull/21248 improves the backlog calculation.
When `isPrecise` is false, sometimes it will fall back to the precise backlog count, if the mark delete position is greater than the last position, this will throw the invalid range:
```
2024-06-20T07:49:44,282+0800 [pulsar-stats-updater-32-1] ERROR org.apache.pulsar.broker.service.persis
tent.PersistentTopic
- Got exception when creating consumer stats for subscription xxxxx: Invalid range: (1563151:-1..1561964:1067]
```
- Add the mark delete position and last position checks, and then calculate the backlog
This PR encapsulates the code without changing its original behavior.

[fix][broker] Check the markDeletePosition and calculate the backlog

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
pulsar-common/pom.xml

- explained in https://github.com/netty/netty/blob/217df76/transport-native-epoll/pom.xml#L208-L218: 
> The unix-common with classifier dependency is optional because it is not a runtime dependency, but a build time dependency to get the static library which is built directly into the shared library generated by this project.
- remove classifier from netty-transport-native-unix-common dependency

[cleanup][misc] Remove classifier from netty-transport-native-unix-common dependency

---

docker/glibc-package/Dockerfile
docker/pulsar/Dockerfile

The base image was set to 3.19.1 . It's better to use a top level version so that an updated base image is used for builds.
The version tag wasn't set for intermediate build images and 3.20 was already used. Instead of sticking to 3.19, it's better to migrate to use 3.20 since it's already stable. 
- consistently use alpine:3.20 as the base image

[improve][misc] Set Alpine base image to 3.20 instead of 3.19.1

---

pulsar-client-admin-shaded/pom.xml

It's necessary to rename the bundled Netty native libraries in the shaded jar file.
This has been done for pulsar-client and pulsar-client-all. Netty is also included in pulsar-client-admin-shaded and the renaming has been missing.
- add similar renaming to `pulsar-client-admin-shaded/pom.xml`
Using pulsar-client-admin dependency might cause applications to crash if the application uses an older version of Netty or Netty Tcnative. The workaround to this issue (before the fix in this PR is released) is to use the shaded pulsar-client-all dependency (which includes both the Java client and the Admin client) instead of using pulsar-client-admin dependency.

[fix][misc] Rename netty native libraries in pulsar-client-admin-shaded

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java

The loading of TC onto which broker depends on which broker the `transaction_coordinator_assign-partition-${TC ID}` is loaded onto.
In order to improve service availability, we need to distribute TC evenly across the entire cluster as much as possible, avoiding all TCs from being loaded onto a few machines.
For example, if all 16 TCs are loaded onto two or three brokers, restarting the broker during cluster rolling upgrades will result in a large number of TCs becoming unavailable simultaneously, which will significantly affect the transaction client.
All shedding algorithm pick up the bundles based on throughput or message rate from the top to the bottom. **However, the system topic has almost no traffic, which means system topic can't be re-distribute evenly with shedding algo.** …

[improve] [broker] make system topic distribute evenly.

---

.github/workflows/ci-maven-cache-update.yaml
.github/workflows/pulsar-ci.yaml

macos-11 runner has been deprecated since January and it will be completely removed in GitHub Actions on June 28th 2024. Jobs are currently failing intentionally by GitHub to raise awareness of the deprecation.
Details are explained [in the GitHub blog post](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/).
replace `macos-11` with `macos-latest`

[fix][ci] Replace removed macos-11 with macos-latest in GitHub Actions

---

build/pulsar_ci_tool.sh
jetcd-core-shaded/pom.xml
pom.xml

Jacoco code coverage report aggregation is currently broken in CI.
[Example failure](https://github.com/apache/pulsar/actions/runs/9644239258/job/26599083286?pr=22962#step:10:258)
```
Error: Exception in thread "main" java.io.IOException: Error while analyzing /tmp/jacocoDir/pulsar_lib/org.apache.pulsar-jetcd-core-shaded-3.4.0-SNAPSHOT-shaded.jar@META-INF/versions/11/io/vertx/core/DeploymentOptions.class with JaCoCo 0.8.11.202310140853/f33756c.
at org.jacoco.cli.internal.core.analysis.Analyzer.analyzerError(Analyzer.java:163)
at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:135)
at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:158)
at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:195)
at …
```

[fix][ci] Fix jacoco code coverage report aggregation

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java

| `time`| `thread: ConsumerImpl.connectionOpened` | `thread: ConsumerImpl.closeAsync` |
| 1 | check connect state: <br> - reconnectiong <br> - `cnx` is `null` | |
| 2 | | Change state to `ready` |
| 3 | | Reconnected |
| 4 | Change state to `closed` and skip sending <br> requests to remove consumer in broker memory | |
After the above steps, there is an orphan consumer in the broker memory, which will cause the error `Exclusive consumer is already connected` and other errors.
BTW, this issue may cause the compaction task stuck, because the new reader can not be created successfully due to the previous consumer has not been removed.
You can reproduce the issue by the test `testConcurrencyClose` in the PR https://github.com/apache/pulsar/pull/22959
Fix the issue.
PR in …

[fix][client] Fix orphan consumer when reconnection and closing are concurrency executing

---

pulsar-functions/instance/pom.xml
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ProducerCache.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java
pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ContextImplTest.java
pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/sink/PulsarSinkTest.java

In Pulsar Functions and Pulsar IO Connectors, there's a Pulsar Producer cache, that 
doesn't expire the producers and doesn't have a maximum size.
This is a problem for functions/connectors that produce to a large number of topics.
- Extract common ProducerCache
- common Producer cache with separate cache areas for
- producers created by calling Context, SinkContext, SourceContext methods
- producers created in Pulsar Sources
- multiple topics are possible by returning destination topics by SinkRecord.getDestinationTopic call
- Keep backwards compatibility on the cache key
- `useThreadLocalProducers` will use the Thread's ID as part of the key so that each thread has it's own isolated producer
- In Sources, the SinkRecord.getPartitionId() is used as part of the cache key
- Cache size is …

[improve][fn] Make producer cache bounded and expiring in Functions/Connectors

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java

Fixes #22967
There's a bug in updatePartitionedTopic when replication is defined at namespace level and there's a topic policy available for the topic that is updated. This seems to be a gap in #22769.
- add a failing test case
- fix the bug

[fix][broker] Fix updatePartitionedTopic when replication at ns level and topic policy is set

---

docker/pulsar/Dockerfile

`wget -O /etc/apk/keys/amazoncorretto.rsa.pub https://apk.corretto.aws/amazoncorretto.rsa.pub`occasionally timeout.
- Use `amazoncorretto:21-alpine` image instead of apk installation

[improve][build] Use amazoncorretto:21-alpine image instead of apk installation

---

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java

The document states that `ackTimeoutRedeliveryBackoff` cannot be used with `consumer.negativeAcknowledge(MessageId messageId)`. However, this is confusing. The `ackTimeoutRedeliveryBackoff` should not relate to the nack.
- Fix the doc for the `ackTimeoutRedeliveryBackoff`
- Improve the doc for `negativeAckRedeliveryBackoff` and `ackTimeoutRedeliveryBackoff`

[fix][doc] Fix the doc for the message redelivery backoff

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarChannelInitializer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java

Fixes #22975
Pulsar broker will start serving requests while the broker is starting. This can cause issues and bugs which are hard to reproduce. Serving requests should be delayed until the broker is ready.
The `brokerId` bug #22975 is just one example of problems that this PR will address.
- start Pulsar binary protocol connections with autoread set to false so that request handling can be postponed
- enable autoread after PulsarService has been started
- add solution to PulsarService for running a function when the service has been started
- add a filter to REST implementation which blocks until PulsarService is started
- add solution to PulsarService to wait until the service has been started

[fix][broker] Ensure that PulsarService is ready for serving incoming requests

---

pip/pip-363.md
pip/pip-364.md

Implementation PR: https://github.com/apache/pulsar/pull/22949
Current load balance algo has defect.
Introduce a new load balance algorithm AvgShedder.

[improve] [pip] PIP-364: Introduce a new load balance algorithm AvgShedder

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorRateLimiterTest.java

When the replicator rate limit value based on bytes is less than the `org.apache.pulsar.broker.service.persistent.PersistentReplicator#readMaxSizeBytes`, this will cause the outgoing bytes to exceed the limit value.
The goal is to make outgoing bytes as close to the rate limit value as possible.
- `org.apache.pulsar.broker.service.persistent.PersistentReplicator#getAvailablePermits` returns the available messages and bytes, and then reads the entries based on that.
The test has been added.

[Fix][broker] Limit replication rate based on bytes

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/Policies.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/PolicyName.java

(cherry-picked from commit https://github.com/apache/pulsar/commit/36bae695fb07f3ee790bee603149c4c2712187e0)
Cherry-picked from #22378
*(or)*
*(or)*
*(example:)*

[feat][broker][branch-3.0] PIP-321 Introduce allowed-cluster at the namespace level (#22378)

---

pulsar-package-management/bookkeeper-storage/src/main/java/org/apache/pulsar/packages/management/storage/bookkeeper/DLOutputStream.java
pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/DLOutputStreamTest.java

Using package API to upload a large package may cause broker OOM.
Because in the current implementation, will copy all data to the heap.
https://github.com/apache/pulsar/blob/2c6fcc7eb8343583ffb48dec937334a5f05afbae/pulsar-package-management/bookkeeper-storage/src/main/java/org/apache/pulsar/packages/management/storage/bookkeeper/DLOutputStream.java#L60-L65
Each time, only copy the size of one record and then upload it directly. 
There is no need to worry about batching, as the `distributedlog client` will handle the batching.
- All related to package management test will pass.

[fix][broker] Fix broker OOM when upload a large package.

---

tests/integration/src/test/resources/containers/otel-collector-config.yaml

Fixes https://github.com/apache/pulsar/issues/22995
OpenTelemetry integration tests are broken due to an upstream change in the OTel receiver. The receiver had a breaking change in v0.104.0, where the listener binds to localhost unless otherwise instructed ([ref](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.104.0)).
Bind the receiver to `0.0.0.0:4317` for the integration tests.
This change is already covered by existing tests, such as `org.apache.pulsar.tests.integration.metrics.OpenTelemetrySanityTest#testOpenTelemetryMetricsOtlpExport`

[fix][test] Update OpenTelemetry receiver endpoint in integration test

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/TokenExpirationProduceConsumerTest.java

After #22838, if to connect a non-persist topic when broker enable client TLS, will failed.
```
2024-07-02T17:04:47,703 - WARN  - [pulsar-io-19-4:ClientCnx] - Error during handshake
java.nio.channels.ClosedChannelException: null
at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1154) ~[netty-handler-4.1.111.Final.jar:4.1.111.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[netty-transport-4.1.111.Final.jar:4.1.111.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) …
```

[fix][broker] Can't connecte to non-persist topic when enable broker client tls

---

pip/pip-337.md

PIP-337: Create a new SSL Factory Plugin to customize SSL Context and SSL Engine Generation
Apache Pulsar's TLS encryption configuration is not pluggable. It only supports file-based certificates. This makes 
Pulsar difficult to adopt for organizations that require loading TLS certificates by other mechanisms.
*(or)*
*(or)*
*(example:)* …

[improve][pip] PIP-337: SSL Factory Plugin to customize SSL Context and SSL Engine generation

---

.github/workflows/ci-owasp-dependency-check.yaml
.github/workflows/pulsar-ci.yaml
distribution/io/pom.xml
pom.xml
pulsar-io/docs/pom.xml
pulsar-io/flume/pom.xml
pulsar-io/hbase/pom.xml
pulsar-io/hdfs2/pom.xml
pulsar-io/hdfs3/pom.xml
tiered-storage/file-system/pom.xml

OWASP Dependency Check download times out. See https://lists.apache.org/thread/hmlz12lxrntlylfo2424pcw0ktrkvqbq for more details.
- Upgrade plugin version to 10.0.1
- Specify NVD API key using NIST_NVD_API_KEY secret which is mapped to NIST_NVD_API_KEY environment variable.
- Use pluginManagement to configure plugin version
- Run schedule dependency check for branch-3.3, branch-3.2, branch-3.0 and master branches

[fix][ci] Fix OWASP Dependency Check download by using NVD API key

---

pulsar-opentelemetry/src/main/java/org/apache/pulsar/opentelemetry/OpenTelemetryService.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/metrics/OpenTelemetrySanityTest.java

The OpenTelemetry collector can be configured to expose the metrics as a Prometheus server, simplifying the deployment and migration of the telemetry pipeline. Pulsar supports this feature out of the box.
There is a catch though: the Prometheus exporter did not copy the OpenTelemetry resource attributes over to corresponding Prometheus labels, so vital information was lost in this process. This limitation is described in https://github.com/open-telemetry/opentelemetry-java/issues/6108, which has since been fixed. The present PR leverages this improvement, instructing the OpenTelemetry SDK to migrate _all_ resource attributes over to Prometheus as labels.
- During OpenTelemetry SDK initialization in …

[feat][misc] PIP-264: Copy OpenTelemetry resource attributes to Prometheus labels

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/TopicDuplicationTest.java

Fixes https://github.com/apache/pulsar/issues/23003
As shown in the issue. fix the risk of topic loading stuck. 
1. make takeSnapshot() async , and if topic loading timeout, topic close should wait until takeSnapshot finish. This would not influence the other area where using takeSnapshot()
3. add test for this issue scene

[fix][broker] Fix MessageDeduplication replay timeout cause topic loading stuck

---

distribution/server/src/assemble/LICENSE.bin.txt
distribution/shell/src/assemble/LICENSE.bin.txt
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/RangeSetWrapper.java
pom.xml
pulsar-common/pom.xml
pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/OpenLongPairRangeSet.java

Fixes #22866
There has been a previous attempt to address #22866 in #22908 which caused regressions and this PR was reverted by #22968. 
After that, PR #22966 made ConcurrentOpenLongPairRangeSet thread safe and renamed the class to OpenLongPairRangeSet. The PR makes changes to the class to properly and consistently use the existing ReadWriteLock for all accesses. 
This PR contains the next step to use the RoaringBitSet class that @dao-jun has contributed to RoaringBitmap 1.1.0. The usage of RoaringBitmap reduces memory usage compared to java.util.BitSet and presumable addresses issue #22866.
- Upgrade RoaringBitmap to 1.2.0
- Remove unnecessary options from OpenLongPairRangeSet class
- Use RoaringBitSet in OpenLongPairRangeSet as the BitSet implementation

[improve][broker] Use RoaringBitmap in tracking individual acks to reduce memory usage

---

pulsar-broker/src/main/java/org/apache/pulsar/zookeeper/LocalBookkeeperEnsemble.java
pulsar-broker/src/test/java/org/apache/pulsar/zookeeper/LocalBookkeeperEnsembleTest.java

Fixes #22992
Replace hard coded port with `streamStoragePort` field in `LocalBookkeeperEnsemble`.
NO
PR in forked repository: https://github.com/zhouyifan279/pulsar/pull/1

[fix][broker] PulsarStandalone started with error if --stream-storage-port is not 4181

---

distribution/shell/src/assemble/LICENSE.bin.txt
managed-ledger/pom.xml
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/RangeSetWrapper.java
pulsar-common/pom.xml
pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/OpenLongPairRangeSet.java

This is a follow-up to #23006
- pulsar-common is also used by the client, a new dependency shouldn't be introduced without a reason.
- pass a supplier for creating the RoaringBitmap's RoaringBitSet. Add the RoaringBitmap dependency to managed-ledger module instead of pulsar-common.

[fix][misc] Remove RoaringBitmap dependency from pulsar-common

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicList.java
pulsar-common/src/test/java/org/apache/pulsar/common/topics/TopicListTest.java

**Background**
- `Pattern.quote` returns a literal pattern string for the specified
- The result of `Pattern.quote("123")` will be `\Q123\E`
**Issue**
So far, `TopicList.removeTopicDomainScheme` will remove `\Q` which is the prefix of the input string. It leads ` lookupService.getTopicsUnderNamespace` can not work with a quote pattern.
Fix the bug

[fix][broker]Fix lookupService.getTopicsUnderNamespace can not work with a quote pattern

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java

The method `BrokerService. getClusterPulsarAdmin` will throw exceptions and the method `topics set replicated clusters` did not catch the exception, which leads to the complete future can not be completed.  Eventually, the API `enbale topic-level replication` gets stuck.
fix the bug

[fix][broker] Fix stuck when enable topic level replication and build remote admin fails

---

pip/pip-359.md

PIP-359
Implementation PR：https://github.com/apache/pulsar/pull/22861
*(or)*
*(or)*
*(example:)*

[improve][pip] PIP-359: Support custom message listener executor for specific subscription

---

pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java

Fixes #22969
As a websocket client, I need to subscribe to a persistent topic that has existing messages.
I need to consume all messages, starting from the first (earliest) one, and keep consuming messages as they become available.
Persistent subscription cursor is needed, hence the use of consumer api.
There is no parameter available for this setting shown in the documentation, or in the code that creates the subscription.
There is a similar setting messageId for the Reader endpoint.
But not for the Consumer endpoint.
Passthru the SubscriptionInitialPosition query parameter to the Consumer java API.

[feat][ws]Add support for initialSubscriptionPosition in Websocket Consumer

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java

We are facing FD reaching max limit even with configuring `maxConcrruentConnection` therefore, we should have debug log that can help the users collect more info when a particular cnx opens and closes gracefully with active cnx count. This PR adds more debug log for better troubleshooting.
Adding more debug logs.
*(or)*
*(or)*
*(example:)* …

[improve][proxy] Add debug logs for proxy cnx management

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/RateLimitingFilter.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/web/WebServiceTest.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PulsarWorkerOpenTelemetry.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/WorkerServer.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/WebServer.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/stats/PulsarProxyOpenTelemetry.java

Adds metrics for the HTTP `RateLimitingFilter` class, currently exposed as Prometheus metric `pulsar_broker_http_rejected_requests` ([ref](https://github.com/apache/pulsar/blob/23163f97b7e971e8e6cc07a6e20899c49e435bef/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/RateLimitingFilter.java#L40)).
- Added metrics, as described by https://github.com/apache/pulsar-site/pull/944, to the OpenTelemetry pipeline.
- Deviating from the exiting design, the new metric exposes counters for both accepted and rejected requests. The cost for doing this is very small, and we get increased visibility into the server.
- Note this PR only exposes these values for the broker. The proxy and function worker integration will …

[feat][misc] PIP-264: Add OpenTelemetry HTTP rate limiting filter metric

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ConsumerStats.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionStats.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/ConsumerStatsImpl.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java

PIP: #20776 
Key_Shared has a mechanism called the "recently joined consumers" to keep message ordering.
However, currently, it doesn't care about some corner cases.
More specifically, we found two out-of-order issues cased by:
1. [issue-1] The race condition in the "recently joined consumers", where consumers can be added before finishing reading and dispatching messages from ledgers.
2. [issue-2] Messages could be added to messagesToRedeliver without consumer-side operations such as unacknowledgement.
We should care about these cases in Key_Shared subscription.
(For more details, please see the PIP document.)
1. Introduce the new position (the lastSentPosition and individuallySentPositions) and use them in PersistentStickyKeyDispatcherMultipleConsumers.
2. Rename the consumer stats …

[fix][broker] Introduce the last sent position to fix message ordering issues in Key_Shared (PIP-282)

---

conf/broker.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/AvgShedder.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerStrategyTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/AvgShedderTest.java

https://github.com/apache/pulsar/pull/22949

[improve][broker][branch-3.0] PIP-364: Introduce a new load balance algorithm AvgShedder
