pulsar-io/jdbc/core/pom.xml, pulsar-io/jdbc/core/src/main/java/org/apache/pulsar/io/jdbc/BaseJdbcAutoSchemaSink.java, pulsar-io/jdbc/core/src/test/java/org/apache/pulsar/io/jdbc/BaseJdbcAutoSchemaSinkTest.java
Currently, when JDBC to convert value that has substructure schema, will get error:
```
java.lang.Exception: Not supported value type, need to add it. class org.apache.pulsar.client.impl.schema.generic.GenericJsonRecord
```
I know handling substructure types is complex, and JDBC databases may not always support defining substructure types.
However, it is possible to write the substructure type as a JSON string into the table. This can be very useful for databases that support JSON parsing.
For examples:
1. JSON data
```
{
"state": "ts",
"zipCode": 1000,
"pcList": [
{
"brand": "b1",
"model": "m1"
},
{
"brand": "b2",
"model": "m2"
}
]
}
```
2. We can insert it to table like:
|state|zipCode|pcList|
|---|---|---|
|ts|1000|[{"brand":"b1","model":"m1"},{"brand":"b2","model":"m2"}]|
- When …
=> [improve][io] The JDBC connector supports JSON substructure schema

pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenLongPairRangeSet.java
https://github.com/apache/pulsar/pull/21953 is an old PR, it depends on `ConcurrentOpenLongPairRangeSet.java`, but before #21953 was merged, the class `ConcurrentOpenLongPairRangeSet` has been removed. 
https://github.com/apache/pulsar/actions/runs/10006362098/job/27658946408?pr=23052
```
Error:  /home/runner/work/pulsar/pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java:[61,49] cannot find symbol
```
Just fix the compile error, if `ConcurrentOpenLongPairRangeSet` is needed to remove, please use a separate PR to improve it.
=> [fix] [broker] fix compile error for PersistentStickyKeyDispatcherMultipleConsumers

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadSheddingTask.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleLoadManagerImplTest.java
don't do load shedding when metadata service not available.
if unload bundle when metadata service not available, these topics which in this bundle can't recover the current ledger and send read again
1. check metadata service state when do load shedding task
2. do not interrupt the task are doing in the same time
*(or)*
*(or)*
*(example:)* …
=> [improve][broker] don't do load shedding when metadata service not available

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ZKReconnectTest.java
GetPartitionMetadata fail also can produce messages
- 'autoUpdatePartitionsInterval' will get partition metadata and will regularly detect partition changes
- if GetPartitionMetadata will return ServiceNotReady, client receive ServiceNotReady will close cnx
- if close the current cnx, all producers and consumers witch use this cnx will close and reconnect
(https://github.com/apache/pulsar/blob/5c6602cbb3660a696bf960f2847aac1a2ae037d2/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L323-L345)
- this will influence a lot of producers and consumers and if current time the zk not available and bundle cache not exist the topic's bundle metadata, the client can't send messages to broker because the producer lookup will fail
GetPartitionMetadata return MetadataError when …
=> [improve][broker] GetPartitionMetadata fail also can produce messages

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/OrphanPersistentTopicTest.java
Since #22860 is difficult to cherry-pick into `branch-2.11`, this PR provides a fast fix and cherry-picked the test `testCloseLedgerThatTopicAfterCreateTimeout` that added in #22860
=> [fix][broker][branch-2.11] The topic might reference a closed ledger (#22860)

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/StandaloneTest.java, pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java, pulsar-broker/src/test/resources/configurations/pulsar_broker_test.conf, pulsar-broker/src/test/resources/configurations/pulsar_broker_test_standalone.conf, pulsar-common/src/main/java/org/apache/pulsar/common/naming/NamespaceName.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java
`LoadableCache.get` cost too many CPU resources
[broker_cpu.html.txt](https://github.com/user-attachments/files/16278265/broker_cpu.html.txt)
```
pulsar-io-4-20" #135 prio=5 os_prio=0 cpu=79326083.91ms elapsed=1465985.25s tid=0x00007f5bc40740b0 nid=0xe9 runnable  [0x00007f5ba51fd000]
at java.util.concurrent.ConcurrentLinkedQueue.offer(java.base@17.0.10/ConcurrentLinkedQueue.java:380)
at java.util.concurrent.ConcurrentLinkedQueue.add(java.base@17.0.10/ConcurrentLinkedQueue.java:283)
at com.google.common.cache.LocalCache$Segment.recordRead(LocalCache.java:2546)
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2068)
at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4 …
```
=> [improve] [broker] Improve CPU resources usege of TopicName Cache

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/InflightReadsLimiter.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheManagerImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/cache/InflightReadsLimiterTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/cache/PendingReadsManagerTest.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnxThrottleTracker.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessagePublishBufferThrottleTest.java, pulsar-opentelemetry/src/main/java/org/apache/pulsar/opentelemetry/OpenTelemetryAttributes.java
Adds messaging rate limit metrics, currently exposed in classes `InflightReadsLimiter` and `ServerCnxThrottleTracker`, to the OpenTelemetry pipeline.
- Added metrics, as described by https://github.com/apache/pulsar-site/pull/943, to the OpenTelemetry pipeline.
- The metrics differ slightly from the existing ones:
- Connection throttling metrics are cumulative totals, instead of the instantaneous value in the existing Prometheus metric `pulsar_broker_throttled_connections`. This gives better visibility into the frequency of rate limiting operations.
- Connection throttling metrics are exposed for pause/resume operations too.
- Managed ledger inflight reads metrics expose both the hard-wired limit and current usage, for …
=> [feat][misc] PIP-264: Add OpenTelemetry messaging rate limit metrics

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
- Found a bug that the ownership monitor tries to clean owned bundles from inactive source brokers
- Fix the bug not to clean owned bundles from inactive source brokers
- Cleaned/refactored override ownership code
- Skip unloading LB internal topics. Instead, close those topics when shutting down the broker.
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/75
=> [fix][broker] Do not try to clean owned bundles from inactive source brokers (ExtensibleLoadManagerImpl only)

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/TopicPoliciesSystemTopicClient.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/TransactionBufferSnapshotBaseSystemTopicClient.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/SystemTopicNames.java
Fixes #xyz
PIP: #xyz 
We have many system topics, such as
- __change_events
- __transaction_buffer_snapshot
- __transaction_buffer_snapshot_indexes
- __transaction_buffer_snapshot_segments
- transaction_coordinator_assign
- __transaction_log_
- __transaction_pending_ack
In Pulsar Broker, we create an internal reader to fetch messages from those system topics. Due to we do not specify the subscription prefix, the reader will generate a random subscription name for each reader. 
In [PIP-355](https://github.com/apache/pulsar/pull/22778), we introduced a broker-level metric named `pulsar_broker_out_bytes_total`, which separate the system subscription traffic bytes and user subscription traffic bytes. Due to the internal readers don't have a subscription prefix, we group the …
=> [improve] [broker] Add subscription prefix for internal reader

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
(cherry picked from commit 55e468ee412fff9706f6badcd07b5c8f11ed8375)
=> [fix][broker][branch-3.1] Do not try to clean owned bundles from inactive source brokers (ExtensibleLoadManagerImpl only) (#23064)

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
related: https://github.com/apache/pulsar/pull/20750
When adding to `unAckedMessageTracker`, the messageId type is converted to `MessageIdImpl`.
- https://github.com/apache/pulsar/blob/v3.3.0/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java#L1162-L1167
- https://github.com/apache/pulsar/blob/v3.3.0/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1820-L1827
If calling `ConsumerImpl#negativeAcknowledge(MessageId)` and the messageId type is `BatchMessageIdImpl`, the message will not be removed from the `unAckedMessageTracker`.
https://github.com/apache/pulsar/blob/v3.3.0/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L814
This will cause both negative ack redeliver and ack timeout redeliver.
Convert the …
=> [fix][client] Fix negative acknowledgement by messageId

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
A deadlock occurs.
```
"metadata-store-13-1" #16 prio=5 os_prio=0 cpu=621052.68ms elapsed=249537.73s tid=0x00007f31415b8570 nid=0x6a waiting on condition  [0x00007f3118ffd000]
at jdk.internal.misc.Unsafe.park(java.base@17.0.11/Native Method)
- parking to wait for  <0x00000000e50e8200> (a java.util.concurrent.CompletableFuture$Signaller)
at java.util.concurrent.locks.LockSupport.park(java.base@17.0.11/LockSupport.java:211)
at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.11/CompletableFuture.java:1864)
at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.11/ForkJoinPool.java:3465)
at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.11/ForkJoinPool.java:3436)
at …
```
=> [fix] [broker] Remove blocking calls from Subscription.getStats

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/MaxProducerTest.java
**Background**
- Pulsar checks compatible of schemas when adding producers/consumers
- After checking schemas, it checks the max producers/consumers count.
**Issue**
- If the clients have already reached max limitation of producers/consumers count, the client will try to register producers/consumers continuously.
- It checks schemas, then checks the max producers/consumers count. This will waste many CPU resources to check the compatibility of schemas.
-  Check max producers/consumers limitation first before other ops to save resources
=> [improve] [broker] Check max producers/consumers limitation first before other ops to save resources

docker/pom.xml, docker/pulsar-all/pom.xml, docker/pulsar/pom.xml, pom.xml
docker-maven-plugin keeps up to the latest version.
- Improve `docker-push` profile
- Remove tag goal, because build goal includes tag feature
- Upgrade docker-maven-plugin to 0.45.0
=> [improve][build] Upgrade docker-maven-plugin to 0.45.0

.github/workflows/ci-maven-cache-update.yaml, .github/workflows/ci-owasp-dependency-check.yaml, .github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml, .mvn/extensions.xml
- fixes deprecation warning:  `The deprecated "GRADLE_ENTERPRISE_ACCESS_KEY" environment variable has been replaced by "DEVELOCITY_ACCESS_KEY"`
- this is used to access [ASF Gradle Develocity server ge.apache.org](https://ge.apache.org/scans?search.rootProjectNames=Pulsar)
- rename environment variable name `GRADLE_ENTERPRISE_ACCESS_KEY` to `DEVELOCITY_ACCESS_KEY`
- Upgrade com.gradle:develocity-maven-extension from 1.21.4 to 1.21.6
=> [improve][ci] Switch to use DEVELOCITY_ACCESS_KEY from GRADLE_ENTERPRISE_ACCESS_KEY

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicTxnBufferSnapshotService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TransactionBufferSnapshotServiceFactory.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SnapshotSegmentAbortedTxnProcessorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SnapshotTableView.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TableView.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java, pulsar-broker/src/main/java/org/apache/pulsar/utils/SimpleCache.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java, pulsar-broker/src/test/java/org/apache/pulsar/utils/SimpleCacheTest.java
During the rolling restarts, the namespace bundle ownerships will change. Assuming there is a producer created on a single topic, and the ownership was transferred to the new broker. Assuming the namespace bundle has N topics and the namespace is `tenant/ns`,
1. All N topics in the same bundle of that topic will be loaded.
2. For each topic, the managed ledger will be initialized, when the transaction coordinator is enabled, a `TopicTransactionBuffer` will be created. A Pulsar reader will be created on `tenant/ns/__transaction_buffer_snapshot` concurrently.
3. Once all N readers are created, the owner of the snapshot topic will start dispatching messages to N readers. Each dispatcher will read messages from BookKeeper concurrently and might fail with too many requests error because BK can …
=> [improve][broker] Reduce the CPU pressure from the transaction buffer in rolling restarts

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
If a subscription has many consumers and each consumer individually acknowledges messages from other consumers, this scenario is very CPU resource-intensive.
Refer this:
In fact, these three methods achieve the same goal: `get owning consumer by message ID`
This operation is very CPU resource-intensive
**getAckOwnerConsumer**:
https://github.com/apache/pulsar/blob/d7e8ea16e6682df9a9354cda25cf4f1f9cb54429/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java#L735-L748
**getBatchSize**:
https://github.com/apache/pulsar/blob/d7e8ea16e6682df9a9354cda25cf4f1f9cb54429/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java#L657
**removePendingAcks**:
https://github.com/apache/pulsar/blob/d7e8ea16e6682df9a9354cda25cf4f1f9cb54429/pulsar-broker/src/main/java/ …
=> [improve][broker] Optimize the performance of individual acknowledgments

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/Ipv4Proxy.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/NetworkErrorTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ZkSessionExpireTest.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java
- settings: enable `systemTopic & topicLevelPolicies`.
- Own topics
- `broker-2` loads a `topic-a` up.
- `broker-2` loads system topic(`{ns}/__change_events`) up.
- The ZK session expires.
- Bundle shedding 
- `topic-a` was transferred to `broker-0`
- the system topic(`{ns}/__change_events`) was transferred to `broker-0`
- **(Highlight)** Issue occurs on `broker-2`
-  The internal reader for `{ns}/__change_events` lookup the topic's owner
- `broker-2` responds `broker-2` due to its `OwnershipCache` contains the old value.
- The internal reader for `{ns}/__change_events` can not be created successfully, all topics under this namespace can not work.
- The consumers/producers who call lookup to `broker-2` will get a wrong value, and keep getting a "Please redo the lookup" error.
- Broker …
=> [fix] [broker] Internal reader of __change_events can not started after metadata store session rebuilt

docker/pom.xml, docker/pulsar-all/pom.xml, docker/pulsar/pom.xml
The profile refactoring breaks the pulsar release in the #23091.
- Move docker-push profile to docker/pulsar and docker/pulsar-all modules
=> [improve][build] Move docker-push profile to submodule

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/coordinator/TransactionCoordinatorClientTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionCoordinatorClientImpl.java
we have two brokerUrls(one is dead) in PulsarClient serviceUrl, it is working well without enabling transactions.
```
PulsarClient client = PulsarClient.builder()
//.enableTransaction(true)
.serviceUrl("pulsar://test.pulsar.com:6650,test.pulsar.com:6651")
.build();
```
If  enabling transactions
```
PulsarClient client = PulsarClient.builder()
.enableTransaction(true)
.serviceUrl("pulsar://test.pulsar.com:6650,test.pulsar.com:6651")
.build();
```
the following error occurs and the `PulsarClient` init fails, It will not retry the other brokerUrl
```
2024-07-27T00:52:27,787 - ERROR - [pulsar-client-io-1-1:TransactionMetaStoreHandler@120] - Transaction meta handler with transaction coordinator id 14 connection failed.
org.apache.pulsar.client.api.PulsarClientException: …
```
=> [fix][client] TransactionCoordinatorClient support retry

pip/pip-352.md
PIP: 352
Currently, there are two types of compactors
available: `TwoPhaseCompactor` and `StrategicTwoPhaseCompactor`. The latter
is specifically utilized for internal load balancing purposes and is not
employed for regular compaction of Pulsar topics. On the other hand, the
former can be configured via `CompactionServiceFactory` in the
`broker.conf`.
I believe it could be advantageous to introduce another type of topic
compactor that operates based on event time. Such a compactor would have
the capability to maintain desired messages within the topic while
preserving the order expected by external applications. Although
applications may send messages with the current event time, variations in
network conditions or redeliveries could result in messages being stored in
the Pulsar topic in …
=> [improve][pip] PIP-352: Event time based topic compactor

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/OrphanPersistentTopicTest.java
Fixes:  fix irregular method name
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/AuroraTwinkle/pulsar/pull/5
=> [fix][broker]: fix irregular method name

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
Main Issue: https://github.com/apache/pulsar/issues/23101
As shown in the issue. fix exception may hidden and result in stuck when topic loading
catch all exceptions which is throw by persistentTopic construct.
=> [fix][broker] fix exception may hidden and result in stuck when topic loading

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicUtils.java
From: https://github.com/apache/pulsar/pull/23102#issuecomment-2262852009
Typecast on exceptions failed in `future.exceptionally` will cause lost calls, and not having any log.
Ensure that all conversions of `ManagedLedgerException` are preceded by checks.
- All unit tests passed, not have any behavior change.
=> [fix][broker] type cast on exceptions in exceptionally can lead to lost calls

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/PulsarZooKeeperClient.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/OxiaMetadataStore.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BaseMetadataStoreTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java, pulsar-metadata/src/test/resources/oxia_client.conf, pulsar-metadata/src/test/resources/zk_client_disabled_sasl.conf
Implementation PR for PIP: https://github.com/apache/pulsar/pull/23033.
Support to specify different config for Configuration and Local Metadata Store in zk and oxia impl
=> [improve][pip] PIP-366: Support to specify different config for Configuration and Local Metadata Store

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderList.java
If we configure multiple AuthenticationProvider, we should authenticate in configuration order, but authenticate from back to front now in AuthenticationListState#authenticateAsync and AuthenticationProviderList#authenticateAsync.
Fix authenticate order in AuthenticationProviderList
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Fix authenticate order in AuthenticationProviderList

pulsar-client-messagecrypto-bc/src/main/java/org/apache/pulsar/client/impl/crypto/MessageCryptoBc.java
Fixes #23121 
- Java Pulsar client uses `BouncyCastleProvider` for AES-GCM encryption, which is known to be slow due to the lack of hardware instruction optimization.
- See #23121 for the detailed benchmark result
- Modify `MessageCryptoBc` to use `SunJCE` provider which comes with hardware-instruction optimization instead of `BouncyCastle` provider.
This change is already covered by existing tests, such as `org.apache.pulsar.tests.integration.SimpleProducerConsumerTest`
PR in forked repository: [Pulsar CI workflow run result](https://github.com/ocadaruma/pulsar/actions/runs/10234721940)
=> [improve][misc] Improve AES-GCM cipher performance

pom.xml, pulsar-broker/pom.xml
In https://github.com/apache/pulsar/pull/22179 , `io.opentelemetry:opentelemetry-sdk-testing` was introduced to pulsar-broker. In https://github.com/apache/pulsar/pull/22467 , `OpenTelemetryAssertions` was used at `org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest`.
However, test cases that extend `org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest` is not only pulsar-broker, but also pulsar-proxy and pulsar-testclient. These are not running after https://github.com/apache/pulsar/pull/22467 is introduced.
Before modification:
```
% mvn test -pl pulsar-proxy -Dtest='org.apache.pulsar.proxy.server.ProxyServiceStarterTest'
...
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] …
```
=> [fix][test] Fixed many tests of pulsar-proxy are not running

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxNonInjectionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java
**Conditions under which problems occur**
- `Failover/Exclusive` subscription
- Sockets of Pulsar IO are not stable
- `ServerCnx` thread is busy.
| time | `registering consumer 1st` | `registering consumer 2nd` |
| 1 | Registered |
| 2 | Socket is unstable |
| 3 | Closing `ServerCnx` |
| 4 | | Retry to subscribe |
| 5 | | Check whether the previous consumer is still active<sup>[1]</sup>, if not,  override it by the current registering |
| 6 | `ServerCnx` is closed |
| 7 | | Call `serverCnx.checkConnectionLiveness`, the Completable Future returned will never be completed |
| 8 | | Client-side: call `ClientCnx.removeConsumer` after the subscribing is timeout |
| 9 | | There is a failed future in `ServerCnx.consumers` |
**[1]**: …
=> [fix][broker]A failed consumer/producer future in ServerCnx can never be removed

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarChannelInitializer.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarChannelInitializer.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/ByteBufPair.java
In Pulsar, there has been a long time workaround (#2464) for a Netty SslHandler issue where the input ByteBuf instances get mutated. After Netty 4.1.111.Final, it's no longer necessary to make buffer copies when TLS is enabled. This change on Netty side https://github.com/netty/netty/pull/14086 contains the fix.
Since the Pulsar client might get used with an older Netty version, it's necessary to detect that the Netty version contains the fix. The simplest way to detect Netty 4.1.111.Final is by checking for existence of the class `io.netty.handler.ssl.SslHandlerCoalescingBufferQueue` since that class was extracted from an inner class in 4.1.111.Final.
Instead of referencing `ByteBufPair.ENCODER` and `ByteBufPair.COPYING_ENCODER` directly, use `ByteBufPair.getEncoder(tlsEnabled)` to …
=> [improve][misc] Optimize TLS performance by omitting extra buffer copies

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ClusterMetadataSetupTest.java
(cherry-picked from commit https://github.com/apache/pulsar/commit/49d3beb4fae7efa60c48ec8dbf1d33f9c033c969)
Cherry-picked from https://github.com/apache/pulsar/pull/23087
=> [improve][broker][branch-3.0] Support to specify auth-plugin, auth-parameters and tls-enable arguments when init cluster metadata (#23087)

pip/pip-368.md
Currently, the lookup process uses only the topic name as its parameter. However, to enhance this process, it's
beneficial for clients to provide additional information. This could be done by introducing the `lookupProperties` field
in the client configuration. Clients can then share these properties with the broker during lookup.
On the broker side, the broker could also contain some properties that are used for the lookup. We can also support the
lookupProperties for the broker. The broker can use these properties to make a better decision on which broker to
return.
Here is the rack-aware lookup scenario for using the client properties for the lookup:
Assuming there are two brokers that broker-0 configures the lookup property "rack" with "A" and broker-1 configures the
lookup property …
=> [improve][pip] PIP-368: Support lookup based on the lookup properties

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BaseResource.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BookiesImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BrokerStatsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BrokersImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ClustersImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ComponentResource.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NonPersistentTopicsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PackagesImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ProxyStatsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ResourceGroupsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ResourceQuotasImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SchemasImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SinksImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SourcesImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TenantsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TransactionsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/WorkerImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java, pulsar-client-admin/src/test/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnectorTest.java, pulsar-client-admin/src/test/resources/log4j2.xml, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBase.java
Fixes #23127 
In Pulsar Admin client, the read timeout is used as the request timeout. A read timeout is supposed to handle the case where the client doesn't receive any data and the connection is idle for more than the read timeout value.
- Use the request timeout as the request timeout instead of using the read timeout as the request timeout
- Stop retries if the request timeout has occurred
=> [fix][client] Fix timeout handling in Pulsar Admin client

pom.xml, pulsar-io/rabbitmq/pom.xml, pulsar-io/rabbitmq/src/test/java/org/apache/pulsar/io/rabbitmq/RabbitMQBrokerManager.java, pulsar-io/rabbitmq/src/test/java/org/apache/pulsar/io/rabbitmq/sink/RabbitMQSinkTest.java, pulsar-io/rabbitmq/src/test/java/org/apache/pulsar/io/rabbitmq/source/RabbitMQSourceTest.java, pulsar-io/rabbitmq/src/test/resources/qpid.json
The build stalled because the Oracle maven repository in pom.xml. There seemed to be an temporary availability issue with the repository. The repository was added in PR #22391 to test scope since qpid requires com.sleepycat:je dependency. It's better to get rid of this repository.
Remove the Oracle maven repository from pom.xml and configure the test Qpid broker to use memory only mode so that the com.sleepycat:je dependency isn't required.
=> [fix][build] Remove unnecessary Oracle maven repository from pom.xml

docker/pulsar/scripts/gen-yml-from-env.py
Apache Pulsar Helm chart uses the gen-yml-from-env.py script to customize the function_worker.yml file so that environment variables are used to override values.
There's support missing for a few configuration keys.
- register `additionalJavaRuntimeArguments`, `additionalEnabledConnectorUrlPatterns` and `additionalEnabledFunctionsUrlPatterns` configuration keys as ones that take a list of values.
=> [improve][fn] Add support for overriding additionalJavaRuntimeArguments with PF_additionalJavaRuntimeArguments env

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/LeaderElectionImpl.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/LeaderElectionTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java
Fixes https://github.com/apache/pulsar/issues/23125
As reported in the issue, https://github.com/apache/pulsar/issues/23125, we have seen a case where the elected leader indefinitely thinks it's a follower. As a result, this issue can block load shedding(run by the leader) and cause broker load imbalance.
Additionally, I think the broker leadership should be checked more aggressively upon zk re-connection as well because znode deletion watch events could be missed while reconnected[1] 
> Watches are maintained locally at the ZooKeeper server to which the client is connected. This allows watches to be lightweight to set, maintain, and dispatch. When a client connects to a new server, the watch will be triggered for any session events. Watches will not be received while disconnected from a …
=> [fix][broker] Fix the bug that elected leader thinks it's a follower

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/PulsarAdminBuilder.java, pulsar-client-admin-shaded/pom.xml, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PackagesImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PulsarAdminImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SinksImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SourcesImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpRequestExecutor.java, pulsar-client-admin/src/test/java/org/apache/pulsar/client/admin/internal/PulsarAdminBuilderImplTest.java, pulsar-client-admin/src/test/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnectorTest.java, pulsar-client-all/pom.xml, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java, pulsar-client-shaded/pom.xml, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientBuilderImplTest.java, pulsar-common/pom.xml
Fixes #22041 
See #22041 . Currently, when using the asynchronous interfaces of the Pulsar Admin client, there's no backpressure by the client itself and the client will keep on opening new connections to the broker to fulfill the in-progress requests.
Eventually, the broker will hit the `maxHttpServerConnections` limit, which is 2048.
It's better to limit the number of connections from a single client. This PR sets the limit to 16 connections per host.
The limit isn't called `connectionsPerBroker` since admin operations usually target a cluster address.
- add `maxConnectionsPerHost` and `connectionMaxIdleSeconds` to PulsarAdminBuilder
- also modify the default `connectionMaxIdleSeconds` from 60 seconds to 25 seconds
- some firewalls/NATs have a timeout of 30 seconds and that's why 25 …
=> [improve][client] Add maxConnectionsPerHost and connectionMaxIdleSeconds to PulsarAdminBuilder

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
Upgrading to latest oxia client version: https://github.com/streamnative/oxia-java/releases/tag/v0.3.2 which fixes the shards sync issue.
- Upgrade the oxia version from 0.3.1 to 0.3.2
=> [fix][metadata] Upgrade Oxia to 0.3.2

pip/TEMPLATE.md
The PIP template's "backward and forward compatibility" section needs to contain geo-replication considerations so that it's handled as part of the PIP design.
- rename "Revert" -> "Downgrade / Rollback" to improve clarity
- reorder so that Upgrade is before "Downgrade / Rollback"
- add "Pulsar Geo-Replication Upgrade & Downgrade/Rollback Considerations"
=> [improve][doc] Add Pulsar Geo-Replication considerations to the PIP template

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/GetPartitionMetadataMultiBrokerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/GetPartitionMetadataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionLowWaterMarkTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ClientCnxTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BinaryProtoLookupService.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpLookupService.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/LookupService.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionCoordinatorClientImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImplTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/PulsarClientImplTest.java, pulsar-common/src/main/proto/PulsarApi.proto
After [PIP-344 add a public API pulsarClient.getPartitionsForTopic(String topic, boolean metadataAutoCreationEnabled)](https://github.com/apache/pulsar/pull/22182), there are `3` compatibility issues:
---
PIP-344 fixed a bug that the Retry/DLQ consumer will still trigger a Retry/DLQ topic with the old rule `{namespace}/{subscription}-RETRY/DLQ`, but the rule was changed to `{namespace}/{topic}-{subscription}-RETRY/DLQ` after `2.8.0`. This behavior has been defined in the PIP-344, so it is fine.
**Modifications for compatibility**: modify the error message to let users know what happened.
---
1. This error will only occur when using Geo-Replication, and one version of the two clusters is larger or equal to `3.0.6` and "3.3.1" and another is smaller than `3.0.6` and `3.3.1`.
2. **Reason why …
=> [fix] [broker] Fix compatibility issues for PIP-344

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
Internal topics ownership conflict is a concern here when the leadership changes frequently - we should make sure only the current leader owns these internal topics.
The persistent internal topic can self-resolve this topic ownership conflict by the ledger fencing logic.
However, I think the non-persistent internal topics can be a problem because the fencing logic doesn't apply to non-persistent topics.
To gracefully release the previous ownership of these internal topics, I think we better make followers explicitly close the internal topics - when leadership changes, there might be a chance that some clients reconnect to the old leader if the connected zk and the old leader's zk are slow. Then, when the old leader zk catches up(notifies a follower signal to the old leader), the old …
=> [improve][broker] Explicitly close LB internal topics when playing a follower (ExtensibleLoadManagerImpl only)

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/OxiaMetadataStore.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/OxiaMetadataStoreErrorTest.java
Once the Oxia's operation fails to execute, you will get many kinds of errors, such as `io.grpc.StatusRuntimeException`, which is not expected, we should convert these exceptions to `MetadataStoreException`
```
Aug 12, 2024 4:52:07 PM com.github.benmanes.caffeine.cache.LocalAsyncCache lambda$handleCompletion$7
WARNING: Exception thrown during asynchronous load
java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874)
at …
```
=> [fix] [meta] Oxia metadta store: Convert error to MetadataStoreException if operation failed

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/pendingack/impl/PendingAckHandleImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckPersistentTest.java
The Pending Ack handler can not recover after encountering a `MetadataStoreException` even the metadata store has been re-established.
```
2024-07-24T02:56:11,347+0000 [pulsar-transaction-executor-5-1] ERROR org.apache.pulsar.broker.transaction.pendingack.impl.PendingAckHandleImpl - [persistent://{tenant}/{ns}/{topic}] [multiTopicsReader-5c010a1ec8] PendingAckHandleImpl init fail!
org.apache.pulsar.metadata.api.MetadataStoreException: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /managed-ledgers/{tenant}/{namespace}/persistent/{topic}-multiTopicsReader-5c010a1ec8__transaction_pending_ack
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.108.Final.jar:4.1.108.Final]
at …
```
=> [fix] [broker] Let Pending ack handler can retry to init when encounters a metadata store error

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
The check for AvgShedder strategy is wrong, we should use `loadBalancerLoadPlacementStrategy` instead of `loadBalancerPlacementStrategy`.
The `loadBalancerPlacementStrategy ` is used by `SimpleLoadManagerImpl`, and it is deprecated.
Use `loadBalancerLoadPlacementStrategy` instead of `loadBalancerPlacementStrategy` to check the `AvgShedder `strategy
=> [fix][broker] Fix AvgShedder strategy check

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
When config `enableReplicatedSubscriptions=false` , the replicated subscriptions controller will never be started. But we will still see the log of the `Disabled replicated subscriptions controller`. In fact, we should not see the log because it has never been started.
Modify judgment conditions, only if replicatedSubscriptionsController has been started do we need to disabled it.
All unit tests passed, not have any behavior change.
=> [fix][broker] Fix 'Disabled replicated subscriptions controller' logic and logging

pulsar-broker/src/test/java/org/apache/pulsar/client/api/InterceptorsTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
When using MultiTopicConsumer with ConsumerInterceptor , the `beforeConsume` method was hit many times
before receiving the first message. The root cause of this is that before the MultiTopicsConsumer receives the message, MultiTopicsConsumer has already completed receiving the message from the internal consumer and executed the `beforeConsume` method, so we can let `beforeConsume` be called in MultiTopicsConsumer to avoid this issue.
https://github.com/apache/pulsar/blob/8707fbe8351fb6ac4337fbd88d86eb32aff55b04/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L228-L254
* Call `beforeConsume` method in MultiTopicsConsumer.
* Wrap ConsumerInterceptors for internal consumer the  and remove `beforeConsume` logic
*(Please pick either of the following …
=> [fix][client] Fix for early hit `beforeConsume` for MultiTopicConsumer

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
The consumer implementation is creating the retry producer synchronously, potentially unexpectedly blocking the calling thread.
This changes modifies this behaviour to fit with how the dead letter queue producer is created—i.e. using the async APIs offloaded to the internal pinned executor.
PR in forked repository: [](https://github.com/omarkj/pulsar)
=> [fix][client] Create the retry producer async

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
After a consumer calls `seek`, the operation `reconnect` will get a fenced error, which leads to more unnecessary reconnects. The steps to produce are as follows:
- `client-side`: consumer connected
- `client-side`: calls `consumer.seek` or `seekAsync`
- `broker-side`:
- mark subscription as `fenced`
- remove all consumer
- do reset the cursor internally
- `client-side`:
- consumer tries to reconnect
- get an error Subscription was fenced due to the task `reset cursor` not finished yet.
- loop...
- `broker-side`: `reset cursor` is completed
- `client-side`: The consumer tries to reconnect, and it will finish at this time.
- This PR fixes the issue that a consumer fenced itself.
- This PR can probably fix the issue that a `consumer.seek` fenced other consumers under the same subscription. …
=> [improve] [broker] Avoid subscription fenced error with consumer.seek whenever possible

pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonDurableSubscriptionTest.java
There are no no-related changes in PR #23129, see the details https://github.com/apache/pulsar/pull/23129/files#r1716538209, the current PR is in order to revert the changes
=> [fix] [test] Revert the modification to NonDurableSubscriptionTest caused by a mistake in the PR#23129

pip/pip-369.md
Discussion thread: #23094 
In Apache Pulsar 3.x, changing a namespace isolation policy results in unloading all namespace bundles that match the namespace's regular expression provided in the isolation policy.
This can be problematic for cases where the regex matches a large subset of namespaces, such as `tenant-x/.*`. 
One of such case is mentioned on this issue [#23092](https://github.com/apache/pulsar/issues/23092) where policy change resulted in 100+ namespace bundles to get unloaded.
And broker exhausted all the available connections due to too many unload calls happening at once resulting in 5xx response.
Other issues that happens with this approach are huge latency spikes as topics are unavailable until bundles are loaded back, increasing the pending produce calls.
The only benefit …
=> [improve][pip] PIP-369: Flag based selective unload on changing ns-isolation-policy 

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/EntryCacheDisabled.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/ReadEntryUtils.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheManagerTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadPrefixReadTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/ShadowTopicRealBkTest.java
For shadow topics, a `ReadOnlyLedgerHandle` is created to read messages from the source topic when the entry is not cached. However, it leverages the `readAsync` API that validates the `lastAddConfirmed` field (LAC). In `ReadOnlyLedgerHandle`, this field could never be updated, so `readAsync` could fail immediately. See `LedgerHandle#readAsync`:
```java
if (lastEntry > lastAddConfirmed) {
LOG.error("ReadAsync exception on ledgerId:{} firstEntry:{} lastEntry:{} lastAddConfirmed:{}",
ledgerId, firstEntry, lastEntry, lastAddConfirmed);
return FutureUtils.exception(new BKReadException());
}
```
This bug is not exposed because:
1. `PulsarMockReadHandle` does not maintain a LAC field.
2. The case for cache miss is never tested.
Replace `readAsync` with `readUnconfirmedAsync` and compare the …
=> [fix][broker] Fix shadow topics cannot be consumed when the entry is not cached

pip/pip-370.md
- [DIscussion](https://lists.apache.org/thread/9fx354cqcy3412w1nx8kwdf9h141omdg)
- [Vote](https://lists.apache.org/thread/vph22st5td1rdh1gd68gkrnp9doo6ct2)
=> [improve] [pip] PIP-370: configurable remote topic creation in geo-replication

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Fixes #23173
Fixes #23181
See #23173 and #23181
- copy ordering key to messages sent to retry letter topic and DLQ topic
=> [fix][client] Copy orderingKey to retry letter topic and DLQ messages and fix bug in copying

docker/pulsar/scripts/update-ini-from-env.py, docker/pulsar/scripts/update-rocksdb-conf-from-env.py
Fixes #23176
The way RocksDB is configured changed in Pulsar 2.11 / Bookkeeper 4.15 .
The settings are handled in `conf/entry_location_rocksdb.conf` file and `dbStorage_rocksDB_*` keys in bookkeeper.conf have no effect. This is mainly a problem for Kubernetes deployments since there's not an easy way to override the configs.
- add generics script `update-ini-from-env.py` for updating keys in RocksDB ini files by environment variables
- add compatibility script `update-rocksdb-conf-from-env.py` for updating `conf/entry_location_rocksdb.conf` file with `dbStorage_rocksDB_*` keys in the environment.
With these changes, it's possible to modify a Pulsar Helm chart's bookkeeper/autorecovery commands to include `&& (([ -x bin/update-rocksdb-conf-from-env.py ] && …
=> [feat] Add scripts for updating BK RocksDB ini files

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-common/src/main/java/org/apache/pulsar/common/util/FieldParser.java
* jackson-1.14.2 has the vulnerability.
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-7569538
*  `@JsonIgnore` in latest version of jackson works well.
https://github.com/apache/pulsar/pull/20182
https://github.com/FasterXML/jackson-databind/commit/4537f09d3419440554c7cf6f2d8130205fc6be6e
I run the following code:
<details>
<summary>JsonIgnore test code</summary>
```
class Foo {
private int a = 10;
@JsonIgnore
private transient int b = 11;
public int getA() {
return a;
}
public void setA(int a) {
this.a = a;
}
public int getB() {
return b;
}
public void setB(int b) {
this.b = b;
}
public static void main(String args[]) throws JsonProcessingException {
ObjectMapper ob = new ObjectMapper();
System.out.println(ob.writeValueAsString(new Foo()));
}
}
```
</details>
result: …
=> [fix][sec]Upgrade jackson to 2.17.2

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
The test SubscriptionSeekTest won't pass unless retries are enabled.
reproducing the issue:
```
mvn -DredirectTestOutputToFile=false -DtestRetryCount=0 test -pl pulsar-broker -Dtest=SubscriptionSeekTest
```
The test doesn't close consumers between test methods and that's why each method needs a unique topic.
- use unique topic name for testSeekIsByReceive method to prevent collisions 
- close producers and consumers between test methods
=> [fix][test] Fix flaky SubscriptionSeekTest.testSeekIsByReceive

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageCumulativeAckTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentDispatcherFailoverConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/NamespaceEventsSystemTopicServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/MockManagedLedger.java
There is still an `instanceof` operation on `ShadowManagedLedgerImpl` in the main code, so users cannot implement their own shadow managed ledger.
Replace the type check with the source topic check.
=> [improve][broker] Support customized shadow managed ledger implementation

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
The `ExtensibleLoadManagerImpl` behavior is not the same as the old LB, the old LB’s ownership will be empty when the broker starts.
When `ExtensibleLoadManagerImpl` starts, it may have some owners will be loaded into table view, and those ownerships will not trigger the bundle ownership listener, which may cause some issues, for example, the kop relies on the load event to load the offset topics.
Notify bundle ownership listener `onLoad` event when ServiceUnitState starts.
=> [improve][broker] Should notify bundle ownership listener onLoad event when ServiceUnitState start (ExtensibleLoadManagerImpl only)

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
When loading the system topic, skip the check of `checkMaxTopicsPerNamespace` at the first line, it can let the system topic `__change_event` start faster and avoid thread switching.
=> [improve] [broker] Optimize performance for checking max topics when the topic is a system topic

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/OrphanPersistentTopicTest.java
There are two scenarios that may leave a failed topic creation future in `brokerService.topics` because forgot to remove the failed future from the map, which leads to the topic never being loaded up successfully.
- Topic load and delete execute at the same time: see the test `testTopicLoadAndDeleteAtTheSameTime`
- Check ownership fails: see the test `testCheckOwnerShipFails `
Remove the failed future if load topic fails
=> [fix] [broker] Topic can never be loaded up due to broker maintains a failed topic creation future

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
We found the CPU of the broker busy with calling `ManagedLedgerImpl.internalReadFromLedger` and broker checked the `readPosition > maxPosition` and then triggered the `readMoreEntries` call again leading to the broker looping to call readMoreEntries. But in `ManagedCursorImpl.asyncReadEntriesWithSkipOrWait` we have checked no more data to read via hasMoreEntries(). I think this case may be caused by `maxReadPosition < lastConfirmedPosition` when the topic exists ongoing Txn. So I think `maxPosition <= readPosition` we should not read entries immediately, instead, we delay calling read entries.
If `maxPosition < readPosition` then delayed trigger readEntries.
Test Code:
```java
@Test
public void testSlowTxn() throws Exception {
String topic = NAMESPACE1 + "/testSlowTxn";
@Cleanup …
```
=> [improve][broker] Optimize high CPU usage when consuming from topics with ongoing txn

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/MessageDuplicationTest.java
---
Move the implementation to one place and avoid duplicated implementation
Fixes #xyz
PIP: #xyz 
*(or)*
*(or)*
*(example:)*
=> [cleanup] Cleanup some duplicated code

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProduceWithMessageIdTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/OpSendMsgStats.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/OpSendMsgStatsImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/SendCallback.java
PIP: #22940 
- Add `OpSendMsgStats` parameters to the `org.apache.pulsar.client.impl.SendCallback.sendComplete`
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/crossoverJie/pulsar/pull/29
=> [improve][broker] Add callback parameters to the SendCallback.sendComplete

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar_topic_load_failed metric may not record the correct failed time if topic load failed before execute BrokerService#createPersistentTopic
move to BrokerService#loadOrCreatePersistentTopic
=> [improve][broker] Improve pulsar_topic_load_failed metric to record correct failed time

pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/reader/MultiVersionAvroReader.java
Currently when a client loads schema from brokers, it will print the whole schema as info logs. The broker's built-in client has the same issue so schemas will be printed in broker logs, which could be very long (hundreds of lines) and might expose user info.
Reduce the log level to debug in `MultiVersionAvroReader`.
=> [improve][client] Don't print info logs for each schema loaded by client

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerMLInitializeDelayTest.java
Fixes #23208
Main Issue: #23208
- https://github.com/apache/pulsar/issues/23208
When `publishing` and `ledger switching` execute concurrently, the broker will print a warn-level log `An OpAddEntry's ledger is empty.`, but it should not be a `warn` level. The test `testConcurrentlyOfPublishAndSwitchLedger` can reproduce the warning log printing.
=> [fix] [log] Do not print warn log when concurrently publishing and switching ledgers

pip/pip-370.md, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedReplicationStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStatsTest.java
see also [PIP-370: configurable remote topic creation in geo-replication ](https://github.com/apache/pulsar/pull/23124)
- Add [metrics defined in the PIP](https://github.com/apache/pulsar/blob/master/pip/pip-370.md#metrics)
=> [improve] [broker] Part 2 of PIP-370: add metrics "pulsar_replication_disconnected_count"

pulsar-common/src/main/java/org/apache/pulsar/common/util/SimpleTextOutputStream.java
On a specific environment /metrics end point timed out consistently, logs contained the exception below.
Applied fix has resolved the issue. 
The fix does not make much sense as String implements CharSequence, so I suspect we hit some weird issue with JIT or jvm.
The JDK is Timurin build 17.0.12+7, I could not repro this locally but it consistently happened in the env.
```
2024-08-23T20:40:42,618+0000 [pulsar-stats-updater-OrderedScheduler-0-0] WARN  org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService - Unexpected throwable from task class com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask: 'org.apache.pulsar.common.util.SimpleTextOutputStream org.apache.pulsar.common.util.SimpleTextOutputStream.write(java. …
```
=> [fix] StatsOutputStream: add string write function (#308)

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLookupData.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/LookupOptions.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/data/BrokerLookupDataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerFilterTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/filter/BrokerIsolationPoliciesFilterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/manager/RedirectManagerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/LookupPropertiesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BinaryProtoLookupService.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/BinaryProtoLookupServiceTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java, pulsar-common/src/main/proto/PulsarApi.proto
PIP: https://github.com/apache/pulsar/pull/23075
This is the implementation for the PIP: https://github.com/apache/pulsar/pull/23075
Currently, the lookup process uses only the topic name as its parameter. However, to enhance this process, it's
beneficial for clients to provide additional information. This could be done by introducing the `lookupProperties` field
in the client configuration. Clients can then share these properties with the broker during lookup.
On the broker side, the broker could also contain some properties that are used for the lookup. We can also support the
lookupProperties for the broker. The broker can use these properties to make a better decision on which broker to
return.
Here is the rack-aware lookup scenario for using the client properties for the lookup: …
=> [feat][broker] PIP-368: Support lookup based on the lookup properties

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/BundleRangeCache.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/AntiAffinityNamespaceGroupTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerSharedTest.java
A concurrent hash map (no matter the `ConcurrentOpenHashMap` in Pulsar or the official `ConcurrentHashMap`) is not a synchronized hash map.
For example, given a `ConcurrentHashMap<Integer, Integer>` object `m`,
```java
synchronized (m) {
m.computeIfAbsent(1, __ -> 100); // [1]
m.computeIfAbsent(2, __ -> 200); // [2]
}
```
```java
m.computeIfAbsent(1, __ -> 300); // [3]
```
If these two code blocks are called in two threads, `[1]->[3]->[2]` is a possible case.
`SimpleLoadManagerImpl` and `ModularLoadManagerImpl` both maintain the bundle range cache:
```java
// The 1st key is broker, the 2nd key is namespace
private final ConcurrentOpenHashMap<String, ConcurrentOpenHashMap<String, ConcurrentOpenHashSet<String>>>
brokerToNamespaceToBundleRange;
```
However, when accessing the `namespace -> …
=> [fix][broker] Fix thread unsafe access on the bundle range cache for load manager

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageRedeliveryController.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedSubscriptionStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionStats.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java
Main Issue: #23205
Currently there aren't ways to observe the number of messages that are "in replay" with Key_Shared or Shared subscriptions. Having these metrics would make it easier to understand the behavior of issues such as #23200 .
Please check #23205 for more reasons.
- add `msgInReplay` in the similar way as the existing `msgDelayed` subscription stat and metric.
=> [improve][broker] Add msgInReplay subscription stat and metric to improve Key_Shared observability

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTestBase.java
Main Issue: #23200 
There's currently a clear problem with Key_Shared that in normal operations, it causes a lot of "ack holes" which result in several problems. One of the problems is the latency issues that are explained in #23200. Another problem is that the large number of "ack holes" exceed managedLedgerMaxUnackedRangesToPersist (10000) in usual cases such as in the demonstration in #23200. 
There are multiple other issues where there has been a large number of "ack holes" when Pulsar users have experienced problems. One of the previous mitigations is [PIP-299: Stop dispatch messages if the individual acks will be lost in the persistent storage.](https://github.com/apache/pulsar/blob/master/pip/pip-299.md). The need for PIP-299 proves that the large number of "ack holes" is a fairly …
=> [improve][broker] Reschedule reads with increasing backoff when no messages are dispatched

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
Fixes #23233
It fixes this issue: https://github.com/apache/pulsar/issues/23233
Currently `peek-message` CLI/API returns encrypted or compressed message , and user can use this CLI/API to retrieve message and metadata information for any kind of debugging. For example, if encrypted messages is failing to decrypt in consumer application and if user wants to know the encryption keys name then peek-message will help to retrieve such information.
But peek-message api/cli fails if message is encrypted and compressed , and failed with below error because broker is trying to decompress invalid message payload as client first compress and encrypt the message, and broker tried to uncompress already encrypted message.
```
Reason: 
Message: offset …
```
=> [fix][broker] support peek-message for compressed and encrypted messages

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/AllocatorStatsGenerator.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/stats/AllocatorStats.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
Expose `usedDirectMemory` and `usedHeapMemory` to track the heap/direct memory usage of ByteBufAllocator.
*(or)*
*(or)*
*(example:)*
=> [improve][admin] Improve BrokerStats.allocatorStats

pulsar-broker/src/test/java/org/apache/pulsar/client/api/UnloadSubscriptionTest.java
Fixes https://github.com/apache/pulsar/issues/19508#issuecomment-1733497179
This problem still exists. The root cause is that `BatchIndexAcknowledgment` is not enabled.
enable batch index acknowledgment
=> [fix][test] Fix flaky UnloadSubscriptionTest.testMultiConsumer

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
When the service unit state channel fails to start, it will throw an exception, and after the PR https://github.com/apache/pulsar/pull/22977 , it will fail forever, because the pulsar broker cannot catch the exception, and it won't have any retry mechanism
Add retry for start service unit state channel
=> [improve][broker] Add retry for start service unit state channel (ExtensibleLoadManagerImpl only)

build/run_unit_group.sh, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ShadowReplicator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/ShadowReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/ShadowTopicRealBkTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java
Currently, the ShadowReplicator syncs all message payloads from the source topic to the shadow topic (ShadowManagedLedger). This significantly increases traffic between brokers. However, the ShadowManagedLedger only requires the position information from these messages. It can retrieve the payload directly from the Bookkeeper. Therefore, the ShadowReplicator does not need to sync the message payloads between brokers.
- Prevent ShadowReplicator from syncing message payloads
*(or)*
*(or)*
*(example:)* …
=> [improve][broker] Optimize message payload traffic for ShadowReplicator

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Netty release 4.1.113.Final contains some bug fixes that are relevant for Pulsar.
It's also worth keeping Netty updated since besides bug fixes, we will also catch possible regressions closer to releases when a change in Netty causes a regression.
* [Netty 4.1.113 release notes](https://netty.io/news/2024/09/04/4-1-113-Final.html)
* [Netty 4.1.112 release notes](https://netty.io/news/2024/07/19/4-1-112-Final.html)
- upgrade Netty to 4.1.113.Final
- upgrades netty-tcnative to 2.0.66.Final
=> [improve][misc] Upgrade Netty to 4.1.113 and netty-tcnative to 2.0.66

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
Currently broker is logging principal-name and producer/consumer creation log into separate line which makes harder to to find out role-name that created producer/consumer which requires for troubleshooting and role-access analysis. Therefore, adding principal name into the same producer/consumer creation log line.
add additional principal name parameter into the log line.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after …
=> [fix][broker] Add principal name into info log to enhance analysis and troubleshooting

pulsar-broker/src/test/java/org/apache/pulsar/client/api/LookupPropertiesTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BinaryProtoLookupService.java
When the lookup properties are modified, the previous pending lookup might use the modified properties for lookup.
- Combine the properties and the topic name as the key to cache pending lookup requests.
- Return copied properties rather than the reference in `ClientConfigurationData#getProperties`
- Add `testConcurrentLookupProperties` to cover this case.
=> [fix][client] Fix concurrent lookup with properties might have different results

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
CompletableFuture has an intuitive behavior
```java
final var future = new CompletableFuture<Integer>();
future.thenRun(() -> System.out.println("A"));
future.thenRun(() -> System.out.println("B"));
future.thenRun(() -> System.out.println("C"));
future.complete(0);
```
The outputs of the code above are:
```
C
B
A
```
That's because it maintains callbacks in the LIFO stack, not FIFO queue.
https://github.com/apache/pulsar/pull/22977 breaks the order of some events during extensible load manager's start by adding the runnable objects via `thenRun()`. The previous events order of `ExtensibleLoadManagerImpl`:
1. `playLeader()` or `playFollower()`
2. `serviceUnitStateChannel.start()`
3. Schedule some tasks (`brokerLoadDataReportTask`, `topBundlesLoadDataReportTask`, etc.) and set `started` …
=> [fix][broker] Execute the pending callbacks in order before ready for incoming requests

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java, pulsar-broker/src/main/java/org/apache/pulsar/PulsarInitialNamespaceSetup.java, pulsar-broker/src/main/java/org/apache/pulsar/PulsarTransactionCoordinatorMetadataSetup.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ClusterMetadataSetupTest.java, pulsar-broker/src/test/resources/conf/zk_client_enable_sasl.conf
The pulsar configuration supported `metadataStoreConfigPath` and `configurationStoreConfigPath`, but the cluster metadata init command does not have a place to set the config path.
Make cluster metadata init command support metadata config path
=> [improve][broker] Make cluster metadata init command support metadata config path

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
`pulsar-admin topics stats-internal` caused a BK client thread deadlock, leading to other ledgers not being opened successfully, and topics not being loaded up.
A race condition that will trigger the issue
- Calling `topics stats-internal`
- Compaction is running at the last step(opening a new ledger to write)
- Remove sync call
=> [fix][broker] fix pulsar-admin topics stats-internal caused a BK client thread a deadlock

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
Bump io.grpc from 1.56.0 to 1.56.1 to address this important fix. https://github.com/grpc/grpc-java/pull/10328
- Bump io.grpc from 1.56.0 to 1.56.1
=> [fix] Bump io.grpc from 1.56.0 to 1.56.1

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
Bump oxia java version from 0.3.2 to 0.4.5
-  Bump oxia java version from 0.3.2 to 0.4.5
The tests will be run in the forked repository until all PR review comments have
been handled, the tests pass and the PR is approved by a reviewer.
-->
=> [feat][meta] Bump oxia java version from 0.3.2 to 0.4.5

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
The log message in `AdminResource` was missing a parameter. The `topicName` was not being included in the success log message when creating partitioned topics for remote clusters.
This results the following errors:
```
ERROR Unable to format msg: [{}] Successfully created partitioned for topic {} for the remote clusters java.lang.IllegalArgumentException: found 2 argument placeholders, but provided 1 for pattern `[{}] Successfully created partitioned for topic {} for the remote clusters`
```
This issue was introduced by https://github.com/apache/pulsar/pull/23169, so we also need to cherry-pick this PR to the branch-3.0
Corrected the log message by adding the missing `topicName` parameter to the success log entry in the `internalCreatePartitionedTopicToReplicatedClustersInBackground` …
=> [fix][broker] fix the log format error in the AdminResource

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java
#23226 introduced a regression since the test coverage was missing for PersistentDispatcherMultipleConsumers.
It causes a performance regression since a backoff is introduced for all calls.
- fix the issue of setting lastNumberOfEntriesDispatched
- modify the existing test backoff test so that it's also used for PersistentDispatcherMultipleConsumers
=> [fix][broker] Fix retry backoff for PersistentDispatcherMultipleConsumers

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloader.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/NonAppendableLedgerOffloader.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/NullLedgerOffloader.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ReadonlyWrapperLedgerOffloader.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadPrefixReadTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadPrefixTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/test/MockedBookKeeperTestCase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiOffloadTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
After https://github.com/apache/pulsar/pull/22497, the broker will not offload data or read data from offloaded for the system topic, the PR has not considered compatibility for the cluster that already offloaded data, which leads to the system topics can not be loaded up if they contain data offloaded.
```
2024-09-09T13:02:53,677+0000 [broker-client-shared-internal-executor-6-1] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://{tenant}/{ns}/__change_events] Compaction failure.
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException: The subscription __compaction of the topic persistent://{tenant}/{ns}/__change_events gets the last message id was failed
{"errorMsg":"Failed to recover Transaction …
```
=> [fix] [broker] Fix system topic can not be loaded up if it contains data offloaded

pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/json/PulsarJsonFieldDecoder.java, pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/decoder/json/TestJsonDecoder.java
If using JSON schema and UUID type, will receive error when use trino.
```
java.lang.IllegalStateException: Expected entry size to be exactly 16 but was 36
at io.trino.spi.type.UuidType.writeSlice(UuidType.java:143)
at io.trino.spi.connector.RecordPageSource.getNextPage(RecordPageSource.java:113)
at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
at io.trino.operator.Driver.processInternal(Driver.java:388)
at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
at io.trino.operator.Driver.tryWithLock(Driver.java:685)
at io.trino.operator.Driver.processFor(Driver.java:285)
at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java: …
```
=> [fix][sql][branch-3.0] Fix UUID convert failed for JSON schema

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/PulsarServerException.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/LoadManagerFailFastTest.java
https://github.com/apache/pulsar/pull/23230 tries to fix the issue that "the pulsar broker cannot catch the exception" caused by https://github.com/apache/pulsar/pull/22977. However, the fix is incorrect because even before https://github.com/apache/pulsar/pull/22977, the broker also wouldn't fail if the extensible load manager failed to start.
It's destructive to have broker running with a failed load manager. Since `BrokerRegistry#unregister` will be called for failures, the issue broker will unregister itself from the metadata store and it could not be selected as the owner broker. Besides, all lookup requests sent to this broker will fail because the load manager is not started.
- Revert https://github.com/apache/pulsar/pull/23230
- Implement `failStarting` correctly:
- If it has …
=> [fix][broker] Fail fast if the extensible load manager failed to start

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryTest.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataCache.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/cache/impl/MetadataCacheImpl.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java
It's observed in our test environment many times after restarting the only broker with the extensible load manager's broker registry service.
```
2024-09-12T14:00:20,557+0000 [main] ERROR org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImpl - Failed to start the extensible load balance and close broker registry org.apache.pulsar.broker.loadbalance.extensions.BrokerRegistryImpl@6d6c4775.
org.apache.pulsar.broker.PulsarServerException: org.apache.pulsar.metadata.api.MetadataStoreException$LockBusyException: Resource at /loadbalance/brokers/<broker-id>:8080 is already locked
at org.apache.pulsar.broker.loadbalance.extensions.BrokerRegistryImpl.start(BrokerRegistryImpl.java:112) ~
at org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImpl.start(Extensible …
```
=> [improve][broker] Register the broker to metadata store without version id compare

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/PulsarServerException.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/LoadManagerFailFastTest.java
cherry picked from commit fc60ec06ae98fa4000473a636bfb06729c210048
backporting PR #23297 to branch-3.0
There are some test failures and problems that show up when running LoadManagerFailFastTest
Could someone take over this PR who understands the problems?
in LoadManagerFailFastTest.testServiceUnitStateChannelFailure, there's an continue loop of "Failed to get the channel owner" exceptions:
```
2024-09-13T07:23:58,402 - WARN  - [pulsar-load-manager-67-1:ExtensibleLoadManagerImpl] - The broker:localhost:56523 failed to set the role. Retrying 10 th ...
java.lang.RuntimeException: Failed to get the channel owner.
at org.apache.pulsar.broker.loadbalance.extensions.channel.ServiceUnitStateChannelImpl.isChannelOwner(ServiceUnitStateChannelImpl.java:467) ~[classes/:?]
at …
```
=> [fix][broker][branch-3.0] Fail fast if the extensible load manager failed to start (#23297)

pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/AbstractTwoPhaseCompactor.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/EventTimeOrderCompactor.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/PublishingOrderCompactor.java
There are many redundant parses of MessageMetadata in topic compaction, including phase one and phase two
reuse the MessageMetadata object  in topic compaction
PR in forked repository:  https://github.com/aloyszhang/pulsar/pull/23
=> [improve][broker] Reducing the parse of MessageMetadata in compaction

pip/pip-374.md, pulsar-broker/src/test/java/org/apache/pulsar/client/api/InterceptorsTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerInterceptor.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerInterceptors.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
#23235 
- Add `onArrival` method to ConsumerInterceptor.
- Call `onArrival` method when message received and successful deserialize.
- Add `testConsumerInterceptorForOnArrive` to cover it.
=> [feat][client] PIP-374: Visibility of messages in receiverQueue for the consumers

pip/pip-378.md
This is a PIP. Please check the doc.
=> [improve][pip] PIP-378 Add ServiceUnitStateTableView abstraction (ExtensibleLoadMangerImpl only)

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaceIsolationPolicy.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/NamespaceIsolationDataImpl.java
This PR is a followup to #23120 to make the backward incompatible change to:
* Make the default value of `unload-scope` to `changed`
* Change behavior of all_matching to cover both removed and added regexes
PIP: #23116 
This change is only meant for pulsar 4.x release
- Added test case to validate behavior of `all_matching` flag
- Added test case to verify default changed to `changed`
PR in forked repository: https://github.com/grssam/pulsar/pull/3
=> [improve][admin] PIP-369 Change default value of `unload-scope` in `ns-isolation-policy set`

.github/workflows/pulsar-ci.yaml, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/DebeziumMsSqlContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/debezium/DebeziumMsSqlSourceTester.java
Pulsar CI is currently broken. The "CI - System - Pulsar IO" build job fails due to this error:
```
Error:  org.apache.pulsar.tests.integration.io.sources.debezium.PulsarDebeziumSourcesTest.testDebeziumMsSqlSource
[INFO]   Run 1: PASS
Error:    Run 2: PulsarDebeziumSourcesTest.testDebeziumMsSqlSource:79->testDebeziumMsSqlConnect:236 » ContainerLaunch Container startup failed for image mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04
-----
!!!!!!!!! FAILURE-- [TestClass name=class org.apache.pulsar.tests.integration.io.sources.debezium.PulsarDebeziumSourcesTest].testDebeziumMsSqlSource([])-------
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image mcr.microsoft.com/mssql/server:2019-CU12-ubuntu-20.04
at …
```
=> [fix][io] Upgrade mssql server docker tag in DebeziumMsSqlContainer

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java
Fixes #23271
The "recently joined consumers" rules should only be applied for Key_Shared in AUTO_SPLIT mode without allowOutOfOrderDelivery. It's unnecessary for the Key_Shared STICKY mode.
Ensure that "recently joined consumers" rules are only applied Key_Shared in AUTO_SPLIT mode without allowOutOfOrderDelivery.
=> [improve][broker] Don't use "recently joined consumers" rules for Key_Shared in STICKY mode

pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java, pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java
Fixes [23273](https://github.com/apache/pulsar/issues/23273)
This PR addresses an issue where the Pulsar broker fails to restart due to incomplete NAR file extraction. The broker attempts to reuse an incomplete directory in the `/tmp` folder, leading to a `NoSuchFileException`. This occurs when the broker is stopped during the extraction process, causing the NAR files to remain in an inconsistent state, which affects future restarts.
* extract to a temporary directory which is renamed to the target directory in the last step. This ensures the consistency of the extracted files.
* Adding new tests that simulate an incomplete NAR extraction, followed by a broker restart to ensure it handles incomplete extractions. …
=> [fix][broker] Fix incomplete NAR file extraction which prevents broker from starting

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataCache.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BaseMetadataStoreTest.java
Fixes #21535 
The test should Provide Consistent Answer .Test revalidateLeaderWithinSameSession failed too many times. 
We are calling the method once store the object and check both the conditions . In this way at both conditions we are checking the same Object.
=> [fix][test] Fix flaky test LeaderElectionTest.revalidateLeaderWithinSameSession

docker/pom.xml
building a docker image with this command will fail. 
```
mvn package -Pdocker,-main -am -pl docker/pulsar -DskipTests
```
error message is
```
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.45.0:build (default) on project pulsar-docker-image: Execution default of goal io.fabric8:docker-maven-plugin:0.45.0:build failed: Given Docker name 'apachepulsar/pulsar:4.0.0-SNAPSHOT-${git.commit.id.abbrev}' is invalid:
[ERROR]    * tag part '4.0.0-SNAPSHOT-${git.commit.id.abbrev}' doesn't match allowed pattern '^[\w][\w.-]{0,127}$'
[ERROR] See http://bit.ly/docker_image_fmt for more details
```
Fix the problem by revisiting the `git-commit-id-plugin` configuration in `docker/pom.xml` file.
Removing `<runOnlyOnce>true</runOnlyOnce>` fixes the problem.
=> [fix][build] Fix problem where git.commit.id.abbrev is missing in image tagging

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
Address CVE-2024-8391
Upgrade vertx from 4.5.8 to 4.5.10
=> [fix][sec] Upgrade vertx to 4.5.10 to address CVE-2024-8391

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
Without #23226 and #23284, the consumption latency is low, but the consumption latency increases to `1s` when the traffic is low.
Consumption latency after an upgrade(3 topics).
`histogram_quantile(0.98, sum-by (le, topic) (rate (Message_duration_eventstate_ inbound_latencymin_bucket {kubernetes_namespace-"$(env)"} [$__rate_interval])))`
Root cause
Change the feature's introduced by #23226 default values to 1ms initial / 10ms max.
=> [fix] Key_Shared mode consumption latency when low traffic

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java
PR #23226 introduced a change to introduce a delay before calling `readMoreEntries` in PersistentDispatcherMultipleConsumers classes when no messages were dispatched.
This logic didn't take into account the case when all messages are delayed messages, marker messages or messages from an aborted transaction. In those cases additional delays would be introduced, causing performance regressions.
- add a failing test case that simulates dispatching a delayed message that gets filtered
- no delay should be introduced before the next call to readMoreEntries
- Fix the regression by tracking how many entries were "processed" by consumers in the last round instead of tracking how many entries were dispatched.
-  `lastNumberOfEntriesProcessed` tracks how many entries were processed by consumers in …
=> [fix][broker] Avoid introducing delay when there are delayed messages or marker messages

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
When `schemavalidaitonenforced` is enabled on topic and producer without schema is created on topic then `IncompatibleSchemaException` is thrown.
When producer without schema is created then by default bytes schema is added to producer.
In error message topic-schema and `schemavalidationenforced=enabled` is not specified.
After specifying `schemavalidaitonenforced=enabled` producer will be created with same schema.
Modified the error message with specifying that `schemaValidaitonEnforced` is enabled.
[PR](https://github.com/nikam14/pulsar/pull/5 ) in forked repository:
=> [improve][schema] Improve Incompatible Schema Exception error message in ServerCnx.java

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdConsume.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdRead.java
Currently user wants to consume encrypted message using pulsar-client CLI for any kind of troubleshooting and validation but CLI tool doesn't support option to consume encrypted message by ignoring decryption failure. Therefore, client-cli should have configuration to define crypto-failure-action for consumer so, client can use it for their consumption usecase.
add param `--crypto-failure-action` to client-cli to support encrypted message consumption.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment …
=> [fix][cli] Fix Pulsar-Client to allow consume encrypted messages with appropriate crypto-failure-action

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/AbstractCmdConsume.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdConsume.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdRead.java
Currently, client-cli doesn't print encryption related metadata which requires in my cases by users to troubleshoot encryption/decryption related issues and validate key related metadata.
Add `--print-metadata` param in client-cli for consumer to allow to print additional metadata of the message.
*(or)*
*(or)*
*(example:)*
PR in …
=> [fix][cli] Fix Pulsar-Client CLI to print metadata of message including encryption metadata

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/GetPartitionMetadataTest.java
If users trying to use a tenant that does not exist, the broker should not print an `error-level` log.
=> [fix] [log] Do not print error log if tenant/namespace does not exist when calling get topic metadata

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryIntegrationTest.java
Disable flaky test BrokerRegistryIntegrationTest (#23365) until it's fixed.
It's currently blocking Pulsar CI.
=> [fix][build] Disable flaky test BrokerRegistryIntegrationTest

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerErrorsTest.java
When open managed ledger fails, the `entryCacheManager`'s ml cache will be a closed managed ledger, then if we open this ledger again, it will fail to read because `org.apache.bookkeeper.mledger.ManagedLedgerException: LastConfirmedEntry is null when reading ledger xxx` exception.
* Remove the `entryCacheManager`'s cache if open ml fails.
* Add unit test to cover this case.
=> [fix][ml] Managed ledger should recover after open ledger failed

pulsar-common/src/main/java/org/apache/pulsar/common/util/SecurityUtility.java
- `pulsar-admin` output parsing breaks in 4.0.0-preview.1 testing because of the warnings
[Example from Pulsar Helm chart testing](https://github.com/apache/pulsar-helm-chart/actions/runs/11076453216/job/30779614305?pr=530#step:6:5223)
```
Creating subscription for output topic
2024-09-27T19:25:20,336+0000 [main] WARN  org.apache.pulsar.common.util.SecurityUtility - Conscrypt isn't available for Linux amd64. Using JDK default security provider.
Waiting for function to be ready
parse error: Invalid numeric literal at line 1, column 14
```
- switch logging level from warn to debug
- previous change in this area:  #20371
=> [fix][misc] Log Conscrypt security provider initialization warnings at debug level

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorRateLimiterTest.java
The `ReplicatorRateLimiterTest` will always fail with `StackOverflowError `, because in https://github.com/apache/pulsar/pull/23322 the `getRateLimiter` always recursive call to itself.
```
ReplicatorRateLimiterTest.testReplicatorRateLimiterMessageNotReceivedAllMessages
java.lang.StackOverflowError
at org.apache.pulsar.broker.service.ReplicatorRateLimiterTest.getRateLimiter(ReplicatorRateLimiterTest.java:614)
```
=> [fix][test] Fix ReplicatorRateLimiterTest

conf/pulsar_tools_env.sh
`-client` and `-server` JVM args have been deprecated in Java for a very long time. Pulsar CLI tools currently add `-client` argument. This causes some OpenJDK distributions to fail:
```
❯ docker run --rm -it bellsoft/liberica-runtime-container:jdk-17-cds-stream-glibc java -client
Unrecognized option: -client
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
- remove the unnecessary `-client` argument.
=> [fix][cli] Remove deprecated "-client" JVM arg

docker/pulsar/Dockerfile
Apache Pulsar Helm chart requires openssl in the docker image.
Install the `openssl` package.
=> [improve] Install openssl in the docker image to fix compatibility with Apache Pulsar Helm chart

.github/workflows/pulsar-ci.yaml, bin/function-localrunner, conf/bkenv.sh, conf/pulsar_env.sh, docker/pulsar/Dockerfile, docker/pulsar/pom.xml, pom.xml
Java 21 has been switched in the Docker image in 3.3.0 with "PIP-324: Alpine image (#22054)":
https://github.com/apache/pulsar/blob/branch-3.3/docker/pulsar/Dockerfile#L61
Pulsar CI should also run on Java 21 by default.
- Use Java 21 by default in CI
- Run a scheduled build on Java 17 with docker image using Java 17
- Add `-XX:+ZGenerational` to `PULSAR_GC` parameters by default when running on Java 21+
- Cleanup remaining Ubuntu related properties from the Maven build.
=> [improve][ci] Switch to Java 21 as default JVM version for CI

pom.xml
Pulsar Python client is embedded in the docker image.
The current version used in the image is 3.4.0 . The newest stable version is 3.5.0 .
Upgrade the Pulsar Python client to 3.5.0 version
=> [improve] Upgrade Pulsar Python client in docker image to 3.5.0

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java
This PR(https://github.com/apache/pulsar/pull/23301) introduces the ServiceUnitStateMetadataStoreTableView, which persists ownership information in metadata store. When this is used, we don't need to configure system topic in the monitor thread. Currently, the monitor thread unnecessarily tries to configure the system topic and prints red-herring error logs `Failed to set compaction threshold for system topic:persistent://pulsar/system/loadbalancer-service-unit-state`
- check if the system topic is used before calling the configureSystemTopics
=> [improve][broker] check system topic is used before configuring system topic (ExtensibleLoadManagerImpl only)

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/EntryAndMetadata.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java, pulsar-common/src/test/java/org/apache/pulsar/common/compression/CommandsTest.java, pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceProducerTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/messaging/MessagingBase.java
Fixes #23212
Taken from issue:
The Key_Shared implementation expects that the incoming message contain either a key/keyBytes or orderingKey.
If the key isn't set, the implementation will use the bytes of the NONE_KEY string as the key. This could be a surprise to users since the implications of not setting the key is not documented.
The problem that this causes is that all messages without a key will handled by a single consumer. If any of these messages is in redelivery, it will cause all message delivery to be blocked.
- Updated all parts where NONE_KEY was used as a default: Prefer 1) ordering key, 2) partition key, 3) new fallback key derived from producer name and sequence number, 4) NONE_KEY
- Updated KeySharedSubscriptionTest …
=> [feat] Use producer name and sequence number as fallback key in Key_Shared implementation

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/RangeSetWrapper.java, managed-ledger/src/main/proto/MLDataFormats.proto, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerBkTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryIntegrationTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenLongPairRangeSet.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/LongPairRangeSet.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/OpenLongPairRangeSet.java
Right now, managed-cursor serializes individually deleted-message ranges and persist them in bookie ledger-entry for the recovery. managed-cursor can persist max 150K ranges due to limited bookie entry size (5MB). 150K ranges might not be enough for some of the use cases while recovering cursor. so, we need a mechanism to persist a couple of million ranges to support such usecases.
with #3818 and #3819 managed-cursor manages individually deleted messages in bitset with OpenRangeSet. Serializing OpenRangeSet can allow managed-cursor to store 10M ranges with 5MB data size. 
Usecases require a large number of individually deleted-messages that can be supported with this change.
=> [fix][broker] Support large number of unack message store for cursor recovery

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
There's an inconsistency in the org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers#cancelPendingRead method:
https://github.com/apache/pulsar/blob/e0b754dd3938a2d142623001dbb15c92cc2f5cb4/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java#L651-L656
In addition to `havePendingRead`, there's a separate field `havePendingReplayRead` that tracks a pending read too. It should be taken into account in `cancelPendingRead` method.
- handle `havePendingReplayRead` in `cancelPendingRead` method.
=> [fix][broker] Cancel possible pending replay read in cancelPendingRead

pip/pip-381-large-positioninfo.md
Proposed implementation: https://github.com/apache/pulsar/pull/22799
=> [improve][pip] PIP-381: Handle large PositionInfo state

pip/README.md
As discussed in this [email thread](https://lists.apache.org/thread/5lv8pwdgtxcobkjfgto274xxvrr3b1q7) , updating PIP process with the improvement.
Also a recent example [PIP-381](https://lists.apache.org/thread/qzbhnnqxxbmmr2bhdh10vn3pn7l5yy0w) shows that this change helped the community to move faster with productive discussion and efficient voting process (VOTE approved with 2 binding vote and in less than a week). and that will help the community to get the new feature out without any unnecessary delay.
*(or)*
*(or)* …
=> [improve][pip] Improve PIP process and voting timeline

docker/pulsar/Dockerfile
When `ROCKSDB_MUSL_LIBC=true` is set in environment, it simplifies the logic on RocksDB side for initializing the library: https://github.com/facebook/rocksdb/blob/444b3f4845dd01b0d127c4b420fdd3b50ad56682/java/src/main/java/org/rocksdb/util/Environment.java#L73-L91
The problem with the RocksDB logic is that it executes a shell command to detect that it's running in a musl environment.
This could be a problem when shell commands are restricted due to security reasons.
```java
// check if ldd indicates a muslc lib
try {
final Process p =
new ProcessBuilder("/usr/bin/env", "sh", "-c", "ldd /usr/bin/env | grep -q musl").start();
if (p.waitFor() == 0) {
return true;
}
} catch (final IOException | InterruptedException e) {
// do nothing, and move on to the next check
}
```
- pass …
=> [improve] Configure Rocksdb to use musl libc flavor of the native library

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsumerIdentityWrapper.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsumerNameIndexTracker.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelectorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsumerIdentityWrapperTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsumerNameIndexTrackerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Range.java
Fixes #23315
Fixes #23321
See #23315 and #23321. This PR fixes a bug in ConsistentHashingStickyKeyConsumerSelector where the selected consumer for a hash could change across 2 existing consumers when a consumer was removed or when a new consumer was added.
In addition it fixes the problem that ConsistentHashingStickyKeyConsumerSelector.getConsumerKeyHashRanges() returned invalid information. These are fixed together since they are in the same code area and fixing getConsumerKeyHashRanges is required for testing the consistent selection of a consumer when there are hash collisions.
In PR #8396 a solution was added to fix a problem where all hash ring points were assigned to the last arrived consumer when there were hash collisions, for example when the consumers had the same name: …
=> [fix][broker] Fix out-of-order issues with ConsistentHashingStickyKeyConsumerSelector

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Main Issue: #23341
- Addressing CVE-2024-7254
- The CVE is categorized as high (8.7/10). It's a potential denial-of-service issue that
doesn't pose a practical risk for Pulsar users. Since it's in the high category, we must address it regardless of the impact for Pulsar users.
- this might break clients, more about the plan in
https://lists.apache.org/thread/qy8xp2ht0htvctlx2cwgrq2ppnjcp4m3
- Upgrade protobuf-java to 3.25.5, this PR is currently WIP. The goal is to see if our CI passes.
=> [fix][sec] Upgrade protobuf-java to 3.25.5

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Main Issue: #23341
this PR is for branch-3.3, the master branch PR is #23356
- Addressing CVE-2024-7254
- The CVE is categorized as high (8.7/10). It's a potential denial-of-service issue that
doesn't pose a practical risk for Pulsar users. Since it's in the high category, we must address it regardless of the impact for Pulsar users.
- this might break clients, more about the plan in
https://lists.apache.org/thread/qy8xp2ht0htvctlx2cwgrq2ppnjcp4m3
- Upgrade protobuf-java to 3.25.5, this PR is currently WIP. The goal is to see if our CI passes.
=> [fix][sec][branch-3.3] Upgrade protobuf-java to 3.25.5 (#23356)

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
Main Issue: #23341
this PR is for branch-3.0, the master branch PR is #23356
- Addressing CVE-2024-7254
- The CVE is categorized as high (8.7/10). It's a potential denial-of-service issue that
doesn't pose a practical risk for Pulsar users. Since it's in the high category, we must address it regardless of the impact for Pulsar users.
- this might break clients, more about the plan in
https://lists.apache.org/thread/qy8xp2ht0htvctlx2cwgrq2ppnjcp4m3
- Upgrade protobuf-java to 3.25.5, this PR is currently WIP. The goal is to see if our CI passes.
=> [fix][sec][branch-3.0] Upgrade protobuf-java to 3.25.5 (#23356)

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistry.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Brokers.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BrokersImpl.java
- metadata store could fail the broker lock registration. In this case, we should retry and also monitor the registry periodically and try to register it if not registered yet.
- also we need to verify if the broker is healthy or not before starting the orphan bundle cleanups, as the broker might receive "out-dated" notifications.
- add monitor logic to periodically check if the broker is registered and to try to register it.
- add timeout logic when the broker re-registration hangs.
- add retry logic when the broker re-registration fails.
- add health check logic before starting the orphan bundle cleanup jobs and canceling the cleanup jobs.
- add brokerId in broker health admin api …
=> [fix][broker] timeout when broker registry hangs and monitor broker registry (ExtensibleLoadManagerImpl only)

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Avro 1.11.3 contains critical 9.3/10 level RCE vulnerability in Avro Java SDK <1.11.4,  CVE-2024-47561
Upgrade Avro to 1.11.4 to address the issue.
[Dev mailing list discussion](https://lists.apache.org/thread/ptb227lw8lljw5zv7z2qo2mx9xxoyl5c) (contains information about release plan)
[Users mailing list discussion](https://lists.apache.org/thread/wgyjsdpnt4ccrd5xk3sdf6pw81zgvkhx)
=> [fix][sec] Upgrade Avro to 1.11.4 to address CVE-2024-47561

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorageTest.java
It fixes https://github.com/apache/pulsar/issues/21751
PIP: #21752 
We have introduced a configuration called `autoSkipNonRecoverableData` before open-sourcing Pulsar as we have come across with various situations when it was not possible to recover ledgers belonging to managed-ledger or managed-cursors and the broker was not able to load the topics. In such situations,`autoSkipNonRecoverableData` flag helps to skip non-recoverable leger-recovery errors such as ledger_not_found and allows the broker to load topics by skipping such ledgers in disaster recovery.
Brokers can recognize such non-recoverable errors using bookkeeper error codes but in some cases, it’s very tricky and not possible to conclude non-recoverable errors. For example, the broker can not differentiate between all the …
=> [improve][broker] PIP-327: Support force topic loading for unrecoverable errors

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/SchemasResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java, pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Schemas.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SchemaMetadata.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SchemasImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSchemas.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdSchema.java
PIP-360:  #22913 
Schema is one of the important part of the topic because it also plays important part in topic availability and required to successfully load the topic, and if schema initialization failure is causing issue in topic loading then it is very important to get schema metadata information to understand schema related issues and perform appropriate actions to mitigate that issue to successfully load the topic and make it available for users. Therefore, similar to ledger metadata and managed-ledger metadata, Pulsar should have API to show schema metadata and related ledger info which can be used by tools or users to perform appropriate actions during topic availability issues or any other troubleshooting.
Adding admin API and cli to read schema metadata.
*(Please pick either of …
=> [improve][pip] PIP-360 Add admin API to display Schema metadata

.github/workflows/pulsar-ci.yaml
Error message in https://github.com/apache/pulsar/actions/runs/11179184671/job/31078661681#step:13:42 was:
```
2024-10-04T12:05:48Z	FATAL	Fatal error	image scan error: scan error: scan failed: failed analysis: analyze error: pipeline error: failed to analyze layer (sha256:e2f493e066e35423c1459a42bb7c97d05f71f262edd92fbb61e45afd5c1c1ae0): post analysis error: post analysis error: Unable to initialize the Java DB: Java DB update failed: DB download error: OCI repository error: 1 error occurred:
* GET https://ghcr.io/v2/aquasecurity/trivy-java-db/manifests/1: TOOMANYREQUESTS: retry-after: 297.486µs, allowed: 44000/minute
```
Add `continue-on-error: true` to Trivy steps in Pulsar CI.
=> [improve][ci] Continue Pulsar CI build even when Trivy scanner fails

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/ClientGetSchemaTest.java
When schema ledger is broken and producer tries to connect without schema then broker fails to add that producer with below error.
It fixes below errors
```
03:46:47.861 [pulsar-io-4-63] DEBUG org.apache.pulsar.broker.service.BrokerService - No autoTopicCreateOverride policy found for persistent://ncp/global/content.ncp/url_uuid_alias.prod
03:46:47.861 [pulsar-io-4-63] DEBUG org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://ncp/global/content.ncp/url_uuid_alias.prod] Storage size = [0], backlog quota limit
[53687091200]
03:46:47.861 [pulsar-io-4-63] DEBUG org.apache.pulsar.broker.service.schema.BookkeeperSchemaStorage - [ncp/content.ncp/url_uuid_alias.prod] Fetching schema from store
03:46:47.862 [pulsar-io-4-63] DEBUG …
```
=> [fix][broker] Fix Broker was failing to create producer with broken schema ledger

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderBuilderImpl.java
Currently it's difficult for client to troubleshoot when Reader creation fails as it error doesn't provide enough information so, create error with more information to help client for troubleshooting.
*(or)*
*(or)*
*(example:)*
=> [fix][client] Add more info while throwing reader creation exception

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageRedeliveryTest.java
Removing unnecessary invocation count for the unit-test that makes test running unnecessary for multiple times.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Fix delivery-test with unnecessary invocation-count

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/BrokerOperabilityMetrics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
Issue: https://github.com/apache/pulsar/issues/20146
To add broker health check into prometheus metric.
Schedule a job at 1 minute time interval which calls healthCheck API on broker and updates the pulsar stats based on the broker health.
Unit test cases were added to verify this change.
=> [feat] [broker] Add broker health check status into prometheus metrics 

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Jetty 9.4.56 contains minor improves over the currently used 9.4.54 version.
It's useful to keep Jetty updated although [Jetty 9.x is already EoL](https://lists.apache.org/thread/d7dqy4w9x1dyrcdrymoypv3v3p7bncxx). (issue to upgrade to newer Jetty version is tracked by #22939, that is postponed).
release notes:
- https://github.com/jetty/jetty.project/releases/tag/jetty-9.4.56.v20240826
- https://github.com/jetty/jetty.project/releases/tag/jetty-9.4.55.v20240627
- Upgrade Jetty to 9.4.56.v20240826
=> [improve][misc] Upgrade Jetty to 9.4.56.v20240826

pip/pip-384.md
Rendered PIP document [PIP-384: ManagedLedger interface decoupling](https://github.com/lhotari/pulsar/blob/lh-pip-384/pip/pip-384.md)
Apache Pulsar uses a component called ManagedLedger to handle persistent storage of messages.
The ManagedLedger interfaces and implementation were initially tightly coupled, making it difficult to introduce alternative implementations or improve the architecture.
This PIP documents changes that have been made in the master branch for Pulsar 4.0. Pull Requests [#22891](https://github.com/apache/pulsar/pull/22891) and [#23311](https://github.com/apache/pulsar/pull/23311) have already been merged.
This work happened after lazy consensus on the dev mailing list based on the discussion thread ["Preparing for Pulsar 4.0: cleaning up the Managed Ledger …
=> [improve] PIP-384: ManagedLedger interface decoupling

.mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
The current maven wrapper version is outdated. It's better to update it before 4.0.0 release.
Updated maven wrapper with `mvn wrapper:wrapper` (running with `mvn` version `3.9.9`).
=> [improve][build] Update maven-wrapper (mvnw) to recent stable version 3.3.2

pip/pip-383.md
In AuthorizationProvider, the authorization interface `grantPermissionAsync(TopicName topicName, Set<AuthAction> actions, String role, String authDataJson)` currently only supports granting permissions to a single topic. 
If multiple topics need to be authorized under a namespace, the client needs to call the authorization interface concurrently. 
Since the permissions information are stored in the namespace-level policies, and multiple topics may be on different brokers, concurrent authorization will cause concurrent modification exceptions. 
Therefore, supporting granting/revoking permissions for multiple topics is very friendly.
=> [improve][PIP] PIP-383: Support granting/revoking permissions for multiple topics

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryIntegrationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/BrokerRegistryMetadataStoreIntegrationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerCloseTest.java
There are at least 2 really flaky tests in Pulsar master:
* ExtensibleLoadManagerCloseTest.testCloseAfterLoadingBundles https://github.com/apache/pulsar/issues/23412
* BrokerRegistryMetadataStoreIntegrationTest.cleanup https://github.com/apache/pulsar/issues/23413
- Move the tests to the `flaky` group until they are fixed.
=> [improve][ci] Move some flaky ExtensibleLoadManager tests to flaky group until they are fixed

.github/workflows/pulsar-ci.yaml, build/run_integration_group.sh, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/PulsarContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarClusterSpec.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarClusterTestBase.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/upgrade/PulsarUpgradeDowngradeTest.java, tests/integration/src/test/resources/pulsar-upgrade.xml
catch issues like https://github.com/apache/pulsar/issues/22051
Added a test for upgrade/downgrade
This change adds tests.
*NO*
PR in forked repository: https://github.com/dlg99/pulsar/pull/18
=> [improve][ci] Upgrade/Downgrade test

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeExclusiveStickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/StickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelectorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelectorTest.java
The Key_Shared PIP-379 implementation performs snapshots of hash range assignments after adding or removing a consumer in order to detect the existing consumers and hash ranges that changed as a result. This result is only used in Key_Shared AUTO_SPLIT ordered mode. Therefore, it's an unnecessary overhead for all other use cases. Any unnecessary work that can be avoided is a useful optimization, although the performance of the current snapshotting isn't a concern based on the microbenchmark and optimizations performed in the initial PR. ([comment](https://github.com/apache/pulsar/pull/23352#discussion_r1791091365), [simple microbenchmark](https://github.com/apache/pulsar/blob/7209b21b58d1efcf28a1869555596f5d52c3b348/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsistentHas …
=> [improve][broker] PIP-379: Snapshot hash range assignments only in AUTO_SPLIT ordered mode

pip/pip-307.md, pip/pip-324-Alpine Docker images.md, pip/pip-337.md, pip/pip-352.md, pip/pip-359.md, pip/pip-368.md
=> [fix][doc] Fix some typos in pip

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
Fixes https://github.com/apache/pulsar/issues/23425
This issue was introduced by PIP-327(https://github.com/apache/pulsar/pull/21759). when we set config ledgerForceRecovery true, the following judgment in method ManagedCursorImpl#recoverFromLedger is always true, which leads to skipping the correct logic behind it.
```java
if (isBkErrorNotRecoverable(rc) || ledgerForceRecovery) {
log.error("[{}] Error opening metadata ledger {} for cursor {}: {}", ledger.getName(), ledgerId, name,
BKException.getMessage(rc));
// Rewind to oldest entry available
initialize(getRollbackPosition(info), Collections.emptyMap(), cursorProperties, callback);
return;
} 
```
- change the condition to `rc != BKException.Code.OK && ledgerForceRecovery`
```java
if (isBkErrorNotRecoverable(rc) || (rc != …
```
=> [fix][ml][PIP-327] fix recover from ledger when ledgerForceRecovery is true

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/GetPartitionMetadataMultiBrokerTest.java
The root cause of this problem is that the `getBroker` method is asynchronous. When the method `getLookupRequestPermits` is called, the `lookupRequestSemaphore` may not have been released yet.
Wait for the `getBroker` method to complete before continuing
=> [fix][test] Fix flaky GetPartitionMetadataMultiBrokerTest.testCompatibilityDifferentBrokersForNonPersistentTopic

bin/bookkeeper, bin/pulsar
This reverts commit fa745384c2c3ea8c16e6c0cd078328a653fa3073.
#22921 reverted the change in #22867 to use correct way of passing parameters in shell scripts. 
The correct syntax is `"$@"`. 
In #22921, the argumentation was that a command `bin/pulsar zookeeper-shell --run-once "ls /ledgers"` no longer works.
This type of command has always been invalid for 2 reasons:
- `bin/pulsar zookeeper-shell` has never supported `--run-once` parameter.
- there's a Python based `zk-shell` which supports this syntax. `bin/pulsar zookeeper-shell` doesn't use `zk-shell` under the covers.
- `bin/pulsar zookeeper-shell` has never supported quoting the arguments to the command. This happened to work because of invalid parameter passing which is fixed by #22867 
- The Python based `zk-shell` requires the …
=> [fix] Reapply shell script parameter passthrough fix #22867 reverted in #22921

.github/workflows/pulsar-ci.yaml
- error message: Bad request - jaxxstorm/action-install-gh-release@v1.10.0 is not allowed to be used in apache/pulsar.
- pin aquasecurity/trivy-action@0.26.0 since master is broken
=> [fix][ci] Pin aquasecurity/trivy-action@0.26.0 since master is broken

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
Occasionally there is an ack hole in the cursor for geo-replication. The following is the internal stats for the topic where the problem occurred:
```json
{
"entriesAddedCounter" : 11000,
"numberOfEntries" : 6999,
"totalSize" : 362285,
"currentLedgerEntries" : 6999,
"currentLedgerSize" : 362285,
"lastLedgerCreatedTimestamp" : "2023-07-30T16:17:10.137+09:00",
"waitingCursorsCount" : 1,
"pendingAddEntriesCount" : 0,
"lastConfirmedEntry" : "1687807:6998",
"state" : "LedgerOpened",
"ledgers" : [ {
"ledgerId" : 1687807,
"entries" : 0,
"size" : 0,
"offloaded" : false,
"underReplicated" : false
} ],
"cursors" : {
"pulsar.repl.cluster-a" : {
"markDeletePosition" : "1687807:6002",
"readPosition" : "1687807:6999",
"waitingReadOp" : true,
"pendingReadOps" : 0,
"messagesConsumedCounter" : 10942, …
```
=> [fix][broker] Fix ack hole in cursor for geo-replication

.github/workflows/pulsar-ci.yaml, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java
The setting was decreased from 180 seconds to 25 seconds in #22541.
The default setting of 25 seconds is causing connection disconnects and connects when they aren't expected.
The reason is that the default for autoUpdatePartitionsInterval is 60 seconds and if idle timeout is shorter, it causes connections to close and open unnecessarily each time the scheduled task runs.
Increase connectionMaxIdleSeconds to 60 seconds
=> [improve][client] Increase default Java client connectionMaxIdleSeconds to 60 seconds

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationProvider.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/GrantTopicPermissionOptions.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/RevokeTopicPermissionOptions.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java
PIP-383:  https://github.com/apache/pulsar/pull/23355
=> [improve][broker] PIP-383: Support granting/revoking permissions for multiple topics

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerCloseTest.java
Fixes #23412
https://github.com/apache/pulsar/pull/23382 brings a regression to the broker stop phase, which could be blocked by waiting:
- `healthCheckBrokerAsync` in `ServiceUnitStateChannelImpl#doCleanup`, which could be blocked for `metadataStoreOperationTimeoutSeconds` seconds (default: 30s)
- `unloadNamespaceBundle` in `BrokerService#unloadNamespaceBundlesGracefully`, which could be blocked for `namespaceBundleUnloadingTimeoutMs` milliseconds (default: 1 min) for each problematic bundle
~~The 2nd method could be blocked when `healthCheckBrokerAsync` failed with `NotFoundException` but the following steps were not skipped.~~
- Check if the service unit state channel is disabled or closed via `channelDisabled` before `healthCheckBrokerAsync`
- Optimize some logs to avoid printing the …
=> [fix][broker] Fix namespace unload might be blocked too long with extensible load manager

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/ClientGetSchemaTest.java
We have made broker resilient during non-recoverable schema error with PR: https://github.com/apache/pulsar/pull/23395
However, there is discussion to make it only if  `SchemaLedgerForceRecovery` enabled. so, this PR enables schema lost recovery only if force flag is enabled.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Allow broker to handle non-recoverable schema error only if SchemaLedgerForceRecovery flag is enabled

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessagesImpl.java
Main Issue: #21631
- Add warn log when can't add message to the container.
=> [improve][client] Add log when can't add message to the container

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/offload/OffloaderUtils.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/plugin/servlet/AdditionalServletUtils.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/BrokerInterceptorUtils.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/protocol/ProtocolHandlerUtils.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/utils/CustomCommandFactoryProvider.java, pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/functions/FunctionUtils.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/io/ConnectorUtils.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/service/WorkerServiceLoader.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/extensions/ProxyExtensionsUtils.java
In the broker configuration, we're using relative paths for parameters such as `brokerInterceptorsDirectory`, `protocolHandlerDirectory`, `additionalServletDirectory`, and `offloadersDirectory`. These paths include the `./` notation, and since the broker doesn't normalize them, the absolute paths generated are incorrect, for example: `/app/pulsar/20241011165422044/./interceptors/pulsar-xxx.nar`. As a result, the broker is unable to resolve the correct file locations.
Test cases: 
```java
@Test
public void testPathNormalize() {
Path path = Paths.get("./interceptors").toAbsolutePath().normalize();
assertEquals(path.toString().indexOf("./"), -1);
}
@Test
public void testPathWithoutNormalize() {
Path path = Paths.get("./interceptors").toAbsolutePath(); …
```
=> [fix][broker] normalize path

pulsar-client-tools/pom.xml, pulsar-common/pom.xml
Pulsar maven build shows some warning at the beginning:
```
[WARNING] Some problems were encountered while building the effective model for org.apache.pulsar:pulsar-common:jar:4.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.google.re2j:re2j:jar -> duplicate declaration of version (?) @ line 250, column 17
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.apache.pulsar:pulsar-client-tools:jar:4.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: ${project.groupId}:pulsar-cli-utils:jar -> duplicate declaration of version ${project.version} @ line 79, column 16
[WARNING]
```
- fix the warnings by removing the duplicate dependencies
=> [fix][build] Remove duplicate dependencies in pom.xml

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsumerHashAssignmentsSnapshot.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelectorTest.java
Fixes #23439
When a consumer joins or leaves, the hash ranges from existing consumers shouldn't move from one to another.
- Revisit adding the to hash ring so that existing consumers aren't replaced when there are collisions.
- Add a test case which ensures this
=> [improve][broker][PIP-379] Don't replace a consumer when there's a collision

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
Fixes https://github.com/apache/pulsar/issues/23164
The previous current ledger can only be deleted if the new ledger is created.
When param closeLedgerByAddEntry is true, there may exist the situation: when call internalTrimEdgers to delete previous current ledger, new ledger has not been created, and causing the test failed.
Whether closeLedgerByAddEntry is true or false, we both need to add `Awaitility.await().untilAsserted(() -> assertEquals(ml.ledgers.size(), 2));` to wait the new ledger create.
=> [fix][test] Fix flaky test ManagedLedgerTest.testDeleteCurrentLedgerWhenItIsClosed

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactorTool.java
Main Issue: https://github.com/apache/pulsar/issues/23445
In the [PIP-352](https://github.com/apache/pulsar/pull/22517)， EventTimeOrderCompactor which compact message based on eventTime was added.
I think that we can add compactor type option in compaction tool, then user can choose to use PublishingOrderCompactor or EventTimeOrderCompactor to compact message
- add option `--compactor-type`, default value is `CompactorType.PUBLISHING`  
=> [improve][cli] Add compactor type option for compaction tool

bin/ledgers.md, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/NamespaceEventsSystemTopicFactory.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java
- Users may start 2 clusters with the Geo-Replication feature with Global ZK
- Users want to hire one cluster, so remove the cluster from `namespace-level replicatedClusters`
- Broker will remove the topics of the cluster removed automatically.
- Issue occurs:
- The system topic `__change_events` being deleted first.
- User topics can not be deleted anymore, because the operation `delete topic-level policies` can not be executed successfully anymore.
- The task `topic.checkReplication` and other operations will retry again and again, as a result, the broker will crash of OOM  
---
---
- Skip removing topic-level policies if the system topic `__change_event` has been deleted.
=> [fix] [broker] topics failed to delete after remove cluster from replicated clusters set and caused OOM

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelector.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/RemovedHashRanges.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ConsistentHashingStickyKeyConsumerSelectorTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Range.java, pulsar-client/src/test/java/org/apache/pulsar/client/api/RangeTest.java
Fixes #23443
In the current ConsistentHashingStickyKeyConsumerSelector implementation, when there's a hash ring point collision,
the original entry will be preserved and the attempted addition will be rejected.
This isn't a problem with the consumerNameIndexTracker solution since the collisions won't align for all hash ring points when using the same consumer name. Because of this, collisions won't affect the overall distribution significantly when the number of hash ring points is sufficiently large (>100).
However, when the "selected" consumer is removed, the colliding consumer should be selected and take over it's hash ring point. This PR implements that logic.
- add HashRingPointEntry which holds the selected consumer and the colliding consumers
- add logic for adding and removing to …
=> [improve][broker][PIP-379] Improve hash collision handling by restoring consumer when other leaves

.gitignore, pom.xml, pulsar-broker/pom.xml, pulsar-common/pom.xml, pulsar-transaction/coordinator/pom.xml
Visual Studio Code (vscode) is a popular IDE. It would be great to support developing Pulsar with [vscode-java](https://github.com/redhat-developer/vscode-java).
One of the reasons for adding vscode-java support is due to Cursor AI code editor building upon vscode. When there's vscode-java support in Pulsar, it would be possible to use Cursor for developing Pulsar.
Similar changes are most likely required for supporting Eclipse for Apache Pulsar development since vscode-java uses Eclipse modules under the covers for Java and Maven support. 
The lightproto maven plugin issue most likely impacts IntelliJ too since currently you need to build Pulsar once in order to get lightproto generated classes to resolve. This change will most likely address that issue too.
- workaround issues with …
=> [fix][build] Add basic support for vscode-java and Eclipse IDE

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java
Fixes #23249
The current javadoc for ConsumerBuilder.isAckReceiptEnabled doesn't make sense and it's wrong, see #23249 for details.
Fix the javadoc.
=> [fix][client] Fix the javadoc for ConsumerBuilder.isAckReceiptEnabled

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/GetPartitionMetadataTest.java
Fixes #23455
GetPartitionMetadataMultiBrokerTest.testCompatibilityForNewClientAndOldBroker is really flaky and fails often. 
There's an explanation for the flakiness, it's similar as #23259.
- Fix the flakiness in the same way as #23259
- Make the test extend TestRetrySupport and adapt the setup and cleanup methods to use TestRetrySupport.
- The test doesn't have retries enabled. There are a lot of flaky tests in Pulsar and one of the solutions is to retry the test if it fails.
=> [fix][test] Address flaky GetPartitionMetadataMultiBrokerTest

pip/pip-367.md
See proposal for detail.
*(or)*
*(or)*
*(example:)*
=> [improve][pip] PIP-367: Propose a Contributor Repository for Pulsar

pom.xml
- Spring 6.1.x is the only OSS supported version at the moment: https://endoflife.date/spring-framework
- OWASP dependency check reports CVE-2024-38808 (Moderate 5.1/10)
- Upgrade Spring version to 6.1.13
=> [improve][io] Upgrade Spring version to 6.1.13 in IO Connectors

pulsar-sql/presto-distribution/LICENSE
When cherry-picking https://github.com/apache/pulsar/pull/23405 to the branch-3.0, we didn't update the `/pulsar-sql/presto-distribution/LICENSE`, this broke the branch-3.0 CI.
- Update jetty version in the `/pulsar-sql/presto-distribution/LICENSE`.
=> [fix][sql] Fix LICENSE

.asf.yaml
Shared branches should always be protected against force pushes, see #14226 for the PR where we enabled this.
- configuration was missing for `branch-3.2` and `branch-3.3`, add
- add for recent `branch-4.0`
=> [improve][ci] Prevent git force push to more recent maintenance branches

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BinaryProtoLookupService.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/BinaryProtoLookupServiceTest.java
Cherry-pick #23378 to the branch-3.0.
=> [fix][client] Use dedicated executor for requests in BinaryProtoLookupService (#23378)

pom.xml
When attempting to build Pulsar on RISC-V 64-bit (riscv64) architecture, the build process fails with an "unknown os.arch: riscv64" error. This is caused by the os-maven-plugin version 1.7.0, which lacks proper support for detecting the riscv64 architecture. This PR aims to resolve this issue and enable successful builds on RISC-V 64-bit systems.
```log
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: unknown
[ERROR] unknown os.arch: riscv64 -> [Help 1]
```
- Updated the os-maven-plugin version in the project's build configuration from 1.7.0 to 1.7.1. …
=> [improve][build] Upgrade os-maven-plugin to support RISC-V 64

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerStats.java
=> [fix][client] Fix ConsumerStats.getRateMsgsReceived javadoc

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
Bump oxia java version from 0.4.5 to 0.4.7
- Bump oxia java version from 0.4.5 to 0.4.7
=> [feat][meta] Bump oxia java version from 0.4.5 to 0.4.7

pulsar-broker/src/test/java/org/apache/pulsar/broker/SameAuthParamsLookupAutoClusterFailoverTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/DisabledCreateTopicToRemoteClusterForReplicationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicationTxnTest.java
Pulsar CI is blocked by #23474.
Mailing list discussion: https://lists.apache.org/thread/7m075w1qthzo01rzfz7fb236ok00hdo7
Move all OneWayReplicatorTestBase tests to flaky group until the problem is resolved.
=> [fix][ci] Temporarily move OneWayReplicatorTestBase tests to flaky group to unblock CI

pulsar-client-admin-shaded/pom.xml, pulsar-client-all/pom.xml
Fixes #22263
Since version 3.0.0, `com.google.protobuf:protobuf-java` has been directly included in `pulsar-client-admin` or `pulsar-client-all` without relocation (i.e., the classes remain in their original package). This is considered bad practice as it may cause conflicts with the user’s application’s version of `protobuf-java`. For example, I encountered this issue in a program that consumes Pulsar messages and writes to a Parquet file using the protobuf schema.
By not shading `protobuf-java`, users can select their desired version of `protobuf-java`.
More details explained in https://github.com/apache/pulsar/issues/22263#issuecomment-2040965946
Prevent shade `protobuf-java`, move it into transitive dependencies, keep consistency with `pulsar-client`. …
=> [fix][client] Prevent embedding protobuf-java class files in pulsar-client-admin and pulsar-client-all

grafana/dashboards/offloader.json
Add grafana dashboard of offloader stats which introduced by https://github.com/apache/pulsar/pull/13833
*(or)*
*(or)*
*(example:)*
=> [feat][monitor] Add offloader stats grafana dashboard

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Added message properties tests for batch and non-batch messages. 
=> [improve][test] Added message properties tests for batch and non-batch messages

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/cache/InflightReadsLimiterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/BrokerOpenTelemetryTestUtil.java, pulsar-opentelemetry/src/test/java/org/apache/pulsar/opentelemetry/OpenTelemetryServiceTest.java
OTel AutoConfiguredOpenTelemetrySdkBuilder will register a shutdown hook by default. This will cause a memory leak since there will be a reference to all OpenTelemetrySdk instances until the test JVM completes running tests.
Disable registering shutdown hook in tests.
=> [fix][test] Fix memory leak via OTel shutdown hooks in tests

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Upgrade OpenTelemetry (OTel) libraries so that we stay up-to-date.
- upgrade OTel to 1.41.0 and use other compatible libraries
=> [improve][monitor] Upgrade OTel to 1.41.0

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
- there are OOMs in test runs such as https://github.com/apache/pulsar/actions/runs/11390425506/job/31692462848?pr=23449#step:11:1687
- it's not necessary to spy invocations that consume a lot of memory
- remove configuration that enabled spying of invocations that was added in #23313 since it was assumed that it was necessary
=> [fix][test] Prevent OOM in test by not spying invocations in SimpleProducerConsumerTest

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java
https://github.com/apache/pulsar/pull/22854 added a new method `List<Integer> getExistsPartitions(String topic)`, which depends on the new method `GetTopicsResult.nonPartitionedOrPartitionTopics`, but the author of the PR forgot the change the deserializer of Pulsar-Proxy, which may cause the following issue:
- Broker respond: `tp-partition-0`
- Proxy received `tp-partition-0` and recreate a new response that may remove the suffix `-partition-0` to client 
- Client received `tp`, which without `-partition-0`
- Client assumed the parition `0` does not exists. 
Fix the bug
=> [fix] [proxy] Fix pattern consumer does not work when using Proxy

pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ClusterMetadataSetupTest.java
Running ClusterMetadataSetupTest fails in IntelliJ since the tests is invalid.
Fix the test
=> [fix][test] Fix running ClusterMetadataSetupTest in IDE

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Fixes https://github.com/apache/pulsar/issues/23501
When seek to the current time `reader.seek(System.currentTimeMillis());`,  `reader.hasMessageAvailable()` should return false cause there has no message to read, but right now it returns true.
- when hasSoughtByTimestamp, we only need to check  result < 0
```java 
else if (hasSoughtByTimestamp) {
completehasMessageAvailableWithValue(booleanFuture, result < 0);
}
```
=> [fix][client] Fix Reader.hasMessageAvailable return wrong value after seeking by timestamp with startMessageIdInclusive

pulsar-broker/src/main/java/org/apache/pulsar/zookeeper/LocalBookkeeperEnsemble.java
Sometimes, the standalone server may not start because `/ledgers/available/%s` have not been deleted correctly, which is introduced by https://github.com/apache/pulsar/pull/21407:
```
2024-10-21T09:51:29,569+0000 [BookieStateManagerService-0] INFO  org.apache.bookkeeper.discover.ZKRegistrationManager - Previous bookie registration znode: /ledgers/available/bk0test exists, so waiting zk sessiontimeout: 10000 ms for znode deletion
2024-10-21T09:51:29,570+0000 [BookieJournal-3181] INFO  org.apache.bookkeeper.bookie.JournalChannel - Opening journal data/standalone/bookkeeper0/current/192ae7cd847.txn
2024-10-21T09:51:35,584+0000 [SessionTracker] INFO  org.apache.zookeeper.server.ZooKeeperServer - Expiring session 0x100091b67e50000, timeout of 6000ms exceeded
2024-10-21T09:51:39,570+0000 …
```
=> [fix][standalone] correctly delete bookie registration znode

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerCloseTest.java
(cherry picked from commit 5506f50fa036f1ad19c3e0abc03e74ecd5c0a665)
=> [fix][broker] Fix namespace unload might be blocked too long with extensible load manager (#23433)

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
…
- There might be a chance that there is no channel owner. The existence of the channel owner(leader) needs to be monitored.
- Elect the channel owner(leader) if no channel owner is found in the role(leader|follower) play and monitor logic.
=> [improve][broker] re-elect the channel owner if no channel owner is found

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/SameAuthParamsLookupAutoClusterFailoverTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/DisabledCreateTopicToRemoteClusterForReplicationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicationTxnTest.java
Fixes #23474
A lock named `isClosingOrDeleting` prevents concurrently deleting/closing topic
---
The code that deleting the topic is like below
```java
CompletableFuture deleteFuture = () -> {
CompletableFuture res = new CompletableFuture();
....
if (success) {
res.complete();
} else {
res.failed();
// Highlight: release the lock `isClosingOrDeleting`.
//Release the lock the first time.
unfenceTopicToResume();
}
};
deleteFuture.whenComplete((__ ,ex) -> {
if (ex != null) {
// Highlight: release the lock `isClosingOrDeleting`.
//Release the lock the second time.
unfenceTopicToResume();
}
});
```
The code in `PersistentTopic.delete` acquires the lock once, but releases it twice, which breaks the locker, and leads to multiple deleting runs at the same time.
---
There is a checker that broker …
=> [fix] [broker] Fix race-condition causing repeated delete topic

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataTeardown.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ClusterMetadataSetupTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ClusterMetadataTeardownTest.java
The pulsar configuration supported `metadataStoreConfigPath` and `configurationStoreConfigPath`, but the cluster metadata teardown command does not have a place to set the config path.
Make cluster metadata init command support metadata config path
=> [improve][broker] Make cluster metadata teardown command support metadata config path

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ReaderBuilder.java
Fixes https://github.com/apache/pulsar/issues/23498
The `Consumer#seek(long)` and `startMessageIdInclusive` have no relation. Whether startMessageIdInclusive is present or not, Consumer#seek(long) that seek by timestamp will contain the firstMessageId.
In the code, we can see that the `Consumer#seek(long)` seekMessageId use the MessageId.earliest.
```java
@Override
public CompletableFuture<Void> seekAsync(long timestamp) {
String seekBy = String.format("the timestamp %d", timestamp);
long requestId = client.newRequestId();
return seekAsyncInternal(requestId, Commands.newSeek(consumerId, requestId, timestamp),
MessageId.earliest, timestamp, seekBy);
}
```
remove the `Consumer#seek(long)` in comment of `ReaderBuilder#startMessageIdInclusive` and `ConsumerBuilder#startMessageIdInclusive`
PR …
=> [fix][client] Fix the javadoc for startMessageIdInclusive

pom.xml, pulsar-io/hdfs3/pom.xml, tiered-storage/file-system/pom.xml
OWASP dependency check shows an error for bcprov-jdk15-on dependency.
```
One or more dependencies were identified with known vulnerabilities in Apache Pulsar :: Tiered Storage :: Parent:
bcprov-jdk15on-1.70.jar (pkg:maven/org.bouncycastle/bcprov-jdk15on@1.70, cpe:2.3:a:bouncycastle:bouncy-castle-crypto-package:1.70:*:*:*:*:*:*:*, cpe:2.3:a:bouncycastle:bouncy_castle_crypto_package:1.70:*:*:*:*:*:*:*, cpe:2.3:a:bouncycastle:bouncy_castle_for_java:1.70:*:*:*:*:*:*:*, cpe:2.3:a:bouncycastle:legion-of-the-bouncy-castle-java-crytography-api:1.70:*:*:*:*:*:*:*, cpe:2.3:a:bouncycastle:the_bouncy_castle_crypto_package_for_java:1.70:*:*:*:*:*:*:*) : CVE-2024-34447, CVE-2024-29857, CVE-2024-30171, CVE-2023-33202, CVE-2023-33201
```
Replace outdated bcprov-jdk15-on dependency with bcprov-jdk18-on …
=> [fix][sec] Replace bcprov-jdk15on dependency with bcprov-jdk18-on

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ClusterMigrationTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
PIP: #16551 
Currently, cluster migration fails while creating migration-redireaction command if brokerUrlsTls doesn't exist and broker fails to send redirection command. Therefore, broker should handle null value for brokerUrl/brokerUrlTls while preparing the command.
```
2024-10-30T22:06:02,653-0700 [pulsar-client-io-1-7] WARN  org.apache.pulsar.client.impl.ClientCnx - [localhost/127.0.0.1:6650] Got exception java.lang.IllegalStateException: Field 'brokerServiceUrlTls' is not set
at org.apache.pulsar.common.api.proto.CommandTopicMigrated.getBrokerServiceUrlTls(CommandTopicMigrated.java:130)
at org.apache.pulsar.client.impl.ClientCnx.handleTopicMigrated(ClientCnx.java:714)
```
This fix will allow cluster migration even if it doesn't have brokerUrlTls configured.
*(Please pick either of …
=> [fix][broker] Fix Broker migration NPE while broker tls url not configured

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdClusters.java
PIP: https://github.com/apache/pulsar/issues/16551
Currently, pulsar-admin cli is not printing cluster migration state response and this PR fixes the printing it on console.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Fix print cluster migration state response

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/cache/InflightReadsLimiterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/BrokerOpenTelemetryTestUtil.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java, pulsar-opentelemetry/src/test/java/org/apache/pulsar/opentelemetry/OpenTelemetryServiceTest.java
Running InflightReadsLimiterTest is slow and prints these warnings
```
Nov 01, 2024 4:37:19 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: Failed to export metrics. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
Nov 01, 2024 4:37:21 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: Failed to export metrics. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
Nov 01, 2024 4:37:26 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: Failed to export metrics. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
Nov 01, 2024 4:37:31 PM …
```
=> [improve][test] Disable OTel autoconfigured exporters in tests

pulsar-package-management/bookkeeper-storage/src/main/java/org/apache/pulsar/packages/management/storage/bookkeeper/DLOutputStream.java, pulsar-package-management/bookkeeper-storage/src/test/java/org/apache/pulsar/packages/management/storage/bookkeeper/DLOutputStreamTest.java
Fixes #23547 
PIP: #xyz 
- org.apache.pulsar.packages.management.storage.bookkeeper.DLOutputStreamTest
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/33
=> [fix][broker] Increase readBuffer size for bookkeeper.DLOutputStream

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java, pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SinkConfigUtilsTest.java
Support update subscription position for sink connector
- Support update subscription position for sink connector
Add test to cover it.
=> [improve][io] Support update subscription position for sink connector

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/LookupImpl.java
If the user deploys a cluster with proxy, and network topology like this: Client -> Proxy(with TLS) -> Broker(without TLS)
When the user calls `pulsar-admin topics lookup <topic name>`, the user will get a `null` response.
But the exact value that the broker responded to is below:
```json
{
"brokerUrl": "pulsar://broker-1.com:6650",
"httpUrl": "http://broker-1.com:8080",
"brokerUrlSsl": ""
}
```
It is caused by the pulsar-admin client's issue: https://github.com/apache/pulsar/blob/master/pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/LookupImpl.java#L60
```java
if (client.useTls) {
return response.brokerUrlSsl; // even if it is null 
}
```
- fix the issue
- the test is hard to write, so I skipped to write a test
=> [fix] [admin] Fix lookup get a null result if uses proxy

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
Fixes #23417 
Ideally, recoverFromLedger should only call operationComplete upon successful recovery and operationFailed upon failure. However, in the actual implementation, both methods may be called due to the following reasons:
Concurrent Execution: If recoverFromLedger is executed in different threads, it may simultaneously meet both success and failure conditions, leading to both callbacks being triggered.
After adding logs, we may see both:
* Cursor recovery success
* Cursor recovery failed
Use an atomic variable. Use an AtomicBoolean in the callback to mark whether the callback method has already been called, preventing duplicate calls.
=> [fix][test] Fix ManagedCursorTest.testForceCursorRecovery

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
Currently when broker fails to load topic it always logs error message with config failure but logging should be done based on exception type to help user while debugging the issue. So, fix the logging during topic loading.
Fix the logging message.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] fix logging with correct error message while loading the topic

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java
When users are calling `pulsar-admin` API, and there is an internal error( such as a deserialize JSON error), there is no error log.
You can test it this way:
- add a method getMsgRateIn() for `TopicStatsImpl`, and return a `String` value(such as `abc`), which will make the `response.msgRateIn` as a String value `abc`.
- call `pulsar-admin topics stats`
- You will get nothing, and no error log is printed. 
Print error log if handle HTTP response fails
=> [improve][admin] Print error log if handle http response fails

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
Fixes #23485
After calling `pause()`, there are still messages retained in `incomingMessages` because the internal `consumer `has already pre fetched a message and placed it in `incomingMessages`.
When calling pause(), these pre fetched messages are not immediately cleared, causing instability as messages can still be received during testing.
A larger `receiverQueueSize` allows more messages to be prefetched and cached, ensuring that messages in the buffer are effectively managed after a pause operation, without causing message interference during testing.
In a multi topic consumer environment, the `receiverQueueSize `should be set reasonably. For multi topic consumers, the receiver Queue Size should be large enough to ensure that each internal ConsumerImpl instance can independently …
=> [fix][test] Fix SimpleProducerConsumerTest.testMultiTopicsConsumerImplPauseForManualSubscription

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/GetPartitionMetadataTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/TokenAuthenticatedProducerConsumerTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
https://github.com/apache/pulsar/pull/23291 introduces a regression that when the authentication is enabled, if the topic does not exist and cannot be automatically created (e.g. namespace does not exist), broker will respond with a `ServerError.MetadataError` that is converted to a trivial `PulsarClientException`, which is not retriable. In this case, the client will loop in sending the `PartitionMetadata` request and failing until the operation timeout happens (30 seconds by default)
Besides, `PulsarClientImpl#checkPartitions` is incorrect. Even if `forceNoPartitioned` is false, `checkPartitions.complete(0)` will still be called.
```java
if (forceNoPartitioned && actEx instanceof PulsarClientException.NotFoundException
|| actEx instanceof PulsarClientException.TopicDoesNotExistException …
```
=> [fix][broker] Fix currently client retries until operation timeout if the topic does not exist

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/SchemaServiceTest.java
Fixes: https://github.com/apache/pulsar/issues/23457
```
Error:  Tests run: 30, Failures: 1, Errors: 0, Skipped: 17, Time elapsed: 59.073 s <<< FAILURE! - in org.apache.pulsar.broker.service.schema.SchemaServiceTest
Error:  org.apache.pulsar.broker.service.schema.SchemaServiceTest.testSchemaRegistryMetrics  Time elapsed: 0.053 s  <<< FAILURE!
java.lang.AssertionError: expected [tenant/ns] but found [public/ns_73b1a31afce34671a5ddc48fe5ad7fc8]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
```
It seems to be caused by lack of sufficient isolation between test runs. 
Use `AssertJ` fluent assertions instead of `for` iterate to do assertion check.
*If the box was checked, please highlight …
=> [fix][test]Flaky-test: SchemaServiceTest.testSchemaRegistryMetrics

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java
Fixes #23542
The original `receiverQueueSize `was 100, and the producer generated a total of 100 messages. It is possible that all messages were put into the dead letter queue by one consumer, resulting in assertion failure.
Reduce the size of the `receiverQueueSize `to ensure that every consumer processes the message.
`receiverQueueSize `：100 -> 20
The last test was manually cancelled.
=> [fix][test] Fix DeadLetterTopicTest.testDeadLetterTopicWithInitialSubscriptionAndMultiConsumers

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java
Currently if user passes proxy-url and proxy-protocol and if user doesn't pass tls param or makes a typo in service-url-tls (eg:: `ppulsar+ssl`) then client lib thinks tls is disabled and doesn't enable SNI proxy without any log message which creates connection failures and makes very difficult for users to debug. so, log the message when client lib disables SNI proxy even after passing complete SNI information.
*(or)*
*(or)*
*(example:)*
- *Extended …
=> [fix][client] Add logging when lib disabled sni even after passing proxy-url

pulsar-broker/src/test/java/org/apache/pulsar/client/api/InterceptorsTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
This is a fix follow up https://github.com/apache/pulsar/pull/23141 which does not cover the earlier hit for beforeConsume() method with message listener. Instead of calling the interceptor before put the message listener task to the message listener thread pool, we should move it to the inside of the message listener task. So that users will not get an earlier hit of the beforeConsume() method in the interceptor.
The expected behavior should be
- before consume message 0
- received message 0
- before consume message 1
- received message 1
- before consume message n
- received message n
Without this fix, the actual behavior was
- before consumer message 0
- before consumer message 1
- before consumer message n
- received message 0
- received message 1
- received message n …
=> [fix][client] fix the beforeConsume() method earlier hit with message listener

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java
It should fix: #23564 
Currently if topic gets fenced for some reason (eg: Metadata-BadVersion) then broker is not allowing non-durable sub to be created and keep failing with below errors because broker is not closing and recreating topic to recover this error in case of non-durable sub where as broker does it during dutable-sub or producer creation.
```
Caused by: org.apache.bookkeeper.mledger.ManagedLedgerException$ManagedLedgerFencedException: java.lang.Exception: Attempted to use a fenced managed ledger
Caused by: java.lang.Exception: Attempted to use a fenced managed ledger
at org.apache.bookkeeper.mledger.ManagedLedgerException$ManagedLedgerFencedException.<init>(ManagedLedgerException.java:80) ~[org.apache.pulsar-managed-ledger-3.3.4.jar:3.3.4]
at …
```
=> [fix][broker] Broker is failing to create non-durable sub if topic is fenced

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
Zookeeper 3.9.3 addresses CVE-2024-51504
- Upgrade Zookeeper to 3.9.3
- Upgrade Curator to 5.7.1 due to incompatibilities in Curator 5.1.0 with Zookeeper 3.9.3
=> [fix][sec] Upgrade Zookeeper to 3.9.3 to address CVE-2024-51504

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataTeardown.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ClusterMetadataTeardownTest.java
When executing the `delete-cluster-metadata` command, it should remove the current cluster from the `replication cluster` and `allowed cluster`, otherwise the cluster will still replicate the data to a deleted cluster.
Support cleanup `replication cluster` and `allowed cluster` when cluster metadata teardown
=> [improve][broker] Support cleanup `replication cluster` and `allowed cluster` when cluster metadata teardown

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannel.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/ExtensibleLoadManagerImplTest.java
…
(cherry picked from commit 266e705d29e16145ccb56a9031b4663a7ae085b7)
=> [improve][broker] re-elect the channel owner if no channel owner is found (#23516)

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/NegativeAcksTracker.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerImplTest.java
**Negative ack feature** need to retain the message id and timestamp info in the memory of the consumer client side, leading to great memory consumption.
This PR aim to replace the `HashMap` with the inner map implementation `ConcurrentLongLongPairHashMap` to reduce the memory consumption. Though `HashMap` is faster than the inner map implementation `ConcurrentLongLongPairHashMap` in some cases, but the most important issue in this case is memory consumption instead of the speed.
Some test data list as follows:
```
public static void main(String[] args) throws IOException {
ConcurrentLongLongPairHashMap map1 = ConcurrentLongLongPairHashMap.newBuilder()
.autoShrink(true)
.concurrencyLevel(16)
.build();
HashMap<MessageId, Long> map2 = new HashMap<>();
long numMessages = 5000000;
long …
```
=> [improve] [broker] replace HashMap with inner implementation ConcurrentLongLongPairHashMap in Negative Ack Tracker.

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Upgrade to Netty 4.1.115.Final to address CVE-2024-47535. This DoS vulnerability doesn't practically apply to Pulsar since the vulnerability requires write access to the filesystem where the application using Netty is running. However, it's always useful to address CVEs by upgrading to a version that doesn't contain known vulnerabilities.
- Upgrade Netty to 4.1.115.Final
- netty-bom in 4.1.115.Final upgrades Netty tcnative to 2.0.69.Final
- Release notes:
- [4.1.115.Final](https://netty.io/news/2024/11/12/4-1-115-Final.html)
- [4.1.114.Final](https://netty.io/news/2024/10/01/4-1-114-Final.html)
- Netty tcnative [changes in 2.0.69.Final since 2.0.66.Final](https://github.com/netty/netty-tcnative/compare/netty-tcnative-parent-2.0.66.Final...netty-tcnative-parent-2.0.69.Final)
=> [fix][sec] Upgrade to Netty 4.1.115.Final to address CVE-2024-47535

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedProducerImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java
After #13344, the default value of maxPendingMessages and maxPendingMessagesAcrossPartitions change to **0**.
When creating a producer with the partitioned topic, setting one of the above configurations doesn't take effect; the actual value is always 0.
Because here have a minimum judgment.
https://github.com/apache/pulsar/blob/92448d5f3113d783d41de6bae718d34cd73ca934/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedProducerImpl.java#L86-L89
- When setting one of the values, use it directly. Only perform the `min` check when both values are not zero.
- Add PartitionedProducerImplTest.testMaxPendingQueueSize to cover this logic.
- Add testProducerQueueFullBlockingWithPartitionedTopic test to cover blockQueueFullWithPartitiond case.
=> [fix][client] The partitionedProducer maxPendingMessages always is 0

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java
Fixes #23588
Enable DNS retryOnTimeout with TCP in netty to fix udp timeout error, we can see similar errors and fixes in other applications
Related links: 
https://github.com/netty/netty/pull/13757
https://github.com/reactor/reactor-netty/issues/2978
https://github.com/reactor/reactor-netty/issues/3059
https://github.com/redisson/redisson/issues/1625
add `socketChannelType` for configure the resolver to fallback to TCP if a timeout is detected
*(or)*
*(or)*
*(example:)* …
=> Enabling DNS retryOnTimeout with TCP in DnsNameResolver

testmocks/src/main/java/org/apache/bookkeeper/client/BookKeeperTestClient.java, testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockBookKeeper.java
I read testmocks model codes, found some code namely maybe more clearly
=> [improve][test] Clarify method signatures in Bookkeeper mock client

distribution/server/pom.xml, jetcd-core-shaded/pom.xml, pom.xml, pulsar-broker/pom.xml, pulsar-metadata/pom.xml
Fixes #23513 
With recent pulsar releases, it raise `NoClassDefFoundError` if setup with a `etcd` metadata.
```shell
docker run -it --rm apachepulsar/pulsar:4.0.0 bin/pulsar standalone --metadata-url etcd:http://a-etcd:2379
docker run -it --rm apachepulsar/pulsar:3.0.6 bin/pulsar standalone --metadata-url etcd:http://a-etcd:2379
```
The `jetcd-core-shaded` module was introduced in #22892 to address the compatibility issues between jetcd-core’s grpc-java dependency and Netty. You can find more details [here][1] and in the [grpc-java documentation][2].
[1]: https://github.com/apache/pulsar/pull/22892#issuecomment-2162347086
[2]: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
Currently, we use `unpack-shaded-jar` execution unpacks the shaded jar produced by …
=> [fix][misc] Unable to connect an etcd metastore with recent releases due to jetc-core sharding problem

tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java, tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemOffloaderLocalFileTest.java, tiered-storage/file-system/src/test/resources/filesystem_offload_core_site.xml
---
Fixes #xyz
PIP: #xyz 
We provided the fileSystemUri in the offload policy as the filesystem offload configuration. The fileSystemUri will overwrite the fs.defaultFS. We should use it as the storage path not the hadoop.tmp.dir as the storage path.
*(or)*
*(or)*
*(example:)*
=> [improve][offload] Use filesystemURI as the storage path

pulsar-broker/src/test/java/org/apache/pulsar/client/api/TokenAuthenticatedProducerConsumerTest.java
`TokenAuthenticatedProducerConsumerTest` cannot pass the test. The root cause is that when a namespace does not exist and the client carries a token without correct permission, the client would fail with `AuthorizationException` but not `TopicDoesNotExistException`.
It's because `PulsarAuthorizationProvider#validateTenantAdminAccess` will fail exceptionally by `NotFoundException` here: https://github.com/apache/pulsar/blob/0b0eef905c3a6ebe8a6fbb284743d98c8e97d5b8/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java#L718
However, when the namespace does not exist, this exception won't be thrown. If `testTopicNotFound` was running after `testTokenProducerAndConsumer`, the "my-property" tenant would be created so it would fail.
However, …
=> [fix][broker] Fix failed TokenAuthenticatedProducerConsumerTest

pip/pip-392.md
- Discuss thread: https://lists.apache.org/thread/scfj13jh167lyx16g2tkwg1rtj8dt7nv
- Vote thread: https://lists.apache.org/thread/vvytpb2tlovmdrkryyg09flqtv1k5dbr
- Draft PR: https://github.com/apache/pulsar/pull/23584
=> [improve][pip] PIP-392: Enable consistent hashing to select active consumer in partitioned topic for failover subscription

conf/broker.conf, conf/standalone.conf, deployment/terraform-ansible/templates/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicsConsumerImplTest.java
#23583 
- Only use mod when topic is partitionedTopic and activeConsumerFailoverConsistentHashing=false.
- Add `testPartitionedTopicDistribution` to cover it
=> [improve][broker] PIP-392: Add configuration to enable consistent hashing to select active consumer for partitioned topic

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/AutoScaledReceiverQueueSizeTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Fixes https://github.com/apache/pulsar/issues/23622
After testing for autoScaledReceiverQueueSizeEnabled config, found that the client memory usage and incomingMessageSize is negative.
This error result in two problem:
1. autoScaledReceiverQueueSize feature is not correct. The receive queue size is expanded based on wrong memory usage.
2. batchReceivePolicy feature is not correct. The MaxNumBytes config in batchReceivePolicy is judged by wrong incomingMessageSize.
By the way, batchReceivePolicy is default used in multiTopicConsumer since pulsar-2.9.4, while autoScaledReceiverQueueSize is a  optional config in consumer.
The reason is because when enter ConsumerImpl#notifyPendingReceivedCallback, the message would directly pass to pendingReceive request. Then consumerImpl just decrease the …
=> [fix][client] fix incomingMessageSize and client memory usage is negative

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/InMemoryDeliveryTrackerTest.java
Delayed queue consume a lot of memory to store the message id. We can reduce the memory occupation with new data structure simillar to https://github.com/apache/pulsar/pull/23601.
Use new data structure to reduce memory occupation of the delayed message queue, `InMemoryDelayedDeliveryTracker`.
List some experiment data with following test code:
```
static long trimLowerBit(long timestamp, int bits) {
return timestamp & (-1L << bits);
}
public static void main(String[] args) throws IOException {
TripleLongPriorityQueue queue = new TripleLongPriorityQueue();
Long2ObjectSortedMap<Long2ObjectMap<Roaring64Bitmap>> map2 = new Long2ObjectAVLTreeMap<>();
long numMessages = 10000000, numLedgers=1000;
long numEntries = numMessages/numLedgers;
long ledgerId, entryId, partitionIndex, …
```
=> [improve][broker] Reduce memory occupation of the delayed message queue

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/util/NameUtil.java
Main Issue:  https://github.com/apache/pulsar-client-go/issues/1297
Relative #21890 
When multiple consumers with same name are using dlq policies at the same time, prompt will throw below exceptions:
`
ERRO[0069] Failed to create DLQ producer  dlq-topic="persistent://<tenant>/<namespace>/<topic>-<subscription>-DLQ" error="server error: ProducerBusy: org.apache.pulsar.broker.service.BrokerServiceException$NamingException: Producer with name '-<subscription>-<consumerName>-DLQ' is already connected to topic"
`
I think maybe we need to add a random suffix in dlq producer name like: `opt.Name = fmt.Sprintf("%s-%s-%s-%s-DLQ", r.topicName, r.subscriptionName, r.consumerName, generateRandomName()) `
This change is already covered by existing tests, such as …
=> [fix][client] Fix DLQ producer name conflicts when there are same name consumers

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java
OneWayReplicatorUsingGlobalZKTest.testRemoveCluster was timing out in branch-3.3 and I had to improve the test in order to get the test passing in branch-3.3 before 3.3.3 release.
- Add `ignoreExceptions()` to Awaitility
- Add 5 second timeout to existence checks of topics
=> [improve][test] Reduce OneWayReplicatorUsingGlobalZKTest.testRemoveCluster execution time

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationDataSubscription.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationDataSubscriptionTest.java
I realized that http header data interface is missing in AuthenticationDataSubscription.
It appears that websocket consumer authorization fails because authorization providers cannot pull the authorization header from AuthenticationDataSubscription.
added http data interface in AuthenticationDataSubscription
=> [fix][ws] Implement missing http header data functions in AuthenticationDataSubscription

jetcd-core-shaded/pom.xml
In the latest release candidates (`3.0.8-candidate-1`, `4.0.1-candidate-1`), the jetcd-core-shaded module [shading issue][1] persists. This occurs because the `maven-shade-plugin` [includes][4] the current project artifact in the shade process. In `jetcd-core-shaded`, we copy `io.etcd.jetcd.*` into the `jetcd-core-shaded` jar without relocation. As a result, when the `install` or `deploy` goals are executed without cleaning the `target` folder, class conflicts arise between `io.etcd.jetcd.*` inside `org.apache.pulsar:jetcd-core-shaded.jar` and `io.etcd:jetcd-core.jar`.
[1]: https://github.com/apache/pulsar/issues/23513#issuecomment-2469496334
#23604 attempted to resolve this issue but failed to account for [build][2] and [deploy][3] in separate steps during the release process. 
[2]: …
=> [fix][misc] Class conflict during jetcd-core-shaded shading process

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java
Currently, there are user applications that want to load client configurations dynamically from a config file and create PulsarClient by passing that dynamically created ClientConfigurationData. In that case, the Pulsar client doesn't initialize authentication with provided auth parameters and authPluginClass into ClientConfigurationData, so user applications are not able to configure authentication correctly.
Therefore, PulsarClient should initialize authentication based on provided auth configuration (param and auth-class) and use it for server connection.
Pulsar client lib can initialize authentication using configured auth-param and class into client-configuration. …
=> [fix][client] Initializing client-authentication using configured auth params

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/InMemoryRedeliveryTracker.java
Reduce memory occupation of the `InMemoryRedeliveryTracker`.
Use `Long2ObjectMap<Long2IntMap>` to replace `ConcurrentLongLongPairHashMap`.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/66
=> [improve][broker] Reduce memory occupation of InMemoryRedeliveryTracker.

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java
**Issue**
- Brokers acquire namespace-bundle locks with the data `OwnershipCache.selfOwnerInfo`
- The initialization of the `OwnershipCache.selfOwnerInfo` is in the method `PulsarService.start()` as bellow
- call `startNamespaceService()`: this line created the object `OwnershipCache`, but the variable `OwnershipCache.selfOwnerInfo` will be set an empty value due to `PulsarService.brokerServiceUrl` has not been initialized yet.
- Initialize `PulsarService.brokerServiceUrl`.
- start leader election service and load manager, at this moment the variable `OwnershipCache.selfOwnerInfo` is still empty, so the client may get a null response
- call `nsService.initialize()`: reset the variable of `OwnershipCache.selfOwnerInfo`.
**Error logs**
```
2024-11-26T12:47:27,323+0000 [pulsar-io-6-2] WARN …
```
=> [fix][broker] fix null lookup result when brokers are starting

build/run_unit_group.sh, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGeneratorWithNoUnsafeTest.java
---
We have met some core dumps when running pulsar service. Then saw Netty suggested using `io.netty.noUnsafe` to see if it works. https://github.com/netty/netty/issues/2950. After adding that property, the core dump is gone, but the metrics failed to report because of the UnsupportedOpeartion exception.
Netty has a property io.netty.noUnsafe which allows disabling use the unsafe api. When this is enabled, the metrics won't collect because of the Unspport operation exception.
The root cause is it calls the internalNioBuffer which only allow to call when the buffer count is 1. But when using the composite buffer the buffer count may more than 1.
So use the buffer directly when the flag is enabled.
The exception:
Caused by: java.lang.UnsupportedOperationException
at …
=> [improve] Use single buffer for metrics when noUnsafe use

pip/pip-389.md
The motivation of this PIP is to provide a way to improve the compression performance by skipping the compression of small messages.
We want to add a new configuration `compressMinMsgBodySize` to the producer configuration.
This configuration will allow the user to set the minimum size of the message body that will be compressed. 
If the message body size is less than the `compressMinMsgBodySize`, the message will not be compressed.
*(or)*
*(or)*
*(example:)* …
=> [improve][pip] PIP-389: Add Producer config compressMinMsgBodySize to improve compression performance

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SystemTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
#21709 introduced a valuable metric: pulsar_storage_backlog_age_seconds, but it only updates when a topic has the message_age backlog quota policy.
- Decouple pulsar_storage_backlog_age_seconds metric from backlogQuota policy
- For now, the `backlogQuotaChecker` is also used to periodically update the `pulsar_storage_backlog_age_seconds` metric, regardless of whether the topic has a backlog quota policy.
- Add `backlogsAgeMetricsNoPreciseWithoutBacklogQuota` and `backlogsAgeMetricsPreciseWithoutBacklogQuota` to cover this change.
=> [improve][broker] Decouple pulsar_storage_backlog_age_seconds metric with backlogQuota check

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/OxiaMetadataStore.java
- oxia-java 0.4.10 switches from javax.annotation to jakarta.annotation
- OxiaMetadataStore close isn't properly changing the state to closed
- upgrade to oxia-java 0.4.10
- fix OxiaMetadataStore.close
=> [improve] Upgrade oxia-java to 0.4.10 and fix closing of OxiaMetadataStore

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessagesImpl.java
Revert this patch #21924, as it has been fixed by https://github.com/apache/pulsar/pull/14139.
And this will involve many confused logs.
=> [fix][broker] Revert "[improve][client] Add log when can't add message to the container

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/BrokerOpenTelemetryTestUtil.java, pulsar-broker/src/test/java/org/apache/pulsar/client/metrics/ClientMetricsTest.java
OpenTelemetry library is improving and it's useful to use a recent version to get the improvements in Pulsar too.
Upgrade OpenTelemetry library from 1.41.0 to 1.44.1 version
=> [improve] Upgrade OpenTelemetry library to 1.44.1 version

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TenantEndpointsAuthorizationTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TenantOperation.java
Support missing tenant-level fine-granted permissions.
- Add missing tenant-level operations
- Keep compatibility for existing superuser validation.
=> [fix][broker] support missing tenant level fine-granted permissions

pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
When `retryLetterProducer` creation fails, `retryLetterProducer` will be set to null. So `retryLetterProducer==null `may occur when race-condition is present, at this time, the results cannot be completed.
Only handle the situation when retryLetterProducer is not equal to null:
https://github.com/apache/pulsar/blob/3f12269d8d99e514cf48ef6d57fc3928d37b3646/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L678
When `retryLetterProducer==null`, mark the result as an completeExceptionally.
=> [fix][client] Fix race-condition causing doReconsumeLater to hang when creating retryLetterProducer has failed

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java
When `allowAutoSubscriptionCreation` is set to `false` on broker, creating a consumer for a subscription that does not exist does not throw a `SubscriptionNotFoundException`. Instead, it throws a `PulsarClientException`. This behavior complicates determining whether the subscription exists, requiring users to perform checks like `getRootCause(e).getMessage().matches(".*Subscription .*does not exist.*")` before #22164. Even after #22164, while the root cause becomes `SubscriptionNotFoundException`, additional handling is still necessary.
```java
try {
Consumer<byte[]> consumer = pulsarClient.newConsumer()
.topic("public/default/subscription-auto-creation-disabled")
.subscriptionName("test")
.subscriptionType(SubscriptionType.Exclusive)
.subscribe();
} catch …
```
=> [improve][client] Enhance error handling for non-exist subscription in consumer creation

docker/pulsar/Dockerfile
Resolves apache/pulsar-helm-chart#554
- the timeout command provided by default busybox implementation in Alpine leaves zombie processes
- see apache/pulsar-helm-chart#554 for details
- add `coreutils` package to the docker image. The size of `coreutils` is small, only about 1MB.
=> [improve] Install coreutils in docker image to improve compatibility

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
Fixes #xyz
PIP: #xyz 
When getting topic stats, the consumer name is missing in each subscription's consumer information
With this change, the topic stats will show consumer name
```
"abortedTxnCount" : 0,
"committedTxnCount" : 0,
"publishers" : [ ],
"waitingPublishers" : 0,
"subscriptions" : {
"test_sub_v1" : {
"msgRateOut" : 303.3964745694218,
"msgThroughputOut" : 14215.002259022087,
"bytesOutCounter" : 140137,
"msgOutCounter" : 2991,
"msgRateRedeliver" : 0.0,
"messageAckRate" : 0.0,
"chunkedMessageRate" : 0.0,
"msgBacklog" : 7183,
"backlogSize" : 75322327,
"earliestMsgPublishTimeInBacklog" : 0,
"msgBacklogNoDelayed" : 7183,
"blockedSubscriptionOnUnackedMsgs" : false,
"msgDelayed" : 0,
"msgInReplay" : 0,
"unackedMessages" : 0,
"type" : "Failover",
"activeConsumerName" : …
```
=> [fix] [broker] Add consumer name for subscription stats

pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/BrokerInterceptorWithClassLoader.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java, tests/docker-images/java-test-plugins/src/main/java/org/apache/pulsar/tests/integration/plugins/LoggingBrokerInterceptor.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/plugins/TestBrokerInterceptors.java
Fixes #23670
PIP: #xyz 
The `BrokerInterceptor` interface has a `onFilter` method, but it is never invoked
- *TestBrokerInterceptors.java#test*
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/36
=> [fix][broker] Invoke custom BrokerInterceptor's `onFilter` method if it's defined

pip/pip-393.md
PIP: 393
Implementation PR: https://github.com/apache/pulsar/pull/23600.
There are many issues with the current implementation of Negative Acknowledgement in Pulsar:
- the memory occupation is high.
- the code execution efficiency is low.
- the redelivery time is not accurate.
- multiple negative ack for messages in the same entry(batch) will interfere with each other.
All of these problem is severe and need to be solved.
Refactor the `NegativeAcksTracker` to solve the above problems.
I will show you how great the new data structure it is with theorectical space complexity analysis.
Before analyzing the new data structure, we need to know how much space it take before this pip. We need to store 4 long field for `(ledgerId, entryId, partitionIndex, timestamp)` for each entry, which takes …
=> [improve][pip] PIP-393: Improve performance of Negative Acknowledgement

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Fixes #xyz
PIP: #xyz 
When using this command `bin/pulsar-admin topics set-retention -s 20g -t 200d persistent://public/default/test_v1` to set a retention policy for a topic, it failed with following exception
```
PicocliException: Could not set value for field private java.lang.Integer org.apache.pulsar.admin.cli.CmdTopics$SetRetention.retentionTimeInSec to 17280000 while processing argument at or before arg[5] '200d' in [topics, set-retention, -s, 20g, -t, 200d, persistent://public/default/test_v1]: picocli.CommandLine$PicocliException: Could not set value for field private java.lang.Integer org.apache.pulsar.admin.cli.CmdTopics$SetRetention.retentionTimeInSec to 17280000
Usage: pulsar-admin topics set-retention [-hv] -s=<sizeLimit>
-t=<retentionTimeInSec> <topicName> …
```
=> [fix][cli] Fix set topic retention policy failed

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Fixes security risk
Dependency common-io, shaded in pulsar-client, is susceptable to a reDos attack prior to version 2.15.0 
Bump commons-io version to 2.18.0
PR in forked repository: https://github.com/ZachChuba/pulsar/pull/2
CI only failed at upload stages
=> [fix][sec] Bump commons-io version to 2.18.0

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/CmdTopicPoliciesTest.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdTopics.java
Fixes a similar issue as #22150, for `pulsar-admin topics set-retention` and `pulsar-admin topicPolicies set-retention` commands. Related to #23688. This adds a test to #23688 changes.
The impact of this bug is that when the value overflows when it's over 2GB. The effective value becomes negative or 0, which disables retention. There won't be a failure. For example, with the parameter `-s 3G`, the value becomes `-1024`. With any value more than 4GB, the value becomes `0`.
- use long value instead of integer
- add tests which also cover #23688 change
=> [fix][cli] Fix set-retention with >2GB size value for topic policy

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/MangedLedgerInterceptorImplTest.java
Currently, the entry payload interceptor processor doesn't catch exceptions, the exception will be swallowed by the executor task.
Catch exception for entry payload interceptor processor.
Add a test for catching exceptions from the payload input interceptor processor.
=> [fix][broker] Catch exception for entry payload interceptor processor

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/TopicEventsListenerTest.java
I have a broker interceptor, which will add a topic event listener to listen the topic creation in the `org.apache.pulsar.broker.intercept.BrokerInterceptor#initialize`. However, the partitioned topic creation event can not be recorded(`bin/pulsar-admin topics create-partitioned-topic -p 3 test-topic-event`).
```java
pulsar.getBrokerService().addTopicEventListener((topic, event, stage, t) -> {
log.info("got event {}__{} for topic {}", event, stage, topic);
});
```
The non-partitioned topic works fine. 
- Call `topicEventsDispatcher` with the `TopicEvent.CREATE` and `EventStage.BEFORE` before creating the persistent/non-persistent partitioned topic.
- Call `topicEventsDispatcher` with the `TopicEvent.CREATE` and `EventStage.SUCCESS/FAILURE`  after the persistent/non-persistent partitioned …
=> [fix][admin] Listen partitioned topic creation event

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
In some cases users would like to be able to set permissions to topics that have not yet been created, for instance if a topic is going to be created lazily at a later time.
This change introduces a new configuration property for the broker to allow changing to that behaviour.
```
```
=> [improve][admin] Opt-out of topic-existence check

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerStatsRecorderImpl.java
Print consumer stats log if prefetched messages are not zero to help users know that the consumer just stop consuming messages from the receiver queue. Now, we only print the stats log if there is receive or ack throughput on the consumer.
=> [improve][client] Print consumer stats log if prefetched messages are not zero

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java
```java
@FieldContext(
category = CATEGORY_SERVER,
dynamic = true,
doc = "The position that replication task start at, it can be set to earliest or latest (default).")
private String replicationStartAt = "latest";
```
The value of the config named `replicationStartAt` are `earliest` or `latest`, but both implementation and test used `MessageId.earliest.toString()` that value is `-1:-1:-1`( so the test works as expected). 
Therefore, setting `replicationStartAt` to `earliest` does not work.
- Fix the incorrect implementation and keep compatibility with the previous version.
=> [fix] [broker] Fix config replicationStartAt does not work when set it to earliest

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageChunkingTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
When a reader's start message id is a chunked message id, this chunked message will be read even if `startMessageIdInclusive()` is not configured.
Only use `getFirstChunkMessageId` as the start message id when `startMessageIdInclusive()` is configured. Improve the `testSeekChunkMessages` to verify it.
=> [fix][client] Fix wrong start message id when it's a chunked message id

pulsar-broker-auth-oidc/src/main/java/org/apache/pulsar/broker/authentication/oidc/AuthenticationProviderOpenID.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ControlledClusterFailover.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpClient.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/auth/oauth2/protocol/TokenClient.java
See CVE-2024-53990. There aren't backend services in Pulsar that would use cookies, however since it's a high severity vulnerability, there's a need to mitigate it. Eventually we will need to upgrade to AsyncHttpClient 3.0.1 to get rid of the vulnerable dependency AsyncHttpClient 2.12.x.
- As a mitigation, disable CookieStore by setting it to null 
- This PR doesn't upgrade to AsyncHttpClient 3.0.1
- Upgrading to AsyncHttpClient 3.0.1 will be more work. It will be handled separately.
=> [fix][sec] Mitigate CVE-2024-53990 by disabling AsyncHttpClient CookieStore

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/BaseResources.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/Backoff.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/BackoffTest.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataCacheConfig.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/cache/impl/MetadataCacheImpl.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java
The method `MetadataCache#readModifyUpdateOrCreate` should handle the BadVersionException by retrying the modification process, as already noted in the Java documentation: "The modify function can potentially be called multiple times due to concurrent updates."
Currently, `MetadataCache#readModifyUpdateOrCreate` does not catch the BadVersionException on the second attempt, allowing the exception to be passed to the caller. This issue can be easily reproduced by increasing concurrent futures in the test `MetadataCacheTest#readModifyUpdateBadVersionRetry`.
The current retry implementation is incorrect and lacks a backoff mechanism, which could lead to too many requests to the metadata store.
- Correct the retry process in `MetadataCache#readModifyUpdateOrCreate` to ensure …
=> [fix][broker] Fix the retry mechanism in `MetadataCache#readModifyUpdateOrCreate`

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxNonInjectionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ClientCnxTest.java
https://github.com/apache/pulsar/pull/23038 changed the behavior of the PulsarClient in handling SendErrors.
Add more tests for the change
- Create producers with a customized name, to confirm users will not get the error `Producer with the same id is already created`
- Create a pulsar client with  a value that does not equal `1`, to confirm users will not get the error `Producer with the same id is already created`
=> [improve] [test] Add more test for the case that client receives a SendError, which relates to the PR #23038

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-broker/pom.xml, pulsar-client-admin-shaded/pom.xml, pulsar-client-admin/pom.xml, pulsar-client-all/pom.xml, pulsar-client-shaded/pom.xml, pulsar-proxy/pom.xml, tiered-storage/jcloud/pom.xml
Upgrade to async-http-client 2.12.4 which contains a fix for CVE-2024-53990. See https://lists.apache.org/thread/fpg465pxytqkxbs57h7p3mckn9dwh3zq for more details.
- Upgrade async-http-client from 2.12.1 to 2.12.4
- [Changes since 2.12.1](https://github.com/AsyncHttpClient/async-http-client/compare/async-http-client-project-2.12.1...6afba08)
- Adapt to https://github.com/AsyncHttpClient/async-http-client/commit/ac2d4bdf46abf96aeb5a61d56bc5718ac005184a change
- Replace `com.sun.activation:javax.activation` with `com.sun.activation:jakarta.activation`
=> [fix][sec] Upgrade async-http-client to 2.12.4 to address CVE-2024-53990

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Fixes https://github.com/apache/pulsar/issues/23715
see https://github.com/apache/pulsar/issues/23715
*(or)*
*(or)*
*(example:)*
=> [fix][admin] Verify is policies read only before revoke permissions on topic

pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java, pulsar-common/src/test/java/org/apache/pulsar/common/naming/TopicNameTest.java
Fixes #23690
When creating a consumer with the topic name only being a whitespace we get:
> java.lang.IllegalArgumentException: topicNames cannot have blank topic
That's why I expect `TopicName.get(" ")` to throw an exception too.
Throw exception if `localName` is blank.
- Added a test with " " as the topic name.
PR in forked repository: https://github.com/pdolif/pulsar/pull/5
=> [fix][common] TopicName: Throw IllegalArgumentException if localName is whitespace only

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaExecutionResult.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstance.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceTest.java
When using asynchronous functions in Pulsar Functions, concurrency needs to be limited to prevent unbounded resource consumption. This is currently handled by the `maxPendingAsyncRequests` configuration parameter (default value: 1000). Without such limits, asynchronous processing could lead to unbounded message consumption from input topics, potentially causing resource exhaustion (out-of-memory errors) and function crashes.
However, the current implementation has a performance issue specifically for asynchronous functions that return `CompletableFuture<Void>`. In these cases, the current queue-based implementation introduces unnecessary processing delays when the concurrency limit is reached. In particular:
1. When there's a slow response at the head of the queue, request processing gets …
=> [improve][fn] Improve implementation for maxPendingAsyncRequests async concurrency limit when return type is CompletableFuture<Void>

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ProducerCache.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ProducerCacheTest.java
- The log messages are verbose when `PulsarClientException.AlreadyClosedException` is returned from `closeAsync`. 
- Don't log the AlreadyClosedException stack trace
- There are concerns that producers could be left in the cache in exceptional cases. Therefore add handling to handle possible runtime exceptions in `flushAsync` and `closeAsync` calls.
- improve ProducerCache logic
- add tests
=> [improve][fn] Improve closing of producers in Pulsar Functions ProducerCache invalidation

pom.xml
Keep up-to-date. 
Change log: https://projectlombok.org/changelog
Using the 1.18.36 can avoid the following error when using the idea runs the tests directly:
```
java: Lombok annotation handler class lombok.javac.handlers.HandleToString failed on repo/pulsar/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java: java.lang.StackOverflowError
```
- Upgrade lombok from 1.18.32 to 1.18.36.
=> [improve] Upgrade lombok to 1.18.36

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/LedgerMetadataUtils.java
Modify the typo in the buildMetadataForCompactedLedger class
Correct the spelling of messageId
=> [fix][broker] Fix typo in `buildMetadataForCompactedLedger`

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Upgrade OpenTelemetry (OTel) libraries so that we stay up-to-date.
- upgrade OTel to 1.45.0 and use other compatible libraries
=> [improve][monitor] Upgrade OTel to 1.45.0

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerImplTest.java
In the current process of closeAsync() in ProducerImpl.java, the client will firstly set the producer to the Closing state, then stop timerTask of sendTimeout, and then send a http request to broker to close the producer. When the client receives a successful response from broker, it sets the producer to the Closed state, removes the producer from the producers in client, and complete the PendingMessage with AlreadyClosedException.
However, if the communication between client and broker is abnormal due to network or other reasons, the PendingMessage will not be cleared anymore. What's worse is that since the producer is already in the Closing state at this time, there is no chance to trigger the cleanup of PendingMessage by calling the closeAsync() again, which is obviously unreasonable. …
=> [Fix][Client] Fix pending message not complete when closeAsync

pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionTest.java
Fixes #23746
KeySharedSubscriptionTest.testNoKeySendAndReceiveWithHashRangeAutoSplitStickyKeyConsumerSelector is flaky.
Increase the number of messages sent during the test from 100 to 300.
PR in forked repository: https://github.com/pdolif/pulsar/pull/6
=> [fix][test] Fix flaky KeySharedSubscriptionTest.testNoKeySendAndReceiveWithHashRangeAutoSplitStickyKeyConsumerSelector

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundles.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/LocalPolicies.java
https://github.com/apache/pulsar/pull/21367 introduced the `migrated` field in `localPolicies` to indicate whether the topics under a namespace have been migrated in the blue-green cluster migration feature.
In https://github.com/apache/pulsar/pull/9598, it is specified that when updating the field content of `localPolicies`, a new object needs to be created instead of updating the original object.
After the addition of the `migrated` field in https://github.com/apache/pulsar/pull/21367, there has been no synchronization of modifications in other places that update `localPolicies`. This could lead to the loss of the `migrated` content during other operations on `localPolicies`, such as setting the `namespaceAntiAffinityGroup`, etc.
1. Synchronize the `migrated` content in the places where …
=> [fix][broker] Fix bug causing loss of migrated information when setting other localPolicies in namespace

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SubscriptionOption.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/ReplicateSubscriptionTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationData.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerBuilderImplTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
The current implementation of subscription replication relies on consumer control with the following configuration:
```java
boolean replicateSubscriptionState = false;
// boolean replicateSubscriptionState = true;
pulsarClient.newConsumer(Schema.STRING)
.replicateSubscriptionState(replicateSubscriptionState)
```
By default, the `replicateSubscriptionState` is set to `false` in the `ConsumerConfigurationData.java`, which creates a mismatch with the `CommandSubscribe` definition, where `replicate_subscription_state` is optional. To address this, I propose changing the default value of `replicateSubscriptionState` to `null`, aligning it with the optional nature of the field in `CommandSubscribe`.
This adjustment would enhance flexibility in managing subscription replication policies, such as …
=> [improve][client] Make replicateSubscriptionState nullable

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java
Fixes #23765
#23765 demonstrated how to reproduce the TimeoutException bug and explained the potential issue. Therefore, this PR aims to fix this problem.
1. The exception is returned via completeExceptionally instead of being thrown directly.
2. A new test case is added to testGetMessageById to verify the effect of the fix.
- Added test in
org/apache/pulsar/broker/admin/PersistentTopicsTest.java#testGetMessageById
=> [fix][admin] Fix exception loss in getMessageId method

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Fixes https://github.com/apache/pulsar/issues/23572
If the topic is a system topic, then we should not migrate it during the blue-green cluster migration
If the topic is a system topic, then we should not migrate it during the blue-green cluster migration
PR in forked repository: https://github.com/hrzzzz/pulsar/pull/14
=> [fix][broker] System topic should not be migrated during blue-green cluster migration

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/DeadLetterPolicy.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/KeySharedPolicy.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Range.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationData.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ReaderConfigurationData.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationDataTest.java
Fixes #23704 
We use the pulsar client to consume messages from a Pulsar broker in a Storm topology. Recently, we encountered an issue where the `deadLetterPolicy` that we set on the `PulsarSpout` seems to be lost when the topology is started. Upon investigation, we found that this is due to the `deadLetterPolicy` attribute in `ConsumerConfigurationData` being marked as transient. This prevents us from utilising the dead letter queue feature in our topology.
Made DeadLetterPolicy, KeySharedPolicy and Range classes implement the java.io.Serializable interface and removed the transient keyword from the corresponding fields in the ConsumerConfigurationData class. In addition, two tests were also modified / updated.
- Extended existing …
=> [fix][client] Make DeadLetterPolicy & KeySharedPolicy serializable

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java, testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockBookKeeper.java
**Background**
There is a mechanism that repeatedly prevents the callback of ML data ledger creation:
- Start a scheduled task to check whether the creation will be timeout.
- Received a callback
- Check whether the future(`@param ctx` of `BK.createAsync`) has been done or not.
- If done: it means the creation has timeout before the creation is completed
- Otherwise: it is a real callback from BK.
**Issue:**
But the timeout event will call the same callback as above, then the steps are as follows, which you ca reproduce by the test `testCreateDataLedgerTimeout`:
- Start creating a data ledger
- Call `BK.createAsync` 
- Timeout
- Mark the future(`@param ctx` of `BK.createAsync`) as completed exceptionally. 
- Trigger the callback related to ledger creation. 
- Check whether the …
=> [fix][ml] Topic load timeout due to ml data ledger future never finishes

tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloader.java
Optimize `BlobStoreManagedLedgerOffloader.getOffloadPolicies()`
*(or)*
*(or)*
*(example:)*
=> [improve][ml] Optimize BlobStoreManagedLedgerOffloader.getOffloadPolicies

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/EnableReplicatedSubscriptionsIsDisabledTest.java
https://github.com/apache/pulsar/pull/23757 breaks `enableReplicatedSubscriptions` config.
When `enableReplicatedSubscriptions=false`, disable the subscription replication.
=> [fix][broker] Fix enableReplicatedSubscriptions

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/batching/MetadataOp.java
**Improvement 1**
```
java.io.IOException: Len error. A message from /127.0.0.6:43889 with advertised length of 17890775 is either a malformed message or too large to process (length is greater than jute.maxbuffer=10485760)
at org.apache.zookeeper.server.NIOServerCnxn.readLength(NIOServerCnxn.java:567) ~[org.apache.zookeeper-zookeeper-3.9.2.jar:3.9.2]
at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:352) ~[org.apache.zookeeper-zookeeper-3.9.2.jar:3.9.2]
at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:508) ~[org.apache.zookeeper-zookeeper-3.9.2.jar:3.9.2]
at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:153) ~[org.apache.zookeeper-zookeeper-3.9.2.jar:3.9.2]
at …
```
=> [improve][log] Print ZK path if write to ZK fails due to data being too large to persist

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
```
Found one Java-level deadlock:
=============================
"metadata-store-10-1":
waiting to lock monitor 0x00007fb363ef6a60 (object 0x00000000bf8b3b88, a java.util.concurrent.ConcurrentHashMap$Node),
which is held by "broker-client-shared-internal-executor-5-1"
"broker-client-shared-internal-executor-5-1":
waiting to lock monitor 0x00007fb36617a5b0 (object 0x00000000bdf00940, a java.util.concurrent.ConcurrentHashMap$ReservationNode),
which is held by "pulsar-io-3-6"
"pulsar-io-3-6":
waiting to lock monitor 0x00007fb363ef6a60 (object 0x00000000bf8b3b88, a java.util.concurrent.ConcurrentHashMap$Node),
which is held by "broker-client-shared-internal-executor-5-1"
Java stack information for the threads listed above:
=================================================== …
```
=> [fix][broker] topic policy deadlock block metadata thread.

pulsar-broker/src/test/java/org/apache/pulsar/client/api/InterceptorsTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
In #22393, the payload of message get released before calling `ProducerInterceptor#onSendAcknowledgement`, hence access message data inside `ProducerInterceptor#onSendAcknowledgement` will get exception below:
```
io.netty.util.IllegalReferenceCountException: refCnt: 0
at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454) ~[netty-buffer-4.1.115.Final.jar:4.1.115.Final]
at io.netty.buffer.UnpooledHeapByteBuf.array(UnpooledHeapByteBuf.java:147) ~[netty-buffer-4.1.115.Final.jar:4.1.115.Final]
at org.apache.pulsar.client.impl.MessageImpl.getData(MessageImpl.java:371) ~[classes/:?]
at org.apache.pulsar.client.api.InterceptorsTest$6.onSendAcknowledgement(InterceptorsTest.java:239) ~[test-classes/:?]
at org.apache.pulsar.client.api.interceptor.ProducerInterceptorWrapper.o …
```
=> [fix][client] Cannot access message data inside ProducerInterceptor#onSendAcknowledgement

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentSubscriptionTest.java
Strictly verify `pulsar.replicated.subscription` value.
Enable the subscription replication when only the value  `pulsar.replicated.subscription` is `1L`.
=> [fix][broker] Fix pulsar.replicated.subscription checks

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
We encountered an issue as follows
| time | `closing topic -> closing curosr` | `in-progress cursor mark deleting` |
| 1 | Mark the cursor as closing |
| 2 | Persistent cursor metadata into the cursor ledger `54781383` |
| 3 | Start to close the cursor ledger `54781383` |
| 4 | Mark the ledger `54781383` is closed in memory |
| 5 | | Try to write metadata to the ledger `54781383`, but the ledger was marked closed |
| 6 | | Try to write metadata to ZK after failed writing BK |
| 7 | Start to write the ledger metadata of `54781383` to ZK |
| 8 | | The ZK server closed the connection due to the pulsar trying to write a large value |
| 9 | Write to ZK failed due to the connection being lost | |
| 10 | | retries and keeps triggering a closing of the ZK connection |
| 11 | …
=> [fix][broker] Skip to persist cursor info if it failed by cursor closed

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderList.java, pulsar-broker-common/src/test/java/org/apache/pulsar/broker/authentication/AuthenticationProviderListTest.java
When using Pulsar admin version 2.10.x with JWT authentication and a broker running 3.0.x (forked from Apache Pulsar) configured with both Kerberos and JWT authentication providers, we encounter the following issue:
```
ERROR org.apache.pulsar.broker.web.AuthenticationFilter - [172.19.0.17] Error performing authentication for HTTP
2024-12-30 09:52:32 java.lang.IllegalStateException: Header token should exist if no role token.
2024-12-30 09:52:32     at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[com.google.guava-guava-32.1.1-jre.jar:?]
2024-12-30 09:52:32     at org.apache.pulsar.broker.authentication.AuthenticationProviderSasl.authenticateHttpRequest(AuthenticationProviderSasl.java:275) ~[com.ascentstream.pulsar-pulsar-broker-auth-sasl-3.0.8.1.jar:3.0.8.1] …
```
=> [fix][broker] Continue using the next provider for authentication if one fails

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceAutoTopicCreationTest.java
Topic name rule
- old version: {tenant}/{cluster}/{namespace}/{topic}
- new version: {tenant}/{namespace}/{topic}
If the name of an automatically created topic contains a "/", the topic will be resolved into a four-segment format (containing a layer of cluster directories). As a result, the automatically created topic does not conform to the latest topic naming rules
No allowto automatically create topic names that contain slashes
=> [feat][broker] Prevent auto-creation of topics using legacy cluster-based naming scheme

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersClassic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersClassicTest.java
Version: `3.0.7`, thanks for @shibd investigating the issue together and mentioning the key clue that items are out of order.
**Issue 1**: concurrentcy access a un-thread-safety collection
- The variable `recentlyJoinedConsumers` of `PersistentStickyKeyDispatcherMultipleConsumers` is used to guarantee the delivery order of Key_Shared subscriptions, which is not a thread-safety collection.
- Almost all operations that access this collection are in a lock block except in one place that the current PR fixes
**Issue 2**: the items in `recentlyJoinedConsumers` are out of order
- First node `104142:122103`
- ...
- middle node 1 `104142:122103`
- middle node 2 `104046:283984`
- ...
- tail node `104046:284275`
But we have more than one place that relies on the order rule, such as follows
- …
=> [fix] [broker] Msg delivery is stuck due to items in the collection recentlyJoinedConsumers are out-of-order

pulsar-broker/src/test/java/org/apache/pulsar/client/api/TlsProducerConsumerTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Authentication.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdConsume.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdProduce.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdRead.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpClient.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarChannelInitializer.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientInitializationTest.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/AdminProxyHandler.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyServiceTlsStarterTest.java, pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java
When the pulsar-admin CLI uses the kerberos authentication with tls transport, we encounter the following issue:
```
$ bin/pulsar-admin tenants list
2024-12-31T15:35:56,308+0800 [main] INFO  org.apache.pulsar.client.impl.auth.AuthenticationSasl - JAAS loginContext is: PulsarClient.
2024-12-31T15:35:56,455+0800 [main] INFO  org.apache.pulsar.common.sasl.JAASCredentialsContainer - successfully logged in.
2024-12-31T15:35:56,459+0800 [pulsar-tgt-refresh-thread] INFO  org.apache.pulsar.common.sasl.TGTRefreshThread - TGT refresh thread started.
2024-12-31T15:35:56,463+0800 [pulsar-tgt-refresh-thread] INFO  org.apache.pulsar.common.sasl.TGTRefreshThread - Client principal is "client/localhost@PULSAR.COM".
2024-12-31T15:35:56,463+0800 [pulsar-tgt-refresh-thread] INFO …
```
=> [fix][client] Fix compatibility between kerberos and tls

distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java, pulsar-client-admin-shaded/pom.xml, pulsar-client-all/pom.xml, pulsar-client-dependencies-minimized/pom.xml, pulsar-client-shaded/pom.xml, pulsar-client/pom.xml, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/NegativeAcksTracker.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationData.java
Implementation PR for PIP-393: https://github.com/apache/pulsar/pull/23601.
There are many issues with the current implementation of Negative Acknowledgement in Pulsar:
- the memory occupation is high.
- the code execution efficiency is low.
- the redelivery time is not accurate.
- multiple negative ack for messages in the same entry(batch) will interfere with each other.
All of these problem is severe and need to be solved.
After the improvement of https://github.com/apache/pulsar/pull/23582, we have reduce half more memory occupation
of `NegativeAcksTracker` by replacing `HashMap` with `ConcurrentLongLongPairHashMap`. With 100w entry, the memory occupation decrease from 178Mb to 64Mb. With 1kw entry, the memory occupation decrease from 1132Mb to 512Mb.
The average memory occupation of …
=> [improve][client] PIP-393: Improve performance of Negative Acknowledgement

pulsar-broker/src/test/java/org/apache/pulsar/client/api/TlsProducerConsumerTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Authentication.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdConsume.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdProduce.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdRead.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpClient.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarChannelInitializer.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/AdminProxyHandler.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyServiceTlsStarterTest.java, pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java
Cherry-pick https://github.com/apache/pulsar/pull/23798.
=> [fix][client][branch-3.0] Fix compatibility between kerberos and tls

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumersClassic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersClassic.java, pulsar-broker/src/test/java/org/apache/bookkeeper/mledger/impl/NonEntryCacheKeySharedSubscriptionV30Test.java
**Background**
- After all, consumers are off-line, the cursor will be triggered a `rewind`
- If there is a pending read is in-progress, the action `rewind` will be delayed after the pending read is complete. 
- The variable `dispatcher.recentlyJoinedConsumers` of `key_shared` mode guarantees delivery in order, it records the `cursor.readPosition` when consumers join.
**Issue**: a case that makes items in `dispatcher.recentlyJoinedConsumers` out-of-order, the steps to reproduce the issue are as follows:
- there are `3` consumers: `c1`, `c2`, `c3`
- `c1` and `c2` consumed all messages that they received.
- `c3` is stuck
- `LAC`: `3:299`, `cursor.readPosition`: `3:300`, `mard-deleted-position`: `3:100`
- The dispatcher will replay the messages that were sent to `c3` after `c3` is removed.
- …
=> [fix] [broker] Fix items in dispatcher.recentlyJoinedConsumers are out-of-order, which may cause a delivery stuck

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/TopicPoliciesSystemTopicClient.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicPolicyTestUtils.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/NamespaceEventsSystemTopicServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/PartitionedSystemTopicTest.java
Make the reader referenced by SystemTopicBasedTopicPoliciesService pooling messages to reduce GC pressure.
If `poolMessage=false` of the Reader, pulsar client will copy message payload into heap without pooling. 
Generally, it is not recommended  to users use the feature, because it requires call `message.release()` manually, or it will lead to mem leak.
However, in the broker side, we need this feature to improve JVM GC performance. 
Especially for there is a big number of topics served by a single broker.
1. Make `poolMessage=true` when SystemTopicBasedTopicPoliciesService component creating a reader
2. Call `message.release()` manually after process messages.
*(or)* …
=> [improve][broker] Improve SystemTopicBasedTopicPoliciesService reader to reduce GC pressure

pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/TransactionBufferSnapshotBaseSystemTopicClient.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SnapshotSegmentAbortedTxnProcessorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TableView.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/SegmentAbortedTxnProcessorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java
Make the reader referenced by TransactionBuffer pooling messages to reduce GC pressure.
If `poolMessage=false` of the Reader, pulsar client will copy message payload into heap without pooling. 
Generally, it is not recommended  to users use the feature, because it requires call `message.release()` manually, or it will lead to mem leak.
However, in the broker side, we need this feature to improve JVM GC performance. 
Especially for there is a big number of topics served by a single broker.
1. Make `poolMessage=true` when TopicTransactionBuffer component creating a reader
2. Call `message.release()` manually after process messages.
*(or)*
This change is already covered …
=> [improve][txn] Improve Reader in TransactionBuffer to reduce GC pressure

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java
Implementation PR for PIP-393: https://github.com/apache/pulsar/pull/23601.
PR https://github.com/apache/pulsar/pull/23600 has implemented most of the logic, but lack of support for configuring `NegativeAckPrecisionBitCnt` by mistake. 
Add support for configuring `NegativeAckPrecisionBitCnt` while building consumer.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/68
=> [improve][client] PIP-393: Support configuring NegativeAckPrecisionBitCnt while building consumer.

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ZkSessionExpireTest.java
See #23389.
ZkSessionExpireTest test is very flaky and blocks PRs and Pulsar CI.
Move ZkSessionExpireTest to flaky group so that a test failure doesn't block merging PRs.
=> [improve][ci] Move ZkSessionExpireTest to flaky group to unblock CI

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Netty 4.1.116.Final contains relevant bug fixes.
* [Netty 4.1.116.Final release notes](https://netty.io/news/2024/12/17/4-1-116-Final.html)
* There have been some reports of https://github.com/netty/netty/issues/14479 with Pulsar 4.0.1 / 3.3.3 release.
* This is fixed with https://github.com/netty/netty/pull/14480
Keep the optional Netty io_uring library up-to-date.
* [io_uring 0.0.26.Final release notes](https://netty.io/news/2024/12/27/io_uring_0-0-26-Final.html)
* [io_uring 0.0.25.Final release notes](https://netty.io/news/2024/02/19/io_uring_0-0-25-Final.html)
- Upgrade Netty to 4.1.116.Final
- Upgrade Netty io_uring to 0.0.26.Final
=> [improve] Upgrade to Netty 4.1.116.Final and io_uring to 0.0.26.Final

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java, pulsar-broker/src/test/java/org/apache/bookkeeper/mledger/impl/MangedLedgerInterceptorImpl2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImplTest.java
The [PR](https://github.com/apache/pulsar/pull/23683) cached the exceptions for entry payload interceptor processor, but the failed OpAddEntry wasn't removed from pendingAddEntries, this will cause the next write to fail.
Remove failed OpAddEntry from pendingAddEntries.
=> [fix][broker] Remove failed OpAddEntry from pendingAddEntries

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/InMemTransactionBuffer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TransactionBufferDisable.java
Cherry-picked #22707
Cherry-picked #22707
=> [improve][broker][branch-3.3] Optimize PersistentTopic.getLastDispatchablePosition (#22707)

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
The `metadata-store` thread is blocked in the Pulsar 3.0.x:
```
"metadata-store-11-1" #18 prio=5 os_prio=0 cpu=191.70ms elapsed=92.64s tid=0x00007fe149887e80 nid=0x3f39b waiting on condition  [0x00007fdedd3fd000]
java.lang.Thread.State: TIMED_WAITING (parking)
at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
- parking to wait for  <0x00001000270a2020> (a java.util.concurrent.CompletableFuture$Signaller)
at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.2/LockSupport.java:252)
at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.2/CompletableFuture.java:1866)
at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.2/ForkJoinPool.java:3463)
at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.2/ForkJoinPool.java:3434 …
```
=> [fix][broker] Remove blocking calls from internalGetPartitionedStats

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsController.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatedSubscriptionTest.java
Let's say two clusters to two-way replication: cluster-1 and cluster-2
- cluster-1: has enabled subscription replication and correctly configured the cluster info for `cluster-2` 
- cluster-2:has either incorrectly configured the information for `cluster-1` or disabled subscription replication.
As a result, `cluster-1` will send **SNAPSHOT_REQUEST** to `cluster-2` at a frequency of `replicatedSubscriptionsSnapshotFrequencyMillis` (1 second by default). 
In extreme cases, this can lead to a large number of consecutive `marker` between `cluster-1` and `cluster-2` topic.
This may affect the performance of `reader` and `consumer`, or cause `reader.readNext()` to time out.
- When there is no complete snapshot, retry according to replicatedSubscriptionsSnapshotTimeoutSeconds to minimize the …
=> [improve][broker] Reduce unnecessary REPLICATED_SUBSCRIPTION_SNAPSHOT_REQUEST

pip/pip-399.md
PIP 399 document.
Implementation: https://github.com/apache/pulsar/pull/23712
=> [fix][pip] PIP-399: Fix Metric Name for Delayed Queue

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConsumerAckTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java
Repeated calls to acknowledgeCumulativeAsync will block, when `AckReceipt` is enabled.
Request only sent when MessageID increases. 
Therefore, `CompletableFuture` returned by `PersistentAcknowledgmentsGroupingTracker` will not be completed.
PR in forked repository: https://github.com/315157973/pulsar/pull/16
=> [fix] [broker] Fix acknowledgeCumulativeAsync block when ackReceipt is enabled

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/AuthenticationServiceTest.java
When using Pulsar admin version 2.10.x with JWT authentication and a broker running 3.0.x (forked from Apache Pulsar) configured with both Kerberos and JWT authentication providers, we encounter the following issue:
```
ERROR org.apache.pulsar.broker.web.AuthenticationFilter - [172.19.0.17] Error performing authentication for HTTP
2024-12-30 09:52:32 java.lang.IllegalStateException: Header token should exist if no role token.
2024-12-30 09:52:32     at com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[com.google.guava-guava-32.1.1-jre.jar:?]
2024-12-30 09:52:32     at org.apache.pulsar.broker.authentication.AuthenticationProviderSasl.authenticateHttpRequest(AuthenticationProviderSasl.java:275) ~[com.ascentstream.pulsar-pulsar-broker-auth-sasl-3.0.8.1.jar:3.0.8.1] …
```
=> [fix][broker] Continue using the next provider for http authentication if one fails

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/AckSetState.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckInMemoryDeleteTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/BitSetRecyclable.java
`MLPendingAckStoreTest#testMainProcess` will fail by NPE if batch index ACK is enabled. The NPE happens when the position argument does not has a non-null `ackSet`.
- Add an `ackBatchPosition` method to handle `Optional` objects correctly with elegant and clear code.
- Replace `BitSetRecyclable` with `BitSet` as the value type of `batchDeletedIndexes` to simplify the unnecessarily complicated code of calling `recycle()`. For example, if `recycle()` is called in a callback of `ConcurrentSkipListMap#compute`, it could be called multiple times. Additionally, the optimization for GC is not provided because `BitSetRecyclable` cannot avoid the memory allocation of its underlying long arrays.
- Mark `batchDeletedIndexes` as `@Nullable` and check if it's not null instead of …
=> [fix][broker] Fix possible mark delete NPE when batch index ack is enabled

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java
PIP: #23789 
There is already one metric called `pulsar_delayed_message_index_size_bytes` for the total memory occupation used by delayed queue of **one topic**. 
```
writeMetric(stream, "pulsar_delayed_message_index_size_bytes", stats.delayedTrackerMemoryUsage,
cluster, namespace, topic, splitTopicAndPartitionIndexLabel);
```
Whereas, the metric for **one sub** also called `pulsar_delayed_message_index_size_bytes`, which do not comform the metric name norm and is confusing.
```
writeSubscriptionMetric(stream, "pulsar_delayed_message_index_size_bytes",
subsStats.delayedTrackerMemoryUsage, cluster, namespace, topic, sub, splitTopicAndPartitionIndexLabel);
```
Currently, it can export metric like:
```
pulsar_delayed_message_index_size_bytes{cluster="MyPulsar",namespace="public/default",topic …
```
=> [fix][broker] PIP-399: Fix Metric Name for Delayed Queue

bin/bookkeeper, bin/function-localrunner, bin/pulsar, bin/pulsar-admin-common.cmd, bin/pulsar-admin-common.sh, bin/pulsar-perf, src/pulsar-io-gen.sh
When using Pulsar with IPv6, it's necessary to set `-Djava.net.preferIPv4Stack=false` since Pulsar startup scripts set `-Djava.net.preferIPv4Stack=true`. Currently it's not possible to override the Pulsar default by passing `-Djava.net.preferIPv4Stack=false` in `OPTS` environment variable. This PR intends to make it possible.
This PR is related to the issue #23843.
Prepend the default value `-Djava.net.preferIPv4Stack=true` to `OPTS` instead of appending to it so that the setting in `OPTS` takes preference. The last setting in the argument line wins when setting system properties for Java processes.
=> [improve] Support overriding java.net.preferIPv4Stack with OPTS

bin/pulsar, bin/pulsar-admin-common.cmd, bin/pulsar-perf, docker/pulsar/Dockerfile
When the log levels (`pulsar.log.level` and `pulsar.log.root.level`) are modified in the `conf/log4j2.yaml` during runtime, the change is not reflected in the logs as expected.
I found the pulsar script always passes the `pulsar.log.level` and `pulsar.log.root.level`, which led to this issue.
- Removed the error environment variable from the `pulsar/Dockerfile`.
- A condition was added to include the `-Dpulsar.log.level` only if `PULSAR_LOG_LEVEL` is defined.
- A condition was added to include the `-Dpulsar.log.root.level` only if `PULSAR_LOG_ROOT_LEVEL` is defined, and ensured `PULSAR_LOG_ROOT_LEVEL` fallback to `PULSAR_LOG_LEVEL` if not defined.
=> [fix][misc] Honor dynamic log levels in log4j2.yaml

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ZkSessionExpireTest.java
Fixes #23389
- `pulsar1.getBrokerService().getTopic(topicName, false)`  may return a `completed empty future`, but the verify `assertTrue(future == null || future.isCompletedExceptionally())` does not match
- Increase timeout to wait for the broker to start
- correct the logic of the verification above
- add more logs
=> [fix][test]Fix flaky test testTopicUnloadAfterSessionRebuild

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/DrainingHashesTracker.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionTest.java
Fixes #23848
The Pulsar 4.0 Key_Shared PIP-379 implementation could deadlock and this problem was first captured in test environment heapdump where the thread stack information included in the heapdump showed multiple threads in blocked state, hinting a deadlock.
With the help of @pdolif, the problem was reproduced in isolation by simply adding this type of test code in a KeySharedSubscriptionTest test case.
```java
// test code that triggered the deadlock issue
new Thread(() -> {
while(true) { pulsar.getBrokerService().updateRates(); }
}).start();
```
In the test case, this triggered a similar pattern of blocked threads and therefore could be considered a reproduction of the previously faced dead lock issue in a test environment.
threaddump with deadlock:
* in jstack.review …
=> [fix][broker] Fix deadlock in Key_Shared PIP-379 implementation

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumersClassic.java
There was a misunderstanding in making the change #23384. This PR reverts the change and adds javadoc to the `cancelPendingReadRequest` method to explain the purpose of the method.
- revert #23384 changes
- revert also this in PersistentDispatcherMultipleConsumersClassic
- add javadoc
=> [fix][broker] Revert "[fix][broker] Cancel possible pending replay read in cancelPendingRead (#23384)"

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerCloseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerReconnectionTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerImplTest.java
**background 1:** producer's reconnection<sup>[1]</sup>
- set its connection to `null`
- check the state is not `closing | closed` 
- set the state to `connecting`
**background 2:** steps of producer closing<sup>[2]</sup>
- if its `connection` is null:
- fails all pending sends
- set state to `closed`
- if its `connection` is present:
- remove producer in broker
- remove the producer in the connection
- ails all pending sends
- set state to `closed`
---
**Issue 1: resending messages encountered a recycled pending message**
| time | thread `reconnection` | thread `close producer` |
| 1 | set its connection to `null` | |
| 2 | check state is not `closing | closed` | |
| 3 | | set state to `closing` |
| 4 | | connection is `null` now |
| 5 | set state to `connecting` |
| …
=> [fix][client] Orphan producer when concurrently calling producer closing and reconnection

pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java
`org.apache.pulsar.client.api.RetryTopicTest#testRetryTopicWithMultiTopic` don't test the behavior of retry topic at all.
Instead of calling `reconsumeLater` to trigger redelivery, current test code trigger redelivery base on ack timeout.
Add reconsumeLater call to test the behavior of retry topic with multiple topics.
=> [fix][test] Add reconsumeLater call in RetryTopicTest#testRetryTopicWithMultiTopic.

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/RangeSetWrapper.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerBkTest.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ManagedLedgerConfigTest.java
- https://github.com/apache/pulsar/pull/9292 introduced a new serialization about cursor metadata, but it will be lost. information when switching the config  `unackedRangesOpenCacheSetEnabled`. You can reproduce the issue with the new test `testUnackmessagesAndRecoveryCompatibility`
- [[DISCUSS] Add an optional config to disable the feature that compresses cursor metadata, which was contributed by #9292](https://lists.apache.org/thread/kfm7n6xf9pf7h76k4gx83zv3c2kj6yy1)
- Fix the issue
- Add an optional config `managedLedgerPersistIndividualAckAsLongArray` to enable or disable the feature that https://github.com/apache/pulsar/pull/9292 introduced, and set the default value to `false`. 
=> [fix] [ml] Fix cursor metadata compatability issue when switching the config unackedRangesOpenCacheSetEnabled

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
For a customized managed ledger implementation, `getCursors()` might not return a `ManagedCursorContainer`. In this case, `updateOldPositionInfo()` will return a failed future so that `monitorBacklogQuota` will keep printing spamming logs.
Return a null completed future in `updateOldPositionInfo` if `getCursors()` does not return a `ManagedCursorContainer`.
=> [improve][broker] Remove spamming logs for customized managed ledger

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Keep up-to-date with Netty 4.1 bug fixes.
* [Netty 4.1.117.Final release notes](https://netty.io/news/2025/01/14/4-1-117-Final.html)
- upgrade Netty to 4.1.117.Final
=> [improve] Upgrade to Netty 4.1.117.Final

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java
- current problem is that unefficient IP address comparison will have to be performed on every match
- equals method should check if the other object is the same instance as the first step
Previously the equals method performance has been improved by @Shawyeok in PR #18662. That addressed the main performance issue and this current PR is a small adjustment to avoid unnecessary work when there's a matching instance.
- add instance check as first step
=> [improve][broker] Improve Consumer.equals performance

testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockBookKeeper.java, testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockLedgerHandle.java, testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockReadHandle.java, testmocks/src/main/java/org/apache/bookkeeper/client/PulsarMockReadHandleInterceptor.java
In Pulsar tests, in-memory PulsarMockBookKeeper is used to implement BookKeeper client API.
There hasn't been a way to write realistic tests where there's variable latencies in BookKeeper reads.
Adding tests for various broker cache scenarios will benefit from this test framework improvement.
Example usage:
```java
// introduce delay to reads
pulsarTestContext.getMockBookKeeper().setReadHandleInterceptor((ledgerId, firstEntry, lastEntry, entries) -> {
log.info("intercepted read entries for ledgerId {}, firstEntry={}, lastEntry={}", ledgerId, firstEntry,
lastEntry);
long delayMillis = ThreadLocalRandom.current().nextLong(25, 50);
return CompletableFuture.supplyAsync(() -> entries,
CompletableFuture.delayedExecutor(delayMillis, TimeUnit.MILLISECONDS));
});
```
The same approach can be used …
=> [improve][test] Add solution to PulsarMockBookKeeper for intercepting reads

pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtilTest.java
There's a test method `BrokerTestUtil.receiveMessages` that is used in some Key_Shared tests to asynchronously read messages from multiple consumers until no more new messages are arrived after a quiet time.
The current implementation is wrong. Currently each consumer is handled separately and if an individual consumer times out, it would stop waiting for new messages even if a recent message arrived on another consumer. 
This makes some Key_Shared blocking tests to fail with short time outs. This makes some tests flaky or fail when they shouldn't.
Instead, the quiet time condition should be across all active consumers. 
Fix the quiet time implementation in `BrokerTestUtil.receiveMessages`.
=> [fix][test] Fix quiet time implementation in BrokerTestUtil.receiveMessages

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
Fixes #23880 
The list sources and sinks command will use default tenant and namespace when not specified, the list functions cmd should have the same bahaviour
- *Added unit test for list functions to use default tenant and namespace*
- when list functions using pulsar-admin without tenant and namespace, no error will be thrown, but the default tenant `public` and namespace `default` will be used
PR in forked repository: https://github.com/jiangpengcheng/pulsar/pull/38
=> [improve][fn] Set default tenant and namespace for ListFunctions cmd

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
Regard [[DISCUSS] Add an optional config to disable the feature that compresses cursor metadata, which was contributed by #9292](https://lists.apache.org/thread/kfm7n6xf9pf7h76k4gx83zv3c2kj6yy1), we get a conclusion:
- `branch-3.0, branch-3.3, branch-4.0`: set default value of the feature `managedLedgerPersistIndividualAckAsLongArray` to `false`
- `branch-4.1`: set the default value of the feature `managedLedgerPersistIndividualAckAsLongArray` to `true`
- Set the default value of managedLedgerPersistIndividualAckAsLongArray to `true`. This PR should not be cherry-picked into previous versions.
=> [improve][ml]Set default value of managedLedgerPersistIndividualAckAsLongArray to true

pulsar-client-admin-shaded/pom.xml, pulsar-client-all/pom.xml, pulsar-client-shaded/pom.xml, pulsar-common/src/main/java/org/apache/pulsar/common/util/ObjectMapperFactory.java, tests/pulsar-client-admin-shade-test/src/test/java/org/apache/pulsar/tests/integration/SmokeTest.java, tests/pulsar-client-all-shade-test/src/test/java/org/apache/pulsar/tests/integration/SmokeTest.java
When using the `pulsar-client-all` and `pulsar-client-admin` libraries, the `admin.brokerStats().getLoadReport()` doesn't work:
```
DEBUG o.a.p.c.util.ObjectMapperFactory - Add LoadManagerReport deserializer failed because LoadManagerReport.class has been shaded
java.lang.ClassNotFoundException: org.apache.pulsar.shade.org.apache.pulsar.policies.data.loadbalancer.LoadManagerReport
2025-01-23 16:15:16.816 [taskScheduler-9] DEBUG o.a.p.c.util.ObjectMapperFactory - Add LoadManagerReport deserializer failed because LoadManagerReport.class has been shaded
java.lang.ClassNotFoundException: org.apache.pulsar.shade.org.apache.pulsar.policies.data.loadbalancer.LoadManagerReport
2025-01-23 16:15:28.232 [http-nio-10000-exec-1] DEBUG o.s.w.s.m.m.a.ExceptionHandlerExceptionResolver - Resolved …
```
=> [fix][client] Fix LoadManagerReport not found

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/ManagedLedgerClientFactory.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicFactory.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/testinterceptor/BrokerTestInterceptor.java
In some Pulsar tests, there's a need to inject special behaviors such as delays, race conditions or failures.
The current solutions require using reflection and replacing instances, which results in hard to maintain test code.
- Add a solution for Pulsar broker tests that allows to decorate persistent topics, subscriptions, dispatchers
managed ledger factory, managed ledger and managed cursor instances.
- Refactor production code so that there are hooks for intercepting the instances in subclasses
- Add a helper methods for creating a Mockito Spy decorator
- for a dispatcher instance
- for a ManagedCursorImpl instance
example usage for spying on a dispatcher and cursor instance:
```java
@Override
protected void doInitConf() throws Exception {
super.doInitConf(); …
```
=> [improve][test] Support decorating topic, subscription, dispatcher, ManagedLedger and ManagedCursors instances in tests

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumersReadLimitsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java
Fixes #23505
See #23505. It is expected that dispatcherMaxReadSizeBytes also limits replay queue reads. Replay reads are currently unbounded in byte size, which is unexpected behavior.
- use `org.apache.bookkeeper.mledger.ManagedCursor#applyMaxSizeCap` also in replay queue reads
- add test
- test uses #23892. That PR should be merged first to clean up the diff of this PR.
=> [fix][broker] Apply dispatcherMaxReadSizeBytes also for replay reads for Shared and Key_Shared subscriptions

docker/pulsar/Dockerfile
In the Pulsar Dockerfile, amazoncorretto:21-alpine is used as the JDK. 
Since Alpine 3.21 has been released, it now contains a JDK built for Alpine 3.21, which might cause compatibility issues.
It's better to use the build that matches the Alpine version used in Pulsar.
Use the ALPINE_VERSION argument so that amazoncorretto:21-alpine3.20 image is used, matching the ALPINE_VERSION of Pulsar image.
=> [fix][build] Use amazoncorretto:21-alpine3.20 JDK build for Alpine 3.20

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/PendingReadsManager.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/InflightReadsLimiterIntegrationTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/cache/PendingReadsManagerTest.java
**Background**
- Broker will limit the pending reading to Bookies if enabled `managedLedgerMaxReadsInFlightSize`
- https://github.com/apache/pulsar/pull/17241 introduced a mechanism that merges BK reading requests if we can, for example:
- Request-1: Read entry `50~59` 
- Request-2: Read entry `50~69`
- The `Request-2` will wait for `Request-1`, and only send a real request that reads `60~69` after `Request-1` is finished.
**Issue**
- The `Request-2` above requests repeatedly
- It requests `50~70` when creating.
- It requests another range `61~70` after `Request-1` is finished.
- Expected: `Request-2` acquire `20` quota.
- Exact:  `Request-2` acquire `40` quota.
- You can call `testPreciseLimitation` to reproduce the issue
- Fix the issue.
=> [fix][broker] Fix repeatedly acquired pending reads quota

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java
Fixes #23882
The test class uses a `delayedDeliveryTickTimeMillis` of 1024.
In the flaky test, a message is produced that should be delivered after 2 seconds. Then, `consumer.receive()` is called with a timeout of 1 second and it is asserted that no message is received. Because of the tick time of 1024ms, the message may already be delivered after 2s-1024ms=976ms. In this case, the test fails because a message is consumed within 1 second.
Configure the message to be delivered after 3 seconds (instead of 2).
This ensures that the message is delivered at the earliest after 3s-1024ms=1976ms. The `consumer.receive()` with 1 second timeout should not receive the message anymore.
After that, there is another `consumer.receive()` whose timeout was increased from 3 to 4 seconds. …
=> [fix][test] Fix flaky DelayedDeliveryTest.testEnableTopicDelayedDelivery

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerBkTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/RangeCacheTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionBrokerCacheTest.java, pulsar-broker/src/test/resources/log4j2.xml, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/impl/TxnLogBufferedWriterTest.java, pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/test/MockedBookKeeperTestCase.java
Fixes #23900
During work on PR #23901, a severe issue was discovered in the RangeCache implementation. Cache lookups consistently fail when the key used to look up an entry differs from the instance used to put the entry into the cache.
One detail of the current broker cache implementation is that it is necessary to configure `cacheEvictionByMarkDeletedPosition=true` so that cached entries don't get evicted by the read position in the managed ledger.
This problematic solution was introduced in PR #22789, which aimed to address race conditions in the RangeCache and prevent the use of already recycled object instances. The solution underwent subsequent refactoring in PRs #22814 and #22818. While the value wrapper solution ensures consistency between cached entries and their corresponding …
=> [fix][broker Fix bug in RangeCache where different instance of the key wouldn't ever match

.github/actions/clean-disk/action.yml
In GitHub Actions CI, disk space has been running out recently.
```
Error:  Failed to execute goal io.fabric8:docker-maven-plugin:0.45.1:build (default) on project pulsar-all-docker-image: Unable to build image [apachepulsar/pulsar-all] : "write /pulsar/connectors/pulsar-io-solr-4.1.0-SNAPSHOT.nar: no space left on device" -> [Help 1]
```
(example from https://github.com/apache/pulsar/actions/runs/13032747233/job/36356115521?pr=23901#step:10:25266)
When running clean-disk action with `mode: full`, configure Docker `data-root` to `/mnt/docker` to avoid running out of disk space. The `/mnt` disk has over 66GB free space in GitHub Actions CI.
=> [fix][ci] Configure Docker data-root to /mnt/docker to avoid running out of disk space

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerFactoryConfig.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/InflightReadsLimiter.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/PendingReadsManager.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheManagerImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/InflightReadsLimiterIntegrationTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/cache/InflightReadsLimiterTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/cache/PendingReadsManagerTest.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/ManagedLedgerClientFactory.java
Fixes #23504
Fixes #23506
In the current implementation before this PR there are multiple problems:
* redelivery (replay) queue reads don't get deduplicated or limited by `managedLedgerMaxReadsInFlightSizeInMB`, reported as #23504
* The `managedLedgerMaxReadsInFlightSizeInMB` limit doesn't work properly if `managedLedgerReadEntryTimeoutSeconds` isn't set, reported as #23506.
In addition to this, even if `managedLedgerReadEntryTimeoutSeconds` is set, when the limit is reached, there's no queuing and all threads will be retrying in a tight loop to acquire permits. This tight loop causes unnecessary CPU consumption and contention. 
Enhanced permit acquisition:
- Added queuing for pending requests when the limit is reached
- Configurable queue size via …
=> [fix][broker] Make InflightReadsLimiter asynchronous and apply it for replay queue reads

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/SameAuthParamsLookupAutoClusterFailover.java
An exception in the `PulsarClientImpl` constructor will lead to close the `SameAuthParamsLookupAutoClusterFailover` instance which might not be initialized yet. When it happens it causes an NPE that masks the original exception.
```
Failed to shutdown Pulsar client @timestamp=2025-01-29T20:21:32.607Z logger-name=org.apache.pulsar.client.impl.PulsarClientImpl thread-name=main level=WARN level-value=30000 stack-trace=`java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.shade.io.netty.util.concurrent.ScheduledFuture.cancel(boolean)" because "this.scheduledCheckTask" is null
at org.apache.pulsar.client.impl.SameAuthParamsLookupAutoClusterFailover.close(SameAuthParamsLookupAutoClusterFailover.java:111)
at org.apache.pulsar.client.impl.PulsarClientImpl.shutdown(PulsarClientImpl.java …
```
=> [fix] Avoid NPE when closing an uninitialized SameAuthParamsLookupAutoClusterFailover

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java
When transaction client is enabled, it gets initialized before the `ServiceUrlProvider` does get a chance to get initialized.
If the URL depends on a probe in the `ServiceUrlProvider`, the txn coordinator client is still going to use the default URL instead of getting an updated URL by the probe.
*(or)*
*(or)*
*(example:)*
PR in …
=> [fix] Initialize UrlServiceProvider before trying to use transaction coordinator

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerServiceException.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
The broker currently logs an error if there's a temporary connection issue:
```
[configuration-metadata-store-14-1] ERROR org.apache.pulsar.broker.service.persistent.PersistentTopic - [xxx] Failed to create subscription: xxxx
java.util.concurrent.CompletionException: org.apache.pulsar.broker.service.BrokerServiceException: Connection was closed while the opening the cursor 
```
We can change this to a warning log level. This way, it won't clutter the broker log, and we can still track connection issues.
- Introduce a new Expcetion BrokerServiceException.ConnectionClosedException to track the connection closed error
- Avoid logging errors when there is a connection issue during subscription.
This change is a trivial rework / code cleanup …
=> [improve][broker] Avoid logging errors when there is a connection issue during subscription.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
If the producer is created with some schema error, the broker will print many error logs like this:
```
ERROR org.apache.pulsar.broker.service.ServerCnx - Try add schema failed, remote address xxx
java.util.concurrent.CompletionException: org.apache.pulsar.broker.service.schema.exceptions.IncompatibleSchemaException: Producers cannot connect or send message without a schema to topics with a schemawhen SchemaValidationEnforced is enabled
```
This error can be reported to the client and not need to print it in the broker.
- Avoid printing log for IncompatibleSchemaException in ServerCnx
*(or)* …
=> [improve][broker] Avoid printing log for IncompatibleSchemaException in ServerCnx

pom.xml, pulsar-io/common/pom.xml, pulsar-io/core/pom.xml, pulsar-io/pom.xml
By default, Pulsar uploads connector JAR and NAR files to Maven Central, but this is unnecessary since connectors are not typically downloaded from Maven Central. Additionally, the large size of the connector files causes timeouts or connection disconnections during the deployment process, as the files exceed Sonatype's size [limitations](https://central.sonatype.org/publish/publish-portal-upload/) for private publishing.
> Central Publisher Portal currently supports common archive extensions, e.g. zip, jar, tar.gz. While you can only upload one zip at a time per publishing request, the archive can contain more than one component. You can upload an archive up to 1GB in size. If your upload fails with an error or does not result in the creation of a deployment first check to see if the …
=> [improve][io] Allow skipping connector deployment

pom.xml, pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenz.java, pulsar-client-auth-athenz/src/test/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenzTest.java
When we can only access the [Athenz ZTS](https://athenz.github.io/athenz/decent_authz_flow/#zts-authz-token-system) server through a forward proxy, we can't use pulsar-client-auth-athenz for an authentication plugin because the current plugin implementation does not support the ztsProxyUrl config of ZTSClient.
Support ztsProxyUrl in the pulsar-client-auth-athenz.
- Added an unit test for ztsProxyUrl config
PR in forked repository: https://github.com/equanz/pulsar/pull/12
=> [feat][client] Support forward proxy for the ZTS server in pulsar-client-auth-athenz

microbench/README.md, microbench/src/main/java/org/apache/pulsar/broker/qos/AsyncTokenBucketBenchmark.java, microbench/src/main/java/org/apache/pulsar/broker/qos/DefaultMonotonicSnapshotClockBenchmark.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/qos/AsyncTokenBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/qos/AsyncTokenBucketBuilder.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/qos/DefaultMonotonicSnapshotClock.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/qos/DynamicRateAsyncTokenBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/qos/DynamicRateAsyncTokenBucketBuilder.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/qos/FinalRateAsyncTokenBucket.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/qos/FinalRateAsyncTokenBucketBuilder.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PublishRateLimiterImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SubscribeRateLimiter.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/qos/AsyncTokenBucketTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/qos/DefaultMonotonicSnapshotClockTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/RGUsageMTAggrWaitForAllMsgsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PublishRateLimiterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/AbstractMessageDispatchThrottlingTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/MessageDispatchThrottlingTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SubscriptionMessageDispatchThrottlingTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessagePublishThrottlingTest.java
Fixes #23920
Prior to this PR, connections in Pulsar could experience excessive throttling and timeouts due to issues in rate limiting implementation. This was caused by both calculation errors in token bucket logic and problems with clock source handling in virtualized environments. The PR addresses these issues to prevent unintended long throttling periods and connection timeouts.
Two key issues are addressed in this PR:
1. Calculation Issue in AsyncTokenBucket:
- The current token calculation logic is flawed when handling consumed tokens in conjunction with newly added tokens
- When adding new tokens, the eventually consistent token calculation should happen before limiting the tokens to the bucket capacity limit. Since the new tokens were first added and capped to the capacity limit, …
=> [fix][broker] Fix rate limiter token bucket and clock consistency issues causing excessive throttling and connection timeouts

tiered-storage/pom.xml
The tiered-storage is only used in the broker, we don't need to publish that to Maven Central.
- Skip tiered-storage deployment.
=> [improve][offload] Skip tiered-storage deployment

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageWithBatchIndexLevelTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/GrowableArrayBlockingQueue.java
Issue: call redeliver `1` message, but it will redeliver `2` messages, you can reproduce the issue by the new test `testBatchMessageNAck`
fix the bug
=> [fix] [client] call redeliver 1 msg but did 2 msgs

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImplTest.java
In protocol handler's implementation, sometimes it needs to record the current base offset before the actual `asyncAddEntry` call (or the wrapped `PersistentTopic#publishMessages` call), for example:
```java
private final PersistentTopic persistentTopic;
private final Set<Long> pendingBaseOffsets = ConcurrentHashMap.newKeySet();
private synchronized void add(ByteBuf buffer, int batchSize) {
final var ml = (ManagedLedgerImpl) persistentTopic.getManagedLedger();
final var interceptor = (ManagedLedgerInterceptorImpl) ml.getManagedLedgerInterceptor();
final var baseOffset = interceptor.getIndex(); // the base offset of the next batch to write
pendingBaseOffsets.add(baseOffset);
ml.asyncAddEntry(buffer, batchSize, new AsyncCallbacks.AddEntryCallback() {
@Override
public void …
```
=> [improve][ml] Do not switch thread to execute asyncAddEntry's core logic

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/RangeCacheTest.java
https://github.com/apache/pulsar/pull/23903 introduces a memory leak issue in `RangeCache#removeEntry`.
```diff
-        Value value = entryWrapper.getValue(key);
+        Value value = getValueMatchingEntry(entry);
```
Unlike `entryWrapper.getValue`, `getValueMatchingEntry` will increase the reference count of `entry`'s value.
- Remove the duplicated retain operation in `RangeCache#removeEntry`. Add some API notes for the private methods that might increase the reference count of the value
- Apply the reference count validation for eviction on a `RangeCache` (`RangeCacheTest.customTimeExtraction`).
=> [fix][ml] Fix memory leak due to duplicated RangeCache value retain operations 

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
**Background**: the logic of calculating `backlog`
- There is a variable named `manegedledger.entriesAddedCounter`, which means how many entries were added after the topic was loaded up at the latest time.
- there is a variable named `cursor.messagesConsumedCounter`, which means how many entries were acked after the cursor was loaded up at the latest time, it can be a negative value.
- Backlog calculating mechanism: `manegedledger.entriesAddedCounter - cursor.messagesConsumedCounter`
**Steps to reproduce the issue**
- `ledgers: [ 1, 2, 3 ]`, `100` entries per ledger.
- `durable-cursor: {mark-deleted-position: 3:0}`
- `manegedledger.entriesAddedCounter`: `0`, no entries were added after the topic was loaded up.
- concurrently trimming ledger and non-durable cursor creation
| time | `trim …
=> [fix] [ml] incorrect non-durable cursor's backlog due to concurrently trimming ledger and non-durable cursor creation

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageFinder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
Fixes https://github.com/apache/pulsar/issues/23910
As the we don't enable `AppendBrokerTimestampMetadataInterceptor` by default, so the entries timestamp is not Strictly Increasing.
Because the message timestamp is generated by the clients, the messages from different producers maybe not in global ordering(because of network delay, backpressure, thread scheduling, etc)
In a single ledger, they may be arranged in the following way:
[2, 1, 3, 5, 4, 6, 7, 9, 8.....]
Overall, they have a self increasing trend, but locally, it may be possible not.
1. If the `Position` is null when call `PersistentMessageFinder.findMessages`, it will reset the cursor position to `earliest`, see: https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ …
=> [fix][broker] Fix seeking by timestamp can be reset the cursor position to earliest

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java
- The canDispatchEntry method uses MutableBoolean as an argument, and then changes its value internally, but this variable is not necessary
- Optimize code for readability
PR in forked repository: https://github.com/guan46/pulsar/pull/3
=> [improve][broker] Refactor a private method to eliminate an unnecessary parameter

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/PendingReadsManager.java
Fixes #23952
A deadlock could occur in PendingReadsManager after #23901 changes. This deadlock was captured in a test case, but based on code analysis this problem applies to production code execution too.
```
Found one Java-level deadlock:
=============================
"main":
waiting to lock monitor 0x00007fd520fe6f10 (object 0x000010003425f350, a org.apache.pulsar.broker.service.persistent.PersistentSubscription),
which is held by "PulsarTestContext-executor-OrderedExecutor-0-0"
"PulsarTestContext-executor-OrderedExecutor-0-0":
waiting to lock monitor 0x00007fd4f400dd00 (object 0x000010003425fd70, a org.apache.pulsar.broker.service.persistent.PersistentDispatcherSingleActiveConsumer),
which is held by "broker-topic-workers-OrderedExecutor-0-0" …
```
=> [fix][ml] Fix deadlock in PendingReadsManager

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
```
┌─────────────────────────────────────────────────────┬────────────────┬──────────┬──────────┬───────────────────┬───────────────┬───────────────────────────────────────────────────────────┐
│                       Library                       │ Vulnerability  │ Severity │  Status  │ Installed Version │ Fixed Version │                           Title                           │
├─────────────────────────────────────────────────────┼────────────────┼──────────┼──────────┼───────────────────┼───────────────┼───────────────────────────────────────────────────────────┤
│ io.netty:netty-handler                              │ CVE-2025-24970 │ HIGH     │ fixed    │ 4.1.117.Final     │ 4.1.118.Final │ Netty, an asynchronous, event-driven network application  │
│ …
```
=> [fix][sec] Upgrade to Netty 4.1.118

docker/pulsar/Dockerfile
There are several CVEs in base image with Alpine 3.20 that are already fixed in 3.21: 
```
apachepulsar/pulsar:4.0.2 (alpine 3.20.5)
Total: 14 (UNKNOWN: 0, LOW: 3, MEDIUM: 7, HIGH: 4, CRITICAL: 0)
┌──────────────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────────┐
│       Library        │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version │                            Title                            │
├──────────────────────┼────────────────┼──────────┼────────┼───────────────────┼───────────────┼─────────────────────────────────────────────────────────────┤
│ bind-libs            │ CVE-2024-11187 │ HIGH     │ fixed  │ 9.18.32-r0        │ 9.18.33-r0    │ bind: bind9: Many …
```
=> [fix] Use Alpine 3.21 in base image

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java
Running `ManagedCursorInfoMetadataTest` and `ManagedLedgerInfoMetadataTest` with Netty leak detector's `paranoid` level reveal Netty `ByteBuf` leaks in `ManagedCursorInfo` and `ManagedLedgerInfo` decompression and compression.
ManagedCursorInfo compression was introduced in [PIP-146](https://github.com/apache/pulsar/issues/14529). ManagedLedgerInfo compression was introduced earlier, in PR #11490.
Fix the leak by properly releasing buffers. 
* In the `parseManagedCursorInfo` and `parseManagedLedgerInfo` methods there was a clear leak where the ByteBuf instance wasn't released
* In the `compressManagedInfo` method, the `CompositeByteBuf` instance was never released. `CompositeByteBuf` might copy input buffers into a new buffer and releasing the components separately is not a correct …
=> [fix][ml] Fix memory leaks in ManagedCursorInfo and ManagedLedgerInfo decompression and compression

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
Function `cursor.getNumberOfEntriesInBacklog(false)` maybe called twice in `PersistentReplicator.expireMessages`.
This PR https://github.com/apache/pulsar/pull/20416 optimizes similar problems in `PersistentSubscription.expireMessages`.
Save backlog to variable.
=> [improve][broker] Avoid PersistentReplicator.expireMessages logic compute backlog twice

pom.xml
Build error on the branch-3.0:
```
$ mvn install -Pcore-modules,-main -DskipTests -Dspotbugs.skip=true -T 1C
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.apache.kerby:kerb-simplekdc:jar:1.1.1 -> org.apache.kerby:kerb-client:jar:1.1.1 -> org.apache.kerby:token-provider:jar:1.1.1 -> com.nimbusds:nimbus-jose-jwt:jar:4.41.2 -> net.minidev:json-smart:jar:[1.3.1,2.3]
```
Build [error](https://github.com/apache/pulsar/actions/runs/13282620861/job/37084137661?pr=23966#step:7:4412) on master:
```
Error:  Failed to execute goal on project pulsar-io-azuredataexplorer: Could not collect dependencies for project org.apache.pulsar:pulsar-io-azuredataexplorer:jar:4.1.0-SNAPSHOT
Error:  No versions available for …
```
=> [fix][build] Upgrade json-smart to 2.5.2

.github/workflows/pulsar-ci.yaml
Pulsar CI runs an "OWASP dependency check" build as part of the CI workflow when a dependency is updated.
This can take very long for Pull Request builds when the dependency check data isn't found in the cache.
```
Warning:  An NVD API Key was not provided - it is highly recommended to use an NVD API key as the update can take a VERY long time without an API Key
[INFO] NVD API has 280,989 records in this update
[INFO] Downloaded 10,000/280,989 (4%)
[INFO] Downloaded 20,000/280,989 (7%)
[INFO] Downloaded 30,000/280,989 (11%)
[INFO] Downloaded 40,000/280,989 (14%)
[INFO] Downloaded 50,000/280,989 (18%)
[INFO] Downloaded 60,000/280,989 (21%)
[INFO] Downloaded 70,000/280,989 (25%)
[INFO] Downloaded 80,000/280,989 (28%)
[INFO] Downloaded 90,000/280,989 (32%)
[INFO] Downloaded 100,000/280,989 …
```
=> [improve][ci] Skip "OWASP dependency check" when data wasn't found in cache

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
There's a Netty ByteBuf leak in ClientCnx.newLookup when there's TooManyRequestsException.
- release the buffer before returning
=> [fix][client] Fix memory leak in ClientCnx.newLookup when there's TooManyRequestsException

pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java
When enabling Netty leak detection with #23956 changes at `paranoid` level, BatchMessageTest.testSendOverSizeMessage shows a Netty ByteBuf memory leak. This is a bug in BatchMessageContainerImpl. It doesn't release the payload when the message size exceeds max message size.
- Properly release the payload (or compressed payload) buffer when the message size exceeds max message size
After #23956 changes are included, it is possible to catch such memory leaks in pull request CI builds.
=> [fix][client] Fix memory leak when message size exceeds max message size and batching is enabled

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/TypedMessageBuilder.java
Fixes #23968
Related Issue: https://github.com/apache/pulsar-site/pull/507
We now support consuming delayed messages with shared and Key-shared type subscriptions, which has been corrected since [pulsar 3.x doc](https://pulsar.apache.org/docs/3.0.x/concepts-messaging/#delayed-message-delivery) in above pr.
But Java code [deliverAt](https://github.com/apache/pulsar/blob/1ab63455c1f36062cbc587244f8c0c5f71be16c5/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/TypedMessageBuilder.java#L192) and [deliverAfter](https://github.com/apache/pulsar/blob/1ab63455c1f36062cbc587244f8c0c5f71be16c5/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/TypedMessageBuilder.java#L205) comment says we can only support Shared type subscription, so that maybe we need to fix them.
Replace …
=> [improve][client] Update TypedMessageBuilder deliverAfter and deliverAt api comment

pulsar-broker-auth-sasl/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderSasl.java
Potential fix for [https://github.com/apache/pulsar/security/code-scanning/22](https://github.com/apache/pulsar/security/code-scanning/22)
To fix the problem, we need to ensure that any user-provided input used in HTTP headers is properly sanitized to prevent HTTP response splitting. This can be done by removing or escaping special characters such as CRLF from the input before using it in the response header.
The best way to fix this issue is to create a method that sanitizes the input by removing or escaping special characters and then use this method to sanitize the `SASL_STATE_SERVER` header value before setting it in the response.
=> [fix] Potential fix for code scanning alert no. 22: HTTP response splitting

pip/pip-395.md
PIP: 395
Pulsar Proxy has a support to use it as HTTP reverse proxy to access Broker’s admin API and can also be extended to act as a reverse proxy other HTTP endpoints. Sometimes, it is very crucial to add customizable headers into the HTTP response returned by Proxy to enhance the security experience while using Proxy over HTTP.
Response headers in a reverse HTTP proxy are critical for maintaining and enhancing the security of the web applications and services behind the proxy. These headers act as a first line of defense, hardening the web server infrastructure and protecting clients from common web vulnerabilities. 
For example, when implementing a reverse HTTP proxy, security headers such as `Referrer-Policy`, `X-Content-Type-Options`, `Strict-Transport-Security`, …
=> [improve] [pip] PIP-395: Add Proxy configuration to support configurable response headers for http reverse-proxy

conf/proxy.conf, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/WebServer.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyAdditionalServletTest.java
PIP: #23648 
Pulsar Proxy has a support to use it as HTTP reverse proxy to access Broker’s admin API and can also be extended to act as a reverse proxy other HTTP endpoints. Sometimes, it is very crucial to add customizable headers into the HTTP response returned by Proxy to enhance the security experience while using Proxy over HTTP.
Response headers in a reverse HTTP proxy are critical for maintaining and enhancing the security of the web applications and services behind the proxy. These headers act as a first line of defense, hardening the web server infrastructure and protecting clients from common web vulnerabilities. 
For example, when implementing a reverse HTTP proxy, security headers such as `Referrer-Policy`, `X-Content-Type-Options`, `Strict-Transport-Security`, …
=> [improve] [proxy] PIP-395: Add Proxy configuration to support configurable response headers for http reverse-proxy

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
Fixes https://github.com/apache/pulsar/issues/22657
This issue was introduced by https://github.com/apache/pulsar/pull/20990. After we call Consumer#addAndGetUnAckedMsgs to change the unackedMessages,  we should check and may update blockedConsumerOnUnackedMsgs.               
- after change the unackedMessages, call updateBlockedConsumerOnUnackedMsgs to update blockedConsumerOnUnackedMsgs's value
=> [fix][broker] Fix incorrect blockedConsumerOnUnackedMsgs value when maxUnackedMessagesPerConsumer is 1

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreExtendedTest.java
Fixes https://github.com/apache/pulsar/issues/23889
Fixes https://github.com/apache/pulsar/issues/23889
zk.put creates persistent znode although it passes ephemeral node creation option.
- pass the creation option when set fails(if the node exists already
PR in forked repository: https://github.com/heesung-sn/pulsar/pull/87
=> [fix][meta] Fix ephemeral Zookeeper put which creates a persistent znode

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java
Main Issue: https://github.com/apache/pulsar/issues/23885
When batch message is negative ack, some undetermined behavior may occur. For example, 
- There are 10 messages batched into one message, all of them are unbatch into consumer's receiver queue.
- consumer negative ack the first 5 messages.
- before the consumer negative ack another 5 messages, the negatve ack tracker trigger the redelivery request.
- broker dispatch this batched message to consumer.
- consumer clear the remaining 5 messages in the queue, and refill 10 messages into the queue.
- Message duplication issue occurs.
IMO, suck kind of problem is reasonable as we only provide At-Least-Once semantices.
This unit test don't handle the batch case at some time. 
Negative ack one message is enough for this test in batch case. …
=> [fix][test] fix flaky testNegativeAcksWithBackoff when batch enabled.

pulsar-package-management/filesystem-storage/src/main/java/org/apache/pulsar/packages/management/storage/filesystem/FileSystemPackagesStorage.java
Potential fix for [https://github.com/apache/pulsar/security/code-scanning/48](https://github.com/apache/pulsar/security/code-scanning/48)
To fix the problem, we need to enhance the validation of the user-provided path to ensure it does not contain any path traversal sequences or absolute paths. We can achieve this by normalizing the path and ensuring it remains within a predefined base directory.
1. Normalize the path to remove any redundant path elements.
2. Ensure the normalized path is still within the intended base directory.
3. Reject any paths that do not meet these criteria.
=> [fix] fix for code scanning alert no. 48: Uncontrolled data used in path expression

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/PulsarRegistrationClient.java
Main Issue: https://github.com/apache/pulsar/issues/23330
Relevant issue: https://github.com/apache/pulsar/issues/23282, https://github.com/apache/pulsar/pull/23283
Fix another issue cause broker lost rack information. There is a previous issue also cause broker lost rack information.
This is the first potential fix, when construct bookieClient and do watchWritableBookies() to register listener, trigger each listener in writableBookiesWatchers. 
This fix can ensure multiple listeners is trigger in a sync way, but it would bring duplicate trigger problem. Since watchWritableBookies() is only executed twice when bookieClient construct. I think the duplicate trigger problem is acceptable. 
Alternative fix is to make BookieRackAffinityMapping#watchAvailableBookies become sync method. Change …
=> [fix][broker] fix broker may lost rack information

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ShadowManagedLedgerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImplTest.java
This reverts commit 215b36dcc73dad91f4c9ba9a90da50540e4899a7.
See some discussion details in https://github.com/apache/pulsar/pull/23983.
https://github.com/apache/pulsar/pull/23940 and https://github.com/apache/pulsar/pull/23983 (not merged) both change the semantic for `ManagedLedgerInterceptor#beforeAddEntry`:
- Before: it's called by the internal executor of the `ManagedLedgerImpl`
- After: it's called as a part of `ManagedLedgerImpl#asyncAddEntry` in the same thread.
Since managed ledger and the interceptor are both pluggable (the interceptor can be changed via configuring `BrokerEntryMetadataInterceptor` or even `ManagedLedgerConfig#setManagedLedgerInterceptor`), the semantic change should require a formal PIP. Before that, the downstream applications should only rely on specific …
=> [revert] "[improve][ml] Do not switch thread to execute asyncAddEntry's core logic (#23940)"

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java, pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundles.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/ProducerConsumerBase.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java, pulsar-metadata/src/test/java/org/apache/bookkeeper/replication/BookKeeperClusterTestCase.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BaseMetadataStoreTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/CounterTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreExtendedTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MockZooKeeperMetadataStoreProvider.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/LedgerManagerIteratorTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/LedgerUnderreplicationManagerTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/bookkeeper/PulsarLedgerIdGeneratorTest.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/impl/MetadataStoreFactoryImplTest.java, testmocks/src/main/java/org/apache/zookeeper/MockZooKeeper.java, testmocks/src/main/java/org/apache/zookeeper/MockZooKeeperSession.java
This PR is a follow-up to #23984 to fix ephemeral status handling in ZKMetadataStore and to improve the ZooKeeper testing infrastructure.
A key addition is enabling pulsar-metadata tests to run against MockZooKeeper through a proper MetadataStoreProvider implementation, ensuring MockZooKeeper correctly implements all features that Pulsar depends on.
1. Fixed Production Code Issues:
- Fixed ephemeral status handling in ZKMetadataStore to properly detect ephemeral nodes by using the correct comparison value (0L) for non-ephemeral (== persistent) nodes
2. MockZooKeeper improvements and fixes:
- Fixed ephemeral node handling and cleanup on session termination
- Improved ZK stat handling with proper timestamps and version numbers
- Added proper session ID management and consistent thread …
=> [fix][meta] Fix ephemeral handling of ZK nodes and fix MockZooKeeper ephemeral and ZK stat handling

pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
- If concurrentPutTest runs before emptyStoreTest, it will cause emptyStoreTest to fail
- change the key used in concurrentPutTest
=> [fix][test] Fix flaky test MetadataStoreTest.emptyStoreTest

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java
In ZKMetadataStore.asyncCreateFullPathOptimistic method, there's a hack using java.io.File to resolve the parent path. This could be simplified.
Use String operations to resolve parent path.
=> [improve][meta] Simplify getting parent path in ZKMetadataStore without using java.io.File

pom.xml
Keep Testcontainers and docker-java up-to-date in Pulsar.
- Upgrade Testcontainers to 1.20.4
- Upgrade docker-java to 3.4.0 since it has to match the version used by Testcontainers
- https://repo1.maven.org/maven2/org/testcontainers/testcontainers/1.20.4/testcontainers-1.20.4.pom references docker-java 3.4.0
=> [improve][test] Upgrade Testcontainers to 1.20.4 and docker-java to 3.4.0

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumersClassic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java
Currently broker is keep printing false logs by incorrectly finding stuck topic when broker has correctly blocked consumers with max-unack messages. Therefore, stuck consumer check task should not consider topic stuck if all the consumers are blocked due to max-unack messages and there are no available consumers, to avoid below false log lines
```
22:21:20.187 [pulsar-stats-updater-OrderedScheduler-0-0] WARN  org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers - persistent://tenant1/ns1/t1 / my-sub Dispatcher is stuck and unblocking by issuing reads
```
Stuck topic check task should not consider topic stuck if none of the consumer is available to consume messages.
This change is a trivial rework / code cleanup …
=> [fix][broker] fix broker identifying incorrect stuck topic

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java
Currently broker faces below NPE when active consumer disconnects and no other consumers are connected on fail-over subscription
```
07:11:28.357 [broker-topic-workers-OrderedExecutor-3-0] ERROR org.apache.bookkeeper.common.util.SingleThreadExecutor - Error while running task: Cannot invoke "org.apache.pulsar.broker.service
.Consumer.consumerName()" because "activeConsumer" is null
java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.broker.service.Consumer.consumerName()" because "activeConsumer" is null
at org.apache.pulsar.broker.service.persistent.PersistentDispatcherSingleActiveConsumer.readMoreEntries(PersistentDispatcherSingleActiveConsumer.java:353) ~[pulsar-broker-.jar:]
at org.apache.pulsar.broker.service.persistent.PersistentDispatcherSingleActiveConsumer.lambda$disp …
```
=> [fix][broker] Fix NPE during active consumer is disconnected

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TransportCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/GeoPersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ShadowReplicator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerMessageDeduplicationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorDeduplicationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/GeoReplicationProducerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ProducerConfigurationData.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Markers.java, pulsar-common/src/main/proto/PulsarApi.proto
**How does deduplication work?**
- Producer sends messages and records sequence-ids that are pending responses in memory, the variable is `{pendingMessages}`
- Brokers will respond to an invalid position `-1:-1` if the sequence ID published is lower than the previous messages.
- Producer checks whether the next sequence id in `{pendingMessages}` is larger than the one that was rejected.
- `{next} > {rejected}`: ignore the error, and continue work
- `{next} < {rejected}`: close channels and reconnect.
Conditions that issue happened
- Replicators send all messages on a topic and do not matter what message was sent by which original producer.
- **(Highlight)** it mixed messages into `{pendingMessages}` with `message.sequenceId` but ignores `message.original-producer-name`, which may cause …
=> [fix][broker] Geo Replication lost messages or frequently fails due to Deduplication is not appropriate for Geo-Replication

.mvn/extensions.xml, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/BaseMetadataStoreTest.java
In Pulsar, we use ASF hosted Gradle Delocity for analysing Pulsar's maven builds.
Example listing of latest builds: https://develocity.apache.org/scans?search.rootProjectNames=Pulsar
There was a  deadlock in https://github.com/apache/pulsar/actions/runs/13410107140/job/37458613913#step:13:1612 which could be caused by Gradle Develocity Maven Extension. The currently used version is 1.22.2 . Since there's a newer version available, it's worth upgrading to see if it resolves the issue in future builds.
```
Found one Java-level deadlock:
=============================
"main":
waiting to lock monitor 0x00007f1a2c8ed3d0 (object 0x000010001b819ea8, a [Ljava.lang.Object;),
which is held by "Thread-110"
"Thread-110":
waiting to lock monitor 0x00007f1ae0002c60 (object 0x00001000073251b0, a …
```
=> [improve][ci] Upgrade Gradle Develocity Maven Extension to 1.23.1

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/InflightReadsLimiterIntegrationTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageWithBatchIndexLevelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java
**Background**
- `B1`: Broker assumes the entry size is `1` when no publishing after the topic was loaded up at the latest time. Otherwise, it uses the average entries size published during the lastest time-range of the topic loaded up.
- Issue: the average entry size is not prectice for the catch-up read after a topic is reloaded. 
- `B2`: The feature `managedLedgerMaxReadsInFlightSize` assumes the entry size is `10kb` when it read nothing. Otherwise, it uses the average entries size of the entries read out before.
**Issue**
Regarding scenario `B2`, it may cause an error `Time-out elapsed while acquiring enough permits on the memory limiter to read from ledger 33, {tenant}/{ns}/persistent/{topic}-partition-0, estimated read size 1937 bytes for 1 entries (check …
=> [improve] [broker] Make the estimated entry size more accurate

pulsar-broker/src/test/java/org/apache/pulsar/client/api/v1/V1_ProducerConsumerTest.java
- https://github.com/apache/pulsar/actions/runs/13456263294/job/37600883842?pr=23931
```
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    V1_ProducerConsumerTest.testConcurrentConsumerReceiveWhileReconnect:594 expected [90] but found [80]
[INFO] 
Error:  Tests run: 366, Failures: 1, Errors: 0, Skipped: 1
```
Root cause: when the verification starts, maybe there is in-flight messages dispatching
Instead of verifying directly, use a `Awaitility.await().untilAsserted(...)`
=> [fix][test]Fix flaky test V1_ProducerConsumerTest.testConcurrentConsumerReceiveWhileReconnect

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java
**Failed test**: https://github.com/apache/pulsar/actions/runs/13403975927/job/37440612533?pr=23697
```
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  org.apache.pulsar.broker.service.OneWayReplicatorUsingGlobalZKTest.testConfigReplicationStartAt
[INFO]   Run 1: PASS
Error:    Run 2: OneWayReplicatorUsingGlobalZKTest.testConfigReplicationStartAt:162 expected object to not be null
```
**Root cause**
- background: the default value of creating subscription is `latest`
- issue: if the new subscription created after the msg replicated, the new consumer will receive a `null` value
- Create the subscription with `start = earliest` manually
=> [fix][test] Fix flaky test OneWayReplicatorUsingGlobalZKTest.testConfigReplicationStartAt

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
Currently, V1 topic's CLI does not return  various additional metadata (`publish-time, event-time, etc,`) for peek-message command. Broker already returns those additional metadata for peek-message API but CLI doesn't print it for v1 topic and it prints for v2 topic. so, this PR will make this behavior consistent between v1 and v2 topics.
This PR doesn't make any change into API definition or its definition. it adds support of printing extra metadata while peek-message command.
*(or)*
*(or)*
*(example:)*
- *Added integration tests …
=> [improve][cli] Support additional msg metadata for V1 topic on peek message cmd

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/InflightReadsLimiter.java
- Because all changes to queuedHandles are in the lock, there is no need to use thread-safe collections
- Replace SpscArrayQueue with ArrayDeque.
PR in forked repository: https://github.com/guan46/pulsar/pull/7
=> [improve][ml] Use lock-free queue in InflightReadsLimiter since there's no concurrent access 

conf/broker.conf, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloaderFactory.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPoliciesImpl.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/JCloudLedgerOffloaderFactory.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloader.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderStreamingTest.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreManagedLedgerOffloaderTest.java
Fixes #xyz
PIP: #xyz 
When we enable Jcloud offloader for all the topics, some topics need to perform catch-up read from the tiered storage; the ledger offload process and ledger catch-up read process are impacted each other due to the ledger offload and offloaded ledger read sharing the same thread pool. We need to separate the read and write thread pool for the offloader.
Separate the read and write thread pool for the offloader.
*(or)*
*(or)*
*(example:)*
- *Added integration tests for end-to-end deployment …
=> [improve] [broker] Separate offload read and write thread pool

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ProducerBuilder.java
Chunk message can work with shared subscription since https://github.com/apache/pulsar/pull/16202.
Related discussion refer to https://github.com/apache/pulsar/pull/24015
Remove the incorrect doc of chunk message.
=> [fix][doc] fix doc related to chunk message feature.

pip/pip-409.md
PIP documentation.
Implementation PR: https://github.com/apache/pulsar/pull/24020
=> [improve][pip] PIP-409: support producer configuration for retry/dead letter topic producer

pip/pip-407.md
Discussion email: https://lists.apache.org/thread/f8n0fbjj67cpzprxd8qp582ncy7hwtdn
Implementation PR: https://github.com/apache/pulsar/pull/23942
=> [improve][pip] PIP-407 Add a newMessage API to create a message with a schema and transaction

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/GeoPersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ShadowReplicator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
https://github.com/apache/pulsar/pull/21865 removes the expire check for the replicator and compaction subscription. However, this introduces a breaking change in that the replication message never expires.
The TTL policy should be applied to the subscription and replicator.
- Add expire check for the replicator.
=> [fix][broker] Add expire check for replicator

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/InMemoryDeliveryTrackerTest.java
When a group of delay messages reach to theire timestamp, we expect that the dispatch sequence in accordance with the message id.
Yet there is corner case that will break this rule, we can reproduce the problem with the unit test `testDelaySequence` in this pr.
The root reason is that the inner map of `delayedMessageMap` is `Long2ObjectMap<Roaring64Bitmap>` instead of `Long2ObjectSortedMap<Roaring64Bitmap>`.
Change the type of `delayedMessageMap` to `Long2ObjectSortedMap<Long2ObjectSortedMap<Roaring64Bitmap>>`.
*(example:)* …
=> [fix][broker] fix delay queue sequence issue.

docker-compose/kitchen-sink/README.MD, docker-compose/kitchen-sink/docker-compose.yml
Fixes #24039
docker-compose examples don't work due to go-yaml/yaml#789 issue. 
It's necessary to replace `command: >` with `command: |`. More details in #24039 comments.
Similar change was made to website docs in https://github.com/apache/pulsar-site/commit/0df29a62.
- replace `command: >` with `command: |` in the docker-compose example
- remove Pulsar Manager component
- remove Pulsar SQL component
- adjust max heap size parameters to run the cluster with reasonable resources
=> [fix][doc] Workaround Go Yaml issue go-yaml/yaml#789 in docker-compose example

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Keep Netty version up-to-date.
There's a new release 4.1.119.Final with SSL fixes that would be useful for Pulsar too:
* [Release notes](https://netty.io/news/2025/02/26/4-1-119-Final.html)
Upgrade Netty version to 4.1.119.Final
=> [improve] Upgrade Netty to 4.1.119.Final

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/TlsSniTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/Metadata.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyEnableHAProxyProtocolTest.java
In Apache Pulsar, the broker enables producers and consumers to connect to a topic and provides an API to retrieve topic statistics. These stats include a list of connected producers and consumers, along with their IP addresses and connection times. This information is particularly valuable when dealing with a large number of producers and consumers from various client hosts, as it helps troubleshoot issues such as:
Identifying which client host has an active consumer
Detecting if a client host has stopped consuming messages
Diagnosing message backlogs
Thus, mapping the client host IP to the corresponding producer or consumer is crucial.
**The Issue with Reverse Proxies**
However, this mapping breaks when a reverse proxy is used between the client and broker. In such cases, the broker …
=> [improve][broker] Support showing client ip address in client stats while using reverse proxy

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TypedMessageBuilderImpl.java
Fixes #24053 
See #24053 
copy eventTime to messages sent to retry letter topic and DLQ topic
- *Added integration tests* : RetryTopicTest#testRetryTopicProperties, DeadLetterTopicTest#testDeadLetterTopicMessagesWithEventTime
PR in forked repository: https://github.com/SantanuKar43/pulsar/pull/1
=> [fix][client] Copy eventTime to retry letter topic and DLQ messages

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsServlet.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PulsarPrometheusMetricsServlet.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsMetricsResource.java
Prometheus 3.x requires explicit version information in the content type header when scraping metrics. Without this change, Prometheus 3.x might fail scraping metrics from Pulsar endpoints in certain cases where scraping succeeded with Prometheus 2.x. This would cause monitoring issues for users who upgrade to Prometheus 3.x.
See https://prometheus.io/docs/prometheus/latest/migration/#scrape-protocols for more details.
A similar change has been made in BookKeeper with https://github.com/apache/bookkeeper/pull/4208
- Added a constant `PROMETHEUS_CONTENT_TYPE_004` in `PrometheusMetricsServlet` class
- Updated the content type in all metrics endpoints to include `version=0.0.4`:
- `PrometheusMetricsServlet`
- `PulsarPrometheusMetricsServlet`
- `FunctionsMetricsResource`
- Added a test in …
=> [improve][monitor] Add version=0.0.4 to /metrics content type for Prometheus 3.x compatibility

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
The estimated entry count may be a negative value in some cases, then the read operation will get an empty result.
Add a negative check after the long value converts to an int value.
=> [fix] Avoid negative estimated entry count

pulsar-common/src/main/java/org/apache/pulsar/common/api/raw/RawMessageImpl.java, pulsar-common/src/test/java/org/apache/pulsar/common/api/raw/RawMessageImplTest.java
Main Issue: #23925
My fork PR: https://github.com/horizonzy/pulsar/pull/20
If the message metadata contains the same key but with different values, we should make the later value override the previous value.
*(or)*
*(or)*
*(example:)*
=> [fix] [common] Fix RawMessageImpl.getProperties() failed when the message metadata contains the same key but with different values

pip/pip-396.md
This proposal is a follow-up to [PR-23628](https://github.com/apache/pulsar/pull/23628).
=> [improve][pip] PIP-396: Align WindowFunction's WindowContext with BaseContext

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/PersistentTopicTerminateTest.java
After calling `pulsar-admin topics terminate <topic name>`, the variable `ML.currentLedger` will relate to a closed ledger, which is expected.
After reloading the topic, the variable `ML.currentLedger` will relate to `null`, which causes many issues, such as follows
- comsuption
- trim ledgers
- ...
you can reproduce the issue by `testRecoverAfterTerminate`
set the variable `ML.currentLedger` to the latest ledger after loaded up a terminated topic.
=> [fix][broker]Fix failed consumption after loaded up a terminated topic

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java
his PR aims to improve the code clarity in the `ThresholdShedder` class by reorganizing the flow of the `tryLowerBoundaryShedding` method. The primary improvement is the early detection of the `hasBrokerBelowLowerBound` condition before attempting to access broker data.
- Reordered condition checks in `tryLowerBoundaryShedding()`
- Reuses the already calculated value from the parent method 
*(or)*
*(or)*
*(example:)*
- *Extended integration test for …
=> [improve][broker] Optimize ThresholdShedder with improved boundary checks and parameter reuse

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicListService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicListWatcherTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java, pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicList.java
After #16062, we use a notification machine to discover topic changes for pattern subscriptions.
If the user sets a pattern string like `my-property/my-ns/test-pattern.*`(without topic domain) when creating a subscription.
It doesn't receive updates for the latest topics because the topic names include the domain when matching.
For example:
- topicName: `persistent://my-property/my-ns/test-pattern-1`
- topicsPattern: `my-property/my-ns/test-pattern.*`
https://github.com/apache/pulsar/blob/fad925f7c522a30ba9fa005e5788162dd17b21ab/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicListService.java#L73
You can run test to reproduce it: `testSubscribePatterWithOutTopicDomain`
BTW: This issue has always existed, but some clients had a fallback by periodically querying topics for …
=> [fix][broker] Pattern subscription doesn't work when the pattern excludes the topic domain.

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
Fixes #24041 
The test contains the following assertion:
```java
assertEquals(systemCursorOutBytes, systemInBytes)
```
`systemInBytes` is set to the value of the `pulsar_broker_in_bytes_total` metric for the system topic.
`systemCursorOutBytes` is currently set to the value of 
- `pulsar_out_bytes_total` of the system reader subscription or 
- `pulsar_out_bytes_total` of the compaction subscription.
The `pulsar_out_bytes_total` metric is always present for both the system reader and compaction subscription, but the order is not deterministic. Therefore, it happens that instead of setting `systemCursorOutBytes` to `pulsar_out_bytes_total` for the system reader subscription, it is set to `pulsar_out_bytes_total` of the compaction subscription (which always seems to be 0).
```java
double …
```
=> [fix][test] Fix flaky PrometheusMetricsTest.testBrokerMetrics

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactionRecord.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorMXBeanImplTest.java
After the topic compaction is triggered, the corresponding Compaction Write Latency metric in the monitoring system remains at 0.
There is no trigger for the Compaction Write Latency refresh() interface. The StatsBuckets.addAll() method only copies the values into the corresponding bucket, but the values in the bucket need to be updated by calling the refresh interface.
Add writeLatencyStats.refresh() in getCompactionLatencyStats();
*(or)*
*(or)*
*(example:)* …
=> [fix][broker] http metric endpoint get compaction latency stats always be 0

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
https://github.com/apache/pulsar/pull/24020 support configure the producer of retry/dead-letter topic, but it don't take effect.
Make sure the config is used.
*(example:)*
PR in forked repository:  https://github.com/thetumbled/pulsar/pull/73
=> [fix][client] PIP-409 retry/dead letter topic producer config don't take effect.

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerMBeanImpl.java
I think pulsar_storage_size is partially double-counted. Currently
[pulsar_storage_size](https://github.com/apache/pulsar/blob/d0025e79e9b866b9d2b5024f16e4d631e744ecd9/pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java#L177) = [pulsar_storage_logical_size * number of replicas](https://github.com/apache/pulsar/blob/d0025e79e9b866b9d2b5024f16e4d631e744ecd9/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerMBeanImpl.java#L359-L361)
Number of replicas is the same as the bookie write quorum.
pulsar_logical_size doesn't account for the replication, it is sum of customer bytes no matter where they stored at.
and it looks like pulsar_storage_logical_size (calculated …
=> [fix][ml] Corrected pulsar_storage_size metric to not multiply offloaded storage by the write quorum

.asf.yaml
GitHub Discussions in ASF projects now require that they are explicitly enabled in `.asf.yaml`. The discussions at https://github.com/apache/pulsar/discussions are currently disabled due to recent changes in ASF infra which now checks this setting.
- enable discussions in `.asf.yaml`
=> [fix] Bring GitHub Discussions back by enabling discussions in .asf.yaml

pulsar-broker/src/test/java/org/apache/pulsar/common/protocol/ProducerBatchSendTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageKeyBasedContainer.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java
- The first single message can not be extracted and gets an error `ava.lang.IllegalArgumentException: Invalid unknown tag type: 3`
-  And it also leads to a message loss issue. 
- You can reproduce the issue by the new test `testNoEnoughMemSend`
---
- Enable batch send
- Publish async msg-1
- Flush batched messages
- Since there is only `1` msg in the container, the batched message will be built as `[{msg-metadata-1}, {msg-payload}]`.
- Failed build `OpSendMsg`
- The variable `BatchMessageContainerImpl.batchedMessageMetadataAndPayload` is `[{msg-metadata-1}, {msg-payload-1}]` now
- **(Highlight)**: Since `{batch-msg-metadata}` will not be appended into `BatchMessageContainerImpl.batchedMessageMetadataAndPayload`, the variable will be `[{msg-payload-1}]`
- Publish async msg-1
- Flush …
=> [fix][client] Fix building broken batched message when publishing

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TopicPolicies.java
Fixes #24043 
Fixes #24043 
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Fix UnsupportedOperationException while setting subscription level dispatch rate policy

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarMetadataEventSynchronizer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
Currently, Metadata Event Syncrhonizer is not using scheduled-executor because of which Synchronizer is not able to recreate the event producer in case of initial failure. This PR will replace the correct schefduler and makes sure that producer will be created after the retries.
*(or)*
*(or)*
*(example:)*
=> [fix][broker] Fix Metadata Event Synchronizer producer creation retry so that the producer gets created eventually

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java
Currently, metadata-store event synchronizer fails with below BadVersion when it receives even from remote region because it tries to validate version against remote cluster's version which is incorrect because Syncrhonzier already validates timestamp and version under for the same cluster under `shouldIgnoreEvent` method and it doesn't have to use that version otherwise. so, this PR will fix below error
```
025-03-11T02:09:52,424+0000 [configuration-metadata-store-13-1] WARN  org.apache.pulsar.metadata.impl.AbstractMetadataStore - Failed to update metadata /admin/policies/cms/global/test3
org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /admin/policies/cms/global
/test3
at …
```
=> [fix][broker] Fix Metadata event synchronizer should not fail with bad version

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarMetadataEventSynchronizer.java
Currently, if broker tries to publish metadata-event before Metadata Event synchronizer is successfully created producer then it throws below NullPointerException and it should be fixed
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.api.Producer.newMessage()" because "this.producer" is null
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:674) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
at …
```
=> [fix][broker] Fix NPE while publishing Metadata-Event with not init producer

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerDisallowAutoCreateTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/util/RetryMessageUtil.java
clean code.
Move the construction of retry topic name into RetryMessagesUtil.
=> [clean][client] Clean code for the construction of retry/dead letter topic name

pip/pip-406.md
- Discuss email: https://lists.apache.org/thread/w9pq1jp3f22prsr97mxzj1yhdoo1cnc4
- Vote thread: https://lists.apache.org/thread/pmgkf67ph98k5l3lr60rtg96octb397q
- Implatement PR: https://github.com/apache/pulsar/pull/23946
=> [improve][pip] PIP-406: Introduce metrics related to dispatch throttled events

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/MessageDeduplication.java
As described in #24085, the changes in #23697 broke compatibility with existing protocol adapters.
Avoid the IllegalStateException mentioned in #24085. This PR doesn't guarantee that there is compatibility, it simply addresses a single issue introduced by #23697 .
=> [fix][broker] Avoid IllegalStateException when marker_type field is not set in publishing

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageTest.java
Fixes #23825
It seems that the PIP-379 breaks https://github.com/apache/pulsar/pull/7266. For example, given the following configs:
- The consumer whose available permits is 10
- There are 10 entries available, each entry's batch size is 10.
When `subscriptionSharedUseClassicPersistentImplementation` is false (by default), 10 entries will be dispatched to the consumer. When it's true (the behavior before 4.0), only 1 entry will be dispatched to the consumer.
Fix the `maxEntriesInThisBatch` calculation in `PersistentDispatcherMultipleConsumers`. In `testBatchMessageDispatchingAccordingToPermits`, wait until the entries are dispatched to consumers. Then this test would fail without this fix.
=> [fix][broker] Restore the behavior to dispatch batch messages according to consumer permits

pip/pip-292.md
=> [improve][pip] PIP-292: Enforce token expiration time in the Websockets plugin

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryCountEstimator.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCountEstimatorTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ReadOnlyCursorTest.java
The changes introduced in PR #23931 caused a regression in the entry count estimation logic for branch-3.0. While PR #24055 attempted to address this regression, it did not fully resolve the issues, leaving Pulsar's branch-3.0 in a broken state. A `NullPointerException` could occur when using `ReadOnlyManagedLedgerImpl` instances, as the `currentLedger` is null in these cases. `ReadOnlyManagedLedgerImpl` is used in branch-3.0 by PulsarSQL. In master branch, it's currently unused, but since the code exists, it makes sense to fix this bug in the master branch. This PR also contains other improvements.
A problem was also detected in using ManagedLedgerImpl.getNextValidPosition method to find the next valid position. This method is relatively costly and takes the current LAC into account …
=> [fix][ml] Fix issues in estimateEntryCountBySize

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConsumerCloseTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java
When the user has a thread try to subscribe(create a consumer) to a topic.
But the thread get interrupted before getting a response for the consumer creation. 
For example: 
- Thread A - call subscribe() method
- Thread A - blocking on waiting for the response of the consumer creation
- The user framework interrupted `Thread A` for aborting a job.
- Cannot close the consumer since user will get InterruptedException and in this case user can't get consumer object
- So, in the end, this consumer leaked.
- Added a variable named `interruptedBeforeConsumerCreation`. When this variable is true, the consumer needs to be closed.
- You can run  `testInterruptedWhenCreateConsumer ` to reproduce this issue.
=> [fix][client] Fix consumer leak when thread is interrupted before subscribe completes

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorRateLimiterTest.java
The `ReplicatorRateLimiterTest` is crucial for verifying the correct behavior of the rate limiter in replication scenarios. If this test is marked as part of the `quarantine` test group, its failure will not block PR merges. This poses a risk: if the replicator limiter is broken, we will not detect regressions promptly.  
To maintain reliability and catch potential issues early, this test should remain a required test and not be moved to `quarantine`.  
- Move `ReplicatorRateLimiterTest` from the `quarantine` test group to the `broker` test group.
- Refactor assert by `Awaitility`.
=> [fix][test] Move ReplicatorRateLimiterTest to broker test group

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Dispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedSubscriptionStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerDispatchRateLimiterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicDispatchRateLimiterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/SubscriptionStatsTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionStats.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java
Refer to #23945
1. Maintain rate limit event fields in AbstractBaseDispatcher.
2. Output these fields when retrieving topic stats and metrics.
- Add `testSubscriptionStatsDispatchThrottled`, `testBrokerDispatchThrottledMetrics `, `testTopicDispatchThrottledMetrics ` to cover it
=> [improve][broker] PIP-406: Introduce metrics related to dispatch throttled events

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicsConsumerImplTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImpl.java
When **EnableBrokerSideSubscriptionPatternEvaluation** is set to false, the pattern subscription can't discover newly created topics. 
This regression was introduced by PR #21853 and #22854, which removed pattern consumer regularity discovery topic logic: 
https://github.com/apache/pulsar/pull/22854/files#diff-779a47f80b0048bab183870ed4c1ecd07ffd538006cf9358e494bee23405d924L154-L159
- Rollback to poll mode for topic discovery when `watcherFuture` returns an exception.
- Remove `recheckPatternTaskBackoff` as it is unused and does not align with the user-side configuration `patternAutoDiscoveryPeriod`.
- Remove test code like `consumer.getRecheckPatternTimeout().task().run(consumer.getRecheckPatternTimeout()); ` from the unit tests, because these tests now operate under the premise of the …
=> [fix][client] Pattern subscription regression when broker-side evaluation is disabled

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Dispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedNamespaceStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/AggregatedSubscriptionStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/TopicStats.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerDispatchRateLimiterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicDispatchRateLimiterTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/SubscriptionStatsTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/SubscriptionStats.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/SubscriptionStatsImpl.java
#23946
(cherry picked from commit 4f9031bd724558017fabd26fe5ac9a5ec2f863d3)
Cherry-pick #23946
Discuss thread: https://lists.apache.org/thread/1jpk5crbzfpjjnsv9fbom97s11sy4ckt
Cherry-pick #23946
=> [improve][broker][branch-4.0] PIP-406: Introduce metrics related to dispatch throttled events

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
This is expected behavior and the error log should not be printed
- Change topic exists log to warn when create a topic
- none
=> [improve][broker] Change topic exists log to warn

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerConsumerInternalTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
https://github.com/apache/pulsar/pull/23526
Fix inconsistent compression threshold behavior across batching modes. For single message sending, compression is enabled when the message size is greater than or equal to the threshold, while for batch sending, compression occurs when the size is greater than the threshold.
1. Standardize the criteria for determining the threshold to enable compression.
2. Optimize formatting.
3. Enhance testing.
*(or)*
*(or)*
*(example:)* …
=> [fix][client] Fix inconsistent compression threshold behavior across batching modes

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/AbstractKafkaConnectSource.java
We observe our debezium source connector latency min is 1s when traffic is small.
According to the [Kafka Source API definition](https://github.com/a0x8o/kafka/blob/master/connect/api/src/main/java/org/apache/kafka/connect/source/SourceTask.java#L94-L105), when there is no data, the implementation should block for a period of time. We don't need to actively sleep here to avoid CPU spinning.
```
"platform/resource/debezium-postgres-source-0" #20 prio=5 os_prio=0 cpu=15396.95ms elapsed=21030.80s tid=0x00007f8cbc99f020 nid=0x20 waiting on condition  [0x00007f8cbb92c000]
java.lang.Thread.State: TIMED_WAITING (sleeping)
at java.lang.Thread.sleep(java.base@17.0.13/Native Method)
at org.apache.pulsar.io.kafka.connect.AbstractKafkaConnectSource.read(AbstractKafkaConnectSource.java:172)
- locked …
```
=> [improve][io] Remove sleep when sourceTask.poll of kafka return null

pulsar-client/src/main/java/org/apache/pulsar/client/impl/auth/oauth2/ClientCredentialsFlow.java
If `ClientCredentialsFlow` initialization fails, the `exchanger` might be null, which could lead to a NullPointerException when closing.
```
2025-03-11 12:26:43,050 WARN  org.apache.pulsar.client.impl.PulsarClientImpl               [] - Failed to close authentication
java.io.IOException: java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.impl.auth.oauth2.protocol.ClientCredentialsExchanger.close()" because "this.exchanger" is null
```
- Add null check.
=> [improve][client] Prevent NullPointException when closing ClientCredentialsFlow

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryCountEstimator.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCountEstimatorTest.java
Following up on #24089 changes. The changes cause a regression which is visible in branch-3.0 where a test fails (`org.apache.pulsar.compaction.CompactionTest#testDispatcherMaxReadSizeBytes`). This test is different in newer branches. The regression is caused by the logic added in #24089 to use `DEFAULT_ESTIMATED_ENTRY_SIZE + BOOKKEEPER_READ_OVERHEAD_PER_ENTRY` as the default average entry size. 
Another gap is that when all ledgers are empty, no average size would be used. That is also fixed in this PR
- when the ledger is completely empty, don't estimate the number of entries, simply return 1 as the estimated entry count
- when all ledgers are empty beyond the read position, find the latest ledger with entries to calculate the average entry count to be used in the estimation
- add test …
=> [fix][ml] Don't estimate number of entries when ledgers are empty, return 1 instead

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataTeardown.java
The current tear-down logic is listing ledgers and then deleting them. So, there's a race condition if some internal logic has deleted the schema ledger, which will cause the down process to fail.
- Ignore deleted ledgers while tear-down.
=> [fix][misc]: ignore deleted ledger when tear down cluster

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/protocol/PulsarClientBasedHandler.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ExclusiveProducerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/ConsumerCreationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/ProducerCreationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/LookupServiceTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java
In Apache Pulsar, clients can produce or consume messages using a fully qualified partition topic name (`public/default/test-partitioned-topic-partition-N`). However, if the topic metadata does not exist and `allowAutoTopicCreationType=non-partitioned` is enabled, Pulsar automatically creates the topic as non-partitioned. This leads to inconsistencies when listing topics, as the expected partitioned topic structure is not maintained.
This issue is especially prevalent in geo-replicated environments, where topic metadata may not be fully synchronized across all regions. Currently, Pulsar lacks validation to ensure that the topic type (partitioned or non-partitioned) matches the actual partition metadata.
- Added a topic consistency check:
- **For non-partitioned topic**: If partition …
=> [fix][broker] Add topic consistency check

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryCountEstimator.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCountEstimatorTest.java
Following up on #24089 changes. The changes cause a regression which is visible in branch-3.0 where a test fails (`org.apache.pulsar.sql.presto.TestCacheSizeAllocator#cacheSizeAllocatorTest`). This test is missing from newer branches. The regression is caused by the logic added in #24089 to return 0 when bytes size <= 0. 
- return 1 when bytes size <= 0 so that the previous behavior is preserved
=> [fix][ml] Return 1 when bytes size is 0 or negative for entry count estimation

jetcd-core-shaded/pom.xml
When using the IDEA to run the test, which can not the `io.etcd.jetcd.Client` and `io.etcd.jetcd.ByteSequence` classes, this plugin can help the IDEA to find these classes.
- Add `build-helper-maven-plugin` plugin for `jetcd-core-shaded` module.
=> [fix][test] Add build-helper-maven-plugin for jetcd-core-shaded

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java
Fixes #24034
This backports  missed CompactedTopicImpl deadlock fixes #20697 and #20984 to branch 3.0
While testing locally, this test fails with the changes:
```
[ERROR] Tests run: 43, Failures: 1, Errors: 0, Skipped: 38, Time elapsed: 192.271 s <<< FAILURE! - in org.apache.pulsar.compaction.CompactedTopicTest
[ERROR] org.apache.pulsar.compaction.CompactedTopicTest.testCompactionWithTopicUnloading  Time elapsed: 40.658 s  <<< FAILURE!
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a org.apache.pulsar.compaction.CompactedTopicTest expected [1000] but found [501] within 30 seconds.
at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
at …
```
=> [fix][broker][branch-3.0] Backport missed CompactedTopicImpl deadlock fixes #20697 and #20984 to branch 3.0

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/OxiaMetadataStore.java
We found a lot of error logs with "the notification type Unknown" for Oxia metadata and I think it's best to classify this as warn level.
```
2025-03-26T03:24:31,999+0000 [grpc-default-worker-ELG-2-1] ERROR org.apache.pulsar.metadata.impl.oxia.OxiaMetadataStore - Unknown notification type KeyRangeDelete[startKeyInclusive=/sequenceId/, endKeyExclusive=/sequenceId/-0000000 │
│ 0000000000015]                                                                                                                                                                                                                          │
│ 2025-03-26T03:24:31,999+0000 [grpc-default-worker-ELG-2-1] ERROR org.apache.pulsar.metadata.impl.oxia.OxiaMetadataStore - Unknown notification type …
```
=> [improve][meta] Change log level from error to warn for unknown notification types in OxiaMetadataStore

pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java
Fixes #20386
It seems that messages are dropped very fast, so the drop stats are already 0 again once we reach the assertion.
- Sleep 10ms after producing a message. With this, the time it takes until all messages are produced is extended. The drop stats are > 0 for a longer time (and at the time when we reach the assertion).
- Increase the number of threads used for the producer from 5 to 10 to increase concurrency and the probability that messages are dropped.
PR in forked repository: https://github.com/pdolif/pulsar/pull/9
=> [fix][test] Fix flaky NonPersistentTopicTest.testMsgDropStat

pulsar-function-go/examples/go.mod, pulsar-function-go/examples/go.sum, pulsar-function-go/go.mod, pulsar-function-go/go.sum
There's CVE-2025-30204 in the pulsar-function-go dependencies.
upgrade github.com/golang-jwt/jwt/v5 to v5.2.2
=> [fix][sec] Upgrade jwt/v5 to 5.2.2 to address CVE-2025-30204

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalPartitionedTest.java
- Envs: `broker.conf: allowAutoTopicCreationType = TopicType.PARTITIONED`
- Users may start 2 clusters with the Geo-Replication feature with Global ZK
- Users want to hire one cluster, so remove the cluster from `namespace-level replicatedClusters`
- Broker will remove the topics of the cluster removed automatically.
- Issue occurs:
- The system topic `__change_events` being deleted first.
- User topics can not be deleted anymore, because the operation `delete topic-level policies` can not be executed successfully anymore.
- The task `topic.checkReplication` and other operations will retry again and again
You can reproduce by the new test `OneWayReplicatorUsingGlobalPartitionedTest. testRemoveCluster`
- Skip removing topic-level policies if the system topic `__change_event` has been …
=> [fix] [broker] topics infinitely failed to delete after remove cluster from replicated clusters modifying when using partitioned system topic

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumerMaxEntriesInBatchTest.java
Fixes https://github.com/apache/pulsar/issues/24094
in order to test MaxEntriesInThisBatch in the PersistentDispatcherMultipleConsumers, extract from trySendMessagesToConsumers() into a method.
* If the box was checked, please highlight the changes*
PR in forked repository: https://github.com/3pacccccc/pulsar/pull/1
=> [improve][broker] extract getMaxEntriesInThisBatch into a method and add unit test for it

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/DisabledCreateTopicToRemoteClusterForReplicationTest.java
Fixes https://github.com/apache/pulsar/issues/23827
fix flaky-test, I think the flaky-test is due to replication not complete yet within 10 seconds, so I added to 30 seconds and change the assertion into await().atMost(30, TimeUnit.SECONDS)
PR in forked repository: https://github.com/3pacccccc/pulsar/pull/2
=> [fix][test] Fix flaky DisabledCreateTopicToRemoteClusterForReplicationTest

docker/pulsar/Dockerfile, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceChaosTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalPartitionedTest.java
Building docker images have started to fail due to the use of a deprecated `--compress zip-9` argument for `jlink`.
This parameter was deprecated in Java 16. It seems that the removal was delayed and now master branch is broken with most recent Corretto 21 and 17 JDK versions (Corretto-21.0.6.7.1 and also Corretto-17.0.14.7.1). 
Valid `jlink` compress argument options:
```
-c, --compress=<0|1|2>                Enable compression of resources:
Level 0: No compression
Level 1: Constant string sharing
Level 2: ZIP
```
The replacement for `--compress zip-9`  is `--compress=2` (zip). 
Replace `--compress zip-9` with `--compress=2`
=> [fix][build] Fix docker image building by replacing deprecated and removed compress argument

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceChaosTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalPartitionedTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/ConsumerCreationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/ProducerCreationTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java
Fixes https://github.com/apache/pulsar/issues/24152
https://github.com/apache/pulsar/pull/24118 breaks `checkTopicExists`.  The topic metadata exists, but the topic may not exist.
~These changes are already covered by `org.apache.pulsar.broker.namespace.NamespaceServiceTest`. However, since this test belongs to the `flaky` test group, regressions might not be reliably caught.~
- Directly query single topic existence when the topic is partitioned.
- Use  `NotFoundException ` instead of `TopicDoesNotExistException` that is introduced by #24118.
=> [fix][broker] Directly query single topic existence when the topic is partitioned

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BkEnsemblesChaosTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceChaosTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java
Fixes #24160
There are multiple issues in the test framework class CanReconnectZKClientPulsarServiceBaseTest which make BrokerServiceChaosTest flaky and the testing itself unreliable.
- when starting the termination, wait for the connection to be terminated at least once
- when stopping the termination, wait for the thread to finish
- improve readability of the code by renaming methods / variables
=> [fix][test] Fix flaky BrokerServiceChaosTest

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java
Fixes #24160
`stopLocalMetadataStoreAlwaysReconnect` should wait for the zk to reconnect.
Listen for metadata store session events, and upon invoking `stopLocalMetadataStoreAlwaysReconnect`, wait until a `Reconnected` is received before proceeding."
=> [fix][test] Fix flaky BrokerServiceChaosTest.testFetchPartitionedTopicMetadataWithCacheRefresh

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicationTopicGcTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicationTopicGcUsingGlobalZKTest.java
- Configure: `brokerDeleteInactivePartitionedTopicMetadataEnabled=true`
- Issue 1: Pulsar leaves orphan topic policies and topic schemas after cleaning the partitioned topic. you can reproduce the issue with the new test `testTopicGC`
- Issue 2:
- Pulsar will lead an orphan schema and a topic-level policy if users are enabling bidirectional Geo-Replication with a global ZK, you can reproduce the issue by `ReplicationTopicGcUsingGlobalZKTest`
- This feature will lead a consumption issue if you are enabling one-way Geo-Replication with a global ZK. You can reproduce the issue by `ReplicationTopicGcUsingGlobalZKTest`
- fix issue 1
- add notes for issue 2
=> [fix][broker] The feature brokerDeleteInactivePartitionedTopicMetadataEnabled leaves orphan topic policies and topic schemas

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerConsumerInternalTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ProducerBuilder.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerBuilderImpl.java
PIP: https://github.com/apache/pulsar/pull/23526
Currently, the `ProducerBuilder` API lacks the ability to directly configure the `compressMinMsgBodySize` property during producer initialization. Users are forced to modify the internal `ProducerConfigurationData` post-creation, which:  
1. **Violates encapsulation** by exposing internal configuration fields.  
2. **Introduces inconsistency** with other compression settings (e.g., `compressionType`) that are already configurable via the builder.  
3. **Creates usability hurdles**, requiring workarounds like:  
```java  
Producer<byte[]> producer = client.newProducer().topic("test").create();  
producer.conf.setCompressMinMsgBodySize(1024); // Insecure and error-prone  
```  
This change aligns the builder API with standard compression …
=> [fix][client]Add setCompressMinMsgBodySize method to ProducerBuilder for compression configuration flexibility

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/scheduler/TransferShedder.java
Currently, ExtensibleLoadManager overrides orphan ownerships one by one while holding the monitor lock. This can delay the synchronized serviceUnitStateChannel.started() call(required for SystemTopicPoliciesService.getTopicPoliciesAsync and others) when the metadata service is slow(is overloaded).
- override orphan ownership concurrently (max 10 bundle ownerships by default and configurable by `loadBalancerServiceUnitStateMaxConcurrentOverrides`).
- removed unnecessary monitor lock from doCleanup
- minor change: put `TopBundlesLoadData is empty` log under debug flag
=> [fix][broker] fix ExtensibleLoadManager to override the ownerships concurrently without blocking load manager thread

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/bookkeeper/mledger/impl/ConsumerUnsubscribeIntegrationTest.java
We encountered an issue after trying to delete a topic multiple times, and all deletions failed, and there are some bundle rebalnces. After checking the heap dump. We found a subscription that relates to a delete cursor.
**Issue**:
- The subscription has a cursor
- but the cursor has been removed from the managed ledger
- Skip deleting the cursor if it has already was deleted
=> [fix][ml] Skip deleting cursor if it was already deleted before calling unsubscribe

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AuthZTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespaceAuthZTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TransactionAndSchemaAuthZTest.java
[Mockito is not thread safe](https://github.com/mockito/mockito/wiki/FAQ#is-mockito-thread-safe) and modifying mocks in multi-threaded code will result in failures such as this one:
```
[ERROR] Failures:
[ERROR]   NamespaceAuthZTest.testMaxConsumersPerTopic:1537->setAuthorizationPolicyOperationChecker:183 » UnfinishedStubbing
Unfinished stubbing detected here:
-> at org.apache.pulsar.broker.admin.NamespaceAuthZTest.setAuthorizationPolicyOperationChecker(NamespaceAuthZTest.java:173)
E.g. thenReturn() may be missing.
Examples of correct stubbing:
when(mock.isOk()).thenReturn(true);
when(mock.isOk()).thenThrow(exception);
doThrow(exception).when(mock).someVoidMethod();
Hints:
1. missing thenReturn()
2. you are trying to stub a final method, which is not supported
3. you are stubbing the …
```
=> [fix][test] Fix UnfinishedStubbing issue in AuthZTests

pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
The test CompactionTest.testDeleteCompactedLedgerWithSlowAck fails with PR #23980. The test appears to be invalid and needs to be revisited.
- revisit CompactionTest.testDeleteCompactedLedgerWithSlowAck
- replace the usage of long deprecated topic naming format where the cluster name is part of the topic name
- ["Many test classes are using deprecated topic naming format V1 which includes the cluster name" on dev mailing list](https://lists.apache.org/thread/60ysbhrgxfltyjwqybgzct1t5csztn2s)
- I'm planning to do this modification to other test classes later
- this format is not compatible with topic policies
- improve the CompactionTest test class by doing some other cleanup such are using static imports for assertion methods.
=> [fix][test] Fix invalid test CompactionTest.testDeleteCompactedLedgerWithSlowAck

docker/pulsar-all/pom.xml, docker/pulsar/pom.xml, pom.xml, tests/docker-images/java-test-image/pom.xml, tests/docker-images/latest-version-image/pom.xml
The `docker-maven-plugin` supports skipping Docker image tags using the `docker.skip.tag` property. However, it does not work correctly when building multi-architecture images using `buildx`. As a workaround, the plugin provides a `skipTag` option in the [build configuration](https://dmp.fabric8.io/#build-configuration), which successfully skips tagging in multi-arch builds/pushes.
**Issue (Old behavior):**
Running the following command:
```shell
cd docker/pulsar
mvn install -Pdocker -Ddocker.skip.tag=true -Ddocker.platforms=linux/arm64,linux/amd64
```
Still resulted in tagging:
```
--tag apachepulsar/pulsar:latest
--tag apachepulsar/pulsar:latest
--tag apachepulsar/pulsar:4.1.0-SNAPSHOT-e8be56d
```
**Fixed behavior:**
By using the `skipTag` configuration:
```
--tag …
```
=> [fix][build] Fix skipTag and use explicit tag for image name

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/IncrementPartitionsTest.java
https://github.com/apache/pulsar/pull/24056 could become flaky, so I will fix it.
Fixed waiting for subscription validation until stats are created.
PR in forked repository: https://github.com/kontotto/pulsar/pull/6
=> [fix][test] Improve reliability of IncrementPartitionsTest

pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/PulsarTestContext.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MockZooKeeperMetadataStoreProvider.java, testmocks/src/main/java/org/apache/zookeeper/MockZooKeeper.java, testmocks/src/main/java/org/apache/zookeeper/MockZooKeeperSession.java
After #23988, MockZooKeeper is correctly single threaded and an injected delay will block the execution of this code in ZKSessionWatcher:
https://github.com/apache/pulsar/blob/6e8c3496647df275071190aec9d29ecbcee55e80/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKSessionWatcher.java#L108-L115
This will trigger a ConnectionLost session event. That's why a delay should be kept under 2000 ms. 
Currently MockZooKeeper's session timeout is hard coded to 30000ms and the check interval is 1/15 of this, therefore 2000ms.
When there's a test that blocks the ZooKeeper thread for more than 2000ms, it will result in a ConnectionLost event.
This PR makes the session timeout configurable and it's possible to increase the session timeout for tests where it's necessary to use a longer …
=> [improve][test] Use configured session timeout for MockZooKeeper and TestZKServer in PulsarTestContext

pip/pip-404-Introduce-per-ledger-properties.md, pip/pip-xyz-Introduce-per-ledger-properties.md
PIP doc
*(or)*
*(or)*
*(example:)*
=> [improve][pip] PIP-404: Introduce per ledger properties

docker/kinesis-producer-alpine/Dockerfile, docker/kinesis-producer-alpine/README.md, docker/kinesis-producer-alpine/build-alpine.sh
The current [`apachepulsar/pulsar-io-kinesis-sink-kinesis_producer` image](https://hub.docker.com/r/apachepulsar/pulsar-io-kinesis-sink-kinesis_producer/tags) has been built with Alpine 3.20.
Some strict security scanners seem to flag the binary due to outdated static libraries or something similar.
- Update Alpine version to 3.21 in the docker image
- The image will be built and pushed separately to https://hub.docker.com/r/apachepulsar/pulsar-io-kinesis-sink-kinesis_producer/tags. This is used in the pulsar-all Dockerfile to provide the kinesis_producer binary for the Pulsar IO Kinesis Sink.
=> [improve][build] Build apachepulsar/pulsar-io-kinesis-sink-kinesis_producer with Alpine 3.21

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java
Proxy overwrites multiple error codes to `LookupError`, which may cause issues that many expressions, such as `ex instance of TopicDoesNotExistException` get a `false` result even if the broker responds a `TopicDoesNotExistException`
The code lines that use the expression `ex instance of TopicDoesNotExistException`
- https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L988
- https://github.com/apache/pulsar/blob/master/pulsar-websocket/src/main/java/org/apache/pulsar/websocket/AbstractWebSocketHandler.java#L160
- https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java#L429
- ...
- Correct the error code
=> [fix][proxy] Fix incorrect client error when calling get topic metadata

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/validator/SchemaDataValidator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/validator/StructSchemaDataValidator.java, pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java, pulsar-broker/src/test/java/org/apache/pulsar/schema/compatibility/SchemaCompatibilityCheckTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericSchemaImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/generic/GenericSchemaTest.java
- User can upload an Avro-Union schema by `pulsar-admin` API
- However, the schema uploaded can not be used, users will get an error "Not a record" when creating a producer with `AUTO_PRODUCE` schema.
- Deny uploading an Avro-Union schema
- Improve the logs when creating a producer failed due to an invalidated schema
=> [fix][schema] Reject unsupported Avro schema types during schema registration

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateData.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateDataTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/Backoff.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataCache.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataCacheConfig.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/cache/impl/MetadataCacheImpl.java, pulsar-metadata/src/main/java/org/apache/pulsar/metadata/tableview/impl/MetadataStoreTableViewImpl.java, pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java
Although we do CAS updates on ServiceUnitStateMetadataStoreTableViewImpl.put, ServiceUnitStateData.versionId can still conflict if cache.readModifyUpdateOrCreate retries multiple times with the updated value's GetResult.Stats.version. 
We should fail-fast if the readModifyUpdateOrCreate fails once(e.g. upon first BadVersionException) not to cause inconsistent ServiceUnitStateData views from different brokers.
Also, to fix the worst case, any inconsistent ServiceUnitStateData views, ServiceUnitStateMetadataStoreTableViewImpl should update the latest value(not only compare the versionId but also all fields) from the MetadataStore by its cache refresh cycles.
- Added No backoff config in MetadataCacheConfig and use it from ServiceUnitStateMetadataStoreTableViewImpl.
- Update …
=> [fix][broker] Fixes Inconsistent ServiceUnitStateData View (ExtensibleLoadManagerImpl only)

pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPoliciesImpl.java, pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/OffloadPoliciesTest.java
Fixes #xyz
PIP: #xyz 
When we set cluster level `managedLedgerDataReadPriority` to `bookkeeper-first` in conf/broker.conf
https://github.com/apache/pulsar/blob/f2618c15bb5a9f3fcb577068584df5d0e2e4f335/conf/broker.conf#L1262-L1264
Then use the command `bin/pulsar-admin namespaces set-offload-threshold -s 0 <namespace>` to set the offload threshold in namespace level to trigger topic offload automatically.
However, the broker side will create an empty OffloadPolicy when setting the offload threshold
https://github.com/apache/pulsar/blob/f2618c15bb5a9f3fcb577068584df5d0e2e4f335/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L2174-L2176
However, the empty OffloadPolicy will set the `OffloadedReadPriority` to `TIERED_STORAGE_FIRST` in …
=> [fix][broker] Fix cluster level OffloadedReadPriority to bookkeeper-first does not work

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelTest.java
There was a bug from this PR, https://github.com/apache/pulsar/pull/24156 that causes NPE during the ownership clean-up, when overriding orphan system bundle ownerships. 
- fix the wrong iterator.next()
=> [fix][broker] Fix NPE from the wrong iterator in the ownership cleanup job(ExtensibleLoadManagerImpl only)

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
Fixes #24193
NamespacesTest.testNamespacesApiRedirects is flaky due to invalid reuse of mocks.
- fix flakiness by creating new instances of with `mock(AsyncResponse.class)`
=> [fix][test] Fix flaky NamespacesTest.testNamespacesApiRedirects

pip/pip-402-role-anonymize.md, pip/pip-402.md
PIP for https://github.com/apache/pulsar/pull/23386
=> [feat][pip] PIP-402: Role Anonymizer for Pulsar Logging

pom.xml, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStore.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KafkaSinkTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/AvroKafkaSourceTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sources/KafkaSourceTester.java
- addresses CVE-2024-31141 in the Pulsar IO Kafka connectors
- upgrade `kafka-client.version` used in Pulsar IO Kafka connectors to `3.8.1`
- according to https://endoflife.date/apache-kafka, 3.8.x is currently supported
- upgrade `confluent.version` to `7.8.2` since it matches the Kafka version `3.8.x` according to ["Confluent Platform and Apache Kafka compatibility" page](https://docs.confluent.io/platform/current/installation/versions-interoperability.html#cp-and-apache-ak-compatibility)
=> [improve][io] Upgrade Kafka client and compatible Confluent platform version

pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java
ProxyTest and derived ProxyDisableZeroCopyTest leak a lot of resources.
```
Warning: Summary: Tests in class org.apache.pulsar.proxy.server.ProxyTest created 1080 new threads. There are now 1090 threads in total.
Warning: Summary: Tests in class org.apache.pulsar.proxy.server.ProxyDisableZeroCopyTest created 1080 new threads. There are now 1090 threads in total.
```
In addition to this, the test `testGetPartitionedMetadataErrorCode` doesn't pass without a retry. There are conflicting tests that expect different `allowAutoTopicCreationType` and `defaultNumPartitions` settings.
- fix resource leaks
- remove `invocationCount = 100` for `testRegexSubscriptionWithTopicDiscovery`
- fix `allowAutoTopicCreationType` and `defaultNumPartitions` config conflicts
=> [fix][test] Fix resource leaks in ProxyTest and fix invalid tests

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalPartitionedTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java
Both `OneWayReplicatorUsingGlobalPartitionedTest` and `OneWayReplicatorUsingGlobalZKTest` extend `OneWayReplicatorTest`. As a result, when a new test case is added to `OneWayReplicatorTest`, it is also executed in the `OneWayReplicatorUsingGlobalPartitionedTest` and `OneWayReplicatorUsingGlobalZKTest`. However, not all test cases are applicable to the global zk scenarios. This forces developers to explicitly disable certain tests in `OneWayReplicatorUsingGlobalPartitionedTest` and `OneWayReplicatorUsingGlobalZKTest`, leading to increased complexity and reduced maintainability.
testcases:
```
[root]
pulsar
OneWayReplicatorUsingGlobalPartitionedTest
OneWayReplicatorUsingGlobalPartitionedTest.testCloseTopicAfterStartReplicationFailed …
```
=> [cleanup][test] Cleanup OneWayReplicatorUsingGlobalPartitionedTest and OneWayReplicatorUsingGlobalZKTest

pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java
- This change is a follow-up on https://github.com/apache/pulsar/pull/23980, which added the log.
- If `CompactedTopicImpl.newCompactedLedger` was called more than once with the same `compactedLedgerId`, it will trigger a ledger deletion, which causes a data loss event.
- The condition of the log should be `previousLedger == @param-newLedger`, but it is `@param-newLedger == @param-newLedger`
- The impact is that there would be invalid error logs for every compaction
Fix the wrong condition of printing error log
=> [fix][broker] Fix compaction service log's wrong condition

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/AdminApiTransactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/OwnerShipForCurrentServerTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageWithBatchIndexLevelTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionProduceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionLowWaterMarkTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionStablePositionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/coordinator/TransactionMetaStoreTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckInMemoryDeleteTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/PendingAckPersistentTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/CustomMessageIdTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/UnloadSubscriptionTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BatchMessageIndexAckTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationData.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerBuilderImplTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/transaction/TransactionTest.java
See #23567 
Enable `enableBatchIndexAcknowledgment` (for client) and `acknowledgmentAtBatchIndexLevelEnabled` (for broker) by default. Remove all explicit enabling in tests to verify it still works.
*(or)*
*(or)*
*(example:)*
PR in forked repository: https://github.com/BewareMyPower/pulsar/pull/39
=> [improve][client] PIP-391: Enable batch index ACK by default

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-functions/runtime-all/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceDepsTest.java
Apache Commons libraries haven't been upgraded recently. In BookKeeper, the Apache Commons libraries were upgraded with PR https://github.com/apache/bookkeeper/pull/4582. It's better to keep the versions upgraded to recent versions to avoid compatibility issues as there were in BookKeeper where commons-codec wasn't compatible with the commons-compress version. It's also useful to keep the versions in sync with versions used in BookKeeper since Pulsar's distribution of BookKeeper uses the versions assigned in Pulsar's pom.xml.
- upgrade 
- commons-cli to 1.9.0
- commons-codec to 1.18.0
- commons-io to 2.19.0
- commons-compress to 1.27.0
- commons-lang3 to 3.17.0
- commons-text to 1.13.1
=> [improve] Upgrade Apache Commons library versions to compatible versions

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalPartitionedTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java
See also https://github.com/apache/pulsar/pull/24200#issuecomment-2827963819
> Sorry, I did not completely review #24200. I assumed that you added new tests in `OneWayReplicatorUsingGlobalZKTest` and `OneWayReplicatorUsingGlobalPartitionedTest`, which makes #24200 meaningful. But the exact changes are that you just copied tests from the super class into the child classes. I will revert this PR, because it did nothing.
- `OneWayReplicatorTest` -- has sub classes -> `OneWayReplicatorUsingGlobalZKTest` and `OneWayReplicatorUsingGlobalPartitionedTest`, they shared some tests 
- Other tests in `OneWayReplicatorUsingGlobalZKTest` and `OneWayReplicatorUsingGlobalPartitionedTest` have not be implemented completely.
https://github.com/apache/pulsar/pull/24200 makes the three test classes …
=> [revert][broker] Revert #24200: Cleanup OneWayReplicatorUsingGlobalPartitionedTest and OneWayReplicatorUsingGlobalZKTest

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTopicPoliciesTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/BacklogQuota.java
- `pulsar-admin namespaces set-backlog-quota <namespace>` does not allow a null attribute `policy`, but HTTP API `POST /admin/v2/namespaces/{namespace}/backlogQuota` allows.
- `pulsar-admin topicPolicies set-backlog-quota <namespace>` does not allow a null attribute `policy`, but HTTP API `POST /admin/v2/namespaces/{topic}/backlogQuota` allows.
It leads a NPE
```
2025-04-21T03:04:02,254+0000 [pulsar-backlog-quota-checker-OrderedScheduler-0-0] INFO  org.apache.pulsar.broker.service.BacklogQuotaManager - Backlog quota type destination_storage exceeded for topic [persistent://public/default/internal-partition-1]. Applying [null] policy
2025-04-21T03:04:02,254+0000 [pulsar-backlog-quota-checker-OrderedScheduler-0-0] ERROR org.apache.pulsar.broker.service.BrokerService - Error when …
```
=> [fix][admin] Backlog quota's policy is null which causes a NPE

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTenantTest.java
Fixes https://github.com/apache/pulsar-client-go/issues/1354
When creating or updating the tenant info, the broker didn't check the null value, so it got the `java.lang.NullPointerException`.
- Ensures clusters are validated when `allowedClusters` is null or empty.
=> [fix][broker] Fix tenant creation and update with null value

pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMappingTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/AbstractDeliveryTrackerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/DelayedDeliveryTrackerFactoryTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/InMemoryDeliveryTrackerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/delayed/bucket/BucketDelayedDeliveryTrackerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicPublishRateThrottleTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ZKReconnectTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProduceWithMessageIdTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/PulsarClientImplTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/TopicListWatcherTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/UnAckedMessageTrackerTest.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/BlobStoreBackedInputStreamTest.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedInputStreamTest.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlockAwareSegmentInputStreamTest.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/OffloadIndexV2Test.java
In Pulsar, there's a thread leak detector in CI which reports tests that start new leaked threads during the test run.
In addition, there's a WIP PR #23956 for adding a reliable way to detect Netty ByteBuf and Timer leaks.
While reviewing some of the detected leaks, I fixed several of the most impactful ones.
The reason why it's useful to pay attention to resource leaks is that many developers copy-paste or reuse tests from other locations. If there's a resource leak in a template, it easily multiplies over time when more resource-leaking tests are added.
The problems caused by resource leaks include higher memory consumption, forcing tests to run with less available memory. In some test jobs in CI, a single test JVM runs for 20 to 30 minutes. In some cases, leaked threads might be doing …
=> [fix][test] Fix multiple resource leaks in tests

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageWithBatchIndexLevelTest.java
https://github.com/apache/pulsar/actions/runs/14659080996/job/41139780758?pr=24209#step:11:1775
```
-------------------------------------------------------------------------------
Test set: org.apache.pulsar.broker.service.BatchMessageWithBatchIndexLevelTest
-------------------------------------------------------------------------------
Tests run: 91, Failures: 1, Errors: 0, Skipped: 22, Time elapsed: 97.442 s <<< FAILURE! - in org.apache.pulsar.broker.service.BatchMessageWithBatchIndexLevelTest
org.apache.pulsar.broker.service.BatchMessageWithBatchIndexLevelTest.testBatchMessageAck  Time elapsed: 10.359 s  <<< FAILURE!
org.awaitility.core.ConditionTimeoutException: Assertion condition expected [20] but found [36] within 10 seconds.
at …
```
=> [fix][test] Fix flaky BatchMessageWithBatchIndexLevelTest.testBatchMessageAck

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Keeping Netty up-to-date and getting minor bug fixes into Pulsar.
- [Netty 4.1.120.Final release notes](https://netty.io/news/2025/04/23/4-1-120-Final.html)
- [Netty 4.1.121.Final release notes](https://netty.io/news/2025/04/24/4-1-121-Final.html)
Upgrade Netty to 4.1.121.Final
=> [improve] Upgrade Netty to 4.1.121.Final

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageFinder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java
**Background**
https://github.com/apache/pulsar/pull/22792 improved the behavior that searching messages by timestamp. For example:
There are ledgers as follows:
```json
[{
"ledger": "1",
"entries": "10",
"closed_time": "1000"
},{
"ledger": "2",
"entries": "10",
"closed_time": "1010"
},{
"ledger": "3",
"entries": "10",
"closed_time": "3000"
}]
```
And the config `broker.conf -> managedLedgerCursorResetLedgerCloseTimestampMaxClockSkewMillis` is `20ms`, when you search for timestamp `1000`, the broker will find ledgers whose timestamp is larger than `ledger.closed_time-20` and less than `ledger.closed_time+20`. Then the result range is `[1:0 ~ 3:9]`.
Since we have the configuration `broker.conf -> managedLedgerCursorResetLedgerCloseTimestampMaxClockSkewMillis`, the entries `[1:0 ~ 1:8]` can …
=> [improve][broker]Improve the feature "Optimize subscription seek (cursor reset) by timestamp": search less entries

pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/OpSendMsgQueueTest.java
`ProducerImpl.OpSendMsgQueue` is a customized collection, but it will not decrease `size` when calling `ProducerImpl.OpSendMsgQueue.Iterator -> remove()`, which causes incorrect `producer.getPendingQueueSize()`
- fix the issue
=> [fix][client] Fix incorrect producer.getPendingQueueSize due to incomplete queue implementation

pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java
Fixes #24227
See #24227. Using the REST API for publishing messages to the broker leads to `io.netty.util.internal.OutOfDirectMemoryError`.
Release the `ByteBuf` after passing it on to publishing by the broker. The reference count will get increased internally.
=> [fix][broker] Fix ByteBuf memory leak in REST API for publishing messages

pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java
When users use TXN, many commands are sent to brokers, such as the following:
- `NEW_TXN`
- `ADD_PARTITION_TO_TXN`
- `ADD_SUBSCRIPTION_TO_TXN`
- `END_TXN`
But once a command times out, they all print the same log as below, which is not clear enough to know what happened
```
org.apache.pulsar.client.api.PulsarClientException$TimeoutException: Could not get response from transaction meta store within given timeout.
at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:1043)
at org.apache.flink.connector.pulsar.common.utils.PulsarTransactionUtils.createTransaction(PulsarTransactionUtils.java:55)
at org.apache.flink.connector.pulsar.sink.writer.topic.ProducerRegister.getOrCreateTransaction(ProducerRegister.java:290)
at …
```
=> [improve][client]Improve transaction log when a TXN command timeout

pulsar-io/kafka-connect-adaptor/pom.xml, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/AbstractKafkaConnectSource.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSource.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSourceTest.java
The current implementation of the Kafka Connect adaptor in Pulsar IO does not support [Kafka Connect transforms](https://github.com/apache/kafka/tree/3.8/connect/transforms/src/main/java/org/apache/kafka/connect/transforms) and [predicates](https://github.com/apache/kafka/tree/3.8/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/predicates). This limits the flexibility and potential of using Kafka Connect-based source connectors, such as the Debezium PostgreSQL source connector, which [rely heavily on transformations](https://debezium.io/documentation/reference/1.9/transformations/index.html) to modify, filter, or enrich records before they are ingested. By adding support for transforms, we enable users to fully leverage these connectors' capabilities, sparing them the …
=> [improve][io] support kafka connect transforms and predicates

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Fixes #24114
Upgrade Jetty to 9.4.57.v20241219 to address CVE-2024-6763
Jetty 9.4.57.v20241219 contains backported CVE-2024-6763 fix in https://github.com/jetty/jetty.project/pull/12532 although it's not explicitly mentioned and most security scanners don't yet contain the information that it's been addressed in 9.4.57.
More details:
* https://github.com/jetty/jetty.project/issues/12630
* https://github.com/jetty/jetty.project/releases/tag/jetty-9.4.57.v20241219
Note: The backport is a partial mitigation and Jetty 9.4.57 will continue to be marked as vulnerable. There's a discussion and explanation here: https://gitlab.eclipse.org/security/cve-assignement/-/issues/25#note_2968611
=> [fix][sec] Upgrade Jetty to 9.4.57.v20241219 to mitigate CVE-2024-6763

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Upgrade errorprone to 2.38.0 for Java 24 byte code support.
=> [improve][build] Upgrade errorprone to 2.38.0

bin/bookkeeper, bin/function-localrunner, bin/pulsar, bin/pulsar-admin-common.cmd, bin/pulsar-admin-common.sh, bin/pulsar-perf, conf/bkenv.sh, conf/pulsar_env.sh, src/pulsar-io-gen.sh
Adapt startup scripts for these Java 24 changes:
- [JEP 471: Deprecate the Memory-Access Methods in sun.misc.Unsafe for Removal](https://openjdk.org/jeps/471)
- [JEP 472: Prepare to Restrict the Use of JNI](https://openjdk.org/jeps/472)
- [JEP 474: ZGC: Generational Mode by Default](https://openjdk.org/jeps/474)
- [JEP 498: Warn upon Use of Memory-Access Methods in sun.misc.Unsafe](https://openjdk.org/jeps/498)
Adapt to JEP 498 and JEP 471 related Netty 4.1.121.Final change:
- https://github.com/netty/netty/pull/14943
- pass `--sun-misc-unsafe-memory-access=allow` on Java 23+
- pass `-XX:+ZGenerational` only on Java 21 or Java 22 by default
- pass `--enable-native-access=ALL-UNNAMED` in `bin/pulsar` and `bin/bookkeeper`, this option is supported also on Java 17
=> [improve] Adapt startup scripts for Java 24 changes

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicPublishRateThrottleTest.java
https://github.com/apache/pulsar/pull/21681 removed actual uses of preciseTopicPublishRateLimiterEnable config but left some plumbing (setting/reading config) in the code. 
Removing unused code
PR in forked repository: https://github.com/dlg99/pulsar/pull/23
=> [fix] chore: remove unused preciseTopicPublishRateLimiterEnable

deployment/terraform-ansible/templates/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
This config was introduced by https://github.com/apache/pulsar/pull/6178, but it never used.
Remove unused config messagePublishBufferCheckIntervalInMillis
*(or)*
*(or)*
*(example:)*
=> [cleanup] remove unused config messagePublishBufferCheckIntervalInMillis

buildtools/pom.xml, buildtools/src/main/java/org/apache/pulsar/tests/BetweenTestClassesListenerAdapter.java, buildtools/src/main/java/org/apache/pulsar/tests/FastThreadLocalCleanupListener.java, buildtools/src/main/java/org/apache/pulsar/tests/MockitoCleanupListener.java, buildtools/src/main/java/org/apache/pulsar/tests/SingletonCleanerListener.java, buildtools/src/main/java/org/apache/pulsar/tests/ThreadLeakDetectorListener.java, buildtools/src/test/java/org/apache/pulsar/tests/BetweenTestClassesListenerAdapterTest.java
In TestNG, there's no readily available way to reliably detect when all tests defined in a single test class have all been executed. That's why BetweenTestClassesListenerAdapter listener has been added a long time ago to execute certain cleanup operations between test classes.
One of the cleanup operations is to cleanup Mockito mocks between test classes so that memory isn't leaked during the test run. 
The previous solution was causing issues in Mockito 5.17 upgrade PR since the "between class" got detected after the next test class had already been initialized. This caused issues with some tests which initialized test mocks in constructor.
- change the way how test class completion is detected in BetweenTestClassesListenerAdapter
- add unit tests for different types of TestNG test …
=> [fix][test] Fix TestNG BetweenTestClassesListenerAdapter listener

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalPartitionedTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleSchemaTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerMemoryLeakTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/GeoReplicationProducerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/HandlerState.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImplementationBindingImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/SchemaInfoTest.java, pulsar-common/src/main/java/org/apache/pulsar/client/impl/schema/SchemaInfoImpl.java, pulsar-common/src/main/java/org/apache/pulsar/client/impl/schema/SchemaUtils.java
**Issue 1: memory leak when publishing messages with a broken schema**
- Pulsar client will discard messages which has a broken schema, but it never releases the message when discarding the message.
- You can reproduce the issue with the new test `testBrokenSchema`.
---
**Issue 2: incorrect replication/producer state**
- The internal producer of the replicator connected.
- The producer tries to register a new schema, and the state was changed: `Ready -> RegisteringSchema`.
- The topic's stats response shows there is a producer connected, but the value of `replication.connected` or `producer.connected` shows `false`
- You can reproduce the issue with the new test `testProducerConnectStateWhenRegisteringSchema`
---
**Issue 3: replication lost messages or is out of order**
| `time / task` | …
=> [fix][broker]fix memory leak, messages lost, incorrect replication state if using multiple schema versions(auto_produce)

pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/AbstractKafkaConnectSource.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSourceTest.java
This change builds on the work previously done in #24221.
The current implementation of the Kafka Connect adaptor in Pulsar IO does not support fully-qualified Pulsar topic names in source records. Instead, it forcefully prepends the default `persistent://<tenant>/<namespace>/` prefix to all destination topics. This behavior can be problematic in multi-tenant environments where dynamic topic routing is required.
For example, consider a setup with:
- A shared PostgreSQL instance where tenants are isolated in separate schemas (e.g. `tenant1`, `tenant2`)
- A shared Pulsar cluster where each tenant has its own Pulsar tenant (e.g. `tenant1`, `tenant2`)
- A single Debezium PostgreSQL source connector deployed in the `global` (shared) tenant
Using Kafka Connect transformations, users may want to …
=> [improve][io][kca] support fully-qualified topic names in source records

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/doc.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/flaky-test.yml
- Reporting an issue with the current bug reporting template is very cumbersome due to multiple fields such as "Minimal reproduce step", "What did you expect to see?", and "What did you see instead?". In many cases, the order is just wrong for describing the issue and puts the issue reporter off track.
- There's not enough guidance to provide relevant information for a bug report.
- Some reporters are sharing long logs or stacktraces in markdown fields or screenshots of logs, which makes it harder to read the relevant details of the issue. In the case of screenshots, it makes the error log messages unsearchable.
- The template id attributes are currently missing. This is mainly a limitation with the https://github.com/lhotari/pulsar-flakes prefilling of template fields. In apache/pulsar, …
=> [improve] Improve the GitHub issue templates

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java
After upgrading Mockito to 5.17, the test ManagedCursorTest.testLastActiveAfterResetCursor is very flaky.
There are two problems:
* the result callback gets triggered before the last active timestamp is updated
* the test assumes that calls will take more than 1 ms to complete
In addition, Pulsar CI is currently blocked since SchemaTest.testPendingQueueSizeIfIncompatible fails consistently. This issue is reported as #24262. To unblock Pulsar CI, the change is included in this PR.
- update the last active timestamp before triggering the callback in ManagedCursorImpl
- add a 1 ms delay in the test code to ensure that the next timestamp is different than the current one
- disable SchemaTest.testPendingQueueSizeIfIncompatible
=> [fix][test] Fix flaky ManagedCursorTest.testLastActiveAfterResetCursor and disable failing SchemaTest

buildtools/pom.xml, distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
- Upgrade Mockito to 5.17.0 and byte-buddy to 1.15.11 so that Java 24 byte code is supported.
=> [improve][build] Upgrade Mockito to 5.17.0 and byte-buddy to 1.15.11

.github/workflows/pulsar-ci.yaml, build/run_integration_group.sh
- currently integration tests produce so much log output that the GitHub Actions UI stalls 
- when a test fails, the logs will get uploaded so that they can be downloaded
- remove `-DredirectTestOutputToFile=false` command line option passed to integration test maven command line
=> [improve][ci] Disable detailed console logging for integration tests in CI

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/PolicyHierarchyValue.java, pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/PolicyHierarchyValueTest.java
Steps for reproducing the issue
- Set a topic policy: max consumer per topic `10`
- Set a global policy: max consumer per topic `20`
- Expected: the non-global value has higher priority, so the value is `10`
- Actual behavior: the second setting has higher priority, in other words, the value is `20`
Fix the issue.
=> [fix][broker]Fix incorrect priority between topic policies and global topic policies

.github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml, docker/pulsar/Dockerfile, pom.xml
As a preparation for JDK 25 LTS version, Pulsar build should allow running with JDK 24 and with JDK 25 once it becomes available so that we can start fixing the different compatibility issues.
One of the already detected issues is that the Security Manager has been removed in JDK 24 with "JEP 486: Permanently Disable the Security Manager". This breaks at least tiered storage since it uses Hadoop libraries which depend on Security Manager (issue: [HDFS-17778](https://issues.apache.org/jira/browse/HDFS-17778)). There are also failing tests in Pulsar IO RabbitMQ connector which use Qpid libraries which require Security Manager features.
- change enforcer plugin config to allow building with JDK 24 and JDK 25 in addition to JDK 17 and JDK 24.
- add required JVM arguments for JDK 24+
- fix …
=> [improve][build] Allow building and running tests on JDK 24 and upcoming JDK 25 LTS

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
There are some issues with the version upgrade of commons-compress in the Pulsar and BookKeeper projects:
1. https://github.com/apache/bookkeeper/pull/4582 there are some issues with the Changes description of your PR, upgrade commons-compress from 1.26.0 to 1.27.1, not 1.27.0, I think the Changes can be modified
2. https://github.com/apache/pulsar/pull/24205 The version number is wrong,I have proposed a new fix https://github.com/apache/pulsar/pull/24270 Please help review it
[commons-compress](https://github.com/apache/commons-compress) would be useful to upgrade to latest version,the new version brings improvements:
1. Compression into BZip2 format has unexpected end of file when using a BufferedOutputStream. Fixes [COMPRESS-686](https://issues.apache.org/jira/browse/COMPRESS-686). …
=> [improve][build] Upgrade commons-compress version from 1.27.0 to 1.27.1

pulsar-common/src/main/java/org/apache/pulsar/common/protocol/ByteBufPair.java, pulsar-common/src/test/java/org/apache/pulsar/common/compression/CommandsTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/protocol/ByteBufPairTest.java
There are ByteBuf leaks in test code that use `ByteBufPair.coalesce` method. ByteBufPair.coalesce is only used in test code so this isn't an issue in production code. Fixing leaks in test code is needed for executing the plan explained in [Enhancing Pulsar CI with Netty leak detection and reporting](https://lists.apache.org/thread/fh63hg31womzr64bc7djv3sovgcx6z99).
- release the input ByteBufPair in ByteBufPair.coalesce.
=> [fix][misc] Fix ByteBuf leaks in tests by making ByteBufPair.coalesce release the input ByteBufPair

pulsar-common/src/main/java/org/apache/pulsar/client/impl/schema/SchemaUtils.java
Netty leak detection reporting catched this leak. Since it's using a heap buffer, it's possible that there's not real impact of the leak other than leak detection nagging about it. 
Release the buffer that is no longer used.
=> [fix][misc] Fix ByteBuf leak in SchemaUtils

pom.xml
This type of warning gets logged to the console when the test starts:
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
```
Suppress the warning with `-Xshare:off` since is a [common way to handle this for running tests](https://github.com/mockito/mockito/issues/3111#issuecomment-2364356045) using Mockito.
=> [improve][build] Suppress JVM class sharing warning when running tests

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/AbstractBaseDispatcherTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SharedConsumerAssignorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/MessageDuplicationTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsSnapshotBuilderTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/compression/CommandsTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/compression/CompressorCodecTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/protocol/CommandUtilsTests.java, pulsar-common/src/test/java/org/apache/pulsar/common/protocol/MarkersTest.java
Fixing Netty ByteBuf leaks in test code is needed for executing the plan explained in [Enhancing Pulsar CI with Netty leak detection and reporting](https://lists.apache.org/thread/fh63hg31womzr64bc7djv3sovgcx6z99).
- Fix ByteBuf leaks in these tests
- `org.apache.bookkeeper.mledger.impl.ManagedCursorTest` (managed-ledger)
- `org.apache.pulsar.broker.intercept.ManagedLedgerInterceptorImplTest` (pulsar-broker)
- `org.apache.pulsar.broker.service.AbstractBaseDispatcherTest` (pulsar-broker)
- `org.apache.pulsar.broker.service.PersistentMessageFinderTest` (pulsar-broker)
- `org.apache.pulsar.broker.service.PersistentTopicTest` (pulsar-broker)
- `org.apache.pulsar.broker.service.ServerCnxTest` (pulsar-broker)
- `org.apache.pulsar.broker.service.SharedConsumerAssignorTest` (pulsar-broker)
- …
=> [fix][test] Fix multiple ByteBuf leaks in tests

pom.xml
[zstd](https://github.com/facebook/zstd/releases/tag/v1.5.7) would be useful to have zstd upgraded to latest version,the new version brings many improvements:
1. Enhanced Compression Speed for Small Data Blocks
2. Substantial --patch-from improvements
3. Compression ratio improvements for large files
4. Command-Line Interface Updates
See release notes for details:
- [zstd v1.5.7 release notes](https://github.com/facebook/zstd/releases/tag/v1.5.7)
- [zstd-jni v1.5.7-3 release notes](https://github.com/luben/zstd-jni/releases/tag/v1.5.7-3)
Upgrade zstd version from 1.5.2-3 to 1.5.7-3
PR in forked …
=> [improve][build] Upgrade zstd version from 1.5.2-3 to 1.5.7-3

buildtools/src/main/java/org/apache/pulsar/tests/ThreadLeakDetectorListener.java
The thread leak detector used in CI to report thread leaks currently reports false positives about "Attach Listener"
Ignore threads with the name "Attach Listener" in leak detection
=> [improve][build] Improve thread leak detector by ignoring "Attach Listener" thread

.github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml, build/pulsar_ci_tool.sh, buildtools/pom.xml, buildtools/src/main/java/org/apache/pulsar/tests/ExtendedNettyLeakDetector.java, buildtools/src/main/java/org/apache/pulsar/tests/PulsarTestListener.java, conf/bkenv.sh, conf/pulsar_tools_env.sh, deployment/terraform-ansible/templates/pulsar_env.sh, pom.xml, pulsar-common/src/test/java/org/apache/pulsar/common/allocator/PulsarByteBufAllocatorDefaultTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/allocator/PulsarByteBufAllocatorOomThrowExceptionTest.java, tests/bc_2_0_0/pom.xml, tests/bc_2_0_1/pom.xml, tests/bc_2_6_0/pom.xml, tests/docker-images/java-test-image/Dockerfile, tests/docker-images/java-test-image/pom.xml, tests/docker-images/latest-version-image/Dockerfile, tests/docker-images/latest-version-image/pom.xml, tests/integration/pom.xml, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/BKContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/CSContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ChaosContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/PulsarContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ZKContainer.java, tests/pulsar-client-admin-shade-test/pom.xml, tests/pulsar-client-all-shade-test/pom.xml, tests/pulsar-client-shade-test/pom.xml
Memory leaks in Netty buffers can lead to performance degradation, resource exhaustion, and unpredictable failures in production. A key challenge we face is that these leaks often go undetected until they cause issues in production environments. 
Currently, our CI pipeline lacks the capability to systematically detect and prevent Netty buffer leaks before they reach production code. This creates a significant blind spot that allows buffer leak regressions to slip through our quality gates. This PR addresses this gap by implementing advanced Netty leak detection capabilities within the Pulsar CI pipeline.
The implementation follows a staged approach:
1. First, enable leak detection and reporting without failing builds
2. Fix identified leaks in both test and production code
3. Eventually, …
=> [improve][ci] Add Netty leak detection reporting to Pulsar CI

pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Fixes #24262
Main Issue: #24262
The issue is a regression of https://github.com/apache/pulsar/pull/24178. The flow of the issue occurring is as follows
- Publish msg 1, which has an incompatible schema
- Publish msg 2, which has an incompatible schema
- The first message's schema failed to register because it is incompatible
- The message was discarded.
- Issue: it did not trigger a schema registration of the following messages 
Fix the issue
=> [fix][client] Fix producer publishing getting stuck after message with incompatible schema is discarded

pulsar-functions/instance/src/main/python/contextimpl.py
Fixes #24295
See #24295
The solution is to prefix the regular expressions with `r` to use Python’s raw string notation.
This is explained in https://docs.python.org/3/library/re.html
=> [fix][io] Fix SyntaxWarning in Pulsar Python functions

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
In Pulsar, it's possible for actual partition topics (e.g., `public/default/test-partitioned-topic-partition-1`) to exist even though the corresponding partitioned topic metadata is missing. This inconsistency can occur due to human error (e.g., accidental deletion of metadata) or implicit topic creation via auto-topic creation settings.
Specifically, if `allowAutoTopicCreation=true` and `allowAutoTopicCreationType=non-partitioned`, then producing or consuming directly from a partition topic name like `test-partitioned-topic-partition-1` will cause Pulsar to auto-create a non-partitioned topic. This leads to an inconsistent state: the topic appears in `topics list`, but not in `topics list-partitioned-topics`. From the user's perspective, they expect to see a partitioned topic, but …
=> [fix][broker] Allow recreation of partitioned topic after metadata loss

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageCumulativeAckTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TransactionMarkerDeleteTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
In https://github.com/apache/pulsar/pull/22792
https://github.com/apache/pulsar/pull/23919
https://github.com/apache/pulsar/pull/24219,
we optimized seeking by timestamp, it also can be used for optimizing message TTL check.
*(or)*
*(or)*
*(example:)*
=> [improve][broker] Optimize message TTL check

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersClassicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumersTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/AcknowledgementsGroupingTrackerTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/BinaryProtoLookupServiceTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientCnxTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientTestFixtures.java
Fixing Netty ByteBuf leaks in test code is needed for executing the plan explained in [Enhancing Pulsar CI with Netty leak detection and reporting](https://lists.apache.org/thread/fh63hg31womzr64bc7djv3sovgcx6z99). The Pulsar CI Netty leak detection and reporting solution was added in #24272.
- Fix ByteBuf leaks in these tests
- `org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersClassicTest` (pulsar-broker)
- `org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest` (pulsar-broker)
- `org.apache.pulsar.client.impl.AcknowledgementsGroupingTrackerTest` (pulsar-client)
- `org.apache.pulsar.client.impl.BinaryProtoLookupServiceTest` (pulsar-client)
- `org.apache.pulsar.client.impl.ClientCnxTest` (pulsar-client)
In …
=> [fix][test] Fix more Netty ByteBuf leaks in tests

docker/pulsar/Dockerfile, pom.xml
Upgrade pulsar-client-python from 3.5.0 to 3.7.0 to get recent fixes.
- Upgrade pulsar-client-python to 3.7.0
- remove previous workaround #22733 for arm64 build, since https://github.com/apache/pulsar-client-python/pull/211 is included in pulsar-client-python 3.7.0
- keep `--only-binary grpcio` option so that grpc package doesn't get built from source and would fail the build if a suitable version isn't available
- simplify installation since requirements.txt file isn't needed
=> [improve] Upgrade pulsar-client-python to 3.7.0 in Docker image

pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSink.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSinkConfig.java
Fixes #24288
The Kinesis Sink currently always enables aggregation of records while producing to the kinesis data streams. This results in records being merged in the final output described https://github.com/awslabs/amazon-kinesis-producer/issues/566. There are use cases like monitoring logs through streams UI and client applications expecting certain record type where this behaviour is not desirable.
Added an `enableAggregation` option to `KinesisSinkConfig` and updated `KinesisSink#open` so that it reads this flag when constructing the Kinesis producer. …
=> [improve][io] Add configuration parameter for disabling aggregation for Kinesis Producers

buildtools/src/main/java/org/apache/pulsar/tests/BetweenTestClassesListenerAdapter.java, buildtools/src/main/java/org/apache/pulsar/tests/FastThreadLocalCleanupListener.java, buildtools/src/main/java/org/apache/pulsar/tests/MockitoCleanupListener.java, buildtools/src/main/java/org/apache/pulsar/tests/SingletonCleanerListener.java, buildtools/src/main/java/org/apache/pulsar/tests/ThreadLeakDetectorListener.java, buildtools/src/test/java/org/apache/pulsar/tests/BetweenTestClassesListenerAdapterTest.java
It wasn't clear how test class changes should be detected with TestNG. 
The solution was recently revisited in #24258. However problems remain after adding that solution. BeforeTest/AfterTest annotation usage won't work and cause false reports for detected leaks.
It turns out that it's possible to detect a test change with ITestListener's `onFinish` callback. In TestNG, it's possible to group multiple test classes into a single test, but this is only when using TestNG's XML configuration for test suites. maven-surefire-plugin will create a separate TestNG test for each test class, so that's why it's the correct solution for BetweenTestClassesListenerAdapter.
- Remove previous logic to detect test class change and instead rely on ITestListener's `onFinish` callback
- Adapt the current …
=> [fix][test] Simplify BetweenTestClassesListenerAdapter and fix issue with BeforeTest/AfterTest annotations

buildtools/pom.xml, buildtools/src/main/java/org/apache/pulsar/tests/ThreadLeakDetectorListener.java
Recent changes broke running tests in IntelliJ since IntelliJ enforces Java 8 compatibility for buildtools module.
The maven build didn't contain the needed `<maven.compiler.release>8</maven.compiler.release>` setting in buildtools module.
- add `<maven.compiler.release>8</maven.compiler.release>`
- fix the single compatibility issue
=> [fix][build] Ensure that buildtools is Java 8 compatible and fix remaining compatibility issue

pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/BrokerMonitor.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationClient.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationController.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/ManagedLedgerWriter.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerfClientUtils.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java, pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceProducerTest.java
Terminating pulsar-perf with CTRL-C could take a while. There's also a similar problem in some test cases that I came across while fixing test resource leaks.
- replace `while(true)` loops with `while(!Thread.currentThread().isInterrupted())` 
- properly propagate Thread interrupted information after catching exceptions
- fix issue in tests related to runtime hook resource leaks
- when the execution completes successfully, remove the shutdown hook and run it without waiting for JVM exit
=> [improve][cli] Make pulsar-perf termination more responsive by using Thread interrupt status

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageFinder.java
Change PersistentMessageFinder's fields modifier to protected, so we can reuse/rewrite the class in protocolhandlers, such as KoP.
Change PersistentMessageFinder's fields modifier to protected.
*(or)*
*(or)*
*(example:)*
=> [improve] Change PersistentMessageFinder's fields modifier to reuse in plugins

buildtools/src/main/java/org/apache/pulsar/tests/ThreadLeakDetectorListener.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java, pulsar-broker-auth-sasl/src/test/java/org/apache/pulsar/broker/authentication/ProxySaslAuthenticationTest.java, pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMappingTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/RateLimiterTest.java, tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileStoreBackedReadHandleImpl.java, tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/FileStoreTestBase.java, tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloaderTest.java, tiered-storage/file-system/src/test/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemOffloaderLocalFileTest.java
Fixing Netty ByteBuf leaks in test code is needed for executing the plan explained in [Enhancing Pulsar CI with Netty leak detection and reporting](https://lists.apache.org/thread/fh63hg31womzr64bc7djv3sovgcx6z99). The Pulsar CI Netty leak detection and reporting solution was added in #24272.
- Fix thread leaks in these tests:
- ProxySaslAuthenticationTest (indent was also changed from tabs to spaces)
- BookieRackAffinityMappingTest
- RateLimiterTest 
- FileSystemOffloaderLocalFileTest
- Fix thread leaks in tests using BookKeeperClusterTestCase base class
- Fix ByteBuf leaks in these tests
- FileSystemManagedLedgerOffloaderTest
=> [fix][test] Fix more resource leaks in tests

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
There is still a call to the synchronous method in `internalCreatePartitionedTopic`, which can lead to a deadlock under certain conditions.
- Replaced synchronous call to `getNamespacePolicies()` with `getNamespacePoliciesAsync()`.
- Replaced synchronous call to `getTopicPartitionList()` with `getTopicPartitionListAsync()`.
- Updated `internalCreatePartitionedTopic` to propagate the async flow properly.
=> [fix][broker] Fix potential deadlock when creating partitioned topic

pip/pip-415.md
we can now obtain the offset of a message by its message id:
1. Get the message by id using `get-message-by-id` cmd
2. Get the index of the message using `Message.getIndex()`
But we cannot obtain the message id by offset. Then we need to add a new API to get the message id by offset.
Add a new http API to retrieve the message ID by offset.
We propose to add a new API to retrieve the message ID by offset, enabling us to cache the mapping between message ID and offset.
This will allow us to use offsets for seek and acknowledgment operations when consuming messages through the standardized API.
*(or)*
This change is already covered by existing tests, such as *(please …
=> [feat][pip]PIP-415: Support getting message ID by Index

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
The config was introduced by https://github.com/apache/pulsar/pull/14515
and deprecated by https://github.com/apache/pulsar/pull/23352/files#diff-6bdf62fdf16d74a56f5f9c1f5a6bf30f4360ad7022c69ab8f90c90a267bc568e
*(or)*
*(or)*
*(example:)*
=> [cleanup] Remove unused config `autoShrinkForConsumerPendingAcksMap`

pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/json/JsonConverter.java, pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/UtilsTest.java, pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/json/JsonConverterTests.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java
AVRO uses `ByteBuffer` for schema BYTES.
In the Kinesis sink, when converting AVRO record to JSON, we get 
```
2025-05-16T19:16:09.142923400Z java.lang.ClassCastException: class java.nio.HeapByteBuffer cannot be cast to class [B (java.nio.HeapByteBuffer and [B are in module java.base of loader 'bootstrap')
2025-05-16T19:16:09.142932060Z 	at org.apache.pulsar.io.kinesis.json.JsonConverter.toJson(JsonConverter.java:80) ~[?:?]
2025-05-16T19:16:09.142933540Z 	at org.apache.pulsar.io.kinesis.json.JsonConverter.toJson(JsonConverter.java:119) ~[?:?]
2025-05-16T19:16:09.142934623Z 	at org.apache.pulsar.io.kinesis.json.JsonConverter.toJson(JsonConverter.java:54) ~[?:?]
2025-05-16T19:16:09.142935763Z 	at org.apache.pulsar.io.kinesis.json.JsonConverter.toJson(JsonConverter.java:113) ~[?:?] …
```
=> [fix][io] Fix kinesis avro bytes handling

pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/decoder/json/PulsarJsonFieldDecoder.java
The original implementation of decoding was introduced by #15687, The implementation is as follows
```java
String textValue = value.isValueNode() ? value.asText() : value.toString();
if (type instanceof DecimalType) {
textValue = textValue.replace(".", "");
BigInteger bigInteger = new BigInteger(textValue);
return Decimals.encodeUnscaledValue(bigInteger);
}
```
#20016 introduced a break change, which added a classcast from `object` to `DecimalNode`, The implementation was changed to as follows
```java
// value is typed "Object", the actual type is a JsonNode
final DecimalNode node = (DecimalNode) value;
type.writeObject(blockBuilder, Int128.valueOf(node.asText().replace(".", "")));
```
Revert the implementation to the original.
=> [fix][io][branch-3.0]Pulsar-SQL: Fix classcast ex when decode decimal value

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/AutoScaledReceiverQueueSizeTest.java
Since not every unit test is cleaned up before execution, the previous unit test may generate some dirty data, affecting the execution results of subsequent test cases.
`setup` and `cleanup` is performed before each unit test is executed
=> [fix][test] Fix flaky AutoScaledReceiverQueueSizeTest.testNegativeClientMemory

pulsar-client-tools/src/main/java/org/apache/pulsar/shell/PulsarShell.java, pulsar-client-tools/src/test/java/org/apache/pulsar/shell/PulsarShellTest.java
Fixes #24319
The `InteractiveLineReader` cannot `parseLine("client produce -m \"hello\ pulsar\" my-topic")` correctly. The result will not retain quotes. 
change the following code from
```
public List<String> parseLine(String line) {
return reader.getParser().parse(line, 0).words();
}
```
to
```
public List<String> parseLine(String line) {
return reader.getParser().parse(line, 0, Parser.ParseContext.SPLIT_LINE).words();
}
```
- *org.apache.pulsar.shell.PulsarShellTest#testInteractiveMode*
=> [fix][cli] Fix pulsar-shell cannot produce message with quotes and space

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicPoliciesService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/systopic/NamespaceEventsSystemTopicServiceTest.java
- Set local topic policy: dispatch rate `2000`
- Set global topic policy: dispatch rate `1000`
- Trigger a compaction for the system topic `__change_events`
- Issue: get local topic policy `1000`
- Set global topic policy: dispatch rate `1000`
- Delete topic, the global topic-level policies will never be deleted
Fix two issues
=> [fix][broker]Non-global topic policies and global topic policies overwrite each other

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
Fixes #24329 
See #24329 
Since the ledger will rollover asynchronously, the number of ledgers will be 11 eventually in the test.
Use Awaitility to assert this.
=> [fix][test] Fix flaky ManagedLedgerTest.testDoNotGetOffloadPoliciesMultipleTimesWhenTrimLedgers

tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImplV2.java
There's a bug in `BlobStoreBackedReadHandleImplV2.readAsync` which can be reproduced with 
the existing test `BlobStoreManagedLedgerOffloaderStreamingTest#testReadAndWriteAcrossSegment`. 
The test is flaky and could result in a `ConcurrentModificationException`.
```
java.util.ConcurrentModificationException
at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
at org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreManagedLedgerOffloaderStreamingTest.testReadAndWriteAcrossSegment(BlobStoreManagedLedgerOffloaderStreamingTest.java:326)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at …
```
=> [fix][offload] Complete the future outside of the reading loop in BlobStoreBackedReadHandleImplV2.readAsync

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
Fix ManagedCursorImpl.individualDeletedMessages concurrent issue.
```txt
2025-05-22T13:16:55,588 - INFO  - [PulsarTestContext-executor-OrderedExecutor-0-0:PulsarMockBookKeeper] - Creating ledger 6
2025-05-22T13:16:55,592 - WARN  - [PulsarTestContext-executor-OrderedExecutor-0-0:ManagedCursorImpl] - [my-property/my-ns/persistent/my-topic1]-my-subscriber-name Failed to serialize individualDeletedMessages
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at org.roaringbitmap.ArrayContainer.copyBitmapTo(ArrayContainer.java:1136) ~[RoaringBitmap-1.2.0.jar:?]
at org.roaringbitmap.BitSetUtil.toLongArray(BitSetUtil.java:94) ~[RoaringBitmap-1.2.0.jar:?]
at org.roaringbitmap.RoaringBitSet.toLongArray(RoaringBitSet.java:216) ~[RoaringBitmap-1.2.0.jar:?]
at …
```
=> [fix][ml] Fix ManagedCursorImpl.individualDeletedMessages concurrent issue

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
At present, the message expiration deletion rate is updated in the getmessageExpiryRate() method, and this rate is updated every time the topic status is obtained. This results in the statistical analysis of message expiration and deletion rates not having a fixed periodicity, making it difficult to represent the true message expiration rate.
Only update the rate in the updateRate() method and only retrieve the value in the getmessageExpiryRate() method
=> [fix][broker] Resolve the issue of frequent updates in message expiration deletion rate

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/stats/client/PulsarBrokerStatsClientTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ManagedLedgerInternalStats.java
In https://github.com/apache/pulsar/pull/24076, we introduced per-ledger properties to ML, it should be exposed to internalStats to help track potential issue.
Expose per ledger props to PersistentTopic.getInternalStats
*(or)*
*(or)*
*(example:)*
=> [improve][admin] Expose per ledger props to PersistentTopic.getInternalStats

pulsar-io/kinesis/pom.xml, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSink.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSinkConfig.java, pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/KinesisSinkTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java
- required for supporting running Pulsar 3.0 Kinesis IO on an Alpine based image
- FunctionMesh uses Alpine based images
- also updates Kinesis producer library version to 0.15.12
- newer version uses AWS STS for tokens and setting the STS endpoint and port is required when testing with LocalStack
=> [fix][io][branch-3.0] Backport Kinesis Sink custom native executable support #23762

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
Fixes https://github.com/apache/pulsar/issues/24312
The `brokerId` was previously initialized in the `start` method, after the `BrokerService` had already started. This could lead to a `NullPointerException` if the `brokerId` is accessed during the early stages of startup. 
- Only handle the metadata changes when broker is fully started. 
- Failed to retrieve `brokerId`, please fall back to `unknown`.
=> [fix][broker] Ignore metadata changes when broker is not in the Started state

pulsar-io/rabbitmq/src/main/java/org/apache/pulsar/io/rabbitmq/RabbitMQSource.java
Fixes #24353
See #24346 
- add `ackFunction` and `failFunction` to the internal `RabbitMQRecord` class and use these functions in the `ack` and `fail` implementations of the `Record` interface.
- switch to use individual acks towards RabbitMQ since there's no benefit of using "multi" acks when every message will get acked in any case
=> [fix][io] Acknowledge RabbitMQ message after processing the message successfully

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicGCTest.java
The reproduction steps of the issue
- Create a partitioned topic with `2` partitions
- A partition was deleted due to the feature `brokerDeleteInactiveTopicsMode`
- Issue: the topic's policies were deleted, even though the partitioned topic still exists
- Do not delete topic policies when a sub topic is deleting
- Delete topic-level poclies when a non-partitioned topic is deleting or a partitioned topic is deleting
=> [fix][broker] Fix issue that topic policies was deleted after a sub topic deleted, even if the partitioned topic still exists

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/InflightReadsLimiter.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java
- When reaching the pending read queue size limitation
- Highlight the config `managedLedgerMaxReadsInFlightPermitsAcquireQueueSize` when the broker reaches the limitation that the pending read queue is full.
- Instead of printing an error-level log,  print a warning-level log.
- Additional print queue size and the limit threshold when the pending read queue is full
- Print warning-level log if reached in-flight messages size is reached, instead of debug-level.
=> [improve][broker]Improve the log when encountered in-flight read limitation

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/ConsumerStatsImpl.java
Expose the consumer name for partitioned topic stats
- Add consumerName for `ConsumerStatsImpl`
=> [fix][broker] expose consumer name for partitioned topic stats

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/client/api/RawReader.java, pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/Compactor.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConsumerCloseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawReaderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicListWatcher.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java
Reproduction steps of the deadlock( see also the new test `testConcurrentCompactionAndTopicDelete` )
1. `thread-compaction`: create a raw reader.
2. `thread-topic-deleting`: mark the topic as deleted and disconnect clients, including the compaction reader.
3. `thread-compaction`: The raw reader attempts to reconnect due to the disconnection in step "2-1".
4. `thread-topic-deleting`: unsubscribe all subscriptions that contain "__compaction".
5. `thread-topic-deleting`: deleting "__compaction" cursor will wait for the in-progress compaction task.
6. `thread-compaction`: the raw read can not connect successfully anymore because the topic was marked as  "fenced && isDeleting".
7. `deadlock`: "thread-topic-deleting" waiting for compaction task being finished, thread-compaction continuously …
=> [fix][broker]Fix deadlock when compaction and topic deletion execute concurrently

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/OffloadedLedgerHandle.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java
https://github.com/apache/pulsar/pull/19783 introduced a feature: release idle offloaded ledger handle to release the direct memory occupied. But it left a potential issue, which has been discussed [here](https://github.com/apache/pulsar/pull/19783#discussion_r2086201906), and it can happen this way
| time/thread | release idle ledger handle | `ledgerHandle.readAsync` |
| 1 | | `touch()`, update `lastAccessTimestamp` |
| 2 | | append the reading request into `executor.queue` |
| 3 | | the `executor` is very busy, leading to delayed executions of `ledgerHandle.readAsync` |
| 4 | Check how long the ledger handle has been idled |
| 5 | release the ledger handle |
| 6 | | `ledgerHandle.readAsync` execute eventually, but the ledger handle has been closed |
Since users can …
=> [improve][ml]Release idle offloaded read handle only the ref count is 0

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsumers.java
Fixes #24379
We have observed inconsistency with the usage of `synchronized` keyword while dispatching messages to the consumer across different dispatchers.
The following are not using `synchronized` keyword while filtering and sending messages to the consumers.
- [NonPersistentDispatcherSingleActiveConsumer#sendMessages](https://github.com/apache/pulsar/blob/a1a2b363cfaa1bbc38933a742484a70a0a56e761/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherSingleActiveConsumer.java#L59)
- [NonPersistentStickyKeyDispatcherMultipleConsumers#sendMessages](https://github.com/apache/pulsar/blob/a1a2b363cfaa1bbc38933a742484a70a0a56e761/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsum …
=> [improve][broker] Added synchronized for sendMessages in Non-Persistent message dispatchers

conf/broker.conf, conf/standalone.conf
To reduce the size of ZNodes, there's ManagedCursorInfo compression which was introduced in [PIP-146](https://github.com/apache/pulsar/issues/14529). ManagedLedgerInfo compression was introduced earlier, in PR #11490.
ManagedCursorInfo compression can enable using a higher `managedLedgerMaxUnackedRangesToPersist` and `managedLedgerMaxUnackedRangesToPersistInMetadataStore` settings.
ManagedLedgerInfo compression is required for a very large amount of BookKeeper or tiered storage ledgers for a single topic.  Both settings reduce the size of metadata storage which will reduce overall ZooKeeper memory usage. After enabling compression, existing entries won't be compressed until they are modified.
- add the settings to `broker.conf` and `standalone.conf` so that it's easier to enable the …
=> [improve][broker] Add managedCursor/LedgerInfoCompressionType settings to broker.conf

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java
https://github.com/apache/pulsar/pull/24381 changed the behavior below:
- original: Pulsar only releases the offloaded ledger handle that is  typed `BlobStoreBackedReadHandle`
- after #24381, Pulsar will release the offloaded ledger handle immediately if its type is not `BlobStoreBackedReadHandle`, because the method `lastAccessTimestamp()` always returns `-1` if its type is not `BlobStoreBackedReadHandle`
- Revert the behavior change.
- Modify `lastAccessTimestamp` first, and modify `pendingReading` second, to avoid getting a new `pendingReading` and an older `lastAccessTimestamp`, which leads to an incorrect ledger handle invalidation.
The following issue still exists. I will push a new PR to fix it in the future.
| time/thread | release idle ledger handle | `ledgerHandle.readAsync` |
| …
=> [fix][ml]Revert a behavior change of releasing idle offloaded ledger handle: only release idle BlobStoreBackedReadHandle

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/NamedEntity.java
**Topic name rule**
- old version: `{tenant}/{cluster}/{namespace}/{topic}/{subscription}`
- new version: `{tenant}/{namespace}/{topic}/{subscription}`
There are many HTTP APIs defined as `HTTP Method {topic name}/{subscription name}`
If a subscription contains `/`, the broker will assume it is a topic created with the old rule, then users will get a `cluster does not exist` error or a `topic not found error`
Use the util method https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/java/org/apache/pulsar/common/naming/NamedEntity.java to check new subscription name
=> [fix] [broker] No longer allow creating subscription that contains slash

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
After disabling `deletionAtBatchIndexLevelEnabled`, `ManagedCursorImpl` ignores positions that have an empty `ackSet` when calling `cursor.delete`, which leads to the caller acknowledging nothing.
And the Transaction task will acknowledge positions that have an empty `ackSet` after all single messages of a batch were acknowledged, 
- https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/PositionAckSetUtil.java#L52 
```java
public static void andAckSet(Position currentPosition, Position otherPosition) {
if (currentPosition == null || otherPosition == null) {
return;
}
AckSetState currentAckSetState = AckSetStateUtil.getAckSetState(currentPosition);
AckSetState otherAckSetState = AckSetStateUtil.getAckSetState(otherPosition);
// The …
```
=> [fix][ml] Cursor ignores the position that has an empty ack-set if disabled deletionAtBatchIndexLevelEnabled

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java
**About cursor deleting, there are two cases**
- `scenario-A`: Acked nothing, because all positions have been acknowledged before.
- `scenario-B`: Acked some position, then it will try to `mark-deleted`.
- `scenario-B1`:  Acked some positions, but `individualDeletedMessages` became empty after combining ranges in the method `setAcknowledgedPosition`, 
- `scenario-B2`: Acked some positions, and `individualDeletedMessages` was still not empty.
**Triggering callbacks**
- Regarding the `scenario-A`, Cursor will skip calling `mark-deleted`, because it is meaningless.
- Regarding the `scenario-B`, Cursor will call `mark-deleted`, which will trigger a `callback`.
**Issue**
Regarding the `scenario-B1`, the Cursor triggers twice the callbacks.
- The first time: calls the callback if …
=> [fix][ml]Received more than once callback when calling cursor.delete

tests/integration/src/test/java/org/apache/pulsar/tests/integration/bookkeeper/BookkeeperInstallWithHttpServerEnabledTest.java
When the Prometheus library versions differ between the broker and the bookkeeper, it may cause compatibility issues that prevent us from retrieving metrics from the bookie.
- Added `testGetBookieMetrics` to verify that bookie metrics can be fetched successfully, ensuring compatibility across Prometheus versions.
=> [improve][test] Add test for retrieving bookie metrics via HTTP

pip/pip-414.md
The changes from #24118 have been merged and should be documented in a Pulsar Improvement Proposal (PIP) to record these important updates.
=> [improve][pip] PIP-414: Enforce topic consistency check

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
This PR addresses a potential NullPointerException (NPE) that could occur when calling the `seek()` method with a `TopicMessageIdImpl` that has a null topic. 
1. Added null check for the owner topic in `MultiTopicsConsumerImpl.java` before attempting to access it
2. Added comprehensive test case in `SubscriptionSeekTest.java` to verify the fix:
- Creates a partitioned topic
- Attempts to seek using a `TopicMessageIdImpl` with null topic
- Verifies the proper exception is thrown with a clear error message
PR in forked repository: https://github.com/3pacccccc/pulsar/pull/8
=> [fix][client] Prevent NPE when seeking with null topic in TopicMessageId

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorRemoveClusterTest.java
**Reproduce steps**
- Create a remote cluster with an incorrect auth-param.
- Call `pulsar-admin topics set-replication-clusters <clusters> <topic>`, which will trigger the creation of an Internal PulsarAdmin Object in the broker's memory.
- Remove the cluster that contains incorrect `auth-params`
- Recreate the cluster with the correct info
- Issue: the broker still maintains a PulsarAdmin with an incorrect `auth-params` that we set the first time
- Close and remove the PulsarAdmin Object of the remote cluster when removing clusters
=> [fix][broker] Once the cluster is configured incorrectly, the broker maintains the incorrect cluster configuration even if you removed it

pip/pip-422.md
- [DIscussion](https://lists.apache.org/thread/5rh536dqm2o35tzop5jl7b5x7r291pv2)
- [Vote](https://lists.apache.org/thread/p0wmnfr3jkmfzh69jfh7jv10184g1vlm)
=> [improve][pip]PIP-422 Support global topic-level policy: replicated clusters and new API to delete topic-level policies

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java
As https://lists.apache.org/thread/3dc1c3n7d0tmwm8974qh9w771jzgy6f6 show, method `getNumberOfDelayedMessages` is called frequently and the current implementation of this method is time cosuming, we need to implement this method with a much more efficient approach.
Introduce an `AtomicLong delayedMessagesCount`.
PR in forked repository: https://github.com/thetumbled/pulsar/pull/74
=> [improve][broker] Reduce cpu usage of InMemoryDelayedDeliveryTracker.

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadLedgerDeleteTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadPrefixTest.java
**The reproduction steps of the issue:**
- There are `4` ledgers in the ManagedLedger
- `3` ledgers are offloaded.
- The BK ledgers are deleted because they were offloaded.
- Issue:
- Actual behavior: `ManagedLedger.getLedgerHandle(long ledgerId)` returns BK ledger handles, which have been deleted
- Expected behavior: `ManagedLedger.getLedgerHandle(long ledgerId)` returns Offloader ledger handles.
**Root cause**
Trimming ledgers, BK ledgers are deleted, and `LedgerCache` of `ManagedLedger` does not remove the cached ledger handle in memory.
- In scope: Remove cached ledger handles when trimming offloaded ledgers.
- Not in scope: This PR will not solve the issue: Ledger is being deleted, but a cursor still uses the ledger handle to read entries. This issue will be resolved automatically …
=> [fix][ml]Still got BK ledger, even though it has been deleted after offloaded

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerEntryMetadataE2ETest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
PIP:https://github.com/apache/pulsar/pull/24220
we can now obtain the offset of a message by its message id:
1. Get the message by id using `get-message-by-id` cmd
2. Get the index of the message using `Message.getIndex()`
But we cannot obtain the message id by offset. Then we need to add a new API to get the message id by offset.
Add a new http API to retrieve the message ID by offset.
We propose to add a new API to retrieve the message ID by offset, enabling us to cache the mapping between message ID and offset.
This will allow us to use offsets for seek and acknowledgment operations when consuming messages through the standardized API.
*(or)*
This change is already …
=> [feat][admin] PIP-415: Support getting message ID by index

pip/pip-428.md
Change TopicPoliciesService interface to fix consistency issues with Topic Policies. Example issues #24393, #21303
This is a PIP document "PIP-428: Change TopicPoliciesService interface to fix consistency issues".
The WIP implementation PR is #24427 .
=> [pip] PIP-428: Change TopicPoliciesService interface to fix consistency issues

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpFindNewest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java
When some ledgers are not offloaded successfully, they will be removed from the metadata store so that seek by timestamp might fail.
```
Error opening ledger for reading at position 4098289:438 - org.apache.bookkeeper.mledger.ManagedLedgerException$LedgerNotExistException: No such ledger exists on Metadata Server
```
skipNonRecoverableData is true, but it does not handle the seek case. The workaround is to see by message id.
When `skipNonRecoverableData` is true, OpFindNewest can auto skip non-recoverable data.
*(or)*
*(or)* …
=> [fix][ml] Enhance OpFindNewest to support skip non-recoverable data

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ConsumerStatsTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/ConsumerStats.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/ConsumerStatsImpl.java
This PR supports two stats for the consumer side to help identify the first message dispatch latency.
- Add stats `firstConsumedFlowTimestamp`
- Add stats `firstMessagesSentTimestamp `
=> [feat][broker] add consumer first consume/flow timestamp

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
- Location: MultiTopicsConsumerImpl.java:581 in the negativeAcknowledge(Message<?> message) method
- Error: java.lang.NullPointerException
- Root Cause: Race condition between closeAsync() and negativeAcknowledge() methods
Technical Details
What was happening:
1. closeAsync() sets consumer state to Closing/Closed and calls cleanupMultiConsumer()
2. cleanupMultiConsumer() sets unAckedMessageTracker = null (line 685)
3. Concurrently, negativeAcknowledge() methods were still being called
4. These methods accessed unAckedMessageTracker.remove(messageId) without checking if it was null
5. This caused NullPointerException at line 581
Race condition timeline:
Thread 1: closeAsync() → setState(Closed) → cleanupMultiConsumer() → unAckedMessageTracker = null
Thread 2: negativeAcknowledge() → …
=> [fix][client] NPE in MultiTopicsConsumerImpl.negativeAcknowledge

pip/pip-431 Add Creation and Last Publish Timestamps to Topic Stats.md
This Pulsar Improvement Proposal (PIP) addresses an observability gap in Apache Pulsar by proposing the addition of two new fields to the topic statistics API: topicCreationTimeStamp and lastPublishTimeStamp. Currently, operators and developers lack a direct and efficient method to determine a topic's age or its most recent message activity, hindering effective lifecycle management, troubleshooting, and compliance auditing. This proposal outlines a plan to introduce these timestamps into the TopicStats object, accessible via the Admin REST API and pulsar-admin CLI. The topicCreationTimeStamp will be retrieved directly from the topic's underlying metadata node statistics, providing an immutable value for all topics. The lastPublishTimeStamp will be maintained as a high-performance, …
=> [improve][pip] PIP-431: Add Creation and Last Publish Timestamps to Topic Stats

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorDeduplicationTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/GeoReplicationProducerImpl.java
**Background of deduplication**: Always regard `markers` as non-repetitive
**Background of replicated subscription**: The internal producer of the replicator will send markers to replicate the subscription ack state to the remote side.
**Reproduce steps of the issue**
0. Replicator replicate a user message(`user-msg-1`) to the remote cluster
0. Replicator sends a replication marker(`marker-1`) to the remote cluster
0. Replicator replicate a user message(`user-msg-2`) to the remote cluster
0. The messages `[marker, user-msg-2]` have not received the send receipt yet.
0. A disconnection of the internal producer occurs.
0. Resend the `2` messages: `[user-msg-1, marker, user-msg-1]`.
0. The remote broker is handling the write of `marker-1`, because it regards all markers as non-repetitive.
a. …
=> [fix][broker] replication does not work due to the mixed and repetitive sending of user messages and replication markers

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/PersistencePolicies.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/CmdTopicPoliciesTest.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdTopics.java
Implementation of pip-427 #24425
- Adjusted the logic in BrokerService to set the throttle mark delete rate based on persistence policies, allowing for a fallback to the broker's default rate when necessary.
- Added comprehensive unit tests to validate the behavior of namespace and topic-level persistence policies, ensuring correct application of the managed ledger max mark delete rate.
- Updated CLI commands to accept a default value of -1 for the mark delete rate, indicating that it should use the broker's default configuration.
- Enhanced test coverage for CLI commands to verify the handling of various mark delete rate scenarios, including negative and zero values.
=> [improve][broker] PIP427:Align pulsar-admin Default for Mark-Delete Rate with Broker Configuration

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/TopicStats.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/TopicStatsImpl.java
Implement PIP-431 https://github.com/apache/pulsar/pull/24469
Need to rebase master branch after https://github.com/apache/pulsar/pull/24469 merged
- Introduced methods to retrieve the last successful add entry time and the creation timestamp of the managed ledger metadata.
- Updated ManagedLedgerImpl to implement these new methods.
- Enhanced PersistentTopic to utilize these timestamps for topic statistics.
- Added unit tests to verify the correct functionality of the new timestamps in various scenarios.
=> [improve][broker][pip-431] PIP-431: Add Creation and Last Publish Timestamps to Topic Stats

pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisRecord.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisRecordProcessor.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisRecordProcessorFactory.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSource.java, pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/KinesisRecordProcessorTest.java, pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/KinesisRecordTest.java
The current Kinesis source connector violates the `at-least-once` delivery guarantee, which can lead to data loss during failures or restarts. The root cause is that the Kinesis checkpointing is based on a time interval, completely decoupled from Pulsar's acknowledgment mechanism.
This creates a race condition that leads to data loss, as illustrated below:
- Time 1: KinesisRecordProcessor fetches record 0 from a Kinesis shard and puts it into the internal queue.
- Time 2: The KinesisSource thread reads record 0 from the queue and attempts to send it to a Pulsar topic, but the send operation is delayed or failing.
- Time 3: The KinesisRecordProcessor's timer triggers. It checkpoints its progress, marking that it has successfully processed up to record 0, even though this record has not yet …
=> [fix][io] Fix data loss issue in Kinesis source connector

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java
If no more message need to compact, then we should skip compaction task
*(or)*
*(or)*
*(example:)*
=> [improve][broker] Enhance compaction triggering with message check to avoid unnecessary operations

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TopicPolicies.java
Fix NPE which introduced by https://github.com/apache/pulsar/pull/21798.
The issue was happened when upgrading the old version cluster to 3.3.0 or later version.
Withe the old version broker, the delayed delivery policy was persistent to the system topic without `delayedDeliveryMaxDelayInMillis` but the new version broker try to convert null to a long value.
```
Message: Cannot invoke "java.lang.Long.longValue()" because the return value of "org.apache.pulsar.common.policies.data.TopicPolicies.getDelayedDeliveryMaxDelayInMillis()" is null
Stacktrace:
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "org.apache.pulsar.common.policies.data.TopicPolicies.getDelayedDeliveryMaxDelayInMillis( …
```
=> [fix][broker] Fix NPE when getting delayed delivery policy

pip/pip-429.md
=> [improve][pip] PIP-429: Optimize Handling of Compacted Last Entry by Skipping Payload Buffer Parsing

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java
The configuration code added in #16165 intends to set the default value of connectionMaxIdleSeconds in Pulsar Proxy to -1. This is not the case. The effective value is 60 since the value is set after the object is no longer used.
https://github.com/apache/pulsar/blob/08caff42b71e619b66094df6b3bcaeb1eba1e97a/pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java#L745-L746
full method code:
https://github.com/apache/pulsar/blob/08caff42b71e619b66094df6b3bcaeb1eba1e97a/pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java#L732-L767
- move the line of code a few lines earlier so that it gets used
- add a test
=> [fix][proxy] Fix default value of connectionMaxIdleSeconds in Pulsar Proxy

pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicList.java, pulsar-common/src/test/java/org/apache/pulsar/common/topics/TopicListTest.java
Pulsar's regular expression pattern-based consumers rely on hashing topic listings for a namespace. The hash for all topics in the namespace is calculated in multiple locations throughout the solution. For example, whenever a new topic is added or deleted, the hash will be recalculated for all topics in the namespace.
The current hash calculation implementation concatenates all topics into a single String instance, which is then passed to the hash calculation. This approach is suboptimal since the Guava Hashing API provides a way to calculate hashes of individual items. The current implementation causes unnecessary large java.lang.String and byte[] allocations. In the optimized version, no new java.lang.String instances are allocated, and the byte[] allocation consists of small …
=> [improve][misc] Optimize topic list hashing so that potentially large String allocation is avoided

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
RE2/J is used in topics pattern consumers on the broker side to match topics. There's a newer version 1.8 available that comes with some bug fixes and optimizations.
Release notes: https://github.com/google/re2j/releases/tag/re2j-1.8
Upgrade RE2/J library from 1.7 to 1.8
=> [improve][misc] Upgrade RE2/J to 1.8

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/test/MockedBookKeeperTestCase.java
Main Issue: #24497
When the `OpReadEntry#readEntriesComplete` is triggered by `RangeEntryCacheImpl#readFromStorage` with an empty list of entries, NPE will happen here: https://github.com/apache/pulsar/blob/bc5b933c0015beec8bb1907273c630730cffc853/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java#L95
Then `updateReadPosition` and `checkReadCompletion` will be skipped, where the result is very similar to https://github.com/apache/pulsar/issues/24497#issuecomment-3073740788
- The callback of `asyncReadEntries` will never complete
- The `entriesReadCount` will be updated but the `readPosition` won't
- `pendingReadOps` will not be reduced to 0
Unfortunately, from the existing analysis, the issue of 24497 might not be caused by this bug, but this NPE is still …
=> [fix][ml] Fix asyncReadEntries might never complete if empty entries are read from BK

pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisRecord.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisRecordProcessor.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisRecordProcessorFactory.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSource.java, pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/KinesisRecordProcessorTest.java
The Kinesis Source connector had several critical issues in its checkpointing mechanism that could lead to data loss, data duplication, or stalled processing.
1.  **Incorrect `shardEnded` Handling**: The connector did not correctly implement the `ShardRecordProcessor#shardEnded` method. It checkpointed at a specific sequence number instead of the required `SHARD_END` marker, which can cause the entire stream processing to stall during Kinesis resharding events. Reference: [Developing KCL 2.x Consumers in Java - shardEnded](https://docs.aws.amazon.com/streams/latest/dev/develop-kcl-consumers-java.html#kcl-java-interface-shardrecordprocessor)
2.  **Unreliable Periodic Checkpoints**: The periodic checkpoint logic was tied to the `processRecords` method. This is unreliable in Kinesis's …
=> [fix][io] Fix Kinesis checkpoint mechanism to prevent data duplication

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdConsume.java
[PIP-435](https://github.com/apache/pulsar/pull/24524) 
Add `startTimestamp` and `endTimestamp ` for  consuming message in client consume cli.
*(or)*
*(or)*
*(example:)*
=> [improve][client] Add `startTimestamp` and `endTimestamp` for consuming message in client cli

conf/broker.conf, conf/standalone.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicListService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicListServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicListWatcherTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplAuthTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicListWatcher.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImplTest.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/TopicListWatcherTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/lookup/GetTopicsResult.java, pulsar-common/src/main/java/org/apache/pulsar/common/topics/JDKTopicsPattern.java, pulsar-common/src/main/java/org/apache/pulsar/common/topics/MatchAllTopicsPattern.java, pulsar-common/src/main/java/org/apache/pulsar/common/topics/RE2JTopicsPattern.java, pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicList.java, pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicsPattern.java, pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicsPatternFactory.java, pulsar-common/src/test/java/org/apache/pulsar/common/topics/TopicListTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/topics/TopicsPatternFactoryTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/topics/TopicsPatternTest.java
PR #22829 introduced a breaking change by switching the regular expression library from JDK's `java.util.regex.Pattern` to RE2/J in the topics pattern consumer implementation. This change breaks backwards compatibility with advanced regular expressions that rely on features not supported by RE2/J.
**Problem**: RE2/J does not support certain regex features by design, such as negative lookaheads. A common use case is subscribing to all topics except those with specific prefixes. For example, the pattern `persistent://public/default/(?!(test2|test3|test4)-).+` should subscribe to all topics in the `public/default` namespace that don't start with `test2-`, `test3-`, or `test4-`.
**Current Behavior**: In Pulsar 4.0.x, this pattern fails with:
``` …
```
=> [fix][misc] Fix topics pattern consumer backwards compatibility

pulsar-io/kinesis/pom.xml, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSink.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSinkConfig.java, pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/KinesisSinkConfigTest.java
Fixes #24422
The Apache Pulsar KinesisSink utilises the KinesisProducer from the KPL. The KPL provides a comprehensive set of configuration parameters through its KinesisProducerConfiguration class.
In the current KinesisSink implementation, most of these parameters such as collectionMaxCount, collectionMaxSize, connectTimeout, maxConnections, and minConnections—are not configurable. This restricts users' ability to optimise the sink's performance, or meet network and operational requirements potentially affecting throughput, latency, and resource utilisation.
- Added the following KPL configuration parameters directly into the KinesisSink configuration.
| Parameter | Description |
|--------|--------|
| collectionMaxCount | Maximum number of items to pack into an PutRecords request. |
| …
=> [improve][io] Add support for the complete KinesisProducerConfiguration in KinesisSinkConfig

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/cache/RangeEntryCacheImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/test/MockedBookKeeperTestCase.java
In PR #24515, a change was made to ManagedLedgerFactoryImpl for testing the changes by adding a new parameter "EntryCacheCreator" to ManagedLedgerFactoryImpl. This conflicts with #24363 changes and one of the conflicts is that the EntryCache instance isn't designed to be instantiated on it's own and I'd like to keep the implementation details in package protected classes. There would be unnecessary complexity just to support this particular testing use cases.
There's already a way to test such changes with the PulsarMockReadHandleInterceptor which is supported by PulsarMockBookKeeper. This is why adding the "EntryCacheCreator" is not necessary.
- revert the changes to add "EntryCacheCreator" to ManagedLedgerFactoryImpl. 
- migrate the test added in #24515 to use …
=> [improve][test] Remove EntryCacheCreator from ManagedLedgerFactoryImpl

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/FailoverSubscriptionTest.java
**1. Pending read if no entries to read.**
- Cursor sets itself into `managedledger.waitingCursors` if there are no entries to read.
- Managed ledger triggers `cursor.notifyEntriesAvailable` once new entries were added.
**2, Double-check that it has more entries.**
- The cursor does an additional check if there are no entries to read<sup>[code-1]</sup>.
- The cursor delays the second checking if the configuration `newEntriesCheckDelayInMillis` is larger than `0`<sup>[code-1]</sup>.
**3. The variable waitingReadOp of cursor**
- It used to maintain an `OpReadEntry` to trigger a new read after getting notified that new entries were added.
- It prevents an issue from occurring, where more than one pending read is in progress
**4. The variable waitingCursors of Managed Cursor**
- It maintains …
=> [fix][broker] Fix Broker OOM due to too many waiting cursors and reuse a recycled OpReadEntry incorrectly

pom.xml, pulsar-io/kinesis/pom.xml
Kafka clients before 3.9.1 include CVE-2025-27818. Kafka clients are used in Pulsar IO Connectors.
- upgrade Kafka clients version to 3.9.1
- set the Confluent Platform version to 7.9.x so that it matches Kafka 3.9.x as explained in https://docs.confluent.io/platform/current/installation/versions-interoperability.html#cp-and-apache-ak-compatibility
- Apache Pulsar IO Connectors include ASL 2.0 licensed dependencies from Confluent Platform:
- io.confluent:kafka-connect-avro-converter
- io.confluent:kafka-schema-registry-client
- io.confluent:kafka-avro-serializer
=> [fix][sec] Upgrade Kafka connector and clients version to 3.9.1 to address CVE-2025-27818

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ZeroQueueSizeTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/GrowableArrayBlockingQueue.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/GrowableArrayBlockingQueueTest.java
Currently, when `consumer.receive()` is called, it blocks indefinitely even when the consumer is being closed. This can lead to threads hanging indefinitely in applications that need to gracefully shutdown consumers. The issue can be reproduced with:
``` java
Thread thread = new Thread(() -> {
try {
// sleep 0.1 second to close consumer to ensure consumer.receive() is triggerd
Thread.sleep(1000);
consumer.close();
} catch (Exception e) {
throw new RuntimeException(e);
}
});
thread.start();
// hangs forever
consumer.receive();
```
in fact, this could happen in many scenario as long as ```consumer.receive()``` called before ```consumer.close()```
**so, this PR aims to ensure that `consumer.receive()` will immediately throw an `IllegalStateException` when the consumer is being closed, …
=> [improve][client] Terminate consumer.receive() when consumer is closed

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerException.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ReadOnlyCursorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
Fixes #24566
The test `ReplicatorTest.testCloseReplicatorStartProducer` was consistently failing due to critical issues introduced in PR #24551. Investigation (shared in https://github.com/apache/pulsar/issues/24566#issuecomment-3119993989 by @3pacccccc ) revealed that the changes led to infinite recursive calls in `ManagedCursorImpl#cancelPendingReadRequest`, causing broker instability and test failures.
The root cause was improper state management for pending read operations, particularly when:
- Multiple threads attempt to cancel pending read requests concurrently
- Cursors are closed while read operations are pending
- OpReadEntry instances are recycled and reused incorrectly
- Cursor state transitions occur without proper synchronization
- Cursor deletion and closure operations race …
=> [fix][broker] Fix ManagedCursor state management race conditions and lifecycle issues

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/GrowableArrayBlockingQueueTest.java
Fixes https://github.com/apache/pulsar/issues/24575
This PR fixes the flaky test caused by incorrect operation order between ```countDown()``` and shared variable updates in https://github.com/apache/pulsar/pull/24550.
PR in forked repository: https://github.com/3pacccccc/pulsar/pull/19
=> [fix][test] fix flaky GrowableArrayBlockingQueueTest.testPollBlockingThreadsTermination

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicAutoCreationTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedProducerImpl.java
(cherry picked from commit 969920794840d5be884d039d9626acf64cb362a8)
=> [fix][client][branch-4.0] Partitioned topics are unexpectedly created by client after deletion (#24554)

tests/docker-images/latest-version-image/Dockerfile
"CI Flaky - System - Pulsar IO - Oracle" in Pulsar CI sometimes fails due to dependency download failing when the pulsar-io-debezium-oracle nar file was patched. Since the image is built in a previous step, it's hard to investigate the issue.
Refactor the way way pulsar-io-debezium-oracle nar file is patched when building the test image
=> [improve][test] Refactor the way way pulsar-io-debezium-oracle nar file is patched when building the test image

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
- Fixed NullPointerException in namespace deletion when redirecting to geo-replicated clusters
- Changed TLS URL selection logic to use remote cluster's TLS config instead of local broker's config
- Added comprehensive test coverage for all TLS configuration scenarios
When deleting a namespace that needs to be redirected to a remote cluster in geo-replication scenarios, the code was incorrectly using the local broker's TLS configuration (`config().isTlsEnabled() || \!isRequestHttps()`) to determine whether to use HTTP or HTTPS URLs for the redirect. This caused issues when:
1. Local broker had different TLS settings than the remote cluster
2. Remote cluster's `serviceUrlTls` was null but TLS logic tried to access it
3. Resulted in `NullPointerException: Cannot invoke "String.length()" …
=> [fix][broker] fix namespace deletion TLS URL selection for geo-replication

.github/actions/upload-coverage/action.yml, .github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml
Codecov metrics have been broken for Pulsar CI since the scheduled master branch build cannot upload metrics without a token. This PR passes the token provided in secrets to the Codecov action. The `CODECOV_TOKEN` secret has been added to `apache/pulsar` repository. This token is only used for `apache/pulsar` branch builds. For PR branch builds, uploads haven't been a problem and that could happen without a token or with the user provided token.
Additional information:
The `CODECOV_TOKEN` secret was added to `apache/pulsar` at https://github.com/apache/pulsar/settings/secrets/actions. The token value is available at https://app.codecov.io/gh/apache/pulsar/config/general for apache/pulsar committers after using GitHub login to login to Codecov.
- upgrade to v5 of …
=> [fix][ci] Fix code coverage metrics in Pulsar CI

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/SimpleProduceConsumeIoTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarHandler.java
There are several methods that get a connection from the `ConnectionPool`.
1. `ConnectionPool#getConnection(ServiceNameResolver)`
It's only used in `BinaryProtoLookupService`. The callbacks are all executed in `PulsarClientImpl#lookupExecutorProvider`: a single thread executor whose thread name starts with `pulsar-client-lookup`.
2. `ConnectionPool#getConnection(InetSocketAddress)`
It's called by the 1st method directly. Besides, it's only called by `BinaryProtoLookupService#findBroker`, which also uses `PulsarClientImpl#lookupExecutorProvider` to execute the callback.
3. `ConnectionPool#getConnection(InetSocketAddress logicalAddress, InetSocketAddress physicalAddress, int randomKey)`
It's called by the 2nd method directly. Besides, it's only called by the 4th method.
4. …
=> [fix][client] Retry for unknown exceptions when creating a producer or consumer

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheManagerTest.java
Fixes https://github.com/apache/pulsar/issues/24608
this test was flaky due to
**line108** in ```EntryCacheManagerTest.java``` of current master branch
already triggered cache eviction, so sometimes the eviction is over, sometimes not, cause this flaky.
1. Removed one entry insertion (`EntryImpl.create(2, 2, new byte[1]`) to:
- Ensure predictable cache eviction timing
- Maintain test's original purpose of verifying eviction logic
2. Updated all affected assertions to match the new expected cache sizes:
- Reduced expected sizes by 1 across all assertions
- Maintained consistent state validation throughout test flow
*(or)*
This change is already covered by existing …
=> [fix][test] Fix flaky EntryCacheManagerTest.simple

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/MessageExpirer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentMessageFinderTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
Broker checks TTL policies in the background per 5 minutes in a single thread. It calls a block method named `topic.isOldestMessageExpired`, which causes a prolonged thread blockage.
Instead of calling a block method, call a non-blocked method
=> [improve][broker]Remove block calling that named cursor.asyncGetNth when expiring messages

pulsar-common/pom.xml
Fixes #24611
See #24611 and https://github.com/apache/bookkeeper/issues/4647
Exclude commons-configuration2 and commons-beanutils in pulsar-common for bookkeeper library dependencies since they aren't needed.
=> [fix][misc] Exclude commons-configuration2 and commons-beanutils in pulsar-common

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicPolicyTestUtils.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/TopicPolicies.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicPoliciesImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopicPolicies.java
See the [PIP-422](https://github.com/apache/pulsar/blob/master/pip/pip-422.md)
- https://github.com/apache/pulsar/pull/24368
```
pulsar-admin topicPolicies delete <topic>
```
- Add Admin API to delete topic policies
=> [improve][broker]Part-2 Add Admin API to delete topic policies

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarChannelInitializer.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/MockBrokerService.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarChannelInitializer.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/FrameDecoderUtil.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ServiceChannelInitializer.java
Using the Pulsar Proxy could result in a `TooLongFrameException`.
When the Pulsar Proxy switches to direct proxy mode, it removes the frame decoder:
https://github.com/apache/pulsar/blob/baa288a0e5acdb7dca94e5c4b066e4a41e06fc55/pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java#L419-L426
However, this fails since the client changes the "frameDecoder" handler's name to "newFrameDecoder"
https://github.com/apache/pulsar/blob/baa288a0e5acdb7dca94e5c4b066e4a41e06fc55/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L396-L404
A possible workaround is to use `proxyZeroCopyModeEnabled=true` since in the zero copy mode, the channel handlers are ignored. The Zero copy mode cannot be enabled when TLS is enabled between the Pulsar Proxy and …
=> [fix][proxy] Fix TooLongFrameException with Pulsar Proxy

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ZeroQueueSizeTest.java
Fixes https://github.com/apache/pulsar/issues/24629
The flakiness occurs because ```batchingMaxPublishDelay``` was set too short(100ms), potentially causing message sent as non-batched message, which is not expected.
set ```batchingMaxPublishDelay``` as a very long time(10s) to ensure that all messages are sent as batch-message.
PR in forked repository: https://github.com/3pacccccc/pulsar/pull/22
=> [fix][test]fix flaky ZeroQueueSizeTest.testZeroQueueGetExceptionWhenReceiveBatchMessage

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/Ipv4Proxy.java
Fixes #24627
As shared in #24627, ZkSessionExpireTest is flaky. In the cleanup method, the main thread tries to close a PulsarService but then remains in WAITING state, and the test runs into the one hour timeout.
The logs shared in the issue contain a ConcurrentModificationException:
```
java.util.ConcurrentModificationException
at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
at org.apache.pulsar.broker.service.Ipv4Proxy.disconnectFrontChannels(Ipv4Proxy.java:87)
at org.apache.pulsar.broker.service.ZkSessionExpireTest.testTopicUnloadAfterSessionRebuild(ZkSessionExpireTest.java:149)
```
The ZkSessionExpireTest calls `Ipv4Proxy.disconnectFrontChannels()` to inject a ZK session expire error: …
=> [fix][test] Fix ConcurrentModificationException in Ipv4Proxy

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/NonProxyRoleTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyRoleAuthTest.java
- Fixes authorization issue where websocket connections using admin token authentication were incorrectly rejected when specifying an originalPrincipal
- Adds support for websocket principals to use originalPrincipal without requiring proxy role authentication
- Includes comprehensive test coverage for the new behavior
- Modified `AuthorizationService.java` to add websocket principal check in authorization logic
- Updated `ProxyRoleAuthTest.java` to make `ADMIN_TOKEN` accessible for test inheritance  
- Added `NonProxyRoleTest.java` to verify websocket proxy authentication without proxy role
=> [fix][ws] Allow websocket principals to specify originalPrincipal without proxy role

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
In race conditions, multiple threads could attempt to create the same non-durable cursor simultaneously.  
Adding a double-check ensures that if a cursor is already created by another thread while waiting in the synchronized block, the existing cursor is returned instead of creating a new one. This preserves thread safety and avoids duplicate cursor creation.
- Added a double-check inside the existing synchronized block for non-durable cursor creation.
=> [fix][broker] Add double-check for non-durable cursor creation

bouncy-castle/bc/LICENSE, bouncy-castle/bc/pom.xml, bouncy-castle/bcfips/LICENSE, distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
Upgrade bouncycastle version to 1.79 to address CVE-2025-8916.
Since all bouncycastle libraries don't have aligned version numbers, the pom.xml has been modified so that different versions can be specified.
This CVE also applies to the `org.bouncycastle:bcpkix-fips` dependency, but there's no 1.0.8 version available yet. That will be upgraded in another PR when the fix is available.
=> [fix][sec] Upgrade bouncycastle bcpkix-fips version to 1.79 to address CVE-2025-8916

pulsar-broker/src/test/java/org/apache/pulsar/client/metrics/ClientMetricsTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MemoryLimitController.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/metrics/InstrumentProvider.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/metrics/MemoryBufferStats.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/metrics/ObservableUpDownCounter.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/metrics/MemoryBufferStatsTest.java
Adds OpenTelemetry metrics to expose the status of the producer memory buffer defined by `producerMemoryLimit` in the Java client. This provides visibility into memory usage and helps with monitoring and alerting on client-side memory consumption.
Currently, there's no way to monitor the memory buffer usage of Pulsar Java clients. Users cannot:
- Track how much memory is being consumed by pending messages
- Set up alerts when memory usage approaches the configured limit
- Debug memory-related issues or performance bottlenecks
- Monitor memory efficiency across different client configurations
Two new OpenTelemetry metrics are added:
1. **`pulsar.client.memory.buffer.usage`** (bytes)
- Current memory buffer usage by the client
- Updates in real-time as messages are queued and sent
2. …
=> [improve][client] Add OpenTelemetry metrics for client memory buffer usage

distribution/server/src/assemble/LICENSE.bin.txt, distribution/shell/src/assemble/LICENSE.bin.txt, pom.xml
[fastutil](https://github.com/vigna/fastutil) is a primitive collection framework which is used in Pulsar. There are some bug fixes since 8.5.14 version that we are currently using:
- https://github.com/vigna/fastutil/blob/master/CHANGES
- upgrade fastutil from 8.5.14 version to 8.5.16
=> [fix][misc] Upgrade fastutil to 8.5.16

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpScan.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java
We do have an optimization(https://github.com/apache/pulsar/pull/21739) that skips messages that have already been acknowledged, but that doesn't prevent the ledger been opened. We can optimize it further by skipping the opening of those ledgers where all entries have already been acknowledged
Check if all entries in this ledger have been deleted (acknowledged). If so, skip opening the ledger and move to the next one.
*(or)*
*(or)*
*(example:)*
- …
=> [improve][ml] Optimize ledger opening by skipping fully acknowledged ledgers

docker/kinesis-producer-alpine/Dockerfile, docker/kinesis-producer-alpine/README.md, docker/kinesis-producer-alpine/build-alpine.sh, docker/kinesis-producer-alpine/kinesis_producer_alpine.patch, docker/pulsar-all/pom.xml, pom.xml, pulsar-io/aws/pom.xml, pulsar-io/kinesis-kpl-shaded/pom.xml, pulsar-io/kinesis/pom.xml, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSink.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSinkConfig.java, pulsar-io/kinesis/src/test/java/org/apache/pulsar/io/kinesis/KinesisSinkConfigTest.java, pulsar-io/pom.xml, tests/integration/pom.xml
[AWS Blog: Announcing end-of-support for Amazon Kinesis Client Library 1.x and Amazon Kinesis Producer Library 0.x effective January 30, 2026](https://aws.amazon.com/blogs/big-data/announcing-end-of-support-for-amazon-kinesis-client-library-1-x-and-amazon-kinesis-producer-library-0-x-effective-january-30-2026/)
* Upgrade AWS Kinesis Producer Library to 1.0.4 version 
* Upgrade AWS Kinesis Consumer Library to 3.1.2 version
* Resolve AWS SDK v2 library version conflicts that emerged after KPL 1.0.4 upgrade by aligning all versions with AWS SDK v2 bom. Set the version to latest 2.32.28
* For consistency, upgrade AWS SDK v1 library version to latest 1.12.788
* Shade AWS Kinesis Producer Library's Java library partially since it depends on protobuf-java 4.29.0 which is incompatible with Pulsar …
=> [improve][io] Upgrade AWS SDK v1 & v2, Kinesis KPL and KPC versions

.mvn/jvm.config
During CI builds, especially when building Docker images or specific modules, Maven occasionally fails with:
```
Error:  Could not acquire lock(s)
Error:  java.lang.IllegalStateException: Could not acquire lock(s)
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error: Process completed with exit code 1.
```
This occurs even in concurrent(`-T 1C`) builds because Maven's default lock wait time (30 seconds) can be insufficient in some CI environments. Increasing the lock wait time prevents these intermittent failures.
- Added the JVM option `-Daether.syncContext.named.time=300` to increase the maximum lock wait time to 5 minutes.
=> [improve][build] Increase maven resolver's sync context timeout

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpFindNewest.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/MessageExpirer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentMessageExpiryMonitor.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/bookkeeper/mledger/impl/PersistentMessageExpiryMonitorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java
**Background**: The steps of expiry of a topic
- Call expiry for each subscription
- The subscription finds the target position, then calls mark deleting for the cursor
- Call expiry for each replicator
- The replicator finds the target position, then calls mark deleting for the cursor
So the task calls for finding the target position many times when a topic expires. But the finding position operation is really expensive
The previous steps of expiring messages by position:
- Search the target position with a binary search
- Expire messages by the target position.
It costs a lot, we can simplify the steps by `managedLedger.getPreviousPosition(x)`
Since all of the tasks that find the target position that relates to the same topic will get the same result, we can call the finding operation …
=> [improve][broker]Find the target position at most once, during expiring messages for a topic, even though there are many subscriptions

pulsar-broker/src/test/java/org/apache/pulsar/client/api/PartitionCreationTest.java
https://github.com/apache/pulsar/pull/24651 changed the behaviour, which allows creating partitions if the partitioned topic metadata exists. Then the test `PartitionCreationTest.testCreateMissedPartitions` is not suitable anymore.
It can pass when merging #24651 because the test has another issue: it calls `createPartitionedTopicAsync`, but never waits for it to be finished, which leads to the next check passing because the creation may not have completed.
Improve the test
=> [fix][broker]Fix flaky test PartitionCreationTest.testCreateMissedPartitions

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SystemTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/systopic/NamespaceEventsSystemTopicFactory.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SnapshotSegmentAbortedTxnProcessorImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/OneWayReplicatorUsingGlobalZKTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/SystemTopicNames.java
- Users may start 2 clusters with the Geo-Replication feature with Global ZK
- Users want to hire one cluster, so remove the cluster from `namespace-level replicatedClusters`
- Broker will remove the topics because the cluster was removed.
- Issue occurs:
- User topics can not be deleted anymore, because the operation `delete data from transaction buffer` can not be executed successfully anymore, and will get an error "Namespace missing local cluster name in clusters list". Because the topic `__transaction_buffer_snapshot` can not be accessed anymore since the cluster was removed.
- The task `topic.checkReplication` and other operations will retry again and again, as a result, the broker will crash of OOM  
- Do not create the transaction buffer component for transaction system topics.
- …
=> [fix][broker]User topic failed to delete after removed cluster because of failed delete data from transaction buffer topic

pip/pip-382.md
- [DIscussion](https://lists.apache.org/thread/f3xhmm342jor042n5ykkxoc32ffcn85s)
- [Vote](https://lists.apache.org/thread/ng6z0dssjh1hgp91f590wkcl2ymhvn48)
=> [improve] [pip] PIP-382: Add a label named reason for topic_load_failed_total

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/PartitionCreationTest.java
To reproduce the issue:
- Create a partitioned topic with 2 partitions
- All partitions are deleted because the feature `brokerDeleteInactiveTopicsEnabled` is `true`
- Try to get the topic-level policies; you will get a Topic not found error
The master branch does not have the issue because #24225 have fixed it [here](https://github.com/apache/pulsar/pull/24225/files#diff-6902810fd24ff29ec34052bcc6a0de36d76107649148d945b80ec2be888e9042L734-R778)
fix the issue
=> [fix][broker][branch-4.0]Can not access topic policies if topic partitions have not been created

pulsar-client/src/main/java/org/apache/pulsar/client/impl/TypedMessageBuilderImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/TypedMessageBuilderImplTest.java
The PIP-420 introduced a new method to encode payload; it requires the topic name, but in some cases, the producer in `TypedMessageBuilderImpl` may be null, which will lead to an NPE issue.
Add a null check while getting the topic name in `TypedMessageBuilderImpl`.
=> [fix][client] Fix potential NPE in TypedMessageBuilderImpl

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
Upgrade the oxia-java client version to 0.6.1 to apply the latest fixes.
- upgrade oxia-java client version
=> [feat][misc] upgrade oxia version to 0.6.2

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java
**Background**
- The oldest behaviour of offload settings: Pulsar only supports setting Broker-level offload policies and namespace-level thresholds. and handle namespace-level thresholds by the following fields:
- `{@link Policies#offload_deletion_lag_ms}`
- `{@link Policies#offload_threshold}`
- `{@link Policies#offload_threshold_in_seconds}`
- After https://github.com/apache/pulsar/pull/6183, Pulsar supports namespace-level policies, which were supported by `{@link Policies#offload_policies}`. And the thresholds were moved to the following fields:
- `{@link Policies#offload_policies} -> {@link OffloadPoliciesImpl#getManagedLedgerOffloadDeletionLagInMillis}`
- ` {@link Policies#offload_policies} -> {@link OffloadPoliciesImpl#getManagedLedgerOffloadThresholdInBytes}`
- `{@link …
=> [fix][broker]Fix dirty reading of namespace level offload thresholds

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorContainer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
I observed the following NPE when I ran some tests.
```
2025-09-05 10:49:38.826 [pulsar-msg-expiry-monitor-OrderedScheduler-0-0] WARN  org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService - Unexpected throwable from task class com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask: Cannot invoke "org.apache.bookkeeper.mledger.impl.ManagedCursorContainer$CursorInfo.getCursor()" because the return value of "org.apache.bookkeeper.mledger.impl.ManagedCursorContainer.getCursorWithOldestPosition()" is null
java.lang.NullPointerException: Cannot invoke "org.apache.bookkeeper.mledger.impl.ManagedCursorContainer$CursorInfo.getCursor()" because the return value of …
```
=> [fix][broker] Fix NPE and annotate nullable return values for ManagedCursorContainer

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternConsumerUpdateQueue.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicListWatcher.java
In PatternMultiTopicsConsumerImpl, if watcherFuture is not done, the closeAsync() method will not close TopicListWatcher.
https://github.com/apache/pulsar/blob/2e6a8eb1f200ca687064058a101963713b896fe2/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternMultiTopicsConsumerImpl.java#L388-L395
Re-write the closeAsync() method to make sure TopicListWatcher is closed. See file changes.
This change is already covered by existing tests, see PatternMultiTopicsConsumerImplTest.
=> [fix][client]TopicListWatcher not closed when calling PatternMultiTopicsConsumerImpl.closeAsync() method

.asf.yaml
Pulsar 4.1.0 has been released and we shouldn't allow force pushes to branch-4.1 .
- Add configuration to `.asf.yaml` to protect `branch-4.1`
=> [improve][misc] Protect branch-4.1

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/DataSketchesOpStatsLogger.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/DataSketchesSummaryLogger.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/ThreadLocalAccessor.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/prometheus/metrics/ThreadLocalAccessorTest.java
See https://github.com/apache/pulsar/pull/24714#issuecomment-3266369903
Currently this issue rarely happens because most metrics updates happen in Netty I/O threads when handling requests. However, `DataSketchesOpStatsLogger` and `DataSketchesSummaryLogger` are public and can be used by downstream plugins (e.g. protocol handlers).
- Refactor the code by adding a `record` method to `LocalData` and `ThreadLocalAccessor` responsible for updating the metrics.
- Then, add `ThreadLocalAccessorTest` to verify when the metrics are updated in a normal thread (not `FastThreadLocalRunnable`), the `LocalData` objects won't be removed from the map in `ThreadLocalAccessor`
- Fix this issue by introducing a weak reference that holds the current thread when creating a `LocalData` in a non-Netty thread …
=> [fix][broker] Fix memory leak when metrics are updated in a thread other than FastThreadLocalThread

pip/pip-437.md
PIP: 437
The current system lacks administrative controls on message delivery delays, which introduces risks to cluster stability and data integrity. This proposal aims to provide granular control at the topic and namespace levels to add a fixed delay delivery configuration 
*(or)*
*(or)*
*(example:)*
=> [improve][pip] PIP-437: Granular and Fixed-Delay Policies for Message Delivery

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeExclusiveStickyKeyConsumerSelector.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/HashRangeExclusiveStickyKeyConsumerSelectorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionTest.java
This PR fixes a critical bug where the `KeyShared` sticky mode consumer in Pulsar would incorrectly consume messages from hash ranges not explicitly assigned to it. 
Specifically, if a single `KeyShared` consumer is configured with non-contiguous sticky ranges, e.g.:
- `[0, 9999]`
- `[20000, 29999]`
- `[40000, 49999]`
The consumer would incorrectly receive messages for keys falling into the gaps (e.g., `15000` which is between `9999` and `20000`). 
The root cause lies in the `HashRangeExclusiveStickyKeyConsumerSelector`'s `select` method, which previously stored only the start/end points of ranges in its `rangeMap`. This led to an erroneous interpretation where any hash between a range's `end` and the next range's `start` would be assigned to the previous range's consumer. …
=> [fix][broker] Ensure KeyShared sticky mode consumer respects assigned ranges

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BkEnsemblesTestBase.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerBkEnsemblesTest.java
Our pulsar cluster encountered an issue where the response of the command `pulsar-admin topics stats --get-precise-backlog --get-subscription-backlog-size  <topic>` has a negative backlog.
And topic internal stats show that a consumer acknowledged messages that do not exist in `topic.ledgers`
- ledgerInfo:  `{"ledgerId":1140377,"entries":5,"size":45573,"offloaded":false,"metadata":null,"underReplicated":false}`
- But the acknowledged more entries: `(1140377:-1..1140377:6]`
---
The issue happened this way:
- Configurations
- `managedLedgerDefaultEnsembleSize=2`
- `managedLedgerDefaultWriteQuorum=2`
- `managedLedgerDefaultAckQuorum=2`
- Topic state
- `ledgers`: `[3: {entries: 1}]`
- Scenarios
-  `bookie-2` is slow
- ZK connections are unstable, which may cause a race condition on owning …
=> [fix][ml] Negative backlog & acked positions does not exist & message lost when concurrently occupying topic owner

build/run_unit_group.sh, buildtools/pom.xml, pom.xml, pulsar-bom/pom.xml
Fixes #24740
- Release notes:
- all: https://github.com/apache/maven-apache-parent/releases
- Changes since parent pom version 29:
- https://github.com/apache/maven-apache-parent/compare/apache-29...apache-35
- upgrade Apache Parent POM to version 35
=> [improve][build] Upgrade Apache Parent POM to version 35

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml
Certain components of BookKeeper are still including the old `commons-lang` dependency (which is already replaced by `commons-lang3`.
We should exclude to avoid CVE: 
```
│ commons-lang:commons-lang                                   │ CVE-2025-48924 │ MEDIUM   │          │ 2.6               │                │ commons-lang/commons-lang: org.apache.commons/commons-lang3: │
│ (commons-lang-commons-lang-2.6.jar)                         │                │          │          │                   │                │ Uncontrolled Recursion vulnerability in Apache Commons Lang  │
│                                                             │                │          │          │                   │                │ https://avd.aquasec.com/nvd/cve-2025-48924                   │ …
```
=> [fix] Exclude commons-lang dep from bookkeeper

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorTest.java
Fixes #24737
Pulsar ProtocolHandler, such as KoP, uses `ManagedLedgerImpl#asyncFindPosition` to find `startCursorPosition` and  create a NonDurableCursor.
When a topic's ledger is trimmed and is empty, `startCursorPosition` will be (currentLedgerId, -1).
However, the created NonDurableCursor's readPosition is not stable if Topic ledger is adding a new entry simultaneously. 
It may be (currentLedgerId, 0) or (currentLedgerId, 2).
We expect the created NonDurableCursor readPosition to always be (currentLedgerId, 0).
In NonDurableCursorImpl constructor, we declare a reference to `ManagedLedgerImpl#lastConfirmedEntry` and use it to compare with `startCursorPosition` and to `initializeCursorPosition`.
Run new test `NonDurableCursorTest#testOpenNonDurableCursorWhileLedgerIsAddingFirstEntryAfterT …
=> [fix][broker] First entry will be skipped if opening NonDurableCursor while trimmed ledger is adding first entry.

.github/workflows/ci-owasp-dependency-check.yaml, .github/workflows/pulsar-ci-flaky.yaml, .github/workflows/pulsar-ci.yaml, .mvn/extensions.xml
Java 25 LTS has been released. There's already support for starting a build with Java 25, but the build fails.
The build fails with unknown JVM option in `MAVEN_OPTS`. There's also another issue since the Gradle Develocity Maven extension version doesn't support Java 25. [Apache's Develocity server](https://develocity.apache.org/scans?search.rootProjectNames=pulsar) is used for Pulsar build analytics.
- add `-XX:+IgnoreUnrecognizedVMOptions` to `MAVEN_OPTS`
- upgrade Gradle Develocity Maven extension dependencies
=> [fix][ci] Fix CI for Java 25 including upgrade of Gradle Develocity Maven extension

pom.xml
To build with JDK25, SpotBugs needs to be upgraded.
- upgrade SpotBugs to latest version 4.9.6
=> [improve][build] Upgrade SpotBugs to a version that supports JDK25

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
Fixes #24765
Revise `BrokerServiceTest.testShutDownWithMaxConcurrentUnload`, since #24731 fixed the issue where the broker couldn’t be shut down via pulsar admin. The original test contains a race condition in its assertion.
```java
admin.brokers().shutDownBrokerGracefully(1, false);
Awaitility.await().atLeast(bundleNum - 1, TimeUnit.SECONDS).untilAsserted(() -> {
assertEquals(pulsar.getBrokerService().getTopics().size(), 0);  // race condition: pulsar.getBrokerService() is possibly be null because the broker is shutting down
});
```
=> [fix][test] Flaky-test: BrokerServiceTest.testShutDownWithMaxConcurrentUnload

tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImpl.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/OffloadIndexEntryImpl.java, tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/BlobStoreBackedReadHandleImplTest.java
The steps of reproducing the issue:
- We have a ledger, which contains `5` entries, the last confirmed is `4`
- Enable offloading for a topic
- Read the first round: `[0 ~ 3]`
- Read the second round `[0 ~ 4]`, the error will occur.
```
2025-09-11T11:22:09,210+0000 [offloader-OrderedScheduler-1-0] ERROR org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreBackedReadHandleImpl - Failed to read entries 0 - 10 from the offloader in ledger 1670362
java.io.EOFException: null
at java.base/java.io.DataInputStream.readFully(Unknown Source) ~[?:?]
at java.base/java.io.DataInputStream.readInt(Unknown Source) ~[?:?]
at org.apache.bookkeeper.mledger.offload.jcloud.impl.BlobStoreBackedReadHandleImpl.lambda$readAsync$2(BlobStoreBackedReadHandleImpl.java:171) ~[?:?]
at …
```
=> [fix][ml]Fix EOFException after enabled topics offloading

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/extensions/models/TopKBundlesTest.java, pulsar-client-admin-api/src/main/java/org/apache/pulsar/policies/data/loadbalancer/NamespaceBundleStats.java, pulsar-client-admin-api/src/test/java/org/apache/pulsar/policies/data/loadbalancer/NamespaceBundleStatsTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/CompareUtil.java, pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/ResourceUnitRanking.java, pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/TimeAverageMessageData.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/CompareUtilTest.java, pulsar-common/src/test/java/org/apache/pulsar/policies/data/loadbalancer/TimeAverageMessageDataTest.java
Fixes #24754
- JVM's default sorting algorithm "TimSort" will fail with `java.lang.IllegalArgumentException: Comparison method violates its general contract!` if `compareTo` doesn't meet [the contract of `Comparable.compareTo` interface](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Comparable.html#compareTo(T))
The contract of `Comparable.compareTo`:
* The implementor must ensure [signum](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Integer.html#signum(int))(x.compareTo(y)) == -signum(y.compareTo(x)) for all x and y. (This implies that x.compareTo(y) must throw an exception if and only if y.compareTo(x) throws an exception.)
* The implementor must also ensure that the relation is transitive: (x.compareTo(y) > 0 && y.compareTo(z) > 0) …
=> [fix][misc] Fix compareTo contract violation for NamespaceBundleStats, TimeAverageMessageData and ResourceUnitRanking

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ConnectionPoolTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/DnsResolverGroupImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
There "PIP-234: Support using shared thread pool across multiple Pulsar client instance", https://github.com/apache/pulsar/issues/19074, which never went forward. The intention is that multiple Pulsar clients could share resources. This is not only needed for thread pools, but also for the Netty DNS resolver cache which is represented by `io.netty.resolver.dns.DnsAddressResolverGroup` in Netty.
PIP-234 has been discussed in the past in threads
* https://lists.apache.org/thread/5jw06hqlmwnrgvbn9lfom1vkwhwqwwd4
* https://lists.apache.org/thread/5obfm17g58n3dnbzyxg57vokgmwyp6hx
Since we don't want to expose Netty internals on the public API, a PulsarClientGroup API has been discussed earlier to abstract this.
Before PIP-234 becomes a reality, it's useful to have an internal API for sharing …
=> [improve][client/broker] Add DnsResolverGroup to share DNS cache across multiple PulsarClient instances

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java
Fixes #xyz
PIP: #xyz 
**log:** https://gist.github.com/Denovo1998/c48c58c1de0270a4008ae77b6161adfb
- Running the full ExtensibleLoadManagerImplTest occasionally fails at testDisableBroker. After calling disableBroker(), the broker unregisters and the channel cleans ownerships. However, subsequent checkOwnershipAsync/getOwnerAsync against the disabled broker could still trigger a liveness verification on metadata-based table view, which throws a MetadataStoreException (wrapped by ExecutionException), causing flaky failures in full-suite runs.
- Meanwhile, ServiceUnitStateChannelTest has explicit expectations on disabled/closed channels:
- isOwner should still return true for Owned or Splitting states if the local broker is the designated owner/source,
- getOwnerAsync …
=> [fix][broker] Flaky-test: ExtensibleLoadManagerImplTest.testDisableBroker

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/BrokerOperabilityMetrics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/BrokerOpenTelemetryTestUtil.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/OpenTelemetryBrokerOperabilityStatsTest.java
PIP: #21080
Please see the [PIP-264 doc](https://github.com/apache/pulsar/blob/v4.1.1/pip/pip-264.md).
ref.
* https://github.com/apache/pulsar/blob/v4.1.1/pip/pip-264.md#switching-summary-to-histograms-in-namespacebroker-level-only
* https://github.com/apache/pulsar/blob/v4.1.1/pip/pip-264.md#which-summaries--histograms-are-effected
* Added publish latency histogram as OTel metrics
* Added `PulsarDeprecatedMetric` annotation to the `pulsar_broker_publish_latency` Prometheus metrics
- Added a simple E2E test to verify the expected metrics is exposed
- Introducing the new OTel metrics `pulsar.broker.topic.publish.latency` …
=> [feat][monitor] Add publish latency histogram as OTel metrics
