.travis.yml, .travis/settings.xml
* Automatically upload snapshot and release artifacts to OSS sonatype
* Releases are automatically synced to maven central
* Distribution tar.gz files uploaded to github releases page
=> Deploy artifacts to OSS sonatype and github release page

pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ConsumerImpl.java
```fetchSingleMessageFromBroker()``` was synchronized which has blocking call on ```incomingMessages.take()``` and at the time of reconnection: OpenConnection-thread gets blocked as mutex is already acquired by fetchSingleMessageFromBroker-thread and it creates a deadlock on consumer-side.
remove synchronized on ```fetchSingleMessageFromBroker``` method and caller acquires a lock so, we can make sure that multiple threads can't access ```fetchSingleMessageFromBroker``` method.
It will avoid possible deadlock.
=> avoid synchronization for method that blocks while fetching zero-queue message

docs/AdminTools.md, pulsar-client-tools/src/main/java/com/yahoo/pulsar/admin/cli/CmdPersistentTopics.java
AdminTools Documentation:
- incorrect REST API url
- Missing Expire-Message api
AdminTools Documentation:
- Fix: REST API url
- Add doc for Expire-Message api
No functionality change.
=> Admin-api-tool doc: Fix REST api url, add expire-messge api doc

pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/Consumer.java, pulsar-broker/src/test/java/com/yahoo/pulsar/client/api/SimpleProducerConsumerTest.java
If Consumer is blocked due to unacked messages then redelivery of messages will not dispatch messages.
On redelivery request : unblock consumer and dispatched requested redelivery-messages.
It will allow blocked consumer to redeliver requested messages.
=> fix: flow permits on blocked consumer while redelivery of messages

docs/GeoReplication.md
Minor change to fix typo in pulsar-admin command.
=> Fix typo in pulsar-admin

pom.xml, pulsar-broker/pom.xml, pulsar-broker/src/test/java/com/yahoo/pulsar/broker/service/AdvertisedAddressTest.java, pulsar-broker/src/test/java/com/yahoo/pulsar/broker/service/BrokerServiceTest.java, pulsar-broker/src/test/java/com/yahoo/pulsar/discovery/service/web/DiscoveryServiceWebTest.java, pulsar-broker/src/test/java/com/yahoo/pulsar/websocket/proxy/SimpleConsumerSocket.java, pulsar-broker/src/test/java/com/yahoo/pulsar/websocket/proxy/SimpleProducerSocket.java, pulsar-client-admin/pom.xml, pulsar-client-admin/src/main/java/com/yahoo/pulsar/client/admin/BrokerStats.java, pulsar-client-admin/src/main/java/com/yahoo/pulsar/client/admin/internal/BrokerStatsImpl.java, pulsar-client-tools/src/main/java/com/yahoo/pulsar/admin/cli/CmdBrokerStats.java, pulsar-client/pom.xml, pulsar-websocket/pom.xml, pulsar-websocket/src/test/java/com/yahoo/pulsar/proxy/socket/client/SimpleTestProducerSocket.java
[Issue #86](https://github.com/yahoo/pulsar/issues/86)
Replaced org.json with gson whose license is Apache 2.0.
=> Replaced Json Library

pom.xml
BookKeeper Changes included:
* [a25b53] Removed unused SortedLruCache
* [74cd2f] Removed unused DbLedgerStorage configuration keys
* [fb279e] Reorder read operations based on Bookie availability
* [d203c2] DataSketches metrics provider
* [17ab66] Catch IndexOutOfBoundsException when reading entry log index map
* [270b69] Fixed NPE when accessing readonly bookie list
=> Updated to BK-4.3.1.45-yahoo

pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ConsumerImpl.java
[ConsumerImpl.messageReceived()](https://github.com/yahoo/pulsar/blob/master/pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ConsumerImpl.java#L615) computes ```numMessages``` added into ```incomingMessages``` and asynchronously ```take()``` from the queue and call ```msg-callback``` using ```listenerExecutor (default thread=1 and being shared across all other consumers)```. Now, in case of ```redeliverUnacknowledgedMessages/connectionOpened``` which clears out ```incomingMessages``` and that can block [Listener-thread](https://github.com/yahoo/pulsar/blob/master/pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ConsumerImpl.java#L668) as it expects earlier computed ```numMessages``` in the queue. And in that scenario all other consumers which share same …
=> Stop consuming messages from consumer-listener if incoming-queue is cleared

all/pom.xml, managed-ledger/pom.xml, pom.xml, pulsar-broker-common/pom.xml, pulsar-broker/pom.xml, pulsar-checksum/pom.xml, pulsar-client-admin/pom.xml, pulsar-client-tools/pom.xml, pulsar-client/pom.xml, pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/PartitionedConsumerImpl.java, pulsar-common/pom.xml, pulsar-discovery-service/pom.xml, pulsar-storm/pom.xml, pulsar-testclient/pom.xml, pulsar-websocket/pom.xml, pulsar-zookeeper-utils/pom.xml
Add more debug logs to client-consumer at receive, ack, redelivery api process.
=> Add more debug logs to client-consumer

pulsar-client-admin/src/main/java/com/yahoo/pulsar/client/admin/PersistentTopics.java, pulsar-client-admin/src/main/java/com/yahoo/pulsar/client/admin/internal/PersistentTopicsImpl.java
Add missing admin async reset cursor
=> Async reset cursor

pom.xml
BookKeeper Changes included:
- [9560ab0](https://github.com/yahoo/bookkeeper/commit/9560ab0f9229da404c88c8c9b3782d5c4e49a032) AsyncReadLastEntry: Handle invalid entry and trigger call back with error
=> Updated to 4.3.1.47-yahoo

pulsar-discovery-service/src/test/java/com/yahoo/pulsar/discovery/service/DiscoveryServiceTest.java
Intermittent test failure on DiscoveryServiceTest: #116 
Fix #116 Intermittent test failure on DiscoveryServiceTest by explicitly refreshing cache rather depending on async-watch updater in MockZookeeper.
=> Intermittent test failure on DiscoveryServiceTest

pulsar-broker/src/test/java/com/yahoo/pulsar/websocket/proxy/SimpleConsumerSocket.java, pulsar-broker/src/test/java/com/yahoo/pulsar/websocket/proxy/SimpleProducerSocket.java
List is being modified by different threads and result might not be visible in the the testng main thread
=> Fix #206 - Intermittent test failure in ProxyPublishConsumeTest

pulsar-broker/src/test/java/com/yahoo/pulsar/websocket/proxy/ProxyPublishConsumeTest.java, pulsar-broker/src/test/java/com/yahoo/pulsar/websocket/proxy/ProxyPublishConsumeWithoutZKTest.java, pulsar-broker/src/test/java/com/yahoo/pulsar/websocket/proxy/SimpleConsumerSocket.java
More flaky tests. Fixed by polling on the completion condition
=> Issue #206: Fixed flaky web socket proxy test

pulsar-broker/src/main/java/com/yahoo/pulsar/broker/stats/metrics/JvmMetrics.java, pulsar-broker/src/test/java/com/yahoo/pulsar/broker/stats/BookieClientsStatsGeneratorTest.java
=> Derive direct memory used count from netty counter (#223)

pulsar-client-cpp/travis-build.sh
Caching C++ build dependencies
Changed travis-build.sh
Faster C++ Build
=> Updated CPP Travis build script to use cached dependencies.

docs/AdminTools.md
Fix `GettingStarted.md` link in `AdminTools.md`
=> add hyperlink for getting-started doc

docs/Architecture.md
typo in code sample in doc
fixes typo
no more typo and code sample compiles
=> typo in the doc

pom.xml
Changes includes:
* Fixes for 64bit ledger ids
* Fixed memory leak on read-only bookies
* Fixed datasketches metric provider concurrency issue
Fixes #258
=> Update BK to 4.3.1.60-yahoo

docs/Authentication.md
Documents for Athenz authentication is helpful for users who wants to use it.
Added documents for how to configure Athenz authentication plugin to Authentication.md.
=> Add Athenz document

pulsar-client-cpp/tests/UrlTest.cc
Increase CPP Client test coverage
Added a few more checks in URL Tests.
More test coverage
=> Added more checks in URL Tests

pulsar-client-admin/src/main/java/com/yahoo/pulsar/client/admin/PulsarAdmin.java
`Authentication#start()` should be called before calling `Authentication#getAuthData()`,
but the order is reversed in PulsarAdmin.
Call `Authentication#start()` before calling `Authentication#getAuthData()`.
Authentication plugin which must be started before providing auth data can work.
=> Start auth service before providing auth data in PulsarAdmin

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorContainer.java, pulsar-broker/src/main/java/com/yahoo/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java, pulsar-broker/src/main/java/com/yahoo/pulsar/broker/loadbalance/impl/SimpleResourceAllocationPolicies.java, pulsar-broker/src/main/java/com/yahoo/pulsar/broker/namespace/NamespaceService.java, pulsar-client-admin/src/main/java/com/yahoo/pulsar/client/admin/PulsarAdmin.java, pulsar-client-tools/src/main/java/com/yahoo/pulsar/client/cli/CmdProduce.java, pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ConsumerStats.java, pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ProducerStats.java, pulsar-common/src/main/java/com/yahoo/pulsar/common/policies/impl/NamespaceIsolationPolicies.java
Here are the list of issues reported by fbinfer(http://fbinfer.com/):
https://gist.github.com/saandrews/213313d8f17932fde01a2968475c1898
No change to feature or tests
=> Fixes to some of the issues reported by fbinfer static code analyzer

docs/BinaryProtocol.md
Image diagrams are not currently show on the BinaryProtocol page.
=> In BinaryProtocol.md use %20 in image links

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryCacheImpl.java
As reported on #383 there is a potential stack overflow when replaying a large number of entries that are being served from cache. Since the entries are immediately available, the callback is triggered in the same thread and that leads to chain it with the next read call.
Trigger replay read callback from background thread to break the stack chain and avoid recursion.
=> Send replay entries read callback from background thread, to avoid recursive stack calls

all/pom.xml, pom.xml, pulsar-common/src/main/java/com/yahoo/pulsar/common/api/DoubleByteBuf.java, pulsar-zookeeper-utils/pom.xml
A fair amount of fixes went into netty since version 4.0.40
=> Upgrade to netty-4.0.46

.gitignore
Ignore bin/ directories in submodules
=> Ignore bin/ directories in submodules

pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java, pulsar-broker/src/test/java/com/yahoo/pulsar/broker/service/PersistentTopicE2ETest.java
As part of #398 : In usecase when shared-subscription has large number of unack messages, redelivery makes `PersistentDispatcherMultipleConsumers` to store large number of `PositionImpl` into `messagesToReplay` set which can be a one of the factor for frequent gc at broker. So, storing message-positions into primitive set can help to improve gc.
Note: rebased on #405 
Change `messagesToReplay` type to `ConcurrentLongPairSet`
No functional change.
=> Replace messagesToReplay set to ConcurrentLongPairSet to improve gc

docs/AdminTools.md
- Fixed links
- Fixed a statement
=> Fixed AdminTools.md related to persistent topic permissions

pom.xml
Use ZK 3.4.10 since it has the fast leader election fixes. ZOOKEEPER-2678
=> Update ZK version to 3.4.10

pulsar-client-cpp/lib/HTTPLookupService.cc, pulsar-client-cpp/lib/LookupDataResult.h, pulsar-client-cpp/lib/Result.cc
Recently we noticed that a few producers were unable to reconnect to the vip after the broker shutdown. Unfortunately, during that time we had no logs since - #426 was not merged but from the broker, logs can see that in some cases after a few HTTP 500 responses from the broker the client stopped client.
I have added some more logging and better handling for HTTP 500 response - so that we are better prepared in future.
Another issue was that because we didn't handle all errors we keep getting Unknown errors - after this release, we will no longer get unknown error codes. 
a. Added more logging to HTTPLookupService
b. Added toString function to LookUpDataResult
c. Added more cases under switch.
In case you are worried about adding more log messages lookup is done **only** during creation …
=> C++ Client - Better handling and logging for curl response.

managed-ledger/src/test/java/org/apache/zookeeper/MockZooKeeper.java
As explained in #434 there is a deadlock in unit test triggered related to the MockZooKeeper implementation.
Replaced `synchronized` block with a `ReentrantMutex` and make sure mutex is unlocked before triggering the callbacks.
Fix the deadlock.
=> In MockZooKeeper triggers callback without holding mutex

pulsar-client-cpp/lib/ProducerConfigurationImpl.h
=> C++ Client - Batch Messages - changing group commit time to 10ms

pulsar-client-cpp/lib/ObjectPool.h, pulsar-client-cpp/lib/SharedBuffer.h, pulsar-client-cpp/tests/ConsumerStatsTest.cc
Small compilation fixes with newer GCC on Ubuntu 17.04
=> Small compilation fixes for GCC 6.3

pulsar-broker/src/main/java/com/yahoo/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/com/yahoo/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/main/java/com/yahoo/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java, pulsar-broker/src/test/java/com/yahoo/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-broker/src/test/java/com/yahoo/pulsar/broker/service/PersistentTopicTest.java, pulsar-broker/src/test/java/com/yahoo/pulsar/client/api/DispatcherBlockConsumerTest.java
Last change added closing the LoadManager on PulsarService shutdown, but that exposed and NPE. Also added logs when exception is thrown in the cleaning up phase.
=> Fixed NPE on load manager shutdown

pulsar-broker/src/test/java/com/yahoo/pulsar/broker/namespace/OwnershipCacheTest.java
Added extra sleep between steps.
=> Add extra wait to avoid intermittent failures in OwnershipCacheTest

pulsar-testclient/src/main/java/com/yahoo/pulsar/proxy/socket/client/PerformanceClient.java
Authentication function of WebSocket Performance tool doesn't work in spite of getting parameters.
Make performance client get auth header and set it.
Authentication function by http header works.
=> Add authetication by http header in WebSocket performance tool

pulsar-zookeeper/src/main/java/com/yahoo/pulsar/zookeeper/ZooKeeperServerAspect.java
In 1.18 release there is a problem in starting the standalone broker.
```
$ bin/pulsar standalone
2017-06-22 17:15:11,865 - INFO  - [main:LocalBookkeeperEnsemble@100] - Running 1 bookie(s).
2017-06-22 17:15:11,893 - INFO  - [main:LocalBookkeeperEnsemble@124] - Starting ZK server
2017-06-22 17:15:11,960 - ERROR - [main:LocalBookkeeperEnsemble@142] - Exception while instantiating ZooKeeper
java.lang.IllegalArgumentException: Collector already registered that provides name: zookeeper_server_znode_count
at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:54)
at io.prometheus.client.Collector.register(Collector.java:128)
at io.prometheus.client.Collector.register(Collector.java:121)
at com.yahoo.pulsar.zookeeper.ZooKeeperServerAspect.timedProcessRequest(ZooKeeperServerAspe …
```
=> Fixed problem in starting ZK server for standalone mode

README.md, all/pom.xml, docs/GettingStarted.md, docs/PulsarSpark.md, docs/PulsarStorm.md, docs/locale/ja/GettingStarted.md, docs/locale/ja/PulsarSpark.md, docs/locale/ja/PulsarStorm.md, docs/locale/ja/README.md, managed-ledger/pom.xml, pom.xml, pulsar-broker-auth-athenz/pom.xml, pulsar-broker-common/pom.xml, pulsar-broker/pom.xml, pulsar-checksum/pom.xml, pulsar-client-admin/pom.xml, pulsar-client-auth-athenz/pom.xml, pulsar-client-tools/pom.xml, pulsar-client/pom.xml, pulsar-common/pom.xml, pulsar-discovery-service/pom.xml, pulsar-spark/pom.xml, pulsar-storm/pom.xml, pulsar-testclient/pom.xml, pulsar-websocket/pom.xml, pulsar-zookeeper-utils/pom.xml, pulsar-zookeeper/pom.xml
Updated maven groupId from `com.yahoo.pulsar` to `org.apache.pulsar`
=> Updated maven groupId from com.yahoo.pulsar to org.apache.pulsar

pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleLoadManagerImplTest.java, pulsar-client-cpp/include/pulsar/Client.h, pulsar-client-cpp/lib/ClientConnection.h
Cleaning up old yahoo-service url in test and comments.
No functional change.
=> cleanup yahoo test-url

.travis.yml, managed-ledger/src/test/resources/log4j.properties, pom.xml, pulsar-broker-auth-athenz/src/test/resources/athenz.conf, pulsar-broker/src/main/resources/pulsar-broker-version.properties, pulsar-broker/src/test/resources/configurations/pulsar_broker_test.conf, pulsar-broker/src/test/resources/log4j.properties, pulsar-broker/src/test/resources/logback.xml, pulsar-checksum/src/main/java/com/scurrilous/circe/crc/package-info.java, pulsar-checksum/src/main/java/com/scurrilous/circe/impl/DirectByteBufferAccess.java, pulsar-checksum/src/main/java/com/scurrilous/circe/impl/package-info.java, pulsar-checksum/src/main/java/com/scurrilous/circe/package-info.java, pulsar-checksum/src/main/java/com/scurrilous/circe/params/package-info.java, pulsar-client-auth-athenz/src/test/resources/athenz.conf, pulsar-client-cpp/lib/auth/CMakeLists.txt, pulsar-client-cpp/lib/checksum/crc32c_sw.h, pulsar-client-tools/src/test/resources/localtest, pulsar-client/src/main/resources/ahc.properties, pulsar-client/src/main/resources/pulsar-client-version.properties, pulsar-client/src/test/resources/logback-test.xml, pulsar-common/src/test/resources/log4j.properties, pulsar-discovery-service/src/test/resources/log4j.properties, pulsar-websocket/src/test/resources/log4j.properties, pulsar-zookeeper/src/main/resources/META-INF/aop.xml
Added apache-rat to check for license headers and fixed a few missing headers
=> Added apache-rat plugin and fixed some license headers

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/zookeeper/aspectj/ClientCnxnAspect.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/zookeeper/ZooKeeperClientAspectJTest.java
As #568 build couldn't complete intermittently: After enabling debug log, found out that build exists because `ZooKeeperSessionWatcher` couldn't get heartbeat with in zksession timeout.
```
[pulsar-zk-session-watcher-274-1:ZooKeeperSessionWatcher@164] - zoo keeper disconnected, waiting to reconnect, time remaining 0
[pulsar-zk-session-watcher-75235-1:ZooKeeperSessionWatcher@158] - timeout expired for reconnecting, invoking shutdown service
```
After digging into it, it seems issue is not BK-ZkClient library but the processing time of zk-response into aspectj-advice. [ZKClientCnxAspect](https://github.com/apache/incubator-pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/zookeeper/aspectj/ClientCnxnAspect.java#L72) intercept zk-response call and if takes more than few …
=> Fix: register zk-stats listener after broker service started

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/MockBrokerService.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/util/netty/EventLoopUtil.java, pulsar-discovery-service/src/main/java/org/apache/pulsar/discovery/service/DiscoveryService.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationClient.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
In many places throughout the code base we are checking if the OS is Linux to enable the Netty Epoll based socket handling.
Grouped the instantation of the `EventLoopGroup` into one single util class.
Better organized code.
=> Simplified the instantiation of Netty EventLoopGroup

.travis.yml, docker/build.sh, docker/get-version.sh, docker/publish.sh
Build the docker images during the CI build and push them to DockerHub when a final tag is created.
=> Build and publish docker images

README.md, pom.xml
Fixed broken links on top-level README file
=> Updated README by removing broken links and adding instruction on how to build

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedConsumerImpl.java
Right now, if application is using `receiveAsync` api and waiting for the result-future, and if consumer gets closed then client-consumer is not clearing up pending-receive queue and application might be waiting on these futures.
Clear up pending-receive queue and fail all the futures in that queue so, application gets notification on that futures.
Application will be notified for the receive-async future in case consumer gets closed.
=> clear up pendingReceive queue when consumer close

src/sign-release.sh
Added tools to create signatures and checksum during the release process.
Instructions on how to use it, will be added on the Release process wiki page.
=> Added script to sign release artifacts

site/_includes/explanations/partitioned-topic-admin.md, site/_includes/navbar.html, site/_plugins/custom_tags.rb, site/contact.md, site/docs/latest/admin/AdminInterface.md
Due to a previous conflict merge, the team links were duplicated.
=> Removed duplicated links

.travis.yml, .travis/settings.xml, pom.xml
Added configuration to publish on ASF Nexus Maven repository for both snapshot and releases.
=> Maven artifacts relases into Apache

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
if consumer acks batch-messages concurrently, then client-consumer is not acking the message to broker even if consumer acks all batch-Index-msg with in that batch-message. `BitSet` which tracks unack-batch-message is not thread-safe and it accessed by multiple thread while acking and therefore, it fails to conclude that all messages have been acked.
make access of `unack-BitSet` thread-safe.
batch-msg ack will be thread-safe.
=> make batch-ack thread-safe

site/_includes/explanations/install-package.md
The installation currently lack instructions on compiling from source.
=> Add instructions on compiling from source

site/docs/latest/advanced/RetentionExpiry.md
This PR addresses issue #655.
Misleading explanations and code samples have been removed.
=> Issue #655: fix misleading info on retention policies

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java
When a retention policy is set, an "inactive" topic should not be garbage collected until the retention period has expired.
Even if there are no subscriptions or active producers/consumers, the data that was published on the topic should be retained for the configured time.
Check for the retention policy config during GC cycle.
=> Do not delete inactive topics if they have retention policy

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
not support tls connection in performance test.
support tls connection in performance test.
we can conduct performance test with tls connection.
=> support tls in performance tool

site/_data/features.yaml, site/_includes/explanations/partitioned-topic-admin.md, site/_includes/explanations/partitioned-topics.md, site/docs/latest/admin-api/partitioned-topics.md, site/docs/latest/admin-api/properties.md, site/docs/latest/advanced/PartitionedTopics.md, site/docs/latest/advanced/RetentionExpiry.md, site/docs/latest/clients/Java.md, site/docs/latest/deployment/InstanceSetup.md, site/docs/latest/getting-started/Clients.md
Fixed broken links in website documentation.
=> Fixed broken links to admin-api/overview

pulsar-client-cpp/python/setup.py
Small fix to the scripts that obtain the version to be compliant with PyPI.
=> Fix Python package version

site/_data/sidebar.yaml, site/docs/latest/getting-started/docker.md
Add a tutorial page to show how you can start a Pulsar standalone service in Docker without downloading anything.
=> Added documentation on how to start the standalone service with Docker

managed-ledger/pom.xml, pom.xml, pulsar-broker/pom.xml, pulsar-checksum/src/main/assembly/assembly.xml, pulsar-zookeeper-utils/pom.xml
Removed unnecessary maven plugin configs that were generating build warnings.
=> Fixed Maven test jars warnings

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryCacheImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/test/ZooKeeperUtil.java, managed-ledger/src/test/java/org/apache/zookeeper/MockZooKeeper.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/MockServletContext.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/BookieClientsStatsGeneratorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/discovery/service/web/DiscoveryServiceWebTest.java, pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTest.java, pulsar-discovery-service/src/test/java/org/apache/pulsar/discovery/service/web/DiscoveryServiceWebTest.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/stats/JvmMetrics.java
Removed some of the warning printed during the build.
=> Refactored usages of deprecated classes

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-discovery-service/src/test/java/org/apache/pulsar/discovery/service/web/ZookeeperCacheLoaderTest.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketService.java
`WebSocketService` doesn't depend on `jcommander` and it should not depend `jcommander->Lists` so, replaced `jcommander->Lists` with `Guava->Lists`.
=> fix list collection import

site/_includes/explanations/partitioned-topics.md, site/docs/latest/admin-api/brokers.md, site/docs/latest/admin/GeoReplication.md, site/docs/latest/getting-started/Clients.md, site/docs/latest/getting-started/ConceptsAndArchitecture.md
Fix broken link mentioned at #692 and #691 .
=> Fix broker links due to invalid package

kubernetes/README.md, site/docs/latest/deployment/Kubernetes.md
Fix broken links: downloads link in Kubernetes.md and link in kubernetes/README
This is for issue #702 
Update the link to new place
links will work.
=> Fix broken links: downloads link in Kubernetes.md and link in kubernetes/README

site/docs/latest/clients/Python.md, site/docs/latest/clients/WebSocket.md, site/docs/latest/deployment/InstanceSetup.md
Fix broken link mentioned at #696 , #697, #698, #699
=> Fix broker links for deployment, client

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/Namespaces.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/MessageDispatchThrottlingTest.java
After moving dispatch-rate policy from local-zk to global-zk, it was not supporting configuration of dispatch-rate for global-namespace. 
Right now, `set-dispatch-rate` api sets dispatch-rate for a given namespace, but for global-namespace, it should be able to configure rate for specific repl-cluster.
When any broker receives `set-dispatch-rate` request for a global-namespace, it sets dispatch-rate for that current cluster so, it's possible to configure dispatch-rate for every cluster.
we will be able to set-dispatch-rate for global namespace.
=> Add support of dispatch rate-limiting for global namespace

site/docs/latest/clients/WebSocket.md
=> Fix NodeJS code sample

site/docs/latest/clients/WebSocket.md
No description about websocket reader endpoint in WebSocket.md.
Added the description to WebSocket.md.
We can read description about websocket reader endpoint.
fixed https://github.com/apache/incubator-pulsar/issues/738
=> Added reader endpoint description to WebSocket.md

site/presentations.md
Added 3 links to blog posts on Pulsar.
=> Added links to blog posts

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
With release 1.20 by default, broker will start persisting ack-msg range into managed-cursor and ledger. However, broker should only persist ack-msg range into ZK while closing cursor and broker should clear it in ZK as soon as it recovers cursor. Therefore, broker should not persist ack-msg range while switching-ledger also.
Do not store ack-msg range into ZK while switching/creating a new ledger.
Broker will not store msg-ack range into zk after recovering cursor.
=> Avoid storing ack-msg range while switching-ledger

pom.xml
BK changes:
* Issue #372: Allow to configure advertised address in bookies
* Fix DoubleByteBuf readableBytes()
=> Updated bookkeper version to 4.3.1.72

pulsar-client-cpp/run-unit-tests.sh
Run Python unit tests along with C++ tests during build and PRs validation.
=> Execute Python client lib unit tests during build

pulsar-client-cpp/lib/HTTPLookupService.cc, pulsar-client-cpp/lib/HTTPLookupService.h
Added correct CPP Client version value to user agent in order to get this information in User agent field in web_access log.
=> CPP Client: Added client version to User Agent in HTTP Lookup

all/licenses/LICENSE-bouncycastle.txt, all/src/assemble/LICENSE.bin.txt
=> Added Bouncy Castle Licence files

site/docs/latest/clients/Java.md
=> Fixed Java client documents related to Athenz

site/_includes/explanations/install-package.md, site/_includes/explanations/service-discovery-setup.md, site/docs/latest/deployment/Kubernetes.md, site/docs/latest/deployment/Monitoring.md
We discovered some errors in documents and fix them.
=> Fixed some documents

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DispatcherBlockConsumerTest.java
As mentioned at ##786 : Fix intermittent test
```
Error Message
expected [600] but found [365]
Stacktrace
java.lang.AssertionError: expected [600] but found [365]
at org.apache.pulsar.client.api.DispatcherBlockConsumerTest.testBlockBrokerDispatching(DispatcherBlockConsumerTest.java:849)
```
=> fix intermittent testBlockBrokerDispatching consume msg async

site/_data/config/bookkeeper.yaml
bokkeeper -> bookkeeper
This typo prevents bookie start-up
Fixed a typo
Bookies should start-up without issue
=> Fix typo in bookkeeper.yaml

all/src/assemble/README.bin.txt
Created the distribution notice as mentioned in https://www.apache.org/dev/crypto.html#inform
=> Added Crypto notice into README

site/_data/sidebar.yaml, site/docs/latest/adaptors/KafkaWrapper.md
Added documentation for the Kafka compatible wrapper on top of Pulsar client API introduced in #761
=> Documentation for Kafka/Pulsar client wrapper

README.md
Our source distribution should also have the crypto notice.
=> Added Crypto notice to src distribution README

all/pom.xml, managed-ledger/pom.xml, pom.xml, pulsar-broker-auth-athenz/pom.xml, pulsar-broker-common/pom.xml, pulsar-broker/pom.xml, pulsar-checksum/pom.xml, pulsar-client-admin/pom.xml, pulsar-client-auth-athenz/pom.xml, pulsar-client-kafka-compat/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka-tests/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka/pom.xml, pulsar-client-tools/pom.xml, pulsar-client/pom.xml, pulsar-common/pom.xml, pulsar-discovery-service/pom.xml, pulsar-proxy/pom.xml, pulsar-spark/pom.xml, pulsar-storm/pom.xml, pulsar-testclient/pom.xml, pulsar-websocket/pom.xml, pulsar-zookeeper-utils/pom.xml, pulsar-zookeeper/pom.xml
@joefk 
Bumped version to 1.21.0-incubating-SNAPSHOT
=> Bumped version to 1.21.0-incubating-SNAPSHOT

pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenz.java
Users can't use `:` or `,` in authParams.
Support json format in athenz plugin's authParams.
Users can use `:` or `,` in authParams, but must change current format(separated by `:` and `,`) to json format.
We think that this change is little impact on users since few users use athenz plugin yet.
=> Support json format in AuthenticationAthenz's authParams

site/docs/latest/project/BinaryProtocol.md
=> Documentation: Added a few more commands to BinaryProtocol.md

pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenz.java
Like #661, added role header property for Athenz Plugin.
=> Add athenz role header property

pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ProducerHandler.java
- client can't pass `CustomPartition` as `MessageRoutingMode` while creating producer in websocket.
- Right now, if client passes invalid enum-configuration while creating producer/consumer then it receives 500 error code, rather client should get bad-request error-code and correct error msg.
- Fix enum-validation with correct error-code and error-msg
- also ignore  routing-mode if client passes it as `CustomPartition`.
=> Validate messageRoutingMode and config-enum values in websocket

site/docs/latest/clients/WebSocket.md
Add query-param info in websocket readme.
=> add query-param for websocket-readme

site/docs/latest/clients/WebSocket.md, site/ja/clients/WebSocket.md
The sample code doesn't work by missing parenthesises.
=> Fix missing parenthesises in WebSocket sample code

pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/LocalBookkeeperEnsemble.java
Currently, the bookie embedded in the Pulsar standalone is binding on the IP address associated with the machine hostname.
When running the Pulsar standalone on a laptop, the IP might change frequently and that will cause the bookie to refuse starting for IP mismatch. 
We should make sure the bookie is using `127.0.0.1` to avoid the mismatch once the machine IP changes. At the same time, we should ensure that this won't break for existing users of the standalone service.
=> Use 127.0.0.1 in standalone and clean the cookie in case of conflicts

pulsar-broker/src/test/java/org/apache/pulsar/client/api/TopicReaderTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/api/ReaderConfiguration.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderImpl.java
Currently, reader can't read encrypted message.
End-to-end encryption support in reader.
Reader can decrypt and read encryped message.
=> End-to-end encryption support in Reader

conf/broker.conf, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java, pulsar-client-cpp/tests/BasicEndToEndTest.cc, site/_data/config/broker.yaml, site/docs/latest/advanced/Encryption.md, site/docs/latest/clients/Java.md
* Fixed typo 
* Fixed overlapping `key rotation` item on [right sidebar](https://pulsar.incubator.apache.org/docs/latest/advanced/Encryption/)
=> Fixed typo

pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ReaderHandler.java
This is the same issue as https://github.com/apache/incubator-pulsar/pull/875
=> Fix ReaderHandler in WebSocket Proxy

pulsar-discovery-service/src/main/java/org/apache/pulsar/discovery/service/DiscoveryService.java, pulsar-discovery-service/src/main/java/org/apache/pulsar/discovery/service/server/DiscoveryServiceStarter.java
Fix discovery service logs that confuses with broker service.
No functional change.
=> Fix: discovery service logs

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BacklogQuotaManager.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
There are some redundant codes related to checking `null`.
Refactor some codes to use `Optional<T>` to check null.
Behaviors  won't change.
=> Use Optional to check null gracefully

conf/bookkeeper.conf, pom.xml
Upgrade to bk-4.3.1.83-yahoo to expose journalSyncData option
=> Upgrade to bk-4.3.1.83-yahoo to expose journalSyncData option

all/pom.xml, managed-ledger/pom.xml, pom.xml, pulsar-broker-auth-athenz/pom.xml, pulsar-broker-common/pom.xml, pulsar-broker-shaded/pom.xml, pulsar-broker/pom.xml, pulsar-checksum/pom.xml, pulsar-client-admin/pom.xml, pulsar-client-auth-athenz/pom.xml, pulsar-client-kafka-compat/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka-tests/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka/pom.xml, pulsar-client-shaded/pom.xml, pulsar-client-tools/pom.xml, pulsar-client/pom.xml, pulsar-common/pom.xml, pulsar-discovery-service/pom.xml, pulsar-proxy/pom.xml, pulsar-spark/pom.xml, pulsar-storm/pom.xml, pulsar-testclient/pom.xml, pulsar-websocket/pom.xml, pulsar-zookeeper-utils/pom.xml, pulsar-zookeeper/pom.xml
Bump up version to 1.22.0-incubating-SNAPSHOT
=> Bumped version to 1.22.0-incubating-SNAPSHOT

all/src/assemble/NOTICE.bin.txt, all/src/assemble/bin.xml
Apply requested changes from ASF incubator list  https://lists.apache.org/thread.html/bcaa7b2547ec72d2457c9516ae4fee8bb27429be17a4e0db77b013df@%3Cgeneral.incubator.apache.org%3E
=> Fixed NOTICE file for binary distribtution

all/src/assemble/src.xml, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/proto/PendingBookieOpsStats.java, pom.xml
Get rid of unused Apache RAT exclusions as commented on incubator mailing list vote for previous release.
=> Fixed Apache RAT exclusions

all/src/assemble/src.xml
Include Kubernetes deployment files in src package
Fixes #935
=> Issue #935: Included Kubernetes deployment files in src package

site/docs/latest/adaptors/KafkaWrapper.md
The current documentation wrt Kafka compatibility matrix as well as maven dep are incorrect. This pr fixes the docs.
This pr only touches the documentation to bring it up to date.
=> Correct the Kafka Wrapper Functionality matrix as well as maven dep

kubernetes/generic/broker.yaml, kubernetes/generic/monitoring.yaml, kubernetes/google-container-engine/broker.yaml, kubernetes/google-container-engine/monitoring.yaml
some files under dir k8s has some typos
1, fix some typos
2, fix containerPort of grafana
typos fixed
=> Fix some typos under k8s dir

site/_sass/_docs.scss
=> Fix image width issue

site/docs/latest/deployment/cluster.md
Removing mentions to GlobalZK and port 2184 on single cluster deployment docs.
cc/ @lucperkins
=> Adjusted documentation for single cluster deployment to remove need of global ZK

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java
Removed unused code since the client version filter was removed some time back.
=> Removed unused client version filter method in WebService

managed-ledger/src/test/java/org/apache/zookeeper/MockZooKeeper.java
This patch adds support for watching for non-existent znode
using ZooKeeper#exists.
=> MockZooKeeper watches for non-existing znode

site/_config.yml
Updated `site/_config.yml` for 1.21.0-incubating according to the following guide:
https://github.com/apache/incubator-pulsar/wiki/Release-process#11-update-the-site
=> Update site/_config.yml for 1.21.0-incubating

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerBase.java
To improve logs that format references to producers and consumers.
=> Implement toString in ProducerBase and ConsumerBase

pom.xml
As described at #989 , fixed bk-client and upgrading bk-version to ` 4.3.1.84-yahoo`.
=> Upgrade bk version to 4.3.1.84-yahoo with ledger-creation fix

site/docs/latest/clients/Python.md
Addresses issue #994.
Correctly lists supported Python versions by platform.
=> Add table listing supported Python versions

pulsar-storm/src/main/java/org/apache/pulsar/storm/PulsarSpout.java
Right now, PulsarSpout consumes messages  from the queue, converts into Tuple and emits to the topology. However, if the converted tuple is null then PulsarSpout doesn't emit the tuple when `nextTuple()` is triggered in the topology. It seems if `nextTuple()` doesn't emit the tuple then [Storm-spout](https://github.com/apache/storm/blob/master/storm-client/src/jvm/org/apache/storm/trident/spout/RichSpoutBatchExecutor.java#L108) doesn't batch the tuples and it creates penalty for PulsarSpout. 
Recently, we have seen that one of the  client-app that uses `PulsarSpout` returns null for for most of the messages while converting pulsar-message to tuple (`getMessageToValuesMapper()`) to throw away pulsar-messages. Because of this behavior `nextTuple()` doesn't emit messages for most of the …
=> Make sure nextTuple emits tuple with non-null values

site/_sass/_docs.scss, site/docs/latest/advanced/Encryption.md, site/docs/latest/deployment/dcos.md
The DC/OS doc has a lot of great info but needed some quick edits from a native speaker. Thanks to @zhaijack for a great doc!
=> Edits to DC/OS doc

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest2.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerBkEnsemblesTests.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceThrottlingTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java
Keep strategically-retry logic common for tests.
=> Keep strategically-retry logic common for tests

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Right now, if encryption is enabled then each producer creates one `ScheduledExecutorService` which creates large number of `Executor` if one client creates large number of producers in the process. It can be avoided by reusing one executor across all the producers.
Reuse PulsarClient executor in all producers to schedule key-generation task.
It will avoid creating multiple executors across all producers.
=> Avoid creating new executor per producer for encryption-key generation

pulsar-common/src/main/java/org/apache/pulsar/common/util/netty/EventLoopUtil.java
This reverts commit efd41890281c0df98557e60f7094ec9263f3880d.
Reverting this to fix test failures on MacOS
=> Revert "Enable usage of KQueue in MacOS (#1036)"

pulsar-broker/src/main/java/org/apache/pulsar/client/api/RawMessage.java, pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawMessageImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawMessageSerDeserTest.java
Serializes the message ID and passes through the payload and metadata
of the raw message.
=> Serialization and Deserialization for RawMessage

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/web/WebServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java, pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenz.java, pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationDataAthenz.java, pulsar-client/src/main/java/org/apache/pulsar/client/api/Authentication.java, pulsar-client/src/main/java/org/apache/pulsar/client/api/AuthenticationFactory.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpClient.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationTls.java, pulsar-common/src/main/java/org/apache/pulsar/common/stats/Metrics.java, pulsar-discovery-service/src/test/java/org/apache/pulsar/discovery/service/BaseDiscoveryTestSetup.java, pulsar-discovery-service/src/test/java/org/apache/pulsar/discovery/service/web/BaseZKStarterTest.java, pulsar-zookeeper-utils/src/test/java/org/apache/pulsar/zookeeper/ZookeeperCacheTest.java
Refactor the usage of several deprecated methods
=> Fixed some of the warnings in Maven build

pom.xml
Upgrade [BK version: 4.3.1.85-yahoo ](https://github.com/yahoo/bookkeeper/commit/c87c887a61dba2d1aa8cb17f6779a017fa2d1a88) to pickup fix for [BK-DoubleByte](https://github.com/yahoo/bookkeeper/pull/16)
=> Upgrade BK version: 4.3.1.85-yahoo with Double bytebuf fix

all/src/assemble/src.xml
@merlimat Should the entire `deployment` directory be included?
=> Fix source distribution XML config to reflect new directory structure

site/docs/latest/clients/Java.md, site/docs/latest/clients/Python.md, site/docs/latest/getting-started/ConceptsAndArchitecture.md
@merlimat There's more that needs to be done here but this seems like a good start. Ready for review.
=> Reader interface documentation

pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/DestinationLookup.java
When unloading a topic or a namespace (eg: during graceful shutdown), the producer/consumer are disconnected and subsequent lookup are being rejected until the unload is completed. 
During that time there can be a bunch of exception reported : 
```
2018-01-26 14:25:08,628 - WARN  - [pulsar-io-55-11:DestinationLookup@285] - Failed to lookup null for topic persistent://sample/standalone/ns1/tx-partition-4005 with error java.lang.IllegalStateException: Namespace bundle sample/standalone/ns1/0x40000000_0x80000000 is being unloaded
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Namespace bundle sample/standalone/ns1/0x40000000_0x80000000 is being unloaded
at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
at …
```
=> Remove stack traces from topic lookup errors during unloads

pom.xml, pulsar-broker/pom.xml, pulsar-client-admin-shaded/pom.xml, pulsar-client-admin/pom.xml, pulsar-client-tools/pom.xml, pulsar-testclient/pom.xml
Fixes #1091 
Publish shaded jar for `pulsar-client-admin` to avoid conflicts with other dependencies.
=> Publish pulsar-client-admin as a shaded artifact

pulsar-client-cpp/include/pulsar/Result.h, pulsar-client-cpp/lib/ClientConnection.cc, pulsar-client-cpp/lib/Commands.cc, pulsar-client-cpp/lib/Result.cc
Fix warnings for missing enum values in switch statements
=> Added missing C++ enum values

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest2.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/IncrementPartitionsTest.java
Fixes #1143 
Refactored the increase-partition REST handler to make use of the create-subscription operation to simplify the logic and make the operation more robust.
=> Fix increase partitions

buildtools/pom.xml, buildtools/src/main/java/org/apache/pulsar/tests/AnnotationListener.java, buildtools/src/main/java/org/apache/pulsar/tests/RetryAnalyzer.java, managed-ledger/pom.xml, managed-ledger/src/test/java/org/apache/bookkeeper/test/PortManager.java, pom.xml, pulsar-broker/pom.xml, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java, pulsar-discovery-service/pom.xml
Due to many test intermittently failing on Jenkins build, introduce a 1 time retry for failing test before the build is marked as failed.
=> Introduce retries for flaky tests

site/docs/latest/advanced/RetentionExpiry.md
Tried to simplify here a couple of statements on Retention and added references to infinite retention time as defined in #1135.
=> Some clarifications on Retention documentation

pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ProducerHandler.java, site/docs/latest/clients/WebSocket.md
We are missing to expose some config options for producer/consumer in the WebSocket API.
=> Added some missing configs on websocket producer/consumer

pulsar-client-cpp/lib/MessageCrypto.cc, pulsar-client/src/main/java/org/apache/pulsar/client/api/ProducerConfiguration.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageCrypto.java
Minor fix & cleanup to MessageCrypto in Java and C++ client.
=> Update logCtx passed to MessageCrypto, removed unused variable

conf/standalone.conf
Remove incorrect value of the auth-provider.
=> Fix: invalid authprovider value from config

site/docs/latest/project/BinaryProtocol.md
Update a phrase on the website documentation to read better.
```diff
- The TCP connection is not being affected.
+ The TCP connection is not affected.
```
=> Update website documentation verbiage

all/pom.xml, buildtools/pom.xml, managed-ledger/pom.xml, pom.xml, pulsar-broker-auth-athenz/pom.xml, pulsar-broker-common/pom.xml, pulsar-broker-shaded/pom.xml, pulsar-broker/pom.xml, pulsar-checksum/pom.xml, pulsar-client-admin-shaded/pom.xml, pulsar-client-admin/pom.xml, pulsar-client-auth-athenz/pom.xml, pulsar-client-kafka-compat/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka-tests/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka/pom.xml, pulsar-client-shaded/pom.xml, pulsar-client-tools/pom.xml, pulsar-client/pom.xml, pulsar-common/pom.xml, pulsar-discovery-service/pom.xml, pulsar-proxy/pom.xml, pulsar-spark/pom.xml, pulsar-storm/pom.xml, pulsar-testclient/pom.xml, pulsar-websocket/pom.xml, pulsar-zookeeper-utils/pom.xml, pulsar-zookeeper/pom.xml
Move development version to 2.0.0-incubating-SNAPSHOT
=> Bumped master to 2.0.0-incubating-SNAPSHOT

pulsar-client-cpp/lib/MessageCrypto.cc, pulsar-client-cpp/lib/MessageCrypto.h
Added additional logging to help debugging.
=> Added debug logs in MessageCrypto

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarStats.java
Right now, broker-stats gives persistent/non-persistent topic-stats under the `persistent` topic section. We need them in separate section to manage them operationally.
Add non-persistent topic under separate section.
Broker-stats will show non-persistent topic in separate section.
```
{
"sample/standalone/ns2": {
"0x00000000_0xffffffff": {
"persistent": {
"persistent://sample/standalone/ns2/tp3": {
"publishers": [],
"replication": {},
"subscriptions": {},
"producerCount": 0,
"averageMsgSize": 0.0,
"msgRateIn": 0.0,
"msgRateOut": 0.0,
"msgThroughputIn": 0.0,
"msgThroughputOut": 0.0,
"storageSize": 0,
"pendingAddEntriesCount": 0
}
},
"non-persistent": {
"non-persistent://sample/standalone/ns2/t2": {
"publishers": [],
"replication": {},
"subscriptions": {},
"producerCount": 0, …
```
=> Add non-persistent topic stats separately in brokers-stat

pulsar-common/src/main/java/org/apache/pulsar/common/util/SecurityUtility.java
- Duplicate code is evil
- There is a resouse leak
- Split context setup process into several steps so they can be reuse
- Reuse the steps
- Fix the resource leak
- No duplicate code
- No resource leak (hopefully)
=> Refactor SecurityUtility class

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
If a handler is making an asynchronous call it should not use the Commands, since commands are recycled on handler completion.
=> Fix in ServerCnx to prevent using recycled commands

bin/pulsar, pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactorTool.java
CLI tool to run compaction on a topic. This can only be run by the
administrator. It runs with the same configuration as the broker.
=> Compaction CLI tool

bin/pulsar-perf, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/ManagedLedgerWriter.java
Added tool to do performance tests directly on BookKeeper, using the ManagedLedger API.
=> Added ManagedLedger perf tool

pom.xml, pulsar-client-tools-shaded/pom.xml
Provide a pulsar-client-tools shaded module. This will be used by pulsar-functions.
=> Add a shaded module for pulsar-client-tools

site/_data/cli/pulsar-admin.yaml, site/_data/cli/pulsar.yaml
The docs for the various Pulsar [CLI tools](http://pulsar.incubator.apache.org/docs/latest/reference/CliTools/) are a bit out of date. This PR brings them up to speed with the current status of those tools.
=> Update CLI documentation (WIP)

pulsar-client-admin/pom.xml, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java
This change is to allow extension for pulsar function CLI, preparing for merging pulsar-functions.
=> Enable multipart feature in pulsar admin and make a few fields protected to allow extension

pulsar-client/src/main/java/org/apache/pulsar/client/impl/Backoff.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/BackoffTest.java
Introduce a mocked clock so we can control time without reaching into the private state of Backoff and adjusting it for our tests.
=> Make BackoffTest deterministic, fixes #1299

site/_includes/footer.html, site/_includes/navbar.html, site/index.html
This includes fixes from some of the issues reported in #1266
=> Updated ASF links on index page.

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImplTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PatternTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationData.java
This is a last sub-task for pip-13, which would auto subscribe new topics, based on regex pattern topics changing subscription.
- add `TopicsChangedListener` to track topics change.
- do auto subscribe/unsubscribe based on topics changes.
- add test cases to verify.
old methods behaviour not changed, 
user could use new method to subscribe to topics based on regex pattern, and do auto subscribe
=> PIP-13-3/3: auto subscribe based on regex pattern topics changing

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java
This change allows pulsar-functions access client configuration in admin tool
=> Make client configuration protected in PulsarAdminTool

pom.xml, pulsar-functions/instance/pom.xml
This removes the temp dependency in `pulsar-functions-instance`
=> Upgrade the bookkeeper storage client dependency to the official bookkeeper version

pulsar-zookeeper-utils/src/test/java/org/apache/pulsar/zookeeper/ZookeeperCacheTest.java
=> Fixed ZK cache test exectutor configuration.

conf/functions_worker.yml, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/SchedulerManager.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java
Also fix issue with SchedulerAssignmentTest that may have been flaky since mockito is not necessarily thread safe
=> adding max retries for assignment write wait

site/_data/resources/presentations.yaml
Added link to latest presentation on Effectively Once semantics
=> Added slides for Effectively-once semantics in Apache Pulsar

pulsar-common/src/main/java/org/apache/pulsar/common/util/protobuf/ByteBufCodedInputStream.java, pulsar-common/src/test/java/org/apache/pulsar/common/util/protobuf/ByteBufCodedInputStreamTest.java
Simply wrong
Throw the exception
The exception will be escalated correctly
=> Fix CID 262329

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Function.java, pulsar-functions/api-java/src/test/java/org/apache/pulsar/functions/api/utils/DefaultSerDeTest.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstance.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceRunnableProcessTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceRunnableTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceTest.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/CounterFunction.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/ExclamationFunction.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/LoggingFunction.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/PublishFunction.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/UserConfigFunction.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/UserMetricFunction.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/VoidFunction.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2ResourceTest.java, site/docs/latest/functions/api.md
This is not just simpler, but also matches the python interface
=> Renamed PulsarFunction to plain Function

pulsar-client/src/main/java/org/apache/pulsar/client/api/Reader.java
=> Fix Reader.readNext() java docs

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BrokerStatsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BrokersImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ClustersImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NonPersistentTopicsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PersistentTopicsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PropertiesImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ResourceQuotasImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/admin/PulsarAdminWithFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java
Prepare the admin client so it can support the v2 admin rest endpoints.
=> Prepare admin client to support v2 api.

pom.xml
Upgrade DataSketches version to 0.8.3.
=> Update to newer version of datasketches

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/ManagedLedgerWriter.java
* Added configurable digest type
* Use multiple threads to write to BK
=> Improved ManagedLedgerWriter to use multiple threads and configurable digest type

pulsar-client-cpp/python/pulsar.py, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstance.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/main/python/python_instance.py, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceRunnableProcessTest.java
Attach information about which input topic/msgid triggered the function computation in any output
=> Correlate Output of function with input

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PersistentTopicsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/WebTargets.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/NamespaceName.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java
Add V2 support to the pulsar admin client for persistent topics.
=> Add V2 compatibility for pulsar admin persistent topics.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/admin/Functions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-functions/instance/src/main/python/python_instance.py, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2Resource.java
Users can trigger running function by sending a message to the input topic.
=> Added trigger Function capability

site/_includes/calendar.html, site/_includes/navbar.html, site/events/current-event.md
#1266
- Added a page for current events
- Created a shared calendar on Google Calender (not a part of this PR)
- Be able to advertise events on our website
- Pass Apache Podling Website Checks for Event page
=> Add a page for events

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/AbstractWebSocketHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ConsumerHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ProducerHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ReaderHandler.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketConsumerServlet.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketProducerServlet.java, pulsar-websocket/src/main/java/org/apache/pulsar/websocket/WebSocketReaderServlet.java
Add v2 support for websockets.
=> Add v2 support to the websockets endpoints.

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/ManagedLedgerWriter.java
The fixed count of messages was not divided across the configured writing threads.
=> Fixed count of messages per thread in managed ledger writer

pulsar-client-cpp/lib/BatchAcknowledgementTracker.cc
Recent commit merged broke the formatting.
=> Fixed C++ formatting

.test-infra/jenkins/common_job_properties.groovy, .test-infra/jenkins/job_pulsar_precommit_cpp.groovy, .test-infra/jenkins/job_pulsar_precommit_integrationtests.groovy, .test-infra/jenkins/job_pulsar_precommit_java8.groovy, .test-infra/jenkins/job_seed.groovy
Added Jenkins DSL definitions for new PR validation jobs.
This will create one job for Java8 tests and one for C++/Python which will be running in parallel.
=> Added Groovy DSL definition for C++/Java PR builds

pulsar-spark/src/test/java/org/apache/pulsar/spark/SparkStreamingPulsarReceiverTest.java
Extending current `SparkStreamingPulsarReceiver` UT coverage 
- Default Settings
- Negative cases (if `ClientConfiguration` or `ConsumerConfiguration` are not set) 
Adding 3 new UT cases to `SparkStreamingPulsarReceiverTest`
Current UT coverage will have been extended.
=> [Spark_Streaming] Extend Receiver UT Coverage

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PropertiesImpl.java
Update the admin client properties to use the new v2 endpoints.
=> Convert admin client properties to use v2 endpoints.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokerStatsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/BrokerStats.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/BrokerStats.java
Make broker stats rest endpoints work with v2 formats.
=> Fix broker stats to work with v2 namespace format.

conf/proxy.conf, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyConnectionThrottlingTest.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyLookupThrottlingTest.java, pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyThrottlingTest.java
Add Throttling in Pulsar Proxy based on inbound connections and number of lookups
=> Added Throttling mechanism to Pulsar Proxy

pulsar-broker/src/test/java/org/apache/pulsar/stats/client/PulsarBrokerStatsClientTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BrokerStatsImpl.java
Add v2 support to the admin client for broker stats.
=> Add v2 support for broker stats in the admin client.

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BrokersImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ClustersImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ResourceQuotasImpl.java
Add v2 support for clusters, brokers and resources quotas in the admin client.
=> Add admin v2 support for clusters, brokers, and resources quotas.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Fix delete topic for v2 format topics. This patch:
- Adds a isReplicated() method to topics
- Adds a isReplicated check before deleting a topic
=> Fix topic deletion for V2 topics.

site/scripts/python-doc-gen.sh
This PR fixes recent website build errors related to the `pdoc` script.
=> Fix Python docs generation script

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
No sweeping changes here, just providing a bit more specificity in the CLI help output for Pulsar Functions
=> Update pulsar-admin functions help language

pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/utils/DefaultSerDe.java, pulsar-functions/api-java/src/test/java/org/apache/pulsar/functions/api/utils/DefaultSerDeTest.java
Right now, Boolean type is missing under DefaultSerDe.
Add Boolean type in DefaultSerDe.
=> add Boolean type in DefaultSerDe

pom.xml, pulsar-common/src/main/java/org/apache/pulsar/common/util/KeyValue.java, pulsar-connect/cassandra/pom.xml, pulsar-connect/cassandra/src/main/java/org/apache/pulsar/connect/cassandra/CassandraSink.java, pulsar-connect/cassandra/src/main/java/org/apache/pulsar/connect/cassandra/CassandraSinkConfig.java, pulsar-connect/pom.xml
Using the Pulsar Connect Sink interface, implemented a simple cassandra sink
=> Implement Cassandra Sink

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
In #1539 there was an attempt to fix the `ManagedCursorTest.cursorPersistenceAsyncMarkDeleteSameThread()` test. One queue add operation was missed to be converted.
=> Fix for cursorPersistenceAsyncMarkDeleteSameThread

pom.xml, pulsar-connect/aerospike/pom.xml, pulsar-connect/aerospike/src/main/java/org/apache/pulsar/connect/aerospike/AerospikeSink.java, pulsar-connect/aerospike/src/main/java/org/apache/pulsar/connect/aerospike/AerospikeSinkConfig.java, pulsar-connect/pom.xml
Added Aerospike Sink to the Pulsar Connect framework
=> Added Aerospike Sink

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloader.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/NullLedgerOffloader.java
An interface which can be used for offloading ledgers to longterm
storage.
Master issue #1511
=> LedgerOffloader interface for ManagedLedger

pulsar-functions/instance/src/main/python/log.py, pulsar-functions/instance/src/main/python/python_instance_main.py, pulsar-functions/instance/src/main/python/util.py, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ProcessRuntimeFactory.java, pulsar-functions/runtime/src/main/resources/java_instance_log4j2.yml, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/ProcessRuntimeTest.java
logging locations vary across languages
=> fixing and standardizing logging in functions

tests/integration-tests-utils/src/main/java/org/apache/pulsar/tests/PulsarClusterUtils.java
Utility to allow an integration test to wait for zookeeper to come up
before proceeding.
=> Utility for integration tests to wait for ZK

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/MessageProcessor.java, pulsar-functions/instance/src/main/python/python_instance.py, pulsar-functions/instance/src/main/python/python_instance_main.py, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceMain.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ProcessRuntime.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/ProcessRuntimeTest.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfig.java
=> Honor User specified Subscription Types while running functions

tests/integration-tests-topologies/src/main/resources/cube-definitions/single-cluster-3-bookie-2-broker.yaml, tests/integration/compaction/pom.xml, tests/integration/compaction/src/test/java/org/apache/pulsar/tests/integration/TestCompaction.java, tests/integration/compaction/src/test/resources/arquillian.xml
Integration test to exercise CLI based compaction from end to end.
=> Compaction CLI integration test

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Brokers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Brokers.java
Add a content type to the brokers admin rest api endpoints.
=> Set admin brokers content type.

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java
If you want to run pulsar on a preexisting bookkeeper installation,
there's currently no way to format the metadata.
This patch skips the bookkeeper initialization if /ledgers already
exists, which indicates that it has already been formatted.
=> Don't format bookkeeper if /ledgers exist

pulsar-connect/aerospike/src/main/java/org/apache/pulsar/connect/aerospike/AerospikeSink.java, pulsar-connect/cassandra/src/main/java/org/apache/pulsar/connect/cassandra/CassandraSink.java, pulsar-connect/core/src/main/java/org/apache/pulsar/connect/core/Message.java, pulsar-connect/core/src/main/java/org/apache/pulsar/connect/core/PushSource.java, pulsar-connect/core/src/main/java/org/apache/pulsar/connect/core/Sink.java, pulsar-connect/kafka/src/main/java/org/apache/pulsar/connect/kafka/KafkaSink.java, pulsar-connect/kafka/src/main/java/org/apache/pulsar/connect/kafka/KafkaSource.java, pulsar-connect/rabbitmq/src/main/java/org/apache/pulsar/connect/rabbitmq/RabbitMQSource.java, pulsar-connect/twitter/src/main/java/org/apache/pulsar/connect/twitter/TwitterFireHose.java
Instead of just passing the message data, it might be useful to have other attributes of the message that is being read/written from/to external connectors. To that end, this pr enhances the Pulsar Connect interface by adding a Message class to encapsulate additional information
=> Enhance Pulsar Connect api by attaching more information about the message

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java
Proxy should force close connections immediately when catching exception. Currently, it's not catching exception in Netty pipeline, so the connection will be actually close 1min later for inactivity.
=> Proxy should close connections immediately after exception caught

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java
Yesterday's fix was just setting the cluster up if the namespace was already there. Fixed the logic and also only writes the z-node if there are changes to be made.
=> Fixed initial default namespace setup with current cluster setup

deployment/kubernetes/aws/README.md, deployment/kubernetes/aws/bookkeeper.yaml, deployment/kubernetes/aws/broker.yaml, deployment/kubernetes/aws/zookeeper.yaml
1. Uncomment nodeselector to choose the type of instance to be used
2. Added option to use encrypted volume(provide the kmsKeyId to encrypt)
3. Each bookie instance creates journal and ledger persistent volumes
=> Added config to deploy pulsar in aws using ebs storage

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Functions.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2Resource.java
=> Made upload/download generic so that it doesnt have to be function specific

pulsar-connect/core/src/main/java/org/apache/pulsar/connect/core/Source.java
add pull source connector interface for Pulsar
=> [pulsar-connect] Add pull source

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstance.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/AtLeastOnceProcessor.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/AtMostOnceProcessor.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/EffectivelyOnceProcessor.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/MessageProcessor.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/MessageProcessorBase.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceRunnableProcessTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceTest.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ThreadRuntime.java
To simplify the processing model for functions.
Prepare to be able to support running connectors on pulsar functions
=>  refactoring java instance to use pull model for message ingress

pulsar-connect/core/src/main/java/org/apache/pulsar/connect/core/Message.java
add acknowledge callback interface to Message so that the message can be acknowledged when its have been fully processed
=> adding ack method to Message interface

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/RestException.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BaseResource.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBase.java, tests/integration/cli/src/test/java/org/apache/pulsar/tests/integration/TestCLI.java
due to #1612 , create subscription will fail with `500` when connecting to a broker that doesn't own the topic. we need to have an integration test to ensure CLI commands are run correctly.
add an integration test for `createSubscription`
=> Add a integration test for create subscription CLI command

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentFailoverE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentQueueE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ResendRequestTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/DispatcherBlockConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/stats/client/PulsarBrokerStatsClientTest.java, pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/pulsar/client/kafka/compat/PulsarConsumerKafkaConfig.java, pulsar-client/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
Fixed typo in API method name before it gets released.
=> Fixed typo in ConsumerBuilder acknowledgmentGroupTime option

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
=> Hide namespace cli commands that are no longer relevant

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBase.java
The output was changed for debugging in #1613 
Revert the output back to original output.
Pulsar admin CLI output should work as before.
=> Fix the exception output for admin commands

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
=> Make upload/download hidden since they are really meant for uploading/downloading generic data

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-functions/instance/pom.xml, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/InstanceUtils.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstance.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/PulsarConfig.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/PulsarRecord.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/PulsarSource.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/AtLeastOnceProcessor.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/AtMostOnceProcessor.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/EffectivelyOnceProcessor.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/MessageProcessor.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/processors/MessageProcessorBase.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceTest.java, pulsar-functions/proto/src/main/proto/Function.proto, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceMain.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ProcessRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ThreadRuntime.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/ProcessRuntimeTest.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionDetailsUtils.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/Reflections.java
=> refactoring functions to use source interface

NOTICE
#1337 Updating copyright notice
=> Updated Copyright in NOTICE to 2017-2018

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java
... otherwise it will throw an NPE and return a 500
=> Return 404 if no schema found

pulsar-client-cpp/python/examples/rpc_client.py, pulsar-client-cpp/python/examples/rpc_server.py, pulsar-client-cpp/python/pulsar.py, pulsar-client-cpp/python/test_consumer.py, pulsar-client-cpp/python/test_producer.py, site/docs/latest/clients/Python.md, site/docs/latest/getting-started/docker.md
Updated Python examples and documentation so that they work with both py-2 and py-3
Fixes #1395
=> Updated Python examples to work with py-2 and py-3

pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/api/ReaderBuilder.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderBuilderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ReaderConfigurationData.java
Support reading through a compacted topic with the "Reader" API
Fixes #1610
=> Support read-compacted on Reader

pulsar-client/src/test/java/org/apache/pulsar/client/schemas/DefaultSchemasTest.java
*Motivation*
#1585 introduced default schemas test. it wasn't rebased to latest master. so the PR was merged without problem but fail the build
*Solution*
Fix the test
=> Fix DefaultSchemasTest

build/docker/Dockerfile, site/.gitignore, site/Makefile, site/scripts/protobuf-doc-gen.sh
This PR changes the website build setup to include an easier installation of the `protoc-gen-doc` tool.
=> Protobuf documentation update

build/docker/Dockerfile
I've verified this new setup:
```bash
$ docker build -t pulsar-build build/docker
$ docker run -it pulsar-build go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
$ docker run -it pulsar-build protoc-gen-doc -h
Usage of protoc-gen-doc:
```
=> Fix Golang setup in Dockerfile

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Functions.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2Resource.java
Added the trigger functionality where one does not need to specify input topic. This will work for those functions who only take one input Pulsar Topic.
=> Allow functions to be triggered without specifying topic name

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorGlobalNSTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PersistentTopics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
adding admin-api to delete topic forcefully.
=> Add admin api to delete topic forcefully

pulsar-broker/src/main/java/org/apache/pulsar/broker/cache/LocalZooKeeperCacheService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleFactory.java, pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundles.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java, pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperDataCache.java
=> Issue #1117: handle race in concurrent bundle split 

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java
=> Fixed Lookup redirect logic on Proxy side

pom.xml, pulsar-client-admin-shaded/pom.xml, pulsar-client-shaded/pom.xml
=> Relocate service files for shading `pulsar-client-admin` module (#1370)

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
=> Fix: deadlock while closing non-persistent topic

deployment/terraform-ansible/aws/terraform.tfvars, pom.xml, tests/README.md
Added missing license header in `terraform.tfvars`
=> Added missing license header in terraform.tfvars

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
=> Fix: deadlock while closing non-shared consumer

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java
=> Broker should not start replicator for root partitioned-topic

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, pulsar-common/src/test/java/org/apache/pulsar/common/naming/TopicNameTest.java
=> Changed property to tenant in various helper messages and tests

pulsar-client-admin-shaded-for-functions/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka-shaded/pom.xml, pulsar-client-shaded/pom.xml
Using JSON schema fails because a dependency is missing.
=> Include Jackson modules in shaded jar as well

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java
The current cli interface is createSource/deleteConnector and createSink/deleteConnector. This is a little inconsistent. This pr changes that to createSource/deleteSource and createSink/deleteSink.
=> Seperate cmd line connector interface to explicit source and sink

all/licenses/LICENSE-AspectJ.txt, all/licenses/LICENSE-JSR305.txt, all/licenses/LICENSE-LevelDB.txt, all/licenses/LICENSE-Lombok.txt, all/licenses/LICENSE-Webbit.txt, all/licenses/LICENSE-google-auth-library.txt, all/licenses/LICENSE-jbzip2.txt, all/licenses/LICENSE-jfastlz.txt, all/licenses/LICENSE-libdivsufsort.txt, all/src/assemble/LICENSE.bin.txt, all/src/assemble/NOTICE.bin.txt
Some new dependencies were missing from LICENSE and NOTICE files.
=> Fixed licenses and notice file

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
If source/sink open fails, we need to bubble up that exception right away because otherwise the function will be in zombie state.
=> Throw exception of source/sink

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfig.java
=> Have the ability to provide source/sink config in cmdline for sources/sinks

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
At upload time, we are doing Codec.encode(path). We need to do the same for download as well.
=> Encode the path for download

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceMain.java
=> refactor source and sink classname to be pulsar source and sink when not set

pulsar-broker/src/main/java/org/apache/pulsar/broker/s3offload/S3BackedInputStream.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/s3offload/impl/S3BackedInputStreamImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/s3offload/S3BackedInputStreamTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/s3offload/S3TestBase.java
Reads from S3 in configurable chunks. Interface allows caller to seek
to an arbitrary position.
=> InputStream to read from S3

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/main/python/contextimpl.py, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfig.java
@sijie @srkukarni please review
=> fixing behavior when configs are empty

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/s3offload/OffloadIndexEntry.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/s3offload/S3ManagedLedgerOffloader.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/s3offload/impl/OffloadIndexEntryImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/s3offload/impl/S3BackedReadHandleImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/s3offload/S3ManagedLedgerOffloaderTest.java
Implementation of bookkeeper ReadHandle, which reads from an S3
object.
=> ReadHandle implementation backed by S3

pulsar-client-cpp/CMakeLists.txt
Couple of fixes to improve cmake libraries discovery on MacOS.
=> Fixes in CMakeFiles to automate build on macos

pulsar-broker/src/main/java/org/apache/pulsar/broker/s3offload/S3ManagedLedgerOffloader.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/s3offload/S3ManagedLedgerOffloaderTest.java
impl deleteOffloaded() for S3ManagedLedgerOffloader
Master issue #1511
=> PIP-17: impl deleteOffloaded() for S3ManagedLedgerOffloader

tests/integration-tests-utils/src/main/java/org/apache/pulsar/tests/PulsarClusterUtils.java
This patch provides two utility methods. One of them allows the update
of a key value properties type configuration, such as broker.conf.
The other allows the update of a log4j2.yaml, to add loggers at a certain
level. This is useful for debugging integration tests.
=> Utilities to update configuration for integration tests

pulsar-client-cpp/homebrew/libpulsar.rb
Added recipe to build C++ client library on Mac for Homebrew. 
First step is to include the recipe here. The final goal, once 2.1 is released is to have this recipe on main Homebrew repository.
=> Added Homebrew recipe for C++ client library

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java
Fixed the flaky behavior by ensuring the read operation completes with the expected failure instead of throwing assertion error in background.
=> Resolve the flaky test ReplicatorTest.testCloseReplicatorStartProducer

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaSink.java
=> Check if producer is not null before closing

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaSource.java
This is similar to the similar change that we  did for Sinks to make them usable
=> Make the KakfaSource abstract by allowing users to implement method to extract value

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java
=> If left unspecified, function tenants and namespaces should have the same behavior as topics

site/docs/latest/admin/GeoReplication.md, site/docs/latest/clients/Java.md
This PR fixes a docs issue pointed out on the Pulsar Slack channel
=> Fix message builder examples

site/docs/latest/clients/Java.md
Simplified the examples and fixed a couple of typos.
=> Fixes to new Java API intro docs

pulsar-client-cpp/docker/build-wheel-file-within-docker.sh, pulsar-client-cpp/docker/build-wheels.sh
Small fix for the script used to build Python wheel files inside docker container
=> Fixed script to build all versions Python wheel files

pom.xml
=> Disable verbose on git maven plugin

pulsar-functions/instance/src/main/python/contextimpl.py, pulsar-functions/instance/src/main/python/python_instance.py
User Defined Serde's might behave unexpectedly, so convert the output of serde to bytes before writing to pulsar
=> Make sure that output_bytes are of type bytes

conf/log4j2.yaml
=> Made the logging file names uniform accross threaded and process modes

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSinkConfig.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSource.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSourceConfig.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/sink/PulsarSinkTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/source/PulsarSourceTest.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfig.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/validation/ValidatorImpls.java
To simply using functions, we will not allow users to set the subscription type
=> removing allowing users set subscription type

conf/log4j2.yaml, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
=> Fixed the filename of the log files in threaded mode

pulsar-broker/src/main/java/org/apache/pulsar/broker/s3offload/impl/S3BackedInputStreamImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/s3offload/S3BackedInputStreamTest.java
Previously, any time seek was called, the current buffer was
discarded, and the next time read was called, a request was made to
S3. This was very inefficient if using seek a lot (which we do).
This patch changes that behaviour so that if the position sought is
within the range of the current buffer, we just change the reader
index on the buffer.
=> S3BackedInputStream seeks within current buffer if possible

pulsar-io/kafka/src/main/java/org/apache/pulsar/io/kafka/KafkaSource.java
=> When fetching from kafka, specify to get the earliest of messages

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfig.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SourceConfig.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/Utils.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/validation/ConfigValidationAnnotations.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/validation/ValidatorImpls.java
- clean up function, sink, source code
- improving source and sink validation
- refactor some code to avoid duplication
=>  improving source and sink validation

site/_data/config/broker.yaml
=> Add tiered storage configuration to website reference

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfig.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfig.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SourceConfig.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/Utils.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/validation/ConfigValidationAnnotations.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/validation/ValidatorImpls.java
Some users want to be able to specify the jar/py file from yml file. 
All other configs can be specified from yml file but not jar.  This might be confusing to users.
=> allowing users to specify function jar in yml file

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/utils/CmdUtils.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/Utils.java
=> improving error messages when loading configs

pulsar-client/pom.xml, pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ProtobufSchema.java, pulsar-client/src/test/java/org/apache/pulsar/client/schemas/ProtobufSchemaTest.java
After discussing with @sijie, we decided to not set the schema in SchemaInfo for right now since extracting a schema from protobuf is non-trivial to get right and there seems to be no existing libraries we can leverage.
=>  adding protobuf schema

pulsar-client-cpp/homebrew/libpulsar.rb, pulsar-client-go/pulsar/c_client.go, pulsar-client-go/pulsar/c_go_pulsar.h, pulsar-client-go/pulsar/client.go
Added support for authentication in Pulsar Go client lib.
cc/ @bruth
=> Added authentication support in Go client lib

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Utils.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionActionerTest.java
In #1092 after doing -ve testing of the PR, missed to revert back the change in func-url validation method.
So, fixing func-url validation method.
=> fix func pkgUrl validation

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionActionerTest.java
fix pkg location init while creating function pkg.
=> fix pkg location init

pulsar-io/twitter/src/main/java/org/apache/pulsar/io/twitter/TwitterFireHose.java
We need to ensure that all required parameters are not null.
=> The check should be for null

pulsar-client-cpp/include/pulsar/ConsumerConfiguration.h, pulsar-client-cpp/include/pulsar/ReaderConfiguration.h, pulsar-client-cpp/include/pulsar/c/consumer_configuration.h, pulsar-client-cpp/include/pulsar/c/reader_configuration.h, pulsar-client-cpp/lib/ClientImpl.cc, pulsar-client-cpp/lib/Commands.cc, pulsar-client-cpp/lib/Commands.h, pulsar-client-cpp/lib/ConsumerConfiguration.cc, pulsar-client-cpp/lib/ConsumerConfigurationImpl.h, pulsar-client-cpp/lib/ConsumerImpl.cc, pulsar-client-cpp/lib/ConsumerImpl.h, pulsar-client-cpp/lib/ReaderConfiguration.cc, pulsar-client-cpp/lib/ReaderConfigurationImpl.h, pulsar-client-cpp/lib/ReaderImpl.cc, pulsar-client-cpp/lib/c/c_ConsumerConfiguration.cc, pulsar-client-cpp/lib/c/c_ReaderConfiguration.cc, pulsar-client-cpp/python/pulsar/__init__.py, pulsar-client-cpp/python/pulsar_test.py, pulsar-client-cpp/python/src/config.cc, pulsar-client-cpp/tests/ConsumerConfigurationTest.cc
Add read compacted flag in C++ consumer configuration.
=> Cpp client: add readCompacted in consumer config

site/_data/cli/pulsar-admin.yaml, site/docs/latest/cookbooks/compaction.md, site/docs/latest/getting-started/ConceptsAndArchitecture.md
Updates for reference and cookbook documentation for compaction to
show users how to set up automatic compaction based on a size threshold.
=> Documentation for threshold based compaction

site/_data/sidebar.yaml, site/docs/latest/reference/CustomAuth.md
Added docs with instructions on how to implement customized authentication or authorization providers.
=> Added documentation for authn & authz plugins

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
Managed ledger has a lock, ledgersListMutex, to control write access
to the list of ledgers that form the managed ledger.
Normally this lock is locked in a non-blocking way (if it fails it
backs off and tries again). Offloading added some operations that
locked in a blocking manner, which can cause some deadlocking, if
operations are running on the orderedexecutor.
This patch changes the offloading operations to only use tryLock on
this lock.
=> Remove potential deadlock in offloading

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
=> Typo compaction threshold rest api

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, tests/integration/s3-offload/src/test/java/org/apache/pulsar/tests/integration/TestS3Offload.java
When triggering offload from the CLI, allow the user to specify human
readable sizes, like 10M, 100G etc.
This patch also fixes a bug where the size wasn't being correctly used
to find the message ID to offload at.
=> Human readable sizes when triggering offload

pom.xml, pulsar-client-admin-shaded/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka-shaded/pom.xml, pulsar-client-shaded/pom.xml, pulsar-common/pom.xml, pulsar-functions/proto/pom.xml
Some of the dependencies added in 2.0 were not properly shaded in client packages
=> Fixed shading of pulsar-client and pulsar-client-admin

site/_config.yml
=> Adding version 1.22.1 to archived_releases

site/_data/cli/pulsar-admin.yaml
*Motivation*
Make sure we document schema CLI
*Solution*
Add the section in pulsar-admin for schemas CLI.
The last `compact` section is duplicated so removed it.
=> Add documentation for schema CLI

site/_config.yml, site/release-notes.md
Updating website to with new release
=> Added release notes for 2.0.1-incubating release

site/docs/latest/getting-started/LocalCluster.md, site/docs/latest/getting-started/docker.md
It was previously using deprecated methods.
=> Use builder methods in getting started docs

pulsar-client-cpp/docker/build-wheel-file-within-docker.sh, pulsar-client-cpp/docker/build-wheels.sh, pulsar-client-cpp/python/pulsar/__init__.py, pulsar-client-cpp/python/setup.py
Fixes for building wheel files on linux/docker
=> Fixed python extension build

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarSinkE2ETest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Functions.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2Resource.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2ResourceTest.java
Add admin-api to update function with package-url.
- add rest-admin api
- add tests
**Note:** 
- will rebase and make cli change once #1956 will be merged.
- User can update function with url where package is uploaded.
=> add admin-api to update function with url

all/licenses/LICENSE-Hamcrest.txt, all/src/assemble/LICENSE.bin.txt, all/src/assemble/NOTICE.bin.txt
- Add bunch of newly introduced dependencies to the LICENSE file 
- Update dependencies of bookkeeper after upgraded to 4.7.1
=> Update LICENSE & NOTICE for newly introduced or version-upgraded dependencies 

pulsar-client-go/pulsar/c_consumer.go, pulsar-client-go/pulsar/c_message.go
Added extra castings to fix compile issues in gcc-4.8
=> Added integer types casting to avoid compile errors with gcc-4.8

managed-ledger-shaded/pom.xml, managed-ledger/pom.xml, pom.xml, pulsar-broker-auth-athenz/pom.xml, pulsar-broker/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka-tests/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka/pom.xml, pulsar-client-tools-test/pom.xml, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageParser.java, pulsar-discovery-service/pom.xml, pulsar-proxy/pom.xml, pulsar-spark/pom.xml, pulsar-storm/pom.xml, pulsar-testclient/pom.xml, pulsar-websocket/pom.xml, pulsar-zookeeper-utils/pom.xml, tests/integration/s3-offload/pom.xml
Shading the managed-ledger API so that using the API externally do not cause class clashes
=>  adding a module that shades managed-ledge

pom.xml
*Motivation*
Apache-rat check is failing
*Changes*
- Exclude two BSD licensed files
- Exclude files related to certs used for testing
=> Exclude a few files from apache-rat:check

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/AuthenticationFilter.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java
So that it can be used by the proxy also.
Master issue: #1991
=> Move AuthenticationFilter to pulsar-broker-common

pulsar-io/kinesis/pom.xml
Upgrade kinesis KPL and aws-sdk version for kinesis-sink.
New KPL and aws-sdk version has bug-fixes.
=> Pulsar Kinesis-sink upgrade aws-sdk version

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstance.java
NPE thrown when submitting a source because context is null
=> fix bug in concerning ContextImpl

docker/pulsar/scripts/gen-yml-from-env.py, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, tests/integration-tests-topologies/src/main/java/org/apache/pulsar/tests/topologies/PulsarCluster.java, tests/integration/semantics/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java, tests/integration/semantics/src/test/java/org/apache/pulsar/tests/integration/functions/runtime/PulsarFunctionsProcessRuntimeTest.java, tests/integration/semantics/src/test/java/org/apache/pulsar/tests/integration/functions/runtime/PulsarFunctionsRuntimeTest.java, tests/integration/semantics/src/test/java/org/apache/pulsar/tests/integration/functions/runtime/PulsarFunctionsThreadRuntimeTest.java
*Motivation*
Pulsar Functions supports both process and thread modes to run functions.
Currently the test case only test process mode.
*Changes*
Improve the existing test to support testing pulsar functions in thread mode
=> Run functions runtime test with thread mode

pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpLookupService.java
Fix invalid v2-topics url to get list of topics/
=> Fix: destination lookup url for v2

pulsar-client-admin-shaded/pom.xml, pulsar-client-shaded/pom.xml
need to shade org.objenesis in both the pulsar client and admin client
=> shade dependencies in pulsar client and admin

pulsar-client-tools/pom.xml, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdSinks.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/Resources.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfig.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/validation/ValidatorImpls.java
=> patching CmdSink and adding extensive unit tests

pulsar-client-admin-shaded/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka-shaded/pom.xml, pulsar-client-shaded/pom.xml
Minimizing the number of dependencies in Pulsar client by shading them
=> shading dependencies in pulsar client

docker/pulsar/scripts/watch-znode.py
The integration tests sometimes fail because the watch-znode script
which is used to set the order of service startup throws an exception
and exits without waiting for initialization to happen.
This patch changes the watch-znode script to only ever exit if
communication with zk has been successful.
=> Only exit from watch-znode if we managed to communicate with zk

pulsar-common/src/main/proto/PulsarApi.proto
Broker/Client version-change comments helps to understand compatibility changes on each version. So, added comment for v13 version introduced in #2071
=> Add pulsar-version comment for future reference

pom.xml, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ProcessRuntime.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/ProcessRuntimeTest.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java, tests/integration-tests-topologies/src/main/java/org/apache/pulsar/tests/containers/CassandraContainer.java, tests/integration-tests-topologies/src/main/java/org/apache/pulsar/tests/topologies/PulsarCluster.java, tests/integration-tests-topologies/src/main/java/org/apache/pulsar/tests/topologies/PulsarClusterTestBase.java, tests/integration/semantics/pom.xml, tests/integration/semantics/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTestBase.java, tests/integration/semantics/src/test/java/org/apache/pulsar/tests/integration/functions/runtime/PulsarFunctionsRuntimeTest.java, tests/integration/semantics/src/test/java/org/apache/pulsar/tests/integration/io/CassandraSinkTester.java, tests/integration/semantics/src/test/java/org/apache/pulsar/tests/integration/io/PulsarIOSinkTest.java, tests/integration/semantics/src/test/java/org/apache/pulsar/tests/integration/io/SinkTester.java, tests/integration/semantics/src/test/java/org/apache/pulsar/tests/integration/utils/TestUtils.java
*Motivation*
The type class names are not set correctly for builtin connectors by FunctionActioner.
*Changes*
Set the type class name inferred from NAR package in FunctionActioner.
=>  FunctionActioner should set the type class name for both source and sink

pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSink.java
Added Kinesis-sink user metrics which can be also fetched using function-stats added in #2130
=> Add kinesis-sink user metrics to sinkContext

pulsar-client-schema/src/main/java/org/apache/pulsar/client/impl/schema/ProtobufSchema.java, pulsar-client-schema/src/test/java/org/apache/pulsar/client/schema/ProtobufSchemaTest.java, pulsar-client-schema/src/test/proto/Test.proto
Adding additional information to Protobuf schema so that the protobuf can be more easily parsed
=> augmenting protoschema with info for parsing

pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarSinkE2ETest.java, pulsar-functions/proto/src/main/proto/InstanceCommunication.proto, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java
for administrative purpose, we need to know worker-owner of the function-instance. so, adding workerId along with function-stats to find out owner of the instance.
=> function-instance lookup: retrieve function instance owner's workerId

site2/docs/administration-geo.md, site2/docs/administration-zk-bk.md, site2/docs/cookbooks-encryption.md, site2/docs/cookbooks-tiered-storage.md, site2/docs/deploy-bare-metal.md, site2/docs/deploy-dcos.md, site2/docs/developing-binary-protocol.md, site2/docs/functions-overview.md, site2/docs/getting-started-concepts-and-architecture.md, site2/docs/io-overview.md, site2/docs/security-encryption.md
Make images work in the docs when there is a base path. Example can be seen here.
https://cckellogg.github.io/incubator-pulsar/docs/functions-overview
=> Make doc image links work when there is a base path.

site2/website/siteConfig.js
Add doc search to site version 2.
=> Add search bar to new site.

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSource.java
I think due to recent refactoring some of the minor code which is not necessary to keep. so, cleaning up unnecessary assignments.
=> Cleanup unnecessary casting and creating variables

site2/docs/admin-api-brokers.md, site2/docs/admin-api-clusters.md, site2/docs/admin-api-namespaces.md, site2/docs/admin-api-non-persistent-topics.md, site2/docs/admin-api-persistent-topics.md, site2/docs/administration-dashboard.md, site2/docs/administration-geo.md, site2/docs/client-libraries-go.md, site2/docs/cookbooks-deduplication.md, site2/docs/cookbooks-tiered-storage.md
There were a few changes merged to site after site2 is merged.
This PR is to address the content inconsistency between site and site2
Fix content inconsistency
=> [website] Fix content inconsistency between site and site2

site2/website/pages/en/download.js, site2/website/siteConfig.js
Fixed to use mirrors and HTTPs for links like existing site.
=> Use HTTPs for downloads in new website

site2/website/core/Footer.js, site2/website/pages/en/contact.js, site2/website/static/js/custom.js
Added  ▼ symbol on top bar drop downs and external link symbols.
=> Open site links in new windows

pulsar-functions/scripts/python/setup.py.template
=> Fixed Spelling.

site2/website/pages/en/admin-rest-api.js, site2/website/siteConfig.js
The urls were hardcoded for local development.
Fix the urls
=> [website] fix swagger file url

pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/InstanceIdAppenderFunction.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/IntegerAdditionFunction.java
We add a few more example pulsar functions.
=> Add Example functions

site2/website/pages/en/contact.js, site2/website/pages/en/download.js, site2/website/pages/en/events.js, site2/website/pages/en/index.js, site2/website/pages/en/resources.js, site2/website/pages/en/team.js, site2/website/pages/en/versions.js
wrap the strings with `<translate>` tags so they can be translated
=> [website] wrap strings with <translate> tags

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java, site2/docs/admin-api-partitioned-topics.md, site2/docs/administration-geo.md, site2/docs/concepts-architecture-overview.md, site2/docs/cookbooks-partitioned.md, site2/docs/deploy-kubernetes.md, site2/docs/security-authorization.md, site2/docs/security-encryption.md, site2/website/versioned_docs/version-2.1.0-incubating/admin-api-partitioned-topics.md, site2/website/versioned_docs/version-2.1.0-incubating/administration-geo.md, site2/website/versioned_docs/version-2.1.0-incubating/concepts-architecture-overview.md, site2/website/versioned_docs/version-2.1.0-incubating/cookbooks-partitioned.md, site2/website/versioned_docs/version-2.1.0-incubating/deploy-kubernetes.md, site2/website/versioned_docs/version-2.1.0-incubating/security-authorization.md, site2/website/versioned_docs/version-2.1.0-incubating/security-encryption.md
- fix swagger definitions on offloader and compaction
- rename property to tenant across documentations
=> [website] rename property to tenant

site2/website/blog/2018-08-06-Apache-Pulsar-2-1-0.md, site2/website/siteConfig.js
To provide a channel for users to catch up with latest information in Pulsar
=> [blog] Enable blog in website and add one for 2.1.0 release

site2/website/blog/2018-08-06-Apache-Pulsar-2-1-0.md
Some typo fixes to the 2.1 release blog post
=> Minor typo fixes

site2/website/languages.js
adding french to website
toggled a flag
=> added FRench to website

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
Perf producer should not discard the first samples of latency collected.
=> Introduce warmup period in performance producer

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java
Test failures are caused by the delayed acks that making the broker redelivering few more messages than what remained unacked. Disabling delayed acked to have the behavior expected by the test.
Example of failures:
```
java.lang.AssertionError: expected [my-message-0] but found [my-message-2]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.apache.pulsar.broker.service.PersistentTopicE2ETest.testMessageRedelivery(PersistentTopicE2ETest.java:1252)
```
https://builds.apache.org/job/pulsar_precommit_java8/2976/testReport/junit/org.apache …
=> Fix flaky test PersistentTopicE2ETest.testMessageRedelivery

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/WorkerStats.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Functions.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/WorkerStats.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/WorkerStatsImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctionWorkerStats.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java, pulsar-functions/proto/src/main/proto/InstanceCommunication.proto, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/Resources.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2Resource.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/WorkerStats.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSink.java, site2/website/scripts/replace.js
right now, function metrics api returns metrics in prometheus format which is not user-friendly and hard to parse. So, we need metrics in json format and cli to fetch metrics same as what we have for broker.
existing metrics:
```
pulsar_function__total_processed__count{cluster="default", namespace="sample/ns1", name="demo1", instanceId="0"} 0.0 1533172228038
pulsar_function__total_processed__max{cluster="default", namespace="sample/ns1", name="demo1", instanceId="0"} 0.0 1533172228039
pulsar_function__total_processed__min{cluster="default", namespace="sample/ns1", name="demo1", instanceId="0"} 0.0 1533172228039
pulsar_function__total_processed__sum{cluster="default", namespace="sample/ns1", name="demo1", instanceId="0"} 0.0 1533172228039 …
```
=> REST and CLI to get function metrics in json for monitoring

site2/website/siteConfig.js
Re-added tracking id to new website
=> Re-added tracking id to new website

conf/functions_worker.yml, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java
remove unused config `functionMetadataSnapshotsTopicPath`
=> Remove snapshot-topic ref

site2/website/versioned_docs/version-2.1.0-incubating/deploy-bare-metal.md
PR #2335 improved documentation on bare mental deployment. But it missed to add to 2.1.0 documentation.
Cherry-pick the documentation changes to version 2.1.0
=> [documentation] Cherry-pick documentation on bare mental deployment to 2.1.0

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeSpawner.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionAssignmentTailer.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionMetaDataManager.java
Right now, at few places, function is not logging function-reference along with exception which makes hard to debug the issue. so, added more function-reference into logs for troubleshooting.
=> add more debug logs with function name reference

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloader.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloaderFactory.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, tiered-storage/jcloud/pom.xml, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/JCloudLedgerOffloaderFactory.java, tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/TieredStorageConfigurationData.java
In order to use NAR for packaging offloaders, we need a factory interface for creating offloaders.
- Provide a ledger offloader factory interface for creating offloaders.
- Move implemention specific settings to implementation package to be respecting to offloader factory interface
=> [tiered storage] Provide LedgerOffloaderFactory for creating offloaders

distribution/server/src/assemble/LICENSE.bin.txt
We are adding license-check in CI build. So we need to make sure current build can pass license-check
Update LICENSE.bin.txt
The binary package can pass license check
=> [build] Fix LICENSE.bin.txt

pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/HostAppenderFunction.java
Add HostNameAppendder to examples
=> Add HostName appender function example

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/WorkerServer.java
Right now, function web-server doesn't have slf4j handler to log web-server log. so, adding handler to capture web-server log like we already have in other modules of pulsar.
=> add slf4j handler to log web-server log

site2/website/versioned_docs/version-2.1.0-incubating/deploy-kubernetes.md
Cherry-pick changes from #2363 to 2.1.0 documentation
=> [documentation] cherry-pick deploy-kubernetes documentation changes

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ContextImplTest.java
This pr fixes two bugs in the path of user publish
1. Stackoverflow error in ContextImpl where getSchema was calling itself
2. Add topicName while building the producer.
=> Fix bug during user publish

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/validation/ValidatorImpls.java
This fixes the input topic validation for submitting new sink functions.
=> Fix InputTopic Submission for Creating Sink

pulsar-io/twitter/src/main/java/org/apache/pulsar/io/twitter/TweetData.java, pulsar-io/twitter/src/main/java/org/apache/pulsar/io/twitter/TwitterFireHose.java
=> Made Twitter FireHose to emit records containing schema information

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java
=> Make all cli arguments follow consistent - notation instead of camelcase

pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorUtils.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarMetadata.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarSplitManager.java
Improve error message handling in presto pulsar connector
=> improve error message handling

site2/website/data/team.js
Added missing committers from "team" page
=> Added missing committers from "team" page

pulsar-client-cpp/python/pulsar/__init__.py, pulsar-client-cpp/python/pulsar_test.py, pulsar-client-cpp/python/src/client.cc, pulsar-client-cpp/python/src/config.cc
app python client support for multi-topics consumer 
add 2 methods in python client
add unit test
all ut pass
=> Issue 2312: add python client multi-topics consumer support

pulsar-client-go/pulsar/c_reader.go, pulsar-client-go/pulsar/reader.go, pulsar-client-go/pulsar/reader_test.go
Added `Reader.HasNext()` in Go client library
=> Added Reader.HasNext in Go client

pulsar-client-cpp/include/pulsar/c/client.h, pulsar-client-cpp/lib/c/c_Client.cc, pulsar-client-go/pulsar/c_consumer.go, pulsar-client-go/pulsar/c_go_pulsar.h, pulsar-client-go/pulsar/consumer.go, pulsar-client-go/pulsar/consumer_test.go
Add multi-topic and regex consumer in Go client
=> Add multi-topic and regex consumer in Go client

pulsar-discovery-service/src/test/java/org/apache/pulsar/discovery/service/DiscoveryServiceTest.java
This test was flaking because it was only waiting for 1 second for
connection and message exchange to complete, which is not enough time
when there's heavy load on the machine (simulated with stress-ng).
The fix is to increase the timeout to 10 seconds. I've also cleaned up
the test to use a CompletableFuture rather than a CountDownLatch so
that the test thread can be notified of failures in the handlers.
=> Fix flake in DiscoveryServiceTest (#1081)

pulsar-client-go/pulsar/c_consumer.go, pulsar-client-go/pulsar/c_reader.go, pulsar-client-go/pulsar/consumer.go, pulsar-client-go/pulsar/consumer_test.go, pulsar-client-go/pulsar/producer_test.go, pulsar-client-go/pulsar/reader.go, pulsar-client-go/pulsar/reader_test.go
Added the option for `ReadCompacted` in Go based consumer/reader configuration.
=> Support compaction options in Go client

site2/website/core/Footer.js, site2/website/pages/en/contact.js, site2/website/pages/en/download.js, site2/website/pages/en/team.js
Fixed few links in contact and download pages
=> Fixed few links in contact and download pages

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, site2/docs/deploy-bare-metal.md, site2/docs/functions-api.md, site2/docs/functions-deploying.md, site2/docs/functions-guarantees.md, site2/docs/functions-overview.md, site2/docs/functions-quickstart.md, site2/docs/io-managing.md, site2/docs/io-quickstart.md, site2/docs/reference-pulsar-admin.md
We recently changed the argument style of functions/sources and sinks to match the rest of pulsar cli. This pr updates the documentation of the same
=> Updated documentation about changed arguments for functions, sources and sinks

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, site2/docs/reference-pulsar-admin.md
This makes the cli interface consistent with custom-serde-inputs
=> Added the --custom-schema-inputs cli arg to allow custom schema input to functions

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/producers/AbstractOneOuputTopicProducers.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/producers/MultiConsumersOneOuputTopicProducers.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSource.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/producers/MultiConsumersOneOutputTopicProducersTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/sink/PulsarSinkTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/source/PulsarSourceTest.java
=> Attach Producer/Consumer property tags so its easier to identify topics being produced/consumed by functions

pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/serde/CustomObject.java
Avro schema requires no arg constructor for object. 
=> Added a no args constructor

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfig.java, site2/docs/reference-pulsar-admin.md
as a user, we need to add sub-name for the function. adding support to attach custom sub-name.
=> add sub-name option to function cli

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java
Right now, If Consumer does cumulative ack then Ack-Tracker continuously acking with invalid messageId and continuously sending unnecessary cmds to broker.
which very first cumulative-ack, client sets `lastCumulativeAck` other than `MessageId.earliest` and because of that ack-tracker flushes ack on every timer task.
avoid sending unnecessary ack-cmd to broker.
=> Fix: avoid continuous acking with invalid msgId for cumulative ack

bin/pulsar
Some arguments in quotes are not pass in correctly e.g.
./bin/pulsar sql --execute 'show catalogs'
=> Fix sql cli

pom.xml, pulsar-flink/pom.xml, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarProducer.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/PulsarJsonTableSink.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/PulsarProduceMode.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/PulsarTableSink.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/partitioner/PulsarKeyExtractor.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/serde/JsonRowDeserializationSchema.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/serde/JsonRowSerializationSchema.java
@XiaoZYang introduces a module for a pulsar sink connector for flink. This PR is moving the work from flink repo to pulsar repo, so the flink connector can be released faster along with Pulsar releases.
Original Flink Github Issue: apache/flink#5845
Jira Issue: https://issues.apache.org/jira/browse/FLINK-9168
Original Author: @XiaoZYang (Zong Yang Xiao)
=> Add pulsar flink sink connector

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Functions.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, site2/docs/reference-pulsar-admin.md
Add CLI support to get status of specific function instance.
=> Add CLI to get function status of a specific instance

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Utils.java
Right now, function-cli doesn't cleanup function-pkg after downloading from http-url.
Delete temp file after submitting function.
=> Delete temp file after submitting function

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/proto/src/main/proto/Function.proto
=> Misc Cleanups

pulsar-client-cpp/docker-format.sh, site2/website/contributing.md
=> [documentation] Add instructions for contributing c++/python code changes

distribution/io/src/assemble/io.xml, pom.xml, pulsar-io/aerospike/pom.xml, pulsar-io/aerospike/src/main/java/org/apache/pulsar/io/aerospike/AerospikeAbstractSink.java, pulsar-io/aerospike/src/main/java/org/apache/pulsar/io/aerospike/AerospikeSinkConfig.java, pulsar-io/aerospike/src/main/java/org/apache/pulsar/io/aerospike/AerospikeStringSink.java, pulsar-io/aerospike/src/main/resources/META-INF/services/pulsar-io.yaml, site2/docs/deploy-bare-metal.md, site2/docs/getting-started-standalone.md, site2/docs/io-aerospike.md, site2/docs/io-connectors.md, site2/docs/io-overview.md, site2/docs/io-quickstart.md
The licensing issue with aerospike client has been resolved with a new version release,, we are now introducing the connector again.
=> Reintroduce Aerospike connector

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/InstanceUtils.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSource.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/sink/PulsarSinkTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/source/PulsarSourceTest.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/validation/ValidatorImpls.java
=> Fix validator logic to differentiate between serializer and deserializer

pulsar-io/twitter/src/main/java/org/apache/pulsar/io/twitter/TweetData.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/AvroSchemaHandler.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/JSONSchemaHandler.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarColumnHandle.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarColumnMetadata.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarInternalColumn.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarMetadata.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordCursor.java, pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/TestPulsarConnector.java, pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/TestPulsarMetadata.java, pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/TestPulsarRecordCursor.java
Support nested fields in POJOs to be able to be queried by sql
=> support nested fields in Pulsar presto connector

pulsar-client-cpp/lib/CMakeLists.txt
Added `install` target to do local install for C++ client lib
=> Added cmake install for lib and headers

dashboard/django/collector.py, dashboard/django/stats/views.py
Make dashboard work with python 3.
=> Fix dashboard to work with python3.

site2/website/data/resources.js, site2/website/pages/en/download.js
Addressed comments on download page links to artifacts signatures links.
=> Fixed download links and resource page

pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/PulsarConsumerSource.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/PulsarSourceBase.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/PulsarSourceBuilder.java, pulsar-flink/src/test/java/org/apache/flink/streaming/connectors/pulsar/PulsarConsumerSourceTests.java
*Motivation*
This ports apache/flink#6200 to apache pulsar repo. It adds a pulsar source connector
which will enable flink jobs to process messages from pulsar topics.
*Changes*
Add a PulsarConsumerSource connector
Author: Chris Kellogg (@cckellogg)
=> [ecosystem] Flink pulsar source connector

site2/website/scripts/replace.js
Fixed website build with missing comma in replace.js
=> Fixed website build with missing comma in replace.js

examples/flink-consumer-source/README.md, examples/flink-consumer-source/pom.xml, examples/flink-consumer-source/src/main/java/org/apache/pulsar/examples/flink/PulsarConsumerSourceWordCount.java, examples/pom.xml, pom.xml, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarProducer.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/PulsarConsumerSource.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/partitioner/PulsarKeyExtractor.java
We added flink source connector (#2441) and sink connector (#2434). It would be great to an example to show how to use flink source & sink connector.
- introduce an `examples` module
- introduce an `examples/flink-consumer-source` module
- add a word count example to use flink source and sink connector
be able to know how to use flink source & sink connector
=>  [documentation][example] Flink Source & Sink Connector

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2Resource.java
Right now, function getstatus doesn't work with auth enable.
get-function status cli will work with enabled auth.
=> Fix: get function status with auth enable

site2/website/scripts/replace.js
Comma is missing in the javascript list.
=> Another fix for website build website/scripts/replace.js

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/CustomBaseObject.java, pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/CustomDerivedObject.java
This pr does a couple of minor nits
1. Add a log statement in Sink to make it consistent with the Source.
2. Added AllArgs/NoArgs constructor for some test related objects
=> Misc fixes

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java
*Motivation*
Following exception is observed in one of the CI jobs.
```
java.lang.NullPointerException
at org.apache.pulsar.common.util.FutureUtil.waitForAll(FutureUtil.java:44)
at org.apache.pulsar.client.impl.BrokerClientIntegrationTest.testMaxConcurrentTopicLoading(BrokerClientIntegrationTest.java:601)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at …
```
=> [tests] Fix the synchronization problem at BrokerClientIntegrationTest.testMaxConcurrentTopicLoading

pulsar-functions/instance/src/main/python/python_instance.py, pulsar-functions/instance/src/main/python/python_instance_main.py, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceMain.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ProcessRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ProcessRuntimeFactory.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeFactory.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeSpawner.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ThreadRuntimeFactory.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/ProcessRuntimeTest.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionActionerTest.java
=> Make use of workerconfig defined health check interval

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageTest.java
*Motivation*
The batching behavior in BatchMessageTest#testSimpleBatchProducerConsumer is non-deterministic.
*Changes*
Disabled time based and size based batch and explicitly flush messages to ensure tests are running in a deterministic way.
=> [tests] improve BatchMessageTest#testSimpleBatchProducerConsumer

docker-compose/standalone-dashboard/README.MD, docker-compose/standalone-dashboard/docker-compose.yml
Add sample compose file for experimentation purposes.
=> Add sample docker-compose file with pulsar standalone

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionMetaDataManager.java
If function metadata-producer gets disconnected  from broker then function-registration admin-api thread gets stuck. 
```
sun.misc.Unsafe.park(boolean, long) @bci=0 (Compiled frame; information may be imprecise)
- java.util.concurrent.locks.LockSupport.park(java.lang.Object) @bci=14, line=175 (Interpreted frame)
- java.util.concurrent.CompletableFuture$Signaller.block() @bci=19, line=1693 (Interpreted frame)
- java.util.concurrent.ForkJoinPool.managedBlock(java.util.concurrent.ForkJoinPool$ManagedBlocker) @bci=119, line=3323 (Interpreted frame)
- java.util.concurrent.CompletableFuture.waitingGet(boolean) @bci=129, line=1729 (Interpreted frame)
- java.util.concurrent.CompletableFuture.get() @bci=11, line=1895 (Interpreted frame)
- …
```
=> Fix: web-thread stuck on function metadata update

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Functions.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2Resource.java
Access function state by rest endpoint
Add related rest functions
test passed
=> Access function state by rest endpoint

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BatchMessageTest.java
Fixed flaky test : 
```
Skip Message
expected [0] but found [4]
Standard Output
Created annotation listener
13:24:36.970 [main:org.apache.pulsar.broker.PulsarService@319] INFO  org.apache.pulsar.broker.PulsarService - Starting Pulsar Broker service; version: '2.2.0.0-SNAPSHOT'
13:24:36.982 [main:org.apache.pulsar.broker.PulsarService@320] INFO  org.apache.pulsar.broker.PulsarService - Git Revision b4b348da6dade88fbf08bc8f49e28f280455d985
13:24:36.984 [main:org.apache.pulsar.broker.PulsarService@321] INFO  org.apache.pulsar.broker.PulsarService - Built by  <> on asf902.gq1.y
...[truncated 42534 chars]...
position3:28:-1:4 data [B@6507f56b
13:24:43.543 [TestNG-method=testBatchAndNonBatchCumulativeAcks-1:org.apache.pulsar.broker.service.BatchMessageTest@563] INFO …
```
=> Fixed flaky test BatchMessageTest.testBatchAndNonBatchCumulativeAcks

site2/docs/concepts-messaging.md, site2/website/versioned_docs/version-2.1.0-incubating/concepts-messaging.md
=> Fixed typo in docs

pulsar-client/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java, pulsar-client/src/main/java/org/apache/pulsar/client/api/PulsarClient.java
There are few document error in code. We should fix them.
Fixes document in `ConsumerBuilder` and `PulsarClient`.
=> Fix ConsumerBuilder and PulsarClient document

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/MembershipManager.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/SchedulerManager.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/scheduler/IScheduler.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/scheduler/RoundRobinScheduler.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/MembershipManagerTest.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java
Handle heartbeat function if owner-worker is not available. 
Function scheduling handles heartbeat function if owner-worker is not available.
=> Avoid scheduling heartbeat function if owner-worker not available

pulsar-io/kafka-connect-adaptor/pom.xml, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSource.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarIOSourceTaskContext.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarKafkaWorkerConfig.java, pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStore.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/KafkaConnectSourceTest.java, pulsar-io/kafka-connect-adaptor/src/test/java/org/apache/pulsar/io/kafka/connect/PulsarOffsetBackingStoreTest.java, pulsar-io/pom.xml
add kafka source connect adaptor for debezium
This will save data from kafka source connect into Pulsar.
add class and test 
ut pass
=> Debezium: add kafka source connect adaptor for debezium

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeFactory.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeTest.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java
This pr will allow functions being deployed as kubernetes jobs have installation defined labels.
=> Have the ability to specify custom labels for k8 jobs

pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/pojo/Tick.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/TestBasicPresto.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java, tests/integration/src/test/resources/pulsar-process.xml
- Tick doesn't implement equals
- TestBasicPresto doesn't run
=> [tests][integration] Fix errors in integration tests

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeFactory.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeTest.java
No need to create any client during unittests
=> Mock out the settting up k8 client part

conf/functions_worker.yml
*Motivation*
People shouldn't be looking into code to understand how to configure a function worker.
We should have all the possible settings available in the configuration file.
*Changes*
reorganize the function worker configuration file and add missing fields
=> [functions][conf] Update functions_worker yml with all the possible settings

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeSpawner.java
*Motivation*
getFunctionStat call can happen before spanwer starts the runtime
*Changes*
Add null checks and also change the order of closing sequence in RuntimeSpawner
=> [function][runtime] NPE at RuntimeSpawner

pulsar-functions/instance/src/main/python/util.py, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntime.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeTest.java
=> The log4j should be prefixed by pulsarRootDir

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/Utils.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarRecord.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/UtilsTest.java, pulsar-functions/utils/pom.xml, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfig.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/Resources.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/Utils.java, pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/validation/ConfigValidationAnnotations.java, pulsar-io/jdbc/src/main/java/org/apache/pulsar/io/jdbc/JdbcAbstractSink.java
No real need for pulsar-functions-utils to depend on admin
=> Removed client-admin dependency from function-utils

pulsar-functions/instance/src/main/python/python_instance.py
*Motivation*
base64 is non compatible between python2 and 3
*Changes*
Provides a python 2/3 compatible method
=> [functions][python] support both python 2 and 3

distribution/server/src/assemble/src.xml, examples/flink-consumer-source/README.md, pom.xml, tests/compose/README.md
Fixed the exclusion and a couple of license headers in newly added files.
=> Fixed apache-rat validations

pulsar-client-cpp/include/pulsar/CryptoKeyReader.h, pulsar-client-cpp/include/pulsar/Logger.h, pulsar-client-cpp/include/pulsar/TopicMetadata.h, pulsar-client-cpp/lib/Hash.h
Few virtual destructors were missing and generating compile warnings.
=> [c++] Fixed virtual destructors

pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/ExclamationFunction.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/SchedulerManager.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java
Updating a function is currently broken since updates are not propagated through in the schedulerManager due to recent updates on how assignments are produced.
Tests are also broken and pass even though they should fail
=> fix: function update and related tests are broken

conf/functions_worker.yml, distribution/server/src/assemble/bin.xml, pulsar-functions/metrics/pom.xml, pulsar-functions/metrics/src/main/java/org/apache/pulsar/functions/metrics/PrometheusMetricsServer.java, pulsar-functions/metrics/src/main/java/org/apache/pulsar/functions/metrics/sink/AbstractWebSink.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeFactory.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeTest.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java
Added an agent to scrape for metrics from the functions container and expose it on a port for prometheus to scrape.
=> Metrics Collector Agent for Functions running in Kubernetes

pulsar-client-cpp/python/pulsar/functions/context.py, pulsar-functions/instance/src/main/python/contextimpl.py
=> Enhance publish method to allow properties

pulsar-client-cpp/python/pulsar/functions/context.py, pulsar-functions/instance/src/main/python/contextimpl.py
=> Added ability to specify compression while publishing

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
=> fix: unsafe cast of schema to JSONSchema

pulsar-functions/run-counter-function.sh, pulsar-functions/run-exclamation-function.sh, pulsar-functions/run-logtopic-function.sh, pulsar-functions/run-publish-function.sh, pulsar-functions/submit-python-function.sh
These are completely out of date.
=> Uptated example scripts

site2/docs/security-tls-transport.md
Inform the user why it is disabled by default and in which scenarios
they should enable it.
Master issue: #2403
=> Document TLS hostname verification option (#2403)

tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
=> Added log statements to debug PulsarFunctionsTest.testJavaExclamationTopicPatternFunction

pulsar-functions/metrics/src/main/resources/prometheus_metricsserver_log4j2.yml, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntime.java
=> Add a simple log4j configuration for PrometheusMetricsServer

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
The error message appears for all pulsar java function and can be a red-herring. Since the exception is bubbled up and printed anyways, we remove this error message
=> Remove annoying error message.

pulsar-functions/instance/src/main/python/contextimpl.py
=> fix python functions context publish

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
Override resources only if the quantities have been specified in cmdline.
=> Set function resources properly

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
The filename of the file uploaded is present in getFileName rather than getName
=> Use the right field to get the filename

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntime.java
=> Reduce memory reserved for prometheus

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/FunctionStats.java
Math error because using longs for division
=> Fixing function latency metric arithmetic error

pulsar-client-cpp/python/pulsar/functions/context.py, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java, pulsar-functions/instance/pom.xml, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/main/python/contextimpl.py, pulsar-functions/instance/src/main/python/python_instance.py, pulsar-functions/instance/src/main/python/python_instance_main.py, pulsar-functions/instance/src/main/python/secretsprovider.py, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ContextImplTest.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceRunnableTest.java, pulsar-functions/instance/src/test/python/test_python_instance.py, pulsar-functions/instance/src/test/python/test_secretsprovider.py, pulsar-functions/runtime/pom.xml, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceMain.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeFactory.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ProcessRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ProcessRuntimeFactory.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ThreadRuntime.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ThreadRuntimeFactory.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeTest.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/ProcessRuntimeTest.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/SchedulerManagerTest.java
This pr defines the secrets interface for java and python functions and hooks their implementations.
=> Hooked up secrets function api with secret function implementations

pulsar-client-cpp/homebrew/libpulsar.rb
Update Homebrew recipe for Pulsar 2.2.0 
Fixes #2894
=> Updating libpulsar Homebrew recipe to 2.2.0

pulsar-functions/secrets/src/main/java/org/apache/pulsar/functions/secretsproviderconfigurator/KubernetesSecretsProviderConfigurator.java, pulsar-functions/secrets/src/test/java/org/apache/pulsar/functions/secretsproviderconfigurator/KubernetesSecretsProviderConfiguratorTest.java
For specifying kubernetes secrets, the secret file is referred to as path in kubernetes parlance. 
=> Rename id to path for better understanding

pulsar-functions/instance/src/main/python/python_instance_main.py
=> Make print statement python3 friendly

tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/TestBasicPresto.java
After the recent dependency changes, presto is now functional again in master.
=> Enable Presto Test

pulsar-functions/instance/src/main/python/python_instance.py
fixing some bugs in the python instance metrics code
=> fix bugs in python instance metrics

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ProcessRuntime.java
=> When killing process make sure to use the force mode

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/windowing/WindowContext.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/windowing/WindowContextImpl.java
A lot has been changed in the Context interface over the last couple of releases that is not reflected in WindowContext. This pr brings it up to date with regular Context
=> Made Window Context up to date with Context

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeFactory.java, pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/KubernetesRuntimeFactoryTest.java
=> Make sure to create client before doing admission check

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
Derive np topic worker threads based on system config
=> Derive np topic worker threads based on system config

pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdSinks.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdSources.java, pulsar-common/src/main/java/org/apache/pulsar/common/functions/Utils.java
If parallelism is not set for sources/sinks, infer it as 1.
=> Infer paralellism as well

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
*Motivation*
When running with more than one function instance, Function instances will crash because of table service throws INTERNAL_SERVER_ERROR
```
org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.exceptions.ClientException: fail to access its root range : code = INTERNAL_SERVER_ERROR
at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.impl.internal.ProtocolInternalUtils.createRootRangeException(ProtocolInternalUtils.java:105) ~[java-instance.jar:2.3.0-SNAPSHOT]
at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.clients.impl.internal.RootRangeClientImpl.processCreateNamespaceResponse(RootRangeClientImpl.java:129) ~[java-instance.jar:2.3.0-SNAPSHOT]
at org.apache.pulsar.functions.runtime.shaded.org.apache.bookkeeper.client …
```
=> [state][standalone] Fix bugs on running function with multiple instances in standalone

distribution/server/src/assemble/LICENSE.bin.txt, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java, pulsar-client-tools/pom.xml, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
change StateGetter to use REST endpoint
- change StateGetter to use REST endpoint
- change related unit test
unit tests pass.
=> Issue #2657: change function cli getstate to use REST endpoint

tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestS3Offload.java
Topic unload is a lighter way to clean up all the broker state for a topic compared to restarting the broker, though it achieves the same result.
=> Use topic unload instead of broker restarts in TestS3Offload

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionE2ETest.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/FunctionStats.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceMain.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Utils.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/FunctionApiV2Resource.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
1. Add additional testing for function stats
2. Corrected stats related to processLatency and lastInvocation to return null when appropriate such as when no messages have arrived yet
=>  Correcting metrics and adding tests

distribution/io/pom.xml, pulsar-io/canal/src/main/java/org/apache/pulsar/io/canal/CanalSource.java, pulsar-io/canal/src/main/java/org/apache/pulsar/io/canal/CanalSourceConfig.java, pulsar-io/cassandra/src/main/java/org/apache/pulsar/io/cassandra/CassandraSinkConfig.java, pulsar-io/cassandra/src/main/java/org/apache/pulsar/io/cassandra/CassandraStringSink.java, pulsar-io/docs/pom.xml, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchConfig.java, pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java, pulsar-io/jdbc/src/main/java/org/apache/pulsar/io/jdbc/JdbcAutoSchemaSink.java, pulsar-io/jdbc/src/main/java/org/apache/pulsar/io/jdbc/JdbcSinkConfig.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSink.java, pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/KinesisSinkConfig.java, pulsar-io/rabbitmq/src/main/java/org/apache/pulsar/io/rabbitmq/RabbitMQConfig.java, pulsar-io/rabbitmq/src/main/java/org/apache/pulsar/io/rabbitmq/RabbitMQSource.java, pulsar-io/twitter/src/main/java/org/apache/pulsar/io/twitter/TwitterFireHose.java, pulsar-io/twitter/src/main/java/org/apache/pulsar/io/twitter/TwitterFireHoseConfig.java
*Motivation*
Include the example yaml files in the io distribution package
=> [doc] Generate connector yaml files for connectors

site2/docs/client-libraries-java.md
=> Delete extraneous punctuation

pulsar-functions/java-examples/src/main/java/org/apache/pulsar/functions/api/examples/WordCountFunction.java
=> Fixed wordcount example to actually extract words from sentence

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
cache StorageClient to avoid create it each time.
add storageClient in FunctionsImpl
original UT pass.
=> Issue #2658: cache StorageClient to avoid create it each time.

tests/integration/src/test/java/org/apache/pulsar/tests/integration/utils/DockerUtils.java
In the arquillian tests, processes were restarted using supervisorctl,
which preserved the contents of the filesystem. This was changed in
the testcontainers change to restart the whole container, which
obliterates the filesystem.
When a container is stopped, the logs are copied to the target
directory. In the case of multiple restarts the logs from the later
restarts were overwriting the logs from earlier restarts so the older
logs were lost.
This PR adds a check to ensure that we don't overwrite old logs and
appends a number to the log if a old log exists.
=> Don't overwrite integration tests longs if container restarted

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Functions.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-common/src/main/java/org/apache/pulsar/common/functions/FunctionState.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
Instead of spitting some unformatted stuff, made querystate print out a proper json object.
=> QueryState now spits out FunctionState

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntime.java
For functions, we need to set both resource requests and limits
=> Set not just resource requests but also limits

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Customers who can't decrypt their message must be given a chance to re decrypt the message if redelivery is enabled.
=> Redeliver messages that can't be decrypted.

site2/website/pages/en/events.js
*Motivation*
Fix apache pulsar events calendar link
=> [website] Fix apache pulsar events calendar

pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Record.java
Add default impl for getKey() method for Record since it is not required
=> add default impl for getKey()

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/KubernetesRuntime.java
=> Fixed Kubernetes runtime bug

pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/AvroSchemaHandler.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorMetricsTracker.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordCursor.java
Few optimizations for pulsar presto connector after doing performance analysis.  Mostly involving reusing objects
=> Few optimizations for pulsar sql

pulsar-client-cpp/python/pulsar/__init__.py, pulsar-client-cpp/python/pulsar/functions/context.py, pulsar-client-cpp/python/pulsar_test.py, pulsar-functions/instance/src/main/python/contextimpl.py, pulsar-functions/instance/src/main/python/python_instance.py
Fixes #3132
This pr adds the following enhancements for python api
1. Ability to specify event time stamp in producers
2. Ability to get event timestamp from the consumed message
3. Interfaces to get message_key, event_timestamp and properties from the current executing message in functions
=> Enhanced Pulsar Message API as well as functions context to get more message details

pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/SinkStatus.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/SourceStatus.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SinkImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SourceImpl.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
Continuing the process of making sources/sinks distinct from functions, this pr modifies the SourceStatus/SinkStatus to be Source/Sink specific.
=> Make Source/Sink status Source/Sink specific

pulsar-sql/presto-distribution/LICENSE, pulsar-sql/presto-pulsar/pom.xml, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordCursor.java
Change from ArrayBlockingQueue to use SpscArrayQueue from JCTools
Change some variables from atomics to just regular
=> more optimizations for sql

pulsar-sql/presto-distribution/LICENSE, pulsar-sql/presto-pulsar/pom.xml, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/JSONSchemaHandler.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordCursor.java
Use Dsl json for  json deserialization is much faster
=>  optimizing json deserialization in sql

pulsar-common/src/main/java/org/apache/pulsar/common/api/Commands.java
Reduce objects created when parsing the messages inside a batch.
=> Recycle objects when parsing single message metadata

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadCalculator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadCalculatorImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java, pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundle.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/SimpleLoadManagerImplTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TopicMessageIdImpl.java, pulsar-discovery-service/src/main/java/org/apache/pulsar/discovery/service/web/DiscoveryServiceServlet.java, pulsar-zookeeper/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperServerAspect.java
This PR aims to do minor cleanup and fix javadocs mostly on broker level.
1- Remove unused `function`, `variable` and `imports`.
2- Fix javadocs.
=> [Pulsar Broker] Minor CleanUp and Fix Javadocs

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ReadOnlyManagedLedgerImpl.java
In managed ledger, the check `Cursor.hasMoreEntries()` is very cheap when the last ledger has at least some entries (eg: just longs comparison). If it's empty, we need to do a more expensive check that involve looking at the ledgers list to make sure the answer is always correct.
When creating a read-only cursor, we get a snapshot of the current state. If the topic was left with a new ledger created and no entry into that, the `hasMoreEntries()` will be always expensive.
To avoid that, if the last ledger is empty, initialize the last written position on the last entry of previous ledger.
=> In managed ledger ReadOnlyCursor, optimize for when there's a new ledger created

pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/SinkStatus.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/SourceStatus.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/FunctionStatsManager.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/proto/src/main/proto/InstanceCommunication.proto, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SinkImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SourceImpl.java
Currently exceptions thrown while getting a new record(from a Source) and writing a new record(to a Sink) are not captured in the status. This pr adds them
=> Introduce Source and Sink exceptions in Status

pulsar-client-schema/src/main/java/org/apache/pulsar/client/impl/schema/JSONSchema.java
=> Use jackson for serialization and deserialization of json since its faster than gson

conf/broker.conf, conf/proxy.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
It seems that some of settings are missing at proxy.conf and broker.conf. This PR try to make them align with `ServiceConfiguration.java` and `ProxyConfiguration`.
=> Issue #2407: make conf file sync with code

pulsar-websocket/src/main/java/org/apache/pulsar/websocket/ProducerHandler.java
Recently, the WebSocket proxy in our Pulsar cluster hangs occasionally. A lot of connections in the CLOSE_WAIT state occur and the WebSocket proxy can not respond at all to requests from clients.
When checking the thread dump at this time, the IO thread is waiting forever for ack to be sent to the client.
https://gist.github.com/massakam/b0cffaf5f7361b94ec2a4dd13c672143#file-websocket_blocked_thread-txt
Some similar issues have been reported in the Jetty repository:
https://github.com/eclipse/jetty.project/issues/272
https://github.com/eclipse/jetty.project/issues/2061
The cause is still unknown, but this phenomenon seems to occur only when using blocking writes.
https://github.com/eclipse/jetty.project/issues/2061#issuecomment-420002658
When WebSocket proxy sends ack to client, it uses …
=> Modify producer handler of WebSocket to send ack to client asynchronously 

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/ProcessRuntime.java
Attempt to create log file only if does not exist.
=> Check if log folder exists

pulsar-client-schema/pom.xml, pulsar-sql/presto-distribution/LICENSE
The pom for pulsar-client-schema module has many unnecessary items.  Cleaning up the unnecessary items to reduce complexity and chances for errors
=> cleaning up pom for pulsar-client-schema

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokerStatsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ResourceQuotasBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/BrokerStats.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java, pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdSources.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsMetricsResource.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SinkImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SourceImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/WorkerImpl.java
Resolve minor spelling issue and formatting.
=> Fix Spellings and Code Cleanup

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Worker.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/WorkerStats.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Worker.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/WorkerImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CliCommand.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctionWorker.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/WorkerFunctionInstanceStats.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/WorkerImpl.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/WorkerApiV2Resource.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v2/WorkerStatsApiV2Resource.java
Cleaning up the Worker endpoints and cli. 
Remove returning protobufs as response
This is also done to pave way for this:
https://github.com/apache/pulsar/pull/3184
=> Cleaning up and improving worker endpoints

deployment/kubernetes/aws/monitoring.yaml
There currently isn't a monitoring yaml configured for EKS.
Adds a monitoring yaml for EKS 
Will create the Pulsar monitoring stack in EKS
=> Add monitoring.yaml for EKS

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
We want to get a new version of caffeine. 
Changed pom.xml's caffeine version to 2.6.2.
Upgraded caffeine change.
=> Upgrade caffiene dependency in pom.xml

pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorConfig.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorUtils.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarMetadata.java, pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/TestPulsarMetadata.java
Currently the information_schema that presto provides by default is not working for the Pulsar Presto connector
=> Get information_schema for pulsar connector to work

.travis.yml, docker/build.sh, pulsar-client-cpp/tests/CMakeLists.txt, pulsar-client-cpp/travis-build.sh
Travis build was broken for some time now, made some fixes to get it working again.
=> Fixes to get the travis build running again

pulsar-io/data-genenator/pom.xml, pulsar-io/data-genenator/src/main/java/org/apache/pulsar/io/datagenerator/DataGeneratorPrintSink.java, pulsar-io/data-genenator/src/main/java/org/apache/pulsar/io/datagenerator/Person.java, pulsar-io/data-genenator/src/main/resources/META-INF/services/pulsar-io.yaml
Currently, data generator from the datagenerator source cannot be deserialized because the library we are using to generate data, i.e. JFairy, have classes that do not have default constructors which makes deserializing thoses POJOs impossible with avro or jackson (json).
I have created "wrapper" classes with default constructors so that deserialization is possible. 
I also created a print sink for the datagenerator source to print the data generated.
=> improve datagenerator source

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/FunctionStatsManager.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
Optimized the stats collection code for java functions to reduce stats collection foot print both memory and cpu.  Reduced the number of objects allocated by 20% in java functions
=> optimize java functions stats code

managed-ledger-shaded/pom.xml, pom.xml, pulsar-broker-shaded/pom.xml, pulsar-client-kafka-compat/pulsar-client-kafka-shaded/pom.xml, pulsar-client-shaded/pom.xml, site/docs/latest/getting-started/docker.md, site2/docs/getting-started-docker.md, site2/website/versioned_docs/version-2.1.0-incubating/getting-started-docker.md, src/rename-netty-native-libs.cmd
To solve make pulsar compile on windows.
=> Make pulsar compile on windows

pulsar-functions/instance/src/main/python/contextimpl.py, pulsar-functions/instance/src/main/python/function_stats.py
Reduce memory allocation in py function stats collection
=> optimize py function stats usage

site2/docs/deploy-bare-metal.md
Issue: https://github.com/apache/pulsar/issues/3213
update the readme to highlight this part
=> document co-run zookeeper and bookie on same machine

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
namespace-service uses leaderElectionService so, leaderElectionService should start before namespace-service.
```
Caused by: java.lang.NullPointerException
at org.apache.pulsar.broker.namespace.NamespaceService.searchForCandidateBroker(NamespaceService.java:376) ~[pulsar-broker-2.2.jar]
... 9 more
at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_131]
at org.apache.pulsar.broker.namespace.NamespaceService.searchForCandidateBroker(NamespaceService.java:395) ~[pulsar-broker-2.2.jar]
at org.apache.pulsar.broker.namespace.NamespaceService.lambda$22(NamespaceService.java:335) ~[pulsar-broker-2.2.jar]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
at …
```
=> Fix NPE: namespaceService need leaderElection service

site/docs/latest/admin-api/persistent-topics.md, site2/docs/admin-api-persistent-topics.md
Issue ticket: https://github.com/apache/pulsar/issues/3233
=> Document new rest api - getLastMessageId

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientBuilderImplTest.java
Improve service url and service url provider prompt when user build a pulsar client.
Add service url and service url provider check when build a pulsar client.
Add  UT.
UT passed
=> Improve service url and service url provider prompt.

pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/PulsarConsumerSource.java, pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/PulsarSourceBuilder.java, pulsar-flink/src/test/java/org/apache/flink/streaming/connectors/pulsar/PulsarSourceBuilderTest.java
Fixes #3255 
Easier to consume multiple topics by PulsarConsumerSource.
Add multi-topic and pattern-topic set for PulsarConsumerSource.
UT passed.
=> Support multi-topic and pattern-topic for PulsarConsumerSource in pulsar

site2/website/versioned_sidebars/version-2.2.1-sidebars.json
website of 2.2.1 is missing left sidebar 
change version from 2.2.0 to 2.2.1
website fixed.
=> Issue #3277: left sidebar missing for 2.2.1 website

NOTICE, distribution/server/src/assemble/NOTICE.bin.txt
NOTICE files need to be up to date for next release
=> Update copyright year in NOTICE files to 2019

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
As per github community guidelines, creating templates for reporting bugs and feature request.
https://github.com/apache/pulsar/community
=> Default Templates for Bugs and Features

dashboard/django/collector.py
https://github.com/apache/pulsar/issues/3226 
Dashboard Consumer, Bundle,Subscription,Topic duplication
Update Consumer, Bundle,Subscription,Topic if exist
normal
=> Add update for Bundle,Topic,Subscription,Consumer if exist in dashboard

pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/utils/JavaSerDe.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Utils.java
We don't need to release resource manually any more since Java 1.7.  We can simplify related code use auto resource management now.
=> Use auto resource management to avoid closing resource manually

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
issue ticket: https://github.com/apache/pulsar/issues/3226
=> fix issue 3226 Unclosed consumer after calling closeAsync

pulsar-client-cpp/README.md
Fixed export path Typo
Fixed export path Typo
=> Fixed export path Typo

docker/pulsar-standalone/Dockerfile, docker/pulsar/Dockerfile, docker/pulsar/pom.xml, docker/pulsar/scripts/install-pulsar-client-27.sh, docker/pulsar/scripts/install-pulsar-client-37.sh, pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java
Default is still existing python2.7 installation
Update scripts to install both pulsar-client
packages for 2.7 and 3.7
=> Install python3.7 packages

docker/pulsar/scripts/apply-config-from-env.py, docker/pulsar/scripts/gen-yml-from-env.py, docker/pulsar/scripts/watch-znode.py
We need to support python2 and python3 for these scripts.
=> Make scripts run on python2 and python3

site2/docs/concepts-overview.md
=> fix typo warn -> warm

site2/docs/functions-quickstart.md
This is document entry for instructions to package python dependencies for functions.
=> Add doc entry for packaging python dependencies.

.github/PULL_REQUEST_TEMPLATE.md
*Motivation*
With the increase of contributions, more and more features are
added pretty quickly. However these features are not documented.
And there is no checklist for contributors to check when
contributing a feature.
*Changes*
This PIP is proposing to improve the github pull request template
by adding a checklist for contributors to check. It also help
improve the review process.
=> [dev] PIP 27: Add checklist in github pull request template

pulsar-client/src/test/java/org/apache/pulsar/client/tutorial/SampleConsumer.java, pulsar-client/src/test/java/org/apache/pulsar/client/tutorial/SampleProducer.java
*Motivation*
Fixes #3373 
The service url in SampleProducer is wrong.
*Modification*
Fix the service url in SampleProducer and SampleConsumer.
=> Issue #3373:  RemotelyClosedException when running SampleProducer

pulsar-client-cpp/docker-tests.sh, pulsar-client-cpp/run-unit-tests.sh
Provide a option to run specific cpp-test in docker test-run script.
=> [cpp-build] support run specific cpp-test using docker build script

site2/docs/adaptors-kafka.md
Kafka Wrapper doc minor improvement.
Amend several typos in Kafka Wrapper.
=> [docs] Fix several typos in Kafka Wrapper

site2/docs/adaptors-kafka.md
Kafka Wrapper doc minor improvement.
Add acks group time of consumer property in Kafka Wrapper.
=> [docs] Add acks group time of consumer property in Kafka Wrapper

site/docs/latest/clients/WebSocket.md, site/ja/clients/WebSocket.md, site2/docs/client-libraries-websocket.md, site2/website/versioned_docs/version-2.1.0-incubating/client-libraries-websocket.md, site2/website/versioned_docs/version-2.2.0/client-libraries-websocket.md, site2/website/versioned_docs/version-2.2.1/client-libraries-websocket.md
Fixes #3375
add Pulsar tenant and namespace created 
- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)
=> Issue #3375 Websocket example not working

pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/pulsar/client/kafka/compat/PulsarConsumerKafkaConfig.java, site2/docs/adaptors-kafka.md
Motivation
Fixes https://github.com/apache/pulsar/issues/3361
Modifications
Add a parameter in PulsarConsumerKafkaConfig to set subscriptionTopicsMode.
=> [Issue 3361][pulsar-client] Support to set 'subscriptionTopicsMode' via properties

site2/docs/functions-quickstart.md
Fix issues in python packaging docs.
=> Fix Python packaging docs

docker/pulsar/Dockerfile, docker/pulsar/scripts/set_python_version.sh, tests/docker-images/latest-version-image/Dockerfile, tests/docker-images/latest-version-image/scripts/run-bookie.sh, tests/docker-images/latest-version-image/scripts/run-broker.sh, tests/docker-images/latest-version-image/scripts/run-functions-worker.sh, tests/docker-images/latest-version-image/scripts/run-global-zk.sh, tests/docker-images/latest-version-image/scripts/run-local-zk.sh, tests/docker-images/latest-version-image/scripts/run-proxy.sh, tests/docker-images/latest-version-image/scripts/run-standalone.sh
This adds a script to change the default python symlink to python in the pulsar container, this is to enable integration tests for python 3.
=> Add set python version script

pulsar-client-api/src/main/java/org/apache/pulsar/common/schema/SchemaType.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/BooleanSchema.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/PrimitiveSchemaTest.java
[pulsar-client]  not support boolean schema
add BooleanSchema.java, encode and decode
- [✅ ] Make sure that the change passes the CI checks.
*(or)*
*(or)*
*(example:)* …
=>  [pulsar-client] add BooleanSchema

conf/functions_worker.yml, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/WorkerServer.java
Keep function-worker web-server thread configurable
=> [pulsar-function][conf] Keep function-worker web-server thread configurable

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Using analysing tools on pulsar-client reported the following fixed thread
safety issues:
- Fix `startMessageId`, `lastDequeuedMessage` and `lastMessageIdInBroker`
fields reads are performed without synchronization and potentially races
with write method, turned them into volatile.
- Fields `possibleSendToDeadLetterTopicMessages`, `deadLetterPolicy` and
`msgCrypto` can be turned into final to prevent being modified after
construction.
=> Fix thread safety violation on ConsumerImpl

pulsar-client-go/pulsar/consumer.go, pulsar-client-go/pulsar/producer.go
use iota to replace the original way
=> [go-client] use iota for go-client

pulsar-client-go/pulsar/c_consumer.go, pulsar-client-go/pulsar/c_go_pulsar.h, pulsar-client-go/pulsar/consumer.go, pulsar-client-go/pulsar/consumer_test.go
support consumer seek for go client.
=> [go-client] support consumer seek

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java, pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java
Use try-resource to auto close opened resource.
=> Use try-resource to auto close opened resource

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
=> [#3515][Broker] Make PulsarStandalone.start() public to be called in Embedded mode

pulsar-client-cpp/CMakeLists.txt, pulsar-client-cpp/lib/HTTPLookupService.cc, pulsar-client-cpp/lib/HTTPLookupService.h, pulsar-client-cpp/lib/auth/AuthAthenz.cc, pulsar-client-cpp/lib/auth/athenz/ZTSClient.cc
Remove compile and link dependency on JsonCPP. Instead use boost::property_tree with JSON parser. This will not require a link time dependency.
=> Replace JsonCPP lib with boost::property_tree

pulsar-client-kafka-compat/pulsar-client-kafka/src/main/java/org/apache/kafka/clients/producer/PulsarKafkaProducer.java
Pulsar producer now supports `flush()` operation. There's no need anymore to have custom implementation from within the Kafka API wrapper.
=> In PulsarKafkaProducer use flush() from pulsar API

pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/sink/KafkaAbstractSinkTest.java, pulsar-io/kafka/src/test/resources/kafkaSinkConfig.yaml
Add a unit test for KafkaAbstractSink to check valid configs.
Add KafkaAbstractSinkTest.
=> [pulsar-io] Add a unit test for KafkaAbstractSink

pulsar-client-cpp/include/pulsar/ConsumerConfiguration.h, pulsar-client-cpp/include/pulsar/InitialPosition.h, pulsar-client-cpp/include/pulsar/c/consumer_configuration.h, pulsar-client-cpp/lib/Commands.cc, pulsar-client-cpp/lib/Commands.h, pulsar-client-cpp/lib/ConsumerConfiguration.cc, pulsar-client-cpp/lib/ConsumerConfigurationImpl.h, pulsar-client-cpp/lib/ConsumerImpl.cc, pulsar-client-cpp/lib/ConsumerImpl.h, pulsar-client-cpp/lib/c/c_ConsumerConfiguration.cc, pulsar-client-cpp/tests/ConsumerConfigurationTest.cc
Fixes #3494  
add SubscriptionInitialPosition option in ConsumerConfiguration [issue:3493](https://github.com/apache/pulsar/issues/3494)
=> [cpp-client] add SubscriptionInitialPosition option in ConsumerConfiguration  #3494

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBase.java
Fixes #3578
Print corresponding usage according to the parsed subcommand.
=> [Issue 3578][pulsar-client-tools] Support CLI pulsar-admin subcommands for concise description

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/LedgerMetadataUtils.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java, pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java, site/docs/latest/cookbooks/bookkeeper-metadata.md, site2/docs/cookbooks-bookkeepermetadata.md, site2/website/sidebars.json
This is JUST a work-in-progress
Fixes #3458
See #3458 
Add a new LedgerMetadataUtils class which holds the logic for building "metadata" to be attached to 
- Anything that affects deployment: (yes)
- Does this pull request introduce a new feature? (yes)
- If yes, how is the feature documented? (not documented)
=> [Issue 3458: Tag Pulsar ledgers in order to distinguish from other leggers in the same Bookkeeper cluster

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/AuthenticationFactory.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/CompressionType.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerCryptoFailureAction.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerEventListener.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerInterceptor.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/CryptoKeyReader.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/DeadLetterPolicy.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/EncryptionKeyInfo.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/HashingScheme.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Message.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/MessageId.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/MessageRouter.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Producer.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ProducerBuilder.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ProducerCryptoFailureAction.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClient.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Reader.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ReaderBuilder.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ReaderListener.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/RegexSubscriptionMode.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ServiceUrlProvider.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/SubscriptionInitialPosition.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/SubscriptionType.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/TypedMessageBuilder.java
Filled in some of the missing stuff in the client API javadocs.
=> Improved Javadocs on Java client API

site2/docs/reference-pulsar-admin.md
Pulsar Admin CLI doc minor improvement.
Add descriptions for several missing subcommands in `pulsar-admin` CLI md.
=> Add several missing subcommands in Pulsar Admin CLI md

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java, site2/docs/reference-pulsar-admin.md
Pulsar Admin CLI doc minor improvement of `namespaces`.
Some minor changes in `CmdNamespaces` and add descriptions for the missing subcommands in `pulsar-admin namespaces` CLI md.
=> Minor improvement of CmdNamespaces and add the missing subcommands in Pulsar Admin CLI md

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ZeroQueueConsumerImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerImplTest.java
Simplified `ConsumerImpl` code by factoring out a bunch of if/else statements into a specialized subclass implementation.
=> Refactored handling of zero-queue consumer into separate subclass

src/stage-release.sh
Fixing minor issue in the staging script introduced in #3601
=> Remove duplicated `pushd` in stage-release.sh

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java
Set producer configs for java functions to be same as python functions
=> set functions config to me uniform

pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/WindowContext.java, pulsar-functions/windowing/src/main/java/org/apache/pulsar/functions/windowing/WindowContextImpl.java
Fixes stack overflow issue with java function window context.
Removed recursion call.
*(or)*
*(or)*
*(example:)*
- The rest …
=> Fix stackoverflow issue with java function window context.

site2/docs/client-libraries-cpp.md
Added note on how to install `libpulsar` with brew on MacOS
=> Added note on how to install `libpulsar` with brew on MacOS

site2/website/release-notes.md
Added release notes for 2.3.0 release
=> 2.3.0 release notes

site2/website/blog/2019-02-20-Apache-Pulsar-2-3-0.md
Added blog post with brief explanation of release highlights
=> Added short blog post for 2.3.0 release

site2/website/versioned_docs/version-2.3.0/client-libraries-cpp.md
Apply docs fix in #3641 also to 2.3 site
=> Apply docs fix in #3641 also to 2.3 site

pulsar-client-cpp/python/pulsar/functions/context.py
Incorrect method signature with context.publish for functions
=> fix context publish signature

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java, pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/Consumer.java, pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/impl/v1/ConsumerV1Impl.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/api/Commands.java, pulsar-common/src/main/java/org/apache/pulsar/common/api/proto/PulsarApi.java, pulsar-common/src/main/proto/PulsarApi.proto, pulsar-flink/src/test/java/org/apache/flink/streaming/connectors/pulsar/PulsarConsumerSourceTests.java
Fixes #3446 #3565 
Reset the subscription associated with this consumer to a specific publish time.
=> add reset cousor to a specific publish time

conf/broker.conf, conf/standalone.conf, deployment/terraform-ansible/templates/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java, pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LoadManagerReport.java, pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LoadReport.java, pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerData.java, site/_data/config/broker.yaml, site/_includes/explanations/ja/non-persistent-topics.md, site/docs/latest/cookbooks/non-persistent-messaging.md, site/docs/latest/getting-started/ConceptsAndArchitecture.md, site2/docs/concepts-messaging.md, site2/docs/cookbooks-non-persistent.md, site2/docs/reference-configuration.md
Reverts apache/pulsar#3348
Keeping this feature for now based on @sijie and @joefk concern at #3348
=> Revert "Remove broker mode to handle persistent/non-persistent topics separately"

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/ModularLoadManagerImplTest.java, pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicFromMessageTest.java, pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarWorkerAssignmentTest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionAdminTest.java, pulsar-broker/src/test/java/org/apache/pulsar/io/PulsarFunctionE2ETest.java, pulsar-broker/src/test/java/org/apache/pulsar/stats/client/PulsarBrokerStatsClientTest.java, tests/pulsar-storm-test/src/test/java/org/apache/pulsar/storm/PulsarSpoutTest.java
Forcing tests to use localhost, this change is needed as due to variety in jenkins hosts, current machine hostname may not resolvable to localhost ip.
=> Fix Test localhost resolution errors

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java
If we have trouble writing the output, depending on the processing semantics, we will need to fail the source record.
*(or)*
*(or)*
*(example:)*
- The default values …
=> Fail the source record if the write fails

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Topics.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java, pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java, site2/docs/admin-api-partitioned-topics.md, site2/docs/reference-pulsar-admin.md
We are adding a REST endpoint which allows the admin to create non-partitioned topics
through PersistentTopics.
=> [Issue #3436][pulsar-broker] Creating REST Endpoint for non-partitioned topic creation

README.md
Pulsar is using lombok. It requires some additional setup for IDEs
Update README instructions for Intellij and Eclipse
=> Update README.md with IDE setup for lombok

site2/website/versioned_docs/version-2.3.0/getting-started-standalone.md
add cli usage demo in standalone mode.
=> add cli client consumer for standalone

site2/docs/cookbooks-retention-expiry.md, site2/website/versioned_docs/version-2.3.0/cookbooks-retention-expiry.md
Fixed typo remove-backlog-quotas to remove-backlog-quota in docs
=> [docs] Fixed typo remove-backlog-quotas to remove-backlog-quota in docs

site2/docs/client-libraries-go.md, site2/docs/client-libraries-java.md, site2/docs/client-libraries-python.md, site2/docs/reference-terminology.md
Added usage of negative acks in the client library examples
=> Updated consumer example to use negative acks

site/docs/latest/cookbooks/RetentionExpiry.md, site/docs/latest/getting-started/LocalCluster.md, site/ja/advanced/RetentionExpiry.md, site2/docs/cookbooks-retention-expiry.md, site2/docs/getting-started-standalone.md, site2/website/versioned_docs/version-2.1.0-incubating/cookbooks-retention-expiry.md, site2/website/versioned_docs/version-2.1.0-incubating/getting-started-standalone.md, site2/website/versioned_docs/version-2.1.1-incubating/getting-started-standalone.md, site2/website/versioned_docs/version-2.2.0/getting-started-standalone.md, site2/website/versioned_docs/version-2.2.1/getting-started-standalone.md, site2/website/versioned_docs/version-2.3.0/cookbooks-retention-expiry.md, site2/website/versioned_docs/version-2.3.0/getting-started-standalone.md
fix document description bugs.
=> fix document description bugs

site2/docs/io-connectors.md, site2/docs/io-elasticsearch.md, site2/docs/io-file.md, site2/docs/io-hdfs.md, site2/docs/io-mongo.md
Fixes #3728
Add the missing doc listed in #3728.
=> [Issue #3728] Add several instructions for IO Connectors

pulsar-client-go/pulsar/c_message.go, pulsar-client-go/pulsar/client_test.go, pulsar-client-go/pulsar/consumer_test.go, pulsar-client-go/pulsar/producer_test.go, pulsar-client-go/pulsar/reader_test.go
There are several Go client unit test are not passing. Fixing them here.
=> Fixes for Go client unit test

site2/docs/concepts-messaging.md
Documentation is inconsistency after the third compression was added. 
Update documentation text.
=> [docs] Update concepts-messaging.md

pom.xml, pulsar-io/elastic-search/pom.xml, tests/integration/pom.xml
<--
- Name the pull request in the form "[Issue XYZ][component] Title of the pull request", where *XYZ* should be replaced by the actual issue number.
Skip *Issue XYZ* if there is no associated github issue for this pull request.
Skip *component* if you are unsure about which is the best component. E.g. `[docs] Fix typo in produce method`.
- Fill out the template below to describe the changes contributed by the pull request. That will give reviewers the context they need to do the review.
- Each pull request should address only one issue, not mix up code from multiple issues.
- Each commit in the pull request has a meaningful commit message
- Once all items of the checklist are addressed, remove the above text and this checklist, leaving only the filled out template below.
**(The sections …
=> fix elasticsearch in pom Consistent with other IOs

site2/docs/client-libraries-java.md
Fix broken @inject link and ```reader-interface``` reference in http://pulsar.apache.org/docs/en/client-libraries-java/
=> Fix broken reference

site2/docs/getting-started-standalone.md, site2/website/versioned_docs/version-2.3.0/getting-started-standalone.md
=> Fix codebase url

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/NegativeAcksTracker.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
Just fix some minor typos I've encountered so far.
=> Fix some minor typos

pulsar-client-go/pulsar/c_consumer.go, pulsar-client-go/pulsar/consumer.go, pulsar-client-go/pulsar/consumer_test.go
Added Go bindings for "Negative acks" implemented in C++ #3750
=> Negative acks implementation for Go client

pulsar-client-cpp/python/pulsar/__init__.py, pulsar-client-cpp/python/pulsar_test.py, pulsar-client-cpp/python/src/config.cc, pulsar-client-cpp/python/src/consumer.cc
Added Python binding for "Negative acks" implemented in C++  #3750
=> Negative acks implementation for Python client

protobuf-shaded/pom.xml
change
`<version>2.3.0-SNAPSHOT</version>` 
into 
`<version>2.4.0-SNAPSHOT</version>`
=> version not match in protobuf-shaded/pom.xml

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
When replicator is repackaging the messages for replication, it's always passing 1 for messages count in the `CommandSend` header. That header is used to compute the publish rate stats in the target cluster. It should be set to the actual number of messages in the batch.
=> Use correct number of messages in batch for publish rate stats during replication

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java
*Motivation*
Topics count is a namespace level metric. Currently if `exposeTopicLevelMetricsInPrometheus=true`
we don't expose `pulsar_topics_count`. However `pulsar_topics_count` is a very useful metric for
monitoring the healthy of the cluster.
if `exposeTopicLevelMetricsInPrometheus=true`, we expose namespace level metrics that are not
exposed at topic level. e.g. `pulsar_topics_count`.
=> [stats] Expose namespace topics count when exposing topic level metrics

src/set-project-version.sh
*Motivation*
The script doesn't update the parent version for protobuf-shaded module
use `versions:update-parent` to update parent version
=> Fix set-project-version.sh

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceRunnableTest.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImplTest.java
Fix for this issue:
https://github.com/apache/pulsar/issues/3873
=> fix: NPE when stats manager not initialized

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
Fixes #3896
Add a default value with null key records.
=> [Issue 3896] [pulsar-io] Fix NPE in ElasticSearchSink

site2/docs/admin-api-non-persistent-topics.md
The original topic name structure is incorrect. I correct the topic name structure.
Refine topic name structure as "non-persistent://tenant/namespace/topic".
=> [Doc]Refine topic name structure

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
Fix: unloading namespace logging
=> Fix: unloading namespace logging

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java, pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/ContextImplTest.java
This pr does a couple of minor fixes
1) Collect input topics from the function details spec:- Currently source is referred before creating the context, while source creation itself needs the context. This circular dependency is removed by making context creation independent of source. 
2) Catch all errors during source/sink close since its user code:- Sink/Source code is external/user code, thus any errors caught need to be caught.
*(or)*
*(or)*
*(example:)* …
=> Misc Function fixes

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Namespaces.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Topics.java
clean-up unnecessary public from interface
=> clean-up unnecessary public from interface

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java
Fixes #3867
Add the usage of chosen subcommand when `processArguments` failed.
=> [Issue 3867] Provide the description of sink/source command for better usage

pulsar-client-cpp/python/pulsar/functions/context.py, pulsar-functions/instance/src/main/python/contextimpl.py, pulsar-functions/instance/src/main/python/state_context.py
Fixes #3926 
Add possibility to delete a counter from a python function
Added a function in the state_context exposing the BK Table delete_str method
Added a function in the ContextImpl exposing this new function in the state context
Added the stub in the Context Class.
- Dependencies (does it add or upgrade a dependency):*no
- The public API: yes
- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? not documented
- If a feature is not applicable for …
=> [Issue 3926][functions] Add delete counter in python functions state_context

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadPrefixTest.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
Triggering offloading with last ledger in a topic empty was failing when triggering from CLI. 
This is due to the position `(lastLedgerId, 0)` that is being passed is marked as invalid. 
Additionally, added more info/warn logs to have more visibility on errors.
=> Fixed manual offloading when the last ledger is empty

pom.xml, pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/DebeziumSource.java, pulsar-io/debezium/postgres/pom.xml, pulsar-io/debezium/postgres/src/main/java/org/apache/pulsar/io/debezium/postgres/DebeziumPostgresSource.java, pulsar-io/debezium/postgres/src/main/resources/META-INF/services/pulsar-io.yaml, pulsar-io/debezium/postgres/src/main/resources/debezium-postgres-source-config.yaml
This PR try to add a source connector for debezium postgres.
changes:
- add debezium postges project;
- add DebeziumSource, and make mysql and postgres both inherit from it.
=> [Pulsar IO]: Add a source connector for debezium postgres

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaCompatibilityStrategy.java
Fix comments of schema compatibility strategy.
Change comment of SchemaCompatibilityStrategy.BACKWARD and SchemaCompatibilityStrategy.FORWARD
- The schema: (yes)
=> Fix comments of schema compatibility strategy.

site2/docs/security-token-admin.md, site2/website/versioned_docs/version-2.2.1/security-token-admin.md
Added information about generated key location for jwt. Added information about generating base64 encoded key.
=> Added information about generate key location for jwt. 

site2/docs/administration-load-distribution.md
The description of "Assignment granularity" is not quite clear, i'm trying to make it easy to understand.
1. Refine the description of "Assignment granularity".
2. Refine some language issues.
=> [Doc] Refine language issues in administration-load-distribution.md

pulsar-flink/src/main/java/org/apache/flink/streaming/connectors/pulsar/FlinkPulsarProducer.java
This is an improvement over #3894.
Because of how Flink instantiates functions, instead of passing a
custom `PulsarProducer` client we need to pass an object that is
serializable. The current implementation will default to always
call `createProducer()` because `producer` is `transient`, so it will
always be null when Flink creates new instances of the sink.
More context of why I need this:
I'm reading from a Kafka stream and writing into a Pulsar cluster.
The amount of data produced by the source is stream is such that
usually my jobs fail with: `Producer send queue is full`.
I was able to solve this by enabling `blockIfQueueFull`:
```kotlin
return FlinkPulsarProducer<ByteArray>(
pulsarServerUrl,
outputTopic,
serializationSchema,
PulsarKeyExtractor { UUID.randomUUID().toString() }, …
```
=> [Flink] Allow to customize PulsarProducer

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
Master issue: https://github.com/apache/pulsar/issues/3993
=> fix bug when updating function running in effectively-once

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
A deadlock can occur when non-persistent topics are deleted by GC. The cause is that thread `pulsar-inactivity-monitor-x` iterates over the topics map and tries to remove the element from the map.
```
"pulsar-inactivity-monitor-23-1" #65 prio=5 os_prio=0 tid=0x00007f64c5a50800 nid=0x723a waiting on condition [0x00007f6429bbc000]
at sun.misc.Unsafe.park(Native Method)
- parking to wait for  <0x00000000c13a3af8> (a org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section)
at java.util.concurrent.locks.StampedLock.acquireWrite(StampedLock.java:1119)
at java.util.concurrent.locks.StampedLock.writeLock(StampedLock.java:354)
at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.remove(ConcurrentOpenHashMap.java:305) …
```
=> [broker] Fix deadlock during GC of non-persistent topic

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/auth/KubernetesSecretsTokenAuthProvider.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/MembershipManager.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Worker.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerConfig.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerService.java, pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerUtils.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/MembershipManagerTest.java
When authenticationEnabled is set to false, don't set or pass any of the other configurations related to authentication
=> Don't pass any auth parameters when authentication is disabled

site2/docs/concepts-overview.md
Some sentences in this file is not quite clear. I'm trying to make it easy to read and understand.
1. Refine some sentences to be a little more smooth.
2. Avoid using ’s to show the possessive form of inanimate objects. 
3. Add periods for all lists. It is to keep styles consistent.
=> [Doc] Update site2/docs/concepts-overview.md file

site2/docs/functions-overview.md, site2/docs/io-develop.md
Fixes #3974
Add steps to build function and some minor fixes.
=> [Issue 3974] Add steps to build Pulsar function to docs

site2/website/release-notes.md
=> Added release notes for 2.3.1

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java, pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java, site2/docs/reference-pulsar-admin.md
Fixes #4047
Add the missing doc for functions/sink/source and some minor updates.
=> [Issue 4047] Catch up docs for functions/sink/source in Admin CLI

pulsar-function-go/conf/conf.yaml, pulsar-function-go/go.mod, pulsar-function-go/go.sum, pulsar-function-go/pf/context.go, pulsar-function-go/pf/instance.go, pulsar-function-go/pf/logAppender.go
support log topic for go function, user-friendly debugging.
=> [go function]support log topic for go function

pulsar-io/data-generator/src/main/java/org/apache/pulsar/io/datagenerator/DataGeneratorSource.java
Only initialize factory once in the beginning
=> improve data-generator source performance

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdminException.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BaseResource.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/ComponentResource.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SinkImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SourceImpl.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnectorProvider.java
Currently function upload, download, create, and update does really stream the function package to or from the function worker rather it reads all of the data in memory and then uploads or writes to file which can cause memory issues especially if the function package is big
=> Optimizing performance for Pulsar function archive download

pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/BrokerMonitor.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationClient.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationController.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/ManagedLedgerWriter.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java, pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
Fixes #4106
Optimize the usage of pulsar-perf subcommands.
=> [Issue 4106] [pulsar-testclient] Improve usage hints for pulsar-perf subcommands

site2/docs/reference-cli-tools.md
Catch up the command-line tools doc.
Add some missing subcommands and other updates.
=> Update command-line tools doc to catch up the work

pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/KeyValueSchema.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/KeyValueSchemaTest.java
The current keySchemaInfo and valueSchenamaInfo of KeyValueSchemahas no saved name, type and properties.
Save name, type, properties for keySchemaInfo and valueSchemaInfo of KeyValueSchema
Test pass
=> [pulsar-clients]Save name, type, properties for KeyValueSchema

pulsar-client/src/main/java/org/apache/pulsar/client/impl/BinaryProtoLookupService.java
The exception message already contains the reason of the lookup failure. The exception stack trace is redundantly verbose and doesn't add useful info in this case.
=> Less verbose error message for lookup failure

site2/docs/getting-started-docker.md
Refine the command and some typos when reading the document.
1. In `Starting Pulsar inside Docker` section, refine the command from `{{site.current_version}}` to `{{pulsar:version}}`.
2. Refine some sentences to be a little more smooth.
=> [Doc] Update the site2/docs/getting-started-docker.md file

site2/README.md
We've applied GSoD project for Pulsar docs, and more contributors might read this file, I some typos when reading the document. 
1. Delete the redundant link and information on versioning for Line 169.
2. Refine some sentences to be a little more smooth.
3. Improve notes in the `Running the site locally` section.
=> [Doc] Update the site2/README.md file

site2/website/pages/en/versions.js
The sentence is not complete and provides no useful information.
Delete the sentence.
=> [Doc] Update site2/website/pages/en/versions.js file

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
addressed #4111: removing atomic-updater from managed-ledger
=> [pulsar-broker] minor fix for removing atomic-updater at managed-ledger

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
as discussed at : #4138
fixing: clearing producer/consumer result from cnx cache.
=> [pulsar-broker] clean up producer/consumer result from connection-cache

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-sql/presto-distribution/LICENSE
This updates the bookkeeper library version to 4.9.1
=> Update bookkeeper ver to 4.9.1

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, site2/docs/security-kerberos.md, site2/docs/security-overview.md, site2/website/sidebars.json
Fixes #3654
Master Issue: #3491
add documentation for kerberos authentication
=> Issue #3654: add documentation for kerberos authentication

dev/README.md, pom.xml
Update testng ver
Update testcontainers ver
Remove arquillian references
Remove jmockit references
=> Update and cleanup test dependencies

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
=> provide better error handling logic for function authorization when a tenant doesn't exist

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/TypedMessageBuilderImpl.java
Sometimes SchemaInfo can be null. Check for those conditions.
*(or)*
*(or)*
*(example:)*
- The wire protocol: (yes …
=> Check for existance of schemaInfo before accessing it

site2/docs/getting-started-clients.md
Refine some typos when reading the document.
Refine sentences to be more clear and concise.
=> [Doc] Update site2/docs/getting-started-clients.md file

site2/website/versioned_docs/version-2.3.1/reference-cli-tools.md
Update docs of version 2.3.1 as PR #4116.
Add some missing subcommands and other updates.
=> Update command-line tools doc for v2.3.1

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
user can't register function with v1 namespace
=> [pulsar-function] fix broken backward compatibility with v1-namespace while registering function

site2/website/versioned_docs/version-2.3.1/getting-started-docker.md
I've corrected the command in this file in #4121, the change does not effect in version 2.3.1 document, since I didn't move the updated file to the site2/website/versioned_docs/version-2.3.1 directory.  
Copy the updated file `getting-started-docker.md` to the site2/website/versioned_docs/version-2.3.1 directory.
=> [Doc] Add site2/website/versioned_docs/version-2.3.1/getting-started-docker.md

site2/docs/getting-started-clients.md, site2/docs/getting-started-docker.md, site2/docs/getting-started-standalone.md
1. Adjust the structure of the chapter **Getting started**.
2. Add contents for the sections under the chapter Getting started. 
@sijie @Jennifer88huang Could you please help review? Thank you.
=> Edit *Getting started* for clarity

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/LocalRunner.java
In regards to problem list in https://github.com/apache/pulsar/issues/4248
=> fix bug with source local run

conf/proxy.conf
This adds the anonymousUserRole to the proxy config. This code checks for it but it's not in the default configs meaning it's undocumented.
*(or)*
*(or)*
*(example:)*
- …
=> add anonymousUserRole to proxy config

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-client-cpp/python/setup.py, pulsar-sql/presto-distribution/LICENSE
Upgrade to latest stable release of BookKeeper.
=> Upgrade to BookKeeper 4.9.2

pulsar-io/common/src/main/java/org/apache/pulsar/io/common/IOConfigUtils.java, pulsar-io/common/src/test/java/org/apache/pulsar/io/common/IOConfigUtilsTest.java
Currently, "loadWithSecrets" method of integrating secrets with connectors only works for sources. 
Add support sinks as well
=> add getting secrets utils method for sinks

pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java
=> typo in word validation

distribution/server/src/assemble/LICENSE.bin.txt, pom.xml, pulsar-client/pom.xml, pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java, pulsar-sql/presto-distribution/LICENSE, tests/integration/pom.xml, tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/Schemas.java
Fixes #4179 
Change joda-time dependency scope.
Add integration test for avro logical types.
This change added tests and can be verified by integration test
- The schema: (yes)
=> [schema] Fix joda dependency issue.

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
When client removes local-cluster from the replication-cluster-list, broker deletes the topic from that cluster. However, sometime due to race-condition when broker receives multiple zk-watch for policies update, broker doesn't fence topic safely which allows multiple threads to delete the same topic. In that case, first thread successfully deletes the topic and second thread fails and keep retrying to delete the same topic continuously and logs below error message.
```
18:41:00.190 [bookkeeper-ml-workers-OrderedExecutor-5-0] ERROR org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://my-prop/global/my-namespace/8:] Error deleting topic
org.apache.bookkeeper.mledger.ManagedLedgerException$MetaStoreException: org.apache.zookeeper.KeeperException$NoNodeException: …
```
=> [pulsar-broker]Fix: race condition while deleting global topic

build/docker/Dockerfile, pom.xml, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/CompressionType.java, pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ProducerBuilder.java, pulsar-client-cpp/CMakeLists.txt, pulsar-client-cpp/docker/Dockerfile, pulsar-client-cpp/include/pulsar/CompressionType.h, pulsar-client-cpp/include/pulsar/ProducerConfiguration.h, pulsar-client-cpp/lib/CompressionCodec.cc, pulsar-client-cpp/lib/CompressionCodec.h, pulsar-client-cpp/lib/CompressionCodecSnappy.cc, pulsar-client-cpp/lib/CompressionCodecSnappy.h, pulsar-common/pom.xml, pulsar-common/src/main/java/org/apache/pulsar/common/api/proto/PulsarApi.java, pulsar-common/src/main/java/org/apache/pulsar/common/compression/CompressionCodecProvider.java, pulsar-common/src/main/java/org/apache/pulsar/common/compression/CompressionCodecSnappy.java, pulsar-common/src/main/proto/PulsarApi.proto, pulsar-common/src/test/java/org/apache/pulsar/common/compression/CompressorCodecTest.java, site2/docs/concepts-messaging.md, site2/docs/reference-cli-tools.md
Support Snappy compression (https://google.github.io/snappy/) for Java/C++.
=> [pulsar-common] Support Snappy compression for Java

pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/HbaseAbstractConfig.java, pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/sink/HbaseGenericRecordSink.java, pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/sink/HbaseSinkConfig.java
1. use pulsar client BooleanSchema encode Boolean data
2. remove unused code.
1. Use  BooleanSchema.encode() replace Bytes.toBytes()
2. remove  unused code, eg:  required = false,
=> [pulsar-io] hbase sink use BooleanSchema encode Boolean data

site2/docs/concepts-messaging.md
Fixes #4119
Catch up documentation of dead letter topic.
=> [doc] Update acknowledgement and dead letter topic documentation.

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientBuilderImpl.java
Fixes #4101 
fix issue
fix keepAliveInterval method java doc
*(or)*
*(or)*
*(example:)*
- …
=> [ISSUE #4101] Fix Javadoc for ClientBuilder.keepAliveInterval

pulsar-io/file/src/main/java/org/apache/pulsar/io/file/utils/GZipFiles.java, pulsar-io/file/src/main/java/org/apache/pulsar/io/file/utils/ZipFiles.java
Close the right stream and remove unused SuppressWarnings.
=> [pulsar-io] Remove unused annotation

conf/broker.conf
Max message size should expose as a config.
=> Add setting param in broker.conf

site2/docs/io-cdc-debezium.md
Fixes https://github.com/apache/pulsar/issues/4074
Master Issue: https://github.com/apache/pulsar/issues/4074
After move it out of Kafka-connect-source, debezium connector documentation need some update.
Update debezium mysql connector.
Move kafka-connect-adaptor to debezium-mysql
=> [issue 4074][pulsar-io]debezium document udpate

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/LongSchemaVersion.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorageTest.java
*Motivation*
The schema version is actually only 8 bytes long but we allocated 64 bytes for it.
*Modification*
Allocate 8 bytes for schema version.
=> [schema] Schema version is 8 bytes long

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
Don't leak resources when a message is being discarded.
- Fix missing release() and recycle() for discarded message on
receiveIndividualMessagesFromBatch method.
- Fix argument missing of debug logging {}-placeholder.
- Fix unnecessary variable reference `payload` on messageReceived().
=> Bugfix - release and recycle on discarded messages

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadManager.java
When calling Logger's method, set the appropriate parameters
=> [pulsar-broker] When calling Logger's method, set the appropriate parameters.(#4350)

site2/docs/functions-api.md, site2/docs/functions-quickstart.md, site2/docs/io-quickstart.md, site2/docs/sql-getting-started.md, site2/website/sidebars.json
Fix https://github.com/apache/pulsar/issues/4073.
@sijie @tuteng could you please help review? Thank you.
=> [Doc] Add *Connect Pulsar to MySQL*

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java
Remove redundant SuppressWarnings.
=> [clean up] Remove redundant SuppressWarnings

pulsar-client-cpp/include/pulsar/ConsumerType.h, pulsar-client-cpp/include/pulsar/Message.h, pulsar-client-cpp/include/pulsar/MessageBuilder.h, pulsar-client-cpp/include/pulsar/c/consumer_configuration.h, pulsar-client-cpp/include/pulsar/c/message.h, pulsar-client-cpp/lib/BrokerConsumerStatsImpl.cc, pulsar-client-cpp/lib/ConsumerImpl.cc, pulsar-client-cpp/lib/Message.cc, pulsar-client-cpp/lib/MessageBuilder.cc, pulsar-client-cpp/lib/MessageImpl.cc, pulsar-client-cpp/lib/MessageImpl.h, pulsar-client-cpp/lib/c/c_Message.cc, pulsar-client-cpp/tests/ConsumerConfigurationTest.cc
support key_shared for pulsar-cpp-client
=> [cpp client]support key shared for cpp client

site/docs/latest/io/quickstart.md, site2/docs/io-cdc-canal.md, site2/docs/io-cdc-debezium.md, site2/docs/io-managing.md, site2/docs/io-quickstart.md, site2/docs/reference-pulsar-admin.md, site2/docs/sql-getting-started.md
Update the Sinks and Sources documentation in regards to https://github.com/apache/pulsar/pull/4363
=> update sinks and sources documentation

conf/broker.conf, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Replicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsController.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsSnapshotBuilder.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/ReplicatedSubscriptionsSnapshotBuilderTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/api/Commands.java
3rd part of changes for PIP-33.  Includes the creation of the snapshots when the replicated subscriptions feature is enabled.
=> Replicated subscriptions - Create snapshots

site2/docs/getting-started-standalone.md
To show the following information on the right navigation panel:
* Install builtin connectors (optional)
* Install tiered storage offloaders (optional)
=> [Doc] Adjust the structure of *Get Started*

site2/docs/security-kerberos.md
Currently, kerberos document is lack of some description when using client to connect brokers with kerberos.
=> Update pulsar kerberos document

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ChaosContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/utils/CommandGenerator.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarTestSuite.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/utils/DockerUtils.java
Fix localrun issue and add tests
This PR is based on https://github.com/apache/pulsar/pull/4395 submitted by @tuteng
Includes https://github.com/apache/pulsar/pull/4395 + tests
=> fix localrun and add tests

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java
Fix NPE
```
Exception in thread "main" java.lang.NullPointerException
at org.apache.pulsar.client.admin.PulsarAdmin.<init>(PulsarAdmin.java:178)
at org.apache.pulsar.client.admin.PulsarAdmin.<init>(PulsarAdmin.java:133)
at org.apache.pulsar.client.admin.PulsarAdmin.main(PulsarAdmin.java:434)
```
=> [pulsar-admin] fix NPE on admin creation

site2/docs/security-tls-authentication.md
According to current documentation, for a beginner can't finish each step smoothly. So add some keys that might go wrong at these steps.
=> [doc] Improve tls authentication documentation.

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentFailoverE2ETest.java
The test is spuriously failing with 
```
org.apache.pulsar.broker.service.PersistentFailoverE2ETest.testSimpleConsumerEventsWithPartition
Skipped for the past 1 build (Since Failed#9425 )
Took 0 ms.
add description
Skip Message
expected [70.0] but found [49.0]
```
The auto-retry kicks in but it fails because the topic was already created: 
```
Error Message
Partitioned topic already exists
Stacktrace
org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Partitioned topic already exists
```
Using unique topic name to make sure the retry succeeds.
=> Fixed intermittent test failure in PersistentFailoverE2ETest.testSimpleConsumerEventsWithPartition

pulsar-io/common/src/main/java/org/apache/pulsar/io/common/IOConfigUtils.java, pulsar-io/common/src/test/java/org/apache/pulsar/io/common/IOConfigUtilsTest.java
Currently the helper method loadWithSecrets doesn't look for "sensitive" fields in parent class.  
Add support for that
=> add support for loading sink/source secrets in inherited fields

site2/docs/reference-cli-tools.md, site2/docs/security-kerberos.md
A minor improvement for pulsar kerberos and cli document.
=> Update pulsar kerberos and cli document

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java
The web service api documents are lack of some descriptions.
=> Update argument description of web service

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java
Add log info for key-shared subscribe mode.
=> Add log info for key-shared subscribe mode

site2/docs/administration-zk-bk.md
Update administration-zk-bk to add the way to start bookie in foreground
Add `bookkeeper` to start a bookie.
=> [doc] Added the way to start bookie in foreground in administration-zk-bk

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedProducerImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerStatsRecorderImpl.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarServiceNameResolver.java
Fix log format for module pulsar-client. 
Part of #4304
=> Fix log format for module pulsar-client

pulsar-client-cpp/lib/MessageId.cc, pulsar-client-go/pulsar/producer_test.go
Fixes #4476 
Fix MessageID output order error
=> [issues 4476] Fix MessageID output order error

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java, pulsar-common/pom.xml, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TenantInfo.java, pulsar-sql/presto-distribution/LICENSE
rest: add swagger doc for tenants
=> rest: add swagger doc for tenants

pom.xml, pulsar-storm/pom.xml, tests/pulsar-storm-test/pom.xml, tests/pulsar-storm-test/src/test/java/org/apache/pulsar/storm/MockOutputCollector.java, tests/pulsar-storm-test/src/test/java/org/apache/pulsar/storm/MockSpoutOutputCollector.java, tests/pulsar-storm-test/src/test/java/org/apache/pulsar/storm/example/StormExample.java
[Storm-2.0](http://storm.apache.org/2019/05/30/storm200-released.html) has been released now and it has performance improvements. So, upgrading storm version in pulsar-storm so, user can use upgraded pulsar-storm in their topology.
cc: @kishorvpatil
=> [pulsar-storm] Upgrade storm version to 2.0.0

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
As discussed at #4447, added async rest handlers for partitioned-topic stats api to avoid blocking of web-threads.
=> [pulsar-admin] change partitioned topic stats on async rest api

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java
Update functions rest api doc for project.
For `createFunction` and `updateFunction` , they dump FunctionConfig as a string of type String, so in order to better show the user, the following way is used:
=> [Improve DOC] Update functions rest api doc

site2/docs/admin-api-permissions.md
Improving the quality of the documentation.
=> [Doc]Fixes a typo in the sidebar section Admin API / Permissions

pulsar-storm/src/main/java/org/apache/pulsar/storm/PulsarBolt.java
add option to pass Producer-configuration to pulsar-bolt to pass additional metadata: encryption, batching, etc.
=> [pulsar-storm] pulsar-bolt: add option to pass producer-configuration

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/NonPersistentTopics.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java, pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/naming/NamespaceName.java
Fix issue for incorrect log parameters
* When calling Logger's method, set the appropriate parameters
* Fix #4408.
=> Fix issue for incorrect log parameters

pulsar-client-cpp/pkg/rpm/Dockerfile
Fixes #1964
When I built cpp-client using `apachepulsar/pulsar-build:centos-7`, I encountered the following error:
```
[root@1fc7007643de pulsar-client-cpp]# make -j12
[ 86%] Built target pulsarShared
[ 86%] Built target pulsarStatic
[ 87%] Built target SampleConsumerListenerCApi
[ 91%] Built target SampleConsumerCApi
[ 91%] Built target SampleProducer
[ 89%] Built target SampleProducerCApi
[ 91%] Built target SampleConsumerListener
[ 93%] Built target SampleConsumer
[ 89%] Built target SampleAsyncProducer
[ 94%] Built target perfProducer
[ 93%] Built target SampleReaderCApi
[ 95%] Built target perfConsumer
[ 95%] Linking CXX shared library _pulsar.so
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status …
```
=> [issue:1964] fix build error of apachepulsar/pulsar-build:centos-7

pulsar-client-cpp/lib/ClientConnection.cc
Fixes #4504 
optimize the ssl hint for cpp
- [  ] Make sure that the change passes the CI checks.
can change the ``pulsar://`` in the examples/SampleProducer.cc to ``pulsar+ssl://`` for testing
- The wire …
=> optimizer ssl hint for cpp

conf/broker.conf, conf/standalone.conf, managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java, pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
Disable publish timeout by default until we figure out right fix for the race condition.
=> [pulsar-broker] disable publish timeout by default

site2/docs/io-quickstart.md
https://github.com/apache/pulsar/pull/4318
=> [Doc] Fix schema layout

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SourcesBase.java
Update source rest api doc, as shown below:
=> [improve doc] Update source rest api doc

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SinksBase.java, pulsar-common/pom.xml, pulsar-common/src/main/java/org/apache/pulsar/common/functions/UpdateOptions.java
This PR aims at refining the documentation of Sink REST API.
I've updated the documentation part as well as HTTP return code.
=> [REST API Doc]Sink API refinement

site2/docs/developing-cpp.md
Fixes #4551
Add the missing dependency package.
=> [Issue 4551] Fix build error of pulsar c++ client

site2/docs/cookbooks-compaction.md
Improving the quality of the documentation.
=> [Doc] Fixed a typo in Cookbook / Topic compaction

site2/docs/admin-api-overview.md, site2/docs/client-libraries-java.md, site2/docs/deploy-bare-metal.md
Pulsar already have been supported multi host. Introduce them in Pulsar document.
=> Introduce multi host in pulsar doc

bin/pulsar, conf/pulsar_env.sh
Fixes #4422
Add BOOKIE options in pulsar_env.sh.
=> [Issue 4422] Support pulsar scripts to work with bookkeeper

site2/docs/functions-overview.md
Improve doc on Pulsar Functions.
1. Add an example of Pulsar Function for Go.
2. Add Pulsar Functions SDK: Go.
3. Add an example of Go function logging.
4. Refine a section title from "Parallelism" as "Run instances in parallel"
5. Refine some typos.
- Does this pull request introduce a new feature? (yes )
- If yes, how is the feature documented? ( docs)
=> [Docs] Update site2/docs/functions-overview.md

pom.xml, pulsar-client-cpp/python/pkg/osx/osx-10.14/Vagrantfile
Fix license header check error by apache-rat.
=> Fix apache-rat license header check.

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
Improve the documentation for Non-Persistent Topic
* Improve error codes and error messages
* Description Information of Improvement Parameters
*(or)*
*(or)*
*(example:)* …
=> [docs]Improve document of non-persistent topic

distribution/server/src/assemble/src.xml
Add pulsar-client-go and pulsar-function-go to src package.
=> Add pulsar-client-go and pulsar-function-go to src package.

site2/docs/functions-debugging.md
@sijie could you please help review? Thanks
=> [Doc] Add two methods (log topic & CLI) for debugging functions

distribution/server/src/assemble/src.xml, pom.xml
Exclude go module configs check in apache-rat.
=> Exclude go module configs check in apache-rat.

pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/RuntimeUtilsTest.java
Forgot to include a test that I added for https://github.com/apache/pulsar/pull/4572
=> add RuntimeUtils test

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdProduce.java
Remove redundant parameter ```totalMessages``` for publish method.
=> [Clean up] Remove redundant parameter totalMessages

site2/docs/client-libraries-java.md
Fixes #4648 
fix cause deadlock while use subscribeAsync demo in java client doc.
=> fix cause deadlock while use subscribeAsync demo in java client doc.

bin/pulsar-managed-ledger-admin
Fixed managed ledger admin tool to work with both Python 2 and 3
=> Fixed managed ledger admin tool to work with Python3

tiered-storage/file-system/pom.xml
Modify file system version
Modify file system version
Does this pull request introduce a new feature? (yes / no)
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
If a feature is not applicable for documentation, explain why?
If a feature is not documented yet in this PR, please create a followup issue for adding the documentation
=> Modify file system offload version to 2.5.0-SNAPSHOT

site2/website/release-notes.md
Added release notes for 2.4.0 release
=> 2.4.0 release notes

pom.xml
Update Debezium version to 0.9.5.Final
=> Update Debezium version to 0.9.5.Final

site2/website/package.json
Fixes https://github.com/apache/pulsar/issues/4606
Master Issue: https://github.com/apache/pulsar/issues/4606
Refine the framework and implement language-specific code tabs
Upgrade the docusaurus version to 1.11.1 for support code tab
*(or)*
*(or)*
*(example:)*
*If `yes` was …
=> [docs]Upgrade the docusaurus to 1.11.1

pulsar-log4j2-appender/src/main/java/org/apache/pulsar/log4j2/appender/PulsarManager.java, pulsar-log4j2-appender/src/test/java/org/apache/pulsar/log4j2/appender/PulsarAppenderTest.java, pulsar-log4j2-appender/src/test/java/org/apache/pulsar/log4j2/appender/builder/ConfigurationAssemblerTest.java, pulsar-log4j2-appender/src/test/java/org/apache/pulsar/log4j2/appender/builder/ConfigurationBuilderTest.java, pulsar-log4j2-appender/src/test/java/org/apache/pulsar/log4j2/appender/builder/CustomConfigurationFactory.java
This merge request is a trivial code cleanup in the log4j-appender.
=> Cleanup in the pulsar-log4j-appender project

site2/website/blog/2019-07-05-Apache-Pulsar-2-4-0.md
=> Blog of 2.4.0 release

conf/broker.conf, site2/docs/reference-configuration.md
Fixes #4693 
Add allowAutoTopicCreation to broker.conf and reference configuration.
=> Add allowAutoTopicCreation to broker.conf and reference configuration.

pulsar-client-cpp/lib/ClientConnection.cc, pulsar-client-cpp/lib/ClientConnection.h
Fixes #4658
As mentioned in https://github.com/apache/pulsar/issues/4658, if sending and receiving a large number of messages with TLS enabled, C++ client's connection is often closed.
This seems to be because SSL socket provided by Boost.Asio may be corrupted if it is read and written by multiple threads concurrently.
A mechanism called "strand" is typically used to prevent this problem, but the Pulsar client is not currently using it.
- https://stackoverflow.com/questions/18656919/boostasiossl-access-violation-on-multi-threaded-application
- https://stackoverflow.com/questions/12794107/why-do-i-need-strand-per-connection-when-using-boostasio
Introduced "strand" to the C++ client so that reading and writing on the SSL socket are not performed simultaneously. By making this change, the …
=> [Issue #4658][pulsar-client-cpp] Introduce strand to C++ client for exclusive control

site2/website/versioned_docs/version-2.4.0/io-cdc-debezium.md
There are some typos in the document content of about debezium, which affect users' use, so fix it.
Fix typos in document of debezium. And format content
=> [doc][puslar-io]Fix document of debezium

site2/website/data/resources.js
The articles list in the resources page was not updated in while. Added blog posts centered on Pulsar.
=> Added more blog posts in the resources page

site2/docs/schema-get-started.md, site2/website/sidebars.json
Add an independent Chapter for Pulsar Schema.
This is the first section—Get started.
=> [Doc] Add Schema Chapter and Get Started Section

site2/website/data/resources.js
*Motivation*
Add a few recent presentations to the resources page. They cover different topics:
- 2.4.0 release
- use case
- serverless
- spark + pulsar
- flink + pulsar
=> Add a few recent presentations to the resources page

conf/presto/catalog/pulsar.properties, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorConfig.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarMetadata.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarSplitManager.java
Allow the presto connector to authentication with a Pulsar Cluster.
=>  Add basic authentication capabilities to Pulsar SQL

pom.xml
upgrade git_commit_id_plugin to 3.0
=> upgrade git_commit_id_plugin to 3.0

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java, pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/FunctionApiV3ResourceTest.java
Fix for the problem described in #4843
=> Fix: check function implements correct interface

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/DefaultSchemaRegistryService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistry.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryService.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/validator/SchemaRegistryServiceWithSchemaDataValidator.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/SchemaServiceTest.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Schemas.java, pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SchemasImpl.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/schema/GetAllVersionsSchemaResponse.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/schema/IsCompatibilityResponse.java, pulsar-common/src/main/java/org/apache/pulsar/common/protocol/schema/LongSchemaVersionResponse.java
Continue the issues of #4782
Add the tests for it
The schema: (yes)
Does this pull request introduce a new feature? (yes / no)
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
If a feature is not applicable for documentation, explain why?
If a feature is not documented yet in this PR, please create a followup issue for adding the documentation
=> Add the schema admin api

site2/docs/schema-evolution-compatibility.md
Structure of Schema Chapter: https://github.com/apache/pulsar/issues/4789
=> [Doc] Add Schema Evolution and Compatibility section

site2/docs/functions-deploy.md
Fixes #4554 
Add a new deploy tutorial for new Pulsar Functions structure.
Based on the original functions-deploying file, re-adjust the structure and language of functions-deploy.
=> [docs] Add functions-deploy guide for Pulsar Functions (new)

.github/PULL_REQUEST_TEMPLATE.md
just fix this particular template comment mark, :)
cc @sijie
=> fix github pull request template comment typo

site2/docs/schema-get-started.md
Structure of Schema Chapter: https://github.com/apache/pulsar/issues/4789
@sijie could you please help review?
=> [Doc] Add contents for *Get Started (Schema)*

site2/website/data/resources.js
- Does this pull request introduce a new feature? No
- If a feature is not applicable for documentation, explain why? I am adding an new resource to the list of resources on Apache Pulsar
=> Added Pulsar in Action book to resources

pulsar-sql/pom.xml, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/AvroSchemaHandler.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/JSONSchemaHandler.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarColumnHandle.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarColumnMetadata.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnector.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorCache.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorConfig.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorFactory.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorId.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorMetricsTracker.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorModule.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorUtils.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarHandleResolver.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarInternalColumn.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarMetadata.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarPlugin.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarPrimitiveSchemaHandler.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordCursor.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordSet.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarRecordSetProvider.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarSplit.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarSplitManager.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarTableHandle.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarTableLayoutHandle.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarTopicDescription.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/SchemaHandler.java, pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/package-info.java
The checksyle plugin was added to the pulsar sql module to enforce the defined style. All violations were fixed:
- Ordering of imports.
- Formatting of the code.
- Absent Javadoc comments.
- Other small issues.
=> Enforce checkstyle in the pulsar sql module

pulsar-common/src/main/java/org/apache/pulsar/common/protocol/PulsarDecoder.java
---
*Motivation*
Add default handler to handle transaction related commands.
=> [Transaction] Add default handler to handle transaction related commands

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
Fix some description information of`/bin/pulsar-admin functions` .
=> Fix pulsar admin functions description information

site2/docs/administration-dashboard.md
Fixes #4913 
The original document may mislead users into thinking that there is no any ready-made docker image and building one from scratch.
=> [doc] dashboard docker relative clarity

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/FunctionsBase.java
Fix swagger of FunctionBase display problem and use `Pulsar Function` instead of `function` or `functions` .
Before fix:
After fix:
=> Fix swagger of FunctionBase display problem

site2/docs/functions-api.md, site2/docs/functions-overview.md
The code snippets in functions documentation are wrong: `Function` class of java native is from package `java.util.function` instead of `java.util`.
in 2 markdown file, corrected 2 java source snippets.
- If yes, how is the feature documented? (not applicable)
=> [site2] fix Function classname importing

dashboard/django/stats/templates/stats/messages.html, dashboard/django/stats/views.py, dashboard/django/utils/__init__.py, dashboard/django/utils/import_utils.py, dashboard/requirements.txt, pulsar-client-cpp/include/pulsar/Message.h, pulsar-client-cpp/include/pulsar/MessageBatch.h, pulsar-client-cpp/include/pulsar/MessageId.h, pulsar-client-cpp/lib/Commands.h, pulsar-client-cpp/lib/Message.cc, pulsar-client-cpp/lib/MessageBatch.cc, pulsar-client-cpp/python/pulsar/__init__.py, pulsar-client-cpp/python/src/message.cc, pulsar-client-cpp/tests/BatchMessageTest.cc
got batch message entry bytes, we can not parse it with cpp/python client.
* provide a message batch class to parse batch message entry for cpp/python client,
* dashboard support parse batch message with pulsar-client.
=> [pulsar-client-cpp/python,dashboard] support parse batch entry

site2/website/core/Footer.js, site2/website/data/users.js, site2/website/pages/en/powered-by.js, site2/website/static/css/custom.css
Add a page with companies using or contributing to Pulsar
=> Added powered-by page

dashboard/django/stats/views.py
`format_single_message` method only receive bytes data
=> [dashboard] fix format single message raw bytes

site2/docs/functions-cli.md, site2/docs/functions-configure.md, site2/website/sidebars.json
Fixes #4554 
Add a new configure tutorial for new Pulsar Functions structure.
Based on #4846, I'd added the Pulsar Functions configuration content.
=> [doc] Pulsar Functions: CLI

site2/docs/concepts-messaging.md
The first question I had when I read this section is what is the name of the DLQ topic. I found the answer in the Java API docs, but I think it makes sense to include it in this section, especially since this feature now also works in the Websocket client. I added the name of the default dead letter queue and an example of how to specify the DLQ name.
Fixes #<xyz>
This change is a trivial rework / code …
=> Clarification in DLQ documentation

dashboard/django/stats/urls.py, dashboard/django/stats/views.py
access v1/v2 admin api by namespace name pattern
=> [dashboard] fix admin path

site2/website/data/users.js, site2/website/pages/en/index.js
Added more companies using Pulsar
=> [website] Added more companies using Pulsar

site2/website/data/users.js
=> [website] add OVH in Pulsar users

site2/docs/security-athenz.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Security document ( Security-athenz section): http://pulsar.apache.org/docs/en/next/security-athenz/
Modifications
=> [doc] Improve Pulsar Security-athenz

site2/docs/security-tls-authentication.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Security document (TLS Authentication section): http://pulsar.apache.org/docs/en/next/security-tls-authentication/
Modifications
=> [doc] Improve Pulsar security-tls-authentication

site2/docs/client-libraries-java.md
@yjshen could you please help review?
=> [Doc] Add configuration description for Java client

site2/docs/io-netty.md
At present, some users want to use the netty source, but the document is not perfect, so the netty source document is added.
* Add document of the netty source
* Add TCP example and Http example
=> [doc]Add document for pulsar IO netty source

site2/docs/cookbooks-compaction.md
Removed Java only warning for compacted read flag
=> [docs] Removed Java only warning for compacted read flag

site2/website/data/users.js
Adds https://turtlequeue.com to http://pulsar.apache.org/powered-by/
=> feat: add turtlequeue to users

site2/docs/security-kerberos.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Security document ( Security-kerberos section): http://pulsar.apache.org/docs/en/next/security-kerberos/
Modifications
=> [doc] Improve Pulsar Security Kerberos

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
public message does not only mean to persist message now, non-persistent topic has same publish path.
=> remove misleading comment in handleSend

site2/docs/client-libraries-python.md
=> Update supported  python osx version docs

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java, pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java, pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TopicStats.java
Fixes [issue-182](https://github.com/streamnative/pulsar-manager/issues/182)
=> Fix storage size always 0 without subscription.

deployment/kubernetes/README.md
Fixes #5098
Modify the relative path in README.md (pulsar/deployment/kubernetes/README.md)
=> [Issue 5098] [doc] Fix wrong reference in kubernetes deployment README.md

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerStatsRecorderImpl.java, pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerStatsRecorderImplTest.java
=> Convert latency to millisecond in producer stats

site2/website/static/js/getSwaggerByVersion.js, site2/website/static/swagger/2.4.1/swagger.json, site2/website/static/swagger/2.4.1/swaggerfunctions.json, site2/website/static/swagger/2.4.1/swaggersink.json, site2/website/static/swagger/2.4.1/swaggersource.json, src/gen-swagger.sh
Currently, there are some problems with the display of rest API for function, source, and sink. 2.4.1 does not generate a new swagger file.
* Create directory master
* Generate swagger json file for 2.4.1
* Fix swagger function, source and sink display
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not …
=> [website]Fix rest api

site2/docs/deploy-bare-metal.md
Fixes #5120
Add the configuration example when using multi-hosts.
=> [Issue 5120] Add the client usage when using multi-hosts

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
The change to use classloaders to load in user code (#4685) broke windowed functions. 
Fix the issue with classloaders and add tests
=> Fix: windowed functions were broken when we changed java function instance to use classloaders

site2/docs/security-token-admin.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Security document (security-token-admin section): http://pulsar.apache.org/docs/en/next/security-token-admin/
Modifications
=> [doc] Improve Pulsar Security-token-admin

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcher.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherMultipleConsumers.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherSingleActiveConsumer.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java, pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
Change ```getMesssageDropRate``` to ```getMessageDropRate```.
=> Fix typo in method getMessageDropRate

tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/DebeziumPostgresqlContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/DebeziumPostgresqlSourceTester.java
Provide new CDC/Debezium Postgresql Integration test. Only Mysql one was present.
=> Add Debezium Postgresql integration test

docker/pulsar/Dockerfile
This adds the ping command to the docker image
=> Add ping util to Docker file

site2/docs/deploy-dcos.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Security document (deploy-dcos section): http://pulsar.apache.org/docs/en/next/deploy-dcos/
Modifications
=> [doc] Improve Pulsar Deployment DCOS

site2/docs/deploy-monitoring.md
Motivation
Improve the language and the overall descriptive style of the Pulsar deployment document (deploy-monitoring section): http://pulsar.apache.org/docs/en/deploy-monitoring/
Modifications
=> [doc] Improve Pulsar Deployment monitoring

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Topics.java
Fix typo and incorrect description for class ```Topics```.
=> [Minor] Fix method comment for class Topics

site2/docs/security-extending.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Security document (security-extending section): http://pulsar.apache.org/docs/en/next/security-extending/
Modifications
=> [doc] Improve Pulsar Security Extending

site2/docs/security-encryption.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Security document (security-encryption section): http://pulsar.apache.org/docs/en/next/security-encryption/
Modifications
=> [doc] Improve Pulsar Security Encryption

site2/website/sidebars.json
=> [Doc] Move Connector Admin CLI to Connector Guide

site2/docs/reference-pulsar-admin.md
=> skip-all is clear-backlog after topics unification

site2/docs/io-cdc.md
Fix https://github.com/apache/pulsar/issues/5015#event-2577499721
=> [Doc] Update *CDC connector guide*

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
There was a mistake in the error message when deleting a topic failed.
=> [pulsar-broker] Fix error message when deleting topic failed

site2/docs/io-hdfs3-sink.md
=> [Doc] Add *HDFS3 sink connector guide*

site2/docs/administration-zk-bk.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Administration document (Administration-zk-bk section): http://pulsar.apache.org/docs/en/administration-zk-bk/
Modifications
=> [doc] Improve Pulsar Administration ZooKeeper and BookKeeper admin

site2/docs/administration-geo.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Administration document (Administration-geo section): http://pulsar.apache.org/docs/en/administration-geo/
Modifications
=> [doc] Improve Pulsar Administration geo-replication

site2/docs/administration-dashboard.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Administration Pulsar dashboard document (Administration-dashboard section): http://pulsar.apache.org/docs/en/administration-dashboard/
Modifications
=> [doc] Improve Pulsar Administration Pulsar dashboard

site2/docs/administration-proxy.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Administration document (Administration-proxy section): http://pulsar.apache.org/docs/en/administration-proxy/
Modifications
=> [doc] Improve Pulsar Administration Pulsar proxy

site2/docs/administration-upgrade.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Administration document (Administration-upgrade section): https://pulsar.apache.org/docs/en/administration-upgrade/
Modifications
=> [doc] Improve Pulsar Administration Upgrade 

site2/docs/administration-load-balance.md
Motivation
Improve the language and the overall descriptive style of the Pulsar Administration document (Administration-load-balance section): http://pulsar.apache.org/docs/en/administration-load-balance/
Modifications
=> [doc] Improve Pulsar Administration load-balance

.gitignore, tests/integration/src/test/java/org/apache/pulsar/tests/integration/cli/HealthCheckTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/PulsarContainer.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTestBase.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/DebeziumPostgreSqlSourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/KafkaSourceTester.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarClusterSpec.java, tests/integration/src/test/java/org/apache/pulsar/tests/integration/upgrade/PulsarZKDowngradeTest.java, tests/integration/src/test/resources/pulsar-cli.xml
Reduce the number of containers for integration tests to make them more stable in CI env.
=> Reduce resources for integration tests

site2/docs/io-cdc.md, site2/docs/io-flume-sink.md, site2/docs/io-flume-source.md, site2/website/sidebars.json
=> [Doc] Add *Flume sink connector guide*

site2/docs/io-connectors.md, site2/docs/io-kinesis-sink.md
=> [Doc] Add *Kinesis sink connector guide* 

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
When the cursor is recovered from a ledger, the ledgerHandle is kept open so that we can delete that ledger after we update the cursor status. 
If we attempt to close the cursor before having had any updates on the cursor itself, we would end up having a harmless error, saying that we're trying to append to a read-only ledger. eg.
```
00:29:32.964 [pulsar-ordered-OrderedExecutor-6-0-EventThread] ERROR org.apache.bookkeeper.client.ReadOnlyLedgerHandle - Tried to add entry on a Read-Only ledger handle, ledgerid=10 
```
Also, when we append on the ledger during the close operation, we need to explicitly close the ledger to avoid the expensive recovery when loading the topic.
=> Don't attempt to append on read-only cursor ledger

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java, pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java
We are debugging issue where client is timing out lookup request and it helps to have debug log for successful lookup response. and fix thread-factory name for proxy.
=> [pulsar-proxy] add debug log + fix thread-factory name

site2/docs/cookbooks-retention-expiry.md
See Slack conversation:
https://apache-pulsar.slack.com/archives/C5Z4T36F7/p1563815652030700
=> Clarify how retention interacts with readers

pulsar-io/mongo/pom.xml, pulsar-io/mongo/src/main/java/org/apache/pulsar/io/mongodb/MongoConfig.java, pulsar-io/mongo/src/main/java/org/apache/pulsar/io/mongodb/MongoSink.java, pulsar-io/mongo/src/main/java/org/apache/pulsar/io/mongodb/MongoSource.java, pulsar-io/mongo/src/main/resources/META-INF/services/pulsar-io.yaml, pulsar-io/mongo/src/test/java/org/apache/pulsar/io/mongodb/MongoConfigTest.java, pulsar-io/mongo/src/test/java/org/apache/pulsar/io/mongodb/MongoSourceTest.java
Add a source connector for MongoDB to be able to listen to change in a MongoDB database.
Add a new class that implements Source interface.
This change added unit tests 
- Dependencies (does it add or upgrade a dependency): yes
- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? docs for the connector (config parameters)
=> Add a source connector for MongoDB
