apache/pulsar

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/DataSketchesSummaryLogger.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/metrics/Summary.java

Added broker publish latency collection and reporting to Prometheus

Collect broker publish latency in prometheus

---

tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarTestSuite.java

There is some instability in the Pulsar Function window integration tests
Number of windows received might be less than expected because not enough time has passed after sending messages.

Fix instability in Pulsar Function window integration test

---

site2/docs/io-rabbitmq-sink.md

[Doc] Add *RabbitMQ sink connector guide*

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

Make skip all messages async
Using exist unit tests

[pulsar-admin]make skip all messages async

---

site2/docs/io-canal-source.md
site2/docs/io-cassandra-sink.md
site2/docs/io-cdc.md
site2/docs/io-cli.md
site2/docs/io-connectors.md
site2/docs/io-debezium-source.md
site2/docs/io-jdbc-sink.md
site2/docs/io-kafka-source.md
site2/docs/io-kinesis-source.md
site2/docs/io-quickstart.md
site2/website/sidebars.json

[Doc] Update connector guide overall

---

pulsar-client-cpp/pkg/deb/Dockerfile
pulsar-client-cpp/pkg/rpm/Dockerfile

Delete unnecessary files when creating docker image.
Delete tar file after zlib make.

[pulsar-client-cpp] Fix Dockerfile

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/NamespaceStats.java

Replace foreach with System.arraycopy for better performance.

Replace foreach with System.arraycopy

---

site2/website/data/users.js

Fixes #5362 
Some logo pathes are not correct, and could not display well at http://pulsar.apache.org/powered-by/
Update the logo pathes.

[Issue 5362][website]Update logo path for Pulsar users

---

pulsar-client-cpp/python/pulsar_test.py

After compaction completes the compacted ledger is recorded as a
property of a cursor. As persisting the cursor is async and we don't
wait for the acknowledgement of the acknowledgement, there may be a
race if we try to read the compacted ledger immediately.
To avoid this race, I've added a 1 second sleep to allow the compacted
ledger to be updated on the broker.
Fixes #2321

Give compacted ledger some time to update in python test (#2321)

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ProducerConfigurationData.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java

Add `batchingMaxMessages` option to perf-producer.

[pulsar-perf] Add batching max message into perf-producer

---

tests/integration/src/test/java/org/apache/pulsar/tests/integration/messaging/MessagingBase.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/messaging/NonPersistentTopicMessagingTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/messaging/TopicMessagingBase.java
tests/integration/src/test/resources/pulsar-messaging.xml

Master Issue: #5452
Enable messaging tests to integration tests.

[integration-tests]Enable messaging tests to integration tests.

---

site2/website/data/resources.js

Some resources are not added to the Resources page.
Add more resources related to Apache Pulsar blogs and presentations.

[website] Update resources.js

---

site2/website/data/team.js

Some new PMC and committers are not added to the team page.
Add new PMC and committers info in the team.js file.

[website] Update PMC and committer info in team.js

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadManager.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/OverloadShedder.java

- make the code easier for reading 
- fix misspelling
- remove redundant keywords in interface, like 'public'
- fix misspelling like 'candidateBroekrs'
- change comments' length 

fix misspelling and adjust code style

---

site2/website/versioned_docs/version-2.3.0/io-cdc.md
site2/website/versioned_docs/version-2.4.0/io-quickstart.md

* Add .md suffix for fix cdc link

[Doc]Add md suffix for fix cdc link

---

site2/docs/cookbooks-deduplication.md

Fixes #5475
1. Some texts are not displayed correctly.
2. Some links do not work well;
1. Fix the display issue.
2. Fix link issues.
3. Refine the structure and language within the md file.

[Issue 5475][docs] Update message deduplication

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java
pulsar-common/src/main/java/org/apache/pulsar/common/io/SinkConfig.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSource.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/PulsarSourceConfig.java
pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/source/PulsarSourceTest.java
pulsar-functions/proto/src/main/proto/Function.proto
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java

In some case, user wants to use a custom subscription position.
Add `--subs-position` for sink.

Add subscribe position param for consumer of sink

---

site2/docs/concepts-architecture-overview.md
site2/website/versioned_docs/version-2.1.0-incubating/admin-api-permissions.md
site2/website/versioned_docs/version-2.1.0-incubating/concepts-architecture-overview.md
site2/website/versioned_docs/version-2.4.1/reference-pulsar-admin.md

Fix https://github.com/apache/pulsar/issues/5345

[Doc] Add pulsar-admin command and fix inconsistencies

---

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java

- Adjust code style
- Add the missing placeholder in log statement
- Delete redundant `return clause` for void method 

add missing placeholder for log, delete redundant 'return' clause

---

site2/docs/concepts-clients.md

I would have found it helpful to know earlier that a reader is implemented in terms of a consumer.

Document that reader is implemented as a consumer

---

pom.xml
tests/integration/pom.xml
tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTestBase.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/utils/DockerUtils.java

Change log statements to use container names

Fix Test Assertion retry

---

pom.xml
pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistory.java
pulsar-io/debezium/core/src/test/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistoryTest.java

Fixes #5561 
Update Debezium version to 0.10.0.Final #5561

[Issue 5561] Update Debezium version to 0.10.0.Final

---

site2/website/contributing.md
site2/website/core/Footer.js
site2/website/pages/en/coding-guide.js

Fixes #5553 
Lack of coding guide page on Pulsar website.
1. Add coding guide.
2. Add coding-guide.js file.
3. Update footer.js file.

[Issue 5553] [website] Add coding-guide page

---

node_modules/.yarn-integrity
site2/docs/admin-api-functions.md
site2/website/sidebars.json

In admin api, the functions docs missing.
Add admin api docs of Pulsar Functions.

[Docs] Add admin api docs of Pulsar Functions

---

site2/docs/functions-develop.md
site2/website/versioned_docs/version-2.4.1/functions-develop.md

Fixes #5618 
The python example is not correct.
1. Correct the python example.
2. Correct two link issues.

[Issue 5618] [docs]Correct python example

---

pulsar-client-cpp/python/pulsar/__init__.py

Resolve https://github.com/apache/pulsar/issues/5345

[Doc] Correct Python versions

---

site2/website/versioned_docs/version-2.4.1/admin-api-functions.md
site2/website/versioned_sidebars/version-2.4.1-sidebars.json

The docs of functions admin api missing in `v2.4.1`
`Cherry-pick` the docs of functions admin api to `v2.4.1`

Cherry-pick functions admin api docs to 2.4.1

---

distribution/server/src/assemble/LICENSE.bin.txt
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerOfflineBacklog.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/Errors.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/OffloadPrefixReadTest.java
pom.xml
pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java
pulsar-sql/presto-distribution/LICENSE
pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZkBookieRackAffinityMapping.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/offload/TestBaseOffload.java
tiered-storage/jcloud/src/main/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/OffloadIndexBlockImpl.java

Bump Apache Bookkeeper version to `4.10.0` to bring bug fixes from bookkeeper for Pulsar.
Upgrade Apache Bookkeeper version to `4.10.0`.

Upgrade bk version to 4.10.0

---

site2/docs/deploy-bare-metal-multi-cluster.md

fix: modfiy tentant to tenant

---

site2/docs/deploy-bare-metal-multi-cluster.md
site2/website/versioned_docs/version-2.1.0-incubating/deploy-bare-metal-multi-cluster.md
site2/website/versioned_docs/version-2.2.0/deploy-bare-metal-multi-cluster.md
site2/website/versioned_docs/version-2.3.1/deploy-bare-metal-multi-cluster.md

fix typo error of website
Fixes #5661 
fix typo error of website
changed test-tentant to test-tenant

[Issue 5661]fix typo error

---

distribution/io/src/assemble/io.xml
pulsar-io/debezium/mongodb/pom.xml
pulsar-io/debezium/mongodb/src/main/java/org/apache/pulsar/io/debezium/mongodb/DebeziumMongoDbSource.java
pulsar-io/debezium/mongodb/src/main/resources/META-INF/services/pulsar-io.yaml
pulsar-io/debezium/mongodb/src/main/resources/debezium-mongodb-source-config.yaml
tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/DebeziumMongoDbContainer.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/DebeziumMongoDbSourceTester.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/DebeziumPostgreSqlSourceTester.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/SourceTester.java

Fixes #5474 
Support CDC Connector for MongoDB
add mongodb module in pular-io-debezium component .
- The wire protocol: ( no)
- The rest endpoints: ( no)
- The admin cli options: ( no)
- Anything that affects deployment: ( no)
- Does this pull request introduce a new feature? ( no)

[Issue 5474][pulsar-io-debezium] Support CDC Connector for MongoDB

---

dashboard/Dockerfile

Fixes #5688
Fix debian release
- Anything that affects deployment: (don't know)

[Issue 5688][dashboard] Fix postgres version in dockerfile

---

site2/docs/client-libraries-java.md
site2/website/versioned_docs/version-2.4.0/client-libraries-java.md
site2/website/versioned_docs/version-2.4.1/client-libraries-java.md

[Issues 5681] fix example code of java client
Fixes #5681 
The example code  of java client can't work.
```
Producer<String> producer = PulsarUtils.getClient().newProducer(Schema.STRING)
.topic("my-topic")
.enableBatch(false)
.create();
// 3 messages with "key-1", 3 messages with "key-2", 2 messages with "key-3" and 2 messages with "key-4"
producer.newMessage().key("key-1").value("message-1-1").send();
producer.newMessage().key("key-1").value("message-1-2").send();
producer.newMessage().key("key-1").value("message-1-3").send();
producer.newMessage().key("key-2").value("message-2-1").send();
producer.newMessage().key("key-2").value("message-2-2").send();
producer.newMessage().key("key-2").value("message-2-3").send();
producer.newMessage().key("key-3").value("message-3-1").send(); …
```

[Issues 5681] fix example code of java client

---

site2/docs/io-cdc.md
site2/docs/io-connectors.md
site2/docs/io-kafka-sink.md
site2/docs/io-kinesis-sink.md
site2/docs/io-kinesis-source.md

Fix https://github.com/apache/pulsar/issues/5667

[Doc] Re-organize built-in connector guide

---

site2/docs/sql-getting-started.md

The structure is not quite clear.
Refine the structure, title and content, make it more clear to follow.

[docs] Update sql getting started

---

site2/docs/sql-overview.md

There are some redundant and unclear description in the Overview.
1. Refine it to be clear and concise.
2. Adopt minimalism writing style.

[docs] Update content of Pulsar SQL overview

---

pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/sink/HbaseGenericRecordSink.java

multi columns add to single put can improve the performace
this can improve hbase put performance
in our test env, it can be better 2.x-3.x
hbase sink : change one column with one put to one put with many columns

[pulsar-io] improve hbase sink performance

---

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactoryConfig.java
pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactoryTest.java
pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java

Fixes #<xyz>
Currently when running functions as kubernetes pods, the grpc/metrics port that the container binds to is hardcoded. This pr allows this to be configurable.
*(or)*
*(or)*
*(example:)*
- *Extended …

Parametrize grpc and metrics ports so that they can be configured

---

site2/docs/io-hbase-sink.md

Fix https://github.com/apache/pulsar/issues/5667
Get configurations from [HbaseSinkConfig.java](https://github.com/apache/pulsar/blob/master/pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/sink/HbaseSinkConfig.java) and [HbaseAbstractConfig.java](https://github.com/apache/pulsar/blob/master/pulsar-io/hbase/src/main/java/org/apache/pulsar/io/hbase/HbaseAbstractConfig.java)
Get configuration examples from [sinkConfig.yaml](https://github.com/apache/pulsar/blob/master/pulsar-io/hbase/src/test/resources/sinkConfig.yaml)

[Doc] Add HBase sink connector guide

---

site2/docs/sql-deployment-configurations.md

The structure and content needs improvement.
1. Improve the structure.
2. Improve the deployment steps.

[docs] Update Pulsar SQL configuration and deployment

---

site2/docs/io-cdc-debezium.md

[Issues 5692]Add document for mongodb connector
Fixes #5692

[Issues 5692]Add document for mongodb connector

---

examples/spark/src/main/java/org/apache/spark/streaming/receiver/example/ProducerSparkWithPojo.java
examples/spark/src/main/java/org/apache/spark/streaming/receiver/example/SensorReading.java

Fixes #<xyz>
Added the class SensorReading and class ProducerSparkWithPojo  to showcase writing Pojo as Json Object to Pulsar Queue 
Based on the documentation written example class to write Pojos to Pulsar 
This mightbe more real life examples for application than bytes stream 
*(or)*
*(or)*
*(example:)* …

Adding Spark example to Write Pojo classes to Stream 

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java

Fixes #5712
This PR changes superuser role checks to go through the authorisation provider instead. Without this change, authorisation provider will not be able to validate admin access on tenants and namespaces.
queries the authorization provider instead of read options from the configuration file. With the default authorization provider, this does not change the behaviour, as it will query the configuration file options too.
pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java
- The default values of configurations: …

[Issue 5712][broker] Auth provider superuser

---

conf/broker.conf
conf/standalone.conf
deployment/terraform-ansible/templates/broker.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java
pulsar-client-cpp/test-conf/standalone-ssl.conf
pulsar-client-cpp/test-conf/standalone.conf
pulsar-client-cpp/tests/authentication.conf
pulsar-client-cpp/tests/standalone.conf
site2/docs/reference-configuration.md
site2/website/versioned_docs/version-2.4.0/reference-configuration.md
site2/website/versioned_docs/version-2.4.1/reference-configuration.md

Fixes #5614 
Deprecate brokerServicePurgeInactiveFrequencyInSeconds.
Modify many files, includes .java, .conf, .md.

[Issue 5614] Deprecate brokerServicePurgeInactiveFrequencyInSeconds

---

site2/docs/sql-rest-api.md
site2/website/sidebars.json

---
Fixes #3009
*Motivation*
There are no REST APIs usage docs for the presto SQL.

[Issue 3009][docs] Add presto sql REST APIs doc

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/TypedMessageBuilderImpl.java
site2/docs/client-libraries-java.md
site2/docs/concepts-messaging.md
site2/website/blog/2019-07-05-Apache-Pulsar-2-4-0.md
site2/website/versioned_docs/version-2.4.0/client-libraries-java.md
site2/website/versioned_docs/version-2.4.1/client-libraries-java.md
site2/website/versioned_docs/version-2.4.1/concepts-messaging.md

Fixes #5682 
Add document for sticky consumer

Add document for sticky consumer 

---

site2/website/pages/en/download.js

Website download link error
* Fix package of pulsar-manager link. Add version in the path.
yarn pass

[website]Fix pulsar-manager download link

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java

fix potential NPE and repeated conditional test
local changes

fix potential NPE and repeated conditional test

---

site2/website/static/swagger/2.4.2/swagger.json
site2/website/static/swagger/2.4.2/swaggerfunctions.json
site2/website/static/swagger/2.4.2/swaggersink.json
site2/website/static/swagger/2.4.2/swaggersource.json

- Update RESTFUL API for 2.4.2 release
docs are generated by the following command:
```
mvn -am -pl pulsar-broker install -DskipTests -Pswagger
mkdir -p site2/website/static/swagger/2.4.2/
cp pulsar-broker/target/docs/*.json site2/website/static/swagger/2.4.2/
```

Update RESTFUL API for 2.4.2 release

---

site2/website/data/team.js

Add Yu to team list.

---

pulsar-client-cpp/python/pulsar/__init__.py
pulsar-client-cpp/python/pulsar_test.py
pulsar-client-cpp/python/src/message.cc

Fixes #5811 
Added redelivery count method to message class
- Added python test for redelivery count
- Does this pull request introduce a new feature? (yes)
- If yes, how is the feature documented? (not documented)

[Issue 5811][pulsar-client-python]Expose redelivery count of message in python client

---

site2/docs/functions-cli.md
site2/docs/functions-debug.md
site2/docs/functions-deploy.md
site2/docs/functions-develop.md
site2/docs/functions-runtime.md
site2/docs/functions-worker.md
site2/website/versioned_docs/version-2.1.0-incubating/io-quickstart.md
site2/website/versioned_docs/version-2.1.1-incubating/io-quickstart.md
site2/website/versioned_docs/version-2.2.0/io-quickstart.md
site2/website/versioned_docs/version-2.4.0/functions-runtime.md
site2/website/versioned_docs/version-2.4.0/functions-worker.md
site2/website/versioned_docs/version-2.4.0/io-quickstart.md
site2/website/versioned_docs/version-2.4.1/functions-cli.md
site2/website/versioned_docs/version-2.4.1/functions-debug.md
site2/website/versioned_docs/version-2.4.1/functions-deploy.md
site2/website/versioned_docs/version-2.4.1/functions-develop.md
site2/website/versioned_docs/version-2.4.1/functions-runtime.md
site2/website/versioned_docs/version-2.4.1/functions-worker.md
site2/website/versioned_docs/version-2.4.2/functions-cli.md
site2/website/versioned_docs/version-2.4.2/functions-debug.md
site2/website/versioned_docs/version-2.4.2/functions-deploy.md
site2/website/versioned_docs/version-2.4.2/functions-develop.md
site2/website/versioned_docs/version-2.4.2/functions-runtime.md
site2/website/versioned_docs/version-2.4.2/functions-worker.md

*Motivation*
Fix warnings 'Header field "Tutorial" is not supported' on building the website

[doc] Fix warnings 'Header field "Tutorial" is not supported'

---

conf/broker.conf
conf/standalone.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/SubscribeRateLimiter.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/MessageDispatchThrottlingTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/DispatchRate.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/RateLimiter.java
pulsar-common/src/test/java/org/apache/pulsar/common/util/RateLimiterTest.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/stats/FunctionStatsManager.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/stats/SinkStatsManager.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/stats/SourceStatsManager.java

As we discussed at #5797, adding broker level relative dispatch-throttling-config.

[pulsar-server] add broker-configuration for relative dispatch throttling

---

dashboard/pom.xml
docker/pom.xml

*Motivation*
Allow skipping deploying docker artifacts to maven repo if `skipBuildDistribution` is specified

[build] Allow skipping deploying docker artifacts to maven repo

---

site2/website/blog/2019-12-04-Apache-Pulsar-2-4-2.md

Publish a blog post to apache pulsar blog:
- http://pulsar.apache.org/blog/

Add a blog post for release 2.4.2

---

site2/docs/schema-understand.md
site2/website/versioned_docs/version-2.4.1/schema-understand.md
site2/website/versioned_docs/version-2.4.2/schema-understand.md

fix example code
Fixes #5808 
Example code display error.
remove text from ```text

[Issue 5808][documentation]fix example code

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

Fixes https://github.com/apache/pulsar/issues/5724
At present, if a topic is a partitioned topic, the sub-partition topic below it is not authorized when grant it, resulting in an error in connection creation. So if the topic is found to be a partitioned topic when authorizing or canceling permissions, all partitioned topics should be authorized or revoke permissions.
support batch authorization of partitioned topic
1 Non partitioned topic, the current logic remains unchanged
2 Partitioned topic, authorize each topic through the for a loop
- …

Support batch authorization of partitioned topic

---

conf/presto/catalog/pulsar.properties
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryCacheManager.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheManagerTest.java
managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/EntryCacheTest.java
pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorCache.java
pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorConfig.java
pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/TestPulsarConnectorConfig.java

Expose more configurations of managed ledger and bookkeeper client, this will provide ability for users to optimize performance of entries reading.
Expose some configurations related to managed ledger and bookkeeper client in pulsar.config.
Add unit tests to verify the default value of the configurations.
- The default values of configurations: (yes)

[pulsar-sql]Expose configurations of managed ledger and bookkeeper client.

---

site2/docs/functions-develop.md

- Add import libs for `WordCountFunction`
- Add import libs for `JavaNativeExclamationFunction `
- Add import libs for `ExclamationFunction `

Update missing import libs in function-develop.md

---

site2/website/blog/2019-12-04-Apache-Pulsar-2-4-2.md

In #5824, I notice there is a force-push from a81364d to 5cde8b8, and the latest update is not incorporated before merging.
Update the 2.4.2 release blog with the latest version.

[release] Update 2.4.2 release blog

---

site2/docs/client-libraries-java.md

To refine the document.
Refine "The Pulsar Java client" content in aspects of grammar, spelling, wording,  etc.

[docs]Refine "The Pulsar Java client" content

---

site2/website/blog/2019-12-04-Apache-Pulsar-2-4-2.md

There are some format issues for the blog on Pulsar website.
Fix the format and link issue.
Test locally, and they work well.

[blog] Refine format issues for Pulsar 2.4.2 release blog

---

site2/website/blog/2019-12-18-Pulsar-summit-cfp.md

Pulsar Summit CFP is open, we need a blog to announce it.
Add a blog to announce Pulsar Summit CFP.

[blog] Add blog on Pulsar Summit CFP

---

site2/docs/schema-get-started.md

[doc] Fix Typo in 'schema get started'

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/SslContextAutoRefreshBuilder.java
pulsar-io/jdbc/src/test/java/org/apache/pulsar/io/jdbc/JdbcSinkTest.java

fix some typos in the comments

fix some typos in the comments

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java

Fix topic stop dispatch messages to consumers after read or replay 0 entries from bookie
Here is the topic stats and internal stats:
```json
{
"msgRateIn" : 231.6668315416007,
"msgThroughputIn" : 62304.81100356746,
"msgRateOut" : 0.0,
"msgThroughputOut" : 0.0,
"averageMsgSize" : 268.94143882819634,
"storageSize" : 5353680152,
"backlogSize" : 2293765539,
"publishers" : [ {
"msgRateIn" : 13.666676654501744,
"msgThroughputIn" : 3648.502666386557,
"averageMsgSize" : 266.0,
"producerId" : 1,
"metadata" : { },
"producerName" : "pulsar-cluster-gz-tencent-0-33",
"connectedSince" : "2019-12-18T16:28:05.043+08:00",
"clientVersion" : "2.4.2",
"address" : "/10.205.54.106:56772"
}, {
"msgRateIn" : 32.66669035219495,
"msgThroughputIn" : 8777.806364494802,
"averageMsgSize" : 268.0,
"producerId" : 1, …
```

[hot-fix]Fix potential read 0 entries cause dispatcher stop dispatch

---

site2/docs/client-libraries-cpp.md

Refine the C++ client libraries.
1. Refine from technical writing perspective.
2. Install and check the technical parts.
3. Add more details on how to connect to Pulsar with C++ client libraries.

[docs] Update C++ client libraries

---

deployment/kubernetes/helm/pulsar/templates/broker-deployment.yaml
deployment/kubernetes/helm/pulsar/values.yaml

Fixes #5818 
- Set the startup order of broker and bookie

[Issue:5818]Set the startup order of broker and bookie

---

pulsar-client-cpp/docker-build.sh
pulsar-client-cpp/docker-format.sh
pulsar-client-cpp/docker/build-client-lib.sh
pulsar-client-cpp/docker/build-wheels.sh

Allow volume override for docker commands
with env variable, this allows the scripts to
work in dind environments.

Make docker files consistent.

---

.github/workflows/ci-unit-flaky.yaml
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaValidationEnforced.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest2.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApiTest2.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageIdSerialization.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/ProxyServer.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/WebSocketProxyConfiguration.java

---
*Motivation*
Some tests are failed by the file they used was changes.
Fix flaky tests

[Github Action] Fix flaky test

---

site2/website/versioned_docs/version-2.4.0/security-jwt.md
site2/website/versioned_docs/version-2.4.0/security-overview.md
site2/website/versioned_docs/version-2.4.2/security-overview.md
site2/website/versioned_sidebars/version-2.4.0-sidebars.json
site2/website/versioned_sidebars/version-2.4.1-sidebars.json
site2/website/versioned_sidebars/version-2.4.2-sidebars.json

JWT content is not linked well.  This PR tries to fix the link
Add support from 2.4.0.
build website locally, verify links for 2.4.0, 2.4.1, 2.4.2 works well.

website : fix jwt link and content

---

site2/tools/pulsar-admin-doc-gen.sh

Because the directory documents not create, throw the exception:
```
+ ./pulsar-admin-doc-gen.sh
./pulsar-admin-doc-gen.sh: line 28: /pulsar/site2/website/brodocs/documents/broker-stats.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 29: /pulsar/site2/website/brodocs/documents/brokers.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 30: /pulsar/site2/website/brodocs/documents/clusters.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 31: /pulsar/site2/website/brodocs/documents/functions.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 32: /pulsar/site2/website/brodocs/documents/namespaces.md: No such file or directory
./pulsar-admin-doc-gen.sh: line 33: /pulsar/site2/website/brodocs/documents/ns-isolation-policy.md: No such file or …
```

[website]Fixed website build error

---

site2/docs/administration-dashboard.md

Pulsar dashboard is deprecated. Pulsar manager is the new tool to manage and monitor topics.
Add a note to specify it.

Pulsar dashboard is deprecated

---

deployment/kubernetes/helm/pulsar/values-mini.yaml

Fix typos and sync values-mini with values
Comments only.
- If a feature is not applicable for documentation, explain why? trivial

[helm] Fix typos and sync values-mini with values

---

pom.xml
pulsar-io/debezium/core/src/main/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistory.java
pulsar-io/debezium/core/src/test/java/org/apache/pulsar/io/debezium/PulsarDatabaseHistoryTest.java

Fixes https://github.com/apache/pulsar/issues/5941
Debezium has released the major version v1.0.0.Final.
* Upgrade version of debezium from 0.10.0 to 1.0.0.Final
Local integration test

[Issue 5941][Pulsar IO]Upgrade debezium from v0.10.0-Final to v1.0.0-Final

---

site2/docs/reference-cli-tools.md
site2/docs/reference-configuration.md

Fixes https://github.com/apache/pulsar/issues/5775
Add the description for broker-tool accordingly.
Refer to: https://github.com/apache/pulsar/pull/5768
broker-tool section added.
This change needs to be reviewed.
Does this pull request introduce a new feature? (yes)
If yes, how is the feature documented? ( docs )
If a feature is not applicable for documentation, explain why?
If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

[Issue 5775][Doc] Description of broker-tool added

---

site2/tools/build-site.sh

Some contents in Japanese and French files cannot be parsed
* Exclude Japanese and French files
crowdin --config ../crowdin.yaml download -b master
yarn build

[website]Crowdin parse document error

---

site2/docs/concepts-messaging.md
site2/docs/developing-binary-protocol.md
site2/docs/io-connectors.md
site2/docs/io-hbase-sink.md
site2/website/sidebars.json

Fix https://github.com/apache/pulsar/issues/6058

[Fix doc issue 6058] Add consumer descriptions

---

site2/website/static/swagger/2.5.0/swagger.json
site2/website/static/swagger/2.5.0/swaggerfunctions.json
site2/website/static/swagger/2.5.0/swaggersink.json
site2/website/static/swagger/2.5.0/swaggersource.json

Fixes #6114 
The swagger files were generated for the version 2.5.0 according to the [instruction](https://github.com/apache/pulsar/issues/6114#issuecomment-576696130) provided by @tuteng

[Issue 6114][Doc 2.5.0] Fix missing Swagger files for the version 2.5.0

---

pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TopicStats.java

[Issue 5505] fix NPE

---

site2/docs/concepts-messaging.md
site2/docs/cookbooks-partitioned.md

Fixes #6056 
There is no doc telling users how to choose partition when you use a key.
Add example on how to choose partition when using a key.

[Issue 6056][docs] Add example on how to choose partition when using a key

---

site2/docs/io-quickstart.md
site2/website/pages/en/download.js
site2/website/sidebars.json
site2/website/versioned_docs/version-2.4.0/io-quickstart.md
site2/website/versioned_docs/version-2.5.0/io-quickstart.md
site2/website/versioned_docs/version-2.5.0/io-use.md
site2/website/versioned_sidebars/version-2.5.0-sidebars.json

Fixed:
https://github.com/apache/pulsar/issues/6115
https://github.com/apache/pulsar/issues/6110
https://github.com/apache/pulsar/issues/6108
https://github.com/apache/pulsar/issues/6100
There are some errors in the content of the current document due to the adjustment of the architecture, so we will fix it.
* The display is inconsistent with the downloaded content.
* Document display error
* Add io-use.md for version 2.5.0
Local pass

[website]Fixed website error

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ZeroQueueConsumerImpl.java

Available permits of ZeroQueueConsuemer must be 1 or less, however ZeroQueueConsuemer using listener may be greater than 1.
If listener is processing message, ZeroQueueConsumer doesn't send permit when it reconnect to broker.
1. ZeroQueueConsuemer using listener consume a topic.
2. Unload that topic( or restart a broker) when listener is processing message.
3.  ZeroQueueConsumer sends permit when it reconnect to broker.
https://github.com/apache/pulsar/blob/v2.5.0/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ZeroQueueConsumerImpl.java#L133
4. ZeroQueueConsumer also sends permit when finished processing message.
https://github.com/apache/pulsar/blob/v2.5.0/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ZeroQueueConsumerImpl.java#L163
5. Available permits become 2.

Fix available permits may be greater than 1 even though queue size is 0.

---

site2/docs/schema-understand.md

Fix typo in schema documentation when create a consumer.

Fix ConsumerBuilder.create() -> .subscribe()

---

site2/docs/functions-develop.md
site2/docs/schema-get-started.md

Fix typo in schema documentation.

Fixed the typo

---

pulsar-client-cpp/python/setup.py

For development and internal release purposes we are providing additional name and versioning options for python packages

Allow Customization of version and name of python packages

---

site2/tools/build-site.sh

After completing this pull request https://github.com/apache/pulsar/pull/5738, it seems that the document was not copied to the correct place to fix the problem.
* Copy the document to the correct place

[website]Add copy file for cli tools

---

site2/docs/concepts-messaging.md

Fix https://github.com/apache/pulsar/issues/6206

[Doc] Fix issue 6206 - Add explanations for acknowledgement 

---

site2/docs/client-libraries-cpp.md
site2/docs/client-libraries-go.md
site2/docs/client-libraries-java.md
site2/docs/client-libraries-node.md
site2/docs/client-libraries-python.md

Fix https://github.com/apache/pulsar/issues/6186

[Doc] Fix issue 6186 - Add explanations for methods in producer and consumer are thread-safe in 5 language clients

---

site2/docs/functions-overview.md

Improved documentation
Update url in the documentation for apache pulsar
- Does this pull request introduce a new feature? **no**

[docs] Update Apache Heron URL

---

.asf.yaml
.github/workflows/ci-cpp.yaml
.github/workflows/ci-go-functions-style.yaml
.github/workflows/ci-go-functions-test.yaml
.github/workflows/ci-integration-backwards-compatibility.yaml
.github/workflows/ci-integration-cli.yaml
.github/workflows/ci-integration-function-state.yaml
.github/workflows/ci-integration-messaging.yaml
.github/workflows/ci-integration-process.yaml
.github/workflows/ci-integration-schema.yaml
.github/workflows/ci-integration-sql.yaml
.github/workflows/ci-integration-standalone.yaml
.github/workflows/ci-integration-thread.yaml
.github/workflows/ci-integration-tiered-filesystem.yaml
.github/workflows/ci-integration-tiered-jcloud.yaml
.github/workflows/ci-license.yaml
.github/workflows/ci-unit-adaptors.yml
.github/workflows/ci-unit-broker-sasl.yml
.github/workflows/ci-unit-broker.yml
.github/workflows/ci-unit-flaky.yaml
.github/workflows/ci-unit-proxy.yaml
.github/workflows/ci-unit.yaml

*Motivation*
ASF Infra provides `.asf.yaml` to control features for a given GitHub repo
https://cwiki.apache.org/confluence/display/INFRA/.asf.yaml+features+for+git+repositories

Add .asf.yaml for configuring the github project

---

.github/workflows/ci-cpp.yaml
.github/workflows/ci-go-functions-style.yaml
.github/workflows/ci-go-functions-test.yaml
.github/workflows/ci-integration-backwards-compatibility.yaml
.github/workflows/ci-integration-cli.yaml
.github/workflows/ci-integration-function-state.yaml
.github/workflows/ci-integration-messaging.yaml
.github/workflows/ci-integration-process.yaml
.github/workflows/ci-integration-schema.yaml
.github/workflows/ci-integration-sql.yaml
.github/workflows/ci-integration-standalone.yaml
.github/workflows/ci-integration-thread.yaml
.github/workflows/ci-integration-tiered-filesystem.yaml
.github/workflows/ci-integration-tiered-jcloud.yaml
.github/workflows/ci-license.yaml
.github/workflows/ci-unit-adaptors.yml
.github/workflows/ci-unit-broker-sasl.yml
.github/workflows/ci-unit-broker.yml
.github/workflows/ci-unit-flaky.yaml
.github/workflows/ci-unit-proxy.yaml
.github/workflows/ci-unit.yaml

*Motivation*
Remove any personal hosted github actions

Switch to use github actions hosted under pulsar-test-infra

---

.asf.yaml
.github/workflows/ci-license.yaml

*Motivation*
Fix the license check errors.

Fix license header and always run license check

---

site2/docs/concepts-messaging.md

Fix https://github.com/apache/pulsar/issues/6177

[Doc] Fix issue 6177 - Correct explanation for routing mode

---

site2/website/languages.js

add code base code.
Thank you for allowing me to write Korean codebase.
{
enabled: true, 
name: '한국어', 
tag: 'ko-KR'},
Fixes #<xyz>
*(or)*
*(or)*
*(example:)* …

add Korean code base.

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java

The test was asserting on the value of the semaphore, when this value
depended on how quickly the broker responds.
I fixed this by making the producers channel unreadable before sending
the messages. Even if the broker responds, the client won't see the
response until the channel is made readable again, so we can reliably
check the value of the semaphore.
For testEnsureNotBlockOnPendingQueue, I switched it to throw on full
rather than block on full because whether something is blocking is
hard to assert for in a test.
Finally, there was a bug in testEnsureNotBlockOnPendingQueue where
waitForAll() was called but nothing was done with the returned
future. This is a really badly named utility, as the name implies that
the method itself does the waiting. It should be renamed.

Fix flakiness in ProducerSemaphoreTest

---

site2/docs/functions-debug.md

Fix https://github.com/apache/pulsar/issues/6242

[Fix doc issue 6242] Add a tip about testng in function debug

---

site2/docs/io-connectors.md
site2/docs/io-debezium-source.md

Fixes #6111 
Add Debezium Mongodb for io-connectors .

[Issue 6111][Doc] Add documentation for Debezium Mongodb connector

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

To avoid get partition metadata while the topic name is a partition name.
Currently, if users want to skip all messages for a partitioned topic or unload a partitioned topic, the broker will call get topic metadata many times. For a topic with the partition name, it is not necessary to call get partitioned topic metadata again.

Avoid getting partition metadata while the topic name is a partition name.

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerOfflineBacklog.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/CallbackMutex.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BaseResource.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/Policies.java
pulsar-common/src/main/java/org/apache/pulsar/common/sasl/KerberosName.java

Four kinds of errors are fixed in this PR:
- Array index out of bounds
- Inconsistent equals and hashCode
- Missing format argument
- Reference equality test of boxed types
According to https://lgtm.com/projects/g/apache/pulsar/alerts/?mode=tree&severity=error&id=&lang=java

[Minor] Fix java code errors reported by lgtm.

---

pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZkIsolatedBookieEnsemblePlacementPolicy.java

Fixes #6343
Add a method to cast object value to `String`.

[Issue 6343] Fix broker to specify a list of bookie groups

---

site2/docs/io-rabbitmq-source.md

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

removed comma from yaml config

---

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/BatchReceivePolicy.java

BatchReceivePolicy implements Serializable.

BatchReceivePolicy implements Serializable.

---

pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZookeeperBkClientFactoryImpl.java

[#6228][pulsar-zookeeper-utils] Close ZK before canceling future with exception

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java

When starting Pulsar in standalone mode with TLS enabled, it will fail to create two namespaces during start. 
This is because it's using the unencrypted URL/port while constructing the PulsarAdmin client.

[Broker] Create namespace failed when TLS is enabled in PulsarStandalone

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/CmdFunctionsTest.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/utils/IOUtilsTest.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolTest.java

The main modification was the reduction of repeated initialization of the variables in the tests.

Refactor tests in pulsar client tools test

---

site2/docs/reference-metrics.md

Motivation is to have correct reference-metrics documentation.
There is an error in the `Topic metrics` section
`pulsar_producers_count` => `pulsar_in_messages_total`
Ref:
> https://github.com/apache/pulsar/pull/5802/files
- Dependencies (does it add or upgrade a dependency): (yes / `no`)
- The public API: (yes / `no`)
- The schema: (yes / `no` / don't know)
- The default values of configurations: (yes / `no`)
- The wire protocol: (yes / `no`)
- The rest endpoints: (yes / `no`)
- The admin cli options: (yes / `no`)
- …

[docs]: fix wrong metric name in `Topic metrics`

---

tiered-storage/pom.xml

This PR is a follow-up of #6494

[Minor]Remove unused property from pom

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java

Fixes #<xyz>
Log more information in the refresh authentication credentials path.
*(or)*
*(or)*
*(example:)* …

Add more logging during refresh credentials path

---

deployment/kubernetes/generic/k8s-1-9-and-above/bookie.yaml
deployment/kubernetes/generic/original/bookie.yaml
deployment/kubernetes/generic/original/broker.yaml
deployment/kubernetes/generic/original/monitoring.yaml
deployment/kubernetes/generic/original/proxy.yaml
deployment/kubernetes/generic/original/zookeeper.yaml
docker/pulsar/scripts/apply-config-from-env.py

Fixes #6507 
deploy fail from k8s
fix apiVersion config on ``deployment/kubernetes/generic/origin/*.yaml``
fix update conf from ``apply-config-from-env.py`` for env
*(or)*
*(or)* …

[Issue 6507][deployment]fix k8s config and env py

---

pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java

Fixes #<xyz>
If the exception is unretriable, fail immediately.
*(or)*
*(or)*
*(example:)*
- …

Do not retry unretriable errors

---

pulsar-broker/src/test/java/org/apache/pulsar/websocket/proxy/ProxyPublishConsumeTest.java
pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClientException.java

Fixes #<xyz>
Producer and Consumer Busy exceptions need not be retried within the client.
*(or)*
*(or)*
*(example:)*
*If `yes` was chosen, please …

ProducerBusy and ConsumerBusy exceptions are unretriable ones

---

docker/pulsar-standalone/Dockerfile

After making this https://github.com/apache/pulsar/pull/5334/files update, the package installation sequence also needs to be updated.
* Update the package installation order
local mvn package success

[docker]Docker standalone build error

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java

The main thread wait on `isClosedCondition` but never gets notified.

[Broker]Signal main thread after close

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/LedgerOffloaderFactory.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedCursor.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerConfig.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerFactory.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryCacheManager.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorContainer.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerOfflineBacklog.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/PositionImplRecyclable.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ReadOnlyCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ReadOnlyManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/offload/OffloadUtils.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java

- unresolved reference in JavaDoc
- unnecessary qualifiers for interfaces
- simple lambda can be replaced with method reference
- missing override annotation

Cleanup managed-ledger module

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicsConsumerImplTest.java

Improve the message TTL test to ensure messages do not expired early.
Improve tests.
This change is the unit test improve

Improve the message TTL test to ensure messages do not expired early.

---

site2/website/data/users.js

some of the powered-by logos are broken. this pr fix ottoo, streamnative, navar

[website]: Fix powered-by -- ottoo, streamnative, navar

---

deployment/kubernetes/helm/pulsar/templates/broker-configmap.yaml

Fixes #6663
Being able to use the Helm chart.
Fixes the helm chart.
However, the CI should run `helm lint` to prevent future issues like this (I can handle that in another PR if you're interested in such checks).

Fix an error in the Helm chart

---

.github/workflows/ci-deployment-helm.yaml

Prevent issues such as #6663 by checking the validity of the Helm chart in the CI.
Add a GitHub Actions workflow checking the chart.
- *run `helm lint`*

[Issue 6663][helm] Lint the Helm chart in the CI

---

site2/docs/deploy-bare-metal.md

There were some sentences that sounded strange and some grammatical mistakes that affected readability. I have made changes to improve the ease of reading the text.
Fixes #<xyz>
*(or)*
*(or)* …

Changes to improve readability

---

site2/docs/concepts-overview.md

added missing "of" to concepts-overview.md

---

conf/bkenv.sh
conf/pulsar_env.sh
deployment/kubernetes/aws/bookkeeper.yaml
deployment/kubernetes/aws/broker.yaml
deployment/kubernetes/aws/zookeeper.yaml
deployment/kubernetes/helm/pulsar/values-mini.yaml
deployment/kubernetes/helm/pulsar/values.yaml
deployment/terraform-ansible/templates/pulsar_env.sh

*Motivation*
-XX:+AggressiveOpts is deprecated in JDK11
Related PR: #6575

Remove deprecated -XX:+AggressiveOpts

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceAutoTopicCreationTest.java

*Motivation*
I cherry-picked the fix of #6685 into branch-2.5. But the cherry-pick missing one class import.
The pull request fixed the cherry-pick error.

Fix cherry-pick error

---

README.md

*Motivation*
Currently we manage multiple different repositories for different components and clients.
We should update README to reflect the current state.

Update README.md about the repositories managed by Pulsar PMC

---

site2/website/languages.js

Fixes #6342
*Motivation*
Fix duplicated entry in the languages.js

Issue 6342: Korean documentation is not built to the website

---

site2/website/data/users.js

Fix StreamNative logo in powered by page.
After change, it would be like:

Fix StreamNative logo in powered by page

---

.ci/chart_test.sh
.ci/clusters/values-bk-tls.yaml
.ci/clusters/values-broker-tls.yaml
.ci/clusters/values-function.yaml
.ci/clusters/values-jwt-asymmetric.yaml
.ci/clusters/values-jwt-symmetric.yaml
.ci/clusters/values-local-pv.yaml
.ci/clusters/values-pulsar-image.yaml
.ci/clusters/values-tls.yaml
.ci/clusters/values-zk-tls.yaml
.ci/clusters/values-zkbk-tls.yaml
.ci/helm.sh
.ci/lint.sh
.ci/release.sh
deployment/kubernetes/helm/pulsar/templates/_autorecovery.tpl
deployment/kubernetes/helm/pulsar/templates/_bookkeeper.tpl
deployment/kubernetes/helm/pulsar/templates/_broker.tpl
deployment/kubernetes/helm/pulsar/templates/_toolset.tpl
deployment/kubernetes/helm/pulsar/templates/proxy-statefulset.yaml
deployment/kubernetes/helm/pulsar/templates/tls-cert-internal-issuer.yaml
deployment/kubernetes/helm/pulsar/templates/tls-certs-internal.yaml
deployment/kubernetes/helm/pulsar/templates/toolset-statefulset.yaml
deployment/kubernetes/helm/pulsar/templates/zookeeper-statefulset.yaml

---
*Motivation*
Make the secret name consistent. And all secret names should
use the release name as the prefix.

Make secret name consistent

---

site2/docs/client-libraries-cgo.md
site2/docs/client-libraries-go.md

- Update native go client docs for Pulsar

[Docs] Update native go client docs for Pulsar

---

CONTRIBUTING.md

It is a common practice to have the CONTRIBUTING.md file with info on how to start contributing to the project.
CONTRIBUTING.md was added to the project with the link to the official Apache Pulsar page.

Add contributing info

---

pulsar-function-go/examples/go.mod
pulsar-function-go/examples/go.sum
pulsar-function-go/go.mod
pulsar-function-go/go.sum

Fixes: #6653
- Update Go client version to 0.1.0

[Go Function]Update Go client version to 0.1.0

---

site2/website/static/swagger/2.5.1/swagger.json
site2/website/static/swagger/2.5.1/swaggerfunctions.json
site2/website/static/swagger/2.5.1/swaggersink.json
site2/website/static/swagger/2.5.1/swaggersource.json

Apache release 2.5.1 add swaggers JSON file
* Apache release 2.5.1 add swaggers JSON file
Local test

[website]Add 2.5.1 swagger json file

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java

Fixes #<xyz>
Make the FunctionRunTimeManager methods used by rest-api syncrhonized since the assignment tailer also is updating it. This fixes the flakiness in PulsarFunctionE2ESecurityTest
*(or)*
*(or)*
*(example:)* …

Fix flakiness in PulsarFunctionE2ESecurityTest

---

pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactedTopicTest.java

Add topic compaction test for the empty message.
Added unit test.
- The rest endpoints: ( no)

Add topic compaction test for the empty message.

---

site2/tools/build-site.sh

* Fixed website publish failed
* Fixed website publish failed

[website]Fixed website publish failed

---

site2/tools/build-site.sh

* Add support for ko language build
* Fixed website build failed due to ko language
Local test pass

[hotfix]Website publish failed for ko language

---

site2/docs/concepts-architecture-overview.md

Added zookeeper role
I was going through the docs and the information given was not complete.
I have completed a sentence regarding zookeeper role in a Pulsar instance.

[docs] Update concepts-architecture-overview.md

---

pulsar-common/src/main/java/org/apache/pulsar/common/util/SearchBcNarUtils.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/SecurityUtility.java

change log level to debug to avoid annoying.

change log level to debug for bouncy castle load

---

site2/docs/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.5.0/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.5.1/reference-pulsar-admin.md

cli commands introduced in https://github.com/apache/pulsar/pull/3986 are not documented. Adding documentation for the same.

[Docs] Document cli commands for publish rate feature

---

site2/docs/helm-deploy.md

Path fix for changing directory after cloned from github

[docs]path fix for changing directory

---

site2/docs/sql-deployment-configurations.md

related to #3828 #4976 #5822 #6884 
Add a note for bookkeeper explicit LAC
Update Pulsar SQL configuration documentation.

Add a note for bookkeeper explicit LAC

---

site2/website/data/users.js

add bigo into poweredby page
https://www.bigo.sg/

add bigo into poweredby page

---

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SourceConfigUtils.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/FunctionConfigUtilsTest.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SinkConfigUtilsTest.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SourceConfigUtilsTest.java

Fix typos in exceptions related to functions. The tests were updated as well.

[functions] Fix typos in exceptions related to functions

---

conf/client.conf
site2/docs/security-tls-keystore.md
site2/website/sidebars.json

related with #6853
add keystore tls config doc

add keystore tls config doc

---

site2/docs/cookbooks-tiered-storage.md

Fix docs of gcs offload

---

site2/docs/helm-deploy.md

Without this I got `Error: invalid argument "600" for "--timeout" flag: time: missing unit in duration 600`.

[docs] Fix helm timeout argument

---

site2/website/languages.js

Referring to messages with Sijie Guo (Crowdin):
Add Polish in Crowdin for translations
@sijie

[docs] Add Polish

---

pulsar-functions/localrun/pom.xml
pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java

Fixes #<xyz>
Remove unused import and therefore unnecessary dependency for LocalRunner
*(or)*
*(or)*
*(example:)*
*If `yes` was chosen, please highlight …

Remove unneeded dependency

---

site2/website/versioned_docs/version-2.4.0/client-libraries-go.md

Fix 2.4.0 missing docs of cgo client

Fix 2.4.0 missing docs of cgo client

---

pulsar-common/src/main/java/org/apache/pulsar/common/validator/ConfigValidation.java
pulsar-common/src/main/java/org/apache/pulsar/common/validator/ConfigValidationAnnotations.java
pulsar-common/src/main/java/org/apache/pulsar/common/validator/ConfigValidationUtils.java
pulsar-common/src/main/java/org/apache/pulsar/common/validator/Validator.java
pulsar-common/src/main/java/org/apache/pulsar/common/validator/ValidatorImpls.java
pulsar-common/src/main/java/org/apache/pulsar/common/validator/package-info.java
pulsar-common/src/test/java/org/apache/pulsar/common/validator/ConfigValidationTest.java
pulsar-common/src/test/java/org/apache/pulsar/common/validator/ValidatorImplsTest.java

Fixes #<xyz>
This pr adds annotations that config classes can use to do member validation. This will be useful for things like source/sink/function submission to check if supplied config is in order before starting the actual source/sink/function
*(or)*
*(or)*
*(example:)*
- *Added integration …

Add Annotations for config validation checking

---

pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java
pulsar-io/common/src/test/java/org/apache/pulsar/io/common/IOConfigUtilsTest.java
pulsar-io/core/src/main/java/org/apache/pulsar/io/core/SourceContext.java
pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/source/KafkaAbstractSourceTest.java

Fixes #<xyz>
Currently function and source context give their writers an ability to create publishers but not consumers. This mr fixes that.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after …

Added ability to build consumers in functions and sources

---

site2/website/versioned_docs/version-2.2.0/developing-load-manager.md

added "broker" in the shell command for updating loadManagerClassName
No issue
Resolves an issue in the load-manager docs
- added "broker" in the shell command for updating loadManagerClassName so that it works.
- Dependencies (does it add or upgrade a dependency):  no
- Does this pull request introduce a new feature? No
- If a …

resolve an issue in the developing-load-manager doc

---

deployment/kubernetes/helm/scripts/pulsar/cleanup_helm_release.sh
deployment/kubernetes/helm/scripts/pulsar/prepare_helm_release.sh

The script `prepare_helm_release.sh` was creating a asymmetric key unless I pass `--symmetric` as last parameter of the command line.
It turns out that the variable is set to false in every step of the parameter parsing loop.
Moved variable assignment outside of the loop.
But is verifiable through the output of the script execution. Passing the parameter `--symmetric` in any order, the output should be:
```
The jwt token secret keys are generated under:
- '${release}-token-symmetric-key'
```
Instead of:
```
The jwt token secret keys are generated under:
- '${release}-token-asymmetric-key'
``` …

[scripts] Variables not properly set in prepare and cleanup scripts

---

site2/docs/io-use.md
site2/website/versioned_docs/version-2.4.2/io-use.md
site2/website/versioned_docs/version-2.5.0/io-use.md

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Update the link for reload in sink and source sections of Use section for PR https://github.com/apache/pulsar/issues/6108

---

site2/website/release-notes.md

[release] [doc] add release notes for 2.5.2

---

site2/website/static/swagger/2.5.2/swagger.json
site2/website/static/swagger/2.5.2/swaggerfunctions.json
site2/website/static/swagger/2.5.2/swaggersink.json
site2/website/static/swagger/2.5.2/swaggersource.json

build swagger files from branch-2.5

[2.5.2 release] add swagger files for release 2.5.2

---

site2/website/sidebars.json

[doc] [website] fix syntax error

---

site2/website/blog/2020-05-19-Apache-Pulsar-2-5-2.md

[website] [release] add blog for 2.5.2 release

---

.github/workflows/ci-integration-tiered-filesystem.yaml
.github/workflows/ci-integration-tiered-jcloud.yaml
pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-io/rabbitmq/src/main/java/org/apache/pulsar/io/rabbitmq/RabbitMQAbstractConfig.java
pulsar-io/rabbitmq/src/main/java/org/apache/pulsar/io/rabbitmq/RabbitMQSink.java
pulsar-io/rabbitmq/src/main/java/org/apache/pulsar/io/rabbitmq/RabbitMQSinkConfig.java

Fix break changes in namespace offload policy and RabbitMQ sink.

Fix break changes in namespace offload policy and RabbitMQ sink.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SinksBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SourcesBase.java

Fixes #<xyz>
This pr fixes swagger annotations for builtin sources and sinks commands
*(or)*
*(or)*
*(example:)*
*If `yes` was chosen, please highlight …

Fix swagger annotations for builtin sources/sinks rest api

---

site2/docs/reference-metrics.md

Fixes #6896
- Add pulsar proxy metrics

Add pulsar proxy metrics

---

site2/docs/reference-metrics.md

Fixes #6898 
- Add the pulsar functions metrics

Add the pulsar functions metrics

---

conf/presto/catalog/pulsar.properties
pulsar-sql/presto-pulsar/src/main/java/org/apache/pulsar/sql/presto/PulsarConnectorMetricsTracker.java
site2/docs/reference-metrics.md

Fixes #6897 
- Add pulsar SQL woker metrics to repo

Add pulsar SQL woker metrics to repo

---

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java

Add test time for perf consumer and perf reader

Add test time for perf consumer and perf reader

---

site2/docs/reference-configuration.md

Update the broker configuration file in the Reference > Pulsar configuration for the issue apache/pulsar#6087
Fixes #<xyz>
*(or)*
*(or)*
*(example:)* …

Update the doc for deleting inactive topic when subscriptions caught up

---

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionPublishTest.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerUtils.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java

Clean function files stored in BK when function is terminated / de-registered

Remove function files stored in BK when function is de-registered

---

.github/workflows/ci-unit-broker.yml
.github/workflows/ci-unit-flaky.yaml
pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionE2ESecurityTest.java

Fixes #<xyz>
Since we don't wait for stop/restart to actually 'complete' serverside, our delete request could get out of date when it reaches the server side. Thus retry it if we get a PulsarAdminException.
*(or)*
*(or)*
*(example:)* …

Fix the flaky function test.

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/IncrementPartitionsTest.java

The underlying issue was already fixed in master, though currently there is no test to validate that we can increase partitions on a topic without subscriptions.

Added test for updating partitioned topic without subscriptions

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java

Change autoTopicCreateOverride/autoSubscriptionOverride log level to debug.
- Dependencies (does it add or upgrade a dependency): (`no)
- Does this pull request introduce a new feature? (no)`

Change autoTopicCreateOverride/autoSubscriptionOverride log level to debug.

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/MessageDispatchThrottlingTest.java

There was a race in testRelativeMessageRateLimitingThrottling where
the test was sending and receiving a message to warmup the broker, and
then testing whether messages could get through with a 1/s dispatch
rate but a high produce rate.
The race triggered when the initial warmup message triggered a backoff
because the initial warmup receive already used up the 1/s permit
quota. This happened because when the dispatcher has read messages
from the managed ledger, it will call #readMoreEntries. If this call
to readMoreEntries occurs before the test starts publishing the
backoff is hit.
The solution is to change to way we validate the functionallity at the
end of the test. The test really wants to verify that if there are a
lot of messages being produced we can keep up. We should only hit the …

Fix race in MessageDispatchThrottlingTest

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java

Add current time into topic name for ReplicatorTest to avoid flaky

[flaky test] add current time into topic name for ReplicatorTest

---

pulsar-client-cpp/tests/BasicEndToEndTest.cc

The topics used in a bunch of the cases in `BasicEndToEndTest` had no
unique identifier, so if you ran it multiple times against the same
standalone cluster, they would fail, as the topics would already have
some state.
This change adds the unique identifier to the topics.

Allow BasicEndToEndTest to run multiple times locally

---

pulsar-client-cpp/python/pulsar/schema/definition.py
pulsar-client-cpp/python/schema_test.py

In Python client, we're not validating the type of the values set on the records when using schema.
This means that, through a simple mistake, an application can end up publishing data that is not compatible with the declared schema.

[Python] Enforce type of values set on record field

---

docker/pulsar-standalone/Dockerfile

Fixes https://github.com/apache/pulsar/issues/7084,  add postgresql to supervisord for pulsar-standalone image.
postgresql did't start when running a container.

add postgresql to supervisord for pulsar-standalone image

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java
pulsar-client-admin/src/main/resources/org/asynchttpclient/config/ahc-default.properties
pulsar-client-tools-test/pom.xml
pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpClient.java
pulsar-client/src/main/resources/ahc.properties
pulsar-sql/presto-distribution/LICENSE

update asynchttpclient verison to avoid security issue.
Some of the method (keepAlive) changed in the new version, so this PR also brings in some code changes.

update asynchttpclient verison

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java

OpenAPI was missing info about body params for namespaces admin API.
Added attributes for the body params in the API for namespaces.

[pulsar-broker] Extend OpenAPI for namespaces with body params

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/ResourceQuotas.java

Swagger annotations were added to the resource quotas APS to improve the description

[pulsar-broker] Extend REST API for resource quotas with swagger annotations

---

site2/docs/reference-configuration.md

Update the reference > pulsar configuration > broker config section:
- Add a maxMessageSize configure item.
This update is for the master currently. once it is reviewed and approved, it will be added to previous releases (until 2.4.0).
Fixes #<xyz>
*(or)* …

[Doc]--Update for the maximum message size

---

site2/docs/client-libraries-cgo.md
site2/docs/client-libraries-cpp.md

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

[Doc]--Add schema config to cpp and cgo client docs

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java
site2/docs/deploy-aws.md
site2/docs/security-athenz.md
site2/docs/security-extending.md
site2/docs/security-jwt.md
site2/docs/security-tls-authentication.md
site2/docs/security-tls-transport.md
site2/website/versioned_docs/version-2.4.0/security-jwt.md
site2/website/versioned_docs/version-2.4.1/security-athenz.md
site2/website/versioned_docs/version-2.4.1/security-tls-authentication.md
site2/website/versioned_docs/version-2.4.1/security-tls-transport.md
site2/website/versioned_docs/version-2.4.1/security-token-client.md
site2/website/versioned_docs/version-2.4.2/security-athenz.md
site2/website/versioned_docs/version-2.4.2/security-tls-authentication.md
site2/website/versioned_docs/version-2.4.2/security-tls-transport.md
site2/website/versioned_docs/version-2.4.2/security-token-client.md
site2/website/versioned_docs/version-2.5.0/deploy-aws.md
site2/website/versioned_docs/version-2.5.0/security-extending.md
site2/website/versioned_docs/version-2.5.0/security-tls-authentication.md
site2/website/versioned_docs/version-2.5.0/security-tls-transport.md
site2/website/versioned_docs/version-2.5.1/security-jwt.md
site2/website/versioned_docs/version-2.5.1/security-tls-authentication.md
site2/website/versioned_docs/version-2.5.1/security-tls-transport.md
site2/website/versioned_docs/version-2.5.2/security-jwt.md
site2/website/versioned_docs/version-2.5.2/security-tls-authentication.md
site2/website/versioned_docs/version-2.5.2/security-tls-transport.md

fix typo: follwing => following

[docs] fix typo follwing

---

site2/website/versioned_docs/version-2.4.0/concepts-messaging.md
site2/website/versioned_docs/version-2.4.1/concepts-messaging.md
site2/website/versioned_docs/version-2.4.2/concepts-messaging.md
site2/website/versioned_docs/version-2.5.0/concepts-messaging.md
site2/website/versioned_docs/version-2.5.1/concepts-messaging.md
site2/website/versioned_docs/version-2.5.2/concepts-messaging.md

These doc updates is for the PR: https://github.com/apache/pulsar/pull/2954
Docs for master is updated and merged.
Update the following releases based on the master updates:
2.5.2, 2.5.1, 2.5.0, 2.4.2, 2.4.1, 2.4.0
Fixes #<xyz>
*(or)*
*(or)*
This …

[Doc]--Update for support consumer priority level in failover mode

---

site2/website/static/js/custom.js
site2/website/static/js/getSwaggerByVersion.js

Rest API version selection error -> http://pulsar.apache.org/admin-rest-api/?version=2.5.2
* Fixed route path
* Fixed URL 
* Add API version
Local test pass

[hotfix]Fixed website rest api select version error

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedCursor.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PublishRateLimiter.java
pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStore.java

1. Simplify the `update` method of `PublishRateLimitImpl` by removing duplicated code
2. add import for java doc 
3. fix some typos

refact duplicated code

---

site2/docs/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.5.0/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.5.1/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.5.2/reference-pulsar-admin.md

Fixes #6598 
Updated the link to the page containing information about CLI commands for sources and sinks

[Issue 6598][docs] Fix the links to the docs about sinks and sources CLI

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

Fix #7189
1. change the `WebApplicationException` log level from error to debug

change topic lookup redirect log level

---

site2/website/data/users.js

Kingsoft Cloud agrees to add its logo to the "Powered By" page. 
Thanks @codelipenghui for providing this info.

Add Kingsoft Cloud to the Powered By page

---

site2/docs/reference-configuration.md

The [PR](https://github.com/apache/pulsar/pull/7078) introduce precise topic publish rate limiting on broker. But the doc is not updated accordingly.
Update the Pulsar doc: Reference > Pulsar configuration > broker

[Doc]--Update doc for precise topic publish rate limiting on Broker

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java

Fixes #<xyz>
All admin apis should be gated by a super user admin check.
*(or)*
*(or)*
*(example:)* …

Ensure that admin operations are gated by super user check

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/NonPersistentTopicE2ETest.java
site2/docs/client-libraries-java.md

Fixes #7205
Add tests and documentation for subscribing to non-persistent with topic pattern

Add tests and documentation for subscribing to non-persistent with topic pattern

---

site2/docs/reference-configuration.md

Add two missing listeners configurations

Add advertised multiple listeners configurations

---

site2/docs/administration-zk-bk.md

While discussing issue https://github.com/apache/pulsar/issues/7055#issuecomment-641038722 yesterday, @sijie suggested I add the documentation for decommissioning bookies to the Pulsar docs.
While adding the documentation for decommissioning, I also saw the BookKeeper sub sections didn't read well. There were duplicate sections for configuration as well.
So just rearranged them in a way that it would be relevant for work flow as well as added the decommissioning process details.
Rearranged the sections as:
- Hardware considerations
- Configure BookKeeper
- Deploy BookKeeper
- Starting bookies manually
- Decommissioning bookies cleanly
Did a `yarn build` and checked out the changes locally.
- Dependencies (does it add or upgrade a …

[Doc] [BookKeeper] Rearrange and remove redundent sections, add decommissioning procedure.

---

site2/website/release-notes.md

Add 2.6.0 Release note.

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MessageIdTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/RoundRobinPartitionMessageRouterImplTest.java
pulsar-io/redis/src/main/java/org/apache/pulsar/io/redis/RedisAbstractConfig.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
tiered-storage/jcloud/src/test/java/org/apache/bookkeeper/mledger/offload/jcloud/impl/OffloadIndexTest.java

Minor: fix `;` typo in config.

[pulsar-server] minor: fix typo in service-config

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java

Fix permission operation check on setRetention admin operation

---

pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenz.java
pulsar-client-auth-athenz/src/test/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenzTest.java

The authentication plugin for Athenz allows users to change the name of the HTTP header for sending an authentication token to a broker server with a parameter named `roleHeader`.
`AuthenticationAthenz` sets the value of `roleHeader` to the system property `athenz.auth.role.header`.
https://github.com/apache/pulsar/blob/12a5001cbbb205ba7811317eeb02f40912e45b56/pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenz.java#L151-L153
The Athenz class `ZTSClient` gets the header name from the system property and sets it in a static field. If no value is set in the system property, the default value is "Athenz-Role-Auth".
https://github.com/yahoo/athenz/blob/62350364e0b3ffecbca13d5c74a5d5d4c7b0df01/clients/java/zts/core/src/main/java/com/yahoo/athenz/zts/Z …

[client] Fix issue where HTTP header used in Athenz authentication can not be renamed

---

site2/docs/reference-metrics.md

1.  Broken links.
2. Incorrect headings.
Fix the link and incorrect heading issues.

[doc] Refine link and heading issues in Pulsar metrics

---

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java

Fixes #<xyz>
Since we use negative ack for managing failures in functions, we need to set its value as well in source spec
*(or)*
*(or)*
*(example:)* …

Set source spec's negativeacktimeout as well as timeout

---

site2/website/versioned_docs/version-2.6.0/io-use.md

```
Error: No 'original_id' field found in /pulsar/site2/website/versioned_docs/version-2.6.0/io-use.md. Perhaps you forgot to add it when importing prior versions of your docs?
at forEach (/pulsar/site2/website/node_modules/docusaurus/lib/server/versionFallback.js:64:11)
at Array.forEach (<anonymous>)
at Object.<anonymous> (/pulsar/site2/website/node_modules/docusaurus/lib/server/versionFallback.js:52:7)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Module._compile (/pulsar/site2/website/node_modules/pirates/lib/index.js:99:24)
at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Object.newLoader [as .js] (/pulsar/site2/website/node_modules/pirates/lib/index.js:104:7)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad …
```

[hotfix]Fixed io-use docs metadata error

---

site2/docs/administration-pulsar-manager.md

The current pulsar-manager v0.1.0 docker image does not support authentication. Use the latest version of the image
* Fixed document pulsar-manager docker image version

[Docs]Fixed puslar manager document image

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java

Simplify some codes in if statement and return statement

simplify code

---

site2/docs/tiered-storage-aws.md
site2/docs/tiered-storage-filesystem.md
site2/docs/tiered-storage-gcs.md
site2/docs/tiered-storage-overview.md
site2/website/sidebars.json

Currently, the docs for tiered storage is not clear and incomplete.
This PR adds and reorganize contents for tiered storage.
Old structure:
New structure:

Update docs for tiered storage

---

site2/docs/functions-runtime.md
site2/website/versioned_docs/version-2.4.0/functions-runtime.md
site2/website/versioned_docs/version-2.4.1/functions-runtime.md
site2/website/versioned_docs/version-2.4.2/functions-runtime.md
site2/website/versioned_docs/version-2.5.0/functions-runtime.md
site2/website/versioned_docs/version-2.5.1/functions-runtime.md
site2/website/versioned_docs/version-2.5.2/functions-runtime.md

Pulsar release 2.4.0 supports Adding labels to function statefulsets and services. The code is implemented but the doc is not updated accordingly. 
Here is the code update PR: https://github.com/apache/pulsar/pull/4038
Therefore, i make this PR to update docs for releases:
master/2.5.2/2.5.1/2.5.0/2.4.2/2.4.1/2.4.0
Add a note in the doc "Setup: Configure Functions runtime" under the Pulsar Functions section

[Doc]--Add labels to function statefulsets and services

---

site2/website/data/users.js

Fix the issue of Kingsoft logo is not displayed

Update Kingsoft logo

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminResourceTest.java

Fixes #7394 
fix update partitions error for non-persistent topic

fix update partitions error for non-persistent topic

---

site2/docs/security-bouncy-castle.md
site2/website/versioned_docs/version-2.5.1/security-bouncy-castle.md
site2/website/versioned_docs/version-2.5.2/security-bouncy-castle.md
site2/website/versioned_docs/version-2.6.0/security-bouncy-castle.md
site2/website/versioned_docs/version-2.6.1/security-bouncy-castle.md

This is related with fix #7453.
After remove module bc-shaded, we should updated the docs.
update related doc related to remove module bc-shaded.

[doc] fix doc after remove bc-shaded

---

.github/workflows/ci-cpp.yaml
.github/workflows/ci-go-functions-style.yaml
.github/workflows/ci-go-functions-test.yaml
.github/workflows/ci-integration-backwards-compatibility.yaml
.github/workflows/ci-integration-cli.yaml
.github/workflows/ci-integration-function-state.yaml
.github/workflows/ci-integration-messaging.yaml
.github/workflows/ci-integration-process.yaml
.github/workflows/ci-integration-schema.yaml
.github/workflows/ci-integration-sql.yaml
.github/workflows/ci-integration-standalone.yaml
.github/workflows/ci-integration-thread.yaml
.github/workflows/ci-integration-tiered-filesystem.yaml
.github/workflows/ci-integration-tiered-jcloud.yaml
.github/workflows/ci-license.yaml
.github/workflows/ci-unit-adaptors.yml
.github/workflows/ci-unit-broker-broker.yml
.github/workflows/ci-unit-broker-client.yml
.github/workflows/ci-unit-broker-flaky.yml
.github/workflows/ci-unit-broker-long-time.yml
.github/workflows/ci-unit-broker-others.yml
.github/workflows/ci-unit-broker-publish-throttle.yml
.github/workflows/ci-unit-broker-sasl.yml
.github/workflows/ci-unit-broker-transaction.yml
.github/workflows/ci-unit-broker.yml
.github/workflows/ci-unit-flaky.yaml
.github/workflows/ci-unit-proxy.yaml
.github/workflows/ci-unit.yaml

Fixes #5736 
This modification in Github Actions should help to run tests when pushing changes to the release branches
This change should be verified manually

[Issue 5736] Add test checks in branches

---

pulsar-functions/instance/src/test/java/org/apache/pulsar/functions/instance/JavaInstanceTest.java

The async function test is relying on a race condition on when the counter is updated. 
With `pendingQueueSize=2`, the 3rd event is blocked on the queue until the 1st event is processed. That makes 1st and 2nd event to be triggered around the same time and the validation to fail, when we the 2nd event to be already done.
Additionally, there are multiple threads leaked by this test.

Fixed flaky test and resource leak in JavaInstanceTest

---

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SinksImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SourcesImpl.java

Some exceptions are being ignored in Pulsar admin, more especially in Functions, Sources, and Sinks.  We need to bubble up these exceptions so it is easier to debug.

Fix: Exception being ignored in PulsarAdmin

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

Fixes #7512
To change the replication policy dynamically without configuring the replicator-dispatch-rate parameter.
To handle java.util.NoSuchElemetnException.

Fixes #7512 handle exception occurred when the geo-replication policy is updated.

---

pulsar-io/core/src/main/java/org/apache/pulsar/io/core/BatchPushSource.java
site2/website/release-notes.md

Fixes #<xyz>
In some batch connectors, its far easier to have a method to just push a record whenever one becomes available. In those cases, using BatchPushSource interface might be much easier to program with.
*(or)*
*(or)*
*(example:)* …

Add BatchPushSource interface

---

tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarStateTest.java

* Add additional tags to functions and state integration tests.

Add test group tags for functions and state integration tests

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java
pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyForwardAuthDataTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyParserTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyRolesEnforcementTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyWithAuthorizationTest.java

Proxy can have it's advertisedAddress configured like pulsar broker

Add advertisedAddress config field to ProxyConfiguration

---

.github/workflows/ci-cpp.yaml

[ci] Fix typo in ci-cpp.yaml

---

pom.xml

Add additional modules to core modules

Add modules to core modules

---

pulsar-broker/pom.xml

Add a maven profile to skip pulsar-broker tests specifically.

Add maven profile to skip broker unit tests

---

site2/website/versioned_sidebars/version-2.5.0-sidebars.json

ISSUE 7415 fix sidebar v2.5.0

---

examples/flink/pom.xml

Addresses [comment in PR for #5922](https://github.com/apache/pulsar/pull/7548/files#r455897202)

[Issue #5922] fix - remove buildtools dependency in flink pom as its already inherited

---

site2/website/versioned_docs/version-2.1.0-incubating/concepts-architecture-overview.md

Update concepts-architecture-overview.md
The original pr is https://github.com/apache/pulsar/pull/6153. This change aims to fix the conflicts.

Fix conflicts in #6153

---

pom.xml

[Issue #7628][build] - changed root pom to use jetty bom

---

pom.xml

[Issue #7631][build] - Changed root pom to use netty bom

---

.github/ISSUE_TEMPLATE/enhancement_request.md

Added a enhancement issue template for github so that its labelled correctly.

Added an enhancement template for github

---

.github/workflows/ci-go-functions-style.yaml
.github/workflows/ci-go-functions-test.yaml
.github/workflows/ci-integration-backwards-compatibility.yaml
.github/workflows/ci-integration-cli.yaml
.github/workflows/ci-integration-function-state.yaml
.github/workflows/ci-integration-messaging.yaml
.github/workflows/ci-integration-process.yaml
.github/workflows/ci-integration-schema.yaml
.github/workflows/ci-integration-sql.yaml
.github/workflows/ci-integration-standalone.yaml
.github/workflows/ci-integration-thread.yaml
.github/workflows/ci-integration-tiered-filesystem.yaml
.github/workflows/ci-integration-tiered-jcloud.yaml
.github/workflows/ci-license.yaml
.github/workflows/ci-unit-broker-broker-gp1.yaml
.github/workflows/ci-unit-broker-broker-gp2.yaml
.github/workflows/ci-unit-broker-client-api.yaml
.github/workflows/ci-unit-broker-client-impl.yaml
.github/workflows/ci-unit-broker-other.yaml
.github/workflows/ci-unit-proxy.yaml

* Fix doc check to run on workflow and pom only changes
* Add retry to flaky integration tests.

Restore maven cache to github workflows

---

pom.xml
pulsar-functions/pom.xml

* Further reduce core-modules profile list
* Filter project by profile in functions.

Further reduce core-modules profile list

---

pulsar-common/src/main/java/org/apache/pulsar/common/functions/FunctionConfig.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java
pulsar-functions/proto/src/main/proto/Function.proto
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/FunctionConfigUtils.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/FunctionConfigUtilsTest.java

Fixes #<xyz>
Just like retainOrdering, sometimes applications want to retain ordering over the message keys. This pr adds support to that.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for recovery after …

Allow ability to specify retain key ordering in functions

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/validator/MultipleListenerValidator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java

Fixes #7618
Correct `BrokerServiceUrlTls` when `tls` is not enabled.

[Issue 7618] Fix NPE when using advertisedListeners

---

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java

Fix #7437，shutdown AsyncHttpConnector.delayer

---

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntimeFactory.java

Fixes #<xyz>
Substantial pre-processing(like uncompressing data) happens in the ioThreads. Thus we need to use available cores for their processing.
*(or)*
*(or)*
*(example:)*
- *Extended integration test for …

Use available cores for io thread processing

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java

Fixes #7693 
When trying to chase down a bug in my custom `AuthenticationProvider` I found that when attempting to consume a topic that I wasn't authorized on would fail to produce an unauthorized response while using the `pulsar-client`. I noticed that the `canConsumeAsync` within `AuthorizationService` `canLookUpAsync` doesn't pass along the `AuthenticationDataSource` when it should. My code relied on that to be passed down each time and thus my methods would never return.
I've added the `AuthenticationDataSource` to the `canConsumeAsync` method.
- The wire protocol: …

[Issue #7693][AuthorizationService] add missing AuthenticationDataSource to canConsumeAsync method call

---

pulsar-io/batch/src/main/java/org/apache/pulsar/io/batch/BatchSourceExecutor.java

Fixes #<xyz>
This will avoid discover being called before open
*(or)*
*(or)*
*(example:)*
- …

Call open before discover. 

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java

Close the previous reader of the health check topic. Not sure what caused the reader to not close properly, this PR tries to delete the previous reader of the health check to make sure the previous readers can be closed.
If the previous reader can't be closed, the backlog of the health check topic will keep increasing. According to the broker heap dump, there is more than one reader can't be closed.
This PR is related to #7589
The problem is hard to reproduce.
- Does this …

Close the previous reader of the health check topic

---

site2/website/pages/en/events.js

The Events page is not updated.
Update Pulsar related events.

Update Pulsar related events

---

site2/docs/functions-worker.md

Update the functions worker doc.
Typos are updated and some sentences are modified.

Fix functions-worker typos

---

site2/docs/io-cli.md

Fixes #5157
The description for source and sink `--processing-guarantees` is not clear.
Update related description for it.

[Issue 5157][docs] Update source and sink --processing-guarantees description 

---

site2/website/versioned_docs/version-2.1.0-incubating/io-quickstart.md
site2/website/versioned_docs/version-2.1.1-incubating/io-managing.md
site2/website/versioned_docs/version-2.1.1-incubating/io-quickstart.md
site2/website/versioned_docs/version-2.2.0/io-managing.md
site2/website/versioned_docs/version-2.2.0/io-quickstart.md
site2/website/versioned_docs/version-2.2.0/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.2.1/io-managing.md
site2/website/versioned_docs/version-2.2.1/io-quickstart.md
site2/website/versioned_docs/version-2.2.1/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.3.0/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.3.1/io-quickstart.md
site2/website/versioned_docs/version-2.3.2/io-quickstart.md
site2/website/versioned_docs/version-2.3.2/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.4.0/io-managing.md
site2/website/versioned_docs/version-2.4.0/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.4.1/io-managing.md
site2/website/versioned_docs/version-2.4.1/io-quickstart.md
site2/website/versioned_docs/version-2.4.1/reference-connector-admin.md
site2/website/versioned_docs/version-2.4.2/io-managing.md
site2/website/versioned_docs/version-2.4.2/io-quickstart.md
site2/website/versioned_docs/version-2.4.2/reference-connector-admin.md
site2/website/versioned_docs/version-2.5.0/io-cli.md
site2/website/versioned_docs/version-2.5.0/io-quickstart.md
site2/website/versioned_docs/version-2.5.1/io-cli.md
site2/website/versioned_docs/version-2.5.1/io-quickstart.md
site2/website/versioned_docs/version-2.5.2/io-cli.md
site2/website/versioned_docs/version-2.5.2/io-quickstart.md
site2/website/versioned_docs/version-2.6.0/io-quickstart.md
site2/website/versioned_docs/version-2.6.1/io-cli.md
site2/website/versioned_docs/version-2.6.1/io-quickstart.md

In #7699, i update doc for the master only. The contents are approved and merged.
This PR is for updating docs for releases 2.6.1 --2.1.0
Update the following docs:
Pulsar IO > get started
Connector Admin CLI

[Doc] Add a note about sink-type and source-type value of the built-in connector.

---

site2/docs/admin-api-partitioned-topics.md

This PR fixes admin-api-partitioned-topics page grammatical errors.

Fix admin-api-partitioned-topics page grammatical errors

---

site2/docs/admin-api-namespaces.md

This PR fixes admin-api-namespaces page grammatical errors.

Fix admin-api-namespaces page grammatical errors

---

site2/website/data/resources.js
site2/website/pages/en/contact.js

Motivation:
The resource page is out of date.
Modification:
1. The tech blog of the same series are put next to each other.
2. The shared slides are updated.
3. The Bot WeChat ID is added on contact page.

Update contact page and resources page

---

site2/website/release-notes.md

- Add 2.6.1 release notes to repo

Add 2.6.1 release notes to repo

---

site2/website/static/swagger/2.6.1/swagger.json
site2/website/static/swagger/2.6.1/swaggerfunctions.json
site2/website/static/swagger/2.6.1/swaggersink.json
site2/website/static/swagger/2.6.1/swaggersource.json

Follow the [Release Process](https://github.com/apache/pulsar/wiki/Release-process#14-update-swagger-file) to update the swagger files for release 2.6.1

Update swagger files for release 2.6.1

---

site2/website/blog/2020-08-24-Pulsar-300-contributors.md

[blog] Update star number

---

site2/website/blog/2020-08-17-Apache-Pulsar-2-6-1.md
site2/website/release-notes.md

Update release 2.6.1 blog

---

site2/website/siteConfig.js

Sync the Pulsar project description with the latest version on home page.

[website] Update siteConfig.js

---

site2/docs/concepts-messaging.md
site2/docs/cookbooks-deduplication.md
site2/docs/reference-pulsar-admin.md

PR (https://github.com/apache/pulsar/pull/7821) supports set/get/remove the deduplication policy at the topic level. 
Update the doc based on code updates.
The following docs are updated:
- Messaging: message deduplication
- Manage message deduplication
- pulsar admin cli reference

[Doc]--support set/get/remove message deduplication policy at topic level

---

.github/workflows/ci-pulsar-website-build.yaml

**Motivation**
Migrate the build website job to github actions.

[Website] Using github action to trigger build website

---

site2/docs/reference-configuration.md

Update AWS deployment in `reference-configuration`.

Update AWS deployment

---

site2/website/pages/en/index.js

Some description is not updated accordingly.
Update the description for different features.

[website] Update index.js

---

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/state/StateContextImpl.java

Rewind ByteBuffers Read/Written to Function's state store

Rewind ByteBuffers Read/Written to Function's state store

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java

Don't fail the health check request when trying to delete the previous subscription.

Don't fail the health check request when trying to delete the previous subscription.

---

pulsar-client/src/main/java/org/apache/pulsar/client/util/TypeCheckUtil.java
pulsar-discovery-service/src/main/java/org/apache/pulsar/discovery/service/web/DiscoveryServiceServlet.java

Fix log level error and typos

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationService.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractReplicator.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/SLAMonitoringTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionAssignmentTailerTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionRuntimeManagerTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyRolesEnforcementTest.java

Fixes #7933 
Newbie trying to make his first contribution to this projection :-)
Added some logging to Authentication Service to help debugging when there are more than one AuthN provider.
When I did that I noticed a typo ('occured' should have two r's) so I decided to try to fix all of them
- Dependencies (does it add or upgrade a dependency): No
- If a feature is not applicable for documentation, explain why? Just …

[Issue 7933][pulsar-broker-common] Add some logging to improve Authentication debugging and Fix typos in code "occured" -> "occurred"

---

site2/docs/security-oauth2.md

**Motivation**
After #7813, the python client supports the oauth2 authentication as well. Add an example for it.

Add python oauth2 document

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java

Fixes #7799
Pulsar metrics providing wrong information
add a reset for counter
PrometheusMetricsTest#testMetricsTopicCount

fix pulsar metrics providing wrong information

---

site2/docs/client-libraries-node.md

- Update description about compatibility, methods and parameters.

[docs] Update Node client document

---

site2/website/static/js/getCliByVersion.js

Fixes #7915 
* Website admin cli link error
* Update link version
* Local test
- If a feature is not applicable for documentation, …

[Admin cli]Fixed website admin cli link error

---

site2/docs/functions-package.md
site2/website/sidebars.json

Add docs of package Pulsar Functions

Add docs of package Pulsar Functions

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java

Forcibly delete batch source intermediate topic

Improve batch source intermediate topic cleanup

---

site2/docs/security-authorization.md
site2/docs/security-extending.md

Small improvements on documentation for AuthN/AuthZ
Custom AuthN/AuthZ can get pretty complicated looking to tighten things up a little bit in this area.
Made some wording suggestions, added a little content especially for proxy/broker which can both do AuthN.
- If yes, how is the feature documented? documentation-only change
- If a feature is not applicable for …

[DOCS] Small improvements and clarifications around AuthN / AuthZ

---

pom.xml

Fixes #7869 
- Upgrade `protobuf` version to `3.11.4`

Upgrade protobuf version to 3.11.4

---

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Issue-7982: Removed blocking call

---

site2/docs/functions-package.md

On [Functions package page](https://pulsar.apache.org/docs/en/next/functions-package/),  the same notes/tips occur many times, and some code snippets are not displayed correctly.
1. Re-org the structure, reduce note/tips
2. Fix code snippet display issues.
3. Fix indent issues.

[docs] Update Functions package content

---

site2/docs/cookbooks-compaction.md

Just fixes a broken link in the docs

Fix broken trigger link

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java

Sometimes errors occur in AuthN custom code e.g. #7893 and there are not enough clues in the logs to help isolate the problem
Added stack trace to several log lines.
Added log lines with a stack trace where an exception was rethrown (also for consistency with the class)
- If a feature is not applicable for …

Add logging of stack trace to help debugging AuthN problems

---

site2/docs/security-jwt.md
site2/website/versioned_docs/version-2.6.0/security-jwt.md
site2/website/versioned_docs/version-2.6.1/security-jwt.md
site2/website/versioned_docs/version-2.6.2/security-jwt.md

---
Master Issue: #7824
*Motivation*
Update the configuration in the doc of authenticating the original auth data.

Update the jwt authentication doc

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Namespaces.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java

Fixes #7959
Add a optional field to force the deletion of all stuffs related to namespace.

[Issue 7959] Added support to force deleting namespace

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java

Replace map with set

---

site2/website/data/users.js
site2/website/static/css/custom.css

Replace Streamlio logo with Splunk

[Website] Replace Streamlio logo with Splunk

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Worker.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerService.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerStatsManager.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Enable worker JVM metrics to be reported via Prometheus

---

site2/website/data/users.js

Add logos for Appen, Keytop, Zhihu.
Update logo path for THG.
Fix logo display issue for OKCoin.

[website] Add user logos

---

site2/website/data/users.js

According to Appen, they prefer to use the this website: https://www.appen.com.cn/
Update as the CN website.

[website] Use the CN website for Appen

---

site2/website/data/users.js

Add logo for Newland corp. They are also using Pulsar.

[WIP][website] Add logo for Newland

---

conf/broker.conf
conf/standalone.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/BookKeeperClientFactoryImpl.java
site2/docs/reference-configuration.md

Add config to configure number of channels per bookie in broker's bk-client.

[pulsar-broker] add configuration to set number of channels per bookie

---

pom.xml
pulsar-functions/runtime/pom.xml
pulsar-functions/secrets/pom.xml

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Standardize kubernetes client version

---

pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Added ability to specify secrets class in localrunner builder

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PreInterceptFilter.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Skip intercepting multipart requests

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java

Add CLI support get last-message-id

[pulsar-admin-tool] add cli command to get last message Id

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ClientConfigurationData.java

Fix #8109 
remove sensitive client configuration info from log

remove sensitive client configuration info from log

---

managed-ledger/src/test/java/org/apache/bookkeeper/test/BookKeeperClusterTestCase.java
pulsar-broker-common/src/main/java/org/apache/pulsar/common/configuration/PulsarConfigurationLoader.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/BundleSplitterTask.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnedBundle.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/OwnershipCache.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/ServiceUnitZkUtils.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApiTest2.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthenticationTlsHostnameVerificationTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/MessageDispatchThrottlingTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java
pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ClientConfiguration.java
pulsar-client-1x-base/pulsar-client-1x/src/main/java/org/apache/pulsar/client/api/ConsumerConfiguration.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-discovery-service/src/main/java/org/apache/pulsar/discovery/service/DiscoveryService.java
pulsar-discovery-service/src/test/java/org/apache/pulsar/discovery/service/DiscoveryServiceTest.java
pulsar-io/kinesis/src/main/java/org/apache/pulsar/io/kinesis/Utils.java
pulsar-storm/src/main/java/org/apache/pulsar/storm/PulsarSpoutConfiguration.java
pulsar-storm/src/main/java/org/apache/pulsar/storm/PulsarSpoutConsumer.java
pulsar-storm/src/main/java/org/apache/pulsar/storm/SharedPulsarClient.java
pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperCache.java
pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperClientFactory.java
site2/docs/security-extending.md

Issues spotted by IntelliJ
IntelliJ complains and highlights these issues
Sync JavaDoc with code

[Doc] Fix JavaDoc issues. 

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java

Signed-off-by: mak <610546069@qq.com>
fix possible npe
*(or)*
*(or)*
*(example:)* …

fix possible NPE

---

pulsar-io/core/src/main/java/org/apache/pulsar/io/core/ConnectorContext.java
pulsar-io/core/src/main/java/org/apache/pulsar/io/core/Context.java
pulsar-io/core/src/main/java/org/apache/pulsar/io/core/SinkContext.java
pulsar-io/core/src/main/java/org/apache/pulsar/io/core/SourceContext.java

<!--
Fixes #8162 
Make working with the connector context's simplier
Added org.apache.pulsar.io.core.Context interface 
- If yes, how is the feature documented? (not applicable)
- If a feature is not documented yet in this PR, please …

[Issue-8162] [pulsar-io] Added org.apache.pulsar.io.core.Context interface

---

site2/website/versioned_sidebars/version-2.6.1-sidebars.json
site2/website/versioned_sidebars/version-2.6.2-sidebars.json

Fixes #8016 
Master Issue: #8016 
* Fixed latest version doc sidebar
* Fixed latest version doc sidebar
local test pass

Fixed latest doc version sidebar

---

site2/docs/functions-develop.md

Follow-up PR for #8132 
Add examples for using user config in Go SDK

[docs] [component/functions] [component/go] Add usage examples for user config in Go SDK

---

pulsar-client-cpp/python/pulsar/schema/definition.py
pulsar-client-cpp/python/schema_test.py

Fix #7673 
For each python defined field type, init default value.

add python schema field default value

---

pulsar-broker/src/test/java/org/apache/pulsar/client/transaction/EndToEndTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java

Currently, the pulsar client transaction test `EndToEndTest` work not well.

Fix pulsar client transaction test

---

site2/docs/functions-develop.md

How to SerDe for Java Functions are not described in the Functions doc.
Add the description.

[docs] Add how to SerDe for Java function

---

pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/LocalBookkeeperEnsemble.java

When running ZK in embedded mode in Pulsar standalone it's not deleted the old snapshot and log files.

Zookeeper in standalone mode is not deleting old snapshots

---

site2/docs/client-libraries-java.md
site2/website/versioned_docs/version-2.5.0/client-libraries-java.md
site2/website/versioned_docs/version-2.5.1/client-libraries-java.md
site2/website/versioned_docs/version-2.5.2/client-libraries-java.md
site2/website/versioned_docs/version-2.6.0/client-libraries-java.md
site2/website/versioned_docs/version-2.6.1/client-libraries-java.md
site2/website/versioned_docs/version-2.6.2/client-libraries-java.md

[Issue 8294][docs]Some errors on the official website document of Pulsar Java client #8294

---

.github/workflows/ci-pulsar-build.yml
pom.xml

Upgrade shaded plugin version to 3.4.2

Fix branch-2.6 build issue

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java

Support replication dispatch throttling for V1-namespace api as well.

[pulsar-broker-admin] Support replication dispatch-rate limiting for v1-namespace api

---

site2/website/pages/en/events.js

[website] Update the Event page

---

site2/website/data/team.js

We have two more committers for Pulsar community.
Add their info on the website.

[website] Add new committers

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/v2/TopicLookup.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TopicOwnerTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Lookup.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/LookupImpl.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CliCommand.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

Fixes #7571 
Support look up for partitioned topic.
Add look up  support for partitioned topic.

Support partitioned topic lookup

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java

remove duplicated code and un-used import
remove duplicated code and un-used import

remove duplicated code and un-used import

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/conf/ConsumerConfigurationData.java
pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java

1. Exception description is clearer
1. add an error message.
2. collapse catch block

Fix: add an error message

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java

Fix typo in PersistentStickyKeyDispatcherMultipleConsumers.java

Fix typo in PersistentStickyKeyDispatcherMultipleConsumers.java

---

site2/docs/client-libraries-node.md

At the official docs, there exists a typo. I want it to be fixed.
I have changed `pusar` to `pulsar` in docs Installation section.
- Dependencies (does it add or upgrade a dependency): (`no`)
- The public API: (`no`)
- The schema: (`no`)
- The default values of configurations: (`no`)
- The wire protocol: (`no`)
- The rest endpoints: (`no`)
- The admin cli options: (`no`)
- Anything that affects deployment: (`no`)
- Does this pull request introduce a new feature? (`no`)
- If yes, how is the feature documented? (`not applicable`)
- If a feature is not applicable for documentation, explain why? `This is a typo fix`
- If a feature is not documented yet in this PR, please create a followup issue for adding the …

Fix typo in Installation section

---

site2/website/versioned_docs/version-2.6.1/helm-deploy.md
site2/website/versioned_docs/version-2.6.2/helm-deploy.md

According to #7365, the helm deployment is updated in 2.6.0
Sync the update in 2.6.0 in 2.6.1 and 2.6.2.

[docs] Update helm deploy content

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java

Minor: fix typo in properties name

[pulsar-cli] Fix properties name

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java

Provides better information for debugging

Log principals when it changes during auth refresh.

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Fix returned status code for get function state when state does not exist

---

site2/website/versioned_docs/version-2.5.0/client-libraries-node.md
site2/website/versioned_docs/version-2.5.1/client-libraries-node.md
site2/website/versioned_docs/version-2.5.2/client-libraries-node.md
site2/website/versioned_docs/version-2.6.0/client-libraries-node.md
site2/website/versioned_docs/version-2.6.1/client-libraries-node.md
site2/website/versioned_docs/version-2.6.2/client-libraries-node.md

Modification:
pusar -> pulsar
Version:
2.5.0 -> 2.6.2

Fix typo in Pulsar installation docs

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

[Issue 8079] Use if to avoid throwing NPE

---

site2/website/static/swagger/2.6.2/swagger.json
site2/website/static/swagger/2.6.2/swaggerfunctions.json
site2/website/static/swagger/2.6.2/swaggersink.json
site2/website/static/swagger/2.6.2/swaggersource.json

Add swagger file for 2.6.2

---

site2/website/blog/2020-11-09-Apache-Pulsar-2-6-2.md

Add 2.6.2 release blog

---

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java
pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java

Fixes #8507
As part of the closed issue: #8012 a customRuntimeOption of "jobName" was added in order to allow an override of the pod name for the function in the Kubernetes runtime. While it covers most issues one was discovered where a jobName could be re-used for a different function and it would cause collisions with the pod and potentially statefulset. In order to alleviate this make sure that a short hash is added to the pod name to avoid collisions like is done when job names are converted when illegal characters are added.
- Make sure when 'jobName' used for custom runtime options that there are no collisions with pod name. To do this make sure tenant, namespace, and function name are used with 'jobName' to create unique reproducible job name (KubernetesRuntime.java)
- Updated unit …

[Issue 8507][pulsar-functions] Overridden 'jobName' in Kubernetes runtime with custom runtime options can have collisions when same 'jobName' is used

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java

Deleted some code that was not used at all

Remove dead code

---

pulsar-client-all/pom.xml

Fixes #8524
Fix the typo in pulsar-client-all module's pom.xml
- Dependencies (does it add or upgrade a dependency): (**yes**)
- Anything that affects deployment: ( no)

[Issue 8524]Fix the typo in pulsar-client-all module's pom.xml

---

conf/pulsar_env.sh

The judge sentences of if is reversed, can not work in jdk8.
Fix the judge sentences.

fix gc log variable judge in jdk8

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ConsumerBatchReceiveTest.java

Add more test case for BatchReceivePolicy.

Add more test case for BatchReceivePolicy.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSender.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarCommandSenderImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TransportCnx.java

**Motivation**
Fix the project style error introduced by #6720

Fix the project style error

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ProtobufNativeSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericProtobufNativeSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/MultiVersionGenericProtobufNativeReader.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/reader/AbstractMultiVersionReader.java

*Motivation*
The protobuf-native schema was broken due to two concurrent merges

Fix broken protobuf-native schema

---

site2/docs/concepts-transactions.md

Introduce the new feature in Pulsar 2.7.0.
Add Transaction concepts info.
Follow-ups: Will add sidebar when the batch of content are submitted.

[docs] Add transaction concepts

---

site2/docs/transaction-guarantee.md

Add Pulsar transaction guarantee content.

[docs] Add Pulsar transactions guarantee

---

site2/docs/transaction-api.md

[docs] Add transaction API

---

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/batch/BatchSourceExecutor.java
pulsar-io/batch-discovery-triggerers/src/main/java/org/apache/pulsar/io/batchdiscovery/CronTriggerer.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Improve naming of threads used in batch source

---

pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperCache.java

Fix cherry-pick issue of the #8304

Fix cherry-pick issue of the #8304

---

pulsar-zookeeper-utils/src/main/java/org/apache/pulsar/zookeeper/ZooKeeperCache.java

[Branch-2.6] Fix cherry-pick issue between #8302 and #8304

[Branch-2.6] Fix cherry-pick issue between #8302 and #8304

---

site2/docs/functions-worker.md
site2/docs/io-cli.md
site2/docs/reference-pulsar-admin.md

Master Issue: #8431
Adding document for e2e encryption pulsar functions
- add docs for functions side
- add docs for sources side
- add docs for function-worker

Add e2e docs for pulsar functions

---

site2/website/blog/2020-11-04-pulsar-summit-asia-schedule.md

Motivation
We are planning to host Pulsar Summit Asia 2020 on 11/28-11/29, 2020.
Modifications
Add a schedule blog for this upcoming event.

[Publish blog] Summit Asia Schedule announcement

---

site2/docs/admin-api-brokers.md
site2/docs/admin-api-clusters.md
site2/docs/admin-api-functions.md
site2/docs/admin-api-namespaces.md
site2/docs/admin-api-overview.md
site2/docs/admin-api-permissions.md
site2/docs/admin-api-tenants.md

Adopt switch tab for pulsar-admin, REST API, and Java.
Add switch tabs in Admin API docs.

Adopt switch tab for pulsar-admin, REST API, and Java

---

pom.xml
pulsar-package-management/core/pom.xml
pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/PackagesManagement.java
pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/PackagesStorage.java
pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/PackagesStorageConfiguration.java
pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/PackagesStorageProvider.java
pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/common/PackageMetadata.java
pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/common/PackageName.java
pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/common/PackageType.java
pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/common/package-info.java
pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/package-info.java
pulsar-package-management/core/src/test/java/org/apache/pulsar/packages/management/core/common/PackageNameTest.java
pulsar-package-management/pom.xml

---
Master issue: #8676 
*Motivation*
Implementation of the PIP-50.
This PR introduces package management APIs and storage APIs.
The related implement will in the next PR.
- Add package management APIs
- Add package storage APIs
- Introduce the package type, name, and metadata struct.

Introduce the packages management interface API

---

pulsar-package-management/core/pom.xml
pulsar-package-management/pom.xml

Update package `org.apache.pulsar:pulsar-package-management` from `2.7.0-SNAPSHOT` version to `2.8.0-SNAPSHOT`.

[Build] Update management module version

---

site2/docs/concepts-transactions.md
site2/docs/transaction-api.md
site2/docs/transaction-guarantee.md
site2/website/sidebars.json

Pulsar introduce transactions content in 2.7.0.
Add transaction content in the sidebar.

[docs] Add transactions in the sidebar

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/DelayedDeliveryTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/delayed/InMemoryDelayedDeliveryTracker.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Dispatcher.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/TripleLongPriorityQueue.java

Clear delayed messages when clear backlog.
Tests added.

Clear delayed messages when clear backlog.

---

buildtools/pom.xml
pom.xml
pulsar-sql/presto-distribution/pom.xml

Keep [license-maven-plugin](https://mycila.mathieu.photography/license-maven-plugin/) updated. 
Adapt existing configuration from 3.0 to 4.0.rc2

[build] Upgrade license-maven-plugin to 4.0.rc2 version

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/PulsarMultiListenersWithInternalListenerNameTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/PulsarMultiListenersWithoutInternalListenerNameTest.java

Fix throw NPE when cleaning

---

site2/docs/deploy-docker.md

Here should be pull the docker image.
Amend `docker run -it apachepulsar/pulsar-all:latest` to `docker pull apachepulsar/pulsar-all:latest`.

[docs] Fix incorrect command

---

site2/website/static/swagger/2.7.0/swagger.json
site2/website/static/swagger/2.7.0/swaggerfunctions.json
site2/website/static/swagger/2.7.0/swaggersink.json
site2/website/static/swagger/2.7.0/swaggersource.json

Update swagger files for 2.7.0

Update swagger files for 2.7.0

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/PulsarMultiListenersWithInternalListenerNameTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/PulsarMultiListenersWithoutInternalListenerNameTest.java

(cherry picked from commit 8e30dd465b7b6849375ec82a09eee06f490f33a9)

[bot-cherry-pick]Fix throw NPE when cleaning

---

site2/docs/client-libraries-websocket.md
site2/docs/getting-started-clients.md
site2/website/sidebars.json

* update
* Update site2/docs/client-libraries-websocket.md
Co-authored-by: HuanliMeng <48120384+Huanli-Meng@users.noreply.github.com>
Co-authored-by: HuanliMeng <48120384+Huanli-Meng@users.noreply.github.com>
(cherry picked from commit 456f265a4c291b36c02a831e8d939cf5e58be880)

[bot-cherry-pick][docs] Update Websocket content

---

pulsar-package-management/bookkeeper-storage/src/main/java/org/apache/pulsar/packages/management/storage/bookkeeper/DLOutputStream.java

---
*Motivation*
The package management module build failed by the spotbugs check.
That will block the project build.
*Modification*
- remove the unused code which checks out by spotbugs

[Build] The package management module failed to build

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java

Fixes #8827
fix exception cast error

fix exception cast error

---

pom.xml
pulsar-io/batch-discovery-triggerers/pom.xml

* update cron-utils to 9.1.3
* update sprint-context to 5.3.1
* this is to resolve security vulnerability "CVE-2020-26238"

Update version for cron-utils and spring-context

---

buildtools/src/main/resources/pulsar/suppressions.xml
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Bookies.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Functions.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java

Main issue: https://github.com/streamnative/pulsar/issues/1768
This PR changes code style related things only

make module `pulsar-broker` gradually conform checkstyle

---

site2/website/versioned_docs/version-2.7.0/client-libraries-websocket.md
site2/website/versioned_docs/version-2.7.0/getting-started-clients.md
site2/website/versioned_sidebars/version-2.7.0-sidebars.json

[docs] Apply changes to 270 release

---

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PackagesImpl.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPackages.java
pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdPackages.java

---
Master Issue: #8676
*Motivation*
Add commands for package management service in pulsar-admin tool.
- Add commands for package management service

Package management client command

---

site2/website/versioned_sidebars/version-2.7.0-sidebars.json

There is a typo in 2.7.0 sidebar.
Update the 2.7.0 doc sidebar.

[Doc]--Update 2.7.0 doc sidebar

---

pulsar-io/netty/pom.xml
pulsar-io/netty/src/main/java/org/apache/pulsar/io/netty/http/NettyHttpServerHandler.java
pulsar-io/netty/src/main/resources/findbugsExclude.xml

Master Issue: #8843
Enable spotbugs for the pulsar-io module. 
Enable soptbugs for pulsar-io-netty
```
mvn clean install -pl pulsar-io/netty
```

[SpotBugs][pulsar-io]Enable spotbugs for pulsar-io-netty

---

.github/workflows/ci-unit-broker-broker-gp1.yaml
.github/workflows/ci-unit-broker-broker-gp2.yaml
.github/workflows/ci-unit-broker-client-api.yaml
.github/workflows/ci-unit-broker-client-impl.yaml
.github/workflows/ci-unit-broker-other.yaml
.github/workflows/ci-unit-proxy.yaml
.github/workflows/ci-unit.yaml
build/retry.sh
build/run_unit_group.sh

* Current unit test group for ci is scattered and error prone.
* This PR unifies all group declarations in single file for easier use and simpler management.

Unify CI script for unit test grouping

---

.github/workflows/ci-pulsarbot.yaml

---
*Motivation*
Disable the cherry-pick bot. Because of the cherry-pick bot
will change the author of the PR and maybe need another way
to do the cherry-pick automatically.

[CI] Disable the cherry-pick bot

---

pulsar-broker/pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PackagesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v3/Packages.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/PackagesApiTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PackagesImpl.java
pulsar-package-management/core/pom.xml
pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/impl/PackagesManagementImpl.java

---
Master Issue: #8676
*Motivation*
Add REST API resources for package management service and
allow the package management service to handle HTTP requests
- Add REST APIs for package management service

Add REST APIs for package management service

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleFactory.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java

fix #8533 , modified only issue-related method, may need to change all calls in this section to asynchronous later.

Issue #8533: Change method `getWebServiceUrl` into async

---

site2/docs/security-tls-keystore.md
site2/website/versioned_docs/version-2.6.0/security-tls-keystore.md
site2/website/versioned_docs/version-2.6.1/security-tls-keystore.md
site2/website/versioned_docs/version-2.6.2/security-tls-keystore.md

Fixes #8872 
When users configure authParam, some errors occur
Try to configure the authParam as JSON

[docs] Configure authParams as JSON

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/TestBasicPresto.java

Master Issue: #8533 
Fix the project style error introduced by #8533

Fix pulsar-broker style error

---

site2/docs/tiered-storage-gcs.md
site2/website/data/users.js

Fix #8909 .
But there is still one bad link left to fix, since I didn't find kubernetes-helm.md, so I don't know what to do better with it.
```
"page": "deploy-monitoring.md",
"brokenLinks": [
"kubernetes-helm.md"
]
```

[ISSUE 8909]Fix Giggso logo link error

---

pulsar-io/nsq/src/main/resources/META-INF/services/pulsar-io.yaml

Fix NSQ source META-INF file name and sourceConfigClass

---

conf/broker.conf
conf/standalone.conf

Fixed typo in Resource usage ThresholdShedder in configuration comments.

[docs] Fix typo in broker.conf and standalone.conf

---

site2/docs/functions-worker.md

Users fail to restart broker with the current workaround.
Fix the workaround.

[docs] Fix workaround for functions worker errors

---

site2/website/versioned_docs/version-2.4.0/functions-worker.md
site2/website/versioned_docs/version-2.4.1/functions-worker.md
site2/website/versioned_docs/version-2.4.2/functions-worker.md
site2/website/versioned_docs/version-2.5.0/functions-worker.md
site2/website/versioned_docs/version-2.6.0/functions-worker.md
site2/website/versioned_docs/version-2.6.1/functions-worker.md
site2/website/versioned_docs/version-2.6.2/functions-worker.md
site2/website/versioned_docs/version-2.7.0/functions-worker.md

Update the Workaround section in versioned docs since 2.4.0.

Fix Workaround in versioned docs since 2.4.0

---

site2/website/docusaurus-version.js
site2/website/package.json

Generate full documentation and sidebars, fixed scripts
* Generate full documentation and sidebars
* Fixed docusaurus-version.js, remove the if check condition
Local test pass

[website]Fixed generate sidebar and full documentation

---

site2/website/sidebars.json
site2/website/versioned_sidebars/version-2.7.0-sidebars.json

Azure offloader content is added in #https://github.com/apache/pulsar/pull/8436
Add it in the sidebar file, so it will be displayed on website.

[website] Add azure offloader to website

---

pulsar-config-validation/pom.xml
pulsar-config-validation/src/main/java/org/apache/pulsar/config/validation/ConfigValidationUtils.java

Add spotbug checks for pulsar-config-validation module.
The only failure check is the redundant null check, so we just remove the null check.

Add spotbug checks for pulsar-config-validation module

---

site2/tools/python-doc-gen.sh

Fixes #8999
https://pulsar.apache.org/api/python/ points to the first ever released Python API. This was confusing me for the longest time until I figured out that the latest API doc is actually at https://pulsar.apache.org/api/python/2.7.0-SNAPSHOT/
https://pulsar.apache.org/api/python/ should redirect to the latest version and the page itself should clearly state which version it documents.
Copy current version of the API docs to /api/python root.

Fix Issue #8999

---

.github/workflows/ci-integration-sql.yaml
tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/TestBasicPresto.java

---
*Motivation*
Using await until for retrying the condition check.

Add retry for the sql test

---

site2/website/data/team.js

Add new committers' info on the Pulsar website.

[website] Update team info

---

site2/docs/adaptors-spark.md
site2/docs/adaptors-storm.md
site2/website/versioned_docs/version-2.6.0/adaptors-spark.md
site2/website/versioned_docs/version-2.6.0/adaptors-storm.md
site2/website/versioned_docs/version-2.6.1/adaptors-spark.md
site2/website/versioned_docs/version-2.6.1/adaptors-storm.md
site2/website/versioned_docs/version-2.6.2/adaptors-spark.md
site2/website/versioned_docs/version-2.6.2/adaptors-storm.md
site2/website/versioned_docs/version-2.7.0/adaptors-spark.md
site2/website/versioned_docs/version-2.7.0/adaptors-storm.md

Fixes #8994
Modification:
Update two example links in separate files.

[ISSUE] DOCS-8994 fix the links of examples

---

site2/website/versioned_docs/version-2.7.1/concepts-clients.md

[DOCS] Update 271 "concept-client"

---

site2/docs/administration-pulsar-manager.md
site2/website/versioned_docs/version-2.5.0/administration-pulsar-manager.md
site2/website/versioned_docs/version-2.6.0/administration-pulsar-manager.md
site2/website/versioned_docs/version-2.6.1/administration-pulsar-manager.md
site2/website/versioned_docs/version-2.6.2/administration-pulsar-manager.md
site2/website/versioned_docs/version-2.7.0/administration-pulsar-manager.md

Fixes #7822
Modification:
Corrections in versioned docs and master.

[DOCS] Refine the description of jwt

---

site2/website/versioned_docs/version-2.7.1/administration-pulsar-manager.md

Fixes #9053 
Update the 2.7.1 version.

[DOCS] FIX-9053

---

site2/website/data/users.js

Panfish is a Pulsar adopter now.
Add their logo on Pulsar user list.

[website] Add panfish logo on Pulsar user list

---

pulsar-client-cpp/include/pulsar/Consumer.h

[cpp-client] Fix compilation issue caused by non-virtual destructor

---

site2/docs/client-libraries-websocket.md

Fixes #8610
- Add how to enable TLS for websocket
- Add how to configure your client to connect to a tls-secured websocket endpoint
@Jennifer88huang could you take a look?

[Issue 8610][WebSocketService] Add configuration TLS to WebSocket service document

---

managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java

The test is intermittently failing because the check is disregarding the timing of when the first callback is received, which can be later than the 3 async call is issued.

Fixed race condition in ManagedLedgerTest.testAsyncUpdateProperties()

---

site2/docs/concepts-messaging.md
site2/website/versioned_docs/version-2.6.0/concepts-messaging.md
site2/website/versioned_docs/version-2.6.1/concepts-messaging.md
site2/website/versioned_docs/version-2.6.2/concepts-messaging.md
site2/website/versioned_docs/version-2.6.3/concepts-messaging.md
site2/website/versioned_docs/version-2.7.0/concepts-messaging.md
site2/website/versioned_docs/version-2.7.1/concepts-messaging.md

DOCS - Modify the note description of Key_shared mode

---

site2/docs/functions-worker.md

- Add how to configure `initializedDlogMetadata` in function-worker document

[docs] Add initializedDlogMetadata config to functions-worker

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryCacheImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryCacheManager.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/EntryImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryMBeanImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerOfflineBacklog.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java

When in debug log, this doesn't provide useful informations
- add the toString method of OpAddEntry
- fix some java doc problems

Supply debug log for OpAddEntry

---

site2/website/data/team.js

**Motivation**
Add me to the team page.

[website] Add me to the team page

---

pom.xml

The Spring plugins repo is not used and it may slowdown the build.
Let's remove it

Remove Spring repo

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

add applied API
Test whether the API works: testGetMaxProducerApplied

Support get topic applied policy for MaxProducer

---

site2/website/data/users.js

We recently discovered unlisted Pulsar user companies:
Dada Group, Huawei Cloud, Su Ning, Ping'an Securites, Ge Tui, KAISA, Bairong.Inc, Itcast.cn
Update the above company logos to Pulsar website.

Update Pulsar user logo on website

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiDelayedDelivery.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Namespaces.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

add applied API for client
unit test:
adminApiDelayedDelivery.testNamespaceDelayedDeliveryPolicyApi
adminApiDelayedDelivery.testDelayedDeliveryApplied

Support get topic applied policy for DelayedDeliveryPolicies

---

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/state/BKStateStoreProviderImpl.java

Add additional logging during the state table setup process to help debug problems.

Add additional logging when setting up state table for function instance

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java

PulsarAdminToolTest failed to run, causing CI to not work

Fix unit test failure in PulsarAdminToolTest.java

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/TopicStats.java
pulsar-common/src/test/java/org/apache/pulsar/common/policies/data/PersistentTopicStatsTest.java

---
*Motivation*
Add offloaded storage size in the topic stats.

[Stats] Expose offloaded storage size to the topic stats

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedgerException.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java

Improves error logs shown in https://github.com/apache/pulsar/issues/9266
How to fix that issue will be decided after more information exposed

Expose more info with unknown exception

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java

The metrics we will test have a high possibility to be the last metrics of the metrics list, but may not be sometimes, which may cause the test to fail.

fix flaky prometheus test

---

pulsar-client-cpp/lib/Commands.cc

Same as https://github.com/apache/pulsar/pull/4930 .

[pulsar-client-cpp] Fix broken replication msg to specific cluster

---

site2/website/release-notes.md

The release time for Pulsar 2.6.3 is incorrect in the Pulsar release note.
Update the release time for Pulsar 2.6.3

[Doc]--Update release time for Pulsar 2.6.3

---

site2/docs/tiered-storage-aws.md
site2/website/versioned_docs/version-2.7.0/tiered-storage-aws.md
site2/website/versioned_docs/version-2.7.1/tiered-storage-aws.md

This PR adds a workaround for https://github.com/apache/pulsar/issues/9084

[Doc] Add notes for S3 offloading configuration

---

site2/docs/client-libraries-java.md
site2/docs/client-libraries-node.md
site2/docs/client-libraries-websocket.md
site2/website/versioned_docs/version-2.5.0/client-libraries-java.md
site2/website/versioned_docs/version-2.5.0/client-libraries-node.md
site2/website/versioned_docs/version-2.5.1/client-libraries-java.md
site2/website/versioned_docs/version-2.5.1/client-libraries-node.md
site2/website/versioned_docs/version-2.5.2/client-libraries-java.md
site2/website/versioned_docs/version-2.5.2/client-libraries-node.md
site2/website/versioned_docs/version-2.6.0/client-libraries-java.md
site2/website/versioned_docs/version-2.6.0/client-libraries-node.md
site2/website/versioned_docs/version-2.6.0/client-libraries-websocket.md
site2/website/versioned_docs/version-2.6.1/client-libraries-java.md
site2/website/versioned_docs/version-2.6.1/client-libraries-node.md
site2/website/versioned_docs/version-2.6.1/client-libraries-websocket.md
site2/website/versioned_docs/version-2.6.2/client-libraries-java.md
site2/website/versioned_docs/version-2.6.2/client-libraries-node.md
site2/website/versioned_docs/version-2.6.2/client-libraries-websocket.md
site2/website/versioned_docs/version-2.6.3/client-libraries-java.md
site2/website/versioned_docs/version-2.6.3/client-libraries-node.md
site2/website/versioned_docs/version-2.6.3/client-libraries-websocket.md
site2/website/versioned_docs/version-2.7.0/client-libraries-java.md
site2/website/versioned_docs/version-2.7.0/client-libraries-node.md
site2/website/versioned_docs/version-2.7.0/client-libraries-websocket.md
site2/website/versioned_docs/version-2.7.1/client-libraries-java.md
site2/website/versioned_docs/version-2.7.1/client-libraries-node.md
site2/website/versioned_docs/version-2.7.1/client-libraries-websocket.md

*with pip-34 since 2.4.0 add add Key_shared subscription type*
*add Key_shared subscription type*

[docs] add Key_shared subscription type

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SchemasResourceBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/SchemasResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SchemasImpl.java
pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java

Support schema admin-api for v1 topics.

[pulsar-broker] Support schema rest api for V1 topics

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataTeardown.java

* change the **-cluster** parameter in the delete-cluster-metadata command to **--cluster** for this parameter exist short name **-c** . 
* update the **-cluster** parameter to **--cluster**.

update the "-cluster" parameter in the delete-cluster-metadata command to "--cluster"

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiOffloadTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

Add applied API for offloadPolicies

Support get topic applied policy for offloader

---

site2/docs/client-libraries-java.md

Fix https://github.com/apache/pulsar/issues/9423

[Doc] Add descriptions for numListenerThreads

---

site2/docs/client-libraries-cgo.md
site2/docs/client-libraries-go.md
site2/website/versioned_docs/version-2.1.0-incubating/client-libraries-go.md
site2/website/versioned_docs/version-2.2.0/client-libraries-go.md
site2/website/versioned_docs/version-2.2.1/client-libraries-go.md
site2/website/versioned_docs/version-2.3.0/client-libraries-go.md
site2/website/versioned_docs/version-2.3.1/client-libraries-go.md
site2/website/versioned_docs/version-2.4.0/client-libraries-go.md
site2/website/versioned_docs/version-2.5.0/client-libraries-go.md
site2/website/versioned_docs/version-2.5.1/client-libraries-cgo.md
site2/website/versioned_docs/version-2.5.1/client-libraries-go.md
site2/website/versioned_docs/version-2.5.2/client-libraries-cgo.md
site2/website/versioned_docs/version-2.5.2/client-libraries-go.md
site2/website/versioned_docs/version-2.6.0/client-libraries-cgo.md
site2/website/versioned_docs/version-2.6.0/client-libraries-go.md
site2/website/versioned_docs/version-2.6.1/client-libraries-cgo.md
site2/website/versioned_docs/version-2.6.1/client-libraries-go.md
site2/website/versioned_docs/version-2.6.2/client-libraries-cgo.md
site2/website/versioned_docs/version-2.6.2/client-libraries-go.md
site2/website/versioned_docs/version-2.6.3/client-libraries-cgo.md
site2/website/versioned_docs/version-2.6.3/client-libraries-go.md
site2/website/versioned_docs/version-2.7.0/client-libraries-cgo.md
site2/website/versioned_docs/version-2.7.0/client-libraries-go.md
site2/website/versioned_docs/version-2.7.1/client-libraries-cgo.md
site2/website/versioned_docs/version-2.7.1/client-libraries-go.md

Fixes #9168 
A follow-up of #9208

[DOCS] Fix the batch delay default value in versioned docs

---

pulsar-client-cpp/CMakeLists.txt
pulsar-client-cpp/python/CMakeLists.txt

Add additional paths for searching python 3.9 libraries.

Add missing python 3.9 paths in CmakeLists.txt

---

docker-compose/standalone-dashboard/README.MD
docker-compose/standalone-dashboard/docker-compose.yml

* Fix incorrect url in readme for docker-compose.

Fix Url in docker compose readme

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java

Fixes #9576
Fixes a flaky test
Increase timeout from 10 seconds to 20 seconds, use Awaitility for waiting.

[Issue 9576] Fix flaky test BrokerServiceLookupTest.testModularLoadManagerSplitBundle

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java

Fixes #9451
Fix flaky test SimpleProducerConsumerTest.testConcurrentConsumerReceiveWhileReconnect
Use Awaitility to wait for assertions to pass.

[Issue 9451] Fix flaky test SimpleProducerConsumerTest.testConcurrentConsumerReceiveWhileReconnect

---

pulsar-client-cpp/python/setup.py

match BookKeeper's grpcio requirement

---

pulsar-transaction/common/pom.xml
pulsar-transaction/common/src/main/resources/findbugsExclude.xml
pulsar-transaction/coordinator/pom.xml
pulsar-transaction/coordinator/src/main/resources/findbugsExclude.xml
pulsar-transaction/pom.xml

Enable spotbugs in module pulsar-transaction.

[Transaction] Enable spotbugs in module pulsar-transaction.

---

pulsar-client-shaded/pom.xml
tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java

Enable spotbugs in module pulsar-transaction.

[Pulsar client] Enable spotbugs in module pulsar-client-shade.

---

pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java
pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java
pulsar-functions/runtime/src/test/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeTest.java

Fixes #9315
per request from @codelipenghui in #9377, this pr is cherry pick #9377 to branch 2.7 and resolved conflicts.
- cherry pick pr
- resolve conflicts in tests
- remove `package` related code
- [] Make sure that the change passes the CI checks.

[branch-2.7] Add downloadDirectory support to function k8s runtime

---

pulsar-io/docs/pom.xml

- connector yaml files aren't generated for all connectors at the moment
- connector yaml generator was introduced in #2936/#3065 by @sijie 
- add all connectors to dependencies of pulsar-io-docs

Configure Pulsar IO connector yaml file generator for all connectors

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java

---
*Motivation*
Master branch builds failed by [ERROR] Medium: org.apache.pulsar.client.impl.ConsumerBase.NONE_KEY should be package protected [org.apache.pulsar.client.impl.ConsumerBase] At ConsumerBase.java:[line 887] MS_PKGPROTECT

[BUILD] Master branch build failed by spotbugs error

---

site2/website/data/users.js

This is a duplicated PR for #9593. As we don't know why #9593 doesn't trigger CI.

add Deposit-Solutions to the website.

---

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java

Currently, `pulsar-perf` has its own implementation class of `CryptoKeyReader` for end-to-end encryption of messages. Instead of this class, use `DefaultCryptoKeyReader` implemented in https://github.com/apache/pulsar/pull/9379. This change allows us to specify public and private keys by data URI as well as by file path.

[cli] pulsar-perf uses DefaultCryptoKeyReader for E2E encryption

---

site2/website/data/users.js

Hey Team. I spoke with Ali yesterday and he suggested I add [Macrometa](https://macrometa.com) to the user's list. Cheers!
add [Macrometa](https://macrometa.com) to the user's list
no

[docs] Add Macrometa to the list of users

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java

Relates to https://github.com/apache/pulsar/issues/9725.
Opening this PR because https://github.com/apache/pulsar/pull/9751 will (likely) have conflicts for cherry picking. See https://github.com/apache/pulsar/pull/9751 for details on the change.

[Issue 9725][Transaction] - Fix deleteTransactionMarker memory leak (target branch-2.7)

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/ResponseHandlerFilter.java

- adding headers will fail if the response has been committed
- this causes flakiness since the response won't be committed in many cases when the response size is less than the response buffer size
- add the header before executing the filter chain
- check if the response has been committed before attempting to add the header

[Broker] Don't add broker-address header if response has already been committed

---

site2/docs/reference-configuration.md
site2/website/versioned_docs/version-2.6.3/reference-configuration.md
site2/website/versioned_docs/version-2.7.0/reference-configuration.md
site2/website/versioned_docs/version-2.7.1/reference-configuration.md

Fix https://github.com/apache/pulsar/pull/8686 and add docs for 2.6.3, 2.7.0, 2.7.1, and master.

[Doc] Add descriptions for HAProxy

---

deployment/terraform-ansible/deploy-pulsar.yaml

Fixes: #9111 
Also add this one to the release process, @zymap please take a look.

Update the Pulsar version to 2.7.0 for the ansible deployment

---

src/set-project-version.sh

---
Master Issue: #9111
*Motivation*
Update pulsar version in terraform file when updating project version.

Update pulsar version in terraform file when setting project version

---

site2/docs/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.7.1/reference-pulsar-admin.md

Master Issue: #8866 
Related PR:  #8924 
In  #8924, we support configuring max subscriptions per topic at the namespace level.
1. Add related doc content for this feature.
2. Move two other features supported at namespace level to the namespace section.
3. Fix some minor typos.

[Doc] Add doc on how to configure max subscriptions per topic at the namespace level

---

site2/docs/deploy-monitoring.md
site2/docs/reference-pulsar-admin.md
site2/website/versioned_docs/version-2.7.1/deploy-monitoring.md

Master Issue: #9535
Related PR: #9618
Add user notes on managed cursor acknowledgement stats.

[docs] Add content for managed cursor ack stats

---

site2/docs/reference-metrics.md
site2/website/versioned_docs/version-2.7.1/reference-metrics.md

Add docs for https://github.com/apache/pulsar/pull/9321 and https://github.com/apache/pulsar/pull/9244.

[Doc] Add metrics for token and authentication

---

site2/docs/concepts-messaging.md

*Motivation*
Add documentation for configuring max message size.

[doc] Add max message size configuration in doc

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

Fix https://github.com/apache/pulsar/pull/8717

[Doc] Add descriptions for set-offload-policies

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v1/V1_AdminApiTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

Add applied API and fix default value in unit test
Verify the applied API and CMD
Verify the default value in namespace-level

Support get applied BlacklogQuota

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/NamespacesImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

1. Add applied API for ReplicatorDispatchRate in topic-level
2. Add remove for ReplicatorDispatchRate in namespace-level
Verify the applied API and CMD

Support get applied ReplicatorDispatchRate

---

site2/tools/pulsar-admin-doc-gen.sh

Currently, we introduced a new command called `packages`. however, due to the lack of scripts generated by the corresponding documents, the relevant document content was not added. This pull request is mainly used to add documents related to `pulsar-admin packages`
Add docs for packages command

Add docs for packages command

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/FunctionRuntimeManagerTest.java

This PR is related to #9502 and [PR #9519](https://github.com/apache/pulsar/pull/9519).
In [PR #9519 ](https://github.com/apache/pulsar/pull/9519), another contributer has fixed the problem described in #9502, but there are still some areas that can be optimized. 
- Abstract a method and then reuse some code.
- Adding a unit test for the `restartFunctionInstances` method
And I am a newcomer to the pulsar community, do I need to recreate an issue?

[Functions] Abstract repetitive code and add unit tests. #9502

---

site2/docs/concepts-clients.md
site2/website/versioned_docs/version-2.6.0/concepts-clients.md
site2/website/versioned_docs/version-2.6.1/concepts-clients.md
site2/website/versioned_docs/version-2.6.2/concepts-clients.md
site2/website/versioned_docs/version-2.6.3/concepts-clients.md
site2/website/versioned_docs/version-2.7.0/concepts-clients.md
site2/website/versioned_docs/version-2.7.1/concepts-clients.md

The clients concepts page should hold links to all official client libraries.
Added link to the C# client

[docs] Added link to official dotnet client

---

site2/website/static/swagger/2.7.1/swagger.json
site2/website/static/swagger/2.7.1/swaggerfunctions.json
site2/website/static/swagger/2.7.1/swaggersink.json
site2/website/static/swagger/2.7.1/swaggersource.json

---
*Motivation*
Update the 2.7.1 swagger file

[Website] Add 2.7.1 swagger files

---

site2/docs/concepts-messaging.md

Add docs for https://github.com/apache/pulsar/pull/8992

[Doc] Add guides for producer access mode

---

site2/docs/concepts-proxy-sni-routing.md

Add docs for https://github.com/apache/pulsar/pull/8957.

[Doc] Add guides for TLS SNI support (C++ and Python clients)

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationProviderToken.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/PrometheusMetricsTest.java

* PrometheusMetricsTest is one of the flaky tests, that needs additional investigation.
* Clear static metrics to harden tests.
* Remove unnecessary string calls.
* Document test errors for future investigation.

Cleanup PrometheusMetricsTest

---

site2/docs/admin-api-packages.md

Fixes https://github.com/apache/pulsar/issues/9971
The REST admin API commands for packages are not displayed well.
Fix the format of the commands.

[docs] Fix package REST API command issues

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java

The list does not need to be copied again

Remove useless wrapper

---

site2/website/data/users.js

Hi, 
As Softtech we have implemented Pulsar in production for IYS project and managing 1B messages daily via Pulsar. We are working on a new project to transfer Is Bank Turkey to Pulsar. Would be glad to share Softtech Logo in Powered By page.
Best
Fixes #<xyz>
*(or)*
This change is already covered by existing tests, such as …

Update powered by page

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest2.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java

* Minor code cleanup for unit tests.
* No functionality changes.

Test Cleanup

---

pom.xml

- 1.18.18 includes fixes for IDE compatibility (IntelliJ, Eclipse, Netbeans).
This is relevant while developing Pulsar.
- see https://projectlombok.org/changelog for more details
- upgrade Lombok version from 1.18.16 to 1.18.18

Upgrade Lombok version

---

site2/website/versioned_docs/version-2.5.0/administration-geo.md
site2/website/versioned_docs/version-2.5.1/administration-geo.md
site2/website/versioned_docs/version-2.5.2/administration-geo.md
site2/website/versioned_docs/version-2.6.0/administration-geo.md
site2/website/versioned_docs/version-2.6.1/administration-geo.md
site2/website/versioned_docs/version-2.6.2/administration-geo.md
site2/website/versioned_docs/version-2.6.3/administration-geo.md
site2/website/versioned_docs/version-2.7.0/administration-geo.md
site2/website/versioned_docs/version-2.7.1/administration-geo.md

Copying recently committed documentation from #9857 to older versions of the docs. Please let me know if we need to include older versions of the documentation or if I included invalid versions. Thanks!

[Docs][Geo Replication] Copy PR 9857 to older versioned docs

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Topics.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

add applied API for compaction threshold

Support get applied compaction threshold

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentDispatcherSingleActiveConsumer.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java

Move duplicate code to abstract parent class

Move duplicate code to abstract parent class

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java

fix NPE: while configuring consumer builder

[pulsar-client] fix NPE: while configuring consumer builder

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ClientCnxTest.java

In the existing solution there's a memory leak that occurs when a lookup request doesn't receive a reply.
The timeout handling doesn't remove the lookup request's future from pending requests.
https://github.com/apache/pulsar/blob/9db880eddb4bcd4478e24d5161ec022991cd5da7/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java#L615-L621
There's a common way to handle request timeouts in ClientCnx class . However, this method wasn't used for lookup requests.
This PR makes changes in lookup request timeout handling to use the common way which uses the `requestTimeoutQueue` based solution.
Another modification is to use `System.nanoTime()` for calculating elapsed time since `System.currentTimeMillis()` is not a stable way to calculate elapsed time.

[Java Client] Use common request timeout handling for lookup requests and a fix a possible memory leak

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionPool.java

Remove redundant signSafeMod

---

site2/docs/client-libraries-node.md

Update the document according to Node client 1.3.0.
- Add [new features of Node.js client 1.3.0](https://github.com/apache/pulsar-client-node/releases/tag/v1.3.0) to the document.
- Fix some grammatical errors.
- If a feature is not applicable for …

[Doc] Update Node client document

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/DocumentTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdGenerateDocument.java
pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdGenerateDocumentation.java
pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/PulsarClientTool.java

Master Issue: #10040
add command that can  generate document automatically for pulsar-client

Support generate document automatically for pulsar-client

---

site2/website/versioned_docs/version-2.7.1/deploy-monitoring.md

[docs] Fix broken link in deploy-monitoring.md

---

site2/README.md
site2/docs/concepts-messaging.md
site2/docs/functions-develop.md
site2/docs/sql-rest-api.md
site2/website/contributing.md
site2/website/versioned_docs/version-2.4.1/functions-develop.md
site2/website/versioned_docs/version-2.4.2/functions-develop.md
site2/website/versioned_docs/version-2.5.0/functions-develop.md
site2/website/versioned_docs/version-2.5.0/sql-rest-api.md
site2/website/versioned_docs/version-2.5.1/functions-develop.md
site2/website/versioned_docs/version-2.5.2/functions-develop.md
site2/website/versioned_docs/version-2.6.0/concepts-messaging.md
site2/website/versioned_docs/version-2.6.0/functions-develop.md
site2/website/versioned_docs/version-2.6.0/sql-rest-api.md
site2/website/versioned_docs/version-2.6.1/concepts-messaging.md
site2/website/versioned_docs/version-2.6.1/functions-develop.md
site2/website/versioned_docs/version-2.6.1/sql-rest-api.md
site2/website/versioned_docs/version-2.6.2/concepts-messaging.md
site2/website/versioned_docs/version-2.6.2/functions-develop.md
site2/website/versioned_docs/version-2.6.2/sql-rest-api.md
site2/website/versioned_docs/version-2.6.3/concepts-messaging.md
site2/website/versioned_docs/version-2.6.3/functions-develop.md
site2/website/versioned_docs/version-2.6.3/sql-rest-api.md
site2/website/versioned_docs/version-2.7.0/concepts-messaging.md
site2/website/versioned_docs/version-2.7.0/functions-develop.md
site2/website/versioned_docs/version-2.7.0/sql-rest-api.md
site2/website/versioned_docs/version-2.7.1/concepts-messaging.md
site2/website/versioned_docs/version-2.7.1/functions-develop.md
site2/website/versioned_docs/version-2.7.1/sql-rest-api.md

Fix https://github.com/apache/pulsar/issues/10030 and https://apache-pulsar.slack.com/archives/CBXCPTYN8/p1617116923006100.

[Doc] Add workflow for "checking dead links" and update instructions for "generating license headers" 

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java

Create 'Global' cluster in standalone mode only if needed. 

---

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java

[function] fix-typo

---

site2/docs/deploy-monitoring.md
site2/docs/functions-develop.md
site2/docs/io-develop.md
site2/docs/reference-metrics.md

Fix https://github.com/apache/pulsar/issues/9932

[Doc] Add monitoring guidelines for function and connector

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

Expose local run config metrics-port-start to CLI

---

conf/standalone.conf
pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java

Pulsar standalone support transaction
create system topic and create transaction coordinator topic.

[Transaction] Standalone support transaction.

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

Fixes #10176
fix npe in CmdTopics
remove the member topics which causes npe easily. always use getAdmin().topics()

[ISSUE 10176] fix npe in CmdTopics

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceUsageTransportManager.java

Fix log format and swallow exception

Fix log format and swallow exception

---

pulsar-function-go/pf/stats.go

Fixes #10153
fix the time unit of avg process latency in go

[ISSUE 10153]fix time unit ns -> ms

---

bin/pulsar-perf
pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/BrokerMonitor.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/CmdGenerateDocumentation.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationClient.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/LoadSimulationController.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/ManagedLedgerWriter.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
pulsar-testclient/src/test/java/org/apache/pulsar/testclient/GenerateDocumentionTest.java

Master Issue: #10040
Modifications
add command to generate document automatically for pulsar-perf

[doc] Support generate document automatically for pulsar-perf

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionBufferClientTest.java

fix transaction buffer op fail handle
add the error handle
Add the tests for it

[Transaction] Fix transaction buffer op fail handle.

---

site2/website/data/users.js

**Motivation**
Based on this [DataStax blog](https://www.datastax.com/blog/2021/04/how-apache-pulsar-helps-vivy-connect-healthcare-professionals-and-users), Vivy has been the Pulsar adopter.
**Modifications**
Update the website

Add Vivy to the "Powered by" Page

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java

Fix flaky ManagedLedgerFactory shutdown

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java

fix https://github.com/apache/pulsar/issues/10360
change partition to one.

[Transaction] Fix flaky txnMessageAckTest.

---

docker/pulsar-standalone/Dockerfile

Fixes #10358
*(or)*
*(or)*
*(example:)*
- The public API: …

fix docker standalone image error

---

site2/docs/client-libraries-java.md
site2/website/versioned_docs/version-2.5.0/client-libraries-java.md
site2/website/versioned_docs/version-2.5.1/client-libraries-java.md
site2/website/versioned_docs/version-2.5.2/client-libraries-java.md
site2/website/versioned_docs/version-2.6.0/client-libraries-java.md
site2/website/versioned_docs/version-2.6.1/client-libraries-java.md
site2/website/versioned_docs/version-2.6.2/client-libraries-java.md
site2/website/versioned_docs/version-2.6.3/client-libraries-java.md
site2/website/versioned_docs/version-2.7.0/client-libraries-java.md
site2/website/versioned_docs/version-2.7.1/client-libraries-java.md
site2/website/versioned_docs/version-2.7.2/client-libraries-java.md

[Doc] Update client-libraries-java.md

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java

Related #10377
adjust log for locating problem and format code

[consumer] adjust log for locating problem and format code

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TransactionBufferHandlerImpl.java

link : https://github.com/apache/pulsar/pull/10407
change sync monitor.
change sync monitor.

[Transaction] Fix transaction buffer handler sync problem.

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/TransactionMetadataStoreServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/buffer/TransactionLowWaterMarkTest.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStore.java

`txnIdSortedSet` is redundant, `txnMetaMap` can replace it.
remove `txnIdSortedSet`.
Add the tests for it

[Transaction] Transaction log low water mark optimization.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java

- backports #10413 to branch-2.7

[Broker] Make PersistentDispatcherMultipleConsumers.readMoreEntries synchronized

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java

[Java Client] Fix concurrency issue in incrementing epoch (#10278)

---

pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java

---
*Motivation*
Branch 2.7 build failed by the SchemaTest file.

[Branch-2.7] Fix the build error

---

README.md

Adds instructions for building custom docker images to README.md

[Docs] Add instructions for building custom docker images

---

site2/docs/client-libraries-go.md

I found some wrong typing in doc when i using golang client. Most of them are package name missioning.
Changed code in doc.

[Document] Golang client usage code

---

pulsar-client-cpp/include/pulsar/c/consumer.h
pulsar-client-cpp/include/pulsar/c/producer.h
pulsar-client-cpp/include/pulsar/c/reader.h
pulsar-client-cpp/lib/c/c_Consumer.cc
pulsar-client-cpp/lib/c/c_Producer.cc
pulsar-client-cpp/lib/c/c_Reader.cc

Add isConnected() method to Producer, Consumer and Reader in C++.
https://github.com/apache/pulsar/pull/10349
Add is_connected method to Producer, Consumer and Reader in CAPI.

[CAPI] Add is_connected method C API

---

pom.xml
pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenz.java
site2/docs/security-athenz.md
site2/website/versioned_docs/version-2.1.0-incubating/security-athenz.md
site2/website/versioned_docs/version-2.4.1/security-athenz.md
site2/website/versioned_docs/version-2.4.2/security-athenz.md
site2/website/versioned_docs/version-2.6.0/security-athenz.md
site2/website/versioned_docs/version-2.6.1/security-athenz.md
site2/website/versioned_docs/version-2.6.2/security-athenz.md

-  backport #10079 to branch-2.7

Upgrade athenz version and remove yahoo.bintray.com repository

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AbstractStructSchema.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java

[schema] simplify code

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/PolicyName.java

[Issue 7899][Broker] support PolicyName and authz on ns new routes

---

site2/website/data/team.js

>k2la | Yuto Furuta | pulsar
http://people.apache.org/committer-index.html

Add Yuto Furuta as committer in the team page

---

README.md
src/idea-code-style.xml

* Added sections in the README
- The public API: (yes / no) no
- The schema: (yes / no / don't know) no
- The default values of configurations: (yes / no) no
- The wire protocol: (yes / no) no
- The rest endpoints: (yes / no) no
- The admin cli options: (yes / no) no
- Anything that affects deployment: (yes / no / don't know) no
- Does this pull request introduce a new feature? (yes / no) no
- If a feature is not documented yet in this PR, …

Add instructions to configure code style and checkstyle for IDEA

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/coordination/impl/LeaderElectionImpl.java

**Motivation**
fix log about LeaderElection

fix log about LeaderElection

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java

**Motivation**
handle startMessageRollbackDurationSec when get durable subscription

get durable subscription without handling startMessageRollbackDurationSec

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/GracefulExecutorServicesShutdownTest.java

**Motivation**
fix flaky test GracefulExecutorServicesShutdownTest.shouldTerminateWhenFutureIsCancelled

Fix flaky test GracefulExecutorServicesShutdownTest.shouldTerminateWhenFutureIsCancelled

---

pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/stats/SinkStatsManager.java
pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/stats/SourceStatsManager.java

Fixes #10546
fix sink/source exception stats

[Issue 10546] fix sink/source exception stats

---

site2/website/blog/2021-05-13-Apache-Pulsar-2-7-2.md

This is the PR to add a blog page for the 2.7.2 relase

Apache Pulsar 2.7.2 blog page

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleSchemaTest.java

Modifications:
Add more test cases about using KeyValueSchema and Schema.AUTO_CONSUME().
These tests cover:
- KeyEncodingType.SEPARATED vs INLINE
- null key
- null value

[Java][Schema] AUTO_CONSUME/GenericObject: add more test cases about KeyValue and NULL values

---

site2/docs/sql-deployment-configurations.md
site2/website/versioned_docs/version-2.2.0/sql-deployment-configurations.md
site2/website/versioned_docs/version-2.5.0/sql-deployment-configurations.md
site2/website/versioned_docs/version-2.6.0/sql-deployment-configurations.md
site2/website/versioned_docs/version-2.6.1/sql-deployment-configurations.md
site2/website/versioned_docs/version-2.6.2/sql-deployment-configurations.md
site2/website/versioned_docs/version-2.6.3/sql-deployment-configurations.md
site2/website/versioned_docs/version-2.7.0/sql-deployment-configurations.md
site2/website/versioned_docs/version-2.7.1/sql-deployment-configurations.md
site2/website/versioned_docs/version-2.7.2/sql-deployment-configurations.md

Fixes #10620 
**Motivation** 
fix cmd in doc

[doc] fix cmd in doc

---

pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java

This patch restored two tests that were not running: testKeyValueSchemaWithStructs with INLINE and SEPARATED KeyEncodingType
The patch also adds a test about Null Key behaviour.
Relates to #10625

[Java][Schema] Enabled disabled tests about AutoConsume and KeyValue and add test case about null keys

---

site2/tools/docker-build-site.sh

Fix: #10676
Node version has been upgraded from 10.24.0 to 14.17.0

feat: update website docker image(upgrade node version)

---

site2/website/versioned_docs/version-2.7.2/deploy-bare-metal-multi-cluster.md
site2/website/versioned_docs/version-2.7.2/deploy-bare-metal.md
site2/website/versioned_docs/version-2.7.2/getting-started-standalone.md

https://github.com/apache/pulsar/runs/2644824512?check_suite_focus=true
```
Error: No 'original_id' field found in /pulsar/site2/website/versioned_docs/version-2.7.2/deploy-bare-metal-multi-cluster.md. Perhaps you forgot to add it when importing prior versions of your docs?
at forEach (/pulsar/site2/website/node_modules/docusaurus/lib/server/versionFallback.js:64:11)
at Array.forEach (<anonymous>)
at Object.<anonymous> (/pulsar/site2/website/node_modules/docusaurus/lib/server/versionFallback.js:52:7)
at Module._compile (internal/modules/cjs/loader.js:1068:30)
at Module._compile (/pulsar/site2/website/node_modules/pirates/lib/index.js:99:24)
at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
at Object.newLoader [as .js] …
```

[Hotfix][Docs]Fixed document missing original

---

site2/docs/deploy-monitoring.md
site2/website/versioned_docs/version-2.7.2/deploy-monitoring.md

[Doc] add metrics for the total non contiguous deleted messages range

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java

Fixes #<xyz>
```
if (log.isDebugEnabled()) {
log.debug("[{}] [{}] Removing decoder from pipeline", inboundChannel, outboundChannel);
}
```
The above log should be output when the decoder is actually removed.
Adjust the location of the log.
- Dependencies (does it add or upgrade …

[pulsar-proxy]Adjust the location of logger.debug

---

site2/website/versioned_docs/version-2.7.3/reference-metrics.md

Same to https://github.com/apache/pulsar/pull/10695

[Doc] Add descriptions for managed cursor acknowledgment state (2.7.3)

---

pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/LongPairRangeSet.java

Fix repeated iterator generation

Fix repeated iterator generation

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TransactionsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/v3/AdminApiTransactionTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Transactions.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TransactionsImpl.java

Transaction admin api add synchronize method
add synchronize method
The admin cli options: (yes)

[Transaction] Transaction admin api add synchronize method.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdClusters.java
pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdClusters.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/ClusterData.java

Fixes #10693
use unify configuration from remote cluster for geo-replicator

[issue 10693] use unify configuration from remote cluster for geo-replicator

---

site2/docs/transaction-api.md

Modify transaction doc.
Now transaction is production ready, so delete Developer Preview.

[Doc] Modify transaction doc.

---

pom.xml
pulsar-sql/presto-distribution/LICENSE
pulsar-sql/presto-distribution/pom.xml
pulsar-sql/presto-distribution/src/assembly/assembly.xml
pulsar-sql/presto-distribution/src/main/resources/launcher.properties
tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/PrestoWorkerContainer.java

Fixes #10727
we want to use a different version sometimes, it's laborious to change `pom.xml`, and it's better to support set any version for pulsar by maven command.
change the parent dependency for pulsar-presto-connector, and the version could be affected by 'mvn versions:set -DnewVersion=' command.

Make Pulsar-SQL module to be a child of Pulsar main project

---

conf/broker.conf
conf/standalone.conf
deployment/terraform-ansible/templates/broker.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-client-cpp/test-conf/standalone-ssl.conf
pulsar-client-cpp/test-conf/standalone.conf
pulsar-client-cpp/tests/authentication.conf
pulsar-client-cpp/tests/standalone.conf

[Conf] Fix typo; switch ledged to ledger

---

distribution/server/src/assemble/LICENSE.bin.txt
pom.xml
pulsar-sql/presto-distribution/LICENSE

Fixes #10798 
Related to: #10266
Rollback netty-tc-native version to 2.0.33.Final

Rollback netty-tc-native version to 2.0.33.Final

---

site2/docs/functions-overview.md
site2/website/versioned_docs/version-2.1.0-incubating/functions-overview.md
site2/website/versioned_docs/version-2.1.1-incubating/functions-overview.md
site2/website/versioned_docs/version-2.2.0/functions-overview.md
site2/website/versioned_docs/version-2.2.1/functions-overview.md
site2/website/versioned_docs/version-2.3.1/functions-overview.md
site2/website/versioned_docs/version-2.4.0/functions-overview.md
site2/website/versioned_docs/version-2.4.1/functions-overview.md
site2/website/versioned_docs/version-2.4.2/functions-overview.md
site2/website/versioned_docs/version-2.5.0/functions-overview.md
site2/website/versioned_docs/version-2.5.1/functions-overview.md
site2/website/versioned_docs/version-2.5.2/functions-overview.md
site2/website/versioned_docs/version-2.6.0/functions-overview.md
site2/website/versioned_docs/version-2.6.1/functions-overview.md
site2/website/versioned_docs/version-2.6.2/functions-overview.md
site2/website/versioned_docs/version-2.6.3/functions-overview.md
site2/website/versioned_docs/version-2.6.4/functions-overview.md
site2/website/versioned_docs/version-2.7.0/functions-overview.md
site2/website/versioned_docs/version-2.7.1/functions-overview.md
site2/website/versioned_docs/version-2.7.2/functions-overview.md
site2/website/versioned_docs/version-2.7.3/functions-overview.md

Error in python sample codes here.
Modify python sample codes about pulsar function in the following files.
`site2/docs/functions-overview.md`
`site2/docs/version-*/functions-overview.md`

[DOC] Fix pulsar function python example code error

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java

*It would be nice to measure and print the number of seconds it takes the broker to bootstrap.*
*Measure and log the elapsed time between the start of pulsar service instance and the broker service ready.*
- Does this pull request introduce a new feature? (yes / no) yes
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) not …

Log number of seconds it takes the broker to bootstrap

---

conf/broker.conf
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java

*Motivation*
Provide a flag to disable managed ledger metrics

Provide a flag to disable managed ledger metrics

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/SourcesBase.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SinksImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/SourcesImpl.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/WorkerImpl.java

Message test is incorrect
Fix error message text.

Fix Error Message

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java

Fixes # throwable exception not thrown.
I found some throwable exception that not thrown, maybe it's a bug.

[Fixed]  #throwable exception not thrown.

---

site2/docs/functions-overview.md
site2/website/versioned_docs/version-2.4.1/functions-overview.md
site2/website/versioned_docs/version-2.4.2/functions-overview.md
site2/website/versioned_docs/version-2.5.0/functions-overview.md
site2/website/versioned_docs/version-2.5.1/functions-overview.md
site2/website/versioned_docs/version-2.5.2/functions-overview.md
site2/website/versioned_docs/version-2.6.0/functions-overview.md
site2/website/versioned_docs/version-2.6.1/functions-overview.md
site2/website/versioned_docs/version-2.6.2/functions-overview.md
site2/website/versioned_docs/version-2.6.3/functions-overview.md
site2/website/versioned_docs/version-2.6.4/functions-overview.md
site2/website/versioned_docs/version-2.7.0/functions-overview.md
site2/website/versioned_docs/version-2.7.1/functions-overview.md
site2/website/versioned_docs/version-2.7.2/functions-overview.md
site2/website/versioned_docs/version-2.7.3/functions-overview.md

Fixes a dead link `#state-storage` in `functions-overview.md`
Use the correct link.

[docs] Fix a bad link in functions overview

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java

Fixes # throwable exception not thrown.
Motivation
I found some throwable exception that not thrown, maybe it's a bug.

Fixes # throwable exception not thrown.

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaceIsolationPolicy.java
pulsar-client-tools/src/test/java/org/apache/pulsar/admin/cli/TestCmdNamespaceIsolationPolicy.java

I fixed an incorrect use list.remove method and add a test.

Fixed #fixed incorrect use list.remove method.

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ParserProxyHandler.java

String is immutable objects and will affect performance when connected in a loop.

Fixed # fixed string concatation in loop.

---

pulsar-broker/src/test/java/org/apache/pulsar/common/naming/NamespaceBundleSplitAlgorithmTest.java
pulsar-broker/src/test/java/org/apache/pulsar/common/naming/RangeEquallyDivideBundleSplitAlgorithmTest.java

Supplementary test for this project.

Feat # Add some test for NamespaceBundleSplitAlgorithmTest

---

site2/docs/tiered-storage-filesystem.md
site2/website/versioned_docs/version-2.7.0/tiered-storage-filesystem.md
site2/website/versioned_docs/version-2.7.1/tiered-storage-filesystem.md
site2/website/versioned_docs/version-2.7.2/tiered-storage-filesystem.md
site2/website/versioned_docs/version-2.7.3/tiered-storage-filesystem.md
site2/website/versioned_docs/version-2.8.0/tiered-storage-filesystem.md

fileSystemProfilePath : For File System Storage, file system profile path
offloadersDirectory: The directory for all the offloader implementations

Fix wrong configuration name

---

site2/docs/reference-configuration.md
site2/website/versioned_docs/version-2.7.0/reference-configuration.md
site2/website/versioned_docs/version-2.7.1/reference-configuration.md
site2/website/versioned_docs/version-2.7.2/reference-configuration.md
site2/website/versioned_docs/version-2.7.3/reference-configuration.md
site2/website/versioned_docs/version-2.8.0/reference-configuration.md

Fixes #10990
Change the default value of `httpServerPort` to `8080`.

[Issue 10990] Fix the default value of httpServerPort in reference conf

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java

Fixes 10996
MutliConsumer not released after calling method unsubscribe, and can't be released by other method.
Make MutliConsumer release completely on method unsuscribe.
Same test as in ISSUE 10996, and jmap shows nothing.

[Issue 10996]  release multiTopicsConsumerImpl when unsubscribe

---

site2/docs/reference-configuration.md
site2/website/versioned_docs/version-2.1.0-incubating/reference-configuration.md
site2/website/versioned_docs/version-2.1.1-incubating/reference-configuration.md
site2/website/versioned_docs/version-2.2.0/reference-configuration.md
site2/website/versioned_docs/version-2.2.1/reference-configuration.md
site2/website/versioned_docs/version-2.3.0/reference-configuration.md
site2/website/versioned_docs/version-2.3.1/reference-configuration.md
site2/website/versioned_docs/version-2.3.2/reference-configuration.md
site2/website/versioned_docs/version-2.4.0/reference-configuration.md
site2/website/versioned_docs/version-2.4.1/reference-configuration.md
site2/website/versioned_docs/version-2.4.2/reference-configuration.md
site2/website/versioned_docs/version-2.5.0/reference-configuration.md
site2/website/versioned_docs/version-2.5.1/reference-configuration.md
site2/website/versioned_docs/version-2.5.2/reference-configuration.md
site2/website/versioned_docs/version-2.6.0/reference-configuration.md
site2/website/versioned_docs/version-2.6.1/reference-configuration.md
site2/website/versioned_docs/version-2.6.2/reference-configuration.md
site2/website/versioned_docs/version-2.6.3/reference-configuration.md
site2/website/versioned_docs/version-2.6.4/reference-configuration.md
site2/website/versioned_docs/version-2.7.0/reference-configuration.md
site2/website/versioned_docs/version-2.7.1/reference-configuration.md
site2/website/versioned_docs/version-2.7.2/reference-configuration.md
site2/website/versioned_docs/version-2.7.3/reference-configuration.md
site2/website/versioned_docs/version-2.8.0/reference-configuration.md

Fix https://github.com/apache/pulsar/issues/10932

[Doc] Add explanations for inactive topics

---

pulsar-broker/src/test/java/org/apache/pulsar/common/naming/TopicCountEquallyDivideBundleSplitAlgorithmTest.java

add test for TopicCountEquallyDivideBundleSplitAlgorithm.

[Tests] Add test for TopicCountEquallyDivideBundleSplitAlgorithm.

---

pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/PrimitiveSchemaTest.java

Fixes #11037
Move the initialisation of the dataset inside a method

Issue #11037: Fix flaky test PrimitiveSchemaTest

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupConfigListenerTest.java

Fixes #11045
Fixes flaky test ResourceGroupConfigListenerTest
- remove `atMost` and rely on Awaitility default of 10 seconds.
- refactor deletion test to not use Thread.sleep
- first check that all resource groups exist
- then delete

[Tests] Fix flaky test ResourceGroupConfigListenerTest

---

site2/website/sidebars.json
site2/website/versioned_sidebars/version-2.1.0-incubating-sidebars.json
site2/website/versioned_sidebars/version-2.1.1-incubating-sidebars.json
site2/website/versioned_sidebars/version-2.2.0-sidebars.json
site2/website/versioned_sidebars/version-2.2.1-sidebars.json
site2/website/versioned_sidebars/version-2.3.0-sidebars.json
site2/website/versioned_sidebars/version-2.3.1-sidebars.json
site2/website/versioned_sidebars/version-2.3.2-sidebars.json
site2/website/versioned_sidebars/version-2.4.0-sidebars.json
site2/website/versioned_sidebars/version-2.4.1-sidebars.json
site2/website/versioned_sidebars/version-2.4.2-sidebars.json
site2/website/versioned_sidebars/version-2.5.0-sidebars.json
site2/website/versioned_sidebars/version-2.5.1-sidebars.json
site2/website/versioned_sidebars/version-2.5.2-sidebars.json
site2/website/versioned_sidebars/version-2.6.0-sidebars.json
site2/website/versioned_sidebars/version-2.6.1-sidebars.json
site2/website/versioned_sidebars/version-2.6.2-sidebars.json
site2/website/versioned_sidebars/version-2.6.3-sidebars.json
site2/website/versioned_sidebars/version-2.6.4-sidebars.json
site2/website/versioned_sidebars/version-2.7.0-sidebars.json
site2/website/versioned_sidebars/version-2.7.1-sidebars.json
site2/website/versioned_sidebars/version-2.7.2-sidebars.json
site2/website/versioned_sidebars/version-2.7.3-sidebars.json
site2/website/versioned_sidebars/version-2.8.0-sidebars.json
site2/website/versioned_sidebars/version-2.8.1-sidebars.json

Improve documentation consistency.
Change capitalization of sidebar headers to title case.

[docs] Capitalize sidebar headers

---

site2/docs/getting-started-helm.md
site2/website/versioned_docs/version-2.6.0/getting-started-helm.md
site2/website/versioned_docs/version-2.6.1/getting-started-helm.md
site2/website/versioned_docs/version-2.6.2/getting-started-helm.md
site2/website/versioned_docs/version-2.6.3/getting-started-helm.md
site2/website/versioned_docs/version-2.6.4/getting-started-helm.md
site2/website/versioned_docs/version-2.7.0/getting-started-helm.md
site2/website/versioned_docs/version-2.7.1/getting-started-helm.md
site2/website/versioned_docs/version-2.7.2/getting-started-helm.md
site2/website/versioned_docs/version-2.7.3/getting-started-helm.md
site2/website/versioned_docs/version-2.8.0/getting-started-helm.md
site2/website/versioned_docs/version-2.8.1/getting-started-helm.md

Fixes #<xyz>
On the docs [Get started in Kubernetes](https://pulsar.apache.org/docs/en/kubernetes-helm/) i found the indentation is incorrect like 
I fixed the indentation issue in Get started in Kubernetes docs.
*(or)*
*(or)*
*(example:)*
- *Extended …

fix: markdown indentation in getting-started-helm

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/TopicsImpl.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java

```
Batch Message ID: 10:1:0
Properties:
"X-Pulsar-batch-size    26825"
"X-Pulsar-num-batch-message    26"
"publish-time    2021-06-25T16:00:40.919+08:00"
```

Print message metadata when getting message by id

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

Fixes #11103
Master Issue: #11103
See this issue: #11103
Due to number of wrong parameters.
- Number of parameters to fix errors

[ Issues 11103 ] Fixed Compile error

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicFromMessageTest.java

Fix Flaky-test: [TopicFromMessageTest].[testMultiTopicConsumerBatchShortName

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroup.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/RGUsageMTAggrWaitForAllMesgs.java

Fixes #<xyz>
Metrics for some resource-groups functionality.
Added some Prometheus metrics for resource-groups, and did basic sanity tests of that functionality in a UT.
- Added a test (RGUsageMTAggrWaitForAllMesgs) with producers/consumers to check usage statistics and Prometheus metrics.
- …

[PIP-82] [pulsar-broker] Resource group metrics

---

pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java
pulsar-functions/utils/src/test/java/org/apache/pulsar/functions/utils/SinkConfigUtilsTest.java
pulsar-functions/worker/src/test/java/org/apache/pulsar/functions/worker/rest/api/v3/SinkApiV3ResourceTest.java

Fixes #10579
Add the list of topic in field `SinkConfig.inputs`.

[Issue 10579] Fix inputs to return a list of topic

---

site2/website/versioned_docs/version-2.7.0/io-debezium-source.md
site2/website/versioned_docs/version-2.7.1/io-debezium-source.md
site2/website/versioned_docs/version-2.7.2/io-debezium-source.md
site2/website/versioned_docs/version-2.7.3/io-debezium-source.md
site2/website/versioned_docs/version-2.8.0/io-debezium-source.md
site2/website/versioned_docs/version-2.8.1/io-debezium-source.md

Backported docu change from https://github.com/apache/pulsar/pull/10978

[docs] backport debezium source docu

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java

Fix Flaky-test: [LoadBalancerTest].[testBrokerRanking]

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolTest.java

Use Awaitility to instead of Thread sleep
- Use Awaitility to instead of Thread sleep

[ Tests ] Use Awaitility to instead of Thread sleep

---

pulsar-config-validation/src/main/java/org/apache/pulsar/config/validation/ValidatorImpls.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java

Fixed some incorrect usage methods.
- Fixed some useless loops.
- Fixed incorrect usage of Array tostring method.

[ Functions ] Fixed some incorrect usage methods.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java

1. Adjust the implementation of getDynamicConfigurationDouble and DynamicConfigurationBoolean.
2. Fix typos.

Adjust the implementation of getDynamicConfigurationDouble and DynamicConfigurationBoolean

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/web/MaxRequestSizeFilterTest.java

Add new unit test
- Add new unit test for MaxRequestSizeFilter

[ Tests ] Add new test for MaxRequestSizeFilter

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java

clear redundant code

---

pulsar-client-tools-test/src/test/java/org/apache/pulsar/client/cli/PulsarClientToolTest.java

Fixed copy-paste error in the test.
thanks to @lhotari  pointed out this mistake.
- Fixed copy-paste error in the test

[ Tests ] Fixed copy-paste error in the test

---

site2/docs/reference-pulsar-admin.md

[https://pulsar.apache.org/docs/en/next/pulsar-admin] pulsar admin website miss tenants head

[Doc] fix pulsar admin website format

---

pulsar-zookeeper-utils/src/test/java/org/apache/pulsar/zookeeper/ZookeeperServerTest.java

Minor refactor for ZookeeperServerTest

[test] Minor refactor for ZookeeperServerTest.

---

pulsar-broker/src/main/java/org/apache/pulsar/utils/CmdGenerateDocumentation.java
pulsar-broker/src/test/java/org/apache/pulsar/utils/CmdTest.java

Master Issue: #10041
Generate documentation of broker automatically.

Generate documentation of broker automatically.

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/TimeAverageBrokerDataTest.java

add test for TimeAverageBrokerData

[Tests] Add test for TimeAverageBrokerData

---

pulsar-client-tools/src/main/java/org/apache/pulsar/client/cli/CmdConsume.java

Fixed #fixed incorrect use toString method.
Motivation
I found an incorrect use toString method. I think it's maybe a bug.

Fixed #fixed incorrect use toString method.

---

site2/docs/getting-started-standalone.md

Motivation
Update program output
Make the document easy to read
Modifications
Modify the output of start
Modify the output of the massage having been successfully consumed
Modify the output of the message having been successfully published

[docs]Update getting-started-standalone.md

---

site2/docs/getting-started-docker.md

Update program output
Make the document easy to read
Modify the command to start pulsar in docker
Modify the output of start
Modify the output  of topic statistics

[docs]Update getting-started-docker.md

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/KeySharedSubscriptionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/TopicReaderTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/v1/V1_ProducerConsumerTest.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/ConsumerImplTest.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyServiceStarterTest.java

[Branch-2.7] Fix branch-2.7 test.

---

site2/docs/reference-configuration.md
site2/website/versioned_docs/version-2.1.0-incubating/reference-configuration.md
site2/website/versioned_docs/version-2.1.1-incubating/reference-configuration.md
site2/website/versioned_docs/version-2.2.0/reference-configuration.md
site2/website/versioned_docs/version-2.2.1/reference-configuration.md
site2/website/versioned_docs/version-2.3.0/reference-configuration.md
site2/website/versioned_docs/version-2.3.1/reference-configuration.md
site2/website/versioned_docs/version-2.3.2/reference-configuration.md
site2/website/versioned_docs/version-2.4.0/reference-configuration.md
site2/website/versioned_docs/version-2.4.1/reference-configuration.md
site2/website/versioned_docs/version-2.4.2/reference-configuration.md
site2/website/versioned_docs/version-2.5.0/reference-configuration.md
site2/website/versioned_docs/version-2.5.1/reference-configuration.md
site2/website/versioned_docs/version-2.5.2/reference-configuration.md
site2/website/versioned_docs/version-2.6.0/reference-configuration.md
site2/website/versioned_docs/version-2.6.1/reference-configuration.md
site2/website/versioned_docs/version-2.6.2/reference-configuration.md
site2/website/versioned_docs/version-2.6.3/reference-configuration.md
site2/website/versioned_docs/version-2.6.4/reference-configuration.md
site2/website/versioned_docs/version-2.7.0/reference-configuration.md
site2/website/versioned_docs/version-2.7.1/reference-configuration.md
site2/website/versioned_docs/version-2.7.2/reference-configuration.md
site2/website/versioned_docs/version-2.7.3/reference-configuration.md
site2/website/versioned_docs/version-2.8.0/reference-configuration.md
site2/website/versioned_docs/version-2.8.1/reference-configuration.md

Fix a typo and duplicate entries in Configuration documentation.
Fix a typo and duplicate entries in Configuration documentation.
- Dependencies (does it add or upgrade a dependency): **no**
- The public API: **no**
- The schema: **no**
- The default values of configurations: **no**
- The wire protocol: **no**
- The rest endpoints: **no**
- The admin cli options: **no**
- Anything that affects deployment: **no**
- Does this pull request introduce a new feature?  **no**
- If yes, how is the feature documented? **N/A**
- If a feature is not applicable for documentation, explain why? **This change simply fixes a typo and duplicate entries in Configuration documentation.**
- If a feature is not documented yet in this …

Fix typo and duplicate config doc entries

---

site2/docs/helm-deploy.md
site2/website/versioned_docs/version-2.6.0/helm-deploy.md
site2/website/versioned_docs/version-2.7.0/helm-deploy.md
site2/website/versioned_docs/version-2.7.1/helm-deploy.md
site2/website/versioned_docs/version-2.7.2/helm-deploy.md
site2/website/versioned_docs/version-2.7.3/helm-deploy.md
site2/website/versioned_docs/version-2.8.0/helm-deploy.md
site2/website/versioned_docs/version-2.8.1/helm-deploy.md

In the [helm-deploy](https://pulsar.apache.org/docs/en/helm-deploy/#deploy-pulsar-cluster-using-helm), the sample uses `helm upgrade --install pulsar apache/pulsar` command which is incorrect. It should be `helm install` rather than `helm upgrade`. 
Update the sample command. 
No code change.

fix: incorrect command in helm-deploy docs

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java

Simplify code of `ManagedLedger.getManagedLedgerInfo()`
unify the method of generating `ManagedLedgerInfo` 
This change is a  code cleanup without any test coverage.
- The default values of configurations: （no)

[hotfix] simplify code

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdClusters.java

fix mistake when resolve the conflicts in #10751

fix add listenerName for geo-replicator

---

pulsar-broker/src/test/java/org/apache/pulsar/functions/worker/PulsarFunctionPublishTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java

Fixes #10720
fix update user config

[function] fix update user config

---

pulsar-client-cpp/lib/ClientConnection.cc

When the Pulsar C++ library was deployed to a Windows server, the program would crash after the connection is established. Though it works on Windows 10. It's caused by the Boost socket `set_option` method. Some socket options are not portable like `TCP_KEEPCNT` and `TCP_KEEPINTVL`, which are defined in system headers. The default behavior of `set_option` method is throwing an exception if the socket option is not supported.
Replace the `set_option` calls with another overload signature that stores the error into a `boost::system::error_code` instead of throwing a `boost::system::system_error`. For Boost's builtin socket options, use warning level logs. For platform dependent socket options, use debug level logs.
References:
- https://www.boost.org/doc/libs/1_76_0/doc/html/boost_asio/refer …

[C++] Avoid throwing exceptions when setting socket option

---

site2/docs/reference-cli-tools.md
site2/website/versioned_docs/version-2.6.0/reference-cli-tools.md
site2/website/versioned_docs/version-2.6.1/reference-cli-tools.md
site2/website/versioned_docs/version-2.6.2/reference-cli-tools.md
site2/website/versioned_docs/version-2.6.3/reference-cli-tools.md
site2/website/versioned_docs/version-2.6.4/reference-cli-tools.md
site2/website/versioned_docs/version-2.7.0/reference-cli-tools.md
site2/website/versioned_docs/version-2.7.1/reference-cli-tools.md
site2/website/versioned_docs/version-2.7.2/reference-cli-tools.md
site2/website/versioned_docs/version-2.7.3/reference-cli-tools.md
site2/website/versioned_docs/version-2.8.0/reference-cli-tools.md
site2/website/versioned_docs/version-2.8.1/reference-cli-tools.md

Add missing parameters for `pulsar-perf` and `zookeeper-shell`

Add missing parameters for pulsar-perf

---

site2/docs/functions-worker.md
site2/website/versioned_docs/version-2.6.0/functions-worker.md
site2/website/versioned_docs/version-2.6.1/functions-worker.md
site2/website/versioned_docs/version-2.6.2/functions-worker.md
site2/website/versioned_docs/version-2.6.3/functions-worker.md
site2/website/versioned_docs/version-2.6.4/functions-worker.md
site2/website/versioned_docs/version-2.7.0/functions-worker.md
site2/website/versioned_docs/version-2.7.1/functions-worker.md
site2/website/versioned_docs/version-2.7.2/functions-worker.md
site2/website/versioned_docs/version-2.7.3/functions-worker.md
site2/website/versioned_docs/version-2.8.0/functions-worker.md
site2/website/versioned_docs/version-2.8.1/functions-worker.md

Add docs about how to use stateful functions in pulsar

Add docs about how to use stateful functions in pulsar

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java

Cherry-picking https://github.com/apache/pulsar/pull/10762 broke the Delayed messages feature in branch-2.7.
This patch restores the method that has been dropped

Branch-2.7 fix Delayed Messages

---

site2/docs/adaptors-kafka.md

Added documentation for encryption support in pulsar-kafka adapter : https://github.com/apache/pulsar-adapters/pull/26

[pulsar-doc] Document pulsar-kafka adapter encryption support

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java

- Netty ByteBufs for commit and abort markers currently leak direct memory
- `ManagedLedgerImpl.asyncAddEntry` will increase the reference count by calling `.retain()` for the marker message's ByteBuf (in `OpAddEntry.create`) and therefore the reference count has to be decreased with the call to `.release()` after  the `asyncAddEntry` call.
- call `.release()` in try-finally block for commit and abort markers after the `asyncAddEntry` call

[Transaction] Fix direct memory leak related to commit and abort markers

---

pulsar-proxy/src/main/java/org/apache/pulsar/proxy/util/CmdGenerateDocumentation.java
pulsar-proxy/src/test/java/org/apache/pulsar/proxy/util/CmdTest.java

Master Issue: #10041
The config object has already been annotated.
We just need to add it to the auto-generated list

Generate documentation of PulsarProxy automatically

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BkEnsemblesTestBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/RackAwareTest.java

Fix #11349 .
This is a bug fix, no need to update doc

Flaky-test: RackAwareTest.testPlacement

---

site2/docs/security-oauth2.md

Fixes #https://github.com/apache/pulsar/issues/11397
Make docs clearer
make java code sample match the actual API

[issues 11397][Docs] make java code sample match the actual API

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java

Fix #11393 .
Documentation
This is a bug fix, no need to update doc

Flaky-test: NamespacesTest.testSubscribeRate

---

pulsar-broker/src/main/java/org/apache/pulsar/utils/CmdGenerateDocumentation.java
pulsar-broker/src/test/java/org/apache/pulsar/utils/CmdTest.java

Master Issue: #10041
The config object has  already  been annotated.
We just need to add it to the auto-generated list

Generate documentation of Client automatically

---

pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java

Fixes #11200
When a metadata resource is updated via pulsar-admin command, on brokers that did not handle the admin API, the cache can get in to an inconsistent state. getData() will then result in a stale cache data to be returned. And the broker never gets the update later on.
In the zookeeper watch callback, there is a race condition between the cache getting updated via the refresh() call here. 
https://github.com/apache/pulsar/blob/c080c845d7b3a680e7af9511ef38aff3781185a8/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/cache/impl/MetadataCacheImpl.java#L271
If a subsystem does a getDataAsync() in the watch callback, the data returned could be stale data in the cache. The bigger issue is that this broker never gets a chance to see the updated data (since the watch event is …

[Issue 11200] [pulsar-metadata] Unit test to verify Metadata cache consistency across brokers

---

pulsar-function-go/go.mod
pulsar-function-go/go.sum
pulsar-function-go/pf/mockMessage_test.go

Upgrade go client version to 0.6.0

[Go Functions] Upgrade go client version to 0.6.0

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java

Do not create system topic for heartbeat namespace

Do not create system topic for heartbeat namespace

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java

Fixes #11395
This is a fix for test, no need doc update.

Flaky-test: PersistentTopicStreamingDispatcherE2ETest.testMessageExpiryWithTopicMessageTTL

---

site2/docs/admin-api-namespaces.md

Missing keyword namespaces，Result in failure to execute

fix required params  to set-retention 

---

site2/docs/client-libraries-cpp.md
site2/website/versioned_docs/version-2.8.0/txn-how.md
site2/website/versioned_docs/version-2.8.0/txn-monitor.md
site2/website/versioned_docs/version-2.8.0/txn-use.md
site2/website/versioned_docs/version-2.8.0/txn-what.md
site2/website/versioned_docs/version-2.8.0/txn-why.md
site2/website/versioned_docs/version-2.8.1/txn-how.md
site2/website/versioned_docs/version-2.8.1/txn-monitor.md
site2/website/versioned_docs/version-2.8.1/txn-use.md
site2/website/versioned_docs/version-2.8.1/txn-what.md
site2/website/versioned_docs/version-2.8.1/txn-why.md
site2/website/versioned_sidebars/version-2.8.0-sidebars.json
site2/website/versioned_sidebars/version-2.8.1-sidebars.json

- Add guides for txn for 2.8.0 and 2.8.1 (https://github.com/apache/pulsar/pull/11235).
- Add docs for cpp client (https://github.com/apache/pulsar/pull/11388).
Local preview:

[Doc] Add guides for txn and cpp client

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

Related to https://github.com/apache/pulsar/pull/11487

Fix some topic policy operation without backoff

---

pulsar-client-cpp/python/pulsar/schema/schema_avro.py

when build python doc website
so fix it.

Fix python doc generate

---

site2/docs/reference-configuration.md

Add docs for broker additional servlet (https://github.com/apache/pulsar/pull/11498).

[Docs] Add broker additional servlet configuration

---

site2/docs/helm-deploy.md
site2/docs/helm-install.md
site2/docs/helm-overview.md
site2/docs/helm-prepare.md

Motivation
Update program output
Make the document easy to read

[Docs]Update Kubernetes (Helm)

---

site2/docs/client-libraries-python.md

Revise official documents to make them easy to understand and use
- Correction of incorrect document
- Add hyperlink jump for file
- Correct inappropriate punctuation
- Correction output
- The schema: ( no )

[Docs]Update docs for Client libraries Python

---

site2/docs/deploy-bare-metal.md

Revise official documents to make them easy to understand and use
Update deploy-bare-metal.md

[docs]Update deploy-bare-metal.md

---

content/.asf.yaml

Fix pulsar website publish .add `.asf.yaml`  config doc : https://s.apache.org/asfyamlpublishing discussion https://the-asf.slack.com/archives/CBX4TSBQ8/p1628582435202100

Fix pulsar website publish

---

site2/docs/deploy-bare-metal-multi-cluster.md

Revise official documents to make them easy to understand and use
Update deploy-bare-metal-multi-cluster.md

[docs] Update deploy-bare-metal-multi-cluster.md

---

pulsar-client-cpp/include/pulsar/c/result.h

**Motivation**
C binding ERROR codes are not in Sync with C++, that makes error handling at C side difficult.
**Change**
Take C++ error code and create corresponding C error code.
**Documentation**
No separate documentation needed.  As this PR just seeks to bring C side error code at par with C++

Sync up C error code with C++

---

distribution/server/src/assemble/LICENSE.bin.txt
pulsar-sql/presto-distribution/LICENSE

[Branch-2.8]fix license mismatch

---

pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClient.java
pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java

Fixes #11628 
* Use random index names and delete it at the end of each test
* Try to fix the flaky test testBulkBlocking

[Issue #11628][ES-Sink] Fix flaky tests

---

site2/docs/adaptors-spark.md
site2/docs/deploy-monitoring.md
site2/docs/io-connectors.md
site2/website/versioned_docs/version-2.7.0/deploy-monitoring.md
site2/website/versioned_docs/version-2.7.1/deploy-monitoring.md
site2/website/versioned_docs/version-2.7.2/deploy-monitoring.md
site2/website/versioned_docs/version-2.7.3/deploy-monitoring.md
site2/website/versioned_docs/version-2.8.0/adaptors-spark.md
site2/website/versioned_docs/version-2.8.0/deploy-monitoring.md
site2/website/versioned_docs/version-2.8.0/io-connectors.md
site2/website/versioned_docs/version-2.8.1/adaptors-spark.md
site2/website/versioned_docs/version-2.8.1/deploy-monitoring.md
site2/website/versioned_docs/version-2.8.1/io-connectors.md

Remove the broken links and link to the third part website.

[docs] Remove broken links

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/web/ExceptionHandler.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PreInterceptFilter.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiSchemaTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/intercept/InterceptFilterOutTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/web/ExceptionHandlerTest.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/BaseResource.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/PackagesImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SinksImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SourcesImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/WorkerImpl.java
pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java

Fixes #11649
This is a bug fix, and do not need to update doc.

[Broker Interceptor] Fix Pulsar didn't respond error messages when throw InterceptException

---

bin/bookkeeper
pulsar-broker/src/main/java/org/apache/pulsar/broker/storage/ManagedLedgerStorage.java

Replace `bookkeper` with `bookkeeper` in bin/bookkeeper

Replace bookkeper with bookkeeper in bin/bookkeeper

---

site2/website/versioned_docs/version-2.7.0/concepts-transactions.md
site2/website/versioned_docs/version-2.7.1/concepts-transactions.md
site2/website/versioned_docs/version-2.7.2/concepts-transactions.md
site2/website/versioned_docs/version-2.7.3/concepts-transactions.md
site2/website/versioned_docs/version-2.8.0/concepts-transactions.md
site2/website/versioned_docs/version-2.8.1/concepts-transactions.md

Fix typos in concepts-transactions.md

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java

Avoid to cal getMaximumRolloverTimeMs everytime

Avoid to cal getMaximumRolloverTimeMs everytime

---

pulsar-broker/src/test/java/org/apache/pulsar/client/impl/LookupRetryTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ClientCnx.java

Lookups and PartitionMetadataRequests(PMR) will get TooManyRequest if
the broker they are talking to is making a lot of async requests to ZK
and thus accepting and parking a lot of requests. This happens if
there is a herding of clients requesting a lot of different
topics. However, if there are few topics, the result will be cached
and served synchronously. If a herd occurs under these conditions,
clients will get a timeout as the i/o handler threads could be
saturated and unable to serve the request in time. In certain
scenarios, such as when the service url is a VIP or load balancer, the
retry request will hit the exact same endpoint. If the broker serving
is overloaded, or just plain broken, the client will get the same
result. Lookups and PMR can be served by any broker, so it makes …

[client] Consider a timed-out lookup equivalent to TooManyRequests

---

site2/docs/concepts-messaging.md

[docs] [ISSUE 11625] Update the intro of Messaging doc

---

site2/docs/administration-load-balance.md

[docs] [ISSUE 10627] Add description for two ways of splitting namespace bundles

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/NoopLoadManager.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/common/naming/ServiceConfigurationTest.java
pulsar-websocket/src/main/java/org/apache/pulsar/websocket/service/ProxyServer.java
site2/docs/security-tls-keystore.md

* cherry-pick / backport #11681 to branch-2.7
cherry-picked 50b6e79d7cc350efb2208b4aa89f684e133e31c0 and resolved merge conflicts.

[cherry-pick] [Broker] Support disabling non-TLS service ports (#11681)

---

docker-compose/standalone-dashboard/README.MD

Docker Compose `README.md` could be better.

Improve Docker Compose README.md

---

.github/ISSUE_TEMPLATE/doc_request.md
.github/PULL_REQUEST_TEMPLATE.md

https://docs.google.com/document/d/1Q-jkdE3OcMVKMwjnsm2ncONHqvjxGpDFR0z-nuhUOxQ/edit

[Doc Workflow] add doc issue template and optimize PR template

---

site2/docs/schema-understand.md

add documentation for https://github.com/apache/pulsar/pull/11238
@Anonymitaet maybe you know better which other files should contain the same content.

[docs] add documentation for Schema.NATIVE_AVRO

---

site2/website/pages/en/index.js

Align the Pulsar Website Main Page with Apache Software Foundation Policy.
Remove company logos and renamed the link to the powered by page.

[Website] Remove Company Logos From Main Page

---

conf/bookkeeper.conf
conf/broker.conf
conf/discovery.conf
conf/global_zookeeper.conf
conf/log4j2-scripts/filter.js
conf/presto/catalog/pulsar.properties
conf/standalone.conf
conf/websocket.conf

Removed unnecessary spaces from the conf files.

[config] Remove unnecessary spaces from conf files

---

site2/website/data/users.js

Some logos are not shown due to incorrect URLs.
Replace the wrong URLs with the correct ones.

[Website] fix incorrect logo URLs

---

site2/website/pages/en/index.js

Improve the powered by hyperlink language on the main page
Changed the hyperlink text.
No tests involved.

[website] Companies Powered by Pulsar

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroup.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceQuotaCalculatorImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/resourcegroup/ResourceQuotaCalculatorImplTest.java

- fix updateLocalQuota to not attempt Dispatch changes
- add checks for totalUsed of 0, and unconfigured RG in ResourceQuotaCalculatorImpl
- UT for above
Bug fixes in RG rate limiting
- don't clobber the publish rate limiter with (yet-unsupported) Dispatch side values
- add checks against unconfigured RG rate-limiter component(s) and total-usage of zero
- mvn test -Dtest=org.apache.pulsar.broker.resourcegroup.ResourceGroupRateLimiterTest -pl pulsar-broker
- mvn test …

[PIP-82] [pulsar-broker] Misc fixes:

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPackages.java

fix the parameter's description in packages client tool
*(or)*
*(or)*
*(example:)*
- The …

[pulsar-client-tools] fix packages tool parameter desc

---

site2/website-next/docs/schema-evolution-compatibility.md
site2/website-next/docs/schema-get-started.md
site2/website-next/docs/schema-manage.md
site2/website-next/docs/schema-understand.md
site2/website-next/scripts/migration.js
site2/website-next/sidebars.js
site2/website-next/sidebars.json
site2/website-next/versioned_docs/version-2.7.3/schema-evolution-compatibility.md
site2/website-next/versioned_docs/version-2.7.3/schema-get-started.md
site2/website-next/versioned_docs/version-2.7.3/schema-manage.md
site2/website-next/versioned_docs/version-2.7.3/schema-understand.md
site2/website-next/versioned_docs/version-2.8.0/schema-evolution-compatibility.md
site2/website-next/versioned_docs/version-2.8.0/schema-get-started.md
site2/website-next/versioned_docs/version-2.8.0/schema-manage.md
site2/website-next/versioned_docs/version-2.8.0/schema-understand.md
site2/website-next/versioned_sidebars/version-2.7.3-sidebars.json
site2/website-next/versioned_sidebars/version-2.8.0-sidebars.json

Master Issue: https://github.com/apache/pulsar/issues/11766
website upgrade
*(or)*
*(or)*
*(example:)* …

[website][upgrade]feat: docs migration about Pulsar Schema (versions: next/2.8.0/2.7.3)

---

site2/website-next/docs/schema-manage.md
site2/website-next/docusaurus.config.js
site2/website-next/package.json
site2/website-next/plugins/remark-linkify-regex.js
site2/website-next/scripts/migration.js
site2/website-next/versioned_docs/version-2.7.3/schema-manage.md
site2/website-next/versioned_docs/version-2.7.3/schema-understand.md
site2/website-next/versioned_docs/version-2.8.0/schema-manage.md
site2/website-next/versioned_docs/version-2.8.0/schema-understand.md

Master Issue: https://github.com/apache/pulsar/issues/11766
website upgrade
*(or)*
*(or)*
*(example:)* …

[website][upgrade] inject link plugin implement

---

pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/ZKMetadataStore.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataStoreTest.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/TestZKServer.java

When creating intermediate nodes in ZooKeeper we can mark them as "container" nodes. This is a new type introduced in ZK 3.5 that will ensure these nodes will get auto-deleted when the last child is deleted (the cleanup is done periodically).
This will allow to do proper cleanup of directory structures in ZK even in presence of failures.
We cannot immediately remove the existing logics that try to manually get rid of them, since for existing clusters these nodes would not get auto-deleted.

Use ZK "container" types for intermediate z-nodes

---

site2/website/data/team.js

Add new committers to the team page

Add new committers to the team page

---

.github/ISSUE_TEMPLATE/pip.md

See discussion in http://mail-archives.apache.org/mod_mbox/pulsar-dev/202109.mbox/%3C66DB34FA-AA47-455B-BEBD-C5A1864F94C2%40streamnative.io%3E. (I didn't find the original email)
Add an issue template for PIP.

Add issue template for PIP

---

site2/website/static/swagger/2.8.1/swagger.json
site2/website/static/swagger/2.8.1/swaggerfunctions.json
site2/website/static/swagger/2.8.1/swaggerpackages.json
site2/website/static/swagger/2.8.1/swaggersink.json
site2/website/static/swagger/2.8.1/swaggersource.json

After Pulsar 2.8.1 released, generate swagger files for 2.8.1
1. generate swagger files for 2.8.1

Generate swagger files for 2.8.1

---

site2/website/pages/en/contact.js

We are getting a lot of great questions to the slack channel, which will be lost in the future because of the 10k limit of slack.  This puts a link to our stack overflow URL in the hopes that more questions will go there.  a
Added a header and a sentence with the link. 
(If you need help on updating docs, …

[doc]Update contact.js with link to stack overflow

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarChannelInitializer.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonDurableSubscriptionTest.java

Fix the failed test https://github.com/apache/pulsar/runs/3554112034?check_suite_focus=true for branch-2.8 after cherry-picked PRs.

Fix cherry-pick issue on branch-2.8

---

site2/website/data/team.js

New members have joined, but the list was not updated.
New members have joined the PMC but the list was not been updated
added PMC to the roles for the three new people. 
- [x ] Make sure that the change passes the CI checks.
- The schema: (no / don't know)
<am I supposed to check box below or just someone with committer privileges?>
Need to …

[doc]Update PMC list

---

site2/website-next/docs/sql-deployment-configurations.md
site2/website-next/docs/sql-getting-started.md
site2/website-next/docs/sql-overview.md
site2/website-next/docs/sql-rest-api.md
site2/website-next/sidebars.json
site2/website-next/versioned_docs/version-2.7.3/sql-deployment-configurations.md
site2/website-next/versioned_docs/version-2.7.3/sql-getting-started.md
site2/website-next/versioned_docs/version-2.7.3/sql-overview.md
site2/website-next/versioned_docs/version-2.7.3/sql-rest-api.md
site2/website-next/versioned_docs/version-2.8.0/sql-deployment-configurations.md
site2/website-next/versioned_docs/version-2.8.0/sql-getting-started.md
site2/website-next/versioned_docs/version-2.8.0/sql-overview.md
site2/website-next/versioned_docs/version-2.8.0/sql-rest-api.md
site2/website-next/versioned_sidebars/version-2.7.3-sidebars.json
site2/website-next/versioned_sidebars/version-2.8.0-sidebars.json

Master Issue: https://github.com/apache/pulsar/issues/11766
website upgrade
*(or)*
*(or)*
*(example:)* …

[website][upgrade]feat: docs migration about Pulsar SQL

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SourceConfigUtils.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/ComponentImpl.java

These string format are malformed, doesn't print thing we want.
Make these string format  correct.
Internal bug fix, no need doc.

Fix malformed format string

---

site2/docs/reference-metrics.md

Fixes #11984
Fix the zookeeper prometheus metrics description

[Issue 11984] Fix zookeeper prometheus metrics doc

---

.github/ISSUE_TEMPLATE/pip.md

#11961 added the template for PIP but it missed the motivation section, which can be found in the original email.
Add motivation section to PIP template.

Add motivation section to PIP template

---

conf/bookkeeper.conf

Bookeeper released a feature that allows bk to bypass journal for writes in 4.14.0, you can refer the [Apache BookKeeper 4.14.0 Release Notes](https://github.com/apache/bookkeeper/blob/64102086e3bf25e52c1e019cc7f6aa13bdad2ec5/site/docs/4.14.0/overview/releaseNotes.md). The latest pulsar pkg(2.8.0) uses the bookkeeper 4.14.1 while the template bk conf misses this config, you can refer the bk config sample [bk_server.conf](https://github.com/apache/bookkeeper/blob/master/conf/bk_server.conf#L338).
Add the config `journalWriteData` to bookkeeper.conf.  …

feat(conf): add journalWriteData config to bk conf

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/cache/ConfigurationCacheService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/MessagingServiceShutdownHook.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorage.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorageFactory.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaStorageFactory.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicConcurrentTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ServerCnxTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentSubscriptionTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/BookkeeperSchemaStorageTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/schema/SchemaServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/web/WebServiceTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/SequenceIdWithErrorTest.java

Removed direct access to ZK client from the `PulsarService` instance.

PIP-45: Removed access to ZK client from PulsarService

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicMessageTTLTest.java

Support remove message-TTL api for v1 namespaces
https://github.com/apache/pulsar/pull/8178

[pulsar-broker] support remove-ttl api for V1 namespace

---

site2/website-next/docs/tiered-storage-aliyun.md
site2/website-next/docs/tiered-storage-aws.md
site2/website-next/docs/tiered-storage-azure.md
site2/website-next/docs/tiered-storage-filesystem.md
site2/website-next/docs/tiered-storage-gcs.md
site2/website-next/docs/tiered-storage-overview.md
site2/website-next/docs/txn-how.md
site2/website-next/docs/txn-monitor.md
site2/website-next/docs/txn-use.md
site2/website-next/docs/txn-what.md
site2/website-next/docs/txn-why.md
site2/website-next/sidebars.json
site2/website-next/versioned_docs/version-2.7.3/transactions-api.md
site2/website-next/versioned_docs/version-2.7.3/transactions-guarantee.md
site2/website-next/versioned_docs/version-2.7.3/transactions.md
site2/website-next/versioned_docs/version-2.8.0/txn-how.md
site2/website-next/versioned_docs/version-2.8.0/txn-monitor.md
site2/website-next/versioned_docs/version-2.8.0/txn-use.md
site2/website-next/versioned_docs/version-2.8.0/txn-what.md
site2/website-next/versioned_docs/version-2.8.0/txn-why.md
site2/website-next/versioned_sidebars/version-2.7.3-sidebars.json
site2/website-next/versioned_sidebars/version-2.8.0-sidebars.json

Master Issue: https://github.com/apache/pulsar/issues/11766
website upgrade
*(or)*
*(or)*
*(example:)* …

[website][upgrade] feat: docs migration - transactions

---

pulsar-broker/src/main/java/org/apache/pulsar/PulsarStandalone.java

Fixes #12046 
No need to update the doc.

Add checkArgument for webServicePortTls and brokerServicePortTls if tls enabled

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java

Fix typo for BrokerService

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest2.java

Support non-partition topic creation using v1 admin api.

[pulsar-server] support v1 api to create non-partition topic

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LoadManager.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java
pulsar-common/src/main/java/org/apache/pulsar/policies/data/loadbalancer/LocalBrokerData.java

Fix typos in load balancing code.
* Fix several typos.
This PR has no breaking changes.
No need to update docs.

Fix several typos in load balancing code

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java

Fixes #11652 .
This is a bug fix, no need to update doc.

Fix deadLetterPolicy is not working with key shared subscription under partitioned topic

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java

If the local and configurationStore are pointing to the same metadata store service, we can use a single instance.

PIP-45: If they're connecting to same service, share local & config MetadataStores

---

site2/docs/reference-configuration.md

* Add doc for #12132 
* Add doc for `tokenSettingPrefix`

[Doc] Add doc for tokenSettingPrefix

---

site2/docs/admin-api-topics.md

[docs]Fix pr-10853 wrong doc

---

site2/docs/client-libraries-cpp.md
site2/website/versioned_docs/version-2.8.1/client-libraries-cpp.md

- Update client-libraries-c++
- Make the document easy to read
- Correct inappropriate punctuation
- Correction of incorrect document

[Docs]Update docs for Client libraries C++

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java

In https://github.com/apache/pulsar/pull/8051, the `producers` and `consumers` sets in the `PulsarClientImpl` were updated to be backed by a concurrent hash map. Therefore, there is no need to synchronize updates to the map or the counting of the size of the map.
This update will help improve shutdown times when there are many producers/consumers.
* Update `cleanupProducer` and `cleanupConsumer` to remove the unnecessary `synchronize` on each set update
* Update `producersCount` and `consumersCount` to remove the unnecessary `synchronize` on each set count
* Update the initialization of each set to make it clear that these sets are intentionally thread safe data structures
This is a trivial change. Since we switched to a concurrent data structure in this PR, …

[Java Client] Remove unnecessary synchronization; Simplify initialization

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/NonPersistentTopics.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/PersistentTopics.java
pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdPersistentTopics.java

Add option to get precise backlog for v1 topic as well.

[pulsar-admin] add option to get precise backlog on v1 topic

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java

Fixes #12272 
Address a breaking change related to existing authorization providers.
Update the `PulsarAuthorizationProvider` base class to to support old-style initialization.

[issue-12272] PulsarAuthorizationProvider initialization

---

pom.xml

Each time the the website build runs, we're generating a big commit in the `asf-site` branch in this repo where each HTML file for Javadoc has 2 lines changed where the timestamp is updated.
eg: 
```
content/api/admin/2.10.0-SNAPSHOT/allclasses-frame.html                                                                                                             |   2 +-
content/api/admin/2.10.0-SNAPSHOT/allclasses-noframe.html                                                                                                           |   2 +-
content/api/admin/2.10.0-SNAPSHOT/constant-values.html                                                                                                              |   2 +-
content/api/admin/2.10.0-SNAPSHOT/deprecated-list.html …
```

[Website] Remove timestamp from generated Javadoc HTML files

---

docker/publish.sh

Remove pulsar-dashboard from the publish process of images, since its image have been removed from branch-2.7

[Branch-2.7]Remove pulsar-dashboard from the publish process of images

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
site2/docs/reference-pulsar-admin.md

fixed #12261 
I will update docs in another pr

reset-cursor support earliest or latest

---

site2/website-next/data/connectors.js
site2/website/data/connectors.js

The [Pulsar Download](https://pulsar.apache.org/en/download/) page missed the source connector of [Debezium MongoDB CDC source](https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=pulsar/pulsar-2.8.1/connectors/pulsar-io-debezium-mongodb-2.8.1.nar) which is included in release since v2.5.0. 
Added the Debezium MongoDB CDC source info in the `connectors.js`.
*(or)*
*(or)*
*(example:)* …

feat(website): add debezium-mongodb source

---

site2/docs/transaction-api.md
site2/website/versioned_docs/version-2.8.0/transaction-api.md
site2/website/versioned_docs/version-2.8.1/transaction-api.md
site2/website/versioned_docs/version-2.8.2/transaction-api.md

This pr aims at fixing #https://github.com/apache/pulsar/pull/10475.

[DOCS] Update the description

---

site2/website-next/versioned_docs/version-2.7.1/io-cdc.md
site2/website-next/versioned_docs/version-2.7.1/io-cli.md
site2/website-next/versioned_docs/version-2.7.1/io-connectors.md
site2/website-next/versioned_docs/version-2.7.1/io-debug.md
site2/website-next/versioned_docs/version-2.7.1/io-develop.md
site2/website-next/versioned_docs/version-2.7.1/io-overview.md
site2/website-next/versioned_docs/version-2.7.1/io-quickstart.md
site2/website-next/versioned_docs/version-2.7.1/io-use.md
site2/website-next/versioned_sidebars/version-2.7.1-sidebars.json

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

[website][upgrade]feat: docs migration - 2.7.1 / io

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java

*Fix typo for LoadManagerShared#filterAntiAffinityGroupOwnedBrokers.*
*Fix typo for LoadManagerShared#filterAntiAffinityGroupOwnedBrokers.*

Fix typo for LoadManagerShared#filterAntiAffinityGroupOwnedBrokers

---

pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/PulsarWorkerService.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/Worker.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/WorkerService.java

- Remove unused zookeeper factory in function worker
- fix some typo

Remove unused zookeeper factory in function worker

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdBookies.java

*Fix doc for pulsar-admin bookies command.*
*Fix doc for pulsar-admin bookies command.*

[docs] Fix doc for pulsar-admin bookies cmd

---

site2/docs/deploy-monitoring.md
site2/website-next/docs/deploy-monitoring.md
site2/website-next/versioned_docs/version-2.7.1/deploy-aws.md
site2/website-next/versioned_docs/version-2.7.1/deploy-bare-metal-multi-cluster.md
site2/website-next/versioned_docs/version-2.7.1/deploy-bare-metal.md
site2/website-next/versioned_docs/version-2.7.1/deploy-dcos.md
site2/website-next/versioned_docs/version-2.7.1/deploy-docker.md
site2/website-next/versioned_docs/version-2.7.1/deploy-kubernetes.md
site2/website-next/versioned_docs/version-2.7.1/deploy-monitoring.md
site2/website-next/versioned_docs/version-2.7.3/deploy-monitoring.md
site2/website-next/versioned_docs/version-2.8.0/deploy-monitoring.md
site2/website-next/versioned_sidebars/version-2.7.1-sidebars.json
site2/website/versioned_docs/version-2.7.0/deploy-monitoring.md
site2/website/versioned_docs/version-2.7.1/deploy-monitoring.md
site2/website/versioned_docs/version-2.7.2/deploy-monitoring.md
site2/website/versioned_docs/version-2.7.3/deploy-monitoring.md
site2/website/versioned_docs/version-2.8.0/deploy-monitoring.md
site2/website/versioned_docs/version-2.8.1/deploy-monitoring.md
site2/website/versioned_docs/version-2.8.2/deploy-monitoring.md

Fixes #11766
*(or)*
*(or)*
*(example:)*
*If …

[website][upgrade]feat: docs migration - 2.7.1 / deploy

---

site2/docs/sql-deployment-configurations.md
site2/website-next/docs/sql-deployment-configurations.md

Seeing couple users asking about why Pulsar SQL can't query the latest message from topic, feel we should update the doc.
Also seems the config part is out of date, so also updated the config section.

[Doc] Update Pulsar SQL document.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthenticatedProducerConsumerTest.java
pulsar-client-cpp/include/pulsar/c/consumer_configuration.h
pulsar-client-cpp/lib/c/c_ConsumerConfiguration.cc

[Branch-2.8]Fix cherry-pick code style

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java

Topic Policies will be initialized when the bundle is bound to Broker. Reader creation may fail, causing Topic Policies to be unrecoverable.
Support retry when creating reader of Topic Policies
This is a internal API

Support retry when creating reader of Topic Policies

---

build/run_unit_group.sh
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorGlobalNSTest.java

Remove replicator global test from the quarantine group

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

Method `PersistentTopic#getPersistentTopic` is totally useless and is not called anywhere.
I don't see any chance it could be used.
Just remove this method.
This method is not called.

[broker] remove useless method "PersistentTopic#getPersistentTopic"

---

pom.xml
pulsar-broker-common/pom.xml
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authentication/AuthenticationService.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TenantResources.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/validator/MultipleListenerValidator.java
pulsar-broker-common/src/main/java/org/apache/pulsar/common/configuration/PulsarConfigurationLoader.java
pulsar-broker-common/src/test/java/org/apache/pulsar/common/configuration/PulsarConfigurationLoaderTest.java
pulsar-proxy/pom.xml

Master Issue: #12271
Apply Maven Modernizer plugin to enforce we move away from legacy APIs.
Add Maven Modernizer plugin in pulsar-broker-common module and fix violation.
This change is already covered by existing tests, such as.
Not changing implementation or public API.

[Modernizer] Apply Modernizer plugin for pulsar broker common module and fix violation.

---

site2/docs/administration-geo.md
site2/website/versioned_docs/version-2.7.2/tiered-storage-aws.md
site2/website/versioned_docs/version-2.7.2/tiered-storage-gcs.md
site2/website/versioned_docs/version-2.8.2/administration-geo.md

Add docs for https://github.com/apache/pulsar/pull/12136
This PR adds doc for 2.8.2 and master. Will add docs for 2.9.1 once the doc set is generated.

[Doc] Add explanations for setting geo-replication at topic level

---

site2/website-next/versioned_docs/version-2.7.1/admin-api-brokers.md
site2/website-next/versioned_docs/version-2.7.1/admin-api-clusters.md
site2/website-next/versioned_docs/version-2.7.1/admin-api-functions.md
site2/website-next/versioned_docs/version-2.7.1/admin-api-namespaces.md
site2/website-next/versioned_docs/version-2.7.1/admin-api-overview.md
site2/website-next/versioned_docs/version-2.7.1/admin-api-permissions.md
site2/website-next/versioned_docs/version-2.7.1/admin-api-tenants.md
site2/website-next/versioned_docs/version-2.7.1/admin-api-topics.md
site2/website-next/versioned_sidebars/version-2.7.1-sidebars.json

Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …

[website][upgrade]feat: docs migration - 2.7.1 / Admin API

---

site2/website/data/team.js

Add one new committers to the team page
There are 47  pulsar committers util November 9, 2021
see [ASF Committers by ID](http://people.apache.org/committer-index.html)

[website] Update team page to add new committer

---

site2/website-next/versioned_docs/version-2.7.2/transaction-api.md
site2/website-next/versioned_docs/version-2.7.2/transaction-guarantee.md
site2/website-next/versioned_sidebars/version-2.7.2-sidebars.json

Fixes #<xyz>
Master Issue:  #11766 
*(or)*
*(or)*
*(example:)* …

[website][upgrade]feat: docs migration - version-2.7.2 Transactions

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java

Fixes #12672 
See  #12672 
Reduced the message send in this test.
This change is already covered by existing tests, such as testPeekWithSubscriptionNameNotExist itself.
Fix flaky test case.

[Issue 12672][test] Reduce unnecessary message send in testPeekWithSubscriptionNameNotExist

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java

Remove unused code in PersistentTopic.java
- [ x ] `no-need-doc`

Remove unused code in PersistentTopic.java

---

pulsar-client-cpp/python/pulsar/schema/definition.py

Fixes #12485
There were some None checks which were too inclusive and didn't allow the use of 0 values for numeric types as well as some other odd behaviors.
Changed checks to explicitly check for None values.
*(or)*
*(or)*
*(example:)*
- Dependencies (does it add or upgrade …

[Issue #12485][Python Client] cannot use any values that evaluates to False

---

site2/docs/admin-api-topics.md
site2/docs/concepts-messaging.md

- This PR add docs for https://github.com/apache/pulsar/pull/10817
- This PR updates `master` firstly. Will update other doc versions once the changes get approved.

[Doc] add explanations for subscription mode

---

site2/docs/schema-evolution-compatibility.md
site2/docs/schema-manage.md

- This PR adds docs for https://github.com/apache/pulsar/pull/11856
- This PR updates `master` firstly. Will update other doc versions once the changes get approved.

[Doc] add explanations for schema compatibility strategy

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java

Fixes #12774
See #12774
Add wait procedures for new created topic syncs to the other clusters.
Fix flaky test.
Fix flaky test.

[Issue 12774] Fix flaky test in ReplicatorTest#testtDoNotReplicateSystemTopic

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java

Num of placeholders does not match number of arguments in logging
remove unnecessary placeholders
- The public API: (yes / no) no
- The schema: (yes / no / don't know) no
- The default values of configurations: (yes / no) no
- The wire protocol: (yes / no) no
- The rest endpoints: (yes / no) no
- The admin cli options: (yes / no) no 
- Anything that affects deployment: (yes / no / don't know) no

remove redundant placeholders

---

site2/website-next/versioned_docs/version-2.7.2/security-athenz.md
site2/website-next/versioned_docs/version-2.7.2/security-authorization.md
site2/website-next/versioned_docs/version-2.7.2/security-bouncy-castle.md
site2/website-next/versioned_docs/version-2.7.2/security-encryption.md
site2/website-next/versioned_docs/version-2.7.2/security-extending.md
site2/website-next/versioned_docs/version-2.7.2/security-jwt.md
site2/website-next/versioned_docs/version-2.7.2/security-kerberos.md
site2/website-next/versioned_docs/version-2.7.2/security-oauth2.md
site2/website-next/versioned_docs/version-2.7.2/security-overview.md
site2/website-next/versioned_docs/version-2.7.2/security-tls-authentication.md
site2/website-next/versioned_docs/version-2.7.2/security-tls-keystore.md
site2/website-next/versioned_docs/version-2.7.2/security-tls-transport.md
site2/website-next/versioned_docs/version-2.7.2/security-token-admin.md
site2/website-next/versioned_sidebars/version-2.7.2-sidebars.json

Fixes #<xyz>
Master Issue:  #11766 
*(or)*
*(or)*
*(example:)* …

[website][upgrade]feat: docs migration - version-2.7.2 Security

---

site2/website/versioned_docs/version-2.8.2/schema-evolution-compatibility.md
site2/website/versioned_docs/version-2.8.2/schema-manage.md

This PR updates the changes in #12746 to version 2.8.2.

[DOCS] Update relevant changes in pr 12746 to docs 2.8.2

---

site2/website-next/versioned_docs/version-2.7.2/admin-api-brokers.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-clusters.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-functions.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-namespaces.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-non-partitioned-topics.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-non-persistent-topics.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-overview.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-partitioned-topics.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-permissions.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-persistent-topics.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-schemas.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-tenants.md
site2/website-next/versioned_docs/version-2.7.2/admin-api-topics.md
site2/website-next/versioned_sidebars/version-2.7.2-sidebars.json

Fixes #<xyz>
*(or)*
*(or)*
*(example:)* …

[website][upgrade]feat: docs migration - version-2.7.2 Admin API

---

site2/website/brodocs/pulsar-admin-manifest.json

Fixes #<xyz>
Add missing docs for `pulsar-admin`
* proxy-stats
* resourcegroups
* transactions
* tenants
* resource-quotas
* schemas
* packages
*(or)*
*(or)*
*(example:)*
- *Added …

feat: add missing docs for `pulsar-admin`

---

pulsar-package-management/filesystem-storage/pom.xml
pulsar-package-management/filesystem-storage/src/main/java/org/apache/pulsar/packages/management/storage/filesystem/FileSystemPackagesStorage.java
pulsar-package-management/filesystem-storage/src/main/java/org/apache/pulsar/packages/management/storage/filesystem/FileSystemPackagesStorageProvider.java
pulsar-package-management/filesystem-storage/src/main/java/org/apache/pulsar/packages/management/storage/filesystem/package-info.java
pulsar-package-management/filesystem-storage/src/test/java/org/apache/pulsar/packages/management/storage/filesystem/FileSystemPackagesStorageTest.java

Added new implementation for package manager that writes files into local filesystem.

Added local filesystem backend for package manager

---

site2/website-next/versioned_docs/version-2.6.3/functions-cli.md
site2/website-next/versioned_docs/version-2.6.3/functions-debug.md
site2/website-next/versioned_docs/version-2.6.3/functions-deploy.md
site2/website-next/versioned_docs/version-2.6.3/functions-develop.md
site2/website-next/versioned_docs/version-2.6.3/functions-overview.md
site2/website-next/versioned_docs/version-2.6.3/functions-runtime.md
site2/website-next/versioned_docs/version-2.6.3/functions-worker.md
site2/website-next/versioned_docs/version-2.6.3/io-cdc.md
site2/website-next/versioned_docs/version-2.6.3/io-cli.md
site2/website-next/versioned_docs/version-2.6.3/io-connectors.md
site2/website-next/versioned_docs/version-2.6.3/io-debug.md
site2/website-next/versioned_docs/version-2.6.3/io-develop.md
site2/website-next/versioned_docs/version-2.6.3/io-overview.md
site2/website-next/versioned_docs/version-2.6.3/io-quickstart.md
site2/website-next/versioned_docs/version-2.6.3/io-use.md
site2/website-next/versioned_docs/version-2.6.3/sql-deployment-configurations.md
site2/website-next/versioned_docs/version-2.6.3/sql-getting-started.md
site2/website-next/versioned_docs/version-2.6.3/sql-overview.md
site2/website-next/versioned_docs/version-2.6.3/sql-rest-api.md
site2/website-next/versioned_docs/version-2.6.3/window-functions-context.md
site2/website-next/versioned_sidebars/version-2.6.3-sidebars.json

Fixes #<xyz>
*(or)*
*(or)*
*(example:)* …

[website][upgrade]feat: website upgrade / docs migration - 2.6.3 / functions/io/sql

---

site2/website-next/versioned_docs/version-2.7.2/developing-binary-protocol.md
site2/website-next/versioned_docs/version-2.7.2/developing-cpp.md
site2/website-next/versioned_docs/version-2.7.2/developing-load-manager.md
site2/website-next/versioned_docs/version-2.7.2/developing-tools.md
site2/website-next/versioned_sidebars/version-2.7.2-sidebars.json

Fixes #11766 
*(or)*
*(or)*
*(example:)* …

[website][upgrade]Fix: docs about 2.7.2

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java

Remove unused listeners if it have no listeners, avoid  the map (`SystemTopicBasedTopicPoliciesService#listeners`) from keep growing.
Remove the key from `listeners` if the value list is empty.
Simple optimization, no user doc needed.

Remove unused listeners if it have no listeners.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java

Fix spelling error and useless code.

Fix spelling error and useless code.

---

pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TenantResources.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java

Fixes #11779.
- [ x ] `no-need-doc`

Fix deleting tenants with active namespaces with 500.

---

managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java
managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/PositionAckSetUtil.java
pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/TopicResources.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest2.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicE2ETest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentStickyKeyDispatcherMultipleConsumersTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/api/InterceptorsTest.java
pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TransactionEndToEndTest.java
pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/impl/AutoTopicCreationOverrideImpl.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSchemas.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/PulsarAdminTool.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/TypedMessageBuilderImpl.java
pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/PrimitiveSchemaTest.java
pulsar-common/src/main/java/org/apache/pulsar/common/net/ServiceURI.java
pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/stats/PublisherStatsImpl.java
pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/functioncache/FunctionCacheManagerImpl.java
pulsar-metadata/src/test/java/org/apache/pulsar/metadata/CounterTest.java
pulsar-sql/presto-pulsar/src/test/java/org/apache/pulsar/sql/presto/decoder/protobufnative/TestMsg.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/DefaultMessageFormatter.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/presto/StockProtoMessage.java

There're many code style issues as indicated by codacy.
1. throw NPE
2. logic inversion
3. unnecessary case change
4. tailing semicolon

clean code style issues

---

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java
site2/docs/reference-cli-tools.md
site2/website-next/docs/reference-cli-tools.md

Modifications
Support listenerThreads configuration.The document update is complete.

[pulsar-perf]Support listenerThreads configuration.

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java

Fixes #12897
See #12897
Use  `Awaitility.await().untilAsserted` to wait until pulsar2 got the replicator producer.
This change is already covered by existing tests, such as testReplicatorProducerName
fix flaky test

[Issue 12897] Fix flaky test in testReplicatorProducerName

---

site2/docs/reference-metrics.md

Add bundles metrics doc
Add bundles metrics doc
*(or)*
*(or)*
*(example:)*
- The public API: (yes / no)  no
- The schema: (yes / no / don't know)  no
- The default values of configurations: (yes / no)  no
- The wire protocol: (yes / no)  no
- The rest endpoints: (yes / …

[docs] [ISSUE 12366] Add doc of bundles metrics

---

site2/docs/client-libraries-python.md

- This PR adds doc for https://github.com/apache/pulsar/pull/12516 

[Doc] add explanations for Avro schema in Python client

---

site2/docs/admin-api-permissions.md
site2/website/versioned_docs/version-2.8.2/admin-api-brokers.md
site2/website/versioned_docs/version-2.8.2/admin-api-clusters.md
site2/website/versioned_docs/version-2.8.2/admin-api-functions.md
site2/website/versioned_docs/version-2.8.2/admin-api-namespaces.md
site2/website/versioned_docs/version-2.8.2/admin-api-overview.md
site2/website/versioned_docs/version-2.8.2/admin-api-packages.md
site2/website/versioned_docs/version-2.8.2/admin-api-permissions.md
site2/website/versioned_docs/version-2.8.2/admin-api-tenants.md
site2/website/versioned_docs/version-2.8.2/admin-api-topics.md

- Add details for permissions
- Add important notice for admin API docs (2.8.2 version)

[Doc] add explanations for permissions

---

site2/docs/client-libraries-rest.md
site2/website/sidebars.json

- This PR adds docs for https://github.com/apache/pulsar/pull/8125 

[Doc] add explanations for REST

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/SchemasResource.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/SchemasResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminTest.java

Remove unused clock field in SchemasResources
little optimize

Remove unused clock field in SchemasResources

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/service/NonPersistentTopicE2ETest.java

Cherry-pick from #12550 .
This is a fix about non-persistent partitioned topics related to #8442.
- [ x ] `no-need-doc` 
This is a fix, doc is updated in #8442. so no need doc.

[Branch-2.8] Clean up the metadata of the non-persistent partitioned topics.

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java

Fixes #12834 
add the `--secrets` argument into `pulsar-admin functions create/update/localrun` command
- The public API: yes  *new `--secrets` argument for submitting/updating* functions

[function] pulsar admin exposes secrets for function

---

pulsar-broker/src/test/java/org/apache/pulsar/client/api/ConsumerBatchReceiveTest.java

Move ConsumerBatchReceiveTest out of the quarantine test group

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java

Code cleanup, these two private fields in DispatchRateLimiter is not used.
- subscriptionRelativeRatelimiterOnMessage
- subscriptionRelativeRatelimiterOnByte
Delete two fields.
Code cleanup.

[broker] [code cleanup] unused field in DispatchRateLimiter

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java
pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java

Cherry pick #12848.  Fixes #11779.
- [ x ] `no-need-doc`

[Branch-2.8] Fix deleting tenants with active namespaces with 500.

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/ByteBufSchema.java
pulsar-common/src/main/java/org/apache/pulsar/common/tls/TlsHostnameVerifier.java
pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java
pulsar-io/flume/src/main/java/org/apache/pulsar/io/flume/FlumeConnector.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java

Some  `if` statement need optimize, reduce code.
- The public API: (yes / no) no
- The schema: (yes / no / don't know) no
- The default values of configurations: (yes / no) no
- The wire protocol: (yes / no) no
- The rest endpoints: (yes / no) no
- The admin cli options: (yes / no) no 
- Anything that affects deployment: (yes / no / don't know) no
no new features.

Optimize if statement

---

tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarWorkerRebalanceDrainProcessTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarWorkerRebalanceDrainTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/java/PulsarWorkerRebalanceDrainThreadTest.java
tests/integration/src/test/java/org/apache/pulsar/tests/integration/topologies/PulsarCluster.java
tests/integration/src/test/resources/pulsar-process.xml
tests/integration/src/test/resources/pulsar-thread.xml

Integration tests for function-worker rebalance and drain operations.
Added integration tests for function-worker rebalance and drain.
- [ X] Make sure that the change passes the CI checks.
mvn -B -ntp test -f tests/pom.xml -DintegrationTestSuiteFile=pulsar-process.xml -DintegrationTests -Dgroups=rebalance_drain
No

Integration tests for function-worker rebalance and drain operations.

---

site2/website/versioned_docs/version-2.8.0/reference-metrics.md
site2/website/versioned_docs/version-2.8.1/reference-metrics.md
site2/website/versioned_docs/version-2.8.2/reference-metrics.md

Fixes #12073 
Update ZK prometheus metrics in 2.8.x versions.

[DOCS] Update ZK prometheus metrics in 2.8.x

---

site2/website/data/resources.js

Added in new blogs and presentations.  For the presentations, added in links to the Pulsar Summit and to a playlist for presentations at ApacheCon 2021.
For the new website, we will want to reorg this so that there is a carousal or something similar that can scroll through some of the blog posts.    
keeping this updated with the latest blog posts and presentations.
Added in a new blog post on streaming and presentations from pulsar summit, apache con …

[docs][Website]Update resources.js to add in new items

---

pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java
pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java
site2/docs/cookbooks-retention-expiry.md

Add docs for https://github.com/apache/pulsar/pull/10093

[Doc] add explanations for time-based backlog quota

---

site2/docs/io-debug.md

Fixes #12691 
Add tab to config content and modify path format.
*(or)*
*(or)*
*(example:)*

[DOCS] Update io-debug.md

---

site2/website/data/resources.js

Adding in 9 new blogs for October and November.
<!--
Keeping the resources page up to date is very important to the community.  These additions were added to the #blog/articles channel of the slack workspace
Added 9 new links to different blogs that have been published in the last month.
Check the box below and label this PR (if you have committer …

[docs][website] Update resources.js

---

pulsar-broker/pom.xml
pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java
pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleFactory.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/MultiBrokerBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/MultiBrokerLeaderElectionTest.java
pulsar-metadata/pom.xml

Backports #13069 to `branch-2.8`

[branch-2.8] [Broker] Fix and improve topic ownership assignment (#13069)

---

site2/website/data/team.js

Fixes #<xyz>
*Add a new committer to the team page*
*Add a new committer to the team page*
Check the …

[website] Add a new committer to the team page.

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

Fix log information in `PersistentTopicsBase#getPartitionedTopicMetadata` method and change`cluster` to `topic`.

Fix log in PersistentTopicsBase#getPartitionedTopicMetadata

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java

change log level in ThresholdShedder

change log level for ThresholdShredder debug message

---

site2/website/pages/en/download.js
site2/website/release-notes.md

Fixes #<xyz>
fix: release note anchor jumper not incorrectly
*(or)*
*(or)*
*(example:)*
*If `yes` was chosen, …

[website]fix: release note anchor jumper

---

site2/docs/deploy-bare-metal.md

Fix https://github.com/apache/pulsar/issues/13078

[Doc] add hardware recommendations

---

site2/docs/reference-metrics.md
site2/website/versioned_docs/version-2.8.0/reference-metrics.md
site2/website/versioned_docs/version-2.8.1/reference-metrics.md
site2/website/versioned_docs/version-2.8.2/reference-metrics.md

The zk metrics list on [https://pulsar.apache.org/docs/en/reference-metrics/#zookeeper](https://pulsar.apache.org/docs/en/reference-metrics/#zookeeper) are generated by AspectJ which was removed by https://github.com/apache/pulsar/pull/10533. So they are not valid from Pulsar 2.8.0, and `/metrics` will return zk metrics generated by itself.
Removed the deprecated zk metrics info and attached zk offical metrics docs link.
*(or)*
*(or)*
*(example:)* …

fix(docs): update zk metrics info in docs

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java

clean unused method isTopicOwned,we can use isTopicOwnedAsync

clean unused method isTopicOwned,we can use isTopicOwnedAsync

---

site2/docs/client-libraries-python.md

Update the pip install commands.

[DOCS] Update pip install command

---

pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/thread/ThreadRuntime.java

- Fix a log not correct in ThreadRuntime
- Make some their fields final
simple optmize

Fix log problem in ThreadRuntime, make it's member final

---

site2/website/static/doap.rdf

This patch adds a default DOAP file for Pulsar
See here for reference
https://projects.apache.org/create.html

Add basic DOAP file for Pulsar

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java
pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStore.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStoreProvider.java
pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionSequenceIdGenerator.java
pulsar-transaction/coordinator/src/test/java/org/apache/pulsar/transaction/coordinator/MLTransactionMetadataStoreTest.java

[Transaction] Fix generate transactionId some comments

---

site2/website/blog/2021-12-11-Log4j-CVE.md

Added blog post to explain workaround for Logj4 security issue.

[Blog] Added Log4j CVE blog post

---

pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java
pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceTransaction.java
pulsar-testclient/src/test/java/org/apache/pulsar/testclient/PerformanceTransactionTest.java

There is one omission and several irregular log formats.
1. messagesSent.increment()
2. log format
*(or)*
*(or)*
*(example:)*
- The wire protocol: (yes / …

[Transaction] Fix performance

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

#7725 change some WebApplicationException log level to debug,
This PR add some parts of WebApplicationException miss to handle.
Change some WebApplicationException log level from errorto debug in PersistentTopicsBase.
This change is a code cleanup without any test coverage.
only change log level

Change some WebApplicationException log level to debug

---

pulsar-client-cpp/wireshark/pulsarDissector.cc

Wireshark Pulsar dissector naming replace yahoo with apache

[C++] Wireshark Pulsar dissector naming replace yahoo with apache

---

site2/website-next/versioned_docs/version-2.8.0/client-libraries-python.md
site2/website/versioned_docs/version-2.8.0/client-libraries-python.md
site2/website/versioned_docs/version-2.8.1/client-libraries-python.md
site2/website/versioned_docs/version-2.8.2/client-libraries-python.md

A follow-up of #13221 
Update 2.8.x and 2.8.0 in website next.

[DOCS] Update shell commands in versioned docs

---

site2/website/blog/2021-12-11-Log4j-CVE.md

* fix typo: `PUSLAR_EXTRA_OPTS` -> `PULSAR_EXTRA_OPTS`

Fix typo in blog post

---

site2/docs/admin-api-topics.md

add description for the `earliestMsgPublishTimeInBacklog ` in pulsar-admin.
Original PR: [12523](https://github.com/apache/pulsar/pull/12523)

add description for the `earliestMsgPublishTimeInBacklog `

---

pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java

Optimize update partition logic

Optimize update partition logic

---

.github/workflows/ci-pulsar-website-build.yaml

Fixes #<xyz>
Before this, some things happened for website every build
(1) It runs for nearly 2 hours.
(2) If it exceeds 2 hours then it is canceled.
Noticed that, it will build full pulsar, But in fact, it's not necessary, It saves a lot of time just build the core modules.
Modified to just build the core modules for website building, it will saves a lot of time.
*(or)*
This change is already covered by existing tests, such as …

feat: optimize website build

---

pulsar-client/src/main/java/org/apache/pulsar/client/impl/TransactionMetaStoreHandler.java

when we send a request (firstly or retry), we put it in `pendingRequests` firstly.
If the state of TCHandler can not send the request, we should remove it from `pendingRequests`.
If the state of TCHandler can not send the request, remove it from `pendingRequests`.
*(or)*
*(or)*
*(example:)*
- Dependencies (does it add or upgrade a …

[Transaction]remove request if can not send

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java
pulsar-client/src/main/java/org/apache/pulsar/client/impl/transaction/TransactionImpl.java

Due to operations such as concurrency, retry, and timeout abort. We should allow  `abort` or `commit` in the state of aborting or committing
Allow `abort` or `commit` in the state of aborting or committing
*(or)*
*(or)*
*(example:)*
- The …

[Transaction] Allow transaction to be committed or aborted in the state of aborting or committing.

---

pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java

Fix broken master checkstyle
simple checkstyle changes, no need doc

Fix broken master checkstyle

---

site2/website/data/users.js

Add the new Apache Pulsar adopted users to the Pulsar website.
Update the website.

[website] Add new Pulsar adopted users to the "Powered by" Page
